### ISSUE TITLE
the sbt do not execute as the "subconfig.txt", if I run other application like activator on top of sbt.

### ISSUE THREAD

**Issue by thinksource** [sbt/sbt#1014]
My system is windows 8, sbt version is 0.13.0, but I guess all window versions have similar problem.

I migrate my user profile form "something Dev" fold to "something" fold.
Then I find the error of sbt

C:\activator>sbt
java.io.FileNotFoundException: C:\Users\propertymode Dev.sbt\boot\update.log (T
he system cannot find the path specified)
    at java.io.FileOutputStream.open(Native Method)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
    at java.io.FileWriter.<init>(FileWriter.java:90)
    at xsbt.boot.Update.<init>(Update.scala:51)
    at xsbt.boot.Launch.update(Launch.scala:279)
    at xsbt.boot.Launch$$anonfun$jansiLoader$1.apply(Launch.scala:124)
    at scala.Option.getOrElse(Option.scala:120)
    at xsbt.boot.Launch.jansiLoader$2f324eef(Launch.scala:119)
    at xsbt.boot.Launch.<init>(Launch.scala:96)
    at xsbt.boot.Launcher$.apply(Launch.scala:294)
    at xsbt.boot.Launch$.apply(Launch.scala:16)
    at xsbt.boot.Boot$.runImpl(Boot.scala:32)
    at xsbt.boot.Boot$.main(Boot.scala:21)
    at xsbt.boot.Boot.main(Boot.scala)
Error during sbt execution: java.io.FileNotFoundException: C:\Users\propertymode
Dev.sbt\boot\update.log (The system cannot find the path specified) 

Then I change the sbtconfig.txt file, add a new line:

-Dsbt.boot.directory=C:\Users\property.sbt\boot\

then the sbt can run normally, as I put the correct sbt boot directory path.

But the problem happens again when I run activator, I think activator depends on sbt. 
the problem again:

C:\Users\property>activator
java.io.FileNotFoundException: C:\Users\propertymode Dev.sbt\boot\update.log (T
he system cannot find the path specified)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
        at java.io.FileWriter.<init>(FileWriter.java:90)
        at xsbt.boot.Update.<init>(Update.scala:51)
        at xsbt.boot.Launch.update(Launch.scala:279)
        at xsbt.boot.Launch$$anonfun$jansiLoader$1.apply(Launch.scala:124)
        at scala.Option.getOrElse(Option.scala:120)
        at xsbt.boot.Launch.jansiLoader$2f324eef(Launch.scala:119)
        at xsbt.boot.Launch.<init>(Launch.scala:96)
        at xsbt.boot.Launcher$.apply(Launch.scala:294)
        at xsbt.boot.Launch$.apply(Launch.scala:16)
        at xsbt.boot.Boot$.runImpl(Boot.scala:32)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)
Error during sbt execution: java.io.FileNotFoundException: C:\Users\propertymode
 Dev.sbt\boot\update.log (The system cannot find the path specified)

I want to run activator with sbt running as my specificated in "sbtconfig.txt", how to do it?

**Comment by harrah** [comment]
Please do not open the same issue on multiple projects.  (Covered by typesafehub/activator#175.)

**Comment by thinksource** [comment]
@harrah I just can not configure that problem is the activator problem or sbt problem

**Comment by harrah** [comment]
That's fine, just work with one project at a time to avoid duplicated effort.  Also, StackOverflow is a good support channel because you can use multiple tags for a question and simultaneously get the attention of multiple projects.

**Comment by thinksource** [comment]
@harrah Actually, I already ask this question on StackOverflow, just no body answer it. 
the link is http://stackoverflow.com/questions/20278454/i-deleted-the-sbt-directory-in-accident-how-to-make-the-sbt-run-again

**Comment by jsuereth** [comment]
Yeah, this is a conformance issue with Activator.  Perhaps you can open an issue against activator that it should also use the `sbtconfig.txt` file?   I maintain both the windows sbt distro + the activator scripts, so if you open a ticket on the activator side, we can fix that.   It's not really an issue with sbt.
