### ISSUE TITLE
SecurityException during `ClassToAPI`, crashes the build

### ISSUE THREAD

**Issue by dragos** [sbt/sbt#1020]
Saw this at a client. I don't know of any workaround (build fails).

```
java.lang.SecurityException: class "org.eclipse.jdt.ui.wizards.NewElementWizardPage"'s signer information does not match signer information of other classes in the same package
                at java.lang.ClassLoader.checkCerts(ClassLoader.java:943)
                at java.lang.ClassLoader.preDefineClass(ClassLoader.java:657)
                at java.lang.ClassLoader.defineClass(ClassLoader.java:785)
                at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
                at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
                at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
                at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
                at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
                at java.security.AccessController.doPrivileged(Native Method)
                at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
                at java.lang.ClassLoader.defineClass1(Native Method)
                at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
                at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
                at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
                at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
                at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
                at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
                at java.security.AccessController.doPrivileged(Native Method)
                at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
                at java.lang.ClassLoader.defineClass1(Native Method)
                at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
                at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
                at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
                at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
                at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
                at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
                at java.security.AccessController.doPrivileged(Native Method)
                at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
                at java.lang.Class.getDeclaredFields0(Native Method)
                at java.lang.Class.privateGetDeclaredFields(Class.java:2308)
                at java.lang.Class.getDeclaredFields(Class.java:1760)
                at sbt.ClassToAPI$.structure(ClassToAPI.scala:74)
                at sbt.ClassToAPI$.x$2$lzycompute$1(ClassToAPI.scala:62)
                at sbt.ClassToAPI$.x$2$1(ClassToAPI.scala:62)
                at sbt.ClassToAPI$.instance$lzycompute$1(ClassToAPI.scala:62)
                at sbt.ClassToAPI$.sbt$ClassToAPI$$instance$1(ClassToAPI.scala:62)
                at sbt.ClassToAPI$$anonfun$5.apply(ClassToAPI.scala:63)
                at sbt.ClassToAPI$$anonfun$5.apply(ClassToAPI.scala:63)
                at xsbti.SafeLazy$Impl._t$lzycompute(SafeLazy.scala:20)
                at xsbti.SafeLazy$Impl._t(SafeLazy.scala:18)
                at xsbti.SafeLazy$Impl.get(SafeLazy.scala:24)
                at sbt.ClassToAPI$$anonfun$process$1.apply(ClassToAPI.scala:22)
                at sbt.ClassToAPI$$anonfun$process$1.apply(ClassToAPI.scala:22)
                at scala.collection.immutable.List.foreach(List.scala:318)
                at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
                at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
                at sbt.ClassToAPI$.process(ClassToAPI.scala:22)
                at sbt.compiler.AggressiveCompile$$anonfun$3.sbt$compiler$AggressiveCompile$$anonfun$$readAPI$1(AggressiveCompile.scala:130)
                at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileJava$1$2$$anonfun$apply$mcV$sp$2$$anonfun$apply$6.apply(AggressiveCompile.scala:138)
                at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileJava$1$2$$anonfun$apply$mcV$sp$2$$anonfun$apply$6.apply(AggressiveCompile.scala:138)
                at sbt.classfile.Analyze$$anonfun$apply$9.apply(Analyze.scala:45)
                at sbt.classfile.Analyze$$anonfun$apply$9.apply(Analyze.scala:43)
                at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772)
                at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:98)
                at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:98)
                at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:226)
                at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:39)
                at scala.collection.mutable.HashMap.foreach(HashMap.scala:98)
                at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:771)
                at sbt.classfile.Analyze$.apply(Analyze.scala:43)
                at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileJava$1$2$$anonfun$apply$mcV$sp$2.apply(AggressiveCompile.scala:138)
                at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileJava$1$2$$anonfun$apply$mcV$sp$2.apply(AggressiveCompile.scala:136)
                at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772)
                at scala.collection.immutable.List.foreach(List.scala:318)
                at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:771)
                at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileJava$1$2.apply$mcV$sp(AggressiveCompile.scala:136)
                at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileJava$1$2.apply(AggressiveCompile.scala:136)
                at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileJava$1$2.apply(AggressiveCompile.scala:136)
                at sbt.compiler.AggressiveCompile.sbt$compiler$AggressiveCompile$$timed(AggressiveCompile.scala:159)
                at sbt.compiler.AggressiveCompile$$anonfun$3.compileJava$1(AggressiveCompile.scala:135)
                at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:142)
                at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:86)
                at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:30)
                at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:28)
                at sbt.inc.Incremental$.cycle(Incremental.scala:73)
                at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:33)
                at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:32)
                at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:41)
                at sbt.inc.Incremental$.compile(Incremental.scala:32)
                at sbt.inc.IncrementalCompile$.apply(Compile.scala:25)
                at sbt.compiler.AggressiveCompile.compile2(AggressiveCompile.scala:150)
                at sbt.compiler.AggressiveCompile.compile1(AggressiveCompile.scala:70)
                at sbt.compiler.AggressiveCompile.apply(AggressiveCompile.scala:45)
                at sbt.compiler.IC$.compile(IncrementalCompiler.scala:22)
                at scala.tools.eclipse.buildmanager.sbtintegration.EclipseSbtBuildManager.runCompiler(EclipseSbtBuildManager.scala:133)
                at scala.tools.eclipse.buildmanager.sbtintegration.EclipseSbtBuildManager.update(EclipseSbtBuildManager.scala:123)
                at scala.tools.eclipse.buildmanager.sbtintegration.EclipseSbtBuildManager.build(EclipseSbtBuildManager.scala:178)
                at scala.tools.eclipse.ScalaProject.build(ScalaProject.scala:664)
                at scala.tools.eclipse.ScalaBuilder.build(ScalaBuilder.scala:119)
                at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:726)
                at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
                at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:199)
                at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:239)
                at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:292)
                at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
                at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:295)
                at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:351)
                at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:374)
                at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
                at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
                at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
```

**Comment by harrah** [comment]
sbt loads classes compiled from Java sources in a class loader as part of its analysis.  That's the sbt specific part- to do anything more with this would require a test case.
