### ISSUE TITLE
sbt throws IllegalArgumentException during init on IBM JVM

### ISSUE THREAD

**Issue by tgpfeiffer** [sbt/sbt#1027]
I tried to build https://github.com/tgpfeiffer/twtdb on a Windows 7 machine with IBM JVM using `.\sbt.bat`, but after downloading all the dependencies, I get

> Got throwable in Signal initialisation : java.lang.IllegalArgumentException: Unknown signal: CONT

The build runs fine on a Linux machine with Sun JVM.

---

Environment details:

```
[...]> java -version
java version "1.6.0"
Java(TM) SE Runtime Environment (build pwa6460sr9ifix-20110211_02(SR9+IZ94423))
IBM J9 VM (build 2.4, JRE 1.6.0 IBM J9 2.4 Windows 7 amd64-64 jvmwa6460sr9-20101124_69295 (JIT enabled, AOT enabled)
J9VM - 20101124_069295
JIT  - r9_20101028_17488ifx2
GC   - 20101027_AA)
JCL  - 20110211_02
```

Stacktrace:

```
[...]> .\sbt.bat
>set SCRIPT_DIR=[...]\twtdb\
>java -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256m -Xmx1024M -Xss2M -jar "[...]\twtdb\\sbt-launch-0.12.1.jar"
[info] Loading project definition from [...]\twtdb\project
[info] Set current project to twtdb - A Twitter Dashboard (in build [...])
Got throwable in Signal initialisation : java.lang.IllegalArgumentException: Unknown signal: CONT
java.lang.IllegalArgumentException: Unknown signal: CONT
        at com.ibm.misc.AbstractSignalInfo.getSignalNumber(AbstractSignalInfo.java:59)
        at com.ibm.misc.SignalInfo.getSignalNumber(SignalInfo.java:43)
        at sun.misc.Signal.<init>(Signal.java:141)
        at sbt.Signals0.supported(Signal.scala:39)
        at sbt.Signals$.supported(Signal.scala:26)
        at sbt.JLine$.<init>(LineReader.scala:116)
        at sbt.JLine$.<clinit>(LineReader.scala)
        at java.lang.J9VMInternals.initializeImpl(Native Method)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:200)
        at sbt.FullReader$.init$default$3(LineReader.scala:123)
        at sbt.BasicCommands$$anonfun$shell$1.apply(BasicCommands.scala:138)
        at sbt.BasicCommands$$anonfun$shell$1.apply(BasicCommands.scala:135)
        at sbt.Command$$anonfun$command$1$$anonfun$apply$1.apply(Command.scala:31)
        at sbt.Command$$anonfun$command$1$$anonfun$apply$1.apply(Command.scala:31)
        at sbt.Command$.process(Command.scala:90)
        at sbt.MainLoop$$anonfun$next$1$$anonfun$apply$1.apply(MainLoop.scala:71)
        at sbt.MainLoop$$anonfun$next$1$$anonfun$apply$1.apply(MainLoop.scala:71)
        at sbt.State$$anon$2.process(State.scala:171)
        at sbt.MainLoop$$anonfun$next$1.apply(MainLoop.scala:71)
        at sbt.MainLoop$$anonfun$next$1.apply(MainLoop.scala:71)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
        at sbt.MainLoop$.next(MainLoop.scala:71)
        at sbt.MainLoop$.run(MainLoop.scala:64)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:53)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:50)
        at sbt.Using.apply(Using.scala:25)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:50)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:33)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:17)
        at sbt.MainLoop$.runLogged(MainLoop.scala:13)
        at sbt.xMain.run(Main.scala:26)
        at xsbt.boot.Launch$.run(Launch.scala:55)
        at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
        at xsbt.boot.Launch$.launch(Launch.scala:69)
        at xsbt.boot.Launch$.apply(Launch.scala:16)
        at xsbt.boot.Boot$.runImpl(Boot.scala:31)
        at xsbt.boot.Boot$.main(Boot.scala:20)
        at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.ExceptionInInitializerError
[error] Use 'last' for the full log.
```

**Comment by ritschwumm** [comment]
hm, https://github.com/sbt/sbt/blob/7dadbf1fc6915e61cb6ddc4aa304fc8ae9e78ae6/util/collection/src/main/scala/sbt/Signal.scala#L39 looks good to me

**Comment by tgpfeiffer** [comment]
I see, the IllegalArgumentException should actually be caught, right? Weird.
Just tried with the 0.12.2 and 0.13.0 jars, same behavior.

**Comment by harrah** [comment]
Thank you for providing plenty of information.  You can workaround it for now by passing `-Dsbt.disable.cont=true` to sbt.  From the output, it appears that the actual error sbt sees is `ExceptionInInitializerError` and perhaps it is J9's Signal implementation that is printing the underlying IllegalArgumentException and stack trace.

After configuring the workaround, can you report back what this does:

```
$ sbt
> eval try { new sun.misc.Signal("CONT") } catch { case e: ExceptionInInitializerError => () }
```

Ideally, it would catch the exception and nothing would be printed to the screen.

**Comment by tgpfeiffer** [comment]
@harrah Thank you very much, the workaround works great!

Concerning the command you posted, I actually get similar output:

```
[...]> .\sbt
>set SCRIPT_DIR=[...]\twtdb\
>java -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256m -Xmx1024M -Xss2M -Dsbt.disable.cont=true -jar "[...]\\sbt-launch-0.13.0.jar"
[info] Loading project definition from [...]\twtdb\project
[info] Set current project to twtdb - A Twitter Dashboard (in build file:/[...]/twtdb/)
> eval try { new sun.misc.Signal("CONT") } catch { case e: ExceptionInInitializerError => () }
Got throwable in Signal initialisation : java.lang.IllegalArgumentException: Unknown signal: CONT
java.lang.IllegalArgumentException: Unknown signal: CONT
        at com.ibm.misc.AbstractSignalInfo.getSignalNumber(AbstractSignalInfo.java:59)
        at com.ibm.misc.SignalInfo.getSignalNumber(SignalInfo.java:43)
        at sun.misc.Signal.<init>(Signal.java:141)
        at $28b59a8e056b1a4a0dce$.$sbtdef(<eval>:1)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
        at java.lang.reflect.Method.invoke(Method.java:611)
        at sbt.compiler.Eval.getValue(Eval.scala:129)
        at sbt.compiler.Eval$$anonfun$load$1.apply(Eval.scala:100)
        [...]
        at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.IllegalArgumentException: Unknown signal: CONT
[error] Use 'last' for the full log.
>
```

The behavior shows with both 0.12.1 and 0.13.0

**Comment by harrah** [comment]
Well that's strange, how about:

```
> eval try { new sun.misc.Signal("CONT") } catch { case e: ExceptionInInitializerError => (); case e: IllegalArgumentException => () }
```

**Comment by tgpfeiffer** [comment]
I did

```
> eval try { new sun.misc.Signal("CONT") } catch {
    case e: ExceptionInInitializerError => println("EIIE");
    case e: IllegalArgumentException => println("IAE");
    case e => println("another exception: " + e) }
```

and got:

```
Got throwable in Signal initialisation : java.lang.IllegalArgumentException: Unknown signal: CONT
java.lang.IllegalArgumentException: Unknown signal: CONT
        at com.ibm.misc.AbstractSignalInfo.getSignalNumber(AbstractSignalInfo.java:59)
        at com.ibm.misc.SignalInfo.getSignalNumber(SignalInfo.java:43)
        [...]
        at xsbt.boot.Boot.main(Boot.scala)
another exception: java.lang.RuntimeException: java.lang.IllegalArgumentException: Unknown signal: CONT
```

I guess that, as you suspected, it is indeed the Signal implementation printing the stacktrace, but I don't really understand the kind of exception handling that is happening here...

**Comment by harrah** [comment]
Fixing this properly probably involves either directly calling `com.ibm.misc.SignalInfo.getSignalNumber` or maybe disabling it based on the jvm vendor and os.name.  The underlying feature is the ability to properly reset the terminal after resuming.  This isn't supported by your OS (at least not via the CONT signal) or isn't necessary, so you aren't losing functionality with the workaround.  I'm unlikely to work on this soon, so patches are welcome.

**Comment by eed3si9n** [comment]
I'm closing this as won't fix.
