### ISSUE TITLE
Compiler crash when .value, etc... used outside of task macro

### ISSUE THREAD

**Issue by harrah** [sbt/sbt#1031]
This was caused by the removal of `resetLocalAttrs`.  When `.value, etc...` are used properly, the task/setting macros remove them as part of macro expansion.  When they are not removed, they survive beyond typers.  Therefore, problems with untyped trees from the `.value`-like macros are only exposed when used in the wrong context.

**Comment by retronym** [comment]
@harrah If I remove the `setType` _and_ omit the manual call to `c.typeCheck`, we get:

```
$q124 tpe is null
    at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.mainTransform(UnCurry.scala:684)
    at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:122)
    at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:82)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1272)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2897)
```
