### ISSUE TITLE
sbt doesn't like colons in project directory names

### ISSUE THREAD

**Issue by ritschwumm** [sbt/sbt#1038]
when the directory of a project contains a colon, sbt fails to start:

```
[info] Done updating.
[info] Compiling 1 Scala source to /home/<censored>/http4s:http4s/project/target/scala-2.10/sbt-0.13/classes...
/home/<censored>/http4s:http4s/build.sbt:1: error: not found: object Http4sDependencies
import Http4sDependencies._
       ^
sbt.compiler.EvalException: Type error in expression
    at sbt.compiler.Eval.checkError(Eval.scala:343)
    at sbt.compiler.Eval.compileAndLoad(Eval.scala:165)
    at sbt.compiler.Eval.evalCommon(Eval.scala:135)
    at sbt.compiler.Eval.evalDefinitions(Eval.scala:109)
    at sbt.EvaluateConfigurations$.evaluateDefinitions(EvaluateConfigurations.scala:125)
    at sbt.EvaluateConfigurations$.evaluateSbtFile(EvaluateConfigurations.scala:48)
    at sbt.Load$.sbt$Load$$loadSettingsFile$1(Load.scala:502)
```

**Comment by harrah** [comment]
At best I see sbt issuing a better error message.  Colons are used for separating Java classpaths on unix.

**Comment by ritschwumm** [comment]
hm, good point. same problem with semicolons on windows, i guess.
