### ISSUE TITLE
Problem loading plugin setting in build.sbt

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#110]
## steps
1. publish 0.3-SNAPSHOT from [this branch](https://github.com/eed3si9n/sbt-assembly/tree/gh-7) locally.
2. add following to plugins/build.sbt:
   
   ```
   libraryDependencies <+= (sbtVersion) { sv => "com.eed3si9n" %% "sbt-assembly" % ("sbt" + sv + "_0.3-SNAPSHOT") }
   ```
3. add following to build.sbt:
   
   ```
   seq(sbtassembly.AssemblyPlugin.assemblySettings)
   ```
4. run sbt 0.10.1
## problem

I get the following error:

```
java.io.IOException: class file needed by AssemblyPlugin is missing.
reference type _$33 of (conf: sbt.Configuration)(ss: Seq[sbt.Project.Setting[_]])Seq[sbt.Project.Setting[_]] refers to nonexisting symbol.
```
## expectation

the settings gets loaded into k-v.

what am I doing wrong?
# full stacktrace

```
[helloworld]$ sbt101
[info] Set current project to default-bd6957 (in build file:/Users/eed3si9n/.sbt/plugins/)
[info] Compiling 1 Scala source to /Users/eed3si9n/.sbt/plugins/target/scala-2.8.1.final/classes...
[info] Set current project to default-35385d (in build file:/Users/eed3si9n/work/helloworld/project/plugins/)
java.io.IOException: class file needed by AssemblyPlugin is missing.
reference type _$33 of (conf: sbt.Configuration)(ss: Seq[sbt.Project.Setting[_]])Seq[sbt.Project.Setting[_]] refers to nonexisting symbol.
    at scala.reflect.generic.UnPickler$Scan.errorMissingRequirement(UnPickler.scala:754)
    at scala.tools.nsc.symtab.classfile.UnPickler$CompileScan.errorMissingRequirement(UnPickler.scala:43)
    at scala.tools.nsc.symtab.classfile.UnPickler$CompileScan.errorMissingRequirement(UnPickler.scala:28)
    at scala.reflect.generic.UnPickler$Scan.readSymbol(UnPickler.scala:194)
    at scala.reflect.generic.UnPickler$Scan$$anonfun$readSymbolRef$1.apply(UnPickler.scala:708)
    at scala.reflect.generic.UnPickler$Scan$$anonfun$readSymbolRef$1.apply(UnPickler.scala:708)
    at scala.reflect.generic.UnPickler$Scan.at(UnPickler.scala:150)
    at scala.reflect.generic.UnPickler$Scan.readSymbolRef(UnPickler.scala:708)
    at scala.reflect.generic.UnPickler$Scan.readType(UnPickler.scala:283)
    at scala.reflect.generic.UnPickler$Scan$$anonfun$readTypeRef$1.apply(UnPickler.scala:709)
    at scala.reflect.generic.UnPickler$Scan$$anonfun$readTypeRef$1.apply(UnPickler.scala:709)
    at scala.reflect.generic.UnPickler$Scan.at(UnPickler.scala:150)
    at scala.reflect.generic.UnPickler$Scan.readTypeRef(UnPickler.scala:709)
    at scala.reflect.generic.UnPickler$Scan$$anonfun$3.apply(UnPickler.scala:284)
    at scala.reflect.generic.UnPickler$Scan$$anonfun$3.apply(UnPickler.scala:284)
    at scala.reflect.generic.PickleBuffer.until(PickleBuffer.scala:162)
    at scala.reflect.generic.UnPickler$Scan.readType(UnPickler.scala:284)
    at scala.reflect.generic.UnPickler$Scan$$anonfun$readTypeRef$1.apply(UnPickler.scala:709)
    at scala.reflect.generic.UnPickler$Scan$$anonfun$readTypeRef$1.apply(UnPickler.scala:709)
    at scala.reflect.generic.UnPickler$Scan.at(UnPickler.scala:150)
    at scala.reflect.generic.UnPickler$Scan.readTypeRef(UnPickler.scala:709)
    at scala.reflect.generic.UnPickler$Scan.readType(UnPickler.scala:307)
    at scala.reflect.generic.UnPickler$Scan$$anonfun$readTypeRef$1.apply(UnPickler.scala:709)
    at scala.reflect.generic.UnPickler$Scan$$anonfun$readTypeRef$1.apply(UnPickler.scala:709)
    at scala.reflect.generic.UnPickler$Scan.at(UnPickler.scala:150)
    at scala.reflect.generic.UnPickler$Scan.readTypeRef(UnPickler.scala:709)
    at scala.reflect.generic.UnPickler$Scan$$anonfun$3.apply(UnPickler.scala:284)
    at scala.reflect.generic.UnPickler$Scan$$anonfun$3.apply(UnPickler.scala:284)
    at scala.reflect.generic.PickleBuffer.until(PickleBuffer.scala:162)
    at scala.reflect.generic.UnPickler$Scan.readType(UnPickler.scala:284)
    at scala.reflect.generic.UnPickler$Scan$$anonfun$readTypeRef$1.apply(UnPickler.scala:709)
    at scala.reflect.generic.UnPickler$Scan$$anonfun$readTypeRef$1.apply(UnPickler.scala:709)
    at scala.reflect.generic.UnPickler$Scan.at(UnPickler.scala:150)
    at scala.reflect.generic.UnPickler$Scan.readTypeRef(UnPickler.scala:709)
    at scala.reflect.generic.UnPickler$Scan.readType(UnPickler.scala:303)
    at scala.tools.nsc.symtab.classfile.UnPickler$CompileScan$LazyTypeRef$$anonfun$1.apply(UnPickler.scala:58)
    at scala.tools.nsc.symtab.classfile.UnPickler$CompileScan$LazyTypeRef$$anonfun$1.apply(UnPickler.scala:58)
    at scala.reflect.generic.UnPickler$Scan.at(UnPickler.scala:150)
    at scala.tools.nsc.symtab.classfile.UnPickler$CompileScan$LazyTypeRef.complete(UnPickler.scala:58)
    at scala.tools.nsc.symtab.classfile.UnPickler$CompileScan$LazyTypeRef.complete(UnPickler.scala:54)
    at scala.tools.nsc.symtab.Symbols$Symbol.info(Symbols.scala:735)
    at scala.tools.nsc.symtab.Symbols$Symbol.tpe(Symbols.scala:710)
    at scala.tools.nsc.symtab.Symbols$Symbol.tpeHK(Symbols.scala:896)
    at scala.tools.nsc.symtab.Types$Type.computeMemberType(Types.scala:536)
    at scala.tools.nsc.symtab.Symbols$MethodSymbol.typeAsMemberOf(Symbols.scala:1780)
    at scala.tools.nsc.symtab.Types$Type.memberType(Types.scala:531)
    at scala.tools.nsc.typechecker.Infer$Inferencer.checkAccessible(Infer.scala:273)
    at scala.tools.nsc.typechecker.Typers$Typer.makeAccessible(Typers.scala:610)
    at scala.tools.nsc.typechecker.Typers$Typer.typedSelect$1(Typers.scala:3607)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:4110)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:4203)
    at scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:2202)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typedArgs$3.apply(Typers.scala:2212)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typedArgs$3.apply(Typers.scala:2211)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:206)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:206)
    at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:61)
    at scala.collection.immutable.List.foreach(List.scala:45)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:206)
    at scala.collection.immutable.List.map(List.scala:45)
    at scala.tools.nsc.typechecker.Typers$Typer.typedArgs(Typers.scala:2211)
    at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:2425)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$tryTypedApply$1$1.apply(Typers.scala:3318)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$tryTypedApply$1$1.apply(Typers.scala:3318)
    at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:722)
    at scala.tools.nsc.typechecker.Typers$Typer.tryTypedApply$1(Typers.scala:3318)
    at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:3378)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:4049)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:4203)
    at scala.tools.nsc.typechecker.Typers$Typer.transformedOrTyped(Typers.scala:4348)
    at scala.tools.nsc.typechecker.Typers$Typer.typedDefDef(Typers.scala:1789)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:3862)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:4203)
    at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:2128)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$20.apply(Typers.scala:2196)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$20.apply(Typers.scala:2196)
    at scala.collection.immutable.List.loop$1(List.scala:115)
    at scala.collection.immutable.List.mapConserve(List.scala:132)
    at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:2196)
    at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1549)
    at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1348)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:3856)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:4203)
    at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:2128)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$20.apply(Typers.scala:2196)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$20.apply(Typers.scala:2196)
    at scala.collection.immutable.List.loop$1(List.scala:115)
    at scala.collection.immutable.List.mapConserve(List.scala:132)
    at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:2196)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:3849)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:4203)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:4252)
    at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:85)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply(Global.scala:282)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply(Global.scala:282)
    at scala.tools.nsc.reporters.Reporter.withSource(Reporter.scala:48)
    at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:282)
    at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:80)
    at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:80)
    at scala.collection.Iterator$class.foreach(Iterator.scala:631)
    at scala.collection.LinearSeqLike$$anon$1.foreach(LinearSeqLike.scala:52)
    at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:80)
    at sbt.compiler.Eval$$anonfun$compile$1$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(Eval.scala:90)
    at sbt.compiler.Eval$$anonfun$compile$1$1$$anonfun$apply$mcV$sp$1.apply(Eval.scala:90)
    at sbt.compiler.Eval$$anonfun$compile$1$1$$anonfun$apply$mcV$sp$1.apply(Eval.scala:90)
    at scala.tools.nsc.symtab.SymbolTable.atPhase(SymbolTable.scala:103)
    at sbt.compiler.Eval$$anonfun$compile$1$1.apply$mcV$sp(Eval.scala:90)
    at sbt.compiler.Eval$$anonfun$compile$1$1.apply(Eval.scala:90)
    at sbt.compiler.Eval$$anonfun$compile$1$1.apply(Eval.scala:90)
    at scala.tools.nsc.reporters.Reporter.withSource(Reporter.scala:48)
    at sbt.compiler.Eval.compile$1(Eval.scala:89)
    at sbt.compiler.Eval.eval0(Eval.scala:96)
    at sbt.compiler.Eval.eval(Eval.scala:62)
    at sbt.EvaluateConfigurations$.evaluateSetting(Build.scala:104)
    at sbt.EvaluateConfigurations$$anonfun$1.apply(Build.scala:92)
    at sbt.EvaluateConfigurations$$anonfun$1.apply(Build.scala:91)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:206)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:206)
    at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:61)
    at scala.collection.immutable.List.foreach(List.scala:45)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:206)
    at scala.collection.immutable.List.map(List.scala:45)
    at sbt.EvaluateConfigurations$.evaluateConfiguration(Build.scala:91)
    at sbt.EvaluateConfigurations$.evaluateConfiguration(Build.scala:87)
    at sbt.EvaluateConfigurations$$anonfun$apply$5.apply(Build.scala:85)
    at sbt.EvaluateConfigurations$$anonfun$apply$5.apply(Build.scala:85)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:206)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:206)
    at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:61)
    at scala.collection.immutable.List.foreach(List.scala:45)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:206)
    at scala.collection.immutable.List.map(List.scala:45)
    at sbt.EvaluateConfigurations$.apply(Build.scala:85)
    at sbt.Load$.configurations(Load.scala:207)
    at sbt.Load$$anonfun$buildConfigurations$1$$anonfun$5.apply(Load.scala:179)
    at sbt.Load$$anonfun$buildConfigurations$1$$anonfun$5.apply(Load.scala:170)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:227)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:227)
    at scala.collection.immutable.Map$Map1.foreach(Map.scala:105)
    at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:227)
    at scala.collection.immutable.Map$Map1.flatMap(Map.scala:93)
    at sbt.Load$$anonfun$buildConfigurations$1.apply(Load.scala:170)
    at sbt.Load$$anonfun$buildConfigurations$1.apply(Load.scala:166)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:227)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:227)
    at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:61)
    at scala.collection.immutable.List.foreach(List.scala:45)
    at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:227)
    at scala.collection.immutable.List.flatMap(List.scala:45)
    at sbt.Load$.buildConfigurations(Load.scala:166)
    at sbt.Load$.apply(Load.scala:118)
    at sbt.Load$.defaultLoad(Load.scala:36)
    at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:371)
    at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:368)
    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:61)
    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:61)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:63)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:63)
    at sbt.Command$.process(Command.scala:91)
    at sbt.MainLoop$$anonfun$next$1$$anonfun$apply$1.apply(Main.scala:66)
    at sbt.MainLoop$$anonfun$next$1$$anonfun$apply$1.apply(Main.scala:66)
    at sbt.State$$anon$1.process(State.scala:59)
    at sbt.MainLoop$$anonfun$next$1.apply(Main.scala:66)
    at sbt.MainLoop$$anonfun$next$1.apply(Main.scala:66)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:13)
    at sbt.MainLoop$.next(Main.scala:66)
    at sbt.MainLoop$.run(Main.scala:61)
    at sbt.xMain.run(Main.scala:33)
    at xsbt.boot.Launch$.run(Launch.scala:54)
    at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:43)
    at xsbt.boot.Launch$.launch(Launch.scala:68)
    at xsbt.boot.Launch$.apply(Launch.scala:14)
    at xsbt.boot.Boot$.runImpl(Boot.scala:24)
    at xsbt.boot.Boot$.main(Boot.scala:15)
    at xsbt.boot.Boot.main(Boot.scala)
[error] java.io.IOException: class file needed by AssemblyPlugin is missing.
[error] reference type _$33 of (conf: sbt.Configuration)(ss: Seq[sbt.Project.Setting[_]])Seq[sbt.Project.Setting[_]] refers to nonexisting symbol.
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, or (i)gnore? 
```

**Comment by ijuma** [comment]
Looks like a scalac separate compilation bug. Mark reported one that got fixed in scalac's trunk a few weeks ago. Try a clean build and see if that fixes your problem.

**Comment by harrah** [comment]
The separate compilation bug is sufficiently probable that I'll close this.  Reopen if it is not the case.

**Comment by eed3si9n** [comment]
## steps

```
$ rm -rf /project/target
$ rm -rf /project/plugins/project/target
$ rm -rf ~/.sbt/plugins/target
$ sbt101
```

I've tried the above, but the same result..

**Comment by eed3si9n** [comment]
## fix

Annotate the setting value with the type:

```
lazy val assemblySettings: Seq[sbt.Project.Setting[_]] = ...
```

**Comment by ijuma** [comment]
You can use "clean" to perform a clean. :) Not sure if the commands you performed are fully equivalent, so I'll leave that to Mark.

**Comment by eed3si9n** [comment]
@ijuma It had nothing to do with the compilation bug. `seq(..)` just could not figure out my settings val's type.

**Comment by ijuma** [comment]
And I mean a clean build of the plugin.

**Comment by ijuma** [comment]
Are you sure? This was discussed in a thread a while ago and adding type annotations was just a way to workaround the separate compilation bug.

**Comment by eed3si9n** [comment]
I've cleanly compiled more than a dozen times in the last few days. Tried `clean`, cloned from github again etc.. You can grab the code and try it yourself.

**Comment by ijuma** [comment]
Interesting.
