### ISSUE TITLE
sbt crashes compiling Play Framework project

### ISSUE THREAD

**Issue by carlosprados** [sbt/sbt#1106]
#### Operative system

```
charlie@kaitain ~ $ uname -a
Linux kaitain 3.8.0-19-generic #30-Ubuntu SMP Wed May 1 16:35:23 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
```
#### Java Version

```
charlie@kaitain ~ $ java -version
java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)
```
#### Play Framework
- 2.2.1

After some Play usage in development mode, this mode performs incremental compilations when a page is reloaded and a source code change is detected, the sbt compiler throws the following error/exception:

Exception/Error:

```
[info] Compiling 1 Java source to /home/charlie/Dropbox/code-dpb/metscale-play/target/scala-2.10/classes...
[error] An exception has occurred in the compiler (1.7.0_51). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.
[error] java.lang.NullPointerException
[error]     at com.sun.tools.javac.comp.Resolve.checkRawArgumentsAcceptable(Resolve.java:441)
[error]     at com.sun.tools.javac.comp.Resolve.rawInstantiate(Resolve.java:396)
[error]     at com.sun.tools.javac.comp.Resolve.selectBest(Resolve.java:688)
[error]     at com.sun.tools.javac.comp.Resolve.findMethod(Resolve.java:950)
[error]     at com.sun.tools.javac.comp.Resolve.findMethod(Resolve.java:911)
[error]     at com.sun.tools.javac.comp.Resolve.resolveConstructor(Resolve.java:1656)
[error]     at com.sun.tools.javac.comp.Resolve.resolveConstructor(Resolve.java:1576)
[error]     at com.sun.tools.javac.comp.Attr.visitNewClass(Attr.java:1734)
[error]     at com.sun.tools.javac.tree.JCTree$JCNewClass.accept(JCTree.java:1372)
[error]     at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:431)
[error]     at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:418)
[error]     at com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:449)
[error]     at com.sun.tools.javac.comp.Attr.visitAssign(Attr.java:1993)
[error]     at com.sun.tools.javac.tree.JCTree$JCAssign.accept(JCTree.java:1466)
[error]     at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:431)
[error]     at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:418)
[error]     at com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:460)
[error]     at com.sun.tools.javac.comp.Attr.visitExec(Attr.java:1294)
[error]     at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1167)
[error]     at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:431)
[error]     at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:418)
[error]     at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:480)
[error]     at com.sun.tools.javac.comp.Attr.attribStats(Attr.java:496)
[error]     at com.sun.tools.javac.comp.Attr.visitBlock(Attr.java:918)
[error]     at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:781)
[error]     at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:431)
[error]     at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:418)
[error]     at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:480)
[error]     at com.sun.tools.javac.comp.Attr.visitIf(Attr.java:1283)
[error]     at com.sun.tools.javac.tree.JCTree$JCIf.accept(JCTree.java:1140)
[error]     at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:431)
[error]     at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:418)
[error]     at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:480)
[error]     at com.sun.tools.javac.comp.Attr.attribStats(Attr.java:496)
[error]     at com.sun.tools.javac.comp.Attr.visitBlock(Attr.java:918)
[error]     at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:781)
[error]     at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:431)
[error]     at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:418)
[error]     at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:480)
[error]     at com.sun.tools.javac.comp.Attr.visitMethodDef(Attr.java:836)
[error]     at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:669)
[error]     at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:431)
[error]     at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:418)
[error]     at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:480)
[error]     at com.sun.tools.javac.comp.Attr.attribClassBody(Attr.java:3250)
[error]     at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:3173)
[error]     at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:3109)
[error]     at com.sun.tools.javac.comp.Attr.attrib(Attr.java:3083)
[error]     at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1184)
[error]     at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:870)
[error]     at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:829)
[error]     at com.sun.tools.javac.main.Main.compile(Main.java:439)
[error]     at com.sun.tools.javac.main.Main.compile(Main.java:353)
[error]     at com.sun.tools.javac.main.Main.compile(Main.java:342)
[error]     at com.sun.tools.javac.main.Main.compile(Main.java:333)
[error]     at com.sun.tools.javac.Main.compile(Main.java:76)
[error]     at com.sun.tools.javac.Main.main(Main.java:61)
[error] (compile:compile) javac returned nonzero exit code
[error] application - 

! @6h7026836 - Internal server error, for (GET) [/metscale/user] ->

play.PlayExceptions$UnexpectedException: Unexpected exception[The compilation failed without reporting any problem!]
    at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$17.apply(PlayReloader.scala:306) ~[na:na]
    at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$17.apply(PlayReloader.scala:306) ~[na:na]
    at scala.Option.getOrElse(Option.scala:120) ~[scala-library.jar:na]
    at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:305) ~[na:na]
    at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:298) ~[na:na]
    at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
sbt.compiler.CompileFailed: null
    at sbt.compiler.JavaCompiler$JavaTool0.compile(JavaCompiler.scala:77) ~[na:na]
    at sbt.compiler.JavaTool$class.apply(JavaCompiler.scala:35) ~[na:na]
    at sbt.compiler.JavaCompiler$JavaTool0.apply(JavaCompiler.scala:63) ~[na:na]
    at sbt.compiler.JavaCompiler$class.compile(JavaCompiler.scala:21) ~[na:na]
    at sbt.compiler.JavaCompiler$JavaTool0.compile(JavaCompiler.scala:63) ~[na:na]
    at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileJava$1$1.apply$mcV$sp(AggressiveCompile.scala:126) ~[na:na]
[warn] play - No application found at invoker init
```

The same error has been reported to Oracle.

**Comment by harrah** [comment]
Without a reproducible test case, the stack trace indicates this is a javac bug.  Note that Oracle will likely require source code as well: "Include your _program_ and the following diagnostic in your report."
