### ISSUE TITLE
[0.13.2] exception during macro expansion: java.lang.NullPointerException

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#1107]
## steps
1. grab sbt/sbt-appengine tag [0.6.1](https://github.com/sbt/sbt-appengine/tree/0.6.1)
2. change to `sbt.version=0.13.2-SNAPSHOT`
## problem

``` scala
sbt-appengine> compile
[info] Updating {file:/x/sbt-appengine/}sbt-appengine...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 2 Scala sources to /x/sbt-appengine/target/scala-2.10/sbt-0.13/classes...
[error] /x/sbt-appengine/src/main/scala/AppenginePlugin.scala:162: exception during macro expansion: 
[error] java.lang.NullPointerException
[error]     at sbt.appmacro.Instance$.sbt$appmacro$Instance$$addType$1(Instance.scala:170)
[error]     at sbt.appmacro.Instance$$anonfun$sbt$appmacro$Instance$$sub$1$1.apply(Instance.scala:178)
[error]     at sbt.appmacro.Instance$$anonfun$sbt$appmacro$Instance$$sub$1$1.apply(Instance.scala:177)
[error]     at sbt.appmacro.Converted$Success.transform(Convert.scala:33)
[error]     at sbt.appmacro.Instance$.sbt$appmacro$Instance$$sub$1(Instance.scala:177)
[error]     at sbt.appmacro.Instance$$anonfun$1.apply(Instance.scala:183)
[error]     at sbt.appmacro.Instance$$anonfun$1.apply(Instance.scala:183)
[error]     at sbt.appmacro.ContextUtil$appTransformer$2$.transform(ContextUtil.scala:227)
[error]     at sbt.appmacro.ContextUtil$appTransformer$2$.transform(ContextUtil.scala:222)
[error]     at scala.reflect.internal.Trees$class.itransform(Trees.scala:1217)
[error]     at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
[error]     at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
[error]     at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2897)
[error]     at sbt.appmacro.ContextUtil$appTransformer$2$.transform(ContextUtil.scala:232)
[error]     at sbt.appmacro.ContextUtil$appTransformer$2$.transform(ContextUtil.scala:222)
[error]     at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2900)
[error]     at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2900)
[error]     at scala.collection.immutable.List.loop$1(List.scala:170)
[error]     at scala.collection.immutable.List.mapConserve(List.scala:186)
[error]     at scala.reflect.api.Trees$Transformer.transformTrees(Trees.scala:2900)
[error]     at scala.reflect.internal.Trees$class.itransform(Trees.scala:1219)
[error]     at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
[error]     at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
[error]     at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2897)
[error]     at sbt.appmacro.ContextUtil$appTransformer$2$.transform(ContextUtil.scala:230)
[error]     at sbt.appmacro.ContextUtil$appTransformer$2$.transform(ContextUtil.scala:222)
[error]     at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2900)
[error]     at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2900)
[error]     at scala.collection.immutable.List.loop$1(List.scala:170)
[error]     at scala.collection.immutable.List.mapConserve(List.scala:186)
[error]     at scala.reflect.api.Trees$Transformer.transformTrees(Trees.scala:2900)
[error]     at scala.reflect.internal.Trees$class.itransform(Trees.scala:1219)
[error]     at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
[error]     at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
[error]     at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2897)
[error]     at sbt.appmacro.ContextUtil$appTransformer$2$.transform(ContextUtil.scala:230)
[error]     at sbt.appmacro.ContextUtil.transformWrappers(ContextUtil.scala:236)
[error]     at sbt.appmacro.Instance$.contImpl(Instance.scala:183)
[error]     at sbt.std.TaskMacro$.iInitializeMacro(TaskMacro.scala:236)
[error]     at sbt.std.TaskMacro$.inputTaskMacro0(TaskMacro.scala:225)
[error]     at sbt.std.TaskMacro$.inputTaskMacroImpl(TaskMacro.scala:220)
[error]     at sbt.std.TaskMacro$.inputTaskAssignMacroImpl(TaskMacro.scala:135)
[error]     gae.requestLogs     := AppEngine.appcfgTask("request_logs", outputFile = Some("request.log")).evaluated,
[error]                         ^
[error] one error found
[error] (compile:compile) Compilation failed
[error] Total time: 36 s, completed Feb 6, 2014 10:03:54 AM
```

The line in question is:

``` scala
    gae.requestLogs     := AppEngine.appcfgTask("request_logs", outputFile = Some("request.log")).evaluated,
```
## expectation

it should compile, since it does in 0.13.1.

**Comment by cunei** [comment]
The issue appeared in the nightly 0.13.1-20131123-062316. There was only one commit on that day in the 0.13 branch, likely the cause of the regression:
https://github.com/sbt/sbt/commit/3b213e59caafdc3b28bfbaf124e80a4584caf3aa

**Comment by retronym** [comment]
Let me know if you need a hand with this one @cunei; I fixed a similar problem for Mark recently.

**Comment by retronym** [comment]
@cunei I'm pretty sure this will fix it. Would appreciate help to add an associate test case.

https://github.com/retronym/xsbt/compare/ticket;1107?expand=1

**Comment by retronym** [comment]
I just checked, this does build sbt-appengine.

Here's a minimal repro:

```
scala> import sbt._, Keys._
import sbt._
import Keys._

scala> def appcfgTask(a: String, b: String) = Def.task("")
appcfgTask: (a: String, b: String)sbt.Def.Initialize[sbt.Task[String]]

scala> TaskKey[Unit]("test") := appcfgTask(b = "", a = "").value
<console>:15: error: exception during macro expansion:
java.lang.NullPointerException
```

// After

```
scala> TaskKey[Unit]("test") := appcfgTask(b = "", a = "").value
res3: sbt.Def.Setting[sbt.Task[Unit]] = setting(ScopedKey(Scope(This,This,This,This),test)) at LinePosition(($iw) <console>,15)
```

**Comment by jsuereth** [comment]
@retronym is that commit good to go? I can make a PR if so...

**Comment by retronym** [comment]
The code is some of the best I've ever written.

If you could turn my comment about into a test and submit the PR, I'd be eternally grateful!

**Comment by jsuereth** [comment]
Sure thing. I'll leave this open in my browser, but you may need to ping me in the AM to remind me.  I'm about to turn into a Father today (less literally than you).
