### ISSUE TITLE
externalPom causes issues with plugins

### ISSUE THREAD

**Issue by JAlexoid** [sbt/sbt#1123]
Adding an external pom reference messes up the classpaths, that results in many of the plugins failing miserably.

sbt/play run and sbt/play war (with play2-war-plugin). Consistently reproducible. Configuration details are below.

_sbt run_ error:

```
java.util.NoSuchElementException: next on empty iterator
    at scala.collection.Iterator$$anon$2.next(Iterator.scala:39)
    at scala.collection.Iterator$$anon$2.next(Iterator.scala:37)
    at scala.collection.IndexedSeqLike$Elements.next(IndexedSeqLike.scala:64)
    at scala.collection.IterableLike$class.head(IterableLike.scala:91)
    at scala.collection.mutable.ArraySeq.scala$collection$IndexedSeqOptimized$$super$head(ArraySeq.scala:45)
    at scala.collection.IndexedSeqOptimized$class.head(IndexedSeqOptimized.scala:120)
    at scala.collection.mutable.ArraySeq.head(ArraySeq.scala:45)
    at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$1.apply(PlayRun.scala:220)
```

_sbt war_ error:

```
scala.reflect.internal.MissingRequirementError: object scala.runtime in compiler mirror not found.
```

_POM.xml_

``` xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <groupId>xfg.tre</groupId>
    <artifactId>webui</artifactId>
    <version>1.0-SNAPSHOT</version>
</project>
```

_build.sbt_

``` scala
import com.github.play2war.plugin._

name := """webui"""
version := "1.0-SNAPSHOT"

libraryDependencies ++= Seq(
  // Select Play modules
  //jdbc,      // The JDBC connection pool and the play.api.db API
  //anorm,     // Scala RDBMS Library
  //javaJdbc,  // Java database API
  //javaEbean, // Java Ebean plugin
  //javaJpa,   // Java JPA plugin
  //filters,   // A set of built-in filters
  javaCore,  // The core Java API
  // WebJars pull in client-side web libraries
  "org.webjars" %% "webjars-play" % "2.2.0",
  "org.webjars" % "bootstrap" % "2.3.1",
  // Add your own project dependencies in the form:
  "net.sf.extjwnl" % "extjwnl" % "1.7.1",
  "net.sf.extjwnl" % "extjwnl-data-wn31" % "1.1",
  "org.scalatest" % "scalatest_2.10" % "2.0" % "test"
)

externalPom(baseDirectory(_ / "pom.xml"))
play.Project.playScalaSettings
Play2WarPlugin.play2WarSettings
Play2WarKeys.servletVersion := "3.0"
```

_plugins.sbt_

``` scala
// Comment to get more information during initialization
logLevel := Level.Warn

// The Typesafe repository
resolvers += "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"

// Use the Play sbt plugin for Play projects
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.2.1")

addSbtPlugin("com.github.play2war" % "play2-war-plugin" % "1.2-beta4")
```

**Comment by jsuereth** [comment]
This is an interesting problem.  Play is actually using ivy's advanced "configurations" feature to grab the documentation and place it on its own configuration.  If you use an externalPom to configure a Play project, you're limited to just the maven-subset of dependency information and you're unable to depend on documentation correctly.

This is a known limitation of using external pom.  If you're going to do so, you need to be able to express all the dependencies of the project.  You're unable to do this for play.  This may require a workaround on the play side (cc @jroper), but for now I'd actually recommend against using POM's with play projects.

**Comment by JAlexoid** [comment]
@jsuereth : I understand and I use sbt for any other Play or Scala project, but this one has to integrate with a Maven based build system. Making the case against Maven is effectively making the case against Play, Scala and SBT itself. It's just not the option I can afford.

A pointer where to look for building a possible solution to using POM while still running SBT builds would be very appreciated.

**Comment by jsuereth** [comment]
you can try the sbt-pom-reader plugin which _may_ get you enough to be
dangerous, but there's still just some fundamental issues between ivy/maven.

I _think_ you could get the sbt-pom-reader to do what you need though.

You're still building with sbt right?  So, are you just using the external
pom for the dependency management section?

On Mon, Feb 17, 2014 at 12:42 PM, Aleksandr Panzin <notifications@github.com

**Comment by JAlexoid** [comment]
The POM is used for Integration tests and builds from the parent. We use SBT for day-to-day activities, but the automated continuous delivery system runs Maven. There is a parent POM that references our POM as a component and Play2 Maven plugin covers that brilliantly.

And there are a number of features(plugins) that Maven has that are killer for us, one being good integration test facility that includes embedded Cassandra.

**Comment by jsuereth** [comment]
Right.  This scenario is the reason teh sbt-pom-reader exists.  It may help out with your issues.  Obviously, we can't run those maven plugins directly.  There may be sbt-correspondents, but the main thing the pom-reader tries to do is to a more direct translation to ivy so that things like `resovlers` and `libraryDependencies` are correct in sbt.  The approach has different flaws, but it _should_ work nicer for your use case.

See: https://github.com/sbt/sbt-pom-reader/blob/master/src/main/scala/com/typesafe/sbt/pom/Plugin.scala#L9

You might be able to either follow the readme or try the "useMavenPom" settings and see how that works...

**Comment by eed3si9n** [comment]
I am closing this due to inactivity.
