### ISSUE TITLE
Print SBT version on launch failure

### ISSUE THREAD

**Issue by benhutchison** [sbt/sbt#118]
[Enhancement]:  My project is failing on launch with a problem related to #111 [https://github.com/harrah/xsbt/issues/111], yet I believe its running 10.1 where this bug is meant to be fixed. But Im struggling to confirm the SBT version...

Observe from the trace below that its not clear (to the user at least) what version of SBT actually ran. Further, there's nothing in the META-INF folder of sbt-launch.jar that tells me either, nor does "sbt-version" work from the command prompt after this error has occurred.

It would assist  debugging & error reporting if the SBT version was clearly printed (if known) whenever SBT fails to launch.

C:\Users\ben\workspace\HeroscapeMk2>java -Dfile.encoding=UTF8 -Xmx1536M -Xss1M -
XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256m -jar "C:\software\scala-2.9.0.
1\bin\sbt-launch.jar"
java.net.URISyntaxException: Illegal character in path at index 2: ..\TagTree
        at java.net.URI$Parser.fail(Unknown Source)
        at java.net.URI$Parser.checkChars(Unknown Source)
        at java.net.URI$Parser.parseHierarchical(Unknown Source)
        at java.net.URI$Parser.parse(Unknown Source)
        at java.net.URI.<init>(Unknown Source)
        at sbt.IO$.toURI(IO.scala:620)
        at sbt.RootProject$.apply(Reference.scala:32)
        at HeroscapeMk2$.tagtree(Build.scala:4)
        at HeroscapeMk2$.myApp(Build.scala:3)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sbt.ReflectUtilities$$anonfun$allValsC$1$$anonfun$apply$2.apply(Refle
ctUtilities.scala:46)
        at sbt.ReflectUtilities$$anonfun$allValsC$1$$anonfun$apply$2.apply(Refle
ctUtilities.scala:44)
        at scala.Option.foreach(Option.scala:185)
        at scala.Option$WithFilter.foreach(Option.scala:164)
        at sbt.ReflectUtilities$$anonfun$allValsC$1.apply(ReflectUtilities.scala
:44)
        at sbt.ReflectUtilities$$anonfun$allValsC$1.apply(ReflectUtilities.scala
:40)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimize
d.scala:34)
        at scala.collection.mutable.ArrayOps.foreach(ArrayOps.scala:35)
        at sbt.ReflectUtilities$.allValsC(ReflectUtilities.scala:40)
        at sbt.ReflectUtilities$.allVals(ReflectUtilities.scala:55)
        at sbt.Build$class.projects(Build.scala:20)
        at HeroscapeMk2$.projects(Build.scala:2)
        at sbt.Build$class.projectDefinitions(Build.scala:19)
        at HeroscapeMk2$.projectDefinitions(Build.scala:2)
        at sbt.Load$$anonfun$projects$1.apply(Load.scala:333)
        at sbt.Load$$anonfun$projects$1.apply(Load.scala:333)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(Traversable
Like.scala:227)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(Traversable
Like.scala:227)
        at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.
scala:61)
        at scala.collection.immutable.List.foreach(List.scala:45)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:
227)
        at scala.collection.immutable.List.flatMap(List.scala:45)
        at sbt.Load$.projects(Load.scala:333)
        at sbt.Load$.loaded(Load.scala:236)
        at sbt.Load$.loadAll(Load.scala:263)
        at sbt.Load$.loadURI(Load.scala:220)
        at sbt.Load$.load(Load.scala:216)
        at sbt.Load$.load(Load.scala:214)
        at sbt.Load$.apply(Load.scala:115)
        at sbt.Load$.defaultLoad(Load.scala:36)
        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:371)
        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:368)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.sca
la:61)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.sca
la:61)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.sca
la:63)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.sca
la:63)
        at sbt.Command$.process(Command.scala:91)
        at sbt.MainLoop$$anonfun$next$1$$anonfun$apply$1.apply(Main.scala:66)
        at sbt.MainLoop$$anonfun$next$1$$anonfun$apply$1.apply(Main.scala:66)
        at sbt.State$$anon$1.process(State.scala:59)
        at sbt.MainLoop$$anonfun$next$1.apply(Main.scala:66)
        at sbt.MainLoop$$anonfun$next$1.apply(Main.scala:66)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:13)
        at sbt.MainLoop$.next(Main.scala:66)
        at sbt.MainLoop$.run(Main.scala:61)
        at sbt.xMain.run(Main.scala:33)
        at xsbt.boot.Launch$.run(Launch.scala:54)
        at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:43)
        at xsbt.boot.Launch$.launch(Launch.scala:68)
        at xsbt.boot.Launch$.apply(Launch.scala:14)
        at xsbt.boot.Boot$.runImpl(Boot.scala:24)
        at xsbt.boot.Boot$.main(Boot.scala:15)
        at xsbt.boot.Boot.main(Boot.scala)
[error] java.net.URISyntaxException: Illegal character in path at index 2: ..\Ta
gTree
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, or (i)gnore?

**Comment by harrah** [comment]
I addressed a several things in recent commits that I think is sufficient to mark this closed:
1. There is now an `about` command that shows the sbt version, Scala versions, and the current project.  You can run this after `(i)gnoring`, since it will run ok without a project loaded.
2. The stack traces should be under better control now, so you shouldn't see that trace by default.
3. There is another option `(l)ast` when loading fails that runs `last` to see the trace.
4. Global logging is cleaned up so that `last` without arguments shows all logging output, including that of tasks.  The 'about' command also shows the temporary file where this output is written to while sbt is running.
