### ISSUE TITLE
sbt hang up for a day after installation

### ISSUE THREAD

**Issue by alartin** [sbt/sbt#1221]
Hi all,
I installed sbt-0.13.1 using homebrew on my Mac OS mavericks. I typed 'brew install sbt' and got a warning of it has been installed. The I create a simple project according to sbt website setup section. Then sbt showed loading sbt launch shell and tried to download sbt library files from maven repository. Then it was hung up for a day! Have you met this issue before? Or is there any log file I can see what happened behind? Thanks!

**Comment by jsuereth** [comment]
Is it unable to download the files?   What did the terminal show?   If you kill and restart what happens?  Are you behind a proxy?  Does sbt have write privileges to your user directory?  Does your filesystem support locking?

**Comment by alartin** [comment]
Terminal:
Getting org.scala-sbt sbt 0.13.1 ...
downloading http://repo1.maven.org/maven2/org/scala-lang/scala-library/2.10.3/scala-library-2.10.3.jar ...
sbt can write to my user dir. If I kill the process and open a new terminal and run sbt, the msg is:
Waiting for lock on /Users/xxx/.sbt/boot/sbt.boot.lock to be available...
I tried to remove all lock files and restart the sbt, it was still hung up with previous msg.
Where can I see the log? What I knew was it tried to download sbt library file from maven repo. But it should not take a long time since I can download it quickly from web browser.

**Comment by jsuereth** [comment]
Yeah, this looks like the launcher is failing to resolve sbt itself.  Something in Ivy is freezing trying to grab that jar.

Can you run jstack on the hung process and dump it here?

**Comment by alartin** [comment]
Yes:
2014-03-28 22:40:30
Full thread dump Java HotSpot(TM) 64-Bit Server VM (24.51-b03 mixed mode):

"Attach Listener" daemon prio=5 tid=0x00007fc8dd2c2000 nid=0x5a07 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Service Thread" daemon prio=5 tid=0x00007fc8dd046000 nid=0x5303 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" daemon prio=5 tid=0x00007fc8de01e000 nid=0x5103 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" daemon prio=5 tid=0x00007fc8de800000 nid=0x4f03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" daemon prio=5 tid=0x00007fc8de016000 nid=0x4d03 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" daemon prio=5 tid=0x00007fc8dd041800 nid=0x3903 in Object.wait() [0x000000010c590000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000007f9580a18> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:135)
        - locked <0x00000007f9580a18> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:151)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:189)

"Reference Handler" daemon prio=5 tid=0x00007fc8dd03e800 nid=0x3703 in Object.wait() [0x000000010c48d000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000007f9588950> (a java.lang.ref.Reference$Lock)
        at java.lang.Object.wait(Object.java:503)
        at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:133)
        - locked <0x00000007f9588950> (a java.lang.ref.Reference$Lock)

"main" prio=5 tid=0x00007fc8dc80b000 nid=0x1903 runnable [0x0000000105551000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:152)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:273)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
        - locked <0x00000007f59d6fc0> (a java.io.BufferedInputStream)
        at sun.net.www.MeteredStream.read(MeteredStream.java:134)
        - locked <0x00000007f59da5a0> (a sun.net.www.http.KeepAliveStream)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3053)
        at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3047)
        at org.apache.ivy.util.FileUtil.copy$2dc1f19f(FileUtil.java:179)
        at org.apache.ivy.util.FileUtil.copy(FileUtil.java:157)
        at org.apache.ivy.util.url.BasicURLHandler.download(BasicURLHandler.java:177)
        at org.apache.ivy.util.FileUtil.copy(FileUtil.java:146)
        at org.apache.ivy.plugins.repository.url.URLRepository.get(URLRepository.java:61)
        at org.apache.ivy.plugins.resolver.RepositoryResolver.get(RepositoryResolver.java:194)
        at org.apache.ivy.plugins.resolver.BasicResolver.getAndCheck(BasicResolver.java:978)
        at org.apache.ivy.plugins.resolver.BasicResolver$6.download(BasicResolver.java:1144)
        at org.apache.ivy.core.cache.DefaultRepositoryCacheManager.download(DefaultRepositoryCacheManager.java:884)
        at org.apache.ivy.plugins.resolver.BasicResolver.download(BasicResolver.java:835)
        at org.apache.ivy.plugins.resolver.RepositoryResolver.download(RepositoryResolver.java:282)
        at org.apache.ivy.plugins.resolver.IBiblioResolver.download(IBiblioResolver.java:508)
        at org.apache.ivy.plugins.resolver.ChainResolver.download(ChainResolver.java:219)
        at org.apache.ivy.core.resolve.ResolveEngine.downloadArtifacts(ResolveEngine.java:369)
        at org.apache.ivy.core.resolve.ResolveEngine.resolve(ResolveEngine.java:312)
        at xsbt.boot.Update.xsbt$boot$Update$$lockedApply(Update.scala:105)
        at xsbt.boot.Update$$anon$4.call(Update.scala:99)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:98)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:81)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:102)
        at xsbt.boot.Using$.withResource(Using.scala:11)
        at xsbt.boot.Using$.apply(Using.scala:10)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:62)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:52)
        - locked <0x00000007f95c6c90> (a xsbt.boot.Locks$GlobalLock)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at xsbt.boot.Update.apply(Update.scala:100)
        at xsbt.boot.Launch.update(Launch.scala:287)
        at xsbt.boot.Launch.xsbt$boot$Launch$$retrieve$1(Launch.scala:149)
        at xsbt.boot.Launch$$anonfun$3.apply(Launch.scala:157)
        at scala.Option.getOrElse(Option.scala:120)
        at xsbt.boot.Launch.xsbt$boot$Launch$$getAppProvider0(Launch.scala:157)
        at xsbt.boot.Launch$$anon$2.call(Launch.scala:142)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:98)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:81)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:102)
        at xsbt.boot.Using$.withResource(Using.scala:11)
        at xsbt.boot.Using$.apply(Using.scala:10)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:62)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:52)
        - locked <0x00000007f95c6ba0> (a xsbt.boot.Locks$GlobalLock)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at xsbt.boot.Launch.locked(Launch.scala:178)
        at xsbt.boot.Launch.app(Launch.scala:93)
        at xsbt.boot.Launch.app(Launch.scala:91)
        at xsbt.boot.Launch$.run(Launch.scala:51)
        at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
        at xsbt.boot.Launch$.launch(Launch.scala:65)
        at xsbt.boot.Launch$.apply(Launch.scala:16)
        at xsbt.boot.Boot$.runImpl(Boot.scala:32)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)

"VM Thread" prio=5 tid=0x00007fc8dd03e000 nid=0x3503 runnable 

"GC task thread#0 (ParallelGC)" prio=5 tid=0x00007fc8dc819000 nid=0x2503 runnable 

"GC task thread#1 (ParallelGC)" prio=5 tid=0x00007fc8dc819800 nid=0x2703 runnable 

"GC task thread#2 (ParallelGC)" prio=5 tid=0x00007fc8dc81a000 nid=0x2903 runnable 

"GC task thread#3 (ParallelGC)" prio=5 tid=0x00007fc8dc81b000 nid=0x2b03 runnable 

"GC task thread#4 (ParallelGC)" prio=5 tid=0x00007fc8dc81b800 nid=0x2d03 runnable 

"GC task thread#5 (ParallelGC)" prio=5 tid=0x00007fc8dc81c000 nid=0x2f03 runnable 

"GC task thread#6 (ParallelGC)" prio=5 tid=0x00007fc8dc81c800 nid=0x3103 runnable 

"GC task thread#7 (ParallelGC)" prio=5 tid=0x00007fc8dc81d800 nid=0x3303 runnable 

"VM Periodic Task Thread" prio=5 tid=0x00007fc8de003000 nid=0x5503 waiting on condition 

JNI global references: 179

**Comment by jsuereth** [comment]
Wow, I'm at a huge loss.  Somehow your download is locked by the file.

**Comment by alartin** [comment]
Similar issue in stackoverlfow:
http://stackoverflow.com/questions/17433403/my-ant-build-hangs-when-i-try-and-resolve-dependencies-using-ivy
Ivy doesn't have parameter to set timeout for dependencies resolver.
It seems something wrong with network speed.

**Comment by jsuereth** [comment]
The answer seems to imply a network proxy.  Do you have a network proxy?

**Comment by alartin** [comment]
No. But it seemed to be a network issue.

发自我的 iPhone

在 2014-3-29，上午5:05，Josh Suereth notifications@github.com 写道：

**Comment by alartin** [comment]
It is no more an issue. It turns out that the damned telecom operator block some websites (BTW, I live in China). I use a VPN to fix it.

**Comment by ourdark** [comment]
proxy is not working exactly, may I know your prox @alartin
