### ISSUE TITLE
Scala Interpreter unusable in cygwin

### ISSUE THREAD

**Issue by claudenobs** [sbt/sbt#1297]
Versions:
CYGWIN_NT-6.1 1.7.28(0.271/5/3) 2014-02-09 21:06 x86_64 Cygwin (using bundled mintty & bash)
Sbt installer 0.13.2
Java JDK 1.7.0_40

```
~/git-repos/scala/example $ sbt
[info] Loading project definition from C:\dev\git-repos\scala\example\project\project
[info] Updating {file:/C:/dev/git-repos/scala/example/project/project/}default-6b6586...
[info] Resolving org.scala-sbt#precompiled-2_10_1;0.12.4 ...
[info] Done updating.
[info] Loading project definition from C:\dev\git-repos\scala\example\project
[info] Updating {file:/C:/dev/git-repos/scala/example/project/}default-f4f609...
[info] Resolving org.scala-sbt#precompiled-2_10_1;0.12.4 ...
[info] downloading http://repo1.maven.org/maven2/net/databinder/dispatch-http_2.9.2/0.8.8/dispatch-http_2.9.2-0.8.8.jar ...
[info]  [SUCCESSFUL ] net.databinder#dispatch-http_2.9.2;0.8.8!dispatch-http_2.9.2.jar (374ms)
[info] downloading http://repo1.maven.org/maven2/org/scalastyle/scalastyle_2.9.2/0.3.2/scalastyle_2.9.2-0.3.2.jar ...
[info]  [SUCCESSFUL ] org.scalastyle#scalastyle_2.9.2;0.3.2!scalastyle_2.9.2.jar (453ms)
[info] downloading http://repo.spray.cc/cc/spray/spray-json_2.9.2/1.1.1/spray-json_2.9.2-1.1.1.jar ...
[info]  [SUCCESSFUL ] cc.spray#spray-json_2.9.2;1.1.1!spray-json_2.9.2.jar (206ms)
[info] downloading http://repo1.maven.org/maven2/org/scalatest/scalatest_2.9.2/1.9.1/scalatest_2.9.2-1.9.1.jar ...
[info]  [SUCCESSFUL ] org.scalatest#scalatest_2.9.2;1.9.1!scalatest_2.9.2.jar (829ms)
[info] downloading http://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar ...
[info]  [SUCCESSFUL ] org.apache.commons#commons-lang3;3.1!commons-lang3.jar (363ms)
[info] downloading http://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.9.2/sbt_0.12/2.1.0/jars/sbteclipse-plugin.jar ...
[info]  [SUCCESSFUL ] com.typesafe.sbteclipse#sbteclipse-plugin;2.1.0!sbteclipse-plugin.jar (421ms)
[info] downloading http://repo1.maven.org/maven2/net/databinder/dispatch-core_2.9.2/0.8.8/dispatch-core_2.9.2-0.8.8.jar ...
[info]  [SUCCESSFUL ] net.databinder#dispatch-core_2.9.2;0.8.8!dispatch-core_2.9.2.jar (393ms)
[info] downloading http://repo1.maven.org/maven2/net/databinder/dispatch-futures_2.9.2/0.8.8/dispatch-futures_2.9.2-0.8.8.jar ...
[info]  [SUCCESSFUL ] net.databinder#dispatch-futures_2.9.2;0.8.8!dispatch-futures_2.9.2.jar (348ms)
[info] downloading http://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.1.3/httpclient-4.1.3.jar ...
[info]  [SUCCESSFUL ] org.apache.httpcomponents#httpclient;4.1.3!httpclient.jar (438ms)
[info] downloading http://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.1.4/httpcore-4.1.4.jar ...
[info]  [SUCCESSFUL ] org.apache.httpcomponents#httpcore;4.1.4!httpcore.jar (351ms)
[info] downloading http://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar ...
[info]  [SUCCESSFUL ] commons-logging#commons-logging;1.1.1!commons-logging.jar (380ms)
[info] downloading http://repo1.maven.org/maven2/commons-codec/commons-codec/1.4/commons-codec-1.4.jar ...
[info]  [SUCCESSFUL ] commons-codec#commons-codec;1.4!commons-codec.jar (468ms)
[info] downloading http://repo1.maven.org/maven2/org/scalariform/scalariform_2.9.2/0.1.4/scalariform_2.9.2-0.1.4.jar ...
[info]  [SUCCESSFUL ] org.scalariform#scalariform_2.9.2;0.1.4!scalariform_2.9.2.jar (544ms)
[info] downloading http://repo1.maven.org/maven2/com/github/scopt/scopt_2.9.2/2.1.0/scopt_2.9.2-2.1.0.jar ...
[info]  [SUCCESSFUL ] com.github.scopt#scopt_2.9.2;2.1.0!scopt_2.9.2.jar (421ms)
[info] downloading http://repo1.maven.org/maven2/org/parboiled/parboiled-scala/1.0.2/parboiled-scala-1.0.2.jar ...
[info]  [SUCCESSFUL ] org.parboiled#parboiled-scala;1.0.2!parboiled-scala.jar (359ms)
[info] downloading http://repo1.maven.org/maven2/org/parboiled/parboiled-core/1.0.2/parboiled-core-1.0.2.jar ...
[info]  [SUCCESSFUL ] org.parboiled#parboiled-core;1.0.2!parboiled-core.jar (371ms)
[info] downloading http://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbteclipse/sbteclipse-core/scala_2.9.2/sbt_0.12/2.1.0/jars/sbteclipse-core.jar ...
[info]  [SUCCESSFUL ] com.typesafe.sbteclipse#sbteclipse-core;2.1.0!sbteclipse-core.jar (618ms)
[info] downloading http://repo1.maven.org/maven2/org/scalaz/scalaz-core_2.9.2/6.0.4/scalaz-core_2.9.2-6.0.4.jar ...
[info]  [SUCCESSFUL ] org.scalaz#scalaz-core_2.9.2;6.0.4!scalaz-core_2.9.2.jar (879ms)
[info] Done updating.
[info] Compiling 8 Scala sources to C:\dev\git-repos\scala\example\project\target\scala-2.9.2\sbt-0.12\classes...
[info] Set current project to progfun-example (in build file:/C:/dev/git-repos/scala/example/)
> console
Getting Scala 2.10.2 ...
downloading http://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.10.2/scala-compiler-2.10.2.jar ...
        [SUCCESSFUL ] org.scala-lang#scala-compiler;2.10.2!scala-compiler.jar (3061ms)
downloading http://repo1.maven.org/maven2/org/scala-lang/scala-library/2.10.2/scala-library-2.10.2.jar ...
        [SUCCESSFUL ] org.scala-lang#scala-library;2.10.2!scala-library.jar (2606ms)
downloading http://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.10.2/scala-reflect-2.10.2.jar ...
        [SUCCESSFUL ] org.scala-lang#scala-reflect;2.10.2!scala-reflect.jar (952ms)
downloading http://repo1.maven.org/maven2/org/scala-lang/jline/2.10.2/jline-2.10.2.jar ...
        [SUCCESSFUL ] org.scala-lang#jline;2.10.2!jline.jar (368ms)
:: retrieving :: org.scala-sbt#boot-scala
        confs: [default]
        5 artifacts copied, 0 already retrieved (24390kB/183ms)
[info] Updating {file:/C:/dev/git-repos/scala/example/}assignment...
[info] Resolving org.hamcrest#hamcrest-parent;1.1 ...
[info] downloading http://repo1.maven.org/maven2/org/scalacheck/scalacheck_2.10/1.10.1/scalacheck_2.10-1.10.1.jar ...
[info]  [SUCCESSFUL ] org.scalacheck#scalacheck_2.10;1.10.1!scalacheck_2.10.jar (517ms)
[info] downloading http://repo1.maven.org/maven2/com/netflix/rxjava/rxjava-scala/0.15.0/rxjava-scala-0.15.0.jar ...
[info]  [SUCCESSFUL ] com.netflix.rxjava#rxjava-scala;0.15.0!rxjava-scala.jar (393ms)
[info] downloading http://repo1.maven.org/maven2/org/json4s/json4s-native_2.10/3.2.5/json4s-native_2.10-3.2.5.jar ...
[info]  [SUCCESSFUL ] org.json4s#json4s-native_2.10;3.2.5!json4s-native_2.10.jar (486ms)
[info] downloading http://repo1.maven.org/maven2/org/scala-lang/scala-swing/2.10.3/scala-swing-2.10.3.jar ...
[info]  [SUCCESSFUL ] org.scala-lang#scala-swing;2.10.3!scala-swing.jar (445ms)
[info] downloading http://repo1.maven.org/maven2/net/databinder/dispatch/dispatch-core_2.10/0.11.0/dispatch-core_2.10-0.11.0.jar ...
[info]  [SUCCESSFUL ] net.databinder.dispatch#dispatch-core_2.10;0.11.0!dispatch-core_2.10.jar (421ms)
[info] downloading http://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar ...
[info]  [SUCCESSFUL ] org.slf4j#slf4j-api;1.7.5!slf4j-api.jar (355ms)
[info] downloading http://repo1.maven.org/maven2/org/slf4j/slf4j-simple/1.7.5/slf4j-simple-1.7.5.jar ...
[info]  [SUCCESSFUL ] org.slf4j#slf4j-simple;1.7.5!slf4j-simple.jar (336ms)
[info] downloading http://repo1.maven.org/maven2/com/squareup/retrofit/retrofit/1.0.0/retrofit-1.0.0.jar ...
[info]  [SUCCESSFUL ] com.squareup.retrofit#retrofit;1.0.0!retrofit.jar (327ms)
[info] downloading http://repo1.maven.org/maven2/org/scala-lang/modules/scala-async_2.10/0.9.0-M2/scala-async_2.10-0.9.0-M2.jar ...
[info]  [SUCCESSFUL ] org.scala-lang.modules#scala-async_2.10;0.9.0-M2!scala-async_2.10.jar(bundle) (620ms)
[info] downloading http://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.10/2.2.3/akka-actor_2.10-2.2.3.jar ...
[info]  [SUCCESSFUL ] com.typesafe.akka#akka-actor_2.10;2.2.3!akka-actor_2.10.jar (1040ms)
[info] downloading http://repo1.maven.org/maven2/com/typesafe/akka/akka-testkit_2.10/2.2.3/akka-testkit_2.10-2.2.3.jar ...
[info]  [SUCCESSFUL ] com.typesafe.akka#akka-testkit_2.10;2.2.3!akka-testkit_2.10.jar(bundle) (370ms)
[info] downloading http://repo1.maven.org/maven2/org/scala-lang/scala-actors/2.10.1/scala-actors-2.10.1.jar ...
[info]  [SUCCESSFUL ] org.scala-lang#scala-actors;2.10.1!scala-actors.jar (449ms)
[info] downloading http://repo1.maven.org/maven2/com/netflix/rxjava/rxjava-core/0.15.0/rxjava-core-0.15.0.jar ...
[info]  [SUCCESSFUL ] com.netflix.rxjava#rxjava-core;0.15.0!rxjava-core.jar (411ms)
[info] downloading http://repo1.maven.org/maven2/org/json4s/json4s-core_2.10/3.2.5/json4s-core_2.10-3.2.5.jar ...
[info]  [SUCCESSFUL ] org.json4s#json4s-core_2.10;3.2.5!json4s-core_2.10.jar (423ms)
[info] downloading http://repo1.maven.org/maven2/org/json4s/json4s-ast_2.10/3.2.5/json4s-ast_2.10-3.2.5.jar ...
[info]  [SUCCESSFUL ] org.json4s#json4s-ast_2.10;3.2.5!json4s-ast_2.10.jar (325ms)
[info] downloading http://repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/2.5.6/paranamer-2.5.6.jar ...
[info]  [SUCCESSFUL ] com.thoughtworks.paranamer#paranamer;2.5.6!paranamer.jar (455ms)
[info] downloading http://repo1.maven.org/maven2/org/scala-lang/scalap/2.10.0/scalap-2.10.0.jar ...
[info]  [SUCCESSFUL ] org.scala-lang#scalap;2.10.0!scalap.jar (495ms)
[info] downloading http://repo1.maven.org/maven2/org/mockito/mockito-all/1.9.0/mockito-all-1.9.0.jar ...
[info]  [SUCCESSFUL ] org.mockito#mockito-all;1.9.0!mockito-all.jar (538ms)
[info] downloading http://repo1.maven.org/maven2/com/ning/async-http-client/1.7.16/async-http-client-1.7.16.jar ...
[info]  [SUCCESSFUL ] com.ning#async-http-client;1.7.16!async-http-client.jar (378ms)
[info] downloading http://repo1.maven.org/maven2/io/netty/netty/3.6.3.Final/netty-3.6.3.Final.jar ...
[info]  [SUCCESSFUL ] io.netty#netty;3.6.3.Final!netty.jar(bundle) (443ms)
[info] downloading http://repo1.maven.org/maven2/com/google/code/gson/gson/2.2.3/gson-2.2.3.jar ...
[info]  [SUCCESSFUL ] com.google.code.gson#gson;2.2.3!gson.jar (319ms)
[info] downloading http://repo1.maven.org/maven2/com/typesafe/config/1.0.2/config-1.0.2.jar ...
[info]  [SUCCESSFUL ] com.typesafe#config;1.0.2!config.jar(bundle) (489ms)
[info] downloading http://repo1.maven.org/maven2/org/scalatest/scalatest_2.10/1.9.1/scalatest_2.10-1.9.1.jar ...
[info]  [SUCCESSFUL ] org.scalatest#scalatest_2.10;1.9.1!scalatest_2.10.jar (2090ms)
[info] downloading http://repo1.maven.org/maven2/junit/junit/4.10/junit-4.10.jar ...
[info]  [SUCCESSFUL ] junit#junit;4.10!junit.jar (404ms)
[info] downloading http://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1.jar ...
[info]  [SUCCESSFUL ] org.hamcrest#hamcrest-core;1.1!hamcrest-core.jar (449ms)
[info] Done updating.
[info] Compiling 2 Scala sources to C:\dev\git-repos\scala\example\target\scala-2.10\classes...
[info] 'compiler-interface' not yet compiled for Scala 2.10.2. Compiling...
[info]   Compilation completed in 11.839 s
[info] Starting scala interpreter...
[info]
[ERROR] Failed to construct terminal; falling back to unsupportedjava.lang.IllegalArgumentException: Invalid terminal type: jline.UnixTerminal
        at scala.tools.jline.TerminalFactory.create(TerminalFactory.java:83)
        at scala.tools.jline.TerminalFactory.get(TerminalFactory.java:154)
        at scala.tools.jline.console.ConsoleReader.<init>(ConsoleReader.java:87)
        at scala.tools.jline.console.ConsoleReader.<init>(ConsoleReader.java:134)
        at scala.tools.nsc.interpreter.JLineReader$JLineConsoleReader.<init>(JLineReader.scala:39)
        at scala.tools.nsc.interpreter.JLineReader.<init>(JLineReader.scala:21)
        at scala.tools.nsc.interpreter.ILoop.chooseReader(ILoop.scala:812)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:831)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:822)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:822)
        at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
        at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:822)
        at scala.tools.nsc.interpreter.ILoop.main(ILoop.scala:889)
        at xsbt.ConsoleInterface.run(ConsoleInterface.scala:57)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:73)
        at sbt.compiler.AnalyzingCompiler.console(AnalyzingCompiler.scala:64)
        at sbt.Console.console0$1(Console.scala:23)
        at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply$mcV$sp(Console.scala:24)
        at sbt.TrapExit$.executeMain$1(TrapExit.scala:33)
        at sbt.TrapExit$$anon$1.run(TrapExit.scala:42)
Caused by: java.lang.ClassNotFoundException: jline.UnixTerminal
        at scala.tools.nsc.interpreter.AbstractFileClassLoader.findClass(AbstractFileClassLoader.scala:69)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at scala.tools.jline.TerminalFactory.create(TerminalFactory.java:80)
        ... 23 more

Welcome to Scala version 2.10.2 (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_40).
Type in expressions to have them evaluated.
Type :help for more information.

scala>
```

**Comment by jsuereth** [comment]
Yet another issue with Jline version incompatibilities.   Scala shades jline and doesn't accept the appropriate flags for configuration.  

You're using the sbt 0.13.2 msi?  If so, you may need to actually use cmd.exe to work around this, or bump the version of Scala.   When scala was still using shaded jline, there was no possible way to get both the sbt console + the scala console working together (Jline 2.x), at least that I found. 

Patches welcome, of course, but please try one of the newer scala versions and see if that helps fix the issue (by using the same jline lib).

**Comment by claudenobs** [comment]
yeah cmd.exe works fine. but suggesting using cmd.exe feels like go back and redo your multi million loc software project in assembler... so thanks but no thanks. :)

well i'm just starting with scala (actually this is a project from an online course, and looking at the output of sbt it seems to config scala to 2.10.1 & sbt to 0.12.4... not sure though)

however running `eval System.setProperty("jline.terminal", "scala.tools.jline.UnixTerminal")` before `console` fixes things... :+1: 
can't sbt detect it's running inside cygwin and just execute this at sbt startup? while it's now fine it's a bit cumbersome havaing to paste this each time after invoking sbt...

**Comment by claudenobs** [comment]
yes this is using the 0.13.2 msi

**Comment by jsuereth** [comment]
"Detect it's running inside cygwin"  A: "One does not simply walk into mordor".

Actually, that's not a bad idea.  We already have some detection in various places.  The issue with doing it automatically is that not all terminals (for windows) are created equal.  Still, a patch around that would be more than welcome.

**Comment by jsuereth** [comment]
So according to that report, you're using sbt version `0.12.4`.  THe sbt launcher may be on `0.13.2` but if your `project/build.properties` has a different version, we'll automatically downgrade.

Unfortunately, due to Jline versioning hell, 0.12.4 and scala 2.10+ are incompatible in cygwin.  We tried for like two weeks to figure out how to make it work, but to no avail.   If you upgrade the project to use sbt 0.13.0+ then it should start working.

Note: The sbt launcher just resolves + starts sbt.  It's version number is important, but not the same as what's used in your project.

PLease reopen if you experience issues with sbt 0.13.2 + cygwin.

**Comment by claudenobs** [comment]
interesting thanks. will try sometime with 0.13.2 :)
