### ISSUE TITLE
Extracting a constant into a private val results in AbstractMethodError

### ISSUE THREAD

**Issue by igorkarp** [sbt/sbt#1298]
Here are the steps to reproduce, standalone but not necessarily minimal.

Create a simple project

```
mkdir sbttest
cd sbttest
mkdir -p src/main/scala
mkdir -p src/test/scala
echo "trait Prod { def x = 1 }" > src/main/scala/Prod.scala
echo "object Test extends Prod {}" > src/main/scala/Test.scala
echo "object TestRunner { def main(args: Array[String]) { println(Test.x) } }" > src/main/scala/TestRunner.scala
sbt "run test/TestRunner"
```

```
[info] Set current project to sbttest (in build file:/Users/igorkarp/sbttest/)
[info] Updating {file:/Users/igorkarp/sbttest/}sbttest...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 3 Scala sources to /Users/igorkarp/sbttest/target/scala-2.10/classes...
[info] Running TestRunner test/TestRunner
1
[success] Total time: 3 s, completed Apr 28, 2014 10:18:58 PM
```

Than extract a constant

If one extracts a constant into a private val this will result in AbstractMethodError. Note that only one class is recompiled.

```
echo "trait Prod { private val y = 1; def x = y }" > src/main/scala/Prod.scala
sbt "run test/TestRunner"
```

```
[info] Set current project to sbttest (in build file:/Users/igorkarp/sbttest/)
[info] Compiling 1 Scala source to /Users/igorkarp/sbttest/target/scala-2.10/classes...
[info] Running TestRunner test/TestRunner
[error] (run-main) java.lang.AbstractMethodError: Test$.Prod$_setter_$Prod$$y_$eq(I)V
java.lang.AbstractMethodError: Test$.Prod$_setter_$Prod$$y_$eq(I)V
    at Prod$class.$init$(Prod.scala:1)
    at Test$.<init>(Test.scala:1)
    at Test$.<clinit>(Test.scala)
    at TestRunner$.main(TestRunner.scala:1)
    at TestRunner.main(TestRunner.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
```

Changing private val to public does cause recompilation.

```
echo "trait Prod { val y = 1; def x = y }" > src/main/scala/Prod.scala
sbt "run test/TestRunner"
```

```
[info] Set current project to sbttest (in build file:/Users/igorkarp/sbttest/)
[info] Compiling 1 Scala source to /Users/igorkarp/sbttest/target/scala-2.10/classes...
[info] Compiling 3 Scala sources to /Users/igorkarp/sbttest/target/scala-2.10/classes...
[info] Running TestRunner test/TestRunner
1
[success] Total time: 3 s, completed Apr 28, 2014 10:27:20 PM
```

SBT Version information

```
sbt sbtVersion
[info] Set current project to sbttest (in build file:/Users/igorkarp/sbttest/)
[info] 0.13.0
```

```
sbt scalaVersion
[info] Set current project to sbttest (in build file:/Users/igorkarp/sbttest/)
[info] 2.10.2
```

**Comment by dwijnand** [comment]
Still present in sbt 0.13.8 and Scala 2.11.7.

**Comment by jozanek** [comment]
This no longer reproduces. The incremental compiler gained a dedicated rule for this case, and the scenario from the original report now recompiles correctly.

I ran the exact steps from the description across:

| sbt | Scala | Result |
|---|---|---|
| 1.11.7 | 2.12.20 | ✅ prints `1` |
| 1.11.7 | 2.13.16 | ✅ |
| 1.11.7 | 3.3.6 | ✅ |
| 2.0.8 | 3.8.4 | ✅ |
| 1.11.7 | 2.13.16, split across two subprojects (`b.dependsOn(a)`) | ✅ |

In each case the `run` after the edit does two compile rounds — `Prod.scala`, then `Test.scala` — rather than the single round that produced the `AbstractMethodError`.

The invalidation is deliberate, from the zinc debug log:

```
Change TraitPrivateMembersModified(Prod) invalidates 2 classes due to
  The private signature of trait Prod changed.
  > by transitive inheritance: Set(Prod, Test)
```

`AnalyzedClass` carries an `extraHash` covering private members alongside the public API hash. When the public API is unchanged but `extraHash` differs and both sides are traits, [`IncrementalNameHashing.findAPIChange`](https://github.com/sbt/zinc/blob/develop/internal/zinc-core/src/main/scala/sbt/internal/inc/IncrementalNameHashing.scala#L71) emits `TraitPrivateMembersModified`, which invalidates by transitive inheritance only — which is the right scope, since a trait's private val is part of the mixin ABI for implementers (`Prod$_setter_$Prod$$y_$eq`) but invisible to call sites.

Fixed by sbt/zinc@7956abaf ("Include private members in API hash of traits") and refined in sbt/zinc#542, with a regression test at `zinc/src/sbt-test/source-dependencies/trait-private-val` covering this exact scenario.

@eed3si9n this looks closeable — anything you'd want verified first?

**Comment by eed3si9n** [comment]
All good. Thanks!
