### ISSUE TITLE
Changing Java interface into abstract class should trigger recompilation of (scala) implementors

### ISSUE THREAD

**Issue by jrudolph** [sbt/sbt#1327]
Reproduction: https://github.com/jrudolph/java-interface-inc-compilation-fail

**Comment by jrudolph** [comment]
The gist of it:

A.java:

``` java
public interface A { // change this to `abstract class` to see the compile failure
    public static final A x = new B();
}
```

B.scala

``` scala
class B extends A
```

When `A` is changed from `interface` to `abstract class` just A is recompiled and the compilation instantly fails with 

```
inc-compilation/src/main/java/A.java:2: error: incompatible types
    public static final A x = new B();
                              ^
  required: A
  found:    B
1 error
```

Instead, both A.java and B.scala should be compiled jointly on the first try.

**Comment by gkossakowski** [comment]
The issue here is that you have a cycle of dependencies between `A.java` and `B.scala` and we don't perform cycle detection during initial invalidation. This issue can be reproduced in pure Scala:

``` scala
// A.scala
abstract class A { // change to to trait and watch scalac crash
  def x = new B
}

// B.scala
class B extends A
```

The change from `trait` to `abstract class` crashes Scala compiler:

```
java.lang.AssertionError: assertion failed: 
     while compiling: /Users/grek/tmp/sbt-name-hashing/A.scala
        during phase: global=jvm, atPhase=erasure
     library version: version 2.10.4
    compiler version: version 2.10.4
[...]
    at scala.tools.nsc.transform.AddInterfaces.transformMixinInfo(AddInterfaces.scala:213)
    at scala.tools.nsc.transform.Erasure.transformInfo(Erasure.scala:329)
    at scala.tools.nsc.transform.InfoTransform$Phase$$anon$1.transform(InfoTransform.scala:38)
    at scala.reflect.internal.Symbols$Symbol.rawInfo(Symbols.scala:1321)
    at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1241)
    at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder.genCallMethod$1(GenASM.scala:2286)
    at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder.genMethodsInstr$1(GenASM.scala:2502)
    at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder.scala$tools$nsc$backend$jvm$GenASM$JPlainBuilder$$genInstr$1(GenASM.scala:2505)
    at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder$$anonfun$genBlock$1$2.apply(GenASM.scala:2352)
    at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder$$anonfun$genBlock$1$2.apply(GenASM.scala:2338)
```

**Comment by jrudolph** [comment]
I see, thanks for the explanation, @gkossakowski.

**Comment by jozanek** [comment]
Still reproduces on sbt 2.0.8 (zinc 2.0.4) and sbt 1.11.7 (zinc 1.11.0) with Scala 3.7.4, and @gkossakowski's 2014 diagnosis still matches: cycle 1 invalidates `A.java` alone, so `scalaSrcs` is empty, javac runs by itself against the stale `B.class` and throws — aborting the loop before the cycle that would detect the `Trait` -> `ClassDef` change and invalidate `B`. Breaking the `A` -> `B` -> `A` cycle makes the same edit work.

Since the incremental compiler now lives in sbt/zinc, I've re-filed it there with a current reproduction: sbt/zinc#1811. Suggest closing this one in favour of that.

(While confirming, I also ran into a silent variant that needs no cycle: with Scala 3 and the Java class in the default package, the implementor is never invalidated and the build reports `[success]` while leaving unloadable classfiles — sbt/zinc#1812.)
