### ISSUE TITLE
Classloader conflict between local and global plugins

### ISSUE THREAD

**Issue by hseeberger** [sbt/sbt#1428]
This issue occurs for sbt 0.13.5 and 0.13.6-MERVER-4. To reproduce it, create an otherwise empty project with the following `project/plugins.sbt`:

```
addSbtPlugin("com.typesafe.sbt" % "sbt-ghpages" % "0.5.2")
```

Then add the following line to your global plugin configuration `~/.sbt/0.13/plugins/plugins.sbt`:

```
addSbtPlugin("name.heikoseeberger" % "sbt-groll" % "3.1.4")
```

Then start sbt and you will get the following:

```
java.lang.NoClassDefFoundError: org/eclipse/jgit/storage/file/FileRepository
    at com.typesafe.sbt.git.DefaultReadableGit.<init>(ReadableGit.scala:23)
    at com.typesafe.sbt.SbtGit$$anonfun$4.apply(SbtGit.scala:78)
    at com.typesafe.sbt.SbtGit$$anonfun$4.apply(SbtGit.scala:78)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:177)
    at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
    at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:67)
    at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:76)
    at sbt.EvaluateSettings$$anon$3.run(INode.scala:72)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jgit.storage.file.FileRepository
...
```

For me it looks like the two plugins depend on different versions of JGit and there's no proper classloader isolation in place.

**Comment by dansanduleac** [comment]
That has been a problem for a while (since `0.13.0` inclusively, I believe). I've fixed this in #1352 but it didn't make it into `0.13.5`, unfortunately.

Edit: I see this particular issue is still a problem, I'll look into why that is. Are you sure these two plugins are meant to work together?

**Comment by dansanduleac** [comment]
Ok - after some investigation, this has nothing to do with sbt, and is instead about incompatible dependencies, as I suspected.

I see that `sbt-ghpages 0.5.2` brings in `sbt-git 0.6.1` which brings in `org.eclipse.jgit#org.eclipse.jgit.pgm;2.2.0.201212191850-r` which depends on `org.eclipse.jgit#org.eclipse.jgit;2.2.0.201212191850-r`. 
At the same time, `sbt-groll 3.1.4` has a dependency on a newer jgit, specifically `org.eclipse.jgit#org.eclipse.jgit;3.3.2.201404171909-r`. 
Therefore using the default ivy conflict manager of `latest-revision`, version `3.3.2.201404171909-r` of jgit will be chosen to be on the classpath. If you look inside that jar, you see that indeed, the class in your error message does not exist, because it has been moved to `org.eclipse.jgit.`**`internal`**`.storage.file.FileRepository`.
Therefore at this point we know that _sbt-jhpages 0.5.2 is incompatible with jgit 3.x_.

You could try to:
- use a version of `sbt-jhpages` that depends on a newer jgit (v3.x)
- add a dependency override for the older version of jgit, and hope that your other plugin (sbt-groll) is compatible with that, something like:

```
dependencyOverrides += "org.eclipse.jgit" % "org.eclipse.jgit" % "2.2.0.201212191850-r"
```

Edit: fixed references that should have said `sbt-ghpages`.

**Comment by hseeberger** [comment]
Thanks @dansanduleac. I have created a PR against gh-pages.

**Comment by hseeberger** [comment]
This can be closed.

**Comment by hedefalk** [comment]
Had the same issue with sbt-git 0.6.2 and sbt 13.5. Didn't find much info so I don't know what pulled in the conflict. But found this issue and it seemed reasonable to just up sbt-git to 0.8.0 which worked. Thanks.
