### ISSUE TITLE
plugins.JvmPlugin cannot be disabled

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#1434]
## steps

```
$ cat project/build.properties 
sbt.version=0.13.5
$ cat build.sbt 
lazy val root = (project in file(".")).
  disablePlugins(plugins.JvmPlugin)
$ mkdir global
$ java -XX:MaxPermSize=512M -Dfile.encoding=UTF-8 -Dsbt.global.base=global -jar "$HOME/.conscript/sbt-launch.jar"  
```
## problem

```
$ java -XX:MaxPermSize=512M -Dfile.encoding=UTF-8 -Dsbt.global.base=global -jar "$HOME/.conscript/sbt-launch.jar"          
References to undefined settings: 

  *:scalaVersion from *:update ((sbt.Classpaths) Defaults.scala:1089)

  *:update::scalaBinaryVersion from *:projectId ((sbt.Classpaths) Defaults.scala:1068)

  *:target from *:ivyConfiguration ((sbt.Classpaths) Defaults.scala:1072)

  *:update::scalaVersion from *:ivyScala ((sbt.Classpaths) Defaults.scala:1061)

  *:update::scalaBinaryVersion from *:ivyScala ((sbt.Classpaths) Defaults.scala:1061)

  *:crossTarget from *:deliverLocalConfiguration ((sbt.Classpaths) Defaults.scala:1081)

  *:updateSbtClassifiers::target from *:updateSbtClassifiers::ivyConfiguration ((sbt.Classpaths) Defaults.scala:1151)

  *:crossTarget from *:makePom::artifactPath ((sbt.Classpaths) Defaults.scala:1064)

  *:artifactName::scalaVersion from *:makePom::artifactPath ((sbt.Classpaths) Defaults.scala:1064)

  *:artifactName::scalaBinaryVersion from *:makePom::artifactPath ((sbt.Classpaths) Defaults.scala:1064)

  *:artifactName from *:makePom::artifactPath ((sbt.Classpaths) Defaults.scala:1064)

        at sbt.Init$class.Uninitialized(Settings.scala:260)
        at sbt.Def$.Uninitialized(Def.scala:10)
        at sbt.Init$class.delegate(Settings.scala:184)
        at sbt.Def$.delegate(Def.scala:10)
        at sbt.Init$class.compiled(Settings.scala:135)
        at sbt.Def$.compiled(Def.scala:10)
        at sbt.Init$class.make(Settings.scala:141)
        at sbt.Def$.make(Def.scala:10)
        at sbt.Load$.apply(Load.scala:139)
        at sbt.Load$.defaultLoad(Load.scala:37)
        at sbt.BuiltinCommands$.doLoadProject(Main.scala:473)
        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:467)
        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:467)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:60)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:60)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:62)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:62)
        at sbt.Command$.process(Command.scala:95)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:100)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:100)
        at sbt.State$$anon$1.process(State.scala:179)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:100)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:100)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
        at sbt.MainLoop$.next(MainLoop.scala:100)
        at sbt.MainLoop$.run(MainLoop.scala:93)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:71)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:66)
        at sbt.Using.apply(Using.scala:25)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:66)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:49)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:33)
        at sbt.MainLoop$.runLogged(MainLoop.scala:25)
        at sbt.StandardMain$.runManaged(Main.scala:57)
        at sbt.xMain.run(Main.scala:29)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:57)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:77)
        at xsbt.boot.Launch$.run(Launch.scala:57)
        at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
        at xsbt.boot.Launch$.launch(Launch.scala:65)
        at xsbt.boot.Launch$.apply(Launch.scala:16)
        at xsbt.boot.Boot$.runImpl(Boot.scala:32)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)
```
## expectation

I can disable `JvmPlugin` if I don't need it.
## note

``` scala
    updateCacheName := "update_cache" + (if (crossPaths.value) s"_${scalaBinaryVersion.value}" else ""),
```

**Comment by jsuereth** [comment]
Good catch.  We should add a pending scripted test for disabling plugins in
the main build....

**Comment by eed3si9n** [comment]
I haven't chased down the reason precisely, but if `updateCacheName` containing `crossPaths` is the reason, that's legitimate. I guess we could introduce Scala specific optimizations in `JvmPlugin`.
