### ISSUE TITLE
OutOfMemoryError if running sbt from the root directory

### ISSUE THREAD

**Issue by ghost** [sbt/sbt#1458]
On a Linux machine, using sbt 0.3.15:

cd /  (yes, the root)
sbt about

```
java.lang.OutOfMemoryError: GC overhead limit exceeded
  at java.io.UnixFileSystem.resolve(UnixFileSystem.java:108)
  at java.io.File.<init>(File.java:262)
  at java.io.File.listFiles(File.java:1284)
  at sbt.FilterFiles.handleFile(Path.scala:182)
  at sbt.DescendantOrSelfPathFinder.sbt$DescendantOrSelfPathFinder$$handleFileDescendant(Path.scala:198)
  at sbt.DescendantOrSelfPathFinder$$anonfun$sbt$DescendantOrSelfPathFinder$$handleFileDescendant$1.apply(Path.scala:200)
  at sbt.DescendantOrSelfPathFinder$$anonfun$sbt$DescendantOrSelfPathFinder$$handleFileDescendant$1.apply(Path.scala:199)
  at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
  at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
  at sbt.DescendantOrSelfPathFinder.sbt$DescendantOrSelfPathFinder$$handleFileDescendant(Path.scala:199)
  at sbt.DescendantOrSelfPathFinder$$anonfun$sbt$DescendantOrSelfPathFinder$$handleFileDescendant$1.apply(Path.scala:200)
  at sbt.DescendantOrSelfPathFinder$$anonfun$sbt$DescendantOrSelfPathFinder$$handleFileDescendant$1.apply(Path.scala:199)
  at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
  at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
  at sbt.DescendantOrSelfPathFinder.sbt$DescendantOrSelfPathFinder$$handleFileDescendant(Path.scala:199)
  at sbt.DescendantOrSelfPathFinder$$anonfun$sbt$DescendantOrSelfPathFinder$$handleFileDescendant$1.apply(Path.scala:200)
  at sbt.DescendantOrSelfPathFinder$$anonfun$sbt$DescendantOrSelfPathFinder$$handleFileDescendant$1.apply(Path.scala:199)
  at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
  at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
  at sbt.DescendantOrSelfPathFinder.sbt$DescendantOrSelfPathFinder$$handleFileDescendant(Path.scala:199)
  at 
....
```

**Comment by jsuereth** [comment]
Looks like our "eager" File => Seq[File] is blowing up your memory.  Not sure how @eed3si9n feels, but this may be a won't fix.

Can you give us a reason why you're running in the root directory?

**Comment by ghost** [comment]
No good reason. I just happened to be in the wrong directory at the wrong time and I figured I'd report it as I searched for similar known issues and didn't find anything.

**Comment by jsuereth** [comment]
Yeah, I'm thinking this may be a "wontfix". for now, but it is an issue that we search all files recursively and load that datastructure into memory.   Maybe @eed3si9n and I need to chat about the Path.get api...

**Comment by som-snytt** [comment]
FWIW, the usability issue where oops, I'm in the wrong directory when I run sbt, bites me all the time. Usually, I intend a quick `sbt console` session.

**Comment by dwijnand** [comment]
Is this "wontfix" then?

**Comment by eed3si9n** [comment]
I am not compelled to fix it right away, but I'd be open to a fix from the community.

**Comment by alienscience** [comment]
I am sorry to do a +1 on this, but I lost several hours setting up a Docker container because the Docker 'RUN' command defaults to the '/' directory and sbt proceeded to run out of memory. I was just trying to initialize _sbt_ by running:

```bash
$ sbt exit
```

Something simple like:
```scala
if (directory == "/") {
   throw new IllegalStateException("Cannot run sbt from root directory")    
}
```
would have have saved a lot of trouble.

**Comment by eed3si9n** [comment]
How about this.

1. By default sbt checks if it's at `/`, and exits with the error message.
2. If you really want to run it from `/` you need to pass in some JVM flag.

The error message is:

```
Are you sure you want to run sbt from the root directory?
If you want to run `sbt -Dsbt.root=true`
```

**Comment by eed3si9n** [comment]
using sbt 1.2.8:

```
[warn] No sbt.version set in project/build.properties, base directory: /
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.base/sun.nio.fs.UnixPath.resolve(UnixPath.java:400)
	at java.base/sun.nio.fs.UnixPath.resolve(UnixPath.java:413)
	at java.base/sun.nio.fs.UnixPath.resolve(UnixPath.java:418)
	at java.base/sun.nio.fs.UnixDirectoryStream$UnixDirectoryIterator.readNextEntry(UnixDirectoryStream.java:182)
	at java.base/sun.nio.fs.UnixDirectoryStream$UnixDirectoryIterator.hasNext(UnixDirectoryStream.java:198)
	at java.base/java.nio.file.FileTreeWalker.next(FileTreeWalker.java:348)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2760)
	at sbt.io.DescendantOrSelfPathFinder.handleFileDescendant(Path.scala:456)
	at sbt.io.DescendantOrSelfPathFinder.$anonfun$addTo$1(Path.scala:447)
	at sbt.io.DescendantOrSelfPathFinder.$anonfun$addTo$1$adapted(Path.scala:445)
	at sbt.io.DescendantOrSelfPathFinder$$Lambda$733/0x000000010070b840.apply(Unknown Source)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:58)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:51)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at sbt.io.DescendantOrSelfPathFinder.addTo(Path.scala:445)
	at sbt.io.PathFinder.get(Path.scala:390)
	at sbt.io.PathFinder.pair(Path.scala:370)
	at sbt.io.IO$.copyDirectory(IO.scala:799)
	at sbt.io.IO$.copyDirectory(IO.scala:789)
	at sbt.io.IO$.copyDirectory(IO.scala:772)
	at sbt.Resolvers$.$anonfun$local$3(Resolvers.scala:34)
	at sbt.Resolvers$$$Lambda$729/0x0000000100708440.apply$mcV$sp(Unknown Source)
	at sbt.Resolvers$.creates(Resolvers.scala:148)
	at sbt.Resolvers$.$anonfun$local$2(Resolvers.scala:34)
	at sbt.Resolvers$$$Lambda$726/0x0000000100707040.apply(Unknown Source)
	at sbt.internal.BuildLoader$.$anonfun$componentLoader$2(BuildLoader.scala:172)
	at sbt.internal.BuildLoader$$$Lambda$728/0x0000000100708840.apply(Unknown Source)
	at scala.Option.map(Option.scala:146)
	at sbt.internal.BuildLoader$.$anonfun$componentLoader$1(BuildLoader.scala:171)
	at sbt.internal.BuildLoader$$$Lambda$709/0x00000001006fc040.apply(Unknown Source)
	at sbt.internal.MultiHandler.apply(BuildLoader.scala:28)
	at sbt.internal.BuildLoader.apply(BuildLoader.scala:240)
Error during sbt execution: java.lang.OutOfMemoryError: GC overhead limit exceeded
```

using sbt 1.3.2:

```
[warn] No sbt.version set in project/build.properties, base directory: /
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOfRange(Arrays.java:4030)
	at java.base/java.lang.StringCoding.decodeASCII(StringCoding.java:524)
	at java.base/java.lang.StringCoding.decode(StringCoding.java:257)
	at java.base/java.lang.String.<init>(String.java:507)
	at java.base/java.lang.String.<init>(String.java:561)
	at java.base/sun.nio.fs.Util.toString(Util.java:63)
	at java.base/sun.nio.fs.UnixPath.toString(UnixPath.java:788)
	at java.base/sun.nio.fs.UnixPath.getPathForPermissionCheck(UnixPath.java:189)
	at java.base/sun.nio.fs.UnixPath.checkRead(UnixPath.java:818)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:49)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:145)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.base/java.nio.file.FileTreeWalker.next(FileTreeWalker.java:373)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2760)
	at sbt.io.DescendantOrSelfPathFinder$.default(Path.scala:684)
	at sbt.io.Path$.$anonfun$defaultDescendantHandler$3(Path.scala:312)
	at sbt.io.Path$.$anonfun$defaultDescendantHandler$3$adapted(Path.scala:312)
	at sbt.io.Path$$$Lambda$71/0x0000000100381440.apply(Unknown Source)
	at sbt.io.DescendantOrSelfPathFinder$$anonfun$$lessinit$greater$1.apply(Path.scala:648)
	at sbt.io.DescendantOrSelfPathFinder$$anonfun$$lessinit$greater$1.apply(Path.scala:648)
	at sbt.io.DescendantOrSelfPathFinder.$anonfun$addTo$1(Path.scala:652)
	at sbt.io.DescendantOrSelfPathFinder.$anonfun$addTo$1$adapted(Path.scala:650)
	at sbt.io.DescendantOrSelfPathFinder$$Lambda$1091/0x0000000100a17040.apply(Unknown Source)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at sbt.io.DescendantOrSelfPathFinder.addTo(Path.scala:650)
	at sbt.io.PathFinderImpl.get(Path.scala:603)
	at sbt.io.PathFinderDefaults.pair(Path.scala:550)
Error during sbt execution: java.lang.OutOfMemoryError: Java heap space
```

Either case `[warn] No sbt.version set in project/build.properties, base directory: /` is printed, so that's a place we can perform this check.

**Comment by som-snytt** [comment]
Not an expert, but I have recently seen the helpful message about it's not a project dir.

I also wanted to express my appreciation for @ghost who seems to have the paranormal ability to be in many places at the same time, much like @eed3si9n.
