### ISSUE TITLE
JUnit XML report contains wrong stacktrace/message when running in forked mode

### ISSUE THREAD

**Issue by benmccann** [sbt/sbt#1469]
@francisdb reported this bug as https://github.com/sbt/junit-interface/issues/55

However, I think this is actually an SBT bug given that [JUnitXmlReportPlugin](https://github.com/sbt/sbt/blob/0.13/main/src/main/scala/sbt/plugins/JUnitXmlReportPlugin.scala) lives here

This is what is reported in the junit xml reports

```
sbt.ForkMain$ForkError
    at com.xxx.ServerTest.testInjectingRawData(ServerTest.java:573)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
```

But the actual failing test stacktrace looks like this

```
[error] Test com.xxx.ServerTest.testInjectingRawData failed: java.lang.NullPointerException: null, took 0.118 sec
[error]     at com.xxx.ServerTest.testInjectingRawData(ServerTest.java:573)
[error]     ...
```

**Comment by eed3si9n** [comment]
@eureka928 Not sure if this is still reproducible, but this might be something you might be interested in investigating?

**Comment by 9876543210-tc-0123456789** [comment]
@eed3si9n I will pick this up.

**Comment by eed3si9n** [comment]
@volcano303 Sure. Please check out our [Contributor's Guildeline](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) and:
1. Make sure you can reproduce the problem and the fix manually
2. Include tests for the change
3. Follow our AI assisted contributions guideline
4. Multiple contributors might work on this issue in parallel
5. Generally we recommend getting CI to pass on a forked repo before sending a pull request
6. Sign Scala CLA <https://contribute.akka.io/contribute/cla/scala>
