### ISSUE TITLE
[0.13.5] sLog is broken when calling reapply()

### ISSUE THREAD

**Issue by dansanduleac** [sbt/sbt#1478]
So I've noticed there's this new `sLog` setting that allows logging in, well, Settings. That's cool.
However, it only works when you Load a build (unit), if you `BuiltinCommands.reapply` then you get this error:

**Settings logger used after project was loaded.**

Example:

```
> set version := { sLog.value.info("yo"); version.value }
[info] Defining foo/*:version
[info] The new value will be used by foo/*:assembly::assemblyDefaultJarName, foo/*:assemblyPackageDependency::assemblyDefaultJarName and 8 others.
[info]  Run `last` for details.
[info] Reapplying settings...
java.lang.RuntimeException: Settings logger used after project was loaded.
    at scala.sys.package$.error(package.scala:27)
    at sbt.LogManager$$anon$1$$anonfun$slog$1.apply(LogManager.scala:110)
    at sbt.LogManager$$anon$1$$anonfun$slog$1.apply(LogManager.scala:110)
    at scala.Option.getOrElse(Option.scala:120)
    at sbt.LogManager$$anon$1.slog(LogManager.scala:110)
    at sbt.LogManager$$anon$1.log(LogManager.scala:115)
    at sbt.Logger$class.info(Logger.scala:117)
    at sbt.LogManager$$anon$1.info(LogManager.scala:109)
    at $dc7ae9d6e6092594e9b2$$anonfun$$sbtdef$1.apply(<set>:1)
    at $dc7ae9d6e6092594e9b2$$anonfun$$sbtdef$1.apply(<set>:1)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
    at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
    at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
    at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
    at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
```

**Comment by jsuereth** [comment]
This is a hard one to test, as it requires memory pressure for the weak-reference to get evicted.  I think I have a patch, but I'm having trouble geting a reliable failure  before I test the fix :)
