### ISSUE TITLE
Publishing via sftp with public key authentication on sftp-only server fails

### ISSUE THREAD

**Issue by michalrus** [sbt/sbt#1492]
When using public key authentication with an OpenSSHd server configured to allow only sftp connections:

```
m@debian:~$ ssh maven@michalrus.com
This service allows sftp connections only.
Connection to michalrus.com closed.
m@debian:~$ sftp maven@michalrus.com
Connected to michalrus.com.
sftp> ls
maven.michalrus.com  
sftp> ^D
m@debian:~$ 
```

... sbt fails with:

```
[info] Done packaging.
[trace] Stack trace suppressed: run last core/*:publish for the full output.
[error] (core/*:publish) java.io.IOException: Remote scp sent illegal error code.
[error] Total time: 74 s, completed Aug 2, 2014 11:06:36 AM
> last core/*:publish
[debug] :: SSH :: connecting to michalrus.com...
[debug] :: SSH :: connected to michalrus.com!
java.io.IOException: Remote scp sent illegal error code.
        at org.apache.ivy.plugins.repository.ssh.SshRepository.put(SshRepository.java:277)
        at org.apache.ivy.plugins.repository.AbstractRepository.put(AbstractRepository.java:130)
        at org.apache.ivy.plugins.resolver.RepositoryResolver.put(RepositoryResolver.java:234)
        at org.apache.ivy.plugins.resolver.RepositoryResolver.publish(RepositoryResolver.java:216)
        at sbt.IvyActions$$anonfun$publish$3.apply(IvyActions.scala:263)
        at sbt.IvyActions$$anonfun$publish$3.apply(IvyActions.scala:262)
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:771)
        at sbt.IvyActions$.publish(IvyActions.scala:262)
        ...
```

`build.sbt` fragment:

``` scala
resolvers += {
  val key = new java.io.File(sys.env("HOME") + "/.ssh/id_rsa")
  Resolver.ssh("michalrus.com", "michalrus.com") as("maven", key)
}

publishTo := Some(Resolver.sftp("michalrus.com", "michalrus.com", "/maven.michalrus.com/"))
```

So, I thought, maybe sbt doesn't know how to use sftp and uses scp instead?...

But that's not the case, since when I remove the private key part from `build.sbt` and _provide password manually_, when prompted, it works... Works with the _same sftp-only account_.

Also, public key authentication works when I lift the sftp-only restriction in OpenSSHd's config.

**Comment by axos88** [comment]
+1
