### ISSUE TITLE
InvalidClassException with sbt.testing.TestSelector

### ISSUE THREAD

**Issue by UnsungHero97** [sbt/sbt#1528]
It looks like some files in sbt.testing that implement `Serializable` are not providing `serialVersionUID`, and I'm seeing an exception when running `play test`.

```
Exception in thread "Thread-74" java.io.InvalidClassException: sbt.testing.TestSelector; local class incompatible: stream classdesc serialVersionUID = -1277815829122539856, local class serialVersionUID = 4300957833082274101
  at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:570)
  at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1601)
  at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1496)
  at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1750)
  at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1329)
  at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1970)
  at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1895)
  at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1777)
  at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1329)
  at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1685)
  at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1323)
  at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1685)
  at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1323)
  at java.io.ObjectInputStream.readObject(ObjectInputStream.java:349)
  at sbt.React.react(ForkTests.scala:116)
  at sbt.ForkTests$$anonfun$mainTestTask$1$Acceptor$2$.run(ForkTests.scala:75)
  at java.lang.Thread.run(Thread.java:695)
Internal error when running tests: sbt.ForkMain$Run$RunAborted: java.net.SocketException: Broken pipe
```

I'm under the impression that any class that implements Serializable should add a serialVersionUID. Is this something that can be added?

**Comment by jsuereth** [comment]
It's true they should specify serialVersionUID (I think they don't), but I'm more concerned ove rhow you got to a place where the classes do not line up.

Is the TestSelector from a `build.sbt` or `set` command?

**Comment by UnsungHero97** [comment]
@jsuereth... this is an interesting case, and @eed3si9n can provide a little more detail since he's aware of my situation, but I'll try to clarify...

I'm using PowerMock in conjunction with Mockito for a test suite I'm working on. The problem happens when I run `play test`, but I do not know who actually calls `TestSelector`. A thing to note is that I've configured PowerMock to use its own Java agent...

https://code.google.com/p/powermock/wiki/PowerMockAgent#TestNG

This is way beyond my knowledge, but I'm guessing that the the play console JVM and the test JVM communicate via serialized Java objects for some meta info. Since PowerMock is using the Java agent, it's probably changing classes somehow, including sbt.\* classes, and the UIDs don't match up.

**Comment by jsuereth** [comment]
Is there a way to get PowerMock to NOT touch sbt's java agent?  If not, we can look at an alternative.  

It is not required for us to force  a specific serial version UID onto serializable classes.   So, I'm ok adding this (sort of, as the ID denotes a lot of compatibility things we'll have to take into account that we've been able to ignore by not having one), but I'd also say that PowerMock has a bug.

**Comment by UnsungHero97** [comment]
Yes, I agree. I also think PowerMock has a bug, and I'm trying to follow up with them (Johan Haleby) to brainstorm a solution for globally ignoring certain classes. As far as I know, however, I don't think there is a way to get PowerMock to not interfere with SBT.

**Comment by UnsungHero97** [comment]
I've posted to PowerMock's Google group to try and get some attention around this issue... https://groups.google.com/forum/#!topic/powermock/aDMNvuOI1bE

**Comment by retronym** [comment]
This might be totally unrelated, but after upgrading the Scala SBT build to SBT 0.13.11, I'm seeing a similar exception:

```
Selected 3 tests drawn from specified tests

# starting 3 tests in run
ok 2 - run/t9546b.scala
ok 1 - run/t9546c.scala
ok 3 - run/t9546.scala

Exception in thread "Thread-12" java.lang.NullPointerException
    at sbt.TestEvent$$anonfun$overallResult$1.apply(TestReportListener.scala:72)
    at sbt.TestEvent$$anonfun$overallResult$1.apply(TestReportListener.scala:71)
    at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:51)
    at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:60)
    at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:34)
    at scala.collection.TraversableOnce$class.$div$colon(TraversableOnce.scala:138)
    at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:105)
    at sbt.TestEvent$.overallResult(TestReportListener.scala:71)
    at sbt.TestEvent$$anon$1.<init>(TestReportListener.scala:66)
    at sbt.TestEvent$.apply(TestReportListener.scala:65)
    at sbt.React.react(ForkTests.scala:129)
    at sbt.ForkTests$$anonfun$mainTestTask$1$Acceptor$2$.run(ForkTests.scala:74)
    at java.lang.Thread.run(Thread.java:745)
Internal error when running tests: sbt.ForkMain$Run$RunAborted: java.net.SocketException: Broken pipe
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
```

Trying to minimize this now.

**Comment by retronym** [comment]
Oh, I see the root exception is not the "broken pipe" but rather the `NPE`. So these bugs are probably unrelated, other than for the fact that SBT ought to print a useful message for `sbt.ForkMain$Run$RunAborted` rather than just the exception name/message.

**Comment by UnsungHero97** [comment]
Closing, as this is not something I'm working on anymore.
