### ISSUE TITLE
NPE  in FileExamples

### ISSUE THREAD

**Issue by paulp** [sbt/sbt#1530]
If I start sbt in /tmp and then hit tab, it goes boom. Doesn't happen if it has a char to work with.

```
/tmp# java -jar ~/.sbt/launchers/0.13.5/sbt-launch.jar
[info] Loading global plugins from /Users/paulp/.sbt/0.13/plugins
[info] Set current project to tmp (in build file:/private/tmp/)
> java.lang.NullPointerException
    at scala.collection.mutable.ArrayOps$ofRef$.length$extension(ArrayOps.scala:114)
    at scala.collection.mutable.ArrayOps$ofRef.length(ArrayOps.scala:114)
    at scala.collection.IndexedSeqLike$class.iterator(IndexedSeqLike.scala:91)
    at scala.collection.mutable.ArrayOps$ofRef.iterator(ArrayOps.scala:108)
    at scala.collection.IterableLike$class.toStream(IterableLike.scala:284)
    at scala.collection.mutable.ArrayOps$ofRef.toStream(ArrayOps.scala:108)
    at sbt.complete.FileExamples.files(ExampleSource.scala:54)
    at sbt.complete.FileExamples$$anonfun$files$1$$anonfun$apply$2.apply(ExampleSource.scala:57)
    at sbt.complete.FileExamples$$anonfun$files$1$$anonfun$apply$2.apply(ExampleSource.scala:57)
    at scala.collection.immutable.Stream$$anonfun$flatMap$1.apply(Stream.scala:450)
```

**Comment by eed3si9n** [comment]
Thanks for the report.
Note to self: #1236
