### ISSUE TITLE
Name hashing: StackOverflow with macros

### ISSUE THREAD

**Issue by gkossakowski** [sbt/sbt#1544]
I found another instance of problem reported in #1237. If you enable name hashing in sbt's `source-dependencies/macro` scripted test then you get:

```
[info] java.lang.StackOverflowError
[info]  at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1098)
[info]  at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:13)
[info]  at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:13)
[info]  at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2825)
[info]  at xsbt.Dependency$ExtractDependenciesByMemberRefTraverser.traverse(Dependency.scala:149)
[info]  at xsbt.Dependency$ExtractDependenciesByMemberRefTraverser.traverse(Dependency.scala:104)
[info]  at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1174)
[info]  at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:13)
[info]  at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:13)
[info]  at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2825)
[info]  at xsbt.Dependency$ExtractDependenciesByMemberRefTraverser.traverse(Dependency.scala:149)
[info]  at xsbt.Dependency$ExtractDependenciesByMemberRefTraverser.traverse(Dependency.scala:146)
[info]  at xsbt.Dependency$ExtractDependenciesByMemberRefTraverser.traverse(Dependency.scala:104)
[info]  at scala.reflect.api.Trees$Traverser.traverseTrees(Trees.scala:2829)
[info]  at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1174)
[info]  at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:13)
[info]  at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:13)
[info]  at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2825)
[...]
```

**Comment by gkossakowski** [comment]
//cc @Duhemm
