### ISSUE TITLE
java.io.EOFException in sbt.Sync with compile:copyResources

### ISSUE THREAD

**Issue by ezh** [sbt/sbt#1559]
I have multi project with 11 subprojects. Also I have plugin that put additional `copyResourcesTask` per subproject. So `compile` task at root invoke 22 copyResources tasks and some of them run in parallel. There is a sporadically: 

```
[error] (subproject/compile:copyResources) Error wrapping InputStream in GZIPInputStream: java.io.EOFException
```

 It is frequent and very annoying.

I attached debugger to SBT process and intercept EOFException. Sync file was absent. So I am sure that `java.util.zip.GZIPInputStream.readUByte` is broken under certain circumstances. There is a lot of related posts in internet with `readUByte` and `GZIPInputStream.java` This error was rare when attached debugger significantly reduce SBT speed (I got 1 error per 30 compilations)

Stack trace:

```
Error wrapping InputStream in GZIPInputStream: java.io.EOFException
        at sbt.ErrorHandling$.translate(ErrorHandling.scala:11)
        at sbt.WrapUsing.open(Using.scala:36)
        at sbt.Using.apply(Using.scala:24)
        at sbt.IO$$anonfun$gzipFileIn$1.apply(IO.scala:782)
        at sbt.IO$$anonfun$gzipFileIn$1.apply(IO.scala:781)
        at sbt.Using.apply(Using.scala:25)
        at sbt.IO$.gzipFileIn(IO.scala:781)
        at sbt.Sync$.readUncaught(Sync.scala:88)
        at sbt.Sync$.readInfo(Sync.scala:84)
        at sbt.Sync$$anonfun$apply$1.apply(Sync.scala:29)
        at sbt.Sync$$anonfun$apply$1.apply(Sync.scala:23)
        at sbt.Defaults$$anonfun$copyResourcesTask$1.apply(Defaults.scala:821)
        at sbt.Defaults$$anonfun$copyResourcesTask$1.apply(Defaults.scala:817)
        at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:35)
        at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:34)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
        at sbt.std.Transform$$anon$4.work(System.scala:64)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
        at sbt.Execute.work(Execute.scala:244)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException
        at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:268)
        at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258)
        at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
        at sbt.Using$$anonfun$gzipInputStream$1.apply(Using.scala:91)
        at sbt.Using$$anonfun$gzipInputStream$1.apply(Using.scala:91)
        at sbt.Using$$anon$1.openImpl(Using.scala:56)
        at sbt.WrapUsing$$anonfun$open$2.apply(Using.scala:36)
        at sbt.ErrorHandling$.translate(ErrorHandling.scala:11)
        at sbt.WrapUsing.open(Using.scala:36)
        at sbt.Using.apply(Using.scala:24)
        at sbt.IO$$anonfun$gzipFileIn$1.apply(IO.scala:782)
        at sbt.IO$$anonfun$gzipFileIn$1.apply(IO.scala:781)
        at sbt.Using.apply(Using.scala:25)
        at sbt.IO$.gzipFileIn(IO.scala:781)
        at sbt.Sync$.readUncaught(Sync.scala:88)
        at sbt.Sync$.readInfo(Sync.scala:84)
        at sbt.Sync$$anonfun$apply$1.apply(Sync.scala:29)
        at sbt.Sync$$anonfun$apply$1.apply(Sync.scala:23)
        at sbt.Defaults$$anonfun$copyResourcesTask$1.apply(Defaults.scala:821)
        at sbt.Defaults$$anonfun$copyResourcesTask$1.apply(Defaults.scala:817)
        at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:35)
        at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:34)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
        at sbt.std.Transform$$anon$4.work(System.scala:64)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
        at sbt.Execute.work(Execute.scala:244)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

```
SBT 0.13.5
```

```
uname -a
Linux devbox 3.16.0-gentoo #1 SMP Thu Aug 14 18:32:51 MSK 2014 x86_64 Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz GenuineIntel GNU/Linux
```

```
java -version
java version "1.8.0_05"
Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.5-b02, mixed mode)
```

My proposal is to modify Sync.readInfo
from

``` scala
    def readInfo[F <: FileInfo](file: File)(implicit infoFormat: Format[F]): RelationInfo[F] =
        try { readUncaught(file)(infoFormat) }
        catch { case e: IOException => (Relation.empty, Map.empty) }
```

to

``` scala
    def readInfo[F <: FileInfo](file: File)(implicit infoFormat: Format[F]): RelationInfo[F] =
        try { readUncaught(file)(infoFormat) }
        catch {
            case e: IOException => (Relation.empty, Map.empty)
            case e: TranslatedIOException => (Relation.empty, Map.empty)
        }
```

Thank you.

**Comment by eed3si9n** [comment]
> Also I have plugin that put additional copyResourcesTask per subproject.

Which plugin is that? I don't know if catching exception is a good solution here. If Sync is not doing its job somehow, that needs to be fixed.
