### ISSUE TITLE
13.6-RC2 does not build my lib

### ISSUE THREAD

**Issue by antonkulaga** [sbt/sbt#1568]
Sbt 0.13.5 build my app ( https://github.com/scalax/semweb/tree/3c455a9c88f889110e61dbc2de0ba2d51ab9a7bc ) perfectly fine. But when I change sbt version to 0.13.6-RC2 and run 'sbt" I get the following:

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[info] Loading project definition from /home/antonkulaga/learn/semweb/project
[info] Updating {file:/home/antonkulaga/learn/semweb/project/}semweb-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 1 Scala source to /home/antonkulaga/learn/semweb/project/target/scala-2.10/sbt-0.13/classes...
java.lang.NoClassDefFoundError: $4bcf7bcca004bfa80317$
    at $2478e33645240457ab85$$anonfun$$sbtdef$1.apply(/home/antonkulaga/learn/semweb/sesame/sesame-build.sbt:28)
    at $2478e33645240457ab85$$anonfun$$sbtdef$1.apply(/home/antonkulaga/learn/semweb/sesame/sesame-build.sbt:28)
    at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:163)
    at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:163)
    at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
    at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
    at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
    at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
    at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: $4bcf7bcca004bfa80317$
    at scala.tools.nsc.interpreter.AbstractFileClassLoader.findClass(AbstractFileClassLoader.scala:83)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at $2478e33645240457ab85$$anonfun$$sbtdef$1.apply(/home/antonkulaga/learn/semweb/sesame/sesame-build.sbt:28)
    at $2478e33645240457ab85$$anonfun$$sbtdef$1.apply(/home/antonkulaga/learn/semweb/sesame/sesame-build.sbt:28)
    at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:163)
    at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:163)
    at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
    at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
    at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
    at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
    at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] java.lang.NoClassDefFoundError: $4bcf7bcca004bfa80317$
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

**Comment by jsuereth** [comment]
Can you give us some more information, particularly:
1.  Are you running IntelliJ/Eclipse/Activator AND sbt at the same time, or otherwise running more than one terminal?
2. If you delete the contents of `project/target` do you still see the issue?

Note:  The error you see above happens frequently if Intellij is trying to compile an sbt project at the same time sbt does.   One of the two will delete the .class file before the other reads it, and pain ensues.   I can look into issuing a lock on the project file to help prevent the issue, but I'd need to verify this is what you're seeing.  That's question 1.   Question 2 is around a new fix in 0.13.6 to prevent .class files leaking onto the filesystem.

**Comment by antonkulaga** [comment]
I deleted the target and ran it from console (without opening in IDE and with only one terminal for this project). Same error.

**Comment by paulp** [comment]
This is easy to reproduce. You'll want to mark it as a blocker.

I'm 80% sure it's 0bfb5a4118.

M2 doesn't show the behavior, RC1 does.

**Comment by paulp** [comment]
Okay, here's your reproduction.

```
// project/plugins.scala
addSbtPlugin("me.lessis" % "bintray-sbt" % "0.1.2")

// js/build.sbt
bintraySettings

// build.sbt
lazy val root = project in file(".")

lazy val js = project

def bigDataSesameVersion = "2.6.10"

libraryDependencies += "foo" % "bar" % bigDataSesameVersion
```

**Comment by fommil** [comment]
:+1: to quality control on RC2

**Comment by paulp** [comment]
Btw that should be plugins.sbt up there. Probably obvious.

**Comment by jsuereth** [comment]
Thanks for the reproduciton, on it.  RC2 is blocked for other criticals as well.

**Comment by jsuereth** [comment]
@paulp Close guess, but it was actually this commit: https://github.com/sbt/sbt/commit/a1b3117a42134fd050813d383d48de3ed218cd86

which I didn't have sufficient tests for, it seems.   Not sure how the multi-project load slipped by the scripted tests, but I'm glad you got me that reproducible test case.    There was just some state I forgot to chain through a method.    Debating starting to use a design which may help prevent these mistakes, when we have a chance to hide the Load code behind interfaces in sbt 1.0, and stop providing support for stale, should-have-been-private APIs.

**Comment by jsuereth** [comment]
sbt 0.13.6-RC3 has the fix for this, please try it out and reopen if you see any more issues.

**Comment by antonkulaga** [comment]
Works like a charm. Thank you for the fix!
