### ISSUE TITLE
sbt uses sbinary to cache objects on filesystem, but it has a hard limit of 64k.

### ISSUE THREAD

**Issue by wchen9911** [sbt/sbt#1614]
We were hit by this limit recently. See the attached stacktrace. This happened on "doc" task when the checkout dir was really long, but as far as I can tell, this is used everywhere. Although most people won't be affected by this, but this is still something that many big project will hit eventually.

Here is the hard limit in sbinary:
https://github.com/DRMacIver/sbinary/blob/master/core/src/javaprotocol.scala#L164

And here is the stacktrace:

```
java.lang.RuntimeException: encoded string too long: 66201 bytes
    at scala.sys.package$.error(package.scala:27)
    at scala.Predef$.error(Predef.scala:142)
    at sbinary.JavaUTF$StringFormat$.writes(javaprotocol.scala:165)
    at sbinary.JavaUTF$StringFormat$.writes(javaprotocol.scala:100)
    at sbt.InputCache$$anon$1.write(SeparatedCache.scala:27)
    at sbt.HListCacheImplicits$$anon$14.write(Cache.scala:185)
    at sbt.HListCacheImplicits$$anon$14.write(Cache.scala:173)
    at sbt.HListCacheImplicits$$anon$14.write(Cache.scala:186)
    at sbt.HListCacheImplicits$$anon$14.write(Cache.scala:173)
    at sbt.HListCacheImplicits$$anon$14.write(Cache.scala:186)
    at sbt.HListCacheImplicits$$anon$14.write(Cache.scala:173)
    at sbt.Tracked$CacheHelp$$anonfun$save$1.apply(Tracked.scala:68)
    at sbt.Tracked$CacheHelp$$anonfun$save$1.apply(Tracked.scala:68)
    at sbt.Using.apply(Using.scala:25)
    at sbt.Tracked$CacheHelp.save(Tracked.scala:68)
    at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:48)
    at sbt.RawCompileLike$$anonfun$cached$1.apply(RawCompileLike.scala:55)
    at sbt.RawCompileLike$$anonfun$cached$1.apply(RawCompileLike.scala:40)
    at sbt.Defaults$$anonfun$docTaskSettings$3.apply(Defaults.scala:694)
    at sbt.Defaults$$anonfun$docTaskSettings$3.apply(Defaults.scala:672)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
    at sbt.std.Transform$$anon$4.work(System.scala:64)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.Execute.work(Execute.scala:244)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
```

**Comment by eed3si9n** [comment]
Do you know what sbt's trying to cache?

**Comment by wchen9911** [comment]
I believe it is the fileInputOptions setting

See:
https://github.com/sbt/sbt/blob/3c8893ef2ccd046f1786df4c87f99a2ffe1c29e1/main/src/main/scala/sbt/Defaults.scala#L723
and 
https://github.com/sbt/sbt/blob/0.13.6/main/actions/src/main/scala/sbt/Doc.scala#L23

**Comment by eed3si9n** [comment]
Assuming you're using sbt 0.13.1, it's https://github.com/sbt/sbt/blob/0.13.1/main/src/main/scala/sbt/Defaults.scala#L694, which is consistent with stacktrace hitting `RawCompileLike` right afterwards.

**Comment by wchen9911** [comment]
Yes, we are on 0.13.1, but the links I gave is on master, and the related code hasn't changed. This is not an urgent problem, we worked around it by setting sources to Seq.empty(). 

But given the growth of a codebase, more projects will be hit by this limit.

**Comment by eed3si9n** [comment]
We'll likely migrate to json-based serialization/data binding in the future. We were just talking about [serialization in sbt](https://groups.google.com/d/msg/sbt-dev/7IpZrq79oz0/JSgVlSOb9RsJ) yesterday and today.

**Comment by wchen9911** [comment]
Thanks, that's good to know.

**Comment by pvlugter** [comment]
We're also hitting this when building the aggregated Play documentation with dbuild.

**Comment by dwijnand** [comment]
Re-opening on account of ["partially because I haven't implemented it for Scaladoc yet"](https://github.com/sbt/incrementalcompiler/pull/17#issue-106907365).

**Comment by eed3si9n** [comment]
sbt 1 doesn't use sbinary, so I am closing this.

**Comment by dwijnand** [comment]
Yes it does: https://github.com/sbt/zinc/blob/v1.3.1/internal/zinc-persist/src/main/scala/sbt/internal/inc/text/TextAnalysisFormat.scala#L40-L41

So, reopening, as it's an issue in Play's build: https://github.com/playframework/playframework/blob/89b28963cc42ef291ecce0aa7cd71e1d5dd880e9/project/Docs.scala#L354

**Comment by dwijnand** [comment]
Actually, `sbt.util.Tracked` in the util-tracking module, uses sjsonnew instead of sbinary, so while sbinary still has this hard limit (https://github.com/sbt/sbinary/blob/84a37cadc88c14ab5cf8f05eee27f8c2432ed6fe/core/src/main/scala/javaprotocol.scala#L165-L166), it's won't be hit when creating docs.
