### ISSUE TITLE
NPE in ClassToAPI

### ISSUE THREAD

**Issue by gkossakowski** [sbt/sbt#1617]
As [reported](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/scala-ide-user/3-vDAKsqu-M/_FHp8G1UWHMJ) by Scala IDE user, we have a NPE in ClassToAPI:

```
scala.MatchError: null
    at sbt.ClassToAPI$.reference(ClassToAPI.scala:255)
    at sbt.ClassToAPI$.defLike(ClassToAPI.scala:154)
    at sbt.ClassToAPI$.methodToDef(ClassToAPI.scala:143)
    at sbt.ClassToAPI$$anonfun$7.apply(ClassToAPI.scala:73)
    at sbt.ClassToAPI$$anonfun$7.apply(ClassToAPI.scala:73)
    at sbt.ClassToAPI$$anonfun$mergeMap$1.apply(ClassToAPI.scala:175)
    at sbt.ClassToAPI$$anonfun$mergeMap$1.apply(ClassToAPI.scala:175)
```

@dragos's hypothesis is that we are getting null from Java Reflection.

**Comment by gkossakowski** [comment]
I believe this got closed by #1619.
