### ISSUE TITLE
[0.13.7] FileNotFoundException: /Users/foo/.m2/settings.xml (No such file or directory)

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#1632]
## steps

Run play using 0.13.7-SNAPSHOT
## problem

```
java.io.FileNotFoundException: /Users/foo/.m2/settings.xml (No such file or directory)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:146)
    at scala.xml.Source$.fromFile(XML.scala:19)
    at scala.xml.factory.XMLLoader$class.loadFile(XMLLoader.scala:47)
    at scala.xml.XML$.loadFile(XML.scala:57)
    at sbt.Resolver$.sbt$Resolver$$loadHomeFromSettings$1(Resolver.scala:307)
    at sbt.Resolver$.mavenLocalDir(Resolver.scala:317)
    at sbt.Resolver$.publishMavenLocal(Resolver.scala:321)
    at sbt.Classpaths$$anonfun$45.apply(Defaults.scala:1065)
    at sbt.Classpaths$$anonfun$45.apply(Defaults.scala:1065)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
    at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
    at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
    at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
    at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```
## expectation

No error.
## notes

```
$ ls ~/.m2/     
ls: /Users/foo/.m2/: No such file or directory
```

I'm guessing this came in from #1600.
/cc @topping

**Comment by briantopping** [comment]
Yes, please assign to me.
