### ISSUE TITLE
0.13.7-M3 - memory leak, or large increase in memory usage?

### ISSUE THREAD

**Issue by paddymahoney** [sbt/sbt#1659]
Within team, we run sbt with -mem set to 2048. Our team is not hitting OOM at this setting within sbt 0.13.5. 

I double this when working on updating sbt versions; -mem 4096. I can confirm that the -Xmx is at 4096 when compiling. 

Upon updating build.properties so that sbt.version=0.13.7-M3, 
the following errors begin to occur: 

```
[info] Compiling 21 Scala sources to /Users/patrick/npl/runtime/target/scala-2.11/classes...

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "sbt-web-scheduler-1"
[ERROR] [10/09/2014 12:11:26.973] [sbt-web-scheduler-1] [ActorSystem(sbt-web)] exception on LARS’ timer thread
java.lang.OutOfMemoryError: GC overhead limit exceeded
    at akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:409)
    at akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375)
    at java.lang.Thread.run(Thread.java:745)

[INFO] [10/09/2014 12:11:34.425] [sbt-web-scheduler-1] [ActorSystem(sbt-web)] starting new LARS thread
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: GC overhead limit exceeded
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:188)
    at sbt.ConcurrentRestrictions$$anon$4.take(ConcurrentRestrictions.scala:188)
    at sbt.Execute.next$1(Execute.scala:83)
    at sbt.Execute.processAll(Execute.scala:86)
    at sbt.Execute.runKeep(Execute.scala:66)
    at sbt.EvaluateTask$.liftedTree1$1(EvaluateTask.scala:342)
    at sbt.EvaluateTask$.run$1(EvaluateTask.scala:341)
    at sbt.EvaluateTask$.runTask(EvaluateTask.scala:361)
    at sbt.Aggregation$$anonfun$3.apply(Aggregation.scala:64)
    at sbt.Aggregation$$anonfun$3.apply(Aggregation.scala:62)
    at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:293)
    at sbt.Aggregation$.timedRun(Aggregation.scala:62)
    at sbt.Aggregation$.runTasks(Aggregation.scala:71)
    at sbt.Aggregation$$anonfun$applyTasks$1.apply(Aggregation.scala:32)
    at sbt.Aggregation$$anonfun$applyTasks$1.apply(Aggregation.scala:31)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
    at sbt.Aggregation$$anonfun$evaluatingParser$4$$anonfun$apply$5.apply(Aggregation.scala:153)
    at sbt.Aggregation$$anonfun$evaluatingParser$4$$anonfun$apply$5.apply(Aggregation.scala:152)
    at sbt.Act$$anonfun$sbt$Act$$actParser0$1$$anonfun$sbt$Act$$anonfun$$evaluate$1$1$$anonfun$apply$10.apply(Act.scala:244)
    at sbt.Act$$anonfun$sbt$Act$$actParser0$1$$anonfun$sbt$Act$$anonfun$$evaluate$1$1$$anonfun$apply$10.apply(Act.scala:241)
    at sbt.Command$.process(Command.scala:92)
    at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
    at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
    at sbt.State$$anon$1.process(State.scala:184)
    at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
    at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.MainLoop$.next(MainLoop.scala:98)
    at sbt.MainLoop$.run(MainLoop.scala:91)
    at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
    at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
    at sbt.Using.apply(Using.scala:24)
    at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
    at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
    at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
    at sbt.MainLoop$.runLogged(MainLoop.scala:24)
    at sbt.StandardMain$.runManaged(Main.scala:53)
    at sbt.xMain.run(Main.scala:28)
    at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
    at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
    at xsbt.boot.Launch$.run(Launch.scala:109)
    at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
    at xsbt.boot.Launch$.launch(Launch.scala:117)
    at xsbt.boot.Launch$.apply(Launch.scala:18)
    at xsbt.boot.Boot$.runImpl(Boot.scala:41)
    at xsbt.boot.Boot$.main(Boot.scala:17)
    at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
    at scala.collection.immutable.VectorBuilder.result(Vector.scala:722)
    at scala.collection.immutable.VectorBuilder.result(Vector.scala:692)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at sbinary.Generic$CollectionFormat.reads(generic.scala:23)
    at sbinary.Operations$.read(operations.scala:9)
    at sbinary.Generic$$anon$5.reads(generic.scala:71)
    at sbinary.Operations$.read(operations.scala:9)
    at sbinary.BasicTypes$$anon$8.reads(standardtypes.scala:127)
    at sbinary.BasicTypes$$anon$8.reads(standardtypes.scala:122)
    at sbinary.Operations$.read(operations.scala:9)
    at sbinary.Generic$$anon$5.reads(generic.scala:71)
    at sbinary.Operations$.read(operations.scala:9)
    at sbinary.Generic$CollectionFormat$$anonfun$reads$1.apply(generic.scala:23)
    at sbinary.Generic$CollectionFormat$$anonfun$reads$1.apply(generic.scala:23)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.immutable.Range.foreach(Range.scala:141)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at sbinary.Generic$CollectionFormat.reads(generic.scala:23)
    at sbinary.Operations$.read(operations.scala:9)
    at sbinary.Generic$$anon$5.reads(generic.scala:71)
    at sbinary.Operations$.read(operations.scala:9)
    at sbinary.BasicTypes$$anon$20.reads(standardtypes.scala:725)
    at sbinary.BasicTypes$$anon$20.reads(standardtypes.scala:704)
    at sbinary.Operations$.read(operations.scala:9)
    at sbinary.Generic$$anon$5.reads(generic.scala:71)
    at sbinary.Operations$.read(operations.scala:9)
    at sbinary.Generic$CollectionFormat$$anonfun$reads$1.apply(generic.scala:23)
    at sbinary.Generic$CollectionFormat$$anonfun$reads$1.apply(generic.scala:23)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[error] java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: GC overhead limit exceeded
[error] Use 'last' for the full log.
```

This is without cached dependency resolution, or any changes to the sbt update options. 
Just a heads up that memory usage must have doubled under some uses, and this may block adoption of this version of sbt with the tasty improvements. 

Please let me know if I can assist in troubleshooting further.

**Comment by paddymahoney** [comment]
launcher version is sbt 0.13.6.
sbt 0.13.6 - compilation is successful (with or without consolidated dependency resolution).

**Comment by paddymahoney** [comment]
Just checked my incOptions - nameHashing is on for all projects including root.

**Comment by paddymahoney** [comment]
This looks to have subsided after moving to play 2.3.6 - the fix for the NullPointerException in chain resolution was likely the solution.
