### ISSUE TITLE
[0.13.7] Natural whitespace parsing breaks XML

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#1666]
Found using community-build - https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x-manual/56/console
## steps

```
[scala-stm] [error] name := "scala-stm"
[scala-stm] [error] 
[scala-stm] [error] organization := "org.scala-stm"
[scala-stm] [error] 
[scala-stm] [error] version := "0.7"
[scala-stm] [error] 
[scala-stm] [error] scalaVersion := "2.11.0"
[scala-stm] [error] 
[scala-stm] [error] //scalaBinaryVersion := "2.11.0-M8"
[scala-stm] [error] 
[scala-stm] [error] //crossScalaVersions := Seq("2.10.1-RC2", "2.10.0", "2.9.3", "2.9.2")
[scala-stm] [error] 
[scala-stm] [error] //libraryDependencies += ("org.scalatest" % "scalatest_2.10.0-RC5" % "[1.5,)" % "test")
[scala-stm] [error] libraryDependencies += ("org.scalatest" %% "scalatest" % "[1.5,)" % "test")
[scala-stm] [error] 
[scala-stm] [error] libraryDependencies += ("junit" % "junit" % "4.5" % "test")
[scala-stm] [error] 
[scala-stm] [error] // skip exhaustive tests
[scala-stm] [error] testOptions += Tests.Argument("-l", "slow")
[scala-stm] [error] 
[scala-stm] [error] // test of TxnExecutor.transformDefault must be run by itself
[scala-stm] [error] parallelExecution in Test := false
[scala-stm] [error] 
[scala-stm] [error] // make sure Java classes use 1.6 file format
[scala-stm] [error] javacOptions in (Compile, compile) ++= Seq("-source", "1.6", "-target", "1.6")
[scala-stm] [error] 
[scala-stm] [error] ////////////////////
[scala-stm] [error] // publishing
[scala-stm] [error] 
[scala-stm] [error] pomExtra :=
[scala-stm] [error]   <url>http://nbronson.github.com/scala-stm/</url>
[scala-stm] [error]   <licenses>
[scala-stm] [error]     <license>
[scala-stm] [error]       <name>BSD</name>
[scala-stm] [error]       <url>https://github.com/nbronson/scala-stm/blob/master/LICENSE.txt</url>
[scala-stm] [error]       <distribution>repo</distribution>
[scala-stm] [error]     </license>
[scala-stm] [error]   </licenses>
[scala-stm] [error]   <scm>
[scala-stm] [error]     <connection>scm:git:git@github.com:nbronson/scala-stm.git</connection>
[scala-stm] [error]     <url>git@github.com:nbronson/scala-stm.git</url>
[scala-stm] [error]   </scm>
[scala-stm] [error]   <developers>
[scala-stm] [error]     <developer>
[scala-stm] [error]       <id>nbronson</id>
[scala-stm] [error]       <name>Nathan Bronson</name>
[scala-stm] [error]       <email>ngbronson@gmail.com</email>
[scala-stm] [error]     </developer>
[scala-stm] [error]   </developers>
[scala-stm] [error] 
[scala-stm] [error] publishMavenStyle := true
[scala-stm] [error] 
[scala-stm] [error] publishTo <<= (version) { v: String =>
[scala-stm] [error]     val base = "https://oss.sonatype.org/"
[scala-stm] [error]     if (v.trim.endsWith("SNAPSHOT"))
[scala-stm] [error]       Some("snapshots" at base + "content/repositories/snapshots/")
[scala-stm] [error]     else
[scala-stm] [error]       Some("releases" at base + "service/local/staging/deploy/maven2/")
[scala-stm] [error]   }
[scala-stm] [error] 
[scala-stm] [error] // exclude scalatest from the Maven POM
[scala-stm] [error] pomPostProcess := { xi: scala.xml.Node =>
[scala-stm] [error]     import scala.xml._
[scala-stm] [error]     val badDeps = (xi \\ "dependency") filter {
[scala-stm] [error]       x => (x \ "artifactId").text != "scala-library"
[scala-stm] [error]     } toSet
[scala-stm] [error]     def filt(root: Node): Node = root match {
[scala-stm] [error]       case x: Elem => {
[scala-stm] [error]         val ch = x.child filter { !badDeps(_) } map { filt(_) }
[scala-stm] [error]         Elem(x.prefix, x.label, x.attributes, x.scope, ch: _*)
[scala-stm] [error]       }
[scala-stm] [error]       case x => x
[scala-stm] [error]     }
[scala-stm] [error]     filt(xi)
[scala-stm] [error]   }
[scala-stm] [error] 
[scala-stm] [error] credentials += Credentials(Path.userHome / ".ivy2" / ".credentials")
```
## problem

```
[scala-stm] [error] [/localhome/jenkinsdbuild3/workspace/Community-2.11.x-manual/target-0.9.1/extraction/cdcab9835c609aecf7d943156d53fb28dbd9eb58/projects/e700e61574afb95ee447d356e119d5985ade471b/build.sbt]:52: ';' expected but 'true' found.
[scala-stm] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
[scala-stm:error] java.lang.RuntimeException: 
[scala-stm:error]   at scala.sys.package$.error(package.scala:27)
[scala-stm:error]   at distributed.support.sbt.SbtRunner.distributed$support$sbt$SbtRunner$$processCommand(SbtRunner.scala:93)
[scala-stm:error]   at distributed.support.sbt.SbtRunner$$anonfun$run$1$$anonfun$apply$2$$anonfun$apply$3.apply(SbtRunner.scala:74)
[scala-stm:error]   at distributed.support.sbt.SbtRunner$$anonfun$run$1$$anonfun$apply$2$$anonfun$apply$3.apply(SbtRunner.scala:74)
[scala-stm:error]   at distributed.support.sbt.SbtRunner$$anonfun$run$1.apply(SbtRunner.scala:74)
[scala-stm:error]   at distributed.support.sbt.SbtRunner$$anonfun$run$1.apply(SbtRunner.scala:64)
[scala-stm:error]   at sbt.IO$.withTemporaryFile(IO.scala:311)
[scala-stm:error]   at distributed.support.sbt.SbtRunner.run(SbtRunner.scala:64)
[scala-stm:error]   at distributed.support.sbt.SbtExtractor$.extractMetaData(DependencyExtractor.scala:99)
[scala-stm:error]   at distributed.support.sbt.SbtBuildSystem.extractDependencies(SbtBuildSystem.scala:58)
[scala-stm:error]   at distributed.support.sbt.SbtBuildSystem.extractDependencies(SbtBuildSystem.scala:18)
```
## notes

Scala allows series of XML nodes as NodeSeq.

``` scala
scala> val x = <x/><y/>
x: scala.xml.NodeBuffer = ArrayBuffer(<x/>, <y/>)
```

/cc @ajozwik

**Comment by ritschwumm** [comment]
hm.. i'd just use xml:group and remove that "feature" from scalac...

**Comment by eed3si9n** [comment]
This issue remains open, and the fix is to bump up the Scala version to 2.10.5.

This issue was originally discovered using community-build during 0.13.7 development. The workaround #1671 was implemented. This however caused subsequent issues such as #1738 (XML parsing/wrapping of arbitrary `Seq[String]` (0.13.7)), which were discovered after 0.13.7 shipped. 

Later it was identified to be Scala compiler issue [SI-9027: Semicolon is not inferred after a XML node sequence literal](https://issues.scala-lang.org/browse/SI-9027). During 0.13.8 development we decided that sbt should roll back the workarounds put in by #1671 (#1765), and tell people to use parens or semicolon. SI-9027 was fixed in scala/scala#4185, and was backported to 2.10.5 in scala/scala#4186.

**Comment by ajozwik** [comment]
I created #1925. I modified two files. The problem is that on Travis sbt with version 0.13.8 is used to verify the tests. But we need sbt with just compiled version again scala 2.10.5. See failed Travis builds for more details.

**Comment by ajozwik** [comment]
More details:
I created branch with updated scala to 2.10.5:
https://github.com/ajozwik/sbt
When you clone repository and run command:
`scripted tests/*` you will receive the error:

```
About to run tests: 
 * tests/*

[trace] Stack trace suppressed: run last sbtRoot/*:scripted for the full output.
[error] (sbtRoot/*:scripted) java.lang.NoSuchMethodException: sbt.test.ScriptedTests$.run(java.io.File, boolean, [Ljava.lang.String;, java.io.File, [Ljava.lang.String;, scala.Function1)
```

But when you call:
`sbt publishLocal`
and after it:
`sbt -Dsbt.version=0.13.9-SNAPSHOT`
and then you call the same script:
`scripted tests/*` - all will pass.

I created #1980 for test.
