### ISSUE TITLE
append unmanagedResourceDirectories crash compiler

### ISSUE THREAD

**Issue by MasseGuillaume** [sbt/sbt#1667]
``` scala
unmanagedResourceDirectories in Backend ++= (unmanagedResourceDirectories in Kata).value
```

```
compile
[info] Compiling 1 Scala source to /home/masgui/Projects/Kata/ScalaKata/Plugin/target/scala-2.10/sbt-0.13/classes...
[info] ======= Position error
[info] Synthetic tree [7215] contains nonsynthetic tree [7214]
[info] == Enclosing tree [7215] of type Select at [1741]ScalaKata.scala
[info] 
[info] [L  66        ] #7215   [1741]          Select     // Select(Apply(method in), set)
[info] 
[info] == Enclosed tree [7214] of type Apply at [1724:1740]ScalaKata.scala
[info] 
[info] [L  66        ] #7214   [1724:1740]     Apply      // 
[info] 
[info] 
[info] While validating #9828
[info] [L   1        ] #9828   [0:7601]        PackageDef // scalakata
[info] 
[info] Children:
[info]   [L   1 P# 9828] #42     [8:21]          Select     // scalakata
[info]   [L   3 P# 9828] #45     [23:46]         Import     // java.awt.Desktop
[info]   [L   5 P# 9828] #47     [48:60]         Import     // sbt._
[info]   [L   6 P# 9828] #1577   [61:82]         Import     // Def.Initialize
[info]   [L   7 P# 9828] #1616   [83:96]         Import     // Keys._
[info]   [L   8 P# 9828] #1619   [97:119]        Import     // Attributed.data
[info]   [L  10 P# 9828] #56     [121:140]       Import     // java.net.URL
[info]   [L  11 P# 9828] #59     [141:160]       Import     // java.io.File
[info]   [L  13 P# 9828] #62     [162:191]       Import     // spray.revolver.Actions
[info]   [L  14 P# 9828] #66     [192:237]       Import     // spray.revolver.RevolverPlugin.Revolver
[info]   [L  16 P# 9828] #68     [239:257]       Import     // sbtdocker._
[info]   [L  17 P# 9828] #71     [258:283]       Import     // sbtdocker.Plugin._
[info]   [L  18 P# 9828] #75     [284:320]       Import     // sbtdocker.Plugin.DockerKeys._
[info]   [L  20 P# 9828] #9827   [322:7601]      ModuleDef  // Scalakata extends Plugin {
[info] =======
[error] 
[error]      while compiling: /home/masgui/Projects/Kata/ScalaKata/Plugin/src/main/scala/com.scalakata/ScalaKata.scala
[error]         during phase: typer
[error]      library version: version 2.10.4
[error]     compiler version: version 2.10.4
[error]   reconstructed args: -deprecation -Yrangepos -feature -bootclasspath /opt/jdk1.8.0_20/jre/lib/resources.jar:/opt/jdk1.8.0_20/jre/lib/rt.jar:/opt/jdk1.8.0_20/jre/lib/sunrsasign.jar:/opt/jdk1.8.0_20/jre/lib/jsse.jar:/opt/jdk1.8.0_20/jre/lib/jce.jar:/opt/jdk1.8.0_20/jre/lib/charsets.jar:/opt/jdk1.8.0_20/jre/lib/jfr.jar:/opt/jdk1.8.0_20/jre/classes:/home/masgui/.sbt/boot/scala-2.10.4/lib/scala-library.jar -unchecked -classpath /home/masgui/Projects/Kata/ScalaKata/Plugin/target/scala-2.10/sbt-0.13/classes:/home/masgui/.ivy2/cache/scala_2.10/sbt_0.13/io.spray/sbt-revolver/jars/sbt-revolver-0.7.2.jar:/home/masgui/.ivy2/cache/scala_2.10/sbt_0.13/se.marcuslonnberg/sbt-docker/jars/sbt-docker-0.5.2.jar:/home/masgui/.ivy2/cache/org.scala-sbt/sbt/jars/sbt-0.13.6.jar:/home/masgui/.ivy2/cache/org.scala-sbt/main/jars/main-0.13.6.jar:/home/masgui/.ivy2/cache/org.scala-sbt/actions/jars/actions-0.13.6.jar:/home/masgui/.ivy2/cache/org.scala-sbt/classpath/jars/classpath-0.13.6.jar:/home/masgui/.sbt/boot/scala-2.10.4/lib/scala-compiler.jar:/home/masgui/.sbt/boot/scala-2.10.4/lib/scala-reflect.jar:/home/masgui/.ivy2/cache/org.scala-sbt/launcher-interface/jars/launcher-interface-0.13.6.jar:/home/masgui/.ivy2/cache/org.scala-sbt/interface/jars/interface-0.13.6.jar:/home/masgui/.ivy2/cache/org.scala-sbt/io/jars/io-0.13.6.jar:/home/masgui/.ivy2/cache/org.scala-sbt/control/jars/control-0.13.6.jar:/home/masgui/.ivy2/cache/org.scala-sbt/completion/jars/completion-0.13.6.jar:/home/masgui/.ivy2/cache/org.scala-sbt/collections/jars/collections-0.13.6.jar:/home/masgui/.ivy2/cache/jline/jline/jars/jline-2.11.jar:/home/masgui/.ivy2/cache/org.scala-sbt/api/jars/api-0.13.6.jar:/home/masgui/.ivy2/cache/org.scala-sbt/compiler-integration/jars/compiler-integration-0.13.6.jar:/home/masgui/.ivy2/cache/org.scala-sbt/incremental-compiler/jars/incremental-compiler-0.13.6.jar:/home/masgui/.ivy2/cache/org.scala-sbt/logging/jars/logging-0.13.6.jar:/home/masgui/.ivy2/cache/org.scala-sbt/process/jars/process-0.13.6.jar:/home/masgui/.ivy2/cache/org.scala-sbt/relation/jars/relation-0.13.6.jar:/home/masgui/.ivy2/cache/org.scala-sbt/compile/jars/compile-0.13.6.jar:/home/masgui/.ivy2/cache/org.scala-sbt/persist/jars/persist-0.13.6.jar:/home/masgui/.ivy2/cache/org.scala-tools.sbinary/sbinary_2.10/jars/sbinary_2.10-0.4.2.jar:/home/masgui/.ivy2/cache/org.scala-sbt/classfile/jars/classfile-0.13.6.jar:/home/masgui/.ivy2/cache/org.scala-sbt/compiler-ivy-integration/jars/compiler-ivy-integration-0.13.6.jar:/home/masgui/.ivy2/cache/org.scala-sbt/ivy/jars/ivy-0.13.6.jar:/home/masgui/.ivy2/cache/org.scala-sbt/cross/jars/cross-0.13.6.jar:/home/masgui/.ivy2/cache/org.scala-sbt.ivy/ivy/jars/ivy-2.3.0-sbt-14d4d23e25f354cd296c73bfff405544434d5f80.jar:/home/masgui/.ivy2/cache/com.jcraft/jsch/jars/jsch-0.1.46.jar:/home/masgui/.ivy2/cache/org.scala-sbt/run/jars/run-0.13.6.jar:/home/masgui/.ivy2/cache/org.scala-sbt/task-system/jars/task-system-0.13.6.jar:/home/masgui/.ivy2/cache/org.scala-sbt/tasks/jars/tasks-0.13.6.jar:/home/masgui/.ivy2/cache/org.scala-sbt/tracking/jars/tracking-0.13.6.jar:/home/masgui/.ivy2/cache/org.scala-sbt/cache/jars/cache-0.13.6.jar:/home/masgui/.ivy2/cache/org.scala-sbt/testing/jars/testing-0.13.6.jar:/home/masgui/.ivy2/cache/org.scala-sbt/test-agent/jars/test-agent-0.13.6.jar:/home/masgui/.ivy2/cache/org.scala-sbt/test-interface/jars/test-interface-1.0.jar:/home/masgui/.ivy2/cache/org.scala-sbt/main-settings/jars/main-settings-0.13.6.jar:/home/masgui/.ivy2/cache/org.scala-sbt/apply-macro/jars/apply-macro-0.13.6.jar:/home/masgui/.ivy2/cache/org.scala-sbt/command/jars/command-0.13.6.jar:/home/masgui/.ivy2/cache/org.scala-sbt/logic/jars/logic-0.13.6.jar:/home/masgui/.ivy2/cache/org.scala-sbt/compiler-interface/jars/compiler-interface-src-0.13.6.jar:/home/masgui/.ivy2/cache/org.scala-sbt/compiler-interface/jars/compiler-interface-bin-0.13.6.jar:/home/masgui/.ivy2/cache/org.scala-sbt/precompiled-2_8_2/jars/compiler-interface-bin-0.13.6.jar:/home/masgui/.ivy2/cache/org.scala-sbt/precompiled-2_9_2/jars/compiler-interface-bin-0.13.6.jar:/home/masgui/.ivy2/cache/org.scala-sbt/precompiled-2_9_3/jars/compiler-interface-bin-0.13.6.jar
[error] 
[error]   last tree to typer: Select(This(object Scalakata), StartArgs)
[error]               symbol: object StartArgs in object Scalakata (flags: <module> <synthetic> <triedcooking>)
[error]    symbol definition: object StartArgs
[error]                  tpe: com.scalakata.Scalakata.StartArgs.type
[error]        symbol owners: object StartArgs -> object Scalakata -> package scalakata
[error]       context owners: method readResolve -> object StartArgs -> object Scalakata -> package scalakata
[error] 
[error] == Enclosing template or block ==
[error] 
[error] DefDef( // private def readResolve(): Object in object StartArgs
[error]   <method> private <synthetic>
[error]   "readResolve"
[error]   []
[error]   List(Nil)
[error]   <tpt> // tree.tpe=Object
[error]   Scalakata.this."StartArgs" // object StartArgs in object Scalakata, tree.tpe=com.scalakata.Scalakata.StartArgs.type
[error] )
[error] 
[error] == Expanded type of tree ==
[error] 
[error] TypeRef(
[error]   pre = ThisType(object Scalakata)
[error]   TypeSymbol(
[error]     class StartArgs extends AbstractFunction7[Int,Seq[java.io.File],String,Int,Boolean,Boolean,Seq[String],com.scalakata.Scalakata.StartArgs] with Serializable
[error]     
[error]   )
[error] )
[error] 
[error] uncaught exception during compilation: scala.tools.nsc.interactive.RangePositions$ValidateException
[trace] Stack trace suppressed: run last compile:compile for the full output.
[error] (compile:compile) scala.tools.nsc.interactive.RangePositions$ValidateException: Synthetic tree [7215] contains nonsynthetic tree [7214]
[error] Total time: 1 s, completed 12-Oct-2014 9:23:19 PM
```

> > last compile:compile

```
 uncaught exception during compilation: scala.tools.nsc.interactive.RangePositions$ValidateException
scala.tools.nsc.interactive.RangePositions$ValidateException: Synthetic tree [7215] contains nonsynthetic tree [7214]
    at scala.tools.nsc.interactive.RangePositions$class.positionError$1(RangePositions.scala:201)
    at scala.tools.nsc.interactive.RangePositions$class.validate$1(RangePositions.scala:218)
    at scala.tools.nsc.interactive.RangePositions$class.validate$1(RangePositions.scala:241)
    at scala.tools.nsc.interactive.RangePositions$class.validate$1(RangePositions.scala:241)
    at scala.tools.nsc.interactive.RangePositions$class.validate$1(RangePositions.scala:241)
    at scala.tools.nsc.interactive.RangePositions$class.validate$1(RangePositions.scala:241)
    at scala.tools.nsc.interactive.RangePositions$class.validate$1(RangePositions.scala:241)
    at scala.tools.nsc.interactive.RangePositions$class.validate$1(RangePositions.scala:241)
    at scala.tools.nsc.interactive.RangePositions$class.validate$1(RangePositions.scala:241)
    at scala.tools.nsc.interactive.RangePositions$class.validate$1(RangePositions.scala:241)
    at scala.tools.nsc.interactive.RangePositions$class.validatePositions(RangePositions.scala:246)
    at xsbt.CachedCompiler0$$anon$1.validatePositions(CompilerInterface.scala:150)
    at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:100)
    at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:464)
    at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:91)
    at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:91)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:91)
    at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1583)
    at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1557)
    at scala.tools.nsc.Global$Run.compileSources(Global.scala:1553)
    at scala.tools.nsc.Global$Run.compile(Global.scala:1662)
    at xsbt.CachedCompiler0.run(CompilerInterface.scala:116)
    at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
    at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
    at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
    at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:41)
    at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.apply$mcV$sp(AggressiveCompile.scala:97)
    at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.apply(AggressiveCompile.scala:97)
    at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.apply(AggressiveCompile.scala:97)
    at sbt.compiler.AggressiveCompile.sbt$compiler$AggressiveCompile$$timed(AggressiveCompile.scala:162)
    at sbt.compiler.AggressiveCompile$$anonfun$3.compileScala$1(AggressiveCompile.scala:96)
    at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:139)
    at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:86)
    at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:38)
    at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:36)
    at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:31)
    at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:39)
    at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:38)
    at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:66)
    at sbt.inc.Incremental$.compile(Incremental.scala:38)
    at sbt.inc.IncrementalCompile$.apply(Compile.scala:26)
    at sbt.compiler.AggressiveCompile.compile2(AggressiveCompile.scala:153)
    at sbt.compiler.AggressiveCompile.compile1(AggressiveCompile.scala:70)
    at sbt.compiler.AggressiveCompile.apply(AggressiveCompile.scala:45)
    at sbt.Compiler$.apply(Compiler.scala:74)
    at sbt.Compiler$.apply(Compiler.scala:65)
    at sbt.Defaults$.sbt$Defaults$$compileTaskImpl(Defaults.scala:777)
    at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:769)
    at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:769)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] (compile:compile) scala.tools.nsc.interactive.RangePositions$ValidateException: Synthetic tree [7215] contains nonsynthetic tree [7214]
```

**Comment by MasseGuillaume** [comment]
``` scala
unmanagedResourceDirectories in Backend <++= (unmanagedResourceDirectories in Kata)
```

yield similar compiler crash

**Comment by MasseGuillaume** [comment]
sbt.version = 0.13.6

**Comment by MasseGuillaume** [comment]
hum everything in the form

``` scala
key in Config1 := (key in Config2).value
// and other ops (+=, ++=, ...)
```

crashes

**Comment by MasseGuillaume** [comment]
hum I had range position scalac options turned on (-Yrangepos).

**Comment by eed3si9n** [comment]
So is this issue to do with sbt or range position?

**Comment by MasseGuillaume** [comment]
@eed3si9n with sbt when range position is On

https://github.com/MasseGuillaume/ScalaKata/tree/develop/Plugin
