### ISSUE TITLE
0.13.7-M3 + Play 2.3.5 + withCachedResolution

### ISSUE THREAD

**Issue by ghost** [sbt/sbt#1679]
Not sure if I should post here or at the playframework project.

Sbt: 0.13.7-M3
Scala: 2.11.2
Play: 2.3.5

``` scala
import play.PlayScala
import sbt._
import sbt.Keys._

object ApplicationBuild extends Build {

  val appDependenciesResolvers = Seq(
    "Typesafe Repository" at "http://repo.typesafe.com/typesafe/releases/",
    "Sonatype Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots/"
  )

  val main = Project("main", file("."))
    .enablePlugins(PlayScala)
    .settings(
      resolvers ++= appDependenciesResolvers,
      updateOptions ~= {_.withCachedResolution(true)},
      scalaVersion := "2.11.2",
      doc in Compile <<= target.map(_ / "none")
    )

}
```

Throws exception;

```
[main] $ run
[info] Updating {file:/Users/mark/Projects/test-project/}main...
[info] :: resolving dependencies :: org.scala-sbt.temp#temp-resolve-4eaae06905cddc4c510c340abfce50cc215a9998;1.0
[info]  confs: [compile, runtime, test, provided, optional, compile-internal, runtime-internal, test-internal, plugin, sources, docs, pom, scala-tool]
[info] Resolving org.reactivemongo#reactivemongo_2.11;0.10.5.akka23-SNAPSHOT ...
[info]  found org.reactivemongo#reactivemongo_2.11;0.10.5.akka23-SNAPSHOT in sbt-chain
[info] Resolving org.scala-lang#scala-library;2.11.1 ...
[info]  found org.scala-lang#scala-library;2.11.1 in sbt-chain
[info]  [2.11.1] org.scala-lang#scala-library;2.11.1
[info] Resolving org.reactivemongo#reactivemongo-bson-macros_2.11;0.10.5.akka23-SNAPSHOT ...
[info]  found org.reactivemongo#reactivemongo-bson-macros_2.11;0.10.5.akka23-SNAPSHOT in sbt-chain
[info] Resolving org.scala-lang#scala-compiler;2.11.1 ...
[info]  found org.scala-lang#scala-compiler;2.11.1 in sbt-chain
[info] Resolving org.scala-lang#scala-reflect;2.11.1 ...
[info]  found org.scala-lang#scala-reflect;2.11.1 in sbt-chain
[info]  [2.11.1] org.scala-lang#scala-reflect;2.11.1
[info] Resolving org.scala-lang.modules#scala-xml_2.11;1.0.2 ...
[info]  found org.scala-lang.modules#scala-xml_2.11;1.0.2 in sbt-chain
[info] Resolving org.scala-lang.modules#scala-parser-combinators_2.11;1.0.1 ...
[info]  found org.scala-lang.modules#scala-parser-combinators_2.11;1.0.1 in sbt-chain
[info] Resolving org.reactivemongo#reactivemongo-bson_2.11;0.10.5.akka23-SNAPSHOT ...
[info]  found org.reactivemongo#reactivemongo-bson_2.11;0.10.5.akka23-SNAPSHOT in sbt-chain
[info] Resolving io.netty#netty;3.6.5.Final ...
[info]  found io.netty#netty;3.6.5.Final in sbt-chain
[info] Resolving com.typesafe.akka#akka-actor_2.11;2.3.3 ...
[info]  found com.typesafe.akka#akka-actor_2.11;2.3.3 in sbt-chain
[info] Resolving com.typesafe#config;1.2.1 ...
[info]  found com.typesafe#config;1.2.1 in sbt-chain
[info] Resolving com.typesafe.play#play-iteratees_2.11;2.3.0 ...
[info]  found com.typesafe.play#play-iteratees_2.11;2.3.0 in sbt-chain
[info] Resolving org.scala-stm#scala-stm_2.11;0.7 ...
[info]  found org.scala-stm#scala-stm_2.11;0.7 in sbt-chain
[info] Resolving org.apache.logging.log4j#log4j-api;2.0-beta9 ...
[info]  found org.apache.logging.log4j#log4j-api;2.0-beta9 in sbt-chain
[info] Resolving org.apache.logging.log4j#log4j-core;2.0-beta9 ...
[info]  found org.apache.logging.log4j#log4j-core;2.0-beta9 in sbt-chain
[info] :: resolution report :: resolve 5005ms :: artifacts dl 4ms
[info]  :: modules in use:
[info]  com.typesafe#config;1.2.1 from sbt-chain in [compile, runtime, test, compile-internal, runtime-internal, test-internal]
[info]  com.typesafe.akka#akka-actor_2.11;2.3.3 from sbt-chain in [compile, runtime, test, compile-internal, runtime-internal, test-internal]
[info]  com.typesafe.play#play-iteratees_2.11;2.3.0 from sbt-chain in [compile, runtime, test, compile-internal, runtime-internal, test-internal]
[info]  io.netty#netty;3.6.5.Final from sbt-chain in [compile, runtime, test, compile-internal, runtime-internal, test-internal]
[info]  org.apache.logging.log4j#log4j-api;2.0-beta9 from sbt-chain in [compile, runtime, test, compile-internal, runtime-internal, test-internal]
[info]  org.apache.logging.log4j#log4j-core;2.0-beta9 from sbt-chain in [compile, runtime, test, compile-internal, runtime-internal, test-internal]
[info]  org.reactivemongo#reactivemongo-bson-macros_2.11;0.10.5.akka23-SNAPSHOT from sbt-chain in [compile, runtime, test, compile-internal, runtime-internal, test-internal]
[info]  org.reactivemongo#reactivemongo-bson_2.11;0.10.5.akka23-SNAPSHOT from sbt-chain in [compile, runtime, test, compile-internal, runtime-internal, test-internal]
[info]  org.reactivemongo#reactivemongo_2.11;0.10.5.akka23-SNAPSHOT from sbt-chain in [compile, runtime, test, compile-internal, runtime-internal, test-internal]
[info]  org.scala-lang#scala-compiler;2.11.1 from sbt-chain in [compile, runtime, test, compile-internal, runtime-internal, test-internal]
[info]  org.scala-lang#scala-library;2.11.1 from sbt-chain in [compile, runtime, test, compile-internal, runtime-internal, test-internal]
[info]  org.scala-lang#scala-reflect;2.11.1 from sbt-chain in [compile, runtime, test, compile-internal, runtime-internal, test-internal]
[info]  org.scala-lang.modules#scala-parser-combinators_2.11;1.0.1 from sbt-chain in [compile, runtime, test, compile-internal, runtime-internal, test-internal]
[info]  org.scala-lang.modules#scala-xml_2.11;1.0.2 from sbt-chain in [compile, runtime, test, compile-internal, runtime-internal, test-internal]
[info]  org.scala-stm#scala-stm_2.11;0.7 from sbt-chain in [compile, runtime, test, compile-internal, runtime-internal, test-internal]
[info]  :: evicted modules:
[info]  org.scala-lang#scala-library;2.11.0 by [org.scala-lang#scala-library;2.11.1] in [test-internal, test, compile, runtime, runtime-internal, compile-internal]
[info]  com.typesafe#config;1.2.0 by [com.typesafe#config;1.2.1] in [test-internal, test, compile, runtime, runtime-internal, compile-internal]
[info]  ---------------------------------------------------------------------
[info]  |                  |            modules            ||   artifacts   |
[info]  |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[info]  ---------------------------------------------------------------------
[info]  |      compile     |   17  |   3   |   0   |   2   ||   17  |   0   |
[info]  |      runtime     |   17  |   3   |   0   |   2   ||   17  |   0   |
[info]  |       test       |   17  |   3   |   0   |   2   ||   17  |   0   |
[info]  |     provided     |   0   |   0   |   0   |   0   ||   0   |   0   |
[info]  |     optional     |   0   |   0   |   0   |   0   ||   0   |   0   |
[info]  | compile-internal |   17  |   3   |   0   |   2   ||   17  |   0   |
[info]  | runtime-internal |   17  |   3   |   0   |   2   ||   17  |   0   |
[info]  |   test-internal  |   17  |   3   |   0   |   2   ||   17  |   0   |
[info]  |      plugin      |   0   |   0   |   0   |   0   ||   0   |   0   |
[info]  |      sources     |   0   |   0   |   0   |   0   ||   0   |   0   |
[info]  |       docs       |   0   |   0   |   0   |   0   ||   0   |   0   |
[info]  |        pom       |   0   |   0   |   0   |   0   ||   0   |   0   |
[info]  |    scala-tool    |   0   |   0   |   0   |   0   ||   0   |   0   |
[info]  ---------------------------------------------------------------------
[info] Done updating.
[warn] Scala version was updated by one of library dependencies:
[warn]  * org.scala-lang:scala-library:(2.11.2, 2.11.0) -> 2.11.1
[warn] To force scalaVersion, add the following:
[warn]  ivyScala := ivyScala.value map { _.copy(overrideScalaVersion = true) }
[warn] Run 'evicted' to see detailed eviction warnings

Failed to instantiate [ch.qos.logback.classic.LoggerContext]
Reported exception:
java.lang.NoClassDefFoundError: ch/qos/logback/core/joran/spi/Pattern
    at ch.qos.logback.classic.joran.JoranConfigurator.addInstanceRules(JoranConfigurator.java:43)
    at ch.qos.logback.core.joran.GenericConfigurator.buildInterpreter(GenericConfigurator.java:116)
    at ch.qos.logback.core.joran.JoranConfiguratorBase.buildInterpreter(JoranConfiguratorBase.java:103)
    at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:146)
    at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
    at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
    at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
    at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
    at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:148)
    at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
    at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
    at org.slf4j.LoggerFactory.bind(LoggerFactory.java:121)
    at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:111)
    at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:268)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:241)
    at play.api.Logger$.<init>(Logger.scala:182)
    at play.api.Logger$.<clinit>(Logger.scala)
    at play.core.ReloadableApplication.<init>(ApplicationProvider.scala:99)
    at play.core.server.NettyServer$$anonfun$mainDev$1.apply(NettyServer.scala:310)
    at play.core.server.NettyServer$$anonfun$mainDev$1.apply(NettyServer.scala:309)
    at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
    at play.core.server.NettyServer$.mainDev(NettyServer.scala:308)
    at play.core.server.NettyServer$.mainDevHttpMode(NettyServer.scala:304)
    at play.core.server.NettyServer.mainDevHttpMode(NettyServer.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at play.PlayRun$class.play$PlayRun$$startDevMode(PlayRun.scala:318)
    at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.devModeServer$lzycompute$1(PlayRun.scala:102)
    at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.play$PlayRun$class$$anonfun$$anonfun$$anonfun$$devModeServer$1(PlayRun.scala:102)
    at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:124)
    at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:95)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.core.joran.spi.Pattern
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 50 more
java.lang.NoClassDefFoundError: ch/qos/logback/core/joran/spi/Pattern
    at ch.qos.logback.classic.joran.JoranConfigurator.addInstanceRules(JoranConfigurator.java:43)
    at ch.qos.logback.core.joran.GenericConfigurator.buildInterpreter(GenericConfigurator.java:116)
    at ch.qos.logback.core.joran.JoranConfiguratorBase.buildInterpreter(JoranConfiguratorBase.java:103)
    at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:146)
    at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
    at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
    at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
    at play.api.Logger$$anonfun$configure$3.apply(Logger.scala:256)
    at play.api.Logger$$anonfun$configure$3.apply(Logger.scala:256)
    at scala.Option.foreach(Option.scala:245)
    at play.api.Logger$.configure(Logger.scala:256)
    at play.core.ReloadableApplication.<init>(ApplicationProvider.scala:99)
    at play.core.server.NettyServer$$anonfun$mainDev$1.apply(NettyServer.scala:310)
    at play.core.server.NettyServer$$anonfun$mainDev$1.apply(NettyServer.scala:309)
    at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
    at play.core.server.NettyServer$.mainDev(NettyServer.scala:308)
    at play.core.server.NettyServer$.mainDevHttpMode(NettyServer.scala:304)
    at play.core.server.NettyServer.mainDevHttpMode(NettyServer.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at play.PlayRun$class.play$PlayRun$$startDevMode(PlayRun.scala:318)
    at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.devModeServer$lzycompute$1(PlayRun.scala:102)
    at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.play$PlayRun$class$$anonfun$$anonfun$$anonfun$$devModeServer$1(PlayRun.scala:102)
    at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:124)
    at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:95)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) java.lang.reflect.InvocationTargetException
[error] Total time: 5 s, completed 16-Oct-2014 12:07:35
```

**Comment by eed3si9n** [comment]
Seems like a regression on sbt. Thanks for the report!

**Comment by eed3si9n** [comment]
I could not reproduce this. What's weird is the "module in use" you quoted:

```
[info]  :: modules in use:
[info]  com.typesafe#config;1.2.1 from sbt-chain in [compile, runtime, test, compile-internal, runtime-internal, test-internal]
[info]  com.typesafe.akka#akka-actor_2.11;2.3.3 from sbt-chain in [compile, runtime, test, compile-internal, runtime-internal, test-internal]
[info]  com.typesafe.play#play-iteratees_2.11;2.3.0 from sbt-chain in [compile, runtime, test, compile-internal, runtime-internal, test-internal]
[info]  io.netty#netty;3.6.5.Final from sbt-chain in [compile, runtime, test, compile-internal, runtime-internal, test-internal]
[info]  org.apache.logging.log4j#log4j-api;2.0-beta9 from sbt-chain in [compile, runtime, test, compile-internal, runtime-internal, test-internal]
[info]  org.apache.logging.log4j#log4j-core;2.0-beta9 from sbt-chain in [compile, runtime, test, compile-internal, runtime-internal, test-internal]
[info]  org.reactivemongo#reactivemongo-bson-macros_2.11;0.10.5.akka23-SNAPSHOT from sbt-chain in [compile, runtime, test, compile-internal, runtime-internal, test-internal]
[info]  org.reactivemongo#reactivemongo-bson_2.11;0.10.5.akka23-SNAPSHOT from sbt-chain in [compile, runtime, test, compile-internal, runtime-internal, test-internal]
[info]  org.reactivemongo#reactivemongo_2.11;0.10.5.akka23-SNAPSHOT from sbt-chain in [compile, runtime, test, compile-internal, runtime-internal, test-internal]
[info]  org.scala-lang#scala-compiler;2.11.1 from sbt-chain in [compile, runtime, test, compile-internal, runtime-internal, test-internal]
[info]  org.scala-lang#scala-library;2.11.1 from sbt-chain in [compile, runtime, test, compile-internal, runtime-internal, test-internal]
[info]  org.scala-lang#scala-reflect;2.11.1 from sbt-chain in [compile, runtime, test, compile-internal, runtime-internal, test-internal]
[info]  org.scala-lang.modules#scala-parser-combinators_2.11;1.0.1 from sbt-chain in [compile, runtime, test, compile-internal, runtime-internal, test-internal]
[info]  org.scala-lang.modules#scala-xml_2.11;1.0.2 from sbt-chain in [compile, runtime, test, compile-internal, runtime-internal, test-internal]
[info]  org.scala-stm#scala-stm_2.11;0.7 from sbt-chain in [compile, runtime, test, compile-internal, runtime-internal, test-internal]
```

is much shorter than the one my project produced, which includes

```
[info]  ch.qos.logback#logback-classic;1.1.1 from sbt-chain in [test, test-internal]
[info]  ch.qos.logback#logback-core;1.1.1 from sbt-chain in [test, test-internal]
```

I wonder if there's some mixup in the way sbt is calculating the direct dependencies.
Do you happen to have any other project on your machine that uses akka actor and reactivemongo?

**Comment by jasonchaffee** [comment]
I am seeing same types of issues with some of my projects, but failing on different dependencies.  It seems when I set withCachedResolution to true, the dependency graph ends up being different then if I set it to false.  I haven't debugged much on it to this point, but it definitely causes the dependency resolution to change whereas I would expect it to be the same, just cached.

**Comment by ghost** [comment]
Good point @eed3si9n. I had some dependencies in my project and seems I didn't test it quite well. Did a rerun and incrementally added some of our dependencies. I found out that;

`"net.logstash.logback" % "logstash-logback-encoder" % "1.3"` was causing the trouble. Upgraded to 3.3 and it was fixed.

**Comment by eed3si9n** [comment]
I was able to reproduce slf4j getting mutually evicted with cached resolution. see #1710
