### ISSUE TITLE
Unresolved dependencies

### ISSUE THREAD

**Issue by jvanz** [sbt/sbt#1690]
Hi

I'm trying the compile the [spark-cassandra-connector](https://github.com/datastax/spark-cassandra-connector), more especially the the tag v1.0.3. But every time I try compile the sbt shows the following problem:

```
[vanz@odin spark-cassandra-connector]$ sbt

[info] Loading project definition from /home/vanz/repos/spark-cassandra-connector/project
[info] Updating {file:/home/vanz/repos/spark-cassandra-connector/project/}spark-cassandra-connector-build...
[info] Resolving org.scala-lang#scala-reflect;2.10.3 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scala-lang#scala-library;2.10.3: configuration not found in org.scala-lang#scala-library;2.10.3: 'compile'. It was required from com.jsuereth#gpg-library_2.10;0.8.3 compile
[warn]  :: com.jcraft#jsch;0.1.46: configuration not found in com.jcraft#jsch;0.1.46: 'compile'. It was required from org.scala-sbt#ivy;0.13.5 compile
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
sbt.ResolveException: unresolved dependency: org.scala-lang#scala-library;2.10.3: configuration not found in org.scala-lang#scala-library;2.10.3: 'compile'. It was required from com.jsuereth#gpg-library_2.10;0.8.3 compile
unresolved dependency: com.jcraft#jsch;0.1.46: configuration not found in com.jcraft#jsch;0.1.46: 'compile'. It was required from org.scala-sbt#ivy;0.13.5 compile
    at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:213)
    at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:122)
    at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:121)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:116)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:116)
    at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:104)
    at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:51)
    at sbt.IvySbt$$anon$3.call(Ivy.scala:60)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:98)
    at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:81)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:102)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:102)
    at xsbt.boot.Using$.withResource(Using.scala:11)
    at xsbt.boot.Using$.apply(Using.scala:10)
    at xsbt.boot.Locks$GlobalLock.withFileLock(Locks.scala:102)
    at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:62)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:52)
    at xsbt.boot.Locks$.apply0(Locks.scala:38)
    at xsbt.boot.Locks$.apply(Locks.scala:28)
    at sbt.IvySbt.withDefaultLogger(Ivy.scala:60)
    at sbt.IvySbt.withIvy(Ivy.scala:101)
    at sbt.IvySbt.withIvy(Ivy.scala:97)
    at sbt.IvySbt$Module.withModule(Ivy.scala:116)
    at sbt.IvyActions$.update(IvyActions.scala:121)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1161)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1159)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$73.apply(Defaults.scala:1182)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$73.apply(Defaults.scala:1180)
    at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1184)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1179)
    at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
    at sbt.Classpaths$.cachedUpdate(Defaults.scala:1187)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1152)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1130)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
    at sbt.std.Transform$$anon$4.work(System.scala:64)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.Execute.work(Execute.scala:244)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: org.scala-lang#scala-library;2.10.3: configuration not found in org.scala-lang#scala-library;2.10.3: 'compile'. It was required from com.jsuereth#gpg-library_2.10;0.8.3 compile
[error] unresolved dependency: com.jcraft#jsch;0.1.46: configuration not found in com.jcraft#jsch;0.1.46: 'compile'. It was required from org.scala-sbt#ivy;0.13.5 compile

Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
```

I installed the scala and sbt using yum and there is no changes in the sources. What is wrong with my environment?

**Comment by jsuereth** [comment]
I hate to do this, but could you snipe the ivy cache of the dependencies which are complaining?  Specifically, there should be a directory for both of those libraries.

Basic gist:
- Ivy attempts to convert Maven POM.xml files into ivy.xml files.
- We recently "fixed" some of this translation, where Ivy would "leak" configurations from maven all over the place
- While this _shouldn't_ be the case, your existing Ivy cache may hold stale translated ivy.xml files

If this is the case, we'll have to look into adding a workaround for this specific issue.   Additionally, once you clear the cache, it shouldn't reoccur unless you swap up/down sbt versions.

**Comment by jvanz** [comment]
Actually I already have tried to delete my cache ( .sbt and .ivy2 ) but the problem persist.
My current cache directories ( .sbt and .ivy2 ) are: https://gist.github.com/guilhermesft/55b01ab3c0baf0955ec0
Is this what all do you need? How can I help you to solve the problem?

**Comment by jsuereth** [comment]
hmm, I'm getting this locally:

```
[warn] io problem while parsing ivy file: http://localhost:8081/artifactory/releases/org/apache/httpcomponents/httpclient/4.2.5/httpclient-4.2.5.pom: Impossible to load parent for file:/home/jsuereth/.ivy2/cache/org.apache.httpcomponents/httpclient/ivy-4.2.5.xml.original. Parent=org.apache.httpcomponents#httpcomponents-client;4.2.5
```

Now, I just bumped to sbt 0.13.7-RC1 and our fixes here appear to have worked. However, you have to delete the cache beause the failed parent-download will actually CORRUPT your ivy cache, and it's hard for us to detect/remove that automatically (yay ivy).

**Comment by zewemli** [comment]
I ran into the same error with Fedora 20. Removing ~/.sbt and ~/.ivy2 fixed the issue.

**Comment by jvanz** [comment]
Well, remove the ~/.sbt and ~/.ivy2 did not work for me. But, I updated the sbt and the problem gone away. =]

**Comment by agarnitin86** [comment]
Hi, 
I am also getting the following exception : [error] sbt.ResolveException: unresolved dependency: org.apache.spark#spark-parent_2.11_2.11;1.4.0: not found
I tried removing .sbt and .ivy2, and also update. 
Didnt work for me

**Comment by aziflaj** [comment]
I'm facing the same issue when executing `./sbt` on lift mvc

```
sbt.ResolveException: unresolved dependency: org.scala-lang#scala-library;2.10.3: configuration not found in org.scala-lang#scala-library;2.10.3: 'compile'. It was required from default#lift_mvc-build;0.1-SNAPSHOT provided
```

**Comment by djx314** [comment]
I  use jbpm and add the dependencies

``` scala
"org.jbpm" % "jbpm-test" % "6.3.0.Final"
```

and catch the error

```
[info] Updating {file:/home/djx314/pro/opensource/enkidu/}enkidu-order...
[info] Resolving com.fasterxml.jackson.datatype#jackson-datatype-jsr310;2.7.1 ..[info] Resolving com.typesafe.play#play-akka-http-server-experimental_2.11;2.5.0[info] Resolving org.jboss.dashboard-builder#dashboard-builder-bom;6.3.0.Final .[info] Resolving org.jboss.dashboard-builder#dashboard-builder-bom;6.3.0.Final ...
[warn] io problem while parsing ivy file: http://repo1.maven.org/maven2/org/kie/kie-platform-bom/6.3.0.Final/kie-platform-bom-6.3.0.Final.pom: Impossible to import module for file:/home/djx314/pro/kuaipan/x32editor/sbtIvy/cache/org.kie/kie-platform-bom/ivy-6.3.0.Final.xml.original. Import=org.jboss.dashboard-builder#dashboard-builder-bom;6.3.0.Final
[warn] io problem while parsing ivy file: http://repo1.maven.org/maven2/org/kie/kie-parent-with-dependencies/6.3.0.Final/kie-parent-with-dependencies-6.3.0.Final.pom: Impossible to import module for file:/home/djx314/pro/kuaipan/x32editor/sbtIvy/cache/org.kie/kie-parent-with-dependencies/ivy-6.3.0.Final.xml.original. Import=org.kie#kie-platform-bom;6.3.0.Final
[warn] io problem while parsing ivy file: http://repo1.maven.org/maven2/org/jbpm/jbpm/6.3.0.Final/jbpm-6.3.0.Final.pom: Impossible to load parent for file:/home/djx314/pro/kuaipan/x32editor/sbtIvy/cache/org.jbpm/jbpm/ivy-6.3.0.Final.xml.original. Parent=org.kie#kie-parent-with-dependencies;6.3.0.Final
[warn] io problem while parsing ivy file: http://repo1.maven.org/maven2/org/jbpm/jbpm-test/6.3.0.Final/jbpm-test-6.3.0.Final.pom: Impossible to load parent for file:/home/djx314/pro/kuaipan/x32editor/sbtIvy/cache/org.jbpm/jbpm-test/ivy-6.3.0.Final.xml.original. Parent=org.jbpm#jbpm;6.3.0.Final
[warn]  module not found: org.jbpm#jbpm-test;6.3.0.Final
[warn] ==== local: tried
[warn]   /home/djx314/pro/kuaipan/x32editor/sbtIvy/local/org.jboss.dashboard-builder/dashboard-builder-bom/6.3.0.Final/ivys/ivy.xml
[warn] ==== mavenRepoJX: tried
[warn]   http://repo1.maven.org/maven2/org/jboss/dashboard-builder/dashboard-builder-bom/6.3.0.Final/dashboard-builder-bom-6.3.0.Final.pom
[warn] ==== bintray/non: tried
[warn]   http://dl.bintray.com/non/maven/org/jbpm/jbpm-test/6.3.0.Final/jbpm-test-6.3.0.Final.pom
[warn] ==== aa: tried
[warn]   https://oss.sonatype.org/service/local/repositories/snapshots/content/org/jbpm/jbpm-test/6.3.0.Final/jbpm-test-6.3.0.Final.pom
[warn] ==== typesafe-ivy: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/org.jbpm/jbpm-test/6.3.0.Final/ivys/ivy.xml
[info] Resolving org.eclipse.jetty.websocket#websocket-client;9.2.15.v20160210 .[info] Resolving org.eclipse.jetty.websocket#websocket-common;9.2.15.v20160210 .[info] Resolving jline#jline;2.12.1 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.jbpm#jbpm-test;6.3.0.Final: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]      org.jbpm:jbpm-test:6.3.0.Final (/home/djx314/pro/opensource/enkidu/build.sbt#L69)
[warn]        +- enkidu-order:enkidu-order_2.11:0.0.1
[trace] Stack trace suppressed: run last enkidu-order/*:update for the full output.
[error] (enkidu-order/*:update) sbt.ResolveException: unresolved dependency: org.jbpm#jbpm-test;6.3.0.Final: not found
[info] Resolving com.typesafe.play#play-akka-http-server-experimental_2.11;2.5.0[info] Resolving com.fasterxml.jackson.datatype#jackson-datatype-jsr310;2.7.1 ..[info] Resolving org.eclipse.jetty.websocket#websocket-client;9.2.15.v20160210 .[info] Resolving org.eclipse.jetty.websocket#websocket-common;9.2.15.v20160210 .[info] Resolving org.eclipse.jetty.websocket#websocket-client;9.2.15.v20160210 .[info] Resolving com.typesafe.play#play-akka-http-server-experimental_2.11;2.5.0[info] Resolving org.eclipse.jetty.websocket#websocket-common;9.2.15.v20160210 .[info] Resolving com.fasterxml.jackson.datatype#jackson-datatype-jsr310;2.7.1 ..[info] Resolving com.typesafe.play#play-akka-http-server-experimental_2.11;2.5.0[info] Resolving com.fasterxml.jackson.datatype#jackson-datatype-jsr310;2.7.1 ..[info] Resolving org.eclipse.jetty.websocket#websocket-client;9.2.15.v20160210 .[info] Resolving org.eclipse.jetty.websocket#websocket-common;9.2.15.v20160210 .[info] Resolving jline#jline;2.12.1 ...
[error] Could not create Eclipse project files:
[error] Error evaluating task 'scalacOptions': error
[error] Error evaluating task 'externalDependencyClasspath': error
[error] Error evaluating task 'update': error
[error] Error evaluating task 'updateClassifiers': error
[error] Error evaluating task 'scalacOptions': error
[error] Error evaluating task 'externalDependencyClasspath': error
[error] Error evaluating task 'update': error
[error] Error evaluating task 'updateClassifiers': error
[enkidu] $ 
```

**Comment by djx314** [comment]
I already remove ~/.sbt and my local ivy repo and download all the dependencies again. But the problem is still here.

**Comment by dmitryaleks** [comment]
Removing ~/.sbt and ~/.ivy2 fixed the issue for me as well under Fedora 24.

**Comment by c1316** [comment]
I remove  ~/.sbt and ~/.ivy2, and I  reinstall sbt . then my problem is solved ,you can try that

**Comment by jannvck** [comment]
I am facing the same issue with the dependency:

```
"edu.stanford.swrl" % "swrlapi-drools-engine" % "1.1.3"
```

Removing ~/.sbt and ~/.ivy2 and reinstalling SBT 0.13.13 made no difference. The dependency resolution fails again:

```
[info] Updating {file:/disk/sim/home/novacek/dev/workspace/de.fzi.autoswift.swrl/}de-fzi-autoswift-swrl...
[info] Resolving org.jboss.dashboard-builder#dashboard-builder-bom;6.4.0.Final ...
[warn] io problem while parsing ivy file: https://repo1.maven.org/maven2/org/kie/kie-platform-bom/6.4.0.Final/kie-platform-bom-6.4.0.Final.pom: Impossible to import module for file:/disk/sim/home/novacek/.ivy2/cache/org.kie/kie-platform-bom/ivy-6.4.0.Final.xml.original. Import=org.jboss.dashboard-builder#dashboard-builder-bom;6.4.0.Final
[warn] io problem while parsing ivy file: https://repo1.maven.org/maven2/org/kie/kie-parent-with-dependencies/6.4.0.Final/kie-parent-with-dependencies-6.4.0.Final.pom: Impossible to import module for file:/disk/sim/home/novacek/.ivy2/cache/org.kie/kie-parent-with-dependencies/ivy-6.4.0.Final.xml.original. Import=org.kie#kie-platform-bom;6.4.0.Final
[warn] io problem while parsing ivy file: https://repo1.maven.org/maven2/org/drools/droolsjbpm-integration/6.4.0.Final/droolsjbpm-integration-6.4.0.Final.pom: Impossible to load parent for file:/disk/sim/home/novacek/.ivy2/cache/org.drools/droolsjbpm-integration/ivy-6.4.0.Final.xml.original. Parent=org.kie#kie-parent-with-dependencies;6.4.0.Final
[warn] io problem while parsing ivy file: https://repo1.maven.org/maven2/org/drools/drools-osgi/6.4.0.Final/drools-osgi-6.4.0.Final.pom: Impossible to load parent for file:/disk/sim/home/novacek/.ivy2/cache/org.drools/drools-osgi/ivy-6.4.0.Final.xml.original. Parent=org.drools#droolsjbpm-integration;6.4.0.Final
[warn] io problem while parsing ivy file: https://repo1.maven.org/maven2/org/drools/drools-osgi-integration/6.4.0.Final/drools-osgi-integration-6.4.0.Final.pom: Impossible to load parent for file:/disk/sim/home/novacek/.ivy2/cache/org.drools/drools-osgi-integration/ivy-6.4.0.Final.xml.original. Parent=org.drools#drools-osgi;6.4.0.Final
[warn] 	module not found: org.drools#drools-osgi-integration;6.4.0.Final
[warn] ==== local: tried
[warn]   /disk/sim/home/novacek/.ivy2/local/org.jboss.dashboard-builder/dashboard-builder-bom/6.4.0.Final/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/jboss/dashboard-builder/dashboard-builder-bom/6.4.0.Final/dashboard-builder-bom-6.4.0.Final.pom
[info] Resolving org.jboss.dashboard-builder#dashboard-builder-bom;6.4.0.Final ...
[warn] io problem while parsing ivy file: https://repo1.maven.org/maven2/org/kie/kie-platform-bom/6.4.0.Final/kie-platform-bom-6.4.0.Final.pom: Impossible to import module for file:/disk/sim/home/novacek/.ivy2/cache/org.kie/kie-platform-bom/ivy-6.4.0.Final.xml.original. Import=org.jboss.dashboard-builder#dashboard-builder-bom;6.4.0.Final
[warn] io problem while parsing ivy file: https://repo1.maven.org/maven2/org/kie/kie-parent-with-dependencies/6.4.0.Final/kie-parent-with-dependencies-6.4.0.Final.pom: Impossible to import module for file:/disk/sim/home/novacek/.ivy2/cache/org.kie/kie-parent-with-dependencies/ivy-6.4.0.Final.xml.original. Import=org.kie#kie-platform-bom;6.4.0.Final
[warn] io problem while parsing ivy file: https://repo1.maven.org/maven2/org/drools/drools/6.4.0.Final/drools-6.4.0.Final.pom: Impossible to load parent for file:/disk/sim/home/novacek/.ivy2/cache/org.drools/drools/ivy-6.4.0.Final.xml.original. Parent=org.kie#kie-parent-with-dependencies;6.4.0.Final
[warn] io problem while parsing ivy file: https://repo1.maven.org/maven2/org/drools/knowledge-api/6.4.0.Final/knowledge-api-6.4.0.Final.pom: Impossible to load parent for file:/disk/sim/home/novacek/.ivy2/cache/org.drools/knowledge-api/ivy-6.4.0.Final.xml.original. Parent=org.drools#drools;6.4.0.Final
[warn] 	module not found: org.drools#knowledge-api;6.4.0.Final
[warn] ==== local: tried
[warn]   /disk/sim/home/novacek/.ivy2/local/org.jboss.dashboard-builder/dashboard-builder-bom/6.4.0.Final/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/jboss/dashboard-builder/dashboard-builder-bom/6.4.0.Final/dashboard-builder-bom-6.4.0.Final.pom
...
(no errors/warnings in between)
...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.drools#drools-osgi-integration;6.4.0.Final: not found
[warn] 	:: org.drools#knowledge-api;6.4.0.Final: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.drools:drools-osgi-integration:6.4.0.Final
[warn] 		  +- edu.stanford.swrl:swrlapi-drools-engine:1.1.3 (/disk/sim/home/novacek/dev/workspace/de.fzi.autoswift.swrl/build.sbt#L1-2)
[warn] 		  +- default:de-fzi-autoswift-swrl_2.10:0.1-SNAPSHOT
[warn] 		org.drools:knowledge-api:6.4.0.Final
[warn] 		  +- edu.stanford.swrl:swrlapi-drools-engine:1.1.3 (/disk/sim/home/novacek/dev/workspace/de.fzi.autoswift.swrl/build.sbt#L1-2)
[warn] 		  +- default:de-fzi-autoswift-swrl_2.10:0.1-SNAPSHOT
[trace] Stack trace suppressed: run last *:update for the full output.
[error] (*:update) sbt.ResolveException: unresolved dependency: org.drools#drools-osgi-integration;6.4.0.Final: not found
[error] unresolved dependency: org.drools#knowledge-api;6.4.0.Final: not found
[error] Total time: 44 s, completed 08.12.2016 11:05:34

**Comment by eed3si9n** [comment]
@jannvck Ivy is having trouble resolving the complicated POM file. 
Try adding `addMavenResolverPlugin` to `project/maven.sbt` and see if that could resolve it - http://www.scala-sbt.org/0.13/docs/sbt-0.13-Tech-Previews.html#Maven+resolver+plugin

**Comment by jannvck** [comment]
@eed3si9n Thank you very much! Adding `addMavenResolverPlugin` to `project/maven.sbt` resolved it.
