### ISSUE TITLE
[0.13.7-RC1] duplicate mappings error with cachedResolution set to true

### ISSUE THREAD

**Issue by jasonchaffee** [sbt/sbt#1705]
I get the following error in a play application when using cachedResolution:

```
Exception: sbt.TrapExitSecurityException thrown from the UncaughtExceptionHandler in thread "run-main-1"
java.lang.RuntimeException: Duplicate mappings:
    /scratch/jenkins/workspace/focus-app/target/web/public/test/public/lib/jquery/jquery.min.js
from
    /scratch/jenkins/workspace/focus-app/target/web/web-modules/main/webjars/lib/jquery/jquery.min.js
        /scratch/jenkins/workspace/focus-app/target/web/web-modules/test/webjars/lib/jquery/jquery.min.js
    /scratch/jenkins/workspace/focus-app/target/web/public/test/public/lib/jquery/jquery.js
from
    /scratch/jenkins/workspace/focus-app/target/web/web-modules/main/webjars/lib/jquery/jquery.js
        /scratch/jenkins/workspace/focus-app/target/web/web-modules/test/webjars/lib/jquery/jquery.js
    at scala.sys.package$.error(package.scala:27)
    at sbt.Sync$.noDuplicateTargets(Sync.scala:67)
    at sbt.Sync$$anonfun$apply$1.apply(Sync.scala:25)
    at sbt.Sync$$anonfun$apply$1.apply(Sync.scala:22)
    at com.typesafe.sbt.web.SbtWeb$.syncMappings(SbtWeb.scala:369)
    at com.typesafe.sbt.web.SbtWeb$$anonfun$projectSettings$31.apply(SbtWeb.scala:187)
    at com.typesafe.sbt.web.SbtWeb$$anonfun$projectSettings$31.apply(SbtWeb.scala:187)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:744)
[error] (web-assets-test:assets) Duplicate mappings:
[error]     /scratch/jenkins/workspace/focus-app/target/web/public/test/public/lib/jquery/jquery.min.js
[error] from
[error]     /scratch/jenkins/workspace/focus-app/target/web/web-modules/main/webjars/lib/jquery/jquery.min.js
[error]         /scratch/jenkins/workspace/focus-app/target/web/web-modules/test/webjars/lib/jquery/jquery.min.js
[error]     /scratch/jenkins/workspace/focus-app/target/web/public/test/public/lib/jquery/jquery.js
[error] from
[error]     /scratch/jenkins/workspace/focus-app/target/web/web-modules/main/webjars/lib/jquery/jquery.js
[error]         /scratch/jenkins/workspace/focus-app/target/web/web-modules/test/webjars/lib/jquery/jquery.js
[error] Total time: 8 s, completed Oct 30, 2014 4:38:30 PM
```

Also, I noticed the resolution isn't picking the correct version of webjars either.  I don't if this is related to the duplicate mappings or not, but I thought I would mention it here in case it is.

With cacheResolution set to false, I see this output:

```
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn]  * org.webjars:jquery:1.11.1 -> 2.1.1
[warn] Run 'evicted' to see detailed eviction warnings
```

With cacheRsolution set to true, I see this output:

```
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn]  * org.webjars:jquery:(2.1.1, 1.9.0, 1.9.1) -> 1.11.1
[warn] Run 'evicted' to see detailed eviction warnings
```

I have 2.1.1 in my build file and in dependencyOverrides.

**Comment by eed3si9n** [comment]
Could you try RC-2 that just came out?

**Comment by eed3si9n** [comment]
This was likely fixed in RC-2.

**Comment by jasonchaffee** [comment]
Yes.  I forgot to reply.  RC2 fixed the issue.
