### ISSUE TITLE
Error during sbt execution: java.io.IOException: Permission denied

### ISSUE THREAD

**Issue by jholmberg-cni** [sbt/sbt#172]
Hi!
I just downloaded sbt to try it out. I'm running on OS X Snow Leopard with Java 1.6_26 and Scala 2.9.0.1.  I've attempted to install sbt two different ways with the same outcome. 

The first was to follow the unix directions on the set up wiki page by placing the latest version of the sbt-launch.jar in my ~/bin folder and creating a shell script to launch it.  After setting the permissions on the script to be executable, I run the sbt command and get the following output:

```
Macintosh-5:~ jared$ sbt
java.io.IOException: Permission denied
    at java.io.UnixFileSystem.createFileExclusively(Native Method)
    at java.io.File.createNewFile(File.java:883)
    at xsbt.boot.Locks$.apply0(Locks.scala:34)
    at xsbt.boot.Locks$.apply(Locks.scala:27)
    at xsbt.boot.Update.apply(Pre.scala:78)
    at xsbt.boot.Provider$initialize.call(Provider.scala:34)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:47)
    at xsbt.boot.Locks$.apply0(Locks.scala:30)
    at xsbt.boot.Locks$.apply(Locks.scala:27)
    at scala.collection.Iterable$class.$init$(Proxy.scala:32)
    at xsbt.boot.Launch$JNAProvider.<init>(Launch.scala:93)
    at xsbt.boot.Launch.topLoader(Launch.scala:87)
    at xsbt.boot.Launch$ScalaProvider.parentLoader(Launch.scala:110)
    at xsbt.boot.Provider$initialize.createLoader(Provider.scala:57)
    at xsbt.boot.Provider$initialize.call(Provider.scala:34)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:69)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:73)
    at xsbt.boot.Using$.withResource(Using.scala:11)
    at xsbt.boot.Using$.apply(Using.scala:10)
    at xsbt.boot.Locks$GlobalLock.liftedTree1$1(Locks.scala:51)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:51)
    at xsbt.boot.Locks$.apply0(Locks.scala:30)
    at xsbt.boot.Locks$.apply(Locks.scala:27)
    at scala.collection.Iterable$class.$init$(Proxy.scala:32)
    at xsbt.boot.Launch$ScalaProvider.<init>(Launch.scala:107)
    at xsbt.boot.Launch$$anonfun$1.apply(Launch.scala:83)
    at org.apache.ivy.plugins.namespace.NamespaceRule.newEntry(Cache.scala:17)
    at org.apache.ivy.plugins.namespace.NamespaceRule.apply(Cache.scala:12)
    at xsbt.boot.Launch.getScala(Launch.scala:85)
    at xsbt.boot.Launch$.run(Launch.scala:49)
    at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:43)
    at xsbt.boot.Launch$.launch(Launch.scala:68)
    at xsbt.boot.Launch$.apply(Launch.scala:14)
    at xsbt.boot.Boot$.runImpl(Boot.scala:24)
    at xsbt.boot.Boot$.main(Boot.scala:15)
    at xsbt.boot.Boot.main(Boot.scala)
Error during sbt execution: java.io.IOException: Permission denied

```

I have attempted to change permissions to be writable in the directory where I attempt to run sbt but that doesn't seem to make a difference. I have also deleted the installation in ~/bin and installed sbt using homebrew but got the same exception.  I was wondering if you have run into this before. If so, what can I do to get past this?

Thanks!
-Jared

**Comment by harrah** [comment]
Please use the mailing list for questions/support.  Thanks!
