### ISSUE TITLE
AssertionError when trying to compile

### ISSUE THREAD

**Issue by puffnfresh** [sbt/sbt#176]
Using SBT 0.10.1

I have a build.sbt of:

```
name := "baklava"

libraryDependencies += "org.parboiled" % "parboiled-core" % "1.0.1"

libraryDependencies += "org.parboiled" % "parboiled-scala" % "1.0.1"
```

Trying to compile gives:

```
$ java -jar ~/Downloads/sbt-launch.jar compile
[info] Set current project to default-4441f4 (in build file:/Users/brianmckenna/Documents/code/baklava/)
[info] Updating {file:/Users/brianmckenna/Documents/code/baklava/}default-4441f4...
[info] Done updating.
[info] Compiling 4 Scala sources to /Users/brianmckenna/Documents/code/baklava/target/scala-2.8.1.final/classes...
[error] {file:/Users/brianmckenna/Documents/code/baklava/}default-4441f4/compile: java.lang.AssertionError: assertion failed
[error] Total time: 8 s, completed Sep 9, 2011 12:27:32 AM
```

Stacktrace in the `target/streams/compile/compile/\$global/out` file:

```
java.lang.AssertionError: assertion failed
        at scala.Predef$.assert(Predef.scala:77)
        at xsbt.API.build$1(API.scala:163)
        at xsbt.API.defDef(API.scala:195)
        at xsbt.API.xsbt$API$$definition(API.scala:276)
        at xsbt.API$$anonfun$xsbt$API$$processDefinitions$1.apply(API.scala:262)
        at xsbt.API$$anonfun$xsbt$API$$processDefinitions$1.apply(API.scala:262)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:227)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:227)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:34)
        at scala.collection.mutable.ArrayOps.foreach(ArrayOps.scala:35)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:227)
        at scala.collection.mutable.ArrayOps.flatMap(ArrayOps.scala:35)
        at xsbt.API.xsbt$API$$processDefinitions(API.scala:262)
        at xsbt.API$$anonfun$mkStructure$3.apply(API.scala:260)
        at xsbt.API$$anonfun$mkStructure$3.apply(API.scala:260)
        at xsbt.Message$$anon$1.apply(Message.scala:8)
        at xsbti.SafeLazy$$anonfun$apply$1.apply(SafeLazy.scala:8)
        at xsbti.SafeLazy$Impl._t(SafeLazy.scala:20)
        at xsbti.SafeLazy$Impl.get(SafeLazy.scala:24)
        at xsbt.API$$anonfun$xsbt$API$$forceStructures$1.apply(API.scala:96)
        at xsbt.API$$anonfun$xsbt$API$$forceStructures$1.apply(API.scala:96)
        at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:61)
        at scala.collection.immutable.List.foreach(List.scala:45)
        at xsbt.API.xsbt$API$$forceStructures(API.scala:96)
        at xsbt.API$ApiPhase.processScalaUnit(API.scala:50)
        at xsbt.API$ApiPhase.processUnit(API.scala:41)
        at xsbt.API$ApiPhase$$anonfun$run$1.apply(API.scala:37)
        at xsbt.API$ApiPhase$$anonfun$run$1.apply(API.scala:37)
        at scala.collection.Iterator$class.foreach(Iterator.scala:631)
        at scala.collection.mutable.ListBuffer$$anon$1.foreach(ListBuffer.scala:304)
        at xsbt.API$ApiPhase.run(API.scala:37)
        at scala.tools.nsc.Global$Run.compileSources(Global.scala:741)
        at scala.tools.nsc.Global$Run.compile(Global.scala:822)
        at xsbt.CompilerInterface.run(CompilerInterface.scala:87)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:57)
        at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:29)
        at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:25)
        at sbt.AggressiveCompile$$anonfun$6.compileScala$1(AggressiveCompile.scala:67)
        at sbt.AggressiveCompile$$anonfun$6.apply(AggressiveCompile.scala:79)
        at sbt.AggressiveCompile$$anonfun$6.apply(AggressiveCompile.scala:57)
        at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:21)
        at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:19)
        at sbt.inc.Incremental$.cycle(Incremental.scala:33)
        at sbt.inc.Incremental$.compile(Incremental.scala:20)
        at sbt.inc.IncrementalCompile$.apply(Compile.scala:17)
        at sbt.AggressiveCompile.compile2(AggressiveCompile.scala:87)
        at sbt.AggressiveCompile.compile1(AggressiveCompile.scala:38)
        at sbt.AggressiveCompile.apply(AggressiveCompile.scala:28)
        at sbt.Compiler$.apply(Compiler.scala:107)
        at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:420)
        at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:420)
        at sbt.Scoped$$anonfun$hf2$1.apply(Structure.scala:506)
        at sbt.Scoped$$anonfun$hf2$1.apply(Structure.scala:506)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:44)
        at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$9.apply(Structure.scala:304)
        at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$9.apply(Structure.scala:304)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$5.work(System.scala:67)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:221)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:221)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:13)
        at sbt.Execute.work(Execute.scala:227)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:221)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:221)
        at sbt.CompletionService$$anon$1$$anon$2.call(CompletionService.scala:26)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
        at java.util.concurrent.FutureTask.run(FutureTask.java:138)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
        at java.util.concurrent.FutureTask.run(FutureTask.java:138)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
        at java.lang.Thread.run(Thread.java:680)
```

Have I done something stupid in the build.sbt file?

**Comment by puffnfresh** [comment]
This may have something to do with the dependencies themselves. I've copied the `org.parboiled` jars from my Ivy cache into `$PROJECT/lib`, removed my `$PROJECT/build.sbt` and I'm getting the same error.

**Comment by harrah** [comment]
This is very likely a bug in sbt's api extraction that would require seeing a reproducible example.  It doesn't need to be minimized much.

**Comment by puffnfresh** [comment]
I created a Gist with a project that reproduces the bug:

https://gist.github.com/1207633

**Comment by harrah** [comment]
Thanks, that reproduced it for me.  I believe it is a bug in Scala 2.8.x that gets triggered by sbt's analysis because it works ok using Scala 2.9.1.  I could work around the immediate error, but got a more problematic error in a later compiler phase.

**Comment by gkossakowski** [comment]
Given the comment that it works ok in Scala 2.9.1 and inactivity for 3 years (nobody reported duplicate of this issue) I'm closing it as part of ticket cleaning.
