### ISSUE TITLE
Identifiers that differ only in case are handled incorrectly in non-case sensitive filesystems

### ISSUE THREAD

**Issue by denisrosset** [sbt/sbt#1777]
I am using Mac OS X 10.7 with non-case sensitive HFS, with SBT 0.13.7 and Scala 2.11.4; code using identifiers that differ only in case leads to an error on recompilation:

```
java.lang.IllegalArgumentException: requirement failed: Source file '/Users/rossetd0/Documents/phd/spire/core/target/scala-2.11/classes/spire/optional/optionAction.class' does not exist.
    at scala.Predef$.require(Predef.scala:233)
    at sbt.IO$.copyFile(IO.scala:583)
    at sbt.IO$.move(IO.scala:786)
    at sbt.inc.ClassfileManager$$anonfun$transactional$1$$anon$2.sbt$inc$ClassfileManager$$anonfun$$anon$$move(ClassfileManager.scala:75)
    at sbt.inc.ClassfileManager$$anonfun$transactional$1$$anon$2$$anonfun$delete$3.apply(ClassfileManager.scala:52)
    at sbt.inc.ClassfileManager$$anonfun$transactional$1$$anon$2$$anonfun$delete$3.apply(ClassfileManager.scala:51)
    at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:153)
    at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:306)
    at sbt.inc.ClassfileManager$$anonfun$transactional$1$$anon$2.delete(ClassfileManager.scala:51)
    at sbt.inc.Incremental$.prune(Incremental.scala:59)
    at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:28)
    at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:39)
    at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:38)
    at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:66)
    at sbt.inc.Incremental$.compile(Incremental.scala:38)
    at sbt.inc.IncrementalCompile$.apply(Compile.scala:26)
    at sbt.compiler.AggressiveCompile.compile2(AggressiveCompile.scala:153)
    at sbt.compiler.AggressiveCompile.compile1(AggressiveCompile.scala:70)
    at sbt.compiler.AggressiveCompile.apply(AggressiveCompile.scala:45)
    at sbt.Compiler$.apply(Compiler.scala:74)
    at sbt.Compiler$.apply(Compiler.scala:65)
    at sbt.Defaults$.sbt$Defaults$$compileTaskImpl(Defaults.scala:789)
    at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:781)
    at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:781)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
[error] (core/compile:compile) java.lang.IllegalArgumentException: requirement failed: Source file '/Users/rossetd0/Documents/phd/spire/core/target/scala-2.11/classes/spire/optional/optionAction.class' does not exist.
```

The code fragment is:

``` scala
trait OptionAction[P, G] extends Any with Action[Option[P], Option[G]] {
  implicit def partial: PartialAction[P, G]
}

object optionAction {
  implicit def optionAction[P, G](implicit ev: PartialAction[P, G]): Action[Option[P], Option[G]] =
    new OptionAction[P, G] {
      def partial = ev
    }
}
```

I can try to write a reproducible test case on request.

**Comment by eed3si9n** [comment]
> code using identifiers that differ only in case leads to an error on recompilation:

Could you clarify the reproduction steps? Does it break only for incremental compilation as opposed to `clean` and `compile`? Does it work when you turn off name hashing:

``` scala
incOptions := incOptions.value.withNameHashing(false)
```

**Comment by eed3si9n** [comment]
I am closing this due to inactivity, but if this is still relevant let us know with more details (reproduction steps etc).
