### ISSUE TITLE
SBT does not work behind proxy java.util.NoSuchElementException

### ISSUE THREAD

**Issue by samthebest** [sbt/sbt#1806]
So when I'm not behind a proxy sbt works fine, not matter what combination of proxy settings I use for `SBT_OPTS` or `http_proxy` I cannot get sbt to work.  I think this is the case for basic authentication, ntlm and kerberos proxies. I can get brew, curl and wget to work behind proxies, and my collegues can get maven to work behind the proxies.  I've reached the conclusion that the proxy support for sbt is lacking.  Please put in better proxy support to sbt.

Here is one of the kind of problems I get (I also see messages like "credentials not found" and "you are behind a poorly configured proxy").

```
[warn]  [FAILED     ] org.scalaz#scalaz-core_2.11;7.1.0!scalaz-core_2.11.jar(bundle): java.util.NoSuchElementException (74ms)
[warn]  [FAILED     ] org.scalaz#scalaz-core_2.11;7.1.0!scalaz-core_2.11.jar(bundle): java.util.NoSuchElementException (58ms)
[warn]  [FAILED     ] org.scalaz#scalaz-core_2.11;7.1.0!scalaz-core_2.11.jar(bundle):  (0ms)
[warn] ==== local: tried
[warn]   /Users/g04508966/.ivy2/local/org.scalaz/scalaz-core_2.11/7.1.0/bundles/scalaz-core_2.11.jar
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/scalaz/scalaz-core_2.11/7.1.0/scalaz-core_2.11-7.1.0.jar
[warn] ==== mvnrepository: tried
[warn]   https://repository.cloudera.com/artifactory/cloudera-repos/org/scalaz/scalaz-core_2.11/7.1.0/scalaz-core_2.11-7.1.0.jar
[warn] ==== spray repo: tried
[warn]   http://repo.spray.io/org/scalaz/scalaz-core_2.11/7.1.0/scalaz-core_2.11-7.1.0.jar
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scalaz#scalaz-core_2.11;7.0.5: java.util.NoSuchElementException
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::              FAILED DOWNLOADS            ::
[warn]  :: ^ see resolution messages for details  ^ ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scalaz#scalaz-core_2.11;7.1.0!scalaz-core_2.11.jar(bundle)
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]      org.scalaz:scalaz-core_2.11:7.0.5 (.../assembly.sbt#L21-59)
[warn]        +- io.openmaths:openmaths_2.11:0.1.0
sbt.ResolveException: unresolved dependency: org.scalaz#scalaz-core_2.11;7.0.5: java.util.NoSuchElementException
download failed: org.scalaz#scalaz-core_2.11;7.1.0!scalaz-core_2.11.jar(bundle)
    at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:243)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:158)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:156)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:147)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:147)
    at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:124)
    at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:56)
    at sbt.IvySbt$$anon$3.call(Ivy.scala:64)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
    at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
    at xsbt.boot.Using$.withResource(Using.scala:10)
    at xsbt.boot.Using$.apply(Using.scala:9)
    at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
    at xsbt.boot.Locks$.apply0(Locks.scala:31)
    at xsbt.boot.Locks$.apply(Locks.scala:28)
    at sbt.IvySbt.withDefaultLogger(Ivy.scala:64)
    at sbt.IvySbt.withIvy(Ivy.scala:119)
    at sbt.IvySbt.withIvy(Ivy.scala:116)
    at sbt.IvySbt$Module.withModule(Ivy.scala:147)
    at sbt.IvyActions$.updateEither(IvyActions.scala:156)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1282)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1279)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$84.apply(Defaults.scala:1309)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$84.apply(Defaults.scala:1307)
    at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1312)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1306)
    at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
    at sbt.Classpaths$.cachedUpdate(Defaults.scala:1324)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1264)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1242)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: org.scalaz#scalaz-core_2.11;7.0.5: java.util.NoSuchElementException
```

**Comment by indrajitr** [comment]
Use the System Properties `http.proxyHost`, `http.proxyPort`, `http.proxyUser`, `http.proxyPassword` etc. via `-Dkey=value` pattern.

**Comment by indrajitr** [comment]
Please take a look at the relevant [docs](http://www.scala-sbt.org/0.13/docs/Setup-Notes.html#HTTP%2FHTTPS%2FFTP+Proxy). Feel encouraged to follow up on [sbt-dev](https://groups.google.com/forum/#!forum/sbt-dev) if this doesn't work for you.

**Comment by samthebest** [comment]
So I've been using the SBT_OPTS environment variable, which certainly does something, but does not make my proxy work.  Like I said, I have tried many permutations of the flags and environment variables.  SBT is indeed using my proxy settings, but it does not work.  As mentioned, _all_ other tools I need to use I can make work behind my proxy, only SBT does not work, therefore it is logical to assume SBT does not have proper proxy support.

The example in the link is inapplicable, since it is explaining how to run `java` command, I'm trying to run SBT.

**Comment by vimalk78** [comment]
i am facing same problem. it does not work behind proxy. i dont know why the issue is closed.

**Comment by techqurarks** [comment]
Simplly use CNTLM(http://cntlm.sourceforge.net/) for detailed steps 
http://stackoverflow.com/a/24540105/1802348
please skip maven part!
I tested it and It worked for me and my friends!
tell me if this does not resolve issuse

P.S. - please give upvote if you find it perfect!

**Comment by wendersonferreira** [comment]
Try this

in my ubuntu change ~/.profile at end of file 

export SBT_OPTS="$SBT_OPTS -Dhttp.proxyHost=host -Dhttp.proxyPort=port -Dhttp.proxyUser=username -Dhttp.proxyPassword=password -Dhttps.proxyHost=host -Dhttps.proxyPort=port -Dhttps.proxyUser=username -Dhttps.proxyPassword=password"

enjoy it

**Comment by Nimi42** [comment]
Did anything solve the problem. I'm having similar problems. I can get pip and conda to work, but
-Dhttp.proxyHost=host -Dhttp.proxyPort=port -Dhttp.proxyUser=username -Dhttp.proxyPassword=password -Dhttps.proxyHost=host -Dhttps.proxyPort=port -Dhttps.proxyUser=username -Dhttps.proxyPassword=password don't fix the problem for sbt.
