### ISSUE TITLE
Publish fails with 'Invalid characters in hostname' on JDK8.

### ISSUE THREAD

**Issue by imeredith** [sbt/sbt#1837]
I have been setting up a new laptop and my publish to jfrog was failing. Since I have it working on a different laptop I  realised the difference was the JDK version in use. Reverting from JDK8 to the Apple version of JDK6 fixed the below issue. I couldn't seem to find anyone else with this issue with Google so maybe its some bug that only gets hit by my specific setup?

java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, m

```
java.lang.IllegalArgumentException: Invalid characters in hostname
    at java.net.HostPortrange.toLowerCase(HostPortrange.java:189)
    at java.net.HostPortrange.<init>(HostPortrange.java:150)
    at java.net.URLPermission$Authority.<init>(URLPermission.java:481)
    at java.net.URLPermission.parseURI(URLPermission.java:449)
    at java.net.URLPermission.init(URLPermission.java:170)
    at java.net.URLPermission.<init>(URLPermission.java:166)
    at sun.net.www.protocol.http.HttpURLConnection.URLtoSocketPermission(HttpURLConnection.java:1032)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1425)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
    at org.apache.ivy.util.url.BasicURLHandler.readResponseBody(BasicURLHandler.java:298)
    at org.apache.ivy.util.url.BasicURLHandler.disconnect(BasicURLHandler.java:277)
    at org.apache.ivy.util.url.BasicURLHandler.upload(BasicURLHandler.java:266)
    at org.apache.ivy.util.FileUtil.copy(FileUtil.java:150)
    at org.apache.ivy.plugins.repository.url.URLRepository.put(URLRepository.java:84)
    at org.apache.ivy.plugins.repository.AbstractRepository.put(AbstractRepository.java:130)
    at sbt.ConvertResolver$ChecksumFriendlyURLResolver$class.put(ConvertResolver.scala:80)
    at sbt.ConvertResolver$PluginCapableResolver$1.put(ConvertResolver.scala:106)
    at org.apache.ivy.plugins.resolver.RepositoryResolver.publish(RepositoryResolver.java:216)
    at sbt.IvyActions$$anonfun$publish$3.apply(IvyActions.scala:263)
    at sbt.IvyActions$$anonfun$publish$3.apply(IvyActions.scala:262)
    at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
    at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:771)
    at sbt.IvyActions$.publish(IvyActions.scala:262)
    at sbt.IvyActions$$anonfun$publish$1$$anonfun$apply$1.apply$mcV$sp(IvyActions.scala:97)
    at sbt.IvyActions$$anonfun$publish$1$$anonfun$apply$1.apply(IvyActions.scala:97)
    at sbt.IvyActions$$anonfun$publish$1$$anonfun$apply$1.apply(IvyActions.scala:97)
    at sbt.IvyActions$.withChecksums(IvyActions.scala:106)
    at sbt.IvyActions$.sbt$IvyActions$$withChecksums(IvyActions.scala:101)
    at sbt.IvyActions$$anonfun$publish$1.apply(IvyActions.scala:97)
    at sbt.IvyActions$$anonfun$publish$1.apply(IvyActions.scala:91)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:115)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:115)
    at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:103)
    at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:48)
    at sbt.IvySbt$$anon$3.call(Ivy.scala:57)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:98)
    at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:81)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:102)
    at xsbt.boot.Using$.withResource(Using.scala:11)
    at xsbt.boot.Using$.apply(Using.scala:10)
    at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:62)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:52)
    at xsbt.boot.Locks$.apply0(Locks.scala:31)
    at xsbt.boot.Locks$.apply(Locks.scala:28)
    at sbt.IvySbt.withDefaultLogger(Ivy.scala:57)
    at sbt.IvySbt.withIvy(Ivy.scala:98)
    at sbt.IvySbt.withIvy(Ivy.scala:94)
    at sbt.IvySbt$Module.withModule(Ivy.scala:115)
    at sbt.IvyActions$.publish(IvyActions.scala:91)
    at sbt.Classpaths$$anonfun$publishTask$1.apply(Defaults.scala:1173)
    at sbt.Classpaths$$anonfun$publishTask$1.apply(Defaults.scala:1172)
    at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:35)
    at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:34)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
    at sbt.std.Transform$$anon$4.work(System.scala:64)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.Execute.work(Execute.scala:244)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] (*:publish) java.lang.IllegalArgumentException: Invalid characters in hostname
```

**Comment by jsuereth** [comment]
what was the hostname you were publishing to?

**Comment by eed3si9n** [comment]
I am closing this due to inactivity, but if this is still relevant let us know with more details (reproduction steps etc).
