### ISSUE TITLE
Resolver.ssh throws NumberFormatException

### ISSUE THREAD

**Issue by bblfish** [sbt/sbt#1860]
Could it be related to IPV6 deployment? I am in France on the Free.fr network that is on IPV6.

Here is a description of the problem.
I am trying to publish my version of [banana-rdf](https://github.com/read-write-web/banana-rdf/tree/master) to bblfish.net .

So I start sbt with

```
$ sbt -Dbanana.publish=bblfish.net:/home/hjs/htdocs/work/repo/
...
> publish
...
[warn] No main class detected
[info] :: delivering :: org.w3#banana_2.11;0.7.2-SNAPSHOT :: 0.7.2-SNAPSHOT :: integration :: Sun Feb 15 15:17:58 CET 2015
[info]  delivering ivy file to /Volumes/Dev/Programming/Scala/banana-rdf/master/target/scala-2.11/ivy-0.7.2-SNAPSHOT.xml
[warn] No main class detected
[trace] Stack trace suppressed: run last banana/*:publish for the full output.
[trace] Stack trace suppressed: run last banana_jvm/*:publish for the full output.
[trace] Stack trace suppressed: run last rdf-test-suite_jvm/*:publish for the full output.
[trace] Stack trace suppressed: run last rdf-test-suite_common_jvm/*:publish for the full output.
[trace] Stack trace suppressed: run last jena/*:publish for the full output.
[trace] Stack trace suppressed: run last plantain_jvm/*:publish for the full output.
[trace] Stack trace suppressed: run last plantain_common_jvm/*:publish for the full output.
[trace] Stack trace suppressed: run last ntriples_jvm/*:publish for the full output.
[trace] Stack trace suppressed: run last ntriples_common_jvm/*:publish for the full output.
[trace] Stack trace suppressed: run last examples/*:publish for the full output.
[trace] Stack trace suppressed: run last rdf_jvm/*:publish for the full output.
[trace] Stack trace suppressed: run last rdf_common_jvm/*:publish for the full output.
[trace] Stack trace suppressed: run last sesame/*:publish for the full output.
[trace] Stack trace suppressed: run last banana_js/*:publish for the full output.
[trace] Stack trace suppressed: run last plantain_js/*:publish for the full output.
[trace] Stack trace suppressed: run last plantain_common_js/*:publish for the full output.
[trace] Stack trace suppressed: run last rdf-test-suite_js/*:publish for the full output.
[trace] Stack trace suppressed: run last rdf-test-suite_common_js/*:publish for the full output.
[trace] Stack trace suppressed: run last rdf_js/*:publish for the full output.
[trace] Stack trace suppressed: run last rdf_common_js/*:publish for the full output.
...
> last banana/*:publish
rdf_common_js/*:publish
[debug] :: SSH :: connecting to bblfish.net...
java.lang.NumberFormatException: For input string: "e00::2"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:580)
    at java.lang.Integer.parseInt(Integer.java:615)
    at com.sun.jndi.dns.DnsContextFactory.filterNameServers(DnsContextFactory.java:238)
    at com.sun.jndi.dns.DnsContextFactory.serversForUrls(DnsContextFactory.java:148)
    at com.sun.jndi.dns.DnsContextFactory.getContext(DnsContextFactory.java:81)
    at com.sun.jndi.url.dns.dnsURLContext.getRootURLContext(dnsURLContext.java:71)
    at com.sun.jndi.toolkit.url.GenericURLDirContext.getAttributes(GenericURLDirContext.java:100)
    at sun.security.krb5.KrbServiceLocator.getKerberosService(KrbServiceLocator.java:85)
    at sun.security.krb5.Config.checkRealm(Config.java:1120)
    at sun.security.krb5.Config.getRealmFromDNS(Config.java:1093)
    at sun.security.krb5.Config.getDefaultRealm(Config.java:987)
    at sun.security.krb5.Realm.getDefault(Realm.java:58)
    at sun.security.krb5.PrincipalName.<init>(PrincipalName.java:451)
    at sun.security.krb5.PrincipalName.<init>(PrincipalName.java:460)
    at sun.security.jgss.krb5.Krb5NameElement.getInstance(Krb5NameElement.java:92)
    at sun.security.jgss.krb5.Krb5MechFactory.getNameElement(Krb5MechFactory.java:95)
    at sun.security.jgss.GSSManagerImpl.getNameElement(GSSManagerImpl.java:203)
    at sun.security.jgss.GSSNameImpl.getElement(GSSNameImpl.java:477)
    at sun.security.jgss.GSSNameImpl.init(GSSNameImpl.java:201)
    at sun.security.jgss.GSSNameImpl.<init>(GSSNameImpl.java:170)
    at sun.security.jgss.GSSNameImpl.<init>(GSSNameImpl.java:151)
    at sun.security.jgss.GSSManagerImpl.createName(GSSManagerImpl.java:128)
    at com.jcraft.jsch.jgss.GSSContextKrb5.create(GSSContextKrb5.java:80)
    at com.jcraft.jsch.UserAuthGSSAPIWithMIC.start(UserAuthGSSAPIWithMIC.java:125)
    at com.jcraft.jsch.Session.connect(Session.java:440)
    at com.jcraft.jsch.Session.connect(Session.java:160)
    at org.apache.ivy.plugins.repository.ssh.SshCache.getSession(SshCache.java:331)
    at org.apache.ivy.plugins.repository.ssh.AbstractSshBasedRepository.getSession(AbstractSshBasedRepository.java:108)
    at org.apache.ivy.plugins.repository.ssh.SshRepository.put(SshRepository.java:238)
    at org.apache.ivy.plugins.repository.AbstractRepository.put(AbstractRepository.java:130)
    at org.apache.ivy.plugins.resolver.RepositoryResolver.put(RepositoryResolver.java:234)
    at org.apache.ivy.plugins.resolver.RepositoryResolver.publish(RepositoryResolver.java:216)
    at sbt.IvyActions$$anonfun$publish$3.apply(IvyActions.scala:322)
    at sbt.IvyActions$$anonfun$publish$3.apply(IvyActions.scala:321)
    at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
    at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:771)
    at sbt.IvyActions$.publish(IvyActions.scala:321)
    at sbt.IvyActions$$anonfun$publish$1$$anonfun$apply$1.apply$mcV$sp(IvyActions.scala:114)
    at sbt.IvyActions$$anonfun$publish$1$$anonfun$apply$1.apply(IvyActions.scala:114)
    at sbt.IvyActions$$anonfun$publish$1$$anonfun$apply$1.apply(IvyActions.scala:114)
    at sbt.IvyActions$.withChecksums(IvyActions.scala:123)
    at sbt.IvyActions$.sbt$IvyActions$$withChecksums(IvyActions.scala:118)
    at sbt.IvyActions$$anonfun$publish$1.apply(IvyActions.scala:114)
    at sbt.IvyActions$$anonfun$publish$1.apply(IvyActions.scala:107)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:151)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:151)
    at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:128)
    at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:56)
    at sbt.IvySbt$$anon$4.call(Ivy.scala:64)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
    at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
    at xsbt.boot.Using$.withResource(Using.scala:10)
    at xsbt.boot.Using$.apply(Using.scala:9)
    at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
    at xsbt.boot.Locks$.apply0(Locks.scala:31)
    at xsbt.boot.Locks$.apply(Locks.scala:28)
    at sbt.IvySbt.withDefaultLogger(Ivy.scala:64)
    at sbt.IvySbt.withIvy(Ivy.scala:123)
    at sbt.IvySbt.withIvy(Ivy.scala:120)
    at sbt.IvySbt$Module.withModule(Ivy.scala:151)
    at sbt.IvyActions$.publish(IvyActions.scala:107)
    at sbt.Classpaths$$anonfun$publishTask$1.apply(Defaults.scala:1248)
    at sbt.Classpaths$$anonfun$publishTask$1.apply(Defaults.scala:1247)
    at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:35)
    at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:34)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] (rdf_common_js/*:publish) java.lang.NumberFormatException: For input string: "e00::2"
rdf_js/*:publish
[debug] :: SSH :: connecting to bblfish.net...
java.lang.NumberFormatException: For input string: "e00::2"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:580)
....
```

I do get a UI that asks me for a username and password first, but then it gives me the error message above.

The key error message seems to be 

```
  at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:580)
    at java.lang.Integer.parseInt(Integer.java:615)
    at com.sun.jndi.dns.DnsContextFactory.filterNameServers(DnsContextFactory.java:238)
```

I noticed that I have the following DNS servers:
- `192.168.69.254`
- `2a01:e00::2`
- `2a01:e00::1`

Where the second one contains the characters `e00::2` .
This makes me think it is DNS related. But it could be due to another cause.

After trying various options I set the DNS Server to Google's IPV6 free ones `2001:4860:4860::8888` and `2001:4860:4860::8844`, and then after rebooting the error messages was

```
[error] (banana/*:publish) java.lang.NumberFormatException: For input string: "4860:4860::8888"
[error] (banana_jvm/*:publish) java.lang.NumberFormatException: For input string: "4860:4860::8888"
[error] (rdf-test-suite_jvm/*:publish) java.lang.NumberFormatException: For input string: "4860:4860::8888"
[error] (rdf-test-suite_common_jvm/*:publish) java.lang.NumberFormatException: For input string: "4860:4860::8888"
```

Now this could just be a bug in java8 on OSX. 

``` bash
$ java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(™) 64-Bit Server VM (build 25.31-b07, mixed mode)
```

**Comment by bblfish** [comment]
When I then change the DNS address to Google's open `8.8.8.8` or `8.8.4.4` and close all java programs ( rather than rebooting ), then the `publish` command works.

So if this is a Java8 bug, any idea here how to fix that nowadays? There used to be a open way to do that at Sun Microsystems, but I am not sure where to go to nowadays.

**Comment by eed3si9n** [comment]
Apparently a known issue with Java:
- [JDK-6991580](https://bugs.openjdk.java.net/browse/JDK-6991580) IPv6 Nameservers in resolv.conf throws NumberFormatException
- [HADOOP-11582](https://issues.apache.org/jira/browse/HADOOP-11582)  
  Hadoop CommonHADOOP-11582
  org.apache.hadoop.net.TestDNS failing with NumberFormatException -IPv6 related?

**Comment by eed3si9n** [comment]
I am closing this due to inactivity, but if this is still relevant let us know with more details (reproduction steps etc).
