### ISSUE TITLE
Impossible to define a project called scala-library

### ISSUE THREAD

**Issue by gkossakowski** [sbt/sbt#1872]
While working on sbt build for Scala I ran into a problem with defining a subproject for the library. When I set `organization` to `org.scala-lang` and `name` to `scala-library` I get the following failure in `update` task:

```
[error] a module is not authorized to depend on itself: org.scala-lang#scala-library;2.11.5
java.lang.IllegalArgumentException: a module is not authorized to depend on itself: org.scala-lang#scala-library;2.11.5
    at org.apache.ivy.core.resolve.IvyNodeCallers.addCaller(IvyNodeCallers.java:167)
    at org.apache.ivy.core.resolve.IvyNode.addCaller(IvyNode.java:1076)
    at org.apache.ivy.core.resolve.IvyNode.getDependencies(IvyNode.java:369)
    at org.apache.ivy.core.resolve.VisitNode.getDependencies(VisitNode.java:313)
    at org.apache.ivy.core.resolve.ResolveEngine.doFetchDependencies(ResolveEngine.java:792)
    at org.apache.ivy.core.resolve.ResolveEngine.fetchDependencies(ResolveEngine.java:722)
    at org.apache.ivy.core.resolve.ResolveEngine.getDependencies(ResolveEngine.java:594)
    at org.apache.ivy.core.resolve.ResolveEngine.resolve(ResolveEngine.java:234)
    at org.apache.ivy.Ivy.resolve(Ivy.java:517)
    at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:266)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:175)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:157)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:151)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:151)
    at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:128)
    at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:56)
    at sbt.IvySbt$$anon$4.call(Ivy.scala:64)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:98)
    at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:81)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:102)
    at xsbt.boot.Using$.withResource(Using.scala:11)
    at xsbt.boot.Using$.apply(Using.scala:10)
    at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:62)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:52)
    at xsbt.boot.Locks$.apply0(Locks.scala:31)
    at xsbt.boot.Locks$.apply(Locks.scala:28)
    at sbt.IvySbt.withDefaultLogger(Ivy.scala:64)
    at sbt.IvySbt.withIvy(Ivy.scala:123)
    at sbt.IvySbt.withIvy(Ivy.scala:120)
    at sbt.IvySbt$Module.withModule(Ivy.scala:151)
    at sbt.IvyActions$.updateEither(IvyActions.scala:157)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1318)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1315)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$85.apply(Defaults.scala:1345)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$85.apply(Defaults.scala:1343)
    at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1348)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1342)
    at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
    at sbt.Classpaths$.cachedUpdate(Defaults.scala:1360)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1300)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1275)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:695)
```

I have `autoScalaLibrary` set to false. The dependency on `scala-library` is coming from the `scala-tool` configuration.

The full reproduction can be found in gkossakowski/scala@c788225. I haven't found any workarounds so far.

**Comment by dwijnand** [comment]
Do you want to try and see if setting moduleName instead of name works?

**Comment by gkossakowski** [comment]
What do you mean specifically? To moduleName to `scala-library` but leave `name` alone?

**Comment by dwijnand** [comment]
Yeah set `moduleName`, leave `name` to default to `id`. I'm not saying your problem isn't legitimate (imho), just offering a plausible workaround.

**Comment by dwijnand** [comment]
Doesn't work by the way, sorry for the noise.

**Comment by gkossakowski** [comment]
No worries. Thanks for checking it for me!

**Comment by gkossakowski** [comment]
The error itself makes sense assuming that artifacts in `scala-tool` configuration has to be resolved as dependencies of the project. However, I'm not sure this is necessary. The `scala-tool` configuration is used internally by sbt to resolve Scala compiler artifacts it will use to compile your code. I don't see any reason why this would have to be expressed as dependencies of a project.
One could imagine that everything that lives in `scala-tool` configuration was resolved in "detached" mode: just a bunch of jars outside of any project. Not sure if that's possible or makes sense, though...

**Comment by adriaanm** [comment]
Would a custom ScalaInstance do the trick?

**Comment by gkossakowski** [comment]
How would you define one?

**Comment by eed3si9n** [comment]
You can delegate the `scalaInstance` to some other sub project as follows. I only confirmed that hello world runs in Java.

``` scala
lazy val commonSettings = Seq[Setting[_]](
  organization := "org.scala-lang",
  version := "2.11.6-SNAPSHOT",
  // we don't cross build Scala itself
  crossPaths := false,
  // do not add Scala library jar as a dependency automatically
  autoScalaLibrary := false,
  managedScalaInstance := false,
  // we always assume that Java classes are standalone and do not have any dependency
  // on Scala classes
  compileOrder := CompileOrder.JavaThenScala,
  scalaInstance := (scalaInstance in bootstrap).value
)

lazy val scalaLibrary = (project in file("library")).
  settings(commonSettings: _*).
  settings(
    name := "scala-library"
  )

lazy val bootstrap = (project in file("bootstrap")).
  settings(
    scalaVersion := "2.11.5",
    name := "bootstrap-scala",
    description := "bootstrap instance of Scala"
  )
```

**Comment by paulp** [comment]
In case anyone's interested in the pile of dust I left after encountering this brick wall way back when: https://github.com/paulp/policy/blob/master/project/PolicyBuild.scala

**Comment by paulp** [comment]
Actually I forgot I found a better way and assembled a self-contained scala build around it (no libsbt dependency.) Here: https://github.com/paulp/scala/commit/2ade09fde6

The excerpt relevant to the exercise is

``` scala
// Can't rely on ivyConfigurations and "scala-tool" business here because
// in scala-compiler's case sbt or ivy or someone thinks we are depending on ourself.
// So we blow away libraryDependencies (yay for immutability) and put ant back.
//
// Somehow this doesn't work without the ridiculous scalaInstance expression.
lazy val compiler = project.core dependsOn (asm, reflect) settings (
         libraryDependencies := List(ant % "compile"),
                scalaVersion := starrVersion,
               scalaInstance := ScalaInstance(scalaVersion.value, appConfiguration.value.provider.scalaProvider.launcher getScala scalaVersion.value),
    unmanagedJars in Compile += scalaInstance.value.libraryJar
)
```

See link for details. It's all in the one commit.

**Comment by gkossakowski** [comment]
@paulp, thanks for a distilled example. This worked perfectly: gkossakowski/scala@9091f4d462bda6c96e1d6c8d787b33a7a37b87b1.

It's time to close this issue.
