### ISSUE TITLE
Sporadic ConcurrentModificationException from JUnitXmlTestsListener

### ISSUE THREAD

**Issue by aerskine** [sbt/sbt#1881]
In sbt 0.13.7 we are seeing a sporadic `ConcurrentModificationException`:

```
java.util.ConcurrentModificationException
    at java.util.Hashtable$Enumerator.next(Hashtable.java:1367)
    at sbt.JUnitXmlTestsListener.<init>(JUnitXmlTestsListener.scala:33)
    at sbt.plugins.JUnitXmlReportPlugin$$anonfun$projectSettings$1.apply(JUnitXmlReportPlugin.scala:27)
    at sbt.plugins.JUnitXmlReportPlugin$$anonfun$projectSettings$1.apply(JUnitXmlReportPlugin.scala:27)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

Examining the code in JUnitXmlTestsListener, this seems likely to be genuine concurrent access from another test.

It could be fixed by creating a defensive clone of the system properties.  The safest way I can think of to do this would be:

``` scala
diff --git a/testing/src/main/scala/sbt/JUnitXmlTestsListener.scala b/testing/src/main/scala/sbt/JUnitXmlTestsListener.scala
index 2611486..5524e2f 100644
--- a/testing/src/main/scala/sbt/JUnitXmlTestsListener.scala
+++ b/testing/src/main/scala/sbt/JUnitXmlTestsListener.scala
@@ -27,7 +27,8 @@ class JUnitXmlTestsListener(val outputDir: String) extends TestsListener {
   val properties =
     <properties>
       {
-        val iter = System.getProperties.entrySet.iterator
+        // create a clone, defending against [[ConcurrentModificationException]]
+        val iter = System.getProperties.clone.asInstanceOf[util.Hashtable[AnyRef, AnyRef]].entrySet.iterator
         val props: ListBuffer[XNode] = new ListBuffer()
         while (iter.hasNext) {
           val next = iter.next
```

Note that using `sys.props.toList` or any variant of this will suffer from the same issue as the current code, specifically that it will use an iterator on the underlying (mutable) entry set.  The clone method on the other hand is synchronized (if clunky looking).

**Comment by eed3si9n** [comment]
Could you send us PR on this?
