### ISSUE TITLE
StackOverflowError at sbt.EvaluateSettings$INode.registerIfNew

### ISSUE THREAD

**Issue by Sciss** [sbt/sbt#1897]
I have started to sporadically see the below `StackOverflowError`; this is with sbt 0.13.7 and cross-publishing (`+publish-signed`), where the scala-versions are 2.11 and 2.10. When I run the command again, the error is gone, so perhaps it's a caching issue.

```
java.lang.StackOverflowError
    at sbt.EvaluateSettings$INode.registerIfNew(INode.scala:113)
    at sbt.EvaluateSettings$INode.doneOrBlock(INode.scala:107)
    at sbt.EvaluateSettings$INode$$anonfun$register$2.apply(INode.scala:117)
    at sbt.EvaluateSettings$INode$$anonfun$register$2.apply(INode.scala:117)
    at scala.collection.TraversableOnce$$anonfun$count$1.apply(TraversableOnce.scala:114)
    at scala.collection.TraversableOnce$$anonfun$count$1.apply(TraversableOnce.scala:113)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.TraversableOnce$class.count(TraversableOnce.scala:113)
    at scala.collection.AbstractTraversable.count(Traversable.scala:105)
    at sbt.EvaluateSettings$INode.register(INode.scala:117)
    at sbt.EvaluateSettings$INode.registerIfNew(INode.scala:113)
    at sbt.EvaluateSettings$INode.doneOrBlock(INode.scala:107)
    at sbt.EvaluateSettings$INode$$anonfun$register$2.apply(INode.scala:117)
    at sbt.EvaluateSettings$INode$$anonfun$register$2.apply(INode.scala:117)
```

**Comment by silles79** [comment]
I'm having the same issue:

[debug] > ++ 2.12.2 metrics/publishLocal
[info] Setting version to 2.12.2
[debug] Forcing garbage collection...
[info] Reapplying settings...
java.lang.StackOverflowError
	at sbt.EvaluateSettings$INode.registerIfNew(INode.scala:113)

[info] This is sbt 0.13.15

**Comment by dwijnand** [comment]
Do you have a reproduction test case?

**Comment by silles79** [comment]
not at the moment, it's a private project and I cannot share it as it is :(

**Comment by eed3si9n** [comment]
I am closing this due to inactivity, but if this is still relevant let us know with more details (reproduction steps etc).
