### ISSUE TITLE
More robustness in help and completion system

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [sbt/sbt#1900]
It's a multi-module project with a `build.sbt` and some custom `project/*.scala` files.
Version of SBT: 0.13.7.

```
> help
java.util.NoSuchElementException: key not found: -capture-settings
        at scala.collection.MapLike$class.default(MapLike.scala:228)
        at scala.collection.AbstractMap.default(Map.scala:58)
        at scala.collection.MapLike$class.apply(MapLike.scala:141)
        at scala.collection.AbstractMap.apply(Map.scala:58)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at sbt.BuiltinCommands$.allTaskAndSettingKeys(Main.scala:180)
        at sbt.BuiltinCommands$.keysHelp(Main.scala:386)
        at sbt.BuiltinCommands$$anonfun$actHelp$1.apply(Main.scala:383)
        at sbt.BuiltinCommands$$anonfun$actHelp$1.apply(Main.scala:383)
        at sbt.BasicCommands$$anonfun$1.apply(BasicCommands.scala:30)
        at sbt.BasicCommands$$anonfun$1.apply(BasicCommands.scala:30)
        at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:111)
        at scala.collection.immutable.List.foldLeft(List.scala:84)
        at scala.collection.TraversableOnce$class.$div$colon(TraversableOnce.scala:138)
        at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:105)
        at sbt.BasicCommands$.helpParser(BasicCommands.scala:30)
        at sbt.BasicCommands$$anonfun$help$1.apply(BasicCommands.scala:26)
        at sbt.BasicCommands$$anonfun$help$1.apply(BasicCommands.scala:26)
        at sbt.Command$$anonfun$sbt$Command$$argParser$1.apply(Command.scala:77)
        at sbt.Command$$anonfun$sbt$Command$$argParser$1.apply(Command.scala:77)
        at sbt.Command$$anonfun$simpleParser$2$$anonfun$apply$8.apply(Command.scala:84)
        at sbt.Command$$anonfun$simpleParser$2$$anonfun$apply$8.apply(Command.scala:81)
        at sbt.complete.BindParser$$anonfun$resultEmpty$7.apply(Parser.scala:656)
        at sbt.complete.BindParser$$anonfun$resultEmpty$7.apply(Parser.scala:656)
        at sbt.complete.Parser$Value.flatMap(Parser.scala:159)
        at sbt.complete.BindParser.resultEmpty$lzycompute(Parser.scala:656)
        at sbt.complete.BindParser.resultEmpty(Parser.scala:656)
        at sbt.complete.HomParser.resultEmpty$lzycompute(Parser.scala:625)
        at sbt.complete.HomParser.resultEmpty(Parser.scala:625)
        at sbt.complete.ParserMain$class.loop$1(Parser.scala:428)
        at sbt.complete.ParserMain$class.result(Parser.scala:437)
        at sbt.complete.Parser$.result(Parser.scala:132)
        at sbt.complete.ParserMain$class.parse(Parser.scala:383)
        at sbt.complete.DefaultParsers$.parse(Parsers.scala:261)
        at sbt.Command$.process(Command.scala:91)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
        at sbt.State$$anon$1.process(State.scala:184)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.MainLoop$.next(MainLoop.scala:98)
        at sbt.MainLoop$.run(MainLoop.scala:91)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
        at sbt.Using.apply(Using.scala:24)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
        at sbt.MainLoop$.runLogged(MainLoop.scala:24)
        at sbt.StandardMain$.runManaged(Main.scala:53)
        at sbt.xMain.run(Main.scala:28)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:57)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:77)
        at xsbt.boot.Launch$.run(Launch.scala:57)
        at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
        at xsbt.boot.Launch$.launch(Launch.scala:65)
        at xsbt.boot.Launch$.apply(Launch.scala:16)
        at xsbt.boot.Boot$.runImpl(Boot.scala:32)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)
[error] java.util.NoSuchElementException: key not found: -capture-settings
```

I can provide if needed my project.

**Comment by eed3si9n** [comment]
The reproduction steps would be type `help` from sbt shell?
I am not seeing the error.

**Comment by DavidPerezIngeniero** [comment]
Yes, maybe the bug is due to my `build.sbt` config.

**Comment by DavidPerezIngeniero** [comment]
In addition, when I press the tab and there is no input yet, I get this exception:

```
> java.util.NoSuchElementException: key not found: -capture-settings
        at scala.collection.MapLike$class.default(MapLike.scala:228)
        at scala.collection.AbstractMap.default(Map.scala:58)
        at scala.collection.MapLike$class.apply(MapLike.scala:141)
        at scala.collection.AbstractMap.apply(Map.scala:58)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at sbt.BuiltinCommands$.allTaskAndSettingKeys(Main.scala:180)
        at sbt.BuiltinCommands$.selectedParser(Main.scala:167)
        at sbt.BuiltinCommands$.showSettingParser(Main.scala:165)
        at sbt.BuiltinCommands$$anonfun$showSettingLike$1.apply(Main.scala:154)
        at sbt.BuiltinCommands$$anonfun$showSettingLike$1.apply(Main.scala:154)
        at sbt.Command$$anonfun$applyEffect$1.apply(Command.scala:58)
        at sbt.Command$$anonfun$applyEffect$1.apply(Command.scala:58)
        at sbt.Command$$anonfun$sbt$Command$$argParser$1.apply(Command.scala:77)
        at sbt.Command$$anonfun$sbt$Command$$argParser$1.apply(Command.scala:77)
        at sbt.Command$$anonfun$simpleParser$2$$anonfun$apply$8.apply(Command.scala:84)
        at sbt.Command$$anonfun$simpleParser$2$$anonfun$apply$8.apply(Command.scala:81)
        at sbt.complete.BindParser$$anonfun$completions$3.apply(Parser.scala:661)
        at sbt.complete.BindParser$$anonfun$completions$3.apply(Parser.scala:658)
        at sbt.complete.Completions$$anonfun$flatMap$1$$anonfun$apply$1.apply(Completions.scala:19)
        at sbt.complete.Completions$$anonfun$flatMap$1$$anonfun$apply$1.apply(Completions.scala:19)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
        at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:153)
        at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:306)
        at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:306)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
        at sbt.complete.Completions$$anonfun$flatMap$1.apply(Completions.scala:19)
        at sbt.complete.Completions$$anonfun$flatMap$1.apply(Completions.scala:19)
        at sbt.complete.Completions$$anon$1.get$lzycompute(Completions.scala:27)
        at sbt.complete.Completions$$anon$1.get(Completions.scala:27)
        at sbt.complete.Completions$$anonfun$$plus$plus$1.apply(Completions.scala:14)
        at sbt.complete.Completions$$anonfun$$plus$plus$1.apply(Completions.scala:14)
        at sbt.complete.Completions$$anon$1.get$lzycompute(Completions.scala:27)
        at sbt.complete.Completions$$anon$1.get(Completions.scala:27)
        at sbt.complete.Completions$$anonfun$$plus$plus$1.apply(Completions.scala:14)
        at sbt.complete.Completions$$anonfun$$plus$plus$1.apply(Completions.scala:14)
        at sbt.complete.Completions$$anon$1.get$lzycompute(Completions.scala:27)
        at sbt.complete.Completions$$anon$1.get(Completions.scala:27)
        at sbt.complete.Completions$$anonfun$$plus$plus$1.apply(Completions.scala:14)
        at sbt.complete.Completions$$anonfun$$plus$plus$1.apply(Completions.scala:14)
        at sbt.complete.Completions$$anon$1.get$lzycompute(Completions.scala:27)
        at sbt.complete.Completions$$anon$1.get(Completions.scala:27)
        at sbt.complete.Completions$$anonfun$$plus$plus$1.apply(Completions.scala:14)
        at sbt.complete.Completions$$anonfun$$plus$plus$1.apply(Completions.scala:14)
        at sbt.complete.Completions$$anon$1.get$lzycompute(Completions.scala:27)
        at sbt.complete.Completions$$anon$1.get(Completions.scala:27)
        at sbt.complete.Completions$$anonfun$$plus$plus$1.apply(Completions.scala:14)
        at sbt.complete.Completions$$anonfun$$plus$plus$1.apply(Completions.scala:14)
        at sbt.complete.Completions$$anon$1.get$lzycompute(Completions.scala:27)
        at sbt.complete.Completions$$anon$1.get(Completions.scala:27)
        at sbt.complete.Completions$$anonfun$$plus$plus$1.apply(Completions.scala:14)
        at sbt.complete.Completions$$anonfun$$plus$plus$1.apply(Completions.scala:14)
        at sbt.complete.Completions$$anon$1.get$lzycompute(Completions.scala:27)
        at sbt.complete.Completions$$anon$1.get(Completions.scala:27)
        at sbt.complete.Completions$$anonfun$$plus$plus$1.apply(Completions.scala:14)
        at sbt.complete.Completions$$anonfun$$plus$plus$1.apply(Completions.scala:14)
        at sbt.complete.Completions$$anon$1.get$lzycompute(Completions.scala:27)
        at sbt.complete.Completions$$anon$1.get(Completions.scala:27)
        at sbt.complete.Completions$$anonfun$$plus$plus$1.apply(Completions.scala:14)
        at sbt.complete.Completions$$anonfun$$plus$plus$1.apply(Completions.scala:14)
        at sbt.complete.Completions$$anon$1.get$lzycompute(Completions.scala:27)
        at sbt.complete.Completions$$anon$1.get(Completions.scala:27)
        at sbt.complete.Completions$$anonfun$$plus$plus$1.apply(Completions.scala:14)
        at sbt.complete.Completions$$anonfun$$plus$plus$1.apply(Completions.scala:14)
        at sbt.complete.Completions$$anon$1.get$lzycompute(Completions.scala:27)
        at sbt.complete.Completions$$anon$1.get(Completions.scala:27)
        at sbt.complete.Completions$$anonfun$flatMap$1.apply(Completions.scala:19)
        at sbt.complete.Completions$$anonfun$flatMap$1.apply(Completions.scala:19)
        at sbt.complete.Completions$$anon$1.get$lzycompute(Completions.scala:27)
        at sbt.complete.Completions$$anon$1.get(Completions.scala:27)
        at sbt.complete.JLineCompletion$.convertCompletions(JLineCompletion.scala:56)
        at sbt.complete.JLineCompletion$$anonfun$parserAsCompletor$1.apply(JLineCompletion.scala:52)
        at sbt.complete.JLineCompletion$$anonfun$parserAsCompletor$1.apply(JLineCompletion.scala:52)
        at sbt.complete.JLineCompletion$$anonfun$customCompletor$1$$anonfun$2.apply(JLineCompletion.scala:75)
        at sbt.complete.JLineCompletion$$anonfun$customCompletor$1$$anonfun$2.apply(JLineCompletion.scala:75)
        at sbt.complete.JLineCompletion$.complete(JLineCompletion.scala:94)
        at sbt.complete.JLineCompletion$$anonfun$customCompletor$1.apply(JLineCompletion.scala:75)
        at sbt.complete.JLineCompletion$$anonfun$customCompletor$1.apply(JLineCompletion.scala:74)
        at sbt.complete.JLineCompletion$CustomHandler.complete(JLineCompletion.scala:30)
        at jline.console.ConsoleReader.complete(ConsoleReader.java:3082)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2501)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2162)
        at sbt.JLine.sbt$JLine$$readLineDirectRaw(LineReader.scala:42)
        at sbt.JLine$$anonfun$readLineDirect$2.apply(LineReader.scala:34)
        at sbt.JLine$$anonfun$readLineDirect$2.apply(LineReader.scala:34)
        at sbt.Signals0.withHandler(Signal.scala:81)
        at sbt.Signals$.withHandler(Signal.scala:11)
        at sbt.JLine.readLineDirect(LineReader.scala:34)
        at sbt.JLine.readLineWithHistory(LineReader.scala:27)
        at sbt.JLine.sbt$JLine$$unsynchronizedReadLine(LineReader.scala:19)
        at sbt.JLine$$anonfun$readLine$1.apply(LineReader.scala:16)
        at sbt.JLine$$anonfun$readLine$1.apply(LineReader.scala:16)
        at sbt.JLine$$anonfun$withJLine$1.apply(LineReader.scala:114)
        at sbt.JLine$$anonfun$withJLine$1.apply(LineReader.scala:112)
        at sbt.JLine$.withTerminal(LineReader.scala:86)
        at sbt.JLine$.withJLine(LineReader.scala:112)
        at sbt.JLine.readLine(LineReader.scala:16)
        at sbt.BasicCommands$$anonfun$shell$1.apply(BasicCommands.scala:164)
        at sbt.BasicCommands$$anonfun$shell$1.apply(BasicCommands.scala:160)
        at sbt.Command$$anonfun$command$1$$anonfun$apply$1.apply(Command.scala:29)
        at sbt.Command$$anonfun$command$1$$anonfun$apply$1.apply(Command.scala:29)
        at sbt.Command$.process(Command.scala:92)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
        at sbt.State$$anon$1.process(State.scala:184)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.MainLoop$.next(MainLoop.scala:98)
        at sbt.MainLoop$.run(MainLoop.scala:91)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
        at sbt.Using.apply(Using.scala:24)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
        at sbt.MainLoop$.runLogged(MainLoop.scala:24)
        at sbt.StandardMain$.runManaged(Main.scala:53)
        at sbt.xMain.run(Main.scala:28)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:57)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:77)
        at xsbt.boot.Launch$.run(Launch.scala:57)
        at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
        at xsbt.boot.Launch$.launch(Launch.scala:65)
        at xsbt.boot.Launch$.apply(Launch.scala:16)
        at xsbt.boot.Boot$.runImpl(Boot.scala:32)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)

Exception occurred while determining completions.
```

**Comment by DavidPerezIngeniero** [comment]
How can I provide my build.sbt?.

**Comment by DavidPerezIngeniero** [comment]
I've discovered that calling the help method of a definedCommand in a State, produces this exception.
This prevents the help and completion system to work ok.
Proably, some plugin has introduced a bad behaved command.
How can I get the name of a Command object?  In the [Command API](http://www.scala-sbt.org/0.13.5/api/index.html#sbt.Command) there's no way to get its name.
I think SBT must be protected from that with try/catch.

**Comment by DavidPerezIngeniero** [comment]
Created pull request https://github.com/sbt/sbt/pull/1916
