### ISSUE TITLE
SBT publish to file system doesn't work

### ISSUE THREAD

**Issue by pauldraper** [sbt/sbt#1917]
...or maybe I'm being dumb.

``` scala
val resolver = Resolver.file("my-test-repo", file(".ivy2"))

lazy val main = project.settings(
  libraryDependencies ++= Seq(
    "org.example" %% "lib" % "0"
  ),
  resolvers := Seq(resolver)
)

lazy val lib = project.settings(
  organization := "org.example",
  publishTo := Some(resolver),
  version := "0"
)
```

Then

```
$ sbt lib/publish main/update
...
[warn]  module not found: org.example#lib_2.10;0
[warn] ==== local: tried
[warn]   /home/paul/.ivy2/local/org.example/lib_2.10/0/ivys/ivy.xml
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/org/example/lib_2.10/0/lib_2.10-0.pom
[warn] ==== my-test-repo: tried
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.example#lib_2.10;0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
sbt.ResolveException: unresolved dependency: org.example#lib_2.10;0: not found
```

If I add `(Resolver.ivyStylePatterns)` to `resolver`, it still fails.

http://stackoverflow.com/questions/28996896/cant-update-after-sbt-publish-to-a-file-resolver

**Comment by jsuereth** [comment]
if you're publishing to an ivy repo, make sure `publishMavenStyle := true`.  I'd love to have that automatically detect which style ot use based on repo, but there are some people still using "Resolver.file" to push maven artifacts, as ivy half-ass supports this.

Also, can you include the publish logs?  Is it acutally pushing the ivy jar to the local repo?

**Comment by pauldraper** [comment]
Adding `(Resolver.ivyStylePatterns)` to `resolver`, and `publishMavenStyle := false` to `lib` works.

Thanks.

The three other possible combinations of `ivyStylePatterns`/`mavenStylePatterns` and `publishMavenStyle := true`/`false` did not work.

Full output of the initial build.sbt (FYI, reproducing is very easy, as it only requires only that file):

```
~/test9$ rm -fr .ivy2 && sbt lib/publish main/update
[info] Loading project definition from /home/paul/test9/project
[info] Set current project to test9 (in build file:/home/paul/test9/)
[warn] No main class detected
[info] Wrote /home/paul/test9/lib/target/scala-2.10/lib_2.10-0.pom
[info] :: delivering :: org.example#lib_2.10;0 :: 0 :: release :: Sat Mar 14 20:43:29 MDT 2015
[info]  delivering ivy file to /home/paul/test9/lib/target/scala-2.10/ivy-0.xml
[info]  published lib_2.10 to /home/paul/test9/.ivy2/org/example/lib_2.10/0.part/lib_2.10-0.pom
[info]  published lib_2.10 to /home/paul/test9/.ivy2/org/example/lib_2.10/0.part/lib_2.10-0.jar
[info]  published lib_2.10 to /home/paul/test9/.ivy2/org/example/lib_2.10/0.part/lib_2.10-0-sources.jar
[info]  published lib_2.10 to /home/paul/test9/.ivy2/org/example/lib_2.10/0.part/lib_2.10-0-javadoc.jar
[info]  publish commited: moved /home/paul/test9/.ivy2/org/example/lib_2.10/0.part 
[info]      to /home/paul/test9/.ivy2/org/example/lib_2.10/0
[success] Total time: 1 s, completed Mar 14, 2015 8:43:29 PM
[info] Updating {file:/home/paul/test9/}main...
[info] Resolving org.example#lib_2.10;0 ...
[warn]  module not found: org.example#lib_2.10;0
[warn] ==== local: tried
[warn]   /home/paul/.ivy2/local/org.example/lib_2.10/0/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/example/lib_2.10/0/lib_2.10-0.pom
[warn] ==== my-test-repo: tried
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.example#lib_2.10;0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]      org.example:lib_2.10:0 (/home/paul/test9/build.sbt#L4)
[warn]        +- main:main_2.10:0.1-SNAPSHOT
sbt.ResolveException: unresolved dependency: org.example#lib_2.10;0: not found
    at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:278)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:175)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:157)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:151)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:151)
    at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:128)
    at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:56)
    at sbt.IvySbt$$anon$4.call(Ivy.scala:64)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:98)
    at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:81)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:102)
    at xsbt.boot.Using$.withResource(Using.scala:11)
    at xsbt.boot.Using$.apply(Using.scala:10)
    at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:62)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:52)
    at xsbt.boot.Locks$.apply0(Locks.scala:31)
    at xsbt.boot.Locks$.apply(Locks.scala:28)
    at sbt.IvySbt.withDefaultLogger(Ivy.scala:64)
    at sbt.IvySbt.withIvy(Ivy.scala:123)
    at sbt.IvySbt.withIvy(Ivy.scala:120)
    at sbt.IvySbt$Module.withModule(Ivy.scala:151)
    at sbt.IvyActions$.updateEither(IvyActions.scala:157)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1318)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1315)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$85.apply(Defaults.scala:1345)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$85.apply(Defaults.scala:1343)
    at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1348)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1342)
    at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
    at sbt.Classpaths$.cachedUpdate(Defaults.scala:1360)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1300)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1275)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] (main/*:update) sbt.ResolveException: unresolved dependency: org.example#lib_2.10;0: not found
[error] Total time: 3 s, completed Mar 14, 2015 8:43:32 PM
```

(Note that `.ivy` I am attempting to use is a new directory in current project, **not** the default `~/.ivy` repository.)

I'm not extremely familar with Ivy/Maven, but it seems(?) there may be a bug and a feature request here
- publishing or resolving a local maven repo doesn't work
- it would be nice to not duplicate the Ivy/Maven information both in the resolver and `publishMavenStyle`

**Comment by eed3si9n** [comment]
Hello from 2019.

I think this is mostly a documentation issue, which I am fixing in https://github.com/sbt/website/pull/832

The gist is:

```scala
publishTo := Some(MavenCache("local-maven", file("path/to/maven-repo/releases")))
```

and

```scala
resolvers += MavenCache("local-maven", file("path/to/maven-repo/releases"))
```

should work for Maven style repo.
