### ISSUE TITLE
*/*:key is undefined - sbt.Extracted remove the previously defined TaskKey while append method

### ISSUE THREAD

**Issue by bilyush** [sbt/sbt#1947]
## steps

The example sbt project is [sbt.Extracted append-example](http://pastebin.com/zEWhcCki), to reproduce the issue just run `sbt fooCmd`

I have tested that with

```
sbt.version=0.13.8
sbt.version=0.13.6
```

and 

```
scalaVersion 2.11.5
```
## problem

There is a suitable method in the sbt.Exctracted to add the TaskKey to the current state. Assume I have inState: State:

```
val key1 = TaskKey[String]("key1")
Project.extract(inState).append(Seq(key1 := "key1 value"), inState)
```

I got the exception in the following example:

```
val key1 = TaskKey[String]("key1")
val key2 = TaskKey[String]("key2")
val st1: State = Project.extract(inState).append(Seq(key1 := "key1 value"), inState)
val st2: State = Project.extract(st1).append(Seq(key2 := "key2 value"), st1)
Project.extract(st2).runTask(key1, st2)
```

leads to:

```
java.lang.RuntimeException: */*:key1 is undefined.
```
## expectation

no errors, can extract the value of `key1` and `key2` from recent `state`

**Comment by dwijnand** [comment]
interesting. I thought this might be fixed with `Extracted#appendWithSession` (#3865) but no:

```scala
TaskKey[Unit]("t") := {
  val inState = state.value
  val key1 = TaskKey[Unit]("key1")
  val key2 = TaskKey[Unit]("key2")
  val st1: State = Project.extract(inState).appendWithSession(Seq(key1 := println("key1 value")), inState)
  val st2: State = Project.extract(st1).appendWithSession(Seq(key2 := println("key2 value")), st1)
  try Project.extract(st2).runTask(key1, st2)
  catch {
    case t: Throwable => t.printStackTrace()
  }
}
```

```
> t
[info] Set current project to t-append (in build file:/s/t-append/)
[info] Set current project to t-append (in build file:/s/t-append/)
java.lang.RuntimeException: Global / key1 is undefined.
	at scala.sys.package$.error(package.scala:27)
	at sbt.Extracted.$anonfun$getOrError$1(Extracted.scala:116)
	at scala.Option.getOrElse(Option.scala:121)
	at sbt.Extracted.getOrError(Extracted.scala:116)
	at sbt.Extracted.runTask(Extracted.scala:61)
	at $e094ad08514769059dc4$.$anonfun$$sbtdef$1(/s/t-append/build.sbt:7)
	at $e094ad08514769059dc4$.$anonfun$$sbtdef$1$adapted(/s/t-append/build.sbt:1)
	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
	at sbt.std.Transform$$anon$4.work(System.scala:66)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
	at sbt.Execute.work(Execute.scala:271)
	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
