### ISSUE TITLE
Dependency resolution is inconsistent between runs

### ISSUE THREAD

**Issue by jkutner** [sbt/sbt#1953]
With this sample project:
https://github.com/jkutner/sbt-dependency-bug

The first run of `sbt udpate` results in this error:

``` sh-session
$ sbt update
[info] Loading global plugins from /Users/jkutner/.sbt/0.13/plugins/project
[info] Loading global plugins from /Users/jkutner/.sbt/0.13/plugins
[info] Loading project definition from /Users/jkutner/workspace/heroku/support/apps/drovers/project
[info] Set current project to activator-sbt-problem (in build file:/Users/jkutner/workspace/heroku/support/apps/drovers/)
[info] Updating {file:/Users/jkutner/workspace/heroku/support/apps/drovers/}root...
[info] Resolving jline#jline;2.12.1 ...
[info] downloading https://repo.typesafe.com/typesafe/releases/org/eclipse/mylyn/github/org.eclipse.egit.github.core/3.4.0.201406110918-r/org.eclipse.egit.github.core-3.4.0.201406110918-r.jar ...
[warn]  [FAILED     ] org.eclipse.mylyn.github#org.eclipse.egit.github.core;3.4.0.201406110918-r!org.eclipse.egit.github.core.jar(eclipse-plugin): The HTTP response code for https://repo.typesafe.com/typesafe/releases/org/eclipse/mylyn/github/org.eclipse.egit.github.core/3.4.0.201406110918-r/org.eclipse.egit.github.core-3.4.0.201406110918-r.jar did not indicate a success. See log for more detail. (53ms)
[warn]  [FAILED     ] org.eclipse.mylyn.github#org.eclipse.egit.github.core;3.4.0.201406110918-r!org.eclipse.egit.github.core.jar(eclipse-plugin): The HTTP response code for https://repo.typesafe.com/typesafe/releases/org/eclipse/mylyn/github/org.eclipse.egit.github.core/3.4.0.201406110918-r/org.eclipse.egit.github.core-3.4.0.201406110918-r.jar did not indicate a success. See log for more detail. (53ms)
[warn] ==== Typesafe Releases Repository: tried
[warn]   https://repo.typesafe.com/typesafe/releases/org/eclipse/mylyn/github/org.eclipse.egit.github.core/3.4.0.201406110918-r/org.eclipse.egit.github.core-3.4.0.201406110918-r.jar
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::              FAILED DOWNLOADS            ::
[warn]  :: ^ see resolution messages for details  ^ ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.eclipse.mylyn.github#org.eclipse.egit.github.core;3.4.0.201406110918-r!org.eclipse.egit.github.core.jar(eclipse-plugin)
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
sbt.ResolveException: download failed: org.eclipse.mylyn.github#org.eclipse.egit.github.core;3.4.0.201406110918-r!org.eclipse.egit.github.core.jar(eclipse-plugin)
    at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:291)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:188)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:165)
...
[error] (*:update) sbt.ResolveException: download failed: org.eclipse.mylyn.github#org.eclipse.egit.github.core;3.4.0.201406110918-r!org.eclipse.egit.github.core.jar(eclipse-plugin)
[error] Total time: 7 s, completed Apr 3, 2015 8:09:16 AM
```

The second run, with no changes in between, results in this:

``` sh-session
$ sbt update
[info] Loading global plugins from /Users/jkutner/.sbt/0.13/plugins/project
[info] Loading global plugins from /Users/jkutner/.sbt/0.13/plugins
[info] Loading project definition from /Users/jkutner/workspace/heroku/support/apps/drovers/project
[info] Set current project to activator-sbt-problem (in build file:/Users/jkutner/workspace/heroku/support/apps/drovers/)
[info] Updating {file:/Users/jkutner/workspace/heroku/support/apps/drovers/}root...
[info] Resolving jline#jline;2.12.1 ...
[info] downloading https://repo.typesafe.com/typesafe/releases/org/eclipse/mylyn/github/org.eclipse.egit.github.core/3.4.0.201406110918-r/org.eclipse.egit.github.core-3.4.0.201406110918-r.jar ...
[warn]  [FAILED     ] org.eclipse.mylyn.github#org.eclipse.egit.github.core;3.4.0.201406110918-r!org.eclipse.egit.github.core.jar(eclipse-plugin): The HTTP response code for https://repo.typesafe.com/typesafe/releases/org/eclipse/mylyn/github/org.eclipse.egit.github.core/3.4.0.201406110918-r/org.eclipse.egit.github.core-3.4.0.201406110918-r.jar did not indicate a success. See log for more detail. (253ms)
[info] downloading https://repo.eclipse.org/content/repositories/releases/org/eclipse/mylyn/github/org.eclipse.egit.github.core/3.4.0.201406110918-r/org.eclipse.egit.github.core-3.4.0.201406110918-r.jar ...
[info]  [SUCCESSFUL ] org.eclipse.mylyn.github#org.eclipse.egit.github.core;3.4.0.201406110918-r!org.eclipse.egit.github.core.jar(eclipse-plugin) (1035ms)
[info] Done updating.
[success] Total time: 6 s, completed Apr 3, 2015 8:09:34 AM
```

I have experimented with various combinations of these resolvers and can never get it to work the first time:

``` scala
resolvers += "Eclipse egit Repository" at "http://repo.eclipse.org/content/repositories/egit-releases/"

resolvers += "Eclipse Foundation Releases" at "https://repo.eclipse.org/content/repositories/releases/"

resolvers += "Eclipse Foundation Snapshots" at "https://repo.eclipse.org/content/repositories/snapshots/"
```

**Comment by eed3si9n** [comment]
Thanks for creating a repro test and reporting this!

**Comment by dwijnand** [comment]
Hmm I can't reproduce this.. @jkutner are you still able to reproduce the problem with that repo?

```
23:21:12 sbt update
[info] Loading global plugins from /Users/dnw/.dotfiles/.sbt/0.13/plugins
[info] Loading project definition from /Users/dnw/Desktop/sbt-dependency-bug/project
[info] Updating {file:/Users/dnw/Desktop/sbt-dependency-bug/project/}sbt-dependency-bug-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to sbt-dependency-bug (in build file:/Users/dnw/Desktop/sbt-dependency-bug/)
[info] Updating {file:/Users/dnw/Desktop/sbt-dependency-bug/}root...
[info] Resolving jline#jline;2.12.1 ...
[info] downloading https://repo.eclipse.org/content/repositories/releases/org/eclipse/mylyn/github/org.eclipse.egit.github.core/3.4.0.201406110918-r/org.eclipse.egit.github.core-3.4.0.201406110918-r.jar ...
[info]  [SUCCESSFUL ] org.eclipse.mylyn.github#org.eclipse.egit.github.core;3.4.0.201406110918-r!org.eclipse.egit.github.core.jar(eclipse-plugin) (1358ms)
[info] Done updating.
[success] Total time: 73 s, completed 22-May-2015 23:23:00
23:23:00 sbt update
[info] Loading global plugins from /Users/dnw/.dotfiles/.sbt/0.13/plugins
[info] Loading project definition from /Users/dnw/Desktop/sbt-dependency-bug/project
[info] Set current project to sbt-dependency-bug (in build file:/Users/dnw/Desktop/sbt-dependency-bug/)
[info] Updating {file:/Users/dnw/Desktop/sbt-dependency-bug/}root...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[success] Total time: 2 s, completed 22-May-2015 23:23:16
23:23:16
```

**Comment by jkutner** [comment]
I can't reproduce it either now. Does that mean something was repaired in the repository? This was reported on Heroku, and reproduced in local environments.

**Comment by dwijnand** [comment]
`repo.typesafe.com` has recently been tweaked/reconfigured at least once, see https://github.com/sbt/sbt/issues/1820#issuecomment-97453246, so it could simply be that.
