### ISSUE TITLE
Plugin uses incorrect 'lib' directory

### ISSUE THREAD

**Issue by 404-** [sbt/sbt#1975]
According to the [Plugins/Global plugins example](http://www.scala-sbt.org/release/docs/Plugins.html#Global+plugins+example) section in the docs:

```
A Plugin may be directly defined in Scala source files in ~/.sbt/0.13/plugins/, such as ~/.sbt/0.13/plugins/MyPlugin.scala. ~/.sbt/0.13/plugins//build.sbt should contain sbtPlugin := true.
```

It seems that with this approach, the plugin will attempt to use the `lib` directory of the `project` directory of the project from where SBT is launched. To demonstrate (using SBT 0.13.8):

(1) In the `~/.sbt/0.13/plugins/`directory:

```
//File: build.sbt 
sbtPlugin := true
```

```
//File: SamplePlugin.scala 
import com.typesafe.config.ConfigFactory

import sbt._
import Keys._

object SamplePlugin extends AutoPlugin {
  private val cfg = ConfigFactory parseString
    s"""foo {
       |  value = "value was set by SamplePlugin from Config"
       |}
       |""".stripMargin
  object autoImport {
    val foo = SettingKey[String]("foo", "this is a custom setting called 'foo'")
  }
  import autoImport._
  override def trigger = allRequirements
  override val projectSettings = Seq(foo := cfg getString "foo.value")
}
```

(2) Add `config-1.2.1.jar` (Typesafe config library) under `~/.sbt/0.13/plugins/lib/`
(3) In the `/opt/exploration/sbt/sbt-plugin-demo/`directory:

```
//File: build.sbt
foo := "overridden in build.sbt"
```

(4) execute `sbt` from `/opt/exploration/sbt/sbt-plugin-demo` to attempt to get into the SBT console
Observed:

```
sbt.IncompatiblePluginsException: Binary incompatibility in plugins detected.
    at sbt.PluginDiscovery$.incompatiblePlugins(PluginDiscovery.scala:144)
    at sbt.PluginDiscovery$.loadModules(PluginDiscovery.scala:134)
...omitted...
        at xsbt.boot.Boot$.main(Boot.scala:17)
    at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.NoClassDefFoundError: com/typesafe/config/ConfigFactory
    at SamplePlugin$.<init>(SamplePlugin.scala:7)
    at SamplePlugin$.<clinit>(SamplePlugin.scala)
    at java.lang.Class.forName0(Native Method)
...omitted...
        at xsbt.boot.Boot$.main(Boot.scala:17)
    at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.ClassNotFoundException: com.typesafe.config.ConfigFactory
    at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
...omitted...
    at xsbt.boot.Boot$.main(Boot.scala:17)
    at xsbt.boot.Boot.main(Boot.scala)
[error] sbt.IncompatiblePluginsException: Binary incompatibility in plugins detected.
```

(5) Now, move the lib directory:
`mkdir -p /opt/exploration/sbt/sbt-plugin-demo/project`
`mv ~/.sbt/0.13/plugins/lib /opt/exploration/sbt/sbt-plugin-demo/project/`
(6) execute `sbt` again and, voila, everything works like a charm

```
> inspect foo
[info] Setting: java.lang.String = overridden in build.sbt
[info] Description:
[info]  this is a custom setting called 'foo'
[info] Provided by:
[info]  {file:/opt/exploration/sbt/sbt-plugin-demo/}sbt-plugin-demo/*:foo
[info] Defined at:
[info]  /opt/exploration/sbt/sbt-plugin-demo/build.sbt:1
[info] Delegates:
[info]  *:foo
[info]  {.}/*:foo
[info]  */*:foo
```

**Comment by eed3si9n** [comment]
So #1974 and this one seem to be a pair of issues.
