### ISSUE TITLE
java.net.SocketException when running forked tests

### ISSUE THREAD

**Issue by Tvaroh** [sbt/sbt#2003]
Hello.

I'm getting the following error when running tests from sbt using fork option (in separate Java machine):

```
[error] Uncaught exception when running tests: java.net.SocketException: Permission denied: connect
Exception in thread "Thread-1" java.io.EOFException
        at java.io.ObjectInputStream$BlockDataInputStream.peekByte(Unknown Source)
        at java.io.ObjectInputStream.readObject0(Unknown Source)
        at java.io.ObjectInputStream.readObject(Unknown Source)
        at sbt.React.react(ForkTests.scala:114)
        at sbt.ForkTests$$anonfun$mainTestTask$1$Acceptor$2$.run(ForkTests.scala:74)
        at java.lang.Thread.run(Unknown Source)
```

After that sbt just freezes forever. Looks like sbt is trying to connect to forked process with no luck.

It can be reproduced on three Windows machines (versions 7 and 8) from my company local domain. On my home Mac and other Windows machines it works fine.

How can I investigate this issue?

**Comment by eed3si9n** [comment]
Could you try 

```
sbt -Djava.net.preferIPv4Stack=true
```

http://stackoverflow.com/questions/16110345/i-get-java-net-socketexception-permission-denied-connect-when-sending-an-email

**Comment by Tvaroh** [comment]
It worked! Thank you so much, Eugene.
