### ISSUE TITLE
Project loading failed

### ISSUE THREAD

**Issue by carloshepe** [sbt/sbt#2044]
I get this error when run sbt command. I am using windows8, jdk8
E:\work\workspace\knowlege\play-scala-di>sbt
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
java.lang.IllegalArgumentException: URI has an authority component
        at java.io.File.<init>(File.java:423)
        at sbt.Classpaths$.sbt$Classpaths$$bootRepository(Defaults.scala:1758)
        at sbt.Classpaths$$anonfun$appRepositories$1.apply(Defaults.scala:1729)
        at sbt.Classpaths$$anonfun$appRepositories$1.apply(Defaults.scala:1729)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at sbt.Classpaths$.appRepositories(Defaults.scala:1729)
        at sbt.Classpaths$$anonfun$41.apply(Defaults.scala:1102)
        at sbt.Classpaths$$anonfun$41.apply(Defaults.scala:1102)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
        at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
        at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
        at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by carloshepe** [comment]
sbt 0.13.5 works well, same environment sbt 0.13.8 throw th above exception

**Comment by albuch** [comment]
fixing C:/Users/USER/.sbt/repositories under Windows 7 64-bit to three slashes for file protocoll resolves the issue for me.

```
[repositories]
  local
  activator-launcher-local: file:///${activator.local.repository-${activator.home-${user.home}/.activator}/repository}, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  activator-local: file:///${activator.local.repository-//D:/activator-1.3.4/repository}, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  maven-central
...
```

There are already issues reported at Activator: 
https://github.com/typesafehub/activator/issues/1037
https://github.com/typesafehub/activator/issues/1033

**Comment by carloshepe** [comment]
thanks, it works for me too

**Comment by keepscoding** [comment]
Where is the repositories file? in the C:/Users/<USER>/.sbt/repositories
I can see my .sbt folder but can't find repositories? I'm using win8.1 pro 64bit

**Comment by mprentic-harris** [comment]
@keepscoding I had to remove the `~/.sbt/` dir and then run activator again for it to create my `~/.sbt/repositories` file. Then I was able to add the `/` to the `file://` URLs to fix the issue.

**Comment by keepscoding** [comment]
Thanks...

**Comment by kennandavison** [comment]
http://puu.sh/jrwXm/90bab27c2a.png

Any reason that my repositories folder isn't showing up? I've deleted the .sbt server and run activator ui in git bash, but it doesn't seem to be generating.

**Comment by keepscoding** [comment]
follow what @mprentic-harris said.... it worked for me...

**Comment by gtrub00** [comment]
three slashes worked for me...

**Comment by jstriedinger** [comment]
Hey guys! I'm still having the problem that I do not find any repositories folder in `~/.sbt` folder. I'm running a 64bit Windows 8.1

This is giving me a headache.

**Comment by cweinreben** [comment]
Had the same problem on a Windows 10 PC. 
Adding a text file
C:/Users/USER/.sbt/repositories 
with the content

```
[repositories]
  local
  activator-launcher-local: file:///${activator.local.repository-${activator.home-${user.home}/.activator}/repository}, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  maven-central  
```

fixed the problem.

**Comment by stink0r** [comment]
The previous one from "cweinreben" actually worked for me on Win10 x64, thank you! But for others: Watchout the invisible whitespaces after "maven-central", and remove them – then it works!
