### ISSUE TITLE
SBT fails to work on Fedora and Debian

### ISSUE THREAD

**Issue by russel** [sbt/sbt#2060]
Some time ago SBT stopped working, but I just switched to Gradle. Now that SBT has repositories for Debian debs and Fedora rpms I tried SBT again. I set up and installed the Fedora RPM. However I get exactly the same problem I got before, see below. I have OpenJDK8 installed via packaging, but normally use an OracleJDK8 installation, and indeed a JDK9 install whenever possible.

```
scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
    at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:16)
    at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:17)
    at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:48)
    at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:40)
    at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:40)
    at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:61)
    at scala.reflect.internal.Mirrors$RootsBase.getClassByName(Mirrors.scala:99)
    at scala.reflect.internal.Mirrors$RootsBase.getRequiredClass(Mirrors.scala:102)
    at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:264)
    at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:264)
    at scala.reflect.internal.Definitions$DefinitionsClass.AnyRefClass$lzycompute(Definitions.scala:263)
    at scala.reflect.internal.Definitions$DefinitionsClass.AnyRefClass(Definitions.scala:263)
    at scala.reflect.internal.Definitions$DefinitionsClass.specialPolyClass(Definitions.scala:1120)
    at scala.reflect.internal.Definitions$DefinitionsClass.RepeatedParamClass$lzycompute(Definitions.scala:407)
    at scala.reflect.internal.Definitions$DefinitionsClass.RepeatedParamClass(Definitions.scala:407)
    at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreClasses$lzycompute(Definitions.scala:1154)
    at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreClasses(Definitions.scala:1152)
    at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode$lzycompute(Definitions.scala:1196)
    at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode(Definitions.scala:1196)
    at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1261)
    at scala.tools.nsc.Global$Run.<init>(Global.scala:1290)
    at sbt.compiler.Eval$$anon$1.<init>(Eval.scala:141)
    at sbt.compiler.Eval.run$lzycompute$1(Eval.scala:141)
    at sbt.compiler.Eval.run$1(Eval.scala:141)
    at sbt.compiler.Eval.unlinkAll$1(Eval.scala:144)
    at sbt.compiler.Eval.evalCommon(Eval.scala:153)
    at sbt.compiler.Eval.eval(Eval.scala:96)
    at sbt.EvaluateConfigurations$.evaluateDslEntry(EvaluateConfigurations.scala:177)
    at sbt.EvaluateConfigurations$$anonfun$9.apply(EvaluateConfigurations.scala:117)
    at sbt.EvaluateConfigurations$$anonfun$9.apply(EvaluateConfigurations.scala:115)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at sbt.EvaluateConfigurations$.evaluateSbtFile(EvaluateConfigurations.scala:115)
    at sbt.Load$.sbt$Load$$loadSettingsFile$1(Load.scala:712)
    at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:717)
    at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:716)
    at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
    at scala.collection.AbstractMap.getOrElse(Map.scala:58)
    at sbt.Load$.sbt$Load$$memoLoadSettingsFile$1(Load.scala:716)
    at sbt.Load$$anonfun$loadFiles$1$2.apply(Load.scala:723)
    at sbt.Load$$anonfun$loadFiles$1$2.apply(Load.scala:723)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at sbt.Load$.loadFiles$1(Load.scala:723)
    at sbt.Load$.discoverProjects(Load.scala:734)
    at sbt.Load$.discover$1(Load.scala:545)
    at sbt.Load$.loadTransitive(Load.scala:574)
    at sbt.Load$.loadProjects$1(Load.scala:442)
    at sbt.Load$.loadUnit(Load.scala:446)
    at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
    at sbt.Load$$anonfun$18$$anonfun$apply$11.apply(Load.scala:281)
    at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
    at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
    at sbt.BuildLoader.apply(BuildLoader.scala:140)
    at sbt.Load$.loadAll(Load.scala:334)
    at sbt.Load$.loadURI(Load.scala:289)
    at sbt.Load$.load(Load.scala:285)
    at sbt.Load$.load(Load.scala:276)
    at sbt.Load$.apply(Load.scala:130)
    at sbt.Load$.defaultLoad(Load.scala:36)
    at sbt.BuiltinCommands$.doLoadProject(Main.scala:481)
    at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
    at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
    at sbt.Command$.process(Command.scala:92)
    at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
    at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
    at sbt.State$$anon$1.process(State.scala:184)
    at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
    at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.MainLoop$.next(MainLoop.scala:98)
    at sbt.MainLoop$.run(MainLoop.scala:91)
    at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
    at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
    at sbt.Using.apply(Using.scala:24)
    at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
    at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
    at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
    at sbt.MainLoop$.runLogged(MainLoop.scala:24)
    at sbt.StandardMain$.runManaged(Main.scala:53)
    at sbt.xMain.run(Main.scala:28)
    at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
    at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
    at xsbt.boot.Launch$.run(Launch.scala:109)
    at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
    at xsbt.boot.Launch$.launch(Launch.scala:117)
    at xsbt.boot.Launch$.apply(Launch.scala:18)
    at xsbt.boot.Boot$.runImpl(Boot.scala:41)
    at xsbt.boot.Boot$.main(Boot.scala:17)
    at xsbt.boot.Boot.main(Boot.scala)
[error] scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
```

**Comment by eed3si9n** [comment]
Thanks for the report. On this particular machine, what do

```
$ java -version
$ which java
$ which sbt
```

print out?

**Comment by russel** [comment]
Hummm… I think I am about to have to admit error and embarrassment.

The problem above happens if I start SBT with JDK9, which is my default Java. I often have to switch to JDK8 for applications which are unable to cope with JDK9, I have some aliases for this to save having to regularly type the extra bits. These had been working for my Gradle use but there was a subtle fault that meant even though I thought I was using JDK8 for SBT (and getting the above problem), it was actually launching with JDK9. Fixing the aliases means SBT works entirely fine.

So there is a bug here, just not the one I was originally reporting. The bug is that SBT doesn't work with JDK9.

Thanks for asking for the obvious data, it made me spot the problem. My embarrassment is that I should have done it myself without prompting.

Should this issue be closed and a new JDK9 opened or should this be morphed into that bug report?

**Comment by eed3si9n** [comment]
I don't think Scala 2.10.x works with Java 9. I'll close this up, but could you resubmit an issue to display a warning if sbt detects JDK 9?

**Comment by russel** [comment]
Shouldn't SBT be using Scala 2.11 by now? Is there a problem holding back the upgrade?

I'll raise a separate issue for JDK9.

**Comment by SethTisue** [comment]
> Shouldn't SBT be using Scala 2.11 by now? 

sbt 1.0.x uses Scala 2.12

the sbt 0.13.x series is stuck on Scala 2.10 forever, since that's the Scala version all of the community's plugins are published for
