### ISSUE TITLE
Trouble when opening sbt by Windows 7 console on a project created by Activator

### ISSUE THREAD

**Issue by thiagoaag** [sbt/sbt#2069]
SBT installed in Win 7 that I have run it by 'cmd' occurs the following error:

```
java.lang.IllegalArgumentException: URI has an authority component
        at java.io.File.<init>(File.java:423)
        at sbt.Classpaths$.sbt$Classpaths$$bootRepository(Defaults.scala:1758)
        at sbt.Classpaths$$anonfun$appRepositories$1.apply(Defaults.scala:1729)
        at sbt.Classpaths$$anonfun$appRepositories$1.apply(Defaults.scala:1729)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at sbt.Classpaths$.appRepositories(Defaults.scala:1729)
        at sbt.Classpaths$$anonfun$41.apply(Defaults.scala:1102)
        at sbt.Classpaths$$anonfun$41.apply(Defaults.scala:1102)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
        at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
        at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
        at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
[error] java.lang.IllegalArgumentException: URI has an authority component
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? i
```

What's problem?

**Comment by eed3si9n** [comment]
Seems to be related to http://stackoverflow.com/questions/2366270/what-does-uri-has-an-authority-component-mean.
How did you install sbt?

**Comment by thiagoaag** [comment]
By sbt-0.13.8.msi

**Comment by thiagoaag** [comment]
I have a project created by 'activator' (Play framework - scala), but can't run by sbt on 'cmd' of Win7

**Comment by eed3si9n** [comment]
Can you use `sbt` on non-activator created projects like if you git cloned some OSS project?
Also could you try

```
sbt -Dsbt.global.base=C:\Foo\.sbt
```

Assuming you give writing rights to `C:\Foo\`.

**Comment by thiagoaag** [comment]
Thanks! 
with this command works fine.

**Comment by eed3si9n** [comment]
So likely you have some rights issue? I'm closing this for now.
