### ISSUE TITLE
sbt doesn't work correctly when specify "-Ybackend:GenBCode"

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt#2076]
- `build.sbt`

``` scala
scalacOptions ++= List("-Ybackend:GenBCode")

scalaVersion := "2.11.7"
```
- `project/build.properties`

```
sbt.version=0.13.9-M1
```
- `Main.scala`

``` scala
package com.example

object Main {
  def main(args: Array[String]): Unit = {
    println("hello")
  }
}
```

`sbt run clean run`

```
$ sbt run clean run
[info] Loading global plugins from /Users/user/.sbt/0.13/plugins
[info] Loading project definition from /Users/user/sbt-GenBCode/project
[info] Updating {file:/Users/user/sbt-GenBCode/project/}sbt-genbcode-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to sbt-genbcode (in build file:/Users/user/sbt-GenBCode/)
[info] Updating {file:/Users/user/sbt-GenBCode/}sbt-genbcode...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Compiling 1 Scala source to /Users/user/sbt-GenBCode/target/scala-2.11/classes...
[info] Running com.example.Main 
hello
[success] Total time: 2 s, completed 2015/06/26 9:09:24
[success] Total time: 0 s, completed 2015/06/26 9:09:24
[info] Updating {file:/Users/user/sbt-GenBCode/}sbt-genbcode...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Running com.example.Main 
[error] (run-main-1) java.lang.ClassNotFoundException: com.example.Main
java.lang.ClassNotFoundException: com.example.Main
        at java.lang.ClassLoader.findClass(ClassLoader.java:530)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[trace] Stack trace suppressed: run last compile:run for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) Nonzero exit code: 1
[error] Total time: 0 s, completed 2015/06/26 9:09:25
```

**Comment by retronym** [comment]
Here is the code in SBT that presumes that GenICode has run: https://github.com/sbt/sbt/blob/adb41611cf73260938274915d8462d924df200c8/compile/interface/src/main/scala/xsbt/Analyzer.scala#L29-L41

I think the most straightforward fix is for us to adapt the new backend to populate `run.icodes`. For 2.12, we should also add a new API that encapsulates logic currently in SBT, and then change SBT to use that . SBT could install the current code as an extension method of the same name to remain compatible with old compilers.

This actually points to a design tool for compiler interface: any non-trivial logic that is added ought to be installed as extension methods on the compiler, so that the compiler could opt to provide them natively in the future.

**Comment by retronym** [comment]
Here's a shim for 2.11.8 and 2.12.0-M2 https://github.com/scala/scala/pull/4588

**Comment by dwijnand** [comment]
I can confirm that the above use-case works with 2.12.0-M2.
