### ISSUE TITLE
Parsing error with sbt 0.13.9-RC1

### ISSUE THREAD

**Issue by lespea** [sbt/sbt#2089]
When I tried testing sbt 0.13.9-RC1 I get weird parsing errors with 2 plugins (scalastyle and scalariform); they did not appear in 0.13.9-M1.  [This gist](https://gist.github.com/lespea/c5cac6d6f6942ac8686e) shows a very simple project that illustrates the error, which in this example is:

```
> scalastyle
    ...
> last compile:scalastyle
[info] scalastyle using config /.../scalastyle-config.xml
[debug] Starting scalastyle
[debug] start file /.../src/main/scala/Test.scala
[error] /.../src/main/scala/Test.scala: Expected token RBRACKET but got Token(XML_START_OPEN,<,18,<)
[debug] end file /.../src/main/scala/Test.scala
java.lang.RuntimeException: errors exist
    at scala.sys.package$.error(package.scala:27)
    at org.scalastyle.sbt.Tasks$.onHasErrors$1(Plugin.scala:123)
    at org.scalastyle.sbt.Tasks$.doScalastyleWithConfig$1(Plugin.scala:167)
    at org.scalastyle.sbt.Tasks$.doScalastyle(Plugin.scala:175)
    at org.scalastyle.sbt.ScalastylePlugin$$anonfun$rawScalastyleSettings$1$$anonfun$apply$1$$anonfun$apply$2.apply(Plugin.scala:88)
    at org.scalastyle.sbt.ScalastylePlugin$$anonfun$rawScalastyleSettings$1$$anonfun$apply$1$$anonfun$apply$2.apply(Plugin.scala:76)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by eed3si9n** [comment]
Potentially related #1666 #1765 #2068

**Comment by lespea** [comment]
Just tried this with RC2 and got the same error.

**Comment by lespea** [comment]
Same with RC3

**Comment by marekzebrowski** [comment]
Same with 0.13.9

**Comment by SethTisue** [comment]
not actually an sbt bug, but a scalariform issue (affecting scalastyle as well, since scalastyle depends on scalariform) having to do with Scala 2.10.5 compatibility; see @mrerrormessage's scalariform PR linked above

**Comment by lespea** [comment]
Okay no need to keep this issue open then; we'll just wait for scalariform to update.  Thanks for the update :)

**Comment by kevinmeredith** [comment]
As an aside, could someone please explain what the following error means,

`Expected token RBRACKET but got Token(XML_START_OPEN,<,18,<)`

?

I've seen a similar error in my 200-line test file, yet my error message shows:

`Expected token RBRACKET but got Token(XML_START_OPEN,<,1288,<)`

**Comment by SethTisue** [comment]
@kevinmeredith it means you need to upgrade to a newer version of Scalariform and/or Scalastyle

**Comment by dwijnand** [comment]
@kevinmeredith Seth is right, and it's to do with Scala 2.10 version bumping and things in the `scala.xml` package...

**Comment by kevinmeredith** [comment]
Thank you. Upgrading the scalastyle plugin fixed my issue:

```
-addSbtPlugin("org.scalastyle" %% "scalastyle-sbt-plugin" % "0.7.0")
+addSbtPlugin("org.scalastyle" %% "scalastyle-sbt-plugin" % "0.8.0")
```
