### ISSUE TITLE
Running sbt run throws JNotifyException on mac osx

### ISSUE THREAD

**Issue by sk3749614** [sbt/sbt#2135]
Running sbt run on mac OS X throws the following exception

> sbt run
> 
> [info] Loading project definition from /Users/sampath/devel/workspace/ScopeServer/project
> [info] Set current project to root (in build file:/Users/sampath/devel/workspace/ScopeServer/)
> 
> 2015-07-30 20:26 java[1305](FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
> net.contentobjects.jnotify.macosx.JNotifyException_macosx: Could not start stream
>       at net.contentobjects.jnotify.macosx.JNotify_macosx.nativeAddWatch(Native Method)
>       at net.contentobjects.jnotify.macosx.JNotify_macosx.addWatch(Unknown Source)
>       at net.contentobjects.jnotify.macosx.JNotifyAdapterMacOSX.addWatch(Unknown Source)
>       at net.contentobjects.jnotify.JNotify.addWatch(Unknown Source)
>       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>       at java.lang.reflect.Method.invoke(Method.java:497)
>       at play.runsupport.JNotifyPlayWatchService$JNotifyDelegate.addWatch(PlayWatchService.scala:140)
>       at play.runsupport.JNotifyPlayWatchService$$anonfun$4.apply(PlayWatchService.scala:123)
>       at play.runsupport.JNotifyPlayWatchService$$anonfun$4.apply(PlayWatchService.scala:122)
>       at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
>       at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
>       at scala.collection.immutable.List.foreach(List.scala:318)
>       at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
>       at scala.collection.AbstractTraversable.map(Traversable.scala:105)
>       at play.runsupport.JNotifyPlayWatchService.watch(PlayWatchService.scala:122)
>       at play.runsupport.PlayWatchService$$anon$1.watch(PlayWatchService.scala:74)
>       at play.runsupport.Reloader.<init>(Reloader.scala:268)
>       at play.runsupport.Reloader$.reloader$lzycompute$1(Reloader.scala:174)
>       at play.runsupport.Reloader$.play$runsupport$Reloader$$reloader$1(Reloader.scala:174)
>       at play.runsupport.Reloader$.startDevMode(Reloader.scala:197)
>       at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.devModeServer$lzycompute$1(PlayRun.scala:75)
>       at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.play$PlayRun$class$$anonfun$$anonfun$$anonfun$$devModeServer$1(PlayRun.scala:75)
>       at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:98)
>       at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:54)
>       at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)

I just installed Xcode on the machine. Not sure if it is related to that.

**Comment by sk3749614** [comment]
Restarting the laptop after upgrading the OS seems to have fixed the issue. Cannot see the error now
