### ISSUE TITLE
Error "URI has an authority component" ~/.sbt/repositories support for UNC paths broken in 0.13.9

### ISSUE THREAD

**Issue by jameskoch** [sbt/sbt#2150]
Here's my ~/.sbt/repositories:

```
[repositories]
    local
    integration: file://server.company.com/repo/,[organisation]/[module](_[scalaVersion])(_[sbtVersion])/[revision]/[artifact]-[revision](-[classifier]).[ext]
```

0.13.5:
Mostly worked (still looking into an issue w/ "latest.integration" and "1.2.+" version specifiers not working properly).

0.13.9:
Error starting SBT.

```
java.lang.IllegalArgumentException: URI has an authority component
    at java.io.File.<init>(File.java:423)
    at sbt.Classpaths$.sbt$Classpaths$$bootRepository(Defaults.scala:1781)
    at sbt.Classpaths$$anonfun$appRepositories$1.apply(Defaults.scala:1752)
    at sbt.Classpaths$$anonfun$appRepositories$1.apply(Defaults.scala:1752)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at sbt.Classpaths$.appRepositories(Defaults.scala:1752)
    at sbt.Classpaths$$anonfun$44.apply(Defaults.scala:1117)
    at sbt.Classpaths$$anonfun$44.apply(Defaults.scala:1117)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
    at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
    at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
    at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
    at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

Tried adding third and fourth slashes (file:/// and file:////) to the URI as described at http://stackoverflow.com/questions/30624099/sbt-0-13-8-uri-has-an-authority-component.  In both cases SBT will now load but the resolvers point to the C drive.

```
[info] ArrayBuffer(FileRepository(integration,FileConfiguration(true,None),Patterns(ivyPatterns=List(C:/server.company.com/repo/[organisation]/[module](_[scalaVersion])(_[sbtVersion])/[revision]/[artifact]-[revision](-[classifier]).[ext]), artifactPatterns=List(C:/server.company.com/repo/[organisation]/[module](_[scalaVersion])(_[sbtVersion])/[revision]/[artifact]-[revision](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false)))
```

Similar to #1570

**Comment by eed3si9n** [comment]
Did it break in 0.13.9, or 0.13.6 etc?

**Comment by jameskoch** [comment]
Related issue https://github.com/sbt/sbt/issues/2279 is what I experienced when I described 0.13.5 as "mostly working".

I'll try to find time to bisect your versions for you, if it helps.

**Comment by ajitspendse** [comment]
Changing URI from file:// to file:/// seems to have resolved this issue for me.

**Comment by eed3si9n** [comment]
For local path on Windows use `file:///C:/foo/` (three slashes).  For UNC, try `file:////unc/foo/` (four slashes).
