### ISSUE TITLE
`0.13.x or later` arguing on 0.13.8

### ISSUE THREAD

**Issue by ror6ax** [sbt/sbt#2164]
Error is as follows:

```
➜  pewpew  ./sbt -sbt-version 0.13.8
Detected sbt version 0.13.8
Starting sbt: invoke with -help for other options
Using /home/ror6ax/.sbt/0.13.8 as sbt dir, -sbt-dir to override.
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384m; support was removed in 8.0
[ERROR] Terminal initialization failed; falling back to unsupported
java.lang.IncompatibleClassChangeError: Found class jline.Terminal, but interface was expected
    at jline.TerminalFactory.create(TerminalFactory.java:101)
    at jline.TerminalFactory.get(TerminalFactory.java:159)
    at sbt.ConsoleLogger$.ansiSupported(ConsoleLogger.scala:123)
    at sbt.ConsoleLogger$.<init>(ConsoleLogger.scala:117)
    at sbt.ConsoleLogger$.<clinit>(ConsoleLogger.scala)
    at sbt.GlobalLogging$.initial(GlobalLogging.scala:43)
    at sbt.StandardMain$.initialGlobalLogging(Main.scala:60)
    at sbt.StandardMain$.initialState(Main.scala:69)
    at sbt.xMain.run(Main.scala:28)
    at xsbt.boot.Launch$.run(Launch.scala:55)
    at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
    at xsbt.boot.Launch$.launch(Launch.scala:60)
    at xsbt.boot.Launch$.apply(Launch.scala:16)
    at xsbt.boot.Boot$.runImpl(Boot.scala:31)
    at xsbt.boot.Boot$.main(Boot.scala:20)
    at xsbt.boot.Boot.main(Boot.scala)

java.lang.IncompatibleClassChangeError: JLine incompatibility detected.  Check that the sbt launcher is version 0.13.x or later.
    at sbt.ConsoleLogger$.ansiSupported(ConsoleLogger.scala:134)
    at sbt.ConsoleLogger$.<init>(ConsoleLogger.scala:117)
    at sbt.ConsoleLogger$.<clinit>(ConsoleLogger.scala)
    at sbt.GlobalLogging$.initial(GlobalLogging.scala:43)
    at sbt.StandardMain$.initialGlobalLogging(Main.scala:60)
    at sbt.StandardMain$.initialState(Main.scala:69)
    at sbt.xMain.run(Main.scala:28)
    at xsbt.boot.Launch$.run(Launch.scala:55)
    at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
    at xsbt.boot.Launch$.launch(Launch.scala:60)
    at xsbt.boot.Launch$.apply(Launch.scala:16)
    at xsbt.boot.Boot$.runImpl(Boot.scala:31)
    at xsbt.boot.Boot$.main(Boot.scala:20)
    at xsbt.boot.Boot.main(Boot.scala)
Error during sbt execution: java.lang.IncompatibleClassChangeError: JLine incompatibility detected.  Check that the sbt launcher is version 0.13.x or later.
```

**Comment by ror6ax** [comment]
The following script returns `True`:

object Tst extends App {
val terminal = jline.TerminalFactory.get
terminal.restore
println(terminal.isAnsiSupported);
}

**Comment by jsuereth** [comment]
Is this using the paulp/sbt-extras launcher?

If so, can you use `-d` to show us what it's really running?

**Comment by ror6ax** [comment]
I'm using vanilla `sbt`.

**Comment by jsuereth** [comment]
which launcher?  -sbt-version <x> changes the version of sbt BUT not the launcher version

**Comment by eed3si9n** [comment]
Closing this since the OP has probably moved on.
