### ISSUE TITLE
sbt 0.13.8 fails to download snapshot

### ISSUE THREAD

**Issue by haifengl** [sbt/sbt#2175]
My project needs ews-java-api, which is available only in snapshot. In my build.sbt, I have

resolvers += "Sonatype OSS snapshots" at "https://oss.sonatype.org/content/repositories/snapshots/"

libraryDependencies += "com.microsoft.ews-java-api" % "ews-java-api" % "2.0-SNAPSHOT"

I work behind a firewall. I do set up all proxy related options on SBT command including

-Dhttp.proxyHost
-Dhttp.proxyPort
-Dhttp.proxyUser 
-Dhttp.proxyPassword
-Dhttps.proxyHost
-Dhttps.proxyPort 
-Dhttps.proxyUser 
-Dhttps.proxyPassword

This works well for other libraries. But for snapshot libraries, I got the following error:

```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.microsoft.ews-java-api#ews-java-api;2.0-SNAPSHOT: java.util.NoSuchElementException
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by eed3si9n** [comment]
Could you try sbt 0.13.9? Also could paste the entire error message?

**Comment by eed3si9n** [comment]
I was able to download the artifacts using sbt 0.13.8.

```
sbt-2175> update
[info] Updating {file:/xx/sbt-2175/}sbt-2175...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] downloading https://oss.sonatype.org/content/repositories/snapshots/com/microsoft/ews-java-api/ews-java-api/2.0-SNAPSHOT/ews-java-api-2.0-20150820.223355-44.jar ...
[info]  [SUCCESSFUL ] com.microsoft.ews-java-api#ews-java-api;2.0-SNAPSHOT!ews-java-api.jar (906ms)
[info] downloading https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.4.1/httpclient-4.4.1.jar ...
[info]  [SUCCESSFUL ] org.apache.httpcomponents#httpclient;4.4.1!httpclient.jar (533ms)
[info] downloading https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.4.1/httpcore-4.4.1.jar ...
[info]  [SUCCESSFUL ] org.apache.httpcomponents#httpcore;4.4.1!httpcore.jar (218ms)
[info] downloading https://repo1.maven.org/maven2/joda-time/joda-time/2.8/joda-time-2.8.jar ...
[info]  [SUCCESSFUL ] joda-time#joda-time;2.8!joda-time.jar (284ms)
[info] Done updating.
[success] Total time: 13 s, completed Aug 25, 2015 12:16:53 PM
```

**Comment by haifengl** [comment]
I tried 0.13.9. sbt update works, but sbt package fails:

```
[info] Resolving com.microsoft.ews-java-api#ews-java-api;2.0-SNAPSHOT ...
[error] Server access Error: Connection timed out url=https://repo1.maven.org/maven2/com/microsoft/ews-java-api/ews-java-api/2.0-SNAPSHOT/maven-metadata.xml
[error] Server access Error: Connection timed out url=https://repo1.maven.org/maven2/com/microsoft/ews-java-api/ews-java-api/2.0-SNAPSHOT/ews-java-api-2.0-SNAPSHOT.pom
[error] Server access Error: Connection timed out url=https://oss.sonatype.org/content/repositories/snapshots/com/microsoft/ews-java-api/ews-java-api/2.0-SNAPSHOT/maven-metadata.xml
[error] Server access Error: Connection timed out url=https://oss.sonatype.org/content/repositories/snapshots/com/microsoft/ews-java-api/ews-java-api/2.0-SNAPSHOT/ews-java-api-2.0-SNAPSHOT.pom
[warn]  module not found: com.microsoft.ews-java-api#ews-java-api;2.0-SNAPSHOT
[warn] ==== local: tried
[warn]   /home/timeline/.ivy2/local/com.microsoft.ews-java-api/ews-java-api/2.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/microsoft/ews-java-api/ews-java-api/2.0-SNAPSHOT/ews-java-api-2.0-SNAPSHOT.pom
[warn] ==== Sonatype OSS snapshots: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/com/microsoft/ews-java-api/ews-java-api/2.0-SNAPSHOT/ews-java-api-2.0-SNAPSHOT.pom
[info] Resolving jline#jline;2.12.1 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.microsoft.ews-java-api#ews-java-api;2.0-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[info] Resolving org.slf4j#slf4j-api;1.7.12 ...
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]      com.microsoft.ews-java-api:ews-java-api:2.0-SNAPSHOT (/home/timeline/epic/email/build.sbt#L26-27)
[warn]        +- com.adp.e:email_2.11:1.0.2
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Packaging /home/timeline/epic/timeline/target/scala-2.11/timeline_2.11-1.0.2.jar ...
[info] Done packaging.
sbt.ResolveException: unresolved dependency: com.microsoft.ews-java-api#ews-java-api;2.0-SNAPSHOT: not found
    at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:291)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:188)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:165)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
    at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
    at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
    at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
    at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
    at xsbt.boot.Using$.withResource(Using.scala:10)
    at xsbt.boot.Using$.apply(Using.scala:9)
    at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
    at xsbt.boot.Locks$.apply0(Locks.scala:31)
    at xsbt.boot.Locks$.apply(Locks.scala:28)
    at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
    at sbt.IvySbt.withIvy(Ivy.scala:127)
    at sbt.IvySbt.withIvy(Ivy.scala:124)
    at sbt.IvySbt$Module.withModule(Ivy.scala:155)
    at sbt.IvyActions$.updateEither(IvyActions.scala:165)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1369)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1365)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1399)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1397)
    at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1402)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1396)
    at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
    at sbt.Classpaths$.cachedUpdate(Defaults.scala:1419)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1348)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1310)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] (email/*:update) sbt.ResolveException: unresolved dependency: com.microsoft.ews-java-api#ews-java-api;2.0-SNAPSHOT: not found
```

**Comment by haifengl** [comment]
For your success with 0.13.8, are you behind a corporate firewall? Thanks!

**Comment by eed3si9n** [comment]
No I'm not behind a firewall, but without further information on how I can reproduce the problem myself, there's not much I can do from here. Maybe contact your local network admin?

**Comment by haifengl** [comment]
another try of sbt update fails with the same error message as above.

**Comment by haifengl** [comment]
Without firewall, sbt works well for me too. Unfortunately, I have to work behind the proxy.

**Comment by haifengl** [comment]
I download it on a machine without proxy and then copy it to the .ivy2 on the corporate machine. But sbt doesn't use it.

**Comment by eed3si9n** [comment]
If your firewall is preventing access to https, you could try passing `-Dsbt.repository.secure=false`

**Comment by haifengl** [comment]
https is okay for other packages, but not for snapshot.

**Comment by haifengl** [comment]
-Dsbt.repository.secure=false does the magic!! It works now. Thank you very much!!

**Comment by eed3si9n** [comment]
Glad it helped.
