### ISSUE TITLE
Scala REPL fails with IncompatibleClassChangeError when sbt-launch.jar is in %SCALA_HOME%/lib

### ISSUE THREAD

**Issue by VDinesh** [sbt/sbt#218]
I installed the latest typesafe stack and then downloaded the sbt-launch.jar into the %SCALA_HOME%/lib.  REPL fails to run
Exception in thread "main" java.lang.IncompatibleClassChangeError: Expecting non-static method scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/m
utable/ArrayOps;
        at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:33)

```
    at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:89)
    at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

When that jar is deleted REPL runs fine.
How do I fix this?

**Comment by retronym** [comment]
"Note: do not put sbt-launch.jar in your $SCALA_HOME/lib directory, your project's lib directory, or anywhere it will be put on a classpath."

https://github.com/harrah/xsbt/wiki/Setup

**Comment by VDinesh** [comment]
Thanks a lot Jason.

On Sun, Oct 9, 2011 at 3:00 PM, Jason Zaugg <
reply@reply.github.com>wrote:

> "Note: do not put sbt-launch.jar in your $SCALA_HOME/lib directory, your
> project's lib directory, or anywhere it will be put on a classpath."
> 
> https://github.com/harrah/xsbt/wiki/Setup
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/harrah/xsbt/issues/218#issuecomment-2338080

## 

Regards,
Dinesh V
