### ISSUE TITLE
SBT 0.13.9 resolves to 0.13.8 for Windows installer

### ISSUE THREAD

**Issue by ekis** [sbt/sbt#2181]
Newly installed SBT 0.13.9 reports its version as 0.13.8 unless version is specified explicitly in `build.properties` file. There is only one SBT installation on the system. 

The synopsis of the problem is given [here](http://stackoverflow.com/questions/32051899/why-is-sbt-0-13-9-reporting-that-its-0-13-8).

**Comment by eed3si9n** [comment]
Probably a mistake during packaging. Are you also using the Windows installer?

**Comment by ekis** [comment]
Yes, I am. I tried using the zipped file and overwrite the installation dir - that bumped the reported version to 0.13.9 but introduced this error as I tried to build the project in IDEA:

```
[info] Applying State transformations org.jetbrains.sbt.ReadProject from C:/Users/homeDirectory/.IntelliJIdea14/config/plugins/Scala/launcher/sbt-structure-1.0.jar
java.lang.ClassNotFoundException: org.jetbrains.sbt.ReadProject$
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at sbt.ModuleUtilities$.getObject(ModuleUtilities.scala:14)
    at sbt.BasicCommands$$anonfun$call$2$$anonfun$6.apply(BasicCommands.scala:130)
    at sbt.BasicCommands$$anonfun$call$2$$anonfun$6.apply(BasicCommands.scala:130)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at sbt.BasicCommands$$anonfun$call$2.apply(BasicCommands.scala:130)
    at sbt.BasicCommands$$anonfun$call$2.apply(BasicCommands.scala:125)
    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
    at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
    at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
    at sbt.Command$.process(Command.scala:93)
    at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
    at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
    at sbt.State$$anon$1.process(State.scala:184)
    at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
    at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.MainLoop$.next(MainLoop.scala:98)
    at sbt.MainLoop$.run(MainLoop.scala:91)
    at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
    at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
    at sbt.Using.apply(Using.scala:24)
    at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
    at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
    at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
    at sbt.MainLoop$.runLogged(MainLoop.scala:24)
    at sbt.StandardMain$.runManaged(Main.scala:53)
    at sbt.xMain.run(Main.scala:28)
    at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
    at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
    at xsbt.boot.Launch$.run(Launch.scala:109)
    at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
    at xsbt.boot.Launch$.launch(Launch.scala:117)
    at xsbt.boot.Launch$.apply(Launch.scala:18)
    at xsbt.boot.Boot$.runImpl(Boot.scala:41)
    at xsbt.boot.Boot$.main(Boot.scala:17)
    at xsbt.boot.Boot.main(Boot.scala)
```

Wasn't sure how to proceed to so I reinstalled the MSI-packaged distro back to the installation dir, cleaned the `.ivy` and `.sbt` directories and then did a `Invalidate And Restart` in IDEA. That helped to build the project back but also left the SBT version on 0.13.8. Only after `build.properties` intervention did that report the expected version (0.13.9).

**Comment by jsuereth** [comment]
Just a note:  We're probably going to be forcing `build.properties` to have the sbt version in the future, and you shoudl ALWAYS have it specified now.

I'm a bit suprised, but this could be related to the intellij sbt plugin using the 0.13.8 launcher.

**Comment by ekis** [comment]
Fair enough - I too think having explicit version set is a good thing. Still, I think a utility shouldn't mis-report its version at any time.

FWIW, my IDEA global SBT settings have Launcher point at the `sbt-launch.jar` at the install directory, not the bundled version; the SBT still reported the version as `0.13.8`.

**Comment by donamk** [comment]
This issue makes me so frustrated. I hope this problem is fixed soon.

**Comment by chrisdostert** [comment]
installing via [All Platforms > SBT-0.13.9.ZIP](http://www.scala-sbt.org/download.html) worked for me and actually installed version 0.13.9.

**Comment by eed3si9n** [comment]
I think the root cause is that I didn't modify the `wixProductUpgradeId` in sbt/sbt-launcher-package#89.
There's now a new installer available from http://www.scala-sbt.org/download.html page.
