### ISSUE TITLE
sbt assembly does not find spark streaming library

### ISSUE THREAD

**Issue by ziploc1010** [sbt/sbt#2219]
I tried removing the following directories first:
rm -rf ~/.sbt/
rm -rf ~/.ivy2/
sbt/sbt assembly

But I got the following error:

[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.apache.spark#spark-streaming_2.10;1.5.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]      org.apache.spark:spark-streaming_2.10:1.5.0 (/home/mhagen/Downloads/spark-cassandra-connector/project/CassandraSparkBuild.scala#L50)
[warn]        +- com.datastax.spark:spark-cassandra-connector-embedded_2.10:1.5.0-M2-SNAPSHOT
[warn] Credentials file /home/mhagen/.ivy2/.credentials does not exist
[warn] Credentials file /home/mhagen/.ivy2/.credentials does not exist
sbt.ResolveException: unresolved dependency: org.apache.spark#spark-streaming_2.10;1.5.0: not found
    at sbt.ivyint.CachedResolutionResolveEngine$class.mergeErrors(CachedResolutionResolveEngine.scala:339)
    at sbt.IvySbt$$anon$5$$anon$3.mergeErrors(Ivy.scala:101)
    at sbt.ivyint.CachedResolutionResolveEngine$class.mergeResults(CachedResolutionResolveEngine.scala:326)
    at sbt.IvySbt$$anon$5$$anon$3.mergeResults(Ivy.scala:101)
    at sbt.ivyint.CachedResolutionResolveEngine$$anonfun$customResolve$1.apply(CachedResolutionResolveEngine.scala:315)
    at sbt.ivyint.CachedResolutionResolveEngine$$anonfun$customResolve$1.apply(CachedResolutionResolveEngine.scala:265)
    at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:189)
    at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:632)
    at sbt.ivyint.CachedResolutionResolveCache.getOrElseUpdateProjectReport(CachedResolutionResolveEngine.scala:223)
    at sbt.ivyint.CachedResolutionResolveEngine$class.customResolve(CachedResolutionResolveEngine.scala:265)
    at sbt.IvySbt$$anon$5$$anon$3.customResolve(Ivy.scala:101)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:175)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:165)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
    at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
    at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
    at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
    at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
    at xsbt.boot.Using$.withResource(Using.scala:10)
    at xsbt.boot.Using$.apply(Using.scala:9)
    at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
    at xsbt.boot.Locks$.apply0(Locks.scala:31)
    at xsbt.boot.Locks$.apply(Locks.scala:28)
    at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
    at sbt.IvySbt.withIvy(Ivy.scala:127)
    at sbt.IvySbt.withIvy(Ivy.scala:124)
    at sbt.IvySbt$Module.withModule(Ivy.scala:155)
    at sbt.IvyActions$.updateEither(IvyActions.scala:165)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1369)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1365)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1399)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1397)
    at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1402)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1396)
    at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
    at sbt.Classpaths$.cachedUpdate(Defaults.scala:1419)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1348)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1310)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error](spark-cassandra-connector-embedded/*:update) sbt.ResolveException: unresolved dependency: org.apache.spark#spark-streaming_2.10;1.5.0: not found

**Comment by dwijnand** [comment]
Can you provide a reproducible case please?

**Comment by SylviaVargasCTL** [comment]
I have the same issue.  What specific information do you need to reproduce this error?

**Comment by ziploc1010** [comment]
Hey this helped me:
In the parent directory create a build.sbt file and place the following in it:

libraryDependencies += "org.apache.spark" % "spark-unsafe_2.10" % "1.5.0"
libraryDependencies += "org.apache.spark" % "spark-streaming_2.10" % "1.5.0"
libraryDependencies += "com.datastax.spark" %% "spark-cassandra-connector" % "1.5.0-M1"
libraryDependencies += "com.datastax.spark" %% "spark-cassandra-connector-java" % "1.5.0-M1"

**Comment by markon** [comment]
I have the same issue. I also tried the solution from ziploc1010, but it didn't work for me.

**Comment by eed3si9n** [comment]
I am closing this due to inactivity, but if this is still relevant let us know with more details (reproduction steps etc).
