### ISSUE TITLE
object Def is not a member of package sbt

### ISSUE THREAD

**Issue by GordeevArt** [sbt/sbt#2220]
I use sbt.version=0.12.4 on Fedora 22 x86_64

I have an error when I use command _sbt_:

```
sbt
<expected-type>:1: error: object Def is not a member of package sbt
sbt.Def.SettingsDefinition
    ^
[error] Type error in expression
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
```

But it works in Ubuntu.

**Comment by SethTisue** [comment]
also asked at http://stackoverflow.com/questions/32724229/object-def-is-not-a-member-of-package-sbt, I see. it's polite to crosslink, so that somebody doesn't waste time answering your question in one place, when it was already answered in another.

**Comment by GordeevArt** [comment]
Yes, forgot about link, thanks for copying it here

**Comment by dwijnand** [comment]
Can you provide a reproducible case please?

**Comment by GordeevArt** [comment]
```
> mkdir sbttest/project -p
> cd sbttest/project/
> echo 'sbt.version=0.12.4' > build.properties
> echo 'logLevel := Level.Warn' > plugins.sbt
> cd ..
> sbt
<expected-type>:1: error: object Def is not a member of package sbt
sbt.Def.SettingsDefinition
    ^
[error] Type error in expression
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

**Comment by GordeevArt** [comment]
But without _plugins.sbt_ it works

**Comment by SethTisue** [comment]
What is in the launch script you are using? Here is a transcript showing it working on OS X, eliminating the use of a launch script, so everything that's involved is right there in the transcript:

```
> mkdir -p sbttest/project                                                                                      
> cd sbttest/project                                                                                            
> echo 'sbt.version=0.12.4' > build.properties
> echo 'logLevel := Level.Warn' > plugins.sbt
> cd ..
> curl -s -O -L 'https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.12.4/sbt-launch.jar'
> java -jar sbt-launch.jar                                                                                      
[info] Loading project definition from /Users/tisue/sbttest/project
[info] Set current project to default-a227ae (in build file:/Users/tisue/sbttest/)
> sbt-version
[info] 0.12.4
```

**Comment by GordeevArt** [comment]
I don't actually know what to show.

```
> which sbt
/usr/bin/sbt
> cat /usr/bin/sbt
#!/bin/sh

if \[ $(rpm -q --queryformat '%{version}' fedora-release) -ge 21 \] ; then
export JLINE=jline
else
export JLINE=jline2
fi

export SBT_BOOT_DIR=${SBT_BOOT_DIR:-/usr/share/sbt/boot}
export SBT_IVY_DIR=${SBT_IVY_DIR:-/usr/share/sbt/ivy-local}

if \[ "x$RPM_PACKAGE_NAME" != x \] && \[ -f /etc/sbt/rpmbuild-sbt.boot.properties \] ; then
    export SBT_BOOT_PROPERTIES=${SBT_BOOT_PROPERTIES:-/etc/sbt/rpmbuild-sbt.boot.properties}
else
    export SBT_BOOT_PROPERTIES=${SBT_BOOT_PROPERTIES:-/etc/sbt/sbt.boot.properties}
fi

export BASE_CLASSPATH=$(build-classpath scala ivy sbt ${JLINE} jansi test-interface sbinary)
export JAVA_OPTS="-Xms512M -Xmx1536M -Xss1M -XX:+CMSClassUnloadingEnabled"

java -Xms512M -Xmx1536M -Xss1M -XX:+CMSClassUnloadingEnabled -Dfedora.sbt.boot.dir=${SBT_BOOT_DIR} -Dfedora.sbt.ivy.dir=${SBT_IVY_DIR} -Dsbt.boot.properties=${SBT_BOOT_PROPERTIES} -cp ${BASE_CLASSPATH} xsbt.boot.Boot "$@"

> cat /etc/sbt/sbt.boot.properties
[scala]
  version: 2.10.4

[app]
  org: ${sbt.organization-org.scala-sbt}
  name: sbt
  version: ${sbt.version-read(sbt.version)[0.13.1]}
  class: ${sbt.main.class-sbt.xMain}
  components: xsbti,extra
  cross-versioned: ${sbt.cross.versioned-false}

[repositories]
  local
  fedora: file:${fedora.sbt.ivy.dir-ivy-local}, [organization]/[module]/[revision]/ivy.xml, [organization]/[module]/[revision]/[artifact]-[revision].[ext]
  typesafe-ivy-releases: http://repo.typesafe.com/typesafe/ivy-releases/, [organization]/[module]/[revision]/[type]s/[artifact](-[classifier]).[ext], bootOnly
  maven-central
  sonatype-snapshots: https://oss.sonatype.org/content/repositories/snapshots

[boot]
  directory: ${sbt.boot.directory-${sbt.global.base-${user.home}/.sbt}/boot/}

[ivy]
  ivy-home: ${sbt.ivy.home-${user.home}/.ivy2/}
  checksums: ${sbt.checksums-sha1,md5}
  override-build-repos: ${sbt.override.build.repos-false}
  repository-config: ${sbt.repository.config-${sbt.global.base-${user.home}/.sbt}/repositories}
```

**Comment by GordeevArt** [comment]
By the way, the script above doesn't work for me:

```
> curl -s -O -L 'https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.12.4/sbt-launch.jar'
> java -jar sbt-launch.jar
java.lang.NoSuchMethodError: scala.Predef$.augmentString(Ljava/lang/String;)Lscala/collection/immutable/StringOps;
    at sbt.ConsoleLogger$.<init>(ConsoleLogger.scala:129)
    at sbt.ConsoleLogger$.<clinit>(ConsoleLogger.scala)
    at sbt.StandardMain$.<init>(Main.scala:52)
    at sbt.StandardMain$.<clinit>(Main.scala)
    at sbt.xMain.run(Main.scala:26)
    at xsbt.boot.Launch$.run(Launch.scala:55)
    at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
    at xsbt.boot.Launch$.launch(Launch.scala:60)
    at xsbt.boot.Launch$.apply(Launch.scala:16)
    at xsbt.boot.Boot$.runImpl(Boot.scala:31)
    at xsbt.boot.Boot$.main(Boot.scala:20)
    at xsbt.boot.Boot.main(Boot.scala)
Error during sbt execution: java.lang.NoSuchMethodError: scala.Predef$.augmentString(Ljava/lang/String;)Lscala/collection/immutable/StringOps;
```

**Comment by SethTisue** [comment]
is it possible the results you're getting are affected by being behind some kind of corporate firewall and/or proxying? the NoSuchMethodError you're getting is typically the result of confusion between major Scala versions, but I don't see how such a situation could arise here unless some kind of man-in-the-middle is serving you up the wrong Scala jars.

does it help to delete or move aside your `~/.ivy2` and/or `~/.sbt` and/or `~/.m2` directories? perhaps you have some cached bad artifacts in one of those locations

**Comment by GordeevArt** [comment]
Thanks, removing of these directories helps with _NoSuchMethodError_. But not with _sbt_.

**Comment by eed3si9n** [comment]
The sbt issue tracker is not a support system. Please see [how can I get help?](http://www.scala-sbt.org/community.html#how-can-I-get-help)
