### ISSUE TITLE
Can't use git worktrees with this repo, because of JGit (via sbt-git)

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#2323]
Given the current HEAD of the 0.13 branch: https://github.com/sbt/sbt/commit/d3cb46951b9d674891b76f0fb736ec47a15f82c3

I'm getting:

```
java.lang.RuntimeException: Setting value cannot be null: {file:/Users/dnw/dev/sbt-0.13/}/*:gitCurrentBranch
    at scala.sys.package$.error(package.scala:27)
    at sbt.EvaluateSettings$INode.setValue(INode.scala:143)
    at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
    at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
    at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
    at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
    at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] Setting value cannot be null: {file:/Users/dnw/dev/sbt-0.13/}/*:gitCurrentBranch
```

**Comment by eed3si9n** [comment]
What's `gitCurrentBranch`?

**Comment by dwijnand** [comment]
from sbt-git: https://github.com/sbt/sbt-git/blob/v0.8.5/src/main/scala/com/typesafe/sbt/SbtGit.scala#L15

**Comment by eed3si9n** [comment]
I can't reproduce it. You might have to wipe out `project/target` manually.

**Comment by dwijnand** [comment]
Didn't help..

So I launched sbt with `-no-share` (which desugars to `-Dsbt.global.base=project/.sbtboot -Dsbt.boot.directory=project/.boot -Dsbt.ivy.home=project/.ivy`) and found.. it still fails!

Do you mind seeing if you can reproduce it without using anything in `.ivy2` and `.sbt`? Requires downloading the internet unfortunately..

**Comment by SethTisue** [comment]
I can reproduce this just by `mv .git git`, so my checkout isn't a git repository anymore.

**Comment by SethTisue** [comment]
is it possible your `.git` directory is corrupt somehow?

**Comment by eed3si9n** [comment]
@dwijnand 

I didn't reproduce this after renaming `.ivy2` and `.sbt`:

```
$ cd
$ mv .ivy2 .ivy2_2015
$ mv .sbt .sbt_2015
$ cd work/sbt
$ sbt
```

@SethTisue 

> is it possible your .git directory is corrupt somehow?

nice catch!

**Comment by dwijnand** [comment]
Ok.. found the cause. It's not corruption, but that got me testing (thanks Seth).

It's something to do with git worktrees and sbt-git (and/or who knows what)... So at least I know what to avoid, but it's a real shame as having two workspaces for both 0.13 and 1.0.x is very convenient, especially at this junction of sbt.

Anyways, sorry for all the noise and thank you both for your time.

**Comment by SethTisue** [comment]
np!

**Comment by dwijnand** [comment]
I'm going to reopen this as it's really annoying for me and I intend to fix it.

**Comment by dwijnand** [comment]
After upgrading to sbt-git 0.8.5 (in local commits against the 0.13 branch) the error is now:

```
org.eclipse.jgit.errors.NoWorkTreeException: Bare Repository has neither a working tree, nor an index
    at org.eclipse.jgit.lib.Repository.getWorkTree(Repository.java:1245)
    at org.eclipse.jgit.treewalk.FileTreeIterator.<init>(FileTreeIterator.java:88)
    at org.eclipse.jgit.api.StatusCommand.call(StatusCommand.java:139)
    at com.typesafe.sbt.git.JGit.hasUncommittedChanges(JGit.scala:84)
    at com.typesafe.sbt.SbtGit$$anonfun$buildSettings$8$$anonfun$apply$8.apply(SbtGit.scala:116)
    at com.typesafe.sbt.SbtGit$$anonfun$buildSettings$8$$anonfun$apply$8.apply(SbtGit.scala:116)
    at com.typesafe.sbt.git.DefaultReadableGit.withGit(ReadableGit.scala:35)
    at com.typesafe.sbt.SbtGit$$anonfun$buildSettings$8.apply(SbtGit.scala:116)
    at com.typesafe.sbt.SbtGit$$anonfun$buildSettings$8.apply(SbtGit.scala:116)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
    at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
    at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
    at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
    at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by dwijnand** [comment]
Perhaps this is dependant on support of git worktrees in JGit? Found this: https://bugs.eclipse.org/bugs/show_bug.cgi?id=477475

/cc @jsuereth ?

**Comment by dwijnand** [comment]
One solution here is to switch away from JGit, such as using https://github.com/dwijnand/sbt-dynver.

@eed3si9n what do you think?

**Comment by eed3si9n** [comment]
I don't use worktree so I don't have strong opinion about this.

**Comment by milessabin** [comment]
How hard would it be to fix upstream in JGit?

**Comment by milessabin** [comment]
Comment [here](https://bugs.eclipse.org/bugs/show_bug.cgi?id=477475#c13) suggests the existence of an unmerged fix ... could we go with that?

**Comment by dwijnand** [comment]
I haven't gone that far. I assume adding worktree support is non-trivial.
