### ISSUE TITLE
scala/reflect/internal/Trees not found when run 'sbt console'

### ISSUE THREAD

**Issue by lawulu** [sbt/sbt#2346]
System: Mac OSX 10.10
Scala version 2.11.5 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_45).

```
➜  scala-lang  scala
Welcome to Scala version 2.11.5 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_45).
Type in expressions to have them evaluated.
Type :help for more information.

scala> import scala.reflect.internal.Trees
import scala.reflect.internal.Trees
```

When I run the sbt console firstly, it began to download the jars, but at last, it failed：

```
:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
download failed: org.scala-sbt#test-interface;1.0!test-interface.jar
Error during sbt execution: Error retrieving required libraries
  (see /Users/inza9hi/.sbt/boot/update.log for complete log)
Error: Could not retrieve sbt 0.13.7
```

Then I ran sbt console again.

```
➜  ~  sbt console
Getting org.scala-sbt sbt 0.13.7 ...
downloading https://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar ...
    [SUCCESSFUL ] org.scala-sbt#test-interface;1.0!test-interface.jar (3215ms)
:: retrieving :: org.scala-sbt#boot-app
    confs: [default]
    50 artifacts copied, 0 already retrieved (12580kB/51ms)
Getting Scala 2.10.4 (for sbt)...
:: retrieving :: org.scala-sbt#boot-scala
    confs: [default]
    2 artifacts copied, 0 already retrieved (21066kB/35ms)
java.lang.NoClassDefFoundError: scala/reflect/internal/Trees
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
```

I googled, and tried to remove the ~/.ivy2 folders，but still the same error.

```
➜  cache  sbt console
java.lang.NoClassDefFoundError: scala/reflect/internal/Trees
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at xsbt.boot.Pre$.xsbt$boot$Pre$$classMissing$1(Pre.scala:66)
    at xsbt.boot.Pre$$anonfun$getMissing$1.apply(Pre.scala:67)
    at scala.collection.TraversableLike$$anonfun$filter$1.apply(TraversableLike.scala:264)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at org.apache.ivy.core.RelativeUrlResolver.filter(RelativeUrlResolver.java:263)
    at scala.collection.AbstractTraversable.filter(Traversable.scala:105)
    at xsbt.boot.Pre$.getMissing$d83f809$3a8a6f87(Pre.scala:67)
    at xsbt.boot.Launch.checkLoader$2accd70c(Launch.scala:185)
    at xsbt.boot.Launch.xsbt$boot$Launch$$provider$1(Launch.scala:249)
    at xsbt.boot.Launch$$anonfun$xsbt$boot$Launch$$getScalaProvider0$2.apply(Launch.scala:252)
    at xsbt.boot.Launch$$anonfun$xsbt$boot$Launch$$getScalaProvider0$2.apply(Launch.scala:251)
    at scala.Option.flatMap(Option.scala:170)
    at xsbt.boot.Launch.xsbt$boot$Launch$$getScalaProvider0(Launch.scala:251)
    at xsbt.boot.Launch$$anon$3.call(Launch.scala:240)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:45)
    at xsbt.boot.Locks$.apply0(Locks.scala:31)
    at xsbt.boot.Locks$.apply(Locks.scala:28)
    at xsbt.boot.Launch.locked(Launch.scala:238)
    at xsbt.boot.Launch.getScalaProvider(Launch.scala:240)
    at xsbt.boot.Launch$$anonfun$1.apply(Launch.scala:141)
    at xsbt.boot.Cache.newEntry(Cache.scala:16)
    at xsbt.boot.Cache.apply(Cache.scala:11)
    at xsbt.boot.Launch.getScala(Launch.scala:144)
    at xsbt.boot.Launch.getScala(Launch.scala:143)
    at xsbt.boot.Launch.xsbt$boot$Launch$$getAppProvider0(Launch.scala:219)
    at xsbt.boot.Launch$$anon$2.call(Launch.scala:196)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
    at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
    at xsbt.boot.Using$.withResource(Using.scala:10)
    at xsbt.boot.Using$.apply(Using.scala:9)
    at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
    at xsbt.boot.Locks$.apply0(Locks.scala:31)
    at xsbt.boot.Locks$.apply(Locks.scala:28)
    at xsbt.boot.Launch.locked(Launch.scala:238)
    at xsbt.boot.Launch.app(Launch.scala:147)
    at xsbt.boot.Launch.app(Launch.scala:145)
    at xsbt.boot.Launch$.run(Launch.scala:102)
    at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
    at xsbt.boot.Launch$.launch(Launch.scala:117)
    at xsbt.boot.Launch$.apply(Launch.scala:18)
    at xsbt.boot.Boot$.runImpl(Boot.scala:41)
    at xsbt.boot.Boot$.main(Boot.scala:17)
    at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.ClassNotFoundException: scala.reflect.internal.Trees
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 69 more
Error during sbt execution: java.lang.NoClassDefFoundError: scala/reflect/internal/Trees
```

**Comment by eed3si9n** [comment]
Works for me using sbt 0.13.9.

```
$ mkdir project
$ echo "sbt.version=0.13.9" >> project/build.properties
$ echo "" >> build.sbt
$ sbt console
[info] Loading global plugins from xxxx
[info] Loading project definition from xxxx
[info] Set current project to xxxx (in build xxxx)
[info] Starting scala interpreter...
[info]
Welcome to Scala version 2.10.5 (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_79).
Type in expressions to have them evaluated.
Type :help for more information.

scala> exit
warning: there were 1 deprecation warning(s); re-run with -deprecation for details
```

Try wiping out `~/.sbt/boot/`.

**Comment by lawulu** [comment]
Thanks @eed3si9n ,as your suggestion, I solved it.
