### ISSUE TITLE
Credential without a realm

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#2366]
Currently a realm is required to define a credential: http://www.scala-sbt.org/0.13/docs/Publishing.html#Credentials

When Sonatype OSS changed their realm on 2016-01-12 from "Sonatype Nexus Repository Manager" to "Nexus Repository Manager", sbt users suddenly became unable to publish their artifacts: https://issues.sonatype.org/browse/OSSRH-13401

Ivy's credential seem to accept `null` or `""` as realm value as blank value: https://github.com/sbt/ivy/blob/3cf31483b03e0ba294c76f5391dc7570b7649090/src/java/org/apache/ivy/util/Credentials.java#L55-L61, if this works, we should probably support it to provide a workaround.
Temporarily the build user might be able to just pass in `""` too. As of 2015-01-13 the issue was resolved by Sonatype by reverting back to the old realm name.

**Comment by hertg** [comment]
I am currently experiencing this issue.

I've set up a Maven Repository on the Google Cloud Platform with the following project:
https://github.com/renaudcerrato/appengine-maven-repository

The project is using Basic Auth **without specifying any realm**, therefore returning `WWW-Authenticate: Basic` instead of `WWW-Authenticate: Basic realm="some-realm-name"`.

I am able to publish and checkout my libraries using gradle, **but not with sbt**.
Already tried setting the realm to empty string `""` and `null` without any success.

ie.
```sbt
credentials += Credentials(
  "",
  "my-repo-url",
  "my-user",
  "my-password"
)
resolvers += "mavenrepo" at "https://maven.company.com"
```
```sbt
credentials += Credentials(
  null,
  "my-repo-url",
  "my-user",
  "my-password"
)
resolvers += "mavenrepo" at "https://maven.company.com"
```

The equivalent configuration in gradle works perfectly fine.
```gradle
repositories {
maven {
    credentials {
            username 'my-user'
            password 'my-password'
        }
        url "https://maven.company.com"
    }
}
```

My sbt version is `1.2.8`.

**Comment by arashi01** [comment]
Also been hit with this issue. Unable to use Azure DevOps included maven repositories for publishing since the realm returned by Azure is not stable (changes depending on server servicing the request).

@eed3si9n Would it be fair to reclassify this as a bug since underlying ivy seems to support this (and Maven and Gradle definitely do)?

**Comment by eed3si9n** [comment]
@arashi01 Sure.

**Comment by pangiole** [comment]
I'm also experiencing troubles in trying to publish to Azure DevOps and had to fallback to Maven Deploy plugin,  what a shame.

It seems that major cloud vendors don't challenge the HTTP client with a stable realm. Maybe, SBT resolvers/publishers should no require it (somehow)

**Comment by eed3si9n** [comment]
## null

Here's what happens if we use `null`:


```scala
credentials += Credentials(null, "oss.sonatype.org", "test", "test")
```

On sbt 1.3.7, the build doesn't load failing to convert credential to Coursier:

<details>
<summary>

```scala
[error] java.lang.NullPointerException
```

</summary>

```scala
$ sbt
[info] Loading settings for project global-plugins from idea.sbt,vimquit.sbt,plugins.sbt,pgp.sbt ...
[info] Loading global plugins from /Users/eed3si9n/.sbt/1.0/plugins
[info] Loading settings for project gigahorse-build from pf.sbt,plugin.sbt,pgp.sbt ...
[info] Loading project definition from /Users/eed3si9n/work/Gigahorse/project
[error] java.lang.NullPointerException
[error] 	at scala.collection.immutable.StringOps$.length$extension(StringOps.scala:51)
[error] 	at scala.collection.immutable.StringOps.length(StringOps.scala:51)
[error] 	at scala.collection.IndexedSeqOptimized.isEmpty(IndexedSeqOptimized.scala:30)
[error] 	at scala.collection.IndexedSeqOptimized.isEmpty$(IndexedSeqOptimized.scala:30)
[error] 	at scala.collection.immutable.StringOps.isEmpty(StringOps.scala:33)
[error] 	at scala.collection.TraversableOnce.nonEmpty(TraversableOnce.scala:114)
[error] 	at scala.collection.TraversableOnce.nonEmpty$(TraversableOnce.scala:114)
[error] 	at scala.collection.immutable.StringOps.nonEmpty(StringOps.scala:33)
[error] 	at sbt.coursierint.CoursierInputsTasks$.$anonfun$credentialsTask$5(CoursierInputsTasks.scala:234)
[error] 	at sbt.coursierint.CoursierInputsTasks$.$anonfun$credentialsTask$5$adapted(CoursierInputsTasks.scala:234)
[error] 	at scala.Option.filter(Option.scala:289)
[error] 	at sbt.coursierint.CoursierInputsTasks$.$anonfun$credentialsTask$4(CoursierInputsTasks.scala:234)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:941)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error] 	at sbt.coursierint.CoursierInputsTasks$.$anonfun$credentialsTask$1(CoursierInputsTasks.scala:229)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] java.lang.NullPointerException
[error] 	at scala.collection.immutable.StringOps$.length$extension(StringOps.scala:51)
[error] 	at scala.collection.immutable.StringOps.length(StringOps.scala:51)
[error] 	at scala.collection.IndexedSeqOptimized.isEmpty(IndexedSeqOptimized.scala:30)
[error] 	at scala.collection.IndexedSeqOptimized.isEmpty$(IndexedSeqOptimized.scala:30)
[error] 	at scala.collection.immutable.StringOps.isEmpty(StringOps.scala:33)
[error] 	at scala.collection.TraversableOnce.nonEmpty(TraversableOnce.scala:114)
[error] 	at scala.collection.TraversableOnce.nonEmpty$(TraversableOnce.scala:114)
[error] 	at scala.collection.immutable.StringOps.nonEmpty(StringOps.scala:33)
[error] 	at sbt.coursierint.CoursierInputsTasks$.$anonfun$credentialsTask$5(CoursierInputsTasks.scala:234)
[error] 	at sbt.coursierint.CoursierInputsTasks$.$anonfun$credentialsTask$5$adapted(CoursierInputsTasks.scala:234)
[error] 	at scala.Option.filter(Option.scala:289)
[error] 	at sbt.coursierint.CoursierInputsTasks$.$anonfun$credentialsTask$4(CoursierInputsTasks.scala:234)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:941)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error] 	at sbt.coursierint.CoursierInputsTasks$.$anonfun$credentialsTask$1(CoursierInputsTasks.scala:229)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (csrConfiguration) java.lang.NullPointerException
```
</details>

## blank string

Let's try blank string:

```scala
credentials += Credentials("", "oss.sonatype.org", "test", "test")
```

This did load the build, but `publish` didn't find the credential:

<details>

<summary>

```scala
[error] Unable to find credentials for [Sonatype Nexus Repository Manager @ oss.sonatype.org].
[error] java.io.IOException: Access to URL https://oss.sonatype.org/service/local/staging/deploy/maven2/com/eed3si9n/gigahorse-core_2.12/0.5.0/gigahorse-core_2.12-0.5.0.pom was refused by the server: Unauthorized
[error] 	at org.apache.ivy.util.url.AbstractURLHandler.validatePutStatusCode(AbstractURLHandler.java:79)
[error] 	at org.apache.ivy.util.url.BasicURLHandler.upload(BasicURLHandler.java:278)
```

</summary>

```scala
sbt:gigahorse> last core / publish
[error] Unable to find credentials for [Sonatype Nexus Repository Manager @ oss.sonatype.org].
[debug] CLIENT ERROR: Unauthorized url=https://oss.sonatype.org/service/local/staging/deploy/maven2/com/eed3si9n/gigahorse-core_2.12/0.5.0/gigahorse-core_2.12-0.5.0.pom
[error] Unable to find credentials for [Sonatype Nexus Repository Manager @ oss.sonatype.org].
[error] java.io.IOException: Access to URL https://oss.sonatype.org/service/local/staging/deploy/maven2/com/eed3si9n/gigahorse-core_2.12/0.5.0/gigahorse-core_2.12-0.5.0.pom was refused by the server: Unauthorized
[error] 	at org.apache.ivy.util.url.AbstractURLHandler.validatePutStatusCode(AbstractURLHandler.java:79)
[error] 	at org.apache.ivy.util.url.BasicURLHandler.upload(BasicURLHandler.java:278)
[error] 	at org.apache.ivy.util.url.URLHandlerDispatcher.upload(URLHandlerDispatcher.java:82)
[error] 	at org.apache.ivy.util.FileUtil.copy(FileUtil.java:150)
[error] 	at org.apache.ivy.plugins.repository.url.URLRepository.put(URLRepository.java:84)
[error] 	at sbt.internal.librarymanagement.ConvertResolver$LocalIfFileRepo.put(ConvertResolver.scala:368)
[error] 	at org.apache.ivy.plugins.repository.AbstractRepository.put(AbstractRepository.java:130)
[error] 	at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put(ConvertResolver.scala:118)
[error] 	at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put$(ConvertResolver.scala:105)
[error] 	at sbt.internal.librarymanagement.ConvertResolver$$anonfun$defaultConvert$lzycompute$1$PluginCapableResolver$1.put(ConvertResolver.scala:165)
[error] 	at org.apache.ivy.plugins.resolver.RepositoryResolver.publish(RepositoryResolver.java:216)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5(IvyActions.scala:501)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5$adapted(IvyActions.scala:500)
[error] 	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:877)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:941)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:876)
[error] 	at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:500)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$3(IvyActions.scala:142)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at sbt.internal.librarymanagement.IvyActions$.withChecksums(IvyActions.scala:156)
[error] 	at sbt.internal.librarymanagement.IvyActions$.withChecksums(IvyActions.scala:149)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$1(IvyActions.scala:142)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$1$adapted(IvyActions.scala:132)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:251)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:215)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:77)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$1.call(Ivy.scala:87)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:87)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:209)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:206)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:250)
[error] 	at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:132)
[error] 	at sbt.Classpaths$.$anonfun$publishTask$4(Defaults.scala:2811)
[error] 	at sbt.Classpaths$.$anonfun$publishTask$4$adapted(Defaults.scala:2811)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (core / publish) java.io.IOException: Access to URL https://oss.sonatype.org/service/local/staging/deploy/maven2/com/eed3si9n/gigahorse-core_2.12/0.5.0/gigahorse-core_2.12-0.5.0.pom was refused by the server: Unauthorized
```

</details>

Likely what we'd need to do is change https://github.com/sbt/ivy/blob/88d6a93d15f9b029958c1c289a8859e8dfe31a19/src/java/org/apache/ivy/util/url/CredentialsStore.java, such that it `getCredentials` first checks using the `key`, but if the credential is NOT found, fallback to `key2` that uses `""` for realm.

**Comment by rohit21agrawal** [comment]
@eed3si9n 
is there a workaround to publish to Azure DevOps Maven feed until then?

**Comment by eed3si9n** [comment]
You can try https://github.com/arktekk/sbt-aether-deploy.
