### ISSUE TITLE
Scala reflection doesn't work with sbt run

### ISSUE THREAD

**Issue by gkossakowski** [sbt/sbt#245]
Scala reflection that is being cooked in Scala's trunk doesn't work when code is executed with `sbt run`.

Example project that shows the problem can be found here: https://github.com/gkossakowski/scala-proxy

I don't know if it's a bug in Scala compiler or Sbt classloader issue. It's bit hard to debug it for someone not understanding sbt's internals. Figuring it out if it's compiler problem or Sbt problem would be already a big help.

Obviously, the code included in example project work fine if run from command line using scala command.

Here's the stacktrace showing the problem:

```
[error] (run-main) java.lang.AssertionError: assertion failed: <none>/interface test.Outer$Foo/<none>/Foo
java.lang.AssertionError: assertion failed: <none>/interface test.Outer$Foo/<none>/Foo
    at scala.reflect.runtime.JavaToScala$$anonfun$classToScala$1.apply(JavaToScala.scala:361)
    at scala.reflect.runtime.JavaToScala$$anonfun$classToScala$1.apply(JavaToScala.scala:359)
    at scala.reflect.runtime.ConversionUtil$TwoWayCache.toScala(ConversionUtil.scala:30)
    at scala.reflect.runtime.JavaToScala$class.classToScala(JavaToScala.scala:358)
    at scala.reflect.runtime.Universe.classToScala(Universe.scala:11)
    at scala.reflect.proxy.ScalaProxy$.apply(ScalaProxy.scala:19)
```

**Comment by gkossakowski** [comment]
Turned out to be a problem in Scala compiler related to classloader. Already fixed: https://groups.google.com/d/msg/simple-build-tool/YvuZbsIgZjI/UKA4nJ0i_YsJ
