### ISSUE TITLE
[0.13.11] broke android-sdk-plugin

### ISSUE THREAD

**Issue by liskin** [sbt/sbt#2476]
```
[tomi@notes sbt-0.13.11-android-sdk-plugin]$ cat >build.sbt
import android.Keys._
android.Plugin.androidBuild
[tomi@notes sbt-0.13.11-android-sdk-plugin]$ mkdir project
[tomi@notes sbt-0.13.11-android-sdk-plugin]$ cat >project/build.properties
sbt.version=0.13.11
[tomi@notes sbt-0.13.11-android-sdk-plugin]$ cat >project/plugins.sbt
addSbtPlugin("com.hanhuy.sbt" % "android-sdk-plugin" % "1.5.17")
[tomi@notes sbt-0.13.11-android-sdk-plugin]$ sbt
[info] Loading global plugins from /home/tomi/.sbt/0.13/plugins
[info] Loading project definition from /tmp/sbt-0.13.11-android-sdk-plugin/project
[info] Updating {file:/tmp/sbt-0.13.11-android-sdk-plugin/project/}sbt-0-13-11-android-sdk-plugin-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
References to undefined settings: 

  android:packageBin::artifactPath from android:exportedProductsNoTracking (/tmp/sbt-0.13.11-android-sdk-plugin/build.sbt:2)

  android:packageBin::artifactPath from android:exportedProductsIfMissing (/tmp/sbt-0.13.11-android-sdk-plugin/build.sbt:2)

        at sbt.Init$class.Uninitialized(Settings.scala:270)
        at sbt.Def$.Uninitialized(Def.scala:10)
        at sbt.Init$class.delegate(Settings.scala:191)
        at sbt.Def$.delegate(Def.scala:10)
        at sbt.Init$class.compiled(Settings.scala:138)
        at sbt.Def$.compiled(Def.scala:10)
        at sbt.Init$class.make(Settings.scala:144)
        at sbt.Def$.make(Def.scala:10)
        at sbt.Load$.apply(Load.scala:145)
        at sbt.Load$.defaultLoad(Load.scala:36)
        at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:492)
        at sbt.BuiltinCommands$.doLoadProject(Main.scala:492)
        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:484)
        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:484)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
        at sbt.Command$.process(Command.scala:93)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
        at sbt.State$$anon$1.process(State.scala:184)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.MainLoop$.next(MainLoop.scala:96)
        at sbt.MainLoop$.run(MainLoop.scala:89)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
        at sbt.Using.apply(Using.scala:24)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
        at sbt.MainLoop$.runLogged(MainLoop.scala:22)
        at sbt.StandardMain$.runManaged(Main.scala:54)
        at sbt.xMain.run(Main.scala:29)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
        at xsbt.boot.Launch$.run(Launch.scala:109)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
        at xsbt.boot.Launch$.launch(Launch.scala:117)
        at xsbt.boot.Launch$.apply(Launch.scala:18)
        at xsbt.boot.Boot$.runImpl(Boot.scala:41)
        at xsbt.boot.Boot$.main(Boot.scala:17)
        at xsbt.boot.Boot.main(Boot.scala)
[error] References to undefined settings: 
[error] 
[error]   android:packageBin::artifactPath from android:exportedProductsNoTracking (/tmp/sbt-0.13.11-android-sdk-plugin/build.sbt:2)
[error] 
[error]   android:packageBin::artifactPath from android:exportedProductsIfMissing (/tmp/sbt-0.13.11-android-sdk-plugin/build.sbt:2)
[error]  
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
```

**Comment by dwijnand** [comment]
sorry about that.. I see sbt-android worked around the semantic change.
