### ISSUE TITLE
SBT doesn't start in fakeroot

### ISSUE THREAD

**Issue by radekm** [sbt/sbt#2493]
## steps
1. Download SBT launcher `sbt` from https://github.com/paulp/sbt-extras/blob/master/sbt
2. Execute launcher `fakeroot ./sbt`.

I'm using Ubuntu 15.10.
## problem

SBT throws exception

```
java.io.IOException: Permission denied
    at java.io.UnixFileSystem.createFileExclusively(Native Method)
    at java.io.File.createNewFile(File.java:1012)
    at xsbt.boot.Locks$.apply0(Locks.scala:34)
    at xsbt.boot.Locks$.apply(Locks.scala:28)
    at xsbt.boot.Launch.locked(Launch.scala:238)
    at xsbt.boot.Launch.app(Launch.scala:147)
    at xsbt.boot.Launch.app(Launch.scala:145)
    at xsbt.boot.Launch$.run(Launch.scala:102)
    at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
    at xsbt.boot.Launch$.launch(Launch.scala:117)
    at xsbt.boot.Launch$.apply(Launch.scala:18)
    at xsbt.boot.Boot$.runImpl(Boot.scala:41)
    at xsbt.boot.Boot$.main(Boot.scala:17)
    at xsbt.boot.Boot.main(Boot.scala)
Error during sbt execution: java.io.IOException: Permission denied
```
## expectation

SBT should work normally.
## notes

I use SBT when building Debian package. In the file `rules` I call SBT in `override_dh_auto_clean` rule. This rule is executed by `dpkg-buildpackage` by calling `fakeroot debian/rules clean`. Note that using SBT in `build` rule works fine.

**Comment by copumpkin** [comment]
Vaguely related to #2498

**Comment by radekm** [comment]
It helps to redefine paths to writable dirs. Here is an example of `debian/rules`:

```makefile
#!/usr/bin/make -f

export DH_VERBOSE=1
export DH_ALWAYS_EXCLUDE=.git

SBT_OPTS=-Dsbt.global.base=/tmp/scala-build/sbt-global-base\
    -Dsbt.ivy.home=/tmp/scala-build/sbt-ivy-home\
    -Dsbt.boot.directory=/tmp/scala-build/sbt-boot-directory

%:
	dh $@

build:
	./sbt ${SBT_OPTS} checkPackage generateExplodedPackage

override_dh_clean:
	./sbt ${SBT_OPTS} cleanExplodedPackage
	dh_clean
	$(RM) -r target
```

It works even if `clean` action is executed in `fakeroot`.

**Comment by radekm** [comment]
Note that above mentioned workaround won't work very well when different users are building on the same machine. Perhaps it would be better to generate random folder in `tmp` and store it's name in `target`.
