### ISSUE TITLE
0.13.11 On OSX; fork := true does not launch if machine is offline/disconnected (JDK 8)

### ISSUE THREAD

**Issue by mustafamotiwala** [sbt/sbt#2520]
## steps
1. In `build.sbt` set `fork := true`
2. Disconnect your macbook/OSX from the network (Turn Wi-Fi Off)
3. Type `run` or `test` on your sbt prompt.
## problem

The application/tests are not launched. Instead sbt seems to freeze for a minute or two and then reports the following output:

```
> test
[error] Uncaught exception when running tests: java.net.ConnectException: Operation timed out
[trace] Stack trace suppressed: run last test:test for the full output.                     
Exception in thread "Thread-1" java.io.EOFException                                            
        at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2601)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1319)                  
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)                    
        at sbt.React.react(ForkTests.scala:114)                                                
        at sbt.ForkTests$$anonfun$mainTestTask$1$Acceptor$2$.run(ForkTests.scala:74)           
        at java.lang.Thread.run(Thread.java:745
```

Interestingly enough, you are never returned to the `sbt` prompt again and have to kill `sbt`. After relaunching sbt and doing `> last test:test` One sees the following output 

```
[debug] javaOptions: List()                                                                  
[debug] Forking tests - parallelism = false                                                  
[debug] Create a single-thread test executor                                                 
[debug] Runner for sbt.FrameworkWrapper produced 0 initial tasks for 0 tests.                
[debug] Runner for org.specs2.runner.Specs2Framework produced 0 initial tasks for 0 tests.   
[error] Uncaught exception when running tests: java.net.ConnectException: Operation timed out
```
## expectation

The tests/application should be able to launch even if the machine is in offline mode (perhaps sbt can connect to the Forked VM via `localhost`?
## notes

What leads me to believe this to be an issue with `fork := true` and not something with `specs2` or my application is that the same tests run when I remove the `fork`; however I need the `fork` as I am running tests with `~;test` - and if I don't fork, the VM eventually dies due to `OutOfMemoryError`.

**Comment by eed3si9n** [comment]
I am closing this due to inactivity, but if this is still relevant let us know with more details (reproduction steps etc).
