### ISSUE TITLE
Ability to programmatically define projects: Seq[Project]

### ISSUE THREAD

**Issue by fommil** [sbt/sbt#2532]
With the new move to `.sbt` files, we will lack a key feature which is the ability to transform `Seq[Project]`.

A typical usecase for this is when the build structure is generated (perhaps translated from another tool) and the owner of the sbt build scripts can only apply transformations to the `Project` object rather than edit the `build.sbt` directly.

I feel this is a blocker for 1.0.

**Comment by dwijnand** [comment]
@Duhemm has explored trying to port this in #2183.

I've needed access to `.projects` to solve the use case details in http://stackoverflow.com/a/31061013/463761.

Also I think this might be a blocker for https://github.com/sbt/sbt-pom-reader.

**Comment by fommil** [comment]
That's interesting. It is explicitly read-only, but this ticket is to allow the "mutation" of `Seq[Project]`.

Somewhat related is the ability to specify / select the `rootProject` from the transformed `Seq[Project]`.

**Comment by dwijnand** [comment]
Yes, that pull requested morphed into read-only.

But I'm agreeing with you, there are use-cases that require programmatically defining projects, for which, to my knowledge, there's no facility currently in 1.0.

**Comment by fommil** [comment]
@eed3si9n can this please be considered for 1.0? This one really is a blocker for me at work in moving to 1.0.

**Comment by SethTisue** [comment]
for MiMa to convert to `build.sbt` style is blocked by this; the MiMa build generates test projects on the fly (one per subdirectory of `reporter/functional-tests/src/test`) and then adds them to the build via `override lazy val projects = ...`

**Comment by fommil** [comment]
Nice! I'll try this out sometime

**Comment by dwijnand** [comment]
@fommil It'll be part of 0.13.13 (and available in the 0.13.13-RC2 pre-release)

**Comment by SethTisue** [comment]
@dwijnand to help you test the fix, could I interest you in submitting a PR upgrading MiMa to use 0.13.13-RCx and addressing https://github.com/typesafehub/migration-manager/blob/7c956c57ae137dbfc729db54f5d35d33b9436347/project/Build.scala#L85-L87?

“to help you”, my god, how transparent. see, it's all about you

**Comment by dwijnand** [comment]
Sure.

**Comment by Atry** [comment]
Is there a corresponding `DslEntry` for `extraProjects` method?

**Comment by Atry** [comment]
`aggregate` and `dependsOn` is similar, however they always error for inline projects:

``` scala
dependsOn(Project("aaa", file("yyy")), Project("xxx2", file("yyy2")))
```

```
java.lang.RuntimeException: No project 'aaa' in 'file:/private/tmp/xxx/'.
Valid project IDs: xxx
	at scala.sys.package$.error(package.scala:27)
	at sbt.Load$$anonfun$checkAll$2$$anonfun$apply$16.apply(Load.scala:401)
	at sbt.Load$$anonfun$checkAll$2$$anonfun$apply$16.apply(Load.scala:396)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at sbt.Load$$anonfun$checkAll$2.apply(Load.scala:396)
	at sbt.Load$$anonfun$checkAll$2.apply(Load.scala:396)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:109)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:771)
	at sbt.Load$.checkAll(Load.scala:396)
	at sbt.Load$.loadURI(Load.scala:321)
	at sbt.Load$.load(Load.scala:316)
	at sbt.Load$.load(Load.scala:305)
	at sbt.Load$$anonfun$4.apply(Load.scala:146)
	at sbt.Load$$anonfun$4.apply(Load.scala:146)
	at sbt.Load$.timed(Load.scala:1025)
	at sbt.Load$.apply(Load.scala:146)
	at sbt.Load$.defaultLoad(Load.scala:39)
	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:496)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:496)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:488)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:488)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$.process(Command.scala:93)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:96)
	at sbt.MainLoop$.run(MainLoop.scala:89)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
	at sbt.MainLoop$.runLogged(MainLoop.scala:22)
	at sbt.StandardMain$.runManaged(Main.scala:57)
	at sbt.xMain.run(Main.scala:29)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
```
