### ISSUE TITLE
“module not found: org.scala-sbt#sbt;0.13.9” after installing from Debian repo

### ISSUE THREAD

**Issue by progval** [sbt/sbt#2536]
(See the guidelines for contributing, linked above)
## steps

Run as root:

```
echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823
apt-get update
apt-get install sbt
sbt
```

(instructions from [this document](http://www.scala-sbt.org/0.13/docs/Installing-sbt-on-Linux.html))
## problem

This error:

```
root@bessie:~/powerapi# sbt
Getting org.scala-sbt sbt 0.13.9 ...

:: problems summary ::
:::: WARNINGS
        module not found: org.scala-sbt#sbt;0.13.9

    ==== local: tried

      /root/.ivy2/local/org.scala-sbt/sbt/0.13.9/ivys/ivy.xml

      -- artifact org.scala-sbt#sbt;0.13.9!sbt.jar:

      /root/.ivy2/local/org.scala-sbt/sbt/0.13.9/jars/sbt.jar

    ==== Maven Central: tried

      https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.9/sbt-0.13.9.pom

      -- artifact org.scala-sbt#sbt;0.13.9!sbt.jar:

      https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.9/sbt-0.13.9.jar

    ==== typesafe-ivy-releases: tried

      https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.9/ivys/ivy.xml

    ==== sbt-ivy-snapshots: tried

      https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/0.13.9/ivys/ivy.xml

        ::::::::::::::::::::::::::::::::::::::::::::::

        ::          UNRESOLVED DEPENDENCIES         ::

        ::::::::::::::::::::::::::::::::::::::::::::::

        :: org.scala-sbt#sbt;0.13.9: not found

        ::::::::::::::::::::::::::::::::::::::::::::::


:::: ERRORS
    Server access Error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target url=https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.9/sbt-0.13.9.pom

    Server access Error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target url=https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.9/sbt-0.13.9.jar

    Server access Error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.9/ivys/ivy.xml

    Server access Error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target url=https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/0.13.9/ivys/ivy.xml


:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
unresolved dependency: org.scala-sbt#sbt;0.13.9: not found
Error during sbt execution: Error retrieving required libraries
  (see /root/.sbt/boot/update.log for complete log)
Error: Could not retrieve sbt 0.13.9
```

Additionally:

```
root@bessie:~/powerapi# cat /root/.sbt/boot/update.log
setting 'ivy.default.settings.dir' to 'jar:file:/usr/share/sbt-launcher-packaging/bin/sbt-launch.jar!/org/apache/ivy/core/settings'
setting 'ivy.basedir' to '/root/powerapi/.'
setting 'ivy.default.conf.dir' to 'jar:file:/usr/share/sbt-launcher-packaging/bin/sbt-launch.jar!/org/apache/ivy/core/settings'
impossible to define new type: class not found: org.apache.ivy.plugins.resolver.SshResolver in [] nor Ivy classloader
impossible to define new type: class not found: org.apache.ivy.plugins.resolver.VsftpResolver in [] nor Ivy classloader
impossible to define new type: class not found: org.apache.ivy.plugins.version.PatternVersionMatcher in [] nor Ivy classloader
impossible to define new type: class not found: org.apache.ivy.plugins.trigger.LogTrigger in [] nor Ivy classloader
impossible to define new type: class not found: org.apache.ivy.ant.AntBuildTrigger in [] nor Ivy classloader
impossible to define new type: class not found: org.apache.ivy.plugins.resolver.IvyRepResolver in [] nor Ivy classloader
impossible to define new type: class not found: org.apache.ivy.plugins.signer.bouncycastle.OpenPGPSignatureGenerator in [] nor Ivy classloader
impossible to define new type: class not found: org.apache.ivy.plugins.conflict.RegexpConflictManager in [] nor Ivy classloader
impossible to define new type: class not found: org.apache.ivy.plugins.resolver.SFTPResolver in [] nor Ivy classloader
impossible to define new type: class not found: org.apache.ivy.osgi.updatesite.UpdateSiteResolver in [] nor Ivy classloader
impossible to define new type: class not found: org.apache.ivy.ant.AntCallTrigger in [] nor Ivy classloader
impossible to define new type: class not found: org.apache.ivy.plugins.resolver.MirroredURLResolver in [] nor Ivy classloader
impossible to define new type: class not found: org.apache.ivy.plugins.resolver.packager.PackagerResolver in [] nor Ivy classloader
impossible to define new type: class not found: org.apache.ivy.plugins.resolver.DualResolver in [] nor Ivy classloader
impossible to define new type: class not found: org.apache.ivy.plugins.resolver.VfsResolver in [] nor Ivy classloader
impossible to define new type: class not found: org.apache.ivy.plugins.resolver.JarResolver in [] nor Ivy classloader
impossible to define new type: class not found: org.apache.ivy.osgi.obr.OBRResolver in [] nor Ivy classloader
impossible to define glob matcher: org.apache.ivy.plugins.matcher.GlobPatternMatcher was not found.
setting 'jline.esc.timeout' to '0'
setting 'java.runtime.name' to 'OpenJDK Runtime Environment'
setting 'sun.boot.library.path' to '/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64'
setting 'java.vm.version' to '25.72-b15'
setting 'user.country.format' to 'FR'
setting 'java.vm.vendor' to 'Oracle Corporation'
setting 'java.vendor.url' to 'http://java.oracle.com/'
setting 'path.separator' to ':'
setting 'java.vm.name' to 'OpenJDK 64-Bit Server VM'
setting 'file.encoding.pkg' to 'sun.io'
setting 'user.country' to 'US'
setting 'sun.java.launcher' to 'SUN_STANDARD'
setting 'sun.os.patch.level' to 'unknown'
setting 'java.vm.specification.name' to 'Java Virtual Machine Specification'
setting 'user.dir' to '/root/powerapi'
setting 'java.runtime.version' to '1.8.0_72-internal-b15'
setting 'java.awt.graphicsenv' to 'sun.awt.X11GraphicsEnvironment'
setting 'java.endorsed.dirs' to '/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/endorsed'
setting 'os.arch' to 'amd64'
setting 'java.io.tmpdir' to '/tmp'
setting 'line.separator' to '
'
setting 'java.vm.specification.vendor' to 'Oracle Corporation'
setting 'os.name' to 'Linux'
setting 'sun.jnu.encoding' to 'UTF-8'
setting 'java.library.path' to '/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib'
setting 'java.specification.name' to 'Java Platform API Specification'
setting 'java.class.version' to '52.0'
setting 'sun.management.compiler' to 'HotSpot 64-Bit Tiered Compilers'
setting 'os.version' to '3.16.0-4-amd64'
setting 'user.home' to '/root'
setting 'user.timezone' to ''
setting 'java.awt.printerjob' to 'sun.print.PSPrinterJob'
setting 'file.encoding' to 'UTF-8'
setting 'java.specification.version' to '1.8'
setting 'java.class.path' to '/usr/share/sbt-launcher-packaging/bin/sbt-launch.jar'
setting 'user.name' to 'root'
setting 'jline.shutdownhook' to 'false'
setting 'java.vm.specification.version' to '1.8'
setting 'sun.java.command' to '/usr/share/sbt-launcher-packaging/bin/sbt-launch.jar'
setting 'java.home' to '/usr/lib/jvm/java-8-openjdk-amd64/jre'
setting 'sun.arch.data.model' to '64'
setting 'user.language' to 'en'
setting 'java.specification.vendor' to 'Oracle Corporation'
setting 'user.language.format' to 'fr'
setting 'awt.toolkit' to 'sun.awt.X11.XToolkit'
setting 'java.vm.info' to 'mixed mode'
setting 'java.version' to '1.8.0_72-internal'
setting 'java.ext.dirs' to '/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext:/usr/java/packages/lib/ext'
setting 'sun.boot.class.path' to '/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jfr.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/classes'
setting 'java.vendor' to 'Oracle Corporation'
setting 'file.separator' to '/'
setting 'java.vendor.url.bug' to 'http://bugreport.sun.com/bugreport/'
setting 'sun.io.unicode.encoding' to 'UnicodeLittle'
setting 'sun.cpu.endian' to 'little'
setting 'sun.cpu.isalist' to ''
setting 'ivy.default.ivy.user.dir' to '/root/.ivy2'
setting 'ivy.home' to '/root/.ivy2'
setting 'ivy.cache.dir' to '/root/.ivy2/cache'
no default cache defined: set to /root/.ivy2/cache
setting 'ivy.checksums' to 'sha1,md5'
setting 'ivy.basedir' to '/root/.sbt/boot'
setting 'basedir' to '/root/.sbt/boot'
:: resolving dependencies :: org.scala-sbt#boot-app;1.0
    confs: [default]
    validate = true
    refresh = false
resolving dependencies for configuration 'default'
== resolving dependencies for org.scala-sbt#boot-app;1.0 [default]
loadData of org.scala-sbt#boot-app;1.0 of rootConf=default
== resolving dependencies org.scala-sbt#boot-app;1.0->org.scala-sbt#sbt;0.13.9 [default->default(compile)]
loadData of org.scala-sbt#sbt;0.13.9 of rootConf=default
    using redefined-public to resolve org.scala-sbt#sbt;0.13.9
redefined-public: Checking cache for: dependency: org.scala-sbt#sbt;0.13.9 {default=[default(compile)]}
redefined-public: no namespace defined: using system
    no ivy file in cache for org.scala-sbt#sbt;0.13.9: tried /root/.ivy2/cache/org.scala-sbt/sbt/ivy-0.13.9.xml
redefined-public: no latest strategy defined: using default
local: no namespace defined: using system
    no ivy file in cache for org.scala-sbt#sbt;0.13.9: tried /root/.ivy2/cache/org.scala-sbt/sbt/ivy-0.13.9.xml
     trying /root/.ivy2/local/org.scala-sbt/sbt/0.13.9/ivys/ivy.xml
        tried /root/.ivy2/local/org.scala-sbt/sbt/0.13.9/ivys/ivy.xml
    local: resource not reachable for org.scala-sbt#sbt;0.13.9: res=/root/.ivy2/local/org.scala-sbt/sbt/0.13.9/ivys/ivy.xml
     trying /root/.ivy2/local/org.scala-sbt/sbt/0.13.9/jars/sbt.jar
        tried /root/.ivy2/local/org.scala-sbt/sbt/0.13.9/jars/sbt.jar
    local: resource not reachable for org.scala-sbt#sbt;0.13.9: res=/root/.ivy2/local/org.scala-sbt/sbt/0.13.9/jars/sbt.jar
    local: no ivy file nor artifact found for org.scala-sbt#sbt;0.13.9
Maven Central: no namespace defined: using system
    no ivy file in cache for org.scala-sbt#sbt;0.13.9: tried /root/.ivy2/cache/org.scala-sbt/sbt/ivy-0.13.9.xml
     trying https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.9/sbt-0.13.9.pom
        tried https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.9/sbt-0.13.9.pom
ERROR: Server access Error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target url=https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.9/sbt-0.13.9.pom
    Maven Central: resource not reachable for org/scala-sbt#sbt;0.13.9: res=https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.9/sbt-0.13.9.pom
     trying https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.9/sbt-0.13.9.jar
        tried https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.9/sbt-0.13.9.jar
ERROR: Server access Error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target url=https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.9/sbt-0.13.9.jar
    Maven Central: resource not reachable for org/scala-sbt#sbt;0.13.9: res=https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.9/sbt-0.13.9.jar
    Maven Central: no ivy file nor artifact found for org.scala-sbt#sbt;0.13.9
typesafe-ivy-releases: no namespace defined: using system
    no ivy file in cache for org.scala-sbt#sbt;0.13.9: tried /root/.ivy2/cache/org.scala-sbt/sbt/ivy-0.13.9.xml
     trying https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.9/ivys/ivy.xml
        tried https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.9/ivys/ivy.xml
ERROR: Server access Error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.9/ivys/ivy.xml
    typesafe-ivy-releases: resource not reachable for org.scala-sbt#sbt;0.13.9: res=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.9/ivys/ivy.xml
    typesafe-ivy-releases: no ivy file found for org.scala-sbt#sbt;0.13.9
sbt-ivy-snapshots: no namespace defined: using system
    no ivy file in cache for org.scala-sbt#sbt;0.13.9: tried /root/.ivy2/cache/org.scala-sbt/sbt/ivy-0.13.9.xml
     trying https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/0.13.9/ivys/ivy.xml
        tried https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/0.13.9/ivys/ivy.xml
ERROR: Server access Error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target url=https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/0.13.9/ivys/ivy.xml
    sbt-ivy-snapshots: resource not reachable for org.scala-sbt#sbt;0.13.9: res=https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/0.13.9/ivys/ivy.xml
    sbt-ivy-snapshots: no ivy file found for org.scala-sbt#sbt;0.13.9
WARN:   module not found: org.scala-sbt#sbt;0.13.9
WARN: ==== local: tried
WARN:   /root/.ivy2/local/org.scala-sbt/sbt/0.13.9/ivys/ivy.xml
WARN:   -- artifact org.scala-sbt#sbt;0.13.9!sbt.jar:
WARN:   /root/.ivy2/local/org.scala-sbt/sbt/0.13.9/jars/sbt.jar
WARN: ==== Maven Central: tried
WARN:   https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.9/sbt-0.13.9.pom
WARN:   -- artifact org.scala-sbt#sbt;0.13.9!sbt.jar:
WARN:   https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.9/sbt-0.13.9.jar
WARN: ==== typesafe-ivy-releases: tried
WARN:   https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.9/ivys/ivy.xml
WARN: ==== sbt-ivy-snapshots: tried
WARN:   https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/0.13.9/ivys/ivy.xml
Nbr of module to sort : 0
    resolved ivy file produced in cache
:: downloading artifacts ::
:: resolution report :: resolve 1297ms :: artifacts dl 0ms
WARN:   ::::::::::::::::::::::::::::::::::::::::::::::
WARN:   ::          UNRESOLVED DEPENDENCIES         ::
WARN:   ::::::::::::::::::::::::::::::::::::::::::::::
WARN:   :: org.scala-sbt#sbt;0.13.9: not found
WARN:   ::::::::::::::::::::::::::::::::::::::::::::::

Nbr of module to sort : 0
    report for org.scala-sbt#boot-app;1.0 default produced in /root/.sbt/boot/resolution-cache/org.scala-sbt-boot-app-default.xml
    resolve done (1297ms resolve - 0ms download)

:: problems summary ::
:::: WARNINGS
        module not found: org.scala-sbt#sbt;0.13.9

    ==== local: tried

      /root/.ivy2/local/org.scala-sbt/sbt/0.13.9/ivys/ivy.xml

      -- artifact org.scala-sbt#sbt;0.13.9!sbt.jar:

      /root/.ivy2/local/org.scala-sbt/sbt/0.13.9/jars/sbt.jar

    ==== Maven Central: tried

      https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.9/sbt-0.13.9.pom

      -- artifact org.scala-sbt#sbt;0.13.9!sbt.jar:

      https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.9/sbt-0.13.9.jar

    ==== typesafe-ivy-releases: tried

      https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.9/ivys/ivy.xml

    ==== sbt-ivy-snapshots: tried

      https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/0.13.9/ivys/ivy.xml

        ::::::::::::::::::::::::::::::::::::::::::::::

        ::          UNRESOLVED DEPENDENCIES         ::

        ::::::::::::::::::::::::::::::::::::::::::::::

        :: org.scala-sbt#sbt;0.13.9: not found

        ::::::::::::::::::::::::::::::::::::::::::::::


:::: ERRORS
    Server access Error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target url=https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.9/sbt-0.13.9.pom

    Server access Error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target url=https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.9/sbt-0.13.9.jar

    Server access Error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.9/ivys/ivy.xml

    Server access Error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target url=https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/0.13.9/ivys/ivy.xml


:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
java.lang.RuntimeException: not found
    at org.apache.ivy.core.resolve.IvyNode.loadData(IvyNode.java:238)
    at org.apache.ivy.core.resolve.VisitNode.loadData(VisitNode.java:292)
    at org.apache.ivy.core.resolve.ResolveEngine.fetchDependencies(ResolveEngine.java:714)
    at org.apache.ivy.core.resolve.ResolveEngine.doFetchDependencies(ResolveEngine.java:799)
    at org.apache.ivy.core.resolve.ResolveEngine.fetchDependencies(ResolveEngine.java:722)
    at org.apache.ivy.core.resolve.ResolveEngine.getDependencies(ResolveEngine.java:594)
    at org.apache.ivy.core.resolve.ResolveEngine.resolve(ResolveEngine.java:234)
    at xsbt.boot.Update.xsbt$boot$Update$$lockedApply(Update.scala:105)
    at xsbt.boot.Update$$anon$4.call(Update.scala:99)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
    at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
    at xsbt.boot.Using$.withResource(Using.scala:10)
    at xsbt.boot.Using$.apply(Using.scala:9)
    at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
    at xsbt.boot.Locks$.apply0(Locks.scala:31)
    at xsbt.boot.Locks$.apply(Locks.scala:28)
    at xsbt.boot.Update.apply(Update.scala:100)
    at xsbt.boot.Launch.update(Launch.scala:350)
    at xsbt.boot.Launch.xsbt$boot$Launch$$retrieve$1(Launch.scala:208)
    at xsbt.boot.Launch$$anonfun$3.apply(Launch.scala:216)
    at scala.Option.getOrElse(Option.scala:120)
    at xsbt.boot.Launch.xsbt$boot$Launch$$getAppProvider0(Launch.scala:216)
    at xsbt.boot.Launch$$anon$2.call(Launch.scala:196)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
    at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
    at xsbt.boot.Using$.withResource(Using.scala:10)
    at xsbt.boot.Using$.apply(Using.scala:9)
    at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
    at xsbt.boot.Locks$.apply0(Locks.scala:31)
    at xsbt.boot.Locks$.apply(Locks.scala:28)
    at xsbt.boot.Launch.locked(Launch.scala:238)
    at xsbt.boot.Launch.app(Launch.scala:147)
    at xsbt.boot.Launch.app(Launch.scala:145)
    at xsbt.boot.Launch$.run(Launch.scala:102)
    at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
    at xsbt.boot.Launch$.launch(Launch.scala:117)
    at xsbt.boot.Launch$.apply(Launch.scala:18)
    at xsbt.boot.Boot$.runImpl(Boot.scala:41)
    at xsbt.boot.Boot$.main(Boot.scala:17)
    at xsbt.boot.Boot.main(Boot.scala)
Error during sbt execution: Error retrieving required libraries
    at xsbt.boot.Pre$.error(Pre.scala:26)
    at xsbt.boot.Update.xsbt$boot$Update$$lockedApply(Update.scala:105)
    at xsbt.boot.Update$$anon$4.call(Update.scala:99)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
    at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
    at xsbt.boot.Using$.withResource(Using.scala:10)
    at xsbt.boot.Using$.apply(Using.scala:9)
    at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
    at xsbt.boot.Locks$.apply0(Locks.scala:31)
    at xsbt.boot.Locks$.apply(Locks.scala:28)
    at xsbt.boot.Update.apply(Update.scala:100)
    at xsbt.boot.Launch.update(Launch.scala:350)
    at xsbt.boot.Launch.xsbt$boot$Launch$$retrieve$1(Launch.scala:208)
    at xsbt.boot.Launch$$anonfun$3.apply(Launch.scala:216)
    at scala.Option.getOrElse(Option.scala:120)
    at xsbt.boot.Launch.xsbt$boot$Launch$$getAppProvider0(Launch.scala:216)
    at xsbt.boot.Launch$$anon$2.call(Launch.scala:196)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
    at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
    at xsbt.boot.Using$.withResource(Using.scala:10)
    at xsbt.boot.Using$.apply(Using.scala:9)
    at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
    at xsbt.boot.Locks$.apply0(Locks.scala:31)
    at xsbt.boot.Locks$.apply(Locks.scala:28)
    at xsbt.boot.Launch.locked(Launch.scala:238)
    at xsbt.boot.Launch.app(Launch.scala:147)
    at xsbt.boot.Launch.app(Launch.scala:145)
    at xsbt.boot.Launch$.run(Launch.scala:102)
    at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
    at xsbt.boot.Launch$.launch(Launch.scala:117)
    at xsbt.boot.Launch$.apply(Launch.scala:18)
    at xsbt.boot.Boot$.runImpl(Boot.scala:41)
    at xsbt.boot.Boot$.main(Boot.scala:17)
    at xsbt.boot.Boot.main(Boot.scala)
Error during sbt execution: Error retrieving required libraries
```
## expectation

sbt compiles the project
## notes

This looks like #2365, but I don't think this is the same issue, because I am not behind a firewall, and wget does not say the certificate is invalid.

**Comment by eed3si9n** [comment]
The key error message is this:

```
    Server access Error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target url=https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.9/sbt-0.13.9.pom
```

It doesn't matter if `wget` can hit https. What matters is `java`. Please go through:
- http://stackoverflow.com/questions/7709540/how-to-solve-sun-security-provider-certpath-suncertpathbuilderexception
- http://stackoverflow.com/questions/13626965/how-to-ignore-pkix-path-building-failed-sun-security-provider-certpath-suncertp
  etc.

**Comment by progval** [comment]
Can't you patch your code / packages to trust these certificates?

**Comment by eed3si9n** [comment]
If a build tool started implementing some arbitrary security workaround, that would be called a loophole or a backdoor. A certificate could be revoked after hacking, for example. Let's let java do the java thing.

**Comment by progval** [comment]
Patch your [install doc](http://www.scala-sbt.org/0.13/docs/Installing-sbt-on-Linux.html) to explain how to do that, then?

**Comment by eed3si9n** [comment]
Yea. That would make a lot more sense, I think.

**Comment by francisdb** [comment]
Just posting a workaround for Ubuntu 16.04 LTS:

``` bash
# Followed ubuntu instructions on installing sbt but ended up with OpenJDK 9
> sudo apt-get install sbt
> java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)
> sbt

# sbt fails to download files

# Install Oracle JDK 8
# instructions here: http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html
> sudo apt-get install oracle-java8-installer
...
> java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
> sbt
sbt starts correctly (after downloading the files that previously failed to download)

```

**Comment by ruliana** [comment]
Just for completeness, let me post another solution, as the one from @francisdb didn't work for me.

Run this at command line:
```sh
sudo /var/lib/dpkg/info/ca-certificates-java.postinst configure
```
The issue seems to be this one https://github.com/docker-library/openjdk/issues/19 (at least for me).

It seem, as far as I understand, that this bug _can_ get back at JDK9 =/

**Comment by mohammedyunus009** [comment]
Thats mainly because that repo(URL) in jar is not working

**Comment by mohammedyunus009** [comment]
Solution is find different compatible jars
