### ISSUE TITLE
Failure to boot into a new sbt 1.0.0-M1 build

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#2597]
## steps

**project/build.properties**

``` ini
sbt.version=1.0.0-M1
```

Run `sbt`
## problem

```
Downloading sbt launcher for 1.0.0-M1:
  From  http://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/sbt-launch/1.0.0-M1/sbt-launch.jar
    To  /Users/dnw/.sbt/launchers/1.0.0-M1/sbt-launch.jar
Getting org.scala-sbt sbt 1.0.0-M1 ...
downloading https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.0.0-M1/sbt-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#sbt;1.0.0-M1!sbt.jar (96ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/main_2.11/1.0.0-M1/main_2.11-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#main_2.11;1.0.0-M1!main_2.11.jar (251ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/actions_2.11/1.0.0-M1/actions_2.11-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#actions_2.11;1.0.0-M1!actions_2.11.jar (107ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/main-settings_2.11/1.0.0-M1/main-settings_2.11-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#main-settings_2.11;1.0.0-M1!main-settings_2.11.jar (112ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/run_2.11/1.0.0-M1/run_2.11-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#run_2.11;1.0.0-M1!run_2.11.jar (97ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/command_2.11/1.0.0-M1/command_2.11-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#command_2.11;1.0.0-M1!command_2.11.jar (98ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/launcher-interface/1.0.0/launcher-interface-1.0.0.jar ...
    [SUCCESSFUL ] org.scala-sbt#launcher-interface;1.0.0!launcher-interface.jar (11ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.0.0-M1/compiler-interface-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#compiler-interface;1.0.0-M1!compiler-interface.jar (11ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/io_2.11/1.0.0-M5/io_2.11-1.0.0-M5-tests.jar ...
    [SUCCESSFUL ] org.scala-sbt#io_2.11;1.0.0-M5!io_2.11.jar (15ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-logging_2.11/0.1.0-M12/util-logging_2.11-0.1.0-M12-tests.jar ...
    [SUCCESSFUL ] org.scala-sbt#util-logging_2.11;0.1.0-M12!util-logging_2.11.jar (17ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-logic_2.11/0.1.0-M12/util-logic_2.11-0.1.0-M12.jar ...
    [SUCCESSFUL ] org.scala-sbt#util-logic_2.11;0.1.0-M12!util-logic_2.11.jar (12ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/librarymanagement_2.11/0.1.0-M9/librarymanagement_2.11-0.1.0-M9.jar ...
    [SUCCESSFUL ] org.scala-sbt#librarymanagement_2.11;0.1.0-M9!librarymanagement_2.11.jar (74ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-compile_2.11/1.0.0-M1/zinc-compile_2.11-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#zinc-compile_2.11;1.0.0-M1!zinc-compile_2.11.jar (10ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/task-system_2.11/1.0.0-M1/task-system_2.11-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#task-system_2.11;1.0.0-M1!task-system_2.11.jar (93ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/tasks_2.11/1.0.0-M1/tasks_2.11-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#tasks_2.11;1.0.0-M1!tasks_2.11.jar (93ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/testing_2.11/1.0.0-M1/testing_2.11-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#testing_2.11;1.0.0-M1!testing_2.11.jar (94ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-classpath_2.11/1.0.0-M1/zinc-classpath_2.11-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#zinc-classpath_2.11;1.0.0-M1!zinc-classpath_2.11.jar (15ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-completion_2.11/0.1.0-M12/util-completion_2.11-0.1.0-M12.jar ...
    [SUCCESSFUL ] org.scala-sbt#util-completion_2.11;0.1.0-M12!util-completion_2.11.jar (21ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-apiinfo_2.11/1.0.0-M1/zinc-apiinfo_2.11-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#zinc-apiinfo_2.11;1.0.0-M1!zinc-apiinfo_2.11.jar (17ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc_2.11/1.0.0-M1/zinc_2.11-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#zinc_2.11;1.0.0-M1!zinc_2.11.jar (10ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-ivy-integration_2.11/1.0.0-M1/zinc-ivy-integration_2.11-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#zinc-ivy-integration_2.11;1.0.0-M1!zinc-ivy-integration_2.11.jar (8ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-relation_2.11/0.1.0-M12/util-relation_2.11-0.1.0-M12.jar ...
    [SUCCESSFUL ] org.scala-sbt#util-relation_2.11;0.1.0-M12!util-relation_2.11.jar (9ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-tracking_2.11/0.1.0-M12/util-tracking_2.11-0.1.0-M12.jar ...
    [SUCCESSFUL ] org.scala-sbt#util-tracking_2.11;0.1.0-M12!util-tracking_2.11.jar (12ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-interface/0.1.0-M12/util-interface-0.1.0-M12.jar ...
    [SUCCESSFUL ] org.scala-sbt#util-interface;0.1.0-M12!util-interface.jar (8ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-collection_2.11/0.1.0-M12/util-collection_2.11-0.1.0-M12.jar ...
    [SUCCESSFUL ] org.scala-sbt#util-collection_2.11;0.1.0-M12!util-collection_2.11.jar (24ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-control_2.11/0.1.0-M12/util-control_2.11-0.1.0-M12.jar ...
    [SUCCESSFUL ] org.scala-sbt#util-control_2.11;0.1.0-M12!util-control_2.11.jar (9ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/test-agent/1.0.0-M1/test-agent-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#test-agent;1.0.0-M1!test-agent.jar (92ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-classfile_2.11/1.0.0-M1/zinc-classfile_2.11-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#zinc-classfile_2.11;1.0.0-M1!zinc-classfile_2.11.jar (15ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-core_2.11/1.0.0-M1/zinc-core_2.11-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#zinc-core_2.11;1.0.0-M1!zinc-core_2.11.jar (23ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-persist_2.11/1.0.0-M1/zinc-persist_2.11-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#zinc-persist_2.11;1.0.0-M1!zinc-persist_2.11.jar (14ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-compile-core_2.11/1.0.0-M1/zinc-compile-core_2.11-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#zinc-compile-core_2.11;1.0.0-M1!zinc-compile-core_2.11.jar (16ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/sbinary_2.11/0.4.3/sbinary_2.11-0.4.3.jar ...
    [SUCCESSFUL ] org.scala-sbt#sbinary_2.11;0.4.3!sbinary_2.11.jar (97ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-cache_2.11/0.1.0-M12/util-cache_2.11-0.1.0-M12.jar ...
    [SUCCESSFUL ] org.scala-sbt#util-cache_2.11;0.1.0-M12!util-cache_2.11.jar (15ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-apply-macro_2.11/0.1.0-M12/util-apply-macro_2.11-0.1.0-M12.jar ...
    [SUCCESSFUL ] org.scala-sbt#util-apply-macro_2.11;0.1.0-M12!util-apply-macro_2.11.jar (11ms)
:: retrieving :: org.scala-sbt#boot-app
    confs: [default]
    47 artifacts copied, 0 already retrieved (18763kB/115ms)
Getting Scala 2.11.8 (for sbt)...
:: retrieving :: org.scala-sbt#boot-scala
    confs: [default]
    6 artifacts copied, 0 already retrieved (26456kB/109ms)
java.lang.NoClassDefFoundError: sbt/internal/util/ConsoleOut$
    at sbt.StandardMain$.<init>(Main.scala:66)
    at sbt.StandardMain$.<clinit>(Main.scala)
    at sbt.xMain.run(Main.scala:36)
    at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
    at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
    at xsbt.boot.Launch$.run(Launch.scala:109)
    at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
    at xsbt.boot.Launch$.launch(Launch.scala:117)
    at xsbt.boot.Launch$.apply(Launch.scala:18)
    at xsbt.boot.Boot$.runImpl(Boot.scala:41)
    at xsbt.boot.Boot$.main(Boot.scala:17)
    at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.ClassNotFoundException: sbt.internal.util.ConsoleOut$
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 12 more
Error during sbt execution: java.lang.NoClassDefFoundError: sbt/internal/util/ConsoleOut$
```
## expectation

I expected to be launched into the sbt `shell`
## notes

Running a custom version of sbt-extras (PR pending): https://github.com/dwijnand/sbt-extras/commit/16f10bec81655453a6531114c2c40de7a3eb5ee8

But I don't think it's relevant because it fails the same way with:

```
java -Xms512m -Xmx1536m -Xss2m -XX:ReservedCodeCacheSize=256m -XX:+TieredCompilation \
  -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC \
  -jar /Users/dnw/.sbt/launchers/1.0.0-M1/sbt-launch.jar shell
```

**Comment by smarter** [comment]
Not to brag, but I think I reported this 6 months ago: https://groups.google.com/forum/#!msg/sbt-dev/EUs6lbx3i8o/35jDkJb1BQAJ :)

**Comment by eed3si9n** [comment]
Here's the problem..

```
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-logging_2.11/0.1.0-M12/util-logging_2.11-0.1.0-M12-tests.jar ...
    [SUCCESSFUL ] org.scala-sbt#util-logging_2.11;0.1.0-M12!util-logging_2.11.jar (17ms)
```

**Comment by eed3si9n** [comment]
It seems like we're hitting #2002/#2451 with https://bintray.com/sbt/maven-releases/librarymanagement/0.1.0-M9/view#files/org/scala-sbt/librarymanagement_2.11/0.1.0-M9:

```
        <dependency>
            <groupId>org.scala-sbt</groupId>
            <artifactId>util-logging_2.11</artifactId>
            <version>0.1.0-M12</version>
            <classifier>tests</classifier>
        </dependency>
```

Note it's missing the scope.

**Comment by gslowikowski** [comment]
#2600 is not enough because `Zinc` pulls transitively three additional `tests` artifacts. Maven dependency tree fragments (from test Maven build with `SBT 1.0.0-M2`):

``` xml
      |  +- org.scala-sbt:zinc-ivy-integration_2.11:jar:1.0.0-M1:compile
      |  |  \- org.scala-sbt:librarymanagement_2.11:jar:tests:0.1.0-M8:compile
      |  |     \- org.scala-sbt:io_2.11:jar:tests:1.0.0-M5:compile
```

and

``` xml
         \- org.scala-sbt:zinc-compile-core_2.11:jar:1.0.0-M1:compile
            \- org.scala-sbt:util-logging_2.11:jar:tests:0.1.0-M12:compile
```
