### ISSUE TITLE
[1.0.0-M1] NoClassDefFoundError: sbt/internal/util/ConsoleOut$

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt#2598]
## steps

```
$ wget http://dl.bintray.com/sbt/maven-releases/org/scala-sbt/sbt-launch/1.0.0-M1/sbt-launch.jar
$ mkdir project
$ echo "sbt.version=1.0.0-M1" > project/build.properties
$ java -jar sbt-launch.jar 
Getting org.scala-sbt sbt 1.0.0-M1 ...
downloading https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.0.0-M1/sbt-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#sbt;1.0.0-M1!sbt.jar (931ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/main_2.11/1.0.0-M1/main_2.11-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#main_2.11;1.0.0-M1!main_2.11.jar (3223ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/actions_2.11/1.0.0-M1/actions_2.11-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#actions_2.11;1.0.0-M1!actions_2.11.jar (730ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/main-settings_2.11/1.0.0-M1/main-settings_2.11-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#main-settings_2.11;1.0.0-M1!main-settings_2.11.jar (751ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/run_2.11/1.0.0-M1/run_2.11-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#run_2.11;1.0.0-M1!run_2.11.jar (489ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/command_2.11/1.0.0-M1/command_2.11-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#command_2.11;1.0.0-M1!command_2.11.jar (1082ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/launcher-interface/1.0.0/launcher-interface-1.0.0.jar ...
    [SUCCESSFUL ] org.scala-sbt#launcher-interface;1.0.0!launcher-interface.jar (477ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.0.0-M1/compiler-interface-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#compiler-interface;1.0.0-M1!compiler-interface.jar (477ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/io_2.11/1.0.0-M5/io_2.11-1.0.0-M5-tests.jar ...
    [SUCCESSFUL ] org.scala-sbt#io_2.11;1.0.0-M5!io_2.11.jar (657ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-logging_2.11/0.1.0-M12/util-logging_2.11-0.1.0-M12-tests.jar ...
    [SUCCESSFUL ] org.scala-sbt#util-logging_2.11;0.1.0-M12!util-logging_2.11.jar (1482ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-logic_2.11/0.1.0-M12/util-logic_2.11-0.1.0-M12.jar ...
    [SUCCESSFUL ] org.scala-sbt#util-logic_2.11;0.1.0-M12!util-logic_2.11.jar (473ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/librarymanagement_2.11/0.1.0-M9/librarymanagement_2.11-0.1.0-M9.jar ...
    [SUCCESSFUL ] org.scala-sbt#librarymanagement_2.11;0.1.0-M9!librarymanagement_2.11.jar (1917ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-compile_2.11/1.0.0-M1/zinc-compile_2.11-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#zinc-compile_2.11;1.0.0-M1!zinc-compile_2.11.jar (481ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/task-system_2.11/1.0.0-M1/task-system_2.11-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#task-system_2.11;1.0.0-M1!task-system_2.11.jar (475ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/tasks_2.11/1.0.0-M1/tasks_2.11-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#tasks_2.11;1.0.0-M1!tasks_2.11.jar (478ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/testing_2.11/1.0.0-M1/testing_2.11-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#testing_2.11;1.0.0-M1!testing_2.11.jar (477ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-classpath_2.11/1.0.0-M1/zinc-classpath_2.11-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#zinc-classpath_2.11;1.0.0-M1!zinc-classpath_2.11.jar (483ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-completion_2.11/0.1.0-M12/util-completion_2.11-0.1.0-M12.jar ...
    [SUCCESSFUL ] org.scala-sbt#util-completion_2.11;0.1.0-M12!util-completion_2.11.jar (722ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-apiinfo_2.11/1.0.0-M1/zinc-apiinfo_2.11-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#zinc-apiinfo_2.11;1.0.0-M1!zinc-apiinfo_2.11.jar (615ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc_2.11/1.0.0-M1/zinc_2.11-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#zinc_2.11;1.0.0-M1!zinc_2.11.jar (512ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-ivy-integration_2.11/1.0.0-M1/zinc-ivy-integration_2.11-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#zinc-ivy-integration_2.11;1.0.0-M1!zinc-ivy-integration_2.11.jar (532ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-relation_2.11/0.1.0-M12/util-relation_2.11-0.1.0-M12.jar ...
    [SUCCESSFUL ] org.scala-sbt#util-relation_2.11;0.1.0-M12!util-relation_2.11.jar (508ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-tracking_2.11/0.1.0-M12/util-tracking_2.11-0.1.0-M12.jar ...
    [SUCCESSFUL ] org.scala-sbt#util-tracking_2.11;0.1.0-M12!util-tracking_2.11.jar (502ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-interface/0.1.0-M12/util-interface-0.1.0-M12.jar ...
    [SUCCESSFUL ] org.scala-sbt#util-interface;0.1.0-M12!util-interface.jar (484ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-collection_2.11/0.1.0-M12/util-collection_2.11-0.1.0-M12.jar ...
    [SUCCESSFUL ] org.scala-sbt#util-collection_2.11;0.1.0-M12!util-collection_2.11.jar (755ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-control_2.11/0.1.0-M12/util-control_2.11-0.1.0-M12.jar ...
    [SUCCESSFUL ] org.scala-sbt#util-control_2.11;0.1.0-M12!util-control_2.11.jar (555ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/test-agent/1.0.0-M1/test-agent-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#test-agent;1.0.0-M1!test-agent.jar (644ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar ...
    [SUCCESSFUL ] org.scala-sbt#test-interface;1.0!test-interface.jar (569ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-classfile_2.11/1.0.0-M1/zinc-classfile_2.11-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#zinc-classfile_2.11;1.0.0-M1!zinc-classfile_2.11.jar (496ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-core_2.11/1.0.0-M1/zinc-core_2.11-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#zinc-core_2.11;1.0.0-M1!zinc-core_2.11.jar (750ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-persist_2.11/1.0.0-M1/zinc-persist_2.11-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#zinc-persist_2.11;1.0.0-M1!zinc-persist_2.11.jar (505ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/zinc-compile-core_2.11/1.0.0-M1/zinc-compile-core_2.11-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#zinc-compile-core_2.11;1.0.0-M1!zinc-compile-core_2.11.jar (621ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/sbinary_2.11/0.4.3/sbinary_2.11-0.4.3.jar ...
    [SUCCESSFUL ] org.scala-sbt#sbinary_2.11;0.4.3!sbinary_2.11.jar (488ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/ivy/ivy/2.3.0-sbt-2cc8d2761242b072cedb0a04cb39435c4fa24f9a/ivy-2.3.0-sbt-2cc8d2761242b072cedb0a04cb39435c4fa24f9a.jar ...
    [SUCCESSFUL ] org.scala-sbt.ivy#ivy;2.3.0-sbt-2cc8d2761242b072cedb0a04cb39435c4fa24f9a!ivy.jar (1115ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/serialization_2.11/0.1.2/serialization_2.11-0.1.2.jar ...
    [SUCCESSFUL ] org.scala-sbt#serialization_2.11;0.1.2!serialization_2.11.jar (712ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-cache_2.11/0.1.0-M12/util-cache_2.11-0.1.0-M12.jar ...
    [SUCCESSFUL ] org.scala-sbt#util-cache_2.11;0.1.0-M12!util-cache_2.11.jar (614ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/util-apply-macro_2.11/0.1.0-M12/util-apply-macro_2.11-0.1.0-M12.jar ...
    [SUCCESSFUL ] org.scala-sbt#util-apply-macro_2.11;0.1.0-M12!util-apply-macro_2.11.jar (485ms)
:: retrieving :: org.scala-sbt#boot-app
    confs: [default]
    47 artifacts copied, 0 already retrieved (18763kB/232ms)
Getting Scala 2.11.8 (for sbt)...
:: retrieving :: org.scala-sbt#boot-scala
    confs: [default]
    6 artifacts copied, 0 already retrieved (26456kB/101ms)
java.lang.NoClassDefFoundError: sbt/internal/util/ConsoleOut$
    at sbt.StandardMain$.<init>(Main.scala:66)
    at sbt.StandardMain$.<clinit>(Main.scala)
    at sbt.xMain.run(Main.scala:36)
    at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
    at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
    at xsbt.boot.Launch$.run(Launch.scala:109)
    at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
    at xsbt.boot.Launch$.launch(Launch.scala:117)
    at xsbt.boot.Launch$.apply(Launch.scala:18)
    at xsbt.boot.Boot$.runImpl(Boot.scala:41)
    at xsbt.boot.Boot$.main(Boot.scala:17)
    at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.ClassNotFoundException: sbt.internal.util.ConsoleOut$
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 12 more
Error during sbt execution: java.lang.NoClassDefFoundError: sbt/internal/util/ConsoleOut$
```
## problem

unexpected `ClassNotFoundException` error

**Comment by xuwei-k** [comment]
Oops, duplicate https://github.com/sbt/sbt/issues/2597

**Comment by dwijnand** [comment]
"I beat Kenji at the first post-release bug report, ask me anything" :-)
