### ISSUE TITLE
compile gives NoType error

### ISSUE THREAD

**Issue by vincentcr** [sbt/sbt#26]
issuing sbt compile gives this error: 

default/compile: java.lang.RuntimeException: NoType

sample:
https://github.com/vincentcr/sbt-098-iter-notype

stack trace:

java.lang.RuntimeException: NoType
        at xsbt.API.error(API.scala:26)
        at xsbt.API.xsbt$API$$makeType(API.scala:330)
        at xsbt.API$$anonfun$xsbt$API$$processType$1.apply(API.scala:312)
        at xsbt.API$$anonfun$xsbt$API$$processType$1.apply(API.scala:312)
        at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:188)
        at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:43)
        at xsbt.API.xsbt$API$$processType(API.scala:312)
        at xsbt.API$$anonfun$xsbt$API$$types$1.apply(API.scala:112)
        at xsbt.API$$anonfun$xsbt$API$$types$1.apply(API.scala:112)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:194)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:194)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:34)
        at scala.collection.mutable.ArrayOps.foreach(ArrayOps.scala:38)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:194)
        at scala.collection.mutable.ArrayOps.map(ArrayOps.scala:38)
        at xsbt.API.xsbt$API$$types(API.scala:112)
        at xsbt.API$$anonfun$mkStructure$1.apply(API.scala:259)
        at xsbt.API$$anonfun$mkStructure$1.apply(API.scala:259)
        at xsbt.Message$$anon$1.apply(Message.scala:8)
        at xsbti.SafeLazy$$anonfun$apply$1.apply(SafeLazy.scala:8)
        at xsbti.SafeLazy$Impl._t(SafeLazy.scala:20)
        at xsbti.SafeLazy$Impl.get(SafeLazy.scala:24)
        at xsbt.API$$anonfun$xsbt$API$$forceStructures$1.apply(API.scala:95)
        at xsbt.API$$anonfun$xsbt$API$$forceStructures$1.apply(API.scala:95)
        at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
        at scala.collection.immutable.List.foreach(List.scala:45)
        at xsbt.API.xsbt$API$$forceStructures(API.scala:95)
        at xsbt.API$ApiPhase.processScalaUnit(API.scala:49)
        at xsbt.API$ApiPhase.processUnit(API.scala:40)
        at xsbt.API$ApiPhase$$anonfun$run$1.apply(API.scala:36)
        at xsbt.API$ApiPhase$$anonfun$run$1.apply(API.scala:36)
        at scala.collection.Iterator$class.foreach(Iterator.scala:652)
        at scala.collection.mutable.ListBuffer$$anon$1.foreach(ListBuffer.scala:311)
        at xsbt.API$ApiPhase.run(API.scala:36)
        at scala.tools.nsc.Global$Run.compileSources(Global.scala:949)
        at scala.tools.nsc.Global$Run.compile(Global.scala:1034)
        at xsbt.CompilerInterface.run(CompilerInterface.scala:87)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:57)
        at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:29)
        at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:25)
        at sbt.AggressiveCompile$$anonfun$5.compileScala$1(AggressiveCompile.scala:66)
        at sbt.AggressiveCompile$$anonfun$5.apply(AggressiveCompile.scala:78)
        at sbt.AggressiveCompile$$anonfun$5.apply(AggressiveCompile.scala:56)
        at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:21)
        at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:19)
        at sbt.inc.Incremental$.cycle(Incremental.scala:34)
        at sbt.inc.Incremental$.compile(Incremental.scala:21)
        at sbt.inc.IncrementalCompile$.apply(Compile.scala:17)
        at sbt.AggressiveCompile.compile2(AggressiveCompile.scala:86)
        at sbt.AggressiveCompile.compile1(AggressiveCompile.scala:37)
        at sbt.AggressiveCompile.apply(AggressiveCompile.scala:27)
        at sbt.Compiler$.apply(Compiler.scala:101)
        at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:397)
        at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:397)
        at sbt.Scoped$$anonfun$hf2$1.apply(Structure.scala:507)
        at sbt.Scoped$$anonfun$hf2$1.apply(Structure.scala:507)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:44)
        at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$9.apply(Structure.scala:305)
        at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$9.apply(Structure.scala:305)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:39)
        at sbt.std.Transform$$anon$5.work(System.scala:66)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:220)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:220)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:13)
        at sbt.Execute.work(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:220)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:220)
        at sbt.CompletionService$$anon$1$$anon$2.call(CompletionService.scala:26)
        at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by harrah** [comment]
Thanks for the minimal example.  At a minimum I'll turn the error into a warning.

**Comment by vincentcr** [comment]
do you mean it points to a real problem in the code?

**Comment by harrah** [comment]
There is an underlying error that scalac will report and because of this error, type information was complete, causing sbt to get confused.  It was a bug in sbt and is now fixed.  Thanks again for the test case.
