### ISSUE TITLE
Sbt compilation errors v0.11.1

### ISSUE THREAD

**Issue by moonboots** [sbt/sbt#262]
I get the error below when trying to compile xsbt v0.11.1 following the instructions in the Setup wiki. I'm using linux x64, java 1.7.0_01, and the latest sbt-launch.jar. The bootstrap sbt script is using 512m. Thanks for the help.

```
[info] Compiling 9 Scala sources to /home/jack/code3/xsbt/compile/interface/target/precompiled_2.9.0/classes...
error: java.lang.OutOfMemoryError: Java heap space
        at scala.tools.nsc.util.HashSet.growTable(HashSet.scala:98)
        at scala.tools.nsc.util.HashSet.findEntryOrUpdate(HashSet.scala:40)
        at scala.tools.nsc.symtab.Types$class.scala$tools$nsc$symtab$Types$$unique(Types.scala:2995)
        at scala.tools.nsc.symtab.Types$TypeRef$.apply(Types.scala:2026)
        at scala.tools.nsc.symtab.Types$class.copyTypeRef(Types.scala:2776)
        at scala.tools.nsc.symtab.SymbolTable.copyTypeRef(SymbolTable.scala:13)
        at scala.tools.nsc.symtab.Types$TypeMap.mapOver(Types.scala:3117)
        at scala.tools.nsc.symtab.Types$AsSeenFromMap.apply(Types.scala:3522)
        at scala.tools.nsc.symtab.Types$AsSeenFromMap.apply(Types.scala:3389)
        at scala.tools.nsc.symtab.Types$TypeMap$$anonfun$16.apply(Types.scala:3229)
        at scala.tools.nsc.symtab.Types$TypeMap$$anonfun$16.apply(Types.scala:3226)
        at scala.collection.LinearSeqOptimized$class.exists(LinearSeqOptimized.scala:79)
        at scala.collection.immutable.List.exists(List.scala:45)
        at scala.tools.nsc.symtab.Types$TypeMap.mapOver(Types.scala:3226)
        at scala.tools.nsc.symtab.Types$TypeMap.mapOver(Types.scala:3128)
        at scala.tools.nsc.symtab.Types$AsSeenFromMap.apply(Types.scala:3522)
        at scala.tools.nsc.symtab.Types$AsSeenFromMap.apply(Types.scala:3389)
        at scala.tools.nsc.symtab.Types$TypeMap.mapOver(Types.scala:3138)
        at scala.tools.nsc.symtab.Types$AsSeenFromMap.apply(Types.scala:3522)
        at scala.tools.nsc.symtab.Types$Type.asSeenFrom(Types.scala:546)
        at scala.tools.nsc.symtab.Types$Type.computeMemberType(Types.scala:575)
        at scala.tools.nsc.symtab.Symbols$MethodSymbol.typeAsMemberOf(Symbols.scala:1853)
        at scala.tools.nsc.symtab.Types$Type.memberType(Types.scala:566)
        at scala.tools.nsc.symtab.Types$Type.findMember(Types.scala:925)
        at scala.tools.nsc.symtab.Types$Type.nonPrivateMembers(Types.scala:484)
        at scala.tools.nsc.symtab.Types$class.lub1$1(Types.scala:5347)
        at scala.tools.nsc.symtab.Types$class.lub0$1(Types.scala:5302)
        at scala.tools.nsc.symtab.Types$class.lub(Types.scala:5387)
        at scala.tools.nsc.symtab.SymbolTable.lub(SymbolTable.scala:13)
        at scala.tools.nsc.symtab.Types$$anonfun$54.apply(Types.scala:5578)
        at scala.tools.nsc.symtab.Types$$anonfun$54.apply(Types.scala:5572)
        at scala.Tuple2$Zipped$$anonfun$map$1.apply(Tuple2.scala:65)

[info] Packaging /home/jack/code3/xsbt/compile/interface/target/precompiled_2.8.1/compiler-interface-bin-0.11.1.jar ...
[info] Done packaging.
[info] Packaging /home/jack/code3/xsbt/compile/interface/target/precompiled_2.8.0/compiler-interface-bin-0.11.1.jar ...
[info] Done packaging.
[info] Packaging /home/jack/code3/xsbt/launch/test-sample/target/launch-test-0.11.1.jar ...
[info] Done packaging.
[info] Packaging /home/jack/code3/xsbt/compile/api/target/scala-2.9.1/api_2.9.1-0.11.1.jar ...
[info] Done packaging.
[info] Packaging /home/jack/code3/xsbt/compile/interface/target/precompiled_2.9.1/compiler-interface-bin-0.11.1.jar ...
[info] Done packaging.
[info] Packaging /home/jack/code3/xsbt/util/log/target/scala-2.9.1/logging_2.9.1-0.11.1.jar ...
[info] Done packaging.
[info] Compiling 11 Scala sources to /home/jack/code3/xsbt/compile/inc/target/scala-2.9.1/classes...
[infosbt appears to be exiting abnormally.
  The log file for this session is at /tmp/sbt4658609606460511114.log
] Compiling 3 Scala sources to /home/jack/code3/xsbt/util/classfile/target/scala-2.9.1/classes...
Exception in thread "main"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "main"
```

**Comment by harrah** [comment]
Please use the mailing list for questions.
