### ISSUE TITLE
alias, set, and multiple commands: a tale of woe

### ISSUE THREAD

**Issue by waywardmonkeys** [sbt/sbt#270]
While I'd love to do this:

```
alias stest=; set parallelExecution in GlobalScope := false; test; set parallelExecution in GlobalScope := true
```

Unfortunately, sbt 0.11.1 isn't so fond of the idea:

```
all> stest
<set>:1: error: eof expected but ';' found.
parallelExecution in GlobalScope := false; test; set parallelExecution in GlobalScope := true
                                         ^
[error] Error parsing expression.  Note that settings are expressions and do not end with semicolons.  (Semicolons are fine within {} blocks, however.)
```

**Comment by lambdaknight** [comment]
It also doesn't work with "eval".  As an example,

```
sbt "; project foo; eval println(\"Foo\"); project bar; shell"
```

Running this produces the following:

```
<eval>:1: error: eof expected but ';' found.
println("Foo"); project bar
              ^
[error] sbt.compiler.EvalException: Error parsing expression.  Note that settings are expressions and do not end with semicolons.  (Semicolons are fine within {} blocks, however.)
```

The full stack trace from "last" is:

```
sbt.compiler.EvalException: Error parsing expression.  Note that settings are expressions and do not end with semicolons.  (Semicolons are fine within {} blocks, however.)
    at sbt.compiler.Eval.checkError(Eval.scala:196)
    at sbt.compiler.Eval.parseExpr(Eval.scala:168)
    at sbt.compiler.Eval.eval0(Eval.scala:73)
    at sbt.compiler.Eval.eval(Eval.scala:62)
    at sbt.BuiltinCommands$$anonfun$eval$1.apply(Main.scala:367)
    at sbt.BuiltinCommands$$anonfun$eval$1.apply(Main.scala:363)
    at sbt.Command$$anonfun$sbt$Command$$apply1$1$$anonfun$apply$6.apply(Command.scala:74)
    at sbt.Command$.process(Command.scala:92)
    at sbt.MainLoop$$anonfun$next$1$$anonfun$apply$1.apply(Main.scala:121)
    at sbt.MainLoop$$anonfun$next$1$$anonfun$apply$1.apply(Main.scala:121)
    at sbt.State$$anon$1.process(State.scala:154)
    at sbt.MainLoop$$anonfun$next$1.apply(Main.scala:121)
    at sbt.MainLoop$$anonfun$next$1.apply(Main.scala:121)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.MainLoop$.next(Main.scala:121)
    at sbt.MainLoop$.run(Main.scala:114)
    at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(Main.scala:103)
    at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(Main.scala:100)
    at sbt.Using.apply(Using.scala:25)
    at sbt.MainLoop$.runWithNewLog(Main.scala:100)
    at sbt.MainLoop$.runAndClearLast(Main.scala:83)
    at sbt.MainLoop$.runLoggedLoop(Main.scala:67)
    at sbt.MainLoop$.runLogged(Main.scala:60)
    at sbt.xMain.run(Main.scala:33)
    at xsbt.boot.Launch$.run(Launch.scala:54)
    at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:43)
    at xsbt.boot.Launch$.launch(Launch.scala:68)
    at xsbt.boot.Launch$.apply(Launch.scala:14)
    at xsbt.boot.Boot$.runImpl(Boot.scala:25)
    at xsbt.boot.Boot$.main(Boot.scala:15)
    at xsbt.boot.Boot.main(Boot.scala)
```
