### ISSUE TITLE
Launch Error

### ISSUE THREAD

**Issue by SamsudhinHabeeb-CTS** [sbt/sbt#2700]
(See the guidelines for contributing, linked above)
## steps

sbt package
## problem

```
Getting org.scala-sbt sbt 0.13.9 ...
java.lang.InternalError
        at sun.security.ec.SunEC.initialize(Native Method)
        at sun.security.ec.SunEC.access$000(SunEC.java:49)
        at sun.security.ec.SunEC$1.run(SunEC.java:61)
        at sun.security.ec.SunEC$1.run(SunEC.java:58)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.security.ec.SunEC.<clinit>(SunEC.java:58)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at java.lang.Class.newInstance(Class.java:383)
        at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:221)
        at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:206)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.security.jca.ProviderConfig.doLoadProvider(ProviderConfig.java:206)
        at sun.security.jca.ProviderConfig.getProvider(ProviderConfig.java:187)
        at sun.security.jca.ProviderList.getProvider(ProviderList.java:233)
        at sun.security.jca.ProviderList.getService(ProviderList.java:331)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:157)
        at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
        at javax.net.ssl.SSLContext.getDefault(SSLContext.java:97)
        at javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:121)
        at javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:333)
        at javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:291)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:85)
        at sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
        at sun.net.www.protocol.https.Handler.openConnection(Handler.java:57)
        at java.net.URL.openConnection(URL.java:982)
        at org.apache.ivy.util.url.BasicURLHandler.getURLInfo$57a0216e(BasicURLHandler.java:66)
        at org.apache.ivy.util.url.BasicURLHandler.getURLInfo(BasicURLHandler.java:54)
        at org.apache.ivy.plugins.repository.url.URLResource.init(URLResource.java:65)
        at org.apache.ivy.plugins.repository.url.URLResource.exists(URLResource.java:81)
        at org.apache.ivy.plugins.resolver.RepositoryResolver.findResourceUsingPattern(RepositoryResolver.java:97)
        at org.apache.ivy.plugins.resolver.AbstractPatternsBasedResolver.findResourceUsingPatterns(AbstractPatternsBasedResolver.java:96)
        at org.apache.ivy.plugins.resolver.IBiblioResolver.findIvyFileRef(IBiblioResolver.java:102)
        at org.apache.ivy.plugins.resolver.BasicResolver.getDependency(BasicResolver.java:228)
        at org.apache.ivy.plugins.resolver.IBiblioResolver.getDependency(IBiblioResolver.java:512)
        at org.apache.ivy.plugins.resolver.ChainResolver.getDependency(ChainResolver.java:104)
        at org.apache.ivy.core.resolve.IvyNode.loadData(IvyNode.java:169)
        at org.apache.ivy.core.resolve.VisitNode.loadData(VisitNode.java:292)
        at org.apache.ivy.core.resolve.ResolveEngine.fetchDependencies(ResolveEngine.java:714)
        at org.apache.ivy.core.resolve.ResolveEngine.doFetchDependencies(ResolveEngine.java:799)
        at org.apache.ivy.core.resolve.ResolveEngine.fetchDependencies(ResolveEngine.java:722)
        at org.apache.ivy.core.resolve.ResolveEngine.getDependencies(ResolveEngine.java:594)
        at org.apache.ivy.core.resolve.ResolveEngine.resolve(ResolveEngine.java:234)
        at xsbt.boot.Update.xsbt$boot$Update$$lockedApply(Update.scala:105)
        at xsbt.boot.Update$$anon$4.call(Update.scala:99)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
        at xsbt.boot.Using$.withResource(Using.scala:10)
        at xsbt.boot.Using$.apply(Using.scala:9)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at xsbt.boot.Update.apply(Update.scala:100)
        at xsbt.boot.Launch.update(Launch.scala:350)
        at xsbt.boot.Launch.xsbt$boot$Launch$$retrieve$1(Launch.scala:208)
        at xsbt.boot.Launch$$anonfun$3.apply(Launch.scala:216)
        at scala.Option.getOrElse(Option.scala:120)
        at xsbt.boot.Launch.xsbt$boot$Launch$$getAppProvider0(Launch.scala:216)
        at xsbt.boot.Launch$$anon$2.call(Launch.scala:196)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
        at xsbt.boot.Using$.withResource(Using.scala:10)
        at xsbt.boot.Using$.apply(Using.scala:9)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at xsbt.boot.Launch.locked(Launch.scala:238)
        at xsbt.boot.Launch.app(Launch.scala:147)
        at xsbt.boot.Launch.app(Launch.scala:145)
        at xsbt.boot.Launch$.run(Launch.scala:102)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
        at xsbt.boot.Launch$.launch(Launch.scala:117)
        at xsbt.boot.Launch$.apply(Launch.scala:18)
        at xsbt.boot.Boot$.runImpl(Boot.scala:41)
        at xsbt.boot.Boot$.main(Boot.scala:17)
        at xsbt.boot.Boot.main(Boot.scala)
Error during sbt execution: java.lang.InternalError
```

**Comment by eed3si9n** [comment]
[Bug 1332456](https://bugzilla.redhat.com/show_bug.cgi?id=1332456) - Build java-1.8.0-openjdk-1.8.0.91-2.b14.fc23 breaks tomcat startup for FreeIPA when nss is not upgraded as well.

Are you using openjdk-1.8.0.91?

**Comment by eed3si9n** [comment]
I am closing this due to inactivity, but if this is still relevant let us know with more details (reproduction steps etc).
