### ISSUE TITLE
sbt 0.13.12 console fails with NoClassDefFoundError when scalaVersion is 2.11.8

### ISSUE THREAD

**Issue by hossameldeen** [sbt/sbt#2704]
## steps
- Created a directory that only has an empty `build.sbt`. Launched sbt and called `compile` then `console`. Everything worked well.
- Exited sbt. Added `scalaVersion := "2.11.8"` in `build.sbt`. Launched sbt and called `compile`, which seems to have worked well. Called `console` which threw an exception, but then started but wasn't fully functional (detailed in problem section).  
  Here're the console contents starting from the second run, after adding `scalaVersion := "2.11.8"`.

<details>
  <summary>

`cmd content. The interesting part is probably after calling console`</summary>

```
D:\Programming\sublime-projects\hello-world>sbt
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[info] Loading global plugins from C:\Users\7\.sbt\0.13\plugins
[info] Set current project to hello-world (in build file:/D:/Programming/sublime-projects/hello-world/)
> compile
[info] Updating default:hello-world_2.11:0.1-SNAPSHOT
[info] Resolved default:hello-world_2.11:0.1-SNAPSHOT dependencies
[info] Fetching artifacts of default:hello-world_2.11:0.1-SNAPSHOT
[info] Fetched artifacts of default:hello-world_2.11:0.1-SNAPSHOT
[success] Total time: 1 s, completed Aug 21, 2016 9:01:15 PM
> console
[info] Starting scala interpreter...
[info]
[ERROR] Terminal initialization failed; falling back to unsupported
java.lang.NoClassDefFoundError: Could not initialize class scala.tools.fusesource_embedded.jansi.internal.Kernel32
        at scala.tools.fusesource_embedded.jansi.internal.WindowsSupport.getConsoleMode(WindowsSupport.java:50)
        at scala.tools.jline_embedded.WindowsTerminal.getConsoleMode(WindowsTerminal.java:204)
        at scala.tools.jline_embedded.WindowsTerminal.init(WindowsTerminal.java:82)
        at scala.tools.jline_embedded.TerminalFactory.create(TerminalFactory.java:101)
        at scala.tools.jline_embedded.TerminalFactory.get(TerminalFactory.java:158)
        at scala.tools.jline_embedded.console.ConsoleReader.<init>(ConsoleReader.java:229)
        at scala.tools.jline_embedded.console.ConsoleReader.<init>(ConsoleReader.java:221)
        at scala.tools.jline_embedded.console.ConsoleReader.<init>(ConsoleReader.java:209)
        at scala.tools.nsc.interpreter.jline_embedded.JLineConsoleReader.<init>(JLineReader.scala:62)
        at scala.tools.nsc.interpreter.jline_embedded.InteractiveReader.<init>(JLineReader.scala:34)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$scala$tools$nsc$interpreter$ILoop$$instantiater$1$1.apply(ILoop.scala:858)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$scala$tools$nsc$interpreter$ILoop$$instantiater$1$1.apply(ILoop.scala:855)
        at scala.tools.nsc.interpreter.ILoop.scala$tools$nsc$interpreter$ILoop$$mkReader$1(ILoop.scala:862)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$21$$anonfun$apply$9.apply(ILoop.scala:873)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$21$$anonfun$apply$9.apply(ILoop.scala:873)
        at scala.util.Try$.apply(Try.scala:192)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$21.apply(ILoop.scala:873)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$21.apply(ILoop.scala:873)
        at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:418)
        at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:418)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1233)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1223)
        at scala.collection.immutable.Stream.collect(Stream.scala:435)
        at scala.tools.nsc.interpreter.ILoop.chooseReader(ILoop.scala:875)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1$$anonfun$apply$mcZ$sp$2.apply(ILoop.scala:914)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:914)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:909)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:909)
        at scala.reflect.internal.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:97)
        at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:909)
        at scala.tools.nsc.interpreter.ILoop.main(ILoop.scala:934)
        at xsbt.ConsoleInterface.run(ConsoleInterface.scala:62)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
        at sbt.compiler.AnalyzingCompiler.console(AnalyzingCompiler.scala:76)
        at sbt.Console.sbt$Console$$console0$1(Console.scala:22)
        at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply$mcV$sp(Console.scala:23)
        at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:23)
        at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:23)
        at sbt.Logger$$anon$4.apply(Logger.scala:84)
        at sbt.TrapExit$App.run(TrapExit.scala:248)
        at java.lang.Thread.run(Unknown Source)

Welcome to Scala 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_92).
Type in expressions for evaluation. Or try :help.

scala>
```

</details>
## problem

There're 3 problems:
1- The exception thrown.
2- In the interpreter that was opened, when I write any characters I don't see anything written or the cursor moving. However, after pressing `Enter/Return`, the command is executed.
3- The opened interpreter doesn't respond to Ctrl+D or Ctrl+C.

But I understand 2 and 3 may be consequences of 1. So, the issue is about 1.
## expectation

For the exception to not be thrown, and for the REPL to start and work correctly.
## notes
- sbt version: 0.3.12
- Content of the file `C:\Users\<username>\.sbt\0.13\plugins\plugins.sbt` just in case that is relevant:

```
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-M12")
addSbtPlugin("org.ensime" % "sbt-ensime" % "1.0.0")
addSbtPlugin("com.orrsella" % "sbt-sublime" % "1.1.1")
```
- OS: Windows 7 64-bit.
- Although the project is called `hello-world`, it has no source files, only `build.sbt`. And the issue occurred on another ordinary project that has source files and all.
- I'm using the terms REPL and the interpreter interchangeably.

**Comment by eed3si9n** [comment]
I can start `console` fine using Scala 2.11.8.
Could you try without your global plugins please?

**Comment by hossameldeen** [comment]
The problem happens only when coursier plugin is enabled and doesn't happen otherwise. Should've thought of trying that. So, I guess the issue can be considered non-existent for sbt, will contact coursier's developers. Thank you!
