### ISSUE TITLE
Sbt fails to run a project

### ISSUE THREAD

**Issue by gmixa** [sbt/sbt#2729]
(See the guidelines for contributing, linked above)
## steps

checkout https://github.com/bbvSoftwareServices/Jasper-Reports-Java-Demo
it contains an example of the discovered issue.

issue  `sbt run` to execute the the defined test program.

Environment info : sbt 0.13.12 with java 1.8 on a windows 10 machine.
## problem

running of the example program fails

if you use gradle to build and run the same project no such issue shows up.

gradlew run works as expected
## expectation

sbt should behave like the other build tool that was setup

**Comment by dwijnand** [comment]
## minimised case

**project/build.properties**

``` ini
sbt.version=0.13.12
```

**build.sbt**

``` scala
libraryDependencies += "net.sf.jasperreports" % "jasperreports" % "6.3.0"
```

**src/main/java/eu/bbv/Main.java**

``` java
package eu.bbv;

import net.sf.jasperreports.engine.*;

public class Main {
  public static void main(String[] args) throws Exception {
    JasperCompileManager.compileReport("src/main/resources/testReport_A4.jrxml");
  }
}
```

**src/main/resources/TestReport_A4.jrxml**

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<jasperReport xmlns="http://jasperreports.sourceforge.net/jasperreports" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://jasperreports.sourceforge.net/jasperreports http://jasperreports.sourceforge.net/xsd/jasperreport.xsd" name="Blank_A4" pageWidth="595" pageHeight="842" columnWidth="555" leftMargin="20" rightMargin="20" topMargin="20" bottomMargin="20" uuid="79f95990-8bf8-48ea-ba47-cbc7f3ba23de">
        <property name="com.jaspersoft.studio.data.defaultdataadapter" value="New Data Adapter "/>
        <queryString>
                <![CDATA[]]>
        </queryString>
        <field name="Name" class="java.lang.String">
                <fieldDescription><![CDATA[The Name of a person]]></fieldDescription>
        </field>
        <title>
                <band height="81" splitType="Stretch">
                        <image>
                                <reportElement x="0" y="0" width="550" height="81" uuid="7b4e12e5-2bcc-4e84-9f08-c7dfaa9c0ac9"/>
                                <imageExpression><![CDATA["http://www.bbv.eu/templates/bbv2015/images/logo.svg"]]></imageExpression>
                        </image>
                </band>
        </title>
        <columnHeader>
                <band height="30" splitType="Stretch">
                        <staticText>
                                <reportElement x="100" y="0" width="100" height="30" uuid="621e3782-40c5-406a-942b-7730a94d3726"/>
                                <text><![CDATA[Name]]></text>
                        </staticText>
                </band>
        </columnHeader>
        <detail>
                <band height="30" splitType="Stretch">
                        <textField>
                                <reportElement x="100" y="0" width="100" height="30" uuid="540b96e7-d5a4-4768-ba15-edcc1724e4a7"/>
                                <textFieldExpression><![CDATA[$F{Name}]]></textFieldExpression>
                        </textField>
                </band>
        </detail>
</jasperReport>
```

## output

```
net.sf.jasperreports.engine.JRException: Errors were encountered when compiling report expressions class file:
1. The type java.util.Map cannot be resolved. It is indirectly referenced from required .class files
/*
^
2. The type java.lang.Throwable cannot be resolved. It is indirectly referenced from required .class files
/*
^
3. The type java.lang.String cannot be resolved. It is indirectly referenced from required .class files
/*
^
4. The type java.lang.Integer cannot be resolved. It is indirectly referenced from required .class files
/*
^
5. The hierarchy of the type Blank_A4_1472821105683_622565 is inconsistent
public class Blank_A4_1472821105683_622565 extends JREvaluator
             <--------------------------->
6. The type java.lang.Object cannot be resolved. It is indirectly referenced from required .class files
public class Blank_A4_1472821105683_622565 extends JREvaluator
                                                   <--------->
7. Map cannot be resolved to a type
        Map pm,
        <->
8. Map cannot be resolved to a type
        Map fm,
        <->
9. Map cannot be resolved to a type
        Map vm
        <->
10. Map cannot be resolved to a type
    private void initParams(Map pm)
                            <->
11. Map cannot be resolved to a type
    private void initFields(Map fm)
                            <->
12. Map cannot be resolved to a type
    private void initVars(Map vm)
                          <->
13. Object cannot be resolved to a type
    public Object evaluate(int id) throws Throwable
           <---->
14. Throwable cannot be resolved to a type
    public Object evaluate(int id) throws Throwable
                                          <------->
15. Object cannot be resolved to a type
        Object value = null;
        <---->
16. java.lang.Integer cannot be resolved to a type
                value = new java.lang.Integer(1); //$JR_EXPR_ID=0$
                            <--------------->
17. java.lang.Integer cannot be resolved to a type
                value = new java.lang.Integer(1); //$JR_EXPR_ID=1$
                            <--------------->
18. java.lang.Integer cannot be resolved to a type
                value = new java.lang.Integer(1); //$JR_EXPR_ID=2$
                            <--------------->
19. java.lang.Integer cannot be resolved to a type
                value = new java.lang.Integer(0); //$JR_EXPR_ID=3$
                            <--------------->
20. java.lang.Integer cannot be resolved to a type
                value = new java.lang.Integer(1); //$JR_EXPR_ID=4$
                            <--------------->
21. java.lang.Integer cannot be resolved to a type
                value = new java.lang.Integer(0); //$JR_EXPR_ID=5$
                            <--------------->
22. java.lang.Integer cannot be resolved to a type
                value = new java.lang.Integer(1); //$JR_EXPR_ID=6$
                            <--------------->
23. java.lang.Integer cannot be resolved to a type
                value = new java.lang.Integer(0); //$JR_EXPR_ID=7$
                            <--------------->
24. java.lang.String cannot be resolved to a type
                value = ((java.lang.String)field_Name.getValue()); //$JR_EXPR_ID=9$
                          <-------------->
25. The method getValue() from the type JRFillField refers to the missing type Object
                value = ((java.lang.String)field_Name.getValue()); //$JR_EXPR_ID=9$
                                                      <------>
26. Object cannot be resolved to a type
    public Object evaluateOld(int id) throws Throwable
           <---->
27. Throwable cannot be resolved to a type
    public Object evaluateOld(int id) throws Throwable
                                             <------->
28. Object cannot be resolved to a type
        Object value = null;
        <---->
29. java.lang.Integer cannot be resolved to a type
                value = new java.lang.Integer(1); //$JR_EXPR_ID=0$
                            <--------------->
30. java.lang.Integer cannot be resolved to a type
                value = new java.lang.Integer(1); //$JR_EXPR_ID=1$
                            <--------------->
31. java.lang.Integer cannot be resolved to a type
                value = new java.lang.Integer(1); //$JR_EXPR_ID=2$
                            <--------------->
32. java.lang.Integer cannot be resolved to a type
                value = new java.lang.Integer(0); //$JR_EXPR_ID=3$
                            <--------------->
33. java.lang.Integer cannot be resolved to a type
                value = new java.lang.Integer(1); //$JR_EXPR_ID=4$
                            <--------------->
34. java.lang.Integer cannot be resolved to a type
                value = new java.lang.Integer(0); //$JR_EXPR_ID=5$
                            <--------------->
35. java.lang.Integer cannot be resolved to a type
                value = new java.lang.Integer(1); //$JR_EXPR_ID=6$
                            <--------------->
36. java.lang.Integer cannot be resolved to a type
                value = new java.lang.Integer(0); //$JR_EXPR_ID=7$
                            <--------------->
37. java.lang.String cannot be resolved to a type
                value = ((java.lang.String)field_Name.getOldValue()); //$JR_EXPR_ID=9$
                          <-------------->
38. The method getOldValue() from the type JRFillField refers to the missing type Object
                value = ((java.lang.String)field_Name.getOldValue()); //$JR_EXPR_ID=9$
                                                      <--------->
39. Object cannot be resolved to a type
    public Object evaluateEstimated(int id) throws Throwable
           <---->
40. Throwable cannot be resolved to a type
    public Object evaluateEstimated(int id) throws Throwable
                                                   <------->
41. Object cannot be resolved to a type
        Object value = null;
        <---->
42. java.lang.Integer cannot be resolved to a type
                value = new java.lang.Integer(1); //$JR_EXPR_ID=0$
                            <--------------->
43. java.lang.Integer cannot be resolved to a type
                value = new java.lang.Integer(1); //$JR_EXPR_ID=1$
                            <--------------->
44. java.lang.Integer cannot be resolved to a type
                value = new java.lang.Integer(1); //$JR_EXPR_ID=2$
                            <--------------->
45. java.lang.Integer cannot be resolved to a type
                value = new java.lang.Integer(0); //$JR_EXPR_ID=3$
                            <--------------->
46. java.lang.Integer cannot be resolved to a type
                value = new java.lang.Integer(1); //$JR_EXPR_ID=4$
                            <--------------->
47. java.lang.Integer cannot be resolved to a type
                value = new java.lang.Integer(0); //$JR_EXPR_ID=5$
                            <--------------->
48. java.lang.Integer cannot be resolved to a type
                value = new java.lang.Integer(1); //$JR_EXPR_ID=6$
                            <--------------->
49. java.lang.Integer cannot be resolved to a type
                value = new java.lang.Integer(0); //$JR_EXPR_ID=7$
                            <--------------->
50. java.lang.String cannot be resolved to a type
                value = ((java.lang.String)field_Name.getValue()); //$JR_EXPR_ID=9$
                          <-------------->
51. The method getValue() from the type JRFillField refers to the missing type Object
                value = ((java.lang.String)field_Name.getValue()); //$JR_EXPR_ID=9$
                                                      <------>
51 errors
.
        at net.sf.jasperreports.engine.design.JRAbstractCompiler.compileReport(JRAbstractCompiler.java:206)
        at net.sf.jasperreports.engine.JasperCompileManager.compile(JasperCompileManager.java:357)
        at net.sf.jasperreports.engine.JasperCompileManager.compile(JasperCompileManager.java:290)
        at net.sf.jasperreports.engine.JasperCompileManager.compileReport(JasperCompileManager.java:575)
        at eu.bbv.Main.main(Main.java:7)
```

**Comment by dwijnand** [comment]
@gmixa You need to set `fork in run := true`. Credit to @pfn.
