### ISSUE TITLE
updateClassifiers does not include scala-library source

### ISSUE THREAD

**Issue by julienrf** [sbt/sbt#2751]
## steps

``` sh
git clone git@github.com:scala-js/scala-js.git
cd scala-js
sbt library/package
```
## problem

`updateClassifiers` does not include `scala-library`’s sources.

```
java.lang.RuntimeException: Could not fetch scala-library sources for version 2.11.8
        at scala.sys.package$.error(package.scala:27)
        at Build$$anonfun$scalalib$1$$anonfun$apply$78$$anonfun$55.apply(Build.scala:851)
        at Build$$anonfun$scalalib$1$$anonfun$apply$78$$anonfun$55.apply(Build.scala:851)
        at scala.Option.getOrElse(Option.scala:120)
        at Build$$anonfun$scalalib$1$$anonfun$apply$78.apply(Build.scala:850)
        at Build$$anonfun$scalalib$1$$anonfun$apply$78.apply(Build.scala:840)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (scalalib/*:fetchScalaSource) Could not fetch scala-library sources for version 2.11.8
```
## expectation

```
[success] Total time: 52 s, completed Sep 22, 2016 2:38:59 PM
```
## notes

On my colleague’s machine it works. Some information on my configuration:

``` sh
$ dpkg-query -l sbt
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                              Version                       Architecture                  Description
+++-=================================================-=============================-=============================-=======================================================================================================
ii  sbt                                               0.13.12                       all                           sbt, the interactive build tool
```

``` sh
$ ls -al ~/.sbt/0.13
total 24
drwxrwxr-x 4 julien julien 4096 Aug 12 22:11 .
drwxr-xr-x 5 julien julien 4096 Aug 12 22:17 ..
-rw-rw-r-- 1 julien julien  133 Aug 12 22:10 sonatype_credentials.sbt
drwxrwxr-x 2 julien julien 4096 Jul 15 14:27 staging
drwxrwxr-x 3 julien julien 4096 Aug 12 22:11 target
```

**Comment by dwijnand** [comment]
I can't reproduce it, sadly.

For the record, the current HEAD of scala-js is e939ae5b98c88fc85730c02765f0187c11bcc800

**Comment by julienrf** [comment]
I think the hardest part in solving this issue is to find how to reproduce it. What additional information about my environment could help?

**Comment by dwijnand** [comment]
I'm not sure..

Pinging @sjrd who authored the `updateClassifier` section of `fetchScalaSource`, in case he might have any ideas or perhaps has seen others hit this issue.

**Comment by sjrd** [comment]
@dwijnand "My colleague" was referring to me (I think).

I've looked at the issue on @julienrf's machine, and I couldn't figure out what was wrong. Lots of people have cloned and built successfully Scala.js for a long time, and it's the first time I've seen this happening :(

**Comment by dwijnand** [comment]
Close as WFEE? (works for everyone else) :-P

Hmm, this is tricky, but I might be looking at `updateClassifiers` at some point, so I'll keep this in mind.
