### ISSUE TITLE
intermittent download failure from Bintray-backed repositories (JCenter, repo.typesafe.com, etc)

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#2758]
We are seeing on Travis CI and Jenkins job that sbt artifacts download is failing.

**Comment by dwijnand** [comment]
It might be Bintray, not us: https://twitter.com/cvogt/status/781147096569245696

**Comment by eed3si9n** [comment]
Yea, the proxy machine has low CPU utilization, so I won't be surprised if it's caused by instability of Bintray. But regardless of the backend if we're failing to deliver the bits, it's on us.

Here's from a recent Travis failure: https://gist.github.com/eed3si9n/f77c354e5f1c3a6a5ad58dccc4e8f977

```
        [FAILED     ] org.scala-sbt#main;0.13.11!main.jar: The HTTP response code for https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main/0.13.11/jars/main.jar did not indicate a success. See log for more detail. (333ms)

        [FAILED     ] org.scala-sbt#main;0.13.11!main.jar: The HTTP response code for https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main/0.13.11/jars/main.jar did not indicate a success. See log for more detail. (333ms)
```

**Comment by virusdave** [comment]
In case this helps, artifacts for me are actually fully reachable when following the redirect chain.

```
$ wget -v 'https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/incremental-compiler/0.13.11/jars/incremental-compiler.jar'
--2016-09-28 13:32:31--  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/incremental-compiler/0.13.11/jars/incremental-compiler.jar
Resolving repo.typesafe.com... 54.165.237.90, 52.203.61.63
Connecting to repo.typesafe.com|54.165.237.90|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/incremental-compiler/0.13.11/jars/incremental-compiler.jar [following]
--2016-09-28 13:32:31--  https://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/incremental-compiler/0.13.11/jars/incremental-compiler.jar
Resolving dl.bintray.com... 54.148.190.237, 52.25.112.156
Connecting to dl.bintray.com|54.148.190.237|:443... connected.
HTTP request sent, awaiting response... 302 
Location: http://akamai.bintray.com/43/436b659f597f99d90ec9d651a6299aceccba1f723696c194213486a87d68b003?__gda__=exp=1475084670~hmac=c2546ecf23f3ac54d47e4a42c867d2c0cd140d039bcd1456741ae1b7c833e870&response-content-disposition=attachment%3Bfilename%3D%22incremental-compiler.jar%22&response-content-type=application%2Fjava-archive&requestInfo=U2FsdGVkX183Z8ZKhxDNhIJB3h6Dwz06chcMr4KKHn5YbikQY_YFrc8fwCBzrPe0rY2jVblSkac339PwgXwEfPdl1NnnZ_f8MnYr-tgukpCyW6ovgxLoU5Wbe4-jqYqYWmd-BysFFA6IKiQSE5muTVbTWqtR0xowsHPuR1qAdiU [following]
--2016-09-28 13:32:34--  http://akamai.bintray.com/43/436b659f597f99d90ec9d651a6299aceccba1f723696c194213486a87d68b003?__gda__=exp=1475084670~hmac=c2546ecf23f3ac54d47e4a42c867d2c0cd140d039bcd1456741ae1b7c833e870&response-content-disposition=attachment%3Bfilename%3D%22incremental-compiler.jar%22&response-content-type=application%2Fjava-archive&requestInfo=U2FsdGVkX183Z8ZKhxDNhIJB3h6Dwz06chcMr4KKHn5YbikQY_YFrc8fwCBzrPe0rY2jVblSkac339PwgXwEfPdl1NnnZ_f8MnYr-tgukpCyW6ovgxLoU5Wbe4-jqYqYWmd-BysFFA6IKiQSE5muTVbTWqtR0xowsHPuR1qAdiU
Resolving akamai.bintray.com... 104.107.5.123
Connecting to akamai.bintray.com|104.107.5.123|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 490708 (479K) [application/java-archive]
Saving to: 'incremental-compiler.jar'

incremental-compiler.jar                                        100%[====================================================================================================================================================>] 479.21K  --.-KB/s    in 0.1s    

```

SBT, however, can't seem to get it:

```
[info] downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/incremental-compiler/0.13.11/jars/incremental-compiler.jar ...
[debug]         typesafe-ivy-releases: downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/incremental-compiler/0.13.11/jars/incremental-compiler.jar
[warn]  [FAILED     ] org.scala-sbt#incremental-compiler;0.13.11!incremental-compiler.jar: The HTTP response code for https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/incremental-compiler/0.13.11/jars/incremental-compiler.jar did not indica
te a success. See log for more detail. (900ms)
[warn]  [FAILED     ] org.scala-sbt#incremental-compiler;0.13.11!incremental-compiler.jar: The HTTP response code for https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/incremental-compiler/0.13.11/jars/incremental-compiler.jar did not indica
te a success. See log for more detail. (900ms)
```

Is there a limit on number of redirects being followed?

**Comment by virusdave** [comment]
Or possibly the redirect from https to http?

**Comment by eed3si9n** [comment]
@virusdave I am not sure if that explains the intermittent nature of the failure.

**Comment by virusdave** [comment]
fair enough.  I don't see it being intermittent on my end though - seems to pretty consistently fail in sbt and always succeeds w/ wget.

**Comment by kstokoz** [comment]
Our CI cannot resolve artifacts as well.

**Comment by gzoller** [comment]
Piling on... I saw the same start 2-3 days ago where Travis started failing to resolve sbt/Scala artifacts.   I haven't looked 1-by-1 but a cursory scan shows they do seem to come from Bintray.  Strangely I have none of these issues locally.  I can clear my .ivy cache and build from nothing--all the dependencies resolve and download and artifact builds.  Odd, indeed.

EDIT--Ok, so now my local builds are failing to resolve in the same way.  Locally anyway my failures were from repo.typesafe.com/

**Comment by kpmeen** [comment]
I'm experiencing the same problems on Shippable as well. And in a docker image that I build on docker hub to be pre-loaded with SBT. Started becoming problematic a day or two ago. Now it's constantly failing. And as @gzoller mentions, I can't reproduce it locally.

**Comment by ahirreddy** [comment]
I'm seeing invalid/empty jars returned by resolution, polluting my cache:

```
[error] error while loading <root>, zip file is empty
scala.reflect.internal.MissingRequirementError: object scala.runtime in compiler mirror not found.
    at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:16)
    at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:17)
    at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:48)
    at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:40)
    at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:61)
    at scala.reflect.internal.Mirrors$RootsBase.getPackage(Mirrors.scala:172)
    at scala.reflect.internal.Mirrors$RootsBase.getRequiredPackage(Mirrors.scala:175)
    at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackage$lzycompute(Definitions.scala:183)
    at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackage(Definitions.scala:183)
    at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackageClass$lzycompute(Definitions.scala:184)
    at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackageClass(Definitions.scala:184)
    at scala.reflect.internal.Definitions$DefinitionsClass.AnnotationDefaultAttr$lzycompute(Definitions.scala:1024)
    at scala.reflect.internal.Definitions$DefinitionsClass.AnnotationDefaultAttr(Definitions.scala:1023)
    at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreClasses$lzycompute(Definitions.scala:1153)
    at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreClasses(Definitions.scala:1152)
    at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode$lzycompute(Definitions.scala:1196)
    at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode(Definitions.scala:1196)
    at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1261)
    at scala.tools.nsc.Global$Run.<init>(Global.scala:1290)
    at xsbt.CachedCompiler0$$anon$2.<init>(CompilerInterface.scala:106)
    at xsbt.CachedCompiler0.run(CompilerInterface.scala:106)
    at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
    at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
    at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
    at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:41)
    at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:50)
    at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
    at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
    at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:74)
    at sbt.compiler.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:49)
    at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:64)
    at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
    at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
    at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
    at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
    at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:32)
    at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:68)
    at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:67)
    at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:95)
    at sbt.inc.Incremental$.compile(Incremental.scala:67)
    at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
    at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
    at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
    at sbt.Compiler$.compile(Compiler.scala:152)
    at sbt.Compiler$.compile(Compiler.scala:138)
    at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:860)
    at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:851)
    at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:849)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] (compile:compileIncremental) scala.reflect.internal.MissingRequirementError: object scala.runtime in compiler mirror not found.
```

**Comment by JoshRosen** [comment]
In the long run, I would love to see these SBT artifacts published to Maven Central. Maven Central is reliable and is widely mirrored/cached, so publishing there will help to insulate users from repository downtime issues.

This isn't the first time that the Typesafe repository has gone down or served corrupt files: [search Twitter for "typesafe repo down"](https://twitter.com/search?q=typesafe%20repo%20down&src=typd) and you'll find tweets going back a few years which mention builds being broken by outages from the Typesafe repository (see also #392, #751, #1690, #2004, just to name a few).

It seems like this entire category of issues could be avoided if the artifacts were also published to Maven Central.

**Comment by dwijnand** [comment]
The plan for 1.0 is to publish to Maven Central.

**Comment by dwijnand** [comment]
By "plan" I don't mean "something we're considering", it's already ready and working: http://search.maven.org/#search|gav|1|g:"org.scala-sbt"%20AND%20a:"sbt%22

**Comment by JoshRosen** [comment]
What about the SBT 0.13.x artifacts? While I realize that the older versions' builds might have not been configured to publish to Maven Central, I believe that the existing JARs from the Typesafe repo could be published with a manually-created POM and manual GPG signing.

This would be ideal because it would give 0.13.x users the benefit of a more stable repository without requiring them to upgrade their builds or configure new resolvers.

**Comment by mf-collinhayden** [comment]
Same issue here, we are getting failures on compilation due to download failures from sbt repo.  We are using 0.3.11 in our properties file, I also tried 0.3.12 and that didn't help.  Sometimes it works and sometimes it doesn't.

Do you guys have a fix for the redirect 302 issue not being handled.  What do you suggest for a short-term fix

**Comment by yhuai** [comment]
It is great to see that 1.0 artifact has been published. But, it will be great if 0.13.x artifacts are published to maven central. So, those 0.13.x users will have a more stable build environment.

**Comment by ahirreddy** [comment]
I agree with @JoshRosen. I couldn't compile ScalaFMT today because I ended up with corrupted jars in my ivy cache. It's not just the issue of updating my own projects, basically every utility in the Scala community is afflicted with this issue. Also, given that SBT 1.0 introduces a number of breaking changes, it will be some time before the long tail of projects can migrate their builds.

**Comment by jeffsteinmetz** [comment]
Its looks to be a 0.13.2 artifact download issue (unrelated to any CI tool, cache, etc)

At 8:21 PDT, Sept 28 2016, I fired up a fresh Ubuntu 14.04 image on Amazon AWS, installed nothing but Java 7, then installed sbt-launcher.jar direct from 
http://www.scala-sbt.org/
manually created an sbt bash as shown in manual steps.

several failures:
`The HTTP response code for https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main/0.13.12/jars/main.jar did not indicate a success`

`The HTTP response code for https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-interface/0.13.12/jars/compiler-interface.jar`

etc...

**Comment by eed3si9n** [comment]
Around 0:30 Eastern September 29, 2016 I followed the steps to create an EC2 instance on us-east-1a with ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-20160627 (ami-2d39803a), and I was able to start sbt fine.
https://gist.github.com/eed3si9n/c4221d212f6d818d7c426349751cc6bf

**Comment by huntc** [comment]
In case it helps, our CI infrastructure is reporting jcenter download issues:

```
[warn]  [FAILED     ] org.openjdk.jmh#jmh-core;1.6!jmh-core.jar: The HTTP response code for https://jcenter.bintray.com/org/openjdk/jmh/jmh-core/1.6/jmh-core-1.6.jar did not indicate a success. See log for more detail. (351ms)
[warn]  [FAILED     ] org.apache.commons#commons-math3;3.2!commons-math3.jar: The HTTP response code for https://jcenter.bintray.com/org/apache/commons/commons-math3/3.2/commons-math3-3.2.jar did not indicate a success. See log for more detail. (148ms)
```

These are indeed causing our builds to fail.

**Comment by ralph-tice** [comment]
Is there any good reason why the dependencies aren't made available via an assembly-type uber jar, or individually within the rpm/deb artifacts being distributed?

Also, the community should be encouraged not to redownload the entire world on every build -- we need to do a better job of helping each other build the appropriate pass through caches.  Right now most of the best options are paid vendor software which is kind of ridiculous and everyone using docker or other containers they blow away every commit is, I'm sure, having a huge impact.

Travis and Circle would both save a lot of bandwidth if they ran mirrors.  I've saved money for my org by using Artifactory as a pass through cache but in my OSS work I'm without an easy recourse...

EDIT: Looks like things are back to operating as normal for me as of ~12:20AM Central time, locally from Central US and via AWS us-east-1...  Also, I hope this reads more as "how can I help" than "this is bad and we should feel bad", it's late 🌝

**Comment by eed3si9n** [comment]
I've initially reported it as repo.typesafe.com failing to serve sbt artifacts, but it seems to be any artifact served from any Bintray-backed repositories including JCenter and repo.scala-sbt.org, which hosts sbt plugins. Any solution specific to solving just the sbt download is not going to solve the larger issue.

**Comment by ralph-tice** [comment]
The best idea I've thought of so far was making a docker container that acted as a pre-warmed cache for dependencies, but that led me towards Apache Archiva and my faith and resolve wavered.

**Comment by ahirreddy** [comment]
I'll reiterate what @JoshRosen already mentioned

> Maven Central is reliable and is widely mirrored/cached, so publishing there will help to insulate users from repository downtime issues.

You can side step most of the described issues by publishing to Maven central

**Comment by eed3si9n** [comment]
@huntc guessed redirection between HTTPS to HTTP as the cause, which is considered insecure and not implemented by `HttpURLConnection`. And he seems to be right.

Here's the curl log - https://gist.github.com/eed3si9n/0f45d3fc0ea1527c03726406a6eb5451

```
$ curl -vL https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-interface/0.13.12/jars/compiler-interface.jar > /dev/null
....
< HTTP/1.1 302 Moved Temporarily
< Content-Type: text/html
< Date: Thu, 29 Sep 2016 06:46:56 GMT
< Location: https://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/compiler-interface/0.13.12/jars/compiler-interface.jar
....
< HTTP/1.1 302
* Server nginx is not blacklisted
< Server: nginx
< Date: Thu, 29 Sep 2016 06:47:33 GMT
< Content-Length: 0
< Connection: keep-alive
< Location: http://akamai.bintray.com/29/29a919a09e5836eb79f860eea342c00fd54a05c8c5141a13a87c9cf65b90faf7?__gda__=exp=1475132373~hmac=37c1508799ae28e734c70419aebcc13d7ef57b2564890e5aefcfd9cd2b23af44&response-content-disposition=attachment%3Bfilename%3D%22compiler-interface.jar%22&response-content-type=application%2Fjava-archive&requestInfo=U2FsdGVkX1-jyHm8trPgH_TS_sFucdtjLU4Hkx7gzGLpp0iEL41Udtzi5sVziLb-3HdVAz3fSBXfbPAkA86HjfqsZOQ-WfljkRZU7JKor87YiGPTza62zESn6aj2Kn6ivhKVg_fB4PsiFr6vR4VinPpOzGgGfyLXkcxBM1UmcVk
```

http://akamai.bintray.com is on HTTP.

**Comment by eed3si9n** [comment]
The redirect issue was identified and resolved at Bintray, so hopefully this should now work.
If there are any further issues, feel free to comment here.

Thanks all for the patience.

**Comment by mkotsbak** [comment]
Ah, that is why I had so much trobles.

**Comment by msillence** [comment]
We are seeing 304 issues again on bintray https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/command/0.13.13/jars/command.jar

I've raised a ticket: #62085 with jfrog

**Comment by msillence** [comment]
seems to have been resolved

**Comment by schlichtanders** [comment]
I still seem to get this error... when trying to run Intellij Idea sbt-shell the first time
```
[info] downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.jetbrains/sbt-idea-shell/scala_2.10/sbt_0.13/2017.2/jars/sbt-idea-shell.jar ...
[warn]  [FAILED     ] org.jetbrains#sbt-idea-shell;2017.2!sbt-idea-shell.jar: The HTTP response code for https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.jetbrains/sbt-idea-shell/scala_2.10/sbt_0.13/2017.2/jars/sbt-idea-shell.jar did not indicate a success. See log for more detail. (2408ms)
[warn]  [FAILED     ] org.jetbrains#sbt-idea-shell;2017.2!sbt-idea-shell.jar:  (0ms)
```
When using curl -vL I see that there is a 302 moved temporarily return value in between

**Comment by schlichtanders** [comment]
my sbt version is 0.13.16

**Comment by schlichtanders** [comment]
I just see, that this might also be related to #2679 as this is a jar-download and I am indeed sitting behind a proxy
