### ISSUE TITLE
sbt run fails in this trivial example

### ISSUE THREAD

**Issue by dportabella** [sbt/sbt#2824]
This is a minimal example to show a very weird thing when using `sbt run`

build.sbt
```
name := "testsbt"

version := "1.0"

scalaVersion := "2.11.8"
```    

project/build.properties
```    
sbt.version = 0.13.13
```    

src/main/scala/application/Test.scala
```    
package application

import java.io._

case class Page(items: List[Item])
case class Item(text: String)

object Test extends App {
    val page = Page(List(Item("item1")))

    val filename = "./page.obj"

    val oos = new ObjectOutputStream(new FileOutputStream(filename))
    try oos.writeObject(page)
    finally oos.close()

    println("read: " + new ObjectInputStream(new FileInputStream(filename)).readObject())
}
```    

executing this with sbt run fails:
```    
$ sbt run 
[error] (run-main-0) java.lang.ClassCastException: cannot assign instance of scala.collection.immutable.List$SerializationProxy to field application.Page.items of type scala.collection.immutable.List in instance of application.Page
```    

however, executing sbt package and running from it works:
```
$ sbt package
$ scala -cp target/scala-2.11/testsbt_2.11-1.0.jar application.Test
read: Page(List(Item(item1)))
```

**Comment by dportabella** [comment]
it seems related to https://issues.apache.org/jira/browse/SPARK-9219

**Comment by ryan-williams** [comment]
Seeing this now, and [made a repro here](https://github.com/ryan-williams/scalac-bug/tree/serde) very similar to the one above.

- `mvn test` succeeds
- `sbt package && scala <jar>` succeeds
- `sbt test` fails
- `sbt run` fails
- `sbt console` and calling the `main()` function (`org.Serde.main(Array())`) fails

Something about running under SBT is breaking Java serialization/deserialization, at least for `List.SerializationProxy`, in all versions of SBT x Scala. 

I even ran it with the same classpath, via `scala` and `sbt`, and still see it. Very  mysterious.

Here's the repro fwiw:

```scala
import java.io._

case class A(s: String)
case class B(as: List[A])  // changing List to any other collection seems to work: Vector, ArrayBuffer, Array

object Serde {
  def serialize(o: Object): Array[Byte] = {
    val baos = new ByteArrayOutputStream()
    val oos = new ObjectOutputStream(baos)
    oos.writeObject(o)
    oos.close()
    baos.toByteArray
  }

  def deserialize[T](bytes: Array[Byte]): T = {
    val ois = new ObjectInputStream(new ByteArrayInputStream(bytes))
    try {
      ois.readObject().asInstanceOf[T]
    } finally {
      ois.close()
    }
  }

  def main(args: Array[String]): Unit = {
    val b = B(List(A("abc"), A("def")))
    val b2 = deserialize[B](serialize(b))  // fails
    println(b2)
  }
}
```

Stack trace:

```
[error] java.lang.ClassCastException: cannot assign instance of scala.collection.immutable.List$SerializationProxy to field org.B.as of type scala.collection.immutable.List in instance of org.B
[error]      at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2133)
[error]      at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1305)
[error]      at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2024)
[error]      at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
[error]      at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
[error]      at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
[error]      at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
[error]      at org.Serde$.deserialize(Serde.scala:20)
[error]      at org.Serde$.main(Serde.scala:28)
[error]      at org.Serde.main(Serde.scala)
[error]      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]      at java.lang.reflect.Method.invoke(Method.java:498)
[error]      at sbt.Run.invokeMain(Run.scala:89)
[error]      at sbt.Run.run0(Run.scala:83)
[error]      at sbt.Run.execute$1(Run.scala:61)
[error]      at sbt.Run.$anonfun$run$4(Run.scala:73)
[error]      at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]      at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error]      at sbt.TrapExit$App.run(TrapExit.scala:252)
[error]      at java.lang.Thread.run(Thread.java:745)
```

**Comment by ryan-williams** [comment]
@eed3si9n [suggested `fork := true`](https://gitter.im/sbt/sbt?at=59b1c89eb16f26464218d793) which works around it

it seems that `List.SerializationProxy`'s `readResolve` method is not getting picked up in the deserialization step, and the `List` field is attempting to get the proxy object assigned to it.

**Comment by ritschwumm** [comment]
does this disppear with `fork in run := true`?

i'd guess this is some kind of classloader issue - as if List$SerializationProxy#readResolve were never called, but why?

**Comment by eed3si9n** [comment]
This is a speculation but, sbt loads Scala stuff on its own classloader, and that might be confusing the serialization which might be expecting everything to be under the same classloader.

See also https://gist.github.com/retronym/5eba5edabca36fc0b917b5f0095ce990

**Comment by eed3si9n** [comment]
I am going to close this with wontfix.

**Comment by devshorts** [comment]
~@eed3si9n are there any workarounds to this? I have tests that I want to verify serialize and deserialize properly, but I can't run them in sbt due to this. SBT runs in `fork in test := true` but I still get this error.~

Nevermind, I needed `fork in Test := true` not just `fork in test := true`
