### ISSUE TITLE
org.scala-sbt#sbt;0.13.13: not found

### ISSUE THREAD

**Issue by 7kemZmani** [sbt/sbt#2836]
## steps
1 - Downloaded the .tgz archive for sbt from [here](http://www.scala-sbt.org/download.html)
2 - Extracted the archive, and placed its content in ~/SBT directory
3 - Set SBT_HOME variable to $HOME/SBT/bin
4 - Followed all the Hello, World instructions [here](http://www.scala-sbt.org/0.12.4/docs/Getting-Started/Hello.html)

## problem
when I run sbt in the same directory where hw.scala is, I get the following error:

```
> setting 'ivy.default.settings.dir' to 'jar:file:/home/ME/SBT/bin/sbt-launch.jar!/org/apache/ivy/core/settings'
setting 'ivy.basedir' to '/home/ME/.sbt/boot/.'
setting 'ivy.default.conf.dir' to 'jar:file:/home/ME/SBT/bin/sbt-launch.jar!/org/apache/ivy/core/settings'
impossible to define new type: class not found: org.apache.ivy.plugins.resolver.SshResolver in [] nor Ivy classloader
impossible to define new type: class not found: org.apache.ivy.plugins.resolver.VsftpResolver in [] nor Ivy classloader
impossible to define new type: class not found: org.apache.ivy.plugins.version.PatternVersionMatcher in [] nor Ivy classloader
impossible to define new type: class not found: org.apache.ivy.plugins.trigger.LogTrigger in [] nor Ivy classloader
impossible to define new type: class not found: org.apache.ivy.ant.AntBuildTrigger in [] nor Ivy classloader
impossible to define new type: class not found: org.apache.ivy.plugins.resolver.IvyRepResolver in [] nor Ivy classloader
impossible to define new type: class not found: org.apache.ivy.plugins.signer.bouncycastle.OpenPGPSignatureGenerator in [] nor Ivy classloader
impossible to define new type: class not found: org.apache.ivy.plugins.conflict.RegexpConflictManager in [] nor Ivy classloader
impossible to define new type: class not found: org.apache.ivy.plugins.resolver.SFTPResolver in [] nor Ivy classloader
impossible to define new type: class not found: org.apache.ivy.osgi.updatesite.UpdateSiteResolver in [] nor Ivy classloader
impossible to define new type: class not found: org.apache.ivy.ant.AntCallTrigger in [] nor Ivy classloader
impossible to define new type: class not found: org.apache.ivy.plugins.resolver.MirroredURLResolver in [] nor Ivy classloader
impossible to define new type: class not found: org.apache.ivy.plugins.resolver.packager.PackagerResolver in [] nor Ivy classloader
impossible to define new type: class not found: org.apache.ivy.plugins.resolver.DualResolver in [] nor Ivy classloader
impossible to define new type: class not found: org.apache.ivy.plugins.resolver.VfsResolver in [] nor Ivy classloader
impossible to define new type: class not found: org.apache.ivy.plugins.resolver.JarResolver in [] nor Ivy classloader
impossible to define new type: class not found: org.apache.ivy.osgi.obr.OBRResolver in [] nor Ivy classloader
impossible to define glob matcher: org.apache.ivy.plugins.matcher.GlobPatternMatcher was not found.
setting 'jline.esc.timeout' to '0'
setting 'java.runtime.name' to 'Java(TM) SE Runtime Environment'
setting 'sun.boot.library.path' to '/usr/java/jdk1.8.0_112/jre/lib/amd64'
setting 'java.vm.version' to '25.112-b15'
setting 'java.vm.vendor' to 'Oracle Corporation'
setting 'java.vendor.url' to 'http://java.oracle.com/'
setting 'path.separator' to ':'
setting 'java.vm.name' to 'Java HotSpot(TM) 64-Bit Server VM'
setting 'file.encoding.pkg' to 'sun.io'
setting 'user.country' to 'CA'
setting 'sun.java.launcher' to 'SUN_STANDARD'
setting 'sun.os.patch.level' to 'unknown'
setting 'java.vm.specification.name' to 'Java Virtual Machine Specification'
setting 'user.dir' to '/home/ME/.sbt/boot'
setting 'java.runtime.version' to '1.8.0_112-b15'
setting 'java.awt.graphicsenv' to 'sun.awt.X11GraphicsEnvironment'
setting 'java.endorsed.dirs' to '/usr/java/jdk1.8.0_112/jre/lib/endorsed'
setting 'os.arch' to 'amd64'
setting 'java.io.tmpdir' to '/tmp'
setting 'line.separator' to '
'
setting 'java.vm.specification.vendor' to 'Oracle Corporation'
setting 'os.name' to 'Linux'
setting 'sun.jnu.encoding' to 'UTF-8'
setting 'java.library.path' to '/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib'
setting 'java.specification.name' to 'Java Platform API Specification'
setting 'java.class.version' to '52.0'
setting 'sun.management.compiler' to 'HotSpot 64-Bit Tiered Compilers'
setting 'os.version' to '4.8.6-201.fc24.x86_64'
setting 'user.home' to '/home/ME'
setting 'user.timezone' to ''
setting 'java.awt.printerjob' to 'sun.print.PSPrinterJob'
setting 'file.encoding' to 'UTF-8'
setting 'java.specification.version' to '1.8'
setting 'java.class.path' to '/home/ME/SBT/bin/sbt-launch.jar'
setting 'user.name' to 'ME'
setting 'jline.shutdownhook' to 'false'
setting 'java.vm.specification.version' to '1.8'
setting 'sun.java.command' to '/home/ME/SBT/bin/sbt-launch.jar'
setting 'java.home' to '/usr/java/jdk1.8.0_112/jre'
setting 'sun.arch.data.model' to '64'
setting 'user.language' to 'en'
setting 'java.specification.vendor' to 'Oracle Corporation'
setting 'awt.toolkit' to 'sun.awt.X11.XToolkit'
setting 'java.vm.info' to 'mixed mode'
setting 'java.version' to '1.8.0_112'
setting 'java.ext.dirs' to '/usr/java/jdk1.8.0_112/jre/lib/ext:/usr/java/packages/lib/ext'
setting 'sun.boot.class.path' to '/usr/java/jdk1.8.0_112/jre/lib/resources.jar:/usr/java/jdk1.8.0_112/jre/lib/rt.jar:/usr/java/jdk1.8.0_112/jre/lib/sunrsasign.jar:/usr/java/jdk1.8.0_112/jre/lib/jsse.jar:/usr/java/jdk1.8.0_112/jre/lib/jce.jar:/usr/java/jdk1.8.0_112/jre/lib/charsets.jar:/usr/java/jdk1.8.0_112/jre/lib/jfr.jar:/usr/java/jdk1.8.0_112/jre/classes'
setting 'java.vendor' to 'Oracle Corporation'
setting 'file.separator' to '/'
setting 'java.vendor.url.bug' to 'http://bugreport.sun.com/bugreport/'
setting 'sun.io.unicode.encoding' to 'UnicodeLittle'
setting 'sun.cpu.endian' to 'little'
setting 'sun.desktop' to 'gnome'
setting 'sun.cpu.isalist' to ''
setting 'ivy.default.ivy.user.dir' to '/home/ME/.ivy2'
setting 'ivy.home' to '/home/ME/.ivy2'
setting 'ivy.cache.dir' to '/home/ME/.ivy2/cache'
no default cache defined: set to /home/ME/.ivy2/cache
setting 'ivy.checksums' to 'sha1,md5'
setting 'ivy.basedir' to '/home/ME/.sbt/boot'
setting 'basedir' to '/home/ME/.sbt/boot'
:: resolving dependencies :: org.scala-sbt#boot-app;1.0
	confs: [default]
	validate = true
	refresh = false
resolving dependencies for configuration 'default'
== resolving dependencies for org.scala-sbt#boot-app;1.0 [default]
loadData of org.scala-sbt#boot-app;1.0 of rootConf=default
== resolving dependencies org.scala-sbt#boot-app;1.0->org.scala-sbt#sbt;0.13.13 [default->default(compile)]
loadData of org.scala-sbt#sbt;0.13.13 of rootConf=default
	using redefined-public to resolve org.scala-sbt#sbt;0.13.13
redefined-public: Checking cache for: dependency: org.scala-sbt#sbt;0.13.13 {default=[default(compile)]}
redefined-public: no namespace defined: using system
	no ivy file in cache for org.scala-sbt#sbt;0.13.13: tried /home/ME/.ivy2/cache/org.scala-sbt/sbt/ivy-0.13.13.xml
redefined-public: no latest strategy defined: using default
local: no namespace defined: using system
	no ivy file in cache for org.scala-sbt#sbt;0.13.13: tried /home/ME/.ivy2/cache/org.scala-sbt/sbt/ivy-0.13.13.xml
	 trying /home/ME/.ivy2/local/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml
		tried /home/ME/.ivy2/local/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml
	local: resource not reachable for org.scala-sbt#sbt;0.13.13: res=/home/ME/.ivy2/local/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml
	 trying /home/ME/.ivy2/local/org.scala-sbt/sbt/0.13.13/jars/sbt.jar
		tried /home/ME/.ivy2/local/org.scala-sbt/sbt/0.13.13/jars/sbt.jar
	local: resource not reachable for org.scala-sbt#sbt;0.13.13: res=/home/ME/.ivy2/local/org.scala-sbt/sbt/0.13.13/jars/sbt.jar
	local: no ivy file nor artifact found for org.scala-sbt#sbt;0.13.13
Maven Central: no namespace defined: using system
	no ivy file in cache for org.scala-sbt#sbt;0.13.13: tried /home/ME/.ivy2/cache/org.scala-sbt/sbt/ivy-0.13.13.xml
	 trying https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.13/sbt-0.13.13.pom
		tried https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.13/sbt-0.13.13.pom
ERROR: Server access Error: RSA premaster secret error url=https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.13/sbt-0.13.13.pom
	Maven Central: resource not reachable for org/scala-sbt#sbt;0.13.13: res=https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.13/sbt-0.13.13.pom
	 trying https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.13/sbt-0.13.13.jar
		tried https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.13/sbt-0.13.13.jar
ERROR: Server access Error: RSA premaster secret error url=https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.13/sbt-0.13.13.jar
	Maven Central: resource not reachable for org/scala-sbt#sbt;0.13.13: res=https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.13/sbt-0.13.13.jar
	Maven Central: no ivy file nor artifact found for org.scala-sbt#sbt;0.13.13
typesafe-ivy-releases: no namespace defined: using system
	no ivy file in cache for org.scala-sbt#sbt;0.13.13: tried /home/ME/.ivy2/cache/org.scala-sbt/sbt/ivy-0.13.13.xml
	 trying https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml
		tried https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml
ERROR: Server access Error: java.lang.RuntimeException: Could not generate DH keypair url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml
	typesafe-ivy-releases: resource not reachable for org.scala-sbt#sbt;0.13.13: res=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml
	typesafe-ivy-releases: no ivy file found for org.scala-sbt#sbt;0.13.13
sbt-ivy-snapshots: no namespace defined: using system
	no ivy file in cache for org.scala-sbt#sbt;0.13.13: tried /home/ME/.ivy2/cache/org.scala-sbt/sbt/ivy-0.13.13.xml
	 trying https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml
		tried https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml
ERROR: Server access Error: java.lang.RuntimeException: Could not generate DH keypair url=https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml
	sbt-ivy-snapshots: resource not reachable for org.scala-sbt#sbt;0.13.13: res=https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml
	sbt-ivy-snapshots: no ivy file found for org.scala-sbt#sbt;0.13.13
WARN: 	module not found: org.scala-sbt#sbt;0.13.13
WARN: ==== local: tried
WARN:   /home/ME/.ivy2/local/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml
WARN:   -- artifact org.scala-sbt#sbt;0.13.13!sbt.jar:
WARN:   /home/ME/.ivy2/local/org.scala-sbt/sbt/0.13.13/jars/sbt.jar
WARN: ==== Maven Central: tried
WARN:   https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.13/sbt-0.13.13.pom
WARN:   -- artifact org.scala-sbt#sbt;0.13.13!sbt.jar:
WARN:   https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.13/sbt-0.13.13.jar
WARN: ==== typesafe-ivy-releases: tried
WARN:   https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml
WARN: ==== sbt-ivy-snapshots: tried
WARN:   https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml
Nbr of module to sort : 0
	resolved ivy file produced in cache
:: downloading artifacts ::
:: resolution report :: resolve 766ms :: artifacts dl 0ms
WARN: 	::::::::::::::::::::::::::::::::::::::::::::::
WARN: 	::          UNRESOLVED DEPENDENCIES         ::
WARN: 	::::::::::::::::::::::::::::::::::::::::::::::
WARN: 	:: org.scala-sbt#sbt;0.13.13: not found
WARN: 	::::::::::::::::::::::::::::::::::::::::::::::

Nbr of module to sort : 0
	report for org.scala-sbt#boot-app;1.0 default produced in /home/ME/.sbt/boot/resolution-cache/org.scala-sbt-boot-app-default.xml
	resolve done (766ms resolve - 0ms download)

:: problems summary ::
:::: WARNINGS
		module not found: org.scala-sbt#sbt;0.13.13

	==== local: tried

	  /home/ME/.ivy2/local/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml

	  -- artifact org.scala-sbt#sbt;0.13.13!sbt.jar:

	  /home/ME/.ivy2/local/org.scala-sbt/sbt/0.13.13/jars/sbt.jar

	==== Maven Central: tried

	  https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.13/sbt-0.13.13.pom

	  -- artifact org.scala-sbt#sbt;0.13.13!sbt.jar:

	  https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.13/sbt-0.13.13.jar

	==== typesafe-ivy-releases: tried

	  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml

	==== sbt-ivy-snapshots: tried

	  https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml

		::::::::::::::::::::::::::::::::::::::::::::::

		::          UNRESOLVED DEPENDENCIES         ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: org.scala-sbt#sbt;0.13.13: not found

		::::::::::::::::::::::::::::::::::::::::::::::


:::: ERRORS
	Server access Error: RSA premaster secret error url=https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.13/sbt-0.13.13.pom

	Server access Error: RSA premaster secret error url=https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.13/sbt-0.13.13.jar

	Server access Error: java.lang.RuntimeException: Could not generate DH keypair url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml

	Server access Error: java.lang.RuntimeException: Could not generate DH keypair url=https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml


:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
java.lang.RuntimeException: not found
	at org.apache.ivy.core.resolve.IvyNode.loadData(IvyNode.java:238)
	at org.apache.ivy.core.resolve.VisitNode.loadData(VisitNode.java:292)
	at org.apache.ivy.core.resolve.ResolveEngine.fetchDependencies(ResolveEngine.java:714)
	at org.apache.ivy.core.resolve.ResolveEngine.doFetchDependencies(ResolveEngine.java:799)
	at org.apache.ivy.core.resolve.ResolveEngine.fetchDependencies(ResolveEngine.java:722)
	at org.apache.ivy.core.resolve.ResolveEngine.getDependencies(ResolveEngine.java:594)
	at org.apache.ivy.core.resolve.ResolveEngine.resolve(ResolveEngine.java:234)
	at xsbt.boot.Update.xsbt$boot$Update$$lockedApply(Update.scala:105)
	at xsbt.boot.Update$$anon$4.call(Update.scala:99)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at xsbt.boot.Update.apply(Update.scala:100)
	at xsbt.boot.Launch.update(Launch.scala:350)
	at xsbt.boot.Launch.xsbt$boot$Launch$$retrieve$1(Launch.scala:208)
	at xsbt.boot.Launch$$anonfun$3.apply(Launch.scala:216)
	at scala.Option.getOrElse(Option.scala:120)
	at xsbt.boot.Launch.xsbt$boot$Launch$$getAppProvider0(Launch.scala:216)
	at xsbt.boot.Launch$$anon$2.call(Launch.scala:196)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at xsbt.boot.Launch.locked(Launch.scala:238)
	at xsbt.boot.Launch.app(Launch.scala:147)
	at xsbt.boot.Launch.app(Launch.scala:145)
	at xsbt.boot.Launch$.run(Launch.scala:102)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
Error during sbt execution: Error retrieving required libraries
	at xsbt.boot.Pre$.error(Pre.scala:26)
	at xsbt.boot.Update.xsbt$boot$Update$$lockedApply(Update.scala:105)
	at xsbt.boot.Update$$anon$4.call(Update.scala:99)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at xsbt.boot.Update.apply(Update.scala:100)
	at xsbt.boot.Launch.update(Launch.scala:350)
	at xsbt.boot.Launch.xsbt$boot$Launch$$retrieve$1(Launch.scala:208)
	at xsbt.boot.Launch$$anonfun$3.apply(Launch.scala:216)
	at scala.Option.getOrElse(Option.scala:120)
	at xsbt.boot.Launch.xsbt$boot$Launch$$getAppProvider0(Launch.scala:216)
	at xsbt.boot.Launch$$anon$2.call(Launch.scala:196)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at xsbt.boot.Launch.locked(Launch.scala:238)
	at xsbt.boot.Launch.app(Launch.scala:147)
	at xsbt.boot.Launch.app(Launch.scala:145)
	at xsbt.boot.Launch$.run(Launch.scala:102)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
Error during sbt execution: Error retrieving required libraries
```

## notes

I'm using Fedora 24 Workstation

**Comment by eed3si9n** [comment]
```
ERROR: Server access Error: RSA premaster secret error url=https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.13/sbt-0.13.13.pom
    Maven Central: resource not reachable for org/scala-sbt#sbt;0.13.13: res=https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.13/sbt-0.13.13.pom
     trying https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.13/sbt-0.13.13.jar
        tried https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.13/sbt-0.13.13.jar
ERROR: Server access Error: RSA premaster secret error url=https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.13/sbt-0.13.13.jar
    Maven Central: resource not reachable for org/scala-sbt#sbt;0.13.13: res=https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.13/sbt-0.13.13.jar
    Maven Central: no ivy file nor artifact found for org.scala-sbt#sbt;0.13.13
typesafe-ivy-releases: no namespace defined: using system
    no ivy file in cache for org.scala-sbt#sbt;0.13.13: tried /home/ME/.ivy2/cache/org.scala-sbt/sbt/ivy-0.13.13.xml
     trying https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml
        tried https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml
ERROR: Server access Error: java.lang.RuntimeException: Could not generate DH keypair url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml
    typesafe-ivy-releases: resource not reachable for org.scala-sbt#sbt;0.13.13: res=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml
    typesafe-ivy-releases: no ivy file found for org.scala-sbt#sbt;0.13.13
sbt-ivy-snapshots: no namespace defined: using system
    no ivy file in cache for org.scala-sbt#sbt;0.13.13: tried /home/ME/.ivy2/cache/org.scala-sbt/sbt/ivy-0.13.13.xml
     trying https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml
        tried https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml
ERROR: Server access Error: java.lang.RuntimeException: Could not generate DH keypair url=https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml
    sbt-ivy-snapshots: resource not reachable for org.scala-sbt#sbt;0.13.13: res=https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml
    sbt-ivy-snapshots: no ivy file found for org.scala-sbt#sbt;0.13.13
```

This looks like you're hitting some SSL handshake issue with your JDK.

**Comment by wpc009** [comment]
There is no `0.13.13` in repo `https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt`
The most recent are `0.13.9`. What is the right repo?

**Comment by eed3si9n** [comment]
https://repo.typesafe.com/ is the right repo.
https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.13/ exists.

**Comment by liupu1106** [comment]
when I run sbt, get below error, how to config right repo?

# sbt
Getting org.scala-sbt sbt 0.13.13 ...
You probably access the destination server through a proxy server that is not well configured.
You probably access the destination server through a proxy server that is not well configured.
You probably access the destination server through a proxy server that is not well configured.
You probably access the destination server through a proxy server that is not well configured.

:: problems summary ::
:::: WARNINGS
        Host repo1.maven.org not found. url=https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.13/sbt-0.13.13.pom

        Host repo1.maven.org not found. url=https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.13/sbt-0.13.13.jar

        Host repo.typesafe.com not found. url=https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml

        Host repo.scala-sbt.org not found. url=https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml

                module not found: org.scala-sbt#sbt;0.13.13

        ==== local: tried

          /root/.ivy2/local/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml

          -- artifact org.scala-sbt#sbt;0.13.13!sbt.jar:

          /root/.ivy2/local/org.scala-sbt/sbt/0.13.13/jars/sbt.jar

        ==== Maven Central: tried

          https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.13/sbt-0.13.13.pom

          -- artifact org.scala-sbt#sbt;0.13.13!sbt.jar:

          https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.13.13/sbt-0.13.13.jar

        ==== typesafe-ivy-releases: tried

          https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml

        ==== sbt-ivy-snapshots: tried

          https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/0.13.13/ivys/ivy.xml

                ::::::::::::::::::::::::::::::::::::::::::::::

                ::          UNRESOLVED DEPENDENCIES         ::

                ::::::::::::::::::::::::::::::::::::::::::::::

                :: org.scala-sbt#sbt;0.13.13: not found

                ::::::::::::::::::::::::::::::::::::::::::::::



:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
unresolved dependency: org.scala-sbt#sbt;0.13.13: not found
Error during sbt execution: Error retrieving required libraries
  (see /root/.sbt/boot/update.log for complete log)
Error: Could not retrieve sbt 0.13.13

**Comment by ConstantTime** [comment]
@liupu1106 You got a solution for this?
I am also having the same problem.

**Comment by liupu1106** [comment]
what problem？


发自网易邮箱大师
On 08/10/2017 20:03, Rakshit Tiwari wrote:

@liupu1106 You got a solution for this?
I am also having the same problem.

**Comment by RidgeA** [comment]
@ConstantTime some time ago i also faced with problems installing scala. During my searches I visited this page and subscribed on it.
I don't know (I don't remember), is it was the solution of this issue, but eventually I installed Oracle Java JDK instead of OpenJDK (I am using Fedora) and after that I was able to run scala and sbt. I hope it helps in your case.

**Comment by Tang8330** [comment]
@7kemZmani did you ever get a chance to fix it? Curious for a write up on how you fixed it. 
I am currently running into the same issue here on my localdev.

**Comment by sshanmuga** [comment]
@Tang8330 : follow the [link](https://stackoverflow.com/questions/27127687/how-to-use-sbt-from-behind-proxy-in-windows-7/29005026)

**Comment by samrudh** [comment]
I also faced the issue.  It turned out to be a network issue. Because of n/w latency, a gateway timeout error is thrown which resulted in the unresolved dependency.  As pointed out by @eed3si9n the repo links are valid.
