### ISSUE TITLE
is the SBT command package cross-compiled for Scala 2.12?

### ISSUE THREAD

**Issue by cos** [sbt/sbt#2847]
## steps

following the guide here: 
http://www.scala-sbt.org/0.13/docs/Command-Line-Applications.html
but updating the Scala and sbt version:
```
scalaVersion := "2.12.0"

libraryDependencies += "org.scala-sbt" % "command" % "0.12.0"
```

and

```
[scala]
version: 2.12.0
```

## problem

when running `sbt @path/to/hello.build.properties`, I get:
```
java.lang.NoClassDefFoundError: scala/Product$class
	at sbt.complete.Infinite$.<init>(UpperBound.scala:21)
	at sbt.complete.Infinite$.<clinit>(UpperBound.scala)
	at sbt.complete.Parser$.zeroOrMore(Parser.scala:220)
	at sbt.complete.ParserMain$$anon$3.$times(Parser.scala:271)
	at sbt.complete.Parsers$class.identifier(Parsers.scala:61)
	at sbt.complete.DefaultParsers$.identifier(Parsers.scala:231)
	at sbt.complete.Parsers$class.ID(Parsers.scala:42)
	at sbt.complete.DefaultParsers$.ID$lzycompute(Parsers.scala:231)
	at sbt.complete.DefaultParsers$.ID(Parsers.scala:231)
	at sbt.complete.Parsers$class.OpOrID(Parsers.scala:51)
	at sbt.complete.DefaultParsers$.OpOrID$lzycompute(Parsers.scala:231)
	at sbt.complete.DefaultParsers$.OpOrID(Parsers.scala:231)
	at sbt.Command$.validID(Command.scala:57)
	at sbt.SimpleCommand.<init>(Command.scala:17)
	at sbt.Command$.make(Command.scala:35)
	at sbt.Command$.command(Command.scala:31)
```

## expectation

as explained in the tutorial

## notes

I think the error is related to SBT not being cross-compiled for Scala 2.12. Still, it seems none of the SBT artifacts are published with a Scala version, so I'm not sure how the version can be chosen. I tried checking out SBT's `0.13.13_2.12cross` branch and publishing locally, but it made no difference.

**Comment by dwijnand** [comment]
No sbt isn't cross-built for 2.12, also you're using sbt 0.12.0, which is probably Scala 2.9 too.

I would recommend using sbt 0.13.13 and scala 2.10.6 for what you're trying to do.

**Comment by cos** [comment]
Thanks! 0.12.0 was a copy-paste source error. I tried 0.13.13, both the regular and by compiling the `0.13.13_2.12cross` branch myself. Are there any plans to cross-build for 2.12? Also, how does cross-compilation happen, as most of the artifacts are not published with a Scala version, i.e., no underscore-scala-version in the name?

**Comment by cos** [comment]
Regarding 2.10, we cannot really use it. We have a mixed Java-Scala project, so we're very happy to be able to use 2.12 (with traits compiled to interfaces with default methods, etc.). As we plan to use sbt to build the command line part for the tool, it will need to be compiled with the same version of Scala as the rest.

**Comment by dwijnand** [comment]
We'll be cross-building sbt modules in sbt 1, and sbt itself will use either 2.11 or 2.12. See https://github.com/sbt/sbt/issues/2389.
