### ISSUE TITLE
Logging causing "No such file or directory"

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#2863]
### steps

Not sure if this is reproducible, but it's the catch of the day on Travis.

```
> scripted source-dependencies/java-mixed
```

### problem

Logging causing "No such file or directory"

```
Running source-dependencies / java-mixed
[error] Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
[info] Getting org.scala-sbt sbt 1.0.0-SNAPSHOT ...
[info] :: retrieving :: org.scala-sbt#boot-app
[info] 	confs: [default]
[info] 	54 artifacts copied, 0 already retrieved (20351kB/101ms)
[info] Getting Scala 2.11.8 (for sbt)...
[info] :: retrieving :: org.scala-sbt#boot-scala
[info] 	confs: [default]
[info] 	6 artifacts copied, 0 already retrieved (26456kB/45ms)
[info] [info] Set current project to java-mixed (in build file:/tmp/sbt_71151c2a/java-mixed/)
[info] [info] Updating {file:/tmp/sbt_71151c2a/java-mixed/}java-mixed...
[info] [info] Done updating.
[info] [info] Compiling 1 Scala source and 1 Java source to /tmp/sbt_71151c2a/java-mixed/target/scala-2.11/classes...
[info] [success] Total time: 3 s, completed Dec 6, 2016 6:12:58 AM
[info] [info] Compiling 1 Scala source to /tmp/sbt_71151c2a/java-mixed/target/scala-2.11/classes...
[info] [info] Compiling 1 Java source to /tmp/sbt_71151c2a/java-mixed/target/scala-2.11/classes...
[info] [error] /tmp/sbt_71151c2a/java-mixed/JJ.java:3: cannot find symbol
[info] [error]   symbol:   method foo(java.lang.String)
[info] [error]   location: class S
[info] [error] 		new S().foo("ahoy");
[info] [error] (compile:compileIncremental) javac returned nonzero exit code
[info] [error] Total time: 1 s, completed Dec 6, 2016 6:12:58 AM
[info] Could not create file /tmp/sbt_71151c2a/java-mixed/target/streams/$global/projectDescriptors/$global/streams/outjava.io.IOException: No such file or directory
[info] 	at sbt.internal.io.ErrorHandling$.translate(ErrorHandling.scala:10)
[info] 	at sbt.io.IO$.touch(IO.scala:167)
[info] 	at sbt.std.Streams$$anon$3$$anon$2.make(Streams.scala:132)
[info] 	at sbt.std.Streams$$anon$3$$anon$2.text(Streams.scala:116)
[info] 	at sbt.std.Streams$$anon$3$$anon$2.log(Streams.scala:127)
[info] 	at sbt.std.TaskStreams$class.log(Streams.scala:59)
[info] 	at sbt.std.Streams$$anon$3$$anon$2.log$lzycompute(Streams.scala:105)
[info] 	at sbt.std.Streams$$anon$3$$anon$2.log(Streams.scala:105)
[info] 	at sbt.Classpaths$$anonfun$depMap$1.apply(Defaults.scala:1640)
[info] 	at sbt.Classpaths$$anonfun$depMap$1.apply(Defaults.scala:1639)
[info] 	at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:35)
[info] 	at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:34)
[info] 	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:44)
[info] 	at sbt.internal.util.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
[info] 	at sbt.std.Transform$$anon$4.work(System.scala:58)
[info] 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:230)
[info] 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:230)
[info] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[info] 	at sbt.Execute.work(Execute.scala:239)
[info] 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:230)
[info] 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:230)
[info] 	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:161)
[info] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[info] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info] 	at java.lang.Thread.run(Thread.java:745)
[info] Caused by: java.io.IOException: No such file or directory
[info] 	at java.io.UnixFileSystem.createFileExclusively(Native Method)
[info] 	at java.io.File.createNewFile(File.java:1012)
[info] 	at sbt.io.IO$$anonfun$1.apply$mcZ$sp(IO.scala:167)
[info] 	at sbt.io.IO$$anonfun$1.apply(IO.scala:167)
[info] 	at sbt.io.IO$$anonfun$1.apply(IO.scala:167)
[info] 	at sbt.internal.io.ErrorHandling$.translate(ErrorHandling.scala:10)
[info] 	at sbt.io.IO$.touch(IO.scala:167)
[info] 	at sbt.std.Streams$$anon$3$$anon$2.make(Streams.scala:132)
[info] 	at sbt.std.Streams$$anon$3$$anon$2.text(Streams.scala:116)
[info] 	at sbt.std.Streams$$anon$3$$anon$2.log(Streams.scala:127)
[info] 	at sbt.std.TaskStreams$class.log(Streams.scala:59)
[info] 	at sbt.std.Streams$$anon$3$$anon$2.log$lzycompute(Streams.scala:105)
[info] 	at sbt.std.Streams$$anon$3$$anon$2.log(Streams.scala:105)
[info] 	at sbt.Classpaths$$anonfun$depMap$1.apply(Defaults.scala:1640)
[info] 	at sbt.Classpaths$$anonfun$depMap$1.apply(Defaults.scala:1639)
[info] 	at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:35)
[info] 	at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:34)
[info] 	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:44)
[info] 	at sbt.internal.util.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
[info] 	at sbt.std.Transform$$anon$4.work(System.scala:58)
[info] 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:230)
[info] 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:230)
[info] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[info] 	at sbt.Execute.work(Execute.scala:239)
[info] 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:230)
[info] 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:230)
[info] 	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:161)
[info] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[info] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info] 	at java.lang.Thread.run(Thread.java:745)
[info] [error] (*:projectDescriptors) Could not create file /tmp/sbt_71151c2a/java-mixed/target/streams/$global/projectDescriptors/$global/streams/outjava.io.IOException: No such file or directory
[info] [error] Total time: 0 s, completed Dec 6, 2016 6:12:58 AM
```

### notes

The script looks like this:

```
$ copy-file changes/S1.scala S.scala
> compile
$ copy-file changes/S2.scala S.scala
-> compile

> clean
$ copy-file changes/build.sbt build.sbt
> reload

$ copy-file changes/S1.scala S.scala
> compile
$ copy-file changes/S2.scala S.scala
-> compile
```

I suspect that it's getting caused by either `clean` or the subsequent `reload` since we see total time for the first two commands.

**Comment by eed3si9n** [comment]
Closing this as duplicate of https://github.com/sbt/sbt/issues/2156
