### ISSUE TITLE
NullPointerException on loading project

### ISSUE THREAD

**Issue by ViliusN** [sbt/sbt#2929]
Someone might want to take a look at this:

```
$ sbt
[info] Loading project definition from /some/where
java.lang.NullPointerException
	at sbt.FileFilter$$anonfun$$minus$minus$1.<init>(NameFilter.scala:18)
	at sbt.FileFilter$class.$minus$minus(NameFilter.scala:18)
	at sbt.SimpleFilter.$minus$minus(NameFilter.scala:71)
	at sbt.Classpaths$.findUnmanagedJars(Defaults.scala:1847)
	at sbt.Classpaths$$anonfun$classpaths$10.apply(Defaults.scala:1072)
	at sbt.Classpaths$$anonfun$classpaths$10.apply(Defaults.scala:1072)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (runtime:unmanagedJars) java.lang.NullPointerException
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? r
[info] Loading project definition from /some/where
[info] Set current project to IdleIterations (in build file:/some/where/)
```

The second time it loaded ok.

**Comment by eed3si9n** [comment]
Do you have a project that can reproduce this behavior?

**Comment by eed3si9n** [comment]
I am closing this due to inactivity, but if this is still relevant let us know with more details (reproduction steps etc).
