### ISSUE TITLE
GC overhead limit exceeded when running `~` commands in Zinc

### ISSUE THREAD

**Issue by jvican** [sbt/sbt#2947]
## steps
* Clone `sbt/zinc`.
* Run `~plz 2.12.1 zincRoot/scripted source-dependencies/java-mixed`.
* Edit code and run it for some iterations.

## problem
  
I suspect there's a memory leak either in sbt, zinc or the scripted tests. I get this error message at least three times a day (and I have 16GB of RAM).
```
sbt appears to be exiting abnormally.
  The log file for this session is at /tmp/sbt7510292030523447106.log
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at sbt.Init$Setting.mapInit(Settings.scala:472)
	at sbt.Load$$anonfun$finalTransforms$1.apply(Load.scala:196)
	at sbt.Load$$anonfun$finalTransforms$1.apply(Load.scala:196)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at sbt.Load$.finalTransforms(Load.scala:196)
	at sbt.Load$.reapply(Load.scala:215)
	at sbt.BuiltinCommands$.reapply(Main.scala:246)
	at sbt.Cross$$anonfun$switchVersion$2.apply(Cross.scala:85)
	at sbt.Cross$$anonfun$switchVersion$2.apply(Cross.scala:34)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$.process(Command.scala:93)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:96)
	at sbt.MainLoop$.run(MainLoop.scala:89)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
Error during sbt execution: java.lang.OutOfMemoryError: GC overhead limit exceeded
```
## expectation
Not to crash by GC overhead limit exceeded. I don't know what's happening under the hood. Perhaps `~` is not correctly clearing memory from previous runs?

## notes
Zinc uses sbt 0.13.13.
  
I post here this report because I'm not sure the culprit is Zinc and it may be sbt misbehaving. Please, let me know if this should go to the Zinc repository.
  
I also had a look for previous errors but the open tickets do not correspond to this behaviour.
  
At some point, I can see the following lines in the log file created by sbt:
```
[0m[[0mdebug[0m] [0m> ++ 2.12.1[0m
[0m[[0minfo[0m] [0mSetting version to 2.12.1[0m
[0m[[0mdebug[0m] [0mForcing garbage collection...[0m
[0m[[0minfo[0m] [0mReapplying settings...[0m
[0m[[0minfo[0m] [0mSet current project to zinc Root (in build file:/data/rw/code/scala/zinc/)[0m
[0m[[0mdebug[0m] [0m> resumeFromFailure[0m
[0m[[0mdebug[0m] [0m> ~ plz 2.12.1 zincRoot/scripted source-dependencies/java-mixed[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mForcing garbage collection...[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
[0m[[0mdebug[0m] [0mRunning task... Cancel: Null, check cycles: false, forcegc: true[0m
```
  
This repeats like an infinite melody, until it gets to re run the task and fail miserably with:
```
[0m[[0minfo[0m] [0m	published zinc-core_2.12 to /home/jvican/.ivy2/local/org.scala-sbt/zinc-core_2.12/1.0.0-X8-SNAPSHOT/poms/zinc-core_2.12.pom[0m
[0m[[0minfo[0m] [0m	published zinc-core_2.12 to /home/jvican/.ivy2/local/org.scala-sbt/zinc-core_2.12/1.0.0-X8-SNAPSHOT/jars/zinc-core_2.12.jar[0m
[0m[[0minfo[0m] [0m	published zinc-core_2.12 to /home/jvican/.ivy2/local/org.scala-sbt/zinc-core_2.12/1.0.0-X8-SNAPSHOT/srcs/zinc-core_2.12-sources.jar[0m
[0m[[0minfo[0m] [0m	published zinc-core_2.12 to /home/jvican/.ivy2/local/org.scala-sbt/zinc-core_2.12/1.0.0-X8-SNAPSHOT/docs/zinc-core_2.12-javadoc.jar[0m
[0m[[0minfo[0m] [0m	published ivy to /home/jvican/.ivy2/local/org.scala-sbt/zinc-core_2.12/1.0.0-X8-SNAPSHOT/ivys/ivy.xml[0m
[0m[[0mdebug[0m] [0mForcing garbage collection...[0m
[0m[[32msuccess[0m] [0mTotal time: 22 s, completed Feb 2, 2017 10:48:38 AM[0m
[0m[[0mdebug[0m] [0m> ++ 2.12.1[0m
[0m[[0minfo[0m] [0mSetting version to 2.12.1[0m
[0m[[0mdebug[0m] [0mForcing garbage collection...[0m
[0m[[0minfo[0m] [0mReapplying settings...[0m
```
  
Then, it crashes.

**Comment by jvican** [comment]
It seems that https://github.com/jvican/zinc/commit/d5d59b6f4c563a5f9aa5d095295b93b912b90cf3 already points out what the issue is. `plz` creates OOM while `wow` doesn't. I wonder why this is the case and whether it can be fixed or not.

**Comment by dwijnand** [comment]
@jvican https://github.com/sbt/zinc/commit/d5d59b6f4c563a5f9aa5d095295b93b912b90cf3 (edit: doh.. that's the same commit, just on your fork...)

**Comment by jvican** [comment]
Yes, I saw that. It would be interesting to know why that OOM happens. @dwijnand

**Comment by eed3si9n** [comment]
I didn't confirm it with sbt 1.2.x, but the scenario seems to work for me on 1.3.2 without an error.
