### ISSUE TITLE
object scala.runtime in compiler mirror not found.

### ISSUE THREAD

**Issue by QiuMing** [sbt/sbt#2958]
I an new to scala ,I get this error and could not solve it after search in google.

## steps
* create play2 seed project  and run
```
sbt new playframework/play-scala-seed.g8
sbt
```

## problem

I get  `[error] scala.reflect.internal.MissingRequirementError: object scala.runtime in compiler mirror not found.`

## expectation

```
$ sbt
[info] Loading global plugins from /home/lxm/.sbt/0.13/plugins
[info] Loading project definition from /home/lxm/project/scala-seed/project
[info] Updating scala-seed-build
[info] Resolved scala-seed-build dependencies
error: error while loading <root>, error in opening zip file
scala.reflect.internal.MissingRequirementError: object scala.runtime in compiler mirror not found.
	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:16)
	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:17)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:48)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:40)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:61)
	at scala.reflect.internal.Mirrors$RootsBase.getPackage(Mirrors.scala:172)
	at scala.reflect.internal.Mirrors$RootsBase.getRequiredPackage(Mirrors.scala:175)
	at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackage$lzycompute(Definitions.scala:183)
	at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackage(Definitions.scala:183)
	at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackageClass$lzycompute(Definitions.scala:184)
	at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackageClass(Definitions.scala:184)
	at scala.reflect.internal.Definitions$DefinitionsClass.AnnotationDefaultAttr$lzycompute(Definitions.scala:1024)
	at scala.reflect.internal.Definitions$DefinitionsClass.AnnotationDefaultAttr(Definitions.scala:1023)
	at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreClasses$lzycompute(Definitions.scala:1153)
	at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreClasses(Definitions.scala:1152)
	at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode$lzycompute(Definitions.scala:1196)
	at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode(Definitions.scala:1196)
	at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1261)
	at scala.tools.nsc.Global$Run.<init>(Global.scala:1290)
	at sbt.compiler.Eval$$anon$1.<init>(Eval.scala:141)
	at sbt.compiler.Eval.run$lzycompute$1(Eval.scala:141)
	at sbt.compiler.Eval.run$1(Eval.scala:141)
	at sbt.compiler.Eval.unlinkAll$1(Eval.scala:144)
	at sbt.compiler.Eval.evalCommon(Eval.scala:153)
	at sbt.compiler.Eval.evalDefinitions(Eval.scala:122)
	at sbt.EvaluateConfigurations$.evaluateDefinitions(EvaluateConfigurations.scala:271)
	at sbt.EvaluateConfigurations$.evaluateSbtFile(EvaluateConfigurations.scala:109)
	at sbt.Load$.sbt$Load$$loadSettingsFile$1(Load.scala:775)
	at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:781)
	at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:780)
	at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
	at scala.collection.AbstractMap.getOrElse(Map.scala:58)
	at sbt.Load$.sbt$Load$$memoLoadSettingsFile$1(Load.scala:780)
	at sbt.Load$$anonfun$loadFiles$1$2.apply(Load.scala:788)
	at sbt.Load$$anonfun$loadFiles$1$2.apply(Load.scala:788)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at sbt.Load$.loadFiles$1(Load.scala:788)
	at sbt.Load$.discoverProjects(Load.scala:799)
	at sbt.Load$.discover$1(Load.scala:585)
	at sbt.Load$.sbt$Load$$loadTransitive(Load.scala:633)
	at sbt.Load$$anonfun$loadUnit$1.sbt$Load$$anonfun$$loadProjects$1(Load.scala:482)
	at sbt.Load$$anonfun$loadUnit$1$$anonfun$40.apply(Load.scala:485)
	at sbt.Load$$anonfun$loadUnit$1$$anonfun$40.apply(Load.scala:485)
	at sbt.Load$.timed(Load.scala:1025)
	at sbt.Load$$anonfun$loadUnit$1.apply(Load.scala:485)
	at sbt.Load$$anonfun$loadUnit$1.apply(Load.scala:459)
	at sbt.Load$.timed(Load.scala:1025)
	at sbt.Load$.loadUnit(Load.scala:459)
	at sbt.Load$$anonfun$25$$anonfun$apply$14.apply(Load.scala:311)
	at sbt.Load$$anonfun$25$$anonfun$apply$14.apply(Load.scala:310)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
	at sbt.BuildLoader.apply(BuildLoader.scala:140)
	at sbt.Load$.loadAll(Load.scala:365)
	at sbt.Load$.loadURI(Load.scala:320)
	at sbt.Load$.load(Load.scala:316)
	at sbt.Load$.load(Load.scala:305)
	at sbt.Load$$anonfun$4.apply(Load.scala:146)
	at sbt.Load$$anonfun$4.apply(Load.scala:146)
	at sbt.Load$.timed(Load.scala:1025)
	at sbt.Load$.apply(Load.scala:146)
	at sbt.Load$.defaultLoad(Load.scala:39)
	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:496)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:496)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:488)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:488)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$.process(Command.scala:93)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:96)
	at sbt.MainLoop$.run(MainLoop.scala:89)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
	at sbt.MainLoop$.runLogged(MainLoop.scala:22)
	at sbt.StandardMain$.runManaged(Main.scala:57)
	at sbt.xMain.run(Main.scala:29)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
[error] scala.reflect.internal.MissingRequirementError: object scala.runtime in compiler mirror not found.
```

### Notes 1:

My java version and scala versoin 
```
$ java -version
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

$ scala -version
cat: /usr/lib/jvm/java-8-openjdk-amd64/release: No such file or directory
Scala code runner version 2.12.1 -- Copyright 2002-2016, LAMP/EPFL and Lightbend, Inc.
```

### Notes 2
Looking form http://stackoverflow.com/questions/23317326/trying-to-cross-compile-a-project-to-scala-2-11-fails-with-error-while-loading,  I add 
```
libraryDependencies += "org.scala-lang" % "scala-library" % "2.11.8"

```

And now my buikd.sbt file
```
name := """scala-seed"""
organization := "com.ming"

version := "1.0-SNAPSHOT"

lazy val root = (project in file(".")).enablePlugins(PlayScala)

scalaVersion := "2.11.8"
libraryDependencies += "org.scala-lang" % "scala-library" % "2.11.8"

libraryDependencies += filters
libraryDependencies += "org.scalatestplus.play" %% "scalatestplus-play" % "1.5.1" % Test

// Adds additional packages into Twirl
//TwirlKeys.templateImports += "com.ming.controllers._"

// Adds additional packages into conf/routes
// play.sbt.routes.RoutesKeys.routesImport += "com.ming.binders._"

```

### Notes 3 
I hava install  coursier plugin in ~/.sbt/0.13/plugins/build.sbt
```
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-M15")
```

**Comment by eed3si9n** [comment]
Could you try without Coursier to make sure that's not causing the issue, plz?

**Comment by dwijnand** [comment]
`MissingRequirementError ` usually means you have a corrupt jar on your classpath somewhere.

Try running `find ~/.ivy2 ~/.sbt -name '*.jar' -exec file {} \; | grep -v 'Zip archive data'` to find any `*.jar` that isn't actually a jar, and delete it.

**Comment by Leammas** [comment]
Just run into the same issue. It is truly the coursier problem. After removing it from plugins compilation went well.

**Comment by Dbz** [comment]
It may be worth noting that I ran into a very similar issue, and I was able to fix it by uninstalling Java 9. I have Java 8.1 and Java 9 on my system. I had my `$JAVA_HOME` environment variable pointed to Java 8.1, and `java -version` showed 8.1; however, it was still giving that error until I uninstalled Java 9, and then everything started working.

**Comment by SethTisue** [comment]
in cases where JDK 9 is suspected to be a factor, upgrading to sbt 0.13.17+ or 1.1.0+ is the first thing to try

**Comment by Dbz** [comment]
My sbt version is showing as `1.1.0` (same as when I troubleshooted the above issue)

**Comment by SethTisue** [comment]
w/r/t play-scala-seed.g8 specifically, I've submitted https://github.com/playframework/play-scala-seed.g8/pull/48

**Comment by Grogs** [comment]
@SethTisue what changed in 0.13.17? A colleague is having this issue with the scala maven plugin, which of course needs to be fixed there, but it would be if we can point them to the problem.

**Comment by SethTisue** [comment]
@Grogs the 0.13.17 changes are JDK 9 specific. I can't answer further off the top of my head without digging. does the problem your colleague is having happen _only_ on JDK 9? also, the presence of the "object scala.runtime in compiler mirror not found" error message isn't sufficient to show that something is the same issue; this message can have different underlying causes

**Comment by SethTisue** [comment]
I suggest we close this ticket, as the original report is stale and we never got further info from the original reporter. So now the ticket has become a place where people bring their miscellaneous "object scala.runtime in compiler mirror not found" errors. It's reasonable for people to guess that this error always has the same cause — but not a correct guess.

The closed ticket will still turn up in searches and people can still go digging in the comments here for clues to possible causes.

**Comment by Grogs** [comment]
Thanks Seth, makes sense.

Yeah, the same project works on Java 8 but fails on Java 9, they've upgraded to Scala 2.12.4 to no avail.

The other bit of information to go on is:
```
error: error while loading Object, Missing dependency ‘object scala in compiler mirror’, required by /modules/java.base/java/lang/Object.class
```

We've raised an issue with scala-maven-plugin. davidB/scala-maven-plugin#234

**Comment by pbhatIIT** [comment]
Even with sbt 1.1.0, I had the same error max os X and java 9. I had to install later version of java 8 to get rid of the error

**Comment by eximius313** [comment]
Same problem with Eclipse 4.7.3, SBT 1.1.2, JDK 9.0.4

**Comment by SethTisue** [comment]
> Same problem with Eclipse 4.7.3, SBT 1.1.2, JDK 9.0.4

@eximius313 you'll see if you review the previous comments that "same problem" isn't helpful here. same error message doesn't necessarily imply same problem. multiple different problems with different causes have now been discussed on this ticket, which is why the ticket is now closed.

**Comment by eximius313** [comment]
@SethTisue I see this problem in my Eclipse:
![image](https://user-images.githubusercontent.com/5578017/38220867-f369373c-36dc-11e8-917b-6cebe9e4bb76.png)
and I have no idea what could be the reason - I only know the problem :(
Therefore I also don't see any better issue to comment.
What you suggest me to do?

**Comment by SethTisue** [comment]
@eximius313 I’m sorry, I don’t know. my usual suggestion would be to try to reproduce the problem outside Eclipse, but I understand that might be difficult if you’re new to the language. I don’t know Eclipse stuff

**Comment by geektcp** [comment]
I resole it ,beacuse the maven dependence err:

            <dependency>
                <groupId>com.haizhi.spark</groupId>
                <artifactId>spark-assembly</artifactId>
                <version>1.6.1</version>
            </dependency>
I remove this dependency , and then sucessful l!!

and then , I have redownload the spark-assembly dependency , and add it, then it is OK!

Chinese:
说白了就是依赖包下载不全，彻底重新下载即可。

**Comment by joe312213** [comment]
currently experiencing this error in Eclipse Photon. I create a new Scala project, add a hello world object with a main function and I get this error: "Error in Scala compiler: object java.lang.Object in compiler mirror not found." 
On Windows 10, JREs added to Eclipse are version 10 (default) and 1.8. Scala project target environment is JRE 10. For good measure, JAVA_HOME environment variable also set to point to JDK 10.

**Comment by SethTisue** [comment]
@joe312213 you have an Eclipse problem, not an sbt problem. unrelated to this ticket. see [my previous comment](
https://github.com/sbt/sbt/issues/2958#issuecomment-369298750)

**Comment by SethTisue** [comment]
y'all Eclipse users should start on a ticket on this in a different bug tracker?

**Comment by f0ster** [comment]
I was having this issue with `java version "1.8.0_161"`, `Scala code runner version 2.12.6`, and upgraded sbt to 1.2.0 via brew to fix

**Comment by yrpatil** [comment]
> I was having this issue with `java version "1.8.0_161"`, `Scala code runner version 2.12.6`, and upgraded sbt to 1.2.0 via brew to fix

Thanks. This helped me resolve this problem.

**Comment by nisanth456** [comment]
Hi,
I get an error while run pio status
ivl@ivl:~/Downloads/PredictionIO-0.12.0-incubating$ pio status
Error: Could not find or load main class
org.apache.predictionio.tools.console.Console

But, elasticsear,hbae running .eventserver not running

ivl@ivl:~/Downloads/PredictionIO-0.12.0-incubating$ jps -l
24357 org.apache.hadoop.hbase.master.HMaster
25510 sun.tools.jps.Jps
24262 org.elasticsearch.bootstrap.Elasticsearch
ivl@ivl:~/Downloads/PredictionIO-0.12.0-incubating$

**Comment by umang-malhotra** [comment]
I had ran in the same issue.
And turns out in my case it got resolved by changing scalaVersion in build.sbt file from 2.11.11 to 2.11.12
I was having following configurations in my sbt project while getting into this issue
scalaVersion := "2.11.12" [in build.sbt file]
play version - "2.5.18" [in  plugins.sbt file]
sbt.version=0.13.18 [in build.properties file]

changin scalaVersion to "2.11.12" started working for me.
So, I changed to scalaVersion := "2.11.12" and it started working.

**Comment by olafurpg** [comment]
I hit on the same issue and adding the following to build.sbt fixed the issue for me

```scala
fork := true
```
The problem was caused by a library on my classpath using `this.getClass.getClassLoader.asInstanceOf[URLClassLoader].getUrls` and feeding those URLs to the Scala compiler.

**Comment by VishSinha** [comment]
> I had ran in the same issue.
> And turns out in my case it got resolved by changing scalaVersion in build.sbt file from 2.11.11 to 2.11.12
> I was having following configurations in my sbt project while getting into this issue
> scalaVersion := "2.11.12" [in build.sbt file]
> play version - "2.5.18" [in plugins.sbt file]
> sbt.version=0.13.18 [in build.properties file]
> 
> changin scalaVersion to "2.11.12" started working for me.
> So, I changed to scalaVersion := "2.11.12" and it started working.

Thanks umang-malhotra, changing scalaVersion := "2.11.12" helped me as well along with JDK version 1.8.0_241
