### ISSUE TITLE
[0.13.14-RC1] Initialization exception on OpenJDK 9 (Docker)

### ISSUE THREAD

**Issue by ScalaWilliam** [sbt/sbt#3005]
## steps
With Docker, run:

```
$ docker run -it java:openjdk-9 bash -c 'wget -q -O - https://dl.bintray.com/sbt/native-packages/sbt/0.13.14-RC1/sbt-0.13.14-RC1.tgz | tar zxf -; ./sbt/bin/sbt'
```

## problem

Output is the following:
```
Copying runtime jar.
mkdir: cannot create directory ‘/root/.sbt/0.13/java9-rt-ext-oracle_corporation_9_debian’: No such file or directory
java.nio.file.NoSuchFileException: /root/.sbt/0.13/java9-rt-ext-oracle_corporation_9_debian/rt.jar
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:215)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
	at java.base/java.nio.file.Files.newOutputStream(Files.java:218)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:98)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:106)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:342)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:291)
	at io.github.retronym.java9rtexport.Export.main(Export.java:42)
Getting org.scala-sbt sbt 0.13.14-RC1  (this may take some time)...
java.lang.ExceptionInInitializerError
	at java.base/javax.crypto.JceSecurityManager.<clinit>(JceSecurityManager.java:65)
	at java.base/javax.crypto.Cipher.getConfiguredPermission(Cipher.java:2606)
	at java.base/javax.crypto.Cipher.getMaxAllowedKeyLength(Cipher.java:2630)
	at java.base/sun.security.ssl.CipherSuite$BulkCipher.isUnlimited(CipherSuite.java:602)
	at java.base/sun.security.ssl.CipherSuite$BulkCipher.<init>(CipherSuite.java:574)
	at java.base/sun.security.ssl.CipherSuite$BulkCipher.<clinit>(CipherSuite.java:460)
	at java.base/sun.security.ssl.CipherSuite.<clinit>(CipherSuite.java:1074)
	at java.base/sun.security.ssl.SSLContextImpl.getApplicableSupportedCipherSuiteList(SSLContextImpl.java:353)
	at java.base/sun.security.ssl.SSLContextImpl.access$100(SSLContextImpl.java:41)
	at java.base/sun.security.ssl.SSLContextImpl$AbstractTLSContext.<clinit>(SSLContextImpl.java:589)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:300)
	at java.base/java.security.Provider$Service.getImplClass(Provider.java:1844)
	at java.base/java.security.Provider$Service.newInstance(Provider.java:1820)
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
	at java.base/javax.net.ssl.SSLContext.getInstance(SSLContext.java:169)
	at java.base/javax.net.ssl.SSLContext.getDefault(SSLContext.java:99)
	at java.base/javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:123)
	at java.base/javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:332)
	at java.base/javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:289)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:86)
	at java.base/sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
	at java.base/sun.net.www.protocol.https.Handler.openConnection(Handler.java:57)
	at java.base/java.net.URL.openConnection(URL.java:1049)
	at org.apache.ivy.util.url.BasicURLHandler.getURLInfo$57a0216e(BasicURLHandler.java:66)
	at org.apache.ivy.util.url.BasicURLHandler.getURLInfo(BasicURLHandler.java:54)
	at org.apache.ivy.plugins.repository.url.URLResource.init(URLResource.java:65)
	at org.apache.ivy.plugins.repository.url.URLResource.exists(URLResource.java:81)
	at org.apache.ivy.plugins.resolver.RepositoryResolver.findResourceUsingPattern(RepositoryResolver.java:97)
	at org.apache.ivy.plugins.resolver.AbstractPatternsBasedResolver.findResourceUsingPatterns(AbstractPatternsBasedResolver.java:96)
	at org.apache.ivy.plugins.resolver.IBiblioResolver.findIvyFileRef(IBiblioResolver.java:102)
	at org.apache.ivy.plugins.resolver.BasicResolver.getDependency(BasicResolver.java:228)
	at org.apache.ivy.plugins.resolver.IBiblioResolver.getDependency(IBiblioResolver.java:512)
	at org.apache.ivy.plugins.resolver.ChainResolver.getDependency(ChainResolver.java:104)
	at org.apache.ivy.core.resolve.IvyNode.loadData(IvyNode.java:169)
	at org.apache.ivy.core.resolve.VisitNode.loadData(VisitNode.java:292)
	at org.apache.ivy.core.resolve.ResolveEngine.fetchDependencies(ResolveEngine.java:714)
	at org.apache.ivy.core.resolve.ResolveEngine.doFetchDependencies(ResolveEngine.java:799)
	at org.apache.ivy.core.resolve.ResolveEngine.fetchDependencies(ResolveEngine.java:722)
	at org.apache.ivy.core.resolve.ResolveEngine.getDependencies(ResolveEngine.java:594)
	at org.apache.ivy.core.resolve.ResolveEngine.resolve(ResolveEngine.java:234)
	at xsbt.boot.Update.xsbt$boot$Update$$lockedApply(Update.scala:105)
	at xsbt.boot.Update$$anon$4.call(Update.scala:99)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at xsbt.boot.Update.apply(Update.scala:100)
	at xsbt.boot.Launch.update(Launch.scala:352)
	at xsbt.boot.Launch.xsbt$boot$Launch$$retrieve$1(Launch.scala:208)
	at xsbt.boot.Launch$$anonfun$3.apply(Launch.scala:216)
	at scala.Option.getOrElse(Option.scala:120)
	at xsbt.boot.Launch.xsbt$boot$Launch$$getAppProvider0(Launch.scala:216)
	at xsbt.boot.Launch$$anon$2.call(Launch.scala:196)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at xsbt.boot.Launch.locked(Launch.scala:238)
	at xsbt.boot.Launch.app(Launch.scala:147)
	at xsbt.boot.Launch.app(Launch.scala:145)
	at xsbt.boot.Launch$.run(Launch.scala:102)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.SecurityException: Can not initialize cryptographic mechanism
	at java.base/javax.crypto.JceSecurity.<clinit>(JceSecurity.java:118)
	... 79 more
Caused by: java.lang.SecurityException: Can't read cryptographic policy directory: unlimited
	at java.base/javax.crypto.JceSecurity.setupJurisdictionPolicies(JceSecurity.java:324)
	at java.base/javax.crypto.JceSecurity.access$000(JceSecurity.java:73)
	at java.base/javax.crypto.JceSecurity$1.run(JceSecurity.java:109)
	at java.base/javax.crypto.JceSecurity$1.run(JceSecurity.java:106)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.crypto.JceSecurity.<clinit>(JceSecurity.java:105)
	... 79 more
Error during sbt execution: java.lang.ExceptionInInitializerError
```

## expectation

No initial exception, like when I run the same command on the OpenJDK 8 image:

```
$ docker run -it java:openjdk-8 bash -c 'wget -q -O - https://dl.bintray.com/sbt/native-packages/sbt/0.13.14-RC1/sbt-0.13.14-RC1.tgz | tar zxf -; ./sbt/bin/sbt'
Getting org.scala-sbt sbt 0.13.14-RC1  (this may take some time)...
```

**Comment by eed3si9n** [comment]
Thanks for trying RC-1 and reporting the bug!

**Comment by ScalaWilliam** [comment]
Still getting the same problem with 0.13.14-RC2.

**Comment by eed3si9n** [comment]
I'm getting the following actually:

```
# /opt/sbt/bin/sbt
rsync: mkdir "/root/.sbt/preloaded" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(675) [Receiver=3.1.2]
Copying runtime jar.
Getting org.scala-sbt sbt 0.13.14-RC2  (this may take some time)...
```

Hopefully something I can fix with more `mkdir`.

**Comment by eed3si9n** [comment]
https://gist.github.com/eed3si9n/cf04771611cf7f1869f83aa5fd5d4b86

```
$ mv ~/Downloads/sbt-0.13.14.tgz ./
$ tar zxvf sbt-0.13.14.tgz
....
$ docker run -it -v /tmp/dockertest/sbt:/opt/sbt java:openjdk-9 bash
# ([[ ! -d $JAVA_HOME/conf ]] && ln -s $JAVA_HOME/lib $JAVA_HOME/conf)
# apt-get update && apt-get install -y rsync
# /opt/sbt/bin/sbt
```

**Comment by ScalaWilliam** [comment]
Still having a similar but reduced problem on 0.13.15:

```
$ docker run -it java:openjdk-9 bash -c 'wget -q -O - https://dl.bintray.com/sbt/native-packages/sbt/0.13.15/sbt-0.13.15.tgz | tar zxf -; ./sbt/bin/sbt'
Copying runtime jar.
Getting org.scala-sbt sbt 0.13.15  (this may take some time)...
java.lang.ExceptionInInitializerError
	at java.base/javax.crypto.JceSecurityManager.<clinit>(JceSecurityManager.java:65)
	at java.base/javax.crypto.Cipher.getConfiguredPermission(Cipher.java:2606)
	at java.base/javax.crypto.Cipher.getMaxAllowedKeyLength(Cipher.java:2630)
	at java.base/sun.security.ssl.CipherSuite$BulkCipher.isUnlimited(CipherSuite.java:602)
	at java.base/sun.security.ssl.CipherSuite$BulkCipher.<init>(CipherSuite.java:574)
	at java.base/sun.security.ssl.CipherSuite$BulkCipher.<clinit>(CipherSuite.java:460)
	at java.base/sun.security.ssl.CipherSuite.<clinit>(CipherSuite.java:1074)
	at java.base/sun.security.ssl.SSLContextImpl.getApplicableSupportedCipherSuiteList(SSLContextImpl.java:353)
	at java.base/sun.security.ssl.SSLContextImpl.access$100(SSLContextImpl.java:41)
	at java.base/sun.security.ssl.SSLContextImpl$AbstractTLSContext.<clinit>(SSLContextImpl.java:589)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:300)
	at java.base/java.security.Provider$Service.getImplClass(Provider.java:1844)
	at java.base/java.security.Provider$Service.newInstance(Provider.java:1820)
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
	at java.base/javax.net.ssl.SSLContext.getInstance(SSLContext.java:169)
	at java.base/javax.net.ssl.SSLContext.getDefault(SSLContext.java:99)
	at java.base/javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:123)
	at java.base/javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:332)
	at java.base/javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:289)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:86)
	at java.base/sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
	at java.base/sun.net.www.protocol.https.Handler.openConnection(Handler.java:57)
	at java.base/java.net.URL.openConnection(URL.java:1049)
	at org.apache.ivy.util.url.BasicURLHandler.getURLInfo$57a0216e(BasicURLHandler.java:66)
	at org.apache.ivy.util.url.BasicURLHandler.getURLInfo(BasicURLHandler.java:54)
	at org.apache.ivy.plugins.repository.url.URLResource.init(URLResource.java:65)
	at org.apache.ivy.plugins.repository.url.URLResource.exists(URLResource.java:81)
	at org.apache.ivy.plugins.resolver.RepositoryResolver.findResourceUsingPattern(RepositoryResolver.java:97)
	at org.apache.ivy.plugins.resolver.AbstractPatternsBasedResolver.findResourceUsingPatterns(AbstractPatternsBasedResolver.java:96)
	at org.apache.ivy.plugins.resolver.IBiblioResolver.findIvyFileRef(IBiblioResolver.java:102)
	at org.apache.ivy.plugins.resolver.BasicResolver.getDependency(BasicResolver.java:228)
	at org.apache.ivy.plugins.resolver.IBiblioResolver.getDependency(IBiblioResolver.java:512)
	at org.apache.ivy.plugins.resolver.ChainResolver.getDependency(ChainResolver.java:104)
	at org.apache.ivy.core.resolve.IvyNode.loadData(IvyNode.java:169)
	at org.apache.ivy.core.resolve.VisitNode.loadData(VisitNode.java:292)
	at org.apache.ivy.core.resolve.ResolveEngine.fetchDependencies(ResolveEngine.java:714)
	at org.apache.ivy.core.resolve.ResolveEngine.doFetchDependencies(ResolveEngine.java:799)
	at org.apache.ivy.core.resolve.ResolveEngine.fetchDependencies(ResolveEngine.java:722)
	at org.apache.ivy.core.resolve.ResolveEngine.getDependencies(ResolveEngine.java:594)
	at org.apache.ivy.core.resolve.ResolveEngine.resolve(ResolveEngine.java:234)
	at xsbt.boot.Update.xsbt$boot$Update$$lockedApply(Update.scala:105)
	at xsbt.boot.Update$$anon$4.call(Update.scala:99)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at xsbt.boot.Update.apply(Update.scala:100)
	at xsbt.boot.Launch.update(Launch.scala:352)
	at xsbt.boot.Launch.xsbt$boot$Launch$$retrieve$1(Launch.scala:208)
	at xsbt.boot.Launch$$anonfun$3.apply(Launch.scala:216)
	at scala.Option.getOrElse(Option.scala:120)
	at xsbt.boot.Launch.xsbt$boot$Launch$$getAppProvider0(Launch.scala:216)
	at xsbt.boot.Launch$$anon$2.call(Launch.scala:196)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at xsbt.boot.Launch.locked(Launch.scala:238)
	at xsbt.boot.Launch.app(Launch.scala:147)
	at xsbt.boot.Launch.app(Launch.scala:145)
	at xsbt.boot.Launch$.run(Launch.scala:102)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.SecurityException: Can not initialize cryptographic mechanism
	at java.base/javax.crypto.JceSecurity.<clinit>(JceSecurity.java:118)
	... 79 more
Caused by: java.lang.SecurityException: Can't read cryptographic policy directory: unlimited
	at java.base/javax.crypto.JceSecurity.setupJurisdictionPolicies(JceSecurity.java:324)
	at java.base/javax.crypto.JceSecurity.access$000(JceSecurity.java:73)
	at java.base/javax.crypto.JceSecurity$1.run(JceSecurity.java:109)
	at java.base/javax.crypto.JceSecurity$1.run(JceSecurity.java:106)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.crypto.JceSecurity.<clinit>(JceSecurity.java:105)
	... 79 more
Error during sbt execution: java.lang.ExceptionInInitializerError
```

**Comment by eed3si9n** [comment]
@ScalaWilliam 

You need to run

```
## https://github.com/docker-library/openjdk/issues/101
([[ ! -d $JAVA_HOME/conf ]] && ln -s $JAVA_HOME/lib $JAVA_HOME/conf)

## sbt uses rsync to sync "offline" preloaded-local repo
apt-get update && apt-get install -y rsync
```

**Comment by ScalaWilliam** [comment]
Ah I see, wasn't clear to me.

That's not going to work well form usability perspective, the point is to have a single command.
So this is the Docker image issue rather than an SBT issue.

**Comment by ScalaWilliam** [comment]
rsync thing is a great idea.

So I got it working like this [by forking](https://github.com/ScalaWilliam/scala-sbt-openjdk9) [Heiko's Docker image](https://github.com/hseeberger/scala-sbt):
```
$ docker run -it scalawilliam/scala-sbt-openjdk9 bash -c 'java -version; sbt sbtVersion'
openjdk version "9-Debian"
OpenJDK Runtime Environment (build 9-Debian+0-9b161-1)
OpenJDK 64-Bit Server VM (build 9-Debian+0-9b161-1, mixed mode)
Updated file /root/project/build.properties setting sbt.version to: 0.13.15
[warn] Executing in batch mode.
[warn]   For better performance, hit [ENTER] to switch to interactive mode, or
[warn]   consider launching sbt without any commands, or explicitly passing 'shell'
[info] Loading project definition from /root/project
[info] Updating {file:/root/project/}root-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to root (in build file:/root/)
[info] 0.13.15
```
