### ISSUE TITLE
intermittent Appender Relay0 scala.MatchError

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#3040]
## steps

This was observed on Travis CI https://travis-ci.org/sbt/sbt/jobs/214530066

```
dependency-management / snapshot-resolution
```

## problem

```
[info] [error] /tmp/sbt_5872409c/snapshot-resolution/dependent/src/main/scala/User.scala:2:18: value name is not a member of object Common (out-44) (out-1)
[info] [error]   println(Common.name) (out-44) (out-1)
[info] [error]                  ^ (out-44) (out-1)
[info] 2017-03-24 05:34:34,596 Log4j2-TF-1-AsyncLogger[AsyncContext@78691363]-1 ERROR An exception occurred processing Appender Relay0 scala.MatchError: sbt.internal.util.ObjectEvent@5fbb8fb2 (of class sbt.internal.util.ObjectEvent) (out-1)
[info] 	at sbt.internal.RelayAppender.appendEvent(RelayAppender.scala:33) (out-1)
[info] 	at sbt.internal.RelayAppender.append(RelayAppender.scala:22) (out-1)
[info] 	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156) (out-1)
[info] 	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129) (out-1)
[info] 	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120) (out-1)
[info] 	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84) (out-1)
[info] 	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:447) (out-1)
[info] 	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:432) (out-1)
[info] 	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:416) (out-1)
[info] 	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:79) (out-1)
[info] 	at org.apache.logging.log4j.core.async.AsyncLogger.actualAsyncLog(AsyncLogger.java:331) (out-1)
[info] 	at org.apache.logging.log4j.core.async.RingBufferLogEvent.execute(RingBufferLogEvent.java:150) (out-1)
[info] 	at org.apache.logging.log4j.core.async.RingBufferLogEventHandler.onEvent(RingBufferLogEventHandler.java:45) (out-1)
[info] 	at org.apache.logging.log4j.core.async.RingBufferLogEventHandler.onEvent(RingBufferLogEventHandler.java:29) (out-1)
[info] 	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:129) (out-1)
[info] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) (out-1)
[info] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) (out-1)
[info] 	at java.lang.Thread.run(Thread.java:745) (out-1)
[info]  (out-1)
```

### note

It works on my machine when I run the test alone.

**Comment by dwijnand** [comment]
Fixed in https://github.com/sbt/sbt/pull/3066/commits/304d167813b96d319eaed8c02d7b10978a14accc
