### ISSUE TITLE
illegal IPv4 address while resolving dependency

### ISSUE THREAD

**Issue by daologger** [sbt/sbt#3059]
(See the guidelines for contributing, linked above)

## steps

1. set up an Artifactory virtual repository that mirrors these 3 sbt repository:

```
http://dl.bintray.com/typesafe/ivy-releases/
http://dl.bintray.com/typesafe/maven-releases/
http://dl.bintray.com/sbt/sbt-plugin-releases/
```

This repository server is broadcasted using mDNS service, with a local domain `sbtdomain.local.`. Its IPv4 address is `192.168.1.100`, Artifactory repo service running on port `8080`.

2. install sbt on OS X with `brew install sbt` (version: stable 0.13.13, devel 1.0.0-M4)
3. in `$HOME/.sbt/` directory, create a repositories file:

```
[repositories]
local
maven-local
central-maven-proxy-releases: http://sbtdomain.local.:8080/artifactory/central-mirror/
my-ivy-proxy-releases: http://sbtdomain.local.:8080/artifactory/sbt/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
my-maven-proxy-releases: http://sbtdomain.local.:8080/artifactory/sbt
```

4. navigate to `$HOME/sbt` directory, a freshly created, empty directory, and run `sbt`

## problem

While resolving dependency `org.scala-lang#jline;2.10.6`, the following error occurs:

```
[info] Loading global plugins from /Users/sbtuser/.sbt/0.13/plugins
[info] Updating {file:/Users/sbtuser/.sbt/0.13/plugins/}global-plugins...
[info] Resolving org.scala-lang#jline;2.10.6 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.scala-lang#jline;2.10.6: several problems occurred while resolving dependency: org.scala-lang#jline;2.10.6 {optional=[compile(*), master(*)]}:
[warn] 	illegal IPv4 address
[warn] 	illegal IPv4 address
[warn] 	illegal IPv4 address
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.scala-lang:jline:2.10.6
[warn] 		  +- org.scala-lang:scala-compiler:2.10.6
[warn] 		  +- org.scala-sbt:classpath:0.13.13
[warn] 		  +- org.scala-sbt:incremental-compiler:0.13.13
[warn] 		  +- org.scala-sbt:persist:0.13.13
[warn] 		  +- org.scala-sbt:compiler-integration:0.13.13
[warn] 		  +- org.scala-sbt:actions:0.13.13
[warn] 		  +- org.scala-sbt:main:0.13.13
[warn] 		  +- org.scala-sbt:sbt:0.13.13
[warn] 		  +- org.scala-sbt:global-plugins:0.0 (scalaVersion=2.10, sbtVersion=0.13)
sbt.ResolveException: unresolved dependency: org.scala-lang#jline;2.10.6: several problems occurred while resolving dependency: org.scala-lang#jline;2.10.6 {optional=[compile(*), master(*)]}:
	illegal IPv4 address
	illegal IPv4 address
	illegal IPv4 address

	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:128)
	at sbt.IvySbt.withIvy(Ivy.scala:125)
	at sbt.IvySbt$Module.withModule(Ivy.scala:156)
	at sbt.IvyActions$.updateEither(IvyActions.scala:168)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1481)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1477)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1512)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1510)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1515)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1509)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1532)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1459)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1411)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: org.scala-lang#jline;2.10.6: several problems occurred while resolving dependency: org.scala-lang#jline;2.10.6 {optional=[compile(*), master(*)]}:
[error] 	illegal IPv4 address
[error] 	illegal IPv4 address
[error] 	illegal IPv4 address
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? i
[warn] Ignoring load failure: no project loaded.
```

## expectation

expect no warning or error information

## notes

When I change the `repositories` file's content by replacing the local domain `sbtdomain.local.` with its relevant IPv4 address, and run `sbt` again, the warning and error info disappears.

```
[repositories]
local
maven-local
central-maven-proxy-releases: http://192.168.1.100:8080/artifactory/central-mirror/
my-ivy-proxy-releases: http://192.168.1.100:8080/artifactory/sbt/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
my-maven-proxy-releases: http://192.168.1.100:8080/artifactory/sbt
```

It seems that while resolving some dependencies, some underlying module of sbt is assuming that the target address should be a IPv4 address instead of a domain.

**Comment by eed3si9n** [comment]
```
http://sbtdomain.local.:8080/artifactory/central-mirror/
```

Could the problem be because of the URI formatting? I think it's a valid URI syntax, but maybe sbt (its underlying dependency manager Ivy) is incorrectly assuming that it's an IPv4 address.
Could you try with "http://sbtdomain.local:8080/artifactory/central-mirror/" instead without the dot after `local`?

**Comment by daologger** [comment]
@eed3si9n Yeah, removing the dot after `local` did solve the issue. Thanks!

**Comment by cunei** [comment]
This could be a bug in some versions of the JDK; see for instance https://bugs.openjdk.java.net/browse/JDK-8139899
I just tried locally, and all worked ok (1.8.0_171-b11):
```
[warn] ==== rover: tried
[warn]   http://topo.gigio.:8088/artifactory/repo/aa/ii/9.1/ii-9.1.pom
```
Unless we can reproduce it with a recent JDK, this ticket can probably be closed.

**Comment by dwijnand** [comment]
> Unless we can reproduce it with a recent JDK, this ticket can probably be closed.
