### ISSUE TITLE
sbt 0.13.14 doesn't run on Windows

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#3086]
If you came here by Googling "URI has an authority component", see https://github.com/sbt/sbt/pull/3088 for URL encoding of file path on Windows.

----

## steps

run sbt 0.13.14 on Windows

## problem

```
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
WARN: No sbt.version set in project/build.properties, base directory: C:\cygwin64\home\bgdev
[warn] Executing in batch mode.
[warn]   For better performance, hit [ENTER] to switch to interactive mode, or
[warn]   consider launching sbt without any commands, or explicitly passing 'shell'
java.lang.IllegalArgumentException: URI has an authority component
        at java.io.File.<init>(File.java:423)
        at sbt.Classpaths$.sbt$Classpaths$$bootRepository(Defaults.scala:1942)
        at sbt.Classpaths$$anonfun$appRepositories$1.apply(Defaults.scala:1912)
        at sbt.Classpaths$$anonfun$appRepositories$1.apply(Defaults.scala:1912)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at sbt.Classpaths$.appRepositories(Defaults.scala:1912)
        at sbt.Classpaths$$anonfun$58.apply(Defaults.scala:1193)
        at sbt.Classpaths$$anonfun$58.apply(Defaults.scala:1190)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
        at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
        at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
        at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] java.lang.IllegalArgumentException: URI has an authority component
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

## notes

This is likely due to the way offline repo is specified.

- http://stackoverflow.com/questions/18520972/converting-java-file-url-to-file-path-platform-independent-including-u
- http://stackoverflow.com/questions/2366270/what-does-uri-has-an-authority-component-mean
- Ref https://github.com/sbt/sbt/issues/564
- Possible duplicate of https://github.com/sbt/sbt/issues/2150

**Comment by dejan2609** [comment]
I just upgraded from sbt  **0.13.12** to sbt **0.13.15**: build works as expected (on Windows 10).
Thanx @eed3si9n !

**Comment by eed3si9n** [comment]
The buggy part was the launcher so you have to test https://bintray.com/sbt/native-packages/download_file?file_path=sbt%2F0.13.15%2Fsbt-0.13.15.msi.

**Comment by dejan2609** [comment]
Tested, all green.

![image](https://cloud.githubusercontent.com/assets/19467899/24841904/649bb992-1d8f-11e7-9fdb-f1cfc7b932ab.png)

**Comment by eed3si9n** [comment]
Thank you!
