### ISSUE TITLE
ClassNotFoundException: xsbt.CompilerInterface

### ISSUE THREAD

**Issue by olafurpg** [sbt/sbt#3124]
I hit on an unexpected exception while trying to create an sbt-scalafmt plugin for sbt 1.0.0-M5.

## steps
(on OSX java version "1.8.0_102" and sbt 0.13.15)

- clone https://github.com/olafurpg/scalafmt/tree/sbt-1.0 (single commit https://github.com/scalameta/scalafmt/commit/4a5aa605321214e7474a8a3c0221179d8e178033)
- run `sbt scalafmtSbt1/compile`

```
[debug] [naha] Recompiling all 67 sources: invalidated sources (67) exceeded 50.0% of all sources
[info] Compiling 67 Scala sources to /Users/ollie/dev/scalafmt/core/target/scala-2.12/classes...
[debug] Getting org.scala-sbt:compiler-interface:1.0.0-M5:component from component compiler for Scala 2.12.2
java.lang.ClassNotFoundException: xsbt.CompilerInterface
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at sbt.compiler.AnalyzingCompiler.getInterfaceClass(AnalyzingCompiler.scala:128)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:104)
	at sbt.compiler.AnalyzingCompiler.newCachedCompiler(AnalyzingCompiler.scala:62)
	at sbt.compiler.AnalyzingCompiler.newCachedCompiler(AnalyzingCompiler.scala:57)
	at sbt.compiler.CompilerCache$$anon$2.apply(CompilerCache.scala:47)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:45)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:74)
	at sbt.compiler.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:49)
	at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:64)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
```

## expectation
I expected the project to compile without exceptions.

## notes

I followed the instructions [here](http://developer.lightbend.com/blog/2017-04-18-sbt-1-0-roadmap-and-beta1/#cross-building-sbt-1-0-plugin-from-sbt-0-13) on how to cross-build plugins. However, I don't need to cross-build my plugin, I want to create a plugin for sbt 1.0.0-M5 from scratch.

**Comment by dwijnand** [comment]
Does your setup include

```scala
scalaCompilerBridgeSource :=
  ("org.scala-sbt" % "compiler-interface" % "0.13.15" % "component").sources
```

?

**Comment by olafurpg** [comment]
Yes https://github.com/scalameta/scalafmt/commit/4a5aa605321214e7474a8a3c0221179d8e178033#diff-fdc3abdfd754eeb24090dbd90aeec2ceR107 but only for the `sbt-scalafmt1` project, not the `core` project which `sbt-scalafmt1` depends on. Should `scalaCompilerBridgeSource` be enabled in all projects that `sbt-scalafmt1` depends on?

**Comment by olafurpg** [comment]
I can confirm that adding

```scala
scalaCompilerBridgeSource :=
  ("org.scala-sbt" % "compiler-interface" % "0.13.15" % "component").sources
```
to the shared build settings resolves the issue. Thank you!

This could be a good entry to mention in the cross-building docs. Feel free to close this issue.

**Comment by dwijnand** [comment]
Perhaps we should advise to set `sbtVersion := "1.0.0-M5"` rather than `sbtVersion in Global := "1.0.0-M5"`...

**Comment by eed3si9n** [comment]
Without `in Global` you'd get another error.

I've created instruction page here - http://www.scala-sbt.org/1.0/docs/Cross-Build-Plugins.html

**Comment by olafurpg** [comment]
@eed3si9n Those docs should mention that `scalaCompilerBridgeSource` needs to be set in all projects in the build that the sbt plugin depends on, not only the sbt plugin settings. That was the cause of confusion for me in this issue, see https://github.com/sbt/sbt/issues/3124#issuecomment-295415844

**Comment by eed3si9n** [comment]
Changed the instruction a bit to cover that case:

```diff
+3. Append the following settings to your plugin project (and any other subprojects that it depends):
```

https://github.com/sbt/website/commit/b4ba9440c5d3244091cec59039af8572bc61babe
