### ISSUE TITLE
zinc crashes when a CompilationUnit is added by a compiler plugin

### ISSUE THREAD

**Issue by Atry** [sbt/sbt#3260]
## steps

Create the following files:

### project/build.properties
```
sbt.version=0.13.15
```

### build.sbt
``` sbt
libraryDependencies += "org.scala-lang" % "scala-compiler" % scalaVersion.value % Provided

scalacOptions in Test += "-Xplugin:" + (packageBin in Compile).value

scalaVersion := "2.12.2"
```

### src/main/resources/scalac-plugin.xml
``` xml
<plugin>
    <name>myplugin</name>
    <classname>myplugin.MyPlugin</classname>
</plugin>
```

### src/main/scala/myplugin/MyPlugin.scala
``` scala
package myplugin

import scala.tools.nsc.Global
import scala.tools.nsc.plugins.{Plugin, PluginComponent}

final class MyPlugin(override val global: Global) extends Plugin {

  override val name: String = "myplugin"

  override val components: List[PluginComponent] = List(
    new PluginComponent {
      override val global: Global = MyPlugin.this.global
      import global._
      override val phaseName: String = MyPlugin.this.name
      override val runsAfter: List[String] = List("parser")

      override def newPhase(prev: scala.tools.nsc.Phase) = new StdPhase(prev) {

        override def apply(unit: CompilationUnit): Unit = {
          if (!currentRun.units.exists(_.source.file.name == "<generated compilation unit>")) {
            currentRun.compileLate(newCompilationUnit("package generatedpackage; class GeneratedClass", "<generated compilation unit>"))
          }
        }

      }
    }
  )
  override val description: String = "A plugin that generate a new compilation unit"
}
```
### src/test/scala/myplugin/Test.scala
```scala
package myplugin

object Test extends generatedpackage.GeneratedClass with App {
  println("Hello, World!")
}

```
## problem

```
$ sbt
[info] Loading global plugins from /Users/twer/.sbt/0.13/plugins
[info] Loading project definition from /private/tmp/generate-compilation-unit/project
[info] Set current project to generate-compilation-unit (in build file:/private/tmp/generate-compilation-unit/)
> test:compile
[info] Updating {file:/private/tmp/generate-compilation-unit/}generate-compilation-unit...
[info] Resolving jline#jline;2.14.3 ...
[info] Done updating.
[info] Compiling 1 Scala source to /private/tmp/generate-compilation-unit/target/scala-2.12/classes...
[info] Packaging /private/tmp/generate-compilation-unit/target/scala-2.12/generate-compilation-unit_2.12-0.1-SNAPSHOT.jar ...
[info] Done packaging.
[info] Compiling 1 Scala source to /private/tmp/generate-compilation-unit/target/scala-2.12/test-classes...
[trace] Stack trace suppressed: run last test:compileIncremental for the full output.
[error] (test:compileIncremental) java.lang.NullPointerException
[error] Total time: 6 s, completed Jun 12, 2017 1:25:09 PM
> last test:compileIncremental
[debug] [naha] 
[debug] [naha] Initial source changes: 
[debug] [naha] 	removed:Set()
[debug] [naha] 	added: Set(/private/tmp/generate-compilation-unit/src/test/scala/myplugin/Test.scala)
[debug] [naha] 	modified: Set()
[debug] [naha] Invalidated products: Set()
[debug] [naha] External API changes: API Changes: Set()
[debug] [naha] Modified binary dependencies: Set()
[debug] [naha] Initial directly invalidated sources: Set(/private/tmp/generate-compilation-unit/src/test/scala/myplugin/Test.scala)
[debug] [naha] 
[debug] [naha] Sources indirectly invalidated by:
[debug] [naha] 	product: Set()
[debug] [naha] 	binary dep: Set()
[debug] [naha] 	external source: Set()
[debug] All initially invalidated sources: Set(/private/tmp/generate-compilation-unit/src/test/scala/myplugin/Test.scala)
[debug] [naha] Initial set of included nodes: Set(/private/tmp/generate-compilation-unit/src/test/scala/myplugin/Test.scala)
[debug] [naha] Recompiling all 1 sources: invalidated sources (1) exceeded 50.0% of all sources
[info] Compiling 1 Scala source to /private/tmp/generate-compilation-unit/target/scala-2.12/test-classes...
[debug] Getting org.scala-sbt:compiler-interface:0.13.15:component from component compiler for Scala 2.12.2
[debug] Getting org.scala-sbt:compiler-interface:0.13.15:component from component compiler for Scala 2.12.2
[debug] Running cached compiler 42fa9469, interfacing (CompilerInterface) with Scala compiler version 2.12.2
[debug] Calling Scala compiler with arguments  (CompilerInterface):
[debug] 	-Xplugin:/private/tmp/generate-compilation-unit/target/scala-2.12/generate-compilation-unit_2.12-0.1-SNAPSHOT.jar
[debug] 	-bootclasspath
[debug] 	/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/classes:/Users/twer/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.12.2.jar
[debug] 	-classpath
[debug] 	/private/tmp/generate-compilation-unit/target/scala-2.12/test-classes:/private/tmp/generate-compilation-unit/target/scala-2.12/classes:/Users/twer/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.12.2.jar:/Users/twer/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.12.2.jar:/Users/twer/.ivy2/cache/org.scala-lang.modules/scala-xml_2.12/bundles/scala-xml_2.12-1.0.6.jar
java.lang.NullPointerException
	at sbt.inc.AnalysisCallback.api(Compile.scala:191)
	at xsbt.API$ApiPhase.processScalaUnit(API.scala:54)
	at xsbt.API$ApiPhase.processUnit(API.scala:38)
	at xsbt.API$ApiPhase.apply(API.scala:36)
	at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:423)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:416)
	at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1(Global.scala:387)
	at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1$adapted(Global.scala:387)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:387)
	at xsbt.API$ApiPhase.run(API.scala:31)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1427)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1412)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1407)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1501)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:116)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:107)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:53)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:74)
	at sbt.compiler.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:49)
	at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:64)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
	at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:32)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:72)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:71)
	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:99)
	at sbt.inc.Incremental$.compile(Incremental.scala:71)
	at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
	at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
	at sbt.Compiler$.compile(Compiler.scala:155)
	at sbt.Compiler$.compile(Compiler.scala:141)
	at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:886)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:877)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:875)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[error] (test:compileIncremental) java.lang.NullPointerException
```

## expectation

It does not crash

## notes

The compiler plugin itself works with ordinary Scalac without sbt.
``` bash
scalac src/test/scala/myplugin/Test.scala -Xplugin:target/scala-2.12/generate-compilation-unit_2.12-0.1-SNAPSHOT.jar
```

sbt version: *0.13.15*

**Comment by jvican** [comment]
@Atry Can you please add a pending scripted test case in https://github.com/sbt/zinc? I'll have a look and see what I can do to fix it.

**Comment by Atry** [comment]
I don't know how to make it a scripted test in that repository, though I can provide the minimized reproducible project here: [generate-complation-unit.zip](https://github.com/sbt/sbt/files/1067430/generate-complation-unit.zip)

**Comment by jvican** [comment]
Great, so you can use that to create one. You can use `trait-super` as a source of inspiration or any scripted tests that has a file `pending`. All the scripted tests are placed in `zinc/src/sbt-test`.
  
I will add official instructions to do so in the Zinc repository. It's true that this should be covered by the CONTRIBUTING guidelines.

**Comment by Atry** [comment]
If the generated compilation unit points to a regular file, zinc does not crash.
However, zinc always recompiles the project, regardless if the file is present in `sources` or not.

**Comment by jvican** [comment]
Do you mean you cannot reproduce with scripted @Atry? I didn't quite get your message.

**Comment by Atry** [comment]
I was talking about another issue that may be related to this one, when replacing `"<generated compilation unit>"` to a regular file.
