### ISSUE TITLE
Autocompletion for ++2.12.x doesn't work

### ISSUE THREAD

**Issue by jvican** [sbt/sbt#3276]
## steps
This is for sbt 1.0.0-M6.
Type `++2.12.2<TAB>`.

## problem

```
> ++2.12.2 java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:349)
	at scala.None$.get(Option.scala:347)
	at sbt.internal.util.complete.FileExamples.$anonfun$files$1(ExampleSource.scala:53)
	at scala.collection.immutable.Stream.map(Stream.scala:415)
	at sbt.internal.util.complete.FileExamples.files(ExampleSource.scala:53)
	at sbt.internal.util.complete.FileExamples.apply(ExampleSource.scala:47)
	at sbt.internal.util.complete.FileExamples.apply(ExampleSource.scala:46)
	at sbt.internal.util.complete.ParserWithExamples.completions(Parser.scala:731)
	at sbt.internal.util.complete.MapParser.completions(Parser.scala:655)
	at sbt.internal.util.complete.SeqParser.completions(Parser.scala:593)
	at sbt.internal.util.complete.MapParser.completions(Parser.scala:655)
	at sbt.internal.util.complete.SeqParser.completions(Parser.scala:593)
	at sbt.internal.util.complete.MapParser.completions(Parser.scala:655)
	at sbt.internal.util.complete.MapParser.completions(Parser.scala:655)
	at sbt.internal.util.complete.HomParser.completions(Parser.scala:601)
	at sbt.internal.util.complete.HomParser.completions(Parser.scala:601)
	at sbt.internal.util.complete.HomParser.completions(Parser.scala:601)
	at sbt.internal.util.complete.HomParser.completions(Parser.scala:601)
	at sbt.internal.util.complete.HomParser.completions(Parser.scala:601)
	at sbt.internal.util.complete.SeqParser.completions(Parser.scala:593)
	at sbt.internal.util.complete.MapParser.completions(Parser.scala:655)
	at sbt.internal.util.complete.MapParser.completions(Parser.scala:655)
	at sbt.internal.util.complete.HomParser.completions(Parser.scala:601)
	at sbt.internal.util.complete.BindParser.$anonfun$completions$4(Parser.scala:636)
	at sbt.internal.util.complete.Completions.$anonfun$flatMap$2(Completions.scala:20)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:320)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:976)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at sbt.internal.util.complete.Completions.$anonfun$flatMap$1(Completions.scala:20)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
	at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
	at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
	at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
	at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
	at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
	at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
	at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
	at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
	at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
	at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
	at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
	at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
	at sbt.internal.util.complete.Completions.$anonfun$map$1(Completions.scala:21)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
	at sbt.internal.util.complete.Completions.$anonfun$flatMap$2(Completions.scala:20)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:95)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at sbt.internal.util.complete.Completions.$anonfun$flatMap$1(Completions.scala:20)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
	at sbt.internal.util.complete.TokenCompletions$$anon$5.$anonfun$completions$2(TokenCompletions.scala:36)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
	at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
	at sbt.internal.util.complete.Completions.$anonfun$flatMap$1(Completions.scala:20)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
	at sbt.internal.util.complete.JLineCompletion$.convertCompletions(JLineCompletion.scala:57)
	at sbt.internal.util.complete.JLineCompletion$.$anonfun$parserAsCompletor$1(JLineCompletion.scala:53)
	at sbt.internal.util.complete.JLineCompletion$.$anonfun$parserAsCompletor$1$adapted(JLineCompletion.scala:53)
	at sbt.internal.util.complete.JLineCompletion$.$anonfun$customCompletor$2(JLineCompletion.scala:76)
	at sbt.internal.util.complete.JLineCompletion$.complete(JLineCompletion.scala:95)
	at sbt.internal.util.complete.JLineCompletion$.$anonfun$customCompletor$1(JLineCompletion.scala:76)
	at sbt.internal.util.complete.JLineCompletion$.$anonfun$customCompletor$1$adapted(JLineCompletion.scala:75)
	at sbt.internal.util.complete.JLineCompletion$CustomHandler.complete(JLineCompletion.scala:31)
	at jline.console.ConsoleReader.complete(ConsoleReader.java:3313)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2648)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2373)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2361)
	at sbt.internal.util.JLine.readLineDirectRaw(LineReader.scala:44)
	at sbt.internal.util.JLine.$anonfun$readLineDirect$2(LineReader.scala:35)
	at sbt.internal.util.Signals0.withHandler(Signal.scala:82)
	at sbt.internal.util.Signals$.withHandler(Signal.scala:11)
	at sbt.internal.util.JLine.readLineDirect(LineReader.scala:35)
	at sbt.internal.util.JLine.readLineWithHistory(LineReader.scala:28)
	at sbt.internal.util.JLine.unsynchronizedReadLine(LineReader.scala:21)
	at sbt.internal.util.JLine.$anonfun$readLine$1(LineReader.scala:18)
	at sbt.internal.util.JLine$.$anonfun$withJLine$1(LineReader.scala:128)
	at sbt.internal.util.JLine$.withTerminal(LineReader.scala:100)
	at sbt.internal.util.JLine$.withJLine(LineReader.scala:126)
	at sbt.internal.util.JLine.readLine(LineReader.scala:18)
	at sbt.internal.ConsoleChannel$$anon$1.run(ConsoleChannel.scala:21)

Exception occurred while determining completions.
```

## expectation
Autocomplete with keys in the current project.

## notes

sbt version: sbt 1.0.0-M6

**Comment by dwijnand** [comment]
Hey @jvican. I had a look and I can't reproduce it in an empty project.

From looking at the code it's something to do with a series of files and using `IO.relativize`, aggressively with `Option#get`: https://github.com/sbt/util/blob/v1.0.0-M24/internal/util-complete/src/main/scala/sbt/internal/util/complete/ExampleSource.scala#L53

Could you please provide a more complete minimisation?

**Comment by eed3si9n** [comment]
I can reproduce this by typing in `++2.12.2<TAB>`.

**Comment by dwijnand** [comment]
Reproducible with sbt/io at https://github.com/sbt/io/commit/880de81bcc9bd4308885d2515d0a1b746026b946.
