### ISSUE TITLE
Tapping [escape] multiple times in the shell throws an exception in sbt 1.0.0-M6

### ISSUE THREAD

**Issue by Duhemm** [sbt/sbt#3286]
## steps
- start sbt 1.0.0-M6
- Press [escape] twice

## problem
- An exception in thrown

## expectation
- Nothing happens

## notes
```
[info] Loading settings from house.sbt,nightlies.sbt ...
[info] Loading project definition from /Users/martin/Documents/Projects.nosync/Duhemm/io/project
[info] Loading settings from build.sbt ...
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[info] Set current project to IO Root (in build file:/Users/martin/Documents/Projects.nosync/Duhemm/io/)
[info] sbt server started at 127.0.0.1:5038
> java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:349)
        at scala.None$.get(Option.scala:347)
        at sbt.internal.util.complete.FileExamples.$anonfun$files$1(ExampleSource.scala:53)
        at scala.collection.immutable.Stream.map(Stream.scala:415)
        at sbt.internal.util.complete.FileExamples.files(ExampleSource.scala:53)
        at sbt.internal.util.complete.FileExamples.apply(ExampleSource.scala:47)
        at sbt.internal.util.complete.FileExamples.apply(ExampleSource.scala:46)
        at sbt.internal.util.complete.ParserWithExamples.completions(Parser.scala:731)
        at sbt.internal.util.complete.MapParser.completions(Parser.scala:655)
        at sbt.internal.util.complete.SeqParser.completions(Parser.scala:593)
        at sbt.internal.util.complete.MapParser.completions(Parser.scala:655)
        at sbt.internal.util.complete.SeqParser.completions(Parser.scala:593)
        at sbt.internal.util.complete.MapParser.completions(Parser.scala:655)
        at sbt.internal.util.complete.MapParser.completions(Parser.scala:655)
        at sbt.internal.util.complete.HomParser.completions(Parser.scala:601)
        at sbt.internal.util.complete.HomParser.completions(Parser.scala:601)
        at sbt.internal.util.complete.HomParser.completions(Parser.scala:601)
        at sbt.internal.util.complete.HomParser.completions(Parser.scala:601)
        at sbt.internal.util.complete.HomParser.completions(Parser.scala:601)
        at sbt.internal.util.complete.SeqParser.completions(Parser.scala:593)
        at sbt.internal.util.complete.MapParser.completions(Parser.scala:655)
        at sbt.internal.util.complete.MapParser.completions(Parser.scala:655)
        at sbt.internal.util.complete.HomParser.completions(Parser.scala:601)
        at sbt.internal.util.complete.BindParser.$anonfun$completions$4(Parser.scala:636)
        at sbt.internal.util.complete.Completions.$anonfun$flatMap$2(Completions.scala:20)
        at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
        at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:320)
        at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:976)
        at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
        at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
        at sbt.internal.util.complete.Completions.$anonfun$flatMap$1(Completions.scala:20)
        at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
        at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
        at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
        at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
        at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
        at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
        at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
        at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
        at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
        at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
        at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
        at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
        at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
        at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
        at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
        at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
        at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
        at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
        at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
        at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
        at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
        at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
        at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
        at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
        at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
        at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
        at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
        at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
        at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
        at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
        at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
        at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
        at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
        at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
        at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
        at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
        at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
        at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
        at sbt.internal.util.complete.Completions.$anonfun$flatMap$1(Completions.scala:20)
        at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
        at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
        at sbt.internal.util.complete.JLineCompletion$.convertCompletions(JLineCompletion.scala:57)
        at sbt.internal.util.complete.JLineCompletion$.$anonfun$parserAsCompletor$1(JLineCompletion.scala:53)
        at sbt.internal.util.complete.JLineCompletion$.$anonfun$parserAsCompletor$1$adapted(JLineCompletion.scala:53)
        at sbt.internal.util.complete.JLineCompletion$.$anonfun$customCompletor$2(JLineCompletion.scala:76)
        at sbt.internal.util.complete.JLineCompletion$.complete(JLineCompletion.scala:95)
        at sbt.internal.util.complete.JLineCompletion$.$anonfun$customCompletor$1(JLineCompletion.scala:76)
        at sbt.internal.util.complete.JLineCompletion$.$anonfun$customCompletor$1$adapted(JLineCompletion.scala:75)
        at sbt.internal.util.complete.JLineCompletion$CustomHandler.complete(JLineCompletion.scala:31)
        at jline.console.ConsoleReader.complete(ConsoleReader.java:3313)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2648)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2373)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2361)
        at sbt.internal.util.JLine.readLineDirectRaw(LineReader.scala:44)
        at sbt.internal.util.JLine.$anonfun$readLineDirect$2(LineReader.scala:35)
        at sbt.internal.util.Signals0.withHandler(Signal.scala:82)
        at sbt.internal.util.Signals$.withHandler(Signal.scala:11)
        at sbt.internal.util.JLine.readLineDirect(LineReader.scala:35)
        at sbt.internal.util.JLine.readLineWithHistory(LineReader.scala:28)
        at sbt.internal.util.JLine.unsynchronizedReadLine(LineReader.scala:21)
        at sbt.internal.util.JLine.$anonfun$readLine$1(LineReader.scala:18)
        at sbt.internal.util.JLine$.$anonfun$withJLine$1(LineReader.scala:128)
        at sbt.internal.util.JLine$.withTerminal(LineReader.scala:100)
        at sbt.internal.util.JLine$.withJLine(LineReader.scala:126)
        at sbt.internal.util.JLine.readLine(LineReader.scala:18)
        at sbt.internal.ConsoleChannel$$anon$1.run(ConsoleChannel.scala:21)

Exception occurred while determining completions.
```

sbt version: 1.0.0-M6

**Comment by dwijnand** [comment]
Looks to be the same stack as #3276.

**Comment by dwijnand** [comment]
Like #3276, I can't reproduce this either. @Duhemm could you please provide a more complete minimisation?

**Comment by eed3si9n** [comment]
## steps

I have the following `~/.inputrc` to emulate vim mode in the sbt shell:

```
$ cat ~/.inputrc
set editing-mode vi
set keyseq-timeout 10
set show-mode-in-prompt on
set skip-completed-text on
set vi-cmd-mode-string :
set vi-ins-mode-string +
set visible-stats on

$if mode=vi
  set keymap vi-command
  "gg": beginning-of-history
  "G": end-of-history

  set keymap vi-insert
  "jj": vi-movement-mode
  "\C-p": history-search-backward
  "\C-l": clear-screen
$endif
```

Next I open up sbt, and tap escape key three times.

### symptom

```
> java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:349)
	at scala.None$.get(Option.scala:347)
	at sbt.internal.util.complete.FileExamples.$anonfun$files$1(ExampleSource.scala:53)
	at scala.collection.immutable.Stream.map(Stream.scala:415)
	at sbt.internal.util.complete.FileExamples.files(ExampleSource.scala:53)
	at sbt.internal.util.complete.FileExamples.apply(ExampleSource.scala:47)
	at sbt.internal.util.complete.FileExamples.apply(ExampleSource.scala:46)
	at sbt.internal.util.complete.ParserWithExamples.completions(Parser.scala:731)
	at sbt.internal.util.complete.MapParser.completions(Parser.scala:655)
	at sbt.internal.util.complete.SeqParser.completions(Parser.scala:593)
	at sbt.internal.util.complete.MapParser.completions(Parser.scala:655)
	at sbt.internal.util.complete.SeqParser.completions(Parser.scala:593)
	at sbt.internal.util.complete.MapParser.completions(Parser.scala:655)
	at sbt.internal.util.complete.MapParser.completions(Parser.scala:655)
	at sbt.internal.util.complete.HomParser.completions(Parser.scala:601)
	at sbt.internal.util.complete.HomParser.completions(Parser.scala:601)
	at sbt.internal.util.complete.HomParser.completions(Parser.scala:601)
	at sbt.internal.util.complete.HomParser.completions(Parser.scala:601)
	at sbt.internal.util.complete.HomParser.completions(Parser.scala:601)
	at sbt.internal.util.complete.SeqParser.completions(Parser.scala:593)
	at sbt.internal.util.complete.MapParser.completions(Parser.scala:655)
	at sbt.internal.util.complete.MapParser.completions(Parser.scala:655)
	at sbt.internal.util.complete.HomParser.completions(Parser.scala:601)
	at sbt.internal.util.complete.BindParser.$anonfun$completions$4(Parser.scala:636)
	at sbt.internal.util.complete.Completions.$anonfun$flatMap$2(Completions.scala:20)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:320)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:976)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at sbt.internal.util.complete.Completions.$anonfun$flatMap$1(Completions.scala:20)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
	at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
	at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
	at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
	at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
	at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
	at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
	at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
	at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
	at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
	at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
	at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
	at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:15)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
	at sbt.internal.util.complete.Completions.$anonfun$flatMap$1(Completions.scala:20)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:28)
	at sbt.internal.util.complete.JLineCompletion$.convertCompletions(JLineCompletion.scala:57)
	at sbt.internal.util.complete.JLineCompletion$.$anonfun$parserAsCompletor$1(JLineCompletion.scala:53)
	at sbt.internal.util.complete.JLineCompletion$.$anonfun$parserAsCompletor$1$adapted(JLineCompletion.scala:53)
	at sbt.internal.util.complete.JLineCompletion$.$anonfun$customCompletor$2(JLineCompletion.scala:76)
	at sbt.internal.util.complete.JLineCompletion$.complete(JLineCompletion.scala:95)
	at sbt.internal.util.complete.JLineCompletion$.$anonfun$customCompletor$1(JLineCompletion.scala:76)
	at sbt.internal.util.complete.JLineCompletion$.$anonfun$customCompletor$1$adapted(JLineCompletion.scala:75)
	at sbt.internal.util.complete.JLineCompletion$CustomHandler.complete(JLineCompletion.scala:31)
	at jline.console.ConsoleReader.complete(ConsoleReader.java:3313)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2648)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2373)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2361)
	at sbt.internal.util.JLine.readLineDirectRaw(LineReader.scala:44)
	at sbt.internal.util.JLine.$anonfun$readLineDirect$2(LineReader.scala:35)
	at sbt.internal.util.Signals0.withHandler(Signal.scala:82)
	at sbt.internal.util.Signals$.withHandler(Signal.scala:11)
	at sbt.internal.util.JLine.readLineDirect(LineReader.scala:35)
	at sbt.internal.util.JLine.readLineWithHistory(LineReader.scala:28)
	at sbt.internal.util.JLine.unsynchronizedReadLine(LineReader.scala:21)
	at sbt.internal.util.JLine.$anonfun$readLine$1(LineReader.scala:18)
	at sbt.internal.util.JLine$.$anonfun$withJLine$1(LineReader.scala:128)
	at sbt.internal.util.JLine$.withTerminal(LineReader.scala:100)
	at sbt.internal.util.JLine$.withJLine(LineReader.scala:126)
	at sbt.internal.util.JLine.readLine(LineReader.scala:18)
	at sbt.internal.ConsoleChannel$$anon$1.run(ConsoleChannel.scala:21)

Exception occurred while determining completions.
```

I am not sure what hitting escape multiple times is sending to the JLine, but the error is reproduced.

**Comment by Duhemm** [comment]
Could you try in sbt/io (escape twice)? Or tab just once? I guess it sends the same thing.

**Comment by dwijnand** [comment]
Cool, I can reproduce in sbt/io, thanks.

**Comment by dwijnand** [comment]
So, reproducible with sbt/io at https://github.com/sbt/io/commit/880de81bcc9bd4308885d2515d0a1b746026b946.
