### ISSUE TITLE
No stack traces when there is a failure when loading the build in sbt 1.0.0-RC2

### ISSUE THREAD

**Issue by sjrd** [sbt/sbt#3343]
(See the guidelines for contributing, linked above)

## steps

`build.sbt`
```scala
ivyConfigurations += Configuration.of("invalid-config-id", "config-name")
```
`project/build.properties`
```
sbt.version=1.0.0-RC2
```
Start sbt:
```
$ sbt
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=768M; support was removed in 8.0
[info] Loading settings from plugins.sbt ...

[info] Loading project definition from /localhome/doeraene/projects/sbt-test/project

[info] Updating {file:/localhome/doeraene/projects/sbt-test/project/}sbt-test-build...

[info] :: loading settings :: url = jar:file:/home/doeraene/.sbt/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-RC2/ivy-2.3.0-sbt-a3314352b638afbf0dca19f127e8263ed6f898bd.jar!/org/apache/ivy/core/settings/ivysettings.xml

[info] :: loading settings :: url = jar:file:/home/doeraene/.sbt/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-RC2/ivy-2.3.0-sbt-a3314352b638afbf0dca19f127e8263ed6f898bd.jar!/org/apache/ivy/core/settings/ivysettings.xml

[info] :: loading settings :: url = jar:file:/home/doeraene/.sbt/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-RC2/ivy-2.3.0-sbt-a3314352b638afbf0dca19f127e8263ed6f898bd.jar!/org/apache/ivy/core/settings/ivysettings.xml

[info] :: loading settings :: url = jar:file:/home/doeraene/.sbt/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-RC2/ivy-2.3.0-sbt-a3314352b638afbf0dca19f127e8263ed6f898bd.jar!/org/apache/ivy/core/settings/ivysettings.xml

[info] :: loading settings :: url = jar:file:/home/doeraene/.sbt/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-RC2/ivy-2.3.0-sbt-a3314352b638afbf0dca19f127e8263ed6f898bd.jar!/org/apache/ivy/core/settings/ivysettings.xml

[info] :: loading settings :: url = jar:file:/home/doeraene/.sbt/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-RC2/ivy-2.3.0-sbt-a3314352b638afbf0dca19f127e8263ed6f898bd.jar!/org/apache/ivy/core/settings/ivysettings.xml

[info] :: loading settings :: url = jar:file:/home/doeraene/.sbt/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-RC2/ivy-2.3.0-sbt-a3314352b638afbf0dca19f127e8263ed6f898bd.jar!/org/apache/ivy/core/settings/ivysettings.xml

[info] :: loading settings :: url = jar:file:/home/doeraene/.sbt/boot/scala-2.12.2/org.scala-sbt/sbt/1.0.0-RC2/ivy-2.3.0-sbt-a3314352b638afbf0dca19f127e8263ed6f898bd.jar!/org/apache/ivy/core/settings/ivysettings.xml

[info] Done updating.

[info] Loading settings from build.sbt ...

[error] java.lang.IllegalArgumentException: requirement failed: oops, it's broken

[error]         at scala.Predef$.require(Predef.scala:277)

[error]         at $1b9490c6b8fed6bb8245$.$anonfun$$sbtdef$1(/localhome/doeraene/projects/sbt-test/build.sbt:2)

[error]         at $1b9490c6b8fed6bb8245$$$Lambda$2893/306678606.apply(Unknown Source)

[error] java.lang.IllegalArgumentException: requirement failed: oops, it's broken

[error] Use 'last' for the full log.

Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
[info] Loading settings from plugins.sbt ...

[info] Loading project definition from /localhome/doeraene/projects/sbt-test/project

[info] Loading settings from build.sbt ...

[error] java.lang.IllegalArgumentException: requirement failed: id must be capitalized: invalid-config-id

[error]         at scala.Predef$.require(Predef.scala:277)

[error] java.lang.IllegalArgumentException: requirement failed: id must be capitalized: invalid-config-id

[error] Use 'last' for the full log.

Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```
Ask for `last`:
```
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? l
[debug] > Exec(reload, None, None)

[debug] > Exec(sbtStashOnFailure, None, None)

[debug] > Exec(onFailure load-failed, None, None)

[debug] > Exec(loadp, None, None)

[debug]   Load.defaultLoad until apply took 1.683325ms

[debug]             Load.loadUnit: plugins took 6.866281ms

[debug]             Load.loadUnit: defsScala took 0.004032ms

[debug] [Loading] Scanning directory /localhome/doeraene/projects/sbt-test/project

[debug]               Load.loadUnit: mkEval took 0.077302ms

[debug] [Loading] Found non-root projects 

[debug] [Loading] Done in /localhome/doeraene/projects/sbt-test/project, returning: ()

[debug] deducing auto plugins based on known facts Set(Atom(sbt.plugins.CorePlugin)) and clauses Clauses(List(Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.IvyPlugin))), Clause(Atom(sbt.plugins.JUnitXmlReportPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.CorePlugin),Set(Atom(sbt.plugins.IvyPlugin))), Clause(Atom(sbt.plugins.IvyPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.JUnitXmlReportPlugin))), Clause(Atom(sbt.plugins.CorePlugin),Set(Atom(sbt.plugins.Giter8TemplatePlugin)))))

[debug]   :: deduced result: Matched(sbt.plugins.CorePlugin,sbt.plugins.Giter8TemplatePlugin,sbt.plugins.IvyPlugin,sbt.plugins.JvmPlugin,sbt.plugins.JUnitXmlReportPlugin)

[debug] Plugins.deducer#function took 0.617172 ms

[info] Loading settings from plugins.sbt ...

[debug]                 Load.resolveProject(sbt-test-build) took 0.521254ms

[debug]               Load.loadTransitive: finalizeProject2(Project(id sbt-test-build, base: /localhome/doeraene/projects/sbt-test/project, plugins: List(<none>))) took 1.449211ms

[debug] [Loading] Done in /localhome/doeraene/projects/sbt-test/project, returning: (sbt-test-build)

[debug]             Load.loadUnit: loadedProjectsRaw took 2.83495ms

[debug]             Load.loadUnit: cleanEvalClasses took 0.009106ms

[debug]           Load.loadUnit(file:/localhome/doeraene/projects/sbt-test/project/, ...) took 10.22698ms

[debug]         Load.apply: load took 10.71777ms

[debug]         Load.apply: resolveProjects took 0.108563ms

[debug]         Load.apply: finalTransforms took 3.32166ms

[debug]         Load.apply: config.delegates took 0.288158ms

[debug]         Load.apply: Def.make(settings)... took 39.32875ms

[debug]         Load.apply: structureIndex took 26.962739ms

[debug]         Load.apply: mkStreams took 0.003626ms

[info] Loading project definition from /localhome/doeraene/projects/sbt-test/project

[debug] Running task... Cancel: Null, check cycles: false, forcegc: true

[debug] Forcing garbage collection...

[debug]       Load.loadUnit: plugins took 784.117223ms

[debug]       Load.loadUnit: defsScala took 0.002806ms

[debug] [Loading] Scanning directory /localhome/doeraene/projects/sbt-test

[debug]         Load.loadUnit: mkEval took 0.059556ms

[debug] [Loading] Found non-root projects 

[debug] [Loading] Done in /localhome/doeraene/projects/sbt-test, returning: ()

[debug] deducing auto plugins based on known facts Set(Atom(sbt.plugins.CorePlugin)) and clauses Clauses(List(Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.IvyPlugin))), Clause(Atom(sbt.plugins.JUnitXmlReportPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.CorePlugin),Set(Atom(sbt.plugins.IvyPlugin))), Clause(Atom(sbt.plugins.IvyPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.JUnitXmlReportPlugin))), Clause(Atom(sbt.plugins.CorePlugin),Set(Atom(sbt.plugins.Giter8TemplatePlugin)))))

[debug]   :: deduced result: Matched(sbt.plugins.CorePlugin,sbt.plugins.Giter8TemplatePlugin,sbt.plugins.IvyPlugin,sbt.plugins.JvmPlugin,sbt.plugins.JUnitXmlReportPlugin)

[debug] Plugins.deducer#function took 0.723269 ms

[info] Loading settings from build.sbt ...

[debug]           Load.resolveProject(sbt-test) took 0.558075ms

[debug]         Load.loadTransitive: finalizeProject2(Project(id sbt-test, base: /localhome/doeraene/projects/sbt-test, plugins: List(<none>))) took 1.634104ms

[debug] [Loading] Done in /localhome/doeraene/projects/sbt-test, returning: (sbt-test)

[debug]       Load.loadUnit: loadedProjectsRaw took 424.372153ms

[debug]       Load.loadUnit: cleanEvalClasses took 0.271779ms

[debug]     Load.loadUnit(file:/localhome/doeraene/projects/sbt-test/, ...) took 1209.245591ms

[debug]   Load.apply: load took 1210.086984ms

[debug]   Load.apply: resolveProjects took 0.077084ms

[debug]   Load.apply: finalTransforms took 2.722649ms

[debug]   Load.apply: config.delegates took 0.271453ms

[error] java.lang.IllegalArgumentException: requirement failed: id must be capitalized: invalid-config-id

[error]         at scala.Predef$.require(Predef.scala:277)

[error] java.lang.IllegalArgumentException: requirement failed: id must be capitalized: invalid-config-id

[error] Use 'last' for the full log.

[debug] > Exec(load-failed, None, None)

[debug] > Exec(last, None, None)
```
## problem

There is no stack trace whatsoever, including when I ask for `last`.

Note that if I directly call `require(false, "boom")` from my `build.sbt`, I get a *somewhat* longer stacktrace.

If I diagnose correctly, sbt truncates the stack trace as soon as it reaches sbt internals, or something like that, which is really not helping.

## expectation

I expect the (whole) stack trace to be displayed.

## notes

sbt version: *1.0.0-RC2*

Note also how the output *without* `last` is ridiculously spammy, giving me all sorts of information I don't care about.

**Comment by eed3si9n** [comment]
After various log-related cleanups my locally built SNAPSHOT looks like this:

```
$ sbt
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512M; support was removed in 8.0
[info] Loading settings from plugins.sbt ...
[error] java.lang.IllegalArgumentException: requirement failed: id must be capitalized: invalid-config-id
[error] 	at scala.Predef$.require(Predef.scala:277)
[error] java.lang.IllegalArgumentException: requirement failed: id must be capitalized: invalid-config-id
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```
