### ISSUE TITLE
sbt new doesn't work on sbt 1.0.0-RC2

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#3355]
## steps

```
$ brew unlink sbt
$ brew install --devel sbt
$ sbt new sbt/sbt-autoplugin.g8
```

## problem

```
$ sbt new sbt/sbt-autoplugin.g8

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512M; support was removed in 8.0
[info] Set current project to work (in build file:/Users/eed3si9n/work/)

[error] java.lang.ClassNotFoundException: sbtgiter8resolver.Giter8TemplateResolver

[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)

[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)

[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

[error] 	at java.lang.Class.forName0(Native Method)

[error] 	at java.lang.Class.forName(Class.java:348)

[error] java.lang.ClassNotFoundException: sbtgiter8resolver.Giter8TemplateResolver

[error] Use 'last' for the full log.
```

## expectation

new works.

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/3364
