### ISSUE TITLE
SBT hangs when trying to replace the `exportedProducts` with the result of an `assembly`

### ISSUE THREAD

**Issue by christian-schlichtherle** [sbt/sbt#3373]
I am using SBT 0.13.15 and sbt-assembly 0.14.5. I'm using the `assembly` task to create an uber JAR which contains a shaded version of ASM with no problems. I have a multi-project build and I want other projects in this build to depend on the resulting uber JAR instead of the compiled class files.

I have created a minified example to reproduce the issue: [test.zip](https://github.com/sbt/sbt/files/1176415/test.zip)

In this minified example, the first project `foo` uses the following settings to replace the exported products with the result of the assembly:

```scala
exportJars := true

exportedProducts in Compile := Seq(Attributed.blank(assembly.value))
```

The second project `bar` simply depends on the first project `foo`. When trying to call `foo/exportedProducts`, sbt hangs after doing the packaging.

```sh
$ sbt foo/exportedProducts
[warn] Executing in batch mode.
[warn]   For better performance, hit [ENTER] to switch to interactive mode, or
[warn]   consider launching sbt without any commands, or explicitly passing 'shell'
[info] Loading global plugins from /Users/christian/.sbt/0.13/plugins
[info] Updating {file:/Users/christian/.sbt/0.13/plugins/}global-plugins...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Loading project definition from /Users/christian/sandbox/test/project
[info] Updating {file:/Users/christian/sandbox/test/project/}test-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to root (in build file:/Users/christian/sandbox/test/)
[info] Updating {file:/Users/christian/sandbox/test/}foo...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 1 Scala source to /Users/christian/sandbox/test/foo/target/scala-2.10/classes...
[info] Packaging /Users/christian/sandbox/test/foo/target/scala-2.10/foo_2.10-0.1-SNAPSHOT.jar ...
[info] Done packaging.
```

I suspected the problem might be caused by recursion, but I could not find any sign of recursion in the source code of the sbt-assembly plugin, nor do I get a `StackOverflowError`. Instead sbt hangs while waiting for some element to appear in a queue. Here's the relevant part of the thread dump:

```java
"main" #1 prio=5 os_prio=31 tid=0x00007f8c06002000 nid=0x1c03 waiting on condition [0x000070000fc27000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007acb3c100> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ExecutorCompletionService.take(ExecutorCompletionService.java:193)
	at sbt.ConcurrentRestrictions$$anon$4.take(ConcurrentRestrictions.scala:188)
	at sbt.Execute.next$1(Execute.scala:85)
	at sbt.Execute.processAll(Execute.scala:88)
	at sbt.Execute.runKeep(Execute.scala:68)
	at sbt.EvaluateTask$.liftedTree1$1(EvaluateTask.scala:359)
	at sbt.EvaluateTask$.run$1(EvaluateTask.scala:358)
	at sbt.EvaluateTask$.runTask(EvaluateTask.scala:378)
	at sbt.Aggregation$$anonfun$3.apply(Aggregation.scala:69)
	at sbt.Aggregation$$anonfun$3.apply(Aggregation.scala:67)
	at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:314)
	at sbt.Aggregation$.timedRun(Aggregation.scala:67)
	at sbt.Aggregation$.runTasks(Aggregation.scala:76)
	at sbt.Aggregation$$anonfun$applyTasks$1.apply(Aggregation.scala:37)
	at sbt.Aggregation$$anonfun$applyTasks$1.apply(Aggregation.scala:36)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Aggregation$$anonfun$evaluatingParser$4$$anonfun$apply$5.apply(Aggregation.scala:158)
	at sbt.Aggregation$$anonfun$evaluatingParser$4$$anonfun$apply$5.apply(Aggregation.scala:157)
	at sbt.Act$$anonfun$sbt$Act$$actParser0$1$$anonfun$sbt$Act$$anonfun$$evaluate$1$1$$anonfun$apply$10.apply(Act.scala:253)
	at sbt.Act$$anonfun$sbt$Act$$actParser0$1$$anonfun$sbt$Act$$anonfun$$evaluate$1$1$$anonfun$apply$10.apply(Act.scala:250)
	at sbt.Command$.process(Command.scala:93)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.State$$anon$1.doX$1(State.scala:183)
	at sbt.State$$anon$1.process(State.scala:190)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:96)
	at sbt.MainLoop$.run(MainLoop.scala:89)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
	at sbt.MainLoop$.runLogged(MainLoop.scala:22)
	at sbt.StandardMain$.runManaged(Main.scala:109)
	at sbt.xMain.run(Main.scala:38)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
```

My approach to do this may be entirely wrong but my expectation is that SBT should never hang.

I've created a question on stackoverflow.com: [How to replace the exported products with the result of an assembly in SBT?](https://stackoverflow.com/questions/45309474/how-to-replace-the-exported-products-with-the-result-of-an-assembly-in-sbt)

**Comment by christian-schlichtherle** [comment]
I've also tried the minified example with SBT 1.0.0-RC2, but it made no difference.

**Comment by christian-schlichtherle** [comment]
I think there is some recursion involved between `assembly` and `packageBin` and it's not being detected by SBT because in `Defaults.scala`, the `exportedProducts` setting is defined using a `Def.taskDyn` macro, which executes another macro. Apparently, the recursion detection doesn't work recursively, or in other words: Too much macro magic will kill you!

**Comment by eed3si9n** [comment]
sbt exposes all settings and tasks to be rewired by the build user, but we don't recommend rewiring them unless you can figure things out on your own from reading the source. The deadlock is more of design limitation on the task engine, and I don't think it's to do with the use of macro.

**Comment by christian-schlichtherle** [comment]
So you say there is a deadlock caused by a design limitation and you want to do nothing about it?

**Comment by eed3si9n** [comment]
Deadlock is directly caused by two tasks mutually waiting on each other. Detecting that is not on my priority. It would be nice if had all the resource to fix these corner cases, but we don't.
