### ISSUE TITLE
NoSuchMethodError with 0.13.16 + scripted + Scala 2.12

### ISSUE THREAD

**Issue by dilation** [sbt/sbt#3394]
## steps

1. Start `sbt` in this example project: https://github.com/dilation/test-scripted
1. `scripted`

## problem

It fails with a `NoSuchMethodError`:
```
> scripted
[info] Packaging .../test-scripted/target/scala-2.12/test-scripted_2.12-0.1.0-SNAPSHOT-sources.jar ...
[info] Done packaging.
[info] Wrote .../test-scripted/target/scala-2.12/test-scripted_2.12-0.1.0-SNAPSHOT.pom
[info] Writing Ivy file .../test-scripted/target/scala-2.12/resolution-cache/default/test-scripted_2.12/0.1.0-SNAPSHOT/resolved.xml.xml
[info] :: delivering :: default#test-scripted_2.12;0.1.0-SNAPSHOT :: 0.1.0-SNAPSHOT :: integration :: Mon Jul 31 11:46:17 CEST 2017
[info] Packaging .../test-scripted/target/scala-2.12/test-scripted_2.12-0.1.0-SNAPSHOT-javadoc.jar ...
[info] Done packaging.
[info] Packaging .../test-scripted/target/scala-2.12/test-scripted_2.12-0.1.0-SNAPSHOT.jar ...
[info] Done packaging.
[info]  delivering ivy file to .../test-scripted/target/scala-2.12/ivy-0.1.0-SNAPSHOT.xml
[info]  published test-scripted_2.12 to .../.ivy2/local/default/test-scripted_2.12/0.1.0-SNAPSHOT/poms/test-scripted_2.12.pom
[info]  published test-scripted_2.12 to .../.ivy2/local/default/test-scripted_2.12/0.1.0-SNAPSHOT/jars/test-scripted_2.12.jar
[info]  published test-scripted_2.12 to .../.ivy2/local/default/test-scripted_2.12/0.1.0-SNAPSHOT/srcs/test-scripted_2.12-sources.jar
[info]  published test-scripted_2.12 to .../.ivy2/local/default/test-scripted_2.12/0.1.0-SNAPSHOT/docs/test-scripted_2.12-javadoc.jar
[info]  published ivy to .../.ivy2/local/default/test-scripted_2.12/0.1.0-SNAPSHOT/ivys/ivy.xml
[trace] Stack trace suppressed: run last *:scripted for the full output.
[error] (*:scripted) java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps;
[error] Total time: 1 s, completed Jul 31, 2017 11:46:17 AM
> last *:scripted
java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps;
        at sbt.test.ListTests.listTests(ScriptedTests.scala:180)
        at sbt.test.ScriptedRunner.listTests(ScriptedTests.scala:161)
        at sbt.test.ScriptedRunner.get(ScriptedTests.scala:159)
        at sbt.test.ScriptedRunner.run(ScriptedTests.scala:147)
        at sbt.test.ScriptedRunner.run(ScriptedTests.scala:125)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sbt.ScriptedPlugin$$anonfun$scriptedTask$1$$anonfun$apply$6$$anonfun$apply$7.apply(ScriptedPlugin.scala:93)
        at sbt.ScriptedPlugin$$anonfun$scriptedTask$1$$anonfun$apply$6$$anonfun$apply$7.apply(ScriptedPlugin.scala:89)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[error] (*:scripted) java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps;
>
```

## expectation

It shouldn't fail with a `NoSuchMethodError`.

## notes

sbt version: 0.13.16

If `scalaVersion` is 2.11, it seems to work fine:
```
> scripted
[info] Packaging .../test-scripted/target/scala-2.11/test-scripted_2.11-0.1.0-SNAPSHOT-sources.jar ...
[info] Done packaging.
[info] Writing Ivy file .../test-scripted/target/scala-2.11/resolution-cache/default/test-scripted_2.11/0.1.0-SNAPSHOT/resolved.xml.xml
[info] Wrote .../test-scripted/target/scala-2.11/test-scripted_2.11-0.1.0-SNAPSHOT.pom
[info] :: delivering :: default#test-scripted_2.11;0.1.0-SNAPSHOT :: 0.1.0-SNAPSHOT :: integration :: Mon Jul 31 11:50:50 CEST 2017
[info]  delivering ivy file to .../test-scripted/target/scala-2.11/ivy-0.1.0-SNAPSHOT.xml
[info] Packaging .../test-scripted/target/scala-2.11/test-scripted_2.11-0.1.0-SNAPSHOT-javadoc.jar ...
[info] Done packaging.
[info] Packaging .../test-scripted/target/scala-2.11/test-scripted_2.11-0.1.0-SNAPSHOT.jar ...
[info] Done packaging.
[info]  published test-scripted_2.11 to .../.ivy2/local/default/test-scripted_2.11/0.1.0-SNAPSHOT/poms/test-scripted_2.11.pom
[info]  published test-scripted_2.11 to .../.ivy2/local/default/test-scripted_2.11/0.1.0-SNAPSHOT/jars/test-scripted_2.11.jar
[info]  published test-scripted_2.11 to .../.ivy2/local/default/test-scripted_2.11/0.1.0-SNAPSHOT/srcs/test-scripted_2.11-sources.jar
[info]  published test-scripted_2.11 to .../.ivy2/local/default/test-scripted_2.11/0.1.0-SNAPSHOT/docs/test-scripted_2.11-javadoc.jar
[info]  published ivy to .../.ivy2/local/default/test-scripted_2.11/0.1.0-SNAPSHOT/ivys/ivy.xml
Running foo / bar
[success] Total time: 13 s, completed Jul 31, 2017 11:51:03 AM
>
```

**Comment by dwijnand** [comment]
I'm not sure why scripted isn't failing you for 2.11 too, but basically sbt 0.13, and its scripted plugin, only supports 2.10.
