### ISSUE TITLE
sbt-1.0.0-RC3 publish command produces malformed ivy XML

### ISSUE THREAD

**Issue by xerial** [sbt/sbt#3412]
## steps
- Checkout this branch: https://github.com/xerial/sbt-sql/pull/12
- Run `sbt publishLocal`
- cat -n ~/.ivy2/local/org.xerial.sbt/sbt-sql-base/scala_2.12/sbt_1.0/0.7-SNAPSHOT/ivys/ivy.xml
...

## problem
The generated Ivy XML file contains invalid `conf` element. This should have no child elements (should produce `<conf .... />` instead of `<conf ...> .... </conf>`:
```
     1	<?xml version="1.0" encoding="UTF-8"?>
     2	<ivy-module version="2.0" xmlns:e="http://ant.apache.org/ivy/extra">
     3	  <info organisation="org.xerial.sbt" module="sbt-sql-base" revision="0.7-SNAPSHOT" status="integration" publication="20170808095218" e:sbtVersion="1.0" e:scalaVersion="2.12">
     4	    <description/>
     5	</info>
     6	  <configurations>
     7	    <conf name="plugin" visibility="public" description=""/>
     8	    <conf name="pom" visibility="public" description=""/>
     9	    <conf extends="runtime" name="test" visibility="public" description=""/>
    10	    <conf name="provided" visibility="public" description=""/>
    11	    <conf extends="compile,optional,provided" name="compile-internal" visibility="public" description="">    
           <----------- (conf tag is not closed here and contains an empty string element)
    12	</conf> 
         ....
    25      </configurations>
```

When trying to use sbt-sql-xxx plugin in some project, the following error is shown:
```
[error] sbt.librarymanagement.ResolveException: unresolved dependency: org.xerial.sbt#sbt-sql-td;0.7-SNAPSHOT: java.text.ParseException: [xml parsing: ivy.xml:12:8: cvc-complex-type.2.1: Element 'conf' must have no character or element information item [children], because the type's content type is empty. in file:/Users/leo/.ivy2/local/org.xerial.sbt/sbt-sql-td/scala_2.12/sbt_1.0/0.7-SNAPSHOT/ivys/ivy.xml
[error] , xml parsing: ivy.xml:18:8: cvc-complex-type.2.1: Element 'conf' must have no character or element information item [children], because the type's content type is empty. in file:/Users/leo/.ivy2/local/org.xerial.sbt/sbt-sql-td/scala_2.12/sbt_1.0/0.7-SNAPSHOT/ivys/ivy.xml
[error] , xml parsing: ivy.xml:24:8: cvc-complex-type.2.1: Element 'conf' must have no character or element information item [children], because the type's content type is empty. in file:/Users/leo/.ivy2/local/org.xerial.sbt/sbt-sql-td/scala_2.12/sbt_1.0/0.7-SNAPSHOT/ivys/ivy.xml
[error] ]
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:331)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:205)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:229)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:190)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:185)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:182)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:228)
[error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:190)
[error] 	at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:38)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:91)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:64)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:104)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:104)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:87)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:141)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:118)
[error] 	at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2313)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[error] 	at sbt.Execute.work(Execute.scala:266)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:748)
```

`sbt scripted` also fails. It seems the root cause is the above malformed Ivy XML data:
```[error]  Cause of test exception: {line 1}  Command failed: Remote sbt initialization failed
Running sbt-sql-td / target
[error] java.io.FileNotFoundException: /var/folders/x6/fvytrfnn38564n3j6cg4jrc40000gn/T/sbt_b902b073/target/test (No such file or directory)
[error]         at java.io.FileInputStream.open0(Native Method)
[error]         at java.io.FileInputStream.open(FileInputStream.java:195)
[error]         at java.io.FileInputStream.<init>(FileInputStream.java:138)
[error]         at sbt.io.Using$.$anonfun$fileInputStream$1(Using.scala:74)
[error]         at sbt.io.Using$$anon$2.openImpl(Using.scala:66)
[error]         at sbt.io.OpenFile.open(Using.scala:43)
[error]         at sbt.io.OpenFile.open$(Using.scala:38)
[error]         at sbt.io.Using$$anon$2.open(Using.scala:65)
[error]         at sbt.io.Using$$anon$2.open(Using.scala:65)
[error]         at sbt.io.Using.apply(Using.scala:22)
[error]         at sbt.io.IO$.transfer(IO.scala:293)
[error]         at sbt.io.IO$.read(IO.scala:721)
[error]         at sbt.internal.scripted.TestScriptParser.parse(TestScriptParser.scala:44)
[error]         at sbt.test.ScriptedTests.$anonfun$commonRunTest$5(ScriptedTests.scala:270)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error]         at sbt.test.ScriptedTests.commonRunTest(ScriptedTests.scala:266)
[error]         at sbt.test.ScriptedTests.$anonfun$singleScriptedTest$5(ScriptedTests.scala:59)
[error]         at sbt.test.ScriptedTests.runOrHandleDisabled(ScriptedTests.scala:224)
[error]         at sbt.test.ScriptedTests.$anonfun$singleScriptedTest$4(ScriptedTests.scala:61)
[error]         at sbt.internal.io.Resources.readWrite$1(Resources.scala:57)
[error]         at sbt.internal.io.Resources.$anonfun$readWriteResourceDirectory$1(Resources.scala:59)
[error]         at sbt.io.IO$.withTemporaryDirectory(IO.scala:332)
[error]         at sbt.io.IO$.withTemporaryDirectory(IO.scala:340)
[error]         at sbt.internal.io.Resources.readWriteResourceDirectory(Resources.scala:59)
[error]         at sbt.internal.io.Resources.readWriteResourceDirectory(Resources.scala:47)
[error]         at sbt.test.ScriptedTests.$anonfun$singleScriptedTest$3(ScriptedTests.scala:53)
[error]         at sbt.test.ScriptedRunner.$anonfun$runAll$1(ScriptedTests.scala:393)
[error]         at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
[error]         at scala.collection.mutable.ArraySeq.foreach(ArraySeq.scala:74)
[error]         at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
[error]         at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
[error]         at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
[error]         at sbt.test.ScriptedRunner.runAll(ScriptedTests.scala:393)
[error]         at sbt.test.ScriptedRunner.run(ScriptedTests.scala:348)
[error]         at sbt.test.ScriptedRunner.run(ScriptedTests.scala:317)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at sbt.ScriptedPlugin$.$anonfun$scriptedTask$3(ScriptedPlugin.scala:139)
[error]         at sbt.ScriptedPlugin$.$anonfun$scriptedTask$3$adapted(ScriptedPlugin.scala:128)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:64)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[error]         at sbt.Execute.work(Execute.scala:266)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (sbt-sql-td/*:scripted) java.io.FileNotFoundException: /var/folders/x6/fvytrfnn38564n3j6cg4jrc40000gn/T/sbt_b902b073/target/test (No such file or directory)
```

## expectation
- sbt-1.0.0-RC3 should produce valid ivy-module XML format data

## notes

sbt version: *1.0.0-RC3*

**Comment by eed3si9n** [comment]
I grabbed your branch but at first I was not able to compile because Coursier failed:

```
[error] coursier.ResolutionException: 1 not found
[error]     /Users/xxx/.sbt/preloaded/org.scala-lang.modules/scala-parser-combinators_2.12/1.0.4/bundles/scala-parser-combinators_2.12.jar
```

so I commented Coursier out,

```scala
// addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-RC9")
```

and published local without it. Here's my ivy.xml:

```
$ cat -n ~/.ivy2/local/org.xerial.sbt/sbt-sql-base/scala_2.12/sbt_1.0/0.7-SNAPSHOT/ivys/ivy.xml
     1	<?xml version="1.0" encoding="UTF-8"?>
     2	<ivy-module version="2.0" xmlns:e="http://ant.apache.org/ivy/extra">
     3		<info organisation="org.xerial.sbt" module="sbt-sql-base" revision="0.7-SNAPSHOT" status="integration" publication="20170808132013" e:sbtVersion="1.0" e:scalaVersion="2.12">
     4			<license name="Apache-2.0" url="https://www.apache.org/licenses/LICENSE-2.0.html"/>
     5			<description>
     6			A sbt plugin for generating model classes from SQL files
     7			</description>
     8		</info>
     9		<configurations>
    10			<conf name="compile" visibility="public" description=""/>
    11			<conf name="runtime" visibility="public" description="" extends="compile"/>
    12			<conf name="test" visibility="public" description="" extends="runtime"/>
    13			<conf name="provided" visibility="public" description=""/>
    14			<conf name="optional" visibility="public" description=""/>
    15			<conf name="compile-internal" visibility="private" description="" extends="compile,optional,provided"/>
    16			<conf name="runtime-internal" visibility="private" description="" extends="runtime,optional"/>
    17			<conf name="test-internal" visibility="private" description="" extends="test,optional,provided"/>
    18			<conf name="plugin" visibility="private" description=""/>
    19			<conf name="pom" visibility="public" description=""/>
    20			<conf name="scala-tool" visibility="private" description=""/>
    21			<conf name="scripted-sbt" visibility="private" description=""/>
    22			<conf name="scripted-sbt-launch" visibility="private" description=""/>
    23		</configurations>
    24		<publications>
    25			<artifact name="sbt-sql-base" type="pom" ext="pom" conf="pom"/>
    26			<artifact name="sbt-sql-base" type="jar" ext="jar" conf="compile"/>
    27			<artifact name="sbt-sql-base" type="src" ext="jar" conf="compile" e:classifier="sources"/>
    28			<artifact name="sbt-sql-base" type="doc" ext="jar" conf="compile" e:classifier="javadoc"/>
    29		</publications>
    30		<dependencies>
    31			<dependency org="org.scala-lang" name="scala-compiler" rev="2.12.3" conf="scala-tool->default,optional(default);compile->default(compile)"/>
    32			<dependency org="org.scala-lang" name="scala-library" rev="2.12.3" conf="scala-tool->default,optional(default);provided->default(compile)"/>
    33			<dependency org="org.scala-sbt" name="sbt" rev="1.0.0-RC3" conf="provided->default(compile)"/>
    34			<dependency org="org.scala-sbt" name="scripted-sbt_2.12" rev="1.0.0-RC3" conf="scripted-sbt->default(compile)"/>
    35			<dependency org="org.scala-sbt" name="sbt-launch" rev="1.0.0-RC3" conf="scripted-sbt-launch->default(compile)"/>
    36			<dependency org="org.xerial" name="xerial-lens_2.12" rev="3.6.0" conf="compile->default(compile)"/>
    37			<dependency org="org.scalatest" name="scalatest_2.12" rev="3.0.1" conf="test->default(compile)"/>
    38			<dependency org="com.facebook.presto" name="presto-jdbc" rev="0.163" conf="test->default(compile)"/>
    39		</dependencies>
    40	</ivy-module>
```

Here's the compile-internal in question:

```
<conf name="compile-internal" visibility="private" description="" extends="compile,optional,provided"/>
```

I am not sure if this is the problem with sbt or something else?

**Comment by xerial** [comment]
@eed3si9n Thanks for checking. I was using sbt-extra script https://github.com/xerial/sbt-sql/blob/master/sbt, but as you did, if I use brew-installed sbt command, the produced XML format ~seems valid~. (Sorry for the confusion. The produced XML was still invalid) 

I'll update sbt script first.

**Comment by xerial** [comment]
After upgrading sbt-extras script, this problem is gone. Thanks for the help. I never imagined sbt scripts can cause such a problem.

**Comment by xerial** [comment]
@eed3si9n FYI. After several attempts to reproduce this issue, I've figured it out it was actually caused by sbt-coursier plugin, which is supposed not to work with sbt-1.0 for now, but worked somehow in my environment. Removing this plugin resolves this malformed XML issue:
`// addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-RC9")`
