### ISSUE TITLE
SBT 1.0 crash - java.lang.VerifyError: Uninitialized object exists on backward branch 

### ISSUE THREAD

**Issue by Arnauld** [sbt/sbt#3471]
(See the guidelines for contributing, linked above)

## steps

* MacOS Sierra
* Download last sbt 1.0 version (tar.gz or brew install)
* tar has been unarchied in `~/dev/sbt`
* On the purpose on initialize a new project (`sbt new sbt/scala-seed.g8`), execute `sbt -v` on an empty folder

## problem

```
 ~/bin/sbt -v
[process_args] java_version = '1.8'
# Executing command line:
java
-Xms1024m
-Xmx1024m
-XX:ReservedCodeCacheSize=128m
-XX:MaxMetaspaceSize=256m
-jar
/Users/Arnauld/dev/sbt/bin/sbt-launch.jar

java.lang.VerifyError: Uninitialized object exists on backward branch 162
Exception Details:
  Location:
    scala/util/matching/Regex.unapplySeq(Lscala/util/matching/Regex$Match;)Lscala/Option; @216: goto
  Reason:
    Error exists in the bytecode
  Bytecode:
    0000000: 2bc6 000a 2bb6 00ef c700 07b2 0052 b02b
    0000010: b600 f2b6 00f3 2ab6 0054 4d59 c700 0b57
    0000020: 2cc6 000d a700 c92c b600 f799 00c2 bb00
    0000030: 6059 b200 65b2 006a 043e c700 0501 bf1d
    0000040: 2bb6 00f8 b600 74b6 0078 2bba 0100 0000
    0000050: b200 93b6 0097 3a06 3a05 59c7 0005 01bf
    0000060: 3a04 1906 b200 93b6 009b a600 7619 04b2
    0000070: 00a0 a600 09b2 00a0 a700 71bb 00a2 5919
    0000080: 04b6 00a8 3a0b 2b19 0bb8 00fc b200 a0b7
    0000090: 00ac 3a07 1907 3a08 1904 b600 afc0 00a4
    00000a0: 3a09 1909 b200 a0a5 0034 bb00 a259 1909
    00000b0: b600 a83a 0b2b 190b b800 fcb2 00a0 b700
    00000c0: ac3a 0a19 0819 0ab6 00b3 190a 3a08 1909
    00000d0: b600 afc0 00a4 3a09 a7ff ca19 07a7 000c
    00000e0: 1904 1905 1906 b800 b9b7 00bc b02a 2bb6
    00000f0: 00ef b601 02b0
  Stackmap Table:
    same_frame(@11)
    same_frame(@15)
    full_frame(@39,{Object[#2],Object[#34],Object[#86]},{Object[#86]})
    same_frame(@46)
    full_frame(@63,{Object[#2],Object[#34],Object[#86],Integer},{Uninitialized[#46],Uninitialized[#46],Object[#98]})
    full_frame(@96,{Object[#2],Object[#34],Object[#86],Integer,Top,Object[#206],Object[#208]},{Uninitialized[#46],Uninitialized[#46],Object[#164]})
    full_frame(@123,{Object[#2],Object[#34],Object[#86],Integer,Object[#164],Object[#206],Object[#208]},{Uninitialized[#46],Uninitialized[#46]})
    full_frame(@162,{Object[#2],Object[#34],Object[#86],Integer,Object[#164],Object[#206],Object[#208],Object[#162],Object[#162],Object[#164],Top,Object[#4]},{Uninitialized[#46],Uninitialized[#46]})
    full_frame(@219,{Object[#2],Object[#34],Object[#86],Integer,Object[#164],Object[#206],Object[#208],Object[#162],Object[#162],Object[#164],Top,Object[#4]},{Uninitialized[#46],Uninitialized[#46]})
    full_frame(@224,{Object[#2],Object[#34],Object[#86],Integer,Object[#164],Object[#206],Object[#208]},{Uninitialized[#46],Uninitialized[#46]})
    full_frame(@233,{Object[#2],Object[#34],Object[#86],Integer,Object[#164],Object[#206],Object[#208]},{Uninitialized[#46],Uninitialized[#46],Object[#4]})
    full_frame(@237,{Object[#2],Object[#34],Object[#86]},{})

	at scala.collection.immutable.StringLike.r(StringLike.scala:281)
	at scala.collection.immutable.StringLike.r$(StringLike.scala:281)
	at scala.collection.immutable.StringOps.r(StringOps.scala:29)
	at scala.collection.immutable.StringLike.r(StringLike.scala:270)
	at scala.collection.immutable.StringLike.r$(StringLike.scala:270)
	at scala.collection.immutable.StringOps.r(StringOps.scala:29)
	at sbt.BuiltinCommands$.<init>(Main.scala:740)
	at sbt.BuiltinCommands$.<clinit>(Main.scala)
	at sbt.xMain.run(Main.scala:69)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
Error during sbt execution: java.lang.VerifyError: Uninitialized object exists on backward branch 162
Exception Details:
  Location:
    scala/util/matching/Regex.unapplySeq(Lscala/util/matching/Regex$Match;)Lscala/Option; @216: goto
  Reason:
    Error exists in the bytecode
  Bytecode:
    0000000: 2bc6 000a 2bb6 00ef c700 07b2 0052 b02b
    0000010: b600 f2b6 00f3 2ab6 0054 4d59 c700 0b57
    0000020: 2cc6 000d a700 c92c b600 f799 00c2 bb00
    0000030: 6059 b200 65b2 006a 043e c700 0501 bf1d
    0000040: 2bb6 00f8 b600 74b6 0078 2bba 0100 0000
    0000050: b200 93b6 0097 3a06 3a05 59c7 0005 01bf
    0000060: 3a04 1906 b200 93b6 009b a600 7619 04b2
    0000070: 00a0 a600 09b2 00a0 a700 71bb 00a2 5919
    0000080: 04b6 00a8 3a0b 2b19 0bb8 00fc b200 a0b7
    0000090: 00ac 3a07 1907 3a08 1904 b600 afc0 00a4
    00000a0: 3a09 1909 b200 a0a5 0034 bb00 a259 1909
    00000b0: b600 a83a 0b2b 190b b800 fcb2 00a0 b700
    00000c0: ac3a 0a19 0819 0ab6 00b3 190a 3a08 1909
    00000d0: b600 afc0 00a4 3a09 a7ff ca19 07a7 000c
    00000e0: 1904 1905 1906 b800 b9b7 00bc b02a 2bb6
    00000f0: 00ef b601 02b0
  Stackmap Table:
    same_frame(@11)
    same_frame(@15)
    full_frame(@39,{Object[#2],Object[#34],Object[#86]},{Object[#86]})
    same_frame(@46)
    full_frame(@63,{Object[#2],Object[#34],Object[#86],Integer},{Uninitialized[#46],Uninitialized[#46],Object[#98]})
    full_frame(@96,{Object[#2],Object[#34],Object[#86],Integer,Top,Object[#206],Object[#208]},{Uninitialized[#46],Uninitialized[#46],Object[#164]})
    full_frame(@123,{Object[#2],Object[#34],Object[#86],Integer,Object[#164],Object[#206],Object[#208]},{Uninitialized[#46],Uninitialized[#46]})
    full_frame(@162,{Object[#2],Object[#34],Object[#86],Integer,Object[#164],Object[#206],Object[#208],Object[#162],Object[#162],Object[#164],Top,Object[#4]},{Uninitialized[#46],Uninitialized[#46]})
    full_frame(@219,{Object[#2],Object[#34],Object[#86],Integer,Object[#164],Object[#206],Object[#208],Object[#162],Object[#162],Object[#164],Top,Object[#4]},{Uninitialized[#46],Uninitialized[#46]})
    full_frame(@224,{Object[#2],Object[#34],Object[#86],Integer,Object[#164],Object[#206],Object[#208]},{Uninitialized[#46],Uninitialized[#46]})
    full_frame(@233,{Object[#2],Object[#34],Object[#86],Integer,Object[#164],Object[#206],Object[#208]},{Uninitialized[#46],Uninitialized[#46],Object[#4]})
    full_frame(@237,{Object[#2],Object[#34],Object[#86]},{})
```

## notes

sbt version: *1.0*

**Comment by eed3si9n** [comment]
This might be caused by JDK bug - https://bugs.openjdk.java.net/browse/JDK-8046233
Could you print the output of `java -version`?

**Comment by Arnauld** [comment]
```
→ java -version
java version "1.8.0"
Java(TM) SE Runtime Environment (build 1.8.0-b132)
Java HotSpot(TM) 64-Bit Server VM (build 25.0-b70, mixed mode)
```

**Comment by eed3si9n** [comment]
I think that's OpenJDK 8 from 2014. Could you grab the latest and see if the problem persist?

**Comment by Arnauld** [comment]
Great, It did works with:

```
→ java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
````
Thanks you @eed3si9n !!

**Comment by dalamar66** [comment]
Same issue here, using:  

```
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)
```

- Struggling to update java because of internal restrictions: (Any workaround?)

```
C:\Development\sbt\bin>sbt
"C:\Users\SobradoD\.sbt\preloaded\org.scala-sbt\sbt\"1.0.2"\jars\sbt.jar"
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; sup
port was removed in 8.0
java.lang.VerifyError: Uninitialized object exists on backward branch 162
Exception Details:
  Location:
    scala/util/matching/Regex.unapplySeq(Lscala/util/matching/Regex$Match;)Lscal
a/Option; @216: goto
  Reason:
    Error exists in the bytecode
  Bytecode:
    0000000: 2bc6 000a 2bb6 00ef c700 07b2 0052 b02b
    0000010: b600 f2b6 00f3 2ab6 0054 4d59 c700 0b57
    0000020: 2cc6 000d a700 c92c b600 f799 00c2 bb00
    0000030: 6059 b200 65b2 006a 043e c700 0501 bf1d
    0000040: 2bb6 00f8 b600 74b6 0078 2bba 0100 0000
    0000050: b200 93b6 0097 3a06 3a05 59c7 0005 01bf
    0000060: 3a04 1906 b200 93b6 009b a600 7619 04b2
    0000070: 00a0 a600 09b2 00a0 a700 71bb 00a2 5919
    0000080: 04b6 00a8 3a0b 2b19 0bb8 00fc b200 a0b7
    0000090: 00ac 3a07 1907 3a08 1904 b600 afc0 00a4
    00000a0: 3a09 1909 b200 a0a5 0034 bb00 a259 1909
    00000b0: b600 a83a 0b2b 190b b800 fcb2 00a0 b700
    00000c0: ac3a 0a19 0819 0ab6 00b3 190a 3a08 1909
    00000d0: b600 afc0 00a4 3a09 a7ff ca19 07a7 000c
    00000e0: 1904 1905 1906 b800 b9b7 00bc b02a 2bb6
    00000f0: 00ef b601 02b0
  Stackmap Table:
    same_frame(@11)
    same_frame(@15)
    full_frame(@39,{Object[#2],Object[#34],Object[#86]},{Object[#86]})
    same_frame(@46)
    full_frame(@63,{Object[#2],Object[#34],Object[#86],Integer},{Uninitialized[#
46],Uninitialized[#46],Object[#98]})
    full_frame(@96,{Object[#2],Object[#34],Object[#86],Integer,Top,Object[#206],
Object[#208]},{Uninitialized[#46],Uninitialized[#46],Object[#164]})
    full_frame(@123,{Object[#2],Object[#34],Object[#86],Integer,Object[#164],Obj
ect[#206],Object[#208]},{Uninitialized[#46],Uninitialized[#46]})
    full_frame(@162,{Object[#2],Object[#34],Object[#86],Integer,Object[#164],Obj
ect[#206],Object[#208],Object[#162],Object[#162],Object[#164],Top,Object[#4]},{U
ninitialized[#46],Uninitialized[#46]})
    full_frame(@219,{Object[#2],Object[#34],Object[#86],Integer,Object[#164],Obj
ect[#206],Object[#208],Object[#162],Object[#162],Object[#164],Top,Object[#4]},{U
ninitialized[#46],Uninitialized[#46]})
    full_frame(@224,{Object[#2],Object[#34],Object[#86],Integer,Object[#164],Obj
ect[#206],Object[#208]},{Uninitialized[#46],Uninitialized[#46]})
    full_frame(@233,{Object[#2],Object[#34],Object[#86],Integer,Object[#164],Obj
ect[#206],Object[#208]},{Uninitialized[#46],Uninitialized[#46],Object[#4]})
    full_frame(@237,{Object[#2],Object[#34],Object[#86]},{})
```

**Comment by git4sun** [comment]
I got the same issue. Any updates on this?

**Comment by Yaski** [comment]
Have same issue with java version "9.0.1" and sbt 1.0.3

**Comment by Yaski** [comment]
When I removed jdk 1.8 got this error
"Unable to find any JVMs matching version "1.8"."
Looks like it hard coded to jdk 1.8. What a lame.

**Comment by RakeshChouhan** [comment]
I am getting the same issue as @dalamar66  facing.
Java version -  
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

sbt version - 1.0

**Comment by rickilambert** [comment]
The same error whether i try jdk 9 or 8 - my current setup after much messing about is 

C:\kafka\sbt\bin>java -version
java version "1.8.0_11"
Java(TM) SE Runtime Environment (build 1.8.0_11-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.11-b03, mixed mode)

**Comment by coldfire-x** [comment]
java version "1.8.0_20"
Java(TM) SE Runtime Environment (build 1.8.0_20-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.20-b23, mixed mode)

**Comment by eed3si9n** [comment]
Please make sure to download and install the latest Java SE Development Kit 8, for example Java SE Development Kit 8u161 (247MB for macOS, 206MB for Windows x64).

**Comment by geoffwa** [comment]
Upgrading java manually on my Sierra install fixed this error.

For some reason the Java auto-updater decided that my Java 8 build was already up to date 😕

**Comment by arthurbryant** [comment]
I Encountered the same problem.

First I update my macOS's java[Java for Mac OS Xのダウンロード](https://www.java.com/ja/download/mac_download.jsp) and turned out it only updates the JRE. 

So I uninstall my SDK and manually update my SDK like @geoffwa said.
- [Installation of the JDK and the JRE on macOS](https://docs.oracle.com/javase/10/install/installation-jdk-and-jre-macos.htm#JSJIG-GUID-0071963E-D247-4D15-BF49-AD19C7260740)
- [Java SE Development Kit 8 \- Downloads](https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)

Now it works!
