### ISSUE TITLE
IllegalStateException during publishLocal after upgrading to 1.0.1 from 0.13.5

### ISSUE THREAD

**Issue by jameskoch2** [sbt/sbt#3496]
## steps

1. Upgrade SBT from 0.13.5 to 1.01.
2. Build defn: lazy val aggProj = project.in(file("aggProj")).aggregate(otherProj)
3. Run aggProj/publishLocal
4. See two stack traces related to these two projects:

```
java.lang.IllegalStateException: Ivy file not found in cache for otherProj#otherProj-otherProj;0.1-SNAPSHOT!
	at sbt.internal.librarymanagement.ResolutionCache.getResolvedModuleDescriptor(ResolutionCache.scala:66)
	at org.apache.ivy.core.deliver.DeliverEngine.deliver(DeliverEngine.java:111)
	at org.apache.ivy.Ivy.deliver(Ivy.java:601)
	at sbt.internal.librarymanagement.IvyActions$.$anonfun$deliver$2(IvyActions.scala:97)
	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:229)
	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:190)
	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:185)
	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:182)
	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:228)
	at sbt.internal.librarymanagement.IvyActions$.deliver(IvyActions.scala:92)
	at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:126)
	at sbt.Classpaths$.$anonfun$publishTask$4(Defaults.scala:2170)
	at sbt.Classpaths$.$anonfun$publishTask$4$adapted(Defaults.scala:2168)
	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
	at sbt.Execute.work(Execute.scala:266)
	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.IllegalStateException: Ivy file not found in cache for aggProj#aggProj_2.11;0.1-SNAPSHOT!
	at sbt.internal.librarymanagement.ResolutionCache.getResolvedModuleDescriptor(ResolutionCache.scala:66)
	at org.apache.ivy.core.deliver.DeliverEngine.deliver(DeliverEngine.java:111)
	at org.apache.ivy.Ivy.deliver(Ivy.java:601)
	at sbt.internal.librarymanagement.IvyActions$.$anonfun$deliver$2(IvyActions.scala:97)
	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:229)
	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:190)
	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:185)
	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:182)
	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:228)
	at sbt.internal.librarymanagement.IvyActions$.deliver(IvyActions.scala:92)
	at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:126)
	at sbt.Classpaths$.$anonfun$publishTask$4(Defaults.scala:2170)
	at sbt.Classpaths$.$anonfun$publishTask$4$adapted(Defaults.scala:2168)
	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
	at sbt.Execute.work(Execute.scala:266)
	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
(otherProj/*:publishLocal) java.lang.IllegalStateException: Ivy file not found in cache for otherProj#otherProj-otherProj;0.1-SNAPSHOT!
(aggProj/*:publishLocal) java.lang.IllegalStateException: Ivy file not found in cache for aggProj#aggProj_2.11;0.1-SNAPSHOT!
```

## notes

1. I was able to work-around the issue by running `aggProj/update` once, then publishLocal immediately started working.  Did not debug further, sorry. Wanted to log here in case others encounter.
2. This has occurred on multiple machines.
3. Googling around, did find this coursier issue - https://github.com/coursier/coursier/issues/619 - but notably I have not enabled any of the new dependency resolution capabilities/engines (yet).

sbt version: 1.0.1

**Comment by mosesn** [comment]
@jameskoch I'm running into this too.  were you able to resolve this?

**Comment by jameskoch2** [comment]
Only by augmenting various scripts to run update first. A giant hack.

**Comment by mosesn** [comment]
@jameskoch update didn't seem to work, but removing coursier did.  cc @alexarchambault

**Comment by mosesn** [comment]
This only seems to be an issue with `publishLocalSigned`, not with `publishLocal`.  Here's the error message I get:

```
[error] java.lang.IllegalStateException: Ivy file not found in cache for com.twitter#util_2.12;17.11.0!
[error] 	at sbt.internal.librarymanagement.ResolutionCache.getResolvedModuleDescriptor(ResolutionCache.scala:66)
[error] 	at org.apache.ivy.core.deliver.DeliverEngine.deliver(DeliverEngine.java:111)
[error] 	at org.apache.ivy.Ivy.deliver(Ivy.java:601)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$deliver$2(IvyActions.scala:97)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:229)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:190)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:185)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:182)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:228)
[error] 	at sbt.internal.librarymanagement.IvyActions$.deliver(IvyActions.scala:92)
[error] 	at sbt.Classpaths$.$anonfun$deliverTask$1(Defaults.scala:2205)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:266)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] (util/*:deliverLocal) java.lang.IllegalStateException: Ivy file not found in cache for com.twitter#util_2.12;17.11.0!
[error] Total time: 31 s, completed Nov 15, 2017 1:37:06 PM
```

It looks like it's trying to find an ivy file for the aggregated root project https://github.com/twitter/util/blob/develop/build.sbt#L109-L124

**Comment by mosesn** [comment]
I filed a new ticket with coursier https://github.com/coursier/coursier/issues/694

**Comment by eed3si9n** [comment]
Closing here.
