### ISSUE TITLE
meta-build resources not available to classes loaded as part of sbt plugins

### ISSUE THREAD

**Issue by bpholt** [sbt/sbt#3498]
I recently updated the version of sbt-git included in several of our projects and ran into https://github.com/sbt/sbt-git/issues/102. Because we include the logback slf4j backend in another plugin, we were unable to use the workaround (including the no-op backend to suppress the messages). I assumed I'd be able to include a `logback.xml` config file in the resources of the meta-build (to change the logging level to ignore debug messages) but it wasn't picked up by the logger. 

I was able to work around the specific issue I had with sbt-git by including the `logback.xml` in another sbt plugin, but I thought I'd create this issue to discuss the larger problem.

## steps
1. Clone https://github.com/bpholt/sbt-metabuild-resource-issue, which demonstrates the issue.
1. Show the value of task `buildClassLoader`. The meta-build resource is available to the task.
1. Show the value of task `jgitClassLoader`. The meta-build resource is unavailable to the task.

## problem
As far as I can tell, the classes and resources defined by the sbt meta-build are not part of the classpath of things loaded as an sbt plugin.

## expectation
Resources in the meta-build are on the classpath of the build code, including code included as part of an sbt plugin.

sbt version: 1.0.1 and 0.13.16

**Comment by sirthias** [comment]
We have the same problem of not being able to inject a `logback.xml` into the classpath of things running in the meta build.

We use the meta-build in the `project` folder for our deployment code and assumed that creating
 `project/src/main/resources/logback.xml` would make it end up on the classpath of the SBT shell.
Unfortunately, and despite the fact the its properly copied to `project/target/scala-2.10/sbt-0.13/classes/logback.xml`, it doesn't get picked up, which is puzzling.

What would be the best work-around?
Creating a fake plugin just to inject the file into the classpath appears to be overly cumbersome.

(This doesn't appear to me as an "Enhancement" but rather a "bug", TBH)

**Comment by bjhartin** [comment]
I have encountered this too, I think - filed as #5726 but it may be a duplicate.  In my case the failure was occurring when a third-party library attempted to load a resource from its jar.  I've included a reproduction repo in that issue if anyone is interested.

**Comment by hedefalk** [comment]
I've just encountered this too. While trying the middlestep of building an internal plugin under `/project`, I've stuck runtime dependencies under the meta project under `project/src/main/java`. These are finely built to `project/target/scala-2.12/sbt-1.0/classes/`. Trying to reach them from my own code in `project/Test.scala` works fine:

```
Class.forName(foobar).getDeclaredConstructor().newInstance();
```

However, we're using a library dependency (https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/java/org/openapitools/codegen) declared under `project/dependencies.sbt` and this one tries to get our declared runtime dependency by reflection. It does the exact same thing that works in our own code, just one step up in the stack and gets `ClassNotFoundException `.

The reason seems to be that our own code gets `UrlClassLoader` while the library code gets `PluginManagement.PluginClassLoader` and the relevant java.base code is:

```java
    @CallerSensitive
    public static Class<?> forName(String className)
                throws ClassNotFoundException {
        Class<?> caller = Reflection.getCallerClass();
        return forName0(className, true, ClassLoader.getClassLoader(caller), caller);
    }
```

So it gets the classloader of the caller and therefore one jump in the stack into the library code that's loaded by a different class loader breaks.

Looking at this bug report I tried to find any classloader shuffling going on in this library we're using but I can't find any so I definitely think that sbt is at blame here. 

Maybe I'm misunderstanding, but I would have thought that code put in the meta project would be available to the library code put in the meta project - even by reflection?

**Comment by hedefalk** [comment]
This is a minimal repro for what I'm trying to achieve:

https://github.com/hedefalk/sbt-issue-3498/

There's a class Foo defined under consumer/project and then there's a library that _I think_ should be able to get that class by:

```scala
object Library {
  def getAClass(name: String) = Class.forName(name)
}
```

There's a plugin under consumer/project that looks like this:

```scala
object LocalPlugin {
  def gen() : Seq[File] = {
    println(s"I can get a class in my Local plugin by Class.forName: ${Class.forName("Foo")}")
    println(s"But it blows up with an indirection, Library.getAClass: ${Library.getAClass("Foo")}")
    Seq.empty
  }
}
```

Output:

```
I can get a class in my Local plugin by Class.forName: class Foo
[error] java.lang.ClassNotFoundException: Foo
[error] 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[error] 	at java.base/java.lang.Class.forName0(Native Method)
[error] 	at java.base/java.lang.Class.forName(Class.java:315)
[error] 	at se.woodenstake.Library$.getAClass(Library.scala:4)
```


To repro, checkout and 

```
cd library/
sbt publishLocal
cd ../consumer
sbt compile
```

**Comment by blast-hardcheese** [comment]
I've also run into this as well, poking around in `reload plugins` gives me a console where I can hit the resources with no problems, then when I pop out those resources are no longer available.
