### ISSUE TITLE
Flaky tests on Travis CI

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#3520]
It seems like scripted tests are failing intermittently on Travis CI.

- Did something change on Travis?
- If so is the problem on their side, or just exposing problem with scripted framework or individual tests?

`scripted actions/*` seems to be affected more than others.

**Comment by eed3si9n** [comment]
https://travis-ci.org/sbt/sbt/jobs/274679103 says "Socket closed":

```
[0m[[0m[31merror[0m] [0m[0mx actions / state [0m
sbt.internal.scripted.TestException: {line -1}  Reload for scripted batch execution failed.
	at sbt.test.ScriptedTests.$anonfun$runBatchedTests$4(ScriptedTests.scala:201)
	at sbt.test.ScriptedTests.$anonfun$runBatchedTests$4$adapted(ScriptedTests.scala:195)
	at sbt.test.ScriptedTests.$anonfun$commonRunTest$5(ScriptedTests.scala:269)
	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
	at sbt.test.ScriptedTests.commonRunTest(ScriptedTests.scala:268)
	at sbt.test.ScriptedTests.$anonfun$runBatchedTests$2(ScriptedTests.scala:205)
	at sbt.test.ScriptedTests.runOrHandleDisabled(ScriptedTests.scala:226)
	at sbt.test.ScriptedTests.$anonfun$runBatchedTests$1(ScriptedTests.scala:209)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at sbt.test.ScriptedTests.runBatchTests$1(ScriptedTests.scala:178)
	at sbt.test.ScriptedTests.runBatchedTests(ScriptedTests.scala:215)
	at sbt.test.ScriptedTests.$anonfun$batchScriptedRunner$8(ScriptedTests.scala:107)
	at sbt.io.IO$.withTemporaryDirectory(IO.scala:365)
	at sbt.io.IO$.withTemporaryDirectory(IO.scala:372)
	at sbt.test.ScriptedTests.$anonfun$batchScriptedRunner$7(ScriptedTests.scala:107)
	at sbt.test.ScriptedRunner.$anonfun$runAllInParallel$1(ScriptedTests.scala:399)
	at scala.collection.parallel.mutable.ParArray$ParArrayIterator.flatmap2combiner(ParArray.scala:416)
	at scala.collection.parallel.ParIterableLike$FlatMap.leaf(ParIterableLike.scala:1070)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:52)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46)
	at scala.collection.parallel.ParIterableLike$FlatMap.tryLeaf(ParIterableLike.scala:1066)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:149)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:145)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:389)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
	at scala.collection.parallel.ForkJoinTasks$WrappedTask.sync(Tasks.scala:375)
	at scala.collection.parallel.ForkJoinTasks$WrappedTask.sync$(Tasks.scala:375)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.sync(Tasks.scala:440)
	at scala.collection.parallel.ForkJoinTasks.executeAndWaitResult(Tasks.scala:423)
	at scala.collection.parallel.ForkJoinTasks.executeAndWaitResult$(Tasks.scala:414)
	at scala.collection.parallel.ForkJoinTaskSupport.executeAndWaitResult(TaskSupport.scala:56)
	at scala.collection.parallel.ParIterableLike$ResultMapping.leaf(ParIterableLike.scala:956)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:52)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46)
	at scala.collection.parallel.ParIterableLike$ResultMapping.tryLeaf(ParIterableLike.scala:951)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:149)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:145)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: sbt.internal.scripted.TestException: {line -1}  Command failed
	at sbt.test.BatchScriptRunner.processStatement(BatchScriptRunner.scala:42)
	at sbt.test.ScriptedTests.$anonfun$runBatchedTests$4(ScriptedTests.scala:197)
	... 57 more
Caused by: java.net.SocketException: Socket closed
	at java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	at java.net.ServerSocket.accept(ServerSocket.java:513)
	at xsbt.IPC$Server.connection(IPC.scala:55)
	at sbt.test.SbtHandler.receive(SbtHandler.scala:71)
	at sbt.test.SbtHandler.$anonfun$apply$1(SbtHandler.scala:30)
	at sbt.test.SbtHandler.$anonfun$apply$1$adapted(SbtHandler.scala:28)
	at sbt.test.SbtHandler.onSbtInstance(SbtHandler.scala:39)
	at sbt.test.SbtHandler.apply(SbtHandler.scala:28)
	at sbt.test.SbtHandler.apply(SbtHandler.scala:19)
	at sbt.test.BatchScriptRunner.processStatement(BatchScriptRunner.scala:33)
```

**Comment by eed3si9n** [comment]
14 days ago when things looked ok the configuration was already on trusty https://travis-ci.org/sbt/sbt/jobs/269834707/config:

```json
{
  "sudo": false,
  ....
  "group": "stable",
  "dist": "trusty",
  "os": "linux"
}
```

```
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```

The current flaky setup is the same - https://travis-ci.org/sbt/sbt/jobs/274724618/config

**Comment by eed3si9n** [comment]
It seems like there are two more flaky tests:
- run / error
- tests / fork-parallel
