### ISSUE TITLE
sbt run hangs when more than one main is available; also Java main not picked up

### ISSUE THREAD

**Issue by mslinn** [sbt/sbt#356]
I've come across two bugs.
1) Java programs with a main() are not identified as runnable programs by 'sbt run'
2) $ sbt run
[info] Loading global plugins from C:\Users\Mike Slinn.sbt\plugins
[info] Loading project definition from E:\work\books\akkafutures\akkaFutures\project
[info] Set current project to AkkaFutures (in build file:/E:/work/books/akkafutures/akkaFutures/)

Multiple main classes detected, select one to run:

 [1] com.micronautics.akka.dispatch.futureScala.FallbackTo
 [2] com.micronautics.akka.dispatch.futureScala.Traverse
 [3] com.micronautics.akka.dispatch.futureScala.FilterBlocking
 [4] com.micronautics.akka.dispatch.futureScala.ReduceNonblockingScala
 [5] com.micronautics.akka.dispatch.futureScala.FilterNonBlocking
 [6] com.micronautics.akka.dispatch.futureScala.WithFilter
 [7] com.micronautics.akka.dispatch.futureScala.ReduceBlockingScala
 [8] com.micronautics.akka.dispatch.futureScala.ScopeSin
 [9] com.micronautics.akka.dispatch.futureScala.Zip
 [10] com.micronautics.akka.dispatch.futureScala.Fold
 [11] com.micronautics.akka.dispatch.futureScala.Map
 [12] com.micronautics.akka.dispatch.futureScala.Apply
 [13] com.micronautics.akka.dispatch.futureScala.Sequence

Enter number: 2
(sbt hangs)

**Comment by vigdorchik** [comment]
I can reproduce the first issue, but for not the second one. Are you sure it's not your program that is hanging? Can you take a threaddump and post here?

**Comment by mslinn** [comment]
There is no dump, it just hangs. I have found this same problem with several projects. BTW, the OS is Windows XP or 7 with Cygwin.

**Comment by vigdorchik** [comment]
If you press ctrl-break (on Windows), it will print the thread state.

**Comment by mslinn** [comment]
This is all I get:

$ sbt run
[info] Loading global plugins from C:\Users\Mike Slinn.sbt\plugins
[info] Loading project definition from K:\work\books\futures\akkaFutures\project
[info] Set current project to AkkaFutures (in build file:/K:/work/books/futures/akkaFutures/)

Multiple main classes detected, select one to run:

 [1] com.micronautics.akka.dispatch.futureScala.Traverse
 [2] com.micronautics.akka.dispatch.futureScala.ReduceNonblockingScala
 [3] com.micronautics.akka.dispatch.futureScala.WithFilter
 [4] com.micronautics.akka.dispatch.futureScala.FilterBlocking
 [5] com.micronautics.akka.dispatch.futureScala.Sequence
 [6] com.micronautics.akka.dispatch.futureScala.Apply
 [7] com.micronautics.akka.dispatch.futureScala.FallbackTo
 [8] com.micronautics.akka.dispatch.futureScala.ReduceBlockingScala
 [9] com.micronautics.akka.dispatch.futureScala.ScopeSin
 [10] com.micronautics.akka.dispatch.futureScala.Fold
 [11] com.micronautics.akka.dispatch.futureScala.Map
 [12] com.micronautics.akka.dispatch.futureScala.FilterNonBlocking
 [13] com.micronautics.akka.dispatch.futureScala.Zip

Enter number: /usr/local/bin/sbt: line 2:  6812 Quit                    (core dumped) java -Xmx512M -jar E:/storage/programming/scala/sbt-launch.jar "$@"

Mike

**Comment by mslinn** [comment]
Works fun under Linux, BTW

**Comment by vigdorchik** [comment]
Weird, I'm also on cygwin, but cannot reproduce it on a simple project. Would it be possible to have a project with reproducible case?

**Comment by mslinn** [comment]
URL is here for 10 minutes: https://gist.github.com/1746574

**Comment by mslinn** [comment]
BTW, it would be really nice to be able to specify the class to run, either by fully qualified class name or by index:
sbt run com.micronautics.akka.dispatch.futureScala.FallbackTo
sbt run 3

**Comment by jsuereth** [comment]
you probably want `run-main` for that.  In fact, you should probably just use `run-main` if you have more than one main.

**Comment by vigdorchik** [comment]
Cloned. Testing now.

**Comment by mslinn** [comment]
Works on Linux and Windows/Cygwin:
sbt 'run-main com.micronautics.akka.dispatch.futureScala.Zip'

**Comment by mslinn** [comment]
Dies when attempting to launch a Java program on Linux and Windows/Cygwin:

$ sbt 'run-main com.micronautics.akka.dispatch.futureJava.ZipBlocking'
[info] Loading global plugins from /home/mslinn/.sbt/plugins
[info] Loading project definition from /home/mslinn/work/books/akkafutures/akkaFutures/project
[info] Set current project to AkkaFutures (in build file:/home/mslinn/work/books/akkafutures/akkaFutures/)
[error](run-main) java.lang.IllegalAccessException: Class sbt.Run can not access a member of class com.micronautics.akka.dispatch.futureJava.ZipBlocking with modifiers "public static"
java.lang.IllegalAccessException: Class sbt.Run can not access a member of class com.micronautics.akka.dispatch.futureJava.ZipBlocking with modifiers "public static"
    at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:95)
    at java.lang.reflect.Method.invoke(Method.java:607)
java.lang.RuntimeException: Nonzero exit code: 1
    at scala.sys.package$.error(package.scala:27)
[error] {file:/home/mslinn/work/books/akkafutures/akkaFutures/}default-0cfff5/compile:run-main: Nonzero exit code: 1
[error] Total time: 0 s, completed Jan 31, 2012 9:39:47 AM

**Comment by vigdorchik** [comment]
I see:

> run
> run

Multiple main classes detected, select one to run:

 [1] com.micronautics.scala.OptionDemo
 [2] com.micronautics.akka.dispatch.futureScala.FilterNonBlocking
 [3] com.micronautics.akka.dispatch.futureJava.FilterNonBlocking1a
 [4] com.micronautics.akka.dispatch.futureJava.FilterNonBlocking2a
 [5] com.micronautics.akka.dispatch.futureJava.FilterNonBlocking2b
 [6] com.micronautics.akka.dispatch.futureScala.Traverse
 [7] com.micronautics.akka.dispatch.futureScala.ReduceBlockingScala
 [8] com.micronautics.akka.dispatch.futureJava.FilterNonBlocking1b
 [9] com.micronautics.akka.dispatch.futureScala.Sequence
 [10] com.micronautics.akka.dispatch.futureScala.WithFilter
 [11] com.micronautics.akka.dispatch.futureScala.Map
 [12] com.micronautics.akka.dispatch.futureScala.Zip
 [13] com.micronautics.akka.dispatch.futureScala.ReduceNonblockingScala
 [14] com.micronautics.akka.dispatch.futureScala.ScopeSin
 [15] com.micronautics.akka.dispatch.futureScala.FallbackTo
 [16] com.micronautics.akka.dispatch.futureScala.FilterBlocking
 [17] com.micronautics.akka.dispatch.futureJava.FuturePropertyDemo
 [18] com.micronautics.akka.dispatch.futureScala.Fold
 [19] com.micronautics.akka.dispatch.futureScala.Apply

Enter number: 2
2

Scala Filter non-blocking result: http://akka.io/

then it blocks. From the output it looks like sbt has resumed, and the blocking is in user code.

**Comment by mslinn** [comment]
Some of these programs have issues. Others do not. I'll do some more work on them and get back to you. You will be able to git pull.

**Comment by mslinn** [comment]
I've fixed up most of the programs. I see that when running SBT under Windows/Cygwin, some of the Java main programs get picked up:

$ sbt run
[info] Loading global plugins from C:\Users\Mike Slinn.sbt\plugins
[info] Loading project definition from K:\work\books\futures\akkaFutures\project
[info] Set current project to AkkaFutures (in build file:/K:/work/books/futures/akkaFutures/)

Multiple main classes detected, select one to run:

 [1] com.micronautics.akka.dispatch.futureScala.Traverse
 [2] com.micronautics.akka.dispatch.futureScala.ReduceNonblockingScala
 [3] com.micronautics.akka.dispatch.futureJava.FilterNonBlocking2b
 [4] com.micronautics.akka.dispatch.futureScala.WithFilter
 [5] com.micronautics.akka.dispatch.futureScala.FilterBlocking
 [6] com.micronautics.akka.dispatch.futureScala.Sequence
 [7] com.micronautics.akka.dispatch.futureScala.Apply
 [8] com.micronautics.akka.dispatch.futureScala.FallbackTo
 [9] com.micronautics.akka.dispatch.futureScala.ReduceBlockingScala
 [10] com.micronautics.akka.dispatch.futureScala.ScopeSin
 [11] com.micronautics.akka.dispatch.futureJava.FuturePropertyDemo
 [12] com.micronautics.scala.OptionDemo
 [13] com.micronautics.akka.dispatch.futureJava.FilterNonBlocking2a
 [14] com.micronautics.akka.dispatch.futureJava.FilterNonBlocking1a
 [15] com.micronautics.akka.dispatch.futureScala.Fold
 [16] com.micronautics.akka.dispatch.futureScala.Map
 [17] com.micronautics.akka.dispatch.futureJava.FilterNonBlocking1b
 [18] com.micronautics.akka.dispatch.futureScala.FilterNonBlocking
 [19] com.micronautics.akka.dispatch.futureScala.Zip

But when running under Linux, they do not:

sbt run
[info] Loading global plugins from /home/mslinn/.sbt/plugins
[info] Loading project definition from /home/mslinn/work/books/akkafutures/akkaFutures/project
[info] Set current project to AkkaFutures (in build file:/home/mslinn/work/books/akkafutures/akkaFutures/)

Multiple main classes detected, select one to run:

 [1] com.micronautics.akka.dispatch.futureScala.ReduceBlockingScala
 [2] com.micronautics.akka.dispatch.futureScala.Sequence
 [3] com.micronautics.akka.dispatch.futureScala.Map
 [4] com.micronautics.akka.dispatch.futureScala.ScopeSin
 [5] com.micronautics.akka.dispatch.futureScala.Zip
 [6] com.micronautics.akka.dispatch.futureScala.ReduceNonblockingScala
 [7] com.micronautics.akka.dispatch.futureScala.Fold
 [8] com.micronautics.akka.dispatch.futureScala.Traverse
 [9] com.micronautics.akka.dispatch.futureScala.FallbackTo
 [10] com.micronautics.akka.dispatch.futureScala.WithFilter
 [11] com.micronautics.akka.dispatch.futureScala.FilterBlocking
 [12] com.micronautics.akka.dispatch.futureScala.FilterNonBlocking
 [13] com.micronautics.akka.dispatch.futureScala.Apply

Enter number: 

Also, if an invalid number is typed in, like 1234, sbt on Windows hangs; on Linux it dies horribly instead of gracefully reprompting:

Number out of range: was 1234, expected number between 1 and 13
java.lang.RuntimeException: No main class detected.
    at scala.sys.package$.error(package.scala:27)

Mike

**Comment by mslinn** [comment]
One more thing: the order of the displayed classes should be sorted alphabetically. The order is consistent but difficult to understand (perhaps it is sorted by String hash code?)

Mike

**Comment by harrah** [comment]
Please use the mailing list for questions.  Do not use the bug tracker for running commentary.  Please provide reproducible, self-contained examples and file a separate issue for each bug. https://github.com/harrah/xsbt/wiki/FAQ.

**Comment by mslinn** [comment]
The originally reported bug still exists on Windows 7, with or without cygwin. Other projects also suffer from the same bug, for example, this one: https://github.com/mslinn/meetupRoll
