### ISSUE TITLE
0.13.16 build becomes slow on Mac using Java 6

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#3575]
## steps

- Check out Giter8 0.10.0 tag - https://github.com/foundweekends/giter8/tree/v0.10.0
- `jenv shell 1.6`
- `sbt`

## problem

sbt takes really long time to load.
When the build eventually comes up, the shell doesn't display typing for about 10s, it's completely unusable.

## expectation

sbt behaves normally, as it does on Linux.

## notes

sbt version: 0.13.6

I'm not sure if this is anything new, but jstack says sbt is spawning a new process to find out what the terminal width is.

```
"main" prio=5 tid=7fa674001000 nid=0x70000132e000 runnable [70000132b000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:53)
	at java.lang.ProcessImpl.start(ProcessImpl.java:91)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:452)
	at jline.internal.TerminalLineSettings.exec(TerminalLineSettings.java:308)
	at jline.internal.TerminalLineSettings.stty(TerminalLineSettings.java:282)
	at jline.internal.TerminalLineSettings.get(TerminalLineSettings.java:143)
	at jline.internal.TerminalLineSettings.fetchConfig(TerminalLineSettings.java:190)
	at jline.internal.TerminalLineSettings.getProperty(TerminalLineSettings.java:171)
	at jline.UnixTerminal.getWidth(UnixTerminal.java:117)
	at jline.console.ConsoleReader.drawBuffer(ConsoleReader.java:944)
	at jline.console.ConsoleReader.drawBuffer(ConsoleReader.java:965)
	at jline.console.ConsoleReader.putString(ConsoleReader.java:919)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2689)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2373)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2361)
	at sbt.JLine.sbt$JLine$$readLineDirectRaw(LineReader.scala:42)
	at sbt.JLine$$anonfun$readLineDirect$2.apply(LineReader.scala:34)
	at sbt.JLine$$anonfun$readLineDirect$2.apply(LineReader.scala:34)
	at sbt.Signals0.withHandler(Signal.scala:81)
	at sbt.Signals$.withHandler(Signal.scala:11)
	at sbt.JLine.readLineDirect(LineReader.scala:34)
	at sbt.JLine.readLineWithHistory(LineReader.scala:27)
	at sbt.JLine.sbt$JLine$$unsynchronizedReadLine(LineReader.scala:19)
	at sbt.JLine$$anonfun$readLine$1.apply(LineReader.scala:16)
	at sbt.JLine$$anonfun$readLine$1.apply(LineReader.scala:16)
	at sbt.JLine$$anonfun$withJLine$1.apply(LineReader.scala:117)
	at sbt.JLine$$anonfun$withJLine$1.apply(LineReader.scala:115)
	at sbt.JLine$.withTerminal(LineReader.scala:89)
	- locked <7620e43a0> (a jline.UnixTerminal)
	- locked <76990a170> (a sbt.JLine$)
	at sbt.JLine$.withJLine(LineReader.scala:115)
	at sbt.JLine.readLine(LineReader.scala:16)
```

**Comment by eed3si9n** [comment]
Now it's happening to another of my 0.13.16 build when I switch to Java 6.

**Comment by SethTisue** [comment]
seems like maybe we just should close this since the versions involved are so old?

**Comment by eed3si9n** [comment]
Yea. When I said slow, I mean really slow, like 10s per key type, with JLine launching some program in the background to look for terminal capability. Hopefully that no longer happens.
