### ISSUE TITLE
Cannot specify -Dconfig.resource=/path/to/configFile when launching gatling integration test with sbt 1.0.2

### ISSUE THREAD

**Issue by keweishang** [sbt/sbt#3585]
## steps
1. Specify sbt version _1.0.2_ in build.properties:
`sbt.version = 1.0.2`
2. Specify scala version _2.11.11_ in build.sbt:
`scalaVersion := "2.11.11"`
3. Add the following plugin in plugins.sbt:
`addSbtPlugin("io.gatling" % "gatling-sbt" % "2.2.2")`
4. Add gatling dependencies in build.sbt:
```
"io.gatling.highcharts" % "gatling-charts-highcharts" % "2.2.3" % "it,test",
"io.gatling" % "gatling-test-framework" % "2.2.3" % "it,test"
```
5. Enable _integration test_ and _gatling plugin_ in build.sbt:
```
lazy val root = (project in file("."))
  // Adds the predefined integration test configuration. This configuration is referred to by the name `it`.
  // For example, `it:test` executes integration test.
  .configs(IntegrationTest)
  // enable Gatling plugin
  .enablePlugins(GatlingPlugin)
```
6. Create the following integration test (which is a gatling simulation) under *src/it/scala/*:
```
import com.typesafe.config.ConfigFactory
import io.gatling.core.Predef._
import io.gatling.http.Predef._

class HealthcheckSimulation extends Simulation {

  // This works.
  //  val config = ConfigFactory.parseResources("loc-gatling.conf")

  // This does not work.
  val config = ConfigFactory.load()

  val base_url: String = config.getString("baseUrl")
  val version = "v1.0"

  val blogHttpConf = http
    .baseURL(base_url)
    .disableWarmUp

  val scenario1 = scenario("Healthcheck GET request")
    .exec(
      http("GET healthcheck request")
        .get("/healthcheck")
        .check(status.is(_ => 200))
    )

  setUp(
    scenario1.inject(rampUsers(1) over 1)
  ).protocols(blogHttpConf)

}
```
7. Create file _loc-gatling.con_f under _src/it/resources/_ with the following content:
`baseUrl = "http://localhost:8080"`

8. Execute the following sbt command in root directory of the project:
`sbt -Dconfig.resource=/loc-gatling.conf gatling-it:test`

## problem
The following error occurs when executing `sbt -Dconfig.resource=/loc-gatling.conf gatling-it:test`:

> [error] com.typesafe.config.ConfigException$Missing: **No configuration setting found for key 'baseUrl'**
> [error] 	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152)
> [error] 	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:170)
> [error] 	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
> [error] 	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
> [error] 	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:246)
> [error] 	at HealthcheckSimulation.<init>(**HealthcheckSimulation.scala:13**)

## expectation
sbt should find the configuration file specified when executing sbt.

## notes
**We didn't have this issue when we were using sbt 0.13.16.** I've already reported this issue in gatling's mailing list but they mentioned it might also be an issue of the **new sbt version 1.0.2**?

sbt version: *1.0.2*

**Comment by swsnr** [comment]
@muuki88, @felixbr and me just had the very same issue: SBT 1.0.2 fails to resolve new dependencies if `config.resource` exists in JVM properties.  

We can reproduce this issue with a `build.sbt` that contains just a single dependency:

```
libraryDependencies += "com.typesafe.akka" % "akka-http" % "3.0.0-RC1"
```

The actual dependency doesn't matter **as long as its not in your Ivy cache!**.

When we now run SBT with `-Dconfig.resource` we see the following error.  Note that the error *disappears* when you run `sbt compile` (without parameter) to resolve and download the dependency.  As soon as a dependency is cached, ie, doesn't need to be downloaded by SBT, it works, regardless of `-Dconfig.resource`.

```
$ sbt -Dconfig.resource=ci.conf
[info] Updated file /Users/sebastian.wiesner/Playground/project/build.properties: set sbt.version to 1.0.2
[info] Loading project definition from /Users/sebastian.wiesner/Playground/project
[info] Updating {file:/Users/sebastian.wiesner/Playground/project/}playground-build...
[info] Done updating.
[info] Loading settings from build.sbt ...
[info] Set current project to playground (in build file:/Users/sebastian.wiesner/Playground/)
[info] sbt server started at 127.0.0.1:5905
sbt:playground> show sbtVersion
[info] 1.0.2
sbt:playground> compile
[info] Updating {file:/Users/sebastian.wiesner/Playground/}playground...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.typesafe.akka#akka-http;3.0.0-RC1: jenkins.conf: java.io.IOException: resource not found on classpath: jenkins.conf
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.typesafe.akka:akka-http:3.0.0-RC1 (/Users/sebastian.wiesner/Playground/build.sbt#L2-3)
[warn] 		  +- default:playground_2.12:0.1-SNAPSHOT
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.akka#akka-http;3.0.0-RC1: jenkins.conf: java.io.IOException: resource not found on classpath: jenkins.conf
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:331)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:205)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:229)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:190)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:185)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:182)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:228)
[error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:190)
[error] 	at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:38)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:91)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:104)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:104)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:87)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:118)
[error] 	at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2353)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:266)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (*:update) sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.akka#akka-http;3.0.0-RC1: jenkins.conf: java.io.IOException: resource not found on classpath: jenkins.conf
[error] Total time: 1 s, completed 25.10.2017 15:55:39
```

To me this very much looks as if SBT's HTTP library would directly or indirectly attempt to initialize typesafe config.

**Comment by swsnr** [comment]
Looks like this is caused by Gigahorse, SBT's HTTP library.  At least this library [loads typesafe config](https://github.com/eed3si9n/gigahorse/blob/9fb854a7da7b8e93533427cc3f0c5b7b1df5498a/core/src/main/scala/gigahorse/GigahorseSupport.scala#L39).

**Comment by swsnr** [comment]
Just FYI, if I disable gigahorse the dependency resolves successfully.  IOW, `sbt -Dconfig.resource=ci.conf -Dsbt.gigahorse=false compile` works perfectly.

**Comment by l15k4** [comment]
Uff, I just spent 3 hours with this to finally find the cure here ... This is a nasty thing ...
