### ISSUE TITLE
webinars resolving fails with NullPointerException (proxy repository)

### ISSUE THREAD

**Issue by schmitch** [sbt/sbt#3627]
(See the guidelines for contributing, linked above)

## steps

create a repository file like that:

```
[repositories]
  local
  envisia-ivy-proxy-releases: https://nexus.envisia.de/repository/ivy-releases/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  envisia-maven-proxy-releases: https://nexus.envisia.de/repository/mvn-releases/
```

## problem

when adding the webinars repository i still can't resolve them since I get the following error:

```
[warn] problem while listing resources in https://nexus.envisia.de/repository/ivy-releases/org.webjars.npm/yargs/ with envisia-ivy-proxy-releases:
[warn]   java.lang.NullPointerException charsetName
```

however if I switch my repository file around to:

```
[repositories]
  local
  envisia-maven-proxy-releases: https://nexus.envisia.de/repository/mvn-releases/
  envisia-ivy-proxy-releases: https://nexus.envisia.de/repository/ivy-releases/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
```

it starts resolving everything correctly.

## expectation

it should resolve webinars without changing the resolvers inside the repositories file.

## notes

sbt version: 1.0.2
nexus version: 3.4.0-02

**Comment by dwijnand** [comment]
Does the NPE come with a stacktrace?

**Comment by schmitch** [comment]
sadly, no basically only the two lines are printed.

what I wondered is that it doesn't failover to the next resolver `envisia-maven-proxy-releases`. which actually contains the webjars

**Comment by schmitch** [comment]
what's even stranger is that when I'm working remotely and try to clean my .ivy2 folder via `mv .ivy2 old_ivy` and then run sbt I get:

```
[info] Loading settings from idea.sbt ...
[info] Loading global plugins from /Users/schmitch/.sbt/1.0/plugins
[info] Loading project definition from /Users/schmitch/projects/envisia/play/envisia-auth/project/project
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /Users/schmitch/projects/envisia/play/envisia-auth/project
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: io.get-coursier#sbt-coursier;1.0.0-RC12: Resolution failed several times for dependency: io.get-coursier#sbt-coursier;1.0.0-RC12 {compile=[default(compile)]}:: 
[warn]  envisia-maven-proxy-releases: unable to get resource for io/get-coursier#sbt-coursier;1.0.0-RC12: res=https://nexus.envisia.de/repository/mvn-releases/io/get-coursier/sbt-coursier_2.12_1.0/1.0.0-RC12/sbt-coursier-1.0.0-RC12.pom: java.net.ConnectException: Failed to connect to nexus.envisia.de/2003:a:a7f:1f00:9e0e:4db0:631a:b50f:443
[warn]  envisia-internal-proxy-releases: unable to get resource for io/get-coursier#sbt-coursier;1.0.0-RC12: res=https://nexus.envisia.de/repository/internal-releases/io/get-coursier/sbt-coursier_2.12_1.0/1.0.0-RC12/sbt-coursier-1.0.0-RC12.pom: java.net.ConnectException: Failed to connect to nexus.envisia.de/2003:a:a7f:1f00:9e0e:4db0:631a:b50f:443
[warn]  envisia-public-proxy: unable to get resource for io/get-coursier#sbt-coursier;1.0.0-RC12: res=https://nexus.envisia.de/repository/public/io/get-coursier/sbt-coursier_2.12_1.0/1.0.0-RC12/sbt-coursier-1.0.0-RC12.pom: java.net.ConnectException: Failed to connect to nexus.envisia.de/2003:a:a7f:1f00:9e0e:4db0:631a:b50f:443
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          io.get-coursier:sbt-coursier:1.0.0-RC12 (scalaVersion=2.12, sbtVersion=1.0)
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]          io.get-coursier:sbt-coursier:1.0.0-RC12 (scalaVersion=2.12, sbtVersion=1.0) (/Users/schmitch/projects/envisia/play/envisia-auth/project/plugins.sbt#L11-12)
[warn]            +- default:envisia-auth-build:0.1-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[error] sbt.librarymanagement.ResolveException: unresolved dependency: io.get-coursier#sbt-coursier;1.0.0-RC12: Resolution failed several times for dependency: io.get-coursier#sbt-coursier;1.0.0-RC12 {compile=[default(compile)]}:: 
[error]         envisia-maven-proxy-releases: unable to get resource for io/get-coursier#sbt-coursier;1.0.0-RC12: res=https://nexus.envisia.de/repository/mvn-releases/io/get-coursier/sbt-coursier_2.12_1.0/1.0.0-RC12/sbt-coursier-1.0.0-RC12.pom: java.net.ConnectException: Failed to connect to nexus.envisia.de/2003:a:a7f:1f00:9e0e:4db0:631a:b50f:443
[error]         envisia-internal-proxy-releases: unable to get resource for io/get-coursier#sbt-coursier;1.0.0-RC12: res=https://nexus.envisia.de/repository/internal-releases/io/get-coursier/sbt-coursier_2.12_1.0/1.0.0-RC12/sbt-coursier-1.0.0-RC12.pom: java.net.ConnectException: Failed to connect to nexus.envisia.de/2003:a:a7f:1f00:9e0e:4db0:631a:b50f:443
[error]         envisia-public-proxy: unable to get resource for io/get-coursier#sbt-coursier;1.0.0-RC12: res=https://nexus.envisia.de/repository/public/io/get-coursier/sbt-coursier_2.12_1.0/1.0.0-RC12/sbt-coursier-1.0.0-RC12.pom: java.net.ConnectException: Failed to connect to nexus.envisia.de/2003:a:a7f:1f00:9e0e:4db0:631a:b50f:443
[error] 
[error]         at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:331)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:205)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:229)
[error]         at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:190)
[error]         at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error]         at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error]         at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
[error]         at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
[error]         at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
[error]         at xsbt.boot.Using$.withResource(Using.scala:10)
[error]         at xsbt.boot.Using$.apply(Using.scala:9)
[error]         at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
[error]         at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
[error]         at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]         at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]         at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:185)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:182)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:228)
[error]         at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:190)
[error]         at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:38)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:91)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:104)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:104)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:87)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:118)
[error]         at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2353)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:64)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:266)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (*:update) sbt.librarymanagement.ResolveException: unresolved dependency: io.get-coursier#sbt-coursier;1.0.0-RC12: Resolution failed several times for dependency: io.get-coursier#sbt-coursier;1.0.0-RC12 {compile=[default(compile)]}:: 
[error]         envisia-maven-proxy-releases: unable to get resource for io/get-coursier#sbt-coursier;1.0.0-RC12: res=https://nexus.envisia.de/repository/mvn-releases/io/get-coursier/sbt-coursier_2.12_1.0/1.0.0-RC12/sbt-coursier-1.0.0-RC12.pom: java.net.ConnectException: Failed to connect to nexus.envisia.de/2003:a:a7f:1f00:9e0e:4db0:631a:b50f:443
[error]         envisia-internal-proxy-releases: unable to get resource for io/get-coursier#sbt-coursier;1.0.0-RC12: res=https://nexus.envisia.de/repository/internal-releases/io/get-coursier/sbt-coursier_2.12_1.0/1.0.0-RC12/sbt-coursier-1.0.0-RC12.pom: java.net.ConnectException: Failed to connect to nexus.envisia.de/2003:a:a7f:1f00:9e0e:4db0:631a:b50f:443
[error]         envisia-public-proxy: unable to get resource for io/get-coursier#sbt-coursier;1.0.0-RC12: res=https://nexus.envisia.de/repository/public/io/get-coursier/sbt-coursier_2.12_1.0/1.0.0-RC12/sbt-coursier-1.0.0-RC12.pom: java.net.ConnectException: Failed to connect to nexus.envisia.de/2003:a:a7f:1f00:9e0e:4db0:631a:b50f:443
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q
```

however downgrading to 0.13.16 still resolves everything.

also i tried to use ipv4, than I get a SSL handshake exception, besides the fact that 0.13.16 does not get any exception, nor does curl or anything else.

**Comment by schmitch** [comment]
I actually also encountered some race conditions in `sbt.librarymanagement`.

I get something like that:
```
[warn] 	[FAILED     ] de.envisia.play#envisia-auth-anorm_2.12;2.0.1!envisia-auth-anorm_2.12.jar: null (39ms)
[warn] 	Detected merged artifact: [FAILED     ] de.envisia.play#envisia-auth-anorm_2.12;2.0.1!envisia-auth-anorm_2.12.jar: null (39ms).
[warn] ==== Envisia Internal: tried
[warn]   https://nexus.envisia.de/repository/internal/de/envisia/play/envisia-auth-anorm_2.12/2.0.1/envisia-auth-anorm_2.12-2.0.1.jar
```
```
[error] sbt.librarymanagement.ResolveException: download failed: de.envisia.play#envisia-auth-anorm_2.12;2.0.1!envisia-auth-anorm_2.12.jar
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:331)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:205)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:229)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:190)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:185)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:182)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:228)
[error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:190)
[error] 	at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:38)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:91)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:104)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:104)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:87)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:118)
[error] 	at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2353)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:266)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (base/*:update) sbt.librarymanagement.ResolveException: download failed: de.envisia.play#envisia-auth-anorm_2.12;2.0.1!envisia-auth-anorm_2.12.jar
```

however just rerunning the command, solves the issue.

**Comment by schmitch** [comment]
My guess is that all issue's are probably related to https://github.com/sbt/librarymanagement/issues/166

**Comment by amelnikov-mylivn** [comment]
I wonder why this bug remains unattended. Is not it a critical issue?
I stuck with this bug. Is there is any workaround? 

My repository file on CI looks like:
```[repositories]
  local
  companyname-snapshots-temp: http://nexus-dev.companyname.internal/repository/companyname-snapshots-temp/
  companyname-releases: http://nexus-dev.companyname.internal/repository/companyname-releases/
  ivy-releases-proxy: http://nexus-dev.companyname.internal/repository/ivy-releases-proxy/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  sbt-plugins-proxy: http://nexus-dev.companyname.internal/repository/sbt-plugins-proxy/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  maven-group: http://nexus-dev.companyname.internal/repository/maven-group/```

**Comment by eed3si9n** [comment]
I think this was fixed in https://github.com/sbt/librarymanagement/pull/214.
