### ISSUE TITLE
Fresh install of sbt via homebrew yields "java.lang.IllegalArgumentException: Invalid Configuration class specified"

### ISSUE THREAD

**Issue by g12mcgov** [sbt/sbt#3646]
(See the guidelines for contributing, linked above)

## steps

Running Homebrew 1.3.5 on OSX 10.10.5:

1. `brew install sbt`

```
me@gMAC:~/Dropbox/.../Tutorials/Scala $ brew install sbt
==> Downloading https://github.com/sbt/sbt/releases/download/v1.0.2/sbt-1.0.2.tgz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/279553/181aaf02-9d40-11e7-85f4-
######################################################################## 100.0%
==> Caveats
You can use $SBT_OPTS to pass additional JVM options to SBT:
   SBT_OPTS="-XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256M"

This formula uses the standard Lightbend sbt launcher script.
Project specific options should be placed in .sbtopts in the root of your project.
Global settings should be placed in /usr/local/etc/sbtopts
==> Summary
🍺  /usr/local/Cellar/sbt/1.0.2: 482 files, 61.0MB, built in 56 seconds
```

## problem

When I try to run `sbt`:

```
me@gMAC:~/Dropbox/.../Tutorials/Scala $ sbt
java.lang.IllegalArgumentException: Invalid Configuration class specified
	at org.apache.logging.log4j.core.config.builder.impl.DefaultConfigurationBuilder.build(DefaultConfigurationBuilder.java:198)
	at org.apache.logging.log4j.core.config.builder.impl.DefaultConfigurationBuilder.build(DefaultConfigurationBuilder.java:159)
	at org.apache.logging.log4j.core.config.builder.impl.DefaultConfigurationBuilder.build(DefaultConfigurationBuilder.java:55)
	at sbt.util.LogExchange.init(LogExchange.scala:129)
	at sbt.util.LogExchange.context$lzycompute(LogExchange.scala:18)
	at sbt.util.LogExchange.context(LogExchange.scala:18)
	at sbt.util.LogExchange.logger(LogExchange.scala:26)
	at sbt.util.LogExchange.logger(LogExchange.scala:24)
	at sbt.internal.util.GlobalLogging$.initial(GlobalLogging.scala:82)
	at sbt.StandardMain$.initialGlobalLogging(Main.scala:116)
	at sbt.StandardMain$.initialState(Main.scala:136)
	at sbt.xMain.run(Main.scala:70)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.logging.log4j.core.config.builder.impl.DefaultConfigurationBuilder.build(DefaultConfigurationBuilder.java:170)
	... 20 more
Caused by: java.lang.NoSuchMethodError: org.apache.logging.log4j.core.config.AbstractConfiguration.<init>(Lorg/apache/logging/log4j/core/LoggerContext;Lorg/apache/logging/log4j/core/config/ConfigurationSource;)V
	at org.apache.logging.log4j.core.config.builder.impl.BuiltConfiguration.<init>(BuiltConfiguration.java:58)
	... 25 more
Error during sbt execution: java.lang.IllegalArgumentException: Invalid Configuration class specified
```

## notes

It looks like this is a logging configuration it's explaining about? Not sure if this is a bug/known issue, or if there are additional steps I need to take here?

sbt version: *insert sbt version*

**Comment by eed3si9n** [comment]
Looks like a bug.
Does this happen on any build or only for `Tutorials/Scala`?
