### ISSUE TITLE
Manual java home cannot be used in sbt 1.x

### ISSUE THREAD

**Issue by jvican** [sbt/sbt#3649]
## steps
Clone https://github.com/jvican/sbt1-bug-forked-test and follow instructions in README. Sneak peek:
  
1. Change the `javaHome` setting in `build.sbt` to the correct JDK directory in your system.
2. Run `sbt test`.

## problem
I get the `Forked test harness failed: java.net.SocketException` error:
```
sbt @ fork-test-error > test
[info] Updating {file:/data/rw/code/scala/repros/fork-test-error/}fork-test-error...
[info] Done updating.
[info] Compiling 1 Scala source to /data/rw/code/scala/repros/fork-test-error/target/scala-2.12/test-classes ...
[info] Done compiling.
[error] Error: Total 0, Failed 0, Errors 0, Passed 0
[error] Error during tests:
[error] 	Forked test harness failed: java.net.SocketException: Connection reset
[error] 	at java.net.SocketInputStream.read(SocketInputStream.java:210)
[error] 	at java.net.SocketInputStream.read(SocketInputStream.java:141)
[error] 	at java.net.SocketInputStream.read(SocketInputStream.java:224)
[error] 	at java.io.ObjectInputStream$PeekInputStream.peek(ObjectInputStream.java:2598)
[error] 	at java.io.ObjectInputStream$BlockDataInputStream.readBlockHeader(ObjectInputStream.java:2792)
[error] 	at java.io.ObjectInputStream$BlockDataInputStream.refill(ObjectInputStream.java:2862)
[error] 	at java.io.ObjectInputStream$BlockDataInputStream.skipBlockData(ObjectInputStream.java:2764)
[error] 	at java.io.ObjectInputStream.skipCustomData(ObjectInputStream.java:2196)
[error] 	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1838)
[error] 	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1713)
[error] 	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1888)
[error] 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1529)
[error] 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
[error] 	at sbt.React.react(ForkTests.scala:156)
[error] 	at sbt.ForkTests$Acceptor$2$.run(ForkTests.scala:96)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 4 s, completed Oct 19, 2017 6:18:27 PM
sbt @ fork-test-error > %                                    
```

## expectation
The test suite to run nothing with a 0 exit code.

## notes
If I change the sbt version to `0.13.16`, it works.

sbt version: 1.0.2

**Comment by jvican** [comment]
I consider this to be a pretty urgent issue given the fact that it's not possible to run sbt 1.x with JDKs previous to version 8. This is the only mechanism for library authors to test their projects with JDK7, and it's currently blocked by it.
  
Without a fix for this, support of sbt 1.x for the Scala Platform modules `better-files` and `scalajson` will probably need to wait. I wonder for how many projects this is a blocking issue. I'm aware that JDK7 and JDK6 are EOLed, but they are still supported by many open source projects since their use in industry is widespread.

**Comment by eed3si9n** [comment]
My guess is that downgrading to lower Java version never worked.
It would be good to fix this though.

**Comment by eed3si9n** [comment]
There's communication going on in https://github.com/sbt/sbt/blob/v1.0.2/main-actions/src/main/scala/sbt/ForkTests.scala#L71-L106 using ObjectOutputStream /ObjectInputStream. That should turn into JSON serialization to avoid Java stickiness.

To contribute, some knowledge of sjson-new would be required, but I think it's somewhat contained issue.

**Comment by jvican** [comment]
I looked into this and I managed to identify the culprit of this error: the scala version. Specifying the scala version to 2.11.11 fixes it (obviously, because JDK7 cannot run Scala 2.12 code).
  
What I think we could improve here is the reported error. Instead of a cryptic protocol error, it would be great to catch the exception in the code spawning the JVM and report it back to sbt.

**Comment by bakenezumi** [comment]
I ran it with sbt 1.1.1, and got the following output.

```
sbt:bug forked test> test
[info] Updating ...
[info] Done updating.
[info] Compiling 1 Scala source to ..
[info] Done compiling.
java.lang.UnsupportedClassVersionError: sbt/ForkMain : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
Exception in thread "main" [error] Could not accept connection from test agent: class java.net.SocketException: socket closed
[error] java.net.SocketException: socket closed
[error]         at java.net.DualStackPlainSocketImpl.accept0(Native Method)
[error]         at java.net.DualStackPlainSocketImpl.socketAccept(Unknown Source)
[error]         at java.net.AbstractPlainSocketImpl.accept(Unknown Source)
[error]         at java.net.PlainSocketImpl.accept(Unknown Source)
[error]         at java.net.ServerSocket.implAccept(Unknown Source)
[error]         at java.net.ServerSocket.accept(Unknown Source)
[error]         at sbt.ForkTests$Acceptor$2$.run(ForkTests.scala:66)
[error]         at java.lang.Thread.run(Unknown Source)
[error] Error: Total 0, Failed 0, Errors 0, Passed 0
[error] Error during tests:
[error]         Running java with options -classpath ... sbt.ForkMain 55513 failed with exit code 1
[error] (Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 5 s, completed 2018/03/16 16:48:19
sbt:bug forked test>
```

Since `java.lang.UnsupportedClassVersionError` can be seen, I think that it can be tracked.

**Comment by eed3si9n** [comment]
That looks good enough for me as the error message.
