### ISSUE TITLE
~ in polling mode is not triggered by IntelliJ IDEA saving files in macOS

### ISSUE THREAD

**Issue by mechkg** [sbt/sbt#3775]
## steps

1. Create a barebones SBT project, e.g. using new SBT project in IntelliJ IDEA. Add a test source file, e.g.

```
object Test extends App {
  println ("Hello SBT!")
}
```

2. Start SBT and run any command prefixed with **~**, e.g.

    ~run

3. Edit the file in IDEA and save it.

## problem

SBT does not detect file changes and does not re-run the command.

## expectation

SBT should detect file changes and re-run the command.

## notes

Changes made by other editors (e.g. TextMate, nano) do trigger SBT 1.0.4!

SBT 0.13.16 triggers correctly regardless of what program modified the file.

SBT 1.0.4 triggers correctly in nio mode (via `-Dsbt.watch.mode=nio`) albeit with a delay.

SBT version: 1.0.0 - 1.0.4
macOS version: High Sierra 10.13.1
Java version: 1.8.0_151

**Comment by mechkg** [comment]
See also https://github.com/sbt/io/issues/86

**Comment by xerial** [comment]
@mechkg Good catch!

**Comment by dwijnand** [comment]
Upstream https://github.com/sbt/io/issues/86

**Comment by eatkins** [comment]
I referenced this in #3695 but, as a temporary fix, I added an sbt plugin that replaces the WatchService for OSX with one that uses the Apple File System Events API. https://github.com/swoval/MacOSXWatchService

**Comment by dwijnand** [comment]
Re-opening to track sbt/io needs releasing for inclusion in 1.1.0-RC2.

**Comment by OlegYch** [comment]
@dwijnand this seems to be specific to IDEA
happens to me on windows, with sbt 1.0.0-1.0.4, with both polling and io, doesn't happen if i eg edit the file with notepad or use IO.touch

**Comment by OlegYch** [comment]
the only difference i can see is that when IDEA saves file - directory last modified time is updated, but not when i use touch

**Comment by eed3si9n** [comment]
New io with the fix was merged in #3816.
If the issue persists with 1.1.0-RC2, then we will reopen this case.

**Comment by dwijnand** [comment]
This issue was about macOS though, where it's using polling. If there are issues with NIO and/or IntelliJ, on Windows, they should be reported.

**Comment by hedefalk** [comment]
I struck this problem with IDEA saves not triggering my ~compile. So I found this and upgraded to latest RC, but now I instead get this issue that it doesn't seem to resolve a softlink for a git-hook:

```
sbt:root> ~compile
Exception in thread "Thread-11" java.io.FileNotFoundException: No such file or directory: /Users/viktor/dev/projects/[project]/.git/hooks/pre-commit
	at sbt.internal.io.MilliPosixBase.checkedIO(Milli.scala:97)
	at sbt.internal.io.MacMilli$.getModifiedTimeNative(Milli.scala:248)
	at sbt.internal.io.MacMilli$.getModifiedTimeNative(Milli.scala:239)
	at sbt.internal.io.MilliNative.getModifiedTime(Milli.scala:66)
	at sbt.internal.io.Milli$.getModifiedTime(Milli.scala:357)
	at sbt.io.IO$.getModifiedTime(IO.scala:1163)
	at sbt.io.PollingWatchService$PollingThread.$anonfun$getFileTimes$3(PollingWatchService.scala:96)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at sbt.io.PollingWatchService$PollingThread.$anonfun$getFileTimes$2(PollingWatchService.scala:96)
	at sbt.io.PollingWatchService$PollingThread.$anonfun$getFileTimes$2$adapted(PollingWatchService.scala:93)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at sbt.io.PollingWatchService$PollingThread.getFileTimes(PollingWatchService.scala:93)
	at sbt.io.PollingWatchService$PollingThread.populateEvents(PollingWatchService.scala:110)
	at sbt.io.PollingWatchService$PollingThread.run(PollingWatchService.scala:86)
```

It is however there as a softlink:

~/d/p/a/.git ❯❯❯ ll  /Users/viktor/dev/projects/[project]/.git/hooks/pre-commit
lrwxr-xr-x  1 viktor  staff    23B Mar  7  2017 /Users/viktor/dev/projects/[project]/.git/hooks/pre-commit@ -> ../../bin/pre-commit.sh

Could this be related to the fix? Dunno why it's trying to grab that file, I have the sbt git plugin sure, but…

**Comment by dwijnand** [comment]
That's https://github.com/sbt/sbt/issues/3820.
