### ISSUE TITLE
traceLevel setting is not taken into account since 1.x

### ISSUE THREAD

**Issue by 2m** [sbt/sbt#3793]
## steps
Given a task
```
TaskKey[Unit]("testTrace") := {
  sys.error("oops")
}
```

The exception stack trace is printed out when the task is ran no matter what the value of `traceLevel` is set.

## problem
`traceLevel` setting does not suppress stack traces of being printed.

## notes

sbt version: 1.0.4, 1.1.0-RC1

Works as expected with sbt 0.13.16.

**Comment by kshakir** [comment]
Would this be related to my [SO post](https://stackoverflow.com/questions/47601811/how-to-suppress-info-messages-in-sbt-1-0-0-1-0-4)? After a week no one seems to know the answer over there either.

**Comment by dvdalilue** [comment]
I have the same issues with sbt `1.0.4`. The use of `-error` does not suppress any message (info nor debug). Finally, i changed to `0.13.16`

**Comment by eed3si9n** [comment]
@dvdalilue That's a separate issue - https://github.com/sbt/sbt/issues/3849

Note to a potential contributor:

`ConsoleAppender` https://github.com/sbt/util/blob/v1.1.2/internal/util-logging/src/main/scala/sbt/internal/util/ConsoleAppender.scala has `getTrace` and `setTrace` that tracks the trace level. `setTrace` is currently not called in sbt 1.

https://github.com/sbt/sbt/blob/fd8b4224889fae96fdc035602ea083f4d99dd7c6/main/src/main/scala/sbt/Project.scala#L442-L444

The above calls https://github.com/sbt/sbt/blob/a28381e93a0c5e46d4c4a9d261cc5e0db3c9f384/main/src/main/scala/sbt/internal/LogManager.scala#L212-L230


This might be more tricky because in sbt loggers and appenders are separated.

**Comment by eed3si9n** [comment]
```
sbt:hello> set check/traceLevel := 4
[info] Defining check / traceLevel
[info] The new value will be used by no settings or tasks.
[info] Reapplying settings...
[info] Set current project to hello (in build file:/Users/eed3si9n/work/hellotest/)
sbt:hello> check
[error] java.lang.RuntimeException: boom
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at $0d89407eaa29f35a5d10$.$anonfun$$sbtdef$1(/Users/eed3si9n/work/hellotest/build.sbt:14)
[error] 	at sbt.std.Transform$$anon$3.$anonfun$apply$2(Transform.scala:46)
[error] (check) boom
[error] Total time: 0 s, completed Aug 20, 2019 11:36:09 AM
```

This seems to work now.

**Comment by contrun** [comment]
I tried 1.3.0-RC4. I want to get the full stack trace. It still does not work for me. Am I doing it the wrong way?

```
sbt:akka-db-load> set run/traceLevel := 10000
[info] Defining run / traceLevel
[info] The new value will be used by no settings or tasks.
[info] Reapplying settings...
[info] Set current project to akka-db-load (in build file:/home/e/Local/decay/)
sbt:akka-db-load> about
[info] This is sbt 1.3.0-RC4
[info] The current project is ProjectRef(uri("file:/home/e/Local/decay/"), "decay") 0.1
[info] The current project is built against Scala 2.12.8
[info] Available Plugins
[info]  - sbt.ScriptedPlugin
[info]  - sbt.plugins.CorePlugin
[info]  - sbt.plugins.Giter8TemplatePlugin
[info]  - sbt.plugins.IvyPlugin
[info]  - sbt.plugins.JUnitXmlReportPlugin
[info]  - sbt.plugins.JvmPlugin
[info]  - sbt.plugins.SbtPlugin
[info]  - sbt.plugins.SemanticdbPlugin
[info] sbt, sbt plugins, and build definitions are using Scala 2.12.8
sbt:akka-db-load> run
[info] Compiling 1 Scala source to /home/e/Local/decay/target/scala-2.12/classes ...
[info] running Main 
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Uncaught error from thread [default-akka.actor.default-dispatcher-2]: akka/actor/dungeon/FaultHandling$$anonfun$handleNonFatalOrInterruptedException$1, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[default]
java.lang.NoClassDefFoundError: akka/actor/dungeon/FaultHandling$$anonfun$handleNonFatalOrInterruptedException$1
	at akka.actor.dungeon.FaultHandling.handleNonFatalOrInterruptedException(FaultHandling.scala:310)
	at akka.actor.dungeon.FaultHandling.handleNonFatalOrInterruptedException$(FaultHandling.scala:310)
	at akka.actor.ActorCell.handleNonFatalOrInterruptedException(ActorCell.scala:447)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:557)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:569)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:293)
	at akka.dispatch.Mailbox.run(Mailbox.scala:228)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.ClassNotFoundException: akka.actor.dungeon.FaultHandling$$anonfun$handleNonFatalOrInterruptedException$1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 12 more
```

**Comment by eed3si9n** [comment]
@contrun `run` internally calls `bgRun`, so that might be the issue.
Could you try `set bgRun / traceLevel := 10000`?

Maybe I should try to share the settings between those tasks?

**Comment by contrun** [comment]
Thank you for the  prompt reply. I just tried bgRun. It seems to be not working also. I don't know what is going on. I think sharing settings could lead to less confusion.

**Comment by eed3si9n** [comment]
I'll create a new issue for traceLevel on run.
