### ISSUE TITLE
FileNotFoundException: No such file or directory in PollingWatchService

### ISSUE THREAD

**Issue by francisdb** [sbt/sbt#3820]
sbt 1.1.0-RC2
MacOS
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

I got this logged while testing `1.1.0-RC2` to see if it would pick up changed when running using `~`. Seems to break the watch service as changes are not detected after this.

after `~test:compile`

```
Exception in thread "Thread-617" java.io.FileNotFoundException: No such file or directory: /Users/me/workspace/proj/module/target/classes.bak
	at sbt.internal.io.MilliPosixBase.checkedIO(Milli.scala:97)
	at sbt.internal.io.MacMilli$.getModifiedTimeNative(Milli.scala:248)
	at sbt.internal.io.MacMilli$.getModifiedTimeNative(Milli.scala:239)
	at sbt.internal.io.MilliNative.getModifiedTime(Milli.scala:66)
	at sbt.internal.io.Milli$.getModifiedTime(Milli.scala:357)
	at sbt.io.IO$.getModifiedTime(IO.scala:1163)
	at sbt.io.PollingWatchService$PollingThread.$anonfun$getFileTimes$3(PollingWatchService.scala:96)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at sbt.io.PollingWatchService$PollingThread.$anonfun$getFileTimes$2(PollingWatchService.scala:96)
	at sbt.io.PollingWatchService$PollingThread.$anonfun$getFileTimes$2$adapted(PollingWatchService.scala:93)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at sbt.io.PollingWatchService$PollingThread.getFileTimes(PollingWatchService.scala:93)
	at sbt.io.PollingWatchService$PollingThread.populateEvents(PollingWatchService.scala:110)
	at sbt.io.PollingWatchService$PollingThread.run(PollingWatchService.scala:86)
```

after `clean`

```
Exception in thread "Thread-688" java.io.FileNotFoundException: No such file or directory: /Users/me/workspace/proj/module/target/streams/compile/$global
	at sbt.internal.io.MilliPosixBase.checkedIO(Milli.scala:97)
	at sbt.internal.io.MacMilli$.getModifiedTimeNative(Milli.scala:248)
	at sbt.internal.io.MacMilli$.getModifiedTimeNative(Milli.scala:239)
	at sbt.internal.io.MilliNative.getModifiedTime(Milli.scala:66)
	at sbt.internal.io.Milli$.getModifiedTime(Milli.scala:357)
	at sbt.io.IO$.getModifiedTime(IO.scala:1163)
	at sbt.io.PollingWatchService$PollingThread.$anonfun$getFileTimes$3(PollingWatchService.scala:96)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at sbt.io.PollingWatchService$PollingThread.$anonfun$getFileTimes$2(PollingWatchService.scala:96)
	at sbt.io.PollingWatchService$PollingThread.$anonfun$getFileTimes$2$adapted(PollingWatchService.scala:93)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at sbt.io.PollingWatchService$PollingThread.getFileTimes(PollingWatchService.scala:93)
	at sbt.io.PollingWatchService$PollingThread.populateEvents(PollingWatchService.scala:110)
	at sbt.io.PollingWatchService$PollingThread.run(PollingWatchService.scala:86)
```

**Comment by francisdb** [comment]
As a workaround we are again falling back to using https://github.com/swoval/MacOSXWatchService

**Comment by dwijnand** [comment]
Hi @francisdb, thanks for reporting the issue. The underlying reason is that when fixing the precision of file's last modified date (https://github.com/sbt/io/pull/92) we switched the semantics. `File.lastModified` returns `0` on missing files, while our new `IO.getLastModified` throws an exectpion.

However, I can't reproduce the issue. Can you share a minimal reproduction of this, please?

**Comment by francisdb** [comment]
I can reproduce this on 2 of our bigger projects, they contain more than 10 subprojects and I use these commands

```
clean
~test:compile
```

(still trying to find out if any specific build settings trigger this)

**Comment by francisdb** [comment]
I tried `parallelExecution in Global := false` but still saw the issue, seems to mostly report this `classes.bak` file. What is writing that?

**Comment by francisdb** [comment]
Closing this for now as I have yet to see it on 1.1.0 final
