### ISSUE TITLE
1.1.0-RC2 breaks 1.1.0-RC1 with IllegalArgumentException for NGWin32NamedPipeLibrary

### ISSUE THREAD

**Issue by drxcc** [sbt/sbt#3821]
Using Windows 8 the sbt launcher fails to launch 1.1.0-RC2 where 1.1.0-RC1 worked very stably.

## steps

> mkdir empty
> cd empty
> sbt

## problem (using 1.1.0-RC2)

```
[warn] No sbt.version set in project/build.properties, base directory: C:\Users\radke\tmp\empty
[info] Loading settings from plugins.sbt ...
[info] Loading global plugins from C:\Users\radke\.sbt\1.0\plugins
[info] Set current project to empty (in build file:/C:/Users/radke/tmp/empty/)
Exception in thread "sbt-socket-server" java.lang.ExceptionInInitializerError
        at sbt.internal.NGWin32NamedPipeServerSocket.<clinit>(NGWin32NamedPipeServerSocket.java:37)
        at sbt.internal.server.Server$$anon$2$$anon$1.$anonfun$run$2(Server.scala:60)
        at sbt.internal.util.ErrorHandling$.translate(ErrorHandling.scala:10)
        at sbt.internal.server.Server$$anon$2.sbt$internal$server$Server$$anon$$addServerError(Server.scala:107)
        at sbt.internal.server.Server$$anon$2$$anon$1.$anonfun$run$1(Server.scala:60)
        at scala.util.Try$.apply(Try.scala:209)
        at sbt.internal.server.Server$$anon$2$$anon$1.run(Server.scala:57)
Caused by: java.lang.IllegalArgumentException: Interface (NGWin32NamedPipeLibrary) of library=kernel32 does not extend Library
        at com.sun.jna.Native.loadLibrary(Native.java:566)
        at sbt.internal.NGWin32NamedPipeLibrary.<clinit>(NGWin32NamedPipeLibrary.java:38)
        ... 7 more
[error] java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
[error]         at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:255)
[error]         at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:183)
[error]         at scala.concurrent.Await$.$anonfun$ready$1(package.scala:191)
[error]         at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[error]         at scala.concurrent.Await$.ready(package.scala:142)
[error]         at sbt.internal.CommandExchange.runServer(CommandExchange.scala:152)
[error]         at sbt.internal.CommandExchange.run(CommandExchange.scala:89)
[error]         at sbt.BuiltinCommands$.$anonfun$shell$1(Main.scala:737)
[error]         at sbt.Command$.$anonfun$command$2(Command.scala:88)
[error]         at sbt.MainLoop$.processCommand(MainLoop.scala:153)
[error]         at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:136)
[error]         at sbt.State$$anon$1.runCmd$1(State.scala:242)
[error]         at sbt.State$$anon$1.process(State.scala:248)
[error]         at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:136)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.MainLoop$.next(MainLoop.scala:136)
[error]         at sbt.MainLoop$.run(MainLoop.scala:129)
[error]         at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:107)
[error]         at sbt.io.Using.apply(Using.scala:22)
[error]         at sbt.MainLoop$.runWithNewLog(MainLoop.scala:101)
[error]         at sbt.MainLoop$.runAndClearLast(MainLoop.scala:57)
[error]         at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:42)
[error]         at sbt.MainLoop$.runLogged(MainLoop.scala:34)
[error]         at sbt.StandardMain$.runManaged(Main.scala:113)
[error]         at sbt.xMain.run(Main.scala:76)
[error]         at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error]         at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error]         at xsbt.boot.Launch$.run(Launch.scala:109)
[error]         at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error]         at xsbt.boot.Launch$.launch(Launch.scala:117)
[error]         at xsbt.boot.Launch$.apply(Launch.scala:18)
[error]         at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error]         at xsbt.boot.Boot$.main(Boot.scala:17)
[error]         at xsbt.boot.Boot.main(Boot.scala)
[error] java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
[error] Use 'last' for the full log.
```

## expectation (using 1.1.0-RC1)

```
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'org.apache.logging.log4j.simplelog.StatusLogger.level' to TRACE to show Log4j2 internal initialization logging.
[warn] No sbt.version set in project/build.properties, base directory: C:\Users\radke\tmp\empty
[info] Loading settings from plugins.sbt ...
[info] Loading global plugins from C:\Users\radke\.sbt\1.0\plugins
[info] Updating ProjectRef(uri("file:/C:/Users/radke/.sbt/1.0/plugins/"), "global-plugins")...
[info] Done updating.
[info] Set current project to empty (in build file:/C:/Users/radke/tmp/empty/)
[info] sbt server started at local:sbt-server-f2b4676176c5019c1d09
sbt:empty>
```

## notes

* sbt version: *sbt-1.1.0-RC2*
* Windows 8
* java 8
* scala 2.12.4  (in the sbt.boot.properties luancher setting conf)

**Comment by cunei** [comment]
This is due to an incompatible change between JNA 4.1.0 and JNA 4.5.0. Thanks for reporting! We need to fix this in RC3.

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/3824

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/3837.

**Comment by drxcc** [comment]
Thanks, I can confirm that RC4 fixed the windows NGWin32NamedPipeLibrary I was seeing (and RC3 did not).

**Comment by eed3si9n** [comment]
Awesome. Thanks for the confirmation.
