### ISSUE TITLE
Typesafe config loading fails in sbt 1.1.0 

### ISSUE THREAD

**Issue by lev112** [sbt/sbt#3899]
## steps
clone this project: https://github.com/lev112/sbt1_config/tree/master
run 
```
sbt myKey
```

## problem
```
[error] com.typesafe.config.ConfigException$UnresolvedSubstitution: module.conf: 8: Could not resolve substitution to a value: ${module1.App.Args.param1}
[error] 	at com.typesafe.config.impl.ConfigReference.resolveSubstitutions(ConfigReference.java:87)
[error] 	at com.typesafe.config.impl.ResolveSource.resolveCheckingReplacement(ResolveSource.java:110)
[error] 	at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:114)
[error] 	at com.typesafe.config.impl.SimpleConfigObject$1.modifyChildMayThrow(SimpleConfigObject.java:340)
[error] 	at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:279)
[error] 	at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:320)
[error] 	at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:24)
[error] 	at com.typesafe.config.impl.ResolveSource.resolveCheckingReplacement(ResolveSource.java:110)
[error] 	at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:114)
[error] 	at com.typesafe.config.impl.SimpleConfigObject$1.modifyChildMayThrow(SimpleConfigObject.java:340)
[error] 	at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:279)
[error] 	at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:320)
[error] 	at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:24)
[error] 	at com.typesafe.config.impl.ResolveSource.resolveCheckingReplacement(ResolveSource.java:110)
[error] 	at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:114)
[error] 	at com.typesafe.config.impl.SimpleConfigObject$1.modifyChildMayThrow(SimpleConfigObject.java:340)
[error] 	at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:279)
[error] 	at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:320)
[error] 	at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:24)
[error] 	at com.typesafe.config.impl.ResolveSource.resolveCheckingReplacement(ResolveSource.java:110)
[error] 	at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:114)
[error] 	at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:149)
[error] 	at com.typesafe.config.impl.SimpleConfig.resolveWith(SimpleConfig.java:70)
[error] 	at com.typesafe.config.impl.SimpleConfig.resolve(SimpleConfig.java:60)
[error] 	at com.typesafe.config.impl.SimpleConfig.resolve(SimpleConfig.java:33)
[error] 	at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:184)
[error] 	at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:113)
[error] 	at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:135)
[error] 	at com.typesafe.config.ConfigFactory.loadDefaultConfig(ConfigFactory.java:216)
[error] 	at com.typesafe.config.ConfigFactory.loadDefaultConfig(ConfigFactory.java:193)
[error] 	at com.typesafe.config.ConfigFactory.loadDefaultConfig(ConfigFactory.java:189)
[error] 	at com.typesafe.config.ConfigFactory.access$000(ConfigFactory.java:38)
[error] 	at com.typesafe.config.ConfigFactory$1.call(ConfigFactory.java:302)
[error] 	at com.typesafe.config.ConfigFactory$1.call(ConfigFactory.java:299)
[error] 	at com.typesafe.config.impl.ConfigImpl$LoaderCache.getOrElseUpdate(ConfigImpl.java:58)
[error] 	at com.typesafe.config.impl.ConfigImpl.computeCachedConfig(ConfigImpl.java:86)
[error] 	at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:299)
[error] 	at $a6f43248724069830195$.$anonfun$$sbtdef$3(/home/user/work/git/sbt1test/sbt1test/build.sbt:30)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (myKey) com.typesafe.config.ConfigException$UnresolvedSubstitution: module.conf: 8: Could not resolve substitution to a value: ${module1.App.Args.param1}

```

## expectation
should print
```
[info] @@@@@@@@@@@@@@@@@@@@@@@
[info] 2
[info] @@@@@@@@@@@@@@@@@@@@@@@
```

## notes
sbt version: 1.1.0

I have the following scenario:
`module.conf` is a self contained config file, that sets the value of `x`

in `application.conf`, I include the `module` conf, and overwrite some value  
in sbt 0.13.16 the config is loaded and parsed as expected

**Comment by eed3si9n** [comment]
This is to be expected since sbt 1 uses ssh-config 0.2.2, which in turn uses config 1.2.0 https://github.com/lightbend/ssl-config/blob/v0.2.2/project/Dependencies.scala

**Comment by lev112** [comment]
is there any workaround for this?
can I force sbt to use the latest config version?

**Comment by 2m** [comment]
By downgrading to 1.2.0 you are stepping on this issue: https://github.com/lightbend/config/issues/136

You can workaround it by changing `application.conf` to
```
App.module1 = {
  include "module.conf"
  Args {
    param1 = 2
  }
}
```
