### ISSUE TITLE
package seems to update instead of replacing existing jar

### ISSUE THREAD

**Issue by fdietze** [sbt/sbt#3906]
## steps
```bash
$ sbt package package
```

## problem
```
[error] java.util.zip.ZipException: duplicate entry: frontend-opt-bundle.js
[error] 	at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:232)
[error] 	at java.util.jar.JarOutputStream.putNextEntry(JarOutputStream.java:109)
[error] 	at sbt.io.IO$.addFileEntry$1(IO.scala:550)
[error] 	at sbt.io.IO$.$anonfun$writeZip$3(IO.scala:559)
[error] 	at sbt.io.IO$.$anonfun$writeZip$3$adapted(IO.scala:559)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:929)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:929)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error] 	at sbt.io.IO$.writeZip(IO.scala:559)
[error] 	at sbt.io.IO$.$anonfun$archive$1(IO.scala:513)
[error] 	at sbt.io.IO$.$anonfun$archive$1$adapted(IO.scala:510)
[error] 	at sbt.io.IO$.$anonfun$withZipOutput$1(IO.scala:595)
[error] 	at sbt.io.IO$.$anonfun$withZipOutput$1$adapted(IO.scala:584)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.io.IO$.withZipOutput(IO.scala:584)
[error] 	at sbt.io.IO$.archive(IO.scala:510)
[error] 	at sbt.io.IO$.jar(IO.scala:489)
[error] 	at sbt.Package$.makeJar(Package.scala:121)
[error] 	at sbt.Package$.$anonfun$apply$4(Package.scala:76)
[error] 	at sbt.Package$.$anonfun$apply$4$adapted(Package.scala:74)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error] 	at sbt.Package$.apply(Package.scala:84)
[error] 	at sbt.Defaults$.$anonfun$packageTask$1(Defaults.scala:1086)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
```

## expectation
A fresh jar.

## notes

sbt version: *1.1.0*
I'm also using sbt-web, add and remap a file like this:
```scala
unmanagedResources in Compile += (crossTarget in (Compile, fullOptJS) in frontend).value / "frontend-opt-bundle.js",
mappings in (Compile, packageBin) += {
  (crossTarget in (Compile, fullOptJS) in frontend).value / "frontend-opt-bundle.js" -> "frontend-opt-bundle.js"
}
```

**Comment by dwijnand** [comment]
Could you provide a complete and minimal reproduction, please?

**Comment by reid-spencer** [comment]
:+1: 
In my case I'm using sbt-typescript to convert Typescript to Javascript. That all works fine, but the "packageBin" task generates a similar message. One thing to note: this occurs in my sbt-web subproject. I could probably generate a reproduction case fairly simply as my project is small so far. I'll see what I can do as this seems to be idle yet its a show stopper for me.

**Comment by reid-spencer** [comment]
Sorry, I'll retract that. My issue truly was a duplicate. But, this issue helped me find it! :)
