### ISSUE TITLE
What's with all the "New I/O worker #38" threads in sbt 1?

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#3962]
## steps

* start sbt
* inspect threads

## problem

there are 153 "New I/O worker" threads in the sbt process I'm looking at

## expectation

people sometimes need to increase the stack size to 1 or 2 MB to compile Scala code with heavily chained calls or heavily nested structure, so all those extra threads can be costly. I wouldn't expect sbt need all these threads.

## notes

sbt version: 1.1.1

similar problem https://github.com/twitter/finagle/issues/152

reported on behalf of @retronym

**Comment by eed3si9n** [comment]
What does `sbt about` say? I am guessing that you'd see `bintray.BintrayPlugin` in there.

Here's a comparison of hello world build vs sbt/io - https://gist.github.com/eed3si9n/e0d7d4d9384229acc4124baa82eb0913

```
"New I/O boss #51" #107 prio=5 os_prio=31 tid=0x00007fe1fda18800 nid=0xdf03 runnable [0x0000700024652000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
	at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
	at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000007a612a2d0> (a sun.nio.ch.Util$3)
	- locked <0x00000007a612a2c0> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000007a612a1a0> (a sun.nio.ch.KQueueSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at org.jboss.netty.channel.socket.nio.SelectorUtil.select(SelectorUtil.java:68)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.select(AbstractNioSelector.java:434)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:212)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Given that the stacktrace here says `org.jboss.netty.channel.socket`, I am guessing that this is a variant of [Possible thread leak](https://github.com/netty/netty/issues/592). Note that I am not pointing finger at Netty exactly, since the usage might be the problem not Netty itself.

sbt uses Gigahorse backed by OkHttp, not AsyncHttpClient (a Netty wrapper). So I am more suspicious of Dispatch/AsyncHttpClient that is introduced by Bintry. If you port the HTTP client to Gigahorse, I am guessing that all these threads will go away.

**Comment by retronym** [comment]
Hmm, I can't reproduce now. I'll minimize it and reopen when I see it again.

**Comment by retronym** [comment]
I see this in the build for `zinc`. That does have the bintray plugin enabled. I haven't established which plugin is using Netty.

**Comment by retronym** [comment]
I set a breakpoint in netty to see who is calling it, and as @eed3si9n suspected, it is `sbt-bintray` -> `dispatch` -> `AsyncHttpClient` -> `netty`.  I'll see if we can patch one of those to configure it to be less thread hungry.

```
  java.lang.Thread.State: RUNNABLE
	  at org.jboss.netty.channel.socket.nio.AbstractNioWorker.newThreadRenamingRunnable(AbstractNioWorker.java:84)
	  at org.jboss.netty.channel.socket.nio.AbstractNioSelector.openSelector(AbstractNioSelector.java:368)
	  at org.jboss.netty.channel.socket.nio.AbstractNioSelector.<init>(AbstractNioSelector.java:100)
	  at org.jboss.netty.channel.socket.nio.AbstractNioWorker.<init>(AbstractNioWorker.java:52)
	  at org.jboss.netty.channel.socket.nio.NioWorker.<init>(NioWorker.java:45)
	  at org.jboss.netty.channel.socket.nio.NioWorkerPool.newWorker(NioWorkerPool.java:44)
	  at org.jboss.netty.channel.socket.nio.NioWorkerPool.newWorker(NioWorkerPool.java:28)
	  at org.jboss.netty.channel.socket.nio.AbstractNioWorkerPool.init(AbstractNioWorkerPool.java:80)
	  at org.jboss.netty.channel.socket.nio.NioWorkerPool.<init>(NioWorkerPool.java:39)
	  at org.jboss.netty.channel.socket.nio.NioWorkerPool.<init>(NioWorkerPool.java:33)
	  at org.jboss.netty.channel.socket.nio.NioClientSocketChannelFactory.<init>(NioClientSocketChannelFactory.java:151)
	  at org.jboss.netty.channel.socket.nio.NioClientSocketChannelFactory.<init>(NioClientSocketChannelFactory.java:133)
	  at com.ning.http.client.providers.netty.channel.ChannelManager.<init>(ChannelManager.java:178)
	  at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.<init>(NettyAsyncHttpProvider.java:56)
	  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java:-1)
	  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	  at com.ning.http.client.AsyncHttpClient.loadDefaultProvider(AsyncHttpClient.java:562)
	  at com.ning.http.client.AsyncHttpClient.<init>(AsyncHttpClient.java:187)
	  at dispatch.InternalDefaults$.client(defaults.scala:31)
	  at dispatch.Http$.<init>(execution.scala:30)
	  at dispatch.Http$.<clinit>(execution.scala:-1)
	  at bintray.BintrayRepo.<init>(BintrayRepo.scala:12)
	  at bintray.Bintray$.$anonfun$cachedRepo$1(Bintray.scala:53)
	  at bintray.Bintray$$$Lambda$3291.1921505764.apply(Unknown Source:-1)
	  at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:903)
	  at bintray.Bintray$.cachedRepo(Bintray.scala:53)
	  at bintray.Bintray$.$anonfun$withRepo$1(Bintray.scala:47)
	  at bintray.Bintray$$$Lambda$3284.1566391724.apply(Unknown Source:-1)
	  at scala.Option.map(Option.scala:146)
	  at bintray.Bintray$.withRepo(Bintray.scala:46)
	  at bintray.BintrayPlugin$.$anonfun$publishToBintray$1(BintrayPlugin.scala:180)
	  at bintray.BintrayPlugin$$$Lambda$2949.490796439.apply(Unknown Source:-1)
	  at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:219)
	  at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:164)
	  - locked <0x2a17> (a sbt.internal.util.EvaluateSettings$MixedNode)
	  at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
	  at sbt.internal.util.EvaluateSettings$$Lambda$1608.564787547.apply$mcV$sp(Unknown Source:-1)
	  at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:98)
	  at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	  at java.lang.Thread.run(Thread.java:748)
```

**Comment by retronym** [comment]
Spun this over to https://github.com/sbt/sbt-bintray/issues/144
