### ISSUE TITLE
cross building using `+compile` with subprojects fails in sbt 1.1.1 (due to incorrect settings)

### ISSUE THREAD

**Issue by ucbjrl** [sbt/sbt#3986]
## steps

This is distilled from a larger, more complex project, but seems to demonstrate the problem.
My layout is:
top/
  src/main/scala/hello/main.scala
  world/src/main/scala/hello/sub/World.scala
  build.sbt

where main.scala contains:
```scala
package hello

import hello._

object Hello {
  def main(args: Array[String]) {
    println("Hello, " + sub.World.string)
  }
}
```
and World.scala contains:
```scala
package hello.sub

object World {
  val string = "world"
}
```
and build.sbt contains:
```scala
name := "projwithsub"

version := "0.1"

scalaVersion := "2.12.4"

crossScalaVersions := Seq("2.11.12", "2.12.4")

lazy val world = (project in file("world"))

lazy val hello = (project in file("."))
  .dependsOn(world)
```

That is, I have a top-level project that depends on a sub-project. I can compile and run the combination successfully:
```bash
% sbt clean run ++2.11.12
 ...
[info] Loading project definition from .../project
[info] Loading settings from build.sbt ...
[info] Set current project to projwithsub (in build file:.../)
[success] Total time: 0 s, completed Mar 5, 2018 4:23:14 PM
[info] Updating ...
[info] Done updating.
[info] Compiling 1 Scala source to .../target/scala-2.12/classes ...
[info] Done compiling.
[info] Packaging .../target/scala-2.12/projwithsub_2.12-0.1.jar ...
[info] Done packaging.
[info] Running hello.Hello 
Hello, world
[success] Total time: 3 s, completed Mar 5, 2018 4:23:17 PM
[info] Setting Scala version to 2.11.12 on 1 projects.
[info] Excluded 1 projects, run ++ 2.11.12 -v for more details.
[info] Reapplying settings...
[info] Set current project to projwithsub (in build file:.../)

Compilation finished at Mon Mar  5 16:23:18

% sbt clean run ++2.12.4
 ...
[info] Loading project definition from .../project
[info] Loading settings from build.sbt ...
[info] Set current project to projwithsub (in build file:.../)
[success] Total time: 0 s, completed Mar 5, 2018 4:26:08 PM
[info] Updating ...
[info] Done updating.
[info] Compiling 1 Scala source to .../target/scala-2.12/classes ...
[info] Done compiling.
[info] Packaging .../target/scala-2.12/projwithsub_2.12-0.1.jar ...
[info] Done packaging.
[info] Running hello.Hello 
Hello, world
[success] Total time: 3 s, completed Mar 5, 2018 4:26:12 PM
[info] Setting Scala version to 2.12.4 on 2 projects.
[info] Reapplying settings...
[info] Set current project to projwithsub (in build file:.../)

Compilation finished at Mon Mar  5 16:26:12
```

## problem
Attempting to run (or compile or package) using `+<command>` fails:
```bash
% sbt +clean +run
 ...
[info] Loading project definition from .../project
[info] Loading settings from build.sbt ...
[info] Set current project to projwithsub (in build file:.../)
[info] Setting Scala version to 2.12.4 on 2 projects.
[info] Reapplying settings...
[info] Set current project to projwithsub (in build file:.../)
[success] Total time: 0 s, completed Mar 5, 2018 4:29:11 PM
[info] Setting Scala version to 2.11.12 on 1 projects.
[info] Excluded 1 projects, run ++ 2.11.12 -v for more details.
[info] Reapplying settings...
[info] Set current project to projwithsub (in build file:.../)
[success] Total time: 0 s, completed Mar 5, 2018 4:29:12 PM
[info] Reapplying settings...
[info] Set current project to projwithsub (in build file:.../)
[info] Setting Scala version to 2.12.4 on 2 projects.
[info] Reapplying settings...
[info] Set current project to projwithsub (in build file:.../)
[info] Updating ...
[info] Done updating.
[info] Compiling 1 Scala source to .../target/scala-2.12/classes ...
[info] Done compiling.
[info] Packaging .../target/scala-2.12/projwithsub_2.12-0.1.jar ...
[info] Done packaging.
[info] Running hello.Hello 
Hello, world
[success] Total time: 3 s, completed Mar 5, 2018 4:29:16 PM
[info] Setting Scala version to 2.11.12 on 1 projects.
[info] Excluded 1 projects, run ++ 2.11.12 -v for more details.
[info] Reapplying settings...
[info] Set current project to projwithsub (in build file:.../)
[info] Updating ...
[warn] 	module not found: world#world_2.11;0.1.0-SNAPSHOT
[warn] ==== local: tried
[warn]   .../.ivy2/local/world/world_2.11/0.1.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/world/world_2.11/0.1.0-SNAPSHOT/world_2.11-0.1.0-SNAPSHOT.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   .../.sbt/preloaded/world/world_2.11/0.1.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file://.../.sbt/preloaded/world/world_2.11/0.1.0-SNAPSHOT/world_2.11-0.1.0-SNAPSHOT.pom
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: world#world_2.11;0.1.0-SNAPSHOT: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		world:world_2.11:0.1.0-SNAPSHOT
[warn] 		  +- projwithsub:projwithsub_2.11:0.1
[error] sbt.librarymanagement.ResolveException: unresolved dependency: world#world_2.11;0.1.0-SNAPSHOT: not found
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:331)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:205)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:242)
[error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:190)
[error] 	at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:46)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:99)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:112)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:112)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:95)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:126)
[error] 	at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2383)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] (update) sbt.librarymanagement.ResolveException: unresolved dependency: world#world_2.11;0.1.0-SNAPSHOT: not found
[error] Total time: 2 s, completed Mar 5, 2018 4:29:18 PM

Compilation exited abnormally with code 1 at Mon Mar  5 16:29:18
```
and similar results for `+compile`, `+package`.

## expectation
```bash
% sbt +clean +compile
```
should be substantially the same as
```bash
% sbt ++2.11.12 clean run
% sbt ++2.12.4 clean run
```

## notes

sbt version: 1.1.1

**Comment by ucbjrl** [comment]
It looks like it's more complicate than this. My simple `++2.11.12` test fails when I put the version specifier at the head of the command chain.
I'll update this, possibly closing it and submitting a new issue, tomorrow.

**Comment by eed3si9n** [comment]
You might want to try:

```scala
ThisBuild / scalaVersion := "2.12.4"
ThisBuild / crossScalaVersions := Seq("2.11.12", "2.12.4")
```

bare setting otherwise would just apply to the root project only.

**Comment by ucbjrl** [comment]
Thanks @eed3si9n. I'm renaming and closing this issue.
