### ISSUE TITLE
Classpath strangeness with 1.0.4+

### ISSUE THREAD

**Issue by NeQuissimus** [sbt/sbt#4014]
I am encountering an issue that I cannot find out enough about to really point anybody in a concrete direction.

So let me provide as much information as possible:

I have a multi-project `build.sbt` that uses sbt 1.1.1.

- `project A` contains a Kafka Streams dependency
- `project B` also contains a Kafka Streams dependency (which I do not really need but I like it for clarity rather than transitively) and a dependency on `project A` via `dependsOn` in the `build.sbt`
- `project B` has `specs2` tests

When I issue `sbt projectB/test`, all tests pass.
Then I run `sbt project/test` again (without changes), I get a stack trace similar to the following:

```
java.lang.ExceptionInInitializerError
	at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:509)
	at com.nequissimus.norm.Foo$.$anonfun$prepare$1(Foo.scala:61)
	at scalaz.effect.IO$.$anonfun$apply$2(IO.scala:178)
	at scalaz.std.FunctionInstances$$anon$1.$anonfun$map$1(Function.scala:77)
	at scalaz.Free.$anonfun$run$1(Free.scala:271)
	at scalaz.Free.go2$1(Free.scala:162)
	at scalaz.Free.go(Free.scala:165)
	at scalaz.Free.run(Free.scala:271)
	at scalaz.effect.IO.unsafePerformIO(IO.scala:22)
	at com.nequissimus.norm.FooSpec.$anonfun$duo2cloudlog$5(FooSpec.scala:61)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:655)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:289)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:140)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: org.apache.kafka.common.config.ConfigException: Invalid value org.apache.kafka.streams.errors.LogAndFailExceptionHandler for configuration default.deserialization.exception.handler: Class org.apache.kafka.streams.errors.LogAndFailExceptionHandler could not be found.
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:715)
	at org.apache.kafka.common.config.ConfigDef$ConfigKey.<init>(ConfigDef.java:945)
	at org.apache.kafka.common.config.ConfigDef.define(ConfigDef.java:137)
	at org.apache.kafka.common.config.ConfigDef.define(ConfigDef.java:157)
	at org.apache.kafka.common.config.ConfigDef.define(ConfigDef.java:196)
	at org.apache.kafka.common.config.ConfigDef.define(ConfigDef.java:358)
	at org.apache.kafka.common.config.ConfigDef.define(ConfigDef.java:371)
	at org.apache.kafka.streams.StreamsConfig.<clinit>(StreamsConfig.java:309)
	... 23 more
```

If I change anything inside the test specification (`FooSpec`) then `sbt projectB/test` will work again, exactly once.

This issue seems to be new to sbt 1.0.4 (I do not encounter the same problem with 0.13.17 or 1.0.{0, 1, 2, 3} but do with 1.0.4 and 1.1.1; I literally just tried all of these)

The interesting bit (to me) here is that Kafka throws an exception that would typically indicate that an old version of `kafka-clients` is present. However, nowhere in my dependency tree, such version can be found. So I presume something else is going on that I do not understand (a class unloaded?)
This is really beyond my understanding of internals, I hope somebody can make sense of this.
I am willing to provide additional information if somebody points me in the right direction.

Unfortunately, I was unable to create a minimal reproduction (I tried).

**Comment by jdrphillips** [comment]
We had a very similar issue in our project.

Like you, not very sure what's going on and it seems to be a confluence of issues.

We were creating an actor context inside a specs2 `in` block. Moving this creation to a context to be used as `in ActorContext {...}` instead worked for us. We made sure `ActorContext` was a top-level trait. Note we are also on `sbt 1.1.x` and I cannot comment on `sbt 1.0.4`.

That kafka exception you're seeing is also a problem we had. We concluded it was unrelated and merely revealed by the upgrade to `sbt 1.x.x`. Our tests ran fine consistently and repeatedly even with that (or similar) exception. We concluded it was an issue with the underlying library (but we no longer use kafka so again I cannot comment further).

The issue which clued us in to it being a specs2 thing rather than an sbt thing is: https://github.com/etorreborre/specs2/issues/556

I do not know why the upgrade of sbt reveals this issue, all other things being the same.

**Comment by eed3si9n** [comment]
Thank you for a detailed report!
Since you narrowed it down to 1.0.4, we can try to guess the cause from list of changes we've added there - https://github.com/sbt/sbt/releases/tag/v1.0.4

What do you get for running `show test:externalDependencyClasspath` do you see any difference before and after running your test once?

**Comment by NeQuissimus** [comment]
I just tried doing that from a different (much faster) machine and can't ever get the tests to pass.
I will run take a look at the classpath from the original machine.
Considering the above observation, we may be looking at some race condition.
Will report back once I have more data.

**Comment by NeQuissimus** [comment]
@eed3si9n I grabbed the classpath output with all of 1.0.3/1.0.4/1.1.0, each before first running the tests, after the first run and after the second run.
All outputs are identical.

Here is something I did find out that is interesting:
I generally run `git clean -xfd` to remove anything untracked (i.e. `target/`), then `rm -rf ~/.sbt ~/.cache/coursier ~/.ivy2/cache` to get rid of my caches.

- On 1.0.3 I can run my tests over and over and they always work and pass.
- On 1.0.4+ they always fail with the stack trace from above.

The above is true **unless** I unplug my laptop from the power adapter (the CPU clock goes down to 900 MHz; Intel m3 CPU) :)
The moment my CPU clock is low, the tests run successfully once before throwing the stack trace upon subsequent runs.

**Comment by eed3si9n** [comment]
> The interesting bit (to me) here is that Kafka throws an exception that would typically indicate that an old version of kafka-clients is present. However, nowhere in my dependency tree, such version can be found. So I presume something else is going on that I do not understand (a class unloaded?)

Does this go away if you forked the test?

```scala
Test / fork := true
```

**Comment by NeQuissimus** [comment]
I have not seen this issue in a very long time. I think we can close this issue.
