### ISSUE TITLE
 [error] scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.

### ISSUE THREAD

**Issue by saikartik1990** [sbt/sbt#4068]
(See the guidelines for contributing, linked above)

## steps
Downloaded Word Count Scala with Storm  Program from google.
JDK 10 Installed.
sbt version 1.1.2
Executed command sbt

## problem

[error] scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.

## expectation

No Error

## notes
[BigDataWithScala-master.zip](https://github.com/sbt/sbt/files/1880408/BigDataWithScala-master.zip)

sbt version: *sbt - 1.1.2*

**Comment by dwijnand** [comment]
that project has `sbt.version` in `project/build.properties` defined as 0.13.13.

if you upgrade it to 0.13.17 it loads.

**Comment by saikartik1990** [comment]
It Worked. Thanks a lot @dwijnand

**Comment by JuKu** [comment]
@dwijnand I have the same problem with Java 10 maven 3.5.4 and **scala-maven-plugin version 3.4.2** .
```text
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T20:33:14+02:00)
Maven home: D:\Users\Justin\apache-maven-3.5.4
Java version: 10, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-10
Default locale: de_DE, platform encoding: UTF-8
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

Source code:
https://github.com/JuKu/rembulan/tree/9fda32856411c86c920589a6024b9f6f7ad2d08c

Exception:
```java
[INFO] --- scala-maven-plugin:3.4.2:testCompile (scala-test-compile) @ rembulan-tests ---
[INFO] D:\Users\Justin\IdeaProjects\java-lua-rembulan\rembulan-tests\src\test\java:-1: info: compiling
[INFO] D:\Users\Justin\IdeaProjects\java-lua-rembulan\rembulan-tests\src\test\scala:-1: info: compiling
[INFO] Compiling 36 source files to D:\Users\Justin\IdeaProjects\java-lua-rembulan\rembulan-tests\target\test-classes at 1539273491567
[ERROR] error: scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
[ERROR] 	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:17)
[ERROR] 	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:18)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:53)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:66)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getClassByName(Mirrors.scala:102)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getRequiredClass(Mirrors.scala:105)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:257)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:257)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1374)
[ERROR] 	at scala.tools.nsc.Global$Run.<init>(Global.scala:1278)
[ERROR] 	at scala.tools.nsc.Driver.doCompile(Driver.scala:33)
[ERROR] 	at scala.tools.nsc.MainClass.doCompile(Main.scala:23)
[ERROR] 	at scala.tools.nsc.Driver.process(Driver.scala:55)
[ERROR] 	at scala.tools.nsc.Driver.main(Driver.scala:68)
[ERROR] 	at scala.tools.nsc.Main.main(Main.scala)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[ERROR] 	at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
[ERROR] 	at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
```

**Comment by eed3si9n** [comment]
Please report to scala-maven-plugin instead.
