### ISSUE TITLE
java.lang.NoClassDefFoundError while trying to use ImageIO extension

### ISSUE THREAD

**Issue by eximius313** [sbt/sbt#4069]
## steps
1) Use quickstart in attachment: [sbt-quickstart.zip](https://github.com/sbt/sbt/files/1881667/sbt-quickstart.zip)
2) Execute `sbt run` - it fails. 
3) Execute `./gradlew run` - it works fine

## problem
I have an application, that is using ImageIO.read(imageFile) and I want to read CMYK image. 
Java doesn't support this out of the box, so I wanted to use https://github.com/haraldk/TwelveMonkeys extension to ImageIO.
When I run application with:
```
  "com.twelvemonkeys.imageio" % "imageio-jpeg" % "3.3.2",
  "com.twelvemonkeys.imageio" % "imageio-tiff" % "3.3.2",
  "com.twelvemonkeys.imageio" % "imageio-bmp" % "3.3.2",
```
in my classpath, sbt throws:
```
[error] (run-main-0) java.lang.NoClassDefFoundError: com/twelvemonkeys/imageio/spi/ImageWriterSpiBase
[error] java.lang.NoClassDefFoundError: com/twelvemonkeys/imageio/spi/ImageWriterSpiBase
[error]         at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[error]         at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1007)
[error]         at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
[error]         at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:545)
[error]         at java.base/java.net.URLClassLoader.access$100(URLClassLoader.java:83)
[error]         at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:453)
[error]         at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:447)
[error]         at java.base/java.security.AccessController.doPrivileged(Native Method)
[error]         at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:446)
[error]         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
[error]         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:550)
[error]         at sbt.internal.inc.classpath.ClasspathFilter.loadClass(ClassLoaders.scala:70)
[error]         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
[error]         at java.base/java.lang.Class.forName0(Native Method)
[error]         at java.base/java.lang.Class.forName(Class.java:375)
[error]         at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1204)
[error]         at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1215)
[error]         at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.access$1200(ServiceLoader.java:1103)
[error]         at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator$1.run(ServiceLoader.java:1262)
[error]         at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator$1.run(ServiceLoader.java:1261)
[error]         at java.base/java.security.AccessController.doPrivileged(Native Method)
[error]         at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
[error]         at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1294)
[error]         at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1379)
[error]         at java.desktop/javax.imageio.spi.IIORegistry.registerApplicationClasspathSpis(IIORegistry.java:207)
[error]         at java.desktop/javax.imageio.spi.IIORegistry.<init>(IIORegistry.java:136)
[error]         at java.desktop/javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:157)
[error]         at java.desktop/javax.imageio.ImageIO.<clinit>(ImageIO.java:66)
[error]         at demo.Main.main(Main.java:14)
```

## expectation
I can use ImageIO excentsions normally

## notes
sbt version: *1.1.2*

**Comment by eximius313** [comment]
Did you managed to reproduce the problem from the sample?

**Comment by eed3si9n** [comment]
@eximius313 Thanks for the report.
I think I had reproduced it before, but forgot to report it here. I just downloaded it again, and was able to reproduce the issue in sbt 1.1.4 as well.

I wonder if there's some problem with the `run` or somehow the resolved JARs became different from that of Gradle.

**Comment by eximius313** [comment]
@eed3si9n I have no idea... Is there something I can do to help you identify the problem?

**Comment by eed3si9n** [comment]
Here are the difference in the way the dependencies resolved:

```
sbt:sbt-quickstart> show Runtime/fullClasspath
[info] Compiling 1 Java source to /Users/xxx/Downloads/sbt-quickstart/target/scala-2.12/classes ...
[info] Done compiling.
[info] * Attributed(/Users/xxx/Downloads/sbt-quickstart/target/scala-2.12/classes)
[info] * Attributed(/Users/xxx/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.12.2.jar)
[info] * Attributed(/Users/xxx/.ivy2/cache/com.twelvemonkeys.imageio/imageio-jpeg/jars/imageio-jpeg-3.3.2.jar)
[info] * Attributed(/Users/xxx/.ivy2/cache/com.twelvemonkeys.imageio/imageio-metadata/jars/imageio-metadata-3.3.2.jar)
[info] * Attributed(/Users/xxx/.ivy2/cache/com.twelvemonkeys.common/common-lang/jars/common-lang-3.3.2.jar)
[info] * Attributed(/Users/xxx/.ivy2/cache/com.twelvemonkeys.common/common-io/jars/common-io-3.3.2.jar)
[info] * Attributed(/Users/xxx/.ivy2/cache/com.twelvemonkeys.common/common-image/jars/common-image-3.3.2.jar)
[info] * Attributed(/Users/xxx/.ivy2/cache/com.twelvemonkeys.imageio/imageio-tiff/jars/imageio-tiff-3.3.2.jar)
[info] * Attributed(/Users/xxx/.ivy2/cache/com.twelvemonkeys.imageio/imageio-bmp/jars/imageio-bmp-3.3.2.jar)
[info] * Attributed(/Users/xxx/.ivy2/cache/junit/junit/jars/junit-4.12.jar)
[info] * Attributed(/Users/xxx/.ivy2/cache/org.hamcrest/hamcrest-core/jars/hamcrest-core-1.3.jar)
```

```
> Task :printClasspath
/Users/xxx/.gradle/caches/modules-2/files-2.1/com.twelvemonkeys.imageio/imageio-jpeg/3.3.2/571aa1b4cd3f38f8b90e88c8f3e240bdc0a478ff/imageio-jpeg-3.3.2.jar
/Users/xxx/.gradle/caches/modules-2/files-2.1/com.twelvemonkeys.imageio/imageio-tiff/3.3.2/9bea1214eae7d287dc0c685fb6be75102318d080/imageio-tiff-3.3.2.jar
/Users/xxx/.gradle/caches/modules-2/files-2.1/com.twelvemonkeys.imageio/imageio-bmp/3.3.2/7b1beeb95a4f961c3c4634b3dca0a1b9c12d70c5/imageio-bmp-3.3.2.jar
/Users/xxx/.gradle/caches/modules-2/files-2.1/com.twelvemonkeys.imageio/imageio-metadata/3.3.2/b8a31725bde0dc6f4e6b01711784f5ca0a2275f3/imageio-metadata-3.3.2.jar
/Users/xxx/.gradle/caches/modules-2/files-2.1/com.twelvemonkeys.imageio/imageio-core/3.3.2/8def41c756831dde3c23f2d525e5667cfbfa1847/imageio-core-3.3.2.jar
/Users/xxx/.gradle/caches/modules-2/files-2.1/com.twelvemonkeys.common/common-image/3.3.2/9c975152864050c6dbb7226ca1100694f0aa099d/common-image-3.3.2.jar
/Users/xxx/.gradle/caches/modules-2/files-2.1/com.twelvemonkeys.common/common-io/3.3.2/e00b1c744993864d3c8dc698ba7d356122019398/common-io-3.3.2.jar
/Users/xxx/.gradle/caches/modules-2/files-2.1/com.twelvemonkeys.common/common-lang/3.3.2/ffbc5e05208c5c9cb43052438294c3ec5546aecf/common-lang-3.3.2.jar
```

Note that imageio-core is missing from sbt, which I haven't check if it's a bug or expected.
Adding

```scala
  "com.twelvemonkeys.imageio" % "imageio-core" % "3.3.2",
```

seems to get the program to run at least.
