### ISSUE TITLE
Issue with resolving dependencies in Sbt / scala

### ISSUE THREAD

**Issue by satishbanka** [sbt/sbt#4100]
When trying to add libraries for nlp using pyspark i am getting the below error

## steps
I tried removing ~/.ivy2/  and rebuilding the project using sbt. 
sbt compile is successful. when i am trying to launch pyspark with 
pyspark --packages JohnSnowLabs:spark-nlp:1.5.0

I am getting below error

## problem
:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: commons-codec#commons-codec;1.9: not found, unresolved dependency: com.fasterxml.jackson.core#jackson-annotations;2.6.0: not found, download failed: commons-logging#commons-logging;1.1.3!commons-logging.jar]
        at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1204)
        at org.apache.spark.deploy.SparkSubmit$.prepareSubmitEnvironment(SparkSubmit.scala:304)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:153)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

## expectation

Please advise on resolving the issue

## notes

sbt version: *0.13.1*

**Comment by dwijnand** [comment]
https://www.scala-sbt.org/support.html
