### ISSUE TITLE
StackOverflowError in consoleProject

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [sbt/sbt#4134]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

## steps

```
> consoleProject
[warn] Managed execution not possible: security manager not installed.
[info] Starting scala interpreter...
Welcome to Scala 2.12.4 (OpenJDK 64-Bit Server VM, Java 1.8.0_162).
Type in expressions for evaluation. Or try :help.

scala> java.lang.StackOverflowError
	at scala.tools.nsc.typechecker.Contexts$Context.make(Contexts.scala:478)
	at scala.tools.nsc.typechecker.Contexts$Context.makeSilent(Contexts.scala:526)
	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:693)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4710)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4757)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5530)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5547)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5584)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5616)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5557)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5562)
	at scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5667)
	at scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5673)
	at scala.tools.nsc.typechecker.Typers$Typer.typedSelectOrSuperCall$1(Typers.scala:5008)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5531)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5547)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5584)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5616)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5557)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5562)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$38(Typers.scala:4708)
	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:698)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4710)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4757)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5530)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5547)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5584)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5616)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5557)
```

## problem

I cannot use the `consoleProject` command

## expectation

I expect to have an usable console.

## notes

Linux 64 bits
Java 8
sbt version: SBT 1.1.2

I think there is infinite recursion.

I can provide privately my project build configuration, if necessary.

**Comment by DavidPerezIngeniero** [comment]
The only special thing I see in my project is that I have 2 `.sbt` files.

**Comment by dwijnand** [comment]
> I can provide privately my project build configuration, if necessary.

We'd need some kind of reproduction to be able to move this forward. Accepting it privately makes it cumbersome, as it's dissociated from this issue :-/

**Comment by DavidPerezIngeniero** [comment]
[my-build.zip](https://github.com/sbt/sbt/files/1966232/my-build.zip)
Here is my build configuration.

**Comment by metasim** [comment]
I'm having the same problem in `0.13.17`. Unfortunately I can't share this particular build configuration. Will followup if I isolate it.

My backtrace is a bit different:

```
> consoleProject
[info] Starting scala interpreter...
[info] 
[error] (run-main-3) java.lang.StackOverflowError

java.lang.StackOverflowError
	at java.io.PrintWriter.<init>(PrintWriter.java:116)
	at java.io.PrintWriter.<init>(PrintWriter.java:100)
	at scala.reflect.api.Printers$class.render(Printers.scala:168)
	at scala.reflect.api.Universe.render(Universe.scala:59)
	at scala.reflect.api.Printers$class.show(Printers.scala:190)
	at scala.reflect.api.Universe.show(Universe.scala:59)
	at scala.reflect.api.Printers$class.treeToString(Printers.scala:182)
	at scala.reflect.api.Universe.treeToString(Universe.scala:59)
	at scala.reflect.api.Trees$TreeApi$class.toString(Trees.scala:192)
	at scala.reflect.internal.Trees$TreeContextApiImpl.toString(Trees.scala:76)

...

	at scala.reflect.internal.Printers$class.backquotedPath(Printers.scala:57)
	at scala.reflect.internal.SymbolTable.backquotedPath(SymbolTable.scala:13)
	at scala.reflect.internal.Printers$TreePrinter.printTree(Printers.scala:382)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:22)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:19)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	at scala.tools.nsc.ast.Printers$TreePrinter.print(Printers.scala:19)
	at scala.reflect.internal.Printers$TreePrinter.printTree(Printers.scala:357)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:22)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:19)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	at scala.tools.nsc.ast.Printers$TreePrinter.print(Printers.scala:19)
	at scala.reflect.api.Printers$class.render(Printers.scala:174)
	at scala.reflect.api.Universe.render(Universe.scala:59)
	at scala.reflect.api.Printers$class.show(Printers.scala:190)
	at scala.reflect.api.Universe.show(Universe.scala:59)
	at scala.reflect.api.Printers$class.treeToString(Printers.scala:182)
	at scala.reflect.api.Universe.treeToString(Universe.scala:59)
	at scala.reflect.api.Trees$TreeApi$class.toString(Trees.scala:192)
	at scala.reflect.internal.Trees$TreeContextApiImpl.toString(Trees.scala:76)
	at scala.reflect.internal.Printers$class.backquotedPath(Printers.scala:57)
	at scala.reflect.internal.SymbolTable.backquotedPath(SymbolTable.scala:13)
```

**Comment by metasim** [comment]
Related: https://github.com/sbt/sbt/issues/2317

**Comment by metasim** [comment]
In case it's relevant, here are the loaded plugins:

```
	sbt.plugins.IvyPlugin
	sbt.plugins.JvmPlugin
	sbt.plugins.CorePlugin
	sbt.plugins.JUnitXmlReportPlugin
	sbt.plugins.Giter8TemplatePlugin
	com.timushev.sbt.updates.UpdatesPlugin
	net.virtualvoid.sbt.graph.DependencyGraphPlugin
	com.typesafe.sbt.SbtLicenseReport
	com.blstream.sbtsearchmavenplugin.SbtSearchMavenPlugin
	sbtassembly.AssemblyPlugin
	com.typesafe.sbt.SbtNativePackager
	com.typesafe.sbt.packager.archetypes.JavaAppPackaging
	com.typesafe.sbt.packager.archetypes.JavaServerAppPackaging
	com.typesafe.sbt.packager.archetypes.jar.ClasspathJarPlugin
	com.typesafe.sbt.packager.archetypes.jar.LauncherJarPlugin
	com.typesafe.sbt.packager.archetypes.scripts.AshScriptPlugin
	com.typesafe.sbt.packager.archetypes.scripts.BashStartScriptPlugin
	com.typesafe.sbt.packager.archetypes.scripts.BatStartScriptPlugin
	com.typesafe.sbt.packager.archetypes.systemloader.SystemVPlugin
	com.typesafe.sbt.packager.archetypes.systemloader.SystemdPlugin
	com.typesafe.sbt.packager.archetypes.systemloader.SystemloaderPlugin
	com.typesafe.sbt.packager.archetypes.systemloader.UpstartPlugin
	com.typesafe.sbt.packager.debian.DebianDeployPlugin
	com.typesafe.sbt.packager.debian.DebianPlugin
	com.typesafe.sbt.packager.debian.JDebPackaging
	com.typesafe.sbt.packager.docker.DockerPlugin
	com.typesafe.sbt.packager.docker.DockerSpotifyClientPlugin
	com.typesafe.sbt.packager.jdkpackager.JDKPackagerDeployPlugin
	com.typesafe.sbt.packager.jdkpackager.JDKPackagerPlugin
	com.typesafe.sbt.packager.linux.LinuxPlugin
	com.typesafe.sbt.packager.rpm.RpmDeployPlugin
	com.typesafe.sbt.packager.rpm.RpmPlugin
	com.typesafe.sbt.packager.universal.UniversalDeployPlugin
	com.typesafe.sbt.packager.universal.UniversalPlugin
	com.typesafe.sbt.packager.windows.WindowsDeployPlugin
	com.typesafe.sbt.packager.windows.WindowsPlugin
	de.heikoseeberger.sbtheader.AutomateHeaderPlugin
	de.heikoseeberger.sbtheader.HeaderPlugin
	com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin
	com.lucidchart.sbt.scalafmt.ScalafmtPlugin
	com.lucidchart.sbt.scalafmt.ScalafmtSbtPlugin
	tut.TutPlugin
	com.typesafe.sbt.site.SitePlugin
	com.typesafe.sbt.site.SitePreviewPlugin
	com.typesafe.sbt.site.SiteScaladocPlugin
	com.typesafe.sbt.site.asciidoctor.AsciidoctorPlugin
	com.typesafe.sbt.site.gitbook.GitBookPlugin
	com.typesafe.sbt.site.hugo.HugoPlugin
	com.typesafe.sbt.site.jekyll.JekyllPlugin
	com.typesafe.sbt.site.laika.LaikaSitePlugin
	com.typesafe.sbt.site.nanoc.NanocPlugin
	com.typesafe.sbt.site.pamflet.PamfletPlugin
	com.typesafe.sbt.site.paradox.ParadoxSitePlugin: enabled in docs
	com.typesafe.sbt.site.preprocess.PreprocessPlugin
	com.typesafe.sbt.site.sphinx.SphinxPlugin
	com.lightbend.paradox.sbt.ParadoxPlugin
	com.typesafe.sbt.web.SbtWeb
	sbtbuildinfo.BuildInfoPlugin
	com.servicerocket.sbt.release.git.flow.SbtGitFlowReleasePlugin
	sbtrelease.ReleasePlugin
```

**Comment by som-snytt** [comment]
If you're close to exhausting stack, `-Xprint:all` is another test.

**Comment by metasim** [comment]
Here's another stack trace:

```
java.lang.StackOverflowError
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4651)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4757)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5530)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5547)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5584)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5616)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5557)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5562)
	at scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5667)
	at scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5673)
	at scala.tools.nsc.typechecker.Typers$Typer.typedSelectOrSuperCall$1(Typers.scala:5008)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5531)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5547)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5584)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5616)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5557)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5562)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$38(Typers.scala:4708)
	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:698)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4710)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4757)
...
```

@DavidPerezIngeniero did you ever find a work-around?

**Comment by DavidPerezIngeniero** [comment]
I have `consoleProject` inusuable for a long time, with SBT 1.x and SBT 0.13.x.

**Comment by eed3si9n** [comment]
I was able to run consoleProject using the zip file provided.
@eatkins discovered that updating to the latest launcher JAR fixed the `consoleProject` at least in some cases, so I might suggest that.

**Comment by DavidPerezIngeniero** [comment]
Here is the result when using SBT 1.3.2 launcher:

```
> consoleProject
[warn] Managed execution not possible: security manager not installed.
[info] Starting scala interpreter...
Welcome to Scala 2.12.4 (OpenJDK 64-Bit Server VM, Java 1.8.0_222).
Type in expressions for evaluation. Or try :help.

scala> 1+1
java.lang.StackOverflowError
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5554)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5562)
	at scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5667)
	at scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5673)
	at scala.tools.nsc.typechecker.Typers$Typer.typedSelectOrSuperCall$1(Typers.scala:5008)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5531)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5547)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5584)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5616)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5557)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5562)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$38(Typers.scala:4708)
	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:698)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4710)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4757)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5530)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5547)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5584)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5616)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5557)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5562)
	at scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5667)
	at scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5673)
	at scala.tools.nsc.typechecker.Typers$Typer.typedSelectOrSuperCall$1(Typers.scala:5008)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5531)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5547)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5584)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5616)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5557)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5562)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$38(Typers.scala:4708)
	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:698)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4710)
```

**Comment by SethTisue** [comment]
I think we should just close this, as we don't have a minimized reproducer and it seems likely the root cause is in some plugin.

We can reopen the ticket if someone 1) shows that the problem exists in current sbt, 2) provides a minimized reproduction (and if the minimized reproduction still involves one more more plugins, we would need evidence that the root cause is in sbt and not one of the plugins).
