### ISSUE TITLE
API phase too eager when computing dependencies on binary types

### ISSUE THREAD

**Issue by dragos** [sbt/sbt#417]
Using 0.11.2.

I have the following crash in the build compiler inside Eclipse. It basically complains about a type not being on my classpath. I think it needn't be, since it's referenced from a classfile on my classpath (that I don't use). The dependency graph is:

my project -> sdt.core -> org.eclipse.jface

on my classpath I have only sdt.core.jar. 

Since the typer succeeded, it means that type wasn't needed for compilation. I wonder if the API phase could skip types that have not been yet completed (so, never force a lazy type).

```
scala.reflect.internal.Types$TypeError: while unpickling /Users/dragos/workspace/git/plugin/dragos-scala-ide/org.scala ide.sdt.core/target/classes/scala/tools/eclipse/javaelements/ScalaOverrideIndicatorBuilder.class, reference value jface of package org.eclipse/List(package eclipse, package org, package <root>)/
   package jdt not found.
at scala.reflect.internal.pickling.UnPickler$Scan.toTypeError(UnPickler.scala:842)
at scala.reflect.internal.pickling.UnPickler$Scan$LazyTypeRef.complete(UnPickler.scala:855)
at scala.reflect.internal.pickling.UnPickler$Scan$LazyTypeRef.load(UnPickler.scala:857)
at scala.reflect.internal.Symbols$Symbol.typeParams(Symbols.scala:1218)
at xsbt.API.typeParameters(API.scala:323)
at xsbt.API.xsbt$API$$mkClassLike(API.scala:354)
at xsbt.API$$anonfun$xsbt$API$$classLike$1.apply(API.scala:340)
at xsbt.API$$anonfun$xsbt$API$$classLike$1.apply(API.scala:340)
at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:169)
at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:91)
at xsbt.API.xsbt$API$$classLike(API.scala:340)
at xsbt.API.xsbt$API$$definition(API.scala:250)
at xsbt.API$$anonfun$xsbt$API$$processDefinitions$1.apply(API.scala:244)
at xsbt.API$$anonfun$xsbt$API$$processDefinitions$1.apply(API.scala:244)
at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:247)
at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:247)
at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:34)
at scala.collection.mutable.ArrayOps.foreach(ArrayOps.scala:38)
at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:247)
at scala.collection.mutable.ArrayOps.flatMap(ArrayOps.scala:38)
at xsbt.API.xsbt$API$$processDefinitions(API.scala:244)
at xsbt.API$$anonfun$mkStructure$3.apply(API.scala:242)
at xsbt.API$$anonfun$mkStructure$3.apply(API.scala:242)
at xsbt.Message$$anon$1.apply(Message.scala:8)
at xsbti.SafeLazy$$anonfun$apply$1.apply(SafeLazy.scala:8)
at xsbti.SafeLazy$Impl._t(SafeLazy.scala:20)
at xsbti.SafeLazy$Impl.get(SafeLazy.scala:24)
at xsbt.API$$anonfun$xsbt$API$$forceStructures$1.apply(API.scala:94)
at xsbt.API$$anonfun$xsbt$API$$forceStructures$1.apply(API.scala:94)
at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
at scala.collection.immutable.List.foreach(List.scala:77)
at xsbt.API.xsbt$API$$forceStructures(API.scala:94)
at xsbt.API$ApiPhase.processScalaUnit(API.scala:46)
at xsbt.API$ApiPhase.processUnit(API.scala:37)
at xsbt.API$ApiPhase$$anonfun$run$1.apply(API.scala:33)
at xsbt.API$ApiPhase$$anonfun$run$1.apply(API.scala:33)
at scala.collection.Iterator$class.foreach(Iterator.scala:695)
at scala.collection.AbstractIterator.foreach(Iterator.scala:1122)
at xsbt.API$ApiPhase.run(API.scala:33)
at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1307)
at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1280)
at scala.tools.nsc.Global$Run.compileSources(Global.scala:1274)
at scala.tools.nsc.Global$Run.compile(Global.scala:1404)
at xsbt.CompilerInterface.run(CompilerInterface.scala:106)
at scala.tools.eclipse.buildmanager.sbtintegration.ScalaSbtCompiler.compile(ScalaSbtCompiler.scala:35)
at scala.tools.eclipse.buildmanager.sbtintegration.AnalysisCompile$$anonfun$9.compileScala$1(AnalysisCompile.scala:137)
at scala.tools.eclipse.buildmanager.sbtintegration.AnalysisCompile$$anonfun$9.apply(AnalysisCompile.scala:175)
at scala.tools.eclipse.buildmanager.sbtintegration.AnalysisCompile$$anonfun$9.apply(AnalysisCompile.scala:112)
at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:21)
at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:19)
at sbt.inc.Incremental$.cycle(Incremental.scala:33)
at sbt.inc.Incremental$.compile(Incremental.scala:20)
at sbt.inc.IncrementalCompile$.apply(Compile.scala:17)
at scala.tools.eclipse.buildmanager.sbtintegration.AnalysisCompile.doCompile(AnalysisCompile.scala:193)
at scala.tools.eclipse.buildmanager.sbtintegration.EclipseSbtBuildManager.runCompiler(EclipseSbtBuildManager.scala:369)
at scala.tools.eclipse.buildmanager.sbtintegration.EclipseSbtBuildManager.update(EclipseSbtBuildManager.scala:331)
at scala.tools.eclipse.buildmanager.sbtintegration.EclipseSbtBuildManager.build(EclipseSbtBuildManager.scala:433)
at scala.tools.eclipse.ScalaProject.build(ScalaProject.scala:718)
at scala.tools.eclipse.ScalaBuilder.build(ScalaBuilder.scala:114)
at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:728)
at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:199)
at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:239)
at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:292)
at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:295)
at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:351)
at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:374)
at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:513)
at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:432)
at org.eclipse.ui.actions.BuildAction$1.runInWorkspace(BuildAction.java:305)
at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:38)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

**Comment by vigdorchik** [comment]
sbt forces not to hold to compiler symbols and types after the API pass is run. While in principle there might be a way (no idea if that's true) to cut the refs for GC otherwise, I don't think it will help you in general case: if at some point 'my project' uses org.'eclipse.jface' classes, the typer will report a missing dependency anyway. So I don't see why you need to have classpath that is narrower than what is declared in Eclipse. Could you maybe elaborate?

**Comment by dragos** [comment]
The point was that the API phase is run after the typer, if I understand correctly. That means that the typer didn't need those symbols (or I would have gotten a type error, and the API phase wouldn't have run at all). So it seems to me the API phase is more eager than the typer. Maybe I'm missing something.

**Comment by vigdorchik** [comment]
It wants to cleanup after itself, so it is more eager. Still why is this a problem for you?

**Comment by dragos** [comment]
The biggest problem is that I need a huge classpath, even though I don't need most of those things. And I discover the necessary jars one-by-one, after each crash of Sbt. Also, being in an OSGi environment it means I put these jars in my MANIFEST.MF, and they will be required and loaded/wired at runtime.

Of course I can add those dependencies, but I don't think it's correct. Sbt should not require a larger classpath than the typer, right?

**Comment by vigdorchik** [comment]
I think sbt is plugged in to the build compiler, rather than the presentation one, so it might rely on a certain type forced later in the compilation process. Mark should be able to provide more rationale behind forcing.

**Comment by dragos** [comment]
I'm not sure I understand. Yes, Sbt uses the build compiler, and the crash happens after JVM bytecode has been emitted. So there is no chance the type would be forced later... it's really the API phase that does it.

As you say, it's easy to work around, it's just an annoyance.

**Comment by harrah** [comment]
This is similar to the (second) problem reported in #117.  There it is a private inner class that is inherited that causes the problem.  That could be ignored, but the implementation for handling Java sources relies on Class.forName and would require a different (custom) approach.  Here, I would need to know what the problematic definition is in order to comment.  I don't think sbt can ignore lazy types just because typer hasn't forced types yet.  refchecks (or something), for example, will look at inherited members.  Also, API runs after typer, so I don't think JVM bytecode would be emitted first.

**Comment by dragos** [comment]
I misunderstood when API runs, sorry about that. But precisely for this kind of errors, wouldn't it be better to have it run after refchecks? I think it's confusing for users to see different error messages when compiling outside of Sbt. 

Otherwise, Sbt could catch this exception and turn it into a simpler error message. Just a thought.

**Comment by harrah** [comment]
Unfortunately, I don't think so.  Right after typer is when definitions/types/whatever are closest to the source API.  If I remember correctly, things start changing even by refchecks.

**Comment by kiritsuku** [comment]
This issue also affects eclipse plugin-development with Scala. After adding Scala nature to a eclipse plugin-project and calling the eclipse API errors are thrown. This could be fixed by adding explicitly some more dependencies to the plugin-project but because sbt doesn't tell one which dependencies need to be added, this is extremely impractical.

Little example: using a `org.eclipse.ui.editors.text.TextEditor` from Scala code expects also the dependencies `org.eclipse.debug.ui` and `org.eclipse.ui.ide` (related Java code doesn't require these dependencies).

Probably related to this is that the errors which are thrown are some internal errors, nothing a user should see. Only using `org.eclipse.ui.editors.text.TextEditor` causes a NPE and adding `org.eclipse.debug.ui` causes an `UnsupportedOperationException`. Both disappear by adding `org.eclipse.ui.ide`. See https://groups.google.com/forum/?fromgroups=#!topic/scala-ide-user/_vt3MDcP_uk for more information on the exceptions.

**Comment by copumpkin** [comment]
This is biting me, too, in the "tail of empty list" form described at https://groups.google.com/forum/#!msg/scala-ide-user/_vt3MDcP_uk/ID09ULOTqNUJ. Using sbt 0.13 with Scala 2.10.2.

**Comment by harrah** [comment]
I didn't know about the "tail of empty list" problem.  It isn't immediately obvious that it has the same cause, so I'll take @dragos's word for it.  A small example might allow me to fix it so it at least doesn't crash in that specific case, although inc. compilation might be less accurate. (Not sure about that, just looking at the stack trace and the code causing the error.)

Fixing the more general problem is not on the roadmap at this time, mainly due to the effort involved.

**Comment by eed3si9n** [comment]
Not sure if this issue is still relevant in the age of Metals, but closing this for now.
