### ISSUE TITLE
sbt run fails if JDK10 is used

### ISSUE THREAD

**Issue by marmistrz** [sbt/sbt#4208]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

## steps
Install `jdk10-openjdk` on Arch Linux.
```
sudo archlinux-java set java-10-openjdk`
sbt run
```
This fails with 
```
$ sbt run
[info] Loading settings from plugins.sbt,assembly.sbt ...
[info] Loading project definition from /home/marcin/proj/xmppester/project
[info] Loading settings from build.sbt ...
[info] Set current project to xmppester (in build file:/home/marcin/proj/xmppester/)
[info] Running (fork) Main 
[info] Connecting...
[error] Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
[error] 	at Main$.delayedEndpoint$Main$1(Main.scala:8)
[error] 	at Main$delayedInit$body.apply(Main.scala:5)
[error] 	at scala.Function0.apply$mcV$sp(Function0.scala:34)
[error] 	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error] 	at scala.App.$anonfun$main$1$adapted(App.scala:76)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at scala.App.main(App.scala:76)
[error] 	at scala.App.main$(App.scala:74)
[error] 	at Main$.main(Main.scala:5)
[error] 	at Main.main(Main.scala)
[error] Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
[error] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
[error] 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
[error] 	... 11 more
[error] java.lang.RuntimeException: Nonzero exit code returned from runner: 1
[error] 	at sbt.ForkRun.processExitCode$1(Run.scala:33)
[error] 	at sbt.ForkRun.run(Run.scala:42)
[error] 	at sbt.Defaults$.$anonfun$bgRunTask$5(Defaults.scala:1169)
[error] 	at sbt.Defaults$.$anonfun$bgRunTask$5$adapted(Defaults.scala:1164)
[error] 	at sbt.internal.BackgroundThreadPool.$anonfun$run$1(DefaultBackgroundJobService.scala:366)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at scala.util.Try$.apply(Try.scala:209)
[error] 	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:289)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:844)
[error] (Compile / run) Nonzero exit code returned from runner: 1
[error] Total time: 1 s, completed Jun 16, 2018, 11:08:43 AM
```
Now change the default Java version to JDK8:
```
sudo archlinux-java set java-8-openjdk
sbt run
```
this succeeds
```
[info] Running (fork) Main 
[info] Connecting...
[success] Total time: 3 s, completed Jun 16, 2018 11:15:09 AM
```
## problem
sbt run fails if JDK10 is used
## expectation
sbt works both with JDK8 and JDK10 (or at least gives an explicit error message that JDK10 is unsupported)

## notes

sbt version: *1.1.4-1*

**Comment by xuwei-k** [comment]
I think this is not sbt bug. Try add

```scala
libraryDependencies += "javax.xml.bind" % "jaxb-api" % "2.3.0"
```

in your build.sbt

https://github.com/playframework/playframework/pull/8382

**Comment by eed3si9n** [comment]
Thanks @xuwei-k! I agree with Yoshida-san that whether JAXB is included in the JRE or not really isn't the bug of sbt.

**Comment by marmistrz** [comment]
@xuwei-k then jaxb should be the part of the default sbt template, possibly with a jre version guard.
