### ISSUE TITLE
sbt does not work on openjdk7

### ISSUE THREAD

**Issue by pathikrit** [sbt/sbt#4219]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

## steps
Create a sbt project using openjdk7, sbt 1.1.x, and scala 2.11.x or 2.12.x

## problem
I tried all 26 possible combinations of (oraclejdk6/7/8/9/10/11 + openjdk6/7/8/9/10/11) across Scala 2.11.x and 2.12.x: https://travis-ci.org/pathikrit/better-files/builds/394190506

All builds pass except on openjdk7 (note that the build is fine with openjdk6 or even oraclejdk7), sbt itself crashes and dies:

```
java.lang.UnsupportedClassVersionError: scala/Option : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:412)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:278)
	at xsbt.boot.Pre$.xsbt$boot$Pre$$classMissing$1(Pre.scala:66)
	at xsbt.boot.Pre$$anonfun$getMissing$1.apply(Pre.scala:67)
	at scala.collection.TraversableLike$$anonfun$filter$1.apply(TraversableLike.scala:264)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at org.apache.ivy.core.RelativeUrlResolver.filter(RelativeUrlResolver.java:263)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:105)
	at xsbt.boot.Pre$.getMissing$d83f809$3a8a6f87(Pre.scala:67)
	at xsbt.boot.Launch.checkLoader$2accd70c(Launch.scala:185)
	at xsbt.boot.Launch.xsbt$boot$Launch$$provider$1(Launch.scala:249)
	at xsbt.boot.Launch$$anonfun$xsbt$boot$Launch$$getScalaProvider0$2.apply(Launch.scala:252)
	at xsbt.boot.Launch$$anonfun$xsbt$boot$Launch$$getScalaProvider0$2.apply(Launch.scala:251)
	at scala.Option.flatMap(Option.scala:170)
	at xsbt.boot.Launch.xsbt$boot$Launch$$getScalaProvider0(Launch.scala:251)
	at xsbt.boot.Launch$$anon$4.call(Launch.scala:240)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:47)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at xsbt.boot.Launch.locked(Launch.scala:238)
	at xsbt.boot.Launch.getScalaProvider(Launch.scala:240)
	at xsbt.boot.Launch$$anonfun$1.apply(Launch.scala:141)
	at xsbt.boot.Cache.newEntry(Cache.scala:16)
	at xsbt.boot.Cache.apply(Cache.scala:11)
	at xsbt.boot.Launch.getScala(Launch.scala:144)
	at xsbt.boot.Launch.getScala(Launch.scala:143)
	at xsbt.boot.Launch.xsbt$boot$Launch$$getAppProvider0(Launch.scala:219)
	at xsbt.boot.Launch$$anon$3.call(Launch.scala:196)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at xsbt.boot.Launch.locked(Launch.scala:238)
	at xsbt.boot.Launch.app(Launch.scala:147)
	at xsbt.boot.Launch.app(Launch.scala:145)
	at xsbt.boot.Launch$.run(Launch.scala:102)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
	at xsbt.boot.Boot$.main(Boot.scala:18)
	at xsbt.boot.Boot.main(Boot.scala)
```

## expectation
sbt should work in openjdk7

## notes

sbt version: 1.1.6

**Comment by chenrui333** [comment]
I think `sbt` requires JDK 8?

> sbt is a build tool for Scala, Java, and more. It requires Java 1.8 or later.
https://www.scala-sbt.org/1.x/docs/index.html

**Comment by pathikrit** [comment]
> I think sbt requires JDK 8?

No it works just fine on openjdk6, oraclejdk7 etc. See: https://travis-ci.org/pathikrit/better-files/builds/394190506

Here's a simpler matrix too: https://travis-ci.org/pathikrit/better-files/builds/392067107

**Comment by chenrui333** [comment]
ah, I see.

**Comment by eed3si9n** [comment]
Hi @pathikrit. sbt 1 does _not_ work on JDK 6 or 7, Oracle or OpenJDK.
The seeming success you're having on Travis CI I think is an illusion because the JDK packaging they are using is not being honest.
For better cross building, check out my blog post here - http://eed3si9n.com/all-your-jdks-on-travis-ci-using-jabba

**Comment by eed3si9n** [comment]
Here's "openjdk6" build https://travis-ci.org/pathikrit/better-files/jobs/392067112:

```
$ java -Xmx32m -version
Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```

See also https://github.com/travis-ci/travis-ci/issues/9713

**Comment by pathikrit** [comment]
Oh wow! Travis is being extremely naughty here! I thought it would give an error.
See: https://travis-ci.org/pathikrit/better-files/jobs/391976178

```
$ jdk_switcher use oraclejdk6
Sun/Oracle JDK 6 is EOL since November 2012, and is no longer supported. Please consider upgrading...
The command "jdk_switcher use oraclejdk6" failed and exited with 1 during .
Your build has been stopped.
```

See this: https://travis-ci.org/pathikrit/better-files/builds/391976176?utm_source=github_status&utm_medium=notification

This uses bunch of really old JDKs and Travis correctly complains that they are not supported!!
