### ISSUE TITLE
'sbt "^^ 1.2.0-RC1" scripted' throw "ClassNotFoundException: sbt.test.ScriptedTests$"

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt#4241]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

### build.properties

```
sbt.version=1.1.6
```

### project/plugins.sbt

```scala
libraryDependencies += "org.scala-sbt" %% "scripted-plugin" % sbtVersion.value
```

### build.sbt

```
sbtPlugin := true
```

run `sbt "^^ 1.2.0-RC1" scripted`

## problem

```
[error] java.lang.ClassNotFoundException: sbt.test.ScriptedTests$
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] 	at java.lang.Class.forName0(Native Method)
[error] 	at java.lang.Class.forName(Class.java:348)
[error] 	at sbt.internal.inc.ModuleUtilities$.getObject(ModuleUtilities.scala:20)
[error] 	at sbt.ScriptedPlugin$.$anonfun$scriptedTestsTask$1(ScriptedPlugin.scala:72)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:272)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (scriptedTests) java.lang.ClassNotFoundException: sbt.test.ScriptedTests$
```

## expectation

success scripted test

## notes

sbt version: 1.1.6, 0.13.17 (maybe all old versions?)

**Comment by eed3si9n** [comment]
This is a bit of a sticky situation. See https://github.com/sbt/sbt/blob/v0.13.17/scripted/plugin/src/main/scala/sbt/ScriptedPlugin.scala

This introduces 

```scala
    libraryDependencies ++= (partialVersion(scriptedSbt.value) match {
      case Some((0, 13)) =>
        Seq(
          "org.scala-sbt" % "scripted-sbt" % scriptedSbt.value % scriptedConf.toString,
          "org.scala-sbt" % "sbt-launch" % scriptedSbt.value % scriptedLaunchConf.toString
        )
      case Some((1, _)) =>
        Seq(
          "org.scala-sbt" %% "scripted-sbt" % scriptedSbt.value % scriptedConf.toString,
          "org.scala-sbt" % "sbt-launch" % scriptedSbt.value % scriptedLaunchConf.toString
        )
    }),
```

Note this uses `"scripted-sbt"` not `"scripted-plugin"`.

In sbt 1.2.0-RC1 the package name of `ScriptedTests` have moved to `sbt.scriptedtest` (to work around https://github.com/sbt/sbt/issues/4242) while keeping the shim in `"scripted-plugin"`.

I'd probably need to move ScriptedTests back into `"scripted-sbt"`, but without inducing #4242.

**Comment by eed3si9n** [comment]
Sent in https://github.com/sbt/sbt/pull/4258
