### ISSUE TITLE
Issue for local resolution of project with dependsOn when scala version is different

### ISSUE THREAD

**Issue by fchaillou** [sbt/sbt#4262]
- [X] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

## steps
This is close to #1448 
```
$ cat project/build.properties 
sbt.version=1.1.6
```
```
$ cat build.sbt               
lazy val rootProj = (project in file(".")).
  aggregate(fooProj, barProj, bazProj).
  settings(
    scalaVersion := "2.12.6",
    crossScalaVersions := Seq("2.11.12", scalaVersion.value)
  )

lazy val fooProj = (project in file("foo")).
  dependsOn(barProj).
  settings(
    scalaVersion := "2.12.6"
  )

lazy val bazProj = (project in file("baz")).
  dependsOn(barProj).
  settings(
    scalaVersion := "2.11.12"
  )

lazy val barProj = (project in file("bar")).
  settings(
    scalaVersion := "2.12.6",
    crossScalaVersions := Seq("2.11.12", scalaVersion.value)
  )
```

## problem

Running `+update` fails

```
 ~/otherDev/sbt-bug> sbt                                                                                          [13/07|8:21]
[info] Loading settings from idea.sbt,sbt-tmpfs.sbt,dirtymoney.sbt,coursier.sbt ...
[info] Loading global plugins from /home/fabien/.sbt/1.0/plugins
[info] Loading project definition from /home/fabien/otherDev/sbt-bug/project
[info] Loading settings from build.sbt ...
[info] Set current project to rootProj (in build file:/home/fabien/otherDev/sbt-bug/)
[info] sbt server started at local:///home/fabien/.sbt/1.0/server/9812531a8551cf39fd5a/sock
sbt:rootProj> +update
[info] Setting Scala version to 2.11.12 on 3 projects.
[info] Excluded 1 projects, run ++ 2.11.12 -v for more details.
[info] Reapplying settings...
[info] Set current project to rootProj (in build file:/home/fabien/otherDev/sbt-bug/)
[info] Updating ...
[info] Updating barProj...
[info] Done updating.
[info] Updating fooProj...
[info] Updating bazProj...
[info] Done updating.
[info] Done updating.
[warn] 	module not found: barproj#barproj_2.12;0.1.0-SNAPSHOT
[warn] ==== local: tried
[warn]   /home/fabien/.ivy2/local/barproj/barproj_2.12/0.1.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/barproj/barproj_2.12/0.1.0-SNAPSHOT/barproj_2.12-0.1.0-SNAPSHOT.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /home/fabien/.sbt/preloaded/barproj/barproj_2.12/0.1.0-SNAPSHOT/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////home/fabien/.sbt/preloaded/barproj/barproj_2.12/0.1.0-SNAPSHOT/barproj_2.12-0.1.0-SNAPSHOT.pom
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: barproj#barproj_2.12;0.1.0-SNAPSHOT: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		barproj:barproj_2.12:0.1.0-SNAPSHOT
[warn] 		  +- fooproj:fooproj_2.12:0.1.0-SNAPSHOT
[error] sbt.librarymanagement.ResolveException: unresolved dependency: barproj#barproj_2.12;0.1.0-SNAPSHOT: not found
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:334)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:242)
[error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
[error] 	at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:46)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:99)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:112)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:112)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:95)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:126)
[error] 	at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2398)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:272)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (fooProj / update) sbt.librarymanagement.ResolveException: unresolved dependency: barproj#barproj_2.12;0.1.0-SNAPSHOT: not found
[error] Total time: 2 s, completed Jul 13, 2018 8:31:48 AM
sbt:rootProj> 
```

but running update separately on each project works.

```
sbt:rootProj> +barProj/update
[info] Setting Scala version to 2.11.12 on 3 projects.
[info] Excluded 1 projects, run ++ 2.11.12 -v for more details.
[info] Reapplying settings...
[info] Set current project to rootProj (in build file:/home/fabien/otherDev/sbt-bug/)
[info] Updating barProj...
[info] Done updating.
[success] Total time: 3 s, completed Jul 13, 2018 8:24:57 AM
[info] Setting Scala version to 2.12.6 on 3 projects.
[info] Excluded 1 projects, run ++ 2.12.6 -v for more details.
[info] Reapplying settings...
[info] Set current project to rootProj (in build file:/home/fabien/otherDev/sbt-bug/)
[info] Updating barProj...
[info] Done updating.
[success] Total time: 1 s, completed Jul 13, 2018 8:25:00 AM
[info] Reapplying settings...
[info] Set current project to rootProj (in build file:/home/fabien/otherDev/sbt-bug/)
```

```
sbt:rootProj> +bazProj/update
[info] Setting Scala version to 2.11.12 on 3 projects.
[info] Excluded 1 projects, run ++ 2.11.12 -v for more details.
[info] Reapplying settings...
[info] Set current project to rootProj (in build file:/home/fabien/otherDev/sbt-bug/)
[info] Updating bazProj...
[info] Done updating.
[success] Total time: 1 s, completed Jul 13, 2018 8:25:31 AM
[info] Reapplying settings...
[info] Set current project to rootProj (in build file:/home/fabien/otherDev/sbt-bug/)
```

```
sbt:rootProj> +fooProj/update
[info] Setting Scala version to 2.12.6 on 3 projects.
[info] Excluded 1 projects, run ++ 2.12.6 -v for more details.
[info] Reapplying settings...
[info] Set current project to rootProj (in build file:/home/fabien/otherDev/sbt-bug/)
[info] Updating fooProj...
[info] Done updating.
[success] Total time: 2 s, completed Jul 13, 2018 8:25:58 AM
[info] Reapplying settings...
[info] Set current project to rootProj (in build file:/home/fabien/otherDev/sbt-bug/)
```

## expectation

`sbt +update` should complete successfuly

## notes

sbt version: 1.1.6

**Comment by muuki88** [comment]
Checkout the [sbt-projectmatrix](https://github.com/sbt/sbt-projectmatrix). This enables way better cross building.

**Comment by eed3si9n** [comment]
Yea and please see the accompanying proposal piece that wrote - https://discuss.lightbend.com/t/spatial-representation-of-cross-building/1277

**Comment by eed3si9n** [comment]
@fchaillou If you set crossScalaVersions to Seq() for the root project, things seem to work as expected.

**Comment by fchaillou** [comment]
@eed3si9n i confirm that this work. great ! I'll take a look at the crossMatrix for the future, thanks for the pointer

**Comment by jgogstad** [comment]
Adding `crossScalaVersions := Seq()` resolves the problem for SBT, but IntelliJ still fails to import

```
[IJ]sbt:myproject> ;reload; set _root_.org.jetbrains.sbt.StructureKeys.sbtStructureOptions in Global := "download resolveClassifiers resolveSbtClassifiers" ;*/*:dumpStructureTo /private/var/folders/8z/mmf5fqnj09xdh6s7jdrykwb00000gp/T/sbt-structure.xml; session clear-all ; set ideaPort in Global := 58010
[info] Loading settings for project global-plugins from idea.sbt ...
snip
[info] Reapplying settings...
[info] Set current project to myproject (in build file:/Users/jgogstad/myproject/)
Downloading https://repo1.maven.org/maven2/com/myproject/api_2.11/1-10-gc9122af-SNAPSHOT/api_2.11-1-10-gc9122af-SNAPSHOT.pom.sha1
snip
[error] coursier.lmcoursier.ResolutionException: Encountered 2 error(s) in dependency resolution:
[error]     com.myorg.myproject:api_2.11:1-10-gc9122af-SNAPSHOT:
[error]         not found:

```

**Comment by realvictorprm** [comment]
same here

**Comment by FloWi** [comment]
Yes, same here for me as well. 

I opened a ticket at jetbrains: https://youtrack.jetbrains.com/issue/IDEA-225121
