### ISSUE TITLE
When compile: java.lang.NoClassDefFoundError: com/google/protobuf/CodedOutputStream

### ISSUE THREAD

**Issue by CNLHC** [sbt/sbt#4273]
- [O ] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

## steps
0. Using Ubuntu 18.04 more details were posted to  [ `note` ](#notes) section

1. Installing sbt from official sources by using command below:

```$ echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
$ sudo apt-get update
$ sudo apt-get install sbt
```
2.  Initializing new demo project.

```bash 
$ mkdir foo-build
$ cd foo-build
$ touch build.sbt
```

3. Then run sbt. After it have downloaded all dependencies, i execute `compile` in sbt , everything is ok.

```bash
$ sbt
[info] Loading project definition from /mnt/SSHHD2/home/foo-build/project
[info] Updating ProjectRef(uri("file:/mnt/SSHHD2/home/foo-build/project/"), "foo-build-build")...
[info] Done updating.
[info] Loading settings from build.sbt ...
[info] Set current project to foo-build (in build file:/mnt/SSHHD2/home/foo-build/)
[info] sbt server started at local:///home/cn/.sbt/1.0/server/727d0c3ac5d4753858b6/sock
sbt:foo-build> compile
[info] Updating ...
[info] Done updating.
[success] Total time: 0 s, completed 2018-7-18 12:45:17
sbt:foo-build> 
```
4. Make a new directory, and add source file.

```bash
$ mkdir -p src/main/scala/example
$ vim ./src/main/scala/example/Hello.scala
```
The content of "Hello.scala" is
```scala
package example

object Hello extends App {
  println("Hello")
}
```
5. Rerun the sbt , and use compile command.
```bash
 $ sbt
[info] Loading project definition from /mnt/SSHHD2/home/foo-build/project
[info] Loading settings from build.sbt ...
[info] Set current project to foo-build (in build file:/mnt/SSHHD2/home/foo-build/)
[info] sbt server started at local:///home/cn/.sbt/1.0/server/727d0c3ac5d4753858b6/sock
sbt:foo-build> compile
[info] Compiling 1 Scala source to /mnt/SSHHD2/home/foo-build/target/scala-2.12/classes ...
[info] Done compiling.
[error] java.lang.NoClassDefFoundError: com/google/protobuf/CodedOutputStream
[error] 	at sbt.internal.inc.FileAnalysisStore$BinaryFileStore.$anonfun$set$1(FileAnalysisStore.scala:84)
......
```
Boom! The problem occurs. Backtrack details will post to the [problem section](#problem) below.

## problem

When i follow steps above(which is  provided by sbt official document ). The full error info output by sbt is.
```bash 
$ sbt 
[info] Loading project definition from /mnt/SSHHD2/home/foo-build/project
[info] Loading settings from build.sbt ...
[info] Set current project to foo-build (in build file:/mnt/SSHHD2/home/foo-build/)
[info] sbt server started at local:///home/cn/.sbt/1.0/server/727d0c3ac5d4753858b6/sock
sbt:foo-build> compile
[info] Compiling 1 Scala source to /mnt/SSHHD2/home/foo-build/target/scala-2.12/classes ...
[info] Done compiling.
[error] java.lang.NoClassDefFoundError: com/google/protobuf/CodedOutputStream
[error] 	at sbt.internal.inc.FileAnalysisStore$BinaryFileStore.$anonfun$set$1(FileAnalysisStore.scala:84)
[error] 	at sbt.internal.inc.FileAnalysisStore$BinaryFileStore.$anonfun$set$1$adapted(FileAnalysisStore.scala:83)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.internal.inc.FileAnalysisStore$BinaryFileStore.set(FileAnalysisStore.scala:83)
[error] 	at sbt.internal.inc.AnalysisStore$CachedAnalysisStore.set(AnalysisStore.scala:27)
[error] 	at sbt.internal.inc.AnalysisStore$SyncedAnalysisStore.set(AnalysisStore.scala:39)
[error] 	at sbt.Defaults$.$anonfun$compileTask$1(Defaults.scala:1411)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:272)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] Caused by: java.lang.ClassNotFoundException: com.google.protobuf.CodedOutputStream
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] 	at sbt.internal.inc.FileAnalysisStore$BinaryFileStore.$anonfun$set$1(FileAnalysisStore.scala:84)
[error] 	at sbt.internal.inc.FileAnalysisStore$BinaryFileStore.$anonfun$set$1$adapted(FileAnalysisStore.scala:83)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.internal.inc.FileAnalysisStore$BinaryFileStore.set(FileAnalysisStore.scala:83)
[error] 	at sbt.internal.inc.AnalysisStore$CachedAnalysisStore.set(AnalysisStore.scala:27)
[error] 	at sbt.internal.inc.AnalysisStore$SyncedAnalysisStore.set(AnalysisStore.scala:39)
[error] 	at sbt.Defaults$.$anonfun$compileTask$1(Defaults.scala:1411)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:272)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (Compile / compile) java.lang.NoClassDefFoundError: com/google/protobuf/CodedOutputStream
[error] Total time: 2 s, completed 2018-7-18 12:51:44
```

## expectation

Since this is just a `Hello World` demo, i am 100% sure i haven't use anything related to `Protobuf`, but the error info is 
```
[error] (Compile / compile) java.lang.NoClassDefFoundError: com/google/protobuf/CodedOutputStream
```
I think this may be caused by sbt itself?

## notes

 Environment may be related to this problem:
```
$ sudo apt list --installed |grep sbt 

sbt/unknown,now 1.1.6 all [installed]

$ sudo apt list --installed |grep openjdk

openjdk-8-dbg/bionic-updates,bionic-security,now 8u171-b11-0ubuntu0.18.04.1 amd64 [installed]
openjdk-8-jdk/bionic-updates,bionic-security,now 8u171-b11-0ubuntu0.18.04.1 amd64 [installed]
openjdk-8-jdk-headless/bionic-updates,bionic-security,now 8u171-b11-0ubuntu0.18.04.1 amd64 [installed]
openjdk-8-jre/bionic-updates,bionic-security,now 8u171-b11-0ubuntu0.18.04.1 amd64 [installed]
openjdk-8-jre-dcevm/bionic,now 8u112-2 amd64 [installed
openjdk-8-jre-headless/bionic-updates,bionic-security,now 8u171-b11-0ubuntu0.18.04.1 amd64 [installed]
openjdk-8-jre-zero/bionic-updates,bionic-security,now 8u171-b11-0ubuntu0.18.04.1 amd64 [installed]

$cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

```

sbt version: *1.1.6*

**Comment by eed3si9n** [comment]
Thanks for the report. Could you try with 1.2.0-RC3 by changing the value in build.properties, and see if the problem persists?

**Comment by CNLHC** [comment]
Since I can not reproduce bug in the other computer, i'll close this issue.
