### ISSUE TITLE
sbt release fails with `java.io.IOException: destination file exists and overwrite == false`

### ISSUE THREAD

**Issue by pathikrit** [sbt/sbt#4275]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

## steps
I tried doing `sbt +release` on better-files

## problem
```
> sbt +release

[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /Users/pbhowmick/workspace/better-files/project
[info] Loading settings from version.sbt,build.sbt ...
[info] Set current project to better-files-root (in build file:/Users/pbhowmick/workspace/better-files/)
[info] Forcing Scala version to 2.11.12 on all projects.
[info] Reapplying settings...
[info] Set current project to better-files-root (in build file:/Users/pbhowmick/workspace/better-files/)
[info] Starting release process off commit: 9cfc2373e7835023b9a7e9e7c16342cd00232624
[info] Checking remote [origin] ...
[info] Updating ...
[info] Updating core...
[info] Done updating.
[info] Updating akka...
[info] Done updating.
[info] Done updating.
Release version [3.5.1] : 3.6.0
Next version [3.6.1-SNAPSHOT] :
[info] Setting version to '3.6.0'.
[info] Reapplying settings...
[info] Set current project to better-files-root (in build file:/Users/pbhowmick/workspace/better-files/)
[info] [master 6e6210b] Setting version to 3.6.0
[info]  1 file changed, 1 insertion(+), 1 deletion(-)
[info] Reapplying settings...
[info] Set current project to better-files-root (in build file:/Users/pbhowmick/workspace/better-files/)
Tag [v3.6.0] exists! Overwrite, keep or abort or enter a new tag (o/k/a)? [a] o
[warn] Overwriting a tag can cause problems if others have already seen the tag (see `git help tag`)!
[info] Reapplying settings...
[info] Set current project to better-files-root (in build file:/Users/pbhowmick/workspace/better-files/)
[info] Packaging /Users/pbhowmick/workspace/better-files/akka/target/scala-2.11/better-files-akka_2.11-3.6.0-sources.jar ...
[info] Packaging /Users/pbhowmick/workspace/better-files/core/target/scala-2.11/better-files_2.11-3.6.0-sources.jar ...
[info] Done packaging.
[info] Done packaging.
[info] Updating core...
[info] Wrote /Users/pbhowmick/workspace/better-files/core/target/scala-2.11/better-files_2.11-3.6.0.pom
[info] Done updating.
[info] Wrote /Users/pbhowmick/workspace/better-files/akka/target/scala-2.11/better-files-akka_2.11-3.6.0.pom
[info] Updating akka...
[info] Packaging /Users/pbhowmick/workspace/better-files/core/target/scala-2.11/better-files_2.11-3.6.0-javadoc.jar ...
[info] Done packaging.
[info] Done updating.
[info] Packaging /Users/pbhowmick/workspace/better-files/akka/target/scala-2.11/better-files-akka_2.11-3.6.0.jar ...
[info] Done packaging.
[info] Packaging /Users/pbhowmick/workspace/better-files/akka/target/scala-2.11/better-files-akka_2.11-3.6.0-javadoc.jar ...
[info] Packaging /Users/pbhowmick/workspace/better-files/core/target/scala-2.11/better-files_2.11-3.6.0.jar ...
[info] Done packaging.
Please enter PGP passphrase (or ENTER to abort): *********
[info] Done packaging.
[error] java.io.IOException: destination file exists and overwrite == false
[error]         at org.apache.ivy.plugins.repository.url.URLRepository.put(URLRepository.java:75)
[error]         at sbt.internal.librarymanagement.ConvertResolver$LocalIfFileRepo.put(ConvertResolver.scala:366)
[error]         at org.apache.ivy.plugins.repository.AbstractRepository.put(AbstractRepository.java:130)
[error]         at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put(ConvertResolver.scala:118)
[error]         at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put$(ConvertResolver.scala:105)
[error]         at sbt.internal.librarymanagement.ConvertResolver$$anonfun$defaultConvert$lzycompute$1$PluginCapableResolver$1.put(ConvertResolver.scala:165)
[error]         at org.apache.ivy.plugins.resolver.RepositoryResolver.publish(RepositoryResolver.java:216)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5(IvyActions.scala:499)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5$adapted(IvyActions.scala:498)
[error]         at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:944)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:944)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:71)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error]         at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
[error]         at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:498)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$3(IvyActions.scala:144)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at sbt.internal.librarymanagement.IvyActions$.withChecksums(IvyActions.scala:157)
[error]         at sbt.internal.librarymanagement.IvyActions$.withChecksums(IvyActions.scala:151)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$1(IvyActions.scala:144)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$1$adapted(IvyActions.scala:134)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
[error]         at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error]         at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error]         at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error]         at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error]         at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error]         at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error]         at xsbt.boot.Using$.withResource(Using.scala:10)
[error]         at xsbt.boot.Using$.apply(Using.scala:9)
[error]         at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error]         at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error]         at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]         at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]         at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:242)
[error]         at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:134)
[error]         at sbt.Classpaths$.$anonfun$publishTask$4(Defaults.scala:2255)
[error]         at sbt.Classpaths$.$anonfun$publishTask$4$adapted(Defaults.scala:2254)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:272)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] java.io.IOException: destination file exists and overwrite == false
[error]         at org.apache.ivy.plugins.repository.url.URLRepository.put(URLRepository.java:75)
[error]         at sbt.internal.librarymanagement.ConvertResolver$LocalIfFileRepo.put(ConvertResolver.scala:366)
[error]         at org.apache.ivy.plugins.repository.AbstractRepository.put(AbstractRepository.java:130)
[error]         at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put(ConvertResolver.scala:118)
[error]         at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put$(ConvertResolver.scala:105)
[error]         at sbt.internal.librarymanagement.ConvertResolver$$anonfun$defaultConvert$lzycompute$1$PluginCapableResolver$1.put(ConvertResolver.scala:165)
[error]         at org.apache.ivy.plugins.resolver.RepositoryResolver.publish(RepositoryResolver.java:216)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5(IvyActions.scala:499)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5$adapted(IvyActions.scala:498)
[error]         at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:944)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:944)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:71)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error]         at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
[error]         at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:498)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$3(IvyActions.scala:144)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at sbt.internal.librarymanagement.IvyActions$.withChecksums(IvyActions.scala:157)
[error]         at sbt.internal.librarymanagement.IvyActions$.withChecksums(IvyActions.scala:151)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$1(IvyActions.scala:144)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$1$adapted(IvyActions.scala:134)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
[error]         at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error]         at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error]         at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error]         at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error]         at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error]         at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error]         at xsbt.boot.Using$.withResource(Using.scala:10)
[error]         at xsbt.boot.Using$.apply(Using.scala:9)
[error]         at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error]         at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error]         at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]         at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]         at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:242)
[error]         at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:134)
[error]         at sbt.Classpaths$.$anonfun$publishTask$4(Defaults.scala:2255)
[error]         at sbt.Classpaths$.$anonfun$publishTask$4$adapted(Defaults.scala:2254)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:272)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (core / publishSigned) java.io.IOException: destination file exists and overwrite == false
[error] (akka / publishSigned) java.io.IOException: destination file exists and overwrite == false
[error] Total time: 7 s, completed Jul 19, 2018 4:20:39 PM
```

## expectation

This should work. Or atleast give me a better error message about what destination file exists. I also have no idea what `overwrite == false` means. Is that a config key I am supposed to specify!?!

## notes

sbt version: 1.1.6

Ref https://github.com/sbt/sbt/issues/3431

**Comment by eed3si9n** [comment]
@pathikrit Thanks for the report.

I looked at the stack trace again, and it seems like the error message is coming from Ivy: https://github.com/sbt/ivy/blob/2.3.x-sbt/src/java/org/apache/ivy/plugins/repository/url/URLRepository.java#L74-L76

we can still workaround it in sbt side here - https://github.com/sbt/librarymanagement/blob/v1.2.0-M3/ivy/src/main/scala/sbt/internal/librarymanagement/ConvertResolver.scala#L365-L366

but it's an Ivy error.

`overwrite == false` means that Ivy is configured not to overwrite an existing file, which is a stricter setting we adopted in sbt 1 to avoid double publishing. 

```scala
publishConfiguration := publishConfiguration.value.withOverwrite(true)
publishLocalConfiguration := publishLocalConfiguration.value.withOverwrite(true)
```

in conjunction with the latest sbt-pgp should allow double publishing.

**Comment by eed3si9n** [comment]
To a potential contributor: The relevant source code is https://github.com/sbt/librarymanagement/blob/v1.2.0-M3/ivy/src/main/scala/sbt/internal/librarymanagement/ConvertResolver.scala#L365-L371

Define a function named `def putError(parent: Option[Throwable])` with a better error message: 

```
PUT failed for $destination because it is configured to not allow overwriting.
Try to fix the double publishing, or relax the setting as follows:
    publishConfiguration := publishConfiguration.value.withOverwrite(true)
    publishLocalConfiguration := publishLocalConfiguration.value.withOverwrite(true)
```

Call that from both line 370 and when `super.put(...)` fails.

**Comment by pathikrit** [comment]
To folks landing up here and wondering what to do, look at this commit: https://github.com/pathikrit/better-files/commit/1fc1bbc711a98e321fe1335b44068c0a9e694b59

**Comment by amiralia** [comment]
When I try this, I get `error: value withOverwrite is not a member of sbt.PublishConfiguration`. Anyone else seen this or know how to go further?

**Comment by shubhampatil17** [comment]
Facing same issue as @amiralia ! Any workaround for that ?

**Comment by gaeljw** [comment]
For anyone coming here, I had the issue when using `cross` with sbt-release although my project was not configured for cross compilation (actually it was but using sbt-projectmatrix).

**Comment by AdityaSaroj** [comment]
How can I modify this code?

    credentials += {
      val envCred = for {
        pwd <- sys.env.get("PASSWORD")
        user <- sys.env.get("USERNAME")
      } yield Credentials("Example", "example.com", user, pwd)
    
      envCred.orElse {
        val credFile = Try(Path.userHome / ".example" / "credentials").toOption
        credFile.map(Credentials(_))
      }.getOrElse {
        Credentials("Example", "example.com", "anonymous", "")
      }
    }

with

    publishConfiguration := publishConfiguration.value.withOverwrite(true)
    publishLocalConfiguration := publishLocalConfiguration.value.withOverwrite(true)

@pathikrit @eed3si9n?
