### ISSUE TITLE
Can not run sbt (1.2.0) with classifiers (sources, javadoc

### ISSUE THREAD

**Issue by DesertCat** [sbt/sbt#4295]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

## goal
I want to make SBT download scala library sources and javadocs.
Found an article http://www.decodified.com/scala/2010/12/17/how-to-make-sbt-download-scala-library-sources.html and started from scratch.

## environment
- sbt version: 1.2.0
- Windows 8.1 + Java 10.0.2
- Ubuntu Linux 14.04 + Java 1.8.0_111 

### On Windows 8.1

0. Checked that there is no `.ivy2` and `.sbt` directories in my homedir
1. Install JDK 10 from Oracle site
2. Add environment variable with value `JAVA_HOME=C:\Program Files\Java\jdk-10.0.2`
3. Download zip version of sbt from https://www.scala-sbt.org/download.html
4. Extract archive to `D:\Programs`
5. Add `D:\Programs\sbt\bin` to `PATH`
6. Extract file `sbt.boot.properties` from the `sbt` sub directory in the file `D:\Programs\sbt\bin\sbt-launch.jar` to `D:\Programs\sbt\bin` and rename it to `custom-sbt.boot.properties`
7. Fire up favorite text editor and add 
```
  classifiers: sources,javadoc
```
after line `2` in file `custom-sbt.boot.properties`

8. Edit file `D:\Programs\sbt\conf\sbtconfig.txt` to enable my custom properties file. Added
```
-Dsbt.boot.properties="custom-sbt.boot.properties"
```
in the end of the file

9. Open Powershell and go to `D:\Scalaprojects`
10. Run `sbt new scala/scala-seed.g8`
11. Program fails with an error:
```
:: retrieving :: org.scala-sbt#boot-scala
java.io.IOException: [[Fatal Error] resolved-org.scala-sbt-boot-scala-1.0.xml:17:89: The prefix "e" for attribute "e:classifier" associated with an element type
 "artifact" is not bound. in file:/C:/Users/cat/.sbt/boot/resolution-cache/resolved-org.scala-sbt-boot-scala-1.0.xml
]
  (see C:\Users\cat\.sbt\boot\update.log for complete log)
Error: Could not retrieve Scala 2.12.6
```

### On Ubuntu 14.04.5 LTS codename Trusty 

0. Checked that there is no `.ivy2` and `.sbt` directories in my homedir
1. Checked java version 
```
cat@trustyserv45:~/Working$ javac -version
javac 1.8.0_111
```
2. Download zip version of sbt from https://www.scala-sbt.org/download.html
3. Extract archive to `/opt`
4. Add `/opt/sbt/bin` to `PATH`
5. Extract file `sbt.boot.properties` from the `sbt` sub directory in the file `/opt/sbt/bin/sbt-launch.jar` to `/opt/sbt/bin` and rename it to `custom-sbt.boot.properties`
6. Fire up vim and add 
```
  classifiers: sources,javadoc
```
after line `2` in file `custom-sbt.boot.properties`

7. Go to `~/Working` and run `sbt` with an extra parameter
```
cat@trustyserv45:~/Working$ sbt -Dsbt.boot.properties="custom-sbt.boot.properties"
```

8. Program fails with an error
```
:: retrieving :: org.scala-sbt#boot-scala
java.io.IOException: [[Fatal Error] resolved-org.scala-sbt-boot-scala-1.0.xml:17:89: The prefix "e" for attribute "e:classifier" associated with an element type "artifact" is not bound. in file:/home/cat/.sbt/boot/resolution-cache/resolved-org.scala-sbt-boot-scala-1.0.xml
]
  (see /home/cat/.sbt/boot/update.log for complete log)
Error: Could not retrieve Scala 2.12.6
```

## problems
Can not run `sbt new scala/scala-seed.g8` with custom classifiers setting neither on Windows nor on Ubuntu Linux

## expectation
- normal working of `sbt new scala/scala-seed.g8`
- scala-library sources in my `/.ivy2`

## notes
I found a workaround of this problem:

1. Run `sbt new scala/scala-seed.g8`
2. See `The prefix "e" for attribute "e:classifier"` error
3. Comment-out
```
#  classifiers: sources,javadoc
```
in my `custom-sbt.boot.properties`
4. Run `sbt new scala/scala-seed.g8` again
5. Project successfully created
6. Uncomment
```
  classifiers: sources,javadoc
```
in my `custom-sbt.boot.properties`
7. Subsequent `sbt new scala/scala-seed.g8` are OK and scala-library sources are also present in my /.ivy2

**Comment by DesertCat** [comment]
Tail of my `home\.sbt\boot\update.log` from Windows-based attempt:

```
. . .
Module descriptor is processed : org.scala-lang#scala-library;2.12.6
Module descriptor is processed : org.scala-lang#scala-reflect;2.12.6
Module descriptor is processed : org.scala-lang.modules#scala-xml_2.12;1.0.6
Module descriptor is processed : jline#jline;2.14.6
    report for org.scala-sbt#boot-scala;1.0 default produced in C:\Users\cat\.sbt\boot\resolution-cache\org.scala-sbt-boot-scala-default.xml
    resolve done (61ms resolve - 76304ms download)
setting 'scala' to '2.12.6'
:: retrieving :: org.scala-sbt#boot-scala
    checkUpToDate=true
post 1.3 ivy file: using exact as default matcher
java.io.IOException: [[Fatal Error] resolved-org.scala-sbt-boot-scala-1.0.xml:17:89: The prefix "e" for attribute "e:classifier" associated with an element type "artifact" is not bound. in file:/C:/Users/cat/.sbt/boot/resolution-cache/resolved-org.scala-sbt-boot-scala-1.0.xml
]
    at org.apache.ivy.core.retrieve.RetrieveEngine.getConfs(RetrieveEngine.java:226)
    at org.apache.ivy.core.retrieve.RetrieveEngine.retrieve(RetrieveEngine.java:98)
    at xsbt.boot.Update.xsbt$boot$Update$$lockedApply(Update.scala:105)
    at xsbt.boot.Update$$anon$4.call(Update.scala:99)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
    at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
    at xsbt.boot.Using$.withResource(Using.scala:10)
    at xsbt.boot.Using$.apply(Using.scala:9)
    at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
    at xsbt.boot.Locks$.apply0(Locks.scala:31)
    at xsbt.boot.Locks$.apply(Locks.scala:28)
    at xsbt.boot.Update.apply(Update.scala:100)
    at xsbt.boot.Launch.update(Launch.scala:359)
    at xsbt.boot.Launch$$anonfun$xsbt$boot$Launch$$getScalaProvider0$3.apply(Launch.scala:254)
    at scala.Option.getOrElse(Option.scala:120)
    at xsbt.boot.Launch.xsbt$boot$Launch$$getScalaProvider0(Launch.scala:254)
    at xsbt.boot.Launch$$anon$4.call(Launch.scala:240)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:47)
    at xsbt.boot.Locks$.apply0(Locks.scala:31)
    at xsbt.boot.Locks$.apply(Locks.scala:28)
    at xsbt.boot.Launch.locked(Launch.scala:238)
    at xsbt.boot.Launch.getScalaProvider(Launch.scala:240)
    at xsbt.boot.Launch$$anonfun$1.apply(Launch.scala:141)
    at xsbt.boot.Cache.newEntry(Cache.scala:16)
    at xsbt.boot.Cache.apply(Cache.scala:11)
    at xsbt.boot.Launch.getScala(Launch.scala:144)
    at xsbt.boot.Launch.getScala(Launch.scala:143)
    at xsbt.boot.Launch.xsbt$boot$Launch$$getAppProvider0(Launch.scala:219)
    at xsbt.boot.Launch$$anon$3.call(Launch.scala:196)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
    at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
    at xsbt.boot.Using$.withResource(Using.scala:10)
    at xsbt.boot.Using$.apply(Using.scala:9)
    at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
    at xsbt.boot.Locks$.apply0(Locks.scala:31)
    at xsbt.boot.Locks$.apply(Locks.scala:28)
    at xsbt.boot.Launch.locked(Launch.scala:238)
    at xsbt.boot.Launch.app(Launch.scala:147)
    at xsbt.boot.Launch.app(Launch.scala:145)
    at xsbt.boot.Launch$.run(Launch.scala:102)
    at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
    at xsbt.boot.Launch$.launch(Launch.scala:117)
    at xsbt.boot.Launch$.apply(Launch.scala:18)
    at xsbt.boot.Boot$.runImpl(Boot.scala:56)
    at xsbt.boot.Boot$.main(Boot.scala:18)
    at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.text.ParseException: [[Fatal Error] resolved-org.scala-sbt-boot-scala-1.0.xml:17:89: The prefix "e" for attribute "e:classifier" associated with an element type "artifact" is not bound. in file:/C:/Users/cat/.sbt/boot/resolution-cache/resolved-org.scala-sbt-boot-scala-1.0.xml
]
    at org.apache.ivy.plugins.parser.AbstractModuleDescriptorParser$AbstractParser.checkErrors(AbstractModuleDescriptorParser.java:89)
    at org.apache.ivy.plugins.parser.xml.XmlModuleDescriptorParser$Parser.parse(XmlModuleDescriptorParser.java:277)
    at org.apache.ivy.plugins.parser.xml.XmlModuleDescriptorParser.parseDescriptor(XmlModuleDescriptorParser.java:117)
    at org.apache.ivy.plugins.parser.AbstractModuleDescriptorParser.parseDescriptor(AbstractModuleDescriptorParser.java:48)
    at org.apache.ivy.core.cache.DefaultResolutionCacheManager.getResolvedModuleDescriptor(DefaultResolutionCacheManager.java:161)
    at org.apache.ivy.core.retrieve.RetrieveEngine.getConfs(RetrieveEngine.java:219)
    ... 49 more
java.io.IOException: [[Fatal Error] resolved-org.scala-sbt-boot-scala-1.0.xml:17:89: The prefix "e" for attribute "e:classifier" associated with an element type "artifact" is not bound. in file:/C:/Users/cat/.sbt/boot/resolution-cache/resolved-org.scala-sbt-boot-scala-1.0.xml
]
```

**Comment by eed3si9n** [comment]
I don't think you have to do any of weird hacks described in the blog post. If you want sbt to grab source JARs, you just type `updateClassifiers` in sbt shell.

Or `show updateClassifiers` if you want to see the result.
