### ISSUE TITLE
Exception when running project after packaging submodule

### ISSUE THREAD

**Issue by LaCuneta** [sbt/sbt#4312]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

## Notes

sbt version: definitely 1.2.1, and we think it affects 1.0+.

We have setup sbt to help us use plugins to [our primary application](https://github.com/NetLogo/NetLogo).  This setup involves git submodules that have their own sbt configs (as they are separate repositories), but we want to package and run them from the parent application for easy bundling and testing.

## Steps

For an empty sbt 1.2.1 project, here is a minimal version of the `build.sbt`:

```scala
import sbt._
import Keys._

val extension = InputKey[Unit]("extension", "build a single extension")

extension := {
  val runner = new xMain()
  val buildConfig = new xsbti.AppConfiguration {
    val provider      = state.value.configuration.provider
    val baseDirectory = new File(".") // this would normally point to a submodule folder, but this works to recreate the error
    val arguments     = Seq("clean", "package").toArray
  }
  runner.run(buildConfig)
}
```

We also need an empty `main()` method in `src\main\scala\App.scala`, just to have something for sbt to `run`.

## Problem

Now in an sbt shell if we run `extension` and then `run` to run our main app, we get an exception:

```
[error] java.util.concurrent.RejectedExecutionException: Task sbt.internal.BackgroundThreadPool$BackgroundRunnable@70994bee rejected from java.util.concurrent.ThreadPoolExecutor@1876144a[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
[error] 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
[error] 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
[error] 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
[error] (Compile / bgRun) java.util.concurrent.RejectedExecutionException: Task sbt.internal.BackgroundThreadPool$BackgroundRunnable@70994bee rejected from java.util.concurrent.ThreadPoolExecutor@1876144a[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
[error] Total time: 0 s, completed Aug 8, 2018 10:19:01 AM
```

## Expectation

This setup worked without any problems in sbt 0.13, so my assumption is that it should work in 1.0+.  Let me know if that assumption is incorrect, or if you need any other details.

Thank you for your help!

**Comment by eed3si9n** [comment]
You're running sbt inside of sbt? That sounds like a very special build.
I wonder you might be better off using some other mechanism like [scripted](https://www.scala-sbt.org/1.x/docs/Testing-sbt-plugins.html), which we use to test sbt itself. One thing you could try is `fgRun` that should behave similarly as the sbt 0.13's `run` task.

**Comment by LaCuneta** [comment]
@eed3si9n That's correct, we've got sbt in our sbt!  Again, it's so we can maintain separate sbt setups for the extension repositories while also using them from the main project.  

Thank you for the suggestions, I'll check them out.  We were obviously hoping to continue using our existing setup, but if our special technique is unsupported, I understand.
