### ISSUE TITLE
Launcher not working with LoginContext

### ISSUE THREAD

**Issue by ghost** [sbt/sbt#435]
I have used the org.apache.activemq.jaas.PropertiesLoginModule in my project. On SBT this LoginModule works fine. With SCREPL it works too (https://github.com/harrah/xsbt/wiki/Scripts). But, if I trying with SBT Launcher the LoginModule could not be found (https://github.com/harrah/xsbt/wiki/Launcher). I get always these messages:

```
> zserver
Getting zserver zserver_2.9.1 0.1.0-SNAPSHOT ...
:: retrieving :: org.scala-tools.sbt#boot-app
    confs: [default]
    1 artifacts copied, 5 already retrieved (4kB/148ms)
javax.security.auth.login.LoginException: unable to find LoginModule class: org.apache.activemq.jaas.PropertiesLoginModule
    at javax.security.auth.login.LoginContext.invoke(LoginContext.java:822)
    at javax.security.auth.login.LoginContext.access$000(LoginContext.java:203)
    at javax.security.auth.login.LoginContext$4.run(LoginContext.java:698)
    at javax.security.auth.login.LoginContext$4.run(LoginContext.java:696)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:695)
    at javax.security.auth.login.LoginContext.login(LoginContext.java:594)
    at zserver.Main.run(Main.scala:19)
    at zserver.Main.run(Main.scala:9)
    at xsbt.boot.Launch$.run(Launch.scala:54)
    at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:43)
    at xsbt.boot.Launch$.launch(Launch.scala:68)
    at xsbt.boot.Launch$.apply(Launch.scala:14)
    at xsbt.boot.Boot$.runImpl(Boot.scala:25)
    at xsbt.boot.Boot$.main(Boot.scala:15)
    at xsbt.boot.Boot.main(Boot.scala)
Error during sbt execution: javax.security.auth.login.LoginException: unable to find LoginModule class: org.apache.activemq.jaas.PropertiesLoginModule
```

I have uploaded an example project for reproduction: https://github.com/myst3r10n/zserver

**Comment by harrah** [comment]
LoginContext apparently uses the context class loader to lookup classes.  Therefore you need to set it in your `run` method before calling `login`:

`Thread.currentThread.setContextClassLoader(getClass.getClassLoader)`
