### ISSUE TITLE
Kafka streams' start ExceptionInInitializerError

### ISSUE THREAD

**Issue by barambani** [sbt/sbt#4360]
- [ X] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines
I'm having an issue while running a kafka streams app in a `cats-effect` `IOApp` when I don't shift the context from global. A sample affected project can be found [here](https://github.com/barambani/kafka-streams-error).

## steps
- pull [this](https://github.com/barambani/kafka-streams-error)
- execute `sbt clean run`

## problem
```
[info] Loading settings for project global-plugins from build.sbt,credentials.sbt,gbg.sbt,idea.sbt,plugins.sbt ...
[info] Loading global plugins from /Users/fmariotti/.sbt/1.0/plugins
[info] Loading settings for project kafka-streams-error-build from plugins.sbt ...
[info] Loading project definition from /Users/fmariotti/temp/kafka-streams-error/project
[info] Loading settings for project root from build.sbt ...
[info] Set current project to test (in build file:/Users/fmariotti/temp/kafka-streams-error/)
[debug] Copy resource mappings:
[debug] 	(/Users/fmariotti/temp/kafka-streams-error/src/main/resources/logback.xml,/Users/fmariotti/temp/kafka-streams-error/target/scala-2.12/classes/logback.xml)
[info] Updating root
[info] Resolved root dependencies
[debug] No changes
[debug] Jar uptodate: /Users/fmariotti/temp/kafka-streams-error/target/scala-2.12/test_2.12-0.1.0-SNAPSHOT.jar
[info] Running Main
[debug] Waiting for threads to exit or System.exit to be called.
[debug]   Classpath:
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/job-1/target/74fce2cd/test_2.12-0.1.0-SNAPSHOT.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/4fdac2fb/jopt-simple-5.0.4.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/99a18e9a/jline-0.9.94.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/0543065c/scala-collection-compat_2.12-0.1.1.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/d66fbb73/kafka_2.12-2.0.0.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/f82c035c/metrics-core-2.2.0.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/fe3f2067/cats-macros_2.12-1.3.1.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/1ee2f2be/jackson-mapper-asl-1.9.13.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/4e393793/jackson-core-2.9.6.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/426a0862/javax.ws.rs-api-2.1.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/af0a2436/kafka-streams-2.0.0.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/3ed64c69/paranamer-2.7.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/9c64274b/xz-1.5.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/cfa4f316/jackson-databind-2.9.6.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/b6c6bb58/scala-logging_2.12-3.9.0.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/5af35056/log4j-1.2.17.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/7c4f3c47/logback-classic-1.2.3.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/de8bff5b/kafka-streams-avro-serde-5.0.0.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/110cefe2/slf4j-log4j12-1.7.25.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/31e99375/zookeeper-3.4.13.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/18ed04a0/netty-3.10.6.Final.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/9c10abea/cats-core_2.12-1.3.1.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/55762d31/audience-annotations-0.5.0.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/ef5e9d1a/kafka-clients-2.0.0-cp1.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/f2c1ebc3/scala-reflect.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/3c304d70/jackson-core-asl-1.9.13.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/d5190b41/snappy-java-1.1.7.1.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/6bd975dd/scala-library.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/f4e11d00/avro-1.8.1.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/ad89b11a/lz4-java-1.4.1.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/00f3fae0/kafka-avro-serializer-5.0.0.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/421b44ad/rocksdbjni-5.7.3.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/a698750c/commons-compress-1.8.1.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/da76ca59/slf4j-api-1.7.25.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/07c10d54/jackson-annotations-2.9.0.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/1606217a/kafka-schema-registry-client-5.0.0.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/be5a0f66/cats-effect_2.12-1.0.0.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/86434440/logback-core-1.2.3.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/c3422ef8/connect-json-2.0.0.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/8dbc042a/connect-api-2.0.0.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/7871d22c/common-config-5.0.0.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/5659bbe9/kafka-streams-scala_2.12-2.0.0.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/2e38a714/common-utils-5.0.0.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/c54d4b5a/zkclient-0.10.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/abf43203/machinist_2.12-0.6.5.jar
[debug] 	/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/b231dd44/cats-kernel_2.12-1.3.1.jar
[debug] Waiting for thread run-main-0 to terminate.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/7c4f3c47/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/var/folders/b5/v41lrpbs23gc0s93p1fr2rcscqch6g/T/sbt_5e779d71/target/110cefe2/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
java.lang.ExceptionInInitializerError
	at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:538)
	at Main$.$anonfun$run$1(Main.scala:27)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:85)
	at cats.effect.internals.IORunLoop$.start(IORunLoop.scala:34)
	at cats.effect.internals.IOBracket$.$anonfun$apply$1(IOBracket.scala:36)
	at cats.effect.internals.IOBracket$.$anonfun$apply$1$adapted(IOBracket.scala:33)
	at cats.effect.internals.IORunLoop$RestartCallback.start(IORunLoop.scala:328)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:117)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:336)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:357)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:303)
	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: org.apache.kafka.common.config.ConfigException: Invalid value org.apache.kafka.streams.errors.LogAndFailExceptionHandler for configuration default.deserialization.exception.handler: Class org.apache.kafka.streams.errors.LogAndFailExceptionHandler could not be found.
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:724)
	at org.apache.kafka.common.config.ConfigDef$ConfigKey.<init>(ConfigDef.java:1043)
	at org.apache.kafka.common.config.ConfigDef.define(ConfigDef.java:146)
	at org.apache.kafka.common.config.ConfigDef.define(ConfigDef.java:166)
	at org.apache.kafka.common.config.ConfigDef.define(ConfigDef.java:205)
	at org.apache.kafka.common.config.ConfigDef.define(ConfigDef.java:367)
	at org.apache.kafka.common.config.ConfigDef.define(ConfigDef.java:380)
	at org.apache.kafka.streams.StreamsConfig.<clinit>(StreamsConfig.java:505)
	... 17 more
```
## expectation
the expectation is for it to run correctly. In fact, if you run
- `sbt clean assembly`
-  `java -jar target/scala-2.12/test-assembly-0.1.0-SNAPSHOT.jar`

the same code starts fine.

## notes
few more details can be found [here](https://github.com/typelevel/cats-effect/issues/360), like the workaround I found. Mainly, as long as the kafka streams' `.start` runs on a different context from global, `sbt run` works fine.

sbt version: 1.2.1 (but it happens with all the previous versions. I noticed that with versions before 1.1.5 it sometimes succeeds though)

Thanks a lot for the help.

**Comment by eed3si9n** [comment]
Please fork your run: 

```scala
Compile / run / fork := true
```

**Comment by barambani** [comment]
Thanks, it works. Any resource or doc that would help me understand why it happens ? 
**UPDATE:** this actually doesn't work as, even if it starts fine, it prevents the fiber from being cancelled properly on interruption (like after a Ctrl-C). In that case there is some finalisation that needs to be done (kafka streams close) that get skipped with this.

**Comment by eed3si9n** [comment]
When you normally run a Scala program, the running program gets its own JVM.
Spinning up JVM takes time, so sbt implements a fake running by constructing a classloader and calling your app as function call in some background thread. It works for simple apps, but it doesn't for more complicated stuff. Fork says "start a new JVM by calling `java` command line", so that should be _closer_ to actual running. Some info is available in https://www.scala-sbt.org/1.x/docs/Forking.html.

As per graceful termination, there's an issue reported on that - https://github.com/sbt/sbt/issues/2274

**Comment by barambani** [comment]
Thanks a lot for the details. Very clear and helpful. 👍
