### ISSUE TITLE
NullPointerException from okhttp3 during resolution

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#4366]
### steps

On sbt 1.2.1.

1) Clean out ivy cache
2) Clone https://github.com/apache/incubator-toree 
3) Run make release

### problem

```[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.fasterxml.jackson.core#jackson-databind;2.6.5: Resolution failed several times for dependency: com.fasterxml.jackson.core#jackson-databind;2.6.5 {test=[default(compile)]}:: 
[error] 	Resolution failed several times for dependency: com.fasterxml.jackson#jackson-parent;2.6.2 {}:: 
[error] 	Resolution failed several times for dependency: com.fasterxml#oss-parent;24 {}:: 
[error] 	java.lang.NullPointerException at okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.java:278)
[error] 	java.lang.NullPointerException at okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.java:278)
[error] 	java.lang.NullPointerException at okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.java:278)
[error] 	java.lang.NullPointerException at okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.java:278)
[error] 
[error] 	java.lang.NullPointerException at okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.java:278)
[error] 	java.lang.NullPointerException at okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.java:278)
[error] 	java.lang.NullPointerException at okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.java:278)
[error] 
[error] 	java.lang.NullPointerException at okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.java:278)
[error] 	java.lang.NullPointerException at okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.java:278)
[error] 	java.lang.NullPointerException at okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.java:278)
[error] 
```

when I turn on debug, I see this

```
^[[0m[^[[0m^[[0mdebug^[[0m] ^[[0m^[[0m          tried /Users/gxc772/.ivy2/local/com.fasterxml/oss-parent/24/jars/oss-parent.jar^[[0m
^[[0m[^[[0m^[[0mdebug^[[0m] ^[[0m^[[0m          tried https://repo1.maven.org/maven2/com/fasterxml/oss-parent/24/oss-parent-24.jar^[[0m
^[[0m[^[[0m^[[0mdebug^[[0m] ^[[0m^[[0mCLIENT ERROR: Not Found url=https://repo1.maven.org/maven2/com/fasterxml/oss-parent/24/oss-parent-24.jar^[[0m
^[[0m[^[[0m^[[0mdebug^[[0m] ^[[0m^[[0m          tried http://repository.apache.org/snapshots/com/fasterxml/oss-parent/24/oss-parent-24.jar^[[0m
^[[0m[^[[0m^[[0mdebug^[[0m] ^[[0m^[[0mproblem occurred while resolving dependency: com.fasterxml#oss-parent;24 {} with public: java.lang.NullPointerException^[[0m
^[[0m[^[[0m^[[0mdebug^[[0m] ^[[0m^[[0m  at okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.java:278)^[[0m
```
sbt is tried to download the jar for a POM type module. Obviously, POM modules don't have jars, so it tries every repository until the last one and gives this exception

_Originally posted by @GaalDornick in https://github.com/sbt/sbt/issues/3519#issuecomment-422498579_

**Comment by GaalDornick** [comment]
Is anyone else able to reproduce this?

**Comment by eed3si9n** [comment]
This worked for me on my machine.

**Comment by wrighton** [comment]
I've seen this too, though it is sporadic. jackson-core version 2.9.5 seemed to the cause. Sometimes it seems to work on the 'second' attempt at compilation.

**Comment by yscialom** [comment]
Reproduced on a CentOS 7, OpenJDK-1.8.0_212, sbt-1.2.8, behind a proxy.
Workaround: added `-Dsbt.gigahorse=false` to sbt options.

**Comment by eed3si9n** [comment]
I'm going to preemptively close this since sbt 1.3.0 uses Coursier internally.
