### ISSUE TITLE
Supershell doesn't work reliably on windows

### ISSUE THREAD

**Issue by eatkins** [sbt/sbt#4421]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines
Certain output seems to cause issues (with jansi?):
```
sbt:swoval> filesJVM/test
  | => filesJVM / Compile / compile / compileInputs 0s
[info] Instrumenting 43 classes to C:\Users\ethan\code\swoval\testing\jvm\target\scala-2.12\jacoco\instrumen-------------------------------- Running Tests --------------------------------\jacoco\instrumented-classes                                                                                                      
-------------------------------- Running Tests --------------------------------
-------------------------------- Running Tests --------------------------------
Not running com.swoval.files.apple.FileEventMonitorTest on Windows
Not running com.swoval.files.ApplePathWatcherTest on Windows
+ com.swoval.files.ApplePathWatcherTest.ignore 11ms
+ com.swoval.files.apple.FileEventMonitorTest.ignore 14ms
+ com.swoval.files.DataViewTest.converter.exceptions.subdirectory 21ms
+ com.swoval.files.DataViewTest.converter.exceptions.file 44ms
+ com.swoval.files.DataViewTest.converter.exceptions.directory 303ms
-------------------------------- Running Tests --------------------------------
-------------------------------- Running Tests --------------------------------
Not running NioFileCacheTest on platform other than the jvm on osx
+ com.swoval.files.NioFileCacheSymlinkTest.ignore 0ms
AsyncLogger error handling event seq=422, value='':
java.lang.NumberFormatException: For input string:
1B
t java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.<init>(Unknown Source)
        at org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:120)
        at java.io.FilterOutputStream.write(Unknown Source)
        at java.io.PrintStream.write(Unknown Source)
        at sun.nio.cs.StreamEncoder.writeBytes(Unknown Source)
        at sun.nio.cs.StreamEncoder.implWrite(Unknown Source)
        at sun.nio.cs.StreamEncoder.write(Unknown Source)
        at java.io.OutputStreamWriter.write(Unknown Source)
        at java.io.BufferedWriter.flushBuffer(Unknown Source)
        at java.io.PrintStream.write(Unknown Source)
        at java.io.PrintStream.print(Unknown Source)
        at java.io.PrintStream.println(Unknown Source)
        at org.apache.logging.log4j.status.StatusConsoleListener.log(StatusConsoleListener.java:81)
        at org.apache.logging.log4j.status.StatusLogger.logMessage(StatusLogger.java:254)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2091)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:1988)
        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1960)
        at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:733)
        at org.apache.logging.log4j.core.appender.DefaultErrorHandler.error(DefaultErrorHandler.java:71)
        at org.apache.logging.log4j.core.config.AppenderControl.handleAppenderError(AppenderControl.java:165)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:158)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448)
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:433)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
        at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:79)
        at org.apache.logging.log4j.core.async.AsyncLogger.actualAsyncLog(AsyncLogger.java:337)
        at org.apache.logging.log4j.core.async.RingBufferLogEvent.execute(RingBufferLogEvent.java:161)
        at org.apache.logging.log4j.core.async.RingBufferLogEventHandler.onEvent(RingBufferLogEventHandler.java:45)
        at org.apache.logging.log4j.core.async.RingBufferLogEventHandler.onEvent(RingBufferLogEventHandler.java:29)
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:129)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
AsyncLogger error handling event seq=423, value='':
```
If I start sbt with `-Dsbt.progress.never`, the tests run with out error.

**Comment by eatkins** [comment]
It seems to work now.
