### ISSUE TITLE
Help Wanted - sbt assembly jar file is having issues with the manifest file - adds empty lines

### ISSUE THREAD

**Issue by ramgad** [sbt/sbt#4482]
- [X ] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps
We use the following image: bigtruedata/sbt:0.13.15-2.11.11
    # copy cached sbt and ivy2 artifacts from project dir to home dir where sbt stores them
    - apt-get update -q && apt-get install -qy rsync
    # create cache dirs in case they were not previously stored in cache
    - mkdir -p .sbt .ivy2
    # copy the cached artifacts to where sbt stores them
    - rsync -rv .sbt ${HOME}/
    - rsync -rv .ivy2 ${HOME}/
    - set -x

  script:
    - sbt compile
    - sbt assembly

The jar file is created using sbt assembly

## problem
The manifest file within the jar that got created by sbt assembly started having empty lines (see below) and breaking our application.. we are using a jar that was built a week ago to remediate the issue in prod for now. My goal is to understand the RC and fix our automation. Please note that my previous builds prior (we have a copy on Nov 30th) that did not have the issue (no empty spaces between the lines in manifest). We are able to confirm that by removing this empty spaces, the application is working, however - we do not know which process is creating the manifest file and which one is adding empty lines. I am hoping that someone who maintains and manges this repo can help us? Thanks!

**Here is the manifest file**
Manifest-Version: 1.0
Implementation-Title: ML
Implementation-Version: 0.15.83

Spark-HasRPackage: false
Specification-Vendor: default
Specification-Title: ML
Implementation-Vendor-Id: default
Specification-Version: 0.15.83

Main-Class: dedupe
Implementation-Vendor: default

## expectation
Caused by: java.lang.ClassNotFoundException: com.barrick.bdf.transformation.utils.ThreadedConcurrentContext$
at java.net.URLClassLoader$1.run(URLClassLoader.java:370)
at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 20 more
Caused by: java.io.IOException: invalid manifest format
at java.util.jar.Manifest.read(Manifest.java:225)
at java.util.jar.Manifest.<init>(Manifest.java:69)
at java.util.jar.JarFile.getManifestFromReference(JarFile.java:199)
at java.util.jar.JarFile.getManifest(JarFile.java:180)
at sun.misc.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:981)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:450)
at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
... 25 more

## notes
**I have few questions:**
1. did anything change under the hoods of "image: bigtruedata/sbt:0.13.15-2.11.11". We believe that the underlying GitHub account had some changes around the same week. 
2. How do I pin (not bring new changes)?
3. I have spent several days to find the root cause and still unable to pin point the issue and wondering if your team has any insight.

#sbt version: *insert sbt version*
Scala code runner version 2.11.11 -- Copyright 2002-2017, LAMP/EPFL
sbt version: 0.13

**Comment by eed3si9n** [comment]
We use GitHub issue mostly to track bugs and discuss feature or bugs on sbt. If you need help, please check this out - https://www.scala-sbt.org/support.html#how-can-I-get-help
