### ISSUE TITLE
sbt 1.2.8 crashes with BootstrapMethodError

### ISSUE THREAD

**Issue by gavinbaumanis** [sbt/sbt#4505]
Hi there,

OS: Mac v 10.14.2 (16 GB RAM)
SBT 1.2.8
Scala 1.12.8
Play 2.6.20
java version "1.8.0_192"

The only memory "config" I have changed is the following in my build.sbt;
javaOptions in run += "-Xmx2048m"

I just upgraded to sbt 1.2.8 and now get the following error, when using "sbt ~run" with a Play application.

java.lang.BootstrapMethodError: call site initialization exception
	at java.lang.invoke.CallSite.makeSite(CallSite.java:341)
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
	at sbt.internal.CommandExchange.shutdown(CommandExchange.scala:168)
	at sbt.StandardMain$.runManaged(Main.scala:140)
	at sbt.xMain.run(Main.scala:89)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
	at xsbt.boot.Boot$.main(Boot.scala:18)
	at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.InternalError: invoker=Lambda(a0:L/SpeciesData<L>,a1:L,a2:L,a3:L,a4:L,a5:L)=>{
    t6:V=MethodHandleImpl.checkSpreadArgument(a5:L,8);
    t7:L=ArrayAccessor.getElementL(a5:L,0);
    t8:L=ArrayAccessor.getElementL(a5:L,1);
    t9:L=ArrayAccessor.getElementL(a5:L,2);
    t10:L=ArrayAccessor.getElementL(a5:L,3);
    t11:L=ArrayAccessor.getElementL(a5:L,4);
    t12:L=ArrayAccessor.getElementL(a5:L,5);
    t13:L=ArrayAccessor.getElementL(a5:L,6);
    t14:L=ArrayAccessor.getElementL(a5:L,7);
    t15:L=Species_L.argL0(a0:L);
    t16:L=Invokers.checkGenericType(a1:L,t15:L);
    t17:V=Invokers.checkCustomized(t16:L);
    t18:L=MethodHandle.invokeBasic(t16:L,a2:L,a3:L,a4:L,t7:L,t8:L,t9:L,t10:L,t11:L,t12:L,t13:L,t14:L);t18:L}
	at java.lang.invoke.MethodHandleStatics.newInternalError(MethodHandleStatics.java:127)
	at java.lang.invoke.LambdaForm.compileToBytecode(LambdaForm.java:660)
	at java.lang.invoke.LambdaForm.prepare(LambdaForm.java:635)
	at java.lang.invoke.MethodHandle.<init>(MethodHandle.java:461)
	at java.lang.invoke.BoundMethodHandle.<init>(BoundMethodHandle.java:58)
	at java.lang.invoke.BoundMethodHandle$Species_L.<init>(BoundMethodHandle.java:211)
	at java.lang.invoke.BoundMethodHandle$Species_L.copyWith(BoundMethodHandle.java:228)
	at java.lang.invoke.MethodHandle.asSpreader(MethodHandle.java:876)
	at java.lang.invoke.Invokers.spreadInvoker(Invokers.java:158)
	at java.lang.invoke.CallSite.makeSite(CallSite.java:324)
	... 14 more
Caused by: java.lang.OutOfMemoryError: Metaspace
Error during sbt execution: java.lang.BootstrapMethodError: call site initialization exception
Exception in thread "Thread-0" java.lang.BootstrapMethodError: call site initialization exception
	at java.lang.invoke.CallSite.makeSite(CallSite.java:341)
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
	at sbt.internal.CommandExchange.shutdown(CommandExchange.scala:168)
	at sbt.StandardMain$.$anonfun$shutdownHook$1(Main.scala:124)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.InternalError: invoker=Lambda(a0:L/SpeciesData<L>,a1:L,a2:L,a3:L,a4:L,a5:L)=>{
    t6:V=MethodHandleImpl.checkSpreadArgument(a5:L,8);
    t7:L=ArrayAccessor.getElementL(a5:L,0);
    t8:L=ArrayAccessor.getElementL(a5:L,1);
    t9:L=ArrayAccessor.getElementL(a5:L,2);
    t10:L=ArrayAccessor.getElementL(a5:L,3);
    t11:L=ArrayAccessor.getElementL(a5:L,4);
    t12:L=ArrayAccessor.getElementL(a5:L,5);
    t13:L=ArrayAccessor.getElementL(a5:L,6);
    t14:L=ArrayAccessor.getElementL(a5:L,7);
    t15:L=Species_L.argL0(a0:L);
    t16:L=Invokers.checkGenericType(a1:L,t15:L);
    t17:V=Invokers.checkCustomized(t16:L);
    t18:L=MethodHandle.invokeBasic(t16:L,a2:L,a3:L,a4:L,t7:L,t8:L,t9:L,t10:L,t11:L,t12:L,t13:L,t14:L);t18:L}
	at java.lang.invoke.MethodHandleStatics.newInternalError(MethodHandleStatics.java:127)
	at java.lang.invoke.LambdaForm.compileToBytecode(LambdaForm.java:660)
	at java.lang.invoke.LambdaForm.prepare(LambdaForm.java:635)
	at java.lang.invoke.MethodHandle.<init>(MethodHandle.java:461)
	at java.lang.invoke.BoundMethodHandle.<init>(BoundMethodHandle.java:58)
	at java.lang.invoke.BoundMethodHandle$Species_L.<init>(BoundMethodHandle.java:211)
	at java.lang.invoke.BoundMethodHandle$Species_L.copyWith(BoundMethodHandle.java:228)
	at java.lang.invoke.MethodHandle.asSpreader(MethodHandle.java:876)
	at java.lang.invoke.Invokers.spreadInvoker(Invokers.java:158)
	at java.lang.invoke.CallSite.makeSite(CallSite.java:324)
	... 5 more
Caused by: java.lang.OutOfMemoryError: Metaspace
Exception in thread "Thread-3" java.lang.BootstrapMethodError: call site initialization exception
	at java.lang.invoke.CallSite.makeSite(CallSite.java:341)
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
	at akka.actor.CoordinatedShutdown.totalTimeout(CoordinatedShutdown.scala:428)
	at akka.actor.CoordinatedShutdown$.$anonfun$initJvmHook$1(CoordinatedShutdown.scala:160)
	at akka.actor.CoordinatedShutdown$$anon$2.run(CoordinatedShutdown.scala:446)
Caused by: java.lang.OutOfMemoryError: Metaspace

**Comment by eed3si9n** [comment]
It says `OutOfMemoryError: Metaspace`.
`javaOptions in run` is used only for forking, so to pass in more memory to JVM, you should start sbt with `sbt -J-Xmx2048M` or put `-Xmx2048M` into `SBT_OPTS` environment variable.
Could you try and see if that would help?

**Comment by eed3si9n** [comment]
Closing this for now.

**Comment by gavinbaumanis** [comment]
I have added the Java options as suggested and I have not had the instance
occur again since.
It is still something different to 1.2.7, in that the extra RAM is not
required in 1.2.7 - but is in 1.2.8

For the record I reverted to 1.2.7 - and the same error occurred.


As always thanks!

Gavin Baumanis
E: gavinbaumanis@gmail.com

I, for one, like Roman numerals.
