### ISSUE TITLE
Detected merged artifact

### ISSUE THREAD

**Issue by eximius313** [sbt/sbt#4520]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## problem
`sbt compile` threw:
```
[info] Executing in batch mode. For better performance use sbt's shell
[success] Total time: 5 s, completed Jan 27, 2019 10:59:37 PM
[info] Updating ...
[info] downloading https://repo1.maven.org/maven2/org/mapstruct/mapstruct-processor/1.3.0.Beta2/mapstruct-processor-1.3.0.Beta2.jar ...
[warn]  [FAILED     ] org.mapstruct#mapstruct-processor;1.3.0.Beta2!mapstruct-processor.jar: Connection reset (721ms)
[warn]  Detected merged artifact: [FAILED     ] org.mapstruct#mapstruct-processor;1.3.0.Beta2!mapstruct-processor.jar: Connection reset (721ms).
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/mapstruct/mapstruct-processor/1.3.0.Beta2/mapstruct-processor-1.3.0.Beta2.jar
[info] downloading https://repo1.maven.org/maven2/org/mapstruct/mapstruct/1.3.0.Beta2/mapstruct-1.3.0.Beta2.jar ...
[info]  [SUCCESSFUL ] org.mapstruct#mapstruct;1.3.0.Beta2!mapstruct.jar (172ms)
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::              FAILED DOWNLOADS            ::
[warn]  :: ^ see resolution messages for details  ^ ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.mapstruct#mapstruct-processor;1.3.0.Beta2!mapstruct-processor.jar
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[error] sbt.librarymanagement.ResolveException: download failed: org.mapstruct#mapstruct-processor;1.3.0.Beta2!mapstruct-processor.jar
[error]         at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:334)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
[error]         at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error]         at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error]         at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error]         at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
[error]         at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
[error]         at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
[error]         at xsbt.boot.Using$.withResource(Using.scala:10)
[error]         at xsbt.boot.Using$.apply(Using.scala:9)
[error]         at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
[error]         at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
[error]         at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]         at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]         at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:242)
[error]         at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
[error]         at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:46)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:99)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:112)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:112)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:95)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:126)
[error]         at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2398)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:272)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]         at java.lang.Thread.run(Thread.java:745)
[error] (update) sbt.librarymanagement.ResolveException: download failed: org.mapstruct#mapstruct-processor;1.3.0.Beta2!mapstruct-processor.jar
[error] Total time: 28 s, completed Jan 27, 2019 11:00:05 PM
[INFO] [01/27/2019 23:00:05.719] [Thread-2] [CoordinatedShutdown(akka://sbt-web)] Starting coordinated shutdown from JVM shutdown hook
```
but when I ran it for the second time it worked fine.

## expectation
It should run fine both times as artifact didn't change

## notes
sbt `1.1.6`

**Comment by eed3si9n** [comment]
Thanks for the report.
Do you have reproduction steps? https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md#steps

**Comment by eximius313** [comment]
as I said - it happened once during `sbt compile`.
I just thought it is worth to inform you about it.

**Comment by levinson** [comment]
Connection reset looks like a problem talking to the remote maven repository -- not an SBT bug.

**Comment by eximius313** [comment]
Ok, so where `Detected merged artifact` comes from? What does it mean?

**Comment by alexey-temnikov** [comment]
I suspect this may impact other scenario - 

`resolvers += "Atlassian Legacy" at "https://packages.atlassian.com/maven-public-legacy/"`

```
libraryDependencies += "com.atlassian.sal" % "sal-api" % "3.0.3"  artifacts Artifact("sal-api", "jar", "jar")
libraryDependencies += "com.atlassian.httpclient" % "atlassian-httpclient-plugin" % "0.23.0" artifacts Artifact("atlassian-httpclient-plugin", "jar", "jar")

libraryDependencies += "com.atlassian.jira" % "jira-rest-java-client-api" % "4.0.0"
libraryDependencies += "com.atlassian.jira" % "jira-rest-java-client-core" % "4.0.0"
```


is failing with the wrong artifact type - 

```
Detected merged artifact: [FAILED     ] com.atlassian.sal#sal-api;3.0.3!sal-api.atlassian-plugin:  (0ms).

[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::              FAILED DOWNLOADS            ::
[warn] 	:: ^ see resolution messages for details  ^ ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.atlassian.sal#sal-api;3.0.3!sal-api.atlassian-plugin
```

This issue is not reproducible in sbt 1.0.4 and reproducible in 1.2.8
