### ISSUE TITLE
ClassNotFoundException when building multiple sbt projects in parallel

### ISSUE THREAD

**Issue by fikovnik** [sbt/sbt#4545]
As a part of my research, I mine public Scala repositories to identify certain coding patterns. For this I have set up pipeline that fetches sbt-based Scala projects and compiles them. To safe time I try to parallelize it (I have a fat server). Most of the projects work just fine, but always there are cases in which it fails on random projects with the following message:

```
[error] java.lang.ClassNotFoundException: $dd8485dc31ac1cbc8a6b$
[error]         at scala.reflect.internal.util.AbstractFileClassLoader.findClass(AbstractFileClassLoader.scala:64)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error]         at java.lang.Class.forName0(Native Method)
[error]         at java.lang.Class.forName(Class.java:348)
[error]         at sbt.compiler.Eval$.getModule(Eval.scala:584)
[error]         at sbt.compiler.Eval$.getValue(Eval.scala:576)
[error]         at sbt.compiler.Eval.$anonfun$eval$1(Eval.scala:129)
[error]         at sbt.internal.EvaluateConfigurations$.$anonfun$evaluateDslEntry$1(EvaluateConfigurations.scala:249)
[error]         at sbt.internal.EvaluateConfigurations$.$anonfun$evaluateSbtFile$6(EvaluateConfigurations.scala:172)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
[error]         at scala.collection.immutable.List.foreach(List.scala:389)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:234)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
[error]         at scala.collection.immutable.List.map(List.scala:295)
[error]         at sbt.internal.EvaluateConfigurations$.$anonfun$evaluateSbtFile$4(EvaluateConfigurations.scala:172)
[error]         at sbt.internal.Load$.loadSettingsFile$1(Load.scala:1137)
[error]         at sbt.internal.Load$.$anonfun$discoverProjects$2(Load.scala:1144)
[error]         at scala.collection.MapLike.getOrElse(MapLike.scala:128)
[error]         at scala.collection.MapLike.getOrElse$(MapLike.scala:126)
[error]         at scala.collection.AbstractMap.getOrElse(Map.scala:59)
[error]         at sbt.internal.Load$.memoLoadSettingsFile$1(Load.scala:1143)
[error]         at sbt.internal.Load$.$anonfun$discoverProjects$4(Load.scala:1151)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
[error]         at scala.collection.immutable.List.foreach(List.scala:389)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:234)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
[error]         at scala.collection.immutable.List.map(List.scala:295)
[error]         at sbt.internal.Load$.loadFiles$1(Load.scala:1151)
[error]         at sbt.internal.Load$.discoverProjects(Load.scala:1165)
[error]         at sbt.internal.Load$.discover$1(Load.scala:862)
[error]         at sbt.internal.Load$.loadTransitive(Load.scala:937)
[error]         at sbt.internal.Load$.loadProjects$1(Load.scala:726)
[error]         at sbt.internal.Load$.$anonfun$loadUnit$11(Load.scala:729)
[error]         at sbt.internal.Load$.timed(Load.scala:1395)
[error]         at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:729)
[error]         at sbt.internal.Load$.timed(Load.scala:1395)
[error]         at sbt.internal.Load$.loadUnit(Load.scala:688)
[error]         at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:484)
[error]         at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:176)
[error]         at sbt.internal.BuildLoader.apply(BuildLoader.scala:241)
[error]         at sbt.internal.Load$.loadURI$1(Load.scala:546)
[error]         at sbt.internal.Load$.loadAll(Load.scala:562)
[error]         at sbt.internal.Load$.loadURI(Load.scala:492)
[error]         at sbt.internal.Load$.load(Load.scala:471)
[error]         at sbt.internal.Load$.$anonfun$apply$1(Load.scala:251)
[error]         at sbt.internal.Load$.timed(Load.scala:1395)
[error]         at sbt.internal.Load$.apply(Load.scala:251)
[error]         at sbt.internal.GlobalPlugin$.build(GlobalPlugin.scala:59)
[error]         at sbt.internal.GlobalPlugin$.load(GlobalPlugin.scala:64)
[error]         at sbt.internal.Load$.loadGlobal(Load.scala:193)
[error]         at sbt.internal.Load$.defaultWithGlobal(Load.scala:150)
[error]         at sbt.internal.Load$.$anonfun$defaultLoad$1(Load.scala:64)
[error]         at sbt.internal.Load$.timed(Load.scala:1395)
[error]         at sbt.internal.Load$.defaultLoad(Load.scala:60)
[error]         at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:829)
[error]         at sbt.BuiltinCommands$.doLoadProject(Main.scala:829)
[error]         at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:800)
[error]         at sbt.Command$.$anonfun$applyEffect$4(Command.scala:142)
[error]         at sbt.Command$.$anonfun$applyEffect$2(Command.scala:137)
[error]         at sbt.Command$.process(Command.scala:181)
[error]         at sbt.MainLoop$.processCommand(MainLoop.scala:151)
[error]         at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:139)
[error]         at sbt.State$$anon$1.runCmd$1(State.scala:246)
[error]         at sbt.State$$anon$1.process(State.scala:250)
[error]         at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:139)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.MainLoop$.next(MainLoop.scala:139)
[error]         at sbt.MainLoop$.run(MainLoop.scala:132)
[error]         at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
[error]         at sbt.io.Using.apply(Using.scala:22)
[error]         at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
[error]         at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
[error]         at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
[error]         at sbt.MainLoop$.runLogged(MainLoop.scala:35)
[error]         at sbt.StandardMain$.runManaged(Main.scala:138)
[error]         at sbt.xMain.run(Main.scala:89)
[error]         at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error]         at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error]         at xsbt.boot.Launch$.run(Launch.scala:109)
[error]         at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error]         at xsbt.boot.Launch$.launch(Launch.scala:117)
[error]         at xsbt.boot.Launch$.apply(Launch.scala:18)
[error]         at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error]         at xsbt.boot.Boot$.main(Boot.scala:18)
[error]         at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.ClassNotFoundException: $dd8485dc31ac1cbc8a6b$
```

When I redo the project again, it works fine. It looks like there is some interference between the different instances of sbt? 

I run each sbt with its own Ivy location and sbt boot location using the `-ivy` and `-sbt` options. Is there any way how to isolate them even more on a single machine without resolving to containers?

**Comment by eed3si9n** [comment]
@fikovnik Thanks for the report. I'd guess that the individual JVM instances are isolated.
How do you think I can reproduce this issue on my machine?

**Comment by fikovnik** [comment]
I can share the pipeline I use to run the analysis, but that might be a bit overwhelming. Perhaps just getting a few sbt projects and building them in parallel - I use GNU parallel to run `sbt compile` using 2-12 parallel jobs depending whether I'm on my workstation (32GB RAM) or server (256GB RAM). In both cases I see the same behavior.

**Comment by kell18** [comment]
Hi! We're facing the same issue from time to time on Jenkins... Any updates on that?

**Comment by eatkins** [comment]
My guess is that the problem is that sbt shares the ~/.sbt directory across all projects. One workaround that might prevent this issue would be to run `sbt -Dsbt.global.base=$SOME_PROJECT_SPECIFIC_DIRECTORY`.

That being said, sbt itself should probably not actually compile the global settings in the global directory for this reason. It's just the easiest way to implement.

**Comment by eatkins** [comment]
> I run each sbt with its own Ivy location and sbt boot location using the -ivy and -sbt options. Is there any way how to isolate them even more on a single machine without resolving to containers?

There are two directory options `-sbt-dir` and `-sbt-boot`. Setting `-sbt-boot` would not solve the problem given my assumption about the root cause. I was surprised to see that there wasn't a single setting to effectively change the base directory for both `sbt.global.base` and and `sbt.boot.directory` from `~/.sbt` to something else.

**Comment by fikovnik** [comment]
@eatkins is right, for us the setting the `-sbt-dir` to a "project-specific" directory helped.
