### ISSUE TITLE
object java.lang.Object in compiler mirror not found.

### ISSUE THREAD

**Issue by Raghav2211** [sbt/sbt#4555]
`error: scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
[ERROR] 	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:17)
[ERROR] 	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:18)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:53)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:66)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getClassByName(Mirrors.scala:102)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getRequiredClass(Mirrors.scala:105)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:257)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:257)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1391)
[ERROR] 	at scala.tools.nsc.Global$Run.<init>(Global.scala:1216)
[ERROR] 	at scala.tools.nsc.Driver.doCompile(Driver.scala:31)
[ERROR] 	at scala.tools.nsc.MainClass.doCompile(Main.scala:23)
[ERROR] 	at scala.tools.nsc.Driver.process(Driver.scala:51)
[ERROR] 	at scala.tools.nsc.Driver.main(Driver.scala:64)
[ERROR] 	at scala.tools.nsc.Main.main(Main.scala)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[ERROR] 	at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
[ERROR] 	at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.684 s
[INFO] Finished at: 2019-03-07T18:22:42+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile (default) on project q24448582: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]`

```java -version
java version '10.0.2' 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
```

**Comment by eed3si9n** [comment]
@Raghav2211 Could you describe what did before you got there? https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md#what-to-report
From the looks of it, you're not even running sbt.

**Comment by eed3si9n** [comment]
I am closing this due to inactivity, but if this is still relevant let us know with more details (reproduction steps etc).
