### ISSUE TITLE
could not launch sbt 1.3.0-M2 with scala-native plugin (References to undefined settings)

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt#4574]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps

build.properties

```
sbt.version=1.3.0-M2
```

project/plugins.sbt

```scala
addSbtPlugin("org.scala-native" % "sbt-scala-native" % "0.3.8")
```

build.sbt

```scala
enablePlugins(ScalaNativePlugin)

scalaVersion := "2.11.12"
```

## problem

```
[info] Loading settings for project sbt-1-3-0-m2-scala-native-build from plugins.sbt ...
[info] Loading project definition from /Users/kenji/sbt-1.3.0-M2-scala-native/project
[info] Loading settings for project sbt-1-3-0-m2-scala-native from build.sbt ...
[error] References to undefined settings: 
[error] 
[error]   Nativetest / testQuick / classLoaderLayeringStrategy from Nativetest / testQuick ((sbt.Defaults.testTasks) Defaults.scala:821)
[error] 
[error]   Nativetest / classLoaderLayeringStrategy from Nativetest / executeTests ((sbt.Defaults.testTasks) Defaults.scala:798)

[error] 
[error]   Nativetest / testOnly / classLoaderLayeringStrategy from Nativetest / testOnly ((sbt.Defaults.testTasks) Defaults.scala:820)
[error] 
[error]   Nativetest / classLoaderLayeringStrategy from Nativetest / testLoader ((sbt.Defaults.testTasks) Defaults.scala:789)

[error]  
[error] 	at sbt.internal.util.Init.Uninitialized(Settings.scala:360)
[error] 	at sbt.internal.util.Init.Uninitialized$(Settings.scala:347)
[error] 	at sbt.Def$.Uninitialized(Def.scala:21)
[error] 	at sbt.internal.util.Init.delegate(Settings.scala:260)
[error] 	at sbt.internal.util.Init.delegate$(Settings.scala:236)
[error] 	at sbt.Def$.delegate(Def.scala:21)
[error] 	at sbt.internal.util.Init.compiled(Settings.scala:194)
[error] 	at sbt.internal.util.Init.compiled$(Settings.scala:182)
[error] 	at sbt.Def$.compiled(Def.scala:21)
[error] 	at sbt.internal.util.Init.make(Settings.scala:204)
[error] 	at sbt.internal.util.Init.make$(Settings.scala:199)
[error] 	at sbt.Def$.make(Def.scala:21)
[error] 	at sbt.internal.Load$.$anonfun$apply$5(Load.scala:268)
[error] 	at sbt.internal.Load$.timed(Load.scala:1398)
[error] 	at sbt.internal.Load$.apply(Load.scala:263)
[error] 	at sbt.internal.Load$.defaultLoad(Load.scala:70)
[error] 	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:826)
[error] 	at sbt.BuiltinCommands$.doLoadProject(Main.scala:826)
[error] 	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:788)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:144)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:139)
[error] 	at sbt.Command$.process(Command.scala:183)
[error] 	at sbt.MainLoop$.$anonfun$processCommand$1(MainLoop.scala:148)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:160)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:148)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:139)
[error] 	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:269)
[error] 	at sbt.State$StateOpsImpl$.process$extension(State.scala:273)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:139)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:139)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:132)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
[error] 	at sbt.io.Using.apply(Using.scala:27)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:35)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:111)
[error] 	at sbt.xMain.run(Main.scala:60)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:18)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] References to undefined settings: 
[error] 
[error]   Nativetest / testQuick / classLoaderLayeringStrategy from Nativetest / testQuick ((sbt.Defaults.testTasks) Defaults.scala:821)
[error] 
[error]   Nativetest / classLoaderLayeringStrategy from Nativetest / executeTests ((sbt.Defaults.testTasks) Defaults.scala:798)

[error] 
[error]   Nativetest / testOnly / classLoaderLayeringStrategy from Nativetest / testOnly ((sbt.Defaults.testTasks) Defaults.scala:820)
[error] 
[error]   Nativetest / classLoaderLayeringStrategy from Nativetest / testLoader ((sbt.Defaults.testTasks) Defaults.scala:789)

[error]  
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
```

## notes

sbt version: 1.3.0-M2

/cc @densh

**Comment by eed3si9n** [comment]
This is a new key that was added in https://github.com/sbt/sbt/pull/4476.

https://github.com/sbt/sbt/blob/v1.3.0-M1/main/src/main/scala/sbt/Defaults.scala#L1808-L1813
```scala
  private val testLayeringSettings: Seq[Setting[_]] = TaskRepository.proxy(
    classLoaderCache,
    // We need a cache of size two for the test dependency layers (regular and snapshot).
    ClassLoaderCache(2)
  ) :+ (classLoaderLayeringStrategy := ClassLoaderLayeringStrategy.TestDependencies)
  lazy val testSettings: Seq[Setting[_]] = configSettings ++ testTasks
```

We should create fallback hierarchy at wider scope, like `Global`, `Global / Test`, etc.

**Comment by eatkins** [comment]
Yeah. I'm pretty sure that in the first version I had a `ClassLoaderLayeringStrategy.Default` that did not specify any particular strategy. I think that would be appropriate at the global level.
