### ISSUE TITLE
update task is not caching correctly

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#4595]
## steps

in sbt/sbt:

```
mainProj/compile
```

## problem

You see eviction warning, which is a sign that update task is running unnecessarily.

## expectation

update is cached.

## notes

Due to error-swallowing behavior of the cache, bugs are treated as cache miss.

Here's what happens if we let it throw exceptions instead:

```
sbt:sbtRoot> mainProj/compile
[error] jawn.IncompleteParseException: exhausted input
[error] 	at jawn.Parser.parse(Parser.scala:362)
[error] 	at jawn.SyncParser.parse(SyncParser.scala:24)
[error] 	at jawn.SupportParser.parseUnsafe(SupportParser.scala:12)
[error] 	at jawn.SupportParser.parseUnsafe$(SupportParser.scala:11)
[error] 	at sjsonnew.support.scalajson.unsafe.Parser$.parseUnsafe(Parser.scala:8)
[error] 	at sbt.internal.BuildStreams$.$anonfun$mkStreams$3(BuildStructure.scala:273)
[error] 	at sjsonnew.IsoString$$anon$1.from(IsoString.scala:27)
[error] 	at sbt.util.PlainInput.read(Input.scala:31)
[error] 	at sbt.util.FileBasedStore.$anonfun$read$1(CacheStore.scala:69)
[error] 	at sbt.io.Using.apply(Using.scala:27)
[error] 	at sbt.util.FileBasedStore.read(CacheStore.scala:69)
[error] 	at sbt.util.Tracked$CacheHelp.$anonfun$changed$1(Tracked.scala:186)
[error] 	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
[error] 	at scala.util.Try$.apply(Try.scala:213)
[error] 	at sbt.util.Tracked$CacheHelp.changed(Tracked.scala:186)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:148)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:124)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2701)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:268)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:277)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:268)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] scala.MatchError: Disabled() (of class sbt.librarymanagement.Disabled$)
[error] 	at sjsonnew.FlatUnionFormats$$anon$5.write(FlatUnionFormats.scala:220)
[error] 	at sjsonnew.JsonWriter.addField(JsonFormat.scala:40)
[error] 	at sjsonnew.JsonWriter.addField$(JsonFormat.scala:37)
[error] 	at sjsonnew.FlatUnionFormats$$anon$5.addField(FlatUnionFormats.scala:208)
[error] 	at sjsonnew.Builder.addField(Builder.scala:43)
[error] 	at sbt.librarymanagement.ModuleIDFormats$$anon$1.write(ModuleIDFormats.scala:46)
[error] 	at sbt.librarymanagement.ModuleIDFormats$$anon$1.write(ModuleIDFormats.scala:9)
[error] 	at sjsonnew.JsonWriter.addField(JsonFormat.scala:40)
[error] 	at sjsonnew.JsonWriter.addField$(JsonFormat.scala:37)
[error] 	at sbt.librarymanagement.ModuleIDFormats$$anon$1.addField(ModuleIDFormats.scala:9)
[error] 	at sjsonnew.Builder.addField(Builder.scala:43)
[error] 	at sbt.librarymanagement.ModuleDescriptorConfigurationFormats$$anon$1.write(ModuleDescriptorConfigurationFormats.scala:35)
[error] 	at sbt.librarymanagement.ModuleDescriptorConfigurationFormats$$anon$1.write(ModuleDescriptorConfigurationFormats.scala:9)
[error] 	at sjsonnew.FlatUnionFormats$$anon$3.write(FlatUnionFormats.scala:148)
[error] 	at sjsonnew.TupleFormats$$anon$3.write(TupleFormats.scala:72)
[error] 	at sjsonnew.TupleFormats$$anon$3.write(TupleFormats.scala:67)
[error] 	at sjsonnew.ImplicitHashWriters$$anon$1.write(ImplicitHashWriters.scala:22)
[error] 	at sjsonnew.SupportHasher.hashUnsafe(SupportHasher.scala:22)
[error] 	at sjsonnew.SupportHasher.hashUnsafe$(SupportHasher.scala:19)
[error] 	at sjsonnew.support.murmurhash.Hasher$.hashUnsafe(Hasher.scala:25)
[error] 	at sjsonnew.SupportHasher.$anonfun$hash$1(SupportHasher.scala:13)
[error] 	at scala.util.Try$.apply(Try.scala:213)
[error] 	at sjsonnew.SupportHasher.hash(SupportHasher.scala:13)
[error] 	at sjsonnew.SupportHasher.hash$(SupportHasher.scala:12)
[error] 	at sjsonnew.support.murmurhash.Hasher$.hash(Hasher.scala:25)
[error] 	at sbt.util.Tracked$CacheHelp.changed(Tracked.scala:188)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:148)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:124)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2701)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:268)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:277)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:268)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (testAgentProj / update) jawn.IncompleteParseException: exhausted input
[error] (ProjectRef(uri("file:/Users/eed3si9n/work/sbt-modules/util/"), "utilInterface") / update) scala.MatchError: Disabled() (of class sbt.librarymanagement.Disabled$)
```

**Comment by eed3si9n** [comment]
Looks like it's https://github.com/sbt/librarymanagement/pull/290.
