### ISSUE TITLE
NumberFormatException upon 1.3.0-M3 start-up

### ISSUE THREAD

**Issue by alexarchambault** [sbt/sbt#4655]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps

Create an empty sbt `1.3.0-M3` project. Have a directory named `~/.sdkman/candidates/java/8u152-zulu` on your machine (stale SDKMAN install?). Run `sbt` from it (I'm using the sbt-extras launcher, but I guess the actual launcher shouldn't matter).

```bash
$ ls ~/.sdkman/candidates/java/
… 8u152-zulu …
$ cat project/build.properties
sbt.version=1.3.0-M3
$ sbt
[info] Loading settings for project global-plugins from idea.sbt,plugins.sbt,metals.sbt ...
[error] java.lang.NumberFormatException: For input string: "-8u152"
[error] 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[error] 	at java.lang.Long.parseLong(Long.java:589)
[error] 	at java.lang.Long.parseLong(Long.java:631)
[error] 	at scala.collection.immutable.StringLike.toLong(StringLike.scala:309)
[error] 	at scala.collection.immutable.StringLike.toLong$(StringLike.scala:309)
[error] 	at scala.collection.immutable.StringOps.toLong(StringOps.scala:33)
[error] 	at sbt.internal.CrossJava$.$anonfun$parseJavaVersion$2(CrossJava.scala:33)
[error] 	at sbt.internal.CrossJava$.$anonfun$parseJavaVersion$2$adapted(CrossJava.scala:33)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:941)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error] 	at sbt.internal.CrossJava$.splitDot$1(CrossJava.scala:33)
[error] 	at sbt.internal.CrossJava$.parseJavaVersion(CrossJava.scala:42)
[error] 	at sbt.JavaVersion$.apply(JavaVersion.scala:43)
[error] 	at sbt.internal.CrossJava$.$anonfun$expandJavaHomes$1(CrossJava.scala:482)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:941)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error] 	at sbt.internal.CrossJava$.expandJavaHomes(CrossJava.scala:481)
[error] 	at sbt.Defaults$.$anonfun$globalJvmCore$8(Defaults.scala:189)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:223)
[error] 	at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:166)
[error] 	at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
[error] 	at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:99)
[error] 	at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] java.lang.NumberFormatException: For input string: "-8u152"
[error] Use 'last' for the full log.
```

## problem

sbt crashes on start-up.

Note that the sdkman directory is stale. sdkman isn't enabled / used anymore on my machine (no `SDKMAN*` env vars, no sdkman initialization at shell start-up, …)

## expectation

sbt doesn't crash on start-up :)

## notes

sbt version: `1.3.0-M3`

**Comment by eed3si9n** [comment]
@alexarchambault Thanks for the report.
sbt tries to detect all your Java installation for cross JDK forking feature `java++ 10!`.
SDKMAN support was added in https://github.com/sbt/sbt/pull/4580, but I guess it doesn't always work. In general, we should just print some warning and move on during the setting so the build is not blocked.

**Comment by eed3si9n** [comment]
Currently SDKMAN uses `8.0.202-zulu` as version convention, but it wasn't always the case I guess.
