### ISSUE TITLE
Coursier and the cursed preloaded local repo

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#4661]
Ref https://github.com/sbt/sbt-launcher-package/issues/250

## steps

1. try building sbt/librarymanagement using sbt 1.3.0-M3 on Travis CI
2. Travis uses SDKMAN to install the official sbt script, which installs preloaded local repo of sbt (1.2.8) artifacts.

https://travis-ci.org/sbt/librarymanagement/jobs/530491979

## problem

Coursier fails to resolve.

```
[error] lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[error] file:///home/travis/.sbt/preloaded/org.scala-lang.modules/scala-parser-combinators_2.12/1.0.4/bundles/scala-parser-combinators_2.12.jar: not found: /home/travis/.sbt/preloaded/org.scala-lang.modules/scala-parser-combinators_2.12/1.0.4/bundles/scala-parser-combinators_2.12.jar
[error] 
[error] 	at lmcoursier.internal.shaded.coursier.Artifacts$.$anonfun$fetchArtifacts$8(Artifacts.scala:261)
[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$2(Task.scala:11)
[error] 	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
```

## expectation

The build that used to build can build.

## notes

This is happening I think because the preloaded local repo has a few artifacts where `ivys/ivy.xml` exists but the corresponding JAR files are missing.
Ivy seems to somehow cruise along these bad local repositories, and move on to the next resolver, but Coursier throws `FetchError`. One workaround might be to not use preloaded local, and in fact there's a setting to ignore preloaded local https://github.com/coursier/sbt-coursier/blob/v1.1.0-M14-1/modules/sbt-coursier-shared/src/main/scala/coursier/sbtcoursiershared/SbtCoursierShared.scala#L65:

```scala
      coursierKeepPreloaded := false,
```

but preloaded is useful for both launcher and metabuild when it works.

Using PathFinder DSL, I tried to find out the bad directories in the currently shipping preloaded local:

```scala
scala> import sbt._

scala> val allDirs = file("/tmp/sbt/lib/local-preloaded").allPaths.filter(_.isDirectory)

scala> allDirs.get.size

scala> val badDirs = allDirs.get collect {
     |   case dir if (dir / "ivys").exists && !(dir / "jars").exists => dir
     | }
badDirs: Seq[java.io.File] = Vector(/tmp/sbt/lib/local-preloaded/org.scala-lang.modules/scala-parser-combinators_2.12/1.0.4, /tmp/sbt/lib/local-preloaded/org.scala-lang.modules/scala-parser-combinators_2.12/1.0.5, /tmp/sbt/lib/local-preloaded/org.scala-lang.modules/scala-xml_2.12/1.0.6, /tmp/sbt/lib/local-preloaded/com.typesafe/config/1.2.0, /tmp/sbt/lib/local-preloaded/com.typesafe/ssl-config-core_2.12/0.2.2, /tmp/sbt/lib/local-preloaded/com.google.protobuf/protobuf-java/3.3.1, /tmp/sbt/lib/local-preloaded/org.scala-lang/scala-compiler/2.12.6)

scala> badDirs foreach println
/tmp/sbt/lib/local-preloaded/org.scala-lang.modules/scala-parser-combinators_2.12/1.0.4
/tmp/sbt/lib/local-preloaded/org.scala-lang.modules/scala-parser-combinators_2.12/1.0.5
/tmp/sbt/lib/local-preloaded/org.scala-lang.modules/scala-xml_2.12/1.0.6
/tmp/sbt/lib/local-preloaded/com.typesafe/config/1.2.0
/tmp/sbt/lib/local-preloaded/com.typesafe/ssl-config-core_2.12/0.2.2
/tmp/sbt/lib/local-preloaded/com.google.protobuf/protobuf-java/3.3.1
/tmp/sbt/lib/local-preloaded/org.scala-lang/scala-compiler/2.12.6
```

I don't know exactly why it happens. Maybe these are evicted artifacts. Coursier seems to separate the resolution and downloading phase completely, so it would not know during the resolution that the reploaded local is missing a JAR. (To be fair, POM-only artifacts do show up from time to time in Maven repos too).

**Comment by eed3si9n** [comment]
### idea 1

One way to solve this is to create a marker text file with some UUID file name, and compare it against the timestamps in `ls ~/.sbt/preloaded/org.scala-sbt/sbt/`.
If there are new installation, we can run a cleanup logic to remove bad directories.

**Comment by eed3si9n** [comment]
> One way to solve this is to create a marker text file with some UUID file name, and compare it against the timestamps in ls `~/.sbt/preloaded/org.scala-sbt/sbt/`.

This probably won't work because the original files in preloaded local are in the installation directory `lib/`, and it gets `rsync`ed by the `sbt` Bash script.

### idea 2

There are actually two preloaded local repos.

```
  local-preloaded-ivy: file:///${sbt.preloaded-${sbt.global.base-${user.home}/.sbt}/preloaded/}, [organization]/[module]/[revision]/[type]s/[artifact](-[classifier]).[ext]
  local-preloaded: file:///${sbt.preloaded-${sbt.global.base-${user.home}/.sbt}/preloaded/}
```

Thus far we have been using `local-preloaded-ivy`, but we can ignore the repository from now on if we can preload using Maven layout using `coursier fetch`.

**Comment by eed3si9n** [comment]
FYI @alexarchambault.

**Comment by bitloi** [comment]
Hi @eed3si9n, Would you mind reviewing my approach?

**Approach**: Re-enable the preloaded repos for Coursier, but wrap them in a filtering repository (in lm-coursier) that only exposes artifacts that actually exist on disk:

- In `find()`: After delegating to the underlying preloaded repo, check which of its artifacts would pass the “file exists” filter. If all would be filtered out (e.g. ivy.xml present but JAR missing), return `Left(...)` so Coursier tries the next resolver (e.g. Maven Central) for that module — matching Ivy’s “cruise along and move on to the next resolver” behavior.
- In `artifacts()`: Delegate to the underlying repo, then filter out any `(Publication, Artifact)` whose `artifact.url` is a `file:` URL and the local file does not exist.

The wrapper would only be used when building `mainRepositories` for resolvers whose name starts with `"local-preloaded"`. In sbt main, preloaded would be re-enabled (e.g. via a `coursierKeepPreloaded` setting, default `true`).
**Rationale:** So we only “claim” a module from preloaded when at least one artifact exists; otherwise we let the next resolver provide it and avoid both `FetchError` and missing JARs on the classpath.
Does this look good to you, or would you prefer a different strategy (e.g. keep preloaded off by default and only expose a setting, or handle this elsewhere)? Please let me know what you think.
Thanks.

**Comment by eed3si9n** [comment]
The idea behind preloaded local repo is to have an installer that contains all sbt JARs in an USB drive. I don't know if we have that kind of need, and even if we did sbt alone won't be enough. I think in this case, closing the issue is the simpler answer. Thanks for checking!
