### ISSUE TITLE
Compile / doc fails with ArrayIndexOutOfBoundsException since sbt 1.2.2

### ISSUE THREAD

**Issue by panditaj** [sbt/sbt#4665]
- [ ] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps
Multi-module project, upgrade of sbt from 1.2.1 to 1.2.3

## problem
Change of sbt version and tried publishToLocal fails. Exception is given below:

```
[error] java.lang.ArrayIndexOutOfBoundsException: 5
[error] 	at scala.reflect.internal.util.BatchSourceFile.findLine$1(SourceFile.scala:192)
[error] 	at scala.reflect.internal.util.BatchSourceFile.offsetToLine(SourceFile.scala:195)
[error] 	at xsbt.DelegatingReporter$.lineOf$1(DelegatingReporter.scala:94)
[error] 	at xsbt.DelegatingReporter$.makePosition$1(DelegatingReporter.scala:107)
[error] 	at xsbt.DelegatingReporter$.convert(DelegatingReporter.scala:129)
[error] 	at xsbt.DelegatingReporter.comment(DelegatingReporter.scala:150)
[error] 	at scala.tools.nsc.Global.signalParsedDocComment(Global.scala:260)
[error] 	at scala.tools.nsc.ast.parser.ScannersCommon$DocScanner.registerDocComment(Scanners.scala:52)
[error] 	at scala.tools.nsc.ast.parser.ScannersCommon$DocScanner.registerDocComment$(Scanners.scala:50)
[error] 	at scala.tools.nsc.javac.JavaScanners$JavaScanner.registerDocComment(JavaScanners.scala:220)
[error] 	at scala.tools.nsc.doc.ScaladocSyntaxAnalyzer$ScaladocScanner.finishDocComment(ScaladocAnalyzer.scala:118)
[error] 	at scala.tools.nsc.doc.ScaladocSyntaxAnalyzer$ScaladocScanner.finishDocComment$(ScaladocAnalyzer.scala:116)
[error] 	at scala.tools.nsc.doc.ScaladocSyntaxAnalyzer$ScaladocJavaUnitScanner.finishDocComment(ScaladocAnalyzer.scala:198)
[error] 	at scala.tools.nsc.javac.JavaScanners$JavaScanner.skipComment(JavaScanners.scala:607)
[error] 	at scala.tools.nsc.javac.JavaScanners$JavaScanner.fetchToken(JavaScanners.scala:477)
[error] 	at scala.tools.nsc.javac.JavaScanners$JavaScanner.nextToken(JavaScanners.scala:251)
[error] 	at scala.tools.nsc.javac.JavaScanners$JavaScanner.init(JavaScanners.scala:871)
[error] 	at scala.tools.nsc.javac.JavaScanners$JavaUnitScanner.<init>(JavaScanners.scala:877)
[error] 	at scala.tools.nsc.doc.ScaladocSyntaxAnalyzer$ScaladocJavaUnitScanner.<init>(ScaladocAnalyzer.scala:198)
[error] 	at scala.tools.nsc.doc.ScaladocSyntaxAnalyzer$ScaladocJavaUnitParser.<init>(ScaladocAnalyzer.scala:212)
[error] 	at scala.tools.nsc.doc.ScaladocGlobalTrait.newJavaUnitParser(ScaladocGlobal.scala:17)
[error] 	at scala.tools.nsc.doc.ScaladocGlobalTrait.newJavaUnitParser$(ScaladocGlobal.scala:16)
[error] 	at scala.tools.nsc.doc.ScaladocGlobal.newJavaUnitParser(ScaladocGlobal.scala:40)
[error] 	at scala.tools.nsc.ast.parser.SyntaxAnalyzer.scala$tools$nsc$ast$parser$SyntaxAnalyzer$$initialUnitBody(SyntaxAnalyzer.scala:85)
[error] 	at scala.tools.nsc.ast.parser.SyntaxAnalyzer$ParserPhase.apply(SyntaxAnalyzer.scala:99)
[error] 	at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:426)
[error] 	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:419)
[error] 	at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1(Global.scala:390)
[error] 	at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1$adapted(Global.scala:390)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:944)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:944)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
[error] 	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:390)
[error] 	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1446)
[error] 	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1430)
[error] 	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1423)
[error] 	at scala.tools.nsc.Global$Run.compile(Global.scala:1539)
[error] 	at scala.tools.nsc.doc.DocFactory.makeUniverse(DocFactory.scala:44)
[error] 	at scala.tools.nsc.doc.DocFactory.generate$1(DocFactory.scala:124)
[error] 	at scala.tools.nsc.doc.DocFactory.document(DocFactory.scala:131)
[error] 	at xsbt.Runner.run(ScaladocInterface.scala:30)
[error] 	at xsbt.ScaladocInterface.run(ScaladocInterface.scala:15)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
[error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:166)
[error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:147)
[error] 	at sbt.Doc$.$anonfun$scaladoc$1(Doc.scala:39)
[error] 	at sbt.Doc$.$anonfun$scaladoc$1$adapted(Doc.scala:39)
[error] 	at sbt.RawCompileLike$.$anonfun$prepare$1(RawCompileLike.scala:83)
[error] 	at sbt.RawCompileLike$.$anonfun$prepare$1$adapted(RawCompileLike.scala:76)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$3(RawCompileLike.scala:67)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$3$adapted(RawCompileLike.scala:65)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$1(RawCompileLike.scala:72)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$1$adapted(RawCompileLike.scala:55)
[error] 	at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1422)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] (foo-service / Compile / doc) java.lang.ArrayIndexOutOfBoundsException: 5
```

## expectation
upgrade of patch versions shouldn't break stuff.

## notes

sbt version: *1.2.3*

**Comment by eed3si9n** [comment]
@panditaj Please see https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md#what-to-report
Could you include information on how we can reproduce the issue on our computers please? Otherwise, I don't know what we can do. Also please try the latest patch version 1.2.8.

**Comment by panditaj** [comment]
While trying to put something which i could upload for re-creating the problem, I came across an empty Java file in one of the modules which I removed and ran publishLocal again and the issue was fixed. :) 

I'll still work on putting something that can reproduce this.

**Comment by andyscott** [comment]
I'm seeing a similar error when trying to publish https://github.com/higherkindness/droste with SBT 1.2.8.

```
[warn]  You need to remove it from the cache manually to take effect.
[info]  published ivy to /Users/andyscott/.ivy2/local/io.higherkindness/droste-macros_2.11/0.7.0/ivys/ivy.xml
[error] java.lang.ArrayIndexOutOfBoundsException: 110
[error]         at scala.reflect.internal.util.BatchSourceFile.findLine$1(SourceFile.scala:178)
[error]         at scala.reflect.internal.util.BatchSourceFile.offsetToLine(SourceFile.scala:181)
[error]         at xsbt.DelegatingReporter$.lineOf$1(DelegatingReporter.scala:94)
[error]         at xsbt.DelegatingReporter$.makePosition$1(DelegatingReporter.scala:107)
[error]         at xsbt.DelegatingReporter$.convert(DelegatingReporter.scala:129)
[error]         at xsbt.DelegatingReporter.info0(DelegatingReporter.scala:160)
[error]         at xsbt.DelegatingReporter.info0(DelegatingReporter.scala:137)
[error]         at scala.reflect.internal.Reporter.warning(Reporting.scala:81)
```

**Comment by eed3si9n** [comment]
@andyscott Thanks for following up with more info.

Looking at the stacktrace again, it looks like ScalaDoc is calling `scala.tools.nsc.javac.JavaScanners` to create a comment and/or warning, and then the registered reporter asks for the position of the event, and it goes to `scala.reflect.internal.util.BatchSourceFile.offsetToLine` and it's out of bounds.
`xsbt.DelegatingReporter` calls `lineOf` only when range position is enabled.

So maybe this happens sometimes, but not always, when you call `doc` task (often as part of `publish` or `publishLocal`) with range position turned on (for semanticdb etc purpose) where the position returns bad offset, or for whatever reason it thinks `5` or `110` is out of bounds. Either case, my guess is that this is a scala/scala compiler bug, not sbt.

**Comment by eed3si9n** [comment]
See also https://github.com/scala/bug/issues/9885

**Comment by andyscott** [comment]
Yep, makes sense!

You should be able to reproduce the error in Droste on commit sha `e92efd0ad467af6af24206bcd2842260b77d8a40` by running `publishLocal` from the root project. The issue went away after downgrading SBT to 1.2.0.

**Comment by xuwei-k** [comment]
- https://github.com/xuwei-k/sbt-usecase-bug
- https://travis-ci.org/xuwei-k/sbt-usecase-bug/builds/552347397

<img width="787" alt="build-log" src="https://user-images.githubusercontent.com/389787/60393724-afc51e00-9b54-11e9-8051-0ad8bb7d2722.png">

**Comment by xuwei-k** [comment]
- https://github.com/sbt/sbt/compare/v1.2.1...v1.2.2
- https://github.com/sbt/zinc/compare/v1.2.1...v1.2.2

Maybe https://github.com/sbt/zinc/pull/580 and/or https://github.com/sbt/zinc/pull/588 ? 🤔/cc @smarter

**Comment by eed3si9n** [comment]
I can't reproduce this with sbt 1.4.2 using @xuwei-k's repro so it was fixed at some point?
