### ISSUE TITLE
[1.3.0-RC1] java.lang.NoClassDefFoundError in tests

### ISSUE THREAD

**Issue by plokhotnyuk** [sbt/sbt#4685]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps

1. Clone the following repo: https://github.com/plokhotnyuk/jsoniter-scala
2. Set `1.3.0-RC1` in `project/build.properties`
3. Run tests: `sbt clean test`

## problem

[error] (jsoniter-scala-benchmark / Test / executeTests) java.lang.NoClassDefFoundError: Could not initialize class com.github.plokhotnyuk.jsoniter_scala.benchmark.DslPlatformJson$

## expectation

No test failures

## notes

The `DslPlatformJson` class uses code generation in run-time.
An example of a stacktrace:
```
[error] java.lang.NoClassDefFoundError: Could not initialize class com.github.plokhotnyuk.jsoniter_scala.benchmark.DslPlatformJson$
[error]         at com.github.plokhotnyuk.jsoniter_scala.benchmark.BigIntWriting.dslJsonScala(BigIntWriting.scala:29)
[error]         at com.github.plokhotnyuk.jsoniter_scala.benchmark.BigIntWritingSpec.$anonfun$new$2(BigIntWritingSpec.scala:13)
[error]         at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[error]         at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[error]         at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[error]         at org.scalatest.Transformer.apply(Transformer.scala:22)
[error]         at org.scalatest.Transformer.apply(Transformer.scala:20)
[error]         at org.scalatest.WordSpecLike$$anon$3.apply(WordSpecLike.scala:1075)
[error]         at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[error]         at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[error]         at org.scalatest.WordSpec.withFixture(WordSpec.scala:1881)
[error]         at org.scalatest.WordSpecLike.invokeWithFixture$1(WordSpecLike.scala:1073)
[error]         at org.scalatest.WordSpecLike.$anonfun$runTest$1(WordSpecLike.scala:1085)
[error]         at org.scalatest.SuperEngine.runTestImpl(Engine.scala:286)
[error]         at org.scalatest.WordSpecLike.runTest(WordSpecLike.scala:1085)
[error]         at org.scalatest.WordSpecLike.runTest$(WordSpecLike.scala:1067)
[error]         at org.scalatest.WordSpec.runTest(WordSpec.scala:1881)
[error]         at org.scalatest.WordSpecLike.$anonfun$runTests$1(WordSpecLike.scala:1144)
[error]         at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:393)
[error]         at scala.collection.immutable.List.foreach(List.scala:392)
[error]         at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
[error]         at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:370)
[error]         at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:407)
[error]         at scala.collection.immutable.List.foreach(List.scala:392)
[error]         at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
[error]         at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:376)
[error]         at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:458)
[error]         at org.scalatest.WordSpecLike.runTests(WordSpecLike.scala:1144)
[error]         at org.scalatest.WordSpecLike.runTests$(WordSpecLike.scala:1143)
[error]         at org.scalatest.WordSpec.runTests(WordSpec.scala:1881)
[error]         at org.scalatest.Suite.run(Suite.scala:1124)
[error]         at org.scalatest.Suite.run$(Suite.scala:1106)
[error]         at org.scalatest.WordSpec.org$scalatest$WordSpecLike$$super$run(WordSpec.scala:1881)
[error]         at org.scalatest.WordSpecLike.$anonfun$run$1(WordSpecLike.scala:1189)
[error]         at org.scalatest.SuperEngine.runImpl(Engine.scala:518)
[error]         at org.scalatest.WordSpecLike.run(WordSpecLike.scala:1189)
[error]         at org.scalatest.WordSpecLike.run$(WordSpecLike.scala:1187)
[error]         at org.scalatest.WordSpec.run(WordSpec.scala:1881)
[error]         at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:317)
[error]         at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:510)
[error]         at sbt.TestRunner.runTest$1(TestFramework.scala:139)
[error]         at sbt.TestRunner.run(TestFramework.scala:153)
[error]         at sbt.TestFramework$$anon$3$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:316)
[error]         at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:276)
[error]         at sbt.TestFramework$$anon$3$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:316)
[error]         at sbt.TestFramework$$anon$3$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:316)
[error]         at sbt.TestFunction.apply(TestFramework.scala:328)
[error]         at sbt.Tests$.$anonfun$toTask$1(Tests.scala:309)
[error]         at sbt.std.Transform$$anon$3.$anonfun$apply$2(Transform.scala:46)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:270)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:279)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:270)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
```

**Comment by eed3si9n** [comment]
Please add the following line to disable layered ClassLoader for your benchmark project:

```diff
@@ -138,6 +138,7 @@ lazy val `jsoniter-scala-benchmark` = project
   .settings(commonSettings)
   .settings(noPublishSettings)
   .settings(
+    Test / classLoaderLayeringStrategy := ClassLoaderLayeringStrategy.Flat,
     libraryDependencies ++= Seq(
```

**Comment by plokhotnyuk** [comment]
@eed3si9n Thanks a lot!

Now it works on Linux and MacOS X, but still fails in tests on Windows with the following error:
```
[error] (jsoniter-scala-macros / Test / compileIncremental) java.nio.file.InvalidPathException: Illegal char <?> at index 144: C:\projects\jsoniter-scala\jsoniter-scala-macros\target\scala-2.12\test-classes\com\github\plokhotnyuk\jsoniter_scala\macros\JsonCodecMakerSpec$?$1.class
```
Please, look for more details in [the Appveyor build log](https://ci.appveyor.com/project/plokhotnyuk/jsoniter-scala/builds/24602003).
Is it yet another misconfiguration or a separated issue that worth reporting?
