### ISSUE TITLE
ClassLoaderLayeringStrategy.ScalaLibrary breaks scalatest

### ISSUE THREAD

**Issue by pshirshov** [sbt/sbt#4689]
Hi,

Seems like `ClassLoaderLayeringStrategy.ScalaLibrary` in 1.3.0-RC1 breaks scalatest with the a cryptic message. Surprisingly default setting works, as well as `.Flat`. I guess it's not a bug but could anyone explain this behaviour? From my understanding of the new scheme it should work fine.

```
[error] java.lang.NoClassDefFoundError: scala/reflect/runtime/package$
[error] 	at org.scalatest.tools.Framework.runner(Framework.scala:985)
[error] 	at sbt.Defaults$.$anonfun$createTestRunners$1(Defaults.scala:1003)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
[error] 	at scala.collection.immutable.Map$Map1.foreach(Map.scala:128)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error] 	at sbt.Defaults$.createTestRunners(Defaults.scala:997)
[error] 	at sbt.Defaults$.allTestGroupsTask(Defaults.scala:1065)
[error] 	at sbt.Defaults$.$anonfun$testTasks$10(Defaults.scala:804)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:270)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:279)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:270)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
```

sbt 1.3.0-RC1
scala 2.12.8
scalatest 3.0.7

**Comment by eed3si9n** [comment]
@pshirshov Thanks for the report. If the default is working, then ScalaLibrary not working sounds like a bug.

**Comment by eed3si9n** [comment]
```
[info] [error] java.lang.NoClassDefFoundError: scala/reflect/runtime/package$
[info] [error]  at org.scalatest.tools.Framework.runner(Framework.scala:985)
[info] [error]  at sbt.Defaults$.$anonfun$createTestRunners$1(Defaults.scala:1003)
[info] [error]  at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
[info] [error]  at scala.collection.immutable.Map$Map1.foreach(Map.scala:128)
[info] [error]  at scala.collection.TraversableLike.map(TraversableLike.scala:237)
[info] [error]  at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
[info] [error]  at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[info] [error]  at sbt.Defaults$.createTestRunners(Defaults.scala:997)
[info] [error]  at sbt.Defaults$.allTestGroupsTask(Defaults.scala:1065)
[info] [error]  at sbt.Defaults$.$anonfun$testTasks$10(Defaults.scala:804)
[info] [error]  at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[info] [error]  at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[info] [error]  at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[info] [error]  at sbt.Execute.$anonfun$submit$2(Execute.scala:270)
[info] [error]  at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[info] [error]  at sbt.Execute.work(Execute.scala:279)
[info] [error]  at sbt.Execute.$anonfun$submit$1(Execute.scala:270)
[info] [error]  at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[info] [error]  at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[info] [error]  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info] [error]  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info] [error]  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info] [error]  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info] [error]  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info] [error]  at java.lang.Thread.run(Thread.java:748)
[info] [error] Caused by: java.lang.ClassNotFoundException: scala.reflect.runtime.package$
[info] [error]  at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[info] [error]  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[info] [error]  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[info] [error]  at org.scalatest.tools.Framework.runner(Framework.scala:985)
[info] [error]  at sbt.Defaults$.$anonfun$createTestRunners$1(Defaults.scala:1003)
[info] [error]  at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
[info] [error]  at scala.collection.immutable.Map$Map1.foreach(Map.scala:128)
[info] [error]  at scala.collection.TraversableLike.map(TraversableLike.scala:237)
[info] [error]  at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
[info] [error]  at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[info] [error]  at sbt.Defaults$.createTestRunners(Defaults.scala:997)
[info] [error]  at sbt.Defaults$.allTestGroupsTask(Defaults.scala:1065)
[info] [error]  at sbt.Defaults$.$anonfun$testTasks$10(Defaults.scala:804)
[info] [error]  at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[info] [error]  at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[info] [error]  at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[info] [error]  at sbt.Execute.$anonfun$submit$2(Execute.scala:270)
[info] [error]  at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[info] [error]  at sbt.Execute.work(Execute.scala:279)
[info] [error]  at sbt.Execute.$anonfun$submit$1(Execute.scala:270)
[info] [error]  at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[info] [error]  at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[info] [error]  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info] [error]  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info] [error]  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info] [error]  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info] [error]  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info] [error]  at java.lang.Thread.run(Thread.java:748)
[info] [error] (Test / executeTests) java.lang.NoClassDefFoundError: scala/reflect/runtime/package$
```

https://github.com/scalatest/scalatest/blob/release-3.0.7/scalatest/src/main/scala/org/scalatest/tools/Framework.scala

```scala
    import scala.reflect.runtime._

    val runtimeMirror = universe.runtimeMirror(testClassLoader)

    val module = runtimeMirror.staticModule("org.scalatest.tools.Runner$")
    val obj = runtimeMirror.reflectModule(module)
    val runnerInstance = obj.instance.asInstanceOf[Runner.type]
```

**Comment by eatkins** [comment]
sigh: https://github.com/scalatest/scalatest/pull/1534/files

**Comment by eatkins** [comment]
Since sbt has always had first class scalatest support, an obvious fix would be to check the defined test frameworks and add the scala reflect library jar if scalatest is in the list. It is a bummer to have to special case scalatest though.

**Comment by eed3si9n** [comment]
It does work out of the box and `Flat`, so the failure almost seems like it's working as expected.

**Comment by eatkins** [comment]
Perhaps, but I'm still a bit confused as to why this is happening because scala reflect is in the ivy.xml for scalatest so the scala reflect jar should be in the layer that contains the scalatest jar.

**Comment by eed3si9n** [comment]
> Perhaps, but I'm still a bit confused as to why this is happening because scala reflect is in the ivy.xml for scalatest so the scala reflect jar should be in the layer that contains the scalatest jar.

It's me. I think broke it in https://github.com/sbt/sbt/pull/4671.

>         val dynamicClasspath =
>          fullCP.filterNot(testDependencySet ++ runtimeDependencies ++ si.allJars)

I missed the si.allJars here.

**Comment by eed3si9n** [comment]
Should be fixed in https://github.com/sbt/sbt/pull/4703.
