### ISSUE TITLE
[1.3.0-RC1] java.nio.file.InvalidPathException on Windows when files names have non-ascii characters

### ISSUE THREAD

**Issue by philwalk** [sbt/sbt#4690]
I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps
1. environment: windows 10, any shell (tested CMD.EXE/sbt.bat, and cygwin/bash/sbt).
2. edit project/build.properties, setting sbt.version=1.3.0-RC1
3. create a file in the current directory with a file named thisenv.out^M
Note: in cygwin bash environment, file can be created via this command:

$ touch thisenv.out^M

where the 2 keystrokes following "out" are ctrl-V ctrl-M

## problem
sbt crashes with this stackdump:

```
[info] Loading settings for project global-plugins from dirtymoney.sbt,idea.sbt,plugins.sbt ...


[info] Loading global plugins from C:\Users\philwalk\.sbt\1.0\plugins
[info] Loading settings for project ue-build from build.sbt,buildinfo.sbt,play-fork-run.sbt,plugins.sbt,sbt-ui.sbt ...
[info] Loading project definition from C:\opt\ue\project
[error] java.nio.file.InvalidPathException: Illegal char <?> at index 21: C:\opt\ue\thisenv.out?
[error]         at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
[error]         at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
[error]         at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
[error]         at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
[error]         at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
[error]         at java.nio.file.Paths.get(Paths.java:84)
[error]         at com.swoval.files.SimpleFileTreeView$Lister.impl(SimpleFileTreeView.java:168)
[error]         at com.swoval.files.SimpleFileTreeView$Lister.fillResults(SimpleFileTreeView.java:140)
[error]         at com.swoval.files.SimpleFileTreeView.list(SimpleFileTreeView.java:50)
[error]         at sbt.nio.file.FileTreeView$DefaultFileTreeView$.list(FileTreeView.scala:48)
[error]         at sbt.nio.file.FileTreeView$$anon$1.fillBuffer(FileTreeView.scala:160)
[error]         at sbt.nio.file.FileTreeView$$anon$1.<init>(FileTreeView.scala:183)
[error]         at sbt.nio.file.FileTreeView$.iterator(FileTreeView.scala:134)
[error]         at sbt.nio.file.FileTreeView$.all(FileTreeView.scala:108)
[error]         at sbt.nio.file.FileTreeView$.all(FileTreeView.scala:102)
[error]         at sbt.nio.file.FileTreeView$Ops$.list$extension0(FileTreeView.scala:73)
[error]         at sbt.io.Path$.$anonfun$defaultChildHandler$3(Path.scala:321)
[error]         at sbt.io.FilterFiles.handleFile(Path.scala:633)
[error]         at sbt.io.ChildPathFinder.$anonfun$addTo$2(Path.scala:717)
[error]         at sbt.io.ChildPathFinder.$anonfun$addTo$2$adapted(Path.scala:716)
[error]         at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[error]         at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[error]         at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[error]         at sbt.io.ChildPathFinder.addTo(Path.scala:716)
[error]         at sbt.io.PathFinderImpl.get(Path.scala:604)
[error]         at sbt.BuildPaths$.configurationSources(BuildPaths.scala:117)
[error]         at sbt.internal.Load$.defaultSbtFiles$lzycompute$2(Load.scala:1110)
[error]         at sbt.internal.Load$.defaultSbtFiles$2(Load.scala:1110)
[error]         at sbt.internal.Load$.associatedFiles$1(Load.scala:1145)
[error]         at sbt.internal.Load$.discoverProjects(Load.scala:1152)
[error]         at sbt.internal.Load$.discover$1(Load.scala:851)
[error]         at sbt.internal.Load$.loadTransitive(Load.scala:926)
[error]         at sbt.internal.Load$.loadProjects$1(Load.scala:716)
[error]         at sbt.internal.Load$.$anonfun$loadUnit$11(Load.scala:719)
[error]         at sbt.internal.Load$.timed(Load.scala:1384)
[error]         at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:719)
[error]         at sbt.internal.Load$.timed(Load.scala:1384)
[error]         at sbt.internal.Load$.loadUnit(Load.scala:678)
[error]         at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:475)
[error]         at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:181)
[error]         at sbt.internal.BuildLoader.apply(BuildLoader.scala:246)
[error]         at sbt.internal.Load$.loadURI$1(Load.scala:537)
[error]         at sbt.internal.Load$.loadAll(Load.scala:553)
[error]         at sbt.internal.Load$.loadURI(Load.scala:483)
[error]         at sbt.internal.Load$.load(Load.scala:462)
[error]         at sbt.internal.Load$.$anonfun$apply$1(Load.scala:239)
[error]         at sbt.internal.Load$.timed(Load.scala:1384)
[error]         at sbt.internal.Load$.apply(Load.scala:239)
[error]         at sbt.internal.Load$.defaultLoad(Load.scala:55)
[error]         at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:881)
[error]         at sbt.BuiltinCommands$.doLoadProject(Main.scala:881)
[error]         at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:843)
[error]         at sbt.Command$.$anonfun$applyEffect$4(Command.scala:144)
[error]         at sbt.Command$.$anonfun$applyEffect$2(Command.scala:139)
[error]         at sbt.Command$.process(Command.scala:183)
[error]         at sbt.MainLoop$.$anonfun$processCommand$1(MainLoop.scala:150)
[error]         at sbt.MainLoop$.processCommand(MainLoop.scala:162)
[error]         at sbt.MainLoop$.processCommand(MainLoop.scala:150)
[error]         at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:138)
[error]         at sbt.State$StateOpsImpl$.runCmd$1(State.scala:269)
[error]         at sbt.State$StateOpsImpl$.process$extension(State.scala:273)
[error]         at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:138)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.MainLoop$.next(MainLoop.scala:138)
[error]         at sbt.MainLoop$.run(MainLoop.scala:131)
[error]         at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:109)
[error]         at sbt.io.Using.apply(Using.scala:27)
[error]         at sbt.MainLoop$.runWithNewLog(MainLoop.scala:103)
[error]         at sbt.MainLoop$.runAndClearLast(MainLoop.scala:58)
[error]         at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:43)
[error]         at sbt.MainLoop$.runLogged(MainLoop.scala:34)
[error]         at sbt.StandardMain$.runManaged(Main.scala:173)
[error]         at sbt.xMainImpl$.run(Main.scala:126)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at sbt.xMain.run(Main.scala:55)
[error]         at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error]         at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error]         at xsbt.boot.Launch$.run(Launch.scala:109)
[error]         at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error]         at xsbt.boot.Launch$.launch(Launch.scala:117)
[error]         at xsbt.boot.Launch$.apply(Launch.scala:18)
[error]         at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error]         at xsbt.boot.Boot$.main(Boot.scala:18)
[error]         at xsbt.boot.Boot.main(Boot.scala)
[error] java.nio.file.InvalidPathException: Illegal char <?> at index 21: C:\opt\ue\thisenv.out?
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

## expectation
should ignore files that are not specified as part of the build, as did previous versions of sbt

## notes
A workaround is to rename the file to something else.

sbt version: 1.3.0-RC1

**Comment by eed3si9n** [comment]
@philwalk Thanks for the report. The expectation makes sense to me too.

**Comment by eed3si9n** [comment]
There was another report on this https://github.com/sbt/sbt/issues/4717

## steps

1. Clone the following repo: https://github.com/plokhotnyuk/jsoniter-scala
2. Set `1.3.0-RC1` in `project/build.properties`
3. Run tests: `sbt clean test`

**Comment by eatkins** [comment]
Fixed in https://github.com/sbt/io/pull/243.
