### ISSUE TITLE
Default ClassLoaderLayeringStrategy breaks some code which uses dirty magic to resolve singletons

### ISSUE THREAD

**Issue by pshirshov** [sbt/sbt#4691]
I have a project with a custom `StaticLoggerBinder` for `slf4j`.

I noticed that slf4j started failing picking up this (dirty and shitty) singleton class while running my tests under 1.30-RC1.

The behaviour observed is explainable.

Also there are other issues, like I'm building my microsite with paradox and sbt-microsite and noticed that sbt throws a lot of `NoClassDefFoundError`s during shutdown.

```
Uncaught error from thread [sbt-web-akka.actor.default-dispatcher-2]: scala/concurrent/Future$$anon$1, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for for ActorSystem[sbt-web]
java.lang.NoClassDefFoundError: scala/concurrent/Future$$anon$1
	at scala.concurrent.Future$.firstCompletedOf(Future.scala:683)
	at akka.actor.CoordinatedShutdown.loop$1(CoordinatedShutdown.scala:382)
	at akka.actor.CoordinatedShutdown.$anonfun$run$6(CoordinatedShutdown.scala:387)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.ClassNotFoundException: scala.concurrent.Future$$anon$1
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 17 more
``` 

I  welcome all the performance improvements made in 1.3 though maybe it's not so good idea to change default behaviour so much?

**Comment by eed3si9n** [comment]
@pshirshov Thanks for the report.

> I welcome all the performance improvements made in 1.3 though maybe it's not so good idea to change default behaviour so much?

I am open to both possibilities. For RC-1, we wanted to turn on all the turbo mode and gauge the community feedback. If the test breakage % is too high, then it makes sense to pick more conservative default. I'd guess that 80% of the builds would be ok, but I am not sure if that's ok enough.

**Comment by pshirshov** [comment]
Just discovered that mdoc fails also.

Damn singletons.

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/4729
