### ISSUE TITLE
pdfxstream library dependency breaks sbt 1.3.0-RC1 but working for earlier versions

### ISSUE THREAD

**Issue by philwalk** [sbt/sbt#4692]
I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps

- download sbt 1.3.0-RC1, and install it as your sbt command line tool
- create a new project containing the following build.sbt

```
import sbt._

name          := "hello"
version       := "0.01"
organization  := "org.foo"
scalaVersion  := "2.12.8"

libraryDependencies += "com.snowtide" % "pdfxstream" % "3.1.1"
```

-  `sbt update
`
## problem
sbt update results in the following error:
```
sbt:hello> update
[info] Updating
[info] Resolved  dependencies
[warn]
[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.snowtide:pdfxstream:3.1.1
[error]   Not found
[error]   not found: /home/philwalk/.ivy2/local/com.snowtide/pdfxstream/3.1.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/snowtide/pdfxstream/3.1.1/pdfxstream-3.1.1.pom
[error]         at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:227)
[error]         at lmcoursier.CoursierDependencyResolution.$anonfun$update$30(CoursierDependencyResolution.scala:196)
[error]         at scala.util.Either$LeftProjection.map(Either.scala:573)
[error]         at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:196)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:87)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:137)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:150)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:150)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:131)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:164)
[error]         at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2844)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:270)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:279)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:270)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.snowtide:pdfxstream:3.1.1
[error]   Not found
[error]   not found: /home/philwalk/.ivy2/local/com.snowtide/pdfxstream/3.1.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/snowtide/pdfxstream/3.1.1/pdfxstream-3.1.1.pom
[error] Total time: 0 s, completed May 16, 2019 3:06:33 PM
```

## expectation
if you then edit `project/build.properties` and specify `sbt.version=1.2.8`, the error goes away.

## notes
Tested on Windows 10 and on Ubuntu 18.04 LTS
The problem seems to be specific to pdfxstream, no problems encountered with the following library dependency:
`
libraryDependencies += "com.github.pathikrit" %% "better-files" % "3.8.0"

`

sbt version: 1.3.0-RC1

**Comment by philwalk** [comment]
ok, this may not be a bug, except in the sense that I have a local copy of pdfxstream in my ivy2 cache, and it might not be available to the new sbt?

**Comment by eed3si9n** [comment]
https://repo1.maven.org/maven2/com/snowtide/ doesn't show pdfxstream.

And I also get this on sbt 1.2.8:

```
sbt:hello> compile
[info] Updating ...
[warn] 	module not found: com.snowtide#pdfxstream;3.1.1
[warn] ==== local: tried
[warn]   /Users/eed3si9n/.ivy2/local/com.snowtide/pdfxstream/3.1.1/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/snowtide/pdfxstream/3.1.1/pdfxstream-3.1.1.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /Users/eed3si9n/.sbt/preloaded/com.snowtide/pdfxstream/3.1.1/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////Users/eed3si9n/.sbt/preloaded/com/snowtide/pdfxstream/3.1.1/pdfxstream-3.1.1.pom
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.snowtide#pdfxstream;3.1.1: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.snowtide:pdfxstream:3.1.1 (/private/tmp/pdfxstream/build.sbt#L8-9)
[warn] 		  +- org.foo:hello_2.12:0.01
```

**Comment by philwalk** [comment]
I don't get any problems with sbt 1.2.8 because my local cache has a copy of pdfxstream.   Shouldn't sbt 1.3.0-RC1 also find it?

**Comment by eed3si9n** [comment]
sbt 1.3.0-RC1 uses Coursier by default - https://www.lightbend.com/blog/sbt-1.3.0-release
