### ISSUE TITLE
Command alias prefixed with `~` doesn't work

### ISSUE THREAD

**Issue by japgolly** [sbt/sbt#4695]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps

1. Add `addCommandAlias("tc" , "test:compile")` to `build.sbt`
2. Start sbt
3. Type `~tc`

## problem

An exception occurs:

```
root> ~tc
[error] java.lang.IllegalStateException: Error attempting to extract scope from tc: Not a valid project ID: tc
[error] Expected ':'
[error] Not a valid key: tc
[error] tc
[error]   ^.
[error] 	at sbt.internal.Continuous$.parseCommand(Continuous.scala:386)
[error] 	at sbt.internal.Continuous$.$anonfun$getAllConfigs$1(Continuous.scala:394)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
[error] 	at scala.collection.immutable.List.map(List.scala:298)
[error] 	at sbt.internal.Continuous$.getAllConfigs(Continuous.scala:394)
[error] 	at sbt.internal.Continuous$.$anonfun$runToTermination$7(Continuous.scala:339)
[error] 	at sbt.std.Streams.use(Streams.scala:104)
[error] 	at sbt.std.Streams.use$(Streams.scala:100)
[error] 	at sbt.std.Streams$$anon$1.use(Streams.scala:117)
[error] 	at sbt.internal.Continuous$.$anonfun$runToTermination$6(Continuous.scala:335)
[error] 	at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:374)
[error] 	at sbt.internal.Continuous$.$anonfun$runToTermination$5(Continuous.scala:335)
[error] 	at sbt.internal.Continuous$.setup(Continuous.scala:269)
[error] 	at sbt.internal.Continuous$.$anonfun$runToTermination$1(Continuous.scala:334)
[error] 	at sbt.internal.Continuous$.withCharBufferedStdIn(Continuous.scala:308)
[error] 	at sbt.internal.Continuous$.runToTermination(Continuous.scala:317)
[error] 	at sbt.internal.Continuous$.$anonfun$continuous$1(Continuous.scala:108)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:144)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:139)
[error] 	at sbt.Command$.process(Command.scala:183)
[error] 	at sbt.MainLoop$.$anonfun$processCommand$1(MainLoop.scala:150)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:162)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:150)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:138)
[error] 	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:269)
[error] 	at sbt.State$StateOpsImpl$.process$extension(State.scala:273)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:138)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:138)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:131)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:109)
[error] 	at sbt.io.Using.apply(Using.scala:27)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:103)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:58)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:43)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:34)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:173)
[error] 	at sbt.xMainImpl$.run(Main.scala:126)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.xMain.run(Main.scala:55)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:18)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.IllegalStateException: Error attempting to extract scope from tc: Not a valid project ID: tc
[error] Expected ':'
[error] Not a valid key: tc
[error] tc
[error]   ^.
[error] Use 'last' for the full log.
```

## expectation

It should be equivalent to running `~test:compile` which works.

## notes

sbt version: 1.3.0-RC1

**Comment by eed3si9n** [comment]
Maybe different mechanisms but we had similar issue with `+` - https://github.com/sbt/sbt/issues/2776
