### ISSUE TITLE
[1.3.0-RC1] does not work with IntelliJ

### ISSUE THREAD

**Issue by kwark** [sbt/sbt#4697]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps

1. sbt new scala/hello-world.g8
2. import project in IntelliJ with "Use sbt shell for imports/for builds checked"
3. edit "project/build.properties" and change sbt version to "1.3.0-RC1"
4. restart sbt-shell (in IntelliJ)

```
[error] (update) java.net.URISyntaxException: Illegal character in path at index 37: file:/Users/peter/Library/Application Support/IntelliJIdea2019.1/Scala/repo/org.jetbrains/sbt-idea-shell/scala_2.12/sbt_1.0/2018.3/jars/sbt-idea-shell.jar
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
```

## problem

IntelliJ starts it's sbt-shell using: 

`/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/bin/java -agentlib:jdwp=transport=dt_socket,address=localhost:57735,suspend=n,server=y -Xdebug -server -Xmx4096M -Didea.managed=true -Dfile.encoding=UTF-8 -jar "/Users/peter/Library/Application Support/IntelliJIdea2019.1/Scala/launcher/sbt-launch.jar" --addPluginSbtFile=/private/var/folders/2w/vnl_r6q11cxc_nxrg5rkxs3w0000gn/T/idea1835.sbt "; set ideaPort in Global := 51934 ; idea-shell"`

IntelliJ uses the `addPluginSbtFile` command to add some of its own sbt plugins to the build. The contents of this file are:

```
// Generated by IntelliJ-IDEA Scala plugin.
// Adds settings when starting sbt from IDEA.
// Manual changes to this file will be lost.
scala.collection.Seq(
resolvers += Resolver.file("intellij-scala-plugin", file(raw"/Users/peter/Library/Application Support/IntelliJIdea2019.1/Scala/repo"))(Resolver.ivyStylePatterns),
addSbtPlugin("org.jetbrains" % "sbt-structure-extractor" % "2018.2.1+4-88400d3f"),
addSbtPlugin("org.jetbrains" % "sbt-idea-shell" % "2018.3"),
addSbtPlugin("org.jetbrains" % "sbt-idea-compiler-indices" % "0.1.3")
)
```

The `intellij-scala-plugin` resolver contains a space in its file name and it looks like this causes the URISyntaxException 

## expectation

IntelliJ sbt-shell should continue to work fine with sbt 1.3.0-RC1

## notes

sbt version: 1.3.0-RC1

**Comment by eed3si9n** [comment]
@kwark Thanks for the report!

**Comment by eed3si9n** [comment]
Here's a quick minimization. Add the following to `project/plugins.sbt`

```scala
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.9")
resolvers += Resolver.file("intellij-scala-plugin", file(raw"/tmp/space the final frontier/repo"))(Resolver.ivyStylePatterns)
```

I get 

```
[error] java.net.URISyntaxException: Illegal character in path at index 17: file:///tmp/space the final frontier/repo/com.eed3si9n/sbt-buildinfo/scala_2.12/sbt_1.0/0.9.0/ivys/ivy.xml
[error] 	at java.net.URI$Parser.fail(URI.java:2848)
[error] 	at java.net.URI$Parser.checkChars(URI.java:3021)
[error] 	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
[error] 	at java.net.URI$Parser.parse(URI.java:3053)
[error] 	at java.net.URI.<init>(URI.java:588)
[error] 	at lmcoursier.internal.shaded.coursier.credentials.DirectCredentials.autoMatches(DirectCredentials.scala:63)
[error] 	at lmcoursier.internal.shaded.coursier.cache.FileCache.$anonfun$filePerPolicy$2(FileCache.scala:639)
[error] 	at lmcoursier.internal.shaded.coursier.cache.FileCache.$anonfun$filePerPolicy$2$adapted(FileCache.scala:639)

                                                                                                              [error] 	at scala.collection.LinearSeqOptimized.find(LinearSeqOptimized.scala:115)

	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)


	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)

	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)         [error] 	at scala.collection.LinearSeqOptimized.find$(LinearSeqOptimized.scala:112)
	at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete(Promise.scala:372)
	at scala.concurrent.impl.Promise.transformWith(Promise.scala:40)
	at scala.concurrent.impl.Promise.transformWith$(Promise.scala:38)
	at scala.concurrent.impl.Promise$KeptPromise$Successful.transformWith(Promise.scala:379)
	at scala.concurrent.Future.flatMap(Future.scala:306)
	at scala.concurrent.impl.Promise$KeptPromise$Successful.onComplete(Promise.scala:379)
	at scala.concurrent.Future.flatMap$(Future.scala:306)

	at scala.concurrent.impl.Promise$KeptPromise$Successful.flatMap(Promise.scala:379)

	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$1(Task.scala:11)
	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$2(Task.scala:11)
[error] 	at scala.collection.immutable.List.find(List.scala:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[error] 	at lmcoursier.internal.shaded.coursier.cache.FileCache.$anonfun$filePerPolicy$1(FileCache.scala:639)
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)

	at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)

	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)

[error] at scalaat lmcoursier.internal.shaded.coursier.util.Monad.$anonfun$map$1(Monad.scala:8)	at scala.concurrent.impl.Promise.transformWith(Promise.scala:40)

	at scala.concurrent.impl.Promise.transformWith$(Promise.scala:38)mise.scala:371)
	at scala.concurrent.impl.Promise$KeptPromise$Successful.transformWith(Promise.scala:379)
	at scala.concurrent.Future.flatMap(Future.scala:306)
	at scala.concurrent.Future.flatMap$(Future.scala:306)





                                                                       [error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$2(Task.scala:11)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] 	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (update) java.net.URISyntaxException: Illegal character in path at index 17: file:///tmp/space the final frontier/repo/com.eed3si9n/sbt-buildinfo/scala_2.12/sbt_1.0/0.9.0/ivys/ivy.xml
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

**Comment by eed3si9n** [comment]
Opened https://github.com/coursier/coursier/issues/1175 on Coursier.
