### ISSUE TITLE
[1.3.0-RC1] Cannot run source generator

### ISSUE THREAD

**Issue by avdv** [sbt/sbt#4701]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines :heavy_check_mark: 

## steps

Our main project uses a source generator, defined as a task. The generator is compiled from the `codegen` sub-project:
```
sourceGenerators in Compile += Def.taskDyn {
   val outputFiles = Seq("Resources.scala", "References.scala").map(targetDir / _)
   Def.task {
          (codegen / Compile / run)
            .toTask(" " + targetDir.getAbsolutePath)
            .value
          outputFiles
        }
}
```

1. `sbt compile`

## problem :boom: 

```
[info] Running check.codegen.Main /home/claudio/src/check/target/scala-2.12/src_managed/main/check/models/resources
[error] (run-main-0) java.lang.NoClassDefFoundError: scala/reflect/api/TypeCreator
[error] java.lang.NoClassDefFoundError: scala/reflect/api/TypeCreator
[error]         at eu.timepit.refined.api.RefType$.<init>(RefType.scala:146)
[error]         at eu.timepit.refined.api.RefType$.<clinit>(RefType.scala)
[error]         at eve.publish.codegen.JsonSchema$.<init>(JsonSchema.scala:319)
[error]         at eve.publish.codegen.JsonSchema$.<clinit>(JsonSchema.scala)
[error]         at eve.publish.codegen.Main$.$anonfun$loadYamlSchema$2(ModelGenerator.scala:111)
[error]         at cats.effect.IO$Map.apply(IO.scala:1426)
[error]         at cats.effect.IO$Map.apply(IO.scala:1422)
[error]         at cats.effect.internals.IORunLoop$.liftedTree3$1(IORunLoop.scala:225)
[error]         at cats.effect.internals.IORunLoop$.step(IORunLoop.scala:225)
[error]         at cats.effect.IO.unsafeRunTimed(IO.scala:321)
[error]         at cats.effect.IO.unsafeRunSync(IO.scala:240)
[error]         at eve.publish.codegen.Main$.$anonfun$main$2(ModelGenerator.scala:71)
[error]         at eve.publish.codegen.Main$.$anonfun$main$2$adapted(ModelGenerator.scala:68)
[error]         at scala.Option.foreach(Option.scala:274)
[error]         at check.codegen.Main$.main(ModelGenerator.scala:68)
[error]         at check.codegen.Main.main(ModelGenerator.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error] Caused by: java.lang.ClassNotFoundException: scala.reflect.api.TypeCreator
[error]         at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error]         at eu.timepit.refined.api.RefType$.<init>(RefType.scala:146)
[error]         at eu.timepit.refined.api.RefType$.<clinit>(RefType.scala)
[error]         at check.codegen.JsonSchema$.<init>(JsonSchema.scala:319)
[error]         at check.codegen.JsonSchema$.<clinit>(JsonSchema.scala)
[error]         at check.codegen.Main$.$anonfun$loadYamlSchema$2(ModelGenerator.scala:111)
[error]         at cats.effect.IO$Map.apply(IO.scala:1426)
[error]         at cats.effect.IO$Map.apply(IO.scala:1422)
[error]         at cats.effect.internals.IORunLoop$.liftedTree3$1(IORunLoop.scala:225)
[error]         at cats.effect.internals.IORunLoop$.step(IORunLoop.scala:225)
[error]         at cats.effect.IO.unsafeRunTimed(IO.scala:321)
[error]         at cats.effect.IO.unsafeRunSync(IO.scala:240)
[error]         at check.codegen.Main$.$anonfun$main$2(ModelGenerator.scala:71)
[error]         at check.codegen.Main$.$anonfun$main$2$adapted(ModelGenerator.scala:68)
[error]         at scala.Option.foreach(Option.scala:274)
[error]         at check.codegen.Main$.main(ModelGenerator.scala:68)
[error]         at check.codegen.Main.main(ModelGenerator.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error] Nonzero exit code: 1
[error] (codegen / Compile / run) Nonzero exit code: 1

```

## expectation

It should work as before with SBT 1.2.8. :smile: 

## workaround

Setting `codegen / Compile / run / classLoaderLayeringStrategy := ClassLoaderLayeringStrategy.Flat` works!

Maybe this should be the default? :thinking: Or did I do something obviously wrong?

## notes

sbt version: 1.3.0-RC1

**Comment by eed3si9n** [comment]
I think this will be fixed with https://github.com/sbt/sbt/pull/4703.
