### ISSUE TITLE
[1.3.0-RC1] coursier fails when with "Conflicting dependencies"

### ISSUE THREAD

**Issue by Katrix** [sbt/sbt#4720]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

## steps
Add `"com.github.gpgekko" % "sbt-autoprefixer" % "1.2.0"` to a project

## problem
```
[error] lmcoursier.internal.shaded.coursier.error.ResolutionError$Several: Error downloading org.webjars.npm:browserslist:[2.5.1,3)
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/org/webjars/npm/browserslist/2.11.3/browserslist-2.11.3.pom
[error]   not found: C:\Users\katri\.ivy2\local\org.webjars.npm\browserslist
[error]   not found: https://repo.triplequote.com/artifactory/sbt-plugins-release/org.webjars.npm/browserslist/
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.webjars.npm/browserslist/
[error]   not found: http://repo.typesafe.com/typesafe/releases/org/webjars/npm/browserslist/maven-metadata.xml
[error] Conflicting dependencies:
[error] org.webjars.npm:is-number:2.1.0:default(compile)
[error] org.webjars.npm:is-number:4.0.0:default(compile)
[error] org.webjars.npm:kind-of:3.2.2:default(compile)
[error] org.webjars.npm:kind-of:6.0.2:default(compile)
[error] org.webjars.npm:string-width:1.0.2:default(compile)
[error] org.webjars.npm:string-width:2.1.1:default(compile)
[error] org.webjars.npm:strip-ansi:3.0.1:default(compile)
[error] org.webjars.npm:strip-ansi:4.0.0:default(compile)
[error]         at lmcoursier.internal.shaded.coursier.error.ResolutionError$.from(ResolutionError.scala:70)
[error]         at lmcoursier.internal.shaded.coursier.Resolve.validate0$1(Resolve.scala:141)
[error]         at lmcoursier.internal.shaded.coursier.Resolve.$anonfun$ioWithConflicts0$4(Resolve.scala:183)
[error]         at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$2(Task.scala:11)
[error]         at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
[error]         at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
[error]         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (update) lmcoursier.internal.shaded.coursier.error.ResolutionError$Several: Error downloading org.webjars.npm:browserslist:[2.5.1,3)
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/org/webjars/npm/browserslist/2.11.3/browserslist-2.11.3.pom
[error]   not found: C:\Users\katri\.ivy2\local\org.webjars.npm\browserslist
[error]   not found: https://repo.triplequote.com/artifactory/sbt-plugins-release/org.webjars.npm/browserslist/
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.webjars.npm/browserslist/
[error]   not found: http://repo.typesafe.com/typesafe/releases/org/webjars/npm/browserslist/maven-metadata.xml
[error] Conflicting dependencies:
[error] org.webjars.npm:is-number:2.1.0:default(compile)
[error] org.webjars.npm:is-number:4.0.0:default(compile)
[error] org.webjars.npm:kind-of:3.2.2:default(compile)
[error] org.webjars.npm:kind-of:6.0.2:default(compile)
[error] org.webjars.npm:string-width:1.0.2:default(compile)
[error] org.webjars.npm:string-width:2.1.1:default(compile)
[error] org.webjars.npm:strip-ansi:3.0.1:default(compile)
[error] org.webjars.npm:strip-ansi:4.0.0:default(compile)
```

## expectation
Now, the POM truly is missing for some reason, but it worked just fine with 1.2.8

sbt version: 1.3.0-RC1

**Comment by eed3si9n** [comment]
@Katrix Thanks for the report!

The error message says:

```
[error] Conflicting dependencies:
[error] org.webjars.npm:is-number:2.1.0:default(compile)
[error] org.webjars.npm:is-number:4.0.0:default(compile)
[error] org.webjars.npm:kind-of:3.2.2:default(compile)
[error] org.webjars.npm:kind-of:6.0.2:default(compile)
[error] org.webjars.npm:string-width:1.0.2:default(compile)
[error] org.webjars.npm:string-width:2.1.1:default(compile)
[error] org.webjars.npm:strip-ansi:3.0.1:default(compile)
[error] org.webjars.npm:strip-ansi:4.0.0:default(compile)
```

I suggest you override the version for those conflicting dependencies - https://www.scala-sbt.org/1.x/docs/Library-Management.html#Overriding+a+version
or use Ivy instead. 

```scala
ThisBuild / useCoursier := false
```

**Comment by joan38** [comment]
I'm hitting this as well in SBT 1.3.0-RC3 and `dependencyOverrides` don't seem to resolve the issue.

**Comment by joan38** [comment]
I tried something like:
```
dependencyOverrides += "org.webjars.npm" %% "kind-of" % "6.0.0"
```
But it doesn't work any idea?

**Comment by eed3si9n** [comment]
That sounds concerning.

@alexarchambault dependencyOverrides should be able to resolve any conflicts, right?

**Comment by joan38** [comment]
@alexarchambault @eed3si9n Reproduction steps:
```
touch build.sbt
mkdir project
cat > project/plugins.sbt << EOF
addSbtPlugin("com.github.gpgekko" % "sbt-autoprefixer" % "1.2.0")
dependencyOverrides ++= Seq(
  "org.webjars.npm" % "is-number" % "4.0.0",
  "org.webjars.npm" % "kind-of" % "6.0.0",
  "org.webjars.npm" % "string-width" % "2.0.0",
  "org.webjars.npm" % "strip-ansi" % "4.0.0"
)
EOF
echo "sbt.version=1.3.0-RC3" > project/build.properties
sbt update
```

**Comment by alexarchambault** [comment]
Seems to be an issue with the wiring of sbt with coursier. [It's an issue with the sbt-lm-coursier plugin too](https://github.com/coursier/coursier/issues/1278), that's very similar to the coursier integration in sbt.
