### ISSUE TITLE
sbt 1.3.0-RC1: [error] java.lang.NumberFormatException: For input string: "0-rc12"

### ISSUE THREAD

**Issue by Miuler** [sbt/sbt#4731]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

S.O.: ArchLinux

## steps
Latter install sdk 1.3.0-RC1 from sdkman, I do execute the sdk command

## problem

``` 
> sbt -Dlog4j2.debug
Copying runtime jar.
DEBUG StatusLogger Using ShutdownCallbackRegistry class org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry
DEBUG StatusLogger Not in a ServletContext environment, thus not loading WebLookup plugin.
DEBUG StatusLogger AsyncLogger.ThreadNameStrategy=UNCACHED (user specified null, default is UNCACHED)
TRACE StatusLogger Using default SystemClock for timestamps.
DEBUG StatusLogger org.apache.logging.log4j.core.util.SystemClock supports precise timestamps.
DEBUG StatusLogger Apache Log4j Core 2.11.2 initializing configuration org.apache.logging.log4j.core.config.builder.impl.BuiltConfiguration@3a3e78f
DEBUG StatusLogger Installed 2 script engines
Warning: Nashorn engine is planned to be removed from a future JDK release
DEBUG StatusLogger Oracle Nashorn version: 12.0.1, language: ECMAScript, threading: Not Thread Safe, compile: true, names: [nashorn, Nashorn, js, JS, JavaScript, javascript, ECMAScript, ecmascript], factory class: jdk.nashorn.api.scripting.NashornScriptEngineFactory
INFO StatusLogger Cannot initialize scripting support because this JRE does not support it.
 scala.reflect.internal.FatalError: class StringContext does not have a member s
	at scala.reflect.internal.Definitions$DefinitionsClass.fatalMissingSymbol(Definitions.scala:1253)
	at scala.reflect.internal.Definitions$DefinitionsClass.$anonfun$getMember$1(Definitions.scala:1276)
	at scala.reflect.internal.Definitions$DefinitionsClass.getMember(Definitions.scala:1271)
	at scala.reflect.internal.Definitions$DefinitionsClass.getMemberMethod(Definitions.scala:1305)
	at scala.reflect.internal.Definitions$DefinitionsClass$RunDefinitions.StringContext_s$lzycompute(Definitions.scala:1495)
	at scala.reflect.internal.Definitions$DefinitionsClass$RunDefinitions.StringContext_s(Definitions.scala:1495)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer$StringContextIntrinsic$.unapply(RefChecks.scala:1598)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformApply(RefChecks.scala:1562)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1798)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStat(RefChecks.scala:1227)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.$anonfun$transformStats$1(RefChecks.scala:1198)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStats(RefChecks.scala:1198)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStats(RefChecks.scala:114)
	at scala.reflect.internal.Trees.itransform(Trees.scala:1402)
	at scala.reflect.internal.Trees.itransform$(Trees.scala:1372)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:27)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:27)
	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2563)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1862)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:114)
	at scala.reflect.internal.Trees.$anonfun$itransform$2(Trees.scala:1399)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2608)
	at scala.reflect.internal.Trees.itransform(Trees.scala:1397)
	at scala.reflect.internal.Trees.itransform$(Trees.scala:1372)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:27)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:27)
	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2563)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1862)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStat(RefChecks.scala:1227)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.$anonfun$transformStats$1(RefChecks.scala:1198)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStats(RefChecks.scala:1198)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStats(RefChecks.scala:114)
	at scala.reflect.internal.Trees.itransform(Trees.scala:1440)
	at scala.reflect.internal.Trees.itransform$(Trees.scala:1372)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:27)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:27)
	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2563)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1862)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:114)
	at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2571)
	at scala.reflect.internal.Trees.$anonfun$itransform$4(Trees.scala:1444)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2608)
	at scala.reflect.internal.Trees.itransform(Trees.scala:1443)
	at scala.reflect.internal.Trees.itransform$(Trees.scala:1372)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:27)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:27)
	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2563)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1862)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStat(RefChecks.scala:1227)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.$anonfun$transformStats$1(RefChecks.scala:1198)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStats(RefChecks.scala:1198)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStats(RefChecks.scala:114)
	at scala.reflect.internal.Trees.$anonfun$itransform$7(Trees.scala:1462)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2608)
	at scala.reflect.internal.Trees.itransform(Trees.scala:1462)
	at scala.reflect.internal.Trees.itransform$(Trees.scala:1372)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:27)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:27)
	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2563)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1862)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:114)
	at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:147)
	at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:37)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:448)
	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:398)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1498)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1482)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1475)
	at scala.tools.nsc.interpreter.IMain._initialize(IMain.scala:134)
	at scala.tools.nsc.interpreter.IMain.initializeSynchronous(IMain.scala:154)
	at scala.tools.nsc.interpreter.Scripted.<init>(Scripted.scala:83)
	at scala.tools.nsc.interpreter.Scripted$.apply(Scripted.scala:318)
	at scala.tools.nsc.interpreter.Scripted$Factory.getScriptEngine(Scripted.scala:311)
	at org.apache.logging.log4j.core.script.ScriptManager.<init>(ScriptManager.java:99)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:216)
	at org.apache.logging.log4j.core.config.builder.impl.DefaultConfigurationBuilder.build(DefaultConfigurationBuilder.java:204)
	at org.apache.logging.log4j.core.config.builder.impl.DefaultConfigurationBuilder.build(DefaultConfigurationBuilder.java:161)
	at org.apache.logging.log4j.core.config.builder.impl.DefaultConfigurationBuilder.build(DefaultConfigurationBuilder.java:57)
	at sbt.util.LogExchange.init(LogExchange.scala:143)
	at sbt.util.LogExchange.context$lzycompute(LogExchange.scala:18)
	at sbt.util.LogExchange.context(LogExchange.scala:18)
	at sbt.util.LogExchange.logger(LogExchange.scala:26)
	at sbt.util.LogExchange.logger(LogExchange.scala:24)
	at sbt.internal.util.GlobalLogging$.initial(GlobalLogging.scala:82)
	at sbt.StandardMain$.initialGlobalLogging(Main.scala:190)
	at sbt.StandardMain$.initialState(Main.scala:216)
	at sbt.xMainImpl$.run(Main.scala:124)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at sbt.xMain.run(Main.scala:55)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
	at xsbt.boot.Boot$.main(Boot.scala:18)
	at xsbt.boot.Boot.main(Boot.scala)
DEBUG StatusLogger Took 0.106769 seconds to load 206 plugins from SbtMetaBuildClassLoader
DEBUG StatusLogger PluginManager 'Core' found 117 plugins
DEBUG StatusLogger PluginManager 'Level' found 0 plugins
DEBUG StatusLogger PluginManager 'Lookup' found 13 plugins
DEBUG StatusLogger Building Plugin[name=loggers, class=org.apache.logging.log4j.core.config.LoggersPlugin].
DEBUG StatusLogger createLoggers(={})
DEBUG StatusLogger Building Plugin[name=appenders, class=org.apache.logging.log4j.core.config.AppendersPlugin].
DEBUG StatusLogger createAppenders(={})
WARN StatusLogger No Root logger was configured, creating default ERROR-level Root logger with Console appender
DEBUG StatusLogger PluginManager 'Converter' found 44 plugins
DEBUG StatusLogger Starting OutputStreamManager SYSTEM_OUT.false.false-1
DEBUG StatusLogger Configuration org.apache.logging.log4j.core.config.builder.impl.BuiltConfiguration@3a3e78f initialized
DEBUG StatusLogger Not in a ServletContext environment, thus not loading WebLookup plugin.
DEBUG StatusLogger Not in a ServletContext environment, thus not loading WebLookup plugin.
DEBUG StatusLogger PluginManager 'Converter' found 44 plugins
DEBUG StatusLogger Starting OutputStreamManager SYSTEM_OUT.false.false-2
DEBUG StatusLogger Starting LoggerContext[name=3bd82cf5, org.apache.logging.log4j.core.LoggerContext@7bb35cc6] with configuration org.apache.logging.log4j.core.config.builder.impl.BuiltConfiguration@3a3e78f...
DEBUG StatusLogger Shutdown hook enabled. Registering a new one.
DEBUG StatusLogger Starting configuration org.apache.logging.log4j.core.config.builder.impl.BuiltConfiguration@3a3e78f
DEBUG StatusLogger Started configuration org.apache.logging.log4j.core.config.builder.impl.BuiltConfiguration@3a3e78f OK.
TRACE StatusLogger Stopping org.apache.logging.log4j.core.config.DefaultConfiguration@66bacdbc...
TRACE StatusLogger DefaultConfiguration notified 1 ReliabilityStrategies that config will be stopped.
TRACE StatusLogger DefaultConfiguration stopping root LoggerConfig.
TRACE StatusLogger DefaultConfiguration notifying ReliabilityStrategies that appenders will be stopped.
TRACE StatusLogger DefaultConfiguration stopping remaining Appenders.
DEBUG StatusLogger Shutting down OutputStreamManager SYSTEM_OUT.false.false-2
DEBUG StatusLogger Shut down OutputStreamManager SYSTEM_OUT.false.false-2, all resources released: true
DEBUG StatusLogger Appender DefaultConsole-2 stopped with status true
TRACE StatusLogger DefaultConfiguration stopped 1 remaining Appenders.
TRACE StatusLogger DefaultConfiguration cleaning Appenders from 1 LoggerConfigs.
DEBUG StatusLogger Stopped org.apache.logging.log4j.core.config.DefaultConfiguration@66bacdbc OK
TRACE StatusLogger Reregistering MBeans after reconfigure. Selector=org.apache.logging.log4j.core.selector.ClassLoaderContextSelector@45667d98
TRACE StatusLogger Reregistering context (1/1): '3bd82cf5' org.apache.logging.log4j.core.LoggerContext@7bb35cc6
TRACE StatusLogger Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=3bd82cf5'
TRACE StatusLogger Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=3bd82cf5,component=StatusLogger'
TRACE StatusLogger Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=3bd82cf5,component=ContextSelector'
TRACE StatusLogger Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=3bd82cf5,component=Loggers,name=*'
TRACE StatusLogger Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=3bd82cf5,component=Appenders,name=*'
TRACE StatusLogger Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=3bd82cf5,component=AsyncAppenders,name=*'
TRACE StatusLogger Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=3bd82cf5,component=AsyncLoggerRingBuffer'
TRACE StatusLogger Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=3bd82cf5,component=Loggers,name=*,subtype=RingBuffer'
DEBUG StatusLogger Registering MBean org.apache.logging.log4j2:type=3bd82cf5
DEBUG StatusLogger Registering MBean org.apache.logging.log4j2:type=3bd82cf5,component=StatusLogger
DEBUG StatusLogger Registering MBean org.apache.logging.log4j2:type=3bd82cf5,component=ContextSelector
DEBUG StatusLogger Registering MBean org.apache.logging.log4j2:type=3bd82cf5,component=Appenders,name=DefaultConsole-1
TRACE StatusLogger Using default SystemClock for timestamps.
DEBUG StatusLogger org.apache.logging.log4j.core.util.SystemClock supports precise timestamps.
TRACE StatusLogger Using DummyNanoClock for nanosecond timestamps.
DEBUG StatusLogger LoggerContext[name=3bd82cf5, org.apache.logging.log4j.core.LoggerContext@7bb35cc6] started OK with configuration org.apache.logging.log4j.core.config.builder.impl.BuiltConfiguration@3a3e78f.
[warn] No sbt.version set in project/build.properties, base directory: /home/miuler/123
[error] java.lang.NumberFormatException: For input string: "0-rc12"
[error] 	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
[error] 	at java.base/java.lang.Long.parseLong(Long.java:699)
[error] 	at java.base/java.lang.Long.parseLong(Long.java:824)
[error] 	at scala.collection.immutable.StringLike.toLong(StringLike.scala:309)
[error] 	at scala.collection.immutable.StringLike.toLong$(StringLike.scala:309)
[error] 	at scala.collection.immutable.StringOps.toLong(StringOps.scala:33)
[error] 	at sbt.internal.CrossJava$.$anonfun$parseJavaVersion$2(CrossJava.scala:34)
[error] 	at sbt.internal.CrossJava$.$anonfun$parseJavaVersion$2$adapted(CrossJava.scala:34)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:941)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error] 	at sbt.internal.CrossJava$.splitDot$1(CrossJava.scala:34)
[error] 	at sbt.internal.CrossJava$.parseJavaVersion(CrossJava.scala:43)
[error] 	at sbt.JavaVersion$.apply(JavaVersion.scala:43)
[error] 	at sbt.internal.CrossJava$.$anonfun$expandJavaHomes$1(CrossJava.scala:490)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:941)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error] 	at sbt.internal.CrossJava$.expandJavaHomes(CrossJava.scala:489)
[error] 	at sbt.Defaults$.$anonfun$globalJvmCore$8(Defaults.scala:192)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:223)
[error] 	at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:166)
[error] 	at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
[error] 	at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:99)
[error] 	at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:835)
[error] java.lang.NumberFormatException: For input string: "0-rc12"
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? l
[debug] > Exec(early(addDefaultCommands), None, None)
[debug] > Exec(addDefaultCommands, None, None)
[debug] > Exec(early(initialize), None, None)
[debug] > Exec(initialize, None, None)
[debug] > Exec(boot, None, None)
[debug] > Exec(writeSbtVersion, None, None)
[warn] No sbt.version set in project/build.properties, base directory: /home/miuler/123
[debug] > Exec(reload, None, None)
[debug] > Exec(sbtStashOnFailure, None, None)
[debug] > Exec(onFailure loadFailed, None, None)
[debug] > Exec(loadp, None, None)
[debug] Load.defaultLoad until apply took 309.864484ms
[debug]     Load.loadUnit: plugins took 64.141311ms
[debug]     Load.loadUnit: defsScala took 0.250601ms
[debug] [Loading] Scanning directory /home/miuler/123
[debug] [Loading] Found non-root projects 
[debug] [Loading] Done in /home/miuler/123, returning: ()
[debug] deducing auto plugins based on known facts Set(Atom(sbt.plugins.CorePlugin)) and clauses Clauses(List(Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.IvyPlugin))), Clause(Atom(sbt.ScriptedPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.SbtPlugin),Set(Atom(sbt.ScriptedPlugin))), Clause(Atom(sbt.plugins.SemanticdbPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.JUnitXmlReportPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.CorePlugin),Set(Atom(sbt.plugins.IvyPlugin))), Clause(Atom(sbt.plugins.IvyPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.SemanticdbPlugin))), Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.JUnitXmlReportPlugin))), Clause(Atom(sbt.plugins.CorePlugin),Set(Atom(sbt.plugins.Giter8TemplatePlugin)))))
[debug]   :: deduced result: Matched(sbt.plugins.CorePlugin,sbt.plugins.Giter8TemplatePlugin,sbt.plugins.IvyPlugin,sbt.plugins.JvmPlugin,sbt.plugins.JUnitXmlReportPlugin,sbt.plugins.SemanticdbPlugin)
[debug] Plugins.deducer#function took 20.46099 ms
[debug]         Load.resolveProject(root-123) took 263.959641ms
[debug]       Load.loadTransitive: finalizeProject2(Project(id root-123, base: /home/miuler/123, plugins: List(<none>))) took 293.515871ms
[debug] [Loading] Done in /home/miuler/123, returning: (root-123)
[debug]     Load.loadUnit: loadedProjectsRaw took 314.73582ms
[debug]     Load.loadUnit: cleanEvalClasses took 0.252833ms
[debug]   Load.loadUnit(file:/home/miuler/123/, ...) took 385.232253ms
[debug] Load.apply: load took 503.727439ms
[debug] Load.apply: resolveProjects took 5.932167ms
[debug] Load.apply: finalTransforms took 60.00071ms
[debug] Load.apply: config.delegates took 9.270631ms
[error] java.lang.NumberFormatException: For input string: "0-rc12"
[error] 	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
[error] 	at java.base/java.lang.Long.parseLong(Long.java:699)
[error] 	at java.base/java.lang.Long.parseLong(Long.java:824)
[error] 	at scala.collection.immutable.StringLike.toLong(StringLike.scala:309)
[error] 	at scala.collection.immutable.StringLike.toLong$(StringLike.scala:309)
[error] 	at scala.collection.immutable.StringOps.toLong(StringOps.scala:33)
[error] 	at sbt.internal.CrossJava$.$anonfun$parseJavaVersion$2(CrossJava.scala:34)
[error] 	at sbt.internal.CrossJava$.$anonfun$parseJavaVersion$2$adapted(CrossJava.scala:34)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:941)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error] 	at sbt.internal.CrossJava$.splitDot$1(CrossJava.scala:34)
[error] 	at sbt.internal.CrossJava$.parseJavaVersion(CrossJava.scala:43)
[error] 	at sbt.JavaVersion$.apply(JavaVersion.scala:43)
[error] 	at sbt.internal.CrossJava$.$anonfun$expandJavaHomes$1(CrossJava.scala:490)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:941)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error] 	at sbt.internal.CrossJava$.expandJavaHomes(CrossJava.scala:489)
[error] 	at sbt.Defaults$.$anonfun$globalJvmCore$8(Defaults.scala:192)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:223)
[error] 	at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:166)
[error] 	at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
[error] 	at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:99)
[error] 	at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:835)
[error] java.lang.NumberFormatException: For input string: "0-rc12"
[error] Use 'last' for the full log.
[debug] > Exec(loadFailed, None, None)
[debug] > Exec(last, None, None)
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? i
```

**Comment by eed3si9n** [comment]
@Miuler Thanks for the report. Looks like it's failing to parse JDK version out of some directory names.
Do you have a JDK installed that contains "0-rc12"?

**Comment by Miuler** [comment]
I've tried it with the following java versions:

8.0.212-zulu
11.0.2-zulu
11.0.3-zulu
12.0.1-zulu

**Comment by eed3si9n** [comment]
Do you have anything under `/usr/java` or `/usr/lib/jvm`?

**Comment by felixbr** [comment]
I have the same issue on OSX using the GraalVM RC-16 (installed via [sdkman.io](https://sdkman.io)).

To reproduce you can use sdkman like this: `sdk install java 1.0.0-rc-16-grl`
After uninstalling that version the problem went away for me.

I think it's generally not a good idea to expect versions always to be completely numeric.

**Comment by eed3si9n** [comment]
I think this is actually caused by https://github.com/sbt/sbt/pull/4659 which I introduced non-numeric tags into the version string to support SDKMAN. Minimum failing test is as follows:

```scala
  test("SDKMAN version can round trip") {
    assert(
      CrossJava.parseJavaVersion(
        CrossJava
          .parseSdkmanString("1.0.0-rc-14-grl")
          .get
          .toString
      ) == JavaVersion(
        Vector(1L, 0L, 0L),
        Vector("rc14"),
        Some("graalvm")
      )
    )
  }
```
