### ISSUE TITLE
java.nio.file.NoSuchFileException: /tmp/swoval-jni/16934016062546041395-libswoval-files0.so

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#4741]
This was reported originally by @adriaanm in https://github.com/scala/community-builds/issues/918#issuecomment-496830679

## steps

scala-swing on Linux using JDK 11.
I think Dbuild loads the build, and then tries to extract the dependency graph.

## problem

https://scala-ci.typesafe.com/view/scala-2.11.x/job/scala-2.11.x-jdk11-integrate-community-build/60/consoleFull

```
[scala-swing] Using Scala 2.11.12-bin-efd31ff during extraction.
[scala-swing] Using sbt version: 1.3.0-RC1
[scala-swing:error] OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
[scala-swing:error] Exception in thread "sbt-load-global-instance" java.lang.ExceptionInInitializerError
[scala-swing:error] 	at com.swoval.files.DirectoryListers.init(DirectoryListers.java:29)
[scala-swing:error] 	at com.swoval.files.FileTreeViews.<clinit>(FileTreeViews.java:21)
[scala-swing:error] 	at sbt.nio.file.FileTreeView$DefaultFileTreeView$.<init>(FileTreeView.scala:44)
[scala-swing:error] 	at sbt.nio.file.FileTreeView$DefaultFileTreeView$.<clinit>(FileTreeView.scala)
[scala-swing:error] 	at sbt.nio.file.FileTreeView$.<init>(FileTreeView.scala:82)
[scala-swing:error] 	at sbt.nio.file.FileTreeView$.<clinit>(FileTreeView.scala)
[scala-swing:error] 	at sbt.io.Path$.<init>(Path.scala:318)
[scala-swing:error] 	at sbt.io.Path$.<clinit>(Path.scala)
[scala-swing:error] 	at sbt.internal.parser.SbtParser$.<init>(SbtParser.scala:45)
[scala-swing:error] 	at sbt.internal.parser.SbtParser$.<clinit>(SbtParser.scala)
[scala-swing:error] 	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
[scala-swing:error] 	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1042)
[scala-swing:error] 	at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
[scala-swing:error] 	at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:186)
[scala-swing:error] 	at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1105)
[scala-swing:error] 	at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1086)
[scala-swing:error] 	at java.base/java.lang.reflect.Field.get(Field.java:418)
[scala-swing:error] 	at sbt.xMain$$anon$1.run(Main.scala:51)
[scala-swing:error] Caused by: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /tmp/swoval-jni/16934016062546041395-libswoval-files0.so
[scala-swing:error] 	at com.swoval.files.NativeDirectoryLister.<clinit>(NativeDirectoryLister.java:34)
[scala-swing:error] 	... 18 more
[scala-swing:error] Caused by: java.nio.file.NoSuchFileException: /tmp/swoval-jni/16934016062546041395-libswoval-files0.so
[scala-swing:error] 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
[scala-swing:error] 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[scala-swing:error] 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
[scala-swing:error] 	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:215)
[scala-swing:error] 	at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
[scala-swing:error] 	at java.base/java.nio.file.Files.createFile(Files.java:647)
[scala-swing:error] 	at java.base/java.nio.file.TempFileHelper.create(TempFileHelper.java:137)
[scala-swing:error] 	at java.base/java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:160)
[scala-swing:error] 	at java.base/java.nio.file.Files.createTempFile(Files.java:867)
[scala-swing:error] 	at com.swoval.runtime.NativeLoader.loadPackaged(NativeLoader.java:117)
[scala-swing:error] 	at com.swoval.runtime.NativeLoader.loadPackaged(NativeLoader.java:169)
[scala-swing:error] 	at com.swoval.files.NativeDirectoryLister.<clinit>(NativeDirectoryLister.java:32)
[scala-swing:error] 	... 18 more
[scala-swing] [error] java.lang.NoClassDefFoundError: Could not initialize class sbt.io.Path$
[scala-swing] [error] 	at sbt.internal.CommandStrings$.sbtRCs(CommandStrings.scala:341)
[scala-swing] [error] 	at sbt.BuiltinCommands$.$anonfun$initialize$1(Main.scala:476)
[scala-swing] [error] 	at sbt.Command$.$anonfun$command$2(Command.scala:93)
[scala-swing] [error] 	at sbt.Command$.process(Command.scala:183)
[scala-swing] [error] 	at sbt.MainLoop$.$anonfun$processCommand$1(MainLoop.scala:150)
[scala-swing] [error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:162)
[scala-swing] [error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:150)
[scala-swing] [error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:138)
[scala-swing] [error] 	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:269)
[scala-swing] [error] 	at sbt.State$StateOpsImpl$.process$extension(State.scala:273)
[scala-swing] [error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:138)
[scala-swing] [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[scala-swing] [error] 	at sbt.MainLoop$.next(MainLoop.scala:138)
[scala-swing] [error] 	at sbt.MainLoop$.run(MainLoop.scala:131)
[scala-swing] [error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:109)
[scala-swing] [error] 	at sbt.io.Using.apply(Using.scala:27)
[scala-swing] [error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:103)
[scala-swing] [error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:58)
[scala-swing] [error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:43)
[scala-swing] [error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:34)
[scala-swing] [error] 	at sbt.StandardMain$.runManaged(Main.scala:173)
[scala-swing] [error] 	at sbt.xMainImpl$.run(Main.scala:126)
[scala-swing] [error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[scala-swing] [error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[scala-swing] [error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[scala-swing] [error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[scala-swing] [error] 	at sbt.xMain.run(Main.scala:55)
[scala-swing] [error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[scala-swing] [error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[scala-swing] [error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[scala-swing] [error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[scala-swing] [error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[scala-swing] [error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[scala-swing] [error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[scala-swing] [error] 	at xsbt.boot.Boot$.main(Boot.scala:17)
[scala-swing] [error] 	at xsbt.boot.Boot.main(Boot.scala)
[scala-swing] [error] java.lang.NoClassDefFoundError: Could not initialize class sbt.io.Path$
[scala-swing] [error] Use 'last' for the full log.
[scala-swing:error] java.lang.NoClassDefFoundError: Could not initialize class sbt.nio.file.FileTreeView$
[scala-swing:error] 	at sbt.io.IO$.$anonfun$delete$2(IO.scala:583)
[scala-swing:error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[scala-swing:error] 	at sbt.internal.io.Retry$.liftedTree2$1(Retry.scala:38)
[scala-swing:error] 	at sbt.internal.io.Retry$.impl$1(Retry.scala:38)
[scala-swing:error] 	at sbt.internal.io.Retry$.apply(Retry.scala:52)
[scala-swing:error] 	at sbt.internal.io.Retry$.apply(Retry.scala:24)
[scala-swing:error] 	at sbt.io.IO$.delete(IO.scala:581)
[scala-swing:error] 	at sbt.internal.AbstractBackgroundJobService.shutdown(DefaultBackgroundJobService.scala:153)
[scala-swing:error] 	at sbt.StandardMain$.runManaged(Main.scala:178)
[scala-swing:error] 	at sbt.xMainImpl$.run(Main.scala:126)
[scala-swing:error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[scala-swing:error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[scala-swing:error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[scala-swing:error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[scala-swing:error] 	at sbt.xMain.run(Main.scala:55)
[scala-swing:error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[scala-swing:error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[scala-swing:error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[scala-swing:error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[scala-swing:error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[scala-swing:error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[scala-swing:error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[scala-swing:error] 	at xsbt.boot.Boot$.main(Boot.scala:17)
[scala-swing:error] 	at xsbt.boot.Boot.main(Boot.scala)
[scala-swing] Error during sbt execution: java.lang.NoClassDefFoundError: Could not initialize class sbt.nio.file.FileTreeView$
[scala-swing:error] java.lang.RuntimeException: 
[scala-swing:error] 	at scala.sys.package$.error(package.scala:27)
[scala-swing:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner.com$typesafe$dbuild$support$sbt$SbtRunner$$processCommand(SbtRunner.scala:94)
[scala-swing:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner$$anonfun$run$1$$anonfun$apply$2$$anonfun$apply$3.apply(SbtRunner.scala:75)
[scala-swing:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner$$anonfun$run$1$$anonfun$apply$2$$anonfun$apply$3.apply(SbtRunner.scala:75)
[scala-swing:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner$$anonfun$run$1.apply(SbtRunner.scala:75)
[scala-swing:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner$$anonfun$run$1.apply(SbtRunner.scala:66)
[scala-swing:error] 	at sbt.IO$.withTemporaryFile(IO.scala:389)
[scala-swing:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner.run(SbtRunner.scala:66)
[scala-swing:error] 	at com.typesafe.dbuild.support.sbt.SbtExtractor$.extractMetaData(DependencyExtractor.scala:107)
[scala-swing:error] 	at com.typesafe.dbuild.support.sbt.SbtBuildSystem.extractDependencies(SbtBuildSystem.scala:85)
[scala-swing:error] 	at com.typesafe.dbuild.support.sbt.SbtBuildSystem.extractDependencies(SbtBuildSystem.scala:22)
```

**Comment by eed3si9n** [comment]
The stack trace looks scary but it seems to be happening as sbt is trying to clean after itself.

```
[scala-swing:error] 	at sbt.io.IO$.delete(IO.scala:581)
[scala-swing:error] 	at sbt.internal.AbstractBackgroundJobService.shutdown(DefaultBackgroundJobService.scala:153)
[scala-swing:error] 	at sbt.StandardMain$.runManaged(Main.scala:178)
```

One thing we probably should do is not initialize `backgroundJobService` if it's never been used, only to call `shutdown()`.

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt/pull/4747?
