### ISSUE TITLE
ClassCastException may be thrown with low probability from File Stamp Cache

### ISSUE THREAD

**Issue by pshirshov** [sbt/sbt#4749]
JDK11, sbt 1.3.0-RC1

```
[error] java.lang.ClassCastException: class java.util.HashMap$Node cannot be cast to class java.util.HashMap$TreeNode (java.util.HashMap$Node and java.util.HashMap$TreeNode are in module java.base of loader 'bootstrap')
[error] 	at java.base/java.util.HashMap$TreeNode.moveRootToFront(HashMap.java:1882)
[error] 	at java.base/java.util.HashMap$TreeNode.treeify(HashMap.java:1998)
[error] 	at java.base/java.util.HashMap.treeifyBin(HashMap.java:767)
[error] 	at java.base/java.util.HashMap.putVal(HashMap.java:639)
[error] 	at java.base/java.util.HashMap.put(HashMap.java:607)
[error] 	at sbt.nio.FileStamp$Cache.put(FileStamp.scala:250)
[error] 	at sbt.Defaults$.$anonfun$compileTask$2(Defaults.scala:1622)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:941)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at sbt.Defaults$.$anonfun$compileTask$1(Defaults.scala:1620)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:270)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:279)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:270)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
```

I didn't look inside though this looks like a concurrency issue. Should be fixed by a lock or ConcurrentHashMap

**Comment by eatkins** [comment]
Thanks for the report. I actually already switched to a ConcurrentHashMap in https://github.com/sbt/sbt/pull/4742/commits/dcccd17fd2a324093c392dcabc53d723a95cad64
