### ISSUE TITLE
[1.3.0-M5] test hangs

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#4774]
## steps

Community Build hang after 15 min of unresponsiveness.
First it was https://github.com/Log4s/log4s, and then https://github.com/monix/minitest.

## problem

```
[log4s] [info] Done compiling.
[log4s] [info] Done compiling.
[log4s] [info] Compiling 6 Scala sources to /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.16/project-builds/log4s-b5557ad4511d0cadf4698914c60cf7ba871b6519/core/jvm/target/scala-2.12/test-classes ...
[log4s] ** COMMUNITY BUILD LINE COUNT: 394
[log4s] [info] Done compiling.
Build timed out (after 15 minutes). Marking the build as aborted.
Build was aborted
...
[minitest:error] java.lang.LinkageError: loader constraint violation: when resolving method "minitest.runner.Task$$anon$1.<init>(Lminitest/runner/Task;Lminitest/api/Result;J)V" the class loader (instance of sbt/internal/LayeredClassLoader) of the current class, minitest/runner/Task, and the class loader (instance of sbt/internal/LayeredClassLoader) for the method's defining class, minitest/runner/Task$$anon$1, have different Class objects for the type minitest/runner/Task used in the signature
[minitest:error] at minitest.runner.Task.event(Task.scala:91)
[minitest:error] at minitest.runner.Task.$anonfun$execute$1(Task.scala:62)
[minitest:error] at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
[minitest:error] at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
[minitest:error] at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[minitest:error] at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[minitest:error] at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[minitest:error] at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[minitest:error] at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[minitest:error] at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Build timed out (after 15 minutes). Marking the build as aborted.
Build was aborted
```

## expectation

On sbt 1.3.0-RC1 the test fails, but it finishes quickly.

Ref https://github.com/sbt/sbt/pull/4769

**Comment by eed3si9n** [comment]
Fixed in #4780
