### ISSUE TITLE
[1.3.0-M5] Fails when running tests multiple times

### ISSUE THREAD

**Issue by regadas** [sbt/sbt#4778]
## steps
While trying this new version in [spotify/scio](http://github.com/spotify/scio) I was running into this error when running tests multiple times in the same sub project.

## problem

```
[info]   java.lang.IllegalArgumentException: interface com.spotify.scio.options.ScioOptions is not visibl
e from class loader
[info]   at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:581)
[info]   at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557)
[info]   at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230)
[info]   at java.lang.reflect.WeakCache.get(WeakCache.java:127)
[info]   at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419)
[info]   at java.lang.reflect.Proxy.getProxyClass(Proxy.java:371)
[info]   at org.apache.beam.sdk.options.PipelineOptionsFactory$Cache.validateWellFormed(PipelineOptionsFa
ctory.java:1895)
[info]   at org.apache.beam.sdk.options.ProxyInvocationHandler.as(ProxyInvocationHandler.java:219)
[info]   at org.apache.beam.sdk.options.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:140)
[info]   at com.sun.proxy.$Proxy73.as(Unknown Source)
```

## expectation

There has been no problem with sbt 1.2.8

**Comment by eed3si9n** [comment]
Yea. M5 seems to be DOA.

**Comment by eatkins** [comment]
This is fixed in https://github.com/sbt/sbt/pull/4780.
