### ISSUE TITLE
ClassNotFoundException during the termination of a test

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#4789]
## steps

https://github.com/sbt/sbt/tree/fd0f078c739ea2144b5829aa6c0c58da30978b78/sbt/src/sbt-test/tests/scala-instance-classloader

```scala
package akka.actor

import org.junit._

class BadTest {

  @Test
  def testCpIssue(): Unit = {
    val system = ActorSystem()
    def evilGetThreadExectionContextName =
      system.asInstanceOf[ActorSystemImpl].internalCallingThreadExecutionContext.getClass.getName
    system.terminate()
    val expected = "scala.concurrent.Future$InternalCallbackExecutor$"
    Assert.assertEquals("Failed to grab appropriate Akka name", expected, evilGetThreadExectionContextName)
  }
}
```

## problem

```
[error] Uncaught error from thread [default-akka.actor.default-dispatcher-6]: akka/actor/dungeon/FaultHandling$$anonfun$handleNonFatalOrInterruptedException$1, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[default]
[error] java.lang.NoClassDefFoundError: akka/actor/dungeon/FaultHandling$$anonfun$handleNonFatalOrInterruptedException$1
[error] 	at akka.actor.dungeon.FaultHandling.handleNonFatalOrInterruptedException(FaultHandling.scala:298)
[error] 	at akka.actor.dungeon.FaultHandling.handleNonFatalOrInterruptedException$(FaultHandling.scala:298)
[error] 	at akka.actor.ActorCell.handleNonFatalOrInterruptedException(ActorCell.scala:431)
[error] 	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:533)
[error] 	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:545)
[error] 	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:283)
[error] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:261)
[error] 	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
[error] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
[error] 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[error] 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[error] 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[error] 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] Caused by: java.lang.ClassNotFoundException: akka.actor.dungeon.FaultHandling$$anonfun$handleNonFatalOrInterruptedException$1
[error] 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[error] 	... 13 more
```

## expectation

No errors?

**Comment by eed3si9n** [comment]
This happens when the test code keeps running the thread after sbt closes the ClassLoader.

In this particular case, the fix https://github.com/sbt/sbt/pull/4784 was to wait for the Actor system to shutdown for 5 seconds.

```diff
-    system.terminate()
+    Await.result(system.terminate(), 5.seconds)
```

**Comment by eed3si9n** [comment]
https://github.com/sbt/sbt/pull/4786 adds a backward compatible mode `-Dsbt.classloader.close=false`.
