### ISSUE TITLE
[sbt 1.3.0-RC2] Cannot read user classes from JMX registry with openjdk11

### ISSUE THREAD

**Issue by xerial** [sbt/sbt#4795]
## steps
sbt version: *1.3.0-RC2*

- Use openjdk11
- Checkout wvlet/airframe
- Run a test: https://travis-ci.org/wvlet/airframe/jobs/543948581#L567
```
$ ./sbt
sbt:airframe-root> ; ++ 2.13.0; logJVM/testOnly *LoggerJMXTest

[info] - should be registered *** FAILED ***
[info]   javax.management.RuntimeErrorException: java.lang.NoClassDefFoundError: wvlet/log/LogLevel$
[info]   at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.rethrow(DefaultMBeanServerInterceptor.java:831)
[info]   at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.rethrowMaybeMBeanException(DefaultMBeanServerInterceptor.java:842)
[info]   at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:645)
[info]   at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678)
[info]   at wvlet.log.LoggerJMXTest.$anonfun$new$2(LoggerJMXTest.scala:33)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   ...
[info]   Cause: java.lang.NoClassDefFoundError: wvlet/log/LogLevel$
[info]   at wvlet.log.Logger.getLogLevelOf$1(Logger.scala:71)
[info]   at wvlet.log.Logger.getLogLevel(Logger.scala:77)
[info]   at wvlet.log.LoggerJMX$.getDefaultLogLevel(LoggerMXBean.scala:35)
[info]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info]   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info]   at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[info]   at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
[info]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info]   ...
[info]   Cause: java.lang.ClassNotFoundException: wvlet.log.LogLevel$
[info]   at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
[info]   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
[info]   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[info]   at wvlet.log.Logger.getLogLevelOf$1(Logger.scala:71)
[info]   at wvlet.log.Logger.getLogLevel(Logger.scala:77)
[info]   at wvlet.log.LoggerJMX$.getDefaultLogLevel(LoggerMXBean.scala:35)
[info]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info]   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info]   at java.base/java.lang.reflect.Method.invoke(Method.java:566)

```

- Corresponding code: https://github.com/wvlet/airframe/blob/962d6c2dd1d1acbf9d59a792701aa62b935d6226/airframe-log/jvm/src/test/scala/wvlet/log/LoggerJMXTest.scala#L33

## problem

- The same code worked before in sbt 1.3.0-RC1 with openjdk11

## expectation

- Fixing the classpass or the class loader to be compatible with openjdk11's behavior

**Comment by eatkins** [comment]
I can't reproduce this on mac or linux:
```
ethanatkins@Ethans-MacBook-ProZ:~/work/oss/sbt/community/wvlet/airframe$ java -version; sbt -Dsbt.version=1.3.0-RC2 ";++2.13.0; logJVM/testOnly *LoggerJMXTest"                                                                                                                           
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
[info] Loading settings for project global-plugins from global.sbt ...
[info] Loading global plugins from /Users/ethanatkins/.sbt/1.0/plugins
[info] Loading settings for project airframe-build from plugin.sbt ...
[info] Loading project definition from /Users/ethanatkins/work/oss/sbt/community/wvlet/airframe/project
[info] Loading settings for project root from build.sbt ...
[info] Resolving key references (36333 settings) ...
[info] Set current project to airframe-root (in build file:/Users/ethanatkins/work/oss/sbt/community/wvlet/airframe/)
[info] Setting Scala version to 2.13.0 on 34 projects.
[info] Excluded 7 projects, run ++ 2.13.0 -v for more details.
[info] Reapplying settings...
[info] Set current project to airframe-root (in build file:/Users/ethanatkins/work/oss/sbt/community/wvlet/airframe/)
[info] LoggerJMXTest:
[info] LoggerJXM
[info] - should be registered
[info] - should support setting log levels through JMX
[info] Run completed in 437 milliseconds.
[info] Total number of tests run: 2
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 2, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 3 s, completed Jun 10, 2019, 3:54:57 PM
```

**Comment by xerial** [comment]
It seems there was some issue at Travis CI. It's working properly now. Let me close this. Thank you for your time for checking!

**Comment by xerial** [comment]
@eatkins This issue happens sporadically. After running the same command multiple times, this issue happens. 

```
leo@TD-0504:~/work/git/airframe> java -version                                                                   [0:03:46 Jun 11 2019]
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
leo@TD-0504:~/work/git/airframe> ./sbt                                                                           [0:03:49 Jun 11 2019]
[info] Loading settings for project global-plugins from idea.sbt,plugins.sbt ...
[info] Loading global plugins from /Users/leo/.sbt/1.0/plugins
[info] Loading settings for project airframe-build from plugin.sbt ...
[info] Loading project definition from /Users/leo/work/git/airframe/project
[info] Loading settings for project root from build.sbt ...
[info] Resolving key references (36298 settings) ...
[info] Set current project to airframe-root (in build file:/Users/leo/work/git/airframe/)
[info] Welcome to sbt 1.3.0-RC2.
[info] Here are some highlights of this release:
[info]   - Coursier: new default library management using https://get-coursier.io
[info]   - Super shell: displays actively running tasks
[info]   - Turbo mode: makes `test` and `run` faster in interactive sessions. Try it by running `set ThisBuild / turbo := true`.
[info] See https://www.lightbend.com/blog/sbt-1.3.0-release for full release notes.
[info] Hide the banner for this release by running `skipBanner`.
[info] sbt server started at local:///Users/leo/.sbt/1.0/server/eda4f13789b4b13dc0aa/sock
sbt:airframe-root> ;++ 2.13.0; jmx/test
[info] Setting Scala version to 2.13.0 on 34 projects.
[info] Excluded 7 projects, run ++ 2.13.0 -v for more details.
[info] Reapplying settings...
[info] Set current project to airframe-root (in build file:/Users/leo/work/git/airframe/)
Jun 12, 2019 12:04:32 AM wvlet.log.Logger log
INFO: Started JMX agent at localhost:55498
[info] JMXRegistryTest:
[info] JMXRegistry
[info] - should register a new mbean
[info] - should support class field
[info] - should handle nested JMX MBean
[info] - should avoid double registration
[info] - should support complex trait name
[info] JMXAgentTest:
[info] JMXAgent
[info] - should find jmx registry
[info] Run completed in 672 milliseconds.
[info] Total number of tests run: 6
[info] Suites: completed 2, aborted 0
[info] Tests: succeeded 6, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 3 s, completed Jun 12, 2019, 12:04:32 AM
sbt:airframe-root> jmx/test
[info] JMXRegistryTest:
[info] wvlet.airframe.jmx.JMXRegistryTest *** ABORTED ***
[info]   java.lang.NoClassDefFoundError: wvlet/log/LogLevel$
[info]   at wvlet.log.LogRecord$.apply(LogRecord.scala:32)
[info]   at wvlet.log.LogFormatter.format(LogFormat.scala:32)
[info]   at wvlet.log.LogFormatter.format$(LogFormat.scala:29)
[info]   at wvlet.log.LogFormatter$SourceCodeLogFormatter$.format(LogFormat.scala:143)
[info]   at wvlet.log.ConsoleLogHandler.publish(Handler.scala:15)
[info]   at java.logging/java.util.logging.Logger.log(Logger.java:979)
[info]   at wvlet.log.Logger.log(Logger.scala:144)
[info]   at wvlet.log.Logger.log(Logger.scala:148)
[info]   at wvlet.airframe.jmx.JMXUtil$.startAndGetAgentURL(JMXUtil.scala:107)
[info]   at wvlet.airframe.jmx.JMXAgent.<init>(JMXAgent.scala:55)
[info]   ...
[info]   Cause: java.lang.ClassNotFoundException: wvlet.log.LogLevel$
[info]   at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
[info]   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
[info]   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[info]   at wvlet.log.LogRecord$.apply(LogRecord.scala:32)
[info]   at wvlet.log.LogFormatter.format(LogFormat.scala:32)
[info]   at wvlet.log.LogFormatter.format$(LogFormat.scala:29)
[info]   at wvlet.log.LogFormatter$SourceCodeLogFormatter$.format(LogFormat.scala:143)
[info]   at wvlet.log.ConsoleLogHandler.publish(Handler.scala:15)
[info]   at java.logging/java.util.logging.Logger.log(Logger.java:979)
[info]   at wvlet.log.Logger.log(Logger.scala:144)
[info]   ...
[info] JMXAgentTest:
[info] JMXAgent
[info] - should find jmx registry
[error] Test suite wvlet.airframe.jmx.JMXRegistryTest failed with java.lang.NoClassDefFoundError: wvlet/log/LogLevel$.
[error] This may be due to the ClassLoaderLayeringStrategy (Flat) used by your task.
[error] To improve performance and reduce memory, sbt attempts to cache the class loaders used to load the project dependencies.
[error] The project class files are loaded in a separate class loader that is created for each test run.
[error] The test class loader accesses the project dependency classes using the cached project dependency classloader.
[error] With this approach, class loading may fail under the following conditions:
[error]
[error]  * Dependencies use reflection to access classes in your project's classpath.
[error]    Java serialization/deserialization may cause this.
[error]  * An open package is accessed across layers. If the project's classes access or extend
[error]    jvm package private classes defined in a project dependency, it may cause an IllegalAccessError
[error]    because the jvm enforces package private at the classloader level.
[error]
[error] These issues, along with others that were not enumerated above, may be resolved by changing the class loader layering strategy.
[error] The Flat and ScalaLibrary strategies bundle the full project classpath in the same class loader.
[error] To use one of these strategies, set the  ClassLoaderLayeringStrategy key
[error] in your configuration, for example:
[error]
[error] set jmx / Test / classLoaderLayeringStrategy := ClassLoaderLayeringStrategy.ScalaLibrary
[error] set jmx / Test / classLoaderLayeringStrategy := ClassLoaderLayeringStrategy.Flat
[error]
[error] See ClassLoaderLayeringStrategy.scala for the full list of options.
[info] Run completed in 212 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 1
[info] Tests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0
[info] *** 1 SUITE ABORTED ***
[error] Error during tests:
[error] 	wvlet.airframe.jmx.JMXRegistryTest
[error] (jmx / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 1 s, completed Jun 12, 2019, 12:04:36 AM```

**Comment by xerial** [comment]
It's probably because my code is trying to reuse JMX agent. Similarly to shutdown hook, in the current sbt configuration, we cannot reuse classes registered to JMX agent.

**Comment by xerial** [comment]
I've tested different strategies, but the result has been the same. 

I guess sbt 1.3.0-RC2 cannot load classes defined in other projects.

**Comment by eatkins** [comment]
Hmm. This seems like a bug. It shouldn't work _sometimes_. I'm reopening.

**Comment by eatkins** [comment]
Actually, you were more or less right. I do find that the tests seem to work if I run with `-Dsbt.classloader.close=false`. The only other choice is to fork that project.
