### ISSUE TITLE
[1.3.0-RC2] java.lang.NumberFormatException: For input string: "0-RC2"

### ISSUE THREAD

**Issue by sergiuszkierat** [sbt/sbt#4807]
## steps
sbt version: 1.3.0-RC2
OS: Linux 4.15.0-50-generic #54-Ubuntu

I've forked https://github.com/playframework/play-samples and I've tried to run `play-scala-starter-example` with updated sbt. You can find it [here](https://github.com/sergiuszkierat/play-samples/tree/2.7.x/play-scala-starter-example)

## problem

```
[15:14:27] skierat ~/D/d/p/p/p/play-scala-starter-example (2.7.x u=) sbt
[info] Loading settings for project global-plugins from idea.sbt ...
[info] Loading global plugins from /home/skierat/.sbt/1.0/plugins
[info] Loading settings for project play-scala-starter-example-build from plugins.sbt ...
[info] Loading project definition from /home/skierat/Documents/dev/projects/priv/play-samples/play-scala-starter-example/project
[info] Loading settings for project root from build.sbt ...
[info] Set current project to play-scala-starter-example (in build file:/home/skierat/Documents/dev/projects/priv/play-samples/play-scala-starter-example/)
[info] Welcome to sbt 1.3.0-RC2.
[info] Here are some highlights of this release:
[info]   - Coursier: new default library management using https://get-coursier.io
[info]   - Super shell: displays actively running tasks
[info]   - Turbo mode: makes `test` and `run` faster in interactive sessions. Try it by running `set ThisBuild / turbo := true`.
[info] See https://www.lightbend.com/blog/sbt-1.3.0-release for full release notes.
[info] Hide the banner for this release by running `skipBanner`.
[info] sbt server started at local:///home/skierat/.sbt/1.0/server/c7eebc01a9065916a17e/sock
[play-scala-starter-example] $ run

--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Enter to stop and go back to the console...)

[error] java.lang.NumberFormatException: For input string: "0-RC2"
[error]         at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[error]         at java.lang.Integer.parseInt(Integer.java:580)
[error]         at java.lang.Integer.parseInt(Integer.java:615)
[error]         at scala.collection.immutable.StringLike.toInt(StringLike.scala:304)
[error]         at scala.collection.immutable.StringLike.toInt$(StringLike.scala:304)
[error]         at scala.collection.immutable.StringOps.toInt(StringOps.scala:33)
[error]         at play.sbt.run.PlayRunCompat.$anonfun$watchContinuously$7(PlayRunCompat.scala:63)
[error]         at play.sbt.run.PlayRunCompat.$anonfun$watchContinuously$7$adapted(PlayRunCompat.scala:63)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
[error]         at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
[error]         at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
[error]         at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:237)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
[error]         at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
[error]         at play.sbt.run.PlayRunCompat.watchContinuously(PlayRunCompat.scala:63)
[error]         at play.sbt.run.PlayRunCompat.watchContinuously$(PlayRunCompat.scala:38)
[error]         at play.sbt.run.PlayRun$.watchContinuously(PlayRun.scala:34)
[error]         at play.sbt.run.PlayRun$.$anonfun$playRunTask$3(PlayRun.scala:113)
[error]         at play.sbt.run.PlayRun$.$anonfun$playRunTask$3$adapted(PlayRun.scala:68)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] (Compile / run) java.lang.NumberFormatException: For input string: "0-RC2"
[error] Total time: 3 s, completed Jun 13, 2019 3:15:47 PM
```

## expectation
no error in the console

## notes
Surprisingly, if I run `curl -I http://localhost:9000`, it will start

```

[error] (Compile / run) java.lang.NumberFormatException: For input string: "0-RC2"
[error] Total time: 3 s, completed Jun 13, 2019 3:15:47 PM


[info] p.a.h.EnabledFilters - Enabled Filters (see <https://www.playframework.com/documentation/latest/Filters>):

    play.filters.csrf.CSRFFilter
    play.filters.headers.SecurityHeadersFilter
    play.filters.hosts.AllowedHostsFilter
    filters.ExampleFilter

[info] play.api.Play - Application started (Dev) (no global state)
```

**Comment by eatkins** [comment]
Thanks for the report! This is a bug in play, however. Please open an issue there.

**Comment by sergiuszkierat** [comment]
@eatkins Thanks for pointing that out to me

Ref : playframework/playframework/issues/9391
