### ISSUE TITLE
Error downloading or parsing org.webjars.npm:dom-serializer:[0,1)

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#4824]
## steps
sbt version: 1.3.0-RC2

## problem

* Take https://github.com/playframework/play-samples/tree/f6519a15096fd7eb49f4f19ae444faade936b479/play-java-jpa-example
* Update to sbt 1.3.0-RC2
* Start `sbt`

```
[error] java.net.URISyntaxException: Illegal character in path at index 64: file://///Users/dnw/.ivy2//local/org.webjars.npm/dom-serializer/[0,1)/ivys/ivy.xml
[error] 	at java.net.URI$Parser.fail(URI.java:2848)
[error] 	at java.net.URI$Parser.checkChars(URI.java:3021)
[error] 	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
[error] 	at java.net.URI$Parser.parse(URI.java:3053)
[error] 	at java.net.URI.<init>(URI.java:588)
[error] 	at lmcoursier.internal.shaded.coursier.credentials.DirectCredentials.autoMatches(DirectCredentials.scala:63)
[error] 	at lmcoursier.internal.shaded.coursier.cache.FileCache.$anonfun$filePerPolicy$2(FileCache.scala:647)
[error] 	at lmcoursier.internal.shaded.coursier.cache.FileCache.$anonfun$filePerPolicy$2$adapted(FileCache.scala:647)
[error] 	at scala.collection.LinearSeqOptimized.find(LinearSeqOptimized.scala:115)
[error] 	at scala.collection.LinearSeqOptimized.find$(LinearSeqOptimized.scala:112)
[error] 	at scala.collection.immutable.List.find(List.scala:89)
[error] 	at lmcoursier.internal.shaded.coursier.cache.FileCache.$anonfun$filePerPolicy$1(FileCache.scala:647)
[error] 	at lmcoursier.internal.shaded.coursier.util.Monad.$anonfun$map$1(Monad.scala:8)
[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$2(Task.scala:11)
[error] 	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (update) java.net.URISyntaxException: Illegal character in path at index 64: file://///Users/dnw/.ivy2//local/org.webjars.npm/dom-serializer/[0,1)/ivys/ivy.xml
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q
```

## expectation

Build loads, unit tests pass.

## notes

Please note that I don't have anything in `Users/dnw/.ivy2//local/org.webjars.npm/dom-serializer`, it's a constructed path/URL.

Also in https://github.com/playframework/play-samples/pull/29 it failed when running `update`, not in loading the build, not sure why:

```
[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.webjars.npm:dom-serializer:[0,1)
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/org/webjars/npm/dom-serializer/%5B0,1)/dom-serializer-%5B0,1).pom
[error]   not found: /home/travis/.ivy2/local/org.webjars.npm/dom-serializer/[0,1)/ivys/ivy.xml
[error]   download error: Caught java.net.URISyntaxException: Illegal character in path at index 87: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.webjars.npm/dom-serializer/[0,1)/ivys/ivy.xml (Illegal character in path at index 87: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.webjars.npm/dom-serializer/[0,1)/ivys/ivy.xml) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.webjars.npm/dom-serializer/[0,1)/ivys/ivy.xml
```

**Comment by eed3si9n** [comment]
Fixed by #4845
