### ISSUE TITLE
Breakage in HOCON loading in Lagom/Akka

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt#4826]
## steps
sbt version: 1.3.0-RC2

* https://github.com/lagom/lagom-samples/pull/71
* Run `test` in couchbase-persistence/couchbase-persistence-scala-sbt

## problem

```
2019-06-15 17:35:33,893 ERROR akka.actor.OneForOneStrategy - play/reference-overrides.conf @ jar:file:/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/com/lightbend/lagom/lagom-persistence-cassandra-core_2.12/1.5.1/lagom-persistence-cassandra-core_2.12-1.5.1.jar!/play/reference-overrides.conf: 66: Configuration key 'keyspace' is set to null but expected STRING
akka.actor.ActorInitializationException: akka://application/system/cassandra-snapshot-store: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:202)
	at akka.actor.ActorCell.create(ActorCell.scala:694)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:545)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:567)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:293)
	at akka.dispatch.Mailbox.run(Mailbox.scala:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at akka.util.Reflect$.instantiate(Reflect.scala:68)
	at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:98)
	at akka.actor.Props.newActor(Props.scala:212)
	at akka.actor.ActorCell.newActor(ActorCell.scala:646)
	at akka.actor.ActorCell.create(ActorCell.scala:672)
	... 7 common frames omitted
Caused by: com.typesafe.config.ConfigException$Null: play/reference-overrides.conf @ jar:file:/home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/com/lightbend/lagom/lagom-persistence-cassandra-core_2.12/1.5.1/lagom-persistence-cassandra-core_2.12-1.5.1.jar!/play/reference-overrides.conf: 66: Configuration key 'keyspace' is set to null but expected STRING
	at com.typesafe.config.impl.SimpleConfig.throwIfNull(SimpleConfig.java:142)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:250)
	at akka.persistence.cassandra.CassandraPluginConfig.<init>(CassandraPluginConfig.scala:33)
	at akka.persistence.cassandra.snapshot.CassandraSnapshotStoreConfig.<init>(CassandraSnapshotStoreConfig.scala:10)
	at akka.persistence.cassandra.snapshot.CassandraSnapshotStore.<init>(CassandraSnapshotStore.scala:35)
	... 16 common frames omitted
```

## expectation

Tests pass

**Comment by eatkins** [comment]
When I run test locally, it fails with both 1.2.8 and 1.3.0-RC2. The failure is different though:
```
[info] HelloServiceSpec:
[info] com.lightbend.lagom.sampleshello.impl.HelloServiceSpec *** ABORTED ***
[info]   com.couchbase.client.core.config.ConfigurationException: Could not open bucket.
[info]   at com.couchbase.client.core.config.DefaultConfigurationProvider$6.call(DefaultConfigurationProvider.java:304)
[info]   at com.couchbase.client.core.config.DefaultConfigurationProvider$6.call(DefaultConfigurationProvider.java:301)
[info]   at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
[info]   at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
[info]   at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
[info]   at rx.internal.operators.OnSubscribeMap$MapSubscriber.onError(OnSubscribeMap.java:88)
[info]   at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
[info]   at rx.internal.operators.OperatorTake$1.onError(OperatorTake.java:66)
[info]   at rx.internal.operators.OperatorMerge$MergeSubscriber.reportError(OperatorMerge.java:266)
[info]   at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:658)
[info]   ...
[info]   Cause: com.couchbase.client.deps.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:8091                                                                                                                                        
[info]   at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
[info]   at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
[info]   at com.couchbase.client.deps.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:225)
[info]   at com.couchbase.client.deps.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:291)
[info]   at com.couchbase.client.deps.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:634)
[info]   at com.couchbase.client.deps.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
[info]   at com.couchbase.client.deps.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
[info]   at com.couchbase.client.deps.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
[info]   at com.couchbase.client.deps.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
[info]   at com.couchbase.client.deps.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[info]   ...
[info]   Cause: java.net.ConnectException: Connection refused
[info]   at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
[info]   at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
[info]   at com.couchbase.client.deps.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:225)
[info]   at com.couchbase.client.deps.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:291)
[info]   at com.couchbase.client.deps.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:634)
[info]   at com.couchbase.client.deps.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
[info]   at com.couchbase.client.deps.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
[info]   at com.couchbase.client.deps.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
[info]   at com.couchbase.client.deps.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
[info]   at com.couchbase.client.deps.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[info]   ...
[info] Run completed in 6 seconds, 567 milliseconds.
[info] Total number of tests run: 2
[info] Suites: completed 1, aborted 1
[info] Tests: succeeded 2, failed 0, canceled 0, ignored 0, pending 0
[info] *** 1 SUITE ABORTED ***
[error] Error during tests:
[error]         com.lightbend.lagom.sampleshello.impl.HelloServiceSpec
[error] (hello-impl / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 19 s, completed Jun 21, 2019 1:23:34 PM
```

**Comment by eatkins** [comment]
It also fails if I set `Test / fork := true`.

**Comment by eed3si9n** [comment]
If it's failing on 1.2.8 and `Test / fork := true`, I am going to remove the 1.3.0 and Regression labeling in the interest of triaging.

**Comment by dwijnand** [comment]
Not so fast: it doesn't fail on 1.2.8 in Travis CI...

https://travis-ci.com/lagom/lagom-samples/jobs/207730145

**Comment by eatkins** [comment]
Why might it work on travis ci but not locally on my mac or linux vm? I don’t doubt there might be a 1.3.0 issue, but there is clearly an issue with this project on 1.2.8 as well.

**Comment by dwijnand** [comment]
Yeah, sorry, guys.

The burden of proof is on lagom-samples, if it fails locally in 1.2.8.
