### ISSUE TITLE
Failed downloads when switching library dependencies

### ISSUE THREAD

**Issue by jxtps** [sbt/sbt#4842]
## Environment
sbt version: 1.2.8
Windows 10
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)

## Problem
1. I create a project that references a library dependency. Things work. 
1. Later I switch out that library dependency for another one. SBT then fails to download the new dependency. 
1. Deleting my .ivy2 cache resolves the issue until I switch back to the first library dependency, at which point I have to delete my .ivy2 cache again. 

## Expectation
Switching library dependencies should not require me to delete the .ivy2 cache. 

The cache contains gigabytes of data that will need to be re-downloaded, taking time & bandwidth. 

## Detailed Steps To Reproduce
`sbt new scala/scala-seed.g8`

Update `build.sbt` to add: 
````
libraryDependencies += "org.nd4j" % "nd4j-cuda-10.1-platform" % "1.0.0-beta4" // - GPU based
````

`sbt compile` <-- succeeds

Update `build.sbt`, remove the previous library dependency and add: 
````
libraryDependencies += "org.nd4j" % "nd4j-native-platform" % "1.0.0-beta4" // - CPU based
````

`sbt compile` fails to fetch dependency: 
````
PS C:\work\test\ivytest> sbt compile
[info] Loading settings for project global-plugins from idea.sbt ...
[info] Loading global plugins from C:\Users\jxtps\.sbt\1.0\plugins
[info] Loading project definition from C:\work\test\ivytest\project
[info] Loading settings for project root from build.sbt ...
[info] Set current project to IvyTest (in build file:/C:/work/test/ivytest/)
[info] Executing in batch mode. For better performance use sbt's shell
[info] Updating ...
[warn]  Detected merged artifact: [FAILED     ] org.bytedeco#mkl-dnn;0.18.1-1.5!mkl-dnn.jar:  (0ms).
[warn] ==== local: tried
[warn] ==== public: tried
[warn]  Detected merged artifact: [FAILED     ] org.bytedeco#openblas;0.3.5-1.5!openblas.jar:  (0ms).
[warn] ==== local-preloaded-ivy: tried
[warn] ==== local: tried
[warn] ==== public: tried
[warn]   C:\Users\jxtps\.sbt\preloaded\org.bytedeco\mkl-dnn\0.18.1-1.5\jars\mkl-dnn-${dependency.platform2}.jar
[warn] ==== local-preloaded: tried
[warn]   https://repo1.maven.org/maven2/org/bytedeco/openblas/0.3.5-1.5/openblas-0.3.5-1.5-${dependency.platform}.jar
[warn]   file:/C:/Users/jxtps/.sbt/preloaded/org/bytedeco/mkl-dnn/0.18.1-1.5/mkl-dnn-0.18.1-1.5-${dependency.platform2}.jar
[warn] ==== local-preloaded-ivy: tried
[warn]   C:\Users\jxtps\.sbt\preloaded\org.bytedeco\openblas\0.3.5-1.5\jars\openblas-${dependency.platform}.jar
[warn] ==== local-preloaded: tried
[warn]   file:/C:/Users/jxtps/.sbt/preloaded/org/bytedeco/openblas/0.3.5-1.5/openblas-0.3.5-1.5-${dependency.platform}.jar
[warn]  Detected merged artifact: [FAILED     ] org.bytedeco#mkl;2019.3-1.5!mkl.jar:  (0ms).
[warn] ==== local: tried
[warn] ==== public: tried
[warn] ==== local-preloaded-ivy: tried
[warn]   C:\Users\jxtps\.sbt\preloaded\org.bytedeco\mkl\2019.3-1.5\jars\mkl-${dependency.platform2}.jar
[warn] ==== local-preloaded: tried
[warn]   file:/C:/Users/jxtps/.sbt/preloaded/org/bytedeco/mkl/2019.3-1.5/mkl-2019.3-1.5-${dependency.platform2}.jar
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::              FAILED DOWNLOADS            ::
[warn]  :: ^ see resolution messages for details  ^ ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.bytedeco#openblas;0.3.5-1.5!openblas.jar
[warn]  :: org.bytedeco#mkl;2019.3-1.5!mkl.jar
[warn]  :: org.bytedeco#mkl-dnn;0.18.1-1.5!mkl-dnn.jar
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[error] sbt.librarymanagement.ResolveException: download failed: org.bytedeco#openblas;0.3.5-1.5!openblas.jar
[error] download failed: org.bytedeco#mkl;2019.3-1.5!mkl.jar
[error] download failed: org.bytedeco#mkl-dnn;0.18.1-1.5!mkl-dnn.jar
[error]         at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:332)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:239)
[error]         at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error]         at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error]         at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error]         at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error]         at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error]         at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error]         at xsbt.boot.Using$.withResource(Using.scala:10)
[error]         at xsbt.boot.Using$.apply(Using.scala:9)
[error]         at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error]         at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error]         at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]         at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]         at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:238)
[error]         at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
[error]         at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:45)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:93)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:106)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:106)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:89)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:120)
[error]         at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2561)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (update) sbt.librarymanagement.ResolveException: download failed: org.bytedeco#openblas;0.3.5-1.5!openblas.jar
[error] download failed: org.bytedeco#mkl;2019.3-1.5!mkl.jar
[error] download failed: org.bytedeco#mkl-dnn;0.18.1-1.5!mkl-dnn.jar
[error] Total time: 2 s, completed Jun 28, 2019 2:03:09 PM
````

Delete .ivy2 cache

`sbt compile` <-- succeeds

Switch back to the first library dependency

`sbt compile` <-- fails to fetch dependency until we delete .ivy2 again

**Comment by eatkins** [comment]
Just out of curiosity, do you need to blow away the ivy cache if you run `reboot full` between changing dependencies?

**Comment by jxtps** [comment]
```
PS C:\work\test\ivytest> sbt "reboot full"
[info] Loading settings for project global-plugins from idea.sbt ...
[info] Loading global plugins from C:\Users\jxtps\.sbt\1.0\plugins
[info] Loading project definition from C:\work\test\ivytest\project
[info] Loading settings for project root from build.sbt ...
[info] Set current project to IvyTest (in build file:/C:/work/test/ivytest/)
[info] Loading settings for project global-plugins from idea.sbt ...
[info] Loading global plugins from C:\Users\jxtps\.sbt\1.0\plugins
[info] Loading project definition from C:\work\test\ivytest\project
[info] Loading settings for project root from build.sbt ...
[info] Set current project to IvyTest (in build file:/C:/work/test/ivytest/)
[info] sbt server started at local:sbt-server-c17d99a3fdb4b4ebe114
sbt:IvyTest>
sbt:IvyTest> compile
[info] Updating ...
[warn]  Detected merged artifact: [FAILED     ] org.bytedeco#cuda;10.1-7.5-1.5!cuda.jar:  (0ms).
[warn] ==== local: tried
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/bytedeco/cuda/10.1-7.5-1.5/cuda-10.1-7.5-1.5-${dependency.platform}.jar
[warn] ==== local-preloaded-ivy: tried
[warn]   C:\Users\jxtps\.sbt\preloaded\org.bytedeco\cuda\10.1-7.5-1.5\jars\cuda-${dependency.platform}.jar
[warn] ==== local-preloaded: tried
[warn]   file:/C:/Users/jxtps/.sbt/preloaded/org/bytedeco/cuda/10.1-7.5-1.5/cuda-10.1-7.5-1.5-${dependency.platform}.jar
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::              FAILED DOWNLOADS            ::
[warn]  :: ^ see resolution messages for details  ^ ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.bytedeco#cuda;10.1-7.5-1.5!cuda.jar
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[error] sbt.librarymanagement.ResolveException: download failed: org.bytedeco#cuda;10.1-7.5-1.5!cuda.jar
[error]         at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:332)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:239)
```
Closing the sbt session and then running `sbt compile` still leads to the same download failure.

**Comment by eatkins** [comment]
Ok, thanks.

**Comment by eed3si9n** [comment]
@jxtps Thanks for the report. We are moving away from Ivy in sbt 1.3.0, so likely we won't attempt to fix the Ivy issue.

**Comment by eed3si9n** [comment]
Preemptively closing this. If the issue still occurs with sbt 1.3.6 let us know.
