### ISSUE TITLE
ClassCastException on 1.3.0-RC2 / java 11

### ISSUE THREAD

**Issue by pshirshov** [sbt/sbt#4846]
From time to time (1 per ~100 runs) I'm getting this stack while compiling 2.13 source:

```
[error] java.lang.ClassCastException: class java.util.HashMap$Node cannot be cast to class java.util.HashMap$TreeNode (java.util.HashMap$Node and java.util.HashMap$TreeNode are in module java.base of loader 'bootstrap')
[error] 	at java.base/java.util.HashMap$TreeNode.moveRootToFront(HashMap.java:1882)
[error] 	at java.base/java.util.HashMap$TreeNode.treeify(HashMap.java:1998)
[error] 	at java.base/java.util.HashMap.treeifyBin(HashMap.java:767)
[error] 	at java.base/java.util.HashMap.putVal(HashMap.java:639)
[error] 	at java.base/java.util.HashMap.put(HashMap.java:607)
[error] 	at sbt.nio.FileStamp$Cache.updateImpl(FileStamp.scala:270)
[error] 	at sbt.nio.FileStamp$Cache.getOrElseUpdate(FileStamp.scala:242)
[error] 	at sbt.nio.Settings$.$anonfun$stamper$2(Settings.scala:362)
[error] 	at sbt.nio.Settings$.$anonfun$fileStamps$2(Settings.scala:323)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:244)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:941)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:244)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:241)
[error] 	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
[error] 	at sbt.nio.Settings$.$anonfun$fileStamps$1(Settings.scala:322)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:270)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:279)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:270)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
```

```
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)
```

**Comment by eatkins** [comment]
That looks like a 1.3.0-RC1 stack trace. The updateImpl method in FileStamp.scala is defined on line 275 in the version of FileStamp.scala that should have been used to build 1.3.0-RC2. The provided stack trace has the error occurring at line 270, which was where it was in 1.3.0-RC1.

**Comment by pshirshov** [comment]
Hm. My bad.
