### ISSUE TITLE
[1.3.0-RC1] [1.3.0-RC2] updateSbtClassifiers broken

### ISSUE THREAD

**Issue by OlegYch** [sbt/sbt#4856]
## steps
sbt version: 1.3.0-RC1 or 1.3.0-RC2

## problem
using eg https://github.com/sbt/zinc/commit/9f09d005f7971a5027dc529ef1d53d144a6a5bd0
executing updateSbtClassifiers returns
```
[error] java.lang.IllegalArgumentException: Cannot add dependency 'com.google.code.gson#gson;2.2.2' to configuration 'default' of module org.scala-sbt#zinc-root$sbt_2.12;1.3.0-M7 because this configuration doesn't exist!
[error]         at org.apache.ivy.core.module.descriptor.DefaultDependencyDescriptor.addDependencyConfiguration(DefaultDependencyDescriptor.java:567)
[error]         at org.apache.ivy.plugins.parser.AbstractModuleDescriptorParser$AbstractParser.parseDepsConfs(AbstractModuleDescriptorParser.java:157)
[error]         at org.apache.ivy.plugins.parser.AbstractModuleDescriptorParser$AbstractParser.parseDepsConfs(AbstractModuleDescriptorParser.java:128)
[error]         at org.apache.ivy.plugins.parser.AbstractModuleDescriptorParser$AbstractParser.parseDepsConfs(AbstractModuleDescriptorParser.java:118)
[error]         at org.apache.ivy.plugins.parser.AbstractModuleDescriptorParser$AbstractParser.parseDepsConfs(AbstractModuleDescriptorParser.java:113)
[error]         at sbt.internal.librarymanagement.CustomXmlParser$CustomParser.parseDepsConfs(CustomXmlParser.scala:36)

[error]         at sbt.internal.librarymanagement.IvySbt$.convertDependency(Ivy.scala:931)
[error]         at sbt.internal.librarymanagement.IvySbt$.$anonfun$addDependencies$1(Ivy.scala:868)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:941)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:237)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
[error]         at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error]         at sbt.internal.librarymanagement.IvySbt$.addDependencies(Ivy.scala:867)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.configureInline(Ivy.scala:294)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.x$7$lzycompute(Ivy.scala:259)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.x$7(Ivy.scala:256)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.moduleDescriptor0$lzycompute(Ivy.scala:256)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.moduleDescriptor0(Ivy.scala:256)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:245)
[error]         at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:210)
[error]         at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:76)[error]         at sbt.internal.librarymanagement.IvySbt$$anon$1.call(Ivy.scala:83)
[error]         at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
[error]         at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
[error]         at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
[error]         at xsbt.boot.Using$.withResource(Using.scala:10)
[error]         at xsbt.boot.Using$.apply(Using.scala:9)
[error]         at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
[error]         at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
[error]         at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]         at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]         at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:83)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:205)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:202)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:244)
[error]         at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:191)
[error]         at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:21)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error]         at sbt.internal.LibraryManagement$.transitiveScratch(LibraryManagement.scala:181)
[error]         at sbt.Classpaths$.$anonfun$sbtClassifiersTasks$13(Defaults.scala:2633)
[error]         at sbt.Classpaths$$anon$4.call(Defaults.scala:2720)
[error]         at sbt.Classpaths$$anon$4.call(Defaults.scala:2712)
[error]         at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
[error]         at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
[error]         at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
[error]         at xsbt.boot.Using$.withResource(Using.scala:10)
[error]         at xsbt.boot.Using$.apply(Using.scala:9)
[error]         at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
[error]         at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
[error]         at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]         at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]         at sbt.Classpaths$.withExcludes(Defaults.scala:2712)
[error]         at sbt.Classpaths$.$anonfun$sbtClassifiersTasks$10(Defaults.scala:2620)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:270)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:279)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:270)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(Unknown Source)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[error]         at java.util.concurrent.FutureTask.run(Unknown Source)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[error]         at java.lang.Thread.run(Unknown Source)
[error] (zincPersist / updateSbtClassifiers) java.lang.IllegalArgumentException: Cannot add dependency 'com.google.code.gson#gson;2.2.2' to configuration 'default' of module org.scala-sbt#zinc-persist$sbt_2.12;1.3.0-M7 because this configuration doesn't exist!
```
this causes intellij import to fail too

## expectation
updateSbtClassifiers downloads sbt libs and sources, intellij import succeeds

## notes
works with 1.2.8 if you remove references to classLoaderLayeringStrategy in zinc build

**Comment by eed3si9n** [comment]
@OlegYch Thanks for the report.
I can't seem to reproduce this, and stacktrace shows Ivy, which sounds suspicious if it's using sbt 1.3.0-RC2.

**Comment by OlegYch** [comment]
@eed3si9n thanks 
you're right it was caused by workaround for this https://github.com/sbt/sbt/issues/3432
works fine after removing it

**Comment by michaelahlers** [comment]
I've encountered this with 1.3.0-RC4.

```
[error] (updateSbtClassifiers) java.lang.IllegalArgumentException: Cannot add dependency 'net.java.dev.jna#jna;5.0.0' to configuration 'default' of module my-package#my-project$sbt_2.12;0.0.0-SNAPSHOT because this configuration doesn't exist!
```

Any work-arounds?
