### ISSUE TITLE
java.lang.IllegalStateException: Tried to extract class loader from closed ReverseLookupClassLoaderHolder

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#4892]
originally reported by @deanwampler

## steps
sbt version: 1.3.0-RC3

https://github.com/lightbend/pipelines-model-serving/tree/586670ce622f1de94c8a8da276fafc107bc7d16c

```
set ThisBuild / turbo := true
~test
```

## problem

```
[error] java.lang.IllegalStateException: Tried to extract class loader from closed ReverseLookupClassLoaderHolder. Try running the `clearCaches` command and re-trying.
[error]   at sbt.internal.ReverseLookupClassLoaderHolder.checkout(LayeredClassLoaders.scala:76)
[error]   at sbt.internal.ClassLoaders$.buildLayers(ClassLoaders.scala:183)
[error]   at sbt.internal.ClassLoaders$.$anonfun$testTask$1(ClassLoaders.scala:48)
[error]   at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]   at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]   at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]   at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
[error]   at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]   at sbt.Execute.work(Execute.scala:289)
[error]   at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
[error]   at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]   at java.lang.Thread.run(Thread.java:748)
[error] (airlineFlightsModelServingPipeline / Test / testLoader) java.lang.IllegalStateException: Tried to extract class loader from closed ReverseLookupClassLoaderHolder. Try running the `clearCaches` command and re-trying.
[error] Total time: 47 s, completed Jul 21, 2019 7:58:44 AM
```

> But using `clearCaches` didn't help within the same session, but when I restarted sbt and then ran `clearCaches` followed by `~test`, it worked fine.

## expectation

works?

## notes

> Note that all this occurred before I removed "avrohugger", but it appears to have gone away for good after I removed "avrohugger".

**Comment by eed3si9n** [comment]
@eatkins and I discussed this today. Potentially this is related to ClassLoader reloading when resource files are changed.

**Comment by eed3si9n** [comment]
Potential workarounds:
- `-Dsbt.classloader.close=false`
- or not use turbo mode

**Comment by eatkins** [comment]
I couldn't clone this repo:
```
 [error]   unauthorized: https://repo.lightbend.com/commercial-releases/com.lightbend.pipelines/sbt-pipelines/scala_2.12/sbt_1.0/1.1.0/ivys/ivy.xml (Bintray)
```
 but I'm hoping that  https://github.com/sbt/sbt/pull/4906 resolves this issue.

**Comment by eatkins** [comment]
I think this is probably fixed but feel free to re-open if I'm wrong.
