### ISSUE TITLE
[1.3.0-RC3] sbt-docker broken

### ISSUE THREAD

**Issue by OlegYch** [sbt/sbt#4909]
## steps
sbt version: 1.3.0-RC3
clone https://github.com/OlegYch/sbt-docker-issue and run `sbt docker`

## problem
```
[error] java.nio.file.FileAlreadyExistsException: /usr/home/ec2-user/sbt-docker-issue/target/docker/0/2/3/4         
[error]         at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:551)                                              
[error]         at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)                          
[error]         at java.nio.file.Files.copy(Files.java:1274)                                                        
[error]         at sbtdocker.staging.CopyFile.copy(SourceFile.scala:31)                                             
[error]         at sbtdocker.staging.CopyFile.$anonfun$stage$1(SourceFile.scala:18)                                 
[error]         at sbtdocker.staging.CopyFile.$anonfun$stage$1$adapted(SourceFile.scala:18)                         
[error]         at scala.Function2.$anonfun$tupled$1(Function2.scala:53)                                            
[error]         at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)                         
[error]         at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)                        
[error]         at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)                               
[error]         at sbtdocker.staging.CopyFile.stage(SourceFile.scala:18)                                            
[error]         at sbtdocker.DockerBuild$.$anonfun$prepareFiles$1(DockerBuild.scala:59)                             
[error]         at sbtdocker.DockerBuild$.$anonfun$prepareFiles$1$adapted(DockerBuild.scala:57)                     
[error]         at scala.collection.immutable.Set$Set1.foreach(Set.scala:97)                                        
[error]         at sbtdocker.DockerBuild$.prepareFiles(DockerBuild.scala:57)                                        
[error]         at sbtdocker.DockerBuild$.apply(DockerBuild.scala:44)                                               
[error]         at sbtdocker.DockerBuild$.apply(DockerBuild.scala:24)                                               
[error]         at sbtdocker.DockerSettings$.$anonfun$baseDockerSettings$1(DockerSettings.scala:17)                 
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)                                           
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)                       
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)                                               
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:280)                                                 
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)                             
[error]         at sbt.Execute.work(Execute.scala:289)                                                              
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:280)                                                 
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)      
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)                                   
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                         
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)                          
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                         
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)                  
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)                  
[error]         at java.lang.Thread.run(Thread.java:748)                                                            
[error] (docker) java.nio.file.FileAlreadyExistsException: /usr/home/ec2-user/sbt-docker-issue/target/docker/0/2/3/4
```

## expectation
creates a docker image if you have docker running or fails trying to connect to it like this
```
[error] java.io.IOException: Cannot run program "docker" (in directory "/usr/home/ec2-user/sbt-docker-issue/target/docker"): error=2, No such file or directory
```

## notes
this is working using sbt 1.3.0-RC2 or below
not sure why it would start failing like this, but there is a related issue here https://github.com/marcuslonnberg/sbt-docker/issues/99

**Comment by eed3si9n** [comment]
Seems to be fixed now.
