### ISSUE TITLE
SBT hangs on launching sbt-launch.jar when called via GNU parallel

### ISSUE THREAD

**Issue by IvanRibakov** [sbt/sbt#4938]
## steps
sbt version: 1.2.8
OS: CentOS 7

1. Create template.spec 
2. Call `sbt packageBin` in `%install` section of template.spec
3. Launch rpmbuild via GNU parallel

## problem

SBT hangs. Running it with debug flag produces following output:
```
+ sbt -d packageBin
[addSbt] arg = '-debug'
[residual] arg = 'packageBin'
[residual] arg = 'packageBin'
[process_args] java_version = '8'
# Executing command line:
java
-Xms1024m
-Xmx1024m
-XX:ReservedCodeCacheSize=128m
-XX:MaxMetaspaceSize=256m
-jar
/usr/share/sbt/bin/sbt-launch.jar
-debug
packageBin

```

## expectation

sbt to continue execution and produce jar

## notes

After aborting stuck rpmbuild and navigating to the build folder I can manually invoke `sbt packageBin` and it executes as expected.

**Comment by IvanRibakov** [comment]
P.S. I tried a simpler `sbt` command and a fresh VM and got slightly more output (but I'm guessing it's because sbt had to fetch scala jar first):

```
+ sbt -d sbtVersion
[addSbt] arg = '-debug'
[residual] arg = 'sbtVersion'
[residual] arg = 'sbtVersion'
[process_args] java_version = '8'
# Executing command line:
java
-Xms1024m
-Xmx1024m
-XX:ReservedCodeCacheSize=128m
-XX:MaxMetaspaceSize=256m
-jar
/usr/share/sbt/bin/sbt-launch.jar
-debug
sbtVersion

Getting org.scala-sbt sbt 1.2.8  (this may take some time)...
downloading https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.2.8/sbt-1.2.8.jar ...
	[SUCCESSFUL ] org.scala-sbt#sbt;1.2.8!sbt.jar (89ms)
downloading https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7.jar ...
	[SUCCESSFUL ] org.scala-lang#scala-library;2.12.7!scala-library.jar (1069ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/main_2.12/1.2.8/main_2.12-1.2.8.jar ...
	[SUCCESSFUL ] org.scala-sbt#main_2.12;1.2.8!main_2.12.jar (386ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/logic_2.12/1.2.8/logic_2.12-1.2.8.jar ...
	[SUCCESSFUL ] org.scala-sbt#logic_2.12;1.2.8!logic_2.12.jar (72ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/actions_2.12/1.2.8/actions_2.12-1.2.8.jar ...
	
...

	[SUCCESSFUL ] org.scala-sbt#util-scripted_2.12;1.2.4!util-scripted_2.12.jar (79ms)
downloading https://repo1.maven.org/maven2/com/github/cb372/scalacache-core_2.12/0.20.0/scalacache-core_2.12-0.20.0.jar ...
	[SUCCESSFUL ] com.github.cb372#scalacache-core_2.12;0.20.0!scalacache-core_2.12.jar (93ms)
downloading https://repo1.maven.org/maven2/com/github/ben-manes/caffeine/caffeine/2.5.6/caffeine-2.5.6.jar ...
	[SUCCESSFUL ] com.github.ben-manes.caffeine#caffeine;2.5.6!caffeine.jar (244ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/ivy/ivy/2.3.0-sbt-cb9cc189e9f3af519f9f102e6c5d446488ff6832/ivy-2.3.0-sbt-cb9cc189e9f3af519f9f102e6c5d446488ff6832.jar ...
	[SUCCESSFUL ] org.scala-sbt.ivy#ivy;2.3.0-sbt-cb9cc189e9f3af519f9f102e6c5d446488ff6832!ivy.jar (249ms)
:: retrieving :: org.scala-sbt#boot-app
	confs: [default]
	80 artifacts copied, 0 already retrieved (28561kB/116ms)
Getting Scala 2.12.7 (for sbt)...
:: retrieving :: org.scala-sbt#boot-scala
	confs: [default]
	5 artifacts copied, 0 already retrieved (19715kB/42ms)
```

Any pointers as to how I can go about debugging this?

**Comment by IvanRibakov** [comment]
**UPDATE** I was able to narrow down the cause of the problem to using GNU parallel to parallelize creation of multiple RPM artifacts.

GNU parallel is being called with following parameters:
```
parallel  -v  --will-cite --load 95% --noswap --halt now,fail=1 --memfree 1G  --keep-order --line-buffer
```

**Comment by eed3si9n** [comment]
When sbt gets completely stuck, it's often Java or JLine related.

What output do you get from running `java -version`?
Also could you try with `-Djline.terminal=none`.

**Comment by IvanRibakov** [comment]
> What output do you get from running java -version?
```
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
```

> Also could you try with `-Djline.terminal=none`

I've tried `-Djline.terminal=none` and `-Djline.terminal=jline.UnsupportedTerminal` but neither had any effect.

**Comment by eatkins** [comment]
Could you obtain a stacktrace with  [jstack](https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/tooldescr016.html) so we can try to figure out where sbt is stuck?

**Comment by IvanRibakov** [comment]
I assume `jstack -F <pid>` is what you are looking for:

```
$ ps -ef | grep java
vagrant   3754  3624 57 18:10 pts/2    00:00:04 java -Xms1024m -Xmx1024m -XX:ReservedCodeCacheSize=128m -XX:MaxMetaspaceSize=256m -jar /usr/share/sbt/bin/sbt-launch.jar -debug -Djline.terminal=none sbtVersion
vagrant   4532 28010  0 18:10 pts/3    00:00:00 grep --color=auto java
$ jstack -F 3754
Attaching to process ID 3754, please wait...
Debugger attached successfully.
Server compiler detected.
JVM version is 25.222-b10
Deadlock Detection:

java.lang.RuntimeException: Unable to deduce type of thread from address 0x00007f150e9f4800 (expected type JavaThread, CompilerThread, ServiceThread, JvmtiAgentThread, or SurrogateLockerThread)
	at sun.jvm.hotspot.runtime.Threads.createJavaThreadWrapper(Threads.java:169)
	at sun.jvm.hotspot.runtime.Threads.first(Threads.java:153)
	at sun.jvm.hotspot.runtime.DeadlockDetector.createThreadTable(DeadlockDetector.java:149)
	at sun.jvm.hotspot.runtime.DeadlockDetector.print(DeadlockDetector.java:56)
	at sun.jvm.hotspot.runtime.DeadlockDetector.print(DeadlockDetector.java:39)
	at sun.jvm.hotspot.tools.StackTrace.run(StackTrace.java:62)
	at sun.jvm.hotspot.tools.StackTrace.run(StackTrace.java:45)
	at sun.jvm.hotspot.tools.JStack.run(JStack.java:66)
	at sun.jvm.hotspot.tools.Tool.startInternal(Tool.java:260)
	at sun.jvm.hotspot.tools.Tool.start(Tool.java:223)
	at sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
	at sun.jvm.hotspot.tools.JStack.main(JStack.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.tools.jstack.JStack.runJStackTool(JStack.java:140)
	at sun.tools.jstack.JStack.main(JStack.java:106)
Caused by: sun.jvm.hotspot.types.WrongTypeException: No suitable match for type of address 0x00007f150e9f4800
	at sun.jvm.hotspot.runtime.InstanceConstructor.newWrongTypeException(InstanceConstructor.java:62)
	at sun.jvm.hotspot.runtime.VirtualConstructor.instantiateWrapperFor(VirtualConstructor.java:80)
	at sun.jvm.hotspot.runtime.Threads.createJavaThreadWrapper(Threads.java:165)
	... 17 more
Can't print deadlocks:Unable to deduce type of thread from address 0x00007f150e9f4800 (expected type JavaThread, CompilerThread, ServiceThread, JvmtiAgentThread, or SurrogateLockerThread)
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.tools.jstack.JStack.runJStackTool(JStack.java:140)
	at sun.tools.jstack.JStack.main(JStack.java:106)
Caused by: java.lang.RuntimeException: Unable to deduce type of thread from address 0x00007f150e9f4800 (expected type JavaThread, CompilerThread, ServiceThread, JvmtiAgentThread, or SurrogateLockerThread)
	at sun.jvm.hotspot.runtime.Threads.createJavaThreadWrapper(Threads.java:169)
	at sun.jvm.hotspot.runtime.Threads.first(Threads.java:153)
	at sun.jvm.hotspot.tools.StackTrace.run(StackTrace.java:75)
	at sun.jvm.hotspot.tools.StackTrace.run(StackTrace.java:45)
	at sun.jvm.hotspot.tools.JStack.run(JStack.java:66)
	at sun.jvm.hotspot.tools.Tool.startInternal(Tool.java:260)
	at sun.jvm.hotspot.tools.Tool.start(Tool.java:223)
	at sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
	at sun.jvm.hotspot.tools.JStack.main(JStack.java:92)
	... 6 more
Caused by: sun.jvm.hotspot.types.WrongTypeException: No suitable match for type of address 0x00007f150e9f4800
	at sun.jvm.hotspot.runtime.InstanceConstructor.newWrongTypeException(InstanceConstructor.java:62)
	at sun.jvm.hotspot.runtime.VirtualConstructor.instantiateWrapperFor(VirtualConstructor.java:80)
	at sun.jvm.hotspot.runtime.Threads.createJavaThreadWrapper(Threads.java:165)
	... 14 more
```

**Comment by IvanRibakov** [comment]
Sorry, I just read the output I posted above and realised that `jstack` was actually unable to get it's job done. Based on the info from [here](https://stackoverflow.com/questions/50444493/why-is-jstack-is-unable-to-get-the-threadump-of-a-java-process-process) I ran `sudo yum install java-1.8.0-openjdk-debug` and tried running jstack again (both as sudo and java process owner) but still got the same result.

**Comment by IvanRibakov** [comment]
@eatkins Solved the `Unable to deduce thread type` problem (was missing `debuginfo` package, following command, albeit an overkill, did the trick: `sudo yum --enablerepo='*-debug*' install java-1.8.0-openjdk-debuginfo.x86_64`):

```
$ ps -ef | grep java
vagrant   3493  3361  0 Aug10 pts/2    00:00:04 java -Xms1024m -Xmx1024m -XX:ReservedCodeCacheSize=128m -XX:MaxMetaspaceSize=256m -jar /usr/share/sbt/bin/sbt-launch.jar -debug -Djline.terminal=none sbtVersion
vagrant   7697 28010  0 00:05 pts/3    00:00:00 grep --color=auto java

$ jstack -F 3493
Attaching to process ID 3493, please wait...
Debugger attached successfully.
Server compiler detected.
JVM version is 25.222-b10
Deadlock Detection:

No deadlocks found.

Thread 4001: (state = IN_NATIVE)
 - java.lang.UNIXProcess.waitForProcessExit(int) @bci=0 (Interpreted frame)
 - java.lang.UNIXProcess.lambda$initStreams$3() @bci=5, line=289 (Interpreted frame)
 - java.lang.UNIXProcess$$Lambda$282.run() @bci=4 (Interpreted frame)
 - java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) @bci=95, line=1149 (Interpreted frame)
 - java.util.concurrent.ThreadPoolExecutor$Worker.run() @bci=5, line=624 (Interpreted frame)
 - java.lang.Thread.run() @bci=11, line=748 (Interpreted frame)


Thread 3798: (state = BLOCKED)
 - sun.misc.Unsafe.park(boolean, long) @bci=0 (Interpreted frame)
 - java.util.concurrent.locks.LockSupport.parkNanos(java.lang.Object, long) @bci=20, line=215 (Interpreted frame)
 - java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(long) @bci=78, line=2078 (Interpreted frame)
 - com.lmax.disruptor.TimeoutBlockingWaitStrategy.waitFor(long, com.lmax.disruptor.Sequence, com.lmax.disruptor.Sequence, com.lmax.disruptor.SequenceBarrier) @bci=46, line=38 (Interpreted frame)
 - com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(long) @bci=18, line=56 (Interpreted frame)
 - com.lmax.disruptor.BatchEventProcessor.processEvents() @bci=17, line=159 (Interpreted frame)
 - com.lmax.disruptor.BatchEventProcessor.run() @bci=37, line=125 (Interpreted frame)
 - java.lang.Thread.run() @bci=11, line=748 (Interpreted frame)


Thread 3517: (state = BLOCKED)


Thread 3508: (state = BLOCKED)
 - java.lang.Object.wait(long) @bci=0 (Interpreted frame)
 - java.lang.ref.ReferenceQueue.remove(long) @bci=59, line=144 (Interpreted frame)
 - java.lang.ref.ReferenceQueue.remove() @bci=2, line=165 (Interpreted frame)
 - java.lang.ref.Finalizer$FinalizerThread.run() @bci=36, line=216 (Interpreted frame)


Thread 3506: (state = BLOCKED)
 - java.lang.Object.wait(long) @bci=0 (Interpreted frame)
 - java.lang.Object.wait() @bci=2, line=502 (Interpreted frame)
 - java.lang.ref.Reference.tryHandlePending(boolean) @bci=54, line=191 (Interpreted frame)
 - java.lang.ref.Reference$ReferenceHandler.run() @bci=1, line=153 (Interpreted frame)


Thread 3495: (state = IN_NATIVE)
 - java.io.FileInputStream.readBytes(byte[], int, int) @bci=0 (Interpreted frame)
 - java.io.FileInputStream.read(byte[], int, int) @bci=4, line=255 (Interpreted frame)
 - java.io.BufferedInputStream.fill() @bci=214, line=246 (Interpreted frame)
 - java.io.BufferedInputStream.read() @bci=12, line=265 (Compiled frame)
 - jline.internal.TerminalLineSettings.waitAndCapture(java.lang.Process) @bci=21, line=331 (Interpreted frame)
 - jline.internal.TerminalLineSettings.exec(java.lang.String[]) @bci=154, line=311 (Interpreted frame)
 - jline.internal.TerminalLineSettings.stty(java.lang.String[]) @bci=26, line=282 (Interpreted frame)
 - jline.internal.TerminalLineSettings.set(java.lang.String) @bci=12, line=148 (Interpreted frame)
 - jline.UnixTerminal.init() @bci=38, line=92 (Interpreted frame)
 - jline.TerminalFactory.create(java.lang.String) @bci=362, line=116 (Interpreted frame)
 - jline.TerminalFactory.get(java.lang.String) @bci=7, line=180 (Interpreted frame)
 - jline.TerminalFactory.get() @bci=1, line=186 (Interpreted frame)
 - sbt.internal.util.ConsoleAppender$.ansiSupported() @bci=0, line=245 (Interpreted frame)
 - sbt.internal.util.ConsoleAppender$.<init>() @bci=30, line=107 (Interpreted frame)
 - sbt.internal.util.ConsoleAppender$.<clinit>() @bci=3 (Interpreted frame)
 - sbt.internal.util.GlobalLogging$.initial(scala.Function3, scala.Function0, sbt.internal.util.ConsoleOut) @bci=16, line=83 (Interpreted frame)
 - sbt.StandardMain$.initialGlobalLogging() @bci=22, line=157 (Interpreted frame)
 - sbt.StandardMain$.initialState(xsbti.AppConfiguration, scala.collection.Seq, scala.collection.Seq) @bci=266, line=183 (Interpreted frame)
 - sbt.xMain.run(xsbti.AppConfiguration) @bci=237, line=87 (Interpreted frame)
 - xsbt.boot.Launch$$anonfun$run$1.apply() @bci=10, line=109 (Interpreted frame)
 - xsbt.boot.Launch$.withContextLoader(java.lang.ClassLoader, scala.Function0) @bci=15, line=128 (Interpreted frame)
 - xsbt.boot.Launch$.run(xsbti.Launcher, xsbt.boot.RunConfiguration) @bci=97, line=109 (Interpreted frame)
 - xsbt.boot.Launch$$anonfun$apply$1.apply(java.lang.Object) @bci=16, line=35 (Interpreted frame)
 - xsbt.boot.Launch$.launch(scala.Function1, xsbt.boot.RunConfiguration) @bci=2, line=117 (Interpreted frame)
 - xsbt.boot.Launch$.apply(xsbt.boot.LauncherArguments) @bci=876, line=18 (Interpreted frame)
 - xsbt.boot.Boot$.runImpl(xsbt.boot.LauncherArguments) @bci=4, line=56 (Interpreted frame)
 - xsbt.boot.Boot$.main(java.lang.String[]) @bci=314, line=18 (Interpreted frame)
 - xsbt.boot.Boot.main(java.lang.String[]) @bci=4 (Interpreted frame)


```

**Comment by eed3si9n** [comment]
In addition to `-Djline.terminal=none`, maybe add `-no-colors`?

```
Thread 3495: (state = IN_NATIVE)
 - java.io.FileInputStream.readBytes(byte[], int, int) @bci=0 (Interpreted frame)
 - java.io.FileInputStream.read(byte[], int, int) @bci=4, line=255 (Interpreted frame)
 - java.io.BufferedInputStream.fill() @bci=214, line=246 (Interpreted frame)
 - java.io.BufferedInputStream.read() @bci=12, line=265 (Compiled frame)
 - jline.internal.TerminalLineSettings.waitAndCapture(java.lang.Process) @bci=21, line=331 (Interpreted frame)
 - jline.internal.TerminalLineSettings.exec(java.lang.String[]) @bci=154, line=311 (Interpreted frame)
 - jline.internal.TerminalLineSettings.stty(java.lang.String[]) @bci=26, line=282 (Interpreted frame)
 - jline.internal.TerminalLineSettings.set(java.lang.String) @bci=12, line=148 (Interpreted frame)
 - jline.UnixTerminal.init() @bci=38, line=92 (Interpreted frame)
 - jline.TerminalFactory.create(java.lang.String) @bci=362, line=116 (Interpreted frame)
 - jline.TerminalFactory.get(java.lang.String) @bci=7, line=180 (Interpreted frame)
 - jline.TerminalFactory.get() @bci=1, line=186 (Interpreted frame)
 - sbt.internal.util.ConsoleAppender$.ansiSupported() @bci=0, line=245 (Interpreted frame)
 - sbt.internal.util.ConsoleAppender$.<init>() @bci=30, line=107 (Interpreted frame)
 - sbt.internal.util.ConsoleAppender$.<clinit>() @bci=3 (Interpreted frame)
 - sbt.internal.util.GlobalLogging$.initial(scala.Function3, scala.Function0, sbt.internal.util.ConsoleOut) @bci=16, line=83 (Interpreted frame)
 - sbt.StandardMain$.initialGlobalLogging() @bci=22, line=157 (Interpreted frame)
 - sbt.StandardMain$.initialState(xsbti.AppConfiguration, scala.collection.Seq, scala.collection.Seq) @bci=266, line=183 (Interpreted frame)
```

**Comment by IvanRibakov** [comment]
Nope, as far as I can see the result is the same:
```
$ ps -ef | grep java
vagrant   1304  1169 17 22:08 pts/2    00:00:03 java -Xms1024m -Xmx1024m -XX:ReservedCodeCacheSize=128m -XX:MaxMetaspaceSize=256m -Dsbt.log.noformat=true -jar /usr/share/sbt/bin/sbt-launch.jar -debug -Djline.terminal=none sbtVersion
vagrant   2161 28010  0 22:08 pts/3    00:00:00 grep --color=auto java

$ jstack -F 1304
Attaching to process ID 1304, please wait...
Debugger attached successfully.
Server compiler detected.
JVM version is 25.222-b10
Deadlock Detection:

No deadlocks found.

Thread 1783: (state = IN_NATIVE)
 - java.lang.UNIXProcess.waitForProcessExit(int) @bci=0 (Interpreted frame)
 - java.lang.UNIXProcess.lambda$initStreams$3() @bci=5, line=289 (Interpreted frame)
 - java.lang.UNIXProcess$$Lambda$282.run() @bci=4 (Interpreted frame)
 - java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) @bci=95, line=1149 (Interpreted frame)
 - java.util.concurrent.ThreadPoolExecutor$Worker.run() @bci=5, line=624 (Interpreted frame)
 - java.lang.Thread.run() @bci=11, line=748 (Interpreted frame)


Thread 1608: (state = BLOCKED)
 - sun.misc.Unsafe.park(boolean, long) @bci=0 (Interpreted frame)
 - java.util.concurrent.locks.LockSupport.parkNanos(java.lang.Object, long) @bci=20, line=215 (Interpreted frame)
 - java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(long) @bci=78, line=2078 (Interpreted frame)
 - com.lmax.disruptor.TimeoutBlockingWaitStrategy.waitFor(long, com.lmax.disruptor.Sequence, com.lmax.disruptor.Sequence, com.lmax.disruptor.SequenceBarrier) @bci=46, line=38 (Interpreted frame)
 - com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(long) @bci=18, line=56 (Interpreted frame)
 - com.lmax.disruptor.BatchEventProcessor.processEvents() @bci=17, line=159 (Interpreted frame)
 - com.lmax.disruptor.BatchEventProcessor.run() @bci=37, line=125 (Interpreted frame)
 - java.lang.Thread.run() @bci=11, line=748 (Interpreted frame)


Thread 1329: (state = BLOCKED)


Thread 1321: (state = BLOCKED)
 - java.lang.Object.wait(long) @bci=0 (Interpreted frame)
 - java.lang.ref.ReferenceQueue.remove(long) @bci=59, line=144 (Interpreted frame)
 - java.lang.ref.ReferenceQueue.remove() @bci=2, line=165 (Interpreted frame)
 - java.lang.ref.Finalizer$FinalizerThread.run() @bci=36, line=216 (Interpreted frame)


Thread 1319: (state = BLOCKED)
 - java.lang.Object.wait(long) @bci=0 (Interpreted frame)
 - java.lang.Object.wait() @bci=2, line=502 (Interpreted frame)
 - java.lang.ref.Reference.tryHandlePending(boolean) @bci=54, line=191 (Interpreted frame)
 - java.lang.ref.Reference$ReferenceHandler.run() @bci=1, line=153 (Interpreted frame)


Thread 1306: (state = IN_NATIVE)
 - java.io.FileInputStream.readBytes(byte[], int, int) @bci=0 (Interpreted frame)
 - java.io.FileInputStream.read(byte[], int, int) @bci=4, line=255 (Interpreted frame)
 - java.io.BufferedInputStream.fill() @bci=214, line=246 (Interpreted frame)
 - java.io.BufferedInputStream.read() @bci=12, line=265 (Compiled frame)
 - jline.internal.TerminalLineSettings.waitAndCapture(java.lang.Process) @bci=21, line=331 (Interpreted frame)
 - jline.internal.TerminalLineSettings.exec(java.lang.String[]) @bci=154, line=311 (Interpreted frame)
 - jline.internal.TerminalLineSettings.stty(java.lang.String[]) @bci=26, line=282 (Interpreted frame)
 - jline.internal.TerminalLineSettings.set(java.lang.String) @bci=12, line=148 (Interpreted frame)
 - jline.UnixTerminal.init() @bci=38, line=92 (Interpreted frame)
 - jline.TerminalFactory.create(java.lang.String) @bci=362, line=116 (Interpreted frame)
 - jline.TerminalFactory.get(java.lang.String) @bci=7, line=180 (Interpreted frame)
 - jline.TerminalFactory.get() @bci=1, line=186 (Interpreted frame)
 - sbt.internal.util.ConsoleAppender$.ansiSupported() @bci=0, line=245 (Interpreted frame)
 - sbt.internal.util.ConsoleAppender$.<init>() @bci=30, line=107 (Interpreted frame)
 - sbt.internal.util.ConsoleAppender$.<clinit>() @bci=3 (Interpreted frame)
 - sbt.internal.util.GlobalLogging$.initial(scala.Function3, scala.Function0, sbt.internal.util.ConsoleOut) @bci=16, line=83 (Interpreted frame)
 - sbt.StandardMain$.initialGlobalLogging() @bci=22, line=157 (Interpreted frame)
 - sbt.StandardMain$.initialState(xsbti.AppConfiguration, scala.collection.Seq, scala.collection.Seq) @bci=266, line=183 (Interpreted frame)
 - sbt.xMain.run(xsbti.AppConfiguration) @bci=237, line=87 (Interpreted frame)
 - xsbt.boot.Launch$$anonfun$run$1.apply() @bci=10, line=109 (Interpreted frame)
 - xsbt.boot.Launch$.withContextLoader(java.lang.ClassLoader, scala.Function0) @bci=15, line=128 (Interpreted frame)
 - xsbt.boot.Launch$.run(xsbti.Launcher, xsbt.boot.RunConfiguration) @bci=97, line=109 (Interpreted frame)
 - xsbt.boot.Launch$$anonfun$apply$1.apply(java.lang.Object) @bci=16, line=35 (Interpreted frame)
 - xsbt.boot.Launch$.launch(scala.Function1, xsbt.boot.RunConfiguration) @bci=2, line=117 (Interpreted frame)
 - xsbt.boot.Launch$.apply(xsbt.boot.LauncherArguments) @bci=876, line=18 (Interpreted frame)
 - xsbt.boot.Boot$.runImpl(xsbt.boot.LauncherArguments) @bci=4, line=56 (Interpreted frame)
 - xsbt.boot.Boot$.main(java.lang.String[]) @bci=314, line=18 (Interpreted frame)
 - xsbt.boot.Boot.main(java.lang.String[]) @bci=4 (Interpreted frame)

```

**Comment by IvanRibakov** [comment]
@eatkins @eed3si9n Any thoughts?

In case you're wondering - here's the simplest way I found to reproduce the issue:
```
parallel ::: "sbt -d sbtVersion"
```

**Comment by eed3si9n** [comment]
Looks like it's still getting stuck at getting the JLine terminal.
You might want to try sbt 1.3.0-RC3 since the logic has changed a bit:

- old https://github.com/sbt/util/blob/v1.2.4/internal/util-logging/src/main/scala/sbt/internal/util/ConsoleAppender.scala#L103-L108
- new https://github.com/sbt/util/blob/ca776cf3f892ccfdce1cbc555c93fe1141ecc78b/internal/util-logging/src/main/scala/sbt/internal/util/ConsoleAppender.scala#L123-L146

**Comment by IvanRibakov** [comment]
I followed instructions from https://github.com/sbt/sbt/blob/develop/DEVELOPING.md to build sbt from sources, however, got the following error when running `./sbt-allsources.sh` for the first time:
```
[info] Loading settings for project zinc from zinc.sbt ...
[error] java.lang.RuntimeException: No project 'lmImpl' in 'file:/Volumes/data/_toremove/sbt-modules/librarymanagement/'.
[error] Valid project IDs: lmCommonTest, lmCore, lmIvy, lmRoot, lmScriptedTest
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at sbt.internal.Load$.$anonfun$checkAll$3(Load.scala:599)
[error] 	at sbt.internal.Load$.$anonfun$checkAll$3$adapted(Load.scala:593)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at sbt.internal.Load$.$anonfun$checkAll$2(Load.scala:593)
[error] 	at sbt.internal.Load$.$anonfun$checkAll$2$adapted(Load.scala:593)
[error] 	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:792)
[error] 	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:234)
[error] 	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:465)
[error] 	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:791)
[error] 	at sbt.internal.Load$.checkAll(Load.scala:593)
[error] 	at sbt.internal.Load$.loadURI(Load.scala:486)
[error] 	at sbt.internal.Load$.load(Load.scala:464)
[error] 	at sbt.internal.Load$.$anonfun$apply$1(Load.scala:240)
[error] 	at sbt.internal.Load$.timed(Load.scala:1385)
[error] 	at sbt.internal.Load$.apply(Load.scala:240)
[error] 	at sbt.internal.Load$.defaultLoad(Load.scala:55)
[error] 	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:832)
[error] 	at sbt.BuiltinCommands$.doLoadProject(Main.scala:832)
[error] 	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:794)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:144)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:139)
[error] 	at sbt.Command$.process(Command.scala:183)
[error] 	at sbt.MainLoop$.process$1(MainLoop.scala:187)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:222)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:141)
[error] 	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:270)
[error] 	at sbt.State$StateOpsImpl$.process$extension(State.scala:274)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:141)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:141)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:132)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
[error] 	at sbt.io.Using.apply(Using.scala:27)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:35)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:124)
[error] 	at sbt.xMainImpl$.run(Main.scala:67)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.internal.XMainConfiguration.runXMain(XMainConfiguration.scala:46)
[error] 	at sbt.xMain.run(Main.scala:39)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:18)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] No project 'lmImpl' in 'file:/Volumes/data/_toremove/sbt-modules/librarymanagement/'.
[error] Valid project IDs: lmCommonTest, lmCore, lmIvy, lmRoot, lmScriptedTest
```

I don't suppose I could get `1.3.0-RC3` binary from anywhere else at this point?

**Comment by eed3si9n** [comment]
1.3.0-RC3 is published to Maven Central.
All you need to do is put `sbt.version=1.3.0-RC3` in build.properties.

**Comment by IvanRibakov** [comment]
@eed3si9n Thanks for the hint! 

I can confirm that `v1.3.0-RC3` with `-Djline.terminal=none` works as expected when running SBT via GNU Parallel

Thank you @eed3si9n and @eatkins for your support on this one!
