### ISSUE TITLE
Shade JLine

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#4943]
## steps

JLine in-sources JAnsi, and JLine is used by both Coursier and Scala.
lm-shaded-coursier recently leaked JLine 3 by mistake, but the same can happen with Scala in the future (https://github.com/scala/scala/pull/8036).

## problem

In case of https://github.com/sbt/sbt/pull/4925, it manifested itself as:

```
[info] [error] java.lang.NoClassDefFoundError: Could not initialize class org.fusesource.jansi.AnsiOutputStream
[info] [error] 	at jline.internal.Ansi.stripAnsi(Ansi.java:28)
[info] [error] 	at jline.console.ConsoleReader.setPrompt(ConsoleReader.java:499)
[info] [error] 	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2425)
[info] [error] 	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2378)
[info] [error] 	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2366)
```

## expectation

Isolate ourselves from upstream uses of JLine.

**Comment by eed3si9n** [comment]
https://github.com/sbt/shaded-jline

**Comment by eed3si9n** [comment]
Looks more complicated than initially thought (#4959), so I am closing this for now.
