### ISSUE TITLE
run / traceLevel doesn't work on run

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#4992]
_Originally posted by @contrun in https://github.com/sbt/sbt/issues/3793#issuecomment-525152332_

## steps

I tried 1.3.0-RC4. I want to get the full stack trace. It still does not work for me. Am I doing it the wrong way?

```
sbt:akka-db-load> set run/traceLevel := 10000
[info] Defining run / traceLevel
[info] The new value will be used by no settings or tasks.
[info] Reapplying settings...
[info] Set current project to akka-db-load (in build file:/home/e/Local/decay/)
sbt:akka-db-load> about
[info] This is sbt 1.3.0-RC4
....
[info] sbt, sbt plugins, and build definitions are using Scala 2.12.8
sbt:akka-db-load> run
```

## problem

```
sbt:akka-db-load> run
[info] Compiling 1 Scala source to /home/e/Local/decay/target/scala-2.12/classes ...
[info] running Main 
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Uncaught error from thread [default-akka.actor.default-dispatcher-2]: akka/actor/dungeon/FaultHandling$$anonfun$handleNonFatalOrInterruptedException$1, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[default]
java.lang.NoClassDefFoundError: akka/actor/dungeon/FaultHandling$$anonfun$handleNonFatalOrInterruptedException$1
	at akka.actor.dungeon.FaultHandling.handleNonFatalOrInterruptedException(FaultHandling.scala:310)
	at akka.actor.dungeon.FaultHandling.handleNonFatalOrInterruptedException$(FaultHandling.scala:310)
	at akka.actor.ActorCell.handleNonFatalOrInterruptedException(ActorCell.scala:447)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:557)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:569)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:293)
	at akka.dispatch.Mailbox.run(Mailbox.scala:228)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.ClassNotFoundException: akka.actor.dungeon.FaultHandling$$anonfun$handleNonFatalOrInterruptedException$1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 12 more
```

## expectation

Full stack trace is displayed.

**Comment by eed3si9n** [comment]
@bitloi Since the default mode of `run` is client-side run, I'm closing this ticket as won't fix. I don't think it's worth the complication.
