### ISSUE TITLE
`consoleProject` fails sbt 1.3.0 from sbt 1.2.8 launcher with `[error] (run-main-0) sbt.internal.inc.InvalidScalaInstance: Scala instance doesn't exist or is invalid:`

### ISSUE THREAD

**Issue by jsoref** [sbt/sbt#5038]
## steps
this isn't a real command, you just need to have installed the sbt launcher before sbt 1.3.0 was available:
```sh
brew install sbt@1.2.8
```
`build.sbt`:
```
scalaVersion := "2.12.8" // this probably doesn't matter
```
`project/build.properties`:
```
sbt.version=1.3.0
```

## problem
Start sbt (1.2.8 launcher, asking to use sbt 1.3.0) and ask it to trigger `consoleProject`:
```sh
sbt -Dsbt.ci=true -Dsbt.ivy=true -Dsbt.banner=false consoleProject
```

Or more precisely:
```sh
java -Xms1024m -Xmx1024m -XX:ReservedCodeCacheSize=128m -XX:MaxMetaspaceSize=256m -Dsbt.version=1.3.0 -jar /usr/local/Cellar/sbt/1.2.8/libexec/bin/sbt-launch.jar -Dsbt.ivy=true -Dsbt.ci=true -Dsbt.banner=false consoleProject
```
(Note: the sbt.ivy bit is a red-herring, it was suggested as a way to rule out coursier, the problem is just the launcher)

```

[error] (run-main-0) sbt.internal.inc.InvalidScalaInstance: Scala instance doesn't exist or is invalid: 
[error]     version 2.12.8, library jars: [Ljava.io.File;@5e1c2fa2, compiler jar: ~/.sbt/boot/scala-2.12.8/lib/scala-compiler.jar, other jars: ~/.sbt/boot/scala-2.12.8/lib/jline.jar, ~/.sbt/boot/scala-2.12.8/lib/scala-reflect.jar, ~/.sbt/boot/scala-2.12.8/lib/scala-xml_2.12.jar
[error] sbt.internal.inc.InvalidScalaInstance: Scala instance doesn't exist or is invalid: 
[error]     version 2.12.8, library jars: [Ljava.io.File;@5e1c2fa2, compiler jar: ~/.sbt/boot/scala-2.12.8/lib/scala-compiler.jar, other jars: ~/.sbt/boot/scala-2.12.8/lib/jline.jar, ~/.sbt/boot/scala-2.12.8/lib/scala-reflect.jar, ~/.sbt/boot/scala-2.12.8/lib/scala-xml_2.12.jar
[error] 	at sbt.internal.inc.ScalaInstance$.slowActualVersion(ScalaInstance.scala:256)
[error] 	at sbt.internal.inc.ScalaInstance$.sbt$internal$inc$ScalaInstance$$actualVersion(ScalaInstance.scala:241)
[error] 	at sbt.internal.inc.ScalaInstance.$anonfun$actualVersion$1(ScalaInstance.scala:105)
[error] 	at sbt.internal.inc.ScalaInstance$$Lambda$2548.00000000A8734820.apply(Unknown Source)
[error] 	at scala.Option.getOrElse(Option.scala:138)
[error] 	at sbt.internal.inc.ScalaInstance.actualVersion$lzycompute(ScalaInstance.scala:103)
[error] 	at sbt.internal.inc.ScalaInstance.actualVersion(ScalaInstance.scala:102)
[error] 	at sbt.internal.inc.ZincComponentCompiler$ZincCompilerBridgeProvider.fetchCompiledBridge(ZincComponentCompiler.scala:79)
[error] 	at sbt.internal.inc.AnalyzingCompiler.loader(AnalyzingCompiler.scala:260)
[error] 	at sbt.internal.inc.AnalyzingCompiler.getInterfaceClass(AnalyzingCompiler.scala:278)
[error] 	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:245)
[error] 	at sbt.internal.inc.AnalyzingCompiler.consoleCommandArguments(AnalyzingCompiler.scala:234)
[error] 	at sbt.internal.inc.AnalyzingCompiler.console(AnalyzingCompiler.scala:188)
[error] 	at sbt.Console.console0$1(Console.scala:48)
[error] 	at sbt.Console.$anonfun$apply$2(Console.scala:51)
[error] 	at sbt.Console$$Lambda$2940.00000000A64FB420.apply$mcV$sp(Unknown Source)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error] 	at sbt.TrapExit$App.run(TrapExit.scala:257)
[error] 	at java.lang.Thread.run(Thread.java:813)
[error] Caused by: java.lang.ClassNotFoundException: scala.tools.nsc.Properties
[error] 	at java.lang.Class.forNameImpl(Native Method)
[error] 	at java.lang.Class.forName(Class.java:416)
[error] 	at sbt.internal.inc.ScalaInstance$.slowActualVersion(ScalaInstance.scala:249)
[error] 	at sbt.internal.inc.ScalaInstance$.sbt$internal$inc$ScalaInstance$$actualVersion(ScalaInstance.scala:241)
[error] 	at sbt.internal.inc.ScalaInstance.$anonfun$actualVersion$1(ScalaInstance.scala:105)
[error] 	at sbt.internal.inc.ScalaInstance$$Lambda$2548.00000000A8734820.apply(Unknown Source)
[error] 	at scala.Option.getOrElse(Option.scala:138)
[error] 	at sbt.internal.inc.ScalaInstance.actualVersion$lzycompute(ScalaInstance.scala:103)
[error] 	at sbt.internal.inc.ScalaInstance.actualVersion(ScalaInstance.scala:102)
[error] 	at sbt.internal.inc.ZincComponentCompiler$ZincCompilerBridgeProvider.fetchCompiledBridge(ZincComponentCompiler.scala:79)
[error] 	at sbt.internal.inc.AnalyzingCompiler.loader(AnalyzingCompiler.scala:260)
[error] 	at sbt.internal.inc.AnalyzingCompiler.getInterfaceClass(AnalyzingCompiler.scala:278)
[error] 	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:245)
[error] 	at sbt.internal.inc.AnalyzingCompiler.consoleCommandArguments(AnalyzingCompiler.scala:234)
[error] 	at sbt.internal.inc.AnalyzingCompiler.console(AnalyzingCompiler.scala:188)
[error] 	at sbt.Console.console0$1(Console.scala:48)
[error] 	at sbt.Console.$anonfun$apply$2(Console.scala:51)
[error] 	at sbt.Console$$Lambda$2940.00000000A64FB420.apply$mcV$sp(Unknown Source)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error] 	at sbt.TrapExit$App.run(TrapExit.scala:257)
[error] 	at java.lang.Thread.run(Thread.java:813)
[error] Nonzero exit code: 1
[error] (consoleProject) Nonzero exit code: 1
[error] Total time: 0 s, completed Sep 5, 2019 1:08:00 PM
sbt:foo> [info] new client connected: network-1
```

## expectation
at the very least, a try block that recognizes this case and explains "sorry, you're using an sbt launcher <1.3.0, this won't work, please upgrade"

Ideally, "it should just work".

## notes
To fix this, just upgrade your sbt launcher:
```
brew upgrade sbt
```
(similar commands for other package management systems)

**Comment by eed3si9n** [comment]
@jsoref Thanks for the report! I didn't realize that this depended on the launcher version.

**Comment by jsoref** [comment]
@eatkins was the one who helped figure that part out.

**Comment by eed3si9n** [comment]
I am closing this due to inactivity. `consoleProject` works for me on sbt 1.12.3 using sbt 1.12.3 launcher.
