### ISSUE TITLE
Regression: skip does not work in sbt 1.3.0

### ISSUE THREAD

**Issue by Atry** [sbt/sbt#5056]
## steps
sbt version: 1.3.0

```
git clone https://github.com/Atry/Dsl.scala-akka-actor.git && cd Dsl.scala-akka-actor && git checkout a129a2d3fcfa62c9e054cfa9cc92bdbafb177991 && git ++2.13.0 test
```

## problem

```
[error] java.lang.RuntimeException: Skipping update requested, but update has not previously run successfully.
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$10(LibraryManagement.scala:86)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:129)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2909)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:289)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
```

## expectation

No error

## notes

Related code: https://github.com/Atry/Dsl.scala-akka-actor/blob/a129a2d3fcfa62c9e054cfa9cc92bdbafb177991/dsl/domains/akka/actor/typed/js/js.sbt#L13

```scala
skip := scalaBinaryVersion.value == "2.13"
```

**Comment by Atry** [comment]
In Sbt 1.2.8, I use `skip := true` to skip a project, including dependency resolving, compiling, publishing. `skip := true` does not work in Sbt 1.3.0

**Comment by armanbilge** [comment]
Relevant code:
https://github.com/sbt/sbt/blob/fe5497938a8b2898dcbab49b60e0f2ef53b06c29/main/src/main/scala/sbt/internal/LibraryManagement.scala#L111-L118

@eed3si9n could we make this error into a non-fatal warning perhaps? Thanks!

**Comment by eed3si9n** [comment]
Doing so might make the error state more confusing as `update` would skip and compilation would now fail with something like symbol `X` was not found in `com.example`?

**Comment by armanbilge** [comment]
Thanks for the response!

Like the OP I'm looking for an easy way to `skip` all steps for the project. I agree if someone is just doing `update / skip := true` (and only that) then the error would could be more confusing. Is there another way to accomplish this?
