### ISSUE TITLE
[1.3.0] not terminating ActorSystem  leads to `NoClassDefFoundError` at the end of `run` as sbt cleans up the ClassLoader

### ISSUE THREAD

**Issue by jrudolph** [sbt/sbt#5075]
Originally reported by @srubietodd, see https://github.com/akka/akka-http/issues/2702.

build.sbt:

```scala
scalaVersion := "2.13.0"
 val akkaVersion = "2.5.23"
 val akkaHttpVersion = "10.1.9"
libraryDependencies ++= Seq(
  "com.typesafe.akka" %% "akka-actor" % akkaVersion,
  "com.typesafe.akka" %% "akka-http" % akkaHttpVersion,
  "com.typesafe.akka" %% "akka-stream" % akkaVersion
)
```

Test.scala:

```scala
import akka.actor.ActorSystem
import akka.http.scaladsl.Http
import akka.http.scaladsl.model._
import akka.stream.ActorMaterializer
import scala.concurrent.Future
import scala.util.{Failure, Success}

object Main extends App {
  implicit val system = ActorSystem()
  implicit val materializer = ActorMaterializer()
  // needed for the future flatMap/onComplete in the end
  implicit val executionContext = system.dispatcher
  val responseFuture: Future[HttpResponse] =
    Http().singleRequest(HttpRequest(uri = "http://akka.io"))
  responseFuture
    .onComplete {
      case Success(res) => println(res)
      case Failure(_)   => sys.error("something wrong")
    }
}
```

Log:

```
> run
[info] running Main 
Uncaught error from thread [default-akka.actor.default-dispatcher-2]: akka/actor/dungeon/FaultHandling$$anonfun$handleNonFatalOrInterruptedException$1, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[default]
java.lang.NoClassDefFoundError: akka/actor/dungeon/FaultHandling$$anonfun$handleNonFatalOrInterruptedException$1
        at akka.actor.dungeon.FaultHandling.handleNonFatalOrInterruptedException(FaultHandling.scala:310)
  | => aat akka.actor.dungeon.FaultHandling.handleNonFatalOrInterruptedException$(FaultHandling.scala:310)
	at akka.actor.ActorCell.handleNonFatalOrInterruptedException(ActorCell.scala:447)
	at akka.actor.ActorCell.invoke(ActorCell.scala:584)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.ClassNotFoundException: akka.actor.dungeon.FaultHandling$$anonfun$handleNonFatalOrInterruptedException$1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more
```

Potential workarounds (any of those works for me):

 * sbt 1.2.8
 * `fork in run := true`
 * `classLoaderLayeringStrategy := ClassLoaderLayeringStrategy.AllLibraryJars`

## workaround

Shutdown your actor system as follows:

```scala
  Await.result(system.terminate(), 5.seconds)
```

or 

```scala
Compile / run / fork := true
```

**Comment by kklorenzotesta** [comment]
I got the same problem when plotting a graph with breeze-viz after upgrading to sbt 1.3.0. I can provide a build to reproduce the bug if needed.

**Comment by SethTisue** [comment]
does `-Dsbt.classloader.close=false` make the problem go away?

**Comment by kklorenzotesta** [comment]
> does -Dsbt.classloader.close=false make the problem go away?

In my project yes, it goes aways

**Comment by drikssy** [comment]
I have the same issue using akka-streams (amqp) and I am new in scala... I dont really understand how o fix it @jrudolph ?  ```Uncaught error from thread [media-hub-test-akka.actor.default-dispatcher-2]: akka/actor/dungeon/FaultHandling$$anonfun$handleNonFatalOrInterruptedException$1, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[media-hub-test]
Uncaught error from thread [media-hub-test-akka.stream.default-blocking-io-dispatcher-6]: akka/actor/dungeon/FaultHandling$$anonfun$handleNonFatalOrInterruptedException$1, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[media-hub-test]
java.lang.NoClassDefFoundError: akka/actor/dungeon/FaultHandling$$anonfun$handleNonFatalOrInterruptedException$1
	at akka.actor.dungeon.FaultHandling.handleNonFatalOrInterruptedException(FaultHandling.scala:310)
	at akka.actor.dungeon.FaultHandling.handleNonFatalOrInterruptedException$(FaultHandling.scala:310)
	at akka.actor.ActorCell.handleNonFatalOrInterruptedException(ActorCell.scala:447)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:557)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:569)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:293)
	at akka.dispatch.Mailbox.run(Mailbox.scala:228)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: akka.actor.dungeon.FaultHandling$$anonfun$handleNonFatalOrInterruptedException$1
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 10 more
java.lang.NoClassDefFoundError: akka/actor/dungeon/FaultHandling$$anonfun$handleNonFatalOrInterruptedException$1
	at akka.actor.dungeon.FaultHandling.handleNonFatalOrInterruptedException(FaultHandling.scala:310)
	at akka.actor.dungeon.FaultHandling.handleNonFatalOrInterruptedException$(FaultHandling.scala:310)
	at akka.actor.ActorCell.handleNonFatalOrInterruptedException(ActorCell.scala:447)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:557)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:569)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:293)
	at akka.dispatch.Mailbox.run(Mailbox.scala:228)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

Exception: sbt.TrapExitSecurityException thrown from the UncaughtExceptionHandler in thread "media-hub-test-akka.stream.default-blocking-io-dispatcher-6"``` many thanks

**Comment by eatkins** [comment]
Great catch @SethTisue. I think we need to make this a warning rather than a strict failure for 1.3.1. It's causing too much confusion.

**Comment by eed3si9n** [comment]
Added workaround section to the description. I think we should recommend

```scala
Compile / run / fork := true
```

instead of running sbt with JVM props.

**Comment by eed3si9n** [comment]
@eatkins Would it make sense to give Akka 3s grace period? Would that solve any problem?

**Comment by eatkins** [comment]
https://github.com/akka/akka-http/issues/2702#issuecomment-531319091

**Comment by eatkins** [comment]
The issue I have with workarounds for this issue is that often it is actually catching a real resource leak in the code. Not shutting down an ActorSystem is very common from what I have gathered. There is a huge performance penalty for fork so I'm somewhat wary fo encouraging people to switch their builds to fork mindlessly.

**Comment by eatkins** [comment]
The example is actually extremely similar to the program I used in the sbt 1.3.0 watch benchmarks: https://github.com/eatkins/scala-build-watch-performance. Even without layered classloaders, forking took about 5.5 seconds compared to 1.5 second for in-process.

**Comment by eed3si9n** [comment]
It is a tricky problem that affects UX (performance vs ease of use).

It is sbt that's emulating `run` as a function call, which makes it sensitive to resource cleanup at the end. iow, if people ran using `java -cp ..` they won't see this particular error message. Maybe we need to document this better and let the user choose between 1.5s `run` vs not shutting down concurrency managers?

**Comment by jrudolph** [comment]
As written in https://github.com/akka/akka-http/issues/2702#issuecomment-531352120, the regression in sbt 1.3.0 seems to be that the `run` task doesn't seem to wait any more until all non-daemon threads of the application are finished. It might be uncommon overall but it's somewhat common with Akka apps to let the main method run out after the initialization code has run. `system.terminate` is often called from another thread later on.

**Comment by eed3si9n** [comment]
Not sure if we waited before, but waiting for non-daemon threads (for some time?) sounds like an improved UX rather than unplugging the ClassLoader under them.

**Comment by eatkins** [comment]
We wait indefinitely for non-daemon threads and have for a long time. The difference is that in 1.3.0 we started closing the classloader in ScalaRun.run, which is before the background job service joins the non-daemon threads. I should be able to restore the old behavior and I also am working on an overhaul of the classloader management for 1.3.1/1.4.0 that I think should be much better than 1.3.0.
