### ISSUE TITLE
[1.3.1 regression] sbt-mima-plugin throws java.lang.NoSuchMethodError: com.typesafe.tools.mima.core.Settings.allSettings()Lscala/collection/mutable/HashSet;

### ISSUE THREAD

**Issue by plokhotnyuk** [sbt/sbt#5107]
## steps
sbt version: 1.3.1

```
git clone https://github.com/plokhotnyuk/jsoniter-scala
cd jsoniter-scala
sed -i 's/1.3.0/1.3.1/g' project/build.properties
sbt clean mimaReportBinaryIssues
```

## problem
Build failure with
```
[error] java.lang.NoSuchMethodError: com.typesafe.tools.mima.core.Settings.allSettings()Lscala/collection/mutable/HashSet;
[error]         at com.typesafe.tools.mima.core.Settings.<init>(Settings.scala:17)
[error]         at com.typesafe.tools.mima.core.Config$.setup(Config.scala:49)
[error]         at com.typesafe.tools.mima.core.Config$.setup(Config.scala:46)
[error]         at com.typesafe.tools.mima.plugin.SbtMima$.makeMima(SbtMima.scala:23)
[error]         at com.typesafe.tools.mima.plugin.SbtMima$.checkBC$1(SbtMima.scala:33)
[error]         at com.typesafe.tools.mima.plugin.SbtMima$.runMima(SbtMima.scala:38)
[error]         at com.typesafe.tools.mima.plugin.MimaPlugin$.$anonfun$binaryIssuesIterator$3(MimaPlugin.scala:88)
[error]         at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:941)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error]         at com.typesafe.tools.mima.plugin.MimaPlugin$.$anonfun$projectSettings$1(MimaPlugin.scala:26)
[error]         at com.typesafe.tools.mima.plugin.MimaPlugin$.$anonfun$projectSettings$1$adapted(MimaPlugin.scala:24)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:289)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] java.lang.NoSuchMethodError: com.typesafe.tools.mima.core.Settings.allSettings()Lscala/collection/mutable/HashSet;
[error]         at com.typesafe.tools.mima.core.Settings.<init>(Settings.scala:17)
[error]         at com.typesafe.tools.mima.core.Config$.setup(Config.scala:49)
[error]         at com.typesafe.tools.mima.core.Config$.setup(Config.scala:46)
[error]         at com.typesafe.tools.mima.plugin.SbtMima$.makeMima(SbtMima.scala:23)
[error]         at com.typesafe.tools.mima.plugin.SbtMima$.checkBC$1(SbtMima.scala:33)
[error]         at com.typesafe.tools.mima.plugin.SbtMima$.runMima(SbtMima.scala:38)
[error]         at com.typesafe.tools.mima.plugin.MimaPlugin$.$anonfun$binaryIssuesIterator$3(MimaPlugin.scala:88)
[error]         at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:941)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error]         at com.typesafe.tools.mima.plugin.MimaPlugin$.$anonfun$projectSettings$1(MimaPlugin.scala:26)
[error]         at com.typesafe.tools.mima.plugin.MimaPlugin$.$anonfun$projectSettings$1$adapted(MimaPlugin.scala:24)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:289)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (jsoniter-scala-core / mimaReportBinaryIssues) java.lang.NoSuchMethodError: com.typesafe.tools.mima.core.Settings.allSettings()Lscala/collection/mutable/HashSet;
[error] (jsoniter-scala-macros / mimaReportBinaryIssues) java.lang.NoSuchMethodError: com.typesafe.tools.mima.core.Settings.allSettings()Lscala/collection/mutable/HashSet;
[error] Total time: 145 s (02:25), completed Sep 20, 2019 9:55:30 AM
```

## expectation

Build completes successfully

## notes

W/A is to switch back to sbt 1.3.0

**Comment by lrytz** [comment]
A new MiMa is being released https://github.com/lightbend/mima/issues/389, https://github.com/lightbend/mima/issues/390

**Comment by plokhotnyuk** [comment]
Solution is updating sbt-mima-plugin to 0.6.1 like [here](https://github.com/plokhotnyuk/jsoniter-scala/commit/35e303c93c140b28ccc300d142d969da591e8ab7)
