### ISSUE TITLE
Project doesn't load (plugin resolution error) after upgrading to sbt 1.3.0

### ISSUE THREAD

**Issue by ignasi35** [sbt/sbt#5147]
Note: This is an edge case that's a bit hard to reproduce.

## Steps to reproduce

1. cleanup `$HOME/.sbt`
2. clone https://github.com/playframework/playframework.git (use https://github.com/playframework/playframework/commit/e5bce46713edd53683bcde721b1bc5ca21e12a62) 
3. load the main `build.sbt` in `playframework` (or any other `build.sbt`). This step is only so `$HOME/.sbt` is rebuilt
4. load the `build.sbt` in [`playframework/documentation/build.sbt`](https://github.com/playframework/playframework/blob/master/documentation/build.sbt)
5. exit the interactive sbt shell
6. add one of the following plugins into `$HOME/.sbt/1.0/plugins/plugins.sbt` (I found that at least the following two cause similar issues, directly or with transitive dependencies):

```	
addSbtPlugin("com.dwijnand" % "sbt-project-graph" % "0.4.0")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.0")
```
 	
7. repeat step `4.` (load the `build.sbt` in `playframework/documentation/build.sbt`)

### Expected

After `7.`, the expectation is that the interactive shell starts and both `sbt-graph` and `sbt-dependency-graph` ara available.

### Actual

The project fails to load and the an output similar to the following is produced:

```
sbt.librarymanagement.ResolveException: Error downloading com.dwijnand:sbt-project-graph
```

<details>
<summary>Fuller output</summary>

Note the following output complains about `sbt-compat` which (I think) is a dependency of `sbt-dependency-graph`. The error message also lists a failure to download `sbt-project-graph` itself.

```
[info] Loading project definition from /Users/ignasi/wip/deleteme/playframework/project/project
[info] Loading settings for project playframework-build from plugins.sbt ...
[info] Loading project definition from /Users/ignasi/wip/deleteme/playframework/project
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Loading settings for project Play-Framework from build.sbt,version.sbt ...
[info] Resolving key references (32636 settings) ...
[info] Loading project definition from /Users/ignasi/wip/deleteme/playframework/documentation/project
[info] Updating
[info] Resolved  dependencies
[warn]
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.dwijnand:sbt-project-graph:0.4.0 (scalaVersion=2.12, sbtVersion=1.0)
[warn]
[warn] 	Note: Unresolved dependencies path:
[info] Updating
[info] Resolved  dependencies
[warn]
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.dwijnand:sbt-project-graph:0.4.0 (scalaVersion=2.12, sbtVersion=1.0)
[warn]
[warn] 	Note: Unresolved dependencies path:
[error] stack trace is suppressed; run last ProjectRef(uri("file:///Users/ignasi/wip/deleteme/playframework/"), "Play-Exceptions") / update for the full output
[error] stack trace is suppressed; run last ProjectRef(uri("file:///Users/ignasi/wip/deleteme/playframework/"), "Sbt-Routes-Compiler") / update for the full output
[error] (ProjectRef(uri("file:///Users/ignasi/wip/deleteme/playframework/"), "Play-Exceptions") / update) sbt.librarymanagement.ResolveException: Error downloading com.dwijnand:sbt-project-graph;sbtVersion=1.0;scalaVersion=2.12:0.4.0
[error]   Not found
[error]   Not found
[error]   not found: /Users/ignasi/.ivy2/local/com.dwijnand/sbt-project-graph/scala_2.12/sbt_1.0/0.4.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/dwijnand/sbt-project-graph_2.12_1.0/0.4.0/sbt-project-graph-0.4.0.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/com/dwijnand/sbt-project-graph_2.12_1.0/0.4.0/sbt-project-graph-0.4.0.pom
[error]   not found: https://oss.sonatype.org/content/repositories/releases/com/dwijnand/sbt-project-graph_2.12_1.0/0.4.0/sbt-project-graph-0.4.0.pom
[error]   not found: https://repo.typesafe.com/typesafe/releases/com/dwijnand/sbt-project-graph_2.12_1.0/0.4.0/sbt-project-graph-0.4.0.pom
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.dwijnand/sbt-project-graph/scala_2.12/sbt_1.0/0.4.0/ivys/ivy.xml
[error] (ProjectRef(uri("file:///Users/ignasi/wip/deleteme/playframework/"), "Sbt-Routes-Compiler") / update) sbt.librarymanagement.ResolveException: Error downloading com.dwijnand:sbt-project-graph;sbtVersion=1.0;scalaVersion=2.12:0.4.0
[error]   Not found
[error]   Not found
[error]   not found: /Users/ignasi/.ivy2/local/com.dwijnand/sbt-project-graph/scala_2.12/sbt_1.0/0.4.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/dwijnand/sbt-project-graph_2.12_1.0/0.4.0/sbt-project-graph-0.4.0.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/com/dwijnand/sbt-project-graph_2.12_1.0/0.4.0/sbt-project-graph-0.4.0.pom
[error]   not found: https://oss.sonatype.org/content/repositories/releases/com/dwijnand/sbt-project-graph_2.12_1.0/0.4.0/sbt-project-graph-0.4.0.pom
[error]   not found: https://repo.typesafe.com/typesafe/releases/com/dwijnand/sbt-project-graph_2.12_1.0/0.4.0/sbt-project-graph-0.4.0.pom
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.dwijnand/sbt-project-graph/scala_2.12/sbt_1.0/0.4.0/ivys/ivy.xml
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q
[info] shutting down sbt server
ignasi at imslightbend in ~/wip/deleteme/playframework/documentation on master*
$ sbt
[info] Loading settings for project global-plugins from plugins.sbt ...
[info] Loading global plugins from /Users/ignasi/.sbt/1.0/plugins
[info] Loading settings for project plugins from plugins.sbt ...
[info] Loading settings for project playframework-build-build from buildinfo.sbt ...
[info] Loading project definition from /Users/ignasi/wip/deleteme/playframework/project/project
[info] Loading settings for project playframework-build from plugins.sbt ...
[info] Loading project definition from /Users/ignasi/wip/deleteme/playframework/project
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Loading settings for project Play-Framework from build.sbt,version.sbt ...
[info] Resolving key references (38702 settings) ...
[info] Loading project definition from /Users/ignasi/wip/deleteme/playframework/documentation/project
[info] Updating
[info] Resolved  dependencies
[warn]
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.dwijnand:sbt-compat:1.1.0 (scalaVersion=2.12, sbtVersion=1.0)
[warn]
[warn] 	Note: Unresolved dependencies path:
[info] Updating
[info] Resolved  dependencies
[warn]
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.dwijnand:sbt-compat:1.1.0 (scalaVersion=2.12, sbtVersion=1.0)
[warn]
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.dwijnand:sbt-compat;sbtVersion=1.0;scalaVersion=2.12:1.1.0
[error]   Not found
[error]   Not found
[error]   not found: /Users/ignasi/.ivy2/local/com.dwijnand/sbt-compat/scala_2.12/sbt_1.0/1.1.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/dwijnand/sbt-compat_2.12_1.0/1.1.0/sbt-compat-1.1.0.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/com/dwijnand/sbt-compat_2.12_1.0/1.1.0/sbt-compat-1.1.0.pom
[error]   not found: https://oss.sonatype.org/content/repositories/releases/com/dwijnand/sbt-compat_2.12_1.0/1.1.0/sbt-compat-1.1.0.pom
[error]   not found: https://repo.typesafe.com/typesafe/releases/com/dwijnand/sbt-compat_2.12_1.0/1.1.0/sbt-compat-1.1.0.pom
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.dwijnand/sbt-compat/scala_2.12/sbt_1.0/1.1.0/ivys/ivy.xml
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:245)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$34(CoursierDependencyResolution.scala:214)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:214)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:52)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:102)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:115)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:115)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:96)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:129)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2909)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:289)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] sbt.librarymanagement.ResolveException: Error downloading com.dwijnand:sbt-compat;sbtVersion=1.0;scalaVersion=2.12:1.1.0
[error]   Not found
[error]   Not found
[error]   not found: /Users/ignasi/.ivy2/local/com.dwijnand/sbt-compat/scala_2.12/sbt_1.0/1.1.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/dwijnand/sbt-compat_2.12_1.0/1.1.0/sbt-compat-1.1.0.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/com/dwijnand/sbt-compat_2.12_1.0/1.1.0/sbt-compat-1.1.0.pom
[error]   not found: https://oss.sonatype.org/content/repositories/releases/com/dwijnand/sbt-compat_2.12_1.0/1.1.0/sbt-compat-1.1.0.pom
[error]   not found: https://repo.typesafe.com/typesafe/releases/com/dwijnand/sbt-compat_2.12_1.0/1.1.0/sbt-compat-1.1.0.pom
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.dwijnand/sbt-compat/scala_2.12/sbt_1.0/1.1.0/ivys/ivy.xml
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:245)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$34(CoursierDependencyResolution.scala:214)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:214)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:52)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:102)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:115)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:115)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:96)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:129)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2909)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:289)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (ProjectRef(uri("file:///Users/ignasi/wip/deleteme/playframework/"), "Play-Exceptions") / update) sbt.librarymanagement.ResolveException: Error downloading com.dwijnand:sbt-compat;sbtVersion=1.0;scalaVersion=2.12:1.1.0
[error]   Not found
[error]   Not found
[error]   not found: /Users/ignasi/.ivy2/local/com.dwijnand/sbt-compat/scala_2.12/sbt_1.0/1.1.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/dwijnand/sbt-compat_2.12_1.0/1.1.0/sbt-compat-1.1.0.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/com/dwijnand/sbt-compat_2.12_1.0/1.1.0/sbt-compat-1.1.0.pom
[error]   not found: https://oss.sonatype.org/content/repositories/releases/com/dwijnand/sbt-compat_2.12_1.0/1.1.0/sbt-compat-1.1.0.pom
[error]   not found: https://repo.typesafe.com/typesafe/releases/com/dwijnand/sbt-compat_2.12_1.0/1.1.0/sbt-compat-1.1.0.pom
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.dwijnand/sbt-compat/scala_2.12/sbt_1.0/1.1.0/ivys/ivy.xml
[error] (ProjectRef(uri("file:///Users/ignasi/wip/deleteme/playframework/"), "Sbt-Routes-Compiler") / update) sbt.librarymanagement.ResolveException: Error downloading com.dwijnand:sbt-compat;sbtVersion=1.0;scalaVersion=2.12:1.1.0
[error]   Not found
[error]   Not found
[error]   not found: /Users/ignasi/.ivy2/local/com.dwijnand/sbt-compat/scala_2.12/sbt_1.0/1.1.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/dwijnand/sbt-compat_2.12_1.0/1.1.0/sbt-compat-1.1.0.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/com/dwijnand/sbt-compat_2.12_1.0/1.1.0/sbt-compat-1.1.0.pom
[error]   not found: https://oss.sonatype.org/content/repositories/releases/com/dwijnand/sbt-compat_2.12_1.0/1.1.0/sbt-compat-1.1.0.pom
[error]   not found: https://repo.typesafe.com/typesafe/releases/com/dwijnand/sbt-compat_2.12_1.0/1.1.0/sbt-compat-1.1.0.pom
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.dwijnand/sbt-compat/scala_2.12/sbt_1.0/1.1.0/ivys/ivy.xml
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q
```
</details>

**Comment by ignasi35** [comment]
Note: I've been using those plugins globally in other projects already migrated to sbt  `1.3.{0,2}` successfully for several days. It's only those global plugins combined with `playframework/documentation/build.sbt` that reproduce the error.

**Comment by eed3si9n** [comment]
```
[info] Loading project definition from /Users/ignasi/wip/deleteme/playframework/documentation/project
[info] Updating
....
[error] (ProjectRef(uri("file:///Users/ignasi/wip/deleteme/playframework/"), "Play-Exceptions") / update) sbt.librarymanagement.ResolveException: Error downloading com.dwijnand:sbt-project-graph;sbtVersion=1.0;scalaVersion=2.12:0.4.0
[error]   Not found
[error]   Not found
[error]   not found: /Users/ignasi/.ivy2/local/com.dwijnand/sbt-project-graph/scala_2.12/sbt_1.0/0.4.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/dwijnand/sbt-project-graph_2.12_1.0/0.4.0/sbt-project-graph-0.4.0.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/com/dwijnand/sbt-project-graph_2.12_1.0/0.4.0/sbt-project-graph-0.4.0.pom
[error]   not found: https://oss.sonatype.org/content/repositories/releases/com/dwijnand/sbt-project-graph_2.12_1.0/0.4.0/sbt-project-graph-0.4.0.pom
[error]   not found: https://repo.typesafe.com/typesafe/releases/com/dwijnand/sbt-project-graph_2.12_1.0/0.4.0/sbt-project-graph-0.4.0.pom
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.dwijnand/sbt-project-graph/scala_2.12/sbt_1.0/0.4.0/ivys/ivy.xml
```

so it seems like it somehow forgets that Play-Exceptions is an sbt plugin and that it should have the resolvers for other plugins.

**Comment by marcospereira** [comment]
> so it seems like it somehow forgets that Play-Exceptions is an sbt plugin and that it should have the resolvers for other plugins.

Wait, but `Play-Exceptions` is not an sbt plugin:

```bash
sbt ";project Play-Exceptions; show sbtPlugin"
```

Outputs:

```
[info] Loading settings for project global-plugins from metals.sbt ...
[info] Loading global plugins from /Users/marcospereira/.sbt/1.0/plugins
[info] Loading settings for project playframework-build-build from buildinfo.sbt ...
[info] Loading project definition from /Users/marcospereira/Lightbend/playframework/playframework/project/project
[info] Loading settings for project playframework-build from plugins.sbt ...
[info] Loading project definition from /Users/marcospereira/Lightbend/playframework/playframework/project
[info] Loading settings for project Play-Framework from version.sbt,build.sbt ...
[info] Resolving key references (31495 settings) ...
[info] Set current project to Play-Framework (in build file:/Users/marcospereira/Lightbend/playframework/playframework/)
[info] Set current project to Play-Exceptions (in build file:/Users/marcospereira/Lightbend/playframework/playframework/)
[info] false
```

Thing is that `Play-Exceptions` does not cross build (`crossPaths := false`).

**Comment by eed3si9n** [comment]
At some point something depends on sbt-compat, and it's not hitting https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.dwijnand/sbt-compat/

**Comment by ignasi35** [comment]
> At some point something depends on sbt-compat, and it's not hitting [repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.dwijnand/sbt-compat](https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.dwijnand/sbt-compat/)

I think one of the global plugins I loaded depends on `sbt-compat` and not Play itself.

Put another way:

1. if I comment out `sbt-dependency-graph` and `sbt-project-graph` from my global plugins the error doesn't manifest.
2. when I use `sbt-dependency-graph` globally, (I think) I get the `sbt-compat` resolution error.
3. when I use `sbt-project-graph` globally, (I am 100% certain) I get at least `sbt-project-graph` resolution error (and maybe also `sbt-compat`?).

I didn't keep track of all possible combinations and error messages but so far removing those two plugins from my global list of plugins solved the issue.


Note the issue manifests `update`ing projects defined in `playframework/builds.sbt` but referenced from `playframework/documentation/builds.sbt`. Also, those of those cross-reference projects are sbt plugins but others are not as @marcospereira pointed out on his previous comment.

**Comment by eed3si9n** [comment]
That sounds as if `$HOME/.sbt/1.0/plugins/plugins.sbt` is acting as if it's `$HOME/.sbt/1.0/global.sbt`.

**Comment by ignasi35** [comment]
> That sounds as if `$HOME/.sbt/1.0/plugins/plugins.sbt` is acting as if it's `$HOME/.sbt/1.0/global.sbt`.

I thought that was a feature so, yeah, I've been using `$HOME/.sbt/1.0/plugins/plugins.sbt` as if it's `$HOME/.sbt/1.0/global.sbt`

**Comment by eed3si9n** [comment]
Adding plugin declarations to `$HOME/.sbt/1.0/plugins/plugins.sbt` is perfectly fine.
https://www.scala-sbt.org/1.x/docs/Global-Settings.html#Global+Settings+using+a+Global+Plugin

What I don't understand is how that's affecting `Play-Exceptions / update`.

**Comment by ignasi35** [comment]
> Wait, but `Play-Exceptions` is not an sbt plugin:

It is not, but it's a dependency of `sbt-plugin`. 🤔

```
 sbt-plugin   depends on sbt-routes-compiler and run-support 
 run-support  depends on build-link
 buid-link    depends on play-exceptions
 sbt-routes-compiler doesn't depend on other projects
 play-exceptions     doesn't depend on other projects
```

So, going back to the original error:

```
[error] stack trace is suppressed; run last ProjectRef(uri("file:///Users/ignasi/wip/deleteme/playframework/"), "Play-Exceptions") / update for the full output
[error] stack trace is suppressed; run last ProjectRef(uri("file:///Users/ignasi/wip/deleteme/playframework/"), "Sbt-Routes-Compiler") / update for the full output
```

One thing `sbt-routes-compiler` and `play-exceptions` have in common is that both are leaves on the dependency tree of `sbt-plugin`.

**Comment by akozumpl** [comment]
Hitting the same, whenever I have

```
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.2")
```

among `~/.sbt/1.0/plugins.sbt` I get the original error. This worked prior to 1.3.0, still can reproduce today with 1.3.3. I can workaround by:

```
resolvers += Resolver.sbtPluginRepo("releases")
```

Of note, the package `publishLocal` then produces has sbt-dependency-graph declared as a dependency in it's pom file. Is that expected? That's not how I understood https://www.scala-sbt.org/1.x/docs/Using-Plugins.html#Global+plugins.

**Comment by eed3si9n** [comment]
> Of note, the package `publishLocal` then produces has sbt-dependency-graph declared as a dependency in it's pom file. Is that expected? 

No, that doesn't make any sense.

**Comment by eed3si9n** [comment]
I am closing this hoping that this is no longer relevant / needed.
