### ISSUE TITLE
[1.3.2] Forward incompatibility with sbt 1.2.8

### ISSUE THREAD

**Issue by albuch** [sbt/sbt#5154]
## steps
sbt version: *1.3.2*
* Publish plugin with sbt 1.3.2 that imports `sbt._`
* Run plugin with sbt 1.2.8

## problem
Several exceptions to classes or methods not found.
```
[error] java.lang.NoSuchMethodError: sbt.package$.fileJsonFormatter()Lsjsonnew/JsonFormat;
[error] 	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckKeys.dependencyCheckScanSet(DependencyCheckKeys.scala:15)
[error] 	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckKeys.dependencyCheckScanSet$(DependencyCheckKeys.scala:15)
[error] 	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$autoImport$.dependencyCheckScanSet$lzycompute(DependencyCheckPlugin.scala:20)
[error] 	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$autoImport$.dependencyCheckScanSet(DependencyCheckPlugin.scala:20)
[error] 	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$.projectSettings$lzycompute(DependencyCheckPlugin.scala:36)
[error] 	at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$.projectSettings(DependencyCheckPlugin.scala:28)
[error] 	at sbt.internal.Load$.$anonfun$resolveProject$3(Load.scala:1062)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:240)
[error] 	at scala.collection.immutable.List.foreach(List.scala:388)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:240)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:237)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:351)
[error] 	at sbt.internal.Load$.autoPluginSettings$1(Load.scala:1062)
[error] 	at sbt.internal.Load$.expandSettings$1(Load.scala:1081)
[error] 	at sbt.internal.Load$.$anonfun$resolveProject$10(Load.scala:1084)
[error] 	at scala.collection.IndexedSeqOptimized.foldLeft(IndexedSeqOptimized.scala:56)
[error] 	at scala.collection.IndexedSeqOptimized.foldLeft$(IndexedSeqOptimized.scala:64)
[error] 	at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:37)
[error] 	at scala.collection.TraversableOnce.$div$colon(TraversableOnce.scala:150)
[error] 	at scala.collection.TraversableOnce.$div$colon$(TraversableOnce.scala:150)
[error] 	at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:104)
[error] 	at sbt.internal.Load$.expandSettings$1(Load.scala:1083)
[error] 	at sbt.internal.Load$.$anonfun$resolveProject$1(Load.scala:1097)
[error] 	at sbt.internal.Load$.timed(Load.scala:1395)
[error] 	at sbt.internal.Load$.resolveProject(Load.scala:1051)
[error] 	at sbt.internal.Load$.finalizeProject$1(Load.scala:886)
[error] 	at sbt.internal.Load$.$anonfun$loadTransitive$15(Load.scala:989)
[error] 	at sbt.internal.Load$.timed(Load.scala:1395)
[error] 	at sbt.internal.Load$.loadTransitive(Load.scala:989)
[error] 	at sbt.internal.Load$.loadProjects$1(Load.scala:726)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$11(Load.scala:729)
[error] 	at sbt.internal.Load$.timed(Load.scala:1395)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:729)
[error] 	at sbt.internal.Load$.timed(Load.scala:1395)
[error] 	at sbt.internal.Load$.loadUnit(Load.scala:688)
[error] 	at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:484)
[error] 	at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:176)
[error] 	at sbt.internal.BuildLoader.apply(BuildLoader.scala:241)
[error] 	at sbt.internal.Load$.loadURI$1(Load.scala:546)
[error] 	at sbt.internal.Load$.loadAll(Load.scala:562)
[error] 	at sbt.internal.Load$.loadURI(Load.scala:492)
[error] 	at sbt.internal.Load$.load(Load.scala:471)
[error] 	at sbt.internal.Load$.$anonfun$apply$1(Load.scala:251)
[error] 	at sbt.internal.Load$.timed(Load.scala:1395)
[error] 	at sbt.internal.Load$.apply(Load.scala:251)
[error] 	at sbt.internal.Load$.defaultLoad(Load.scala:69)
[error] 	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:829)
[error] 	at sbt.BuiltinCommands$.doLoadProject(Main.scala:829)
[error] 	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:800)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:142)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:137)
[error] 	at sbt.Command$.process(Command.scala:181)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:151)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:139)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:246)
[error] 	at sbt.State$$anon$1.process(State.scala:250)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:139)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:139)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:132)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:35)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:138)
[error] 	at sbt.xMain.run(Main.scala:89)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:18)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
```
Relevant class at https://github.com/albuch/sbt-dependency-check/blob/master/src/main/scala/net/vonbuchholtz/sbt/dependencycheck/DependencyCheckKeys.scala#L3
``` 
[error] java.lang.NoClassDefFoundError: sbt/io/PathFinderDefaults
[error]         at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$.$anonfun$checkTask$2(DependencyCheckPlugin.scala:298)
[error]         at net.vonbuchholtz.sbt.dependencycheck.DependencyCheckPlugin$.$anonfun$checkTask$2$adapted(DependencyCheckPlugin.scala:261)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
```
## expectation
Publishing a sbt plugin with sbt 1.3.2 without previously changing any sbt API related code that  worked when publishing with sbt 1.2.8 should still run with sbt 1.2.8

## notes
- The first exception I could eliminate by importing only the needed classes/objects. For other exceptions it gets a little more complicated I think.

Downstream issue: https://github.com/albuch/sbt-dependency-check/issues/87

**Comment by nigredo-tori** [comment]
The first part is the same as #5049.

**Comment by eed3si9n** [comment]
@albuch Thanks for the report. The auto capturing of JSON format + making JSON format available is an unfortunate combination. I've posted the workaround in #5049, and I think we capture most of the problem statement in there, so can we close this as a duplicate?

**Comment by albuch** [comment]
@eed3si9n I can't seem to cross build for sbt 0.13.18 anymore when I set the workaround.

```
pluginCrossBuild / sbtVersion := "1.2.8"
crossSbtVersions := Vector("0.13.18", "1.3.2")
```
`^ publishLocal` will only publish the sbt 1.x version twice instead of sbt 0.13 and 1.0

```
IJ]sbt:sbt-dependency-check> ^ publishLocal
[info] Setting `sbtVersion in pluginCrossBuild` to 0.13.18
[info] Set current project to sbt-dependency-check (in build file:/F:/Development/dependency-check-sbt/)
[info] Wrote F:\Development\dependency-check-sbt\target\scala-2.12\sbt-1.0\sbt-dependency-check-1.3.2-SNAPSHOT.pom
[info] :: delivering :: net.vonbuchholtz#sbt-dependency-check;1.3.2-SNAPSHOT :: 1.3.2-SNAPSHOT :: integration :: Sat Oct 05 10:55:20 CEST 2019
[info]  delivering ivy file to F:\Development\dependency-check-sbt\target\scala-2.12\sbt-1.0\ivy-1.3.2-SNAPSHOT.xml
[info]  published sbt-dependency-check to C:\Users\....\.ivy2\local\net.vonbuchholtz\sbt-dependency-check\scala_2.12\sbt_1.0\1.3.2-SNAPSHOT\poms\sbt-dependency-check.pom
[info]  published sbt-dependency-check to C:\Users\....\.ivy2\local\net.vonbuchholtz\sbt-dependency-check\scala_2.12\sbt_1.0\1.3.2-SNAPSHOT\jars\sbt-dependency-check.jar
[info]  published sbt-dependency-check to C:\Users\.....\.ivy2\local\net.vonbuchholtz\sbt-dependency-check\scala_2.12\sbt_1.0\1.3.2-SNAPSHOT\srcs\sbt-dependency-check-sources.jar
[info]  published sbt-dependency-check to C:\Users\.....\.ivy2\local\net.vonbuchholtz\sbt-dependency-check\scala_2.12\sbt_1.0\1.3.2-SNAPSHOT\docs\sbt-dependency-check-javadoc.jar
[info]  published ivy to C:\Users\.....\.ivy2\local\net.vonbuchholtz\sbt-dependency-check\scala_2.12\sbt_1.0\1.3.2-SNAPSHOT\ivys\ivy.xml
[success] Total time: 1 s, completed 05.10.2019 10:55:21
[info] Setting `sbtVersion in pluginCrossBuild` to 1.3.2
[info] Set current project to sbt-dependency-check (in build file:/F:/Development/dependency-check-sbt/)
[info] Wrote F:\Development\dependency-check-sbt\target\scala-2.12\sbt-1.0\sbt-dependency-check-1.3.2-SNAPSHOT.pom
[info] :: delivering :: net.vonbuchholtz#sbt-dependency-check;1.3.2-SNAPSHOT :: 1.3.2-SNAPSHOT :: integration :: Sat Oct 05 10:55:21 CEST 2019
[info]  delivering ivy file to F:\Development\dependency-check-sbt\target\scala-2.12\sbt-1.0\ivy-1.3.2-SNAPSHOT.xml
[info]  published sbt-dependency-check to C:\Users\....\.ivy2\local\net.vonbuchholtz\sbt-dependency-check\scala_2.12\sbt_1.0\1.3.2-SNAPSHOT\poms\sbt-dependency-check.pom
[info]  published sbt-dependency-check to C:\Users\.....\.ivy2\local\net.vonbuchholtz\sbt-dependency-check\scala_2.12\sbt_1.0\1.3.2-SNAPSHOT\jars\sbt-dependency-check.jar
[info]  published sbt-dependency-check to C:\Users\.....\.ivy2\local\net.vonbuchholtz\sbt-dependency-check\scala_2.12\sbt_1.0\1.3.2-SNAPSHOT\srcs\sbt-dependency-check-sources.jar
[info]  published sbt-dependency-check to C:\Users\.....\.ivy2\local\net.vonbuchholtz\sbt-dependency-check\scala_2.12\sbt_1.0\1.3.2-SNAPSHOT\docs\sbt-dependency-check-javadoc.jar
[info]  published ivy to C:\Users\...\.ivy2\local\net.vonbuchholtz\sbt-dependency-check\scala_2.12\sbt_1.0\1.3.2-SNAPSHOT\ivys\ivy.xml
[success] Total time: 1 s, completed 05.10.2019 10:55:22
[info] Setting `sbtVersion in pluginCrossBuild` to scripted
[info] Set current project to sbt-dependency-check (in build file:/F:/Development/dependency-check-sbt/)
```

**Comment by nigredo-tori** [comment]
@albuch, @eed3si9n's "workaround" is to build for 1.2.8. The code he provided doesn't work for cross-building - for that we should just do
```scala
crossSbtVersions := Vector("0.13.18", "1.2.8")
```
