### ISSUE TITLE
IllegalArgumentException after migrating from SBT 1.2.8 to 1.3.3 

### ISSUE THREAD

**Issue by eximius313** [sbt/sbt#5194]
## steps
sbt version: *1.3.3*

## problem
I'm using Play Framework (`2.6.23`) with sbt `1.2.8` and everything runs fine.
When I change sbt to `1.3.3` and type `sbt run`, it fails with:
```
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3962)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3966)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4951)
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4957)
        at com.google.inject.internal.util.StackTraceElements.forMember(StackTraceElements.java:71)
        at com.google.inject.internal.Messages.formatParameter(Messages.java:282)
        at com.google.inject.internal.Messages.formatInjectionPoint(Messages.java:273)
        at com.google.inject.internal.Messages.formatSource(Messages.java:229)
        at com.google.inject.internal.Messages.formatSource(Messages.java:220)
        at com.google.inject.internal.Messages.formatMessages(Messages.java:90)
        at com.google.inject.CreationException.getMessage(CreationException.java:50)
        at play.api.UnexpectedException$$anonfun$$lessinit$greater$1.$anonfun$new$1(Exceptions.scala:13)
        at scala.Option.map(Option.scala:146)
        at play.api.UnexpectedException$$anonfun$$lessinit$greater$1.apply(Exceptions.scala:13)
        at play.api.UnexpectedException$$anonfun$$lessinit$greater$1.apply(Exceptions.scala:13)
        at scala.Option.getOrElse(Option.scala:121)
        at play.api.UnexpectedException.<init>(Exceptions.scala:13)
        at play.core.server.DevServerStart$$anon$1.reload(DevServerStart.scala:193)
        at play.core.server.DevServerStart$$anon$1.get(DevServerStart.scala:125)
        at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:281)
        at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:173)
        at akka.stream.impl.fusing.MapAsyncUnordered$$anon$31.onPush(Ops.scala:1318)
        at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:515)
        at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:478)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:374)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
        at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:474)
        at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:730)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:745)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:655)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592)
        at akka.actor.ActorCell.invoke(ActorCell.scala:561)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
        at akka.dispatch.Mailbox.run(Mailbox.scala:225)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.IllegalArgumentException: null
        at com.google.inject.internal.asm.$ClassReader.<init>(ClassReader.java:160)
        at com.google.inject.internal.asm.$ClassReader.<init>(ClassReader.java:143)
        at com.google.inject.internal.asm.$ClassReader.<init>(ClassReader.java:418)
        at com.google.inject.internal.util.LineNumbers.<init>(LineNumbers.java:64)
        at com.google.inject.internal.util.StackTraceElements$1.load(StackTraceElements.java:49)
        at com.google.inject.internal.util.StackTraceElements$1.load(StackTraceElements.java:45)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3523)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2249)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2132)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
        ... 42 common frames omitted
```

## expectation
It runs fine just like `1.2.8`

**Comment by eed3si9n** [comment]
@eximius313 Thanks for the report. Following https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md#what-to-report could you elaborate on the reproduction steps? Does this happen with any Play app, for example created using https://github.com/playframework/play-scala-seed.g8?

**Comment by eximius313** [comment]
Ok, here is one of the weirdest things that happened to me..
1) I copied my project to different location on disk
2) I was removing files/configs in order to pinpoint the place which causes the error.
3) I was making git commit after each change
4) When it stared to work, I got back one commit and.... it still worked
5) I got back several commits back and it worked
6) I returned to the main project (nothing was touched there) - and it worked

Do you have any idea how to explain this? Does `sbt` stores it's state somewhere??

**Comment by eed3si9n** [comment]
> Does `sbt` stores it's state somewhere??

The state of tasks are normally in `target` directory, but potentially `project/target` or the state of Ivy or Coursier cache would affect the outcome of the build.

I am closing this due to inactivity, but if this is still relevant let us know with more details (reproduction steps etc).
