### ISSUE TITLE
dependencyOverrides being ignored for test task on 1.2.8 / fork=true

### ISSUE THREAD

**Issue by mvallebr** [sbt/sbt#5201]
## steps
sbt version: 1.2.8

1. Create a project using the given `build.sbt` bellow
2. run `sbt evicted` to see no warnings are generated
3. run `sbt test` to see warning `[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.`
4. Check the stacktrace when tests run to confirm wrong version of dependency has been used

## problem

Given the sbt file:

```scala
name := "something"
organization := "something.else"
version := "0.1.0"
scalaVersion := "2.11.8"

dependencyOverrides += "commons-beanutils" % "commons-beanutils" % "1.9.4"
dependencyOverrides += "org.apache.hadoop" % "hadoop-common" % "2.8.3"
dependencyOverrides += "com.google.code.findbugs" % "jsr305" % "1.3.9"
dependencyOverrides += "io.netty" % "netty" % "3.9.9.Final"
dependencyOverrides += "com.google.guava" % "guava" % "18.0"

libraryDependencies += "commons-beanutils" % "commons-beanutils" % "1.9.4" force()
libraryDependencies += "org.yaml" % "snakeyaml" % "1.25" force()
libraryDependencies += "org.apache.logging.log4j" % "log4j-core" % "2.12.0" force()
libraryDependencies += "org.apache.commons" % "commons-configuration2" % "2.6" force()
libraryDependencies += "com.amazonaws" % "aws-java-sdk" % "1.11.433" force()
libraryDependencies += "com.oracle" % "ojdbc6" % "11.2.0.4.0" force()
libraryDependencies += "org.scala-lang" % "scala-library" % "2.11.8" force()
libraryDependencies += "org.apache.spark" %% "spark-core" % "2.4.0" force()
libraryDependencies += "org.apache.spark" %% "spark-sql" % "2.4.0" force()
libraryDependencies += "org.apache.spark" %% "spark-hive" % "2.4.0" force()
libraryDependencies += "com.amazonaws" % "aws-java-sdk-s3" % "1.11.77" force()
libraryDependencies += "org.scalikejdbc" %% "scalikejdbc" % "3.3.5" force()
libraryDependencies += "org.coursera" % "dropwizard-metrics-datadog" % "1.1.13" force()
libraryDependencies += "io.circe" %% "circe-core" % "0.11.1" force()
libraryDependencies += "io.circe" %% "circe-generic" % "0.11.1" force()
libraryDependencies += "io.circe" %% "circe-parser" % "0.11.1" force()

libraryDependencies += "org.scalikejdbc" %% "scalikejdbc-test" % "3.3.5" % Test
libraryDependencies += "org.scalatest" %% "scalatest" % "3.0.8" % Test
libraryDependencies += "org.scalamock" %% "scalamock" % "4.4.0" % Test
libraryDependencies += "com.holdenkarau" %% "spark-testing-base" % "2.4.0_0.11.0" % Test

resolvers += Resolver.mavenLocal

// for the urandom thing, check https://stackoverflow.com/questions/6110395/sqlrecoverableexception-i-o-exception-connection-reset
// this is to solve connection reset problems with oracle docker image
javaOptions ++= Seq("-Djava.security.egd=file:/dev/./urandom")
javaOptions ++= Seq("-Dsecurerandom.source=file:/dev/./urandom")

fork := true
```
When I run `sbt test`, one of my tests fail:

```
[error] sbt.ForkMain$ForkError: java.lang.NoSuchMethodError: com.google.common.base.Enums.valueOfFunction(Ljava/lang/Class;)Lcom/google/common/base/Function;
[error] 	at org.apache.hadoop.fs.shell.XAttrCommands$GetfattrCommand.<clinit>(XAttrCommands.java:69)
[error] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
```

I specified version `2.8.3` for `hadoop-common`, in the sbt file, which doesn't use `Enums`. 
If I look at `hadoop-common` version `2.6.3`, I can see the use of use of `Enum` there, at `XAttrCommands.java:69`. 

So sbt is clearly using version `2.6.3` instead the one specified in `dependencyOverrides`.

## expectation

sbt should run scala test using `dependencyOverrides += "org.apache.hadoop" % "hadoop-common" % "2.8.3"` - which is not happening.

## notes

Output of `sbt evicted` is at https://gist.github.com/mvallebr/93d83ff18a59d542291a09f84005126a

**Comment by eed3si9n** [comment]
@mvallebr Thanks for the report. Does this happen on sbt 1.3.3?

**Comment by mvallebr** [comment]
Hi, 

I just tested that by using the following procedure: 

1. I changed the contents of `build.properties` to `sbt.version = 1.3.3`
2. I've run `sbt update`
3. I've run `sbt test`

Same problem.

I haven't upgraded the system version of sbt though, my brew (mac) says the system version is `1.2.8`, here is the output of `sbt about` outside of my project folder:

```
$ sbt about
[warn] No sbt.version set in project/build.properties, base directory: /Users/marcelo.valle/testData
[info] Loading global plugins from /Users/marcelo.valle/.sbt/1.0/plugins
[info] Set current project to testdata (in build file:/Users/marcelo.valle/testData/)
[info] This is sbt 1.2.8
[info] The current project is ProjectRef(uri("file:/Users/marcelo.valle/testData/"), "testdata") 0.1.0-SNAPSHOT
[info] The current project is built against Scala 2.12.7
[info] Available Plugins
[info]  - sbt.ScriptedPlugin
[info]  - sbt.plugins.CorePlugin
[info]  - sbt.plugins.Giter8TemplatePlugin
[info]  - sbt.plugins.IvyPlugin
[info]  - sbt.plugins.JUnitXmlReportPlugin
[info]  - sbt.plugins.JvmPlugin
[info]  - sbt.plugins.SbtPlugin
[info] sbt, sbt plugins, and build definitions are using Scala 2.12.7
```

and here is the output inside my project folder:

```
$ sbt about
[info] Loading global plugins from /Users/marcelo.valle/.sbt/1.0/plugins
[info] Loading settings for project my-project-build from plugins.sbt ...
[info] Loading project definition from /Users/marcelo.valle/git/my-project/project
[info] Loading settings for project dsrf from build.sbt ...
[info] Loading settings for project my-project from build.sbt ...
[info] Set current project to my-project (in build file:/Users/marcelo.valle/git/my-project/)
[info] This is sbt 1.3.3
[info] The current project is ProjectRef(uri("file:/Users/marcelo.valle/git/my-project/"), "my-project") 0.1.0
[info] The current project is built against Scala 2.11.8
[info] Available Plugins
[info]  - net.virtualvoid.sbt.graph.DependencyGraphPlugin
[info]  - sbt.ScriptedPlugin
[info]  - sbt.plugins.CorePlugin
[info]  - sbt.plugins.Giter8TemplatePlugin
[info]  - sbt.plugins.IvyPlugin
[info]  - sbt.plugins.JUnitXmlReportPlugin
[info]  - sbt.plugins.JvmPlugin
[info]  - sbt.plugins.SbtPlugin
[info]  - sbt.plugins.SemanticdbPlugin
[info]  - sbtassembly.AssemblyPlugin
[info] sbt, sbt plugins, and build definitions are using Scala 2.12.10
```
