### ISSUE TITLE
Parsers.NotQuoted doesn't pass the whole string on .map()

### ISSUE THREAD

**Issue by fspillner** [sbt/sbt#5213]
## steps
sbt version: 1.3.3

## problem
I've updated to sbt 1.3.3 and one of the custom parser has been failed due to Parsers.NotQuoted combinator because it doesn't pass the whole string as argument onto the map() function.

## expectation
It should pass the whole string onto the map() function.

## notes
I've switched to flatMap and it works as expected.

**Comment by eed3si9n** [comment]
@fspillner Thanks for the report. Do you have a simple snippet that would reproduce the issue?

**Comment by fspillner** [comment]
First, I've tried to reproduce this bug directly with the parser combinators, but the property test passed e.g.

```scala
// in $ROOT$/internal/util-complete/src/test/scala/DefaultParsersSpec.scala
property("parser == parser.map(identity)") = forAll(genID) { s =>
  matches(NotQuoted.map(identity), s)
}
```

And then, I've created an AutoPlugin and finally I'm able to reproduce the bug. The plugin code looks like:

```scala
package org.example.sbt

import sbt._
import sbt.Keys._
import sbt.complete._
import sbt.complete.DefaultParsers._
import sbt.plugins.JvmPlugin

object TestPlugin extends AutoPlugin {

  override def trigger = allRequirements
  override def requires = JvmPlugin

  object autoImport {
    val exampleTask: InputKey[Unit] =
      inputKey[Unit]("Execute an example task")
  }

  import autoImport._

  private val exampleTaskParser: Def.Initialize[Parser[String]] = Def.setting {
    val arguments = Map("first" -> "passed")
    (Space ~> NotQuoted).map(arg => arguments(arg))
  }

  override lazy val projectSettings = Seq(
    exampleTask := streams.value.log.info(exampleTaskParser.parsed.toString)
  )

  override lazy val buildSettings = Seq()
  override lazy val globalSettings = Seq()
}
```

The following sbt command fails then:

`exampleTask first`

And the output log:

```
[debug] > Exec(exampleTask first, Some(d82ac9bd-e207-42af-b8d6-72ca2a35c425), Some(CommandSource(console0)))
[debug] Evaluating tasks: checkBuildSources
[debug] Running task... Cancel: Signal, check cycles: false, forcegc: true
[error] java.util.NoSuchElementException: key not found: f
[error]         at scala.collection.immutable.Map$Map1.apply(Map.scala:114)
[error] 	at org.example.sbt.TestPlugin$.$anonfun$exampleTaskParser$2(TestPlugin.scala:23)
[error] 	at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
[error] 	at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
[error] 	at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
[error] 	at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
[error] 	at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
[error] 	at sbt.internal.util.complete.Parser$Value.map(Parser.scala:167)
[error] 	at sbt.internal.util.complete.MapParser.resultEmpty$lzycompute(Parser.scala:766)
[error] 	at sbt.internal.util.complete.MapParser.resultEmpty(Parser.scala:766)
[error] 	at sbt.internal.util.complete.ParserSeq.$anonfun$resultEmpty$6(Parser.scala:722)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
[error] 	at scala.collection.immutable.List.map(List.scala:298)
[error] 	at sbt.internal.util.complete.ParserSeq.resultEmpty$lzycompute(Parser.scala:722)
[error] 	at sbt.internal.util.complete.ParserSeq.resultEmpty(Parser.scala:721)
[error] 	at sbt.internal.util.complete.MapParser.resultEmpty$lzycompute(Parser.scala:766)
[error] 	at sbt.internal.util.complete.MapParser.resultEmpty(Parser.scala:766)
[error] 	at sbt.internal.util.complete.MatchedString.resultEmpty(Parser.scala:796)
[error] 	at sbt.internal.util.complete.And.resultEmpty$lzycompute(Parser.scala:824)
[error] 	at sbt.internal.util.complete.And.resultEmpty(Parser.scala:824)
[error] 	at sbt.internal.util.complete.HomParser.resultEmpty$lzycompute(Parser.scala:704)
[error] 	at sbt.internal.util.complete.HomParser.resultEmpty(Parser.scala:704)
[error] 	at sbt.internal.util.complete.MapParser.resultEmpty$lzycompute(Parser.scala:766)
[error] 	at sbt.internal.util.complete.MapParser.resultEmpty(Parser.scala:766)
[error] 	at sbt.internal.util.complete.And.resultEmpty$lzycompute(Parser.scala:824)
[error] 	at sbt.internal.util.complete.And.resultEmpty(Parser.scala:824)
[error] 	at sbt.internal.util.complete.SeqParser.derive(Parser.scala:691)
[error] 	at sbt.internal.util.complete.BindParser.derive(Parser.scala:752)
[error] 	at sbt.internal.util.complete.MapParser.derive(Parser.scala:767)
[error] 	at sbt.internal.util.complete.HomParser.derive(Parser.scala:703)
[error] 	at sbt.internal.util.complete.ParserMain.loop$1(Parser.scala:483)
[error] 	at sbt.internal.util.complete.ParserMain.result(Parser.scala:485)
[error] 	at sbt.internal.util.complete.ParserMain.result$(Parser.scala:471)
[error] 	at sbt.internal.util.complete.Parser$.result(Parser.scala:138)
[error] 	at sbt.internal.util.complete.ParserMain.parse(Parser.scala:434)
[error] 	at sbt.internal.util.complete.ParserMain.parse$(Parser.scala:433)
[error] 	at sbt.internal.util.complete.DefaultParsers$.parse(Parsers.scala:344)
[error] 	at sbt.Command$.process(Command.scala:186)
[error] 	at sbt.MainLoop$.process$1(MainLoop.scala:185)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:218)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:142)
[error] 	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:273)
[error] 	at sbt.State$StateOpsImpl$.process$extension(State.scala:277)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:142)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:142)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:133)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:111)
[error] 	at sbt.io.Using.apply(Using.scala:27)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:105)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:60)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:45)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:36)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:132)
[error] 	at sbt.xMain$.run(Main.scala:67)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:46)
[error] 	at sbt.xMain.run(Main.scala:39)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:130)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:111)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:119)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:20)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:18)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] java.util.NoSuchElementException: key not found: f
```

I hope this is helpful enough for you?

**Comment by fspillner** [comment]
It works as expected if I use `StringEscapable` instead of `NotQuoted` and call the sbt task with `exampleTask "first"`.

**Comment by fspillner** [comment]
I had deeper look and I'm now sure that it's not a bug :-) 

I just used the parser in the wrong way. I should have use flatMap if I have to deal with possible errors / exceptions.

The behavior how the sbt command works has been changed in sbt 1.3 (it calls the flatMap/map multiple times with possible values) e.g.:

build.sbt
``` 
  private val exampleTaskParser: Def.Initialize[State => Parser[String]] = Def.setting { (state: State) =>
    val arguments = Map("firstt"-> "passed but firstt", "first" -> "passed")
    (Space ~> token(NotQuoted)).flatMap {
      case label if arguments.contains(label) => success(arguments(label))
      case s =>
        state.log.info(s)
        failure("Argument not found")
    }
  }
```

The log output of `sbt exampleTask first`:

```
[info] f
[info] f
[info] f
[info] fi
[info] fi
[info] fi
[info] fir
[info] fir
[info] fir
[info] firs
[info] firs
[info] firs
[info] passed
```
