### ISSUE TITLE
Sbt deadlock when running test in root project aggregating 5 subprojects

### ISSUE THREAD

**Issue by nafg** [sbt/sbt#522]
Sbt 0.12.0.

Ctrl-\ tells me:

```
Found one Java-level deadlock:
=============================
"pool-10-thread-3":
  waiting to lock monitor 0x00007f26d81203c0 (object 0x0000000702b0e7a0, a sbt.classpath.ClasspathUtilities$$anon$1),
  which is held by "pool-10-thread-1"
"pool-10-thread-1":
  waiting to lock monitor 0x00007f26f8049d48 (object 0x00000007023718c8, a sbt.classpath.ClasspathUtilities$$anon$1),
  which is held by "pool-10-thread-3"

Java stack information for the threads listed above:
===================================================
"pool-10-thread-3":
        at org.zeroturnaround.jrebel.lift.cbp.ScalaSingletonProxySupportCBP.process(ScalaSingletonProxySupportCBP.java:23)
        at org.zeroturnaround.javarebel.integration.support.JavassistClassBytecodeProcessor.process(JRebel:59)
        at org.zeroturnaround.javarebel.integration.util.WeakUtil$WeakClassBytecodeProcessorAdapter.process(JRebel:210)
        at com.zeroturnaround.javarebel.SDKIntegrationImpl.processManagedClass(JRebel:534)
        at com.zeroturnaround.javarebel.xn.a(JRebel:705)
        at com.zeroturnaround.javarebel.xn.a(JRebel:685)
        at com.zeroturnaround.javarebel.xn.a(JRebel:674)
        at com.zeroturnaround.javarebel.oX.processReloadableClass(JRebel:327)
        at com.zeroturnaround.javarebel.SDKIntegrationImpl.runBytecodeProcessors(JRebel:440)
        at com.zeroturnaround.javarebel.java4.RuntimeInstall.transform(JRebel:36)
        at java.lang.ClassLoader.defineClass(ClassLoader.java)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:447)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
        - locked <0x00000007023718c8> (a sbt.classpath.ClasspathUtilities$$anon$1)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.scalatest.tools.ScalaTestFramework$ScalaTestRunner.run(ScalaTestFramework.scala:113)
        at sbt.TestRunner.delegateRun(TestFramework.scala:57)
        at sbt.TestRunner.run(TestFramework.scala:51)
        at sbt.TestRunner.runTest$1(TestFramework.scala:71)
        at sbt.TestRunner.run(TestFramework.scala:80)
        at sbt.TestFramework$$anonfun$6$$anonfun$apply$8$$anonfun$7$$anonfun$apply$9.apply(TestFramework.scala:178)
        at sbt.TestFramework$$anonfun$6$$anonfun$apply$8$$anonfun$7$$anonfun$apply$9.apply(TestFramework.scala:178)
        at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:190)
        at sbt.TestFramework$$anonfun$6$$anonfun$apply$8$$anonfun$7.apply(TestFramework.scala:178)
        at sbt.TestFramework$$anonfun$6$$anonfun$apply$8$$anonfun$7.apply(TestFramework.scala:178)
        at sbt.Tests$$anonfun$makeParallel$1$$anonfun$apply$7.apply(Tests.scala:119)
        at sbt.Tests$$anonfun$makeParallel$1$$anonfun$apply$7.apply(Tests.scala:119)
        at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:47)
        at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:47)
        at sbt.std.Transform$$anon$5.work(System.scala:71)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
        at sbt.Execute.work(Execute.scala:238)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:166)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:166)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:722)
"pool-10-thread-1":
        at org.zeroturnaround.jrebel.lift.cbp.ScalaSingletonProxySupportCBP.process(ScalaSingletonProxySupportCBP.java:23)
        at org.zeroturnaround.javarebel.integration.support.JavassistClassBytecodeProcessor.process(JRebel:59)
        at org.zeroturnaround.javarebel.integration.util.WeakUtil$WeakClassBytecodeProcessorAdapter.process(JRebel:210)
        at com.zeroturnaround.javarebel.SDKIntegrationImpl.processManagedClass(JRebel:534)
        at com.zeroturnaround.javarebel.xn.a(JRebel:705)
        at com.zeroturnaround.javarebel.xn.a(JRebel:685)
        at com.zeroturnaround.javarebel.xn.a(JRebel:674)
        at com.zeroturnaround.javarebel.oX.processReloadableClass(JRebel:327)
        at com.zeroturnaround.javarebel.SDKIntegrationImpl.runBytecodeProcessors(JRebel:440)
        at com.zeroturnaround.javarebel.java4.RuntimeInstall.transform(JRebel:36)
        at java.lang.ClassLoader.defineClass(ClassLoader.java)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:447)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
        - locked <0x0000000702b0e7a0> (a sbt.classpath.ClasspathUtilities$$anon$1)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.scalatest.tools.ScalaTestFramework$ScalaTestRunner.run(ScalaTestFramework.scala:113)
        at sbt.TestRunner.delegateRun(TestFramework.scala:57)
        at sbt.TestRunner.run(TestFramework.scala:51)
        at sbt.TestRunner.runTest$1(TestFramework.scala:71)
        at sbt.TestRunner.run(TestFramework.scala:80)
        at sbt.TestFramework$$anonfun$6$$anonfun$apply$8$$anonfun$7$$anonfun$apply$9.apply(TestFramework.scala:178)
        at sbt.TestFramework$$anonfun$6$$anonfun$apply$8$$anonfun$7$$anonfun$apply$9.apply(TestFramework.scala:178)
        at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:190)
        at sbt.TestFramework$$anonfun$6$$anonfun$apply$8$$anonfun$7.apply(TestFramework.scala:178)
        at sbt.TestFramework$$anonfun$6$$anonfun$apply$8$$anonfun$7.apply(TestFramework.scala:178)
        at sbt.Tests$$anonfun$makeParallel$1$$anonfun$apply$7.apply(Tests.scala:119)
        at sbt.Tests$$anonfun$makeParallel$1$$anonfun$apply$7.apply(Tests.scala:119)
        at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:47)
        at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:47)
        at sbt.std.Transform$$anon$5.work(System.scala:71)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
        at sbt.Execute.work(Execute.scala:238)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:166)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:166)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:722)

Found 1 deadlock.
```

**Comment by ijuma** [comment]
Is forking enabled?

**Comment by nafg** [comment]
@ismael - whatever the default is, I haven't set anything explicitly.

**Comment by harrah** [comment]
The last stack frames are from JRebel, so I don't see how this is a bug in sbt.
