### ISSUE TITLE
stopping sbt requires twice CTRL+C

### ISSUE THREAD

**Issue by robstoll** [sbt/sbt#5226]
## steps
sbt version: 1.3.3
1. start a akka-http app via sbt
2. CTRL+C => exception but sbt / akka still runs
3. CTRL+C => sbt stops

## problem
The following exception occurs for the first CTRL+C
```
Exception in thread "sbt-bg-threads-1" java.util.concurrent.RejectedExecutionException
	at java.base/java.util.concurrent.ForkJoinPool.externalPush(ForkJoinPool.java:1880)
	at java.base/java.util.concurrent.ForkJoinPool.externalSubmit(ForkJoinPool.java:1921)
	at java.base/java.util.concurrent.ForkJoinPool.execute(ForkJoinPool.java:2453)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:24)
	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.$anonfun$cleanup$1(DefaultBackgroundJobService.scala:390)
	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.$anonfun$cleanup$1$adapted(DefaultBackgroundJobService.scala:389)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.cleanup(DefaultBackgroundJobService.scala:389)
	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:359)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

## expectation
It should stop immediately

## notes
This behaviour changed when we updated sbt from 1.2.8 to 1.3.0 (maybe with 1.3.2)

**Comment by rawyler** [comment]
This is especially tricky when trying to kill the sbt process via script.

**Comment by turb** [comment]
May be related: after an update to SBT 1.3.3, Play! framework cannot be stopped using CTRL-C when launched using `sbt run`.

It only logs `[warn] Canceling execution...` and does not stop. I forces to kill the process.

Reverting to 1.2.8 fixes the problem. Going to 1.3.0 makes it happen again.

**Comment by ma3574** [comment]
Seeing this too on sbt 1.3.3 with AKKA microservices

**Comment by eed3si9n** [comment]
@robstoll Thanks for the report. This is one of sbt 1.3.x feature we added, which is to allow Ctrl-C to cancel the running task.

If you want the older behavior, you can do this:

```scala
Global / cancelable := false
```

**Comment by azolotko** [comment]
@eed3si9n This seems to be caused by `StandardMain.executionContext` being shutdown by `StandardMain.closeRunnable`
before `BackgroundRunnable.cleanup()` gets its chance to execute the callbacks of `stopListeners` on it:

https://github.com/sbt/sbt/blob/v1.3.8/main/src/main/scala/sbt/Main.scala#L123

https://github.com/sbt/sbt/blob/v1.3.8/main/src/main/scala/sbt/internal/DefaultBackgroundJobService.scala#L390

This leads to an infinite loop in `AbstractBackgroundJobService.shutdown()` because the job is never removed from `jobSet` (should be done by a `stopListeners` callback):

https://github.com/sbt/sbt/blob/v1.3.8/main/src/main/scala/sbt/internal/DefaultBackgroundJobService.scala#L390

Should the `stopListeners` callbacks be executed on the `AbstractBackgroundJobService.pool` instead? It seems to be live just as long as all the jobs and their callback are executed:

https://github.com/sbt/sbt/blob/v1.3.8/main/src/main/scala/sbt/internal/DefaultBackgroundJobService.scala#L168

I’ll create a PR to address this.
