### ISSUE TITLE
autoScalaLibrary :=false and 2.10.0-...

### ISSUE THREAD

**Issue by mbiely** [sbt/sbt#524]
I have checked with both the 0.13 snapshot and 0.12 versions of sbt, and against a couple of different versions of scala-2.10.0
(AFAIR at least M4-M6)

When I have 

```
scalaVersion := "2.10.0-M6"

autoScalaLibrary := false
```

then I get MissingRequirementError (full stacktrace below) during the compilation stage. I guess
that when autoScalaLibrary too many dependencies are removed from the classpath ... or conversely 
scala-reflect is not added, which seems to be the missing jar. 

Full Stacktrace: 

```
[info] Compiling 1 Scala source to /Users/biely/src/sbt-with-2.10-M6/target/scala-2.10/classes...
scala.reflect.internal.MissingRequirementError: object scala.runtime in compiler mirror not found.
    at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:16)
    at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:17)
    at scala.reflect.internal.Mirrors$RootsBase$$anonfun$getModuleOrClass$3.apply(Mirrors.scala:45)
    at scala.reflect.internal.Mirrors$RootsBase$$anonfun$getModuleOrClass$3.apply(Mirrors.scala:45)
    at scala.reflect.internal.Symbols$Symbol.orElse(Symbols.scala:2332)
    at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:44)
    at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:36)
    at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:57)
    at scala.reflect.internal.Mirrors$RootsBase.getPackage(Mirrors.scala:168)
    at scala.reflect.internal.Mirrors$RootsBase.getRequiredPackage(Mirrors.scala:171)
    at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackage$lzycompute(Definitions.scala:189)
    at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackage(Definitions.scala:189)
    at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackageClass$lzycompute(Definitions.scala:190)
    at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackageClass(Definitions.scala:190)
    at scala.reflect.internal.Definitions$DefinitionsClass.AnnotationDefaultAttr$lzycompute(Definitions.scala:966)
    at scala.reflect.internal.Definitions$DefinitionsClass.AnnotationDefaultAttr(Definitions.scala:965)
    at scala.reflect.internal.Definitions$DefinitionsClass.magicSymbols$lzycompute(Definitions.scala:1143)
    at scala.reflect.internal.Definitions$DefinitionsClass.magicSymbols(Definitions.scala:1142)
    at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1238)
    at scala.tools.nsc.Global$Run.<init>(Global.scala:1284)
    at xsbt.CachedCompiler0.run(CompilerInterface.scala:87)
    at xsbt.CachedCompiler0.run(CompilerInterface.scala:72)
    at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:73)
    at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:35)
    at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:29)
    at sbt.compiler.AggressiveCompile$$anonfun$4$$anonfun$compileScala$1$1.apply$mcV$sp(AggressiveCompile.scala:71)
    at sbt.compiler.AggressiveCompile$$anonfun$4$$anonfun$compileScala$1$1.apply(AggressiveCompile.scala:71)
    at sbt.compiler.AggressiveCompile$$anonfun$4$$anonfun$compileScala$1$1.apply(AggressiveCompile.scala:71)
    at sbt.compiler.AggressiveCompile.sbt$compiler$AggressiveCompile$$timed(AggressiveCompile.scala:101)
    at sbt.compiler.AggressiveCompile$$anonfun$4.compileScala$1(AggressiveCompile.scala:70)
    at sbt.compiler.AggressiveCompile$$anonfun$4.apply(AggressiveCompile.scala:88)
    at sbt.compiler.AggressiveCompile$$anonfun$4.apply(AggressiveCompile.scala:60)
    at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:24)
    at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:22)
    at sbt.inc.Incremental$.cycle(Incremental.scala:39)
    at sbt.inc.Incremental$.compile(Incremental.scala:26)
    at sbt.inc.IncrementalCompile$.apply(Compile.scala:20)
    at sbt.compiler.AggressiveCompile.compile2(AggressiveCompile.scala:96)
    at sbt.compiler.AggressiveCompile.compile1(AggressiveCompile.scala:44)
    at sbt.compiler.AggressiveCompile.apply(AggressiveCompile.scala:31)
    at sbt.Compiler$.apply(Compiler.scala:79)
    at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:571)
    at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:571)
    at sbt.Scoped$$anonfun$hf2$1.apply(Structure.scala:578)
    at sbt.Scoped$$anonfun$hf2$1.apply(Structure.scala:578)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:49)
    at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
    at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$5.work(System.scala:71)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.Execute.work(Execute.scala:238)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:680)
[error] (compile:compile) scala.reflect.internal.MissingRequirementError: object scala.runtime in compiler mirror not found.
[error] Total time: 2 s, completed Aug 21, 2012 2:09:44 PM
```

**Comment by harrah** [comment]
If you disable `autoScalaLibrary`, you need to get the Scala library and other necessary jars on the classpath yourself.

**Comment by mbiely** [comment]
ok. Then my understanding of `autoScalaLibrary` was wrong ... I wasn't aware that that holds also for building. (I thought it just removes the scala libraries from dependencies).

**Comment by harrah** [comment]
That is indeed all `autoScalaLibrary` does.  You need the Scala library on the classpath, though, and if it isn't a managed dependency, sbt doesn't know where to get it.
