### ISSUE TITLE
NoSuchFileException on files in `classes.bak` from `~compile`

### ISSUE THREAD

**Issue by Blaisorblade** [sbt/sbt#5280]
## steps
sbt version: 1.2.8

- set `scalaSource in Compile := baseDirectory.value` in `build.sbt` (full config. below)
- run `~compile`

Configuration
`build.sbt`:
```
scalaVersion := "0.20.0-RC1"

scalacOptions ++= Seq("-feature", "-deprecation")

scalaSource in Compile := baseDirectory.value
```

`project/plugins.sbt`:
```
addSbtPlugin("ch.epfl.lamp" % "sbt-dotty" % "0.3.4")
```

## problem

Today, maybe because I set `scalaSource in Compile := baseDirectory.value`, when running `~compile` in a small project (using dotty, tho that might be not relevant to the stacktrace since it only mentions sbt), I sometimes get the following stacktrace:
```
2. Waiting for source changes in project scala-examples... (press enter to interrupt)
Exception in thread "watch-state-event-thread-7" java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /Users/pgiarrusso/git/Coq/dot-iris/scala-examples/target/scala-0.20/classes.bak/sbt2346685002098359091.class
	at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:88)
	at java.nio.file.FileTreeIterator.hasNext(FileTreeIterator.java:104)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:295)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:207)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:170)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:301)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:39)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:507)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:454)
	at scala.collection.Iterator.foreach(Iterator.scala:937)
	at scala.collection.Iterator.foreach$(Iterator.scala:937)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:58)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:49)
	at scala.collection.immutable.VectorBuilder.$plus$plus$eq(Vector.scala:658)
	at scala.collection.immutable.VectorBuilder.$plus$plus$eq(Vector.scala:635)
	at scala.collection.TraversableOnce.to(TraversableOnce.scala:309)
	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:307)
	at scala.collection.AbstractIterator.to(Iterator.scala:1425)
	at scala.collection.TraversableOnce.toIndexedSeq(TraversableOnce.scala:299)
	at scala.collection.TraversableOnce.toIndexedSeq$(TraversableOnce.scala:299)
	at scala.collection.AbstractIterator.toIndexedSeq(Iterator.scala:1425)
	at sbt.internal.io.EventMonitor$$anon$1.filesForNewDirectory(EventMonitor.scala:218)
	at sbt.internal.io.EventMonitor$$anon$1.$anonfun$getFilesForKey$5(EventMonitor.scala:153)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:240)
	at scala.collection.Iterator.foreach(Iterator.scala:937)
	at scala.collection.Iterator.foreach$(Iterator.scala:937)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
	at scala.collection.IterableLike.foreach(IterableLike.scala:70)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:240)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:237)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at sbt.internal.io.EventMonitor$$anon$1.getFilesForKey(EventMonitor.scala:153)
	at sbt.internal.io.EventMonitor$$anon$1.loop(EventMonitor.scala:132)
	at sbt.internal.io.EventMonitor$Looper.runImpl(EventMonitor.scala:283)
	at sbt.internal.io.EventMonitor$Looper.run(EventMonitor.scala:293)
Caused by: java.nio.file.NoSuchFileException: /Users/pgiarrusso/git/Coq/dot-iris/scala-examples/target/scala-0.20/classes.bak/sbt2346685002098359091.class
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.nio.file.FileTreeWalker.next(FileTreeWalker.java:372)
	at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:84)
	... 39 more
[info] Compiling 2 Scala sources to /Users/pgiarrusso/git/Coq/dot-iris/scala-examples/target/scala-0.20/classes ...
[error] -- Error: /Users/pgiarrusso/git/Coq/dot-iris/scala-examples/coqTranslation/fromPDotMutualRecV.scala:37:8
[error] 37 |    val AnyType : Type = upcast(0) // new {}
[error]    |        ^
[error]    |error overriding value AnyType in trait Types of type typing_unstamped_derivedV.Later[Type];
[error]    |  value AnyType of type Type has incompatible type
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 0 s, completed Dec 10, 2019 1:31:45 AM
3. Waiting for source changes in project scala-examples... (press enter to interrupt)
```

When I do, `~compile` stops listening to source changes till I run `~compile` again (which might retrigger this error). After a while, restarting sbt stopped the error from manifesting.

## expectation

`~compile` should work as specified and not print such stacktraces.

## notes
OS: macOS 10.14.6

**Comment by eatkins** [comment]
Does this happen with sbt 1.3.4? We rewrote watch entirely for 1.3.0 and I'm unlikely to debug issues with older versions myself.

**Comment by Blaisorblade** [comment]
Thanks for the reply!
Upgrading this seems to fix it — tho it was not easy to reproduce in the first place. In doubt, I'm closing.
