### ISSUE TITLE
SBT proxy with basic authentication not working

### ISSUE THREAD

**Issue by ovu** [sbt/sbt#5307]
## steps
sbt version: *insert sbt version*
1.3.4
sbt -v gives the following output.

```
[process_args] java_version = '8'
[sbt_options] declare -a sbt_options=()
# Executing command line:
java
-Dhttp.proxyHost=ProxyServer
-Dhttp.proxyPort=MyPort
-Dhttp.proxyUser=MyUser
-Dhttp.proxyPassword=MyPwd
-Dhttps.proxyHost=ProxyServer
-Dhttps.proxyPort=ThePort
-Dhttps.proxyUser=MyUser
-Dhttps.proxyPassword=MyPwd
-Xms1024m
-Xmx1024m
-Xss4M
-XX:ReservedCodeCacheSize=128m
-jar
/usr/share/sbt/bin/sbt-launch.jar
```

## problem
I am working behind an authenticated proxy and when compiling sbt cannot get 
libraries/dependencies.
I configured the proxy using $JAVA_OPTIONS on Linux (See version above).

When compiling I am getting the error:

```
stack trace is suppressed; run last update for the full output
[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.scala-lang:scala-library:2.12.4
[error]   Not found
[error]   Not found
[error]   not found: /home/diego/.ivy2/local/org.scala-lang/scala-library/2.12.4/ivys/ivy.xml
[error]   download error: Caught java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required" (Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required") while downloading https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.4/scala-libr
```

## expectation
SBT should use basic authentication.

**Comment by eed3si9n** [comment]
Looks like this might be a limitation of Coursier? - https://github.com/coursier/coursier/issues/930

Could you try:

```scala
ThisBuild / useCoursier := false
```

?

**Comment by ovu** [comment]
Thanks @eed3si9n, the workaround worked!
But it is still a bug. Who should fix it? SBT or Coursier?

**Comment by eed3si9n** [comment]
I agree it's still a bug. Since both are open source projects, whoever is invested in this bug should work on it. In the past I've gone into both Coursier and Ivy code base when a bug became a priority.

**Comment by ekrich** [comment]
I have some additional information on this issue related to Basic auth and the redirect need to download plugins - normal dependencies download ok.

```
[error]   download error: Caught java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy
Authentication Required" (Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required") while 
downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-native/sbt-scala-native/scala_2.12/sbt_1.0/0.4.0-
M2/ivys/ivy.xml
... (full error below)
```

I am able to access via `curl` with `-L` required for redirect:

```
$ curl -I -L -v  --proxy-user user:pass  https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-native/sbt-scala-native/scala_2.12/sbt_1.0/0.4.0-M2/ivys/ivy.xml
```

I found this SOF: https://stackoverflow.com/questions/41505219/unable-to-tunnel-through-proxy-proxy-returns-http-1-1-407-via-https
Which points to this Oracle notice for jdk 8 and above about Basic auth excluded: https://www.oracle.com/java/technologies/javase/8u111-relnotes.html

I tried adding the following to `JAVA_OPTS` with no luck. I have the same output as the original issue plus these.

```
-Djdk.http.auth.tunneling.disabledSchemes=
-Djdk.http.auth.proxying.disabledSchemes=
```

Somehow I got this to work using `sbt` `1.4.0-M2` but not `1.3.13`. Now I can not repeat. I can get a normal Scala app to work but not a Scala Native that requires a plugin and thus a redirect via a proxy with Basic auth.

```
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          org.scala-native:sbt-scala-native:0.4.0-M2 (sbtVersion=1.0, scalaVersion=2.12)
[warn]
[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading org.scala-native:sbt-scala-native;sbtVersion=1.0;scalaVersion=2.12:0.4.0-M2
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/org/scala-native/sbt-scala-native_2.12_1.0/0.4.0-M2/sbt-scala-native-0.4.0-M2.pom
[error]   not found: /home/eric/.ivy2/local/org.scala-native/sbt-scala-native/scala_2.12/sbt_1.0/0.4.0-M2/ivys/ivy.xml
[error]   download error: Caught java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required" (Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required") while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-native/sbt-scala-native/scala_2.12/sbt_1.0/0.4.0-M2/ivys/ivy.xml
[error]   download error: Caught java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required" (Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required") while downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-native/sbt-scala-native/scala_2.12/sbt_1.0/0.4.0-M2/ivys/ivy.xml
[error]         at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:249)
[error]         at lmcoursier.CoursierDependencyResolution.$anonfun$update$35(CoursierDependencyResolution.scala:218)
[error]         at scala.util.Either$LeftProjection.map(Either.scala:573)
[error]         at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:218)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:53)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:103)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:116)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:116)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:97)
[error]         at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:130)
[error]         at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:3118)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:210)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:52)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.scala-native:sbt-scala-native;sbtVersion=1.0;scalaVersion=2.12:0.4.0-M2
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/org/scala-native/sbt-scala-native_2.12_1.0/0.4.0-M2/sbt-scala-native-0.4.0-M2.pom
[error]   not found: /home/eric/.ivy2/local/org.scala-native/sbt-scala-native/scala_2.12/sbt_1.0/0.4.0-M2/ivys/ivy.xml
[error]   download error: Caught java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required" (Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required") while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-native/sbt-scala-native/scala_2.12/sbt_1.0/0.4.0-M2/ivys/ivy.xml
[error]   download error: Caught java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required" (Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required") while downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-native/sbt-scala-native/scala_2.12/sbt_1.0/0.4.0-M2/ivys/ivy.xml
```

**Comment by ekrich** [comment]
I added more information in https://github.com/coursier/coursier/issues/930

**Comment by tomasjura** [comment]
a solution is written [here](https://github.com/coursier/coursier/issues/930#issuecomment-680884752)

I guess that the system properties 
```
http.proxyUser 
http.proxyPassword
https.proxyUser 
https.proxyPassword
```
are not taken in account by default

**Comment by eed3si9n** [comment]
Closing this now.
