### ISSUE TITLE
sbt 1.3.5: `+ publish` task tries to see non-target Scala version dependencies

### ISSUE THREAD

**Issue by xerial** [sbt/sbt#5310]
Ref https://github.com/sbt/sbt/pull/5265

## steps
sbt version: *1.3.5*

Reproduction:
- Checkout https://github.com/wvlet/airframe/releases/tag/v19.12.1
- Run  ./sbt "+ projectJVM2_12/publishSigned"
- It will show unresolved dependency error by trying to download Spark for Scala 2.13:
```
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading org.apache.spark:spark-sql_2.13:2.4.0
[error]   Not found
[error]   Not found
[error]   not found: /Users/leo/.ivy2/local/org.apache.spark/spark-sql_2.13/2.4.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/apache/spark/spark-sql_2.13/2.4.0/spark-sql_2.13-2.4.0.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:245)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$34(CoursierDependencyResolution.scala:214)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:214)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:52)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:102)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:115)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:115)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:96)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:129)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2947)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] (sql / update) sbt.librarymanagement.ResolveException: Error downloading org.apache.spark:spark-sql_2.13:2.4.0
[error]   Not found
[error]   Not found
[error]   not found: /Users/leo/.ivy2/local/org.apache.spark/spark-sql_2.13/2.4.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/apache/spark/spark-sql_2.13/2.4.0/spark-sql_2.13-2.4.0.pom
[error] Total time: 4 s, completed Dec 13, 2019, 4:39:38 PM
```

## problem

- sbt 1.3.5 might be checking libraryDependencies of non-target Scala versions. 
 - In my case, I have a project that uses Spark, which doesn't support Scala 2.13 yet, so the build.sbt has several projects only for Scala 2.12/2.11 (with Spark 2.4.0) and Scala 2.13/2.12/2.11 (without Spark). The latter aggregated project is causing error when running publishSigned. 
- This problem doesn't occur when using sbt 1.3.4

## expectation

- The same behavior with sbt 1.3.4

**Comment by eed3si9n** [comment]
@xerial Thanks for the report.

I can reproduce this using

```
./sbt +projectJVM2_12/compile
```

/cc @eatkins

**Comment by marcospereira** [comment]
@eed3si9n adding a comment as requested:

We are having a problem when cross running tasks in Lagom build as well, see the following job log: [job-267154846-log.txt](https://github.com/sbt/sbt/files/3970096/job-267154846-log.txt)

```# Executing command line:
java
-Xms2G
-Xmx2G
-Xss2M
-XX:MaxInlineLevel=18
-XX:MaxMetaspaceSize=1G
-Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2
-Dakka.test.timefactor=10
-jar
/home/travis/.sbt/launchers/1.3.5/sbt-launch.jar
--warn
"set concurrentRestrictions in Global += Tags.limitAll(1)"
+headerCheck
+test:headerCheck
multi-jvm:headerCheck

saving stty: 500:5:bf:8a3b:3:1c:7f:15:4:0:1:0:11:13:1a:0:12:f:17:16:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[warn] there was one feature warning; re-run with -feature for details
[warn] one warning found
[info] entering *experimental* thin client - BEEP WHIRR
[info] server was not detected. starting an instance
[info] waiting for the server...
[info] waiting for the server...
[info] server found
> /
```

The job then fails since sbt hangs. It is possible to reproduce this locally:

- `sbt clean` works
- `sbt +clean` fails.

(when running the commands in Lagom master with sbt 1.3.5)

**Comment by eed3si9n** [comment]
@xerial I noticed that `sql/crossScalaVersions` actually include 2.13.1:

```
sbt:airframe-root> sql/crossScalaVersions
[info] * 2.13.1
[info] * 2.12.10
[info] * 2.11.12
```

so `+projectJVM2_12/compile` triggering the 2.13 build on `sql` subproject might be working as expected?

**Comment by eed3si9n** [comment]
Sent https://github.com/wvlet/airframe/pull/860

**Comment by eed3si9n** [comment]
Splitting out Lagom issue to https://github.com/sbt/sbt/issues/5314
