### ISSUE TITLE
Stackoverflow simlink to /tmp

### ISSUE THREAD

**Issue by MasseGuillaume** [sbt/sbt#534]
to speed up sbt i added a symlink to /tmp

``` bash
mkdir /tmp/$USER
mkdir /tmp/$USER/.sbt
ln -s /tmp/$USER/.sbt ~/.sbt

mkdir /tmp/$USER/.ivy2
ln -s /tmp/$USER/.ivy2 ~/.ivy2
```

when I run sbt it give me a java.lang.StackOverflowError

this is the stack output

``` bash
        at sbt.BuildLoader.apply(BuildLoader.scala:131)
        at sbt.Load$.loadAll(Load.scala:284)
        at sbt.Load$.loadURI(Load.scala:240)
        at sbt.Load$.load(Load.scala:236)
        at sbt.Load$.load(Load.scala:234)
        at sbt.Load$.apply(Load.scala:118)
        at sbt.Load$.buildPluginDefinition(Load.scala:451)
        at sbt.Load$.buildPlugins(Load.scala:436)
        at sbt.Load$.plugins(Load.scala:425)
        at sbt.Load$.loadUnitNew(Load.scala:383)
        at sbt.Load$.loadUnit(Load.scala:378)
        at sbt.Load$$anonfun$11$$anonfun$apply$10.apply(Load.scala:231)
        at sbt.Load$$anonfun$11$$anonfun$apply$10.apply(Load.scala:231)
        at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:94)
        at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:93)
        at sbt.BuildLoader.apply(BuildLoader.scala:131)
        at sbt.Load$.loadAll(Load.scala:284)
        at sbt.Load$.loadURI(Load.scala:240)
        at sbt.Load$.load(Load.scala:236)
        at sbt.Load$.load(Load.scala:234)
        at sbt.Load$.apply(Load.scala:118)
        at sbt.Load$.buildPluginDefinition(Load.scala:451)
        at sbt.Load$.buildPlugins(Load.scala:436)
        at sbt.Load$.plugins(Load.scala:425)
        at sbt.Load$.loadUnitNew(Load.scala:383)
        at sbt.Load$.loadUnit(Load.scala:378)
        at sbt.Load$$anonfun$11$$anonfun$apply$10.apply(Load.scala:231)
        at sbt.Load$$anonfun$11$$anonfun$apply$10.apply(Load.scala:231)
        at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:94)
        at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:93)
        at sbt.BuildLoader.apply(BuildLoader.scala:131)
        at sbt.Load$.loadAll(Load.scala:284)
        at sbt.Load$.loadURI(Load.scala:240)
        at sbt.Load$.load(Load.scala:236)
        at sbt.Load$.load(Load.scala:234)
        at sbt.Load$.apply(Load.scala:118)
        at sbt.Load$.buildPluginDefinition(Load.scala:451)
        at sbt.Load$.buildPlugins(Load.scala:436)
        at sbt.Load$.plugins(Load.scala:425)
        at sbt.Load$.loadUnitNew(Load.scala:383)
        at sbt.Load$.loadUnit(Load.scala:378)
        at sbt.Load$$anonfun$11$$anonfun$apply$10.apply(Load.scala:231)
        at sbt.Load$$anonfun$11$$anonfun$apply$10.apply(Load.scala:231)
        at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:94)
        at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:93)
        at sbt.BuildLoader.apply(BuildLoader.scala:131)
        at sbt.Load$.loadAll(Load.scala:284)
        at sbt.Load$.loadURI(Load.scala:240)
        at sbt.Load$.load(Load.scala:236)
        at sbt.Load$.load(Load.scala:234)
        at sbt.Load$.apply(Load.scala:118)
        at sbt.Load$.buildPluginDefinition(Load.scala:451)
```

**Comment by harrah** [comment]
sbt has to check whether it is in the global directory to know whether it should load global settings first.  The right way is to just set the global and ivy directories via the relevant system properties:  http://www.scala-sbt.org/0.13.0/docs/Detailed-Topics/Command-Line-Reference.html#command-line-options
