### ISSUE TITLE
MatchError from Log4J2 when Building Play 2.7.4

### ISSUE THREAD

**Issue by neilchaudhuri** [sbt/sbt#5378]
## steps
Given the following:

OpenJDK 11
SBT 1.3.6
Play 2.7.4
An actual logging config file in the classpath (in `conf/`)

`sbt run`.

## problem

MatchError from log4j2 when attempting to run Play Framework 2.7.4

```
[warn] a.a.CoordinatedShutdown - Task [akka-http-server-unbind] in phase [service-unbind] threw an exception before its future could be constructed: null
2020-01-16 00:10:56,308 pool-9-thread-5 ERROR No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
[error] scala.MatchError: org.apache.logging.log4j.simple.SimpleLoggerContext@3da55dc6 (of class org.apache.logging.log4j.simple.SimpleLoggerContext)
[error] 	at sbt.util.LogExchange.logger(LogExchange.scala:28)
[error] 	at sbt.internal.LogManager$.defaultLogger(LogManager.scala:137)
[error] 	at sbt.internal.LogManager$DefaultLogManager.apply(LogManager.scala:104)
[error] 	at sbt.internal.LogManager$.$anonfun$construct$1(LogManager.scala:52)
[error] 	at sbt.std.Streams$$anon$3$$anon$2.log(Streams.scala:178)
[error] 	at sbt.std.TaskStreams.log(Streams.scala:85)
[error] 	at sbt.std.TaskStreams.log$(Streams.scala:85)
[error] 	at sbt.std.Streams$$anon$3$$anon$2.log$lzycompute(Streams.scala:136)
[error] 	at sbt.std.Streams$$anon$3$$anon$2.log(Streams.scala:136)
[error] 	at play.twirl.sbt.SbtTwirl$.$anonfun$compileTemplatesTask$1(SbtTwirl.scala:108)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
```

## expectation

sbt should build and run Play Framework

**Comment by eed3si9n** [comment]
@neilchaudhuri Thanks for the report.

Using `g8 playframework/play-scala-seed.g8 -b 2.7.x`, `sbt run` works fine for me with Play 2.7.4.

```
$ sbt run
[info] Loading settings for project global-plugins from idea.sbt,vimquit.sbt,plugins.sbt,pgp.sbt ...
[info] Loading global plugins from /Users/eed3si9n/.sbt/1.0/plugins
[info] Loading settings for project hello-play-build from plugins.sbt ...
[info] Loading project definition from /private/tmp/hello-play/project
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Loading settings for project root from build.sbt ...
[info] Set current project to hello-play (in build file:/private/tmp/hello-play/)
[info] Updating
https://repo1.maven.org/maven2/com/typesafe/play/filters-helpers_2.13/2.7.4/filters-helpers_2.13-2.7.4.pom
  100.0% [##########] 2.8 KiB (6.8 KiB / s)
https://repo1.maven.org/maven2/com/typesafe/play/play-logback_2.13/2.7.4/play-logback_2.13-2.7.4.pom
  100.0% [##########] 2.2 KiB (5.2 KiB / s)
[info] Resolved  dependencies
[info] Updating
https://repo1.maven.org/maven2/com/typesafe/play/play-omnidoc_2.13/2.7.4/play-omnidoc_2.13-2.7.4.pom
  100.0% [##########] 1.7 KiB (42.6 KiB / s)
https://repo1.maven.org/maven2/com/typesafe/play/play-docs_2.13/2.7.4/play-docs_2.13-2.7.4.pom
  100.0% [##########] 2.0 KiB (50.3 KiB / s)
[info] Resolved  dependencies
[info] Fetching artifacts of
https://repo1.maven.org/maven2/com/typesafe/play/play-logback_2.13/2.7.4/play-logback_2.13-2.7.4.jar
  100.0% [##########] 10.2 KiB (182.5 KiB / s)
https://repo1.maven.org/maven2/com/typesafe/play/filters-helpers_2.13/2.7.4/filters-helpers_2.13-2.7.4.jar
  100.0% [##########] 363.8 KiB (870.4 KiB / s)
https://repo1.maven.org/maven2/com/typesafe/play/play-omnidoc_2.13/2.7.4/play-omnidoc_2.13-2.7.4.jar
  100.0% [##########] 14.2 MiB (2.4 MiB / s)
https://repo1.maven.org/maven2/com/typesafe/play/play-docs_2.13/2.7.4/play-docs_2.13-2.7.4.jar
  100.0% [##########] 11.7 MiB (1.8 MiB / s)
[info] Fetched artifacts of
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.

--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Enter to stop and go back to the console...)

[info] p.c.s.AkkaHttpServer - Stopping server...
[info] Compiling 7 Scala sources and 1 Java source to /private/tmp/hello-play/target/scala-2.13/classes ...
[info] p.a.h.EnabledFilters - Enabled Filters (see <https://www.playframework.com/documentation/latest/Filters>):

    play.filters.csrf.CSRFFilter
    play.filters.headers.SecurityHeadersFilter
    play.filters.hosts.AllowedHostsFilter

[info] play.api.Play - Application started (Dev) (no global state)

[success] Total time: 22 s, completed Jan 22, 2020 1:44:32 PM
```

**Comment by neilchaudhuri** [comment]
The project I have wasn't built with g8. It was built with Activator with Play 2.3 back in the day, and unfortunately it isn't possible to run g8 and try to simply port all the existing code over to a pristine build.

Judging from the stack trace, it might be that SbtTwirl in Play is binary incompatible with akka-slf4j and that SBT has nothing to do with it. I will continue investigating and will close ASAP.

**Comment by eed3si9n** [comment]
Closing this for now.
