### ISSUE TITLE
testOnly tab completion really slow for somewhat reasonably sized number of potential completions

### ISSUE THREAD

**Issue by jrudolph** [sbt/sbt#5380]
In akka/akka

```
project akka-stream-tests
testOnly akka.streams.scaladsl.<tab>
[> 10 second wait]
Display all 294 possibilities? (y or n)
```

Waiting > 10 seconds without being able to abort the search is somewhat annoying :)

294 possibilities is quite a lot but still reasonably sized. Maybe there's some O(n^2) going on?

Here's a stack trace of what it's doing most of the time:

```
   java.lang.Thread.State: RUNNABLE
	at scala.runtime.Statics.anyHash(Statics.java:122)
	at scala.collection.immutable.HashSet.elemHashCode(HashSet.scala:179)
	at scala.collection.immutable.HashSet.computeHash(HashSet.scala:188)
	at scala.collection.immutable.HashSet.$plus(HashSet.scala:84)
	at scala.collection.immutable.HashSet.$plus(HashSet.scala:35)
	at scala.collection.mutable.SetBuilder.$plus$eq(SetBuilder.scala:28)
	at scala.collection.mutable.SetBuilder.$plus$eq(SetBuilder.scala:24)
	at scala.collection.TraversableLike.$anonfun$partition$1(TraversableLike.scala:402)
	at scala.collection.TraversableLike$$Lambda$83/1997963191.apply(Unknown Source)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:321)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:977)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:977)
	at scala.collection.TraversableLike.partition(TraversableLike.scala:402)
	at scala.collection.TraversableLike.partition$(TraversableLike.scala:400)
	at scala.collection.AbstractTraversable.partition(Traversable.scala:108)
	at sbt.Defaults$.$anonfun$distinctParser$1(Defaults.scala:1908)
	at sbt.Defaults$$$Lambda$10850/1659718021.apply(Unknown Source)
	at sbt.internal.util.complete.BindParser.derive(Parser.scala:754)
	at sbt.internal.util.complete.MapParser.derive(Parser.scala:767)
	at sbt.internal.util.complete.SeqParser.derive(Parser.scala:690)
	at sbt.internal.util.complete.MapParser.derive(Parser.scala:767)
	at sbt.internal.util.complete.ParserSeq.$anonfun$derive$3(Parser.scala:734)
	at sbt.internal.util.complete.ParserSeq$$Lambda$8170/1092345627.apply(Unknown Source)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.TraversableLike$$Lambda$8/1873859565.apply(Unknown Source)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.immutable.List.map(List.scala:298)
	at sbt.internal.util.complete.ParserSeq.derive(Parser.scala:734)
	at sbt.internal.util.complete.MapParser.derive(Parser.scala:767)
	at sbt.internal.util.complete.HomParser.derive(Parser.scala:703)
	at sbt.internal.util.complete.And.derive(Parser.scala:822)
	at sbt.internal.util.complete.MatchedString.derive(Parser.scala:792)
	at sbt.internal.util.complete.MapParser.derive(Parser.scala:767)
	at sbt.internal.util.complete.HomParser.derive(Parser.scala:703)
	at sbt.internal.util.complete.HomParser.derive(Parser.scala:703)
	at sbt.internal.util.complete.MatchedString.derive(Parser.scala:792)
	at sbt.internal.util.complete.MapParser.derive(Parser.scala:767)
	at sbt.internal.util.complete.TokenStart.derive(Parser.scala:806)
	at sbt.internal.util.complete.MapParser.derive(Parser.scala:767)
	at sbt.internal.util.complete.HomParser.derive(Parser.scala:703)
	at sbt.internal.util.complete.MapParser.derive(Parser.scala:767)
	at sbt.internal.util.complete.ParserMain.derive1(Parser.scala:494)
	at sbt.internal.util.complete.ParserMain.derive1$(Parser.scala:493)
	at sbt.internal.util.complete.Parser$.derive1(Parser.scala:138)
	at sbt.internal.util.complete.ParserMain.$anonfun$apply$1(Parser.scala:490)
	at sbt.internal.util.complete.ParserMain.$anonfun$apply$1$adapted(Parser.scala:490)
	at sbt.internal.util.complete.ParserMain$$Lambda$63/26728049.apply(Unknown Source)
	at scala.collection.IndexedSeqOptimized.foldLeft(IndexedSeqOptimized.scala:60)
	at scala.collection.IndexedSeqOptimized.foldLeft$(IndexedSeqOptimized.scala:68)
	at scala.collection.immutable.StringOps.foldLeft(StringOps.scala:33)
	at sbt.internal.util.complete.ParserMain.apply(Parser.scala:490)
	at sbt.internal.util.complete.ParserMain.apply$(Parser.scala:489)
	at sbt.internal.util.complete.Parser$.apply(Parser.scala:138)
	at sbt.internal.util.complete.BindParser.$anonfun$completions$3(Parser.scala:745)
	at sbt.internal.util.complete.BindParser$$Lambda$10859/1972812394.apply(Unknown Source)
	at sbt.internal.util.complete.Completions.$anonfun$flatMap$2(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$Lambda$10870/1987725294.apply(Unknown Source)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$Lambda$91/1127224355.apply(Unknown Source)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:321)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:977)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:977)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at sbt.internal.util.complete.Completions.$anonfun$flatMap$1(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$Lambda$10860/380390774.apply(Unknown Source)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:42)
	- locked <0x0000000757420ce8> (a sbt.internal.util.complete.Completions$$anon$1)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:42)
	at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:20)
	at sbt.internal.util.complete.Completions$$Lambda$10868/954053560.apply(Unknown Source)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:42)
	- locked <0x0000000757420d18> (a sbt.internal.util.complete.Completions$$anon$1)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:42)
	at sbt.internal.util.complete.Completions.$anonfun$flatMap$1(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$Lambda$10860/380390774.apply(Unknown Source)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:42)
	- locked <0x0000000757420d58> (a sbt.internal.util.complete.Completions$$anon$1)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:42)
	at sbt.internal.util.complete.JLineCompletion$.convertCompletions(JLineCompletion.scala:75)
	at sbt.internal.util.complete.JLineCompletion$.$anonfun$parserAsCompletor$1(JLineCompletion.scala:72)
	at sbt.internal.util.complete.JLineCompletion$.$anonfun$parserAsCompletor$1$adapted(JLineCompletion.scala:72)
	at sbt.internal.util.complete.JLineCompletion$$$Lambda$8246/1240559528.apply(Unknown Source)
	at sbt.internal.util.complete.JLineCompletion$.$anonfun$customCompletor$2(JLineCompletion.scala:101)
	at sbt.internal.util.complete.JLineCompletion$$$Lambda$10841/1133423325.apply(Unknown Source)
	at sbt.internal.util.complete.JLineCompletion$.complete(JLineCompletion.scala:122)
	at sbt.internal.util.complete.JLineCompletion$.$anonfun$customCompletor$1(JLineCompletion.scala:101)
	at sbt.internal.util.complete.JLineCompletion$.$anonfun$customCompletor$1$adapted(JLineCompletion.scala:100)
	at sbt.internal.util.complete.JLineCompletion$$$Lambda$8247/892319395.apply(Unknown Source)
	at sbt.internal.util.complete.JLineCompletion$CustomHandler.complete(JLineCompletion.scala:47)
	at jline.console.ConsoleReader.complete(ConsoleReader.java:3317)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2653)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2378)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2366)
	at sbt.internal.util.JLine.readLineDirectRaw(LineReader.scala:65)
	at sbt.internal.util.JLine.$anonfun$readLineDirect$2(LineReader.scala:56)
	at sbt.internal.util.JLine$$Lambda$8252/2078797947.apply(Unknown Source)
	at sbt.internal.util.Signals0.withHandler(Signal.scala:89)
	at sbt.internal.util.Signals$.withHandler(Signal.scala:18)
	at sbt.internal.util.JLine.readLineDirect(LineReader.scala:56)
	at sbt.internal.util.JLine.readLineWithHistory(LineReader.scala:48)
	at sbt.internal.util.JLine.unsynchronizedReadLine(LineReader.scala:41)
	at sbt.internal.util.JLine.$anonfun$readLine$1(LineReader.scala:32)
	at sbt.internal.util.JLine$$Lambda$8249/1550936908.apply(Unknown Source)
	at sbt.internal.util.JLine$.$anonfun$withJLine$1(LineReader.scala:163)
	at sbt.internal.util.JLine$$$Lambda$8250/1481569306.apply(Unknown Source)
	at sbt.internal.util.JLine$.withTerminal(LineReader.scala:128)
	- locked <0x0000000757500b08> (a jline.UnixTerminal)
	- locked <0x00000007311442e8> (a sbt.internal.util.JLine$)
	at sbt.internal.util.JLine$.withJLine(LineReader.scala:160)
	at sbt.internal.util.JLine.readLine(LineReader.scala:32)
	at sbt.internal.ConsoleChannel$$anon$1.run(ConsoleChannel.scala:28)
```

sbt 1.3.6

**Comment by eed3si9n** [comment]
@jrudolph Thanks for the report.

To potential contributors, here are some code that might be relevant:
- https://github.com/sbt/sbt/blob/develop/internal/util-complete/src/main/scala/sbt/internal/util/complete/JLineCompletion.scala
- https://github.com/sbt/sbt/blob/v1.3.7/main/src/main/scala/sbt/Defaults.scala#L1895-L1901
- https://github.com/sbt/sbt/blob/develop/internal/util-complete/src/main/scala/sbt/internal/util/complete/Completions.scala
- https://github.com/sbt/sbt/blob/develop/internal/util-complete/src/main/scala/sbt/internal/util/complete/Parser.scala

**Comment by reibitto** [comment]
I'm experiencing this now too. The difference with me though is I started seeing this slowness starting with sbt 1.4. For example, if I type `dep` and hit tab, it takes around 12 seconds to complete for 1.4, but less than 1 second for 1.3.13. I'm not sure why I didn't experience this before. I had assumed it was the new highlighting that was causing it, but now I'm not sure.

![colors](https://user-images.githubusercontent.com/6395394/95456088-c2f6a880-09a9-11eb-985d-f5780164e793.png)

**Comment by eatkins** [comment]
@reibitto do you have a repro project? I can reproduce the testOnly issue in the akka project but that seems distinct from your issue which I cannot reproduce.

Also, could you try what @jrudolph did in the initial report and give us a stack trace that shows where sbt is stuck? In case you haven't done that before, you need the pid of the sbt process (which can usually be found with `ps ux | grep java`) and then while sbt is hanging, run `jstack $PID` in a different terminal. There will be a lot of background threads displayed in the output, but it should be pretty obvious where sbt is stuck.

**Comment by eatkins** [comment]
The way that sbt parsers are implemented makes it very difficult to reason about the algorithmic complexity. My guess is something at least n^2 is going on but possibly even worse. It may actually be easier to reimplement the parsers than to find a workaround for this behavior.

**EDIT** actually I'm not sure it's N^2. It could just be linear with a horrible constant factor. On my computer, `testOnly akka.` takes about 4 seconds and returns 917 results, `testOnly akka.stream.` takes about 1 second and returns 247 results and `testOnly akka.stream.javadsl.` returns effectively instantly and returns 18 results.

**Comment by reibitto** [comment]
@eatkins Oh, sorry if mine was a separate issue. I wasn't using `testOnly` completion specifically. I was trying to complete the first part of a command.

I tried it just now with a plain scala-seed project: `sbt new scala/scala-seed.g8` (and changing sbt.version to 1.4.0). I also disabled all my global plugins.

It's not 12 seconds slowness for this, but I can still see 5+ seconds sometimes. I can't really make sense of it though. For example:

`a<Tab>`: ~5 seconds
`b<Tab>`: almost instantaneous
`c<Tab>`: ~5 seconds
`d<Tab>`: almost instantaneous
`e<Tab>`: ~5 seconds
...etc

I don't see a correlation between the number of results returned and the time it takes. For example, even though `p<Tab>` returns a lot of results, it's still really fast.

I could try the `jstack` thing also to gather more information.

**Comment by reibitto** [comment]
I don't know if this helps or if I correctly identified it, but I gave it a shot:

```
   java.lang.Thread.State: RUNNABLE
	at scala.runtime.Statics.anyHash(Statics.java:122)
	at scala.collection.immutable.HashMap.elemHashCode(HashMap.scala:103)
	at scala.collection.immutable.HashMap.computeHash(HashMap.scala:112)
	at scala.collection.immutable.HashMap.contains(HashMap.scala:75)
	at scala.collection.MapLike$DefaultKeySet.contains(MapLike.scala:176)
	at scala.collection.GenSetLike.apply(GenSetLike.scala:48)
	at scala.collection.GenSetLike.apply$(GenSetLike.scala:48)
	at scala.collection.AbstractSet.apply(Set.scala:53)
	at scala.collection.immutable.MapLike$ImmutableDefaultKeySet.apply(MapLike.scala:112)
	at sbt.internal.util.complete.Parser$Value.filter(Parser.scala:169)
	at sbt.internal.util.complete.Filter.filterResult(Parser.scala:779)
	at sbt.internal.util.complete.Filter.resultEmpty$lzycompute(Parser.scala:781)
	- locked <0x00000007df04a0d8> (a sbt.internal.util.complete.Filter)
	at sbt.internal.util.complete.Filter.resultEmpty(Parser.scala:781)
	at sbt.internal.util.complete.MapParser.resultEmpty$lzycompute(Parser.scala:769)
	- locked <0x00000007df04a118> (a sbt.internal.util.complete.MapParser)
	at sbt.internal.util.complete.MapParser.resultEmpty(Parser.scala:769)
	at sbt.internal.util.complete.TokenStart.resultEmpty(Parser.scala:818)
	at sbt.internal.util.complete.SeqParser.derive(Parser.scala:694)
	at sbt.internal.util.complete.MapParser.derive(Parser.scala:770)
	at sbt.internal.util.complete.BindParser.derive(Parser.scala:755)
	at sbt.internal.util.complete.HomParser.derive(Parser.scala:706)
	at sbt.internal.util.complete.ParserSeq.$anonfun$derive$3(Parser.scala:737)
	at sbt.internal.util.complete.ParserSeq$$Lambda$3618/0x0000000801154040.apply(Unknown Source)
	at scala.collection.immutable.List.map(List.scala:297)
	at sbt.internal.util.complete.ParserSeq.derive(Parser.scala:737)
	at sbt.internal.util.complete.BindParser.derive(Parser.scala:755)
	at sbt.internal.util.complete.HomParser.derive(Parser.scala:706)
	at sbt.internal.util.complete.MapParser.derive(Parser.scala:770)
	at sbt.internal.util.complete.BindParser.derive(Parser.scala:755)
	at sbt.internal.util.complete.HomParser.derive(Parser.scala:706)
	at sbt.internal.util.complete.MatchedString.derive(Parser.scala:795)
	at sbt.internal.util.complete.And.derive(Parser.scala:825)
	at sbt.internal.util.complete.HomParser.derive(Parser.scala:706)
	at sbt.internal.util.complete.MapParser.derive(Parser.scala:770)
	at sbt.internal.util.complete.And.derive(Parser.scala:825)
	at sbt.internal.util.complete.SeqParser.derive(Parser.scala:693)
	at sbt.internal.util.complete.ParserMain.derive1(Parser.scala:496)
	at sbt.internal.util.complete.ParserMain.derive1$(Parser.scala:495)
	at sbt.internal.util.complete.Parser$.derive1(Parser.scala:138)
	at sbt.internal.util.complete.ParserMain.$anonfun$apply$1(Parser.scala:492)
	at sbt.internal.util.complete.ParserMain.$anonfun$apply$1$adapted(Parser.scala:492)
	at sbt.internal.util.complete.ParserMain$$Lambda$397/0x00000008004cd040.apply(Unknown Source)
	at scala.collection.IndexedSeqOptimized.foldLeft(IndexedSeqOptimized.scala:60)
	at scala.collection.IndexedSeqOptimized.foldLeft$(IndexedSeqOptimized.scala:68)
	at scala.collection.immutable.StringOps.foldLeft(StringOps.scala:33)
	at sbt.internal.util.complete.ParserMain.apply(Parser.scala:492)
	at sbt.internal.util.complete.ParserMain.apply$(Parser.scala:491)
	at sbt.internal.util.complete.Parser$.apply(Parser.scala:138)
	at sbt.internal.util.complete.BindParser.$anonfun$completions$3(Parser.scala:748)
	at sbt.internal.util.complete.BindParser$$Lambda$3872/0x00000008011b6040.apply(Unknown Source)
	at sbt.internal.util.complete.Completions.$anonfun$flatMap$2(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$Lambda$3885/0x00000008011c6840.apply(Unknown Source)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:292)
	at scala.collection.TraversableLike$$Lambda$422/0x0000000800505040.apply(Unknown Source)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:330)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:1104)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:1104)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:1104)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:292)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:289)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at sbt.internal.util.complete.Completions.$anonfun$flatMap$1(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$Lambda$3873/0x00000008011b6c40.apply(Unknown Source)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:42)
	- locked <0x00000007d924bd28> (a sbt.internal.util.complete.Completions$$anon$1)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:42)
	at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:20)
	at sbt.internal.util.complete.Completions$$Lambda$3874/0x00000008011b5840.apply(Unknown Source)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:42)
	- locked <0x00000007d924bcf8> (a sbt.internal.util.complete.Completions$$anon$1)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:42)
	at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:20)
	at sbt.internal.util.complete.Completions$$Lambda$3874/0x00000008011b5840.apply(Unknown Source)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:42)
	- locked <0x00000007d924bcc8> (a sbt.internal.util.complete.Completions$$anon$1)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:42)
	at sbt.internal.util.complete.Completions.$anonfun$map$1(Completions.scala:30)
	at sbt.internal.util.complete.Completions$$Lambda$3893/0x00000008011cb440.apply(Unknown Source)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:42)
	- locked <0x00000007fb09dc50> (a sbt.internal.util.complete.Completions$$anon$1)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:42)
	at sbt.internal.util.complete.Completions.$anonfun$flatMap$2(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$Lambda$3885/0x00000008011c6840.apply(Unknown Source)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:292)
	at scala.collection.TraversableLike$$Lambda$422/0x0000000800505040.apply(Unknown Source)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:141)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:292)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:289)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at sbt.internal.util.complete.Completions.$anonfun$flatMap$1(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$Lambda$3873/0x00000008011b6c40.apply(Unknown Source)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:42)
	- locked <0x00000007d924bc28> (a sbt.internal.util.complete.Completions$$anon$1)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:42)
	at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:20)
	at sbt.internal.util.complete.Completions$$Lambda$3874/0x00000008011b5840.apply(Unknown Source)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:42)
	- locked <0x00000007d924bbf8> (a sbt.internal.util.complete.Completions$$anon$1)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:42)
	at sbt.internal.util.complete.TokenCompletions$$anon$5.$anonfun$completions$1(TokenCompletions.scala:50)
	at sbt.internal.util.complete.TokenCompletions$$anon$5$$Lambda$3871/0x00000008011b7c40.apply(Unknown Source)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:42)
	- locked <0x00000007d9800ba8> (a sbt.internal.util.complete.Completions$$anon$1)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:42)
	at sbt.internal.util.complete.Completions.$anonfun$$plus$plus$1(Completions.scala:20)
	at sbt.internal.util.complete.Completions$$Lambda$3874/0x00000008011b5840.apply(Unknown Source)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:42)
	- locked <0x00000007d9800c30> (a sbt.internal.util.complete.Completions$$anon$1)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:42)
	at sbt.internal.util.complete.Completions.$anonfun$flatMap$1(Completions.scala:28)
	at sbt.internal.util.complete.Completions$$Lambda$3873/0x00000008011b6c40.apply(Unknown Source)
	at sbt.internal.util.complete.Completions$$anon$1.get$lzycompute(Completions.scala:42)
	- locked <0x00000007d9800c58> (a sbt.internal.util.complete.Completions$$anon$1)
	at sbt.internal.util.complete.Completions$$anon$1.get(Completions.scala:42)
	at sbt.internal.util.LineReader$$anon$1.$anonfun$complete$1(LineReader.scala:66)
	at sbt.internal.util.LineReader$$anon$1$$Lambda$3922/0x00000008011df040.apply(Unknown Source)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:330)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:1104)
	at sbt.internal.util.LineReader$$anon$1.complete(LineReader.scala:43)
	at org.jline.reader.impl.LineReaderImpl.doComplete(LineReaderImpl.java:4394)
	at org.jline.reader.impl.LineReaderImpl.doComplete(LineReaderImpl.java:4360)
	at org.jline.reader.impl.LineReaderImpl.expandOrComplete(LineReaderImpl.java:4299)
	at org.jline.reader.impl.LineReaderImpl$$Lambda$3749/0x0000000801193c40.apply(Unknown Source)
	at org.jline.reader.impl.LineReaderImpl$1.apply(LineReaderImpl.java:3793)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:665)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:454)
	at sbt.internal.util.LineReader$$anon$2.$anonfun$readLine$4(LineReader.scala:86)
	at sbt.internal.util.LineReader$$anon$2$$Lambda$3857/0x00000008011afc40.apply(Unknown Source)
	at scala.Option.getOrElse(Option.scala:189)
	at sbt.internal.util.LineReader$$anon$2.$anonfun$readLine$2(LineReader.scala:86)
	at sbt.internal.util.LineReader$$anon$2$$Lambda$3855/0x00000008011aec40.apply(Unknown Source)
	at sbt.internal.util.Terminal.withRawInput(Terminal.scala:145)
	at sbt.internal.util.Terminal.withRawInput$(Terminal.scala:143)
	at sbt.internal.util.Terminal$TerminalImpl.withRawInput(Terminal.scala:853)
	at sbt.internal.util.LineReader$$anon$2.readLine(LineReader.scala:86)
	at sbt.internal.ui.UITask$Reader$$anon$1.readLine(UITask.scala:70)
	at sbt.internal.ui.UITask.impl$1(UITask.scala:34)
	at sbt.internal.ui.UITask.run(UITask.scala:37)
	at sbt.internal.ui.UITask.run$(UITask.scala:32)
	at sbt.internal.ui.UITask$AskUserTask.run(UITask.scala:109)
	at sbt.internal.ui.UserThread$$anon$1.run(UserThread.scala:38)
```

**Comment by eatkins** [comment]
@reibitto No need to apologize. Thank you for the clarification!

**Comment by eatkins** [comment]
I think @reibitto's report exonerates jline 3 at least. We only made one small change to the parser, https://github.com/sbt/sbt/pull/5745,  that I'm aware of in 1.4.0 that I think is very unlikely to have made much of a difference. It is possible that there is something else about 1.4.0 that makes the performance issues more likely to occur triggering @reibitto's experience but I don't know. The depth of the stacktraces speak to what I am saying about the unpredictable performance of the sbt parser implementation.
