### ISSUE TITLE
java.lang.Exception: make app id

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#5384]
## steps

Nightly build
https://jenkins.scala-sbt.org:8592/job/sbt-validator/1923/consoleFull

## problem

I noticed there are multiple entries of "java.lang.Exception: make app id" with different stack trace.

```
java.lang.Exception: make app id
	at sbt.ApplicationID.<init>(MainControl.scala:34)
	at sbt.RunFromSourceMain$$anon$2$$anon$3.id(RunFromSourceMain.scala:155)
	at sbt.RunFromSourceMain$$anon$2$$anon$3.id(RunFromSourceMain.scala:113)
	at sbt.BuiltinCommands$.sbtVersion(Main.scala:268)
	at sbt.BuiltinCommands$.writeSbtVersionUnconditionally(Main.scala:923)
	at sbt.BuiltinCommands$.writeSbtVersion(Main.scala:951)
	at sbt.BuiltinCommands$.$anonfun$writeSbtVersion$1(Main.scala:975)
	at sbt.Command$.$anonfun$command$2(Command.scala:97)
	at sbt.Command$.process(Command.scala:188)
	at sbt.MainLoop$.process$1(MainLoop.scala:193)
	at sbt.MainLoop$.processCommand(MainLoop.scala:229)
	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:142)
	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:273)
	at sbt.State$StateOpsImpl$.process$extension(State.scala:277)
	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:142)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.MainLoop$.next(MainLoop.scala:142)
	at sbt.MainLoop$.run(MainLoop.scala:133)
	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:111)
	at sbt.io.Using.apply(Using.scala:27)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:105)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:60)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:45)
	at sbt.MainLoop$.runLogged(MainLoop.scala:36)
	at sbt.StandardMain$.runManaged(Main.scala:131)
	at sbt.xMain$.run(Main.scala:67)
	at sbt.RunFromSourceMain$.launch(RunFromSourceMain.scala:63)
	at sbt.RunFromSourceMain$.runImpl(RunFromSourceMain.scala:56)
	at sbt.RunFromSourceMain$.run(RunFromSourceMain.scala:50)
	at sbt.RunFromSourceMain$.main(RunFromSourceMain.scala:44)
	at sbt.RunFromSourceMain.main(RunFromSourceMain.scala)
```

## expectation

Probably there shouldn't be any of them?

**Comment by eatkins** [comment]
See #5385
