### ISSUE TITLE
"[error] [launcher] error during sbt launcher: java.lang.NoClassDefFoundError"

### ISSUE THREAD

**Issue by ximik3** [sbt/sbt#5388]
## steps
sbt version: 1.3.7 (1.3.6)
macOS ver: 10.15.2
java ver:       13.0.1+9(openJDK)

Fresh system:
1) Install java & sbt

   ```
   > brew cask install java
   > brew install sbt
   ```

2) check versions

   ```> java -version
   openjdk version "13.0.1" 2019-10-15
   OpenJDK Runtime Environment (build 13.0.1+9)
   OpenJDK 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)
   ```

```
> sbt -v
[process_args] java_version = '13'
[sbt_options] declare -a sbt_options='()'
[copyRt] java9_rt = '/Users/vkukhar/.sbt/0.13/java9-rt-ext-oracle_corporation_13_0_1/rt.jar'
# Executing command line:
java
-Dfile.encoding=UTF-8
-Xms1024m
-Xmx1024m
-Xss4M
-XX:ReservedCodeCacheSize=128m
-Dscala.ext.dirs=/Users/vkukhar/.sbt/0.13/java9-rt-ext-oracle_corporation_13_0_1
-jar
/usr/local/Cellar/sbt/1.3.7/libexec/bin/sbt-launch.jar

java.lang.NoClassDefFoundError: sjsonnew/shaded/scalajson/ast/unsafe/JValue
        at sbt.StandardMain$.exchange$lzycompute(Main.scala:106)
        at sbt.StandardMain$.exchange(Main.scala:106)
        at sbt.StandardMain$.$anonfun$closeRunnable$1(Main.scala:122)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at sbt.internal.ShutdownHooks$.$anonfun$add$1(ShutdownHooks.scala:30)
        at sbt.internal.ShutdownHooks$.$anonfun$add$3(ShutdownHooks.scala:38)
        at sbt.internal.ShutdownHooks$.$anonfun$add$3$adapted(ShutdownHooks.scala:38)
        at scala.Option.foreach(Option.scala:407)
        at sbt.internal.ShutdownHooks$.$anonfun$add$2(ShutdownHooks.scala:38)
        at sbt.StandardMain$.runManaged(Main.scala:134)
        at sbt.xMain$.run(Main.scala:67)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:45)
        at sbt.xMain.run(Main.scala:39)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:130)
        at xsbt.boot.Launch$.run(Launch.scala:111)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
        at xsbt.boot.Launch$.launch(Launch.scala:119)
        at xsbt.boot.Launch$.apply(Launch.scala:20)
        at xsbt.boot.Boot$.runImpl(Boot.scala:56)
        at xsbt.boot.Boot$.main(Boot.scala:18)
        at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.ClassNotFoundException: sjsonnew.shaded.scalajson.ast.unsafe.JValue
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:436)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 26 more
[error] [launcher] error during sbt launcher: java.lang.NoClassDefFoundError: sjsonnew/shaded/scalajson/ast/unsafe/JValue
```

## problem
Can't start sbt. I've tried to launch `sbt-launch.jar` diractly as well as use `sbt` downloaded from https://github.com/sbt/sbt/releases with no success. 

## expectation
Sbt starts normally. 

## notes
Actually any sbt command can be used to reproduce this.
`sbt new scala/hello-world.g8` gives the same error.

**Comment by ximik3** [comment]
Same thing with `adoptopenjdk`
`> brew cask remove java`
`> brew cask install adoptopenjdk`
`> sbt -v`
... java.lang.NoClassDefFoundError: sjsonnew/shaded/scalajson/ast/unsafe/JValue

**Comment by ximik3** [comment]
Same thing with recommended by SBT AdoptOpenJDK JDK 11
`> brew cask remove adoptopenjdk`
`> brew tap AdoptOpenJDK/openjdk`
`> brew install adoptopenjdk11`
`> rm -r ~/.sbt`
`> sbt -v`

**Comment by ximik3** [comment]
It's now running on AdoptOpenJDK 13 after removing `~/.sbt` and `~/.ivy2/cache`.

**Comment by eed3si9n** [comment]
> It's now running on AdoptOpenJDK 13 after removing `~/.sbt` and `~/.ivy2/cache`.

If that's the case, likely the launcher failed to resolve the sbt artifacts for some reason, and it's not related to JDK 13.

**Comment by eed3si9n** [comment]
Hopefully this type of issue is fixed after switching the launcher to use Coursier in sbt 1.5.0.

**Comment by hoosierEE** [comment]
I'm on an M1 mac and both `brew install sbt` and `brew install coursier/formulas/coursier && cs setup` resulted in an sbt that does not start. I have this error, slightly different from the original commentor:

```
sbt -version
copying runtime jar...
[info] [launcher] getting org.scala-sbt sbt 1.3.10  (this may take some time)...
[info] [launcher] getting Scala 2.12.10 (for sbt)...
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:425)
	at sbt.TrapExit$.installManager(TrapExit.scala:53)
	at sbt.StandardMain$.runManaged(Main.scala:127)
	at sbt.xMain$.run(Main.scala:67)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:45)
	at sbt.xMain.run(Main.scala:39)
	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
	at xsbt.boot.Launch$.run(Launch.scala:149)
	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
	at xsbt.boot.Launch$.launch(Launch.scala:159)
	at xsbt.boot.Launch$.apply(Launch.scala:44)
	at xsbt.boot.Launch$.apply(Launch.scala:21)
	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
	at xsbt.boot.Boot$.run(Boot.scala:73)
	at xsbt.boot.Boot$.main(Boot.scala:21)
	at xsbt.boot.Boot.main(Boot.scala)
[error] [launcher] error during sbt launcher: java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
sbt script version: 1.8.2
```

Meanwhile scala itself seems ok:
```
scala -version
Scala code runner version 3.2.2 -- Copyright 2002-2023, LAMP/EPFL
```

One thing I noticed is `cs setup` said it couldn't find a JDK even though I already have OpenJDK. I said `y` to install one anyway, but it did not replace my system java:
```
java -version
openjdk version "19.0.2" 2023-01-17
OpenJDK Runtime Environment Homebrew (build 19.0.2)
OpenJDK 64-Bit Server VM Homebrew (build 19.0.2, mixed mode, sharing)
```

Finally, I tried deleting the `~/.sbt` folder as suggested by @ximik3 but the only change I noticed was it ran these commands before repeating the error:
```
copying runtime jar...
[info] [launcher] getting org.scala-sbt sbt 1.3.10  (this may take some time)...
[info] [launcher] getting Scala 2.12.10 (for sbt)...
```

**Comment by eed3si9n** [comment]
`sbt` the shell script is a runner that's capable of launching multiple sbt versions (like `gradlew` if you're familiar with Gradle). The actual sbt version is determined by `project/build.properties` file. From the log it sounds like you're trying to launch sbt 1.3.10. The current latest stable is sbt 1.8.2. I've added JDK 17 support in 2021 as sbt 1.6.0 - https://eed3si9n.com/sbt-1.6.0, so it kind of makes sense that old sbt 1.x doesn't work well with JDK 19.
