### ISSUE TITLE
MiniHBaseCluster crash in tests

### ISSUE THREAD

**Issue by limansky** [sbt/sbt#5389]
## steps
sbt version: *1.3.7*

I tried to upgrade to sbt *1.3.7* from *1.2.8*. We are using HBase testkit in our tests, and it unable to start with new sbt. The project is here: https://github.com/rusexpertiza-llc/yupana 

The command leads to crash is `hbase/test`.

## problem
```
[info] org.yupana.hbase.BTreeIndexDaoHBaseTest *** ABORTED ***
[info]   java.io.IOException: Shutting down
[info]   at org.apache.hadoop.hbase.MiniHBaseCluster.init(MiniHBaseCluster.java:234)
[info]   at org.apache.hadoop.hbase.MiniHBaseCluster.<init>(MiniHBaseCluster.java:96)
[info]   at org.apache.hadoop.hbase.HBaseTestingUtility.startMiniHBaseCluster(HBaseTestingUtility.java:1071)
[info]   at org.apache.hadoop.hbase.HBaseTestingUtility.startMiniCluster(HBaseTestingUtility.java:1031)
[info]   at org.apache.hadoop.hbase.HBaseTestingUtility.startMiniCluster(HBaseTestingUtility.java:903)
[info]   at org.apache.hadoop.hbase.HBaseTestingUtility.startMiniCluster(HBaseTestingUtility.java:897)
[info]   at org.yupana.hbase.BTreeIndexDaoHBaseTest.beforeAll(BTreeIndexDaoHBaseTest.scala:10)
[info]   at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:212)
[info]   at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
[info]   at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
[info]   ...
[info]   Cause: java.lang.RuntimeException: Failed construction of Master: class org.apache.hadoop.hbase.master.HMaster
[info]   at org.apache.hadoop.hbase.util.JVMClusterUtil.createMasterThread(JVMClusterUtil.java:143)
[info]   at org.apache.hadoop.hbase.LocalHBaseCluster.addMaster(LocalHBaseCluster.java:220)
[info]   at org.apache.hadoop.hbase.LocalHBaseCluster.<init>(LocalHBaseCluster.java:155)
[info]   at org.apache.hadoop.hbase.MiniHBaseCluster.init(MiniHBaseCluster.java:216)
[info]   at org.apache.hadoop.hbase.MiniHBaseCluster.<init>(MiniHBaseCluster.java:96)
[info]   at org.apache.hadoop.hbase.HBaseTestingUtility.startMiniHBaseCluster(HBaseTestingUtility.java:1071)
[info]   at org.apache.hadoop.hbase.HBaseTestingUtility.startMiniCluster(HBaseTestingUtility.java:1031)
[info]   at org.apache.hadoop.hbase.HBaseTestingUtility.startMiniCluster(HBaseTestingUtility.java:903)
[info]   at org.apache.hadoop.hbase.HBaseTestingUtility.startMiniCluster(HBaseTestingUtility.java:897)
[info]   at org.yupana.hbase.BTreeIndexDaoHBaseTest.beforeAll(BTreeIndexDaoHBaseTest.scala:10)
[info]   ...
[info]   Cause: java.io.IOException: Problem in starting http server. Server handlers failed
[info]   at org.apache.hadoop.hbase.http.HttpServer.start(HttpServer.java:966)
[info]   at org.apache.hadoop.hbase.http.InfoServer.start(InfoServer.java:91)
[info]   at org.apache.hadoop.hbase.regionserver.HRegionServer.putUpWebUI(HRegionServer.java:1826)
[info]   at org.apache.hadoop.hbase.regionserver.HRegionServer.<init>(HRegionServer.java:613)
[info]   at org.apache.hadoop.hbase.master.HMaster.<init>(HMaster.java:427)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info]   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[info]   at org.apache.hadoop.hbase.util.JVMClusterUtil.createMasterThread(JVMClusterUtil.java:139)
```

## expectation

All tests run successfully.

**Comment by eed3si9n** [comment]
@limansky Thanks for the report.
Could you try setting `Test / fork := true` on the subproject that's failing?

**Comment by limansky** [comment]
@eed3si9n I've tried, and it doesn't changed the situation.

**Comment by eed3si9n** [comment]
Looks like this was a Coursier resolution issue, so I'm closing this for now. Feel free to submit a new issue on coursier/coursier to discuss the resolution difference.

https://github.com/rusexpertiza-llc/yupana/commit/52b2179cc6b4f039c2e1806623b2f4859d2f94ab
