### ISSUE TITLE
sbt 1.3.7 on JDK 13 consistently throws OverlappingFileLockException when fetching the compiler bridge

### ISSUE THREAD

**Issue by christian-schlichtherle** [sbt/sbt#5399]
## steps
sbt version: 1.3.7
Java version: OpenJDK 13.0.2

## problem

This is a log from my project Fun I/O: https://github.com/christian-schlichtherle/fun-io
You can access the full log here: https://api.travis-ci.org/v3/job/641183473/log.txt

```
[info] Loading settings for project workdir-build from plugins.sbt ...
[info] Loading project definition from /workdir/project
[info] Compiling 2 Scala sources to /workdir/project/target/scala-2.12/sbt-1.0/classes ...
[info] Non-compiled module 'compiler-bridge_2.12' for Scala 2.12.10. Compiling...
[info]   Compilation completed in 16.563s.
[info] Attempting to fetch org.scala-sbt:compiler-bridge_2.12:1.3.2.
[error] ## Exception when compiling 2 sources to /workdir/project/target/scala-2.12/sbt-1.0/classes
[error] java.nio.channels.OverlappingFileLockException
[error] java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
[error] java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
[error] java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1155)
[error] java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1178)
[error] xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:88)
[error] xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error] xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error] xsbt.boot.Using$.withResource(Using.scala:10)
[error] xsbt.boot.Using$.apply(Using.scala:9)
[error] xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error] xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error] xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] xsbt.boot.Locks$.apply(Locks.scala:28)
[error] sbt.internal.inc.ZincComponentManager.lock(ZincComponentManager.scala:89)
[error] sbt.internal.inc.ZincComponentManager.lockLocalCache(ZincComponentManager.scala:82)
[error] sbt.internal.inc.ZincComponentManager.define(ZincComponentManager.scala:78)
[error] sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$3(ZincComponentCompiler.scala:262)
[error] sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$3$adapted(ZincComponentCompiler.scala:250)
[error] sbt.io.IO$.withTemporaryDirectory(IO.scala:489)
[error] sbt.io.IO$.withTemporaryDirectory(IO.scala:499)
[error] sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$2(ZincComponentCompiler.scala:250)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.util.BufferedLogger.bufferQuietly(BufferedLogger.scala:119)
[error] sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$1(ZincComponentCompiler.scala:250)
[error] sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$1$adapted(ZincComponentCompiler.scala:247)
[error] sbt.io.IO$.withTemporaryDirectory(IO.scala:489)
[error] sbt.io.IO$.withTemporaryDirectory(IO.scala:499)
[error] sbt.internal.inc.ZincComponentCompiler.compileAndInstall(ZincComponentCompiler.scala:247)
[error] sbt.internal.inc.ZincComponentCompiler.$anonfun$compiledBridgeJar$1(ZincComponentCompiler.scala:215)
[error] sbt.internal.inc.IfMissing$Define.run(IfMissing.scala:19)
[error] sbt.internal.inc.ZincComponentManager.createAndCache$1(ZincComponentManager.scala:49)
[error] sbt.internal.inc.ZincComponentManager.$anonfun$files$3(ZincComponentManager.scala:60)
[error] sbt.internal.inc.ZincComponentManager.getOrElse$1(ZincComponentManager.scala:42)
[error] sbt.internal.inc.ZincComponentManager.$anonfun$files$2(ZincComponentManager.scala:60)
[error] sbt.internal.inc.ZincComponentManager$$anon$1.call(ZincComponentManager.scala:89)
[error] xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error] xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error] xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error] xsbt.boot.Using$.withResource(Using.scala:10)
[error] xsbt.boot.Using$.apply(Using.scala:9)
[error] xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error] xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error] xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] xsbt.boot.Locks$.apply(Locks.scala:28)
[error] sbt.internal.inc.ZincComponentManager.lock(ZincComponentManager.scala:89)
[error] sbt.internal.inc.ZincComponentManager.$anonfun$lockSecondaryCache$1(ZincComponentManager.scala:86)
[error] scala.Option.map(Option.scala:230)
[error] sbt.internal.inc.ZincComponentManager.lockSecondaryCache(ZincComponentManager.scala:86)
[error] sbt.internal.inc.ZincComponentManager.fromSecondary$1(ZincComponentManager.scala:58)
[error] sbt.internal.inc.ZincComponentManager.$anonfun$files$6(ZincComponentManager.scala:64)
[error] sbt.internal.inc.ZincComponentManager.getOrElse$1(ZincComponentManager.scala:42)
[error] sbt.internal.inc.ZincComponentManager.$anonfun$files$5(ZincComponentManager.scala:64)
[error] sbt.internal.inc.ZincComponentManager$$anon$1.call(ZincComponentManager.scala:89)
[error] xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error] xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error] xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error] xsbt.boot.Using$.withResource(Using.scala:10)
[error] xsbt.boot.Using$.apply(Using.scala:9)
[error] xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error] xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error] xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] xsbt.boot.Locks$.apply(Locks.scala:28)
[error] sbt.internal.inc.ZincComponentManager.lock(ZincComponentManager.scala:89)
[error] sbt.internal.inc.ZincComponentManager.lockLocalCache(ZincComponentManager.scala:82)
[error] sbt.internal.inc.ZincComponentManager.files(ZincComponentManager.scala:64)
[error] sbt.internal.inc.ZincComponentManager.file(ZincComponentManager.scala:70)
[error] sbt.internal.inc.ZincComponentCompiler.compiledBridgeJar(ZincComponentCompiler.scala:215)
[error] sbt.internal.inc.ZincComponentCompiler$ZincCompilerBridgeProvider.compiledBridge(ZincComponentCompiler.scala:75)
[error] sbt.internal.inc.ZincComponentCompiler$ZincCompilerBridgeProvider.fetchCompiledBridge(ZincComponentCompiler.scala:81)
[error] sbt.internal.inc.AnalyzingCompiler.loader(AnalyzingCompiler.scala:260)
[error] sbt.internal.inc.AnalyzingCompiler.getInterfaceClass(AnalyzingCompiler.scala:278)
[error] sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:245)
[error] sbt.internal.inc.AnalyzingCompiler.newCachedCompiler(AnalyzingCompiler.scala:145)
[error] sbt.internal.inc.AnalyzingCompiler.newCachedCompiler(AnalyzingCompiler.scala:132)
[error] sbt.internal.inc.FreshCompilerCache.apply(CompilerCache.scala:102)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:92)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:91)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:186)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3$adapted(MixedAnalyzingCompiler.scala:77)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:215)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:77)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:146)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:343)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:343)
[error] sbt.internal.inc.Incremental$.doCompile(Incremental.scala:120)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:100)
[error] sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:180)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:98)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:102)
[error] sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:155)
[error] sbt.internal.inc.Incremental$.compile(Incremental.scala:92)
[error] sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:75)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:348)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:301)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:168)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:248)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:74)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1762)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1735)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] sbt.Execute.work(Execute.scala:290)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] java.base/java.lang.Thread.run(Thread.java:830)
[error]            
[error] java.nio.channels.OverlappingFileLockException
[error] 	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
[error] 	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
[error] 	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1155)
[error] 	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1178)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:88)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.inc.ZincComponentManager.lock(ZincComponentManager.scala:89)
[error] 	at sbt.internal.inc.ZincComponentManager.lockLocalCache(ZincComponentManager.scala:82)
[error] 	at sbt.internal.inc.ZincComponentManager.define(ZincComponentManager.scala:78)
[error] 	at sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$3(ZincComponentCompiler.scala:262)
[error] 	at sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$3$adapted(ZincComponentCompiler.scala:250)
[error] 	at sbt.io.IO$.withTemporaryDirectory(IO.scala:489)
[error] 	at sbt.io.IO$.withTemporaryDirectory(IO.scala:499)
[error] 	at sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$2(ZincComponentCompiler.scala:250)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at sbt.internal.util.BufferedLogger.bufferQuietly(BufferedLogger.scala:119)
[error] 	at sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$1(ZincComponentCompiler.scala:250)
[error] 	at sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$1$adapted(ZincComponentCompiler.scala:247)
[error] 	at sbt.io.IO$.withTemporaryDirectory(IO.scala:489)
[error] 	at sbt.io.IO$.withTemporaryDirectory(IO.scala:499)
[error] 	at sbt.internal.inc.ZincComponentCompiler.compileAndInstall(ZincComponentCompiler.scala:247)
[error] 	at sbt.internal.inc.ZincComponentCompiler.$anonfun$compiledBridgeJar$1(ZincComponentCompiler.scala:215)
[error] 	at sbt.internal.inc.IfMissing$Define.run(IfMissing.scala:19)
[error] 	at sbt.internal.inc.ZincComponentManager.createAndCache$1(ZincComponentManager.scala:49)
[error] 	at sbt.internal.inc.ZincComponentManager.$anonfun$files$3(ZincComponentManager.scala:60)
[error] 	at sbt.internal.inc.ZincComponentManager.getOrElse$1(ZincComponentManager.scala:42)
[error] 	at sbt.internal.inc.ZincComponentManager.$anonfun$files$2(ZincComponentManager.scala:60)
[error] 	at sbt.internal.inc.ZincComponentManager$$anon$1.call(ZincComponentManager.scala:89)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.inc.ZincComponentManager.lock(ZincComponentManager.scala:89)
[error] 	at sbt.internal.inc.ZincComponentManager.$anonfun$lockSecondaryCache$1(ZincComponentManager.scala:86)
[error] 	at scala.Option.map(Option.scala:230)
[error] 	at sbt.internal.inc.ZincComponentManager.lockSecondaryCache(ZincComponentManager.scala:86)
[error] 	at sbt.internal.inc.ZincComponentManager.fromSecondary$1(ZincComponentManager.scala:58)
[error] 	at sbt.internal.inc.ZincComponentManager.$anonfun$files$6(ZincComponentManager.scala:64)
[error] 	at sbt.internal.inc.ZincComponentManager.getOrElse$1(ZincComponentManager.scala:42)
[error] 	at sbt.internal.inc.ZincComponentManager.$anonfun$files$5(ZincComponentManager.scala:64)
[error] 	at sbt.internal.inc.ZincComponentManager$$anon$1.call(ZincComponentManager.scala:89)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.inc.ZincComponentManager.lock(ZincComponentManager.scala:89)
[error] 	at sbt.internal.inc.ZincComponentManager.lockLocalCache(ZincComponentManager.scala:82)
[error] 	at sbt.internal.inc.ZincComponentManager.files(ZincComponentManager.scala:64)
[error] 	at sbt.internal.inc.ZincComponentManager.file(ZincComponentManager.scala:70)
[error] 	at sbt.internal.inc.ZincComponentCompiler.compiledBridgeJar(ZincComponentCompiler.scala:215)
[error] 	at sbt.internal.inc.ZincComponentCompiler$ZincCompilerBridgeProvider.compiledBridge(ZincComponentCompiler.scala:75)
[error] 	at sbt.internal.inc.ZincComponentCompiler$ZincCompilerBridgeProvider.fetchCompiledBridge(ZincComponentCompiler.scala:81)
[error] 	at sbt.internal.inc.AnalyzingCompiler.loader(AnalyzingCompiler.scala:260)
[error] 	at sbt.internal.inc.AnalyzingCompiler.getInterfaceClass(AnalyzingCompiler.scala:278)
[error] 	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:245)
[error] 	at sbt.internal.inc.AnalyzingCompiler.newCachedCompiler(AnalyzingCompiler.scala:145)
[error] 	at sbt.internal.inc.AnalyzingCompiler.newCachedCompiler(AnalyzingCompiler.scala:132)
[error] 	at sbt.internal.inc.FreshCompilerCache.apply(CompilerCache.scala:102)
[error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:92)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:91)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:186)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3$adapted(MixedAnalyzingCompiler.scala:77)
[error] 	at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:215)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:77)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:146)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:343)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:343)
[error] 	at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:120)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:100)
[error] 	at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:180)
[error] 	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:98)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:102)
[error] 	at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:155)
[error] 	at sbt.internal.inc.Incremental$.compile(Incremental.scala:92)
[error] 	at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:75)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:348)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:301)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:168)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:248)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:74)
[error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1762)
[error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1735)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:830)
[error] (Compile / compileIncremental) java.nio.channels.OverlappingFileLockException
```

## expectation

No exception.

## notes

No other build is running.

**Comment by christian-schlichtherle** [comment]
This is happening every time I start the build.

**Comment by christian-schlichtherle** [comment]
Same result for JDK 12, BTW. It does work with JDK 11, however.

**Comment by eed3si9n** [comment]
@christian-schlichtherle Thanks for the report.

**Comment by christian-schlichtherle** [comment]
Same issue seems to exist in version 1.2.8, although it’s not as consistent there.

**Comment by eatkins** [comment]
I was unable to reproduce this locally on my mac and an ubuntu 17 vm. My naive guess is that this may have to do with the docker file system. I don't have a docker setup on my machine so I'm not able to debug further at this time.

**Comment by eatkins** [comment]
@christian-schlichtherle if you can point me to instructions for installing and running docker on my system so that I can approximate your travis ci setup, I can look further.

**Comment by christian-schlichtherle** [comment]
No problem, just install [Docker Desktop For Mac](https://docs.docker.com/docker-for-mac/install/). Then you can check out my repository (master or sbt-1.3.7 branch), cd into the directory and run:

    ./docker-sbtx 13-jdk -batch +test:compile

This reproduces where Travis CI fails.

Now here's the catch: I dockerized the build because it should protect the build from changes in the Travis CI environment and make it reproducible on any platform which runs Docker. So I should get the exact same behavior on any platform, right?! Well, for whatever reason, when I do as said above on my macOS, the build sometimes passes and sometimes fails with yet other exceptions. For whatever the reason, there is definitely some inconsistence. It may well be that these inconsistencies are not due to a bug in sbt, but some other part of the tech stack.

**Comment by christian-schlichtherle** [comment]
Well, it turns out the Scala compiler bridge is already installed on my system, which is why it works then. Your mileage may vary.

**Comment by niklasf** [comment]
Line throwing the exception, for reference: https://github.com/sbt/launcher/blob/fbe82523cdfe5453642f1dccbd2415cc806093a1/launcher-implementation/src/main/scala/xsbt/boot/Locks.scala#L88

**Comment by niklasf** [comment]
The same issue is intermittent on GitHub Actions.

When running with `-Dsbt.boot.lock=false`:

```
[error] cannot redefine component.  ID: org.scala-sbt-compiler-bridge_2.13-1.3.5-bin_2.13.1__57.0, files: /home/runner/.sbt/1.0/zinc/org.scala-sbt/org.scala-sbt-compiler-bridge_2.13-1.3.5-bin_2.13.1__57.0-1.3.5_20200330T000931.jar
```
Full log: https://github.com/ornicar/lila/runs/565677535#step:7:62

---

~Promising workaround: Since this appears to be filesystem related, simply put `~/.sbt` on tmpfs. Of course that's only acceptable for ephemeral build environments.~

Edit: This did not solve the issue, although anecdotally it may have reduced the frequency.

**Comment by eed3si9n** [comment]
I am closing this due to inactivity, but let us know if this still happens.
