### ISSUE TITLE
Use of compiler directive "-usejavacp" causes compiler error.

### ISSUE THREAD

**Issue by gavinbaumanis** [sbt/sbt#5402]
I originally entered this as Scala issue, https://github.com/scala/bug/issues/11863
I was asked to log it here, instead, by, Dale Wijnand @dwijnand.

**Description:**

Using the scala compiler directive **-usejavacp** causes an error when attempting to compile the play-scala-seed  - irrespective of the value passed.

**Environment:**

Mac OSX Catalina
Scala 2.13.1
sbt 1.3.7
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

**Steps:**
1. sbt new playframework/play-scala-seed.g8
2. create a scala.sbt file in the root of the project with;
```
scalacOptions ++= Seq(
"-usejavacp", "false"
)
```

or 

```
scalacOptions ++= Seq(
"-usejavacp", "true"
)
```

(either) causes the following stacktrace;
```
[error] scala.reflect.internal.FatalError: class List does not have a member apply
[error] scala.reflect.internal.Definitions$DefinitionsClass.fatalMissingSymbol(Definitions.scala:1355)
[error] scala.reflect.internal.Definitions$DefinitionsClass.$anonfun$getMember$1(Definitions.scala:1379)
[error] scala.reflect.internal.Definitions$DefinitionsClass.getMember(Definitions.scala:1374)
[error] scala.reflect.internal.Definitions$DefinitionsClass.getMemberMethod(Definitions.scala:1409)
[error] scala.reflect.internal.Definitions$DefinitionsClass.List_apply(Definitions.scala:488)
[error] scala.reflect.internal.Definitions$DefinitionsClass$RunDefinitions.List_apply$lzycompute(Definitions.scala:1645)
[error] scala.reflect.internal.Definitions$DefinitionsClass$RunDefinitions.List_apply(Definitions.scala:1645)
[error] scala.reflect.internal.Definitions$DefinitionsClass$RunDefinitions.isListApply(Definitions.scala:1655)
[error] scala.tools.nsc.typechecker.Typers$Typer.handleMonomorphicCall$1(Typers.scala:3756)
[error] scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3771)
[error] scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4962)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4971)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5840)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5886)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5950)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3394)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3394)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2536)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:5815)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5850)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5886)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedDefDef(Typers.scala:5948)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5793)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5886)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5950)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3394)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3394)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2049)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1879)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5794)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5886)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5950)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3394)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3394)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5494)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5797)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5886)
[error] scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.apply(Analyzer.scala:115)
[error] scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:452)
[error] scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.run(Analyzer.scala:104)
[error] scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1506)
[error] scala.tools.nsc.Global$Run.compileUnits(Global.scala:1490)
[error] scala.tools.nsc.Global$Run.compileSources(Global.scala:1482)
[error] scala.tools.nsc.Global$Run.compile(Global.scala:1614)
[error] xsbt.CachedCompiler0.run(CompilerInterface.scala:153)
[error] xsbt.CachedCompiler0.run(CompilerInterface.scala:125)
[error] xsbt.CompilerInterface.run(CompilerInterface.scala:39)
[error] java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error] sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:122)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:95)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:91)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:186)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3$adapted(MixedAnalyzingCompiler.scala:77)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:215)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:77)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:146)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:343)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:343)
[error] sbt.internal.inc.Incremental$.doCompile(Incremental.scala:120)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:100)
[error] sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:180)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:98)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:102)
[error] sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:155)
[error] sbt.internal.inc.Incremental$.compile(Incremental.scala:92)
[error] sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:75)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:348)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:301)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:168)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:248)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:74)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1762)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1735)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] sbt.Execute.work(Execute.scala:290)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] java.base/java.lang.Thread.run(Thread.java:834)
[error]
[error] scala.reflect.internal.FatalError: class List does not have a member apply
[error] 	at scala.reflect.internal.Definitions$DefinitionsClass.fatalMissingSymbol(Definitions.scala:1355)
[error] 	at scala.reflect.internal.Definitions$DefinitionsClass.$anonfun$getMember$1(Definitions.scala:1379)
[error] 	at scala.reflect.internal.Definitions$DefinitionsClass.getMember(Definitions.scala:1374)
[error] 	at scala.reflect.internal.Definitions$DefinitionsClass.getMemberMethod(Definitions.scala:1409)
[error] 	at scala.reflect.internal.Definitions$DefinitionsClass.List_apply(Definitions.scala:488)
[error] 	at scala.reflect.internal.Definitions$DefinitionsClass$RunDefinitions.List_apply$lzycompute(Definitions.scala:1645)
[error] 	at scala.reflect.internal.Definitions$DefinitionsClass$RunDefinitions.List_apply(Definitions.scala:1645)
[error] 	at scala.reflect.internal.Definitions$DefinitionsClass$RunDefinitions.isListApply(Definitions.scala:1655)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.handleMonomorphicCall$1(Typers.scala:3756)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3771)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4962)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4971)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5840)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5886)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5950)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3394)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3394)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2536)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:5815)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5850)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5886)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedDefDef(Typers.scala:5948)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5793)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5886)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5950)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3394)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3394)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2049)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1879)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5794)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5886)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5950)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3394)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3394)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5494)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5797)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5886)
[error] 	at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.apply(Analyzer.scala:115)
[error] 	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:452)
[error] 	at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.run(Analyzer.scala:104)
[error] 	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1506)
[error] 	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1490)
[error] 	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1482)
[error] 	at scala.tools.nsc.Global$Run.compile(Global.scala:1614)
[error] 	at xsbt.CachedCompiler0.run(CompilerInterface.scala:153)
[error] 	at xsbt.CachedCompiler0.run(CompilerInterface.scala:125)
[error] 	at xsbt.CompilerInterface.run(CompilerInterface.scala:39)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by eed3si9n** [comment]
@gavinbaumanis @dwijnand What is the problem statement and expected outcome here?

**Comment by gavinbaumanis** [comment]
@eed3si9n  @dwijnand 

The problem statement / file / etc is not mentioned in the output at all for the play-scala seed : see below copy/paste of my console;
```
play-scala-seed % sbt compile
[info] Loading settings for project play-scala-seed-build from plugins.sbt ...
[info] Loading project definition from /Users/gavinbaumanis/workspace/a/play-scala-seed/project
[info] Loading settings for project root from scala.sbt,build.sbt ...
[info] Set current project to play-scala-seed (in build file:/Users/gavinbaumanis/workspace/a/play-scala-seed/)
[info] Executing in batch mode. For better performance use sbt's shell
[info] Compiling 7 Scala sources and 1 Java source to /Users/gavinbaumanis/workspace/a/play-scala-seed/target/scala-2.13/classes ...
[error] ## Exception when compiling 8 sources to /Users/gavinbaumanis/workspace/a/play-scala-seed/target/scala-2.13/classes
[error] scala.reflect.internal.FatalError: class List does not have a member apply
...
```

**Comment by gavinbaumanis** [comment]
@eed3si9n  @dwijnand 

I only chose to log the issue with the play-scala-seed because it is easily reproducible.
However in my own application I get the following - which is not evident in the seed application;

(The error "marker / caret" is pointing at "request")
```
[error] /Users/gavinbaumanis/workspace/ecpr/pas/app/au/com/ecpr/controllers/ApplicationController.scala:50:54: missing parameter type
[error]     def index: Action[AnyContent] = Action {implicit request =>
```

**Comment by eed3si9n** [comment]
By "problem statement" I mean https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md#what-to-report

> Next, describe the problems, or what *you think* is the problem.

As far as I can tell sbt is just passing through the compiler flag to the compiler, and compiler is not having a good time because it can't find things in the Java classpath. This could be related to the fact that sbt invokes the Scala compiler as function call in a sandbox classloader, and we don't rely on the classpath.

Dale wrote:

> perhaps the only solution is to filter out any specified `-usejavacp` option.

Filtering out explicitly passed in `scalacOptions` doesn't sound like a good solution.

**Comment by dwijnand** [comment]
I'm all for a better solution.  But I mentioned it because I'm not sure if sbt can support the compiler being called with `-usejavacp`.

**Comment by eed3si9n** [comment]
Maybe Zinc prints out a warning and explanation of why Zinc does not handle `-usejavacp`.
