### ISSUE TITLE
TestEvent.error == null when tests are forked

### ISSUE THREAD

**Issue by ewiner** [sbt/sbt#543]
I'm trying to use a test reporting plugin (https://github.com/guardian/sbt-teamcity-test-reporting-plugin), but it's not working well when I've specified `fork := true`.  It looks like ForkMain just throws away the exception message for failed tests.  Even if it can't send the actual exception object back to the main SBT JVM, maybe it could toString the message and stack trace it and wrap it in a special Exception type, so any test listeners could pick it up.

**Comment by vigdorchik** [comment]
@ewiner It would be nice if you could post a small example where this problem can be reproduced, so that we can include it as a test.

**Comment by ewiner** [comment]
Sure thing.  Here's a test class:

``` scala
import org.scalatest.FunSuite

class SBT543 extends FunSuite {
  test("throws a JVM excpetion") {
    throw new IllegalArgumentException("your argument is illegal")
  }

  class MyCustomException(message: String) extends RuntimeException(message)
  test("throws a custom excpetion") {
    throw new MyCustomException("this is a custom exception")
  }
}
```

and a corresponding build.sbt:

``` scala
libraryDependencies += "org.scalatest" %% "scalatest" % "1.8" % "test"

fork := true

testListeners += new TestReportListener {
  def testEvent(event: TestEvent) {
    for (e <- event.detail.filter(_.result() == org.scalatools.testing.Result.Failure)) {
      val diditwork = Option(e.error()) match {
        case None => "Exception returned null! (sbt issue 543)"
        case Some(exc) => "Exception returned to SBT! (message: " + exc.getMessage + ")"
      }
      println(diditwork)
    }
  }
  def startGroup(name: String) {}
  def endGroup(name: String, t: Throwable) {}
  def endGroup(name: String, result: TestResult.Value) {}
}
```

I haven't yet tested it against your commit...

**Comment by vigdorchik** [comment]
Great, thank you. Your test showed that my commit doesn't work for scalatest, that throws an exception that is of an inner class. I'll try to rework it.

**Comment by TheSultan** [comment]
@vigdorchik I took this over from ewiner and tested the patch. It appears better but not quite right, and differs a bit depending on the test runner. We now get the exception message back but the stack trace is still from the test runner, not the underlying test. For scalatest this seems acceptable because it at least contains the original test stack inside its own but for junit it doesn't. Here are example outputs from both

Scalatest output:
[19:45:35]: throws a custom exception
[19:45:35]: [throws a custom exception] sbt.ForkMain$ForkError: this is a custom exception at sbt.ForkMain$ForkEvent.<init>(ForkMain.java:73) at sbt.ForkMain$Run$2.handle(ForkMain.java:155) at org.scalatest.tools.ScalaTestFramework$ScalaTestRunner$SbtReporter.fireEvent(ScalaTestFramework.scala:249) at org.scalatest.tools.ScalaTestFramework$ScalaTestRunner$SbtReporter.apply(ScalaTestFramework.scala:267) at org.scalatest.CatchReporter.apply(CatchReporter.scala:38) at org.scalatest.Suite$.reportTestFailed(Suite.scala:2893) at org.scalatest.SuperEngine.runTestImpl(Engine.scala:211) at org.scalatest.FunSuite$class.runTest(FunSuite.scala:1271) at SBT543Test.runTest(SBT543Test.scala:3) at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1304) at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1304) at org.scalatest.SuperEngine$$anonfun$org$scalatest$SuperEngine$$runTestsInBranch$1.apply(Engine.scala:260) at org.scalatest.SuperEngine$$anonfun$org$scalatest$SuperEngine$$runTestsInBranch$1.apply(Engine.scala:249) at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59) at scala.collection.immutable.List.foreach(List.scala:45) at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:249) at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:326) at org.scalatest.FunSuite$class.runTests(FunSuite.scala:1304) at SBT543Test.runTests(SBT543Test.scala:3) at org.scalatest.Suite$class.run(Suite.scala:2303) at SBT543Test.org$scalatest$FunSuite$$super$run(SBT543Test.scala:3) at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1310) at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1310) at org.scalatest.SuperEngine.runImpl(Engine.scala:362) at org.scalatest.FunSuite$class.run(FunSuite.scala:1310) at SBT543Test.run(SBT543Test.scala:3) at org.scalatest.tools.ScalaTestFramework$ScalaTestRunner.run(ScalaTestFramework.scala:214) at sbt.ForkMain$Run.runTests(ForkMain.java:157) at sbt.ForkMain$Run.run(ForkMain.java:171) at sbt.ForkMain.main(ForkMain.java:86) 

JUnit output:
sbt.ForkMain$ForkError: Exception Message
    at sbt.ForkMain$ForkEvent.<init>(ForkMain.java:73)
    at sbt.ForkMain$Run$2.handle(ForkMain.java:155)
    at com.novocode.junit.EventDispatcher.postIfFirst(EventDispatcher.java:81)
    at com.novocode.junit.EventDispatcher.testFailure(EventDispatcher.java:42)
    at org.junit.runner.notification.RunNotifier$4.notifyListener(RunNotifier.java:100)
    at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:41)
    at org.junit.runner.notification.RunNotifier.fireTestFailure(RunNotifier.java:97)
    at org.junit.internal.runners.model.EachTestNotifier.addFailure(EachTestNotifier.java:25)
    at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:83)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
    at org.junit.runners.Suite.runChild(Suite.java:128)
    at org.junit.runners.Suite.runChild(Suite.java:24)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
    at com.novocode.junit.JUnitRunner.run(JUnitRunner.java:50)
    at sbt.ForkMain$Run.runTests(ForkMain.java:157)
    at sbt.ForkMain$Run.run(ForkMain.java:171)
    at sbt.ForkMain.main(ForkMain.java:86)

**Comment by vigdorchik** [comment]
@TheSultan isn't it the problem with junit runner that doesn't wrap the original error inside its own?

**Comment by TheSultan** [comment]
@vigdorchik not quite, the outputs are different but basically useless in both cases (i.e. the line number in scalatest is just the test class declaration, not where the test actually threw an exception). The main problem I'm seeing is that when forked, you're getting the stack trace from the test runner, not the test class itself. I'm trying to debug it to see if I can figure out why.

**Comment by vigdorchik** [comment]
@TheSultan how is the output above generated? If it is through printStackTrace, then I have an explanation that printStackTrace in java.lang.Throwable doesn't use serialized stacktrace, and delegates to other private method.

**Comment by harrah** [comment]
Yeah, looks like printStackTrace skips getStackTrace and goes right to the private getOurStackTrace.  Thanks!

**Comment by TheSultan** [comment]
Gents, to confirm
a) Yes, that output was generated via printStackTrace as the Teamcity test output plugin uses that. 
b) Your fix appears to work for us now, thanks
