### ISSUE TITLE
No stack error using sbt 1.3.X

### ISSUE THREAD

**Issue by Djiggy** [sbt/sbt#5468]
## steps

I migrate from sbt 0.13.16 to 1.3.8. In my build.sbt i had this line : 
`val dstDir = SettingKey[File]("Deploy destination dir")`

## problem
During reload of the project, an error was throw : 
```
10:24 $ sbt reload
[info] Loading settings for project boagents-build from plugins.sbt,build.sbt ...
[info] Loading project definition from /home/etienne/projets/boAgents/project
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[error] java.lang.ExceptionInInitializerError
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

There was no stack provided

i revert sbt version to 1.2.7, then i was able to view the stack linked to the error :
```
[error] java.lang.ExceptionInInitializerError
[error] 	at java.lang.Class.forName0(Native Method)
[error] 	at java.lang.Class.forName(Class.java:348)
[error] 	at sbt.compiler.Eval$.getModule(Eval.scala:584)
[error] 	at sbt.compiler.EvalDefinitions.values(Eval.scala:58)
[error] 	at sbt.internal.DefinedSbtValues.$anonfun$values$1(LoadedSbtFile.scala:50)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:240)
[error] 	at scala.collection.immutable.List.foreach(List.scala:388)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:240)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:237)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:351)
[error] 	at sbt.internal.DefinedSbtValues.values(LoadedSbtFile.scala:50)
[error] 	at sbt.internal.EvaluateConfigurations$.$anonfun$evaluateSbtFile$4(EvaluateConfigurations.scala:166)
[error] 	at sbt.internal.Load$.loadSettingsFile$1(Load.scala:1137)
[error] 	at sbt.internal.Load$.$anonfun$discoverProjects$2(Load.scala:1144)
[error] 	at scala.collection.MapLike.getOrElse(MapLike.scala:127)
[error] 	at scala.collection.MapLike.getOrElse$(MapLike.scala:125)
[error] 	at scala.collection.AbstractMap.getOrElse(Map.scala:59)
[error] 	at sbt.internal.Load$.memoLoadSettingsFile$1(Load.scala:1143)
[error] 	at sbt.internal.Load$.$anonfun$discoverProjects$4(Load.scala:1151)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
[error] 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:58)
[error] 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:51)
[error] 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:233)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
[error] 	at sbt.internal.Load$.loadFiles$1(Load.scala:1151)
[error] 	at sbt.internal.Load$.discoverProjects(Load.scala:1165)
[error] 	at sbt.internal.Load$.discover$1(Load.scala:862)
[error] 	at sbt.internal.Load$.loadTransitive(Load.scala:937)
[error] 	at sbt.internal.Load$.loadProjects$1(Load.scala:726)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$11(Load.scala:729)
[error] 	at sbt.internal.Load$.timed(Load.scala:1395)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:729)
[error] 	at sbt.internal.Load$.timed(Load.scala:1395)
[error] 	at sbt.internal.Load$.loadUnit(Load.scala:688)
[error] 	at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:484)
[error] 	at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:176)
[error] 	at sbt.internal.BuildLoader.apply(BuildLoader.scala:241)
[error] 	at sbt.internal.Load$.loadURI$1(Load.scala:546)
[error] 	at sbt.internal.Load$.loadAll(Load.scala:562)
[error] 	at sbt.internal.Load$.loadURI(Load.scala:492)
[error] 	at sbt.internal.Load$.load(Load.scala:471)
[error] 	at sbt.internal.Load$.$anonfun$apply$1(Load.scala:251)
[error] 	at sbt.internal.Load$.timed(Load.scala:1395)
[error] 	at sbt.internal.Load$.apply(Load.scala:251)
[error] 	at sbt.internal.Load$.defaultLoad(Load.scala:69)
[error] 	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:829)
[error] 	at sbt.BuiltinCommands$.doLoadProject(Main.scala:829)
[error] 	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:800)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:142)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:137)
[error] 	at sbt.Command$.process(Command.scala:181)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:151)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:139)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:246)
[error] 	at sbt.State$$anon$1.process(State.scala:250)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:139)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:139)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:132)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:35)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:138)
[error] 	at sbt.xMain.run(Main.scala:89)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:130)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:111)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:119)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:20)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:18)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] Caused by: java.lang.IllegalArgumentException: requirement failed: A named attribute key must start with a lowercase letter: Deploy destination dir
```

So there is no stack error provided with sbt version 1.3.X

**Comment by eatkins** [comment]
This is by design. Do you see the full stack trace when you enter ‘l’?

**Comment by eed3si9n** [comment]
That's L for Lima :)

I should also note https://github.com/sbt/util/pull/211 / https://github.com/sbt/sbt/issues/4964
