### ISSUE TITLE
NumberFormatException with SDKman and Graal JDK installed

### ISSUE THREAD

**Issue by dhinojosa** [sbt/sbt#5478]
## steps

1. Install SDKMan,
2. Install any AdoptOpenJDK version, per SDKMan's instructions. (e.g. `sdk install java 8.0.242.hs-adpt`)
3. Install any GraalVM, per SDKMan's instructions. (e.g. `sdk install java 20.0.0.r11-grl`)
4. Ensure that you are *using* the AdoptOpenJDK version (e.g. `sdk use java 11.0.6.hs-adpt`)
5. Run `sbt`

Here is an example of what is installed on my machine.

```
Available Java Versions
================================================================================
 Vendor        | Use | Version      | Dist    | Status     | Identifier
--------------------------------------------------------------------------------
 AdoptOpenJDK  |     | 13.0.2.j9    | adpt    |            | 13.0.2.j9-adpt
               |     | 13.0.2.hs    | adpt    |            | 13.0.2.hs-adpt
               |     | 12.0.2.j9    | adpt    |            | 12.0.2.j9-adpt
               |     | 12.0.2.hs    | adpt    |            | 12.0.2.hs-adpt
               |     | 11.0.6.j9    | adpt    |            | 11.0.6.j9-adpt
               |     | 11.0.6.hs    | adpt    | installed  | 11.0.6.hs-adpt
               |     | 8.0.242.j9   | adpt    |            | 8.0.242.j9-adpt
               | >>> | 8.0.242.hs   | adpt    | installed  | 8.0.242.hs-adpt
```
and a little further down the list (notice `20.0.0.r11`)

```
GraalVM       |     | 20.0.0.r11   | grl     | installed  | 20.0.0.r11-grl
               |     | 20.0.0.r8    | grl     |            | 20.0.0.r8-grl
               |     | 19.3.1.r11   | grl     |            | 19.3.1.r11-grl
               |     | 19.3.1.r8    | grl     |            | 19.3.1.r8-grl
               |     | 19.3.0.r11   | grl     |            | 19.3.0.r11-grl
               |     | 19.3.0.r8    | grl     |            | 19.3.0.r8-grl
```
## problem

When running `sbt` at the command line on a pre-created project:
```
[info] Loading settings for project global-plugins from idea.sbt,plugins.sbt ...
[error] java.lang.NumberFormatException: For input string: "0-r11"
[error] 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[error] 	at java.lang.Long.parseLong(Long.java:589)
[error] 	at java.lang.Long.parseLong(Long.java:631)
[error] 	at scala.collection.immutable.StringLike.toLong(StringLike.scala:309)
[error] 	at scala.collection.immutable.StringLike.toLong$(StringLike.scala:309)
[error] 	at scala.collection.immutable.StringOps.toLong(StringOps.scala:33)
[error] 	at sbt.internal.CrossJava$.$anonfun$parseJavaVersion$2(CrossJava.scala:34)
[error] 	at sbt.internal.CrossJava$.$anonfun$parseJavaVersion$2$adapted(CrossJava.scala:34)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
```
## expectation

Ability to run `sbt` without any exception

## notes

I suspect strongly that `CrossJava.scala` has no idea how to handle SDKMan's Graal versions.

**Comment by eed3si9n** [comment]
@dhinojosa Thanks for the report! This sounds similar to https://github.com/sbt/sbt/issues/4731. Which version of sbt are you using?

**Comment by dhinojosa** [comment]
Works like a champ. Thanks, @eed3si9n. Sorry I didn't report back on time. I appreciate all your hard work. :)

**Comment by eed3si9n** [comment]
I am confused. Does it work with the latest sbt version? If so can we close this issue?

**Comment by dhinojosa** [comment]
Sorry, not sure what happened closing. Yes, works great.
