### ISSUE TITLE
Regression in servicing app.class.path to in-process execution (used when configuring classpath of programattic scalac)

### ISSUE THREAD

**Issue by retronym** [sbt/sbt#5502]
## steps

```
sbt.version=1.3.9
```

```scala
scalaVersion := "2.12.11"
libraryDependencies += scalaOrganization.value % "scala-compiler" % scalaVersion.value
```

```scala
import scala.tools.nsc._

object Main {
  def main(args: Array[String]): Unit = {
    val s = new Settings()
    s.embeddedDefaults[Main.type]
    s.outputDirs.setSingleOutput(new io.VirtualDirectory("(memory)", None))
    val g = new Global(s, new reporters.StoreReporter)
    new g.Run().compileSources(List(g.newSourceFile("class C")))
  }
}
```

## problem

```
$ sbt run
[info] Loading settings for project global-plugins from global-plugins.sbt ...
[info] Loading global plugins from /Users/dnw/.dotfiles/.sbt/1.0/plugins
[info] Loading project definition from /s/t-sbt-embeddedDefaults/project
[info] Loading settings for project t-sbt-embeddeddefaults from build.sbt ...
[info] Set current project to t-sbt-embeddeddefaults (in build file:/s/t-sbt-embeddedDefaults/)
[info] running Main
[error] (run-main-0) scala.reflect.internal.MissingRequirementError: object scala in compiler mirror not found.
[error] scala.reflect.internal.MissingRequirementError: object scala in compiler mirror not found.
[error] 	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:24)
[error] 	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:25)
[error] 	at scala.reflect.internal.Mirrors$RootsBase.$anonfun$getModuleOrClass$6(Mirrors.scala:65)
[error] 	at scala.reflect.internal.Mirrors$RootsBase.getPackage(Mirrors.scala:65)
[error] 	at scala.reflect.internal.Definitions$DefinitionsClass.ScalaPackage$lzycompute(Definitions.scala:197)
[error] 	at scala.reflect.internal.Definitions$DefinitionsClass.ScalaPackage(Definitions.scala:197)
[error] 	at scala.reflect.internal.Definitions$DefinitionsClass.ScalaPackageClass$lzycompute(Definitions.scala:198)
[error] 	at scala.reflect.internal.Definitions$DefinitionsClass.ScalaPackageClass(Definitions.scala:198)
[error] 	at scala.reflect.internal.Definitions$DefinitionsClass.AnyClass$lzycompute(Definitions.scala:293)
[error] 	at scala.reflect.internal.Definitions$DefinitionsClass.AnyClass(Definitions.scala:293)
[error] 	at scala.tools.nsc.symtab.classfile.ClassfileParser$ClassTypeCompleter.complete(ClassfileParser.scala:1268)
[error] 	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1539)
[error] 	at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1696)
[error] 	at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1480)
[error] 	at scala.tools.nsc.Global$Run.<init>(Global.scala:1197)
[error] 	at Main$.main(Main.scala:9)
[error] 	at Main.main(Main.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] stack trace is suppressed; run last Compile / bgRun for the full output
[error] Nonzero exit code: 1
[error] (Compile / run) Nonzero exit code: 1
[error] Total time: 2 s, completed 14-Apr-2020 21:10:27
```

## expectation

```
$ sbt -Dsbt.version=1.2.8 run
[warn] sbt version mismatch, current: 1.2.8, in build.properties: "1.3.9", use 'reboot' to use the new value.
[info] Loading settings for project global-plugins from global-plugins.sbt ...
[info] Loading global plugins from /Users/dnw/.dotfiles/.sbt/1.0/plugins
[info] Loading project definition from /s/t-sbt-embeddedDefaults/project
[info] Loading settings for project t-sbt-embeddeddefaults from build.sbt ...
[info] Set current project to t-sbt-embeddeddefaults (in build file:/s/t-sbt-embeddedDefaults/)
[info] Running Main
[success] Total time: 3 s, completed 14-Apr-2020 21:12:15
```

## notes

* https://github.com/sbt/sbt/commit/600053bf2cc9df13629239796851dd3a0a29efec is the introduction of the feature in sbt (what happened to that test?)
* https://github.com/scala/scala/commit/6dfcae30bfcdc93509755185f814c8e318a64012#diff-d7da7216ed859145d1d161cf3de4a829 is the introduction of `embeddedDefaults` in the compiler to make use of it

### workaround

`fork := true`

(though it wouldn't be "in-process execution" then...)

or

```diff
+addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.9.0")
```

```diff
+  .enablePlugins(BuildInfoPlugin)
+  .settings(
+    buildInfoKeys := List[BuildInfoKey](
+      BuildInfoKey.map(scalaInstance) { case (_, si) =>
+        "scalaJars" -> si.libraryJars.toList
+      },
+    ),
+  )
```

```diff
-    s.embeddedDefaults[Main.type]
+    s.classpath.value =
+      util.ClassPath.join(buildinfo.BuildInfo.scalaJars.map(_.getPath): _*)
```

or, without having to add sbt-buildinfo

```diff
+  Compile / resourceGenerators += Def.task {
+    val f = (Compile / resourceManaged).value / "app.class.path"
+    IO.write(f, scalaInstance.value.libraryJars.mkString(java.io.File.pathSeparator))
+    List(f)
+  }.taskValue,
```

### original report

With this `resources` is no longer used, and therefore no longer serviced...

This breaks the compiler's `Settings#embeddedDefaults` which relies on those resources.

_Originally posted by @dwijnand in https://github.com/sbt/sbt/pull/4906_

**Comment by retronym** [comment]
SBT is supposed to provide special classpath resources `app.class.path` and `boot.class.path` to non-forked executions. These are used by `scalac`-s `Settings#embeddedDefaults` methods to use the classpath of the execution as the classpath for a programatticaly used compiler.

Example: https://github.com/scala/scala-async/blob/master/src/test/scala/scala/async/package.scala#L67

**Comment by eatkins** [comment]
This bug report is missing a reproduction step that would be helpful for anyone inclined to investigate the issue. Only including the specific what that broke isn’t useful to an outsider without a more general what and/or a how. 

I am not fully convinced that what sbt did before is what it _should_ do so much as some downstream projects seem to have depended on what sbt _did_ do. Layering classloaders has a lot of subtlety and I did a lot of work to ensure the best possible balance of performance and correctness. I’m not trying to be difficult but I’d suggest looking into a downstream fix because this is an obscure issue and it is easy to create unintended negative consequences when messing with the layered classloaders.

**Comment by dwijnand** [comment]
@eatkins fair enough, filled out the report.  It doesn't have so much to do with layering, as far as I see it - just need to make sure the generated resources are served by one of the classloaders.

**Comment by retronym** [comment]
> what happened to that test?

Accidentally dropped rather than ported to a supported Scala version in:

https://github.com/sbt/sbt/pull/2589

**Comment by dwijnand** [comment]
Added to the issue another workaround for how to add the magic resource, which makes embeddedDefaults work again, without needing sbt-buildinfo.
