### ISSUE TITLE
Can't import  in idea sbt project

### ISSUE THREAD

**Issue by BioQwer** [sbt/sbt#5510]
## steps

https://github.com/BioQwer/spark-scala-tutorial 
import this sbt project in idea 

## problem

```
C:/Program Files/AdoptOpenJDK/jdk-8.0.242.08-hotspot/bin/java.exe -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -Xmx5000M -Didea.managed=true -Dfile.encoding=UTF-8 -jar C:/Users/BioQw/AppData/Roaming/JetBrains/IntelliJIdea2020.1/plugins/Scala/launcher/sbt-launch.jar
[info] Loading global plugins from C:\Users\BioQw\.sbt\1.0\plugins
[info] Loading settings for project spark-scala-tutorial-build from plugins.sbt ...
[info] Loading project definition from C:\Users\BioQw\Development\spark-scala-tutorial\project
[warn]
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.typesafe.sbteclipse:sbteclipse-plugin:4.0.0 (sbtVersion=1.0, scalaVersion=2.12)
[warn] 		net.virtual-void:sbt-dependency-graph:0.8.0 (sbtVersion=1.0, scalaVersion=2.12)
[warn]
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.typesafe.sbteclipse:sbteclipse-plugin;sbtVersion=1.0;scalaVersion=2.12:4.0.0
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbteclipse/sbteclipse-plugin_2.12_1.0/4.0.0/sbteclipse-plugin-4.0.0.pom
[error]   not found: C:\Users\BioQw\.ivy2\local\com.typesafe.sbteclipse\sbteclipse-plugin\scala_2.12\sbt_1.0\4.0.0\ivys\ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0/4.0.0/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0/4.0.0/ivys/ivy.xml
[error] Error downloading net.virtual-void:sbt-dependency-graph;sbtVersion=1.0;scalaVersion=2.12:0.8.0
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/net/virtual-void/sbt-dependency-graph_2.12_1.0/0.8.0/sbt-dependency-graph-0.8.0.pom
[error]   not found: C:\Users\BioQw\.ivy2\local\net.virtual-void\sbt-dependency-graph\scala_2.12\sbt_1.0\0.8.0\ivys\ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/net.virtual-void/sbt-dependency-graph/scala_2.12/sbt_1.0/0.8.0/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/net.virtual-void/sbt-dependency-graph/scala_2.12/sbt_1.0/0.8.0/ivys/ivy.xml
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:247)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$35(CoursierDependencyResolution.scala:216)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:216)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:52)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:102)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:115)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:115)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:96)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:129)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2950)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.typesafe.sbteclipse:sbteclipse-plugin;sbtVersion=1.0;scalaVersion=2.12:4.0.0
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbteclipse/sbteclipse-plugin_2.12_1.0/4.0.0/sbteclipse-plugin-4.0.0.pom
[error]   not found: C:\Users\BioQw\.ivy2\local\com.typesafe.sbteclipse\sbteclipse-plugin\scala_2.12\sbt_1.0\4.0.0\ivys\ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0/4.0.0/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0/4.0.0/ivys/ivy.xml
[error] Error downloading net.virtual-void:sbt-dependency-graph;sbtVersion=1.0;scalaVersion=2.12:0.8.0
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/net/virtual-void/sbt-dependency-graph_2.12_1.0/0.8.0/sbt-dependency-graph-0.8.0.pom
[error]   not found: C:\Users\BioQw\.ivy2\local\net.virtual-void\sbt-dependency-graph\scala_2.12\sbt_1.0\0.8.0\ivys\ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/net.virtual-void/sbt-dependency-graph/scala_2.12/sbt_1.0/0.8.0/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/net.virtual-void/sbt-dependency-graph/scala_2.12/sbt_1.0/0.8.0/ivys/ivy.xml
Invalid response.
```

## notes

many time ago is working

**Comment by eed3si9n** [comment]
Looking at https://dl.bintray.com/sbt/sbt-plugin-releases/com.typesafe.sbteclipse/sbteclipse-plugin/scala_2.12/sbt_1.0/, sbteclipse-plugin does not exist for 4.0.0. Maybe you updated from sbt 0.13 to 1.x recently?

Before importing to IntelliJ, could you try running sbt alone and make sure your plugins are up to date?

**Comment by BioQwer** [comment]
ok thx
