### ISSUE TITLE
SBT Console (Scala 2.11) fails on SBT 1.3.10 on Ubuntu 20.04 LTS with default Java 11

### ISSUE THREAD

**Issue by fernandoracca** [sbt/sbt#5550]
## steps

build.sbt
```scala
organization := "com.github.fractal"
name := "scala-211-java11"

scalaVersion := "2.11.12"

lazy val scalaTestVersion = "3.0.5"

libraryDependencies ++= Seq(
  "org.scalatest" %% "scalatest" % scalaTestVersion % "test")

```
Then access SBT's Scala console

## problem
Console fails as follows:

```
 sbt
[info] Loading settings for project skeleton-211-build from plugins.sbt ...
[info] Loading project definition from /home/ice/coding/Scala/skeleton-211/project
[info] Loading settings for project skeleton-211 from build.sbt,compiler.sbt ...
[info] Set current project to scala-211-java11 (in build file:/home/ice/coding/Scala/skeleton-211/)
[info] sbt server started at local:///home/ice/.sbt/1.0/server/e7fa6f6fb5c673698344/sock
sbt:scala-211-java11> console
[info] Compiling 1 Scala source to /home/ice/coding/Scala/skeleton-211/target/scala-2.11/classes ...
[info] Starting scala interpreter...
Welcome to Scala 2.11.12 (OpenJDK 64-Bit Server VM, Java 11.0.7).
Type in expressions for evaluation. Or try :help.
[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "0x100"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.valueOf(Integer.java:983)
	at jline.internal.InfoCmp.parseInfoCmp(InfoCmp.java:59)
	at jline.UnixTerminal.parseInfoCmp(UnixTerminal.java:242)
	at jline.UnixTerminal.<init>(UnixTerminal.java:65)
	at jline.UnixTerminal.<init>(UnixTerminal.java:50)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at jline.TerminalFactory.getFlavor(TerminalFactory.java:211)
	at jline.TerminalFactory.create(TerminalFactory.java:102)
	at jline.TerminalFactory.get(TerminalFactory.java:186)
	at jline.TerminalFactory.get(TerminalFactory.java:192)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:243)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:235)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:223)
	at scala.tools.nsc.interpreter.jline.JLineConsoleReader.<init>(JLineReader.scala:64)
	at scala.tools.nsc.interpreter.jline.InteractiveReader.<init>(JLineReader.scala:33)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$scala$tools$nsc$interpreter$ILoop$$instantiater$1$1.apply(ILoop.scala:858)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$scala$tools$nsc$interpreter$ILoop$$instantiater$1$1.apply(ILoop.scala:855)
	at scala.tools.nsc.interpreter.ILoop.scala$tools$nsc$interpreter$ILoop$$mkReader$1(ILoop.scala:862)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$22$$anonfun$apply$10.apply(ILoop.scala:873)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$22$$anonfun$apply$10.apply(ILoop.scala:873)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$22.apply(ILoop.scala:873)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$22.apply(ILoop.scala:873)
	at scala.collection.immutable.Stream.map(Stream.scala:418)
	at scala.tools.nsc.interpreter.ILoop.chooseReader(ILoop.scala:873)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1$$anonfun$newReader$1$1.apply(ILoop.scala:893)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.newReader$1(ILoop.scala:893)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.scala$tools$nsc$interpreter$ILoop$$anonfun$$preLoop$1(ILoop.scala:897)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1$$anonfun$startup$1$1.apply(ILoop.scala:964)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:990)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:891)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:891)
	at scala.reflect.internal.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:97)
	at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:891)
	at xsbt.ConsoleInterface.run(ConsoleInterface.scala:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
	at sbt.internal.inc.AnalyzingCompiler.console(AnalyzingCompiler.scala:210)
	at sbt.Console.console0$1(Console.scala:48)
	at sbt.Console.$anonfun$apply$2(Console.scala:51)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
	at sbt.TrapExit$App.run(TrapExit.scala:257)
	at java.base/java.lang.Thread.run(Thread.java:834)
````

## expectation

SBT Console should work. This works ok on Scala 2.13 on the same and other machine.

## notes

```
$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal

$ uname -a
Linux x 5.4.0-29-generic #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ dpkg -s openjdk-11-jdk-headless
Package: openjdk-11-jdk-headless
Status: install ok installed
Priority: optional
Section: java
Installed-Size: 221562
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Multi-Arch: same
Source: openjdk-lts
Version: 11.0.7+10-3ubuntu1
Replaces: openjdk-11-jre-headless (<< 11~19-2)
Provides: java-compiler, java-sdk-headless, java10-sdk-headless, java11-sdk-headless, java2-sdk-headless, java5-sdk-headless, java6-sdk-headless, java7-sdk-headless, java8-sdk-headless, java9-sdk-headless
Depends: openjdk-11-jre-headless (= 11.0.7+10-3ubuntu1), libc6 (>= 2.2.5)
Suggests: openjdk-11-demo, openjdk-11-source
Conflicts: openjdk-11-jre-headless (<< 11~19-2)
Description: OpenJDK Development Kit (JDK) (headless)
 OpenJDK is a development environment for building applications,
 applets, and components using the Java programming language.
Homepage: http://openjdk.java.net/
Original-Maintainer: OpenJDK Team <openjdk@lists.launchpad.net>

$ java -version
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-3ubuntu1, mixed mode, sharing)
```

**Comment by fernandoracca** [comment]
Related issues and source:
https://github.com/sbt/sbt/blob/develop/main/src/main/scala/sbt/internal/CrossJava.scala
https://github.com/sbt/sbt/blob/develop/main/src/test/scala/sbt/internal/CrossJavaTest.scala

https://github.com/sbt/sbt/issues/4731
https://github.com/sbt/sbt/issues/5011
https://github.com/sbt/sbt/issues/5478

**Comment by fernandoracca** [comment]
A colleague of mine mentioned this Scala bug report, and a very quick workaround -
https://github.com/scala/bug/issues/11723

```
export TERM=xterm-color
x@a:~/coding/Scala/skeleton-211$ sbt
[info] Loading settings for project skeleton-211-build from plugins.sbt ...
[info] Loading project definition from /home/x/coding/Scala/skeleton-211/project
[info] Loading settings for project skeleton-211 from build.sbt,compiler.sbt ...
[info] Set current project to scala-211-java11 (in build file:/home/x/coding/Scala/skeleton-211/)
[info] sbt server started at local:///home/x/.sbt/1.0/server/e7fa6f6fb5c673698344/sock
sbt:scala-211-java11> console
[info] Compiling 1 Scala source to /home/x/coding/Scala/skeleton-211/target/scala-2.11/classes ...
[info] Starting scala interpreter...
Welcome to Scala 2.11.12 (OpenJDK 64-Bit Server VM, Java 11.0.7).
Type in expressions for evaluation. Or try :help.

scala> 
```

Strangely, SBT seems to be using a version of JLine that should deal with this correctly according to same bug report.

https://github.com/sbt/sbt/blob/v1.3.10/project/Dependencies.scala#L122

**Comment by eed3si9n** [comment]
Thanks for the report.

I think the actual issue is https://github.com/scala/bug/issues/11723 / https://github.com/jline/jline2/issues/281, not sbt.

the following stack trace

```
	at jline.TerminalFactory.create(TerminalFactory.java:102)
	at jline.TerminalFactory.get(TerminalFactory.java:186)
	at jline.TerminalFactory.get(TerminalFactory.java:192)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:243)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:235)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:223)
	at scala.tools.nsc.interpreter.jline.JLineConsoleReader.<init>(JLineReader.scala:64)
	at scala.tools.nsc.interpreter.jline.InteractiveReader.<init>(JLineReader.scala:33)
```

also shows it's Scala REPL causing this. Scala 2.11.12 uses JLine 2.14.3 - https://github.com/scala/scala/blob/v2.11.12/versions.properties#L35.
