### ISSUE TITLE
VirtualFile breaks the Java compiler

### ISSUE THREAD

**Issue by adpi2** [sbt/sbt#5562]
## steps

Compile a sbt project containing java sources with latest sbt version.

## problem

Compilation fails with error:
```
[error] An exception has occurred in the compiler (1.8.0_252). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
[error] java.lang.IllegalArgumentException: Not supported: WrappedJavaFileObject[${0}/testing/agent/src/main/java/sbt/FrameworkWrapper.java]
[error] 	at com.sun.tools.javac.file.JavacFileManager.isSameFile(JavacFileManager.java:647)
[error] 	at com.sun.tools.javac.comp.Check.checkForBadAuxiliaryClassAccess(Check.java:3471)
[error] 	at com.sun.tools.javac.comp.Attr.checkIdInternal(Attr.java:3547)
[error] 	at com.sun.tools.javac.comp.Attr.checkId(Attr.java:3490)
[error] 	at com.sun.tools.javac.comp.Attr.visitIdent(Attr.java:3233)
[error] 	at com.sun.tools.javac.tree.JCTree$JCIdent.accept(JCTree.java:2011)
[error] 	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
[error] 	at com.sun.tools.javac.comp.Attr.attribType(Attr.java:638)
[error] 	at com.sun.tools.javac.comp.Attr.attribType(Attr.java:631)
[error] 	at com.sun.tools.javac.comp.Attr.visitNewClass(Attr.java:1970)
[error] 	at com.sun.tools.javac.tree.JCTree$JCNewClass.accept(JCTree.java:1516)
[error] 	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
[error] 	at com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:618)
[error] 	at com.sun.tools.javac.comp.Attr.visitAssign(Attr.java:2996)
[error] 	at com.sun.tools.javac.tree.JCTree$JCAssign.accept(JCTree.java:1686)
[error] 	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
[error] 	at com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:625)
[error] 	at com.sun.tools.javac.comp.Attr.visitExec(Attr.java:1593)
[error] 	at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1296)
[error] 	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
[error] 	at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:645)
[error] 	at com.sun.tools.javac.comp.Attr.visitIf(Attr.java:1582)
[error] 	at com.sun.tools.javac.tree.JCTree$JCIf.accept(JCTree.java:1269)
[error] 	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
[error] 	at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:645)
[error] 	at com.sun.tools.javac.comp.Attr.attribStats(Attr.java:661)
[error] 	at com.sun.tools.javac.comp.Attr.visitBlock(Attr.java:1124)
[error] 	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:909)
[error] 	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
[error] 	at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:645)
[error] 	at com.sun.tools.javac.comp.Attr.visitForLoop(Attr.java:1152)
[error] 	at com.sun.tools.javac.tree.JCTree$JCForLoop.accept(JCTree.java:1000)
[error] 	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
[error] 	at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:645)
[error] 	at com.sun.tools.javac.comp.Attr.attribStats(Attr.java:661)
[error] 	at com.sun.tools.javac.comp.Attr.visitBlock(Attr.java:1124)
[error] 	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:909)
[error] 	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
[error] 	at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:645)
[error] 	at com.sun.tools.javac.comp.Attr.visitMethodDef(Attr.java:1013)
[error] 	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:778)
[error] 	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
[error] 	at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:645)
[error] 	at com.sun.tools.javac.comp.Attr.attribClassBody(Attr.java:4364)
[error] 	at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4272)
[error] 	at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4201)
[error] 	at com.sun.tools.javac.comp.Attr.attrib(Attr.java:4176)
[error] 	at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1248)
[error] 	at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
[error] 	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
[error] 	at com.sun.tools.javac.main.Main.compile(Main.java:523)
[error] 	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
[error] 	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
[error] 	at sbt.internal.inc.javac.LocalJavaCompiler.run(LocalJava.scala:329)
[error] 	at sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$12(AnalyzingJavaCompiler.scala:164)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at sbt.internal.inc.javac.AnalyzingJavaCompiler.timed(AnalyzingJavaCompiler.scala:246)
[error] 	at sbt.internal.inc.javac.AnalyzingJavaCompiler.compile(AnalyzingJavaCompiler.scala:154)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$6(MixedAnalyzingCompiler.scala:150)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:198)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compileJava$1(MixedAnalyzingCompiler.scala:114)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:162)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:446)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:446)
[error] 	at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:137)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$6(Incremental.scala:111)
[error] 	at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:201)
[error] 	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:110)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$5(Incremental.scala:114)
[error] 	at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:176)
[error] 	at sbt.internal.inc.Incremental$.compile(Incremental.scala:102)
[error] 	at sbt.internal.inc.IncrementalCompile$.apply(IncrementalCompile.scala:82)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:452)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:401)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:264)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:347)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:79)
[error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1885)
[error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1858)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:184)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:41)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```

**Comment by adpi2** [comment]
With JDK 11 it is working fine though.
