### ISSUE TITLE
too noisy output when fork in testing is turned on and tests are failing

### ISSUE THREAD

**Issue by pk11** [sbt/sbt#557]
the console is full of "Cannot write to socket" noisy and unhelpful messages when tests are failing.

https://github.com/harrah/xsbt/blob/0.13/testing/agent/src/main/java/sbt/ForkMain.java#L109
it's coming from here but it does not really add anything useful

**Comment by vigdorchik** [comment]
This message is present when the socket connection is broken and the agent cannot communicate tests results back to sbt, not when tests are failing. We have to figure out why the connection gets broken.

**Comment by pk11** [comment]
In case of play, this error message is shown only when a test is failing, hence my description. Since these are system errors, we can not even filter them out.  

Please see an example below:

```
Exception in thread "Thread-3" java.lang.NullPointerException
    at sbt.PlayTestListener$$anonfun$testEvent$1.apply(PlayTestListener.scala:60)
    at sbt.PlayTestListener$$anonfun$testEvent$1.apply(PlayTestListener.scala:53)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:34)
    at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:33)
    at sbt.PlayTestListener.testEvent(PlayTestListener.scala:53)
    at sbt.ForkTests$$anonfun$apply$2$Acceptor$2$$anonfun$react$1$7.apply(ForkTests.scala:62)
    at sbt.ForkTests$$anonfun$apply$2$Acceptor$2$$anonfun$react$1$7.apply(ForkTests.scala:62)
    at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
    at scala.collection.immutable.List.foreach(List.scala:76)
    at sbt.ForkTests$$anonfun$apply$2$Acceptor$2$.react$1(ForkTests.scala:62)
    at sbt.ForkTests$$anonfun$apply$2$Acceptor$2$.react$1(ForkTests.scala:56)
    at sbt.ForkTests$$anonfun$apply$2$Acceptor$2$.react$1(ForkTests.scala:56)
    at sbt.ForkTests$$anonfun$apply$2$Acceptor$2$.react$1(ForkTests.scala:56)
    at sbt.ForkTests$$anonfun$apply$2$Acceptor$2$.react$1(ForkTests.scala:56)
    at sbt.ForkTests$$anonfun$apply$2$Acceptor$2$.react$1(ForkTests.scala:56)
    at sbt.ForkTests$$anonfun$apply$2$Acceptor$2$.react$1(ForkTests.scala:56)
    at sbt.ForkTests$$anonfun$apply$2$Acceptor$2$.react$1(ForkTests.scala:56)
    at sbt.ForkTests$$anonfun$apply$2$Acceptor$2$.react$1(ForkTests.scala:56)
    at sbt.ForkTests$$anonfun$apply$2$Acceptor$2$.react$1(ForkTests.scala:56)
    at sbt.ForkTests$$anonfun$apply$2$Acceptor$2$.react$1(ForkTests.scala:54)
    at sbt.ForkTests$$anonfun$apply$2$Acceptor$2$.react$1(ForkTests.scala:54)
    at sbt.ForkTests$$anonfun$apply$2$Acceptor$2$.react$1(ForkTests.scala:56)
    at sbt.ForkTests$$anonfun$apply$2$Acceptor$2$.react$1(ForkTests.scala:56)
    at sbt.ForkTests$$anonfun$apply$2$Acceptor$2$.react$1(ForkTests.scala:56)
    at sbt.ForkTests$$anonfun$apply$2$Acceptor$2$.run(ForkTests.scala:84)
    at java.lang.Thread.run(Thread.java:680)
Cannot write to socket
Cannot write to socket
Cannot write to socket
Cannot write to socket
Cannot write to socket
Cannot write to socket
Cannot write to socket
Cannot write to socket
Cannot write to socket
Cannot write to socket
Cannot write to socket
Cannot write to socket
Cannot write to socket
Cannot write to socket
Cannot write to socket
Cannot write to socket
Cannot write to socket
Cannot write to socket
Cannot write to socket
Cannot write to socket
Cannot write to socket
Cannot write to socket
Cannot write to socket
Cannot write to socket
```

**Comment by vigdorchik** [comment]
Aha, I see. The NPE at PlayTestListener.scala:60 nukes the thread that listens to the test results. Is the bogus code at PlayTestListener part of play or user code?

**Comment by vigdorchik** [comment]
Ok, so play relies on 'error' being non-null. In the release 0.12.1 version it's null, and has been addressed in https://github.com/harrah/xsbt/pull/544
I think it's safe to integrate this change into the next 0.12 version, but in the meantime you can check for null error.

**Comment by pk11** [comment]
I see, I will modify our listener to avoid the NPE - Thanks! That said, I still believe the system errors "Cannot write to socket" printed on the console are just noise (the user does not benefit from them, since the exception is printed already)

**Comment by harrah** [comment]
What is the conclusion?  Is there a bug in sbt that needs to be fixed?

**Comment by vigdorchik** [comment]
I would say no. The message is printed directly to stdout only when the connection with the master in sbt process is lost, like in your example. In other cases the communication goes through master/agent socket. The master should not die, so maybe it makes sense to protect the calls to external methods. Still it's the client of API who should fix the problem in the first place. Also the request as formulated here can't be easily fixed.

**Comment by pk11** [comment]
@vigdorchik What I am just suggesting is to get rid of `System.err.println("Cannot write to socket");` since it's not user friendly. As my example above demonstrates, it can pollute the output for no good reason (the stacktrace has all the useful information there)

**Comment by pk11** [comment]
@vigdorchik we did fix the NPE that triggered this error from our end but that does not change the fact that the message was not useful and other users can run into this as well.

**Comment by vigdorchik** [comment]
@pk11 Your scenario when the agent cannot write to the socket may not be the only one. What the agent faces is that it cannot communicate the test results back to sbt, so it can only write to stdout. At this point it cannot write anything more meaningful, also writing nothing doesn't look right either, since there might be no other way to signal broken socket.

**Comment by pk11** [comment]
@vigdorchik there is an exception there as well - that's more than enough for a user. Anyway, I am not going to argue this further, if you do not consider the included output as bad user experience then we have to agree to disagree here.

**Comment by harrah** [comment]
I think you guys are talking past each other.  I doubt @vigdorchik would argue repeating the same message is helpful, but doesn't want to end up in a situation where there isn't an error message.  I don't think @pk11 would argue that no message should be output, but doesn't see why the same message needs to be repeated.  I don't really want to get into this, so I'd appreciate it if you guys would resolve this.  Why is the message repeated, is it avoidable, if this only shows up when there is a bug in a test listener or some internal bug, can the error message be improved to indicate that?, etc...

**Comment by vigdorchik** [comment]
I think we could avoid message duplication if we accept that once the socket is broken it's broken forever, so we can give up running further; also the message could be improved and could explicitly say the run has been aborted. @pk11 what do you think of such change?

**Comment by pk11** [comment]
that sounds perfect - thanks guys!
