### ISSUE TITLE
sbt 1.4.0 ScriptedPlugin reflectively calls methods that do not exist

### ISSUE THREAD

**Issue by bishabosha** [sbt/sbt#5592]
## steps

publish local sbt with commit b1192c9021970fdd4252498ca5fcf9d7cffa9b32

- create seed `sbt new scala/hello-world.g8`
- change `sbt.version` to `1.4.0-SNAPSHOT`
- add a basic subproject `foo-plugin` for a plugin that extends AutoPlugin, with no definitions, in say `foo-plugin/src/main/scala` dir
- add basic `foo-plugin/src/sbt-test` scripted test that calls `run` on a basic hello world project
- run `foo-plugin/scripted`

## problem
`foo-plugin/scripted` crashes with `java.lang.NoSuchMethodException`:

```scala
sbt:hello-world> foo-plugin/scripted
[info] Wrote /Users/jamie/Workspace/sbt-1_4-playground/foo-plugin/target/scala-2.12/sbt-1.0/foo-plugin-0.1.0-SNAPSHOT.pom
[info] Compiling 1 Scala source to /Users/jamie/Workspace/sbt-1_4-playground/foo-plugin/target/scala-2.12/sbt-1.0/classes ...
[info] Main Scala API documentation to /Users/jamie/Workspace/sbt-1_4-playground/foo-plugin/target/scala-2.12/sbt-1.0/api...
model contains 2 documentable templates
[info] Main Scala API documentation successful.
[info] :: delivering :: foo-plugin#foo-plugin;0.1.0-SNAPSHOT :: 0.1.0-SNAPSHOT :: integration :: Thu Jun 04 18:36:44 CEST 2020
[info] 	delivering ivy file to /Users/jamie/Workspace/sbt-1_4-playground/foo-plugin/target/scala-2.12/sbt-1.0/ivy-0.1.0-SNAPSHOT.xml
[info] 	published foo-plugin to /Users/jamie/.ivy2/local/foo-plugin/foo-plugin/scala_2.12/sbt_1.0/0.1.0-SNAPSHOT/poms/foo-plugin.pom
[info] 	published foo-plugin to /Users/jamie/.ivy2/local/foo-plugin/foo-plugin/scala_2.12/sbt_1.0/0.1.0-SNAPSHOT/jars/foo-plugin.jar
[info] 	published foo-plugin to /Users/jamie/.ivy2/local/foo-plugin/foo-plugin/scala_2.12/sbt_1.0/0.1.0-SNAPSHOT/srcs/foo-plugin-sources.jar
[info] 	published foo-plugin to /Users/jamie/.ivy2/local/foo-plugin/foo-plugin/scala_2.12/sbt_1.0/0.1.0-SNAPSHOT/docs/foo-plugin-javadoc.jar
[info] 	published ivy to /Users/jamie/.ivy2/local/foo-plugin/foo-plugin/scala_2.12/sbt_1.0/0.1.0-SNAPSHOT/ivys/ivy.xml
[error] stack trace is suppressed; run last foo-plugin / scriptedRun for the full output
[error] (foo-plugin / scriptedRun) java.lang.NoSuchMethodException: sbt.scriptedtest.ScriptedTests$.run(java.io.File, boolean, [Ljava.lang.String;, java.io.File, [Ljava.lang.String;, java.util.List)
```

trace:

```scala
sbt:hello-world> last foo-plugin / scriptedRun
[error] java.lang.NoSuchMethodException: sbt.scriptedtest.ScriptedTests$.run(java.io.File, boolean, [Ljava.lang.String;, java.io.File, [Ljava.lang.String;, java.util.List)
[error] 	at java.lang.Class.getMethod(Class.java:1786)
[error] 	at sbt.ScriptedPlugin$.$anonfun$scriptedRunTask$1(ScriptedPlugin.scala:117)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:184)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:41)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (foo-plugin / scriptedRun) java.lang.NoSuchMethodException: sbt.scriptedtest.ScriptedTests$.run(java.io.File, boolean, [Ljava.lang.String;, java.io.File, [Ljava.lang.String;, java.util.List)

```

It looks like the reflective caller below does not align with any of the methods declared in source code:

https://github.com/sbt/sbt/blob/b1192c9021970fdd4252498ca5fcf9d7cffa9b32/main/src/main/scala/sbt/ScriptedPlugin.scala#L115

here in `def scriptedRunTask` the methods searched with reflection do not exist on the classes returned by the `scriptedTests` task.

## expectation

I should expect the `foo-plugin/scripted` test to succeed

## notes

I used the following settings in main project:

```scala
scalaVersion := "2.13.1"
organization := "ch.epfl.scala"
version := "1.0-SNAPSHOT"

lazy val `foo-plugin` = (project in file("foo-plugin"))
  .enablePlugins(SbtPlugin)
  .settings(
    name := "foo-plugin",
    scriptedLaunchOpts := { scriptedLaunchOpts.value ++
      Seq("-Xmx1024M", "-Dplugin.version=" + version.value)
    },
    scriptedBufferLog := false
  )
```

scripted test `foo-plugin/src/sbt-test/simple/test`:
```
> run
```

with scripted test plugins in `foo-plugin/src/sbt-test/simple/project/plugins.sbt`:
```scala
sys.props.get("plugin.version") match {
  case Some(x) => addSbtPlugin("ch.epfl.scala" % "foo-plugin" % x)
  case _ => sys.error("""|The system property 'plugin.version' is not defined.
                         |Specify this property using the scriptedLaunchOpts -D.""".stripMargin)
}
```
and scripted test build file in `foo-plugin/src/sbt-test/simple/build.sbt`:
```scala
lazy val root = (project in file("."))
  .settings(
    version := "0.1",
    scalaVersion := "2.13.1",
    isFoo := true
  )
```
and single source in `foo-plugin/src/sbt-test/foo-plugin/simple/src/main/scala/hello/Hello.scala`:
```scala
package hello

object Hello {
  def main(args: Array[String]): Unit = {
    println(s"Hello, World!")
  }
}
```

**Comment by eed3si9n** [comment]
@bishabosha Thanks for the report.

**Comment by bishabosha** [comment]
@eatkins it looks like the methods were deleted here https://github.com/sbt/sbt/pull/5367

**Comment by eed3si9n** [comment]
Here's my PR for this - https://github.com/sbt/sbt/pull/5615
