### ISSUE TITLE
sbt new command fails with error on windows environment

### ISSUE THREAD

**Issue by PashoQ** [sbt/sbt#5617]
## steps

sbt version 1.3.12

## problem

when run command 
`sbt new scala/scala-seed.g8`
It fails with this error

PS C:\Dev\Temp\t> sbt new scala/scala-seed.g8
[info] welcome to sbt 1.3.12 (AdoptOpenJDK Java 1.8.0_252)
[info] loading settings for project global-plugins from dependency-graph.sbt,updates.sbt ...
[info] loading global plugins from C:\Users\id967052\.sbt\1.0\plugins
[info] set current project to t (in build file:/C:/Dev/Temp/t/)
[info] set current project to t (in build file:/C:/Dev/Temp/t/)

A minimal Scala project.

name [Scala Seed Project]:
java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\\
        at java.util.regex.Pattern.error(Pattern.java:1969)
        at java.util.regex.Pattern.compile(Pattern.java:1708)
        at java.util.regex.Pattern.<init>(Pattern.java:1352)
        at java.util.regex.Pattern.compile(Pattern.java:1028)
        at java.lang.String.split(String.java:2380)
        at java.lang.String.split(String.java:2422)
        at giter8.G8$.expandPath(g8.scala:212)
        at giter8.G8$.$anonfun$writeTemplates$1(g8.scala:488)
        at scala.collection.immutable.Stream.map(Stream.scala:418)
        at giter8.G8$.writeTemplates(g8.scala:486)
        at giter8.G8$.$anonfun$applyT$1(g8.scala:347)
        at scala.util.Either$RightProjection.flatMap(Either.scala:701)
        at giter8.G8$.applyT(g8.scala:330)
        at giter8.G8$.fromDirectory(g8.scala:76)
        at giter8.G8TemplateRenderer$.render(TemplateRenderer.scala:40)
        at giter8.AppProcessor.process(giter8.scala:58)
        at giter8.Runner.$anonfun$run$9(Runner.scala:54)
        at scala.util.Either.flatMap(Either.scala:341)
        at giter8.Runner.$anonfun$run$5(Runner.scala:51)
        at scala.util.Either.flatMap(Either.scala:341)
        at giter8.Runner.$anonfun$run$4(Runner.scala:50)
        at scala.util.Either.flatMap(Either.scala:341)
        at giter8.Runner.run(Runner.scala:49)
        at giter8.Giter8.run(giter8.scala:33)
        at giter8.Giter8.run(giter8.scala:30)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at giter8.LauncherProcessor.call(LauncherMain.scala:113)
        at giter8.LauncherProcessor.virtuallyRun(LauncherMain.scala:87)
        at giter8.LauncherProcessor.process(LauncherMain.scala:38)
        at giter8.Runner.$anonfun$run$9(Runner.scala:54)
        at scala.util.Either.flatMap(Either.scala:341)
        at giter8.Runner.$anonfun$run$5(Runner.scala:51)
        at scala.util.Either.flatMap(Either.scala:341)
        at giter8.Runner.$anonfun$run$4(Runner.scala:50)
        at scala.util.Either.flatMap(Either.scala:341)
        at giter8.Runner.run(Runner.scala:49)
        at giter8.Runner.run(Runner.scala:75)
        at sbtgiter8resolver.Giter8TemplateResolver.run(Giter8TemplateResolver.scala:34)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sbt.TemplateCommandUtil$.call(TemplateCommandUtil.scala:121)
        at sbt.TemplateCommandUtil$.runTemplate(TemplateCommandUtil.scala:96)
        at sbt.TemplateCommandUtil$.$anonfun$run$1(TemplateCommandUtil.scala:72)
        at sbt.TemplateCommandUtil$.$anonfun$run$1$adapted(TemplateCommandUtil.scala:68)
        at scala.collection.LinearSeqOptimized.find(LinearSeqOptimized.scala:115)
        at scala.collection.LinearSeqOptimized.find$(LinearSeqOptimized.scala:112)
        at scala.collection.immutable.List.find(List.scala:89)
        at sbt.TemplateCommandUtil$.run(TemplateCommandUtil.scala:68)
        at sbt.TemplateCommandUtil$.runTemplate(TemplateCommandUtil.scala:55)
        at sbt.TemplateCommandUtil$.$anonfun$templateCommand$2(TemplateCommandUtil.scala:25)
        at sbt.Command$.$anonfun$applyEffect$4(Command.scala:149)
        at sbt.Command$.$anonfun$applyEffect$2(Command.scala:144)
        at sbt.Command$.process(Command.scala:187)
        at sbt.MainLoop$.process$1(MainLoop.scala:199)
        at sbt.MainLoop$.processCommand(MainLoop.scala:233)
        at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:147)
        at sbt.State$StateOpsImpl$.runCmd$1(State.scala:273)
        at sbt.State$StateOpsImpl$.process$extension(State.scala:277)
        at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:147)
        at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
        at sbt.MainLoop$.next(MainLoop.scala:147)
        at sbt.MainLoop$.run(MainLoop.scala:138)
        at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:116)
        at sbt.io.Using.apply(Using.scala:27)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:110)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:65)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:50)
        at sbt.MainLoop$.runLogged(MainLoop.scala:41)
        at sbt.StandardMain$.runManaged(Main.scala:132)
        at sbt.xMain$.run(Main.scala:67)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:45)
        at sbt.xMain.run(Main.scala:39)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:130)
        at xsbt.boot.Launch$.run(Launch.scala:111)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
        at xsbt.boot.Launch$.launch(Launch.scala:119)
        at xsbt.boot.Launch$.apply(Launch.scala:20)
        at xsbt.boot.Boot$.runImpl(Boot.scala:56)
        at xsbt.boot.Boot$.main(Boot.scala:18)
        at xsbt.boot.Boot.main(Boot.scala)
[error] java.io.IOException: Unable to delete file: C:\Dev\Temp\giter8-15070555583700\src\main\g8\.gitignore
[error] Use 'last' for the full log.

## expectation

It should generate project template on Windows

## notes

same command works on Llinux  as expected and generates template just fine

**Comment by eed3si9n** [comment]
@PashoQ  `sbt new` sends template processing to a template resolver. Could you report it to https://github.com/foundweekends/giter8/issues please?
