### ISSUE TITLE
Crash: 'URI has an authority component' while processing dependencies

### ISSUE THREAD

**Issue by dragos** [sbt/sbt#564]
I found this stack trace in my logs (using 0.13.0-SNAPSHOT):

```
java.lang.IllegalArgumentException: URI has an authority component
    at java.io.File.<init>(File.java:368)
    at sbt.IO$.urlAsFile(IO.scala:77)
    at sbt.classfile.Analyze$$anonfun$apply$9$$anonfun$processDependency$1$1$$anonfun$apply$mcV$sp$1.apply(Analyze.scala:48)
    at sbt.classfile.Analyze$$anonfun$apply$9$$anonfun$processDependency$1$1$$anonfun$apply$mcV$sp$1.apply(Analyze.scala:48)
    at scala.Option.foreach(Option.scala:197)
    at sbt.classfile.Analyze$$anonfun$apply$9$$anonfun$processDependency$1$1.apply$mcV$sp(Analyze.scala:48)
    at sbt.classfile.Analyze$.sbt$classfile$Analyze$$trapAndLog(Analyze.scala:78)
    at sbt.classfile.Analyze$$anonfun$apply$9.processDependency$1(Analyze.scala:47)
    at sbt.classfile.Analyze$$anonfun$apply$9$$anonfun$apply$12.apply(Analyze.scala:65)
    at sbt.classfile.Analyze$$anonfun$apply$9$$anonfun$apply$12.apply(Analyze.scala:65)
    at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:130)
    at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:275)
    at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:275)
    at sbt.classfile.Analyze$$anonfun$apply$9.apply(Analyze.scala:65)
    at sbt.classfile.Analyze$$anonfun$apply$9.apply(Analyze.scala:42)
    at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:95)
    at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:95)
    at scala.collection.Iterator$class.foreach(Iterator.scala:772)
    at scala.collection.mutable.HashTable$$anon$1.foreach(HashTable.scala:157)
    at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:190)
    at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:45)
    at scala.collection.mutable.HashMap.foreach(HashMap.scala:95)
    at sbt.classfile.Analyze$.apply(Analyze.scala:42)
```

The classpath contains UNC paths, like so:

`\\foo\dist\bar\sunjdk\1.6.0_31\exec\jre\lib\resources.jar;\\foo\dist\bar\sunjdk\1.6.0_31\exec\jre\lib\rt.jar;`

**Comment by vigdorchik** [comment]
The following code looks suspicious:
https://github.com/harrah/xsbt/blob/0.13/util/io/IO.scala#L77
I don't understand why URI is constructed from path.

**Comment by harrah** [comment]
A URL with `jar` as its protocol has the form `jar:<url-of-jar-file>!/path/inside/jar`.  The linked code will extract `<url-of-jar-file>` and pass that to URI constructor.  Java is known to handle UNC poorly in certain cases, so that is one possible cause.  For example, http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=5086147, but that was supposed to be fixed in Java 1.6.

**Comment by dragos** [comment]
I get the following error with the patched Sbt. I hope this helps:

```
 Could not convert URL 'jar:file://foo/dist/bar/sunjdk/1.6.0_31/exec/jre/lib/rt.jar!/java/lang/Enum.class' to File: java.lang.IllegalArgumentException: URI has an authority component
```

**Comment by kyj17096** [comment]
I happend to this problem. may be two reasons
1. there may be space in sbt installation path
2. get clue from this link https://github.com/typesafehub/activator/issues/1033, just delete the C:\Users<username>.sbt*.*
