### ISSUE TITLE
[1.4.0-M1] sbt-explicit-dependencies plugin task error

### ISSUE THREAD

**Issue by anilkumarmyla** [sbt/sbt#5644]
Just tried out 1.4.0-M1, all commands work except `unusedCompileDependencies` provided by `sbt-explicit-dependencies` plugin, stack trace included. Hopefully its an sbt issue, let me know if its a plugin issue

## steps
-sbt.version=1.3.12
+sbt.version=1.4.0-M1

## problem
```
sbt unusedCompileDependencies
[info] welcome to sbt 1.4.0-M1 (AdoptOpenJDK Java 1.8.0_252)
...
[error] java.lang.ClassCastException: sbt.internal.inc.MappedVirtualFile cannot be cast to java.io.File
[error] 	at scala.collection.TraversableLike.$anonfun$filterImpl$1(TraversableLike.scala:291)
[error] 	at scala.collection.immutable.HashMap$HashMapKeys.$anonfun$foreach$1(HashMap.scala:145)
[error] 	at scala.collection.immutable.HashMap$HashMap1.foreachEntry(HashMap.scala:371)
[error] 	at scala.collection.immutable.HashMap$HashTrieMap.foreachEntry(HashMap.scala:682)
[error] 	at scala.collection.immutable.HashMap$HashMapKeys.foreach(HashMap.scala:145)
[error] 	at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:290)
[error] 	at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:284)
[error] 	at scala.collection.AbstractTraversable.filterImpl(Traversable.scala:108)
[error] 	at scala.collection.TraversableLike.filter(TraversableLike.scala:382)
[error] 	at scala.collection.TraversableLike.filter$(TraversableLike.scala:382)
[error] 	at scala.collection.AbstractTraversable.filter(Traversable.scala:108)
[error] 	at explicitdeps.Logic$.getCompileDependencies(Logic.scala:67)
[error] 	at explicitdeps.Logic$.getUnusedCompileDependencies(Logic.scala:45)
[error] 	at explicitdeps.ExplicitDepsPlugin$.$anonfun$unusedCompileDependenciesTask$1(ExplicitDepsPlugin.scala:76)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:210)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:52)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (unusedCompileDependencies) java.lang.ClassCastException: sbt.internal.inc.MappedVirtualFile cannot be cast to java.io.File
```

## expectation
sbt task works

**Comment by eed3si9n** [comment]
Thanks for the report. Could you provide reproduction steps so we can reproduce your problem on _our computers_?

**Comment by anilkumarmyla** [comment]
@eed3si9n Sorry, generated one repo https://github.com/anilkumarmyla/issue-5644 fresh off of scala-seed.g8
It just has a new file `project/sbt-explicit-dependencies.sbt` and changed build.properties to 1.4.0-M1. Run `sbt unusedCompileDependencies` to reproduce the error

**Comment by eed3si9n** [comment]
Thanks for the repro project.

**Comment by anilkumarmyla** [comment]
also reported here https://github.com/cb372/sbt-explicit-dependencies/issues/70
