### ISSUE TITLE
BSP server does not respond when connected sbt server is closed

### ISSUE THREAD

**Issue by jastice** [sbt/sbt#5651]
## steps

1. start an sbt shell on a project
2. start a BSP server for the same project (eg via opening it in IntelliJ)
3. the BSP server will connect to the existing shell
4. close the shell

## problem
1. BSP server throws an error:
```
Exception in thread "Thread-0" java.lang.ArrayIndexOutOfBoundsException: arraycopy: length -1 is negative
at java.base/java.lang.System.arraycopy(Native Method)
at java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:129)
at java.base/java.io.PrintStream.write(PrintStream.java:559)
at sbt.internal.client.BspClient.sbt$internal$client$BspClient$$transferTo(BspClient.scala:26)
at sbt.internal.client.BspClient$$anon$1.run(BspClient.scala:34)
```
2. running a request on the server hangs indefinitely with no response.

## expectation

Either:
* BSP server exits, so client can start a fresh process, or
* BSP server responds with error on request, or
* BSP server start its own fresh sbt process

**Comment by adpi2** [comment]
I would be in favor of the first solution:
- BSP server exits, so client can start a fresh process

I see the `sbt -bsp` process more like a broker. So if the main sbt server is killed, the BSP client would be responsible to start a new process.

What do you and others think?

**Comment by jastice** [comment]
Yes, I think that's the simplest solution, since the client needs to do it anyway if the bsp server process quits for any other reason.
