### ISSUE TITLE
CoursierInputsTasks#credentialsTask fails to resolve credentials during project initialization

### ISSUE THREAD

**Issue by onmomo** [sbt/sbt#5658]
Since my build.sbt is not even loaded at the moment in time, I don't know of any other way to provide Coursier with credentials. The way I configured the credentials system-wide worked for sbt with ivy since sbt 0.13.0.

## workaround 
To make sbt load the project again with ivy, start with `sbt -Dsbt.coursier=false`

## steps

* sbt 1.3.12 with a clean coursier cache
* add to the project root `.sbtopts` ->
```
-Dsbt.repository.config=project/proxy-repositories
-Dsbt.override.build.repos=true
```
OR make sure any other way sbt resolves completely via an authenticated repository manager with a global config

* add proxy-repositories file
```
[repositories]
# Consider locally cached ivy artifacts
local
# Consider locally cached maven artifacts
maven-local
# We use the the repository as proxy for all sbt and project dependencies. Credentials are required in order to login.
# Proxy all requests to resolve sbt itself from the internal proxy repository, as well as any sbt plugins that may be required.
acme-ivy-proxy-sbt-repos: https://acme.jfrog.io/acme/sbt-repos/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
# Proxy all standard maven repositories with the internal sbt proxy repository
acme-maven-proxy-sbt-repos: https://acme.jfrog.io/acme/sbt-repos/
# Proxy all standard maven repositories with the internal maven proxy repository
acme-maven-proxy-releases: https://acme.jfrog.io/acme/maven-remotes/

```
* add file to `~/.ivy/.credentials`
```
realm=Artifactory Realm
host=acme.jfrog.io
user=$USERNAME
password=APIKEY
```
* add `~/.sbt/1.0/plugins/global.sbt`
```
credentials += Credentials(Path.userHome / ".ivy2" / ".credentials")
```
(also tried to move this to `~/.sbt/1.0/global.sbt`), since it seems to be the default location but did not help.

* add `export SBT_CREDENTIALS=~/.ivy2/.credentials` to `~/.zshrc` or ~/.bashrc (this is probably not relevant for this issue.)
I skipped the credentials I configured in the project itself since the project is not yet loaded.
* set a breakpoint at LMCoursier:255
* `sbt -Dsbt.coursier=true -jvm-debug 5005`
* Check the result of `LMCoursier.allCredentialsTask` task. -> it doesn't return any credentials for my env

## problem

The project can't be loaded because coursier dependency resolution won't provide credentials to the repository manager.
Initializing the project with `-Dsbt.coursier=false` resolves the dependencies as expected.
```
sbt -Dsbt.coursier=true -jvm-debug 5005
Listening for transport dt_socket at address: 5005
Warning: a legacy coursier cache was found at /Users/username/.coursier/cache/v1 and is currently being used.

Support for that cache location will be removed in coursier 2.0.0 final, whose release is imminent.

Follow the instructions at
  https://github.com/coursier/cache-migration#cache-migration
in order to migrate your cache to the newer location.


[info] welcome to sbt 1.3.12 (Oracle Corporation Java 11.0.2)
[info] loading global plugins from /Users/username/.sbt/1.0/plugins/project
[info] Updating 
[info] Resolved  dependencies
[warn] 
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading org.scala-sbt:sbt:1.3.12
[error]   Not found
[error]   Not found
[error]   not found: /Users/username/.ivy2/local/org.scala-sbt/sbt/1.3.12/ivys/ivy.xml
[error]   not found: /Users/username/.m2/repository/org/scala-sbt/sbt/1.3.12/sbt-1.3.12.pom
[error]   unauthorized: https://acme.jfrog.io/acme/sbt-repos/org.scala-sbt/sbt/1.3.12/ivys/ivy.xml (Artifactory Realm)
[error]   unauthorized: https://acme.jfrog.io/acme/sbt-repos/org/scala-sbt/sbt/1.3.12/sbt-1.3.12.pom (Artifactory Realm)
[error]   unauthorized: https://acme.jfrog.io/acme/maven-remotes/org/scala-sbt/sbt/1.3.12/sbt-1.3.12.pom (Artifactory Realm)
[error] Error downloading org.scala-lang:scala-library:2.12.10
[error]   Not found
[error]   Not found
[error]   not found: /Users/username/.ivy2/local/org.scala-lang/scala-library/2.12.10/ivys/ivy.xml
[error]   not found: /Users/username/.m2/repository/org/scala-lang/scala-library/2.12.10/scala-library-2.12.10.pom
[error]   unauthorized: https://acme.jfrog.io/acme/sbt-repos/org.scala-lang/scala-library/2.12.10/ivys/ivy.xml (Artifactory Realm)
[error]   unauthorized: https://acme.jfrog.io/acme/sbt-repos/org/scala-lang/scala-library/2.12.10/scala-library-2.12.10.pom (Artifactory Realm)
[error]   unauthorized: https://acme.jfrog.io/acme/maven-remotes/org/scala-lang/scala-library/2.12.10/scala-library-2.12.10.pom (Artifactory Realm)
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:249)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$35(CoursierDependencyResolution.scala:218)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:218)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:52)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:102)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:115)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:115)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:96)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:129)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2950)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.scala-sbt:sbt:1.3.12
[error]   Not found
[error]   Not found
[error]   not found: /Users/username/.ivy2/local/org.scala-sbt/sbt/1.3.12/ivys/ivy.xml
[error]   not found: /Users/username/.m2/repository/org/scala-sbt/sbt/1.3.12/sbt-1.3.12.pom
[error]   unauthorized: https://acme.jfrog.io/acme/sbt-repos/org.scala-sbt/sbt/1.3.12/ivys/ivy.xml (Artifactory Realm)
[error]   unauthorized: https://acme.jfrog.io/acme/sbt-repos/org/scala-sbt/sbt/1.3.12/sbt-1.3.12.pom (Artifactory Realm)
[error]   unauthorized: https://acme.jfrog.io/acme/maven-remotes/org/scala-sbt/sbt/1.3.12/sbt-1.3.12.pom (Artifactory Realm)
[error] Error downloading org.scala-lang:scala-library:2.12.10
[error]   Not found
[error]   Not found
[error]   not found: /Users/username/.ivy2/local/org.scala-lang/scala-library/2.12.10/ivys/ivy.xml
[error]   not found: /Users/username/.m2/repository/org/scala-lang/scala-library/2.12.10/scala-library-2.12.10.pom
[error]   unauthorized: https://acme.jfrog.io/acme/sbt-repos/org.scala-lang/scala-library/2.12.10/ivys/ivy.xml (Artifactory Realm)
[error]   unauthorized: https://acme.jfrog.io/acme/sbt-repos/org/scala-lang/scala-library/2.12.10/scala-library-2.12.10.pom (Artifactory Realm)
[error]   unauthorized: https://acme.jfrog.io/acme/maven-remotes/org/scala-lang/scala-library/2.12.10/scala-library-2.12.10.pom (Artifactory Realm)
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? r

```
## expectation

Coursier provides credentials defined for the project or globally at `.sbt/1.0/.credentials` to the repository manager 

## notes
* MacOS, java11, sbt 1.3.12, artifactory
* Pretty sure my debugger tricks me when returing `Not implemented Macro execption` but still `val credentialsTask = Def.task { ... }` won't return any credentials for Coursier
* sbt.librarymanagement.Credentials#register is called with the expected `FileCredentials` for ivy

**Comment by eed3si9n** [comment]
@onmomo Could you add how your credentials are added into the build please? Normally those are added via machine-wide (global) settings.

**Comment by onmomo** [comment]
@eed3si9n thanks for getting back to me, I updated the issue. Let me know if I can provide more information.

**Comment by cchepelov** [comment]
After applying #6278 (sbt release 1.4.7), I'm still having credentials-related issues.

What works for me:
 - creating a plugin in $BOOT/1.0/credentials.sbt, and doing some `credentials += Credentials(r,h,u,p)` or `credentials += Credentials(file_with_one_set_of_credentials)

What doesn't work for me:
  - `SBT_CREDENTIALS` and `sbt.boot.credentials` are picked up by sbt-launcher, but the credentials then read are stuffed within the Ivy credentials cache and then never actually used (beyond perhaps resolving the core of sbt)
  
@onmomo, can you check whether your situation matches mine using sbt 1.4.7 ? 

If yes: I am willing to work on this.

My plans:

Plan A: 
- patch `LMCoursier.allCredentialsTask` (which already "emulates Ivy") in order to heed SBT_CREDENTIALS / sbt.boot.credentials the way sbt-launcher does (in https://github.com/sbt/sbt/blob/0a6e5c311696ae2ae39e3da2ac80f9206a64179d/main/src/main/scala/sbt/coursierint/LMCoursier.scala#L305) 
- modify `IvyCredentials.toDirect` and `IvyCredentials.loadCredentials` to return a `Seq[DirectCredentials]` according to Coursier's credentials file specification https://get-coursier.io/docs/other-credentials in addition to the existing file format. This would be there: https://github.com/sbt/librarymanagement/blob/99641bb5525628fd5a2309b15b2df2248c3bb32f/ivy/src/main/scala/sbt/librarymanagement/ivy/Credentials.scala#L41 
  - question: is sbt.librarymanagement.ivy.IvyCredentials considered part of sbt's public interface? In which case I suspect a deprecation cycle for the single-credentials `toDirect` and `loadCredentials` functions will be required. If not
  
Plan B:
- Modify sbt-launcher to not store the credentials into the Ivy resolver's key set, but into a (new) singleton to be built within launcher-interface. The credentials would _still_ be stored by sbt-launcher into Ivy's CredentialStore.INSTANCE for the initial 
- Modify LMCoursier to pick up the credentials from that new singleton within launcher-interface

Plan C:
- create a _new_ micro-library whose job is solely to deal with realm/host/user/password credentials. The single canonical implementation of reading env vars, reading files, etc. is there and thoroughly tested.  This library might notionally be  `org.scala-sbt % sbt-credentials`.
- every case where credentials are loaded, manipulated in sbt, sbt-librarymanagement *and* sbt-launcher is updated to delegate to that new library in order to maybe perform these operations multiple times due to legacy, but always behave consistently. 
 
Whichever:
- modify sbt-launcher's Update https://github.com/sbt/launcher/blob/09719ff9aa6c14e747dcb7908bb973d77db4e294/launcher-implementation/src/main/scala/xsbt/boot/Update.scala#L66 so that it understands credentials files the same way as Coursier in addition to what it used to (noting that xsbt/boot/Update.scala and IvyCredentiasl from sbt % librarymanagement don't understand the same files)
- optional: support the COURSIER_CREDENTIALS env var and coursier.credentials property in addition to SBT_CREDENTIALS / sbt.boot.credentials  (_ping @alexarchambault : is the COURSIER_CREDENTIALS format foreseen to be sufficiently stable?_) 
- update the documentation with every supported use case of supplying credentials and prove it

I'm willing to tackle this. Thoughts?

**Comment by onmomo** [comment]
@cchepelov @eed3si9n I test with sbt-1.4.7 launcher to resolve a project with sbt-1.4.1 defined from scratch including an internal plugin. It was able to resolve sbt-1.4.1 including the plugin via the internal repository manager. It failed to authorized for all requests once I removed the `~/.sbt/1.0/plugins/global.sbt`
I think the only future proof solution for sbt to deal with internal repository managers is to come up with an end to end test that tries to resolve sbt and the project dependencies solely via a repository manager. I saw it failing so many times the last 6 years because of authorization issues. Using the OS version of Nexus would do the trick. Happy to support here, I might require some pointers how sbt is dealing with e2e tests.

**Comment by cchepelov** [comment]
@onmomo so according to your first paragraph, your situation appears in sync with mine, and improved from your original report.

regarding the rest: I fully agree. Beyond the current unit tests, it seems there is value in having an integration test suite with:

- a private Nexus repo  (+later on, Artifactory and so on)
- a public Nexus repo   (+later on, Artifactory etc.)

- a container-based test suite using the build's artifact, testing all the various use case for authentication. AIUI this should include:
   - boot from 'just the launcher' (ivy resolution): 1st on public repo, then on private repo, using all ways of supplying credentials
   - compilation of a "hello world" project with a plugin and a dependency, (first on a public repo, then on a private repo) x (all the supported ways one can supply credentials) x (using Coursier or Ivy resolution, at least until the latter is dropped)
   - publication of that project onto the private repo, first using sbt's bundled publication, then possibly using https://github.com/arktekk/sbt-aether-deploy 
   
if that works, this suite would probably want to live within https://github.com/sbt/sbt/blob/develop/.github/workflows/ci.yml 
  

@eed3si9n WDYT about my comments above? I'm of a mind to go with Plan C and work on the integration test suite orthogonally

**Comment by eed3si9n** [comment]
Either plan is fine by me but I'll note a few things here:
- sbt launcher is a Scala 2.10 application that is proguarded, and runs its application like sbt in a sandbox ClassLoader, so you may not be able to share objects between them.
- `SBT_CREDENTIALS` and `-Dsbt.boot.credentials` are meant to be sbt launcher feature, and sbt launcher I think is meant to be a separate app from sbt itself. Conscript tried to fully materialize the effort, but it never really took off.

Cousier should be the heir for both sbt launcher and Apache Ivy. If we're putting renewed effort into behind-the-proxy usage of sbt, the ideal we should shoot for is [`~/.sbt/repositories`](https://www.scala-sbt.org/1.x/docs/Proxy-Repositories.html#Proxy+Repositories) support for Cousier.

Then Plan C "create a new micro-library whose job is solely to deal with realm/host/user/password credentials" effectively becomes, Plan D:

- Replace sbt launcher with Coursier CLI.

/cc @alexarchambault

**Comment by scottrice10** [comment]
Similar to the initial post in this thread, I am trying to come up with a company strategy to use an authenticated internal resolver to serve all dependencies fetched by sbt. This includes repos using sbt versions 0.13.6 through latest 1.5.3. The intent is for the internal resolver to be used for bootstrapping sbt, as well as fetching plugins and libraries.

Based on the most recent comments in this thread by @cchepelov and @onmomo, it seems that this may be possible by:
- using the sbt-1.4.7+ launcher for all projects
- adding $BOOT/1.0/credentials.sbt or ~/.sbt/1.0/plugins/global.sbt with creds in all projects using sbt 1.X.X
- adding $BOOT/0.13/credentials.sbt or ~/.sbt/0.13/plugins/global.sbt with creds in all projects using sbt 0.13.X
- adding a `.sbtopts` file in each project with:
```
-Dsbt.repository.config=project/proxy-repositories
-Dsbt.override.build.repos=true
```

Does this seem correct?

What has been attempted so far is:
 - using the sbt-0.13.18 launcher for all projects (that is what's currently on our CI envs, which can be changed)
 - $BOOT/project/credentials.sbt in all projects
 - Setting `SBT_CREDENTIALS` and `-Dsbt.boot.credentials` for all projects
 - running sbt on each project with:
```
-Dsbt.repository.config=project/proxy-repositories
-Dsbt.override.build.repos=true
```

This works for plugins and libs for all projects, and works for bootstrapping sbt on projects using up to sbt 1.13.11. It fails to bootstrap sbt for 1.13.12+.

**Comment by Nestor10** [comment]
This was a life saver. Thanks for the work around was able to add ~/.sbt/1.0/plugins/global.sbt w/ credentials += Credentials(Path.userHome / ".sbt" / ".credentials") and now jfrog and sbt talk. 

Looking to extend this solution to a CI environment, Jenkins. Would the prescribed solution be to include a global.sbt plugin in the docker image?
