### ISSUE TITLE
sbt publishLocal fails when there is a reference to a type 55 class file

### ISSUE THREAD

**Issue by DavidGoodenough** [sbt/sbt#5678]
I have a scalafx program which references a method which is overriden from a Java interface within which the method has a default.  It is javafx.scene.control.TableColumn.getStyeableNode.

At first I had difficulty getting either sbt compile or the metals LSP to see this method (it could see getStyleableParent but not ...Node).  Then I changed to using java-11 and the compiler and LSP could both see the method.

sbt assemble works just fine, as does sbt compile, but when I try sbt publishLocal it produces an enormous stack trace

```scala
[error] java.lang.NullPointerException
[error]         at scala.reflect.internal.Symbols$Symbol.unsafeTypeParamPhase(Symbols.scala:1753)
[error]         at scala.reflect.internal.Symbols$Symbol.unsafeTypeParams(Symbols.scala:1766)
[error]         at scala.reflect.internal.Symbols$TypeSymbol.updateTypeCache(Symbols.scala:3226)
[error]         at scala.reflect.internal.Symbols$TypeSymbol.maybeUpdateTypeCache(Symbols.scala:3215)
[error]         at scala.reflect.internal.Symbols$TypeSymbol.tpe_$times(Symbols.scala:3193)
[error]         at scala.reflect.internal.Symbols$Symbol.typeOfThis(Symbols.scala:2095)
[error]         at scala.reflect.internal.Types$ThisType.underlying(Types.scala:1401)
[error]         at scala.reflect.internal.Types$SimpleTypeProxy.typeSymbolDirect(Types.scala:158)
[error]         at scala.reflect.internal.Types$SimpleTypeProxy.typeSymbolDirect$(Types.scala:158)
[error]         at scala.reflect.internal.Types$SingletonType.typeSymbolDirect(Types.scala:1101)
[error]         at scala.reflect.internal.tpe.TypeMaps$AsSeenFromMap.<init>(TypeMaps.scala:416)
[error]         at scala.reflect.internal.Types$Type.asSeenFrom(Types.scala:697)
[error]         at scala.reflect.internal.Types$Type.computeMemberType(Types.scala:733)
[error]         at scala.reflect.internal.Symbols$MethodSymbol.typeAsMemberOf(Symbols.scala:3052)
[error]         at scala.reflect.internal.Types$Type.memberType(Types.scala:724)
[error]         at scala.reflect.internal.pickling.UnPickler$Scan$LazyTypeRefAndAlias.$anonfun$completeInternal$5(UnPickler.scala:757)
[error]         at scala.reflect.internal.pickling.UnPickler$Scan$LazyTypeRefAndAlias.$anonfun$completeInternal$5$adapted(UnPickler.scala:755)
[error]         at scala.reflect.internal.Symbols$Symbol.filter(Symbols.scala:2002)
[error]         at scala.reflect.internal.Symbols$Symbol.suchThat(Symbols.scala:2019)
[error]         at scala.reflect.internal.pickling.UnPickler$Scan$LazyTypeRefAndAlias.$anonfun$completeInternal$4(UnPickler.scala:755)
[error]         at scala.reflect.internal.SymbolTable.slowButSafeEnteringPhase(SymbolTable.scala:289)
[error]         at scala.reflect.internal.pickling.UnPickler$Scan$LazyTypeRefAndAlias.completeInternal(UnPickler.scala:754)
[error]         at scala.reflect.internal.pickling.UnPickler$Scan$LazyTypeRef.complete(UnPickler.scala:739)
[error]         at scala.reflect.internal.Symbols$Symbol.completeInfo(Symbols.scala:1541)
[error]         at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1513)
[error]         at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1702)
[error]         at scala.reflect.internal.SymbolPairs$Cursor.fillDecls$1(SymbolPairs.scala:159)
[error]         at scala.reflect.internal.SymbolPairs$Cursor.fillDecls$1(SymbolPairs.scala:156)
[error]         at scala.reflect.internal.SymbolPairs$Cursor.fillDecls$1(SymbolPairs.scala:156)
[error]         at scala.reflect.internal.SymbolPairs$Cursor.fillDecls$1(SymbolPairs.scala:156)
[error]         at scala.reflect.internal.SymbolPairs$Cursor.fillDecls$1(SymbolPairs.scala:156)
[error]         at scala.reflect.internal.SymbolPairs$Cursor.fillDecls$1(SymbolPairs.scala:156)
[error]         at scala.reflect.internal.SymbolPairs$Cursor.fillDecls$1(SymbolPairs.scala:156)
[error]         at scala.reflect.internal.SymbolPairs$Cursor.fillDecls$1(SymbolPairs.scala:156)
[error]         at scala.reflect.internal.SymbolPairs$Cursor.fillDecls$1(SymbolPairs.scala:156)
[error]         at scala.reflect.internal.SymbolPairs$Cursor.fillDecls$1(SymbolPairs.scala:156)
[error]         at scala.reflect.internal.SymbolPairs$Cursor.fillDecls$1(SymbolPairs.scala:156)
[error]         at scala.reflect.internal.SymbolPairs$Cursor.fillDecls$1(SymbolPairs.scala:156)
[error]         at scala.reflect.internal.SymbolPairs$Cursor.init(SymbolPairs.scala:167)
[error]         at scala.reflect.internal.SymbolPairs$Cursor.<init>(SymbolPairs.scala:128)
[error]         at scala.tools.nsc.transform.OverridingPairs$Cursor.<init>(OverridingPairs.scala:27)
[error]         at scala.tools.nsc.typechecker.TypeDiagnostics$checkUnused.isImplementation$1(TypeDiagnostics.scala:732)
[error]         at scala.tools.nsc.typechecker.TypeDiagnostics$checkUnused.warnable$1(TypeDiagnostics.scala:744)
[error]         at scala.tools.nsc.typechecker.TypeDiagnostics$checkUnused.$anonfun$run$8(TypeDiagnostics.scala:747)
[error]         at scala.tools.nsc.typechecker.TypeDiagnostics$checkUnused.$anonfun$run$8$adapted(TypeDiagnostics.scala:747)
[error]         at scala.collection.Iterator$$anon$6.hasNext(Iterator.scala:472)
[error]         at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
[error]         at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:920)
[error]         at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:890)
[error]         at scala.tools.nsc.typechecker.TypeDiagnostics$checkUnused.run(TypeDiagnostics.scala:747)
[error]         at scala.tools.nsc.typechecker.TypeDiagnostics$checkUnused.apply(TypeDiagnostics.scala:756)
[error]         at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.apply(Analyzer.scala:123)
[error]         at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:451)
[error]         at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.run(Analyzer.scala:105)
[error]         at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1505)
[error]         at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1489)
[error]         at scala.tools.nsc.Global$Run.compileSources(Global.scala:1481)
[error]         at scala.tools.nsc.Global$Run.compile(Global.scala:1616)
[error]         at scala.tools.nsc.doc.DocFactory.makeUniverse(DocFactory.scala:54)
[error]         at scala.tools.nsc.doc.DocFactory.generate$1(DocFactory.scala:135)
[error]         at scala.tools.nsc.doc.DocFactory.document(DocFactory.scala:142)
[error]         at xsbt.Runner.run(ScaladocInterface.scala:34)
[error]         at xsbt.ScaladocInterface.run(ScaladocInterface.scala:19)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
[error]         at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:177)
[error]         at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:158)
[error]         at sbt.Doc$.$anonfun$scaladoc$1(Doc.scala:39)
[error]         at sbt.Doc$.$anonfun$scaladoc$1$adapted(Doc.scala:39)
[error]         at sbt.RawCompileLike$.$anonfun$prepare$1(RawCompileLike.scala:83)
[error]         at sbt.RawCompileLike$.$anonfun$prepare$1$adapted(RawCompileLike.scala:76)
[error]         at sbt.RawCompileLike$.$anonfun$cached$3(RawCompileLike.scala:67)
[error]         at sbt.RawCompileLike$.$anonfun$cached$3$adapted(RawCompileLike.scala:65)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)
[error]         at sbt.RawCompileLike$.$anonfun$cached$1(RawCompileLike.scala:72)
[error]         at sbt.RawCompileLike$.$anonfun$cached$1$adapted(RawCompileLike.scala:55)
[error]         at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1631)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (Compile / doc) java.lang.NullPointerException
```

This occurs whether I use the java-8 or java-11 runtime.

Given that I have just done a clean sbt compile it is perplexing that publishLocal seems to be trying to compile something.

This does not happen with all publishLocals, but is repeatable with this one.  Unfortunately it involves a very large project.
 I am running sbt 1.3.13 on Debian Linux (sid), with scala 2.13.2 (not all the libraries were available for 2.13.3 last time I checked).

**Comment by eed3si9n** [comment]
Hi. When you report an issue to sbt/sbt, please follow the template and the issue reporting guide (https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md#what-to-report).

Looking at the stack trace, the part that's erroring is Scaladoc. Likely you'd get the same error if you type `doc`.

**Comment by DavidGoodenough** [comment]
Well I am glad to see that you are so eager to fix problems in your code.  As I explained I can not generate a simple step by step way to reproduce this problem, but it is absolutely reproducible in my environment, but I have absolutely no idea how to simplify it. I tried to follow the template, but it made absolutely no sense in this case and in the end I gave up and went for a simple description of what happened.

Is there a way to turn off Scaladoc when doing a publishLocal?

**Comment by DavidGoodenough** [comment]
BTW, turning off doc (which a little googling revealed) does fix it.  Fortunately I only need this project published locally for testing purposes.  But one day someone is going to have to fix it.

**Comment by eed3si9n** [comment]
<img width="539" alt="sbt_publishLocal_fails_when_there_is_a_reference_to_a_type_55_class_file_·_Issue__5678_·_sbt_sbt" src="https://user-images.githubusercontent.com/184683/87231528-e8adea80-c385-11ea-9678-57366346ca63.png">

I'd like to remind you as the maintainer of sbt that all communication in this GitHub repository is covered under Lightbend Community Code of Conduct (https://www.lightbend.com/conduct).

Maybe it was unclear to you, but I tried to tell you that this is likely not an sbt bug and it's Scaladoc's issue instead, and I found your comment to be hostile and against our CoC. I hope you can participate in the open source community with more positive attitude in the future.
