### ISSUE TITLE
Invalid Path exception in Windows when creating new project

### ISSUE THREAD

**Issue by cprieto** [sbt/sbt#5681]
## steps
- OS: Windows 10 build 19041
- sbt version: 1.3.13
- JDK version: OpenJDK 11.0.2 2019-01-15
- JRE version: OpenJDK 18.9 11.0.2+9

In a powershell terminal create a simple hello world project

`sbt new scala/hello-world.g8`

## problem

In Windows, an exception is raised:

```
java.nio.file.InvalidPathException: Illegal char < at index 0:  ____________________________\Coursier\cache\v1
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
        at java.base/java.io.File.toPath(File.java:2290)
        at lmcoursier.internal.shaded.coursier.paths.CoursierPaths.computeCacheDirectory(CoursierPaths.java:68)
        at lmcoursier.internal.shaded.coursier.paths.CoursierPaths.computeCacheDirectory(CoursierPaths.java:37)
        at lmcoursier.internal.shaded.coursier.paths.CoursierPaths.cacheDirectory(CoursierPaths.java:79)
        at lmcoursier.internal.shaded.coursier.paths.CachePath.defaultCacheDirectory(CachePath.java:97)
        at lmcoursier.internal.shaded.coursier.cache.CacheDefaults$.location$lzycompute(CacheDefaults.scala:16)
        at lmcoursier.internal.shaded.coursier.cache.CacheDefaults$.location(CacheDefaults.scala:16)
        at lmcoursier.internal.shaded.coursier.cache.CacheDefaults$.warnLegacyCacheLocation(CacheDefaults.scala:22)
        at lmcoursier.CoursierConfiguration$.checkLegacyCache(CoursierConfiguration.scala:90)
        at sbt.MainLoop$.runLogged(MainLoop.scala:33)
        at sbt.StandardMain$.runManaged(Main.scala:132)
        at sbt.xMain$.run(Main.scala:67)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:45)
        at sbt.xMain.run(Main.scala:39)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:130)
        at xsbt.boot.Launch$.run(Launch.scala:111)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
        at xsbt.boot.Launch$.launch(Launch.scala:119)
        at xsbt.boot.Launch$.apply(Launch.scala:20)
        at xsbt.boot.Boot$.runImpl(Boot.scala:56)
        at xsbt.boot.Boot$.main(Boot.scala:18)
        at xsbt.boot.Boot.main(Boot.scala)
[error] [launcher] error during sbt launcher: java.nio.file.InvalidPathException: Illegal char < at index 0:  ____________________________\Coursier\cache\v1
```

## expectation

The project should be created, no exception should be raised.

## notes

I tried with different templates, the same error happens.

**Comment by eed3si9n** [comment]
@cprieto Thanks for the report!

I wonder if this is related to https://github.com/dirs-dev/directories-jvm/issues/36  or https://github.com/dirs-dev/directories-jvm/issues/37

**Comment by eed3si9n** [comment]
As a workaround I'd suggest setting `COURSIER_CACHE` environment variable to avoid computeCacheDirectory.

**Comment by eed3si9n** [comment]
I am closing this due to inactivity, but if this is still relevant let us know with more details (reproduction steps etc).
