### ISSUE TITLE
[1.4.x] "Bad history file syntax"

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#5682]
## steps

Use locally built 1.4.x on sbt/sbt.

## problem

```
  503 WARNING: Failed to load history
  504 java.lang.IllegalArgumentException: Bad history file syntax! The history file `/Users/eed3si9n/work/sbt-modules/sbt/target/.history` may be an older history: please remove it or use a different history file.
  505         at org.jline.reader.impl.history.DefaultHistory.addHistoryLine(DefaultHistory.java:179)
  506         at org.jline.reader.impl.history.DefaultHistory.addHistoryLine(DefaultHistory.java:169)
  507         at org.jline.reader.impl.history.DefaultHistory.lambda$load$0(DefaultHistory.java:86)
  508         at java.util.Iterator.forEachRemaining(Iterator.java:116)
  509         at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
  510         at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
  511         at org.jline.reader.impl.history.DefaultHistory.load(DefaultHistory.java:86)
  512         at org.jline.reader.impl.history.DefaultHistory.attach(DefaultHistory.java:69)
  513         at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:589)
  514         at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:454)
  515         at sbt.internal.util.LineReader$$anon$2.$anonfun$readLine$3(LineReader.scala:83)
  516         at scala.Option.getOrElse(Option.scala:189)
  517         at sbt.internal.util.LineReader$$anon$2.$anonfun$readLine$1(LineReader.scala:83)
  518         at sbt.internal.util.Terminal$ConsoleTerminal.liftedTree2$1(Terminal.scala:789)
  519         at sbt.internal.util.Terminal$ConsoleTerminal.withRawInput(Terminal.scala:789)
  520         at sbt.internal.util.LineReader$$anon$2.readLine(LineReader.scala:83)
  521         at sbt.internal.ui.UITask$Reader$.impl$2(UITask.scala:55)
```

## expectation

No error.

## notes

Change the history file name for JLine3?

https://github.com/sbt/sbt/blob/8b73d2bc2abcc0fd56647b3d52f73ecd4db2de54/main/src/main/scala/sbt/Defaults.scala#L424

**Comment by eatkins** [comment]
Yeah. I noticed that but punted on addressing it. The two options are rename the file or validate it first and either backup or delete the old file if it isn't valid. The jline3 format is s"${System.currentTimeMillis}:${LINE}" while jline2 is just s"$LINE". I suppose we could also rewrite the history file with a dummy event time as well so that users don't lose their past history when they upgrade as a third option.

**Comment by eed3si9n** [comment]
Potentially the user can go back and forth between 1.4.x and 1.3.x especially during the RC cycle, so I'd suggest we simply rename.
