### ISSUE TITLE
Retry Ivy publishing in case of transient failures

### ISSUE THREAD

**Issue by NicolasRouquette** [sbt/sbt#5698]
With SBT 1.13.11, we experience lots of problems publishing Maven artifacts with stack traces like this:

```
[error] java.io.IOException: Server returned HTTP response code: 503 for URL: https://....
[error] at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error] at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[error] at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error] at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[error] at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1969)
[error] at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1964)
[error] at java.base/java.security.AccessController.doPrivileged(Native Method)
[error] at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1963)
[error] at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1531)
[error] at java.base/sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1507)
[error] at java.base/sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1505)
[error] at java.base/java.security.AccessController.doPrivileged(Native Method)
[error] at java.base/java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:795)
[error] at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1504)
[error] at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
[error] at org.apache.ivy.util.url.BasicURLHandler.upload(BasicURLHandler.java:285)
[error] at org.apache.ivy.util.url.URLHandlerDispatcher.upload(URLHandlerDispatcher.java:82)
[error] at org.apache.ivy.util.FileUtil.copy(FileUtil.java:150)
[error] at org.apache.ivy.plugins.repository.url.URLRepository.put(URLRepository.java:84)
[error] at sbt.internal.librarymanagement.ConvertResolver$LocalIfFileRepo.put(ConvertResolver.scala:368)
[error] at org.apache.ivy.plugins.repository.AbstractRepository.put(AbstractRepository.java:130)
[error] at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put(ConvertResolver.scala:118)
[error] at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put$(ConvertResolver.scala:105)
[error] at sbt.internal.librarymanagement.ConvertResolver$$anonfun$defaultConvert$lzycompute$1$PluginCapableResolver$1.put(ConvertResolver.scala:165)
[error] at org.apache.ivy.plugins.resolver.RepositoryResolver.publish(RepositoryResolver.java:216)
[error] at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5(IvyActions.scala:501)
[error] at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5$adapted(IvyActions.scala:500)
[error] at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:877)
[error] at scala.collection.Iterator.foreach(Iterator.scala:941)[error] at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error] at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)[error] at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] at scala.collection.IterableLike.foreach$(IterableLike.scala:73)[error] at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:876)
[error] at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:500)
```

These errors occur with an Artifactory server. The vendor, JFrog, recommends retrying.

SBT, like Gradle, uses Ivy for publishing Maven artifacts. Recently, Gradle added logic for retrying publishing in case of transient failures, see: https://github.com/gradle/gradle/pull/12024/

It would be great to have a similar functionality available in SBT.

**Comment by eed3si9n** [comment]
@NicolasRouquette Sounds like a good idea.

The relevant code is probably around https://github.com/sbt/librarymanagement/blob/50ca3902c379cf4056ec2a677dfe7fd30c3640cc/ivy/src/main/scala/sbt/internal/librarymanagement/ConvertResolver.scala#L365-L413 or https://github.com/sbt/librarymanagement/blob/develop/ivy/src/main/scala/sbt/internal/librarymanagement/IvyActions.scala if we don't want to directly mess with Ivy. Would you like to try sending a PR for this since it sounds like it would be beneficial to your work?

**Comment by NicolasRouquette** [comment]
@eed3si9n Thanks for the pointer. I'll give a shot at a PR this weekend.

**Comment by zzvara** [comment]
@eed3si9n we have the same problem with JFrog Artifactory.

**Comment by eed3si9n** [comment]
This was contributed by @izharahmd in https://github.com/sbt/librarymanagement/pull/340 and https://github.com/sbt/librarymanagement/pull/341, and will be part of sbt 1.4.0.
