### ISSUE TITLE
sbt cannot build itself when using scala 2.12.12

### ISSUE THREAD

**Issue by eatkins** [sbt/sbt#5705]
## steps

publish a local version sbt based on https://github.com/sbt/sbt/pull/5704
run `sbt -Dsbt.version=1.4.0-SNAPSHOT clean; mainProj/generateContrabands`

## problem

```
sbt:sbtRoot> mainProj/ generateContrabands                                                                                             
[error] stack trace is suppressed; run last mainProj / Compile / generateContrabands for the full output
[error] (mainProj / Compile / generateContrabands) java.lang.BootstrapMethodError: java.lang.NoSuchMethodError: 
[error] Total time: 0 s, completed Jul 27, 2020 10:10:42 AM
sbt:sbtRoot> last mainProj/ generateContrabands                                                                                        
[error] java.lang.BootstrapMethodError: java.lang.NoSuchMethodError:                                                                   
[error]         at org.json4s.MonadicJValue.findDirectByName(MonadicJValue.scala:25)                                                   
[error]         at org.json4s.MonadicJValue.$bslash(MonadicJValue.scala:18)                                                            
[error]         at sbt.contraband.parser.JsonParser$JSONHelper.$minus$greater$times$qmark(JsonParser.scala:26)                         
[error]         at sbt.contraband.parser.JsonParser$JSONHelper.$minus$greater$times(JsonParser.scala:32)                               
[error]         at sbt.contraband.parser.JsonParser$Document$.parse(JsonParser.scala:154)                                              
[error]         at sbt.contraband.parser.JsonParser$Document$.parse(JsonParser.scala:151)                                              
[error]         at sbt.contraband.parser.Parse.parse(JsonParser.scala:124)                                                             
[error]         at sbt.contraband.parser.Parse.parse$(JsonParser.scala:122)                                                            
[error]         at sbt.contraband.parser.JsonParser$Document$.parse(JsonParser.scala:151)                                              
[error]         at sbt.contraband.Generate$.$anonfun$generate$1(ContrabandPlugin.scala:134)                                            
[error]         at scala.collection.immutable.List.map(List.scala:293)                                                                 
[error]         at sbt.contraband.Generate$.generate(ContrabandPlugin.scala:134)                                                       
[error]         at sbt.contraband.Generate$.gen$1(ContrabandPlugin.scala:201)                                                          
[error]         at sbt.contraband.Generate$.$anonfun$apply$1(ContrabandPlugin.scala:209)                                               
[error]         at sbt.util.FileFunction$.$anonfun$cached$1(FileFunction.scala:80)                                                     
[error]         at sbt.util.FileFunction$.$anonfun$cached$4(FileFunction.scala:153)                                                    
[error]         at sbt.util.Difference.apply(Tracked.scala:414)                                                                        
[error]         at sbt.util.Difference.apply(Tracked.scala:394)                                                                        
[error]         at sbt.util.FileFunction$.$anonfun$cached$3(FileFunction.scala:149)                                                    
[error]         at sbt.util.Difference.apply(Tracked.scala:414)                                                                        
[error]         at sbt.util.Difference.apply(Tracked.scala:389)                                                                        
[error]         at sbt.util.FileFunction$.$anonfun$cached$2(FileFunction.scala:148)                                                    
[error]         at sbt.contraband.Generate$.apply(ContrabandPlugin.scala:210)                                                          
[error]         at sbt.contraband.ContrabandPlugin$autoImport$.$anonfun$baseContrabandSettings$19(ContrabandPlugin.scala:76)           
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)                                                              
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)                                          
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)                                                                  
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)                                                                    
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)                                                
[error]         at sbt.Execute.work(Execute.scala:291)                                                                                 
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)                                                                    
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:215)                         
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:59)                                                      
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                            
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)                                             
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                            
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)                                     
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)                                     
[error]         at java.lang.Thread.run(Thread.java:748) 

```

## expectation

That we are able to successfully load all classes.

## notes
My gut feeling is that this is most likely a bug in scala 2.12.12 but I haven't really debugged this at all.

**Comment by eed3si9n** [comment]
Adding 

```scala
scalaVersion := "2.12.12"
```

`project/plugins.sbt` on the current build using sbt 1.3.10 seem to work ok.

**Comment by eed3si9n** [comment]
Current version of Contraband is using json4s 3.4.2 released in 2016. This had a ticking bug because it was built with `-optimize` flag, which inlined some code. This was fixed in 2017, and Contraband can fix this by upgrading to a newer json4s or using scalajson.

Ref https://github.com/json4s/json4s/issues/455 / https://github.com/scala/bug/issues/12100

**Comment by eed3si9n** [comment]
This was fixed in https://github.com/sbt/contraband/pull/150 and https://github.com/sbt/sbt/pull/5743.
