### ISSUE TITLE
scalac option -uniqid causes sbt to lose its mind

### ISSUE THREAD

**Issue by paulp** [sbt/sbt#577]
Another for agatha christie.  Here's a build.sbt:

```
name := "buggo"

organization := "org.improving"

version := "0.0.1-SNAPSHOT"

scalaVersion := "2.10.0-RC1"

scalacOptions += "-uniqid"
```

And src/test/scala/run.scala

```
object Test {
  def main(args: Array[String]): Unit = {
    println("foo")
  }
}
```

And:

```
java.lang.RuntimeException: No main class detected.
  at scala.sys.package$.error(package.scala:27)

% sbt "last test:run"
Detected sbt version 0.12.1
Using /Users/paulp/.sbt/0.12.1 as sbt dir, -sbt-dir to override.
[info] Loading project definition from /Users/paulp/scratch/Oct12-06PM/project
[info] Set current project to buggo (in build file:/Users/paulp/scratch/Oct12-06PM/)
java.lang.RuntimeException: No main class detected.
  at scala.sys.package$.error(package.scala:27)
  at sbt.Defaults$$anonfun$runTask$1$$anonfun$apply$27$$anonfun$13.apply(Defaults.scala:519)
  at sbt.Defaults$$anonfun$runTask$1$$anonfun$apply$27$$anonfun$13.apply(Defaults.scala:519)
  at scala.Option.getOrElse(Option.scala:108)
  at sbt.Defaults$$anonfun$runTask$1$$anonfun$apply$27.apply(Defaults.scala:519)
  at sbt.Defaults$$anonfun$runTask$1$$anonfun$apply$27.apply(Defaults.scala:518)
  at sbt.Scoped$$anonfun$hf5$1.apply(Structure.scala:581)
  at sbt.Scoped$$anonfun$hf5$1.apply(Structure.scala:581)
  at scala.Function1$$anonfun$compose$1.apply(Function1.scala:49)
```

If I take away -uniqid, it runs.  If I give give it -Ydebug instead, it runs.  Whatever is going on, "No main class detected" is a suboptimal error.

**Comment by paulp** [comment]
It looks like it's your use of Symbol#nameString, which you shouldn't be using because it is for printing.  Like here:

```
    def parameterS(s: Symbol): xsbti.api.MethodParameter =
        makeParameter(s.nameString, s.info, s.info.typeSymbol, s)
```

That seems like a likely winner.
