### ISSUE TITLE
Scaladoc doesn't work with 1.4.0-M2

### ISSUE THREAD

**Issue by eatkins** [sbt/sbt#5798]
## steps

In the sbt project, run `sbt mainProj/doc`

## problem

No classes are documented.

## expectation

Scaladocs are generated for project classes.

## notes
Here is the debug output with 1.4.0-M2
```
[info] Main Scala API documentation to /Users/ethanatkins/work/scratch/doc/target/api...
[debug] Getting org.scala-sbt:compiler-bridge_2.12:1.4.0-SNAPSHOT:compile for Scala 2.12.12
[debug] Calling Scaladoc with arguments:
[debug]         -d
[debug]         /Users/ethanatkins/work/scratch/doc/target/api
[debug]         -Xfatal-warnings
[debug]         -bootclasspath
[debug]         /Users/ethanatkins/.sdkman/candidates/java/8.0.252-zulu/zulu-8.jdk/Contents/Home/jre/lib/resources.jar:/Users/ethanatkins/.sdkman/candidates/java/8.0.252-zulu/zulu-8.jdk/Contents/Home/jre/lib/rt.jar:/Users/ethanatkins/.sdkman/candidates/java/8.0.252-zulu/zulu-8.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Users/ethanatkins/.sdkman/candidates/java/8.0.252-zulu/zulu-8.jdk/Contents/Home/jre/lib/jsse.jar:/Users/ethanatkins/.sdkman/candidates/java/8.0.252-zulu/zulu-8.jdk/Contents/Home/jre/lib/jce.jar:/Users/ethanatkins/.sdkman/candidates/java/8.0.252-zulu/zulu-8.jdk/Contents/Home/jre/lib/charsets.jar:/Users/ethanatkins/.sdkman/candidates/java/8.0.252-zulu/zulu-8.jdk/Contents/Home/jre/lib/jfr.jar:/Users/ethanatkins/.sdkman/candidates/java/8.0.252-zulu/zulu-8.jdk/Contents/Home/jre/classes:/Users/ethanatkins/.sbt/boot/scala-2.12.12/lib/scala-library.jar
[debug]         -classpath
[debug]         dummy_dc7e56a1
```
Here it is with 1.3.13:
```
[info] Main Scala API documentation to /Users/ethanatkins/work/scratch/doc/target/api...
[debug] Getting org.scala-sbt:compiler-bridge_2.12:1.3.5:compile for Scala 2.12.10
[debug] Calling Scaladoc with arguments:
[debug]         -Xfatal-warnings
[debug]         -d
[debug]         /Users/ethanatkins/work/scratch/doc/target/api
[debug]         -bootclasspath
[debug]         /Users/ethanatkins/.sdkman/candidates/java/8.0.252-zulu/zulu-8.jdk/Contents/Home/jre/lib/resources.jar:/Users/ethanatkins/.sdkman/candidates/java/8.0.252-zulu/zulu-8.jdk/Contents/Home/jre/lib/rt.jar:/Users/ethanatkins/.sdkman/candidates/java/8.0.252-zulu/zulu-8.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Users/ethanatkins/.sdkman/candidates/java/8.0.252-zulu/zulu-8.jdk/Contents/Home/jre/lib/jsse.jar:/Users/ethanatkins/.sdkman/candidates/java/8.0.252-zulu/zulu-8.jdk/Contents/Home/jre/lib/jce.jar:/Users/ethanatkins/.sdkman/candidates/java/8.0.252-zulu/zulu-8.jdk/Contents/Home/jre/lib/charsets.jar:/Users/ethanatkins/.sdkman/candidates/java/8.0.252-zulu/zulu-8.jdk/Contents/Home/jre/lib/jfr.jar:/Users/ethanatkins/.sdkman/candidates/java/8.0.252-zulu/zulu-8.jdk/Contents/Home/jre/classes:/Users/ethanatkins/.sbt/boot/scala-2.12.10/lib/scala-library.jar
[debug]         -classpath
[debug]         dummy_fdd42bcd
[debug]         /Users/ethanatkins/work/scratch/doc/A.scala
[debug]         /Users/ethanatkins/work/scratch/doc/package.scala
[debug]         /Users/ethanatkins/work/scratch/doc/src/main/java/pkg/J.java
[debug]         /Users/ethanatkins/work/scratch/doc/src/main/java/pkg/K.java
model contains 5 documentable templates
[info] Main Scala API documentation successful.
```

~~So somehow it appears that the sources are not being passed down to zinc.~~ The sources are making their way to zinc so this is actually a zinc and/or sbt integration with zinc bug.

**Comment by eatkins** [comment]
Also, if I publish the latest zinc and rebuild sbt with it, I get the following error in `scripted actions/doc`:
```
[info] [info] Main Scala API documentation to /private/var/folders/zv/2wskcxc14cn6kyj4yb53whc40000gn/T/sbt_82a984d0/target/api...
[info] [error] java.lang.NoSuchMethodException: xsbt.ScaladocInterface.run([Ljava.lang.String;, xsbti.Logger, xsbti.Reporter)
[info] [error]  at java.lang.Class.getMethod(Class.java:1786)
[info] [error]  at sbt.internal.inc.AnalyzingCompiler.invoke(AnalyzingCompiler.scala:314)
[info] [error]  at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:170)
[info] [error]  at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:131)
[info] [error]  at sbt.Doc$.$anonfun$scaladoc$1(Doc.scala:52)
[info] [error]  at sbt.Doc$.$anonfun$scaladoc$1$adapted(Doc.scala:40)
[info] [error]  at sbt.RawCompileLike$.$anonfun$prepare$1(RawCompileLike.scala:79)
[info] [error]  at sbt.RawCompileLike$.$anonfun$prepare$1$adapted(RawCompileLike.scala:72)
[info] [error]  at sbt.RawCompileLike$.$anonfun$cached$4(RawCompileLike.scala:63)
[info] [error]  at sbt.RawCompileLike$.$anonfun$cached$4$adapted(RawCompileLike.scala:61)
[info] [error]  at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[info] [error]  at sbt.RawCompileLike$.$anonfun$cached$1(RawCompileLike.scala:68)
[info] [error]  at sbt.RawCompileLike$.$anonfun$cached$1$adapted(RawCompileLike.scala:52)
[info] [error]  at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1853)
```

I then updated zinc with the following patch:
```patch
diff --git a/internal/compiler-bridge/src/main/scala/xsbt/ScaladocBridge.scala b/internal/compiler-bridge/src/main/scala/xsbt/ScaladocBridge.scala
index 2dee4cc91..fd78028d9 100644
--- a/internal/compiler-bridge/src/main/scala/xsbt/ScaladocBridge.scala
+++ b/internal/compiler-bridge/src/main/scala/xsbt/ScaladocBridge.scala
@@ -30,12 +30,13 @@ private class Runner(
   import scala.tools.nsc.{ doc, Global, reporters }
   import reporters.Reporter
   val docSettings: doc.Settings = new doc.Settings(Log.settingsError(log))
-  val command = new CompilerCommand(args.toList, docSettings)
+  val fullArgs = args.toList ++ sources.map(_.toString)
+  val command = new CompilerCommand(fullArgs, docSettings)
   val reporter = DelegatingReporter(docSettings, delegate)
   def noErrors = !reporter.hasErrors && command.ok
 
   def run(): Unit = {
-    debug(log, "Calling Scaladoc with arguments:\n\t" + args.mkString("\n\t"))
+    debug(log, "Calling Scaladoc with arguments:\n\t" + fullArgs.mkString("\n\t"))
     if (noErrors) {
       import doc._ // 2.8 trunk and Beta1-RC4 have doc.DocFactory.  For other Scala versions, the next line creates forScope.DocFactory
       val processor = new DocFactory(reporter, docSettings)
diff --git a/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/AnalyzingCompiler.scala b/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/AnalyzingCompiler.scala
index f1438d0d8..30ff44b4e 100644
--- a/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/AnalyzingCompiler.scala
+++ b/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/AnalyzingCompiler.scala
@@ -297,7 +297,7 @@ final class AnalyzingCompiler(
 
   // see https://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html
   private def loadService[A](cls: Class[A], log: xLogger): Option[A] = {
-    val sl = ServiceLoader.load(cls, loader(log))
+    val sl = ServiceLoader.load(cls, this.getClass.getClassLoader)
     val it = sl.iterator
     if (it.hasNext) Some(it.next)
     else None
```
After that change, the test found a doc bridge but the actual doc failed with:
```
[info] [debug] Calling Scaladoc with arguments:                                                                                        
[info] [debug]  -d                                                                                                                     
[info] [debug]  /private/var/folders/zv/2wskcxc14cn6kyj4yb53whc40000gn/T/sbt_9121562c/target/api                                       
[info] [debug]  -Xfatal-warnings                                                                                                       
[info] [debug]  -bootclasspath                                                                                                         
[info] [debug]  /Users/ethanatkins/.sdkman/candidates/java/8.0.252-zulu/zulu-8.jdk/Contents/Home/jre/lib/resources.jar:/Users/ethanatkins/.sdkman/candidates/java/8.0.252-zulu/zulu-8.jdk/Contents/Home/jre/lib/rt.jar:/Users/ethanatkins/.sdkman/candidates/java/8.0.252-zulu/z
ulu-8.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Users/ethanatkins/.sdkman/candidates/java/8.0.252-zulu/zulu-8.jdk/Contents/Home/jre/lib/jsse.jar:/Users/ethanatkins/.sdkman/candidates/java/8.0.252-zulu/zulu-8.jdk/Contents/Home/jre/lib/jce.jar:/Users/ethanatkins/.sdkman/can
didates/java/8.0.252-zulu/zulu-8.jdk/Contents/Home/jre/lib/charsets.jar:/Users/ethanatkins/.sdkman/candidates/java/8.0.252-zulu/zulu-8.jdk/Contents/Home/jre/lib/jfr.jar:/Users/ethanatkins/.sdkman/candidates/java/8.0.252-zulu/zulu-8.jdk/Contents/Home/jre/classes:/Users/eth
anatkins/.sbt/scripted/boot/fakeboot/scala-2.12.12/lib/scala-library.jar                                                               
[info] [debug]  -classpath                                                                                                             
[info] [debug]  dummy_b77664b                                                                                                          
[info] [debug]  /private/var/folders/zv/2wskcxc14cn6kyj4yb53whc40000gn/T/sbt_9121562c/A.scala                 
[info] [debug]  /private/var/folders/zv/2wskcxc14cn6kyj4yb53whc40000gn/T/sbt_9121562c/package.scala                                    
[info] [debug]  /private/var/folders/zv/2wskcxc14cn6kyj4yb53whc40000gn/T/sbt_9121562c/src/main/java/pkg/J.java                         
[info] [debug]  /private/var/folders/zv/2wskcxc14cn6kyj4yb53whc40000gn/T/sbt_9121562c/src/main/java/pkg/K.java
[info] [error] scala.MatchError: /private/var/folders/zv/2wskcxc14cn6kyj4yb53whc40000gn/T/sbt_9121562c/A.scala (of class scala.reflect.io.PlainFile)                
[info] [error]  at xsbt.DelegatingReporter$.makePosition$1(DelegatingReporter.scala:92)           
[info] [error]  at xsbt.DelegatingReporter$.convert(DelegatingReporter.scala:150) 
[info] [error]  at xsbt.DelegatingReporter.comment(DelegatingReporter.scala:171)                                                       
[info] [error]  at scala.tools.nsc.Global.signalParsedDocComment(Global.scala:270)                            
[info] [error]  at scala.tools.nsc.ast.parser.ScannersCommon$DocScanner.registerDocComment(Scanners.scala:63)
[info] [error]  at scala.tools.nsc.ast.parser.ScannersCommon$DocScanner.registerDocComment$(Scanners.scala:61)            
[info] [error]  at scala.tools.nsc.ast.parser.Scanners$Scanner.registerDocComment(Scanners.scala:138)                      
[info] [error]  at scala.tools.nsc.doc.ScaladocSyntaxAnalyzer$ScaladocScanner.finishDocComment(ScaladocAnalyzer.scala:124)    
[info] [error]  at scala.tools.nsc.doc.ScaladocSyntaxAnalyzer$ScaladocScanner.finishDocComment$(ScaladocAnalyzer.scala:122)
[info] [error]  at scala.tools.nsc.doc.ScaladocSyntaxAnalyzer$ScaladocUnitScanner.finishDocComment(ScaladocAnalyzer.scala:129)
[info] [error]  at scala.tools.nsc.ast.parser.Scanners$Scanner.skipComment(Scanners.scala:193)
[info] [error]  at scala.tools.nsc.ast.parser.Scanners$Scanner.fetchToken(Scanners.scala:494)
[info] [error]  at scala.tools.nsc.ast.parser.Scanners$Scanner.nextToken(Scanners.scala:348)
[info] [error]  at scala.tools.nsc.ast.parser.Parsers$Parser.accept(Parsers.scala:637)          
[info] [error]  at scala.tools.nsc.ast.parser.Parsers$Parser.templateBody(Parsers.scala:72) 
[info] [error]  at scala.tools.nsc.ast.parser.Parsers$Parser.templateBodyOpt(Parsers.scala:3061)
[info] [error]  at scala.tools.nsc.ast.parser.Parsers$Parser.templateOpt(Parsers.scala:3025)
[info] [error]  at scala.tools.nsc.ast.parser.Parsers$Parser.objectDef(Parsers.scala:2906)      
[info] [error]  at scala.tools.nsc.ast.parser.Parsers$Parser.tmplDef(Parsers.scala:2849)                                  
[info] [error]  at scala.tools.nsc.ast.parser.Parsers$Parser.topLevelTmplDef(Parsers.scala:2830)                        
[info] [error]  at scala.tools.nsc.ast.parser.Parsers$Parser$$anonfun$topStat$1.$anonfun$applyOrElse$1(Parsers.scala:3117)
[info] [error]  at scala.tools.nsc.doc.ScaladocSyntaxAnalyzer$ScaladocUnitParser.joinComment(ScaladocAnalyzer.scala:200)
[info] [error]  at scala.tools.nsc.ast.parser.Parsers$Parser$$anonfun$topStat$1.applyOrElse(Parsers.scala:3117)
[info] [error]  at scala.tools.nsc.ast.parser.Parsers$Parser.statSeq(Parsers.scala:3094)   
[info] [error]  at scala.tools.nsc.ast.parser.Parsers$Parser.topStatSeq(Parsers.scala:3109)                
[info] [error]  at scala.tools.nsc.ast.parser.Parsers$Parser.topstats$1(Parsers.scala:3308)                
[info] [error]  at scala.tools.nsc.ast.parser.Parsers$Parser.$anonfun$compilationUnit$1(Parsers.scala:3314)
[info] [error]  at scala.tools.nsc.ast.parser.Parsers$Parser.checkNoEscapingPlaceholders(Parsers.scala:505)        
[info] [error]  at scala.tools.nsc.ast.parser.Parsers$Parser.compilationUnit(Parsers.scala:3276)
[info] [error]  at scala.tools.nsc.ast.parser.Parsers$SourceFileParser.$anonfun$parseStartRule$1(Parsers.scala:169)
[info] [error]  at scala.tools.nsc.ast.parser.Parsers$Parser.$anonfun$parse$1(Parsers.scala:375)
[info] [error]  at scala.tools.nsc.ast.parser.Parsers$Parser.parseRule(Parsers.scala:368)                
[info] [error]  at scala.tools.nsc.ast.parser.Parsers$Parser.parse(Parsers.scala:375)         
[info] [error]  at scala.tools.nsc.ast.parser.Parsers$UnitParser.$anonfun$smartParse$1(Parsers.scala:265)                              
[info] [error]  at scala.tools.nsc.ast.parser.Parsers$UnitParser.smartParse(Parsers.scala:240)                                          
[info] [error]  at scala.tools.nsc.ast.parser.SyntaxAnalyzer.scala$tools$nsc$ast$parser$SyntaxAnalyzer$$initialUnitBody(SyntaxAnalyzer.scala:94)                    
[info] [error]  at scala.tools.nsc.ast.parser.SyntaxAnalyzer$ParserPhase.apply(SyntaxAnalyzer.scala:106)
[info] [error]  at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:454)
[info] [error]  at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:402)          
[info] [error]  at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1511)
[info] [error]  at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1495)  
[info] [error]  at scala.tools.nsc.Global$Run.compileSources(Global.scala:1488)
[info] [error]  at scala.tools.nsc.Global$Run.compile(Global.scala:1614)           
[info] [error]  at scala.tools.nsc.doc.DocFactory.makeUniverse(DocFactory.scala:51)
[info] [error]  at scala.tools.nsc.doc.DocFactory.generate$1(DocFactory.scala:131)
[info] [error]  at scala.tools.nsc.doc.DocFactory.document(DocFactory.scala:138)                                                        
[info] [error]  at xsbt.Runner.run(ScaladocInterface.scala:41)                                                                         
[info] [error]  at xsbt.ScaladocInterface.run(ScaladocInterface.scala:20)
```

**Comment by eatkins** [comment]
I can reproduce the same match error if I apply a different patch in AnalyzingCompiler.scala:
```patch
diff --git a/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/AnalyzingCompiler.scala b/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/AnalyzingCompiler.scala
index f1438d0d8..d98157726 100644
--- a/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/AnalyzingCompiler.scala
+++ b/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/AnalyzingCompiler.scala
@@ -164,10 +164,11 @@ final class AnalyzingCompiler(
               compArgs.makeArguments(fileSources, cp, Some(outputDirectory), options)
             onArgsHandler(arguments)
             invoke(bridge, bridgeClass, "run", log)(
+              classOf[Array[VirtualFile]],
               classOf[Array[String]],
               classOf[xLogger],
               classOf[Reporter]
-            )(arguments.toArray[String], log, reporter)
+            )(sources.toArray, arguments.toArray[String], log, reporter)
         }
     }
     ()
```

**Comment by eed3si9n** [comment]
Looks like `mainProj/doc` works with 1.4.0-RC1 :)

**Comment by eatkins** [comment]
Great. I updated https://github.com/sbt/sbt/pull/5799 which should serve as a regression test that ensures that docs are generated for the project classes.
