### ISSUE TITLE
NPE in RegexMatcher when called from SBT

### ISSUE THREAD

**Issue by vpatryshev** [sbt/sbt#5813]
## steps

clone [https://github.com/geek94/Akka-Https][1]), do `sbt run`

## problem

NPE in sbt

## expectation

no NPE in sbt

## notes

I have SBT ver 1.3.13, and java openjdk version "11.0.8" 2020-07-14
Running my project (`sbt run` in [https://github.com/geek94/Akka-Https][1]) I get an NPE, namely:
```
Vlad4087688721:Akka-Https vpatryshev$ sbt run
[info] Loading project definition from /Users/vpatryshev/projects/Akka-Https/project
java.lang.NullPointerException
	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1769)
	at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
	at java.base/java.util.regex.Matcher.<init>(Matcher.java:253)
	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1130)
	at java.base/java.util.regex.Pattern.split(Pattern.java:1249)
	at java.base/java.util.regex.Pattern.split(Pattern.java:1322)
	at sbt.IO$.pathSplit(IO.scala:744)
	at sbt.IO$.parseClasspath(IO.scala:859)
	at sbt.compiler.CompilerArguments.extClasspath(CompilerArguments.scala:62)
	at sbt.compiler.MixedAnalyzingCompiler$.withBootclasspath(MixedAnalyzingCompiler.scala:189)
	at sbt.compiler.MixedAnalyzingCompiler$.searchClasspathAndLookup(MixedAnalyzingCompiler.scala:167)
	at sbt.compiler.MixedAnalyzingCompiler$.apply(MixedAnalyzingCompiler.scala:177)
	at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
	at sbt.Compiler$.compile(Compiler.scala:128)
	at sbt.Compiler$.compile(Compiler.scala:114)
	at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:814)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:805)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:803)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
[error] (compile:compileIncremental) java.lang.NullPointerException

**Comment by eed3si9n** [comment]
`project/build.properties` says 0.13.18. If you upgrade it to 1.3.13 and bump the plugins to the latest it should run.

**Comment by vpatryshev** [comment]
Thank you Eugene! Really impressed.
