### ISSUE TITLE
1.4.0-RC1: TaskProgress: RejectedExecutionException

### ISSUE THREAD

**Issue by jtjeferreira** [sbt/sbt#5825]
## steps

In a play 2.7 project with `PlayImport.PlayKeys.playInteractionMode := play.sbt.StaticPlayNonBlockingInteractionMode` when running `run` and making a request I got:

```
> run
Starting server

--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
[info] p.c.s.AkkaHttpServer - Listening for HTTPS on /0:0:0:0:0:0:0:0:9443
[success] Total time: 12 s, completed Sep 8, 2020, 7:50:27 PM
[error] a.a.OneForOneStrategy - Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2f3f1ea5[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@813863d[Wrapped task = sbt.internal.TaskProgress$$Lambda$2473/0x0000000840c81840@23a0e9a9]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@78538804[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 49655]
akka.actor.ActorInitializationException: akka://play-dev-mode/system/StreamSupervisor-0/flow-2-1: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:202)
	at akka.actor.ActorCell.create(ActorCell.scala:696)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:547)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:569)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:293)
	at akka.dispatch.Mailbox.run(Mailbox.scala:228)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2f3f1ea5[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@813863d[Wrapped task = sbt.internal.TaskProgress$$Lambda$2473/0x0000000840c81840@23a0e9a9]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@78538804[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 49655]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(ScheduledThreadPoolExecutor.java:632)
	at java.base/java.util.concurrent.Executors$DelegatedScheduledExecutorService.scheduleAtFixedRate(Executors.java:785)
	at sbt.internal.TaskProgress.schedule(TaskProgress.scala:45)
	at sbt.internal.TaskProgress.afterReady(TaskProgress.scala:90)
	at sbt.internal.TaskProgress.afterReady(TaskProgress.scala:23)
	at sbt.EvaluateTask$$anon$1.afterReady(EvaluateTask.scala:240)
	at sbt.EvaluateTask$$anon$1.afterReady(EvaluateTask.scala:231)
> 

```

## problem

Can't run the application

## expectation

No exception in logs, and a running application...

## notes

If `playInteractionMode` is `PlayConsoleInteractionMode` then everything works.

AFAICT, this is the usage of that key in the play plugin https://github.com/playframework/playframework/blob/2.7.x/dev-mode/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala#L72

If the description and the stack traces are not enough, I can work on a smaller reproducer...

**Comment by eatkins** [comment]
A repro project would be helpful. This task is violating an assumption about task evaluation that TaskProgress is relying on.

**Comment by jtjeferreira** [comment]
> A repro project would be helpful. This task is violating an assumption about task evaluation that TaskProgress is relying on.

OK. Was hoping the stacktrace would ring some bell...

**Comment by eatkins** [comment]
I see where the exception is thrown but it doesn't help me figure out why my assumption is violated.

**Comment by jtjeferreira** [comment]
Reproducer in https://github.com/jtjeferreira/sbt-5825-play-seed, but the error is a bit different as you can see in the README. However when calling `playStop` we can see again a reference to `sbt.internal.TaskProgress` :thinking: 

I will keep looking to reproduce the exact stack trace as above...

**Comment by eatkins** [comment]
Ok. Thanks. I'll take a look soon.

**Comment by jtjeferreira** [comment]
I was trying to add a few more plugins to the project to reproduce the initial exception, but no luck...

**Comment by jtjeferreira** [comment]
@eatkins is this fixed then?

**Comment by eed3si9n** [comment]
Looks like it - https://github.com/sbt/sbt/pull/5840#issuecomment-691237828
