### ISSUE TITLE
Play run doesn't work with sbt 1.4.x

### ISSUE THREAD

**Issue by eatkins** [sbt/sbt#5841]
## steps

* clone https://github.com/jtjeferreira/sbt-5825-play-seed
* `sbt -Dsbt.version=1.4.0-SNAPSHOT`
* `> run`
* open localhost:9000 in a web browser

## problem
Nothing is rendered in the browser and the following error is printed
```
[sbt-5825-play-seed] $ run
Starting server

--- (Running the application, auto-reloading is enabled) ---
[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
[success] Total time: 2 s, completed Sep 11, 2020 10:58:36 AM
[error] a.a.ActorSystemImpl - Internal server error, sending 500 response
akka.http.impl.util.One2OneBidiFlow$OutputTruncationException: Inner flow was completed without producing result elements for 1 outstanding elements
        at akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$.apply(One2OneBidiFlow.scala:22)
        at akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$.apply(One2OneBidiFlow.scala:22)
        at akka.http.impl.util.One2OneBidiFlow$One2OneBidi$$anon$1$$anon$4.onUpstreamFinish(One2OneBidiFlow.scala:97)
        at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:523)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625)
        at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:502)
        at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:769)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:784)
```
## expectation

The default play landing page rendered

## notes

Initially reported as #5825

**Comment by eatkins** [comment]
There isn't really a whole lot to go on here from a debugging perspective. cc @dwijnand @jtjeferreira

**Comment by eatkins** [comment]
Nevermind. I just missed something in #5840.

**Comment by ericdotdata** [comment]
For other searchers, "~run" works in intellij to keep the server active
