### ISSUE TITLE
addPluginSbtFile breaks project referencing external RootProject

### ISSUE THREAD

**Issue by jastice** [sbt/sbt#5850]
## steps

1. Create a project that references an external `RootProject`:

```scala
name := "intellij-scala-plugin-bug"
version := "0.1"
scalaVersion := "2.13.3"

Global / scalaVersion := "2.13.3"

lazy val externalProject = RootProject(
  build = uri(s"ssh://git@github.com/fpopic/github-repo-hosting-protobuf.git")
)

lazy val root = (project in file("."))
  .dependsOn(externalProject)
```

2. start sbt with `addPluginSbtFile` (sbt file can be empty)

```
> sbt --addPluginSbtFile=/path/to/file.sbt
```

## problem

Loading the build fails with `java.net.URISyntaxException`

```
> sbt --addPluginSbtFile=/Users/jast/playspace/scl-18124/inject/nothing.sbt
[info] welcome to sbt 1.4.0-RC1 (Oracle Corporation Java 1.8.0_101)
[info] loading global plugins from /Users/jast/.sbt/1.0/plugins
[info] loading settings for project scl-18124-build from nothing.sbt ...
[info] loading project definition from /Users/jast/playspace/SCL-18124/project
[error] 
[error] Use 'last' for the full log.
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
```

## notes

reproduced under sbt 1.3.13 and 1.4.0-RC1

via https://youtrack.jetbrains.com/issue/SCL-18124

**Comment by eed3si9n** [comment]
@jastice Thanks for the report. Could you include the stack trace `l` prints out please?

**Comment by jastice** [comment]
Sure, full stacktrace:

```
[17:22:59] jast@koios /Users/jast/playspace/scl-18124 (1)
> sbt --addPluginSbtFile=/Users/jast/playspace/scl-18124/inject/nothing.sbt
[info] welcome to sbt 1.4.0-RC1 (Oracle Corporation Java 1.8.0_101)
[info] loading global plugins from /Users/jast/.sbt/1.0/plugins
[info] loading settings for project scl-18124-build from nothing.sbt ...
[info] loading project definition from /Users/jast/playspace/SCL-18124/project
[error] java.net.URISyntaxException: Illegal character in scheme name at index 3: git@github.com:build-server-protocol/build-server-protocol.git
[error] Use 'last' for the full log.
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
[debug] > Exec(early(addDefaultCommands), None, None)
[debug] > Exec(addDefaultCommands, None, None)
[debug] > Exec(early(initialize), None, None)
[debug] > Exec(initialize, None, None)
[debug] > Exec(--addPluginSbtFile=/Users/jast/playspace/scl-18124/inject/nothing.sbt, None, None)
[debug] > Exec(addPluginSbtFile=/Users/jast/playspace/scl-18124/inject/nothing.sbt, None, None)
[debug] > Exec(boot, None, None)
[debug] > Exec(writeSbtVersion, None, None)
[debug] > Exec(reload, None, None)
[debug] > Exec(sbtStashOnFailure, None, None)
[debug] > Exec(onFailure loadFailed, None, None)
[debug] > Exec(loadp, None, None)
[info] welcome to sbt 1.4.0-RC1 (Oracle Corporation Java 1.8.0_101)
[debug]       Load.loadUnit: plugins took 62.558529ms
[debug]       Load.loadUnit: defsScala took 0.310545ms
[debug] [Loading] Scanning directory /Users/jast/.sbt/1.0/plugins
[debug] [Loading] Found non-root projects
[debug] [Loading] Done in /Users/jast/.sbt/1.0/plugins, returning: ()
[debug] deducing auto plugins based on known facts Set(Atom(sbt.plugins.CorePlugin)) and clauses Clauses(List(Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.IvyPlugin))), Clause(Atom(sbt.ScriptedPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.SbtPlugin),Set(Atom(sbt.ScriptedPlugin))), Clause(Atom(sbt.plugins.SemanticdbPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.JUnitXmlReportPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.CorePlugin),Set(Atom(sbt.plugins.IvyPlugin))), Clause(Atom(sbt.plugins.IvyPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.SemanticdbPlugin))), Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.JUnitXmlReportPlugin))), Clause(Atom(sbt.plugins.CorePlugin),Set(Atom(sbt.plugins.Giter8TemplatePlugin)))))
[debug]   :: deduced result: Matched(sbt.plugins.CorePlugin,sbt.plugins.Giter8TemplatePlugin,sbt.plugins.IvyPlugin,sbt.plugins.JvmPlugin,sbt.plugins.JUnitXmlReportPlugin,sbt.plugins.SemanticdbPlugin)
[debug] Plugins.deducer#function took 17.491923 ms
[debug]           Load.resolveProject(global-plugins) took 7.868235ms
[debug]         Load.loadTransitive: finalizeProject(Project(id global-plugins, base: /Users/jast/.sbt/1.0/plugins, plugins: List(<none>))) took 50.365791ms
[debug] [Loading] Done in /Users/jast/.sbt/1.0/plugins, returning: (global-plugins)
[debug]       Load.loadUnit: loadedProjectsRaw took 66.997303ms
[debug]       Load.loadUnit: cleanEvalClasses took 0.340571ms
[debug]     Load.loadUnit(file:/Users/jast/.sbt/1.0/plugins/, ...) took 136.195739ms
[debug]   Load.apply: load took 498.648857ms
[debug]   Load.apply: resolveProjects took 5.155207ms
[debug]   Load.apply: finalTransforms took 41.382948ms
[debug]   Load.apply: config.delegates took 5.844468ms
[debug]   Load.apply: Def.make(settings)... took 247.503834ms
[debug]   Load.apply: structureIndex took 66.678028ms
[debug]   Load.apply: mkStreams took 1.261095ms
[info] loading global plugins from /Users/jast/.sbt/1.0/plugins
[debug] Running task... Cancel: Signal, check cycles: false, forcegc: true
[debug] Load.defaultLoad until apply took 1871.776381ms
[debug]           Load.loadUnit: plugins took 14.435406ms
[debug]           Load.loadUnit: defsScala took 0.002861ms
[debug] [Loading] Scanning directory /Users/jast/playspace/SCL-18124/project
[debug]             Load.loadUnit: mkEval took 0.186856ms
[debug] [Loading] Found non-root projects
[debug] [Loading] Done in /Users/jast/playspace/SCL-18124/project, returning: ()
[debug] deducing auto plugins based on known facts Set(Atom(sbt.plugins.CorePlugin)) and clauses Clauses(List(Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.IvyPlugin))), Clause(Atom(sbt.ScriptedPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.SbtPlugin),Set(Atom(sbt.ScriptedPlugin))), Clause(Atom(sbt.plugins.SemanticdbPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.JUnitXmlReportPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.CorePlugin),Set(Atom(sbt.plugins.IvyPlugin))), Clause(Atom(sbt.plugins.IvyPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.SemanticdbPlugin))), Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.JUnitXmlReportPlugin))), Clause(Atom(sbt.plugins.CorePlugin),Set(Atom(sbt.plugins.Giter8TemplatePlugin)))))
[debug]   :: deduced result: Matched(sbt.plugins.CorePlugin,sbt.plugins.Giter8TemplatePlugin,sbt.plugins.IvyPlugin,sbt.plugins.JvmPlugin,sbt.plugins.JUnitXmlReportPlugin,sbt.plugins.SemanticdbPlugin)
[debug] Plugins.deducer#function took 1.621448 ms
[info] loading settings for project scl-18124-build from nothing.sbt ...
[debug]               Load.resolveProject(scl-18124-build) took 27.47948ms
[debug]             Load.loadTransitive: finalizeProject(Project(id scl-18124-build, base: /Users/jast/playspace/SCL-18124/project, plugins: List(<none>))) took 29.549958ms
[debug] [Loading] Done in /Users/jast/playspace/SCL-18124/project, returning: (scl-18124-build)
[debug]           Load.loadUnit: loadedProjectsRaw took 56.7049ms
[debug]           Load.loadUnit: cleanEvalClasses took 0.020899ms
[debug]         Load.loadUnit(file:/Users/jast/playspace/SCL-18124/project/, ...) took 71.708675ms
[debug]       Load.apply: load took 72.458177ms
[debug]       Load.apply: resolveProjects took 0.052142ms
[debug]       Load.apply: finalTransforms took 7.670452ms
[debug]       Load.apply: config.delegates took 0.378117ms
[debug]       Load.apply: Def.make(settings)... took 48.796695ms
[debug]       Load.apply: structureIndex took 19.212928ms
[debug]       Load.apply: mkStreams took 0.002478ms
[info] loading project definition from /Users/jast/playspace/SCL-18124/project
[debug] Running task... Cancel: Signal, check cycles: false, forcegc: true
[debug]     Load.loadUnit: plugins took 302.703079ms
[debug]     Load.loadUnit: defsScala took 0.00195ms
[debug] [Loading] Scanning directory /Users/jast/playspace/SCL-18124
[debug]       Load.loadUnit: mkEval took 0.303837ms
[error] java.net.URISyntaxException: Illegal character in scheme name at index 3: git@github.com:build-server-protocol/build-server-protocol.git
[error] 	at java.net.URI$Parser.fail(URI.java:2848)
[error] 	at java.net.URI$Parser.checkChars(URI.java:3021)
[error] 	at java.net.URI$Parser.parse(URI.java:3048)
[error] 	at java.net.URI.<init>(URI.java:588)
[error] 	at sbt.package$.uri(package.scala:32)
[error] 	at $f1609a8715f0316df356$.externalProject$lzycompute(build.sbt:9)
[error] 	at $f1609a8715f0316df356$.externalProject(build.sbt:7)
[error] 	at $f1609a8715f0316df356$.root$lzycompute(build.sbt:13)
[error] 	at $f1609a8715f0316df356$.root(build.sbt:12)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.compiler.EvalDefinitions.$anonfun$values$1(Eval.scala:59)
[error] 	at scala.collection.immutable.List.map(List.scala:293)
[error] 	at sbt.compiler.EvalDefinitions.values(Eval.scala:59)
[error] 	at sbt.internal.DefinedSbtValues.$anonfun$values$1(LoadedSbtFile.scala:50)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:366)
[error] 	at sbt.internal.DefinedSbtValues.values(LoadedSbtFile.scala:50)
[error] 	at sbt.internal.EvaluateConfigurations$.$anonfun$evaluateSbtFile$4(EvaluateConfigurations.scala:165)
[error] 	at sbt.internal.Load$.loadSettingsFile$1(Load.scala:1107)
[error] 	at sbt.internal.Load$.$anonfun$discoverProjects$2(Load.scala:1116)
[error] 	at scala.collection.MapLike.getOrElse(MapLike.scala:131)
[error] 	at scala.collection.MapLike.getOrElse$(MapLike.scala:129)
[error] 	at scala.collection.AbstractMap.getOrElse(Map.scala:65)
[error] 	at sbt.internal.Load$.memoLoadSettingsFile$1(Load.scala:1115)
[error] 	at sbt.internal.Load$.$anonfun$discoverProjects$4(Load.scala:1123)
[error] 	at scala.collection.immutable.List.map(List.scala:293)
[error] 	at sbt.internal.Load$.loadFiles$1(Load.scala:1123)
[error] 	at sbt.internal.Load$.discoverProjects(Load.scala:1137)
[error] 	at sbt.internal.Load$.discover$1(Load.scala:889)
[error] 	at sbt.internal.Load$.loadTransitive(Load.scala:943)
[error] 	at sbt.internal.Load$.loadProjects$1(Load.scala:726)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$11(Load.scala:729)
[error] 	at sbt.internal.Load$.timed(Load.scala:1382)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:729)
[error] 	at sbt.internal.Load$.timed(Load.scala:1382)
[error] 	at sbt.internal.Load$.loadUnit(Load.scala:688)
[error] 	at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:486)
[error] 	at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:180)
[error] 	at sbt.internal.BuildLoader.apply(BuildLoader.scala:245)
[error] 	at sbt.internal.Load$.loadURI$1(Load.scala:548)
[error] 	at sbt.internal.Load$.loadAll(Load.scala:564)
[error] 	at sbt.internal.Load$.loadURI(Load.scala:494)
[error] 	at sbt.internal.Load$.load(Load.scala:473)
[error] 	at sbt.internal.Load$.$anonfun$apply$1(Load.scala:242)
[error] 	at sbt.internal.Load$.timed(Load.scala:1382)
[error] 	at sbt.internal.Load$.apply(Load.scala:242)
[error] 	at sbt.internal.Load$.defaultLoad(Load.scala:55)
[error] 	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:923)
[error] 	at sbt.BuiltinCommands$.doLoadProject(Main.scala:923)
[error] 	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:876)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:150)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:145)
[error] 	at sbt.Command$.process(Command.scala:189)
[error] 	at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:245)
[error] 	at scala.Option.getOrElse(Option.scala:189)
[error] 	at sbt.MainLoop$.process$1(MainLoop.scala:245)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:271)
[error] 	at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:162)
[error] 	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:286)
[error] 	at sbt.State$StateOpsImpl$.process$extension(State.scala:322)
[error] 	at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:162)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:162)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:143)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:118)
[error] 	at sbt.io.Using.apply(Using.scala:27)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:111)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:65)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:50)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:41)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:187)
[error] 	at sbt.xMain$.$anonfun$run$5(Main.scala:99)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error] 	at scala.Console$.withIn(Console.scala:230)
[error] 	at sbt.internal.util.Terminal$.withIn(Terminal.scala:528)
[error] 	at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:333)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error] 	at scala.Console$.withOut(Console.scala:167)
[error] 	at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:518)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error] 	at scala.Console$.withErr(Console.scala:196)
[error] 	at sbt.internal.util.Terminal$.withOut(Terminal.scala:518)
[error] 	at sbt.internal.util.Terminal$.withStreams(Terminal.scala:333)
[error] 	at sbt.xMain$.run(Main.scala:82)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:83)
[error] 	at sbt.xMain.run(Main.scala:47)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:130)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:111)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:119)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:20)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:18)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] java.net.URISyntaxException: Illegal character in scheme name at index 3: git@github.com:build-server-protocol/build-server-protocol.git
[error] Use 'last' for the full log.
[debug] > Exec(loadFailed, None, None)
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
```

**Comment by eed3si9n** [comment]
Maybe during loading something is rewriting the URI somehow.

```scala
scala> val u = sbt.uri(s"ssh://git@github.com/fpopic/github-repo-hosting-protobuf.git")
u: sbt.URI = ssh://git@github.com/fpopic/github-repo-hosting-protobuf.git

scala> sbt.io.IO.directoryURI(u)
res0: java.net.URI = ssh://git@github.com/fpopic/github-repo-hosting-protobuf.git
```

`IO.directoryURI(...)` seems to be ok.

**Comment by jobegrabber** [comment]
> Maybe during loading something is rewriting the URI somehow.
> 
> ```scala
> scala> val u = sbt.uri(s"ssh://git@github.com/fpopic/github-repo-hosting-protobuf.git")
> u: sbt.URI = ssh://git@github.com/fpopic/github-repo-hosting-protobuf.git
> 
> scala> sbt.io.IO.directoryURI(u)
> res0: java.net.URI = ssh://git@github.com/fpopic/github-repo-hosting-protobuf.git
> ```
> 
> `IO.directoryURI(...)` seems to be ok.

Coming back to this, as I keep running into this issue. 😞 
The trigger seems to be that the git dependency doesn't contain a `project` directory.

When starting sbt with `--addPluginSbtFile`, the build takes a different branch in [this line](https://github.com/sbt/sbt/blob/v1.7.1/main/src/main/scala/sbt/internal/Load.scala#L1231):
```scala
    if (hasDefinition(dir) || extraSbtFiles.nonEmpty)
      buildPlugins(dir, s, enableSbtPlugin(activateGlobalPlugin(config)))
    else
      noPlugins(dir, config)
```

Without `--addPluginSbtFile`, `noPlugins` is called, as the `project` dir (= `dir`) doesn't exist in the git repo.
However, with that command-line argument provided, `buildPlugins` is called and the build fails (I couldn't find the exact place where that happens, though).

As a workaround I did try to manually add an (empty) `project` directory to the checked-out git repository in the staging space - and that seemed to do the trick.

So I guess the solution is to either make `buildPlugins` work when there's no `project` directory, or preemptively create that directory after a git checkout.

I have no deeper insights into sbt apart from the bits of debugging I did for this issue, so @eed3si9n could you tell me if my findings "make sense" and which approach to fix the issue seems most reasonable? 🙂

**Comment by jonathan-neufeld-asurion** [comment]
Is there a work-around for this?  Creating an empty project folder doesn't work for me.  It just makes SBT think the _entire_ project is empty.  I am presently blocked from running _any_ SBT tasks from within IntelliJ unless I completely delete the sub-folder so that SBT doesn't try to scan it (not even much of a work-around, let alone a solution).  What's more strange is that there are other sub-folders similar to the trouble-one but SBT doesn't have a problem with them.  Why SBT is specifically looking for a "project" in this trouble sub-folder (and not others) is a mystery to me.
