### ISSUE TITLE
sbt 1.4.0-RC1 can't resolve paths with spaces on Windows

### ISSUE THREAD

**Issue by 0paIescent** [sbt/sbt#5868]
## steps
test-lib:
```
name := "test-lib"
organization := "com.sioonhho"
scalaVersion := "2.12.12"
```

test-proj:
```
name := "test-proj"
scalaVersion := "2.12.12"
libraryDependencies += "com.sioonhho" %% "test-lib" % "1.0"
```

## problem
On 1.2.8 the dependency is resolved, on 1.4.0-RC1 it isn't.
```
sbt:test-proj> sbtVersion
[info] 1.2.8
sbt:test-proj> update
[info] Updating ...
[info] Done updating.
[success] Total time: 1 s, completed Sep 18, 2020, 10:22:40 PM
sbt:test-proj>

---

sbt:test-proj> sbtVersion
[info] 1.4.0-RC1
sbt:test-proj> update
[warn]
[warn]  Note: Unresolved dependencies path:
[error] stack trace is suppressed; run last update for the full output
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.sioonhho:test-lib_2.12:1.0
[error]   Not found
[error]   Not found
[error]   not found: C:\Users\Andrew%20DeFilippo\.ivy2\local\com.sioonhho\test-lib_2.12\1.0\ivys\ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/sioonhho/test-lib_2.12/1.0/test-lib_2.12-1.0.pom
[error] Total time: 1 s, completed Sep 18, 2020, 10:24:57 PM
sbt:test-proj> last update
[debug] not up to date. inChanged = true, force = true
[debug] Updating ...
[warn]
[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.sioonhho:test-lib_2.12:1.0
[error]   Not found
[error]   Not found
[error]   not found: C:\Users\Andrew%20DeFilippo\.ivy2\local\com.sioonhho\test-lib_2.12\1.0\ivys\ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/sioonhho/test-lib_2.12/1.0/test-lib_2.12-1.0.pom
[error]         at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:258)
[error]         at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:227)
[error]         at lmcoursier.CoursierDependencyResolution$$Lambda$3739/0000000000000000.apply(Unknown Source)
[error]         at scala.util.Either$LeftProjection.map(Either.scala:573)
[error]         at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:227)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:53)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:103)
[error]         at sbt.internal.LibraryManagement$$$Lambda$2717/0000000000000000.apply(Unknown Source)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error]         at sbt.util.Tracked$$$Lambda$2678/0000000000000000.apply(Unknown Source)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:116)
[error]         at sbt.internal.LibraryManagement$$$Lambda$2719/0000000000000000.apply(Unknown Source)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:116)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:97)
[error]         at sbt.internal.LibraryManagement$$$Lambda$2713/0000000000000000.apply(Unknown Source)
[error]         at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error]         at sbt.util.Tracked$$$Lambda$2646/0000000000000000.apply(Unknown Source)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:130)
[error]         at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:3327)
[error]         at sbt.Classpaths$$$Lambda$1344/0000000000000000.apply(Unknown Source)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at scala.Function1$$Lambda$1041/0000000000000000.apply(Unknown Source)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.internal.util.$tilde$greater$$Lambda$2307/0000000000000000.apply(Unknown Source)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.Execute$$Lambda$2325/0000000000000000.apply(Unknown Source)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.Execute$$Lambda$2315/0000000000000000.apply(Unknown Source)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:233)
[error]         at sbt.ConcurrentRestrictions$$anon$4$$Lambda$2322/0000000000000000.apply(Unknown Source)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:59)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:836)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.sioonhho:test-lib_2.12:1.0
[error]   Not found
[error]   Not found
[error]   not found: C:\Users\Andrew%20DeFilippo\.ivy2\local\com.sioonhho\test-lib_2.12\1.0\ivys\ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/sioonhho/test-lib_2.12/1.0/test-lib_2.12-1.0.pom
sbt:test-proj>
```

Specifying an explicit URL where there are no folders with spaces in the names successfully updates.
```
name := "test-proj"
scalaVersion := "2.12.12"
libraryDependencies += "com.sioonhho" %% "test-lib" % "1.0" from "file:///Z:/.ivy2/local/com.sioonhho/test-lib_2.12/1.0/ivys/ivy.xml"
```

```
sbt:test-proj> sbtVersion
[info] 1.4.0-RC1
sbt:test-proj> update
[success] Total time: 0 s, completed Sep 18, 2020, 10:42:01 PM
sbt:test-proj> last update
[debug] not up to date. inChanged = false, force = true
[debug] Updating ...
[debug] Done updating
sbt:test-proj>
```

**Comment by 0paIescent** [comment]
Went ahead and reported this on coursier/coursier as well since this looks like the exact same thing as #5433 https://github.com/coursier/coursier/issues/1861

**Comment by eed3si9n** [comment]
If this is a complete duplicate then I'm closing this in favor of #5433 then.
