### ISSUE TITLE
serverTestProj/test is getting flaky?

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#5891]
## steps

Not sure what but Travis CI job has been getting really flaky.

## problem

! 7058.1

```
[info] Here are some highlights of this release:
[info]   - Build server protocol (BSP) support
[info]   - sbtn: a native thin client for sbt
[info]   - VirtualFile + RemoteCache: caches build artifacts across different machines
[info]   - ThisBuild / versionScheme to take the guessing out of eviction warning
[info] See http://eed3si9n.com/sbt-1.4.0-beta for full release notes.
[info] Hide the banner for this release by running `skipBanner`.
[info] sbt server started at local:///home/travis/.sbt/1.0/server/cfd9b8fa94297dc5b51d/sock
[build-1] waiting for the server...
[build-1] waiting for the server...
[build-1] waiting for the server...
[build-1] waiting for the server...
[error] Uncaught exception when running testpkg.ServerCompletionsTest: java.lang.RuntimeException: Timeout. /home/travis/build/sbt/sbt/target/test-server/server-test648017339595567195/completions/project/target/active.json is not found.
[error] sbt.ForkMain$ForkError: java.lang.RuntimeException: Timeout. /home/travis/build/sbt/sbt/target/test-server/server-test648017339595567195/completions/project/target/active.json is not found.
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at testpkg.TestServer.waitForPortfile(TestServer.scala:189)
[error] 	at testpkg.TestServer.<init>(TestServer.scala:194)
[error] 	at testpkg.TestServer$.get(TestServer.scala:89)
[error] 	at testpkg.AbstractServerTest.setupSuite(TestServer.scala:58)
[error] 	at testpkg.AbstractServerTest.setupSuite$(TestServer.scala:40)
[error] 	at testpkg.ServerCompletionsTest$.setupSuite(ServerCompletionsTest.scala:13)
[error] 	at verify.TestSuite.$anonfun$properties$3(TestSuite.scala:42)
[error] 	at verify.runner.Task.$anonfun$execute$3(Task.scala:65)
[error] 	at scala.Option.fold(Option.scala:251)
[error] 	at verify.runner.Task.execute(Task.scala:63)
[error] 	at verify.runner.Task.execute(Task.scala:76)
[error] 	at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] Failed to execute task java.util.concurrent.FutureTask@6b26e945[Completed exceptionally: java.lang.NoClassDefFoundError: sbt/ForkMain$Run$3]
[error] Uncaught exception when running tests: java.net.SocketException: Too many open files
[error] sbt.ForkMain$ForkError: java.net.SocketException: Too many open files
[error] 	at java.base/java.net.Socket.createImpl(Socket.java:462)
[error] 	at java.base/java.net.Socket.<init>(Socket.java:433)
[error] 	at java.base/java.net.Socket.<init>(Socket.java:213)
[error] 	at org.scalatest.tools.SocketReporter.<init>(SocketReporter.scala:26)
[error] 	at org.scalatest.tools.ReporterFactory.createSocketReporter(ReporterFactory.scala:227)
[error] 	at org.scalatest.tools.ReporterFactory.getReporterFromConfiguration(ReporterFactory.scala:242)
[error] 	at org.scalatest.tools.ReporterFactory.$anonfun$createReportersFromConfigurations$1(ReporterFactory.scala:248)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:285)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at org.scalatest.tools.ReporterConfigurations.foreach(ReporterConfiguration.scala:42)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:285)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:278)
[error] 	at org.scalatest.tools.ReporterConfigurations.map(ReporterConfiguration.scala:42)
[error] 	at org.scalatest.tools.ReporterFactory.createReportersFromConfigurations(ReporterFactory.scala:247)
[error] 	at org.scalatest.tools.ReporterFactory.getDispatchReporter(ReporterFactory.scala:251)
[error] 	at org.scalatest.tools.Framework$ScalaTestRunner.<init>(Framework.scala:654)
[error] 	at org.scalatest.tools.Framework.runner(Framework.scala:1102)
[error] 	at sbt.ForkMain$Run.runTests(ForkMain.java:343)
[error] 	at sbt.ForkMain$Run.run(ForkMain.java:191)
[error] 	at sbt.ForkMain$Run.access$100(ForkMain.java:186)
[error] 	at sbt.ForkMain.main(ForkMain.java:177)
[error] 	at sbt.ForkMain.main(ForkMain.java:163)
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by eatkins** [comment]
Yes. This started happening after the recent jline changes. I’ll try and figure out what is going on.
