### ISSUE TITLE
NullPointerException with -Vphases scalac option

### ISSUE THREAD

**Issue by Jasper-M** [sbt/sbt#5907]
## steps
```
$ mkdir -p sbt-bug/project
$ cd sbt-bug
$ echo 'sbt.version=1.3.13' > project/build.properties
$ echo 'scalaVersion := "2.13.3"' > build.sbt
$ echo 'class Foo' > Foo.scala
$ sbt 'set scalacOptions += "-Vphases"' compile
```

## problem

No output from the compiler is printed. Compilation crashes with a `NullPointerException` instead.

<details>
<summary>Click to expand stacktrace</summary>

```scala         
[error] java.lang.NullPointerException
[error] 	at xsbt.ZincCompiler.phaseDescriptors$lzycompute(CallbackGlobal.scala:137)
[error] 	at xsbt.ZincCompiler.phaseDescriptors(CallbackGlobal.scala:135)
[error] 	at scala.tools.nsc.Global$Run.<init>(Global.scala:1236)
[error] 	at scala.tools.nsc.Global.phaseNames$lzycompute(Global.scala:742)
[error] 	at scala.tools.nsc.Global.phaseNames(Global.scala:741)
[error] 	at scala.tools.nsc.Global.phaseHelp(Global.scala:773)
[error] 	at scala.tools.nsc.Global.phaseDescriptions(Global.scala:747)
[error] 	at scala.tools.nsc.CompilerCommand.getInfoMessage(CompilerCommand.scala:115)
[error] 	at xsbt.CachedCompiler0.run(CompilerInterface.scala:144)
[error] 	at xsbt.CachedCompiler0.run(CompilerInterface.scala:125)
[error] 	at xsbt.CompilerInterface.run(CompilerInterface.scala:39)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
[error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:122)
[error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:95)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:91)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:186)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3$adapted(MixedAnalyzingCompiler.scala:77)
[error] 	at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:215)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:77)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:146)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:343)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:343)
[error] 	at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:120)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:100)
[error] 	at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:180)
[error] 	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:98)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:102)
[error] 	at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:155)
[error] 	at sbt.internal.inc.Incremental$.compile(Incremental.scala:92)
[error] 	at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:75)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:348)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:301)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:168)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:248)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:74)
[error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1765)
[error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1738)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
```
</details>

## expectation

Info should be printed to the screen, followed by this message.

```
[error] (Compile / compileIncremental) Compiler option supplied that disabled Zinc compilation.
```
Which is what happens when you use compiler options such as `-Y`, `-X` or `-V` (they print the available options).

**Comment by eed3si9n** [comment]
https://github.com/sbt/zinc/blob/1.3.x/internal/compiler-bridge/src/main/scala/xsbt/CallbackGlobal.scala#L135-L142

```scala
  override lazy val phaseDescriptors = {
    phasesSet += sbtAnalyzer
    if (callback.enabled()) {
      phasesSet += sbtDependency
      phasesSet += apiExtractor
    }
    this.computePhaseDescriptors
  }
```

I guess it could check that those phases no longer exists and error out more elegantly?

**Comment by som-snytt** [comment]
The use case is that if I enable some compiler plugin, I want to see the phases for a compiler run with `-Vphases`.

Still an issue under 1.4.0.
```
➜  phases sbt compile
[info] welcome to sbt 1.4.0 (Oracle Corporation Java 15)
[info] loading project definition from .../project
[info] loading settings for project phases from build.sbt ...
[info] set current project to phases (in build file:.../phases/)
[info] Executing in batch mode. For better performance use sbt's shell
[info] compiling 1 Scala source to .../phases/target/scala-2.13/classes ...
[error] ## Exception when compiling 1 sources to .../phases/target/scala-2.13/classes
[error] java.lang.NullPointerException: Cannot invoke "xsbti.AnalysisCallback.enabled()" because the return value of "xsbt.ZincCompiler.callback()" is null
[error] xsbt.ZincCompiler.phaseDescriptors$lzycompute(CallbackGlobal.scala:142)
[error] xsbt.ZincCompiler.phaseDescriptors(CallbackGlobal.scala:140)
[error] scala.tools.nsc.Global$Run.<init>(Global.scala:1236)
[error] scala.tools.nsc.Global.phaseNames$lzycompute(Global.scala:742)
[error] scala.tools.nsc.Global.phaseNames(Global.scala:741)
[error] scala.tools.nsc.Global.phaseHelp(Global.scala:773)
[error] scala.tools.nsc.Global.phaseDescriptions(Global.scala:747)
[error] scala.tools.nsc.CompilerCommand.getInfoMessage(CompilerCommand.scala:115)
[error] xsbt.CachedCompiler0.run(CompilerBridge.scala:154)
[error] xsbt.CachedCompiler0.run(CompilerBridge.scala:134)
[error] xsbt.CompilerBridge.run(CompilerBridge.scala:39)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:92)
```
