### ISSUE TITLE
1.4.0: AssertionError: Created a Compilations with duplicate compilations

### ISSUE THREAD

**Issue by jtjeferreira** [sbt/sbt#5911]
## steps

In my play work project I got the following exception:

```
java.lang.AssertionError: assertion failed: Created a Compilations with duplicate compilations
	at scala.Predef$.assert(Predef.scala:223)
	at sbt.internal.inc.MCompilations.<init>(Compilations.scala:41)
	at sbt.internal.inc.MCompilations.$plus$plus(Compilations.scala:44)
	at sbt.internal.inc.MAnalysis.$plus$plus(Analysis.scala:148)
	at play.sbt.PlayCommands$.$anonfun$playReloadTask$2(PlayCommands.scala:16)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:91)
	at scala.collection.LinearSeqOptimized.reduceLeft(LinearSeqOptimized.scala:140)
	at scala.collection.LinearSeqOptimized.reduceLeft$(LinearSeqOptimized.scala:138)
	at scala.collection.immutable.List.reduceLeft(List.scala:91)
	at play.sbt.PlayCommands$.$anonfun$playReloadTask$1(PlayCommands.scala:16)
	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.Execute.work(Execute.scala:291)
	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:252)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

## problem

This is a an assertion introduced by https://github.com/sbt/zinc/pull/800/files, but I am not sure if the problem is the assertion or the play plugin is breaking some invariant

## expectation

The default play landing page rendered

## notes

Since I dont have a reproducer project yet. Here is what I found using a debugger:

`allCompilations: Seq[Compilation]` has size 431, but `allCompilations.map(_.getStartTime).distinct` has size 430.

The duplicate entry is like this
```
Compilation(1601373667716, SingleOutput(/home/joao/git/project/modules/urlshortener/target/scala-2.12/classes))
Compilation(1601373667716, SingleOutput(/home/joao/git/project/modules/fxrateservice/target/scala-2.12/classes))
``` 

There are multiple entries referencing the same `output`. For example `urlshortener` appears 6 times, `fxrateservice` appears 5 times. The total distribution is `3, 3, 3, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 8, 8, 8, 8, 8, 9, 9, 9, 9, 10, 11, 11, 11, 12, 12, 12, 12, 13, 13, 13, 14, 16, 30, 30, 31, 31
` (i.e some modules appear 3 times, others appear 31 times...)

**Comment by sbrunk** [comment]
I've just tried sbt 1.4.0 on our play project and I'm running into the same issue.

**Comment by jtjeferreira** [comment]
Found an workaround which is to set 

```scala
play.sbt.PlayInternalKeys.playCompileEverything ~= (_.map(_.copy(compilations = sbt.internal.inc.Compilations.of(Seq.empty)))),
```

This works because the play plugin code will only use `analysis.relations` and not `analysis.compilations`

**Comment by Victorblsilveira** [comment]
@jtjeferreira 

Set as project settings, 

```
lazy val myproject = (project in file("myproject"))
  .settings(
       play.sbt.PlayInternalKeys.playCompileEverything ~= (_.map(_.copy(compilations = sbt.internal.inc.Compilations.of(Seq.empty))))
)
```

**Comment by jtjeferreira** [comment]
> @jtjeferreira
> 
> Set as project settings,
> 
> ```
> lazy val myproject = (project in file("myproject"))
>   .settings(
>        play.sbt.PlayInternalKeys.playCompileEverything ~= (_.map(_.copy(compilations = sbt.internal.inc.Compilations.of(Seq.empty))))
> )
> ```

Hi @Victorblsilveira! Was that a question? Or that is just an example of how to set the `playCompileEverything`?

**Comment by Victorblsilveira** [comment]
Was just an example

**Comment by francisdb** [comment]
Should this be reported in the play project?

**Comment by jtjeferreira** [comment]
> Should this be reported in the play project?

I mentioned this ticket in https://github.com/playframework/playframework/pull/10489

**Comment by bjaglin** [comment]
No longer a problem in 1.4.3 thanks to https://github.com/sbt/zinc/pull/940
