### ISSUE TITLE
Error while resolving dependencies for com.lightbend.cinnamon#cinnamon-agent;2.13.1

### ISSUE THREAD

**Issue by zerohour69** [sbt/sbt#5942]
## steps

```scala
import sbt._

lazy val base = (project in file("."))
  .aggregate(
    common,
    exercises
  )
  .settings(CommonSettings.commonSettings: _*)

lazy val common = project
  .settings(CommonSettings.commonSettings: _*)

lazy val exercises = project
  .settings(CommonSettings.commonSettings: _*)
  .dependsOn(common % "test->test;compile->compile")
  .enablePlugins(Cinnamon)

(Compile / runMain) := ((Compile / runMain) in exercises).evaluated
onLoad in Global := (onLoad in Global).value andThen (Command.process("project exercises", _))
```

## problem

<details>
<summary>

```
[error] 	typesafe-maven-releases: unable to get resource for com/lightbend/cinnamon#cinnamon-agent;2.13.1: res=http://repo.typesafe.com/typesafe/maven-releases/com/lightbend/cinnamon/cinnamon-agent/2.13.1/cinnamon-agent-2.13.1.pom: java.net.ConnectException: Failed to connect to repo.typesafe.com/34.202.110.138:80
[error] 	typesafe-maven-releases: unable to get resource for com/lightbend/cinnamon#cinnamon-agent;2.13.1: res=http://repo.typesafe.com/typesafe/maven-releases/com/lightbend/cinnamon/cinnamon-agent/2.13.1/cinnamon-agent-2.13.1.jar: java.net.ConnectException: Failed to connect to repo.typesafe.com/34.202.110.138:80
```

</summary>

```
[warn]	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.lightbend.cinnamon#cinnamon-agent;2.13.1: Resolution failed several times for dependency: com.lightbend.cinnamon#cinnamon-agent;2.13.1 {javaagent=[default(compile)]}::
[warn] 	typesafe-maven-releases: unable to get resource for com/lightbend/cinnamon#cinnamon-agent;2.13.1: res=http://repo.typesafe.com/typesafe/maven-releases/com/lightbend/cinnamon/cinnamon-agent/2.13.1/cinnamon-agent-2.13.1.pom: java.net.ConnectException: Failed to connect to repo.typesafe.com/34.202.110.138:80
[warn] 	typesafe-maven-releases: unable to get resource for com/lightbend/cinnamon#cinnamon-agent;2.13.1: res=http://repo.typesafe.com/typesafe/maven-releases/com/lightbend/cinnamon/cinnamon-agent/2.13.1/cinnamon-agent-2.13.1.jar: java.net.ConnectException: Failed to connect to repo.typesafe.com/34.202.110.138:80
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.lightbend.cinnamon:cinnamon-agent:2.13.1 ((com.lightbend.sbt.javaagent.JavaAgent.projectSettings) JavaAgent.scala#L62)
[warn] 		  +- com.lightbend.training:exercises_2.13:1.3.0
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.lightbend.cinnamon#cinnamon-agent;2.13.1: Resolution failed several times for dependency: com.lightbend.cinnamon#cinnamon-agent;2.13.1 {javaagent=[default(compile)]}::
[error] 	typesafe-maven-releases: unable to get resource for com/lightbend/cinnamon#cinnamon-agent;2.13.1: res=http://repo.typesafe.com/typesafe/maven-releases/com/lightbend/cinnamon/cinnamon-agent/2.13.1/cinnamon-agent-2.13.1.pom: java.net.ConnectException: Failed to connect to repo.typesafe.com/34.202.110.138:80
[error] 	typesafe-maven-releases: unable to get resource for com/lightbend/cinnamon#cinnamon-agent;2.13.1: res=http://repo.typesafe.com/typesafe/maven-releases/com/lightbend/cinnamon/cinnamon-agent/2.13.1/cinnamon-agent-2.13.1.jar: java.net.ConnectException: Failed to connect to repo.typesafe.com/34.202.110.138:80
[error]
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:332)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:239)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:238)
[error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
[error] 	at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:45)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:93)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:106)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:106)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:89)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:120)
[error] 	at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2561)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.lightbend.cinnamon#cinnamon-agent;2.13.1: Resolution failed several times for dependency: com.lightbend.cinnamon#cinnamon-agent;2.13.1 {javaagent=[default(compile)]}::
[error] 	typesafe-maven-releases: unable to get resource for com/lightbend/cinnamon#cinnamon-agent;2.13.1: res=http://repo.typesafe.com/typesafe/maven-releases/com/lightbend/cinnamon/cinnamon-agent/2.13.1/cinnamon-agent-2.13.1.pom: java.net.ConnectException: Failed to connect to repo.typesafe.com/34.202.110.138:80
[error] 	typesafe-maven-releases: unable to get resource for com/lightbend/cinnamon#cinnamon-agent;2.13.1: res=http://repo.typesafe.com/typesafe/maven-releases/com/lightbend/cinnamon/cinnamon-agent/2.13.1/cinnamon-agent-2.13.1.jar: java.net.ConnectException: Failed to connect to repo.typesafe.com/34.202.110.138:80
[error]
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:332)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:239)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:238)
[error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
[error] 	at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:45)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:93)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:106)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:106)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:89)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:120)
[error] 	at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2561)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (update) sbt.librarymanagement.ResolveException: unresolved dependency: com.lightbend.cinnamon#cinnamon-agent;2.13.1: Resolution failed several times for dependency: com.lightbend.cinnamon#cinnamon-agent;2.13.1 {javaagent=[default(compile)]}::
[error] 	typesafe-maven-releases: unable to get resource for com/lightbend/cinnamon#cinnamon-agent;2.13.1: res=http://repo.typesafe.com/typesafe/maven-releases/com/lightbend/cinnamon/cinnamon-agent/2.13.1/cinnamon-agent-2.13.1.pom: java.net.ConnectException: Failed to connect to repo.typesafe.com/34.202.110.138:80
[error] 	typesafe-maven-releases: unable to get resource for com/lightbend/cinnamon#cinnamon-agent;2.13.1: res=http://repo.typesafe.com/typesafe/maven-releases/com/lightbend/cinnamon/cinnamon-agent/2.13.1/cinnamon-agent-2.13.1.jar: java.net.ConnectException: Failed to connect to repo.typesafe.com/34.202.110.138:80
[error] (ssExtractDependencies) sbt.librarymanagement.ResolveException: unresolved dependency: com.lightbend.cinnamon#cinnamon-agent;2.13.1: Resolution failed several times for dependency: com.lightbend.cinnamon#cinnamon-agent;2.13.1 {javaagent=[default(compile)]}::
[error] 	typesafe-maven-releases: unable to get resource for com/lightbend/cinnamon#cinnamon-agent;2.13.1: res=http://repo.typesafe.com/typesafe/maven-releases/com/lightbend/cinnamon/cinnamon-agent/2.13.1/cinnamon-agent-2.13.1.pom: java.net.ConnectException: Failed to connect to repo.typesafe.com/34.202.110.138:80
[error] 	typesafe-maven-releases: unable to get resource for com/lightbend/cinnamon#cinnamon-agent;2.13.1: res=http://repo.typesafe.com/typesafe/maven-releases/com/lightbend/cinnamon/cinnamon-agent/2.13.1/cinnamon-agent-2.13.1.jar: java.net.ConnectException: Failed to connect to repo.typesafe.com/34.202.110.138:80
[error] Total time: 64 s, completed Oct 6, 2020 4:15:37 PM
[info] shutting down server
```

</details>

## expectation

All the dependencies should get resolved 

## notes
I had added below option in the environment variable sbt_opts :
-Dsbt.repository.secure=false -Dsbt.gigahorse=false

**Comment by eed3si9n** [comment]
@zerohour69 Thanks for this bug report, especially including the full error message!

From the error message I can tell that it's trying to hit http://repo.typesafe.com/typesafe/maven-releases/com/lightbend/cinnamon/cinnamon-agent/2.13.1/cinnamon-agent-2.13.1.pom.

Lightbend has stopped HTTP on repo.typesafe.com starting August 5, 2020 for security reason. See this blog post that I wrote (https://www.lightbend.com/blog/lightbend-to-require-https-on-repos-starting-august-5-2020) while I was there. The fix is to switch to using HTTPS. If you're a customer using Cinnamon, it's probably better to contact them about this via support case.

**Comment by zerohour69** [comment]
Thanks a lot for the prompt info.I was able to correct the issue by change all the repository link from http to https.

**Comment by zerohour69** [comment]
> @zerohour69 Thanks for this bug report, especially including the full error message!
> 
> From the error message I can tell that it's trying to hit http://repo.typesafe.com/typesafe/maven-releases/com/lightbend/cinnamon/cinnamon-agent/2.13.1/cinnamon-agent-2.13.1.pom.
> 
> Lightbend has stopped HTTP on repo.typesafe.com starting August 5, 2020 for security reason. See this blog post that I wrote (https://www.lightbend.com/blog/lightbend-to-require-https-on-repos-starting-august-5-2020) while I was there. The fix is to switch to using HTTPS. If you're a customer using Cinnamon, it's probably better to contact them about this via support case.

Thanks a lot for the prompt info.I was able to correct the issue by change all the repository link from http to https.

**Comment by waterWang** [comment]
I had my resolvers set to "http://repo.typesafe.com/typesafe/releases/" and changing the resolver to using https made it work.
