### ISSUE TITLE
Weird `CancellationException` thrown when importing sbt project with BSP

### ISSUE THREAD

**Issue by adpi2** [sbt/sbt#5963]
## steps
Into the sbt repository:
- start the sbt shell
- run the `clean` command
- run the `bspBuildTargetCompile file:/home/adpi2/sbt/sbt/#serverTestProj/Test file:/home/adpi2/sbt/sbt/#runProj/Test` command

The `bspBuildTargetCompile` command corresponds to the `buildTarget/compile` BSP request. It triggers the `compile` task of all given projects and then reply success or error to the client.

In the given example we want to compile `serverTestProj / Test` and `runProj / Test`.

## problem

The first problem is that the generated classpath contains an empty `home/adpi2/sbt/sbt/run/target/scala-2.12/early/run_2.12-1.4.1-SNAPSHOT.jar` which causes some compilation error of the form:

```
[error] /home/adpi2/sbt/sbt/main-actions/src/main/scala/sbt/ForkTests.scala:29:13: not found: type ForkOptions
[error]       fork: ForkOptions,
```

The second problem is that a `CancellationException` is thrown. The full stack trace is:

```
java.util.concurrent.CancellationException
        at java.util.concurrent.FutureTask.report(FutureTask.java:121)
  | => aat java.util.concurrent.FutureTask.get(FutureTask.java:192)
  | => pat sbt.ConcurrentRestrictions$$anon$4.take(ConcurrentRestrictions.scala:309)
        at sbt.Execute.next$1(Execute.scala:117)
	at sbt.Execute.processAll(Execute.scala:127)
	at sbt.Execute.runKeep(Execute.scala:95)
	at sbt.EvaluateTask$.liftedTree1$1(EvaluateTask.scala:472)
	at sbt.EvaluateTask$.run$1(EvaluateTask.scala:471)
	at sbt.EvaluateTask$.runTask(EvaluateTask.scala:494)
	at sbt.internal.Aggregation$.$anonfun$timedRun$4(Aggregation.scala:101)
	at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:388)
	at sbt.internal.Aggregation$.timedRun(Aggregation.scala:99)
	at sbt.internal.Aggregation$.runTasks(Aggregation.scala:113)
	at sbt.internal.Aggregation$.$anonfun$applyDynamicTasks$4(Aggregation.scala:181)
	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:145)
	at sbt.internal.Act$.$anonfun$actParser0$4(Act.scala:436)
	at sbt.Command$.process(Command.scala:189)
	at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:245)
	at scala.Option.getOrElse(Option.scala:189)
	at sbt.MainLoop$.process$1(MainLoop.scala:245)
	at sbt.MainLoop$.processCommand(MainLoop.scala:269)
	at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:162)
	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:286)
	at sbt.State$StateOpsImpl$.process$extension(State.scala:322)
	at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:162)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.MainLoop$.next(MainLoop.scala:162)
	at sbt.MainLoop$.run(MainLoop.scala:143)
	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:118)
	at sbt.io.Using.apply(Using.scala:27)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:111)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:65)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:50)
	at sbt.MainLoop$.runLogged(MainLoop.scala:41)
	at sbt.StandardMain$.runManaged(Main.scala:188)
	at sbt.xMain$.$anonfun$run$6(Main.scala:100)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withIn(Console.scala:230)
	at sbt.internal.util.Terminal$.withIn(Terminal.scala:540)
	at sbt.internal.util.Terminal$.$anonfun$withStreams$2(Terminal.scala:335)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withOut(Console.scala:167)
	at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:530)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withErr(Console.scala:196)
	at sbt.internal.util.Terminal$.withOut(Terminal.scala:530)
	at sbt.internal.util.Terminal$.withStreams(Terminal.scala:335)
	at sbt.xMain$.run(Main.scala:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:83)
	at sbt.xMain.run(Main.scala:46)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:130)
	at xsbt.boot.Launch$.run(Launch.scala:111)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
	at xsbt.boot.Launch$.launch(Launch.scala:119)
	at xsbt.boot.Launch$.apply(Launch.scala:20)
	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
	at xsbt.boot.Boot$.main(Boot.scala:18)
	at xsbt.boot.Boot.main(Boot.scala)
```

## expectation

No exception should be thrown.

**Comment by eed3si9n** [comment]
Maybe related to https://github.com/sbt/sbt/pull/5847?

**Comment by eed3si9n** [comment]
I am closing this due to inactivity, but if this is still relevant let us know with more details (reproduction steps etc).
