### ISSUE TITLE
Regression on Windows during migration from 1.4.0 to 1.4.1

### ISSUE THREAD

**Issue by plokhotnyuk** [sbt/sbt#5994]
## steps

It happened during CI build with GitHub Actions using JDK 8 and JDK 16: 
https://github.com/plokhotnyuk/expression-evaluator/pull/53/checks?check_run_id=1279518609

## problem

An unexpected exception during compilation of unit tests:
```
Error:  D:\a\expression-evaluator\expression-evaluator\src\test\scala\com\github\plokhotnyuk\expression_evaluator\EvalSpec.scala:48:60: exception during macro expansion: 
Error:  java.nio.file.InvalidPathException: Illegal char <<> at index 0: <macro>
Error:  	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
Error:  	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
Error:  	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
Error:  	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
Error:  	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
Error:  	at java.nio.file.Paths.get(Paths.java:84)
Error:  	at sbt.internal.inc.MappedVirtualFile$.toPath(MappedVirtualFile.scala:36)
Error:  	at sbt.internal.inc.MappedFileConverter.toPath(MappedVirtualFile.scala:53)
Error:  	at sbt.Defaults$.$anonfun$toAbsoluteSourceMapper$2(Defaults.scala:471)
Error:  	at java.util.Optional.map(Optional.java:215)
Error:  	at sbt.Defaults$.$anonfun$toAbsoluteSourceMapper$1(Defaults.scala:470)
Error:  	at sbt.Defaults$.$anonfun$foldMappers$3(Defaults.scala:2246)
Error:  	at sbt.internal.inc.LoggedReporter.log(LoggedReporter.scala:131)
Error:  	at sbt.internal.server.BuildServerReporter.log(BuildServerReporter.scala:55)
Error:  	at sbt.internal.server.BuildServerReporter.log$(BuildServerReporter.scala:50)
Error:  	at sbt.internal.server.BuildServerReporterImpl.log(BuildServerReporter.scala:62)
Error:  	at xsbt.DelegatingReporter.info0(DelegatingReporter.scala:185)
Error:  	at xsbt.DelegatingReporter.info0(DelegatingReporter.scala:162)
Error:  	at scala.reflect.internal.Reporter.warning(Reporting.scala:90)
Error:  	at scala.reflect.internal.Reporting.warning(Reporting.scala:74)
Error:  	at scala.reflect.internal.Reporting.warning$(Reporting.scala:74)
Error:  	at scala.reflect.internal.SymbolTable.warning(SymbolTable.scala:28)
Error:  	at scala.tools.nsc.typechecker.ConstantFolder.apply(ConstantFolder.scala:52)
Error:  	at scala.tools.nsc.typechecker.Typers$Typer.handleMonomorphicCall$1(Typers.scala:3715)
Error:  	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$doTypedApply$29(Typers.scala:3722)
Error:  	at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3722)
Error:  	at scala.tools.nsc.typechecker.Typers$Typer.handleOverloaded$1(Typers.scala:3520)
Error:  	at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3523)
Error:  	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$26(Typers.scala:4767)
Error:  	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$silent$2(Typers.scala:725)
Error:  	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:725)
Error:  	at scala.tools.nsc.typechecker.Typers$Typer.tryTypedApply$1(Typers.scala:4767)
Error:  	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4851)
Error:  	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4862)
Error:  	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5678)
Error:  	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5724)
Error:  	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedArg$1(Typers.scala:3353)
Error:  	at scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:490)
Error:  	at scala.tools.nsc.typechecker.Typers$Typer.typedArgToPoly$1(Typers.scala:3743)
Error:  	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$doTypedApply$32(Typers.scala:3751)
Error:  	at scala.tools.nsc.typechecker.Typers$Typer.handlePolymorphicCall$1(Typers.scala:3751)
Error:  	at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3762)
Error:  	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4853)
Error:  	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4862)
Error:  	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5678)
Error:  	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5724)
Error:  	at scala.reflect.macros.contexts.Typers.$anonfun$typecheck$4(Typers.scala:38)
Error:  	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$silent$2(Typers.scala:725)
Error:  	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:725)
Error:  	at scala.reflect.macros.contexts.Typers.$anonfun$typecheck$3(Typers.scala:38)
Error:  	at scala.reflect.macros.contexts.Typers.$anonfun$typecheck$2(Typers.scala:38)
Error:  	at scala.reflect.macros.contexts.Typers.doTypecheck$1(Typers.scala:37)
Error:  	at scala.reflect.macros.contexts.Typers.$anonfun$typecheck$7(Typers.scala:50)
Error:  	at scala.reflect.internal.Trees.wrappingIntoTerm(Trees.scala:1782)
Error:  	at scala.reflect.internal.Trees.wrappingIntoTerm$(Trees.scala:1779)
Error:  	at scala.reflect.internal.SymbolTable.wrappingIntoTerm(SymbolTable.scala:28)
Error:  	at scala.reflect.macros.contexts.Typers.typecheck(Typers.scala:50)
Error:  	at scala.reflect.macros.contexts.Typers.typecheck$(Typers.scala:32)
Error:  	at scala.reflect.macros.contexts.Context.typecheck(Context.scala:18)
Error:  	at scala.reflect.macros.contexts.Context.typecheck(Context.scala:18)
Error:  	at scala.reflect.macros.Typers.typeCheck(Typers.scala:70)
Error:  	at scala.reflect.macros.Typers.typeCheck$(Typers.scala:69)
Error:  	at scala.reflect.macros.contexts.Context.typeCheck(Context.scala:18)
Error:  	at org.scalatest.CompileMacro$.assertCompilesImpl(CompileMacro.scala:308)
Error:        assert(intercept[TestFailedException](assertCompiles {
```

## expectation

Successful build

**Comment by eed3si9n** [comment]
Thanks for the report!

@adpi2 I'm guessing this is related to https://github.com/sbt/sbt/pull/5948
In some cases the compiler was emitting warnings for synthetic classes (that was previously ignored?) that's now causing issue because Windows is more strict about `<` character appearing in the path.

**Comment by adpi2** [comment]
This one fails on `sbt 1.4.0` as well: https://github.com/adpi2/expression-evaluator/runs/1286912320?check_suite_focus=true
So clearly #5948 is not the root cause.

I rather think that #5857 is the problem:
  - sometime the compiler reports errors on "fake" position: in the present case the `sourceFile` is `"<macro>"`
  - when we try to convert the `sourceFile` to absolute path it fails
