### ISSUE TITLE
java.nio.file.InvalidPathException caused by file names in parent directory of the project directory

### ISSUE THREAD

**Issue by divijan** [sbt/sbt#5997]
## steps
Encountered with sbt 1.3.13, with sbt 1.4.1 it was worse. I use Manjaro Linux. The issue was reproduced in Konsole terminal emulator and in actual terminal.

Here is my `build.sbt`:
```
name := "cats-sandbox"

version := "0.0.1-SNAPSHOT"

scalaVersion := "2.13.1"

libraryDependencies += "org.typelevel" %% "cats-core" % "2.0.0"

// scalac options come from the sbt-tpolecat plugin so need to set any here

addCompilerPlugin("org.typelevel" %% "kind-projector" % "0.11.0" cross CrossVersion.full)
```
in addition to that, you have to put some file with "unmappable characters" in the name (in my case, cyrillic) in the parent directory of your project root directory, i.e. if your project is in `~/code/some-project`, put the culprit file in `~/code`

## problem

**For sbt 1.3.x:** when trying to run task with triggered execution (preceded with `~`) in batch or interactive mode, the task doesn't start and I get:

`java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /home/yar/coding/ПодарyнoкOLX.html`

**For sbt 1.4.1:** when trying to run any task in batch mode or just launch interactive mode I get:

```[info] welcome to sbt 1.4.1 (Oracle Corporation Java 1.8.0_265)
[info] loading global plugins from /home/yar/.sbt/1.0/plugins
[info] loading settings for project throttling-service-build from plugins.sbt ...
[info] loading project definition from /home/yar/coding/throttling-service/project
[info] loading settings for project throttling-service from build.sbt ...
[info] set current project to throttling-service (in build file:/home/yar/coding/throttling-service/)
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /home/yar/coding/ПодарyнoкOLX.html
        at sun.nio.fs.UnixPath.encode(UnixPath.java:147)
        at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
        at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
        at java.nio.file.Paths.get(Paths.java:84)
        at com.swoval.files.SimpleFileTreeView$Lister.impl(SimpleFileTreeView.java:168)
        at com.swoval.files.SimpleFileTreeView$Lister.fillResults(SimpleFileTreeView.java:140)
        at com.swoval.files.SimpleFileTreeView.list(SimpleFileTreeView.java:50)
        at com.swoval.files.CachedDirectoryImpl.init(CachedDirectoryImpl.java:568)
        at com.swoval.files.CachedDirectoryImpl.init(CachedDirectoryImpl.java:557)
        at com.swoval.files.NioPathWatcher.findOrAddRoot(NioPathWatcher.java:275)
        at com.swoval.files.NioPathWatcher.getOrAdd(NioPathWatcher.java:295)
        at com.swoval.files.NioPathWatcher.register(NioPathWatcher.java:194)
        at com.swoval.files.FileCacheDirectoryTree.register(FileCacheDirectoryTree.java:417)
        at com.swoval.files.FileCachePathWatcher.register(FileCachePathWatcher.java:24)
        at com.swoval.files.FileTreeRepositoryImpl.register(FileTreeRepositoryImpl.java:101)
        at sbt.internal.nio.FileTreeRepositoryImpl.register(FileTreeRepositoryImpl.scala:130)
        at sbt.internal.nio.CheckBuildSources.$anonfun$reset$3(CheckBuildSources.scala:78)
        at sbt.internal.nio.CheckBuildSources.$anonfun$reset$3$adapted(CheckBuildSources.scala:78)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at sbt.internal.nio.CheckBuildSources.sbt$internal$nio$CheckBuildSources$$reset(CheckBuildSources.scala:78)
        at sbt.internal.nio.CheckBuildSources$.init(CheckBuildSources.scala:185)
        at sbt.BuiltinCommands$.doLoadProject(Main.scala:946)
        at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:882)
        at sbt.Command$.$anonfun$applyEffect$4(Command.scala:150)
        at sbt.Command$.$anonfun$applyEffect$2(Command.scala:145)
        at sbt.Command$.process(Command.scala:189)
        at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:245)
        at scala.Option.getOrElse(Option.scala:189)
        at sbt.MainLoop$.process$1(MainLoop.scala:245)
        at sbt.MainLoop$.processCommand(MainLoop.scala:271)
        at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:162)
        at sbt.State$StateOpsImpl$.runCmd$1(State.scala:286)
        at sbt.State$StateOpsImpl$.process$extension(State.scala:322)
        at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:162)
        at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
        at sbt.MainLoop$.next(MainLoop.scala:162)
        at sbt.MainLoop$.run(MainLoop.scala:143)
        at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:118)
        at sbt.io.Using.apply(Using.scala:27)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:111)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:65)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:50)
        at sbt.MainLoop$.runLogged(MainLoop.scala:41)
        at sbt.StandardMain$.runManaged(Main.scala:188)
        at sbt.xMain$.$anonfun$run$6(Main.scala:100)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withIn(Console.scala:230)
        at sbt.internal.util.Terminal$.withIn(Terminal.scala:542)
        at sbt.internal.util.Terminal$.$anonfun$withStreams$2(Terminal.scala:337)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withOut(Console.scala:167)
        at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:532)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withErr(Console.scala:196)
        at sbt.internal.util.Terminal$.withOut(Terminal.scala:532)
        at sbt.internal.util.Terminal$.withStreams(Terminal.scala:337)
        at sbt.xMain$.run(Main.scala:83)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:83)
        at sbt.xMain.run(Main.scala:46)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:130)
        at xsbt.boot.Launch$.run(Launch.scala:111)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
        at xsbt.boot.Launch$.launch(Launch.scala:119)
        at xsbt.boot.Launch$.apply(Launch.scala:20)
        at xsbt.boot.Boot$.runImpl(Boot.scala:56)
        at xsbt.boot.Boot$.main(Boot.scala:18)
        at xsbt.boot.Boot.main(Boot.scala)
[error] java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /home/yar/coding/ПодарyнoкOLX.html
[error] Use 'last' for the full log.
```

## expectation

sbt shouldn't care what file names there are in paths above the project directory.

**Comment by eatkins** [comment]
Thanks for the report! This looks like more of a jdk problem than an sbt problem. It looks like you may need to set some environment variables for the jdk to handle non-utf8 characters: https://stackoverflow.com/questions/22413421/git-error-malformed-input-or-input-contains-unmappable-chacraters. Please report back if setting those environment variables fix or do not fix your issue.

**Comment by divijan** [comment]
Ok, thanks, but why does sbt care what files are named outside the project directory anyway? In that stackoverflow question that bad filename was at least inside the project directory

**Comment by eatkins** [comment]
If sbt is monitoring a directory, it may need to monitor the parent directory so that it can detect if the directory is deleted. The behavior depends on what platform you are using because the file watch semantics are different.

**Comment by divijan** [comment]
I see. I'm using Manjaro Linux. That fix you gave link to works

**Comment by eatkins** [comment]
@eed3si9n I'm wondering if we should add documentation for the InvalidPathException with non-ascii path names so that it will hopefully be googleable. Any thoughts on where that should go?

**Comment by eed3si9n** [comment]
@eatkins Probably here? https://www.scala-sbt.org/1.x/docs/Setup-Notes.html
