### ISSUE TITLE
Triggered Execution Testing with `testOnly` grinds and then display concurrency error 

### ISSUE THREAD

**Issue by dhinojosa** [sbt/sbt#6020]
## steps

This has started happening with 1.4.0 and greater.
Running a set of tests, for example, with my [cat-study](https://github.com/dhinojosa/cats-study) project, where I have numerous tests, I run `~testOnly <class>`. The test grinds to a halt never really finishing the test.  When I hit *CTRL+C*, the following message appears

```
java.util.concurrent.RejectedExecutionException
  | => cat sbt.ConcurrentRestrictions$$anon$4.submit(ConcurrentRestrictions.scala:242)
	at sbt.Execute.submit(Execute.scala:282)
	at sbt.Execute.ready(Execute.scala:262)
	at sbt.Execute.notifyDone(Execute.scala:201)
	at sbt.Execute.$anonfun$retire$2(Execute.scala:172)
	at sbt.Execute.$anonfun$retire$2$adapted(Execute.scala:171)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at sbt.Execute.retire(Execute.scala:171)
	at sbt.Execute.$anonfun$retire$3(Execute.scala:175)
	at sbt.Execute.$anonfun$retire$3$adapted(Execute.scala:174)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at sbt.Execute.retire(Execute.scala:174)
	at sbt.Execute.$anonfun$work$2(Execute.scala:299)
	at sbt.Execute$$anon$1.process(Execute.scala:27)
	at sbt.Execute.next$1(Execute.scala:117)
	at sbt.Execute.processAll(Execute.scala:127)
	at sbt.Execute.runKeep(Execute.scala:95)
	at sbt.EvaluateTask$.liftedTree1$1(EvaluateTask.scala:472)
	at sbt.EvaluateTask$.run$1(EvaluateTask.scala:471)
	at sbt.EvaluateTask$.runTask(EvaluateTask.scala:494)
```

Running `last` I get:

```
[debug] > Exec(__stopWatch console0, None, None)
[debug] > Exec(__waitWatch console0, None, None)
[debug] > Exec(resumeFromFailure, None, None)
[debug] > Exec(__waitWatch console0, None, None)
[debug] > Exec(resumeFromFailure, None, None)
[debug] > Exec(__waitWatch console0, None, None)
[debug] > Exec(resumeFromFailure, None, None)
[debug] > Exec(shell, None, None)
```

## problem

I suspect there is a change with the SBT 1.4.0 and how it does concurrency and testing, this didn't happen with 1.3x

## expectation

It should run a single test with ~testOnly.

**Comment by dhinojosa** [comment]
False alarm. Thanks everyone
