### ISSUE TITLE
`OutOfMemoryError` with large resource files 

### ISSUE THREAD

**Issue by vincenzobaz** [sbt/sbt#6029]
## steps

sbt version: 1.4.0
build.sbt: minmal (name, version, scala version)
Large (> 1GB) static file in `src/main/resources`

## problem

`sbt compile` succeeds but `sbt run` crashes with the following stack trace:

```shell
➜  errors sbt run
[info] welcome to sbt 1.4.0 (AdoptOpenJDK Java 11.0.7)
[info] loading settings for project errors-build-build-build from metals.sbt ...
[info] loading project definition from /home/vinz/Desktop/errors/project/project/project
[info] loading settings for project errors-build-build from metals.sbt ...
[info] loading project definition from /home/vinz/Desktop/errors/project/project
[success] Generated .bloop/errors-build-build.json
[success] Total time: 1 s, completed Oct 26, 2020, 10:34:10 AM
[info] loading settings for project errors-build from metals.sbt,plugins.sbt ...
[info] loading project definition from /home/vinz/Desktop/errors/project
[success] Generated .bloop/errors-build.json
[success] Total time: 1 s, completed Oct 26, 2020, 10:34:11 AM
[info] loading settings for project errors from build.sbt ...
[info] set current project to errors (in build file:/home/vinz/Desktop/errors/)
java.lang.OutOfMemoryError: Required array size too large
        at java.base/java.nio.file.Files.readAllBytes(Files.java:3211)
        at sbt.internal.inc.HashUtil$.farmHash(HashUtil.scala:24)
        at sbt.internal.inc.FarmHash$.ofPath(Stamp.scala:89)
        at sbt.internal.inc.Stamper$.$anonfun$forFarmHashP$2(Stamp.scala:196)
        at sbt.internal.inc.Stamper$.tryStamp(Stamp.scala:188)
        at sbt.internal.inc.Stamper$.$anonfun$forFarmHashP$1(Stamp.scala:196)
        at sbt.nio.FileStamp$.hash(FileStamp.scala:91)
        at sbt.nio.FileStamp$.apply(FileStamp.scala:65)
        at sbt.nio.FileStamp$Cache.updateImpl(FileStamp.scala:318)
        at sbt.nio.FileStamp$Cache.getOrElseUpdate(FileStamp.scala:285)
        at sbt.nio.Settings$.$anonfun$fileStamps$4(Settings.scala:288)
        at sbt.nio.Settings$.$anonfun$fileStamps$6(Settings.scala:293)
        at scala.collection.parallel.AugmentedIterableIterator.flatmap2combiner(RemainsIterator.scala:133)
        at scala.collection.parallel.AugmentedIterableIterator.flatmap2combiner$(RemainsIterator.scala:130)
        at scala.collection.parallel.immutable.ParVector$ParVectorIterator.flatmap2combiner(ParVector.scala:66)
        at scala.collection.parallel.ParIterableLike$FlatMap.leaf(ParIterableLike.scala:1074)
        at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
        at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
        at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
        at scala.collection.parallel.ParIterableLike$FlatMap.tryLeaf(ParIterableLike.scala:1070)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:160)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:157)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:150)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
        at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[error] [launcher] error during sbt launcher: java.lang.OutOfMemoryError: Required array size too large
```

## expectation

sbt should not crash

## notes
The error disappears if I move the static files to the root of the project

**Comment by eatkins** [comment]
@eed3si9n this is a problem with FarmHash because it doesn't offer a streaming version. I'm wondering if there is another fast hasher that doesn't require loading the entire file into memory?

**Comment by eed3si9n** [comment]
We could load into the memory smaller chunks at a time, and hash the resulting `Vector[Long]`.
If there's a 1GB _resource_ file, I don't know if it's worth content hashing the whole thing.

**Comment by eatkins** [comment]
Yeah, I had that thought too about size gating the content hashing. One thing that we could do is that instead of just wrapping with time stamps, we could wrap with time stamp and size. If the size is sufficiently big, we could skip the content hashing. The one minor issue there is that `Files.readAttributes` returns the size and last modified but the last modified time only has second precision on jdk < 10. If we wanted millisecond precision we have to double stat the file for older jdks.

I actually could see an argument for skipping content hashing entirely and always just using timestamp and size. There would of course be pathological cases where we'd under compile but I'd guess that something like 99% of use cases would work correctly without content hashing.

**Comment by eed3si9n** [comment]
For text files it's easy to have the same size just by fixing some typo. Also time is almost meaningless when people start sharing Zinc state across CI jobs or machines. So for Zinc purposes farm hash is a good fit.
Resource file on the other hand, is not tracked by Zinc afaik. This stamping is for watch purpose, I'm guessing?

**Comment by eatkins** [comment]
Right, I am thinking about the case where there is no zinc sharing across time stamps and/or the user is developing locally. The (Time, Size) tuple should be correct on a local machine the vast majority of the time. Yeah, I think the stamping is for watch purposes though I'm not 100% sure from git blame. I think the issue could probably be fixed by setting `unmanagedResources / inputFileStamper := sbt.nio.FileStamper.LastModified`.

@vincenzobaz does your build work if you set `Compile / unmanagedResources / inputFileStamper := sbt.nio.FileStamper.LastModified`.

**Comment by eatkins** [comment]
There was a typo in the initial setting in the comment above^

**Comment by vincenzobaz** [comment]
Thank you for the very quick responses!
@eatkins that works half way unfortunately as sbt hangs with `| => errors / Compile / packageBin 400s`  which is similar to the behavior that I had obtained by downgrading sbt to 1.3.6

For me it is not a problem, I can move the files to another directory, I had opened the issue mainly because at the beginning I was puzzled by the error message which I think could be more user firendly

**Comment by dodhaim** [comment]
I have the same problem when I'm trying to build the projects at the CI.
my Resources folder is about 20g and I need all of it.
The project passes the tests when the files in the folder are under 2 g, but I want to run my tests over larger file (~16g).
I have tried **Everything!!!** and nothing works.

**Comment by strokyl** [comment]
Same issue for me with sbt 1.5.3 with a 7.5go resources files

**Comment by Friendseeker** [comment]
Fixed by https://github.com/sbt/zinc/pull/1018

**Comment by Friendseeker** [comment]
Actually still need to check if `farmHash` is used elsewhere in sbt source code. Maybe need to port Zinc fix here too.

**Comment by Friendseeker** [comment]
Yep it is fixed by https://github.com/sbt/zinc/pull/1018. sbt does not directly call `farmHash` against a large byte array.
