### ISSUE TITLE
[1.4.3] watch aborts with TimeoutException

### ISSUE THREAD

**Issue by ritschwumm** [sbt/sbt#6095]
## steps

having installed sbt-revolver, i run `~myProject/reStart` inside the jEdit console (TERM=dumb).

## problem

when i do changes to one of my files, restart is triggered and immediately aborts with an exception like this
```
info] Build triggered by <file>. Running '<myProject>/reStart'.
Watch caught unexpected error:
java.util.concurrent.TimeoutException: Unable to join thread Thread[sbt-watch-console0-handle-input-1,5,main] after 1 second
	at sbt.internal.util.JoinThread$ThreadOps$.joinFor$extension(JoinThread.scala:27)
	at sbt.internal.Continuous$WatchExecutor$FutureImpl.cancel(Continuous.scala:717)
	at sbt.internal.Continuous$.$anonfun$combineInputAndFileEvents$1(Continuous.scala:866)
	at sbt.internal.Continuous$.$anonfun$combineInputAndFileEvents$1$adapted(Continuous.scala:821)
	at sbt.nio.Watch$.safeNextAction$1(Watch.scala:375)
	at sbt.nio.Watch$.next$1(Watch.scala:382)
	at sbt.nio.Watch$.impl$1(Watch.scala:391)
	at sbt.nio.Watch$.apply(Watch.scala:409)
	at sbt.internal.ContinuousCommands$WatchUITask.sbt$internal$ContinuousCommands$WatchUITask$$$anonfun$reader$1(Continuous.scala:1297)
	at sbt.internal.ContinuousCommands$WatchUITask$$anonfun$reader$lzycompute$1.readLine(Continuous.scala:1289)
	at sbt.internal.ui.UITask.impl$1(UITask.scala:34)
	at sbt.internal.ui.UITask.run(UITask.scala:37)
	at sbt.internal.ui.UITask.run$(UITask.scala:32)
	at sbt.internal.ContinuousCommands$WatchUITask.run(Continuous.scala:1283)
	at sbt.internal.ui.UserThread$$anon$1.run(UserThread.scala:38)
```

## expectation

this should work as it did in sbt 1.4.2 - compile and restart my code.

**Comment by eed3si9n** [comment]
https://github.com/sbt/sbt/pull/6071 might be related?

**Comment by eed3si9n** [comment]
I think this will be fixed in next sbt - https://github.com/sbt/sbt/pull/6107
