### ISSUE TITLE
sbt fails with FileAlreadyExistsException

### ISSUE THREAD

**Issue by sideeffffect** [sbt/sbt#6098]
_Is it possible, this is related to "unusual" filesystem causing issues for sbt as in https://github.com/sbt/sbt/issues/6101 ?_

But it shouldn't fail; if the directory exists, it should just create the subdirectories that don't exist yet and move on.
The stack trace looks like this.

```
java.io.IOException: Could not create directory /projects/console-scala-simple/example/target/streams/compile/bloopGenerate/_global/streams: java.nio.file.FileAlreadyExistsException: /projects/console-scala-simple/example/target
        at sbt.io.IO$.createDirectory(IO.scala:337)
        at sbt.io.IO$.$anonfun$touch$2(IO.scala:315)
        at sbt.internal.io.Retry$.apply$mVc$sp(Retry.scala:40)
        at sbt.internal.io.Retry$.apply$mVc$sp(Retry.scala:23)
        at sbt.io.IO$.touch(IO.scala:313)
        at sbt.std.Streams$$anon$2$$anon$3.make(Streams.scala:197)
        at sbt.std.Streams$$anon$2$$anon$3.text(Streams.scala:164)
        at sbt.std.Streams$$anon$2$$anon$3.log(Streams.scala:185)
        at sbt.std.TaskStreams.log(Streams.scala:72)
        at sbt.std.TaskStreams.log$(Streams.scala:72)
        at sbt.std.Streams$$anon$2$$anon$3.log$lzycompute(Streams.scala:144)
        at sbt.std.Streams$$anon$2$$anon$3.log(Streams.scala:144)
        at sbt.EvaluateTask$.log$1(EvaluateTask.scala:360)
        at sbt.EvaluateTask$.$anonfun$logIncomplete$2(EvaluateTask.scala:364)
        at sbt.EvaluateTask$.$anonfun$logIncomplete$2$adapted(EvaluateTask.scala:359)
        at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:924)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:923)
        at sbt.EvaluateTask$.logIncomplete(EvaluateTask.scala:359)
        at sbt.EvaluateTask$.logIncResult(EvaluateTask.scala:350)
        at sbt.EvaluateTask$.run$1(EvaluateTask.scala:481)
        at sbt.EvaluateTask$.runTask(EvaluateTask.scala:498)
        at sbt.internal.Aggregation$.$anonfun$timedRun$4(Aggregation.scala:101)
        at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:388)
        at sbt.internal.Aggregation$.timedRun(Aggregation.scala:99)
        at sbt.internal.Aggregation$.runTasks(Aggregation.scala:113)
        at sbt.internal.Aggregation$.$anonfun$applyTasks$1(Aggregation.scala:68)
        at sbt.Command$.$anonfun$applyEffect$2(Command.scala:145)
        at sbt.internal.Aggregation$.$anonfun$evaluatingParser$11(Aggregation.scala:227)
        at sbt.internal.Act$.$anonfun$actParser0$4(Act.scala:436)
        at sbt.Command$.process(Command.scala:189)
        at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:245)
        at scala.Option.getOrElse(Option.scala:189)
        at sbt.MainLoop$.process$1(MainLoop.scala:245)
        at sbt.MainLoop$.processCommand(MainLoop.scala:269)
        at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:162)
        at sbt.State$StateOpsImpl$.runCmd$1(State.scala:289)
        at sbt.State$StateOpsImpl$.process$extension(State.scala:325)
        at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:162)
        at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
        at sbt.MainLoop$.next(MainLoop.scala:162)
        at sbt.MainLoop$.run(MainLoop.scala:143)
        at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:118)
        at sbt.io.Using.apply(Using.scala:27)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:111)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:65)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:50)
        at sbt.MainLoop$.runLogged(MainLoop.scala:41)
        at sbt.StandardMain$.runManaged(Main.scala:188)
        at sbt.xMain$.$anonfun$run$6(Main.scala:100)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withIn(Console.scala:230)
        at sbt.internal.util.Terminal$.withIn(Terminal.scala:553)
        at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:343)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withOut(Console.scala:167)
        at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:543)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withErr(Console.scala:196)
        at sbt.internal.util.Terminal$.withOut(Terminal.scala:543)
        at sbt.internal.util.Terminal$.withStreams(Terminal.scala:343)
        at sbt.xMain$.run(Main.scala:83)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:83)
        at sbt.xMain.run(Main.scala:46)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:130)
        at xsbt.boot.Launch$.run(Launch.scala:111)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
        at xsbt.boot.Launch$.launch(Launch.scala:119)
        at xsbt.boot.Launch$.apply(Launch.scala:20)
        at xsbt.boot.Boot$.runImpl(Boot.scala:56)
        at xsbt.boot.Boot$.main(Boot.scala:18)
        at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.nio.file.FileAlreadyExistsException: /projects/console-scala-simple/example/target
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
        at java.base/java.nio.file.Files.createDirectory(Files.java:689)
        at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:796)
        at java.base/java.nio.file.Files.createDirectories(Files.java:782)
        at sbt.io.IO$.$anonfun$createDirectory$1(IO.scala:333)
        at sbt.internal.io.Retry$.apply(Retry.scala:40)
        at sbt.internal.io.Retry$.apply(Retry.scala:23)
        at sbt.io.IO$.createDirectory(IO.scala:335)
        ... 76 more
[error] java.io.IOException: Could not create directory /projects/console-scala-simple/example/target/streams/compile/bloopGenerate/_global/streams: java.nio.file.FileAlreadyExistsException: /projects/console-scala-simple/example/target
```

**Comment by sideeffffect** [comment]
Similar bug
/cc @eatkins

**Comment by sideeffffect** [comment]
Similar bug https://github.com/sbt/sbt/issues/5970
/cc @eatkins

**Comment by sideeffffect** [comment]
other, similar error
```
java.io.IOException: Could not create directory /projects/console-scala-simple/.bloop/example/scala-2.13/it-classes: java.nio.file.FileAlreadyExistsException: /projects/console-scala-simple/.bloop/example/scala-2.13
        at sbt.io.IO$.createDirectory(IO.scala:337)
        at bloop.integrations.sbt.BloopDefaults$.$anonfun$generateBloopProductDirectories$1(SbtBloop.scala:335)
        at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:228)
        at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:170)
        at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
        at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:99)
        at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.nio.file.FileAlreadyExistsException: /projects/console-scala-simple/.bloop/example/scala-2.13
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
        at java.base/java.nio.file.Files.createDirectory(Files.java:689)
        at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:796)
        at java.base/java.nio.file.Files.createDirectories(Files.java:782)
        at sbt.io.IO$.$anonfun$createDirectory$1(IO.scala:333)
        at sbt.internal.io.Retry$.apply(Retry.scala:40)
        at sbt.internal.io.Retry$.apply(Retry.scala:23)
        at sbt.io.IO$.createDirectory(IO.scala:335)
        ... 9 more
[error] java.io.IOException: Could not create directory /projects/console-scala-simple/.bloop/example/scala-2.13/it-classes: java.nio.file.FileAlreadyExistsException: /projects/console-scala-simple/.bloop/example/scala-2.13
```

**Comment by sideeffffect** [comment]
```
java.io.IOException: Could not create directory /projects/console-scala-simple/project/.bloop/console-scala-simple-build/scala-2.12/sbt-1.0/test-classes: java.nio.file.FileAlreadyExistsException: /projects/console-scala-simple/project/.bloop/console-scala-simple-build
        at sbt.io.IO$.createDirectory(IO.scala:337)
        at bloop.integrations.sbt.BloopDefaults$.$anonfun$generateBloopProductDirectories$1(SbtBloop.scala:335)
        at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:228)
        at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:170)
        at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
        at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:99)
        at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.nio.file.FileAlreadyExistsException: /projects/console-scala-simple/project/.bloop/console-scala-simple-build
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
        at java.base/java.nio.file.Files.createDirectory(Files.java:689)
        at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:796)
        at java.base/java.nio.file.Files.createDirectories(Files.java:782)
        at sbt.io.IO$.$anonfun$createDirectory$1(IO.scala:333)
        at sbt.internal.io.Retry$.apply(Retry.scala:40)
        at sbt.internal.io.Retry$.apply(Retry.scala:23)
        at sbt.io.IO$.createDirectory(IO.scala:335)
        ... 9 more
[error] java.io.IOException: Could not create directory /projects/console-scala-simple/project/.bloop/console-scala-simple-build/scala-2.12/sbt-1.0/test-classes: java.nio.file.FileAlreadyExistsException: /projects/console-scala-simple/project/.bloop/console-scala-simple-build
```
```
/projects/console-scala-simple $ ls -alh /projects/console-scala-simple/project/.bloop/console-scala-simple-build
total 8K     
drwxr-xr-x    2 user     root        4.0K Nov 17 02:32 .
drwxr-xr-x    3 user     root        4.0K Nov 17 02:32 ..
```

**Comment by eed3si9n** [comment]
Please follow the bug reporting guideline - https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md#what-to-report

**Comment by eatkins** [comment]
I can't debug this. It looks like various methods in `Files` such as `Files.createDirectories` and `Files.isDirectory` do not work as expected on this file system. This will require outside help for a fix.
