### ISSUE TITLE
Pipelining crashes with custom Predef

### ISSUE THREAD

**Issue by japgolly** [sbt/sbt#6117]
I added `ThisBuild / usePipelining := true` and gave it a try with sbt 1.4.3 and it crashes.

```
[error] ## Exception when compiling 129 sources to /tmp/shipreq.sbt/webapp-member/jvm/target/scala-2.13/classes
[error] java.lang.NoClassDefFoundError: shipreq/Predef$
[error] shipreq.webapp.member.project.util.GenericDataMacroImpls.$anonfun$localNameToExpr$1(GenericDataMacros.scala:55)
[error] shipreq.webapp.member.project.util.GenericDataMacroImpls.$anonfun$localNameToExpr$1$adapted(GenericDataMacros.scala:55)
[error] scala.Option.filter(Option.scala:319)
[error] shipreq.webapp.member.project.util.GenericDataMacroImpls.localNameToExpr(GenericDataMacros.scala:55)
[error] shipreq.webapp.member.project.util.GenericDataMacroImpls.implAllValues(GenericDataMacros.scala:65)
[error] shipreq.webapp.member.project.util.GenericDataMacroImpls.quietAllValues(GenericDataMacros.scala:61)
[error] java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error] scala.reflect.macros.runtime.JavaReflectionRuntimes$JavaReflectionResolvers.$anonfun$resolveJavaReflectionRuntime$5(JavaReflectionRuntimes.scala:45)
[error] scala.tools.nsc.typechecker.Macros.macroExpandWithRuntime(Macros.scala:758)
[error] scala.tools.nsc.typechecker.Macros.macroExpandWithRuntime$(Macros.scala:734)
[error] scala.tools.nsc.Global$$anon$5.macroExpandWithRuntime(Global.scala:484)
[error] scala.tools.nsc.typechecker.Macros$MacroExpander.$anonfun$expand$1(Macros.scala:564)
[error] scala.tools.nsc.Global.withInfoLevel(Global.scala:228)
[error] scala.tools.nsc.typechecker.Macros$MacroExpander.expand(Macros.scala:557)
[error] scala.tools.nsc.typechecker.Macros$MacroExpander.apply(Macros.scala:544)
[error] scala.tools.nsc.typechecker.Macros.standardMacroExpand(Macros.scala:719)
[error] scala.tools.nsc.typechecker.Macros.standardMacroExpand$(Macros.scala:717)
[error] scala.tools.nsc.Global$$anon$5.standardMacroExpand(Global.scala:484)
[error] scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$10.default(AnalyzerPlugins.scala:456)
[error] scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$10.default(AnalyzerPlugins.scala:453)
[error] scala.tools.nsc.typechecker.AnalyzerPlugins.invoke(AnalyzerPlugins.scala:410)
[error] scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand(AnalyzerPlugins.scala:453)
[error] scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand$(AnalyzerPlugins.scala:453)
[error] scala.tools.nsc.Global$$anon$5.pluginsMacroExpand(Global.scala:484)
[error] scala.tools.nsc.typechecker.Macros.macroExpand(Macros.scala:708)
[error] scala.tools.nsc.typechecker.Macros.macroExpand$(Macros.scala:701)
[error] scala.tools.nsc.Global$$anon$5.macroExpand(Global.scala:484)
[error] scala.tools.nsc.typechecker.Typers$Typer.vanillaAdapt$1(Typers.scala:1217)
[error] scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1285)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5988)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:3415)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedArgs$1(Typers.scala:3420)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedArgs(Typers.scala:3420)
[error] scala.tools.nsc.typechecker.Typers$Typer.tryTypedArgs$1(Typers.scala:4887)
[error] scala.tools.nsc.typechecker.Typers$Typer.onError$2(Typers.scala:4948)
[error] scala.tools.nsc.typechecker.Typers$Typer.tryTypedApply$1(Typers.scala:4967)
[error] scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:5049)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:5060)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5916)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5973)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:3415)
[error] scala.tools.nsc.typechecker.PatternTypers$PatternTyper.typedArgWithFormal$1(PatternTypers.scala:117)
[error] scala.tools.nsc.typechecker.PatternTypers$PatternTyper.$anonfun$typedArgsForFormals$4(PatternTypers.scala:131)
[error] scala.tools.nsc.typechecker.PatternTypers$PatternTyper.typedArgsForFormals(PatternTypers.scala:131)
[error] scala.tools.nsc.typechecker.PatternTypers$PatternTyper.typedArgsForFormals$(PatternTypers.scala:112)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedArgsForFormals(Typers.scala:203)
[error] scala.tools.nsc.typechecker.Typers$Typer.handleMonomorphicCall$1(Typers.scala:3743)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$doTypedApply$26(Typers.scala:3790)
[error] scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3790)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$27(Typers.scala:4965)
[error] scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:706)
[error] scala.tools.nsc.typechecker.Typers$Typer.tryTypedApply$1(Typers.scala:4965)
[error] scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:5049)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:5060)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5916)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5973)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:6051)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$8(Typers.scala:3397)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3397)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2558)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:5891)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5926)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5973)
[error] scala.tools.nsc.typechecker.Typers$Typer.computeType(Typers.scala:6062)
[error] scala.tools.nsc.typechecker.Namers$Namer.assignTypeToTree(Namers.scala:1128)
[error] scala.tools.nsc.typechecker.Namers$Namer.methodSig(Namers.scala:1450)
[error] scala.tools.nsc.typechecker.Namers$Namer.memberSig(Namers.scala:1913)
[error] scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1878)
[error] scala.tools.nsc.typechecker.Namers$Namer$MonoTypeCompleter.completeImpl(Namers.scala:875)
[error] scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:2062)
[error] scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:2060)
[error] scala.tools.nsc.typechecker.Namers$TypeCompleterBase.complete(Namers.scala:2055)
[error] scala.reflect.internal.Symbols$Symbol.completeInfo(Symbols.scala:1546)
[error] scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1518)
[error] scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1707)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5573)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5973)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:6051)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$8(Typers.scala:3397)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3397)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2058)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1889)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5882)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5973)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:6051)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$8(Typers.scala:3397)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3397)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2058)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1934)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5883)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5973)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:6051)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$8(Typers.scala:3397)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3397)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5582)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5885)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5973)
[error] scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.apply(Analyzer.scala:117)
[error] scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:454)
[error] scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.run(Analyzer.scala:105)
[error] scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1515)
[error] scala.tools.nsc.Global$Run.compileUnits(Global.scala:1499)
[error] scala.tools.nsc.Global$Run.compileSources(Global.scala:1491)
[error] scala.tools.nsc.Global$Run.compileFiles(Global.scala:1605)
[error] xsbt.CachedCompiler0.run(CompilerBridge.scala:163)
[error] xsbt.CachedCompiler0.run(CompilerBridge.scala:134)
[error] xsbt.CompilerBridge.run(CompilerBridge.scala:39)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:92)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:186)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:241)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:176)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:157)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:157)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:194)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:573)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:573)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:173)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:171)
[error] sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:458)
[error] sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:261)
[error] sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:413)
[error] sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:498)
[error] sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:400)
[error] sbt.internal.inc.Incremental$.apply(Incremental.scala:165)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:573)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:491)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2176)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2133)
[error] sbt.internal.io.Retry$.apply(Retry.scala:40)
[error] sbt.internal.io.Retry$.apply(Retry.scala:23)
[error] sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2129)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] sbt.Execute.work(Execute.scala:291)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] java.base/java.lang.Thread.run(Thread.java:834)
[error]            
java.util.concurrent.CancellationException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:121)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at sbt.ConcurrentRestrictions$$anon$4.take(ConcurrentRestrictions.scala:309)
	at sbt.Execute.next$1(Execute.scala:117)
	at sbt.Execute.processAll(Execute.scala:127)
	at sbt.Execute.runKeep(Execute.scala:95)
	at sbt.EvaluateTask$.liftedTree1$1(EvaluateTask.scala:476)
	at sbt.EvaluateTask$.run$1(EvaluateTask.scala:475)
	at sbt.EvaluateTask$.runTask(EvaluateTask.scala:498)
	at sbt.internal.Aggregation$.$anonfun$timedRun$4(Aggregation.scala:101)
	at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:388)
	at sbt.internal.Aggregation$.timedRun(Aggregation.scala:99)
	at sbt.internal.Aggregation$.runTasks(Aggregation.scala:113)
	at sbt.internal.Aggregation$.$anonfun$applyTasks$1(Aggregation.scala:68)
	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:145)
	at sbt.internal.Aggregation$.$anonfun$evaluatingParser$11(Aggregation.scala:227)
	at sbt.internal.Act$.$anonfun$actParser0$4(Act.scala:436)
	at sbt.Command$.process(Command.scala:189)
	at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:245)
	at scala.Option.getOrElse(Option.scala:189)
	at sbt.MainLoop$.process$1(MainLoop.scala:245)
	at sbt.MainLoop$.processCommand(MainLoop.scala:269)
	at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:162)
	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:289)
	at sbt.State$StateOpsImpl$.process$extension(State.scala:325)
	at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:162)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.MainLoop$.next(MainLoop.scala:162)
	at sbt.MainLoop$.run(MainLoop.scala:143)
	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:118)
	at sbt.io.Using.apply(Using.scala:27)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:111)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:65)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:50)
	at sbt.MainLoop$.runLogged(MainLoop.scala:41)
	at sbt.StandardMain$.runManaged(Main.scala:188)
	at sbt.xMain$.$anonfun$run$6(Main.scala:100)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withIn(Console.scala:230)
	at sbt.internal.util.Terminal$.withIn(Terminal.scala:553)
	at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:343)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withOut(Console.scala:167)
	at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:543)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withErr(Console.scala:196)
	at sbt.internal.util.Terminal$.withOut(Terminal.scala:543)
	at sbt.internal.util.Terminal$.withStreams(Terminal.scala:343)
	at sbt.xMain$.run(Main.scala:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:83)
	at sbt.xMain.run(Main.scala:46)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:131)
	at xsbt.boot.Launch$.run(Launch.scala:111)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
	at xsbt.boot.Launch$.launch(Launch.scala:120)
	at xsbt.boot.Launch$.apply(Launch.scala:20)
	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
	at xsbt.boot.Boot$.main(Boot.scala:18)
	at xsbt.boot.Boot.main(Boot.scala)
```

Unfortunately my project (https://shipreq.com :tada:) is closed-source so I can't share the full build.

I presume it's because pipelining doesn't take custom predefs into account when building it's dependency graph. In my case I have:

```scala
  lazy val basePredefJvm = basePredef.jvm
  lazy val basePredefJs  = basePredef.js
  lazy val basePredef =
    crossProject(JSPlatform, JVMPlatform)
      .in(file("base-predef"))
      .configureJvm(Common.jvmSettings)
      .configureJs(Common.jsSettings(NoTests))
      .settings(
        scalacOptions ~= (_.filterNot(_.startsWith("-Yimports:")) :+ "-Yimports:scala"),
        test := (()))
```

And all my other modules have `-Yimports:java.lang,scala,shipreq.Predef` in their `scalacOptions`.

**Comment by eed3si9n** [comment]
You might need to pepper around 

```scala
exportPipelining := false
```

to some of the subprojects that provide your macros.

**Comment by eed3si9n** [comment]
I am closing this due to inactivity. Probably a won't-fix scenario.
