### ISSUE TITLE
After upgrading to sbt 1.4.3 compilation of scalameta for 2.11.12 fails

### ISSUE THREAD

**Issue by kpbochenek** [sbt/sbt#6124]
## steps

Changing only version of sbt from `1.3.13` to `1.4.3` in PR: https://github.com/scalameta/scalameta/pull/2167/files

Everything works for scala 2.12.x and 2.13.x

## problem

Compilation fails

## expectation

Compilation works

## notes

Error:
```
java.lang.ClassCastException: scala.reflect.internal.Symbols$NoSymbol cannot be cast to scala.reflect.internal.Symbols$ClassSymbol
	at scala.reflect.internal.Symbols$Symbol.newLinkedModule(Symbols.scala:321)
	at scala.reflect.internal.pickling.UnPickler$Scan.readSymbol(UnPickler.scala:364)
	at scala.reflect.internal.pickling.UnPickler$Scan.run(UnPickler.scala:87)
	at scala.reflect.internal.pickling.UnPickler.unpickle(UnPickler.scala:38)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.scala$tools$nsc$symtab$classfile$ClassfileParser$$parseAttribute$1(ClassfileParser.scala:839)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.parseAttributes(ClassfileParser.scala:1016)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.parseClass(ClassfileParser.scala:502)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.parse(ClassfileParser.scala:139)
	at scala.tools.nsc.symtab.SymbolLoaders$ClassfileLoader$$anonfun$doComplete$2.apply$mcV$sp(SymbolLoaders.scala:347)
	at scala.tools.nsc.symtab.SymbolLoaders$ClassfileLoader$$anonfun$doComplete$2.apply(SymbolLoaders.scala:347)
	at scala.tools.nsc.symtab.SymbolLoaders$ClassfileLoader$$anonfun$doComplete$2.apply(SymbolLoaders.scala:347)
	at scala.reflect.internal.SymbolTable.enteringPhase(SymbolTable.scala:235)
	at scala.tools.nsc.symtab.SymbolLoaders$ClassfileLoader.doComplete(SymbolLoaders.scala:347)
	at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.complete(SymbolLoaders.scala:211)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1535)
	at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1680)
	at xsbt.Dependency$DependencyProcessor.processDependency(Dependency.scala:178)
	at xsbt.Dependency$DependencyProcessor$$anonfun$2.apply(Dependency.scala:107)
	at xsbt.Dependency$DependencyProcessor$$anonfun$2.apply(Dependency.scala:107)
	at xsbt.Dependency$DependencyProcessor.processTopLevelImportDependency(Dependency.scala:97)
	at xsbt.Dependency$DependencyTraverser.addTopLevelImportDependency(Dependency.scala:300)
	at xsbt.Dependency$DependencyTraverser.xsbt$Dependency$DependencyTraverser$$addDependency(Dependency.scala:318)
	at xsbt.Dependency$DependencyTraverser$$anonfun$traverse$1.apply(Dependency.scala:398)
	at xsbt.Dependency$DependencyTraverser$$anonfun$traverse$1.apply(Dependency.scala:389)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at xsbt.Dependency$DependencyTraverser.traverse(Dependency.scala:389)
	at xsbt.Dependency$DependencyTraverser.traverse(Dependency.scala:206)
	at scala.reflect.api.Trees$Traverser$$anonfun$traverseStats$1$$anonfun$apply$1.apply$mcV$sp(Trees.scala:2498)
	at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2507)
	at scala.reflect.api.Trees$Traverser.traverseStats(Trees.scala:2497)
	at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1326)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
	at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)
	at xsbt.Dependency$DependencyTraverser.traverse(Dependency.scala:467)
	at xsbt.Dependency$DependencyPhase.apply(Dependency.scala:68)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply$mcV$sp(Global.scala:467)
	at scala.tools.nsc.Global$GlobalPhase.withCurrentUnit(Global.scala:458)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:467)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:425)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:425)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:425)
	at xsbt.Dependency$DependencyPhase.run(Dependency.scala:49)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1528)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1513)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1508)
	at scala.tools.nsc.Global$Run.compileFiles(Global.scala:1598)
	at xsbt.CachedCompiler0.run(CompilerBridge.scala:163)
	at xsbt.CachedCompiler0.run(CompilerBridge.scala:134)
	at xsbt.CompilerBridge.run(CompilerBridge.scala:39)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:92)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:186)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:241)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:176)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:157)
	at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:157)
	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:204)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:573)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:573)
	at sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:173)
	at sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:171)
	at sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:458)
	at sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:261)
	at sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:413)
	at sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:498)
	at sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:400)
	at sbt.internal.inc.Incremental$.apply(Incremental.scala:165)
	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:573)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:491)
	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2176)
	at sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2133)
	at sbt.internal.io.Retry$.apply(Retry.scala:40)
	at sbt.internal.io.Retry$.apply(Retry.scala:23)
	at sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2129)
	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.Execute.work(Execute.scala:291)
	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] error while loading SkipWindows, class file '/home/runner/work/scalameta/scalameta/tests/jvm/target/scala-2.11/classes/scala/meta/tests/SkipWindows.class' is broken
[error] (class java.lang.RuntimeException/error reading Scala signature of SkipWindows.class: scala.reflect.internal.Symbols$NoSymbol cannot be cast to scala.reflect.internal.Symbols$ClassSymbol)
[error] one error found
```

**Comment by tgodzik** [comment]
The SkipWindows class is very simple:
```scala
package scala.meta.tests

import munit.Tag

object SkipWindows extends Tag("SkipWindows")

```

It's an munit tag. This might be reproducible using just that and 2.11.12. Let me know how I can help! I think this could some of the recent zinc changes, but I have no idea where to even look.

**Comment by eed3si9n** [comment]
> but I have no idea where to even look.

A good place to start would be git blame on the erring line 
https://github.com/sbt/zinc/blame/757a0ea106d55752f47246e5436856d29f188f41/internal/compiler-bridge/src/main/scala/xsbt/Dependency.scala#L178

In this case it could probably be solve by doing something like try-catch and let it return `None`.

**Comment by adpi2** [comment]
I tried to reproduce and I have found that there is another `SkipWindows` symbol in the same package:

```scala
package scala.meta

package object tests {
  val Slow = new munit.Tag("Slow")
  val SkipWindows = new munit.Tag("SkipWindows")
}
```

So I am not sure it is worth fixing in Zinc

**Comment by adpi2** [comment]
New PR #2185

**Comment by adpi2** [comment]
I confirm that Zinc is happier without the duplicated `SkipWindows` symbol: https://github.com/scalameta/scalameta/pull/2185

**Comment by tgodzik** [comment]
I think we can close it. No idea why the tag was duplicated :O
