### ISSUE TITLE
RejectedExecutionException on any CTRL+C in SBT 1.4.x

### ISSUE THREAD

**Issue by KarelCemus** [sbt/sbt#6192]
## steps

Start any task (compile, run, test, ...) and then interrupt it with CTRL+C

## problem

```
[warn] Canceling execution...
java.util.concurrent.RejectedExecutionException
	at sbt.ConcurrentRestrictions$$anon$4.submit(ConcurrentRestrictions.scala:242)
	at sbt.Execute.submit(Execute.scala:282)
	at sbt.Execute.ready(Execute.scala:262)
	at sbt.Execute.notifyDone(Execute.scala:201)
	at sbt.Execute.$anonfun$retire$2(Execute.scala:172)
	at sbt.Execute.$anonfun$retire$2$adapted(Execute.scala:171)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at sbt.Execute.retire(Execute.scala:171)
	at sbt.Execute.$anonfun$work$2(Execute.scala:299)
	at sbt.Execute$$anon$1.process(Execute.scala:27)
	at sbt.Execute.next$1(Execute.scala:117)
	at sbt.Execute.processAll(Execute.scala:127)
	at sbt.Execute.runKeep(Execute.scala:95)
	at sbt.EvaluateTask$.liftedTree1$1(EvaluateTask.scala:472)
	at sbt.EvaluateTask$.run$1(EvaluateTask.scala:471)
	at sbt.EvaluateTask$.runTask(EvaluateTask.scala:494)
	at sbt.internal.Aggregation$.$anonfun$timedRun$4(Aggregation.scala:101)
	at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:388)
	at sbt.internal.Aggregation$.timedRun(Aggregation.scala:99)
	at sbt.internal.Aggregation$.runTasks(Aggregation.scala:113)
	at sbt.internal.Aggregation$.$anonfun$applyDynamicTasks$4(Aggregation.scala:181)
	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:145)
	at sbt.internal.Act$.$anonfun$actParser0$4(Act.scala:436)
	at sbt.Command$.process(Command.scala:189)
	at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:245)
	at scala.Option.getOrElse(Option.scala:189)
	at sbt.MainLoop$.process$1(MainLoop.scala:245)
	at sbt.MainLoop$.processCommand(MainLoop.scala:269)
	at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:162)
	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:286)
	at sbt.State$StateOpsImpl$.process$extension(State.scala:322)
	at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:162)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.MainLoop$.next(MainLoop.scala:162)
	at sbt.MainLoop$.run(MainLoop.scala:143)
	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:118)
	at sbt.io.Using.apply(Using.scala:27)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:111)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:65)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:50)
	at sbt.MainLoop$.runLogged(MainLoop.scala:41)
	at sbt.StandardMain$.runManaged(Main.scala:188)
	at sbt.xMain$.$anonfun$run$6(Main.scala:100)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withIn(Console.scala:230)
	at sbt.internal.util.Terminal$.withIn(Terminal.scala:540)
	at sbt.internal.util.Terminal$.$anonfun$withStreams$2(Terminal.scala:335)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withOut(Console.scala:167)
	at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:530)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withErr(Console.scala:196)
	at sbt.internal.util.Terminal$.withOut(Terminal.scala:530)
	at sbt.internal.util.Terminal$.withStreams(Terminal.scala:335)
	at sbt.xMain$.run(Main.scala:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:83)
	at sbt.xMain.run(Main.scala:46)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:130)
	at xsbt.boot.Launch$.run(Launch.scala:111)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
	at xsbt.boot.Launch$.launch(Launch.scala:119)
	at xsbt.boot.Launch$.apply(Launch.scala:20)
	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
	at xsbt.boot.Boot$.main(Boot.scala:18)
	at xsbt.boot.Boot.main(Boot.scala)
```

## expectation

"Silently" interrupt the task without any internal error.

## notes

- happens on all our working stations, Mac OS 10.15.5 and Windows 10 with WSL2
- does not happen with SBT 1.3.x, it works fine
- happens with 1.4.0 as well as with 1.4.4
- reproduced even with the most simple project - no project dependencies just one file with `Thread.sleep` and then CTRL+C in `run` task

**Comment by eatkins** [comment]
Yeah, this is annoying.
