### ISSUE TITLE
Exception in thread "sbt-socket-server" java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native, under emulated RISC-V env.

### ISSUE THREAD

**Issue by advancedwebdeveloper** [sbt/sbt#6215]
## steps

1. Follow all steps from https://en.opensuse.org/openSUSE:RISC-V
2. sudo zypper update && sudo install java-16-openjdk    java-16-openjdk-accessibility    java-16-openjdk-demo java-16-openjdk-devel  java-16-openjdk-headless java-16-openjdk-javadoc java-16-openjdk-jmods java-16-openjdk-src
3. Create an ordinary Linux user, define a password and login
4. Download https://github.com/sbt/sbt/releases/download/v1.4.5/sbt-1.4.5.zip and extract it

## problem

Looks like the shell is able to run - but the build servers is not able to start.
Citation from https://gist.github.com/advancedwebdeveloper/f4aee40215ef5bd61d96f18e1b2268a7 :

> Exception in thread "sbt-socket-server" java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
>         at com.sun.jna.Structure.setAlignType(Structure.java:280)
>         at com.sun.jna.Structure.<init>(Structure.java:197)
>         at com.sun.jna.Structure.<init>(Structure.java:193)
>         at com.sun.jna.Structure.<init>(Structure.java:180)
>         at com.sun.jna.Structure.<init>(Structure.java:172)
>         at org.scalasbt.ipcsocket.UnixDomainSocketLibrary$SockaddrUn.<init>(UnixDomainSocketLibrary.java:88)
>         at org.scalasbt.ipcsocket.JNAUnixDomainSocketLibraryProvider.maxSocketLength(UnixDomainSocketLibrary.java:273)
>         at org.scalasbt.ipcsocket.UnixDomainSocketLibraryProvider.maxSocketLength(UnixDomainSocketLibraryProvider.java:31)
>         at sbt.internal.server.Server$$anon$1$$anon$2.$anonfun$run$1(Server.scala:75)
>         at scala.util.Try$.apply(Try.scala:213)
>         at sbt.internal.server.Server$$anon$1$$anon$2.run(Server.scala:63)
> [warn] sbt server could not start in 10s

**Comment by eed3si9n** [comment]
I'm guessing that this is due to the fact that our [sbt/ipcsocket](https://github.com/sbt/ipcsocket) library doesn't support your CPU architecture.

Putting the following to your build.sbt can be a workaround:

```scala
Global / serverConnectionType := ConnectionType.Tcp // experimental
```

Note that this opens up the sbt server to the local network, so it should be done only in a trusted network.

**Comment by advancedwebdeveloper** [comment]
I assume that you are proposing to build https://github.com/sbt/ipcsocket/tree/master/jni , for rv64gc arch.?
Do you have any automated cross-compilation option, on x86_64 host, using a x86_64 build of Bazel?
There are two possible cross-compilers, to consider: https://github.com/riscv/riscv-gnu-toolchain and https://www.lowrisc.org/blog/2019/07/risc-v-llvm-backend-in-clang-llvm-9.0/ (I am using Clang 10, currently).

**Comment by advancedwebdeveloper** [comment]
It might be of help if you would share how C compilers is invoked by sbt, when this library is compiled on x86_64.

**Comment by eed3si9n** [comment]
> I assume that you are proposing to build https://github.com/sbt/ipcsocket/tree/master/jni , for rv64gc arch.?

I'm not really proposing anything.

JNI was added https://github.com/sbt/ipcsocket/pull/8, and afaik it calls gcc from `sbt buildLinux` task. In https://github.com/sbt/ipcsocket/pull/12 Ethan added AArch64 / ARM64 cross compilation.

**Comment by advancedwebdeveloper** [comment]
Aha! So it could be possible to submit a patch for cross-compile x86_64 -> rv64gc ?
Sounds interesting

**Comment by advancedwebdeveloper** [comment]
> oceanfish81@riscv:/home/oceanfish81/scala-native> sbt build
> [info] [launcher] getting org.scala-sbt sbt 1.4.4 (this may take some time)...
> downloading https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.4.4/sbt-1.4.4.jar ...
> :: loading settings :: url = jar:file:/home/oceanfish81/sbt/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
> downloading https://repo1.maven.org/maven2/org/scala-sbt/main_2.12/1.4.4/main_2.12-1.4.4.jar ...
> :: loading settings :: url = jar:file:/home/oceanfish81/sbt/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
> :: loading settings :: url = jar:file:/home/oceanfish81/sbt/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
> :: loading settings :: url = jar:file:/home/oceanfish81/sbt/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
> downloading https://repo1.maven.org/maven2/org/scala-sbt/logic_2.12/1.4.4/logic_2.12-1.4.4.jar ...
> downloading https://repo1.maven.org/maven2/org/scala-sbt/actions_2.12/1.4.4/actions_2.12-1.4.4.jar ...
> [SUCCESSFUL ] org.scala-sbt#logic_2.12;1.4.4!logic_2.12.jar (5951ms)
> (...it takes some time...)
> [SUCCESSFUL ] io.get-coursier#lm-coursier-shaded_2.12;2.0.3!lm-coursier-shaded_2.12.jar (268524ms)
> :: retrieving :: org.scala-sbt#boot-app
> confs: [default]
> 84 artifacts copied, 0 already retrieved
> java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/linux-riscv64/libjnidispatch.so) not found in resource path ([file:/home/oceanfish81/.sbt/boot/scala-2.12.12/org.scala-sbt/sbt/1.4.4/jna-platform-5.5.0.jar, file:/home/oceanfish81/.sbt/boot/scala-2.12.12/org.scala-sbt/sbt/1.4.4/jline-terminal-jna-3.16.0.jar, file:/home/oceanfish81/.sbt/boot/scala-2.12.12/org.scala-sbt/sbt/1.4.4/jline-2.14.7-sbt-5e51b9d4f9631ebfa29753ce4accc57808e7fd6b.jar, file:/home/oceanfish81/.sbt/boot/scala-2.12.12/org.scala-sbt/sbt/1.4.4/jansi-1.18.jar, file:/home/oceanfish81/.sbt/boot/scala-2.12.12/org.scala-sbt/sbt/1.4.4/jline-terminal-3.16.0-sbt-211a082ed6326908dc84ca017ce4430728f18a8a.jar, file:/home/oceanfish81/.sbt/boot/scala-2.12.12/org.scala-sbt/sbt/1.4.4/jline-terminal-jansi-3.16.0.jar, file:/home/oceanfish81/.sbt/boot/scala-2.12.12/org.scala-sbt/sbt/1.4.4/jna-5.5.0.jar])
> at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1032)
> at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
> at com.sun.jna.Native.<clinit>(Native.java:195)
> at org.scalasbt.ipcsocket.UnixDomainSocketLibrary.<clinit>(UnixDomainSocketLibrary.java:129)
> at org.scalasbt.ipcsocket.JNAUnixDomainSocketLibraryProvider.socket(UnixDomainSocketLibrary.java:165)
> at org.scalasbt.ipcsocket.UnixDomainServerSocket.<init>(UnixDomainServerSocket.java:109)
> at org.scalasbt.ipcsocket.UnixDomainServerSocket.<init>(UnixDomainServerSocket.java:87)
> at sbt.internal.BootServerSocket.newSocket(BootServerSocket.java:342)
> at sbt.internal.BootServerSocket.<init>(BootServerSocket.java:295)
> at sbt.xMain$.getSocketOrExit(Main.scala:120)
> at sbt.xMain$.run(Main.scala:75)
> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
> at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.base/java.lang.reflect.Method.invoke(Method.java:567)
> at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:83)
> at sbt.xMain.run(Main.scala:46)
> at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
> at xsbt.boot.Launch$.withContextLoader(Launch.scala:131)
> at xsbt.boot.Launch$.run(Launch.scala:111)
> at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
> at xsbt.boot.Launch$.launch(Launch.scala:120)
> at xsbt.boot.Launch$.apply(Launch.scala:20)
> at xsbt.boot.Boot$.runImpl(Boot.scala:56)
> at xsbt.boot.Boot$.main(Boot.scala:18)
> at xsbt.boot.Boot.main(Boot.scala)
> [error] [launcher] error during sbt launcher: **java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/linux-riscv64/libjnidispatch.so) not found in resource path** ([file:/home/oceanfish81/.sbt/boot/scala-2.12.12/org.scala-sbt/sbt/1.4.4/jna-platform-5.5.0.jar, file:/home/oceanfish81/.sbt/boot/scala-2.12.12/org.scala-sbt/sbt/1.4.4/jline-terminal-jna-3.16.0.jar, file:/home/oceanfish81/.sbt/boot/scala-2.12.12/or
