### ISSUE TITLE
ConcurrentModificationException while compiling with sbt 1.4.6

### ISSUE THREAD

**Issue by dotta** [sbt/sbt#6233]
## steps

The problem occurred while compiling the master branch of shapeless, but it seems like it's a race condition that could potetially happen on any other project. Just in case, it's the first time I encounter it.

## problem

```
java.util.ConcurrentModificationException
  | => cat java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
  | => cat java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:752)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:750)
	at scala.collection.convert.Wrappers$JMapWrapperLike$$anon$5.next(Wrappers.scala:288)
	at scala.collection.convert.Wrappers$JMapWrapperLike$$anon$5.next(Wrappers.scala:285)
	at scala.collection.MapLike$$anon$2.next(MapLike.scala:223)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:213)
	at sbt.internal.nio.Observers.onNext(Observers.scala:117)
	at sbt.internal.nio.FileTreeRepositoryImpl$$anon$1.$anonfun$onDelete$1(FileTreeRepositoryImpl.scala:63)
	at sbt.internal.nio.FileTreeRepositoryImpl$$anon$1.$anonfun$onDelete$1$adapted(FileTreeRepositoryImpl.scala:62)
	at scala.util.Either.foreach(Either.scala:270)
	at sbt.internal.nio.FileTreeRepositoryImpl$$anon$1.onDelete(FileTreeRepositoryImpl.scala:62)
	at com.swoval.files.CacheObservers.onDelete(CacheObservers.java:43)
	at com.swoval.files.FileCacheDirectoryTree$6.run(FileCacheDirectoryTree.java:512)
	at com.swoval.files.FileCacheDirectoryTree$4.run(FileCacheDirectoryTree.java:258)
	at com.swoval.files.Executor$PriorityRunnable.run(Executor.java:161)
	at com.swoval.files.Executor$ExecutorImpl$1.run(Executor.java:65)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

## expectation

no crash

## notes

The project was configured to use sbt 1.4.6.

**Comment by eed3si9n** [comment]
I am closing this due to inactivity, but if this is still relevant let us know with more details (reproduction steps etc).
