### ISSUE TITLE
Run task cancelation doesn't seem to work in the shell

### ISSUE THREAD

**Issue by djspiewak** [sbt/sbt#6242]
`fork := false`

Within the shell, invoking `run`, waiting a moment for the `main` to get rolling, and then hitting `ctrl-c` appears to not work at all. It *used* to `Thread#interrupt`, but no longer. To be clear, the `main` in question is sitting on a `CountDownLatch#await()`, and I've wrapped a `try/catch` around it to ensure I handle anything. What actually ends up happening is the following exception is printed to stderr (but *not* raised within my `try`/`catch`!):

```
java.util.concurrent.RejectedExecutionException
	at sbt.ConcurrentRestrictions$$anon$4.submit(ConcurrentRestrictions.scala:242)
	at sbt.Execute.submit(Execute.scala:282)
	at sbt.Execute.ready(Execute.scala:262)
	at sbt.Execute.notifyDone(Execute.scala:201)
	at sbt.Execute.$anonfun$retire$2(Execute.scala:172)
	at sbt.Execute.$anonfun$retire$2$adapted(Execute.scala:171)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at sbt.Execute.retire(Execute.scala:171)
	at sbt.Execute.$anonfun$work$2(Execute.scala:299)
	at sbt.Execute$$anon$1.process(Execute.scala:27)
	at sbt.Execute.next$1(Execute.scala:117)
	at sbt.Execute.processAll(Execute.scala:127)
	at sbt.Execute.runKeep(Execute.scala:95)
	at sbt.EvaluateTask$.liftedTree1$1(EvaluateTask.scala:476)
	at sbt.EvaluateTask$.run$1(EvaluateTask.scala:475)
	at sbt.EvaluateTask$.runTask(EvaluateTask.scala:498)
	at sbt.internal.Aggregation$.$anonfun$timedRun$4(Aggregation.scala:101)
	at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:388)
	at sbt.internal.Aggregation$.timedRun(Aggregation.scala:99)
	at sbt.internal.Aggregation$.runTasks(Aggregation.scala:113)
	at sbt.internal.Aggregation$.$anonfun$applyDynamicTasks$4(Aggregation.scala:181)
	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:145)
	at sbt.internal.Act$.$anonfun$actParser0$4(Act.scala:436)
	at sbt.Command$.process(Command.scala:189)
	at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:245)
	at scala.Option.getOrElse(Option.scala:189)
	at sbt.MainLoop$.process$1(MainLoop.scala:245)
	at sbt.MainLoop$.processCommand(MainLoop.scala:269)
	at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:162)
	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:289)
	at sbt.State$StateOpsImpl$.process$extension(State.scala:325)
	at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:162)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.MainLoop$.next(MainLoop.scala:162)
	at sbt.MainLoop$.run(MainLoop.scala:143)
	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:118)
	at sbt.io.Using.apply(Using.scala:27)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:111)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:65)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:50)
	at sbt.MainLoop$.runLogged(MainLoop.scala:41)
	at sbt.StandardMain$.runManaged(Main.scala:188)
	at sbt.xMain$.$anonfun$run$6(Main.scala:100)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withIn(Console.scala:230)
	at sbt.internal.util.Terminal$.withIn(Terminal.scala:553)
	at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:343)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withOut(Console.scala:167)
	at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:543)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withErr(Console.scala:196)
	at sbt.internal.util.Terminal$.withOut(Terminal.scala:543)
	at sbt.internal.util.Terminal$.withStreams(Terminal.scala:343)
	at sbt.xMain$.run(Main.scala:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:83)
	at sbt.xMain.run(Main.scala:46)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:131)
	at xsbt.boot.Launch$.run(Launch.scala:111)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
	at xsbt.boot.Launch$.launch(Launch.scala:120)
	at xsbt.boot.Launch$.apply(Launch.scala:20)
	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
	at xsbt.boot.Boot$.main(Boot.scala:18)
	at xsbt.boot.Boot.main(Boot.scala)
```

Sbt then returns to the shell and acts as if the process has been canceled, but if you do a thread dump, you'll see the `main` still stuck in `await()`. This also happens with `fork := true`, incidentally.

As far as I can tell, this appears to be sbt *itself* hitting a failure condition within the scheduling of the interrupts within `Execute`. Since the task is already canceled, subsequent executions hit the rejection exception shown above, including the step which would have interrupted the constituent threads from the `main`.

**Comment by djspiewak** [comment]
Duplicate of #6192

**Comment by djspiewak** [comment]
As @armanbilge pointed out, I was in err to close this as a duplicate. Reopening. This issue still manifests.

**Comment by Friendseeker** [comment]
Related issue: https://github.com/sbt/sbt/issues/6346

**Comment by Friendseeker** [comment]
Reproduction in https://github.com/typelevel/cats-effect/issues/2251#issuecomment-1536987989

Reproducible on sbt 1.0.1, not reproducible on sbt 1.0.0....

This will be a hell of a ride...


----

Reproduction setup with Java 8 & sbt 1.0.1
- build.sbt
```scala
cancelable in Global := true

lazy val root = (project in file("."))
  .settings(
    name := "test-cat-thread-interrupt",
    scalaVersion := "2.12.20",
    libraryDependencies ++= Seq(
      "org.typelevel" %% "cats-effect" % "3.5.6" // Use the latest Cats Effect version
    ),
  )
```

- Test.scala
```
import cats.effect._
import scala.concurrent.duration._
import java.nio.file.{Files, Paths, StandardOpenOption}

object Test extends IOApp.Simple {
  val filePath = Paths.get("test")

  import java.nio.file.{Files, Paths, StandardOpenOption}

  def writeToFile: Unit = {
    val line = "huh\n"
    Files.write(
      filePath,
      line.getBytes,
      StandardOpenOption.CREATE, // Create the file if it doesn't exist
      StandardOpenOption.APPEND // Append to the file
    )
  }

  def run = IO({println("huh"); writeToFile}).delayBy(10.seconds)
}
```

**Comment by Friendseeker** [comment]
Commits that might be of interest

https://github.com/sbt/sbt/commit/9003ed4fac471f872dc9670e7c7d087020c33761
https://github.com/sbt/sbt/commit/b6f2fe7654e40df76b144888182c0b3a9b0ff981

**Comment by Friendseeker** [comment]
Crosspost from https://discord.com/channels/632277896739946517/632277897448652844/1310893527252860948

> I managed to somewhat isolated the problem and identified a workaround. Here's the commit that caused the regression:
> 
> https://github.com/sbt/sbt/commit/b6f2fe7654e40df76b144888182c0b3a9b0ff981#diff-6d9589bfb3f1247d2eace99bab7e928590337680d1aebd087d9da286586fba77R507
> 
> So basically before that commit, sbt `run` calls `runTask`, which does not have the thread cleanup issue. After that commit, sbt `run` invokes `foregroundRunTask`, which has the cleanup issue.
> 
> The workaround, for now, is to use `fgRun` instead of run. `fgRun` calls runTask under the hood hence cleans up all threads properly.
> 
> I was looking into the drawback of `fgRun` and it seems that the only drawback is that `fgRun` blocks (uses sbt main thread to run the application), while `foregroundRunTask` places the run as a non-blocking background job.
