### ISSUE TITLE
sbt -timings leads to exception in shutdown hook

### ISSUE THREAD

**Issue by ahe-humio** [sbt/sbt#6253]
## steps

1. Create an empty directory.
2. cd into that directory.
3. run `sbt -timings help`.

sbt version in this project: 1.4.6
sbt script version: 1.4.6

Note: There's no build.sbt attached, since I can reproduce this problem in an empty directory.

## problem

Timings aren't printed when exiting, instead I see this message:

```
Caught exception running shutdown hook: java.nio.channels.ClosedChannelException
java.nio.channels.ClosedChannelException
	at sbt.internal.util.Terminal$TerminalImpl.throwIfClosed(Terminal.scala:904)
	at sbt.internal.util.Terminal$TerminalImpl$$anon$6.write(Terminal.scala:931)
	at sbt.internal.util.Terminal$LinePrintStream.println(Terminal.scala:454)
	at sbt.internal.util.ConsoleOut$$anon$2.println(ConsoleOut.scala:87)
	at sbt.internal.TaskTimings$$anon$1.log(TaskTimings.scala:32)
	at sbt.util.Logger.info(Logger.scala:26)
	at sbt.internal.TaskTimings.report(TaskTimings.scala:62)
	at sbt.internal.TaskTimings.$anonfun$new$1(TaskTimings.scala:41)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.internal.ShutdownHooks$.$anonfun$add$1(ShutdownHooks.scala:30)
	at sbt.internal.ShutdownHooks$.$anonfun$runAll$1(ShutdownHooks.scala:41)
	at java.base/java.util.concurrent.ConcurrentHashMap$ForEachValueTask.compute(ConcurrentHashMap.java:5019)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
	at java.base/java.util.concurrent.ConcurrentHashMap.forEachValue(ConcurrentHashMap.java:4050)
	at sbt.internal.ShutdownHooks$.sbt$internal$ShutdownHooks$$runAll(ShutdownHooks.scala:41)
	at sbt.internal.ShutdownHooks$.close(ShutdownHooks.scala:45)
	at sbt.xMain$.run(Main.scala:109)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:83)
	at sbt.xMain.run(Main.scala:46)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:131)
	at xsbt.boot.Launch$.run(Launch.scala:111)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
	at xsbt.boot.Launch$.launch(Launch.scala:120)
	at xsbt.boot.Launch$.apply(Launch.scala:20)
	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
	at xsbt.boot.Boot$.main(Boot.scala:18)
	at xsbt.boot.Boot.main(Boot.scala)
```

## expectation

I had expected to see timings.

## notes

This problem can be reproduced in an empty directory. However, I'm trying to debug performance problems in a real sbt project, and I'm seeing the same behavior there.

**Comment by eed3si9n** [comment]
Thanks for the report.
