### ISSUE TITLE
sbt is not working under DCEVM 11

### ISSUE THREAD

**Issue by rustyx** [sbt/sbt#6262]
## steps

1. Install [DCEVM 11](http://dcevm.github.io/)
1. Install `sbt`
1. Run `sbt` on any Scala project

## problem

```
error: error while loading package, Missing dependency 'object java.lang.Object in compiler mirror', required by C:\Users\user\.sbt\boot\scala-2.10.6\lib\scala-library.jar(scala/runtime/package.class)
scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
        at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:16)
        at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:17)
        at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:48)
        at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:40)
        at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:40)
        at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:61)
        at scala.reflect.internal.Mirrors$RootsBase.getClassByName(Mirrors.scala:99)
        at scala.reflect.internal.Mirrors$RootsBase.getRequiredClass(Mirrors.scala:102)
        at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:264)
        at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:264)
        at scala.reflect.internal.Definitions$DefinitionsClass.AnyRefClass$lzycompute(Definitions.scala:263)
        at scala.reflect.internal.Definitions$DefinitionsClass.AnyRefClass(Definitions.scala:263)
        at scala.reflect.internal.Definitions$DefinitionsClass.specialPolyClass(Definitions.scala:1120)
        at scala.reflect.internal.Definitions$DefinitionsClass.RepeatedParamClass$lzycompute(Definitions.scala:407)
        at scala.reflect.internal.Definitions$DefinitionsClass.RepeatedParamClass(Definitions.scala:407)
        at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreClasses$lzycompute(Definitions.scala:1154)
        at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreClasses(Definitions.scala:1152)
        at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode$lzycompute(Definitions.scala:1196)
        at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode(Definitions.scala:1196)
        at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1261)
        at scala.tools.nsc.Global$Run.<init>(Global.scala:1290)
        at sbt.compiler.Eval$$anon$1.<init>(Eval.scala:141)
        at sbt.compiler.Eval.run$lzycompute$1(Eval.scala:141)
        at sbt.compiler.Eval.run$1(Eval.scala:141)
        at sbt.compiler.Eval.unlinkAll$1(Eval.scala:144)
        at sbt.compiler.Eval.evalCommon(Eval.scala:153)
        at sbt.compiler.Eval.eval(Eval.scala:96)
        . . .
```

**Comment by eed3si9n** [comment]
The sbt version is mainly determined by the version listed in `project/build.properties` file.
Could you make sure you bump it up to:

```scala
sbt.version=1.4.6
```

The stack trace listing Scala 2.10.6 makes me suspect you're running some old sbt 0.13 that doesn't have JDK 11 support at the Scala level.

**Comment by rustyx** [comment]
Thanks, it seems to work indeed.

There's just one stack trace logged, but `sbt` nevertheless appears to be working

```
C:\Projects\sbttest>sbt run
Starting HotswapAgent 'C:\dev\dcevm11\lib\hotswap\hotswap-agent.jar'
HOTSWAP AGENT: 00:22:17.469 INFO (org.hotswap.agent.HotswapAgent) - Loading Hotswap agent {1.4.1} - unlimited runtime class redefinition.
HOTSWAP AGENT: 00:22:17.705 INFO (org.hotswap.agent.config.PluginRegistry) - Discovered plugins: [JdkPlugin, Hotswapper, WatchResources, ClassInitPlugin, AnonymousClassPatch, Hibernate, Hibernate3JPA, Hibernate3, Spring, Jersey1, Jersey2, Jetty, Tomcat, ZK, Logback, Log4j2, MyFaces, Mojarra, Omnifaces, ELResolver, WildFlyELResolver, OsgiEquinox, Owb, Proxy, WebObjects, Weld, JBossModules, ResteasyRegistry, Deltaspike, GlassFish, Vaadin, Wicket, CxfJAXRS, FreeMarker, Undertow, MyBatis]
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 13: HOTSWAP AGENT: 00:22:16.464 INFO (org.hotswap.agent.HotswapAgent) - Loading Hotswap agent {1.4.1} - unlimited runtime class redefinition.\rt.jar
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at sbt.rt.java9rtexport.Export.main(Export.java:42)
Starting HotswapAgent 'C:\dev\dcevm11\lib\hotswap\hotswap-agent.jar'
HOTSWAP AGENT: 00:22:19.068 INFO (org.hotswap.agent.HotswapAgent) - Loading Hotswap agent {1.4.1} - unlimited runtime class redefinition.
HOTSWAP AGENT: 00:22:19.296 INFO (org.hotswap.agent.config.PluginRegistry) - Discovered plugins: [JdkPlugin, Hotswapper, WatchResources, ClassInitPlugin, AnonymousClassPatch, Hibernate, Hibernate3JPA, Hibernate3, Spring, Jersey1, Jersey2, Jetty, Tomcat, ZK, Logback, Log4j2, MyFaces, Mojarra, Omnifaces, ELResolver, WildFlyELResolver, OsgiEquinox, Owb, Proxy, WebObjects, Weld, JBossModules, ResteasyRegistry, Deltaspike, GlassFish, Vaadin, Wicket, CxfJAXRS, FreeMarker, Undertow, MyBatis]
[info] welcome to sbt 1.4.5 (AdoptOpenJDK Java 11.0.8)
[info] loading project definition from C:\Projects\sbttest\project
[info] loading settings for project sbttest from build.sbt ...
[info] set current project to sbttest (in build file:/C:/Projects/sbttest/)
[info] running example.Hello
Hello
[success] Total time: 1 s, completed 18 Jan 2021, 00:22:25

C:\Projects\sbttest>
```
