### ISSUE TITLE
Please release a new version for the Ctrl+C fix

### ISSUE THREAD

**Issue by ngocdaothanh** [sbt/sbt#6268]
The latest version 1.4.6 doesn't contain this fix:
https://github.com/sbt/sbt/pull/6213

Please release a new version, because the exception displayed on Ctrl+C is very annoying:

```
^C
[warn] Canceling execution...
[warn] Run canceled.
java.util.concurrent.RejectedExecutionException
	at sbt.ConcurrentRestrictions$$anon$4.submit(ConcurrentRestrictions.scala:242)
	at sbt.Execute.submit(Execute.scala:282)
	at sbt.Execute.ready(Execute.scala:262)
	at sbt.Execute.notifyDone(Execute.scala:201)
	at sbt.Execute.$anonfun$retire$2(Execute.scala:172)
	at sbt.Execute.$anonfun$retire$2$adapted(Execute.scala:171)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at sbt.Execute.retire(Execute.scala:171)
	at sbt.Execute.$anonfun$work$2(Execute.scala:299)
	at sbt.Execute$$anon$1.process(Execute.scala:27)
	at sbt.Execute.next$1(Execute.scala:117)
	at sbt.Execute.processAll(Execute.scala:127)
	at sbt.Execute.runKeep(Execute.scala:95)
	at sbt.EvaluateTask$.liftedTree1$1(EvaluateTask.scala:476)
	at sbt.EvaluateTask$.run$1(EvaluateTask.scala:475)
	at sbt.EvaluateTask$.runTask(EvaluateTask.scala:498)
	at sbt.internal.Aggregation$.$anonfun$timedRun$4(Aggregation.scala:101)
	at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:388)
	at sbt.internal.Aggregation$.timedRun(Aggregation.scala:99)
	at sbt.internal.Aggregation$.runTasks(Aggregation.scala:113)
	at sbt.internal.Aggregation$.$anonfun$applyDynamicTasks$4(Aggregation.scala:181)
	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:145)
	at sbt.internal.Act$.$anonfun$actParser0$4(Act.scala:436)
	at sbt.Command$.process(Command.scala:189)
	at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:242)
	at scala.Option.getOrElse(Option.scala:189)
	at sbt.MainLoop$.process$1(MainLoop.scala:242)
	at sbt.MainLoop$.processCommand(MainLoop.scala:266)
	at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:162)
	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:289)
	at sbt.State$StateOpsImpl$.process$extension(State.scala:325)
	at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:162)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.MainLoop$.next(MainLoop.scala:162)
	at sbt.MainLoop$.run(MainLoop.scala:143)
	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:118)
	at sbt.io.Using.apply(Using.scala:27)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:111)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:65)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:50)
	at sbt.MainLoop$.runLogged(MainLoop.scala:41)
	at sbt.StandardMain$.runManaged(Main.scala:191)
	at sbt.xMain$.$anonfun$run$8(Main.scala:102)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withIn(Console.scala:230)
	at sbt.internal.util.Terminal$.withIn(Terminal.scala:557)
	at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:347)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withOut(Console.scala:167)
	at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:547)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withErr(Console.scala:196)
	at sbt.internal.util.Terminal$.withOut(Terminal.scala:547)
	at sbt.internal.util.Terminal$.withStreams(Terminal.scala:347)
	at sbt.xMain$.run(Main.scala:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:83)
	at sbt.xMain.run(Main.scala:46)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:131)
	at xsbt.boot.Launch$.run(Launch.scala:111)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
	at xsbt.boot.Launch$.launch(Launch.scala:120)
	at xsbt.boot.Launch$.apply(Launch.scala:20)
	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
	at xsbt.boot.Boot$.main(Boot.scala:18)
	at xsbt.boot.Boot.main(Boot.scala)
[error] java.util.concurrent.RejectedExecutionException
[error] Use 'last' for the full log.
```

**Comment by mkurz** [comment]
Fixed in sbt 1.4.7.
Can be closed.
