### ISSUE TITLE
sbt should try to recover from a corrupted target/ or ~/.sbt directory

### ISSUE THREAD

**Issue by smarter** [sbt/sbt#6338]
Out of ~210 students starting a class at EPFL today using sbt 1.4.7, at least two had issues related to corrupted files in their target/ directory which prevented them from using sbt until I told them to clean that directory:
![cor0](https://user-images.githubusercontent.com/63430/109036559-05efb900-76ca-11eb-9b11-6178299d6ead.png)
```scala
[error] java.lang.NoClassDefFoundError: $643da8ee4d202b04c2da$
[error]     at $7024695f5b734dee7409$.$anonfun$$sbtdef$1(/Users/oskar/EPFL/CS-206/cs206-example/build.sbt:12)
[error]     at sbt.std.Transform$$anon$3.$anonfun$apply$2(Transform.scala:46)
[error]     at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]     at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]     at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]     at sbt.Execute.work(Execute.scala:291)
[error]     at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]     at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]     at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]     at java.lang.Thread.run(Thread.java:748)
```
I have no idea how this happens (hardware issue?) but since it doesn't seem to be that uncommon, it would be great if sbt had a fallback mode where it would delete its own target and restart instead of exiting with an error because it failed to start.

**Comment by eed3si9n** [comment]
@smarter Thanks for the report. I guess first thing we should look into is make sure the metabuild automatically gets invalidated when sbt version changes.

**Comment by smarter** [comment]
I've also seen had two students now where sbt failed to find its own classes:
![sbtcnf](https://user-images.githubusercontent.com/63430/109821402-3ab5c000-7c36-11eb-9211-d85c7ae47ee2.png)
I was able to confirm at least in one case that deleting `~/.sbt` fixed the problem.
