### ISSUE TITLE
sbt console does not show while I am typing

### ISSUE THREAD

**Issue by ahmetlekesiz** [sbt/sbt#6365]
## steps

Invoke sbt in terminal

## problem

I am able to type and get result after entering the input but I can not see while I am writing.

## expectation

I want to see what I am typing.

## notes
The console is working as expected when I invoke sbt as follows: `sbt "-Djline.terminal=none"`.
However the problem occurs when I invoke by `sbt`.

* sbt version: 1.4.7
* java version: openjdk version "1.8.0_282"
* OS: Mac OS 10.15.7

**Comment by eed3si9n** [comment]
@ahmetlekesiz Thanks for the report. Could you provide more details so we can reproduce this on our machines.

For instance, 
- How did you install sbt? (are you using the official launcher or one of the fake ones?)
- Is this your first time using sbt on the machine, or did this issue start recently?
- What terminal program are you using and what is the TERM environment variable?

**Comment by ahmetlekesiz** [comment]
Sure @eed3si9n. Thanks for fast reply.
* I have installed sbt by using Homebrew 3.0.3
* It is the first time that I am using sbt on this machine.
* I have faced with this issue while using default terminal of Mac and tried iTerm but could not solve the problem.
* TERM=xterm-256color

**Comment by ahmetlekesiz** [comment]
I thought the problem is caused by the Homebrew, however I have seen that someone faced with similar issue with sdkman. #4021

**Comment by eed3si9n** [comment]
Works for me using Terminal.app.

```
$ sbt
[info] welcome to sbt 1.4.7 (AdoptOpenJDK Java 1.8.0_282)
[info] loading settings for project global-plugins from idea.sbt,pgp.sbt,plugins.sbt,vimquit.sbt ...
[info] loading global plugins from /Users/eed3si9n/.sbt/1.0/plugins
[info] loading project definition from /private/tmp/hello/project
[info] compiling 1 Scala source to /private/tmp/hello/project/target/scala-2.12/sbt-1.0/classes ...
[info] loading settings for project root from build.sbt ...
[info] set current project to hello (in build file:/private/tmp/hello/)
[info] sbt server started at local:///Users/eed3si9n/.sbt/1.0/server/478e6db75688771ddcf1/sock
[info] started sbt server
sbt:hello> name
[info] hello
```

I guess another question is: are you using Intel mac or Apple Silicon (AArch64) M1.

**Comment by ahmetlekesiz** [comment]
I use Intel mac. I will reinstall the sbt and let you know if it is still an issue.

**Comment by ahmetlekesiz** [comment]
@eed3si9n May I learn how did you install sbt?

**Comment by eed3si9n** [comment]
I use sdkman.

**Comment by SethTisue** [comment]
closing for inactivity / lack of information

**Comment by Tarbetu** [comment]
As a Linux user, I face with the same problem. I installed the sbt via with command which shown in this page:
https://docs.scala-lang.org/getting-started/index.html

```shell
❯ sbt --version
sbt version in this project: 1.8.2
sbt script version: 1.8.2
❯ scala --version
Scala code runner version 3.2.2 -- Copyright 2002-2023, LAMP/EPFL
❯ uname -a
Linux localhost.localdomain 6.2.2-1-default #1 SMP PREEMPT_DYNAMIC Thu Mar  9 06:06:13 UTC 2023 (44ca817) x86_64 x86_64 x86_64 GNU/Linux
```

I'm using openSUSE Tumbleweed and I have an AMD Ryzen system, it happens while using both the embedded terminal of VS Code and Konsole application of KDE.

By the way, when I see the starter of issue is Turkish like me, I thought that it might be language or keyboard layout based bug.

**Comment by SethTisue** [comment]
It might be worth checking https://github.com/jline/jline3/issues to see if it's been reported there.

**Comment by Tarbetu** [comment]
I can add some information.

I have a debugging trick for handing the language errors. When I call sbt with "LANG=C" it works fine. But when call sbt with "LANG=tr_TR.UTF-8 sbt", I face with this issue.

Furthermore, I got some interesting errors when I call "exit". 
```shell
❯ LANG=tr_TR.UTF-8 sbt
[info] welcome to sbt 1.8.2 (Oracle Corporation Java 11.0.18)
[info] loading settings for project printable-build-build-build from metals.sbt ...
[info] loading project definition from /home/emre/Code/Scala/printable/project/project/project
[info] loading settings for project printable-build-build from metals.sbt ...
[info] loading project definition from /home/emre/Code/Scala/printable/project/project
[success] Generated .bloop/printable-build-build.json
[success] Total time: 1 s, completed 26 Mar 2023 16:08:22
[info] loading settings for project printable-build from metals.sbt,plugins.sbt ...
[info] loading project definition from /home/emre/Code/Scala/printable/project
[success] Generated .bloop/printable-build.json
[success] Total time: 1 s, completed 26 Mar 2023 16:08:23
[info] loading settings for project printable from build.sbt ...
[info] set current project to printable (in build file:/home/emre/Code/Scala/printable/)
[info] sbt server started at local:///home/emre/.sbt/1.0/server/3c50465bb669b3e1741d/sock
[info] started sbt server
sbt:printable> exit
[info] shutting down sbt server
java.io.IOError: java.io.IOException: Error executing 'stty mın 0 tıme 1': stty: geçersiz argüman `mın'
Daha fazla bilgi için 'stty --help' deneyin.
        at org.jline.terminal.impl.AbstractPosixTerminal.setAttributes(AbstractPosixTerminal.java:54)
        at org.jline.terminal.impl.AbstractTerminal.enterRawMode(AbstractTerminal.java:141)
        at sbt.internal.util.Terminal$.withStreams(Terminal.scala:371)
        at sbt.xMain$.withStreams$1(Main.scala:87)
        at sbt.xMain$.run(Main.scala:121)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:57)
        at sbt.xMain.run(Main.scala:46)
        at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
        at xsbt.boot.Launch$.run(Launch.scala:149)
        at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
        at xsbt.boot.Launch$.launch(Launch.scala:159)
        at xsbt.boot.Launch$.apply(Launch.scala:44)
        at xsbt.boot.Launch$.apply(Launch.scala:21)
        at xsbt.boot.Boot$.runImpl(Boot.scala:78)
        at xsbt.boot.Boot$.run(Boot.scala:73)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.io.IOException: Error executing 'stty mın 0 tıme 1': stty: geçersiz argüman `mın'
Daha fazla bilgi için 'stty --help' deneyin.
        at org.jline.utils.ExecHelper.exec(ExecHelper.java:42)
        at org.jline.terminal.impl.ExecPty.doSetAttr(ExecPty.java:101)
        at org.jline.terminal.impl.AbstractPty.setAttr(AbstractPty.java:29)
        at org.jline.terminal.impl.AbstractPosixTerminal.setAttributes(AbstractPosixTerminal.java:52)
        ... 21 more
[error] [launcher] error during sbt launcher: java.io.IOError: java.io.IOException: Error executing 'stty mın 0 tıme 1': stty: geçersiz argüman `mın'
[error] [launcher] Daha fazla bilgi için 'stty --help' deneyin.
```

The translation of "geçersiz argüman" is "invalid argument" and it complains about there is no argument like  "mın" and "tıme". In Turkish language, the lowercase of "I" is "ı", not "i", also the uppercase of "i" is "İ". It seems like some arguments are messed up. You might check this page for more information: https://en.wikipedia.org/wiki/Dotted_and_dotless_I_in_computing about this topic.

I don't know should I report in jline, actually I very new at JVM field and don't know what would to fix it. As an advice, sbt should operate in English because Scala users in Turkey are very few, and they know English very well.
