### ISSUE TITLE
Breaking change: sbt 1.4.9 breaks sbt-errors-summary because it used private[sbt] method

### ISSUE THREAD

**Issue by marconilanna** [sbt/sbt#6389]
## steps

Barebones sbt project, just a `project/build.properties` with `sbt.version = 1.4.9` and the following `project/plugins.sbt`:

```
// http://github.com/Duhemm/sbt-errors-summary
addSbtPlugin("org.duhemm" % "sbt-errors-summary" % "0.6.3")
```

## problem

sbt fails to load with the `plugins.sbt` above:

```
$ sbt
[info] welcome to sbt 1.4.9 (AdoptOpenJDK Java 1.8.0_282)
[error] java.lang.NoSuchMethodError: sbt.Defaults$.foldMappers(Lscala/collection/Seq;)Lscala/Function1;
[error] 	at sbt.errorssummary.Plugin$.$anonfun$reporterSettings$1(Plugin.scala:39)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (Compile / compile / compilerReporter) java.lang.NoSuchMethodError: sbt.Defaults$.foldMappers(Lscala/collection/Seq;)Lscala/Function1;
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
```

sbt loads normally if the `plugins.sbt` file is deleted.

## expectation

sbt 1.4.9 should not break existing plugins. The project above loads normally with sbt 1.4.7.

## notes

Relates to https://github.com/sbt/sbt/commit/de313bbdde866abc07577f89a0077b1de898bf34

**Comment by eed3si9n** [comment]
@marconilanna Thanks for the report. Please check out https://github.com/sbt/sbt/issues/6379.
