### ISSUE TITLE
sbt 1.5.0-RC1 throw "java.lang.LinkageError: loader constraint violation in interface itable initialization"

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt#6402]
## steps

https://github.com/xuwei-k/sbt-1-5-0-RC1-loader-constraint-violation/commit/d6d6fe3758c03d8d51e04543ca2b67f287a7b4ba

```diff
diff --git a/Main.scala b/Main.scala
new file mode 100644
index 0000000..4b8a48e
--- /dev/null
+++ b/Main.scala
@@ -0,0 +1,26 @@
+import better.files.File
+import java.nio.file.Files
+import cats.effect.ExitCode
+import cats.effect.IO
+import cats.effect.IOApp
+import org.scalasteward.core.application.Cli
+import org.scalasteward.core.application.Context
+
+object Main extends IOApp {
+  override def run(args: List[String]): IO[ExitCode] = {
+    val tmp = Files.createTempDirectory("temp-steward")
+    val a = Cli.Args(
+      workspace = tmp,
+      reposFile = File("repos.md"),
+      defaultRepoConf = None,
+      gitAuthorName = "aaa",
+      gitAuthorEmail = "aaa@example.com",
+      vcsLogin = "aaa",
+      gitAskPass = File("aaa.sh"),
+      envVar = Nil,
+      disableSandbox = true,
+      doNotFork = true
+    )
+    Context.step0[IO](a).use(_.stewardAlg.runF)
+  }
+}
diff --git a/aaa.sh b/aaa.sh
new file mode 100755
index 0000000..e69de29
diff --git a/build.sbt b/build.sbt
new file mode 100644
index 0000000..18e9bcc
--- /dev/null
+++ b/build.sbt
@@ -0,0 +1,3 @@
+libraryDependencies += "org.scala-steward" %% "scala-steward-core" % "0.9.1"
+
+scalaVersion := "2.13.5"
```

`sbt -sbt-version 1.5.0-RC1 run`

## problem

https://github.com/xuwei-k/sbt-1-5-0-RC1-loader-constraint-violation/runs/2136627267#step:5:53

```
java.lang.LinkageError: loader constraint violation in interface itable initialization: when resolving method "coursier.interop.PlatformCatsImplicits$$anon$1.bind(Ljava/lang/Object;Lscala/Function1;)Ljava/lang/Object;" the class loader (instance of sbt/internal/LayeredClassLoader) of the current class, coursier/interop/PlatformCatsImplicits$$anon$1, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for interface coursier/util/Monad have different Class objects for the type scala/Function1 used in the signature
	at coursier.interop.PlatformCatsImplicits.coursierSyncFromCats(PlatformCatsImplicits.scala:14)
	at org.scalasteward.core.coursier.CoursierAlg$.create(CoursierAlg.scala:54)
	at org.scalasteward.core.application.Context$.$anonfun$step1$8(Context.scala:129)
	at cats.effect.IO$Map.apply(IO.scala:1699)
	at cats.effect.IO$Map.apply(IO.scala:1697)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:187)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:463)
	at cats.effect.internals.IORunLoop$RestartCallback.run(IORunLoop.scala:474)
	at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:67)
	at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:35)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:90)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:90)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:90)
	at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
	at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:42)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:482)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:422)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:183)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:463)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:484)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:422)
	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
	at cats.effect.internals.PoolUtils$$anon$2$$anon$3.run(PoolUtils.scala:52)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

## expectation

Don't throw error

## notes

only 1.5.0-RC1. not throw error with sbt 1.4.9 and 1.5.0-M2

https://github.com/xuwei-k/sbt-1-5-0-RC1-loader-constraint-violation/actions/runs/663278369

![build-matrix](https://user-images.githubusercontent.com/389787/111570396-1cc88d80-87e8-11eb-9ad4-e0d4289235df.png)

**Comment by eed3si9n** [comment]
@xuwei-k Thanks for the report!

> java.lang.LinkageError: loader constraint violation in interface itable initialization: when resolving method "coursier.interop.PlatformCatsImplicits$$anon$1.bind(Ljava/lang/Object;Lscala/Function1;)Ljava/lang/Object;" the class loader (instance of sbt/internal/LayeredClassLoader) of the current class, coursier/interop/PlatformCatsImplicits$$anon$1, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for interface coursier/util/Monad have different Class objects for the type scala/Function1 used in the signature

I'm not sure which change during https://github.com/sbt/sbt/compare/v1.5.0-M2...v1.5.0-RC1 could be causing this. It looks like something layered ClassLoader related?

**Comment by xuwei-k** [comment]
>  It looks like something layered ClassLoader related?

but sbt 1.5.0-RC1 throws same error if `fork / run := true` 🤔 🤔 🤔

**Comment by adpi2** [comment]
> but sbt 1.5.0-RC1 throws same error if `fork / run := true`

You should try with `run / fork := true` instead :wink:

https://github.com/adpi2/sbt-1-5-0-RC1-loader-constraint-violation/pull/2

**Comment by adpi2** [comment]
I am not able to reproduce this bug locally but I forked the repo to get more information about the `LayeredClassLoader` being used:

https://github.com/adpi2/sbt-1-5-0-RC1-loader-constraint-violation/pull/1/checks?check_run_id=2138927608

It looks like this:

```
sbt.internal.LayeredClassLoader:
  urls:
    ./target/bg-jobs/sbt_6141d3e2/job-1/target/b757ce4b/ce0b50a5/sbt-1-5-0-rc1-loader-constraint-violation_2.13-0.1.0-SNAPSHOT.jar
    ./target/bg-jobs/sbt_6141d3e2/target/6b17bb42/2a681fee/scala-steward-core_2.13-0.9.1.jar
    ./target/bg-jobs/sbt_6141d3e2/target/f3977382/c22f4efb/atto-core_2.13-0.9.0.jar
    ./target/bg-jobs/sbt_6141d3e2/target/f647e249/493381db/bcprov-jdk15to18-1.68.jar
    ./target/bg-jobs/sbt_6141d3e2/target/a92ded8e/4afc5e4f/better-files_2.13-3.9.1.jar
    ./target/bg-jobs/sbt_6141d3e2/target/8df53ee6/d4bc254a/case-app_2.13-2.0.4.jar
    ./target/bg-jobs/sbt_6141d3e2/target/0bbeb0b8/7b81bdb1/cats-core_2.13-2.3.1.jar
    ./target/bg-jobs/sbt_6141d3e2/target/45cc9283/29e46382/cats-effect_2.13-2.3.1.jar
    ./target/bg-jobs/sbt_6141d3e2/target/bb48c3e0/0e3a46d3/circe-config_2.13-0.8.0.jar
    ./target/bg-jobs/sbt_6141d3e2/target/d083367f/62917132/circe-generic_2.13-0.13.0.jar
    ./target/bg-jobs/sbt_6141d3e2/target/b11003d8/149da3db/circe-generic-extras_2.13-0.13.0.jar
    ./target/bg-jobs/sbt_6141d3e2/target/9762a85e/eb2e98f4/circe-parser_2.13-0.13.0.jar
    ./target/bg-jobs/sbt_6141d3e2/target/70034d4d/580331ed/circe-refined_2.13-0.13.0.jar
    ./target/bg-jobs/sbt_6141d3e2/target/7d2fa958/3ca1f48a/commons-io-2.8.0.jar
    ./target/bg-jobs/sbt_6141d3e2/target/0808c438/c7c9ac57/coursier_2.13-2.0.9.jar
    ./target/bg-jobs/sbt_6141d3e2/target/8c1a1865/d15d0f6f/coursier-cats-interop_2.13-2.0.9.jar
    ./target/bg-jobs/sbt_6141d3e2/target/31153cd3/8c0b7c06/cron4s-core_2.13-0.6.1.jar
    ./target/bg-jobs/sbt_6141d3e2/target/9c6b8a09/89b7724d/fs2-core_2.13-2.5.0.jar
    ./target/bg-jobs/sbt_6141d3e2/target/b6cf01ca/e9ca8039/fs2-io_2.13-2.5.0.jar
    ./target/bg-jobs/sbt_6141d3e2/target/8f6b63bc/4f474f79/http4s-circe_2.13-0.21.16.jar
    ./target/bg-jobs/sbt_6141d3e2/target/d3a91532/43a14db3/http4s-client_2.13-0.21.16.jar
    ./target/bg-jobs/sbt_6141d3e2/target/47fb5c46/2459e623/http4s-core_2.13-0.21.16.jar
    ./target/bg-jobs/sbt_6141d3e2/target/88fe900a/bb42a6c2/http4s-okhttp-client_2.13-0.21.16.jar
    ./target/bg-jobs/sbt_6141d3e2/target/85cd055e/7fbda7e0/jjwt-api-0.11.2.jar
    ./target/bg-jobs/sbt_6141d3e2/target/ce3f8ae3/1886c1c6/jjwt-impl-0.11.2.jar
    ./target/bg-jobs/sbt_6141d3e2/target/2ddf79c5/943d1e8e/jjwt-jackson-0.11.2.jar
    ./target/bg-jobs/sbt_6141d3e2/target/0e9b1206/bf290a68/log4cats-slf4j_2.13-1.1.1.jar
    ./target/bg-jobs/sbt_6141d3e2/target/92c31a5d/d203bc6f/monocle-core_2.13-2.1.0.jar
    ./target/bg-jobs/sbt_6141d3e2/target/b8fbadd6/1088e80e/refined_2.13-0.9.20.jar
    ./target/bg-jobs/sbt_6141d3e2/target/51b16098/c2fef9f7/refined-cats_2.13-0.9.20.jar
    ./target/bg-jobs/sbt_6141d3e2/target/b8846573/189d852e/scalacache-caffeine_2.13-0.28.0.jar
    ./target/bg-jobs/sbt_6141d3e2/target/8c3f79ec/ccdef2fa/scalacache-cats-effect_2.13-0.28.0.jar
    ./target/bg-jobs/sbt_6141d3e2/target/84a3010e/97705cb7/logback-classic-1.2.3.jar
    ./target/bg-jobs/sbt_6141d3e2/target/6bdc2517/325a618e/case-app-annotations_2.13-2.0.4.jar
    ./target/bg-jobs/sbt_6141d3e2/target/c0043e79/07da8068/case-app-util_2.13-2.0.4.jar
    ./target/bg-jobs/sbt_6141d3e2/target/3e981d65/24ba96ab/cats-kernel_2.13-2.3.1.jar
    ./target/bg-jobs/sbt_6141d3e2/target/9c5f7901/cc05423f/simulacrum-scalafix-annotations_2.13-0.5.3.jar
    ./target/bg-jobs/sbt_6141d3e2/target/b7db2772/65a4d7a3/config-1.4.0.jar
    ./target/bg-jobs/sbt_6141d3e2/target/55e3ee77/4379f235/circe-core_2.13-0.13.0.jar
    ./target/bg-jobs/sbt_6141d3e2/target/9a18a133/0cc2d7d5/shapeless_2.13-2.3.3.jar
    ./target/bg-jobs/sbt_6141d3e2/target/df5df9a1/5be78909/circe-jawn_2.13-0.13.0.jar
    ./target/bg-jobs/sbt_6141d3e2/target/137644de/b4ae5ae0/coursier-core_2.13-2.0.9.jar
    ./target/bg-jobs/sbt_6141d3e2/target/4fa770cf/3963bceb/coursier-cache_2.13-2.0.9.jar
    ./target/bg-jobs/sbt_6141d3e2/target/17f42abc/3bdd2e7b/argonaut-shapeless_6.2_2.13-1.2.0.jar
    ./target/bg-jobs/sbt_6141d3e2/target/97b60a3d/de51ef4b/scala-parser-combinators_2.13-1.1.2.jar
    ./target/bg-jobs/sbt_6141d3e2/target/dac7db79/ff6f3545/scodec-bits_2.13-1.1.23.jar
    ./target/bg-jobs/sbt_6141d3e2/target/70f94709/d8a305f1/http4s-jawn_2.13-0.21.16.jar
    ./target/bg-jobs/sbt_6141d3e2/target/50288158/d3f8e2d1/log4s_2.13-1.9.0.jar
    ./target/bg-jobs/sbt_6141d3e2/target/686faf2f/401011f1/parboiled_2.13-2.0.1.jar
    ./target/bg-jobs/sbt_6141d3e2/target/978a66f8/9f4f0e8c/slf4j-api-1.7.30.jar
    ./target/bg-jobs/sbt_6141d3e2/target/920690d0/e01d9fdc/vault_2.13-2.0.0.jar
    ./target/bg-jobs/sbt_6141d3e2/target/cac4d1ba/298127e9/okhttp-4.9.0.jar
    ./target/bg-jobs/sbt_6141d3e2/target/342e6237/2996fe01/okio-2.9.0.jar
    ./target/bg-jobs/sbt_6141d3e2/target/a4fbb61c/2d7848d1/jackson-databind-2.9.10.4.jar
    ./target/bg-jobs/sbt_6141d3e2/target/60766695/f63e1904/log4cats-core_2.13-1.1.1.jar
    ./target/bg-jobs/sbt_6141d3e2/target/072efe38/fab8c9fe/cats-free_2.13-2.1.1.jar
    ./target/bg-jobs/sbt_6141d3e2/target/734151d9/0eefb744/scala-compiler-2.13.5.jar
    ./target/bg-jobs/sbt_6141d3e2/target/96f719ce/f4c65b0c/scala-xml_2.13-1.3.0.jar
    ./target/bg-jobs/sbt_6141d3e2/target/26d731f9/9a6aacfd/scalacache-core_2.13-0.28.0.jar
    ./target/bg-jobs/sbt_6141d3e2/target/3b742371/d7057493/caffeine-2.7.0.jar
    ./target/bg-jobs/sbt_6141d3e2/target/6752d054/8d05bad2/logback-core-1.2.3.jar
    ./target/bg-jobs/sbt_6141d3e2/target/728f939b/155ba2a0/circe-numbers_2.13-0.13.0.jar
    ./target/bg-jobs/sbt_6141d3e2/target/655be7bc/a5e01df1/jawn-parser_2.13-1.0.1.jar
    ./target/bg-jobs/sbt_6141d3e2/target/5bf9b348/a6bf1040/coursier-util_2.13-2.0.9.jar
    ./target/bg-jobs/sbt_6141d3e2/target/6034039c/0baf0bfb/concurrent-reference-hash-map-1.0.0.jar
    ./target/bg-jobs/sbt_6141d3e2/target/c5ae1df6/47a84cb8/windows-ansi-0.0.3.jar
    ./target/bg-jobs/sbt_6141d3e2/target/9b6220f0/b9eb7e85/argonaut_2.13-6.2.5.jar
    ./target/bg-jobs/sbt_6141d3e2/target/05a88e07/24684ad0/jawn-fs2_2.13-1.0.0.jar
    ./target/bg-jobs/sbt_6141d3e2/target/50c9dacf/adbe6aa6/unique_2.13-2.0.0.jar
    ./target/bg-jobs/sbt_6141d3e2/target/537e6797/4e2d8c4f/kotlin-stdlib-1.4.10.jar
    ./target/bg-jobs/sbt_6141d3e2/target/7ca5e408/3674ae8d/kotlin-stdlib-common-1.4.10.jar
    ./target/bg-jobs/sbt_6141d3e2/target/d8ad0ae5/4cd1c67e/jackson-annotations-2.9.10.jar
    ./target/bg-jobs/sbt_6141d3e2/target/b6d548b1/d95ad43b/jackson-core-2.9.10.jar
    ./target/bg-jobs/sbt_6141d3e2/target/12dcbff6/54b1b19c/cats-macros_2.13-2.1.1.jar
    ./target/bg-jobs/sbt_6141d3e2/target/9d008aa6/c430ad4e/jline-3.19.0.jar
    ./target/bg-jobs/sbt_6141d3e2/target/90454b60/d06fed31/jna-5.3.1.jar
    ./target/bg-jobs/sbt_6141d3e2/target/923565af/0769abd6/checker-qual-2.6.0.jar
    ./target/bg-jobs/sbt_6141d3e2/target/86103b53/44c2192d/error_prone_annotations-2.3.3.jar
    ./target/bg-jobs/sbt_6141d3e2/target/1b682ff0/d2afeec3/scala-collection-compat_2.13-2.2.0.jar
    ./target/bg-jobs/sbt_6141d3e2/target/496d5430/539430a2/jansi-1.18.jar
    ./target/bg-jobs/sbt_6141d3e2/target/0ce48193/910e9f63/annotations-13.0.jar
  parent:
    sbt.internal.classpath.WrappedLoader:
      urls:
        file:/home/runner/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.5/scala-reflect-2.13.5.jar
      parent:
        sbt.internal.ScalaReflectClassLoader:
          urls:
            file:/home/runner/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.5/scala-reflect-2.13.5.jar
          parent:
            sbt.internal.classpath.WrappedLoader:
              urls:
                file:/home/runner/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.5/scala-library-2.13.5.jar
              parent:
                sbt.internal.ScalaLibraryClassLoader:
                  urls:
                    file:/home/runner/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.5/scala-library-2.13.5.jar
                  parent:
                    sbt.internal.SbtInterfaceLoader:
                      urls:
                        file:/home/runner/.sbt/boot/scala-2.12.13/org.scala-sbt/sbt/1.5.0-RC1/test-interface-1.0.jar
                        file:/home/runner/.sbt/boot/scala-2.12.13/org.scala-sbt/sbt/1.5.0-RC1/compiler-interface-1.5.0-M4.jar
                      parent:
                        null:
                          parent:
                            xsbt.boot.BootFilteredLoader:
                              parent:
                                sun.misc.Launcher.AppClassLoader:
                                  urls:
                                    file:/home/runner/.sbt/launchers/1.5.0-RC1/sbt-launch.jar
                                  parent:
                                    sun.misc.Launcher.ExtClassLoader:
                                      urls:
                                        file:/home/runner/.jabba/jdk/adopt@1.8.0-275/jre/lib/ext/zipfs.jar
                                        file:/home/runner/.jabba/jdk/adopt@1.8.0-275/jre/lib/ext/nashorn.jar
                                        file:/home/runner/.jabba/jdk/adopt@1.8.0-275/jre/lib/ext/sunec.jar
                                        file:/home/runner/.jabba/jdk/adopt@1.8.0-275/jre/lib/ext/jaccess.jar
                                        file:/home/runner/.jabba/jdk/adopt@1.8.0-275/jre/lib/ext/dnsns.jar
                                        file:/home/runner/.jabba/jdk/adopt@1.8.0-275/jre/lib/ext/sunpkcs11.jar
                                        file:/home/runner/.jabba/jdk/adopt@1.8.0-275/jre/lib/ext/localedata.jar
                                        file:/home/runner/.jabba/jdk/adopt@1.8.0-275/jre/lib/ext/sunjce_provider.jar
                                        file:/home/runner/.jabba/jdk/adopt@1.8.0-275/jre/lib/ext/cldrdata.jar
```

As far as this printing can tell, there is no difference between the classloader used in 1.5.0-M2 and the classloader used in 1.5.0-RC1.

**Comment by adpi2** [comment]
Actually the problem must be that `sbt-launch.jar` contains a different `coursier/util/Monad.class` than `coursier_2.13-2.0.9.jar`.

In fact `sbt-launch.jar` used to not contain any coursier class in 1.4.9 but now it does:
https://github.com/sbt/launcher/commit/4b81529f6b75fad35feff70ffd78cf9c75dbffdd

@eed3si9n, would it be possible to remove coursier from `sbt-launch.jar`?

**Comment by eed3si9n** [comment]
Nice catch! It would be nice to keep Coursier launcher for 1.5.0 either by shading or filtering.
