### ISSUE TITLE
sbt 1.5.0 failing with java.io.IOException: failed to create lock file /root/.ivy2/.sbt.ivy.lock when `.ivy2` is in root directory

### ISSUE THREAD

**Issue by YuvalItzchakov** [sbt/sbt#6437]
## steps

- Create `build.sbt` file
- Add `sbt-native-packager`
- Start docker with the path to your code: `docker run -i -t -v <path_to_local_code_directory>:<path_in_container> hseeberger/scala-sbt:15.0.2_1.5.0_2.13.5 /bin/bash`
- Run `sbt "Universal / stage"`

Scala 2.13.5

Running the above, I receive the following error:

```
[success] Total time: 70 s (01:10), completed Apr 8, 2021, 6:09:51 AM
[warn] sbt 0.13 shell syntax is deprecated; use slash syntax instead: Universal / stage
[info] Main Scala API documentation to /root/foo/target/scala-2.13/api...
[info] compiling 2 Scala sources to /root/foo/target/scala-2.13/classes ...
[info] done compiling
[info] Main Scala API documentation successful.
[error] java.io.IOException: failed to create lock file /root/.ivy2/.sbt.ivy.lock
[error] 	at xsbt.boot.Locks$.liftedTree1$1(Locks.scala:43)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:41)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:36)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:87)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:209)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:206)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:250)
[error] 	at sbt.internal.librarymanagement.IvyActions$.makePomFile(IvyActions.scala:72)
[error] 	at sbt.librarymanagement.ivy.IvyPublisher.makePomFile(IvyPublisher.scala:22)
[error] 	at sbt.librarymanagement.Publisher.makePomFile(Publisher.scala:43)
[error] 	at sbt.Classpaths$.$anonfun$ivyPublishSettings$2(Defaults.scala:2823)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[error] 	at java.base/java.lang.Thread.run(Thread.java:832)
[error] Caused by: java.io.IOException: No such file or directory
[error] 	at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
[error] 	at java.base/java.io.File.createNewFile(File.java:1026)
[error] 	at xsbt.boot.Locks$.liftedTree1$1(Locks.scala:41)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:41)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:36)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:87)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:209)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:206)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:250)
[error] 	at sbt.internal.librarymanagement.IvyActions$.makePomFile(IvyActions.scala:72)
[error] 	at sbt.librarymanagement.ivy.IvyPublisher.makePomFile(IvyPublisher.scala:22)
[error] 	at sbt.librarymanagement.Publisher.makePomFile(Publisher.scala:43)
[error] 	at sbt.Classpaths$.$anonfun$ivyPublishSettings$2(Defaults.scala:2823)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[error] 	at java.base/java.lang.Thread.run(Thread.java:832)
[error] (makePom) java.io.IOException: failed to create lock file /root/.ivy2/.sbt.ivy.lock
```

## expectation

sbt should be able to access ivy lock

## notes

**Workaround**: Setting the `-ivy` flag for sbt explicitly to target NON root directory:

`sbt -ivy /tmp/.ivy2 ";test;Universal / stage"`

Makes sbt run properly.

**Comment by eed3si9n** [comment]
@YuvalItzchakov Thanks for the report! Too bad it seems like Ivy is still involved in certain aspects of basic operations like making POM.

@alexarchambault Is Coursier publish command still experimental?

**Comment by keithly** [comment]
I have also experienced this with Java 8 and Scala 2.12.13 `hseeberger/scala-sbt:8u282_1.5.0_2.12.13`

**Comment by rawyler** [comment]
This is just a temporary fix for the oraclelinux part: https://github.com/hseeberger/scala-sbt/pull/140 creating the missing .ivy2 directory https://github.com/hseeberger/scala-sbt/pull/140

I also added git to the oraclelinux Docker image as it is a requirement for projects using sbt-dynver

As a workaround I based builds failing with `java.io.IOException: failed to create lock file /root/.ivy2/.sbt.ivy.lock` on `tegonal/scala-sbt:16_1.5.0_2.13.5` until it is resolved

**Comment by Nirvikalpa108** [comment]
I reproduced this problem as you described (thanks for documenting so clearly!💕) and found that the error is caused by the broken sym-link in `/root` to `.ivy2` on @hseeberger's Docker image. Hopefully this can get fixed soon.

```
root@39fb5e15b665:/# cd root/
root@39fb5e15b665:~# ls -la
total 20
drwx------ 1 root root 4096 May  2 18:56 .
drwxr-xr-x 1 root root 4096 May  2 18:49 ..
-rw-r--r-- 1 root root  570 Jan 31  2010 .bashrc
lrwxrwxrwx 1 root root   20 Apr  9 00:44 .cache -> /home/sbtuser/.cache
lrwxrwxrwx 1 root root   19 Apr  9 00:44 .ivy2 -> /home/sbtuser/.ivy2
-rw-r--r-- 1 root root  148 Aug 17  2015 .profile
lrwxrwxrwx 1 root root   18 Apr  9 00:44 .sbt -> /home/sbtuser/.sbt
drwxr-xr-x 2 root root 4096 May  2 18:56 test
root@39fb5e15b665:~# cd .ivy2
bash: cd: .ivy2: No such file or directory
root@39fb5e15b665:~# cd /home/sbtuser/.ivy2
bash: cd: /home/sbtuser/.ivy2: No such file or directory
root@39fb5e15b665:~# cd /home/sbtuser
root@39fb5e15b665:/home/sbtuser# ls -la
total 32
drwxr-xr-x 1 sbtuser sbtuser 4096 Apr  9 00:44 .
drwxr-xr-x 1 root    root    4096 Apr  9 00:44 ..
drwxr-xr-x 1 sbtuser sbtuser 4096 Apr  9 00:44 .cache
drwxr-xr-x 1 sbtuser sbtuser 4096 Apr  9 00:44 .sbt
root@39fb5e15b665:/home/sbtuser#
```

**Comment by eed3si9n** [comment]
Thanks for the investigation work @Nirvikalpa108!

**Comment by francisdb** [comment]
@Nirvikalpa108 as maintainer of the scala-sbt docker image I'm also having a look at this
https://github.com/hseeberger/scala-sbt/issues/145

**Comment by francisdb** [comment]
@YuvalItzchakov confirmation that this is now fixed would be welcome (`16_1.5.1_2.13.5` or `11.0.10_1.5.1_2.13.5`)
