### ISSUE TITLE
java.io.IOException: Resource deadlock avoided

### ISSUE THREAD

**Issue by taylorleese** [sbt/sbt#650]
Resource deadlock occurs when running sbt test on multiple projects simultaneously. I've experienced this locally as well as via Jenkins.

``` bash
java.io.IOException: Resource deadlock avoided
    at sun.nio.ch.FileChannelImpl.lock0(Native Method)
    at sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:832)
    at java.nio.channels.FileChannel.lock(FileChannel.java:860)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:69)
    at xsbt.boot.Locks$GlobalLock.withChannelRetries$1(Locks.scala:58)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:79)
    at xsbt.boot.Using$.withResource(Using.scala:11)
    at xsbt.boot.Using$.apply(Using.scala:10)
    at xsbt.boot.Locks$GlobalLock.liftedTree1$1(Locks.scala:51)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:51)
    at xsbt.boot.Locks$.apply0(Locks.scala:30)
    at xsbt.boot.Locks$.apply(Locks.scala:27)
    at sbt.ComponentManager.lock(ComponentManager.scala:50)
    at sbt.ComponentManager.lockLocalCache(ComponentManager.scala:47)
    at sbt.ComponentManager.files(ComponentManager.scala:44)
    at sbt.ComponentManager.file(ComponentManager.scala:53)
    at sbt.compiler.ComponentCompiler.getPrecompiled(ComponentCompiler.scala:41)
    at sbt.compiler.ComponentCompiler.apply(ComponentCompiler.scala:36)
    at sbt.compiler.ComponentCompiler$$anon$1.apply(ComponentCompiler.scala:25)
    at sbt.compiler.AnalyzingCompiler.loader(AnalyzingCompiler.scala:83)
    at sbt.compiler.AnalyzingCompiler.getInterfaceClass(AnalyzingCompiler.scala:88)
    at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:70)
    at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:35)
    at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:29)
    at sbt.compiler.AggressiveCompile$$anonfun$4$$anonfun$compileScala$1$1.apply$mcV$sp(AggressiveCompile.scala:71)
    at sbt.compiler.AggressiveCompile$$anonfun$4$$anonfun$compileScala$1$1.apply(AggressiveCompile.scala:71)
    at sbt.compiler.AggressiveCompile$$anonfun$4$$anonfun$compileScala$1$1.apply(AggressiveCompile.scala:71)
    at sbt.compiler.AggressiveCompile.sbt$compiler$AggressiveCompile$$timed(AggressiveCompile.scala:101)
    at sbt.compiler.AggressiveCompile$$anonfun$4.compileScala$1(AggressiveCompile.scala:70)
    at sbt.compiler.AggressiveCompile$$anonfun$4.apply(AggressiveCompile.scala:88)
    at sbt.compiler.AggressiveCompile$$anonfun$4.apply(AggressiveCompile.scala:60)
    at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:24)
    at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:22)
    at sbt.inc.Incremental$.cycle(Incremental.scala:40)
    at sbt.inc.Incremental$.compile(Incremental.scala:25)
    at sbt.inc.IncrementalCompile$.apply(Compile.scala:20)
    at sbt.compiler.AggressiveCompile.compile2(AggressiveCompile.scala:96)
    at sbt.compiler.AggressiveCompile.compile1(AggressiveCompile.scala:44)
    at sbt.compiler.AggressiveCompile.apply(AggressiveCompile.scala:31)
    at sbt.Compiler$.apply(Compiler.scala:79)
    at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:572)
    at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:572)
    at sbt.Scoped$$anonfun$hf2$1.apply(Structure.scala:578)
    at sbt.Scoped$$anonfun$hf2$1.apply(Structure.scala:578)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:49)
    at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
    at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:41)
    at sbt.std.Transform$$anon$5.work(System.scala:71)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.Execute.work(Execute.scala:238)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:680)
```

**Comment by harrah** [comment]
What sbt version and what Java version?  I will try to reproduce this, but if I cannot, are you able to run sbt built from source or a temporary binary in order to get additional information?

**Comment by taylorleese** [comment]
I've seen it with both 0.12.1 and 0.12.2. Not sure about earlier versions. I can try running with a temporary binary if you'd like. Just let me know.

``` bash
taylor:billing taylor$ java -version
java version "1.6.0_37"
Java(TM) SE Runtime Environment (build 1.6.0_37-b06-434-11M3909)
Java HotSpot(TM) 64-Bit Server VM (build 20.12-b01-434, mixed mode)
```

**Comment by harrah** [comment]
I've reproduced this, but is isn't easily repeatable or minimzed enough to start doing anything with it yet.

**Comment by taylorleese** [comment]
It happens to us in Jenkins whenever we have about > 3 builds running at once.

**Comment by harrah** [comment]
Diagnosis: https://gist.github.com/harrah/4714661

**Comment by harrah** [comment]
Possible workarounds:
1. Only ever acquire a lock on the same, single file within the whole jvm.
2. Only ever acquire one lock at a time within the whole jvm.
3. Require locks be acquired according to a jvm-wide ordering. For locks 1,2,3,... require 1 be acquired in order to acquire 2, 1+2 to acquire 3, ...
4. Fork a special process for each file lock that accepts lock/unlock commands.
5. Trap the exception and try again.

Going with 5.  4-5 are questionable solutions, but 1-3 would increase contention for the common case of a single process.  Of 4 and 5, 5 seemed the least questionable and the least work.

**Comment by taylorleese** [comment]
Great, thanks for working through this. It will be a big help.

**Comment by harrah** [comment]
I forgot to mention that this fix is restricted to the launcher, so if you were so inclined, you could apply the patch to the 0.12.2 branch, run 'sbt proguard', and use the resulting launcher in place of the official 0.12.2 one without compatibility problems.

**Comment by ijuma** [comment]
@harrah, I have a question regarding the comment about this being restricted to the launcher. Does that mean that a launcher upgrade will be needed to get this fix?

**Comment by harrah** [comment]
Yes.

**Comment by ijuma** [comment]
Thanks, good to know. (we ran into this a couple of times yesterday and today)

**Comment by taylorleese** [comment]
I'm still seeing this with 0.12.3 unfortunately. Is the milestone correct as 0.12.3 in the issue? Here's the stack trace:

``` scala
Waiting for lock on /home/jenkins/.ivy2/.sbt.ivy.lock to be available...
java.io.IOException: Resource deadlock avoided
    at sun.nio.ch.FileChannelImpl.lock0(Native Method)
    at sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:832)
    at java.nio.channels.FileChannel.lock(FileChannel.java:860)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:69)
    at xsbt.boot.Locks$GlobalLock.withChannelRetries$1(Locks.scala:58)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:79)
    at xsbt.boot.Using$.withResource(Using.scala:11)
    at xsbt.boot.Using$.apply(Using.scala:10)
    at xsbt.boot.Locks$GlobalLock.liftedTree1$1(Locks.scala:51)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:51)
    at xsbt.boot.Locks$.apply0(Locks.scala:30)
    at xsbt.boot.Locks$.apply(Locks.scala:27)
    at sbt.IvySbt.withDefaultLogger(Ivy.scala:61)
    at sbt.IvySbt.withIvy(Ivy.scala:102)
    at sbt.IvySbt.withIvy(Ivy.scala:98)
    at sbt.IvySbt$Module.withModule(Ivy.scala:117)
    at sbt.IvySbt$Module.moduleDescriptor(Ivy.scala:119)
    at sbt.IvySbt$Module.dependencyMapping(Ivy.scala:122)
    at sbt.Classpaths$$anonfun$depMap$3$$anonfun$apply$51.apply(Defaults.scala:1020)
    at sbt.Classpaths$$anonfun$depMap$3$$anonfun$apply$51.apply(Defaults.scala:1020)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:233)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:233)
    at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
    at scala.collection.immutable.List.foreach(List.scala:76)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:233)
    at scala.collection.immutable.List.map(List.scala:76)
    at sbt.Classpaths$$anonfun$depMap$3.apply(Defaults.scala:1020)
    at sbt.Classpaths$$anonfun$depMap$3.apply(Defaults.scala:1019)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:49)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:49)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:41)
    at sbt.std.Transform$$anon$5.work(System.scala:71)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.Execute.work(Execute.scala:238)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
java.io.IOException: Resource deadlock avoided
    at sun.nio.ch.FileChannelImpl.lock0(Native Method)
    at sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:832)
    at java.nio.channels.FileChannel.lock(FileChannel.java:860)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:69)
    at xsbt.boot.Locks$GlobalLock.withChannelRetries$1(Locks.scala:58)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:79)
    at xsbt.boot.Using$.withResource(Using.scala:11)
    at xsbt.boot.Using$.apply(Using.scala:10)
    at xsbt.boot.Locks$GlobalLock.liftedTree1$1(Locks.scala:51)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:51)
    at xsbt.boot.Locks$.apply0(Locks.scala:30)
    at xsbt.boot.Locks$.apply(Locks.scala:27)
    at sbt.IvySbt.withDefaultLogger(Ivy.scala:61)
    at sbt.IvySbt.withIvy(Ivy.scala:102)
    at sbt.IvySbt.withIvy(Ivy.scala:98)
    at sbt.IvySbt$Module.withModule(Ivy.scala:117)
    at sbt.IvySbt$Module.moduleDescriptor(Ivy.scala:119)
    at sbt.IvySbt$Module.dependencyMapping(Ivy.scala:122)
    at sbt.Classpaths$$anonfun$depMap$3$$anonfun$apply$51.apply(Defaults.scala:1020)
    at sbt.Classpaths$$anonfun$depMap$3$$anonfun$apply$51.apply(Defaults.scala:1020)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:233)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:233)
    at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
    at scala.collection.immutable.List.foreach(List.scala:76)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:233)
    at scala.collection.immutable.List.map(List.scala:76)
    at sbt.Classpaths$$anonfun$depMap$3.apply(Defaults.scala:1020)
    at sbt.Classpaths$$anonfun$depMap$3.apply(Defaults.scala:1019)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:49)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:49)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:41)
    at sbt.std.Transform$$anon$5.work(System.scala:71)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.Execute.work(Execute.scala:238)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
```

**Comment by harrah** [comment]
Yes, the tag is correct.  Make sure you are using the 0.12.3 launcher, since this was a launcher bug.  The stack trace doesn't look like it came from 0.12.3, but I can't be certain.
