### ISSUE TITLE
Caused by: java.lang.RuntimeException: java.io.IOException: resource not found on classpath: conf/application.conf

### ISSUE THREAD

**Issue by Nikitha963** [sbt/sbt#6507]
I am  facing  issue like while migarting from play 2.2.6 to 2.6.6 and also sbt 0.13.0 to 1.3.0 and scala 2.10.3 to 2.12.3

when I execute sbt run :

[error] stack trace is suppressed; run last Compile / playEbeanModels for the full output
[error] (Compile / playEbeanModels) com.typesafe.config.ConfigException$IO: conf/application.conf: java.io.IOException: resource not found on classpath: conf/application.conf
[error] application - 

! @7jke665m6 - Internal server error, for (GET) [/] ->
 
play.sbt.PlayExceptions$UnexpectedException: Unexpected exception[RuntimeException: com.typesafe.config.ConfigException$IO: conf/application.conf: java.io.IOException: resource not found on classpath: conf/application.conf]
	at play.sbt.run.PlayReload$.$anonfun$taskFailureHandler$1(PlayReload.scala:36)
	at scala.Option.map(Option.scala:163)
	at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:29)
	at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:25)
	at play.sbt.run.PlayReload$.$anonfun$compile$3(PlayReload.scala:52)
	at scala.util.Either$LeftProjection.map(Either.scala:573)
	at play.sbt.run.PlayReload$.compile(PlayReload.scala:52)
	at play.sbt.run.PlayRun$.$anonfun$playRunTask$4(PlayRun.scala:77)
	at play.runsupport.Reloader.$anonfun$reload$1(Reloader.scala:413)
	at play.runsupport.Reloader$$anon$1.run(Reloader.scala:51)
Caused by: java.lang.RuntimeException: com.typesafe.config.ConfigException$IO: conf/application.conf: java.io.IOException: resource not found on classpath: conf/application.conf
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:188)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
	at com.typesafe.config.impl.Parseable.parse(Parseable.java:299)
	at com.typesafe.config.ConfigFactory.parseResources(ConfigFactory.java:957)
	at com.typesafe.config.ConfigFactory.parseResources(ConfigFactory.java:885)
	at com.typesafe.config.DefaultConfigLoadingStrategy.parseApplicationConfig(DefaultConfigLoadingStrategy.java:49)
	at com.typesafe.config.ConfigFactory.defaultApplication(ConfigFactory.java:473)
	at com.typesafe.config.ConfigFactory$1.call(ConfigFactory.java:259)
	at com.typesafe.config.ConfigFactory$1.call(ConfigFactory.java:256)
	at com.typesafe.config.impl.ConfigImpl$LoaderCache.getOrElseUpdate(ConfigImpl.java:65)
Caused by: java.lang.RuntimeException: java.io.IOException: resource not found on classpath: conf/application.conf
	at com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:735)
	at com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:710)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
	at com.typesafe.config.impl.Parseable.parse(Parseable.java:299)
	at com.typesafe.config.ConfigFactory.parseResources(ConfigFactory.java:957)
	at com.typesafe.config.ConfigFactory.parseResources(ConfigFactory.java:885)
	at com.typesafe.config.DefaultConfigLoadingStrategy.parseApplicationConfig(DefaultConfigLoadingStrategy.java:49)
	at com.typesafe.config.ConfigFactory.defaultApplication(ConfigFactory.java:473)
	at com.typesafe.config.ConfigFactory$1.call(ConfigFactory.java:259)

Please help me in resolving this

**Comment by eed3si9n** [comment]
We use GitHub issue mostly to track bugs and tasks on sbt development. If you need help, please check this out - https://www.scala-sbt.org/support.html

**Comment by mkurz** [comment]
@Nikitha963 you should not upgrade from Play 2.2 to 2.6 directly. You should upgrade release by release and read the migration guides for each release.
