### ISSUE TITLE
sbt updateClassifiers failed while working with sbt-lm-coursier

### ISSUE THREAD

**Issue by kinglywork** [sbt/sbt#6508]
## steps

sbt version: 1.5.0
sbt-lm-coursier version: 2.0.8
scala version: 2.13.5
IDE: Intellij idea

## problem

while load sbt changes from IDE, there is an error occurs, exception stack trace is:

```
[IJ]last updateClassifiers
[error] java.lang.NoSuchMethodException: sbt.internal.LibraryManagement$.cachedUpdate(sbt.librarymanagement.DependencyResolution, sbt.librarymanagement.ModuleDescriptor, sbt.util.CacheStoreFactory, java.lang.String, sbt.librarymanagement.UpdateConfiguration, scala.Function1, boolean, boolean, boolean, sbt.librarymanagement.UnresolvedWarningConfiguration, sbt.librarymanagement.EvictionWarningOptions, boolean, sbt.internal.librarymanagement.CompatibilityWarningOptions, boolean, boolean, sbt.util.Logger)
[error] 	at java.base/java.lang.Class.getMethod(Class.java:2109)
[error] 	at sbt.hack.Foo$.reflMethod$Method1(Foo.scala:99)
[error] 	at sbt.hack.Foo$.$anonfun$updateTask$5(Foo.scala:99)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] (updateClassifiers) java.lang.NoSuchMethodException: sbt.internal.LibraryManagement$.cachedUpdate(sbt.librarymanagement.DependencyResolution, sbt.librarymanagement.ModuleDescriptor, sbt.util.CacheStoreFactory, java.lang.String, sbt.librarymanagement.UpdateConfiguration, scala.Function1, boolean, boolean, boolean, sbt.librarymanagement.UnresolvedWarningConfiguration, sbt.librarymanagement.EvictionWarningOptions, boolean, sbt.internal.librarymanagement.CompatibilityWarningOptions, boolean, boolean, sbt.util.Logger)
[IJ]
```

this error occurs from sbt 1.5.0, 1.4.9 works well

## expectation

while load sbt changes from IDE, no error occurs and can load successfully

**Comment by eed3si9n** [comment]
@kinglywork Thanks for the report. From the stack trace it looks like the error is coming from sbt-coursier actually:

```
[error] 	at sbt.hack.Foo$.reflMethod$Method1(Foo.scala:99)
[error] 	at sbt.hack.Foo$.$anonfun$updateTask$5(Foo.scala:99)
```

I think it's trying to call sbt's internal function `sbt.internal.LibraryManagement.cachedUpdate`, and every time we change it it breaks. Could you report this to coursier/coursier instead please?
