### ISSUE TITLE
Proxy repositories `bootOnly` command does not include global plugins

### ISSUE THREAD

**Issue by arkban** [sbt/sbt#6519]
## steps

I tried to run SBT 1.5.2 with a custom [`repositories`](https://www.scala-sbt.org/1.x/docs/Proxy-Repositories.html). The resolver that holds the SBT dependencies -- i.e. SBT itself -- specified the [`bootOnly`](https://www.scala-sbt.org/1.x/docs/Launcher-Configuration.html#3.+Repositories+Section0) command. 

## problem

When SBT gets to resolving dependencies for global plugins it fails.

I think this is a bug because the [docs say](https://www.scala-sbt.org/1.x/docs/Launcher-Configuration.html#3.+Repositories+Section):

> The bootOnly string is used to tell Ivy to only use this repository during startup. i.e. To find sbt’s own JARs and the JARs of any plugins. Repositories with the bootOnly string will not be used for build-time dependency resolution. 

## expectation

I think that it should work, i.e. at least get me to the SBT prompt.

## notes

Cribbed `repositories` file (sorry for the cribbing):
```
[repositories]
    local
    remote-repos: https://my.company.artifactory/remote-repos/, bootOnly
```

Custom `.sbtopts` to make SBT use the above custom `repositories` file:
```
-Dsbt.override.build.repos=true
-Dsbt.repository.config="./repositories"
```

Output from SBT (with `-debug` flag):
```
 sbt --debug
[addSbt] arg = '-debug'
[sbt_options] declare -a sbt_options='()'
[process_args] java_version = '8'
[addMemory] arg = '1024'
[addJava] arg = '-Xms1024m'
[addJava] arg = '-Xmx1024m'
[addJava] arg = '-Xss4M'
[addJava] arg = '-XX:ReservedCodeCacheSize=128m'
# Executing command line:
java
-Dfile.encoding=UTF-8
-Dsbt.override.build.repos=true
-Dsbt.repository.config=./repositories
-Xms1024m
-Xmx1024m
-Xss4M
-XX:ReservedCodeCacheSize=128m
-jar
/usr/local/Cellar/sbt/1.5.2/libexec/bin/sbt-launch.jar
-debug

[debug] not up to date. inChanged = true, force = false
[debug] Updating ProjectRef(uri("file:/Users/arkban/.sbt/1.0/plugins/"), "global-plugins")...
[info] Updating
[info] Resolved  dependencies
[warn]
[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading org.scala-sbt:sbt:1.5.2
[error]   Not found
[error]   Not found
[error]   not found: /Users/arkban/.ivy2/local/org.scala-sbt/sbt/1.5.2/ivys/ivy.xml
[error]   unauthorized: https://my.company.artifactory/remote-repos/org/scala-sbt/sbt/1.5.2/sbt-1.5.2.pom (Artifactory Realm)
[error]         at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:258)
[error]         at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:227)
[error]         at scala.util.Either$LeftProjection.map(Either.scala:573)
[error]         at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:227)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:59)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
[error]         at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
[error]         at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3667)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.scala-sbt:sbt:1.5.2
[error]   Not found
[error]   Not found
[error]   not found: /Users/arkban/.ivy2/local/org.scala-sbt/sbt/1.5.2/ivys/ivy.xml
[error]   unauthorized: https://my.company.artifactory/remote-repos/org/scala-sbt/sbt/1.5.2/sbt-1.5.2.pom (Artifactory Realm)
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
[debug] > Exec(early(addDefaultCommands), None, None)
[debug] > Exec(early(addDefaultCommands), None, None)
[debug] > Exec(addDefaultCommands, None, None)
[debug] > Exec(early(initialize), None, None)
[debug] > Exec(initialize, None, None)
[debug] > Exec(-debug, None, None)
[debug] > Exec(debug, None, None)
[debug] > Exec(boot, None, None)
[debug] > Exec(writeSbtVersion, None, None)
[debug] > Exec(reload, None, None)
[debug] > Exec(sbtStashOnFailure, None, None)
[debug] > Exec(onFailure loadFailed, None, None)
[debug] > Exec(loadp, None, None)
[info] welcome to sbt 1.5.2 (AdoptOpenJDK Java 1.8.0_292)
[debug]       Load.loadUnit: plugins took 219.304033ms
[debug]       Load.loadUnit: defsScala took 0.433226ms
[debug] [Loading] Scanning directory /Users/arkban/.sbt/1.0/plugins
[debug] [Loading] Found non-root projects
[debug] [Loading] Done in /Users/arkban/.sbt/1.0/plugins, returning: ()
[debug] deducing auto plugins based on known facts Set(Atom(sbt.plugins.CorePlugin)) and clauses Clauses(Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.IvyPlugin)))
[debug] Clause(Atom(sbt.ScriptedPlugin),Set(Atom(sbt.plugins.JvmPlugin)))
[debug] Clause(Atom(sbt.plugins.SbtPlugin),Set(Atom(sbt.ScriptedPlugin)))
[debug] Clause(Atom(sbt.plugins.SemanticdbPlugin),Set(Atom(sbt.plugins.JvmPlugin)))
[debug] Clause(Atom(sbt.plugins.JUnitXmlReportPlugin),Set(Atom(sbt.plugins.JvmPlugin)))
[debug] Clause(Atom(sbt.plugins.MiniDependencyTreePlugin),Set(Atom(sbt.plugins.JvmPlugin)))
[debug] Clause(Atom(sbt.plugins.CorePlugin),Set(Atom(sbt.plugins.IvyPlugin)))
[debug] Clause(Atom(sbt.plugins.IvyPlugin),Set(Atom(sbt.plugins.JvmPlugin)))
[debug] Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.SemanticdbPlugin)))
[debug] Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.JUnitXmlReportPlugin)))
[debug] Clause(Atom(sbt.plugins.CorePlugin),Set(Atom(sbt.plugins.Giter8TemplatePlugin)))
[debug] Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.MiniDependencyTreePlugin))))
[debug]   :: deduced result: Matched(sbt.plugins.CorePlugin,sbt.plugins.Giter8TemplatePlugin,sbt.plugins.IvyPlugin,sbt.plugins.JvmPlugin,sbt.plugins.MiniDependencyTreePlugin,sbt.plugins.JUnitXmlReportPlugin,sbt.plugins.SemanticdbPlugin)
[debug] Plugins.deducer#function took 20.017885 ms
[debug]           Load.resolveProject(global-plugins) took 53.991966ms
[debug]         Load.loadTransitive: finalizeProject(Project(id global-plugins, base: /Users/arkban/.sbt/1.0/plugins, plugins: List(<none>))) took 111.89529ms
[debug] [Loading] Done in /Users/arkban/.sbt/1.0/plugins, returning: (global-plugins)
[debug]       Load.loadUnit: loadedProjectsRaw took 137.040744ms
[debug]       Load.loadUnit: cleanEvalClasses took 0.304672ms
[debug]     Load.loadUnit(file:/Users/arkban/1.0/plugins/, ...) took 366.90442ms
[debug]   Load.apply: load took 642.689296ms
[debug]   Load.apply: resolveProjects took 8.175474ms
[debug]   Load.apply: finalTransforms took 76.293559ms
[debug]   Load.apply: config.delegates took 9.83604ms
[debug]   Load.apply: Def.make(settings)... took 340.66936ms
[debug]   Load.apply: structureIndex took 88.629671ms
[debug]   Load.apply: mkStreams took 1.626587ms
[info] loading global plugins from /Users/arkbanp/.sbt/1.0/plugins
[debug] Running task... Cancel: Signal, check cycles: false, forcegc: true
[info] Updating
[info] Resolved  dependencies
[warn]
[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading org.scala-sbt:sbt:1.5.2
[error]   Not found
... same error as above ...
```

When I remove the `bootOnly` flag from `repositories` it works fine.

**Comment by eed3si9n** [comment]
Thanks for the report.

Looking at the error message, it actually tried to hit your Artifactory as specified but just failed to authenticate?

```
[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading org.scala-sbt:sbt:1.5.2
[error]   Not found
[error]   Not found
[error]   not found: /Users/arkban/.ivy2/local/org.scala-sbt/sbt/1.5.2/ivys/ivy.xml
[error]   unauthorized: https://my.company.artifactory/remote-repos/org/scala-sbt/sbt/1.5.2/sbt-1.5.2.pom (Artifactory Realm)
[error]         at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:258)
```

**Comment by arkban** [comment]
Looking back at this, I'm going to chalk this one up to "user error". 

I was doing a _lot_ of SBT fiddling and I cannot say for certain this wasn't a PEBKAC.

I appreciate you taking the time to respond!
