### ISSUE TITLE
FileNotFoundException: sbt-load.sock when running tests via SbtDriver

### ISSUE THREAD

**Issue by scf37** [sbt/sbt#6520]
## steps
1. Checkout https://github.com/scf37/sbt-overwatch/tree/sbt-bug
2. cd test
3. sbt test

## problem

Problem appeared when upgrading from sbt 1.1.x to 1.5.2 due to Scala 3 migration.
```
[info] Test:
[info] - overwatch should react on file change/create/delete *** FAILED ***
[info]   java.io.FileNotFoundException: /home/asm/mywork/sbt-overwatch/test/project/target/sbt-load.sock (No such device or address)
[info]   at java.io.FileInputStream.open0(Native Method)
[info]   at java.io.FileInputStream.open(FileInputStream.java:195)
[info]   at java.io.FileInputStream.<init>(FileInputStream.java:138)
[info]   at org.apache.commons.io.FileUtils.doCopyFile(FileUtils.java:1141)
[info]   at org.apache.commons.io.FileUtils.doCopyDirectory(FileUtils.java:1446)
[info]   at org.apache.commons.io.FileUtils.doCopyDirectory(FileUtils.java:1444)
[info]   at org.apache.commons.io.FileUtils.doCopyDirectory(FileUtils.java:1444)
[info]   at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1388)
[info]   at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1268)
[info]   at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1237)
[info]   ...
[info] Run completed in 323 milliseconds.
```

## expectation

Successful compilation

**Comment by scf37** [comment]
Workaround: `echo "; +test; exit" | sbt`

**Comment by eed3si9n** [comment]
Sorry about the late response. I can't reproduce this using latest sbt 1.11.7, so closing this for now.
