### ISSUE TITLE
BSP Server doesn't work on arm64 (M1 Mac)

### ISSUE THREAD

**Issue by quelgar** [sbt/sbt#6531]
## steps

```
$ uname -rsvm
Darwin 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 arm64
```

```
$ java -version
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment Zulu16.30+19-CA (build 16.0.1+9)
OpenJDK 64-Bit Server VM Zulu16.30+19-CA (build 16.0.1+9, mixed mode)
```

```
$ sbt
[info] [launcher] getting org.scala-sbt sbt 1.5.3  (this may take some time)...
[info] [launcher] getting Scala 2.12.14 (for sbt)...
[info] welcome to sbt 1.5.3 (Azul Systems, Inc. Java 16.0.1)
```

Then launch IntelliJ, import the project as BSP with bloop disabled.

## problem

SBT itself works fine, but when IntelliJ tries to connect via BSP:

```
Exception in thread "sbt-network-1-write-thread" java.lang.NoClassDefFoundError: Could not initialize class org.scalasbt.ipcsocket.UnixDomainSocketLibrary
	at org.scalasbt.ipcsocket.JNAUnixDomainSocketLibraryProvider.write(UnixDomainSocketLibrary.java:247)
	at org.scalasbt.ipcsocket.UnixDomainSocket$UnixDomainSocketOutputStream.doWrite(UnixDomainSocket.java:185)
	at org.scalasbt.ipcsocket.UnixDomainSocket$UnixDomainSocketOutputStream.write(UnixDomainSocket.java:176)
	at java.base/java.io.OutputStream.write(OutputStream.java:127)
	at sbt.internal.server.NetworkChannel.impl$1(NetworkChannel.scala:345)
	at sbt.internal.server.NetworkChannel.$anonfun$writeThread$1(NetworkChannel.scala:360)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

## expectation

On an Intel Mac, IntelliJ connects successfully to the running SBT via BSP.

**Comment by eed3si9n** [comment]
Thanks for the report. This was unexpected since I think we did release a new ipcsocket with M1 support.

I also vaguely remember that JNA wasn't out for M1 so we had to switch to JNI iirc, so the fact that stack trace shows JNA could be a hint.

**Comment by eed3si9n** [comment]
The following system properties are checked:

https://github.com/sbt/sbt/blob/9e98b6daa1c5021b852661feb2a5b263bda9ce67/main-command/src/main/java/sbt/internal/BootServerSocket.java#L352-L355

Could you also try running with `-Dsbt.ipcsocket.jni=true` please?

**Comment by quelgar** [comment]
`sbt -Dsbt.ipcsocket.jni=true` produced the same error.

```
scala> sys.props("os.name")
val res0: String = Mac OS X

scala> sys.props("os.arch")
val res1: String = aarch64
```

Weird.

**Comment by quelgar** [comment]
I added some `println`s. The `XXX` lines are from sbt, the `YYY` from ipcsocket. Startup is fine:

```
[info] deleting /Users/lachlanodea/.sbt/boot/scala-2.12.14/org.scala-sbt/sbt/1.5.4-SNAPSHOT
[info] shutting down sbt server
[info] [launcher] getting org.scala-sbt sbt 1.5.4-SNAPSHOT  (this may take some time)...
XXX: jni=true
YYY: useJNI=true
YYY: JNIUnixDomainSocketLibraryProvider instance
[info] welcome to sbt 1.5.4-SNAPSHOT (Azul Systems, Inc. Java 16.0.1)
[info] loading settings for project zio-nio-build-build from metals.sbt ...
[info] loading project definition from /Users/lachlanodea/Code/zio-nio/project/project
[info] loading settings for project zio-nio-build from metals.sbt,plugins.sbt ...
[info] loading project definition from /Users/lachlanodea/Code/zio-nio/project
[info] loading settings for project zio-nio from build.sbt ...
[info] set current project to zio-nio (in build file:/Users/lachlanodea/Code/zio-nio/)
YYY: useJNI=true
YYY: JNIUnixDomainSocketLibraryProvider instance
[warn] XXX: useJNI=true
YYY: useJNI=true
YYY: JNIUnixDomainSocketLibraryProvider instance
[info] sbt server started at local:///Users/lachlanodea/.sbt/1.0/server/ca038c0e548b9ec41c6d/sock
[info] started sbt server
```

but when I tell the IDE to fire up the BSP connection:

```
YYY: useJNI=false
YYY: JNAUnixDomainSocketLibraryProvider instance
[info] new client connected: network-1
sbt:zio-nio> Exception in thread "sbt-network-1-write-thread" java.lang.NoClassDefFoundError: Could not initialize class org.scalasbt.ipcsocket.UnixDomainSocketLibrary
```

I can't find where in sbt this last call to `UnixDomainSocketLibraryProvider` is coming from though.

**Comment by eed3si9n** [comment]
Probably here 
 - https://github.com/sbt/ipcsocket/blob/d5e67af724877eca42021b0d33fce7d60e795d19/src/main/java/org/scalasbt/ipcsocket/UnixDomainSocket.java#L71

```java
  /** Creates a Unix domain socket backed by a native file descriptor. */
  public UnixDomainSocket(int fd, boolean useJNI) {
    provider = UnixDomainSocketLibraryProvider.get(useJNI);
```

**Comment by quelgar** [comment]
Ok I fixed it, the problem was in ipcsocket, PR coming. Thanks for the pointers.

**Comment by mkurz** [comment]
Can be closed now?

**Comment by eed3si9n** [comment]
we can keep it open till ipcsocket is updated.

**Comment by eed3si9n** [comment]
I've released two versions of ipcsocket:
- 1.3.1 with just the fixes - https://github.com/sbt/ipcsocket/releases/tag/v1.3.1
- 1.4.0 that upgrades JNA - https://github.com/sbt/ipcsocket/releases/tag/v1.4.0
