### ISSUE TITLE
Cross-compiled version but with the same versioned library causing runtime issue.

### ISSUE THREAD

**Issue by Swoorup** [sbt/sbt#6578]
## steps

Reproduction available as [sbt-bug.zip](https://github.com/sbt/sbt/files/6754273/sbt-bug.zip).

```scala
val scala3Version = "3.0.1-RC2"

lazy val catsCoreV          = "2.6.1"
lazy val catsEffectV        = "3.1.1"

lazy val root = project
  .in(file("."))
  .settings(
    name := "scala3-simple",
    version := "0.1.0",

    scalaVersion := scala3Version,
    libraryDependencies ++= Seq(
      "org.typelevel"                 %% "cats-core"                     % catsCoreV,
      "com.novocode" % "junit-interface" % "0.11" % "test"
    ),
    libraryDependencies ++= Seq(
      "io.github.paoloboni" %% "binance-scala-client" % "1.2.3"
    ).map(_.cross(CrossVersion.for3Use2_13))
  )
```

* sbt - 1.5.4
* scala - 3.0.1-RC1
* Unpack the zip and `sbt run` 

Here, cats is specified as dependency for both the root project(scala 3) and as a result of transitive dependency (scala 2.13 via binance-scala-client). It appears sbt doesn't detect this and issue becomes a runtime one.

## problem

```
[error] (run-main-0) java.lang.NoSuchMethodError: 'void cats.SemigroupK.$init$(cats.SemigroupK)'
[error] java.lang.NoSuchMethodError: 'void cats.SemigroupK.$init$(cats.SemigroupK)'
[error]         at cats.effect.IO$IOSemigroupK.<init>(IO.scala:1248)
[error]         at cats.effect.IO$.<clinit>(IO.scala:1246)
[error]         at PriceMonitor$.run(Main.scala:18)
[error]         at cats.effect.IOApp.main(IOApp.scala:70)
[error]         at cats.effect.IOApp.main$(IOApp.scala:35)
[error]         at PriceMonitor$.main(Main.scala:10)
[error]         at PriceMonitor.main(Main.scala)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error] stack trace is suppressed; run last Compile / bgRun for the full output
[error] Nonzero exit code: 1
[error] (Compile / run) Nonzero exit code: 1
[error] Total time: 2 s, completed 2 Jul. 2021, 9:20:42 pm
```

## expectation

At least runtime error shouldn't have occurred.

**Comment by smarter** [comment]
For reference, the code in sbt which is supposed to detect cross-version conflicts is in https://github.com/sbt/librarymanagement/blob/564119c40407a1663043441059a5f923ad98ab73/core/src/main/scala/sbt/librarymanagement/ConflictWarning.scala#L39

**Comment by eed3si9n** [comment]
@Swoorup Thanks for the bug report with a repro project!

**Comment by eed3si9n** [comment]
```scala
scala> val CrossSuffixPattern = """(.+)_(\d+\.\d+(?:\.\d+)?(?:-.+)?)""".r
val CrossSuffixPattern: scala.util.matching.Regex = (.+)_(\d+\.\d+(?:\.\d+)?(?:-.+)?)

scala> "cats-core_3" match { case CrossSuffixPattern(raw, _) => raw }
scala.MatchError: cats-core_3 (of class java.lang.String)
  at repl$.rs$line$2$.<clinit>(rs$line$2:1)
  at repl$.rs$line$2.res0(rs$line$2)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at dotty.tools.repl.Rendering.$anonfun$3(Rendering.scala:115)
  at scala.Option.map(Option.scala:242)
```

**Comment by eed3si9n** [comment]
I guess we never caught this during RC-x because they all had dots in the version number.
