### ISSUE TITLE
sbt fails with java.lang.NoClassDefFoundError: scala/Serializable

### ISSUE THREAD

**Issue by djinnome** [sbt/sbt#6587]
## steps

On a Mac OSX 10.14.6, I run
```bash
$ brew install openjdk
$ brew install sbt
$ sbt sbtVersion
```
## problem

This is the output:

```bash
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
java.lang.NoClassDefFoundError: scala/Serializable
	at sbt.internal.ClassLoaderWarmup$.warmup(XMainConfiguration.scala:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:82)
	at sbt.xMain.run(Main.scala:46)
	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
	at xsbt.boot.Launch$.run(Launch.scala:149)
	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
	at xsbt.boot.Launch$.launch(Launch.scala:159)
	at xsbt.boot.Launch$.apply(Launch.scala:44)
	at xsbt.boot.Launch$.apply(Launch.scala:21)
	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
	at xsbt.boot.Boot$.run(Boot.scala:73)
	at xsbt.boot.Boot$.main(Boot.scala:21)
	at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.ClassNotFoundException: scala.Serializable
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:436)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 18 more
[error] [launcher] error during sbt launcher: java.lang.NoClassDefFoundError: scala/Serializable
```
## expectation

I was hoping for something like  
```
sbt version 1.5.4
```

## notes
Is it some `CLASSPATH` issue?

**Comment by eed3si9n** [comment]
We only test sbt using JDK 8 and JDK 11. Homebrew maintainers have added a dependency to JDK 13 because they want to use more brew dependencies (brew#50649). This causes sbt to use JDK 13 even when java available on PATH is JDK 8 or 11.

My usual suggestion is to use jEnv or remove Homebrew sbt, and use SDKMAN instead.

**Comment by djinnome** [comment]
After removing all traces of sbt and ensuring I have the right version of java installed, I try again:

```bash
$ brew uninstall sbt
$ sdk uninstall sbt 1.5.4
$ rm -rf /usr/local/share/sbt
$ cd /usr/local/share
$ jenv version
1.8 (set by JENV_VERSION environment variable)
$ wget -c https://github.com/sbt/sbt/releases/download/v1.4.0/sbt-1.4.0.tgz
$ tar xzvf sbt-1.4.0.tar.tgz
$ /usr/local/share/sbt/bin/sbt sbtVersion
[info] welcome to sbt 1.5.4 (Oracle Corporation Java 1.8.0_282)
[info] loading project definition from /usr/local/share/project
[info] set current project to share (in build file:/usr/local/share/)
[info] 1.5.4
```

This is progress, but why is it displaying version `1.5.4`, when I clearly downloaded version `1.4.0`?


Second question: if I change directories, why do I get the same problem again?

```
$ cd /usr/local/share/sbt
$ /usr/local/share/sbt/bin/sbt sbtVersion
java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: scala/Serializable
	at sbt.internal.ClassLoaderWarmup$.warmup(XMainConfiguration.scala:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:82)
	at sbt.xMain.run(Main.scala:46)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:131)
	at xsbt.boot.Launch$.run(Launch.scala:111)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
	at xsbt.boot.Launch$.launch(Launch.scala:120)
	at xsbt.boot.Launch$.apply(Launch.scala:20)
	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
	at xsbt.boot.Boot$.main(Boot.scala:18)
	at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.NoClassDefFoundError: scala/Serializable
	... 16 more
Caused by: java.lang.ClassNotFoundException: scala.Serializable
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 16 more
[error] [launcher] error during sbt launcher: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: scala/Serializable
```

**Comment by eed3si9n** [comment]
> This is progress, but why is it displaying version 1.5.4, when I clearly downloaded version 1.4.0?

What you download is a combination of `sbt` the shell script (called runner sometimes) and `sbt-launch.jar`. You can display the version of it as:

```
sbt --script-version
```

The actual sbt version that gets used is set in `project/build.properties` file to improve the repeatability of the build (as opposed what's installed on someone's laptop). We normally try to make sure that the runner + launcher is able to launch all recent versions of sbt.

I wonder if I messed something up so one of the combinations no longer work. It seems like for some reason the launcher now thinks sbt is an Scala 2.13 application?

See

```
  [info] [launcher] getting org.scala-sbt sbt 1.4.1  (this may take some time)...
  [info] [launcher] getting Scala 2.13.3 (for sbt)...
```

in https://github.com/scala-steward-org/scala-steward/issues/2170 that has a similar error.

**Comment by eed3si9n** [comment]
```
$ sbt --script-version
1.5.4
$ mkdir -p project
$ echo "sbt.version=1.4.0" > project/build.properties
$ sbt --no-global
java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: scala/Serializable
	at sbt.internal.ClassLoaderWarmup$.warmup(XMainConfiguration.scala:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:82)
	at sbt.xMain.run(Main.scala:46)
	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
	at xsbt.boot.Launch$.run(Launch.scala:149)
	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
	at xsbt.boot.Launch$.launch(Launch.scala:159)
	at xsbt.boot.Launch$.apply(Launch.scala:44)
	at xsbt.boot.Launch$.apply(Launch.scala:21)
	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
	at xsbt.boot.Boot$.run(Boot.scala:73)
	at xsbt.boot.Boot$.main(Boot.scala:21)
	at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.NoClassDefFoundError: scala/Serializable
	... 18 more
Caused by: java.lang.ClassNotFoundException: scala.Serializable
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 18 more
[error] [launcher] error during sbt launcher: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: scala/Serializable
```

Also reproduced it on CI - https://github.com/sbt/launcher/pull/98

**Comment by eed3si9n** [comment]
I think I know what's happening.

I messed up util-interface during 1.4.x and accidentally added Scala dependency to it.
For sbt 1.4.0, 1.4.1, and 1.4.2, Scala 2.13 is added. If you use sbt 1.4.3 and onwards, it should be ok.

**Comment by djinnome** [comment]
Thanks for the clue, @eed3si9n .  I updated the `project/build.properties` to use `sbt 1.5.4` and now everything works as expected.

**Comment by eed3si9n** [comment]
Great. I added a workaround to launcher, so hopefully launcher 1.5.5 will be able to launch sbt 1.4.0 as well, even though staying on the latest is usually recommended.
