### ISSUE TITLE
Cannot runMain with Scala 3 using ScriptEngineManager

### ISSUE THREAD

**Issue by deusaquilus** [sbt/sbt#6595]
## steps

Scala 3 officially supports running in ScriptEngineManager:
https://github.com/lampepfl/dotty/blob/7627583448ddde71c3f19c8ec962f3b16f917652/tests/run-with-compiler/scripting.scala

I take this code, compile it with SBT and then use runMain:
```scala
object Example {
  def main(args: Array[String]): Unit = {
    val m = new javax.script.ScriptEngineManager(getClass().getClassLoader())
    val e = m.getEngineByName("scala")
    println(e.eval("42"))
    println(e.eval("Some(42)").asInstanceOf[Option[Int]].get)
    println(e.eval(new java.io.StringReader("42")))
  }
}
```
Then in SBT:
```
> compile
[info] compiling 1 Scala source ...
[success] Total time: 1 s, completed Jul 13, 2021 2:25:26 AM
> runMain:
[error] (run-main-1) java.lang.ClassCastException: dotty.tools.dotc.core.Symbols$NoSymbol$ cannot be cast to dotty.tools.dotc.core.Symbols$ClassSymbol
[error] java.lang.ClassCastException: dotty.tools.dotc.core.Symbols$NoSymbol$ cannot be cast to dotty.tools.dotc.core.Symbols$ClassSymbol
[error]         at dotty.tools.dotc.core.Symbols$Symbol.asClass(Symbols.scala:172)
[error]         at dotty.tools.dotc.core.Definitions.IntClass(Definitions.scala:570)
[error]         at dotty.tools.dotc.typer.Typer.typedNumber(Typer.scala:682)
[error]         at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2671)
[error]         at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2731)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2796)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2800)
[error]         at dotty.tools.dotc.typer.Namer.typedAheadExpr$$anonfun$1(Namer.scala:1377)
[error]         at dotty.tools.dotc.typer.Namer.typedAhead(Namer.scala:1364)
[error]         at dotty.tools.dotc.typer.Namer.typedAheadExpr(Namer.scala:1377)
[error]         at dotty.tools.dotc.typer.Namer.typedAheadRhs$1$$anonfun$1(Namer.scala:1505)
[error]         at dotty.tools.dotc.typer.PrepareInlineable$.dropInlineIfError(PrepareInlineable.scala:225)
[error]         at dotty.tools.dotc.typer.Namer.typedAheadRhs$2(Namer.scala:1505)
[error]         at dotty.tools.dotc.typer.Namer.rhsType$1(Namer.scala:1513)
[error]         at dotty.tools.dotc.typer.Namer.cookedRhsType$1(Namer.scala:1538)
[error]         at dotty.tools.dotc.typer.Namer.lhsType$1(Namer.scala:1539)
[error]         at dotty.tools.dotc.typer.Namer.inferredType$1(Namer.scala:1550)
[error]         at dotty.tools.dotc.typer.Namer.valOrDefDefSig(Namer.scala:1559)
[error]         at dotty.tools.dotc.typer.Namer$Completer.typeSig(Namer.scala:699)
[error]         at dotty.tools.dotc.typer.Namer$Completer.completeInCreationContext(Namer.scala:826)
[error]         at dotty.tools.dotc.typer.Namer$Completer.complete(Namer.scala:727)
[error]         at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:167)
[error]         at dotty.tools.dotc.core.Denotations$Denotation.completeInfo$1(Denotations.scala:188)
[error]         at dotty.tools.dotc.core.Denotations$Denotation.info(Denotations.scala:190)
[error]         at dotty.tools.dotc.core.SymDenotations$SymDenotation.ensureCompleted(SymDenotations.scala:369)
[error]         at dotty.tools.dotc.typer.Typer.retrieveSym(Typer.scala:2611)
[error]         at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2636)
[error]         at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2730)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2796)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2800)
[error]         at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2822)
[error]         at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2872)
[error]         at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2328)
[error]         at dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$2(Typer.scala:2657)
[error]         at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2661)
[error]         at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2730)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2796)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2800)
[error]         at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2822)
[error]         at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2872)
[error]         at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2451)
[error]         at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2702)
[error]         at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2731)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2796)
[error]         at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2800)
[error]         at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2916)
[error]         at dotty.tools.dotc.typer.FrontEnd.liftedTree1$1(FrontEnd.scala:79)
[error]         at dotty.tools.dotc.typer.FrontEnd.typeCheck$$anonfun$1(FrontEnd.scala:84)
[error]         at dotty.tools.dotc.typer.FrontEnd.monitor(FrontEnd.scala:43)
[error]         at dotty.tools.dotc.typer.FrontEnd.typeCheck(FrontEnd.scala:85)
[error]         at dotty.tools.repl.REPLFrontEnd.runOn(ReplFrontEnd.scala:24)
[error]         at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:205)
[error]         at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error]         at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error]         at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
[error]         at dotty.tools.dotc.Run.runPhases$5(Run.scala:215)
[error]         at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:223)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[error]         at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
[error]         at dotty.tools.dotc.Run.compileUnits(Run.scala:230)
[error]         at dotty.tools.dotc.Run.compileUnits(Run.scala:172)
[error]         at dotty.tools.repl.ReplCompiler.runCompilationUnit(ReplCompiler.scala:150)
[error]         at dotty.tools.repl.ReplCompiler.compile(ReplCompiler.scala:160)
[error]         at dotty.tools.repl.ReplDriver.compile(ReplDriver.scala:249)
[error]         at dotty.tools.repl.ReplDriver.interpret(ReplDriver.scala:212)
[error]         at dotty.tools.repl.ReplDriver.run$$anonfun$1(ReplDriver.scala:154)
[error]         at dotty.tools.repl.ReplDriver.withRedirectedOutput(ReplDriver.scala:167)
[error]         at dotty.tools.repl.ReplDriver.run(ReplDriver.scala:155)
[error]         at dotty.tools.repl.ScriptEngine.eval(ScriptEngine.scala:38)
[error]         at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
[error]         at io.getquill.Example$.main(Example.scala:7)
[error]         at io.getquill.Example.main(Example.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
```

## problem

The `runMain` command fails as shown above.

## expectation

The `main` function inside of `Example.scala` should work.

## notes

Running this `main` function with metals works fine. 
Packaging it up and then running with java directly also works
```
> java -cp ./target/scala-3.0.0/sbt_dotty_script_issue-assembly-0.1.0.jar io.getquill.Example
42
42
42
```
Only `runMain` in SBT fails.

Repository with full code sample can be found here:
https://github.com/deusaquilus/sbt_dotty_script_issue

**Comment by griggt** [comment]
It works for me if I set `fork := true`:

```
sbt:sbt_dotty_script_issue> runMain io.getquill.Example
[info] compiling 1 Scala source to /tmp/sbt_dotty_script_issue/target/scala-3.0.0/classes ...
[info] done compiling
[info] running (fork) io.getquill.Example 
[info] 42
[info] 42
[info] 42
```

**Comment by deusaquilus** [comment]
@griggt That works for me too! Yay!
```
sbt:sbt_dotty_script_issue> runMain io.getquill.Example
[info] running (fork) io.getquill.Example 
[info] 6 |        val result = run(q).string
[info]   |                     ^^^^^^
[info]   |                 Compile Time Query Is: SELECT x.name, x.age FROM Person x
[info] Output: SELECT x.name, x.age FROM Person x
[info] ()
```
It only works if you fork though. Is that technically a bug?

**Comment by deusaquilus** [comment]
Hi @griggt. It looks like starting 3.2.0 the ScriptEngine doesn't load 3rd party dependencies anymore:
```
[info] running (fork) io.getquill.Example 
[info] -- [E008] Not Found Error: -----------------------------------------------------
[info] 1 |import io.getquill._
[info]   |       ^^^^^^^^^^^
[error] Exception in thread "main" java.lang.ClassNotFoundException: rs$line$0
[info]   |       value getquill is not a member of io
```
I tried to mess around with "usejavacp" amongst other things without much success. I even tried extending `dotty.tools.repl.ScriptEngine` and messing around with the options there without much success.
Is there some way to get the ScriptEngine to work with the external-dependencies of the project that's loading it?

**Comment by deusaquilus** [comment]
Hi @griggt. It looks like as of Scala 3.2.0 it's no longer working again.
```
sbt:Dotty-ScriptEngine-Quill> runMain io.getquill.Example
[info] running (fork) io.getquill.Example 
[info] -- [E008] Not Found Error: -----------------------------------------------------
[error] Exception in thread "main" java.lang.ClassNotFoundException: rs$line$0
[info] 2 |      import io.getquill._
[info]   |             ^^^^^^^^^^^
[info]   |             value getquill is not a member of io
```
I tried messing around with "usejavacp" and even extended ScriptEngine without much success. Has something changed significantly?

I've got a full code-sample here:
https://github.com/deusaquilus/Dotty-ScriptEngine-Quill

**Comment by fwbrasil** [comment]
I'm hitting this problem as well. The use case is evaluating code at runtime to evaluate the behavior of a large language model. 

```
Caused by: java.lang.ClassNotFoundException: rs$line$0
	at dotty.tools.repl.AbstractFileClassLoader.findClass(AbstractFileClassLoader.scala:54)
AbstractFileClassLoader.scala:54
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
ClassLoader.java:593
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
ClassLoader.java:526
	at dotty.tools.repl.AbstractFileClassLoader.loadClass(AbstractFileClassLoader.scala:60)
AbstractFileClassLoader.scala:60
	at java.base/java.lang.Class.forName0(Native Method)
Class.java:226
	at java.base/java.lang.Class.forName(Class.java:534)
Class.java:534
	at java.base/java.lang.Class.forName(Class.java:513)
Class.java:513
	at dotty.tools.repl.ScriptEngine.eval(ScriptEngine.scala:42)
ScriptEngine.scala:42
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:262)
AbstractScriptEngine.java:262
	at kyo.copilot.internal.SeedGen$.eval$$anonfun$1(SeedGen.scala:68)
```
