### ISSUE TITLE
armv7l version of sbt shipped by chromebrew won't build simple scala project

### ISSUE THREAD

**Issue by apple-corps** [sbt/sbt#6622]
## steps

(chromebrew armv7l version of sbt 1.5.5. build.sbt provided by g8 template installed in steps)

From chrome-os / chromium-os on armv7l machine
  
 install chromebrew (https://github.com/skycocker/chromebrew)

  then
```
  crew install sbt
  sbt new scala/scala3.g8
```
  from project directory
  start sbt.

## problem
  
  Starting sbt from project directory gives stack trace below.

## expectation
  
  A functioning hello world project

## stack trace

```
[info] welcome to sbt 1.5.5 (Oracle Corporation Java 1.8.0_291)
[info] loading project definition from /usr/local/home/scala/test/hello-world/project
[error] ## Exception when compiling 0 sources to /usr/local/home/scala/test/hello-world/project/target/scala-2.12/sbt-1.0/classes
[error] java.lang.InternalError: java.lang.InternalError: java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
[error] sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error] sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[error] sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error] java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[error] java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
[error] java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
[error] java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720)
[error] scala.collection.parallel.ForkJoinTasks$WrappedTask.sync(Tasks.scala:379)
[error] scala.collection.parallel.ForkJoinTasks$WrappedTask.sync$(Tasks.scala:379)
[error] scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.sync(Tasks.scala:440)
[error] scala.collection.parallel.ForkJoinTasks.executeAndWaitResult(Tasks.scala:423)
[error] scala.collection.parallel.ForkJoinTasks.executeAndWaitResult$(Tasks.scala:416)
[error] scala.collection.parallel.ForkJoinTaskSupport.executeAndWaitResult(TaskSupport.scala:60)
[error] scala.collection.parallel.ExecutionContextTasks.executeAndWaitResult(Tasks.scala:555)
[error] scala.collection.parallel.ExecutionContextTasks.executeAndWaitResult$(Tasks.scala:555)
[error] scala.collection.parallel.ExecutionContextTaskSupport.executeAndWaitResult(TaskSupport.scala:84)
[error] scala.collection.parallel.mutable.ParArray.map(ParArray.scala:588)
[error] sbt.internal.inc.caching.ClasspathCache$.hashClasspath(ClasspathCache.scala:71)
[error] sbt.internal.inc.MixedAnalyzingCompiler$.doHash$1(MixedAnalyzingCompiler.scala:308)
[error] sbt.internal.inc.MixedAnalyzingCompiler$.makeConfig(MixedAnalyzingCompiler.scala:314)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:471)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2357)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2314)
[error] sbt.internal.io.Retry$.apply(Retry.scala:46)
[error] sbt.internal.io.Retry$.apply(Retry.scala:28)
[error] sbt.internal.io.Retry$.apply(Retry.scala:23)
[error] sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2310)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] sbt.Execute.work(Execute.scala:291)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] java.lang.Thread.run(Thread.java:748)
[error]            
java.util.concurrent.ExecutionException: java.lang.InternalError: java.lang.InternalError: java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at sbt.ConcurrentRestrictions$$anon$4.take(ConcurrentRestrictions.scala:311)
	at sbt.Execute.next$1(Execute.scala:117)
	at sbt.Execute.processAll(Execute.scala:127)
	at sbt.Execute.runKeep(Execute.scala:95)
	at sbt.EvaluateTask$.liftedTree1$1(EvaluateTask.scala:485)
	at sbt.EvaluateTask$.run$1(EvaluateTask.scala:484)
	at sbt.EvaluateTask$.runTask(EvaluateTask.scala:507)
	at sbt.EvaluateTask$.$anonfun$apply$3(EvaluateTask.scala:352)
	at scala.Option$WithFilter.map(Option.scala:230)
	at sbt.EvaluateTask$.$anonfun$apply$1(EvaluateTask.scala:351)
	at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:397)
	at sbt.EvaluateTask$.apply(EvaluateTask.scala:350)
	at sbt.EvaluateTask$.evalPluginDef(EvaluateTask.scala:311)
	at sbt.internal.Load$.$anonfun$defaultPreGlobal$1(Load.scala:100)
	at sbt.internal.Load$.buildPluginDefinition(Load.scala:1312)
	at sbt.internal.Load$.buildPlugins(Load.scala:1240)
	at sbt.internal.Load$.plugins(Load.scala:1219)
	at sbt.internal.Load$.$anonfun$loadUnit$2(Load.scala:695)
	at sbt.internal.Load$.timed(Load.scala:1393)
	at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:695)
	at sbt.internal.Load$.timed(Load.scala:1393)
	at sbt.internal.Load$.loadUnit(Load.scala:689)
	at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:487)
	at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:180)
	at sbt.internal.BuildLoader.apply(BuildLoader.scala:245)
	at sbt.internal.Load$.loadURI$1(Load.scala:549)
	at sbt.internal.Load$.loadAll(Load.scala:565)
	at sbt.internal.Load$.loadURI(Load.scala:495)
	at sbt.internal.Load$.load(Load.scala:474)
	at sbt.internal.Load$.$anonfun$apply$1(Load.scala:243)
	at sbt.internal.Load$.timed(Load.scala:1393)
	at sbt.internal.Load$.apply(Load.scala:243)
	at sbt.internal.Load$.defaultLoad(Load.scala:56)
	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:959)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:959)
	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:912)
	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:150)
	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:145)
	at sbt.Command$.process(Command.scala:189)
	at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:245)
	at scala.Option.getOrElse(Option.scala:189)
	at sbt.MainLoop$.process$1(MainLoop.scala:245)
	at sbt.MainLoop$.processCommand(MainLoop.scala:278)
	at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:163)
	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:289)
	at sbt.State$StateOpsImpl$.process$extension(State.scala:325)
	at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:163)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.MainLoop$.next(MainLoop.scala:163)
	at sbt.MainLoop$.run(MainLoop.scala:144)
	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:119)
	at sbt.io.Using.apply(Using.scala:27)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:112)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:66)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:51)
	at sbt.MainLoop$.runLogged(MainLoop.scala:42)
	at sbt.StandardMain$.runManaged(Main.scala:218)
	at sbt.xMain$.$anonfun$run$11(Main.scala:133)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withIn(Console.scala:230)
	at sbt.internal.util.Terminal$.withIn(Terminal.scala:569)
	at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:350)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withOut(Console.scala:167)
	at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:559)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withErr(Console.scala:196)
	at sbt.internal.util.Terminal$.withOut(Terminal.scala:559)
	at sbt.internal.util.Terminal$.withStreams(Terminal.scala:350)
	at sbt.xMain$.withStreams$1(Main.scala:87)
	at sbt.xMain$.run(Main.scala:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:56)
	at sbt.xMain.run(Main.scala:46)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.InternalError: java.lang.InternalError: java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720)
	at scala.collection.parallel.ForkJoinTasks$WrappedTask.sync(Tasks.scala:379)
	at scala.collection.parallel.ForkJoinTasks$WrappedTask.sync$(Tasks.scala:379)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.sync(Tasks.scala:440)
	at scala.collection.parallel.ForkJoinTasks.executeAndWaitResult(Tasks.scala:423)
	at scala.collection.parallel.ForkJoinTasks.executeAndWaitResult$(Tasks.scala:416)
	at scala.collection.parallel.ForkJoinTaskSupport.executeAndWaitResult(TaskSupport.scala:60)
	at scala.collection.parallel.ExecutionContextTasks.executeAndWaitResult(Tasks.scala:555)
	at scala.collection.parallel.ExecutionContextTasks.executeAndWaitResult$(Tasks.scala:555)
	at scala.collection.parallel.ExecutionContextTaskSupport.executeAndWaitResult(TaskSupport.scala:84)
	at scala.collection.parallel.mutable.ParArray.map(ParArray.scala:588)
	at sbt.internal.inc.caching.ClasspathCache$.hashClasspath(ClasspathCache.scala:71)
	at sbt.internal.inc.MixedAnalyzingCompiler$.doHash$1(MixedAnalyzingCompiler.scala:308)
	at sbt.internal.inc.MixedAnalyzingCompiler$.makeConfig(MixedAnalyzingCompiler.scala:314)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:471)
	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2357)
	at sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2314)
	at sbt.internal.io.Retry$.apply(Retry.scala:46)
	at sbt.internal.io.Retry$.apply(Retry.scala:28)
	at sbt.internal.io.Retry$.apply(Retry.scala:23)
	at sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2310)
	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.Execute.work(Execute.scala:291)
	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.InternalError: java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720)
	at scala.collection.parallel.ForkJoinTasks$WrappedTask.sync(Tasks.scala:379)
	at scala.collection.parallel.ForkJoinTasks$WrappedTask.sync$(Tasks.scala:379)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.sync(Tasks.scala:440)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:174)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:157)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:150)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)
Caused by: java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
	at scala.collection.parallel.Tasks$WrappedTask.release$(Tasks.scala:117)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.release(Tasks.scala:440)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:171)
	... 10 more
[error] java.util.concurrent.ExecutionException: java.lang.InternalError: java.lang.InternalError: java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
[error] Use 'last' for the full log.
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
```

**Comment by drocsid** [comment]
Possibly due to a bad java installation?

**Comment by eed3si9n** [comment]
Please follow, steps, problem, expectation structure. sbt project does not really test anything other than Intel x86 compatible CPU, so I am not sure if I'd call any other architecture support "bug".

The last part of the stack trace looks like Parallel Collection and Java's Fork/Join.

```
[error] ## Exception when compiling 0 sources to /usr/local/home/scala/test/hello-world/project/target/scala-2.12/sbt-1.0/classes
[error] java.lang.InternalError: java.lang.InternalError: java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
[error] sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error] sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[error] sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error] java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[error] java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
[error] java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
[error] java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720)
[error] scala.collection.parallel.ForkJoinTasks$WrappedTask.sync(Tasks.scala:379)
[error] scala.collection.parallel.ForkJoinTasks$WrappedTask.sync$(Tasks.scala:379)
[error] scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.sync(Tasks.scala:440)
[error] scala.collection.parallel.ForkJoinTasks.executeAndWaitResult(Tasks.scala:423)
[error] scala.collection.parallel.ForkJoinTasks.executeAndWaitResult$(Tasks.scala:416)
[error] scala.collection.parallel.ForkJoinTaskSupport.executeAndWaitResult(TaskSupport.scala:60)
[error] scala.collection.parallel.ExecutionContextTasks.executeAndWaitResult(Tasks.scala:555)
[error] scala.collection.parallel.ExecutionContextTasks.executeAndWaitResult$(Tasks.scala:555)
[error] scala.collection.parallel.ExecutionContextTaskSupport.executeAndWaitResult(TaskSupport.scala:84)
[error] scala.collection.parallel.mutable.ParArray.map(ParArray.scala:588)
```

Do those things work on ARMv7?

**Comment by apple-corps** [comment]
> Please follow, steps, problem, expectation structure

My bad. Corrected. Can I change the `bug` label to `feature`?

___


> Do those things work on ARMv7? ( Parallel Collection and Java's Fork/Join.)

I'd expect if things didn't work that they should produce an `UnsupportedOperationException`. I will try to look around for more information


We do see 

```java.util.concurrent.ExecutionException: java.lang.InternalError: java.lang.InternalError: java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code```

I'm curious if this could be related to system libraries for the chromebrew java / sbt deployment. I looked up the InternalError.

https://stackoverflow.com/questions/45536049/java-lang-internalerror-a-fault-occurred-in-a-recent-unsafe-memory-access-opera/45536678#45536678

____


I don't understand the following log message.Is it normal for a Scala 3 project to compile it's sources via Scala 2.12? Compiling 0 sources?

`[error] ## Exception when compiling 0 sources to /usr/local/home/scala/test/hello-world/project/target/scala-2.12/sbt-1.0/classes`

**Comment by eed3si9n** [comment]
> I don't understand the following log message.Is it normal for a Scala 3 project to compile it's sources via Scala 2.12? Compiling 0 sources?

```bash
[info] loading project definition from /usr/local/home/scala/test/hello-world/project
[error] ## Exception when compiling 0 sources to /usr/local/home/scala/test/hello-world/project/target/scala-2.12/sbt-1.0/classes
[error] java.lang.InternalError: java.lang.InternalError: java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
[error] sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
```

I think so. sbt first tries to compile `build.sbt` together with the loaded plugins and sbt core artifacts, and that all happens in Scala 2.12. This is internally called metabuild, and happens inside `<root>/project` directory.

**Comment by apple-corps** [comment]
> I think so. sbt first tries to compile `build.sbt` together with the loaded plugins and sbt core artifacts, and that all happens in Scala 2.12. This is internally called metabuild, and happens inside `<root>/project` directory.

Thanks for those details.

I'm going to try

1. to build a non Scala 3 project
2. to manually install AdoptOpenJDK 11 for armv7l (no package available) and try to build the Scala projects

and will see if I find any success with either step

**Comment by eed3si9n** [comment]
Closing this for now.
sbt 2.0.0-RC6 uses Scala 3.x in the metabuild, so maybe the situation has improved? Feel free to open a new issue if the situation persists.
