### ISSUE TITLE
NPE import renaming static member of a Java source

### ISSUE THREAD

**Issue by tarossi** [sbt/sbt#6647]
## steps

Using Scala 2.12.14 + SBT 1.5.x
Just include this import in your source

### A.scala

```scala
import java.time.temporal.ChronoUnit.MILLIS.{between => millisBetween}
```

## problem

```
java.lang.NullPointerException
	at xsbt.Dependency$DependencyTraverser.lookupImported$1(Dependency.scala:394)
	at xsbt.Dependency$DependencyTraverser.$anonfun$traverse$1(Dependency.scala:396)
	at xsbt.Dependency$DependencyTraverser.$anonfun$traverse$1$adapted(Dependency.scala:389)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at xsbt.Dependency$DependencyTraverser.traverse(Dependency.scala:389)
	at xsbt.Dependency$DependencyTraverser.traverse(Dependency.scala:206)
	at scala.reflect.api.Trees$Traverser.$anonfun$traverseTrees$1(Trees.scala:2492)
	at scala.reflect.api.Trees$Traverser.traverseTrees(Trees.scala:2492)
	at xsbt.Dependency$DependencyTraverser.traverse(Dependency.scala:442)
	at xsbt.Dependency$DependencyTraverser.traverse(Dependency.scala:206)
	at scala.reflect.internal.Trees.$anonfun$itraverse$1(Trees.scala:1272)
	at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2515)
	at scala.reflect.internal.Trees.traverseMemberDef$1(Trees.scala:1267)
	at scala.reflect.internal.Trees.itraverse(Trees.scala:1391)
	at scala.reflect.internal.Trees.itraverse$(Trees.scala:1264)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:28)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:28)
	at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2483)
	at xsbt.Dependency$DependencyTraverser.traverse(Dependency.scala:472)
	at xsbt.Dependency$DependencyTraverser.traverse(Dependency.scala:206)
	at scala.reflect.api.Trees$Traverser.$anonfun$traverseStats$2(Trees.scala:2506)
	at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2515)
	at scala.reflect.api.Trees$Traverser.$anonfun$traverseStats$1(Trees.scala:2506)
	at scala.reflect.api.Trees$Traverser.traverseStats(Trees.scala:2505)
	at scala.reflect.internal.Trees.itraverse(Trees.scala:1390)
	at scala.reflect.internal.Trees.itraverse$(Trees.scala:1264)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:28)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:28)
	at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2483)
	at xsbt.Dependency$DependencyTraverser.traverse(Dependency.scala:473)
	at xsbt.Dependency$DependencyPhase.apply(Dependency.scala:68)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:453)
	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:400)
	at xsbt.Dependency$DependencyPhase.run(Dependency.scala:49)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1511)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1495)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1488)
	at scala.tools.nsc.Global$Run.compileFiles(Global.scala:1599)
	at xsbt.CachedCompiler0.run(CompilerBridge.scala:163)
	at xsbt.CachedCompiler0.run(CompilerBridge.scala:134)
	at xsbt.CompilerBridge.run(CompilerBridge.scala:39)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:192)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:247)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:182)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:163)
	at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:163)
	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:210)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:528)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:528)
	at sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:175)
	at sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:173)
	at sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:459)
	at sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
	at sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:414)
	at sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:501)
	at sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:401)
	at sbt.internal.inc.Incremental$.apply(Incremental.scala:167)
	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:528)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:482)
	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2357)
	at sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2314)
	at sbt.internal.io.Retry$.apply(Retry.scala:46)
	at sbt.internal.io.Retry$.apply(Retry.scala:28)
	at sbt.internal.io.Retry$.apply(Retry.scala:23)
	at sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2310)
	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.Execute.work(Execute.scala:291)
	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

## expectation

Be able to use the function through its alias

## notes

Demo: https://scastie.scala-lang.org/TzlNQ1V9Rqm7IafLj93LWg

**Comment by eed3si9n** [comment]
@tarossi Thanks for the report!
