### ISSUE TITLE
Compilation failed for Scala 3 project with cross version dependencies

### ISSUE THREAD

**Issue by greenhost87** [sbt/sbt#6648]
## steps

Create empty project with provided build.sbt file

```
lazy val root = (project in file(".")).settings(
  organization := "test",
  scalaVersion := "3.0.2",
  name         := "reproduce",
  version      := "0.0.1",
  libraryDependencies ++= Seq(
    ("com.typesafe.akka" %% "akka-stream" % "2.6.16").cross(CrossVersion.for3Use2_13),
    "org.scalikejdbc"    %% "scalikejdbc" % "4.0.0-RC2"
  )
)
```

## problem

If I use SBT 1.5.4 `sbt compile` work well
If I use SBT 1.5.5 `sbt compile` end with error

```
[info] Executing in batch mode. For better performance use sbt's shell
[error] Modules were resolved with conflicting cross-version suffixes in ProjectRef(uri("file:/Users/develop/reproduce/"), "root"):
[error]    org.scala-lang.modules:scala-parser-combinators _2.13, _3
[error] java.lang.RuntimeException: Conflicting cross-version suffixes in: org.scala-lang.modules:scala-parser-combinators
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at sbt.librarymanagement.ConflictWarning$.processCrossVersioned(ConflictWarning.scala:39)
[error] 	at sbt.librarymanagement.ConflictWarning$.apply(ConflictWarning.scala:19)
[error] 	at sbt.Classpaths$.$anonfun$ivyBaseSettings$71(Defaults.scala:3194)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[error] 	at java.base/java.lang.Thread.run(Thread.java:831)
[error] (update) Conflicting cross-version suffixes in: org.scala-lang.modules:scala-parser-combinators
[error] Total time: 1 s, completed Sep 3, 2021, 4:06:47 PM
```

## expectation

Compilation work on both version of SBT

**Comment by eed3si9n** [comment]
It likely means that you have a conflict in your dependency graph. I fixed the bug https://github.com/sbt/sbt/issues/6578 in 1.5.5 that wasn't reporting conflict error for `_3`.
