### ISSUE TITLE
Transient ResolveExceptions are not properly retried

### ISSUE THREAD

**Issue by antonipp** [sbt/sbt#6685]
## problem
It seems that https://repo1.maven.org was unstable this morning and many of our sbt builds started failing with transient errors. Example:
```
[error] sbt.librarymanagement.ResolveException: Error downloading com.thesamet.scalapb:scalapb-runtime-grpc_2.12:0.11.4
[error]   Not found
[error]   Not found
[error]   not found: /root/.ivy2/localcom.thesamet.scalapb/scalapb-runtime-grpc_2.12/0.11.4/ivys/ivy.xml
[error]   download error: Caught java.net.ConnectException: Connection timed out (Connection timed out) (Connection timed out (Connection timed out)) while downloading https://repo1.maven.org/maven2/com/thesamet/scalapb/scalapb-runtime-grpc_2.12/0.11.4/scalapb-runtime-grpc_2.12-0.11.4.pom
[error] Error downloading com.thesamet.scalapb:sparksql-scalapb_2.12:0.11.0
[error]   Not found
[error]   Not found
[error]   not found: /root/.ivy2/localcom.thesamet.scalapb/sparksql-scalapb_2.12/0.11.0/ivys/ivy.xml
[error]   download error: Caught java.net.ConnectException: Connection timed out (Connection timed out) (Connection timed out (Connection timed out)) while downloading https://repo1.maven.org/maven2/com/thesamet/scalapb/sparksql-scalapb_2.12/0.11.0/sparksql-scalapb_2.12-0.11.0.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:258)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:227)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:227)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:53)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:103)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:116)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:116)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:97)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:130)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:3486)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (proto / update) sbt.librarymanagement.ResolveException: Error downloading com.thesamet.scalapb:scalapb-runtime-grpc_2.12:0.11.4
[error]   Not found
[error]   Not found
[error]   not found: /root/.ivy2/localcom.thesamet.scalapb/scalapb-runtime-grpc_2.12/0.11.4/ivys/ivy.xml
[error]   download error: Caught java.net.ConnectException: Connection timed out (Connection timed out) (Connection timed out (Connection timed out)) while downloading https://repo1.maven.org/maven2/com/thesamet/scalapb/scalapb-runtime-grpc_2.12/0.11.4/scalapb-runtime-grpc_2.12-0.11.4.pom
[error] Error downloading com.thesamet.scalapb:sparksql-scalapb_2.12:0.11.0
[error]   Not found
[error]   Not found
[error]   not found: /root/.ivy2/localcom.thesamet.scalapb/sparksql-scalapb_2.12/0.11.0/ivys/ivy.xml
[error]   download error: Caught java.net.ConnectException: Connection timed out (Connection timed out) (Connection timed out (Connection timed out)) while downloading https://repo1.maven.org/maven2/com/thesamet/scalapb/sparksql-scalapb_2.12/0.11.0/sparksql-scalapb_2.12-0.11.0.pom
```
Simply retrying the build was enough to fix this.
However, as far as I can tell, there are no retries for these types of exceptions in sbt or in Coursier.

## expectation
I would expect sbt and / or Coursier to be able to retry transient exceptions under the hood. Allowing users to configure retry settings would be great as well.

## notes
We use sbt 1.4.6.

**Comment by eed3si9n** [comment]
Coursier does retry under some circumstances (see https://github.com/coursier/coursier/pull/507/commits/869d7c628edcd9315a43f75d87614198146ce6bb), but I guess not for  `java.net.ConnectException`. 

Could you report this to the upstream coursier/coursier as well and ask to retry on `java.net.ConnectException`?

**Comment by antonipp** [comment]
Thank you for your quick answer, I reported the issue upstream: https://github.com/coursier/coursier/issues/2217

**Comment by eed3si9n** [comment]
Closing this issue for now since we'd get the update when someone works on it on Coursier.
