### ISSUE TITLE
SBT Typesafe Config Not Getting Merged

### ISSUE THREAD

**Issue by joesan** [sbt/sbt#6686]
## problem

I have a Spark standalone sbt application which when run using a GitHub action, is not able to read the config from the default application.conf

## steps

I have a application.conf file located under src/main/resources folder that contain several key value configuration elements. I have then in my scr/test/resources another file called application.test.conf file in which I include the application.conf file., but somehow the contents from the application.conf are not included.

I have also included Merge strategy in my build.sbt, but this does not take any effect. I'm not sure what the problem is. Locally when I run, it seems to be working, but when run on GitHub action, it fails.

Here is the log output:

```
2021-10-08T13:52:16.4393802Z Found online and idle hosted runner in the current repository's organization account that matches the required labels: 'ubuntu-20.04'
2021-10-08T13:52:16.5631454Z Waiting for a Hosted runner in the 'organization' to pick this job...
2021-10-08T13:52:16.8806501Z Job is waiting for a hosted runner to come online.
2021-10-08T13:52:21.7023302Z Job is about to start running on the hosted runner: Hosted Agent (hosted)
2021-10-08T13:52:25.6938769Z Current runner version: '2.283.1'
2021-10-08T13:52:25.7001132Z ##[group]Operating System
2021-10-08T13:52:25.7002331Z Ubuntu
2021-10-08T13:52:25.7002849Z 20.04.3
2021-10-08T13:52:25.7003374Z LTS
2021-10-08T13:52:25.7003891Z ##[endgroup]
2021-10-08T13:52:25.7004585Z ##[group]Virtual Environment
2021-10-08T13:52:25.7005371Z Environment: ubuntu-20.04
2021-10-08T13:52:25.7005989Z Version: 20211004.1
2021-10-08T13:52:25.7007161Z Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20211004.1/images/linux/Ubuntu2004-README.md
2021-10-08T13:52:25.7008673Z Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20211004.1
2021-10-08T13:52:25.7009718Z ##[endgroup]
2021-10-08T13:52:25.7010475Z ##[group]Virtual Environment Provisioner
2021-10-08T13:52:25.7011193Z 1.0.0.0-master-20210922-1
2021-10-08T13:52:25.7011827Z ##[endgroup]
2021-10-08T13:52:25.7014106Z ##[group]GITHUB_TOKEN Permissions
2021-10-08T13:52:25.7015774Z Actions: write
2021-10-08T13:52:25.7016417Z Checks: write
2021-10-08T13:52:25.7017402Z Contents: write
2021-10-08T13:52:25.7018077Z Deployments: write
2021-10-08T13:52:25.7018774Z Discussions: write
2021-10-08T13:52:25.7019380Z Issues: write
2021-10-08T13:52:25.7019988Z Metadata: read
2021-10-08T13:52:25.7020551Z Packages: write
2021-10-08T13:52:25.7021176Z Pages: write
2021-10-08T13:52:25.7021764Z PullRequests: write
2021-10-08T13:52:25.7022538Z RepositoryProjects: write
2021-10-08T13:52:25.7023305Z SecurityEvents: write
2021-10-08T13:52:25.7023936Z Statuses: write
2021-10-08T13:52:25.7024700Z ##[endgroup]
2021-10-08T13:52:25.7028277Z Prepare workflow directory
2021-10-08T13:52:25.7712647Z Prepare all required actions
2021-10-08T13:52:25.7723764Z Getting action download info
2021-10-08T13:52:25.9825138Z Download action repository 'actions/checkout@v2' (SHA:5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f)
2021-10-08T13:52:27.6448241Z Download action repository 'actions/cache@v1' (SHA:70655ec8323daeeaa7ef06d7c56e1b9191396cbe)
2021-10-08T13:52:27.9618394Z ##[group]Run actions/checkout@v2
2021-10-08T13:52:27.9619230Z with:
2021-10-08T13:52:27.9620254Z   repository: joesan/housing-price-prediction-data-preparation
2021-10-08T13:52:27.9621785Z   token: ***
2021-10-08T13:52:27.9622304Z   ssh-strict: true
2021-10-08T13:52:27.9622960Z   persist-credentials: true
2021-10-08T13:52:27.9623567Z   clean: true
2021-10-08T13:52:27.9624099Z   fetch-depth: 1
2021-10-08T13:52:27.9624607Z   lfs: false
2021-10-08T13:52:27.9625130Z   submodules: false
2021-10-08T13:52:27.9625674Z ##[endgroup]
2021-10-08T13:52:28.6535306Z Syncing repository: joesan/housing-price-prediction-data-preparation
2021-10-08T13:52:28.6537534Z ##[group]Getting Git version info
2021-10-08T13:52:28.6539560Z Working directory is '/home/runner/work/housing-price-prediction-data-preparation/housing-price-prediction-data-preparation'
2021-10-08T13:52:28.6541794Z [command]/usr/bin/git version
2021-10-08T13:52:28.6542369Z git version 2.33.0
2021-10-08T13:52:28.6544490Z ##[endgroup]
2021-10-08T13:52:28.6546438Z Deleting the contents of '/home/runner/work/housing-price-prediction-data-preparation/housing-price-prediction-data-preparation'
2021-10-08T13:52:28.6550295Z ##[group]Initializing the repository
2021-10-08T13:52:28.6552285Z [command]/usr/bin/git init /home/runner/work/housing-price-prediction-data-preparation/housing-price-prediction-data-preparation
2021-10-08T13:52:28.6554254Z hint: Using 'master' as the name for the initial branch. This default branch name
2021-10-08T13:52:28.6555217Z hint: is subject to change. To configure the initial branch name to use in all
2021-10-08T13:52:28.6556169Z hint: of your new repositories, which will suppress this warning, call:
2021-10-08T13:52:28.6556866Z hint: 
2021-10-08T13:52:28.6557708Z hint: 	git config --global init.defaultBranch <name>
2021-10-08T13:52:28.6558363Z hint: 
2021-10-08T13:52:28.6559224Z hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
2021-10-08T13:52:28.6560437Z hint: 'development'. The just-created branch can be renamed via this command:
2021-10-08T13:52:28.6561506Z hint: 
2021-10-08T13:52:28.6562186Z hint: 	git branch -m <name>
2021-10-08T13:52:28.6564131Z Initialized empty Git repository in /home/runner/work/housing-price-prediction-data-preparation/housing-price-prediction-data-preparation/.git/
2021-10-08T13:52:28.6567064Z [command]/usr/bin/git remote add origin https://github.com/joesan/housing-price-prediction-data-preparation
2021-10-08T13:52:28.6569179Z ##[endgroup]
2021-10-08T13:52:28.6570443Z ##[group]Disabling automatic garbage collection
2021-10-08T13:52:28.6571408Z [command]/usr/bin/git config --local gc.auto 0
2021-10-08T13:52:28.6572604Z ##[endgroup]
2021-10-08T13:52:28.6575497Z ##[group]Setting up auth
2021-10-08T13:52:28.6576702Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2021-10-08T13:52:28.6578402Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2021-10-08T13:52:28.6580098Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2021-10-08T13:52:28.6582148Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
2021-10-08T13:52:28.6585053Z [command]/usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
2021-10-08T13:52:28.6586630Z ##[endgroup]
2021-10-08T13:52:28.6587797Z ##[group]Fetching the repository
2021-10-08T13:52:28.6589563Z [command]/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +071b8a6a6c7ed146735e465046fe036591ae19dc:refs/remotes/origin/master
2021-10-08T13:52:28.6590975Z remote: Enumerating objects: 46, done.        
2021-10-08T13:52:28.6591681Z remote: Counting objects:   2% (1/46)        
2021-10-08T13:52:28.6592523Z remote: Counting objects:   4% (2/46)        
2021-10-08T13:52:28.6593210Z remote: Counting objects:   6% (3/46)        
2021-10-08T13:52:28.6593858Z remote: Counting objects:   8% (4/46)        
2021-10-08T13:52:28.6594516Z remote: Counting objects:  10% (5/46)        
2021-10-08T13:52:28.6595180Z remote: Counting objects:  13% (6/46)        
2021-10-08T13:52:28.6595826Z remote: Counting objects:  15% (7/46)        
2021-10-08T13:52:28.6596482Z remote: Counting objects:  17% (8/46)        
2021-10-08T13:52:28.6597126Z remote: Counting objects:  19% (9/46)        
2021-10-08T13:52:28.6597783Z remote: Counting objects:  21% (10/46)        
2021-10-08T13:52:28.6598758Z remote: Counting objects:  23% (11/46)        
2021-10-08T13:52:28.6599426Z remote: Counting objects:  26% (12/46)        
2021-10-08T13:52:28.6600089Z remote: Counting objects:  28% (13/46)        
2021-10-08T13:52:28.6600734Z remote: Counting objects:  30% (14/46)        
2021-10-08T13:52:28.6601405Z remote: Counting objects:  32% (15/46)        
2021-10-08T13:52:28.6602063Z remote: Counting objects:  34% (16/46)        
2021-10-08T13:52:28.6602720Z remote: Counting objects:  36% (17/46)        
2021-10-08T13:52:28.6603378Z remote: Counting objects:  39% (18/46)        
2021-10-08T13:52:28.6604022Z remote: Counting objects:  41% (19/46)        
2021-10-08T13:52:28.6604891Z remote: Counting objects:  43% (20/46)        
2021-10-08T13:52:28.6605556Z remote: Counting objects:  45% (21/46)        
2021-10-08T13:52:28.6606199Z remote: Counting objects:  47% (22/46)        
2021-10-08T13:52:28.6606855Z remote: Counting objects:  50% (23/46)        
2021-10-08T13:52:28.6607501Z remote: Counting objects:  52% (24/46)        
2021-10-08T13:52:28.6608160Z remote: Counting objects:  54% (25/46)        
2021-10-08T13:52:28.6608818Z remote: Counting objects:  56% (26/46)        
2021-10-08T13:52:28.6609458Z remote: Counting objects:  58% (27/46)        
2021-10-08T13:52:28.6610114Z remote: Counting objects:  60% (28/46)        
2021-10-08T13:52:28.6610763Z remote: Counting objects:  63% (29/46)        
2021-10-08T13:52:28.6611588Z remote: Counting objects:  65% (30/46)        
2021-10-08T13:52:28.6612247Z remote: Counting objects:  67% (31/46)        
2021-10-08T13:52:28.6612896Z remote: Counting objects:  69% (32/46)        
2021-10-08T13:52:28.6613555Z remote: Counting objects:  71% (33/46)        
2021-10-08T13:52:28.6614192Z remote: Counting objects:  73% (34/46)        
2021-10-08T13:52:28.6614846Z remote: Counting objects:  76% (35/46)        
2021-10-08T13:52:28.6615491Z remote: Counting objects:  78% (36/46)        
2021-10-08T13:52:28.6616146Z remote: Counting objects:  80% (37/46)        
2021-10-08T13:52:28.6617273Z remote: Counting objects:  82% (38/46)        
2021-10-08T13:52:28.6617926Z remote: Counting objects:  84% (39/46)        
2021-10-08T13:52:28.6618586Z remote: Counting objects:  86% (40/46)        
2021-10-08T13:52:28.6619228Z remote: Counting objects:  89% (41/46)        
2021-10-08T13:52:28.6619894Z remote: Counting objects:  91% (42/46)        
2021-10-08T13:52:28.6620558Z remote: Counting objects:  93% (43/46)        
2021-10-08T13:52:28.6621197Z remote: Counting objects:  95% (44/46)        
2021-10-08T13:52:28.6621854Z remote: Counting objects:  97% (45/46)        
2021-10-08T13:52:28.6622500Z remote: Counting objects: 100% (46/46)        
2021-10-08T13:52:28.6623185Z remote: Counting objects: 100% (46/46), done.        
2021-10-08T13:52:28.6623878Z remote: Compressing objects:   3% (1/31)        
2021-10-08T13:52:28.6624590Z remote: Compressing objects:   6% (2/31)        
2021-10-08T13:52:28.6625298Z remote: Compressing objects:   9% (3/31)        
2021-10-08T13:52:28.6625994Z remote: Compressing objects:  12% (4/31)        
2021-10-08T13:52:28.6626705Z remote: Compressing objects:  16% (5/31)        
2021-10-08T13:52:28.6627399Z remote: Compressing objects:  19% (6/31)        
2021-10-08T13:52:28.6628107Z remote: Compressing objects:  22% (7/31)        
2021-10-08T13:52:28.6628942Z remote: Compressing objects:  25% (8/31)        
2021-10-08T13:52:28.6629872Z remote: Compressing objects:  29% (9/31)        
2021-10-08T13:52:28.6630594Z remote: Compressing objects:  32% (10/31)        
2021-10-08T13:52:28.6631294Z remote: Compressing objects:  35% (11/31)        
2021-10-08T13:52:28.6632005Z remote: Compressing objects:  38% (12/31)        
2021-10-08T13:52:28.6632700Z remote: Compressing objects:  41% (13/31)        
2021-10-08T13:52:28.6633412Z remote: Compressing objects:  45% (14/31)        
2021-10-08T13:52:28.6634127Z remote: Compressing objects:  48% (15/31)        
2021-10-08T13:52:28.6634821Z remote: Compressing objects:  51% (16/31)        
2021-10-08T13:52:28.6635534Z remote: Compressing objects:  54% (17/31)        
2021-10-08T13:52:28.6636226Z remote: Compressing objects:  58% (18/31)        
2021-10-08T13:52:28.6636937Z remote: Compressing objects:  61% (19/31)        
2021-10-08T13:52:28.6637643Z remote: Compressing objects:  64% (20/31)        
2021-10-08T13:52:28.6638340Z remote: Compressing objects:  67% (21/31)        
2021-10-08T13:52:28.6639047Z remote: Compressing objects:  70% (22/31)        
2021-10-08T13:52:28.6639745Z remote: Compressing objects:  74% (23/31)        
2021-10-08T13:52:28.6640452Z remote: Compressing objects:  77% (24/31)        
2021-10-08T13:52:28.6641146Z remote: Compressing objects:  80% (25/31)        
2021-10-08T13:52:28.6641851Z remote: Compressing objects:  83% (26/31)        
2021-10-08T13:52:28.6642562Z remote: Compressing objects:  87% (27/31)        
2021-10-08T13:52:28.6643254Z remote: Compressing objects:  90% (28/31)        
2021-10-08T13:52:28.6643960Z remote: Compressing objects:  93% (29/31)        
2021-10-08T13:52:28.6644652Z remote: Compressing objects:  96% (30/31)        
2021-10-08T13:52:28.6645356Z remote: Compressing objects: 100% (31/31)        
2021-10-08T13:52:28.6646087Z remote: Compressing objects: 100% (31/31), done.        
2021-10-08T13:52:28.6708337Z remote: Total 46 (delta 1), reused 31 (delta 1), pack-reused 0        
2021-10-08T13:52:28.6913162Z From https://github.com/joesan/housing-price-prediction-data-preparation
2021-10-08T13:52:28.6915119Z  * [new ref]         071b8a6a6c7ed146735e465046fe036591ae19dc -> origin/master
2021-10-08T13:52:28.6957283Z ##[endgroup]
2021-10-08T13:52:28.6958577Z ##[group]Determining the checkout info
2021-10-08T13:52:28.6959777Z ##[endgroup]
2021-10-08T13:52:28.6960921Z ##[group]Checking out the ref
2021-10-08T13:52:28.6962341Z [command]/usr/bin/git checkout --progress --force -B master refs/remotes/origin/master
2021-10-08T13:52:28.7057381Z Reset branch 'master'
2021-10-08T13:52:28.7058421Z Branch 'master' set up to track remote branch 'master' from 'origin'.
2021-10-08T13:52:28.7059904Z ##[endgroup]
2021-10-08T13:52:28.7092052Z [command]/usr/bin/git log -1 --format='%H'
2021-10-08T13:52:28.7139403Z '071b8a6a6c7ed146735e465046fe036591ae19dc'
2021-10-08T13:52:28.8903525Z ##[group]Run actions/cache@v1
2021-10-08T13:52:28.8904130Z with:
2021-10-08T13:52:28.8904623Z   path: ~/.ivy2/cache
2021-10-08T13:52:28.8908557Z   key: Linux-sbt-ivy-cache-3e7c6ec22324f22ac29e5f2c81655315571cc96edcf7b22cbe3d191900a0b17e-5a0f614fcc7d99521be626f10eeb3f7c1ed3aa42f06ee993f80e0d3428021e14
2021-10-08T13:52:28.8912448Z ##[endgroup]
2021-10-08T13:52:29.0532333Z Cache not found for input keys: Linux-sbt-ivy-cache-3e7c6ec22324f22ac29e5f2c81655315571cc96edcf7b22cbe3d191900a0b17e-5a0f614fcc7d99521be626f10eeb3f7c1ed3aa42f06ee993f80e0d3428021e14.
2021-10-08T13:52:29.0664557Z ##[group]Run sbt clean test -Denv=test
2021-10-08T13:52:29.0665335Z [36;1msbt clean test -Denv=test[0m
2021-10-08T13:52:29.0717383Z shell: /usr/bin/bash -e {0}
2021-10-08T13:52:29.0717962Z ##[endgroup]
2021-10-08T13:52:29.8596628Z copying runtime jar...
2021-10-08T13:52:38.9022946Z [info] [launcher] getting org.scala-sbt sbt 1.4.9  (this may take some time)...
2021-10-08T13:52:43.6188589Z [info] [launcher] getting Scala 2.12.12 (for sbt)...
2021-10-08T13:52:45.8453549Z [0m[[0m[0minfo[0m] [0m[0mwelcome to sbt 1.4.9 (AdoptOpenJDK Java 11.0.11)[0m
2021-10-08T13:52:50.2568443Z [0m[[0m[0minfo[0m] [0m[0mloading settings for project housing-price-prediction-data-preparation-build from plugins.sbt ...[0m
2021-10-08T13:52:51.3380655Z [0m[[0m[0minfo[0m] [0m[0mloading project definition from /home/runner/work/housing-price-prediction-data-preparation/housing-price-prediction-data-preparation/project[0m
2021-10-08T13:52:58.3065593Z [0m[[0m[0minfo[0m] [0m[0mloading settings for project housing-price-prediction-data-preparation from build.sbt ...[0m
2021-10-08T13:52:58.5349533Z [0m[[0m[0minfo[0m] [0m[0mset current project to housing-price-prediction-data-preparation (in build file:/home/runner/work/housing-price-prediction-data-preparation/housing-price-prediction-data-preparation/)[0m
2021-10-08T13:52:59.0112532Z [0m[[0m[32msuccess[0m] [0m[0mTotal time: 0 s, completed Oct 8, 2021, 1:52:58 PM[0m
2021-10-08T13:53:11.2709904Z [0m[[0m[33mwarn[0m] [0m[0mThere may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.[0m
2021-10-08T13:53:11.9756816Z [0m[[0m[0minfo[0m] [0m[0mcompiling 9 Scala sources to /home/runner/work/housing-price-prediction-data-preparation/housing-price-prediction-data-preparation/target/scala-2.12/classes ...[0m
2021-10-08T13:53:12.0644173Z [0m[[0m[0minfo[0m] [0m[0mNon-compiled module 'compiler-bridge_2.12' for Scala 2.12.12. Compiling...[0m
2021-10-08T13:53:22.7445307Z [0m[[0m[0minfo[0m] [0m[0m  Compilation completed in 10.679s.[0m
2021-10-08T13:53:25.7092564Z [0m[[0m[0minfo[0m] [0m[0mdone compiling[0m
2021-10-08T13:53:26.1289616Z [0m[[0m[0minfo[0m] [0m[0mcompiling 3 Scala sources to /home/runner/work/housing-price-prediction-data-preparation/housing-price-prediction-data-preparation/target/scala-2.12/test-classes ...[0m
2021-10-08T13:53:27.2448616Z [0m[[0m[0minfo[0m] [0m[0mdone compiling[0m
2021-10-08T13:53:28.6947509Z OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
2021-10-08T13:53:31.2048342Z SLF4J: Class path contains multiple SLF4J bindings.
2021-10-08T13:53:31.2060073Z SLF4J: Found binding in [jar:file:/home/runner/.cache/coursier/v1/https/repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2021-10-08T13:53:31.2098971Z SLF4J: Found binding in [jar:file:/home/runner/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/slf4j-log4j12/1.7.30/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2021-10-08T13:53:31.2101005Z SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
2021-10-08T13:53:31.4147049Z SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
2021-10-08T13:53:31.4175194Z Loading default from test Resource **************** 
2021-10-08T13:53:31.4197039Z Loading from Resource ********************************* ........ application.test.conf 
2021-10-08T13:53:31.4753203Z cgf obtained is Config(SimpleConfigObject({"resource":"/home/runner/work/housing-price-prediction-data-preparation/housing-price-prediction-data-preparation/src/test/resources/application.test.conf"}))
2021-10-08T13:53:31.6412775Z WARNING: An illegal reflective access operation has occurred
2021-10-08T13:53:31.6461140Z WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/runner/.cache/coursier/v1/https/repo1.maven.org/maven2/org/apache/spark/spark-unsafe_2.12/3.1.2/spark-unsafe_2.12-3.1.2.jar) to constructor java.nio.DirectByteBuffer(long,int)
2021-10-08T13:53:31.6464262Z WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
2021-10-08T13:53:31.6481267Z WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
2021-10-08T13:53:31.6482660Z WARNING: All illegal access operations will be denied in a future release
2021-10-08T13:53:31.9564268Z 13:53:31.954 [pool-1-thread-1] WARN  org.apache.hadoop.util.NativeCodeLoader - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2021-10-08T13:53:33.6943990Z [0m[[0m[0minfo[0m] [0m[0m[32mHousingDataTest:[0m[0m
2021-10-08T13:53:34.0952099Z [0m[[0m[0minfo[0m] [0m[0m[32mdata quality check[0m[0m
2021-10-08T13:53:34.1139196Z This shit failed **************************** 
2021-10-08T13:53:34.1145130Z com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'data.file.source'
2021-10-08T13:53:34.1150068Z 	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152)
2021-10-08T13:53:34.1153902Z 	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:145)
2021-10-08T13:53:34.1157703Z 	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:172)
2021-10-08T13:53:34.1172054Z 	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
2021-10-08T13:53:34.1174123Z 	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
2021-10-08T13:53:34.1175922Z 	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
2021-10-08T13:53:34.1177736Z 	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
2021-10-08T13:53:34.1179458Z 	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:246)
2021-10-08T13:53:34.1181460Z 	at com.bigelectrons.housingml.dataprep.model.AppConfig$.$anonfun$load$1(AppConfig.scala:31)
2021-10-08T13:53:34.1182855Z 	at scala.util.Try$.apply(Try.scala:213)
2021-10-08T13:53:34.1184211Z 	at com.bigelectrons.housingml.dataprep.model.AppConfig$.load(AppConfig.scala:26)
2021-10-08T13:53:34.1186379Z 	at com.bigelectrons.housingml.dataprep.HousingDataTest.<init>(HousingDataTest.scala:26)
2021-10-08T13:53:34.1188876Z 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2021-10-08T13:53:34.1191931Z 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
2021-10-08T13:53:34.1196690Z 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2021-10-08T13:53:34.1199735Z 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
2021-10-08T13:53:34.1201050Z 	at java.base/java.lang.Class.newInstance(Class.java:584)
2021-10-08T13:53:34.1202256Z 	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:435)
2021-10-08T13:53:34.1203374Z 	at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)
2021-10-08T13:53:34.1204470Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2021-10-08T13:53:34.1206256Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-10-08T13:53:34.1208287Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-10-08T13:53:34.1209613Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2021-10-08T13:53:34.1408745Z [0m[[0m[0minfo[0m] [0m[0m[32m- should check the quality of training data (19 milliseconds)[0m[0m
2021-10-08T13:53:34.3352407Z [0m[[0m[0minfo[0m] [0m[0mScalaTest[0m
2021-10-08T13:53:34.3359019Z [0m[[0m[0minfo[0m] [0m[0m[36mRun completed in 5 seconds, 703 milliseconds.[0m[0m
2021-10-08T13:53:34.3361541Z [0m[[0m[0minfo[0m] [0m[0m[36mTotal number of tests run: 1[0m[0m
2021-10-08T13:53:34.3363915Z [0m[[0m[0minfo[0m] [0m[0m[36mSuites: completed 1, aborted 0[0m[0m
2021-10-08T13:53:34.3366542Z [0m[[0m[0minfo[0m] [0m[0m[36mTests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0[0m[0m
2021-10-08T13:53:34.3368987Z [0m[[0m[0minfo[0m] [0m[0m[32mAll tests passed.[0m[0m
2021-10-08T13:53:34.3385688Z [0m[[0m[0minfo[0m] [0m[0mPassed: Total 1, Failed 0, Errors 0, Passed 1[0m
2021-10-08T13:53:34.3594391Z [0m[[0m[32msuccess[0m] [0m[0mTotal time: 35 s, completed Oct 8, 2021, 1:53:34 PM[0m
2021-10-08T13:53:34.7361262Z [0J
2021-10-08T13:53:34.9770541Z Post job cleanup.
2021-10-08T13:53:35.1419023Z [command]/usr/bin/tar -cz -f /home/runner/work/_temp/4d650d4a-8cda-4117-9739-9bbac47af6b9/cache.tgz -C /home/runner/.ivy2/cache .
2021-10-08T13:53:35.1476198Z /usr/bin/tar: /home/runner/.ivy2/cache: Cannot open: No such file or directory
2021-10-08T13:53:35.1477589Z /usr/bin/tar: Error is not recoverable: exiting now
2021-10-08T13:53:35.1518149Z [warning]Tar failed with error: The process '/usr/bin/tar' failed with exit code 2
2021-10-08T13:53:35.1680825Z Post job cleanup.
2021-10-08T13:53:35.2843315Z [command]/usr/bin/git version
2021-10-08T13:53:35.2891152Z git version 2.33.0
2021-10-08T13:53:35.2928919Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2021-10-08T13:53:35.2966191Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2021-10-08T13:53:35.3223720Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2021-10-08T13:53:35.3250911Z http.https://github.com/.extraheader
2021-10-08T13:53:35.3262752Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2021-10-08T13:53:35.3300285Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
2021-10-08T13:53:35.3727631Z Cleaning up orphan processes
```

**Comment by eed3si9n** [comment]
> I have also included Merge strategy in my build.sbt, but this does not take any effect. I'm not sure what the problem is. Locally when I run, it seems to be working, but when run on GitHub action, it fails.

We use GitHub issue mostly to track bugs and tasks on sbt development. If you need help, please check out https://users.scala-lang.org/ or see https://www.scala-sbt.org/support.html
