### ISSUE TITLE
"java.nio.file.InvalidPathException: Illegal char <<> at index 0: <macro>" on Windows for code that produces warning when compiled by a macro

### ISSUE THREAD

**Issue by pweisenburger** [sbt/sbt#6720]
Ref https://github.com/sbt/sbt/issues/5994

## Steps

Using SBT 1.5.5 and Scala 2.13.7, define a macro that just leaves the expression under expansion unchanged:

```scala
package test

import scala.language.experimental.macros
import scala.reflect.macros.blackbox

object Test {
  def apply(v: Any): Any = macro TestImpl.test
}

object TestImpl {
  def test(c: blackbox.Context)(v: c.Tree): c.Tree = v
}
```

Apply the macro as in the following ScalaTest test case:

```scala
package test

import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers

class TestSpec extends AnyFlatSpec with Matchers {
  "test" should "compile" in {
    "Test { new { val v = 1 } with AnyRef }" should compile
  }
}
```

## Problem

On Windows, the code crashes the compilation. May be related to #5994 (but this is supposed to be fixed).

<details>
<summary>Stack trace</summary>

```
## Exception when compiling 1 sources
java.nio.file.InvalidPathException: Illegal char <<> at index 0: <macro>
java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
java.base/java.nio.file.Path.of(Path.java:147)
java.base/java.nio.file.Paths.get(Paths.java:69)
sbt.internal.inc.MappedVirtualFile$.toPath(MappedVirtualFile.scala:36)
sbt.internal.inc.MappedFileConverter.toPath(MappedVirtualFile.scala:53)
sbt.internal.server.BuildServerReporterImpl.$anonfun$publishDiagnostic$2(BuildServerReporter.scala:120)
sbt.internal.server.BuildServerReporterImpl.$anonfun$publishDiagnostic$2$adapted(BuildServerReporter.scala:118)
scala.Option.foreach(Option.scala:407)
sbt.internal.server.BuildServerReporterImpl.$anonfun$publishDiagnostic$1(BuildServerReporter.scala:118)
sbt.internal.server.BuildServerReporterImpl.$anonfun$publishDiagnostic$1$adapted(BuildServerReporter.scala:117)
scala.Option.foreach(Option.scala:407)
sbt.internal.server.BuildServerReporterImpl.publishDiagnostic(BuildServerReporter.scala:117)
sbt.internal.server.BuildServerReporter.log(BuildServerReporter.scala:62)
sbt.internal.server.BuildServerReporter.log$(BuildServerReporter.scala:55)
sbt.internal.server.BuildServerReporterImpl.log(BuildServerReporter.scala:70)
xsbt.DelegatingReporter.info0(DelegatingReporter.scala:185)
scala.tools.nsc.reporters.MakeFilteringForwardingReporter.doReport(ForwardingReporter.scala:59)
scala.tools.nsc.reporters.FilteringReporter.info0(Reporter.scala:104)
scala.reflect.internal.Reporter.filteredInfo(Reporting.scala:116)
scala.reflect.internal.Reporter.warning(Reporting.scala:110)
scala.tools.nsc.Reporting$PerRunReporting.issueWarning(Reporting.scala:118)
scala.tools.nsc.Reporting$PerRunReporting.$anonfun$runFinished$2(Reporting.scala:85)
scala.tools.nsc.Reporting$PerRunReporting.$anonfun$runFinished$2$adapted(Reporting.scala:85)
scala.collection.mutable.LinkedHashSet.foreach(LinkedHashSet.scala:127)
scala.tools.nsc.Reporting$PerRunReporting.$anonfun$runFinished$1(Reporting.scala:85)
scala.tools.nsc.Reporting$PerRunReporting.$anonfun$runFinished$1$adapted(Reporting.scala:85)
scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
scala.collection.AbstractIterator.foreach(Iterator.scala:1296)
scala.tools.nsc.Reporting$PerRunReporting.runFinished(Reporting.scala:85)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:192)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:247)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:182)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:163)
	at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:163)
	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:210)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:528)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:528)
	at sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:175)
	at sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:173)
	at sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:459)
	at sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
	at sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:414)
	at sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:501)
	at sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:401)
	at sbt.internal.inc.Incremental$.apply(Incremental.scala:167)
	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:528)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:482)
	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2357)
	at sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2314)
	at sbt.internal.io.Retry$.apply(Retry.scala:46)
	at sbt.internal.io.Retry$.apply(Retry.scala:28)
	at sbt.internal.io.Retry$.apply(Retry.scala:23)
	at sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2310)
	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.Execute.work(Execute.scala:291)
	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
</details>

## Expectation

SBT compiles the code fine under Linux; you only get the following warning from the Scala compiler (which is expected for the code):

```
<macro>:1:15: early initializers are deprecated; they will be replaced by trait parameters in 3.0, see the migration guide on avoiding var/val in traits.
{ Test { new { val v = 1 } with AnyRef } }
             ^
```

**Comment by eed3si9n** [comment]
@pweisenburger Thanks for the report.

Looking at the stack trace in previously reported #5994 the middle part looks like:

```scala
sbt.internal.inc.MappedFileConverter.toPath(MappedVirtualFile.scala:53)
sbt.Defaults$.$anonfun$toAbsoluteSourceMapper$2(Defaults.scala:471)
java.util.Optional.map(Optional.java:215)
sbt.Defaults$.$anonfun$toAbsoluteSourceMapper$1(Defaults.scala:470)
sbt.Defaults$.$anonfun$foldMappers$3(Defaults.scala:2246)
sbt.internal.inc.LoggedReporter.log(LoggedReporter.scala:131)
sbt.internal.server.BuildServerReporter.log(BuildServerReporter.scala:55)
sbt.internal.server.BuildServerReporter.log$(BuildServerReporter.scala:50)
sbt.internal.server.BuildServerReporterImpl.log(BuildServerReporter.scala:62)
xsbt.DelegatingReporter.info0(DelegatingReporter.scala:185)
```

whereas in your case we have:

```scala
sbt.internal.inc.MappedFileConverter.toPath(MappedVirtualFile.scala:53)
sbt.internal.server.BuildServerReporterImpl.$anonfun$publishDiagnostic$2(BuildServerReporter.scala:120)
sbt.internal.server.BuildServerReporterImpl.$anonfun$publishDiagnostic$2$adapted(BuildServerReporter.scala:118)
scala.Option.foreach(Option.scala:407)
sbt.internal.server.BuildServerReporterImpl.$anonfun$publishDiagnostic$1(BuildServerReporter.scala:118)
sbt.internal.server.BuildServerReporterImpl.$anonfun$publishDiagnostic$1$adapted(BuildServerReporter.scala:117)
scala.Option.foreach(Option.scala:407)
sbt.internal.server.BuildServerReporterImpl.publishDiagnostic(BuildServerReporter.scala:117)
sbt.internal.server.BuildServerReporter.log(BuildServerReporter.scala:62)
sbt.internal.server.BuildServerReporter.log$(BuildServerReporter.scala:55)
sbt.internal.server.BuildServerReporterImpl.log(BuildServerReporter.scala:70)
xsbt.DelegatingReporter.info0(DelegatingReporter.scala:185)
```

so it seems like the fix applied by @adpi2 in #6008 no longer applies to this code path because it was done in `toAbsoluteSourceMapper`.

I wonder if we should do the check here instead or in addition - https://github.com/sbt/sbt/blob/b2f0b7dadad0f66f2c2511b6541b1bc158fc3a57/main/src/main/scala/sbt/internal/server/BuildServerReporter.scala#L120

**Comment by pweisenburger** [comment]
> I wonder if we should do the check here instead or in addition

Well, I don't really know where to put this best, but it would be nice to get this fixed. In particular in conjunction with scala/bug#12498, this problem prevents compiling code that shouldn't even produce a warning under Windows. Fixing or working around either of these issues would already help me.

**Comment by eed3si9n** [comment]
Here's my PR for this - https://github.com/sbt/sbt/pull/6730

**Comment by pweisenburger** [comment]
Thanks for the fix!
