### ISSUE TITLE
1.6.0-RC1 no longer downloads snapshot dependencies

### ISSUE THREAD

**Issue by hmemcpy** [sbt/sbt#6737]
In our project we're depending on a snapshot version of a library (jeromq) from sonatype, using the `changing ()` keyword.
Since upgrading to 1.6.0-RC1 (from 1.6.0-M1) it no longer resolves the latest snapshot version, failing to find `org.zeromq:jeromq:0.5.3-SNAPSHOT`

The minimal sbt project to reproduce:

**build.sbt**
```scala
ThisBuild / scalaVersion     := "2.13.7"
ThisBuild / version          := "0.1.0-SNAPSHOT"
ThisBuild / organization     := "com.example"
ThisBuild / organizationName := "example"

lazy val root = (project in file("."))
  .settings(
    resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots",
    libraryDependencies ++= Seq(
      "org.zeromq" % "jeromq" % "0.5.3-SNAPSHOT" changing ()
    )
  )
```

With sbt 1.6.0-M1 this downloads just fine, with 1.6.0-RC1 this fails with `ResolveException`.

See attached logs:

<details>
 <summary>1.6.0-M1 (macOS, run with --debug)</summary>

```
# Executing command line:
java
-Dfile.encoding=UTF-8
-Dscala.ext.dirs=/Users/hmemcpy/.sbt/0.13/java9-rt-ext-graalvm_community_11_0_12
-Xms1024M
-Xmx4G
-Xss2M
-XX:+UseG1GC
-jar
/usr/local/Cellar/sbt/1.4.4/libexec/bin/sbt-launch.jar
-debug
compile

[debug] [zinc] IncrementalCompile -----------
[debug] IncrementalCompile.incrementalCompile
[debug] previous = Stamps for: 0 products, 0 sources, 0 libraries
[debug] current source = Set()
[debug] > initialChanges = InitialChanges(Changes(added = Set(), removed = Set(), changed = Set(), unmodified = ...),Set(),Set(),API Changes: Set())
[debug] Full compilation, no sources in previous analysis.
[debug] Created transactional ClassFileManager with tempDir = /Users/hmemcpy/.sbt/1.0/plugins/target/scala-2.12/sbt-1.0/classes.bak
[debug] Removing the temporary directory used for backing up class files: /Users/hmemcpy/.sbt/1.0/plugins/target/scala-2.12/sbt-1.0/classes.bak
[debug] Copy resource mappings: 
[debug] 	
[debug] Other repositories:
[debug] Default repositories:
[debug] Using inline dependencies specified in Scala.
[debug] [zinc] IncrementalCompile -----------
[debug] IncrementalCompile.incrementalCompile
[debug] previous = Stamps for: 2 products, 1 sources, 3 libraries
[debug] current source = Set(${BASE}/project/Dependencies.scala)
[debug] > initialChanges = InitialChanges(Changes(added = Set(), removed = Set(), changed = Set(), unmodified = ...),Set(),Set(),API Changes: Set())
[debug] No changes
[debug] Created transactional ClassFileManager with tempDir = /Users/hmemcpy/git/sbt-bug/project/target/scala-2.12/sbt-1.0/classes.bak
[debug] Removing the temporary directory used for backing up class files: /Users/hmemcpy/git/sbt-bug/project/target/scala-2.12/sbt-1.0/classes.bak
[debug] Copy resource mappings: 
[debug] 	
[warn] jeromq-0.5.3-20211128.145727-50.jar no longer exists at /Users/hmemcpy/Library/Caches/Coursier/v1/https/oss.sonatype.org/content/repositories/snapshots/org/zeromq/jeromq/0.5.3-SNAPSHOT/jeromq-0.5.3-20211128.145727-50.jar
[debug] not up to date. inChanged = false, force = false
[debug] Updating ...
[debug] downloaded https://repo1.maven.org/maven2/org/zeromq/jeromq/0.5.3-SNAPSHOT/jeromq-0.5.3-SNAPSHOT.pom
[debug] downloaded https://repo1.maven.org/maven2/org/zeromq/jeromq/0.5.3-SNAPSHOT/jeromq-0.5.3-SNAPSHOT.pom.sha1
[debug] downloaded https://repo1.maven.org/maven2/org/zeromq/jeromq/0.5.3-SNAPSHOT/maven-metadata.xml
[debug] downloaded https://repo1.maven.org/maven2/org/zeromq/jeromq/0.5.3-SNAPSHOT/maven-metadata.xml.sha1
[debug] downloaded https://oss.sonatype.org/content/repositories/snapshots/org/zeromq/jeromq/0.5.3-SNAPSHOT/jeromq-0.5.3-SNAPSHOT.pom
[debug] downloaded https://oss.sonatype.org/content/repositories/snapshots/org/zeromq/jeromq/0.5.3-SNAPSHOT/jeromq-0.5.3-SNAPSHOT.pom.sha1
[debug] downloaded https://oss.sonatype.org/content/repositories/snapshots/org/zeromq/jeromq/0.5.3-SNAPSHOT/maven-metadata.xml
[debug] downloaded https://oss.sonatype.org/content/repositories/snapshots/org/zeromq/jeromq/0.5.3-SNAPSHOT/maven-metadata.xml.sha1
[debug] downloaded https://oss.sonatype.org/content/repositories/snapshots/org/zeromq/jeromq/0.5.3-SNAPSHOT/jeromq-0.5.3-20211128.145727-50.pom
[debug] downloaded https://oss.sonatype.org/content/repositories/snapshots/org/zeromq/jeromq/0.5.3-SNAPSHOT/jeromq-0.5.3-20211128.145727-50.pom.sha1
[debug] downloaded https://oss.sonatype.org/content/repositories/snapshots/org/zeromq/jeromq/0.5.3-SNAPSHOT/jeromq-0.5.3-20211128.145727-50.jar
[debug] downloaded https://oss.sonatype.org/content/repositories/snapshots/org/zeromq/jeromq/0.5.3-SNAPSHOT/jeromq-0.5.3-20211128.145727-50.jar.sha1
[debug] Done updating 
[debug] [zinc] IncrementalCompile -----------
[debug] IncrementalCompile.incrementalCompile
[debug] previous = Stamps for: 4 products, 1 sources, 1 libraries
[debug] current source = Set(${BASE}/src/main/scala/example/Hello.scala)
[debug] > initialChanges = InitialChanges(Changes(added = Set(), removed = Set(), changed = Set(), unmodified = ...),Set(),Set(),API Changes: Set())
[debug] No changes
[debug] Created transactional ClassFileManager with tempDir = /Users/hmemcpy/git/sbt-bug/target/scala-2.13/classes.bak
[debug] Removing the temporary directory used for backing up class files: /Users/hmemcpy/git/sbt-bug/target/scala-2.13/classes.bak
```
</details>

<details>
 <summary>1.6.0-RC1 (macOS, run with --debug)</summary>

```
# Executing command line:
java
-Dfile.encoding=UTF-8
-Dscala.ext.dirs=/Users/hmemcpy/.sbt/0.13/java9-rt-ext-graalvm_community_11_0_12
-Xms1024M
-Xmx4G
-Xss2M
-XX:+UseG1GC
-jar
/usr/local/Cellar/sbt/1.4.4/libexec/bin/sbt-launch.jar
-debug
compile

[debug] [zinc] IncrementalCompile -----------
[debug] IncrementalCompile.incrementalCompile
[debug] previous = Stamps for: 0 products, 0 sources, 0 libraries
[debug] current source = Set()
[debug] > initialChanges = InitialChanges(Changes(added = Set(), removed = Set(), changed = Set(), unmodified = ...),Set(),Set(),API Changes: Set())
[debug] Full compilation, no sources in previous analysis.
[debug] Created transactional ClassFileManager with tempDir = /Users/hmemcpy/.sbt/1.0/plugins/target/scala-2.12/sbt-1.0/classes.bak
[debug] Removing the temporary directory used for backing up class files: /Users/hmemcpy/.sbt/1.0/plugins/target/scala-2.12/sbt-1.0/classes.bak
[debug] Copy resource mappings: 
[debug] 	
[debug] Other repositories:
[debug] Default repositories:
[debug] Using inline dependencies specified in Scala.
[debug] [zinc] IncrementalCompile -----------
[debug] IncrementalCompile.incrementalCompile
[debug] previous = Stamps for: 2 products, 1 sources, 3 libraries
[debug] current source = Set(${BASE}/project/Dependencies.scala)
[debug] > initialChanges = InitialChanges(Changes(added = Set(), removed = Set(), changed = Set(), unmodified = ...),Set(),Set(),API Changes: Set())
[debug] No changes
[debug] Created transactional ClassFileManager with tempDir = /Users/hmemcpy/git/sbt-bug/project/target/scala-2.12/sbt-1.0/classes.bak
[debug] Removing the temporary directory used for backing up class files: /Users/hmemcpy/git/sbt-bug/project/target/scala-2.12/sbt-1.0/classes.bak
[debug] Copy resource mappings: 
[debug] 	
[debug] not up to date. inChanged = true, force = false
[debug] Updating ...
[debug] downloaded https://repo1.maven.org/maven2/org/zeromq/jeromq/0.5.3-SNAPSHOT/jeromq-0.5.3-SNAPSHOT.pom
[debug] downloaded https://repo1.maven.org/maven2/org/zeromq/jeromq/0.5.3-SNAPSHOT/jeromq-0.5.3-SNAPSHOT.pom.sha1
[debug] downloaded https://repo1.maven.org/maven2/org/zeromq/jeromq/0.5.3-SNAPSHOT/maven-metadata.xml
[debug] downloaded https://repo1.maven.org/maven2/org/zeromq/jeromq/0.5.3-SNAPSHOT/maven-metadata.xml.sha1
[debug] downloaded https://oss.sonatype.org/content/repositories/snapshots/org/zeromq/jeromq/0.5.3-SNAPSHOT/jeromq-0.5.3-SNAPSHOT.pom
[debug] downloaded https://oss.sonatype.org/content/repositories/snapshots/org/zeromq/jeromq/0.5.3-SNAPSHOT/jeromq-0.5.3-SNAPSHOT.pom.sha1
[debug] downloaded https://oss.sonatype.org/content/repositories/snapshots/org/zeromq/jeromq/0.5.3-SNAPSHOT/maven-metadata.xml
[debug] downloaded https://oss.sonatype.org/content/repositories/snapshots/org/zeromq/jeromq/0.5.3-SNAPSHOT/maven-metadata.xml.sha1
[debug] downloaded https://oss.sonatype.org/content/repositories/snapshots/org/zeromq/jeromq/0.5.3-SNAPSHOT/maven-metadata.xml
[debug] downloaded https://oss.sonatype.org/content/repositories/snapshots/org/zeromq/jeromq/0.5.3-SNAPSHOT/maven-metadata.xml.sha1
[warn] 
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading org.zeromq:jeromq:0.5.3-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /Users/hmemcpy/.ivy2/local/org.zeromq/jeromq/0.5.3-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/zeromq/jeromq/0.5.3-SNAPSHOT/jeromq-0.5.3-SNAPSHOT.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/org/zeromq/jeromq/0.5.3-SNAPSHOT/jeromq-0.5.3-SNAPSHOT.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:345)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:314)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:314)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:59)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3690)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:829)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.zeromq:jeromq:0.5.3-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /Users/hmemcpy/.ivy2/local/org.zeromq/jeromq/0.5.3-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/zeromq/jeromq/0.5.3-SNAPSHOT/jeromq-0.5.3-SNAPSHOT.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/org/zeromq/jeromq/0.5.3-SNAPSHOT/jeromq-0.5.3-SNAPSHOT.pom
```
</details>

In both cases, the Coursier cache (at `~/Library/Caches/Coursier/v1/https/oss.sonatype.org/content/repositories/`) was deleted to force redownload.

Reading the release notes for RC1 I'm not sure where the culprit is, perhaps the Coursier version update in #6725?

**Comment by hmemcpy** [comment]
Tagging @alexarchambault for additional input perhaps?

**Comment by eed3si9n** [comment]
@hmemcpy Thanks for the report. Could you also open the issue on coursier/coursier please?

**Comment by hmemcpy** [comment]
@eed3si9n just did! I managed to reproduce this with just coursier 2.1.0-M1, so I think it's an issue there https://github.com/coursier/coursier/issues/2287

**Comment by SethTisue** [comment]
I suspect we may be hitting this over at https://github.com/scala/scala/pull/9763 . Or maybe it's something else, but I'm not sure digging into it makes sense until this ticket is fixed.

I guess I'll wait for 1.6.0-RC2 and then try again, but @eed3si9n if you want me to test a nightly build or something _before_ RC2 is available, I could do that.

**Comment by eed3si9n** [comment]
Looks like https://github.com/coursier/sbt-coursier/releases/tag/v2.0.10 was released so we can move forward. 

@SethTisue Thanks. Maybe I should build M2 before announcing it as RC2 then.

**Comment by eed3si9n** [comment]
Given the mounting log4j issues, I am now thinking it would be better to have an RC2 out soon this weekend (when I have time).
