### ISSUE TITLE
libraryDependencySchemes doesn't seem to work for scala-java8-compat

### ISSUE THREAD

**Issue by alexklibisz** [sbt/sbt#6745]
## steps

Reproducible example on Scastie: https://scastie.scala-lang.org/hRyPIl7IQiCLzo2RXG6gwg

Using SBT 1.5.6. Not necessarily restricted to 1.5.6, I haven't checked other 1.5.x. I'm not sure what version of SBT scastie is using, but it fails the same as 1.5.6 in a local project.

With following dependencies:

- akka-actor 2.6.0, which depends on scala-java8-compat 0.8.0.
- swagger-akka-http 1.4.0, which depends on scala-java8-compat 0.9.1.

With following eviction settings:

```
assumedEvictionErrorLevel := Level.Error
assumedVersionScheme := VersionScheme.EarlySemVer
libraryDependencySchemes += "org.scala-lang.modules" %% "scala-java8-compat" % VersionScheme.Always
```

## problem

`sbt evicted` still returns an error:

```
java.lang.RuntimeException: found version conflict(s) in library dependencies; some are suspected to be binary incompatible:

	* org.scala-lang.modules:scala-java8-compat_2.12:0.9.1 (early-semver?) is selected over 0.8.0
	    +- com.github.swagger-akka-http:swagger-akka-http_2.12:1.4.0 (depends on 0.9.1)
	    +- com.typesafe.akka:akka-actor_2.12:2.6.0            (depends on 0.8.0)


this can be overridden using libraryDependencySchemes or evictionErrorLevel
	at scala.sys.package$.error(package.scala:30)
	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:89)
	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3678)
	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.Execute.work(Execute.scala:291)
	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

## expectation

From my understanding, the `libraryDependencySchemes` setting to `Always` should mean that versions of scala-java8-compat library are _always_ compatible. So the 0.8.0 and 0.9.1 incompatibility should be ignored, and the error should not be thrown.

## notes

Is setting the version scheme for a specific library to "always" the correct way to specify "don't check the version compatibility of this library"? That's what it seems like from the docs and release notes, but maybe I've missed someting.

**Comment by SethTisue** [comment]
The problem goes away if you don't set `assumedVersionScheme`. I don't know what to make of that.

**Comment by eed3si9n** [comment]
If that indicates that assumption logic (`assumedVersionScheme`) is taking higher precedence than manually set `libraryDependencySchemes` overrides, that sounds like a bug?

**Comment by alexklibisz** [comment]
FWIW, still seeing this in 1.8.2. This time w/ scala-xml

**Comment by ches** [comment]
@alexklibisz Not sure if this is the case for you for scala-xml, but it was for me and it might help some others:

The source of a scala-xml conflict for me was _in the metabuild_, with (2.12…) scala-compiler depending on 2.x and several sbt plugins wanting 1.x.

Since it's the metabuild the solution is to _make the setting in **project/**_ such as `project/plugins.sbt`.

```scala
libraryDependencySchemes += "org.scala-lang.modules" %% "scala-xml" % VersionScheme.Always
```

This worked for me. (Well, with fingers crossed that we don't encounter any runtime errors).

I'm using sbt 1.8.2.

I do not set `assumedVersionScheme` explicitly and `show assumedVersionScheme` shows `always` as the default. For science I tried setting it to `VersionScheme.EarlySemVer` in light of @SethTisue's earlier point and it didn't make a difference either way. That is expected though since scala-xml 2.1.0 does have a version scheme property in its POM, an assumed scheme shouldn't be applied to it.

**Comment by alexklibisz** [comment]
@ches  Yeah, I had to do this in a project recently, too. I put the setting in project/build.sbt. Seemed like it relates to the recent scala-xml major dependency upgrade. https://github.com/sbt/sbt/issues/6997

**Comment by eed3si9n** [comment]
A fix was contributed by @adriaanm in https://github.com/sbt/librarymanagement/pull/415
