### ISSUE TITLE
[1.6] java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:///D:/sbt16/ on Windows

### ISSUE THREAD

**Issue by OlegYch** [sbt/sbt#6774]
## steps
use windows
create play v2.8 project eg using `sbt new playframework/play-scala-seed.g8`
set sbt version to 1.6 eg using `printf sbt.version=1.6.0-M1> project\build.properties`

## problem

`assets` task fails with `[error] (Web-assets / assets) java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:///D:/sbt16/play-scala-seed/public/javascripts/main.js`

## notes
sbt 1.5.8 works fine

**Comment by eed3si9n** [comment]
@OlegYch Thanks for the report. Do you have a stacktrace on this? (last may display this)

This sound related to previous issues with Windows + Scalac returning fake positions:
- https://github.com/sbt/sbt/issues/6720
- https://github.com/sbt/sbt/issues/5994

**Comment by OlegYch** [comment]
@eed3si9n 
```
[error] java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:///D:/sbt16/play-scala-seed/public/javascripts/main.js
[error]         at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
[error]         at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
[error]         at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
[error]         at sun.nio.fs.WindowsPath.parse(Unknown Source)
[error]         at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
[error]         at java.nio.file.Paths.get(Unknown Source)
[error]         at sbt.internal.inc.MappedVirtualFile$.toPath(MappedVirtualFile.scala:36)
[error]         at sbt.internal.inc.MappedFileConverter.toPath(MappedVirtualFile.scala:53)
[error]         at sbt.Sync$.$anonfun$convertFromVirtual$1(Sync.scala:175)
[error]         at sbt.internal.util.Relation$.$anonfun$switch$1(Relation.scala:58)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
[error]         at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:400)
[error]         at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:728)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:286)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
[error]         at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error]         at sbt.internal.util.Relation$.switch(Relation.scala:56)
[error]         at sbt.Sync$.convertFromVirtual(Sync.scala:175)
[error]         at sbt.Sync$.readInfoWrapped(Sync.scala:168)
[error]         at sbt.Sync$.$anonfun$sync$1(Sync.scala:67)
[error]         at com.typesafe.sbt.web.SbtWeb$.syncMappings(SbtWeb.scala:537)
[error]         at com.typesafe.sbt.web.SbtWeb$.$anonfun$unscopedAssetSettings$40(SbtWeb.scala:293)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.util.concurrent.FutureTask.run(Unknown Source)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[error]         at java.util.concurrent.FutureTask.run(Unknown Source)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[error]         at java.lang.Thread.run(Unknown Source)
```

**Comment by mkurz** [comment]
Another report here: https://github.com/playframework/playframework/issues/11087

**Comment by Nirvikalpa108** [comment]
@OlegYch @eed3si9n @mkurz 
Hi, I've tried reproducing this, but I can't get it to break using the steps described in this issue. If you have ideas of anything else I can try, please let me know. Thank you

**Comment by OlegYch** [comment]
@Nirvikalpa108 apparently this only happens if the project is on another drive eg 'd:\'

**Comment by OlegYch** [comment]
looks like caches produced by sbt.Sync 1.5 were storing info in format incompatible with 1.6
the error is gone after clean

**Comment by jxtps** [comment]
I have a project that uses a submodule, and `sbt clean` did not clean things out sufficiently to recover. 

I had to manually go in and delete `/target`, `/project/target`, and `/submodule/target` to get it to work. 

Perhaps we could add versioning information to sensitive files so that sbt can detect that it needs to rewrite them?
