### ISSUE TITLE
sbt thinks that server is already booting because of this exception

### ISSUE THREAD

**Issue by a1russell** [sbt/sbt#6777]
## steps

Using sbt 1.6.1 on Windows 10. I am also using Amazon Corretto JDK 8.312, if that makes a difference. The issue is present in both Git Bash and cmd.

1. Open a terminal, cd to a project, and execute `sbt`.
2. Open another terminal, cd to the same project, and try executing `sbt` in any form, including `sbt --no-server`. This will give an error.

## problem

This is what I receive upon executing the second sbt command:
```
>sbt --no-server compile
sbt thinks that server is already booting because of this exception:
sbt.internal.ServerAlreadyBootingException: java.io.IOException: Could not create lock for \\.\pipe\sbt-load-8979016220299674466_lock, error 5
        at sbt.internal.BootServerSocket.newSocket(BootServerSocket.java:348)
        at sbt.internal.BootServerSocket.<init>(BootServerSocket.java:294)
        at sbt.xMain$.getSocketOrExit(Main.scala:145)
        at sbt.xMain$.bootServerSocket$lzycompute$1(Main.scala:77)
        at sbt.xMain$.bootServerSocket$1(Main.scala:77)
        at sbt.xMain$.withStreams$1(Main.scala:85)
        at sbt.xMain$.run(Main.scala:121)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:57)
        at sbt.xMain.run(Main.scala:46)
        at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
        at xsbt.boot.Launch$.run(Launch.scala:149)
        at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
        at xsbt.boot.Launch$.launch(Launch.scala:159)
        at xsbt.boot.Launch$.apply(Launch.scala:44)
        at xsbt.boot.Launch$.apply(Launch.scala:21)
        at xsbt.boot.Boot$.runImpl(Boot.scala:78)
        at xsbt.boot.Boot$.run(Boot.scala:73)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.io.IOException: Could not create lock for \\.\pipe\sbt-load-8979016220299674466_lock, error 5
        at org.scalasbt.ipcsocket.Win32NamedPipeServerSocket.<init>(Win32NamedPipeServerSocket.java:129)
        at org.scalasbt.ipcsocket.Win32NamedPipeServerSocket.<init>(Win32NamedPipeServerSocket.java:48)
        at sbt.internal.BootServerSocket.newSocket(BootServerSocket.java:342)
        ... 23 more
Create a new server? y/n (default y)
```

## expectation

Ideally, the server would work without my intervention. If the server absolutely can't work, at least there should be a working way to disable it (again, without my intervention).

## notes

This issue, at least in some form, was reported previously in #6101, which has been marked as closed with #6728. However, the issue is still present for me.

**Comment by trinitronx** [comment]
+1 to this being an issue (Especially in CI/CD).  In case it helps track this exception down:

I was able to reproduce this on MacOS Monterey `12.3` using Docker Desktop `4.6.1` by turning on the new VirtioFS experimental feature.  With that "`Enable VirtioFS accelerated directory sharing`" setting checked, a container running `sbt test` gets stuck asking for confirmation to start a server:

```
sbt thinks that server is already booting because of this exception:
java.io.IOException: org.scalasbt.ipcsocket.NativeErrorException: [1] Operation not permitted
Create a new server? y/n (default y)
```

The tests run blazingly fast under VirtioFS, but require user interaction to type in `y`. (Although you could probably use `yes` or `expect` commands to work around this).

Turning the VirtioFS setting off and also unchecking "`Use the new Virtualization framework`" under Docker Desktop's "`Experimental Features`" section avoids the issue.  The tests run much more slowly, but don't require user interaction.

**Comment by AlonsoM45** [comment]
I have managed to get this working with one of the suggestions in the original issue. Add the options `--batch -Dsbt.server.forcestart=true` when running sbt.
Examples:
`sbt --batch -Dsbt.server.forcestart=true compile`
`sbt --batch -Dsbt.server.forcestart=true run`

However, that seems to only be a workaround instead of an actual fix for this issue.

**Comment by a1russell** [comment]
To be clear, the workaround mentioned by @AlonsoM45 does not work for me, either.

**Comment by spangaer** [comment]
The one with batch work for me, but obviously you don't get a working interactive mode. But that fine.
`.bash_aliases`
`alias wsbt='sbt --batch -Dsbt.server.forcestart=true'`

**Comment by AlonsoM45** [comment]
I have been researching more about this issue. I realized that, in my case, this happens because the directory that contains the file is on a Network File System (which results in the socket being created on the NFS, since the socket is created on **<project-directory>/project/target**). I have been doing some tests and I discovered that my particular issue can be avoided if the socket is created on another location. 

I think maybe there could be an option for **sbt** that allows us to specify the location of the socket. Consider this scenario:
- **/home/username/nfs-dir/** directory is on a NFS
- **/home/username/normal-dir/** directory is a normal directory
- I want to create my project at **/home/username/nfs-dir/project-dir/**
- If I run `sbt compile` (or any other sbt command, for that matter) while being on **/home/username/nfs-dir/project-dir/**, then sbt will try to create the socket at **/home/username/nfs-dir/project-dir/project/target/sbt-socket.sock** (I think that is the name of the socket, it might be something different but it does not matter much) and will fail, because that location is on a NFS.

**There are two solutions I can think of:**
### Socket Location Flag
Instead of running `sbt compile`, I could run `sbt compile -Dsbt.server.socketlocation=/home/username/normal-dir/.custom-socket-location`, and then sbt would know that it must create the socket at **/home/username/normal-dir/.custom-socket-location/sbt-socket.sock**. The socket will be created succesfully and that would be the end of that (I think all references to the location of the socket use the same function to compute the location).

### Global Configuration for Socket Locations
I could run `sbt compile` after having applied a global configuration for sbt. Maybe an option in **.sbtopts**, called **alternativeSocketRootLocation**. Let's say I set **alternativeSocketRootLocation** to **/home/username/.alternative-socket-root-location** and, when I try to compile my project, **stb** will create the socket at **/home/username/.alternative-socket-root-location/home/username/nfs-dir/project-dir/sbt-socket.sock**.

As you can see, this path is composed of  **/home/username/.alternative-socket-root-location/** (the alternative location I configured for my project) followed by **home/username/nfs-dir/project-dir/sbt-socket.sock** (the absolute path of the project). This convention will prevent conflicts between sockets that belong to different projects. Maybe something else could be used; for instance we could use a hash computed from the absolute path of the project, which would result in something like **/home/username/.alternative-socket-root-location/6aa341ccdhh1010/sbt-socket.sock**.

The idea with this second option is to simplify the way in which one could handle projects in an environment where not all directories will allow the creaton of sockets, while also preventing an scenario where the user will need to pass the flags each and every time an sbt command is run. It will also help with sbt commands that are run automatically (in my case, I stumbled upon this bug while using **Metals**, which at some point runs **sbt bloopInstall** and it fails).

Let me know what you think about these options.

By the way, you might wonder: _Why am I creating the project on the NFS?_  It is part of the requirements of the project I am working on. Metals support is also another requirement, and that is the reason why I am so interested in finding a solution for this problem (and a solution that can be integrated into **sbt**; I will get nowhere if I apply a dirty patch in a custom sbt version generated by me).

**Comment by mikenac** [comment]
Confirmed. This is still an issue. I am running this with 1.6.2 on Alpine in docker and it fails with --no-server.

**Comment by arobert-da** [comment]
(Edited) Can confirm this is resolved (for running in a VM with source in a shared filesystem) with 1.8.2.

**Comment by jonathancrosmer** [comment]
This happens for me even on 1.8.2 on a vanilla, brand-new Ubuntu desktop install:

```
$ sbt
sbt thinks that server is already booting because of this exception:
sbt.internal.ServerAlreadyBootingException: java.io.IOException: org.scalasbt.ipcsocket.NativeErrorException: [13] Permission denied
	at sbt.internal.BootServerSocket.newSocket(BootServerSocket.java:356)
	at sbt.internal.BootServerSocket.<init>(BootServerSocket.java:295)
	at sbt.xMain$.getSocketOrExit(Main.scala:150)
	at sbt.xMain$.bootServerSocket$lzycompute$1(Main.scala:77)
	at sbt.xMain$.bootServerSocket$1(Main.scala:77)
	at sbt.xMain$.withStreams$1(Main.scala:85)
	at sbt.xMain$.run(Main.scala:121)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:57)
	at sbt.xMain.run(Main.scala:46)
	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
	at xsbt.boot.Launch$.run(Launch.scala:149)
	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
	at xsbt.boot.Launch$.launch(Launch.scala:159)
	at xsbt.boot.Launch$.apply(Launch.scala:44)
	at xsbt.boot.Launch$.apply(Launch.scala:21)
	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
	at xsbt.boot.Boot$.run(Boot.scala:73)
	at xsbt.boot.Boot$.main(Boot.scala:21)
	at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.io.IOException: org.scalasbt.ipcsocket.NativeErrorException: [13] Permission denied
	at org.scalasbt.ipcsocket.UnixDomainServerSocket.bind(UnixDomainServerSocket.java:140)
	at org.scalasbt.ipcsocket.UnixDomainServerSocket.<init>(UnixDomainServerSocket.java:114)
	at org.scalasbt.ipcsocket.UnixDomainServerSocket.<init>(UnixDomainServerSocket.java:93)
	at sbt.internal.BootServerSocket.newSocket(BootServerSocket.java:350)
	... 21 more
Caused by: org.scalasbt.ipcsocket.NativeErrorException: [13] Permission denied
	at org.scalasbt.ipcsocket.JNAUnixDomainSocketLibraryProvider.bind(UnixDomainSocketLibrary.java:178)
	at org.scalasbt.ipcsocket.UnixDomainServerSocket.bind(UnixDomainServerSocket.java:136)
	... 24 more
Create a new server? y/n (default y)
y
[info] welcome to sbt 1.8.2 (Private Build Java 19.0.1)
[info] loading settings for project ...```

**Comment by AlonsoM45** [comment]
What is your `XDG_RUNTIME_DIR` environment variable set to? If that variable is set, then that should be the place where **sbt** is trying to create a socket.

**Comment by Winand** [comment]
I've managed to run the second instance of sbt 1.9.1 on Windows 10 using the following env variables:
```
SBT_SERVER_FORCESTART=1
SBT_TERMINAL_PROPS="80,20,false,false,false"
```
See also [xMain.getSocketOrExit](https://github.com/sbt/sbt/blob/v1.9.1/main/src/main/scala/sbt/Main.scala#L144)

**Comment by dontgitit** [comment]
I get the same results with `sbt` and `sbt --client`, however `sbt --no-server` and `sbtn` both appear to work without errors;
```
sbt
[info] welcome to sbt 1.10.10 (Eclipse Adoptium Java 21.0.6)
[info] loading project definition from C:\Users\ilya\IdeaProjects\TestXlint\project
[info] loading settings for project root from build.sbt...
[info] set current project to TestXlint (in build file:/C:/Users/ilya/IdeaProjects/TestXlint/)
[error] server failed to start on local:sbt-server-786a926c76b0a8dd8905. java.io.IOException: Could not create lock for \\.\pipe\sbt-server-786a926c76b0a8dd8905_lock, error 5
```

```
sbt --client
[info] welcome to sbt 1.10.10 (Eclipse Adoptium Java 21.0.6)
[info] loading project definition from C:\Users\ilya\IdeaProjects\TestXlint\project
[info] loading settings for project root from build.sbt...
[info] set current project to TestXlint (in build file:/C:/Users/ilya/IdeaProjects/TestXlint/)
[error] server failed to start on local:sbt-server-786a926c76b0a8dd8905. java.io.IOException: Could not create lock for \\.\pipe\sbt-server-786a926c76b0a8dd8905_lock, error 5
```

```
sbt --no-server
[info] welcome to sbt 1.10.10 (Eclipse Adoptium Java 21.0.6)
[info] loading project definition from C:\Users\ilya\IdeaProjects\TestXlint\project
[info] loading settings for project root from build.sbt...
[info] set current project to TestXlint (in build file:/C:/Users/ilya/IdeaProjects/TestXlint/)
sbt:TestXlint>
```

```
sbtn
[info] entering *experimental* thin client - BEEP WHIRR
[info] terminate the server with `shutdown`
[info] disconnect from the server with `exit`
sbt:TestXlint>
```
