### ISSUE TITLE
SBT launcher still extracts a pseudo rt.jar for JDK9+, this plays badly with scalac -release, at least for @PolymorphicSignature support for MethodHandle.invoke

### ISSUE THREAD

**Issue by retronym** [sbt/sbt#6817]
## steps

```
➜ find . -type f | grep -v target | grep -v .idea | grep -v .bsp | xargs tail -n100
==> ./project/build.properties <==
sbt.version=1.6.2

==> ./build.sbt <==

ThisBuild / scalaVersion := "2.13.8"

ThisBuild / scalacOptions ++= List("-release", "11", "-Ylog-classpath")

==> ./src/main/scala/MethodHandleInvoke.scala <==

object MethodHandleInvoke {
  def main(args: Array[String]): Unit = {
    import java.lang.invoke._
    val lookup = MethodHandles.lookup()
    val String_hashCode = lookup.findVirtual(classOf[String], "hashCode", MethodType.methodType(Integer.TYPE))
    String_hashCode.invoke("")
  }
}

➜  /opt/homebrew/Cellar/sbt/1.6.2/libexec/bin/sbt clean run
[info] welcome to sbt 1.6.1 (Azul Systems, Inc. Java 16)
[info] loading global plugins from /Users/jz/.sbt/1.0/plugins
[info] loading project definition from /Users/jz/code/java-17-weirdness/project
[info] loading settings for project java-17-weirdness from build.sbt ...
[info] set current project to java-17-weirdness (in build file:/Users/jz/code/java-17-weirdness/)
[success] Total time: 0 s, completed 9 Feb 2022, 9:07:32 am
[info] compiling 1 Scala source to /Users/jz/code/java-17-weirdness/target/scala-2.13/classes ...
Classpath built from (-bootclasspath = /Users/jz/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8.jar -encoding = UTF-8 -classpath = /Users/jz/code/java-17-weirdness/target/scala-2.13/classes -release = 11 -Vclasspath = true)
Defaults: object Defaults {
  scalaHome            =
  javaBootClassPath    =
  scalaLibDirFound     = None
  scalaLibFound        =
  scalaBootClassPath   =
  scalaPluginPath      = misc/scala-devel/plugins
}
Calculated: object Calculated {
  scalaHome            =
  javaBootClassPath    =
  javaExtDirs          =
  javaUserClassPath    =
  useJavaClassPath     = false
  scalaBootClassPath   = /Users/jz/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8.jar
  scalaExtDirs         = /Users/jz/.sbt/1.0/java9-rt-ext-azul_systems__inc__16
  userClassPath        = /Users/jz/code/java-17-weirdness/target/scala-2.13/classes
  sourcePath           =
}
After java boot/extdirs classpath has 3 entries:
  ZipArchiveClassPath(/Users/jz/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8.jar,Some(11))
  ZipArchiveClassPath(/Users/jz/.sbt/1.0/java9-rt-ext-azul_systems__inc__16/rt.jar,Some(11))
  DirectoryClassPath(/Users/jz/code/java-17-weirdness/target/scala-2.13/classes)
[info] [search path for source files: ]
[info] [search path for class files: /Users/jz/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8.jar:/Users/jz/.sbt/1.0/java9-rt-ext-azul_systems__inc__16/rt.jar:/Users/jz/code/java-17-weirdness/target/scala-2.13/classes]
[info] running MethodHandleInvoke
[error] java.lang.ClassCastException: Cannot cast [Ljava.lang.Object; to java.lang.String
[error] 	at java.base/java.lang.Class.cast(Class.java:3818)
[error] 	at MethodHandleInvoke$.main(MethodHandleInvoke.scala:7)
[error] 	at MethodHandleInvoke.main(MethodHandleInvoke.scala)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[error] stack trace is suppressed; run last Compile / run for the full output
[error] (Compile / run) java.lang.ClassCastException: Cannot cast [Ljava.lang.Object; to java.lang.String
[error] Total time: 5 s, completed 9 Feb 2022, 9:07:37 am

```

## problem

The standard SBT launcher script extracts a pseudo rt.jar from the jrt:// NIO filesystem in JDK9+, and forces this onto the compiler's classpath with -Dscala.ext.dir=

This was done to support using legacy scalac versions, either for compiling the build itself or for the user's code.

However, when using `scalac -release`, we don't want the current API visible to the compiler, the compiler loads a historical snapshot of the API from the ct.sym archive. This is first on the AggregateClassPath, but the presence of rt.jar later on can cause problems.

The problem I noticed here is quite subtle -- Scala already has a hack for recognising `@PolymorphicSignature` annotated methods (e.g. `MethodHandle.invoke`) when using `-release`. That hack is necessary because `PolymorphicSignature` is not public, and as such not included in the historical API. So the compiler is able to match based on the fully qualified name of the annotation reference, even when the referred-to class is absent from the classpath. This hack gets foiled by the existence of `pseudo-rt.jar!/java/lang/invoke/MethodHandles$PolymorphicSignature.class`. I will generalize the existing hack in scalac to accomodate this.

But more generally, the presence of the pseudo rt.jar on the classpath may prevent the compiler issuing "symbol not found" errors if code refers to a newly added class/method in the JDK that it should not see given the `-release` option.

## expectation

The launcher script could continue to extract rt.jar for backwards compatiblity, but SBT should not pass it to the compiler when "-release" is among the compiler options.

**Comment by SethTisue** [comment]
@retronym @lrytz @dwijnand after https://github.com/scala/scala/pull/9930 (Scala 2.12.16 / Scala 2.13.9) we no longer look for `PolymorphicSignature` at all, but follow the JLS spec on how to identify polymorphic methods

so perhaps this isn't an issue at all anymore...?
