### ISSUE TITLE
`derivedProjects` does not work if there is no explicit projects

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt#6860]
### `build.sbt`

```scala
name := "sample"
```

### `project/SampleDerivedProject.scala`

```scala
import sbt._

object SampleDerivedProjects extends AutoPlugin {
  val value1 = settingKey[Int]("value1")

  val myGenerateProject = Project("foo", file("foo")).settings(
    value1 := 3
  )

  override def derivedProjects(proj: ProjectDefinition[?]) =
    proj.projectOrigin match {
      case ProjectOrigin.DerivedProject =>
        Nil
      case _ =>
        Seq(myGenerateProject)
    }

  override def trigger = allRequirements

  override def projectSettings = Seq(
    SettingKey[Int]("value2") := (myGenerateProject / value1).value
  )
}
```

## problem

```
[info] welcome to sbt 1.6.2 (Temurin Java 1.8.0_322)
[info] loading global plugins from /Users/kenji/.sbt/1.0/plugins
[info] loading project definition from /Users/kenji/sbt-derivedProjects-bug/project
[info] loading settings for project sbt-derivedprojects-bug from build.sbt ...
Reference to undefined setting: 

  foo / value1 from value2 (/Users/kenji/sbt-derivedProjects-bug/project/SampleDerivedProject.scala:22)
 
	at sbt.internal.util.Init.Uninitialized(Settings.scala:419)
	at sbt.internal.util.Init.Uninitialized$(Settings.scala:406)
	at sbt.Def$.Uninitialized(Def.scala:24)
	at sbt.internal.util.Init.delegate(Settings.scala:313)
	at sbt.internal.util.Init.delegate$(Settings.scala:275)
	at sbt.Def$.delegate(Def.scala:24)
	at sbt.internal.util.Init.compiled(Settings.scala:200)
	at sbt.internal.util.Init.compiled$(Settings.scala:187)
	at sbt.Def$.compiled(Def.scala:24)
	at sbt.internal.util.Init.makeWithCompiledMap(Settings.scala:217)
	at sbt.internal.util.Init.makeWithCompiledMap$(Settings.scala:212)
	at sbt.Def$.makeWithCompiledMap(Def.scala:24)
	at sbt.internal.Load$.$anonfun$apply$5(Load.scala:263)
	at sbt.internal.Load$.timed(Load.scala:1408)
	at sbt.internal.Load$.apply(Load.scala:255)
	at sbt.internal.Load$.defaultLoad(Load.scala:56)
	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:953)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:953)
	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:906)
	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:150)
	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:145)
	at sbt.Command$.process(Command.scala:189)
	at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:245)
	at scala.Option.getOrElse(Option.scala:189)
	at sbt.MainLoop$.process$1(MainLoop.scala:245)
	at sbt.MainLoop$.processCommand(MainLoop.scala:278)
	at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:163)
	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:289)
	at sbt.State$StateOpsImpl$.process$extension(State.scala:325)
	at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:163)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.MainLoop$.next(MainLoop.scala:163)
	at sbt.MainLoop$.run(MainLoop.scala:144)
	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:119)
	at sbt.io.Using.apply(Using.scala:27)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:112)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:66)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:51)
	at sbt.MainLoop$.runLogged(MainLoop.scala:42)
	at sbt.StandardMain$.runManaged(Main.scala:215)
	at sbt.xMain$.$anonfun$run$11(Main.scala:133)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withIn(Console.scala:230)
	at sbt.internal.util.Terminal$.withIn(Terminal.scala:569)
	at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:350)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withOut(Console.scala:167)
	at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:559)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withErr(Console.scala:196)
	at sbt.internal.util.Terminal$.withOut(Terminal.scala:559)
	at sbt.internal.util.Terminal$.withStreams(Terminal.scala:350)
	at sbt.xMain$.withStreams$1(Main.scala:87)
	at sbt.xMain$.run(Main.scala:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:57)
	at sbt.xMain.run(Main.scala:46)
	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
	at xsbt.boot.Launch$.run(Launch.scala:149)
	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
	at xsbt.boot.Launch$.launch(Launch.scala:159)
	at xsbt.boot.Launch$.apply(Launch.scala:44)
	at xsbt.boot.Launch$.apply(Launch.scala:21)
	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
	at xsbt.boot.Boot$.run(Boot.scala:73)
	at xsbt.boot.Boot$.main(Boot.scala:21)
	at xsbt.boot.Boot.main(Boot.scala)
[error] Reference to undefined setting: 
[error] 
[error]   foo / value1 from value2 (/Users/kenji/sbt-derivedProjects-bug/project/SampleDerivedProject.scala:22)
[error]  
[error] Use 'last' for the full log.
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
```

### workaround 

add explicit `root` project in `build.sbt`

```scala
val root = project.in(file("."))
```

**Comment by bitcompass** [comment]
Hi, @eed3si9n 
As a new contributor, I want to work on this issue.
If this issue still available, could you assign this to me?

**Comment by eed3si9n** [comment]
@bitcompass If this issue can still be reproduced using 2.0.0-RC10, this issue is open for contribution.

As with the other issue, please check out our [Contributor's Guildeline](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) and:
1. Make sure you can reproduce the problem and the fix manually (we regularly block folks who send speculative PRs)
2. Include tests for the change
3. Follow our AI assisted contributions guideline
4. Multiple contributors might work on this issue in parallel
5. Generally we recommend getting CI to pass on a forked repo before sending a pull request
6. Sign Scala CLA <https://contribute.akka.io/contribute/cla/scala>

**Comment by bitcompass** [comment]
This issue is still reproducible on the current codebase(which targets 2.0.0-RC10).
Set expand=true for the synthetic root in `loadTransitive`, matching the behavior when an explicit root project is defined. 
Added scripted test `project/derived-no-explicit-root` to cover this scenario.

Please check this commit first.
https://github.com/bitcompass/sbt/commit/63f2606df6079089446ffb3abd0dbf7e4be10d88

**Comment by eed3si9n** [comment]
Nice. The commit looks good. Please open a pull request.

A minor note: If both cases are returning `true`, you could probably remove the `expand` variable and directly pass `true`?

**Comment by bitcompass** [comment]
Yes,  `expand` is only used in the `processProject` call, I can remove it from the tuple destructuring and pass `true` directly.
I will open a PR include this feature too.
