### ISSUE TITLE
"sbt-networkchannel-0" java.lang.NullPointerException

### ISSUE THREAD

**Issue by francisdb** [sbt/sbt#6864]
`sbt.version=1.6.2`

Darwin foo.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 **arm64**

```
java --version
openjdk 11.0.14 2022-01-18
OpenJDK Runtime Environment Microsoft-30447 (build 11.0.14+9-EA)
OpenJDK 64-Bit Server VM Microsoft-30447 (build 11.0.14+9-EA, mixed mode)
```

## steps

Reload a project in intellij a few times when sbt is already running

## problem

```
sbt
[info] welcome to sbt 1.6.2 (Microsoft Java 11.0.14)
[info] loading settings for project scala-integration-tests-build from plugins.sbt ...
[info] loading project definition from /Users/foo/test/project
[info] loading settings for project scala-integration-tests from build.sbt ...
[info] set current project to integration-tests (in build file:/Users/foo/test/)
[info] sbt server started at local:///Users/foo/.sbt/1.0/server/b63181f1ee0df9d4309b/sock
[info] started sbt server
[info] new client connected: network-1
[info] shutting down client connection network-1
[info] new client connected: network-2
sbt:integration-tests> Exception in thread "sbt-networkchannel-0" java.lang.NullPointerException
	at sbt.internal.server.NetworkChannel.sbt$internal$server$NetworkChannel$$doFlush(NetworkChannel.scala:671)
	at sbt.internal.server.NetworkChannel.shutdown(NetworkChannel.scala:567)
	at sbt.internal.server.NetworkChannel.shutdown(NetworkChannel.scala:553)
	at sbt.internal.server.NetworkChannel$$anon$3.run(NetworkChannel.scala:189)
[info] new client connected: network-3
sbt:integration-tests> Exception in thread "sbt-networkchannel-0" java.lang.NullPointerException
	at sbt.internal.server.NetworkChannel.sbt$internal$server$NetworkChannel$$doFlush(NetworkChannel.scala:671)
	at sbt.internal.server.NetworkChannel.shutdown(NetworkChannel.scala:567)
	at sbt.internal.server.NetworkChannel.shutdown(NetworkChannel.scala:553)
	at sbt.internal.server.NetworkChannel$$anon$3.run(NetworkChannel.scala:189)
exit
[info] shutting down client connection network-2
[info] shutting down client connection network-3
[info] shutting down client connection network-2
[info] shutting down client connection network-3
[info] shutting down sbt server
```

## Notes

This is not breaking anything as far as I know

**Comment by kubukoz** [comment]
```
Exception in thread "sbt-networkchannel-0" java.lang.NullPointerException: Cannot enter synchronized block because "this.sbt$internal$server$NetworkChannel$$outputBuffer" is null
        at sbt.internal.server.NetworkChannel.sbt$internal$server$NetworkChannel$$doFlush(NetworkChannel.scala:672)
        at sbt.internal.server.NetworkChannel.shutdown(NetworkChannel.scala:568)
        at sbt.internal.server.NetworkChannel.shutdown(NetworkChannel.scala:554)
        at sbt.internal.server.NetworkChannel$$anon$3.run(NetworkChannel.scala:190)
```

here's a more verbose NPE from 1.9.2.

**Comment by Primetalk** [comment]
In 1.10.7:
```
Exception in thread "sbt-networkchannel-0" java.lang.NullPointerException: Cannot enter synchronized block because "this.sbt$internal$server$NetworkChannel$$outputBuffer" is null
        at sbt.internal.server.NetworkChannel.sbt$internal$server$NetworkChannel$$doFlush(NetworkChannel.scala:672)
        at sbt.internal.server.NetworkChannel.shutdown(NetworkChannel.scala:568)
        at sbt.internal.server.NetworkChannel.shutdown(NetworkChannel.scala:554)
        at sbt.internal.server.NetworkChannel$$anon$3.run(NetworkChannel.scala:190)
```
