### ISSUE TITLE
Better error message for matching scala version error?

### ISSUE THREAD

**Issue by He-Pin** [sbt/sbt#6877]
`[IJ]++2.12
[info] Setting Scala version to 2.12 on 40 projects.
[info] Excluded 2 projects, run ++ 2.12 -v for more details.
[info] Reapplying settings...
[error] scala.MatchError: 2.12 (of class java.lang.String)
[error] Use 'last' for the full log.
[IJ]scala.MatchError: 2.12 (of class java.lang.String)
        at akka.OSGi$.scalaImport(OSGi.scala:133)
        at akka.OSGi$.defaultImports(OSGi.scala:126)
        at akka.OSGi$.$anonfun$exports$1(OSGi.scala:117)
        at scala.Function1.$anonfun$compose$1(Function1.scala:49)
        at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:228)
        at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:170)
        at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
        at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:99)
        at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

[IJ]++2.12.15
[info] Setting Scala version to 2.12.15 on 40 projects.
`

expection:

```
2.12 is not a valid scala versioin ?
```

**Comment by eed3si9n** [comment]
Thanks for the report. Please follow the prescribed format. In particular, you've omitted the reproducible steps.

From looking at the stacktraces, it seem like the problem is coming from 

```scala
[IJ]scala.MatchError: 2.12 (of class java.lang.String)
at akka.OSGi$.scalaImport(OSGi.scala:133)
```

https://github.com/akka/akka/blob/bfafb8cf0f02aa935cec5f696eae639860a9823b/project/OSGi.scala#L133 not sbt.

**Comment by He-Pin** [comment]
Sorry i missed that
