### ISSUE TITLE
NPE in coursier during compilation

### ISSUE THREAD

**Issue by coffius** [sbt/sbt#6890]
## steps
So far I don't have a minimalistic project to reproduce the error

## problem

`java.lang.NullPointerException` is thrown each time when `sbt compile` is launched.

## expectation
The project's source code is compiled.

## notes
Versions:
```
sbt 1.6.2 (Oracle Corporation Java 16.0.1)
```
Full stacktrace:
```
[error] java.lang.NullPointerException: Cannot invoke "java.io.FileInputStream.close()" because "is" is null
[error]         at lmcoursier.internal.shaded.coursier.cache.FileCache$.computeDigest(FileCache.scala:461)
[error]         at lmcoursier.internal.shaded.coursier.cache.FileCache$.coursier$cache$FileCache$$persistedDigest(FileCache.scala:431)
[error]         at lmcoursier.internal.shaded.coursier.cache.FileCache.$anonfun$validateChecksum$4(FileCache.scala:132)
[error]         at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[error]         at scala.util.Success.$anonfun$map$1(Try.scala:255)
[error]         at scala.util.Success.map(Try.scala:213)
[error]         at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[error]         at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[error]         at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[error]         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[error]         at java.base/java.lang.Thread.run(Thread.java:831)
[error] java.lang.NullPointerException: Cannot invoke "java.io.FileInputStream.close()" because "is" is null
[error]         at lmcoursier.internal.shaded.coursier.cache.FileCache$.computeDigest(FileCache.scala:461)
[error]         at lmcoursier.internal.shaded.coursier.cache.FileCache$.coursier$cache$FileCache$$persistedDigest(FileCache.scala:431)
[error]         at lmcoursier.internal.shaded.coursier.cache.FileCache.$anonfun$validateChecksum$4(FileCache.scala:132)
[error]         at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[error]         at scala.util.Success.$anonfun$map$1(Try.scala:255)
[error]         at scala.util.Success.map(Try.scala:213)
[error]         at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[error]         at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[error]         at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[error]         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[error]         at java.base/java.lang.Thread.run(Thread.java:831)
[error] java.lang.NullPointerException: Cannot invoke "java.io.FileInputStream.close()" because "is" is null
[error]         at lmcoursier.internal.shaded.coursier.cache.FileCache$.computeDigest(FileCache.scala:461)
[error]         at lmcoursier.internal.shaded.coursier.cache.FileCache$.coursier$cache$FileCache$$persistedDigest(FileCache.scala:431)
[error]         at lmcoursier.internal.shaded.coursier.cache.FileCache.$anonfun$validateChecksum$4(FileCache.scala:132)
[error]         at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[error]         at scala.util.Success.$anonfun$map$1(Try.scala:255)
[error]         at scala.util.Success.map(Try.scala:213)
[error]         at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[error]         at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[error]         at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[error]         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[error]         at java.base/java.lang.Thread.run(Thread.java:831)
[error] (domainCommon / update) java.lang.NullPointerException: Cannot invoke "java.io.FileInputStream.close()" because "is" is null
[error] (mainInmemResources / update) java.lang.NullPointerException: Cannot invoke "java.io.FileInputStream.close()" because "is" is null
[error] (domain / update) java.lang.NullPointerException: Cannot invoke "java.io.FileInputStream.close()" because "is" is null
[error] Total time: 4 s, completed May 3, 2022, 4:25:16 PM
```

**Comment by eed3si9n** [comment]
@coffius Thanks for the report. Could you open a GitHub issue on coursier/coursier as well? Also if this happened at work code, please consider contributing a fix to Coursier.

**Comment by SethTisue** [comment]
@coffius are you still seeing this on sbt 1.8.2? coursier and sbt have moved on since sbt 1.6.2 days, so unless you can confirm that you've seen this recently on current sbt, I think we should probably close this

**Comment by eed3si9n** [comment]
I am closing this due to inactivity / not sure if this actionable by contributors.
