### ISSUE TITLE
Too many open files `stty` on 1.7.0-RC2

### ISSUE THREAD

**Issue by cquiroz** [sbt/sbt#6953]
## steps

The error happens randomly in the console he using sbtn

## problem

In the console I see the error below and sbt dies

```
sbt:root> Exception in thread "sbt-serverconnection-0" java.io.IOError: java.io.IOException: Cannot run program "stty": error=24, Too many open files
	at org.jline.terminal.impl.AbstractPosixTerminal.getAttributes(AbstractPosixTerminal.java:46)
	at org.jline.terminal.impl.AbstractTerminal.echo(AbstractTerminal.java:143)
	at sbt.internal.util.Terminal$ConsoleTerminal.isEchoEnabled(Terminal.scala:824)
	at sbt.internal.client.NetworkClient.onRequest(NetworkClient.scala:663)
	at sbt.internal.client.NetworkClient$$anon$2.onRequest(NetworkClient.scala:285)
	at sbt.internal.client.ServerConnection$$anon$1.$anonfun$run$2(ServerConnection.scala:47)
	at sbt.internal.client.ServerConnection$$anon$1.$anonfun$run$2$adapted(ServerConnection.scala:46)
	at scala.util.Either.fold(Either.scala:191)
	at sbt.internal.client.ServerConnection$$anon$1.run(ServerConnection.scala:46)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: java.io.IOException: Cannot run program "stty": error=24, Too many open files
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at org.jline.utils.ExecHelper.exec(ExecHelper.java:35)
	at org.jline.terminal.impl.ExecPty.doGetConfig(ExecPty.java:175)
	at org.jline.terminal.impl.ExecPty.getAttr(ExecPty.java:87)
	at org.jline.terminal.impl.AbstractPosixTerminal.getAttributes(AbstractPosixTerminal.java:44)
	... 10 more
Caused by: java.io.IOException: error=24, Too many open files
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_io_IOException_2_0002e_0003cinit_0003e_00028Ljava_lang_String_2_00029V(JNIJavaCallWrappers.java:0)
	at java.lang.UNIXProcess.forkAndExec(UNIXProcess.java)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 14 more
```

## expectation

No error

## notes
This only happened after I started testing sbt 1.7.0-RC2. I have never seen it on 1.6.x

**Comment by eed3si9n** [comment]
@cquiroz Could you tell us some hints on how we could potentially reproduce this on our computers to debug this? For example, which operating system and terminal environment are you using? Does this happen with any of the publicly available projects?

**Comment by cquiroz** [comment]
Sure, unfortunately I don't have a recipe to reproduce it but for more info.
OS: Mac OS Monterry on a M1 Max Pro laptop
Terminal: Kitty
Editor: neovim with nvim-metals

I keep neovim open in a terminal to edit the files and in a separate terminal sbtn open in tiggered mode like `~compile`

I'll keep trying to reprroduce it more exactly

**Comment by cquiroz** [comment]
Just happened to me again. I changed a bulid.sbt, run reload and immediately got:

```
sbt:root> reload
Exception in thread "sbt-serverconnection-0" java.io.IOError: java.io.IOException: Cannot run program "stty": error=24, Too many open files
	at org.jline.terminal.impl.AbstractPosixTerminal.getAttributes(AbstractPosixTerminal.java:46)
	at org.jline.terminal.impl.AbstractTerminal.echo(AbstractTerminal.java:143)
	at sbt.internal.util.Terminal$ConsoleTerminal.isEchoEnabled(Terminal.scala:824)
	at sbt.internal.client.NetworkClient.onRequest(NetworkClient.scala:663)
	at sbt.internal.client.NetworkClient$$anon$2.onRequest(NetworkClient.scala:285)
	at sbt.internal.client.ServerConnection$$anon$1.$anonfun$run$2(ServerConnection.scala:47)
	at sbt.internal.client.ServerConnection$$anon$1.$anonfun$run$2$adapted(ServerConnection.scala:46)
	at scala.util.Either.fold(Either.scala:191)
	at sbt.internal.client.ServerConnection$$anon$1.run(ServerConnection.scala:46)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: java.io.IOException: Cannot run program "stty": error=24, Too many open files
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at org.jline.utils.ExecHelper.exec(ExecHelper.java:35)
	at org.jline.terminal.impl.ExecPty.doGetConfig(ExecPty.java:175)
	at org.jline.terminal.impl.ExecPty.getAttr(ExecPty.java:87)
	at org.jline.terminal.impl.AbstractPosixTerminal.getAttributes(AbstractPosixTerminal.java:44)
	... 10 more
Caused by: java.io.IOException: error=24, Too many open files
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_io_IOException_2_0002e_0003cinit_0003e_00028Ljava_lang_String_2_00029V(JNIJavaCallWrappers.java:0)
	at java.lang.UNIXProcess.forkAndExec(UNIXProcess.java)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 14 more
Jul 05, 2022 4:36:22 PM org.jline.utils.Log logr
WARNING: Task failed
java.io.IOException: Cannot run program "stty": error=24, Too many open files
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at org.jline.utils.ExecHelper.exec(ExecHelper.java:35)
	at org.jline.terminal.impl.ExecPty.doGetConfig(ExecPty.java:175)
	at org.jline.terminal.impl.ExecPty.getAttr(ExecPty.java:87)
	at org.jline.terminal.impl.ExecPty.doSetAttr(ExecPty.java:93)
	at org.jline.terminal.impl.AbstractPty.setAttr(AbstractPty.java:29)
	at org.jline.terminal.impl.AbstractPosixTerminal.doClose(AbstractPosixTerminal.java:76)
	at org.jline.terminal.impl.PosixSysTerminal.doClose(PosixSysTerminal.java:95)
	at org.jline.terminal.impl.AbstractTerminal.close(AbstractTerminal.java:95)
	at org.jline.utils.ShutdownHooks.runTasks(ShutdownHooks.java:55)
	at org.jline.utils.ShutdownHooks.access$000(ShutdownHooks.java:21)
	at org.jline.utils.ShutdownHooks$1.run(ShutdownHooks.java:36)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: java.io.IOException: error=24, Too many open files
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_io_IOException_2_0002e_0003cinit_0003e_00028Ljava_lang_String_2_00029V(JNIJavaCallWrappers.java:0)
	at java.lang.UNIXProcess.forkAndExec(UNIXProcess.java)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 13 more
```

**Comment by charego** [comment]
I see this error regularly when using sbt native client (and only when using the native client). It occurs early on after launching the sbt server and kicks out my client. I can reconnect to the server, it's just annoying. Yes, I even reproduced it on sbt/sbt. I have seen the error under sbt 1.6.2 as well, so I assume it's more of an issue with sbt native client than anything else. I use the environment variable rather than `sbtn` to launch sbt.

Environment:
* macOS Monterey (12.x)
* Intel Core i7
* 16 GB RAM
* iTerm2
* Eclipse Adoptium Java 17.x
* `SBT_NATIVE_CLIENT=true`

**Comment by olegbonar** [comment]
Also facing this on my Mac

**Comment by markusa380** [comment]
Here too. (M1 Mac)

**Comment by jkleckner** [comment]
I found that I had to run ulimit to increase the file descriptors: `ulimit -n 10240`
* https://discussions.apple.com/thread/251000125?sortBy=best

**Comment by eed3si9n** [comment]
I think I tried to fix this for sbt 2.x in https://github.com/sbt/sbt/pull/7977. If this is happening frequently I can try to backport it to sbt 1.x.
