### ISSUE TITLE
dependency resolution failure with unresolved maven property

### ISSUE THREAD

**Issue by simlei** [sbt/sbt#6961]
`sbt.version=1.7.0-RC2`

## steps

add the following line to any sbt project:
```scala
libraryDependencies += "org.eclipse.platform" % "org.eclipse.swt" % "3.120.0"
```

(from https://mvnrepository.com/artifact/org.eclipse.platform/org.eclipse.swt.gtk.linux.x86_64/3.120.0)

## problem

The maven property ${osgi.platform} is not properly resolved it seems.

Neither of the following workarounds works; however I understand they are from a time before coursier was used to resolve dependencies.
- https://stackoverflow.com/a/46763742 (pseudo-task that sets `sys.props`)
- https://github.com/sbt/sbt/issues/3618#issuecomment-424924293 (ad-hoc auto plugin that set sys.props)

```txt
sbt.librarymanagement.ResolveException: Error downloading org.eclipse.platform:org.eclipse.swt.${osgi.platform}:[3.120.0,3.120.0]                                                                   
[error]   No version found for [3.120.0,3.120.0] in·
[error]   No version found for [3.120.0,3.120.0] in·
[error]   not found: /home/snuc/.ivy2/local/org.eclipse.platform/org.eclipse.swt.${osgi.platform}
[error]   not found: https://repo1.maven.org/maven2/org/eclipse/platform/org.eclipse.swt.${osgi.platform}/maven-metadata.xml
[error]     at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:345)
[error]     at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:314)
```

## expectation

Well I would like to use the library without a separate maven project that mirrors/fatJars and installs it locally (which would be what I'd be doing now, were I in a rush...).

**Comment by eed3si9n** [comment]
@simlei Thanks for the report. sbt uses Coursier for dependency resolution, so could you also report this to coursier/coursier as well please?

**Comment by simlei** [comment]
There is an issue with coursier now. I myself have not found how to convince coursier / lmcoursier to provide this property with a value -- I'd highly appreciate any idea on how to work around this issue!

**Comment by adpi2** [comment]
Until its implemented in Coursier, here is a workaround:

```scala
onLoad := {
  sys.props += "osgi.platform" -> "gtk.linux.x86_64"
  onLoad.value
}
useCoursier := false
```

**Comment by danbills** [comment]
I wasn't able to get @adpi2 's fix to work, but this worked for me:

add a `settings.propeties` file to the root of your sbt project.  Then populate it with the osgi platform you are targeting.  Mine says:
```
osgi.platform=gtk.linux.x86_64
```
