### ISSUE TITLE
dependencyBrowseGraph fails with `key not found: GraphModuleId` when pagerduty-client is present

### ISSUE THREAD

**Issue by frosforever** [sbt/sbt#6976]
### Project files:
`build.sbt`:
```sbt
libraryDependencies ++= Seq(
    "com.github.dikhan" % "pagerduty-client" % "3.1.2"
    )
```
`project/plugins.sbt`:
```
addDependencyTreePlugin
```
`project/build.properties`:
```
sbt.version=1.7.1
```

## problem

Calling `dependencyBrowseGraph` on the project fails with `NoSuchElementException: key not found: GraphModuleId(org.apache.commons,commons-io,1.3.2)`

### Sbt commands
```shell
$ sbt dependencyBrowseGraph
[info] welcome to sbt 1.7.1 (Azul Systems, Inc. Java 1.8.0_332)
[info] loading settings for project sbt-dependency-graph-bug-build from plugins.sbt ...
[info] loading project definition from sbt-dependency-graph-bug/project
[info] loading settings for project sbt-dependency-graph-bug from build.sbt ...
[info] set current project to sbt-dependency-graph-bug (in build file:/sbt-dependency-graph-bug/)
[error] java.util.NoSuchElementException: key not found: GraphModuleId(org.apache.commons,commons-io,1.3.2)
[error] 	at scala.collection.MapLike.default(MapLike.scala:236)
[error] 	at scala.collection.MapLike.default$(MapLike.scala:235)
[error] 	at scala.collection.AbstractMap.default(Map.scala:65)
[error] 	at scala.collection.MapLike.apply(MapLike.scala:144)
[error] 	at scala.collection.MapLike.apply$(MapLike.scala:143)
[error] 	at scala.collection.AbstractMap.apply(Map.scala:65)
[error] 	at sbt.internal.graph.ModuleGraph.module(model.scala:70)
[error] 	at sbt.internal.graph.rendering.DOT$.originWasEvicted$1(DOT.scala:34)
[error] 	at sbt.internal.graph.rendering.DOT$.$anonfun$dotGraph$6(DOT.scala:56)
[error] 	at sbt.internal.graph.rendering.DOT$.$anonfun$dotGraph$6$adapted(DOT.scala:56)
[error] 	at scala.collection.TraversableLike.$anonfun$filterImpl$1(TraversableLike.scala:304)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:303)
[error] 	at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:297)
[error] 	at scala.collection.AbstractTraversable.filterImpl(Traversable.scala:108)
[error] 	at scala.collection.TraversableLike.filterNot(TraversableLike.scala:403)
[error] 	at scala.collection.TraversableLike.filterNot$(TraversableLike.scala:403)
[error] 	at scala.collection.AbstractTraversable.filterNot(Traversable.scala:108)
[error] 	at sbt.internal.graph.rendering.DOT$.dotGraph(DOT.scala:56)
[error] 	at sbt.plugins.DependencyTreeSettings$.$anonfun$browseGraphHTMLTask$1(DependencyTreeSettings.scala:195)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:750)
[error] (Compile / dependencyBrowseGraphHTML) java.util.NoSuchElementException: key not found: GraphModuleId(org.apache.commons,commons-io,1.3.2)
[error] Total time: 0 s, completed Jul 15, 2022 10:56:29 AM
```

## expectation

A nice graph in my browser for my viewing pleasure!

## notes

Thanks very much for reviewing. Please let me know if this is not the correct repo to report dependency graph plugin issues.

**Comment by eed3si9n** [comment]
@frosforever Thanks for the report with clear repro steps!

**Comment by eed3si9n** [comment]
If anyone is interested in working on this, the relevant code is likely here:
- https://github.com/sbt/sbt/blob/v1.7.1/main/src/main/scala/sbt/internal/graph/rendering/DOT.scala
- https://github.com/sbt/sbt/blob/v1.7.1/main/src/main/scala/sbt/internal/graph/model.scala

**Comment by frosforever** [comment]
Happy to make an attempt. Is there an easy way to generate a test `ConfigurationReport` that's used in the plugin https://github.com/sbt/sbt/blob/38125c534747d4cad12895e64ea1dc4b3f680aa5/main/src/main/scala/sbt/plugins/DependencyTreeSettings.scala#L76?

**Comment by eed3si9n** [comment]
We typically use integration test (https://www.scala-sbt.org/1.x/docs/Testing-sbt-plugins.html) - for example https://github.com/sbt/sbt/blob/1.7.x/sbt-app/src/sbt-test/dependency-graph/testDotFileGeneration/build.sbt

LM API has some example of generating UpdateReport in test - https://github.com/sbt/librarymanagement/blob/develop/ivy/src/test/scala/sbt/internal/librarymanagement/ResolutionSpec.scala

**Comment by frosforever** [comment]
Very helpful thanks for the pointers @eed3si9n!

I think this maybe an upstream issue in coursier but not 100% sure yet. 
The update report looks like 
```
sbt> show updateFull
[info] Update report:
...
[info] 	commons-io:commons-io
[info] 		- 1.3.2
[info] 			evicted: false
[info] 			homepage: http://jakarta.apache.org/commons/io/
[info] 			configurations: test, optional, compile, default, runtime
[info] 			callers: org.apache.commons:commons-io:1.3.2
```
I would expect `org.apache.commons:commons-io` instead of the current `commons-io:commons-io`.

This means that `ModuleGraph.edges` winds up with what seems like an orphaned edge `(GraphModuleId(org.apache.commons,commons-io,1.3.2),GraphModuleId(commons-io,commons-io,1.3.2))` which then causes the failure with `commons-io` is used a key. 

I wonder if this is similar to https://github.com/coursier/coursier/issues/1471? 

Setting `ThisBuild / useCoursier := false` allows `dependencyBrowseGraph` to work without issue.

**Comment by eed3si9n** [comment]
Do you mind raising this issue to coursier/coursier as well? Non-caller is registered as a caller? (https://github.com/sbt/librarymanagement/blob/v1.7.0/core/src/main/contraband-scala/sbt/librarymanagement/Caller.scala)
In the meantime, on sbt's side could we workaround this by using `Map#get` instead of `Map#apply` in https://github.com/sbt/sbt/blob/v1.7.1/main/src/main/scala/sbt/internal/graph/model.scala#L70?

**Comment by krittanon-w** [comment]
Got the same issue, I have many dependencies, and I don't know what the actual lib that caused this issue.
sbt=1.6.2

```
[error] java.util.NoSuchElementException: key not found: GraphModuleId(org.apache.commons,commons-io,1.3.2)
```
