### ISSUE TITLE
sbt try to access /run/user/1000

### ISSUE THREAD

**Issue by Phantom1003** [sbt/sbt#7056]
## steps
My environment is CentOS 7.9 with Linux 5.4.206-200.el7.x86_64.
```
$ id -u
1005
$ sbt
java.nio.file.AccessDeniedException: /run/user/1000/.sbt
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.checkAccess(UnixFileSystemProvider.java:308)
        at java.nio.file.Files.createDirectories(Files.java:746)
        at sbt.internal.BootServerSocket.<init>(BootServerSocket.java:290)
        at sbt.xMain$.getSocketOrExit(Main.scala:150)
        at sbt.xMain$.bootServerSocket$lzycompute$1(Main.scala:77)
        at sbt.xMain$.bootServerSocket$1(Main.scala:77)
        at sbt.xMain$.withStreams$1(Main.scala:85)
        at sbt.xMain$.run(Main.scala:121)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:57)
        at sbt.xMain.run(Main.scala:46)
        at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
        at xsbt.boot.Launch$.run(Launch.scala:149)
        at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
        at xsbt.boot.Launch$.launch(Launch.scala:159)
        at xsbt.boot.Launch$.apply(Launch.scala:44)
        at xsbt.boot.Launch$.apply(Launch.scala:21)
        at xsbt.boot.Boot$.runImpl(Boot.scala:78)
        at xsbt.boot.Boot$.run(Boot.scala:73)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)
[error] [launcher] error during sbt launcher: java.nio.file.AccessDeniedException: /run/user/1000/.sbt
```

## problem

I found that sbt looks like try to create a socket under /run/user/1000/.sbt.
This makes other users failed to launch sbt.

**Comment by SethTisue** [comment]
Does it happen even in a freshly created user account?

What version of sbt is it?

What does `echo $HOME` say?

What does Java think the `user.home` system property is set to?

**Comment by Phantom1003** [comment]
> Does it happen even in a freshly created user account?

Yes, 1005 is a new created user.

> What version of sbt is it?

sbt script version: 1.7.2
 
> What does `echo $HOME` say?

Point to 1005's home.

> What does Java think the `user.home` system property is set to?

I use the following code and get the same value as the $HOME.
```
class Main{
    public static void main(String args[]){
     System.out.println(System.getProperty("user.home"));
    }
}
```

**Comment by SethTisue** [comment]
It's hard to imagine by what possible mechanism `/run/user/1000` is even becoming involved, then. Is it possible that the `sbt` or `java` commands are owned by that user and have their setuid bit set? I'm grasping at straws.

**Comment by Phantom1003** [comment]
I found that there is a socket directory `sbt-socket4806564942100116857` under `/run/user/1000/.sbt`.

**Comment by Phantom1003** [comment]
I think I found the reason, I use ssh to log in to the server with user 1000, and switch to user 1005.
If I directly log in as 1005, sbt works fine :)

**Comment by SethTisue** [comment]
If you're switching with `su` for testing purposes, consider using `su -` instead of plain `su` — that makes it more like a fresh login.

Glad you got it sorted.

**Comment by SethTisue** [comment]
similar: #7515
