### ISSUE TITLE
Error doesn't display suppressed exception

### ISSUE THREAD

**Issue by som-snytt** [sbt/sbt#7066]
## steps

In scala 2.13.10 project, `assertThrown` notices if the wrong exception type is thrown, and adds the bad exception (`addSuppressed`) as suppressed to the `AssertionError`.

## problem

It seems that sbt doesn't display suppressed exceptions when showing errors.

Here is the `printStackTrace` added to the output, showing the truncated `[error]` messaging at the bottom.

```
[info] Test scala.collection.IterableTest.IterableOnceOps.reduceLeft consumes no iterator started
java.lang.AssertionError: Wrong exception: expected java.lang.UnsupportedOperationException but was java.lang.AssertionError=> testkit / Compile / compileIncremental 0s
        at scala.tools.testkit.AssertUtil$.assertThrown(AssertUtil.scala:138)
        at scala.tools.testkit.AssertUtil$.assertThrows(AssertUtil.scala:119)
        at scala.collection.IterableTest.IterableOnceOps$u002EreduceLeft$u0020consumes$u0020no$u0020iterator(IterableTest.scala:458)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at com.novocode.junit.JUnitTask.execute(JUnitTask.java:64)
        at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1589)
        Suppressed: java.lang.AssertionError: Attempted to iterate!
                at scala.tools.testkit.AssertUtil$.fail(AssertUtil.scala:44)
                at scala.collection.IterableTest$ZeroUseIterable.iterator(IterableTest.scala:394)
                at scala.collection.IterableTest$ZeroUseIterable.iterator(IterableTest.scala:393)
                at scala.collection.IterableOnceOps.reduceLeftIterator(IterableOnce.scala:759)
                at scala.collection.IterableOnceOps.reduceLeft(IterableOnce.scala:756)
                at scala.collection.IterableOnceOps.reduceLeft$(IterableOnce.scala:754)
                at scala.collection.IterableTest$ZeroUseIterable.reduceLeft(IterableTest.scala:393)
                at scala.collection.IterableTest.$anonfun$IterableOnceOps$u002EreduceLeft$u0020consumes$u0020no$u0020iterator$1(IterableTest.scala:458)
                at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.scala:17)
                at scala.tools.testkit.AssertUtil$.assertThrown(AssertUtil.scala:128)
                ... 37 more
[error] Test scala.collection.IterableTest.IterableOnceOps.reduceLeft consumes no iterator failed: java.lang.AssertionError: Wrong exception: expected java.lang.UnsupportedOperationException but was java.lang.AssertionError, took 0.014 sec
[error]     at scala.tools.testkit.AssertUtil$.assertThrown(AssertUtil.scala:138)
[error]     at scala.tools.testkit.AssertUtil$.assertThrows(AssertUtil.scala:119)
[error]     at scala.collection.IterableTest.IterableOnceOps.reduceLeft consumes no iterator(IterableTest.scala:458)
[error]     at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[error]     at java.lang.reflect.Method.invoke(Method.java:578)
[error]     ...
```

## expectation

Here is 2.13.10 REPL with sample trace.

```
Welcome to Scala 2.13.10 (OpenJDK 64-Bit Server VM, Java 19).
Type in expressions for evaluation. Or try :help.

scala> List.empty[Int].product
val res0: Int = 1

scala> val e = new Throwable("Uh-oh!")
val e: Throwable = java.lang.Throwable: Uh-oh!

scala> val ae = new AssertionError("Nope")
val ae: AssertionError = java.lang.AssertionError: Nope

scala> ae.addSuppressed(e)

scala> throw ae
java.lang.AssertionError: Nope
  ... 30 elided
  Suppressed: java.lang.Throwable: Uh-oh!
    ... 6 elided and 24 more

scala>

```

**Comment by eed3si9n** [comment]
sbt by default truncates the stacktrace since we often emulate JVM process using a function, and we don't want to confuse the users. Would typing in `last` into sbt shell display the whole thing?

**Comment by som-snytt** [comment]
The REPL example shows the truncated stack trace plus truncated suppressed stack trace, which is pretty clever. I don't recall if that is unique to that stack trace printer.

https://github.com/scala/scala/blob/2.13.x/src/compiler/scala/tools/nsc/util/StackTracing.scala#L74

`last` does not print more. I remember sometimes it prompts you to say last for the exception.
```
sbt:root> last
[debug] > Exec(junit/testOnly scala.collection.IterableTest, Some(54d7965f-3fe9-4cdd-92c1-ec18a4c29672), Some(CommandSource(console0)))
[debug] Evaluating tasks: junit / Test / testOnly
[debug] Running task... Cancel: Signal, check cycles: false, forcegc: true
[info] Test run scala.collection.IterableTest started
[info] Test scala.collection.IterableTest.concatTest started
[info] Test scala.collection.IterableTest.IterableOnceOps.reduceLeft consumes no iterator started
[error] Test scala.collection.IterableTest.IterableOnceOps.reduceLeft consumes no iterator failed: java.lang.AssertionError: Wrong exception: expected java.lang.UnsupportedOperationException but was java.lang.AssertionError, took 0.008 sec
[error]     at scala.tools.testkit.AssertUtil$.assertThrown(AssertUtil.scala:138)
[error]     at scala.tools.testkit.AssertUtil$.assertThrows(AssertUtil.scala:119)
[error]     at scala.collection.IterableTest.IterableOnceOps.reduceLeft consumes no iterator(IterableTest.scala:458)
[error]     at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[error]     at java.lang.reflect.Method.invoke(Method.java:578)
[error]     ...
[info] Test scala.collection.IterableTest.IterableOnceOps.reduceLeft of empty iterator started
```
