### ISSUE TITLE
"[error] sbt.librarymanagement.ResolveException: Error downloading org.scalameta:semanticdb-scalac_2.12.17:4.5.9"

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#7069]
This was originally reported by @keynmol on Discord
See also https://github.com/coursier/coursier/issues/2573

## steps

???

## problem

```
2022.11.05 12:01:39 INFO  [info] welcome to sbt 1.7.3 (GraalVM Community Java 17.0.4)[0m
2022.11.05 12:01:39 INFO  [info] loading global plugins from /Users/velvetbaldmime/.sbt/1.0/plugins[0m
2022.11.05 12:01:41 INFO  [info] loading settings for project twotm8-build-build-build from metals.sbt ...[0m
2022.11.05 12:01:41 INFO  [info] loading project definition from /Users/velvetbaldmime/projects/twotm8/project/project/project[0m
2022.11.05 12:01:44 INFO  [warn] [0m
2022.11.05 12:01:44 INFO  [warn]     Note: Unresolved dependencies path:[0m
2022.11.05 12:01:44 INFO  [error] sbt.librarymanagement.ResolveException: Error downloading org.scalameta:semanticdb-scalac_2.12.17:4.5.9[0m
2022.11.05 12:01:44 INFO  [error]   Not found[0m
2022.11.05 12:01:44 INFO  [error]   Not found[0m
2022.11.05 12:01:44 INFO  [error]   not found: https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.12.17/4.5.9/semanticdb-scalac_2.12.17-4.5.9.pom[0m
2022.11.05 12:01:44 INFO  [error]   not found: /Users/velvetbaldmime/.ivy2/local/org.scalameta/semanticdb-scalac_2.12.17/4.5.9/ivys/ivy.xml[0m
2022.11.05 12:01:44 INFO  [error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scalameta/semanticdb-scalac_2.12.17/4.5.9/ivys/ivy.xml[0m
2022.11.05 12:01:44 INFO  [error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/org.scalameta/semanticdb-scalac_2.12.17/4.5.9/ivys/ivy.xml[0m
2022.11.05 12:01:44 INFO  [error]     at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:344)[0m
2022.11.05 12:01:44 INFO  [error]     at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:313)[0m
2022.11.05 12:01:44 INFO  [error]     at scala.util.Either$LeftProjection.map(Either.scala:573)[0m
```

## expectation

It works.

## notes

SemanticDB 4.5.9 doesn't exist for the version. Likely fix would be to upgrade the default Semantdb version or downgrade the Scala version on some transitive dependency.

**Comment by eed3si9n** [comment]
```scala
semanticdbVersion := "4.5.13"
```
was bumped up in 1.8.x in https://github.com/sbt/sbt/pull/7021, so really this is a problem with 1.7.x, and it sort of makes sense because I didn't anticipate Scala version to be 2.12.17 in 1.7.x series.

**Comment by SethTisue** [comment]
closing since I presume there will be no more 1.7.x releases
