### ISSUE TITLE
Unexpected exception in Scala.js linker after migration to 1.8.0

### ISSUE THREAD

**Issue by plokhotnyuk** [sbt/sbt#7076]
## Steps

1. Clone Scala Steward's fork of jsoniter-scala:
```
git clone --depth 50 https://github.com/scala-steward/jsoniter-scala
```
2. Enter to the project directory:
```
cd jsoniter-scala
```
3. Checkout a branch with updated sbt version:
```
git checkout scala-steward:update/sbt-1.8.0
```
4. Run the build:
```
sbt clean test
```

## Problem

Unexpected exception in Scala.js linker:
```
[error] java.lang.AssertionError: version 0.21.0/1.11.0 contains invalid '/'
[error] 	at lmcoursier.internal.shaded.coursier.core.Validation$.$anonfun$assertValid$1(Definitions.scala:421)
[error] 	at scala.util.Either.fold(Either.scala:192)
[error] 	at lmcoursier.internal.shaded.coursier.core.Validation$.assertValid(Definitions.scala:421)
[error] 	at lmcoursier.internal.shaded.coursier.core.Dependency.<init>(Dependency.scala:24)
[error] 	at lmcoursier.internal.shaded.coursier.core.Dependency$.apply(Dependency.scala:144)
[error] 	at lmcoursier.internal.shaded.coursier.core.Dependency$.apply(Dependency.scala:178)
[error] 	at lmcoursier.internal.shaded.coursier.package$Dependency$.apply(package.scala:24)
[error] 	at lmcoursier.internal.SbtUpdateReport$.moduleReports(SbtUpdateReport.scala:209)
[error] 	at lmcoursier.internal.SbtUpdateReport$.$anonfun$apply$1(SbtUpdateReport.scala:320)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error] 	at lmcoursier.internal.SbtUpdateReport$.apply(SbtUpdateReport.scala:306)
[error] 	at lmcoursier.internal.UpdateRun$.$anonfun$update$1(UpdateRun.scala:87)
[error] 	at lmcoursier.internal.Lock$.maybeSynchronized(Lock.scala:9)
[error] 	at lmcoursier.internal.UpdateRun$.update(UpdateRun.scala:59)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$37(CoursierDependencyResolution.scala:311)
[error] 	at scala.util.Either.map(Either.scala:353)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$36(CoursierDependencyResolution.scala:308)
[error] 	at scala.util.Either.flatMap(Either.scala:341)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:306)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.librarymanagement.DependencyResolution.retrieve(DependencyResolution.scala:129)
[error] 	at scalajsbundler.sbtplugin.Settings$.$anonfun$globalSettings$1(Settings.scala:52)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:831)
[error] (Zero / scalaJSLinkerImpl / fullClasspath) java.lang.AssertionError: version 0.21.0/1.11.0 contains invalid '/'
```
## Expectation

Successful build

## Notes

Works fine with sbt 1.8.0-RC1

**Comment by eed3si9n** [comment]
@plokhotnyuk Thanks for the report with repro steps! Since the behavior is coming from Coursier I've copied this issue to coursier/coursier.

**Comment by eed3si9n** [comment]
Looking at this more closely, I think the issue is https://github.com/scalacenter/scalajs-bundler/issues/440

**Comment by plokhotnyuk** [comment]
@eed3si9n Thanks a lot!

**Comment by sjrd** [comment]
scalajs-bundler v0.21.0 is out and fixes this issue.

**Comment by plokhotnyuk** [comment]
@sjrd Thanks a bunch! v0.21.1 works fine for me: https://github.com/plokhotnyuk/jsoniter-scala/commit/4d76b19da676bb2f172a18d31c8a49657a18dc85
