### ISSUE TITLE
SBT scripted tests fail when run under github actions Windows CI image

### ISSUE THREAD

**Issue by mdedetrich** [sbt/sbt#7082]
## steps

With an sbt plugin that has scripted tests, run it under a github actions Windows CI image

## problem

The scripted test fails because the sbt server (i.e. https://www.scala-sbt.org/1.x/docs/sbt-server.html#Server+discovery+and+authentication) is unable to communicate with the sbt client, i.e. 

```
Error:  java.net.ConnectException: Connection refused: connect
Error:  	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
Error:  	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
Error:  	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
Error:  	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
Error:  	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
Error:  	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
Error:  	at java.base/java.net.Socket.connect(Socket.java:609)
Error:  	at java.base/java.net.Socket.connect(Socket.java:558)
Error:  	at java.base/java.net.Socket.<init>(Socket.java:454)
Error:  	at java.base/java.net.Socket.<init>(Socket.java:264)
Error:  	at xsbt.IPC$.client(IPC.scala:21)
Error:  	at sbt.BasicCommands$.readMessage(BasicCommands.scala:472)
Error:  	at sbt.BasicCommands$.doRead(BasicCommands.scala:448)
Error:  	at sbt.BasicCommands$.$anonfun$read$2(BasicCommands.scala:435)
Error:  	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:150)
Error:  	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:145)
Error:  	at sbt.Command$.process(Command.scala:189)
Error:  	at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:245)
Error:  	at scala.Option.getOrElse(Option.scala:189)
Error:  	at sbt.MainLoop$.process$1(MainLoop.scala:245)
Error:  	at sbt.MainLoop$.processCommand(MainLoop.scala:276)
Error:  	at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:163)
Error:  	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:289)
Error:  	at sbt.State$StateOpsImpl$.process$extension(State.scala:325)
Error:  	at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:163)
Error:  	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
Error:  	at sbt.MainLoop$.next(MainLoop.scala:163)
Error:  	at sbt.MainLoop$.run(MainLoop.scala:144)
Error:  	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:119)
Error:  	at sbt.io.Using.apply(Using.scala:27)
Error:  	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:112)
Error:  	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:66)
Error:  	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:51)
Error:  	at sbt.MainLoop$.runLogged(MainLoop.scala:42)
Error:  	at sbt.StandardMain$.runManaged(Main.scala:218)
Error:  	at sbt.xMain$.$anonfun$run$11(Main.scala:133)
Error:  	at sbt.internal.util.Terminal$.withStreams(Terminal.scala:[381](https://github.com/sbt/sbt-github-actions/actions/runs/3587764952/jobs/6038462004#step:8:382))
Error:  	at sbt.xMain$.withStreams$1(Main.scala:87)
Error:  	at sbt.xMain$.run(Main.scala:121)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Error:  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Error:  	at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:56)
Error:  	at sbt.xMain.run(Main.scala:46)
Error:  	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
Error:  	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
Error:  	at xsbt.boot.Launch$.run(Launch.scala:149)
Error:  	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
Error:  	at xsbt.boot.Launch$.launch(Launch.scala:159)
Error:  	at xsbt.boot.Launch$.apply(Launch.scala:44)
Error:  	at xsbt.boot.Launch$.apply(Launch.scala:21)
Error:  	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
Error:  	at xsbt.boot.Boot$.run(Boot.scala:73)
Error:  	at xsbt.boot.Boot$.main(Boot.scala:21)
Error:  	at xsbt.boot.Boot.main(Boot.scala)
```

## expectation

sbt works as expected and/or its documented on sbt how to fix this problem.

## notes

So it appears the core problem here is that specifically on Windows, the port that the sbt client/server uses is not open which causes the `java.net.ConnectException: Connection refused: connect` error. On the surface one of the following thing/s may need to be done to solve the problem

* Find a port that is open on github actions windows CI image and configure the sbt to use that port
  * Maybe this can be done within [actions/setup-java](https://github.com/actions/setup-java) so that it can automatically configure itself and sbt if it happens to be running under Windows so it just works™
* Add logic into SBT server/client so it can detect typically open ports on Windows and configure itself

**Comment by mdedetrich** [comment]
Official github discussions created on this issue at https://github.com/orgs/community/discussions/40540

**Comment by eed3si9n** [comment]
scripted test has been around for a while, and I don't think it uses sbt server to communicate with the forked sbt instance.
For example, here's Github Action for sbt-assembly running CI on windows-latest - https://github.com/sbt/sbt-assembly/actions/runs/3433991539/jobs/5724885388

It's potentially possible that there's something going on in the forked session of scripted sbt, like it's internally trying to use client-server mechanism, and somehow failing to communicate against IPC (named pipe on Windows).

**Comment by eed3si9n** [comment]
As a test I tried adding windows-latest to sbt-pgp as well (https://github.com/sbt/sbt-pgp/pull/198) and initially I did see the socket related issue, but it went away when I upgraded sbt version for the plugin to 1.2.8.

**Comment by eed3si9n** [comment]
Likely the relevant part of the code is the last launch off point in the stack trace:

```scala
Error:  	at java.base/java.net.Socket.<init>(Socket.java:264)
Error:  	at xsbt.IPC$.client(IPC.scala:21)
```

https://github.com/sbt/sbt/blob/1.8.x/main-command/src/main/scala/xsbt/IPC.scala. I think that's part of the code that randomly opens TCP/IP port, used only for scripted tests (and hasn't changed much https://github.com/sbt/sbt-zero-thirteen/blame/0.13/util/io/src/main/scala/xsbt/IPC.scala). Maybe whatever the containment system used for Windows is not well-isolated compared to Linux?

**Comment by ptrdom** [comment]
Any updates on this? Maybe somebody came up with a workaround? Currently dealing with this on https://github.com/ptrdom/scalajs-esbuild/actions/runs/6113494804/job/16593092828?pr=12.

**Comment by mdedetrich** [comment]
I tried to isolate the problem/find a root cause but was unsuccessful so I have up so there aren't any more updates on this

**Comment by ptrdom** [comment]
Hmm, that is quite a problem then. I know this is more of a github runners issue, things are getting broken on them from time to time, but it might be easier for us to accomodate those changes on sbt side than to fix github runners.

**Comment by mdedetrich** [comment]
The biggest problem is that while I can replicate it in the core project where I was experiencing the issue (sbt-github-actions) I found problems trying to minimize this.

Ontop of this what was more problematic is that I couldn't replicate this issue (even in the original project) on my Windows desktop, I even't went to the effort of installing a VM on my Windows machine to get WIndows Server (which is what github actions Windows runner uses) and I still couldn't replicate.

I think it may be some setting that is done specifically for CI, but yeah I kinda gave up after that point.

**Comment by ptrdom** [comment]
All is good on my Windows Desktop too.

Now I started to remember some things - I had this issue some years ago with Windows GitHub runners, issue was that range of ports needed to be clamped for `new ServerSocket`. Even though it returns fine, the port would end up as taken, and thus not usable. I see `IPC` already uses a mechanism similar to what I implemented for myself, but the range is too broad for Windows GitHub runners. I suggest we introduce system arguments that would allow user to specify these ranges, as a workaround for such unpredictable cases.

**Comment by ptrdom** [comment]
I could try testing this out on my repo where I am having this issue, though releasing a snapshot sbt version somewhere for the runner to use is a bit of a hassle.

**Comment by ptrdom** [comment]
This is also quite difficult to replicate, because the issue is specific to how GitHub sets up its runners, so not possible to replicate locally, and the range is not quite clear. IIRC it is 50000+ that are the problem. So with the picking being random, you still have some chance of it working fine.

**Comment by mdedetrich** [comment]
I think I remember changing the randomly generated port range and it not having an effect

**Comment by OlegYch** [comment]
this happens for me locally
i get ConnectionRefused randomly, sometimes even after a test has passed successfully:
```
[info] + sbt-guardrail/scalafmt
[error] java.net.ConnectException: Connection refused: connect
[error]         at java.base/sun.nio.ch.Net.connect0(Native Method)
[error]         at java.base/sun.nio.ch.Net.connect(Net.java:589)
[error]         at java.base/sun.nio.ch.Net.connect(Net.java:578)
[error]         at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583)
[error]         at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[error]         at java.base/java.net.Socket.connect(Socket.java:751)
[error]         at java.base/java.net.Socket.connect(Socket.java:686)
[error]         at java.base/java.net.Socket.<init>(Socket.java:555)
[error]         at java.base/java.net.Socket.<init>(Socket.java:356)
[error]         at xsbt.IPC$.client(IPC.scala:23)
[error]         at sbt.BasicCommands$.readMessage(BasicCommands.scala:477)
[error]         at sbt.BasicCommands$.doRead(BasicCommands.scala:453)
[error]         at sbt.BasicCommands$.$anonfun$read$2(BasicCommands.scala:440)
[error]         at sbt.Command$.$anonfun$applyEffect$4(Command.scala:151)
[error]         at sbt.Command$.$anonfun$applyEffect$2(Command.scala:146)
[error]         at sbt.Command$.process(Command.scala:194)
[error]         at sbt.MainLoop$.$anonfun$processCommand$7(MainLoop.scala:267)
[error]         at scala.Option.getOrElse(Option.scala:189)
[error]         at sbt.MainLoop$.process$1(MainLoop.scala:267)
[error]         at sbt.MainLoop$.processCommand(MainLoop.scala:312)
[error]         at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:171)
[error]         at sbt.State$StateOpsImpl$.runCmd$1(State.scala:290)
[error]         at sbt.State$StateOpsImpl$.process$extension(State.scala:326)
[error]         at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:171)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error]         at sbt.MainLoop$.next(MainLoop.scala:171)
[error]         at sbt.MainLoop$.run(MainLoop.scala:152)
[error]         at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:127)
[error]         at sbt.io.Using.apply(Using.scala:28)
[error]         at sbt.MainLoop$.runWithNewLog(MainLoop.scala:120)
[error]         at sbt.MainLoop$.runAndClearLast(MainLoop.scala:74)
[error]         at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:59)
[error]         at sbt.MainLoop$.runLogged(MainLoop.scala:50)
[error]         at sbt.StandardMain$.runManaged(Main.scala:225)
[error]         at sbt.xMain$.$anonfun$run$11(Main.scala:135)
[error]         at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error]         at scala.Console$.withIn(Console.scala:230)
[error]         at sbt.internal.util.Terminal$.withIn(Terminal.scala:610)
[error]         at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:390)
[error]         at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error]         at scala.Console$.withOut(Console.scala:167)
[error]         at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:600)
[error]         at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error]         at scala.Console$.withErr(Console.scala:196)
[error]         at sbt.internal.util.Terminal$.withOut(Terminal.scala:600)
[error]         at sbt.internal.util.Terminal$.withStreams(Terminal.scala:390)
[error]         at sbt.xMain$.withStreams$1(Main.scala:88)
[error]         at sbt.xMain$.run(Main.scala:123)
[error]         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[error]         at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:59)
[error]         at sbt.xMain.run(Main.scala:47)
[error]         at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
[error]         at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
[error]         at xsbt.boot.Launch$.run(Launch.scala:149)
[error]         at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
[info] [error] java.net.ConnectException: Connection refused: connect
[error]         at xsbt.boot.Launch$.launch(Launch.scala:159)
[error]         at xsbt.boot.Launch$.apply(Launch.scala:44)
[error]         at xsbt.boot.Launch$.apply(Launch.scala:21)
[error]         at xsbt.boot.Boot$.runImpl(Boot.scala:78)
[error]         at xsbt.boot.Boot$.run(Boot.scala:73)
[error]         at xsbt.boot.Boot$.main(Boot.scala:21)
[error]         at xsbt.boot.Boot.main(Boot.scala)
[info] [error] Use 'last' for the full log.
[error] java.net.ConnectException: Connection refused: connect
[info] [error] java.net.ConnectException: Connection refused: connect
[error]         at java.base/sun.nio.ch.Net.connect0(Native Method)
[error]         at java.base/sun.nio.ch.Net.connect(Net.java:589)
[info] [error] Use 'last' for the full log.
[error]         at java.base/sun.nio.ch.Net.connect(Net.java:578)
[error]         at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583)
[error]         at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[error]         at java.base/java.net.Socket.connect(Socket.java:751)
[error]         at java.base/java.net.Socket.connect(Socket.java:686)
[error]         at java.base/java.net.Socket.<init>(Socket.java:555)
[error]         at java.base/java.net.Socket.<init>(Socket.java:356)
[error]         at xsbt.IPC$.client(IPC.scala:23)
[error]         at sbt.BasicCommands$.readMessage(BasicCommands.scala:477)
[error]         at sbt.BasicCommands$.doRead(BasicCommands.scala:453)
[error]         at sbt.BasicCommands$.$anonfun$read$2(BasicCommands.scala:440)
[error]         at sbt.Command$.$anonfun$applyEffect$4(Command.scala:151)
[error]         at sbt.Command$.$anonfun$applyEffect$2(Command.scala:146)
[error]         at sbt.Command$.process(Command.scala:194)
[error]         at sbt.MainLoop$.$anonfun$processCommand$7(MainLoop.scala:267)
[error]         at scala.Option.getOrElse(Option.scala:189)
[error]         at sbt.MainLoop$.process$1(MainLoop.scala:267)
[error]         at sbt.MainLoop$.processCommand(MainLoop.scala:312)
[error]         at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:171)
[error]         at sbt.State$StateOpsImpl$.runCmd$1(State.scala:290)
[error]         at sbt.State$StateOpsImpl$.process$extension(State.scala:326)
[error]         at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:171)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error]         at sbt.MainLoop$.next(MainLoop.scala:171)
[error]         at sbt.MainLoop$.run(MainLoop.scala:152)
[error]         at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:127)
[error]         at sbt.io.Using.apply(Using.scala:28)
[error]         at sbt.MainLoop$.runWithNewLog(MainLoop.scala:120)
[error]         at sbt.MainLoop$.runAndClearLast(MainLoop.scala:74)
[error]         at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:59)
[error]         at sbt.MainLoop$.runLogged(MainLoop.scala:50)
[error]         at sbt.StandardMain$.runManaged(Main.scala:225)
[error]         at sbt.xMain$.$anonfun$run$11(Main.scala:135)
[error]         at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error]         at scala.Console$.withIn(Console.scala:230)
[error]         at sbt.internal.util.Terminal$.withIn(Terminal.scala:610)
[error]         at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:390)
[error]         at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error]         at scala.Console$.withOut(Console.scala:167)
[error]         at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:600)
[error]         at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error]         at scala.Console$.withErr(Console.scala:196)
[error]         at sbt.internal.util.Terminal$.withOut(Terminal.scala:600)
[error]         at sbt.internal.util.Terminal$.withStreams(Terminal.scala:390)
[error]         at sbt.xMain$.withStreams$1(Main.scala:88)
[error]         at sbt.xMain$.run(Main.scala:123)
[error]         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[error]         at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:59)
[error]         at sbt.xMain.run(Main.scala:47)
[error]         at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
[error]         at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
[error]         at xsbt.boot.Launch$.run(Launch.scala:149)
[error]         at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
[error]         at xsbt.boot.Launch$.launch(Launch.scala:159)
[error]         at xsbt.boot.Launch$.apply(Launch.scala:44)
[error]         at xsbt.boot.Launch$.apply(Launch.scala:21)
[error]         at xsbt.boot.Boot$.runImpl(Boot.scala:78)
[error]         at xsbt.boot.Boot$.run(Boot.scala:73)
[error]         at xsbt.boot.Boot$.main(Boot.scala:21)
[error]         at xsbt.boot.Boot.main(Boot.scala)
[success] Total time: 46 s, completed Jul 14, 2024, 4:25:06тАпPM
```

**Comment by OlegYch** [comment]
the problem goes away if i remove `ThisBuild / pluginCrossBuild / sbtVersion := "1.5.0"` setting
otherwise it happens regardless of sbt.version in the scripted test, tried 1.5.0 1.9.8 and 1.10.1

**Comment by OlegYch** [comment]
so i guess there was some bug in 1.5.0 which causes scripted to fail on driver side
i guess instead i'll just run tests using sbt.version=1.5.0 to ensure compatibility without actually using 1.5.0 on driver side
let me know if anyone has better ideas

**Comment by eed3si9n** [comment]
Closing this as resolved.
