### ISSUE TITLE
Error "SSLException: Unsupported or unrecognized SSL message while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/..."

### ISSUE THREAD

**Issue by nileshrockfire** [sbt/sbt#7086]
Below are the versions I'm using :

SBT : 1.3.13

Scala version : 2.13.3

Open JDK version : 1.8.0_275

Environment : Amazon EC2 - Linux

 

Content of plugin.sbt file :

```scala
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.8.18")
```
 
While running sbt build, it is giving below exception. I have not added any web related plugins. Still it is giving web plugin errors :

```
=============================================

[info] Loading settings for project sbttest-build from plugin.sbt ...

[info] Loading project definition from /home/ec2-user/sbtTest/project

[info] Updating

[info] Resolved  dependencies

[warn]

[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.

[warn]          com.typesafe.sbt:sbt-js-engine:1.2.3 (scalaVersion=2.12, sbtVersion=1.0)

[warn]          com.typesafe.sbt:sbt-native-packager:1.5.2 (scalaVersion=2.12, sbtVersion=1.0)

[warn]          com.lightbend.sbt:sbt-javaagent:0.1.5 (scalaVersion=2.12, sbtVersion=1.0)

[warn]          com.typesafe.sbt:sbt-twirl:1.5.1 (scalaVersion=2.12, sbtVersion=1.0)

[warn]          com.typesafe.sbt:sbt-web:1.4.4 (scalaVersion=2.12, sbtVersion=1.0)

[warn]

[warn]  Note: Unresolved dependencies path:

[error] sbt.librarymanagement.ResolveException: Error downloading com.typesafe.sbt:sbt-js-engine;sbtVersion=1.0;scalaVersion=2.12:1.2.3

[error]   Not found

[error]   Not found

[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-js-engine_2.12_1.0/1.2.3/sbt-js-engine-1.2.3.pom

[error]   not found: /home/ec2-user/.ivy2/local/com.typesafe.sbt/sbt-js-engine/scala_2.12/sbt_1.0/1.2.3/ivys/ivy.xml

[error]   download error: Caught javax.net.ssl.SSLException: Unsupported or unrecognized SSL message (Unsupported or unrecognized SSL message) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-js-engine/scala_2.12/sbt_1.0/1.2.3/ivys/ivy.xml

[error]   download error: Caught javax.net.ssl.SSLException: Unsupported or unrecognized SSL message (Unsupported or unrecognized SSL message) while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-js-engine/scala_2.12/sbt_1.0/1.2.3/ivys/ivy.xml

[error] Error downloading com.typesafe.sbt:sbt-native-packager;sbtVersion=1.0;scalaVersion=2.12:1.5.2

[error]   Not found

[error]   Not found

[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-native-packager_2.12_1.0/1.5.2/sbt-native-packager-1.5.2.pom

[error]   not found: /home/ec2-user/.ivy2/local/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.5.2/ivys/ivy.xml

[error]   download error: Caught javax.net.ssl.SSLException: Unsupported or unrecognized SSL message (Unsupported or unrecognized SSL message) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.5.2/ivys/ivy.xml

[error]   download error: Caught javax.net.ssl.SSLException: Unsupported or unrecognized SSL message (Unsupported or unrecognized SSL message) while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.5.2/ivys/ivy.xml

[error] Error downloading com.lightbend.sbt:sbt-javaagent;sbtVersion=1.0;scalaVersion=2.12:0.1.5

[error]   Not found

[error]   Not found

[error]   not found: https://repo1.maven.org/maven2/com/lightbend/sbt/sbt-javaagent_2.12_1.0/0.1.5/sbt-javaagent-0.1.5.pom

[error]   not found: /home/ec2-user/.ivy2/local/com.lightbend.sbt/sbt-javaagent/scala_2.12/sbt_1.0/0.1.5/ivys/ivy.xml

[error]   download error: Caught javax.net.ssl.SSLException: Unsupported or unrecognized SSL message (Unsupported or unrecognized SSL message) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.lightbend.sbt/sbt-javaagent/scala_2.12/sbt_1.0/0.1.5/ivys/ivy.xml

[error]   download error: Caught javax.net.ssl.SSLException: Unsupported or unrecognized SSL message (Unsupported or unrecognized SSL message) while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.lightbend.sbt/sbt-javaagent/scala_2.12/sbt_1.0/0.1.5/ivys/ivy.xml

[error] Error downloading com.typesafe.sbt:sbt-twirl;sbtVersion=1.0;scalaVersion=2.12:1.5.1

[error]   Not found

[error]   Not found

[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-twirl_2.12_1.0/1.5.1/sbt-twirl-1.5.1.pom

[error]   not found: /home/ec2-user/.ivy2/local/com.typesafe.sbt/sbt-twirl/scala_2.12/sbt_1.0/1.5.1/ivys/ivy.xml

[error]   download error: Caught javax.net.ssl.SSLException: Unsupported or unrecognized SSL message (Unsupported or unrecognized SSL message) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-twirl/scala_2.12/sbt_1.0/1.5.1/ivys/ivy.xml

[error]   download error: Caught javax.net.ssl.SSLException: Unsupported or unrecognized SSL message (Unsupported or unrecognized SSL message) while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-twirl/scala_2.12/sbt_1.0/1.5.1/ivys/ivy.xml

[error] Error downloading com.typesafe.sbt:sbt-web;sbtVersion=1.0;scalaVersion=2.12:1.4.4

[error]   Not found

[error]   Not found

[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-web_2.12_1.0/1.4.4/sbt-web-1.4.4.pom

[error]   not found: /home/ec2-user/.ivy2/local/com.typesafe.sbt/sbt-web/scala_2.12/sbt_1.0/1.4.4/ivys/ivy.xml

[error]   download error: Caught javax.net.ssl.SSLException: Unsupported or unrecognized SSL message (Unsupported or unrecognized SSL message) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-web/scala_2.12/sbt_1.0/1.4.4/ivys/ivy.xml

[error]   download error: Caught javax.net.ssl.SSLException: Unsupported or unrecognized SSL message (Unsupported or unrecognized SSL message) while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-web/scala_2.12/sbt_1.0/1.4.4/ivys/ivy.xml

[error]         at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:247)

[error]         at lmcoursier.CoursierDependencyResolution.$anonfun$update$35(CoursierDependencyResolution.scala:216)

[error]         at scala.util.Either$LeftProjection.map(Either.scala:573)

[error]         at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:216)

[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)

[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:52)

[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:102)

[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:69)

[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:115)

[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:228)

[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:115)

[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:96)

[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:150)

[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:129)

[error]         at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:2950)

[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)

[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)

[error]         at sbt.std.Transform$$anon$[4.work](http://4.work/)(Transform.scala:67)

[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)

[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)

[error]         at [sbt.Execute.work](http://sbt.execute.work/)(Execute.scala:290)

[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)

[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)

[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)

[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)

[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)

[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

[error]         at java.lang.Thread.run(Thread.java:748)

[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.typesafe.sbt:sbt-js-engine;sbtVersion=1.0;scalaVersion=2.12:1.2.3

[error]   Not found

[error]   Not found

[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-js-engine_2.12_1.0/1.2.3/sbt-js-engine-1.2.3.pom

[error]   not found: /home/ec2-user/.ivy2/local/com.typesafe.sbt/sbt-js-engine/scala_2.12/sbt_1.0/1.2.3/ivys/ivy.xml

[error]   download error: Caught javax.net.ssl.SSLException: Unsupported or unrecognized SSL message (Unsupported or unrecognized SSL message) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-js-engine/scala_2.12/sbt_1.0/1.2.3/ivys/ivy.xml

[error]   download error: Caught javax.net.ssl.SSLException: Unsupported or unrecognized SSL message (Unsupported or unrecognized SSL message) while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-js-engine/scala_2.12/sbt_1.0/1.2.3/ivys/ivy.xml

[error] Error downloading com.typesafe.sbt:sbt-native-packager;sbtVersion=1.0;scalaVersion=2.12:1.5.2

[error]   Not found

[error]   Not found

[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-native-packager_2.12_1.0/1.5.2/sbt-native-packager-1.5.2.pom

[error]   not found: /home/ec2-user/.ivy2/local/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.5.2/ivys/ivy.xml

[error]   download error: Caught javax.net.ssl.SSLException: Unsupported or unrecognized SSL message (Unsupported or unrecognized SSL message) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.5.2/ivys/ivy.xml

[error]   download error: Caught javax.net.ssl.SSLException: Unsupported or unrecognized SSL message (Unsupported or unrecognized SSL message) while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.5.2/ivys/ivy.xml

[error] Error downloading com.lightbend.sbt:sbt-javaagent;sbtVersion=1.0;scalaVersion=2.12:0.1.5

[error]   Not found

[error]   Not found

[error]   not found: https://repo1.maven.org/maven2/com/lightbend/sbt/sbt-javaagent_2.12_1.0/0.1.5/sbt-javaagent-0.1.5.pom

[error]   not found: /home/ec2-user/.ivy2/local/com.lightbend.sbt/sbt-javaagent/scala_2.12/sbt_1.0/0.1.5/ivys/ivy.xml

[error]   download error: Caught javax.net.ssl.SSLException: Unsupported or unrecognized SSL message (Unsupported or unrecognized SSL message) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.lightbend.sbt/sbt-javaagent/scala_2.12/sbt_1.0/0.1.5/ivys/ivy.xml

[error]   download error: Caught javax.net.ssl.SSLException: Unsupported or unrecognized SSL message (Unsupported or unrecognized SSL message) while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.lightbend.sbt/sbt-javaagent/scala_2.12/sbt_1.0/0.1.5/ivys/ivy.xml

[error] Error downloading com.typesafe.sbt:sbt-twirl;sbtVersion=1.0;scalaVersion=2.12:1.5.1

[error]   Not found

[error]   Not found

[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-twirl_2.12_1.0/1.5.1/sbt-twirl-1.5.1.pom

[error]   not found: /home/ec2-user/.ivy2/local/com.typesafe.sbt/sbt-twirl/scala_2.12/sbt_1.0/1.5.1/ivys/ivy.xml

[error]   download error: Caught javax.net.ssl.SSLException: Unsupported or unrecognized SSL message (Unsupported or unrecognized SSL message) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-twirl/scala_2.12/sbt_1.0/1.5.1/ivys/ivy.xml

[error]   download error: Caught javax.net.ssl.SSLException: Unsupported or unrecognized SSL message (Unsupported or unrecognized SSL message) while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-twirl/scala_2.12/sbt_1.0/1.5.1/ivys/ivy.xml

[error] Error downloading com.typesafe.sbt:sbt-web;sbtVersion=1.0;scalaVersion=2.12:1.4.4

[error]   Not found

[error]   Not found

[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-web_2.12_1.0/1.4.4/sbt-web-1.4.4.pom

[error]   not found: /home/ec2-user/.ivy2/local/com.typesafe.sbt/sbt-web/scala_2.12/sbt_1.0/1.4.4/ivys/ivy.xml

[error]   download error: Caught javax.net.ssl.SSLException: Unsupported or unrecognized SSL message (Unsupported or unrecognized SSL message) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-web/scala_2.12/sbt_1.0/1.4.4/ivys/ivy.xml

[error]   download error: Caught javax.net.ssl.SSLException: Unsupported or unrecognized SSL message (Unsupported or unrecognized SSL message) while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-web/scala_2.12/sbt_1.0/1.4.4/ivys/ivy.xml
```

Below is build.sbt file content :

=======================================

```scala
scalaVersion := "2.13.3"

version := "1.0.0"

name := "mySBTtest"

libraryDependencies ++= Seq(

  "com.google.inject" % "guice" % "4.1.0",

  "com.amazonaws" % "aws-java-sdk" % "1.11.46",

  "commons-io" % "commons-io" % "2.5",

  "com.fasterxml.jackson.core" % "jackson-core" % "2.8.7",

  "com.fasterxml.jackson.core" % "jackson-databind" % "2.8.7",

  "com.fasterxml.jackson.core" % "jackson-annotations" % "2.8.7",

  "com.fasterxml.jackson.dataformat" % "jackson-dataformat-csv" % "2.9.0",

  "org.mockito" % "mockito-core" % "2.8.9",

  "com.couchbase.client" % "java-client" % "3.3.1",

  "org.mindrot" % "jbcrypt" % "0.3m",

  "io.vavr" % "vavr" % "0.9.0",

  "io.vavr" % "vavr-jackson" % "0.9.0",

  "io.vavr" % "vavr-match" % "0.9.0",

  "com.google.code.gson" % "gson" % "2.8.1",

  "junit" % "junit" % "4.12",

  "com.typesafe.play" % "play_2.12" % "2.8.9",

  "io.reactivex" % "rxjava" % "1.3.0",

  "com.fasterxml.jackson.dataformat" % "jackson-dataformat-csv" % "2.9.0",

  "io.vavr" % "vavr-match" % "0.9.0",

  "commons-io" % "commons-io" % "2.4",

  "com.googlecode.jsontoken" % "jsontoken" % "1.0",

  "com.google.guava" % "guava" % "18.0",

  "org.mongodb" % "bson" % "3.3.0",

  "org.apache.tika" % "tika-core" % "1.18",

  "org.apache.tika" % "tika-parsers" % "1.18"

)
```

**Comment by mkurz** [comment]
I recommend using sbt 1.7.1, not outdated 1.3.x

**Comment by nileshrockfire** [comment]
Tried with SBT version : 1.7.1, and Scala version 2.13.3.

content of my plugin.sbt

`addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.8.10")`

 

Still getting same error :

 

`[info] welcome to sbt 1.7.1 (Red Hat, Inc. Java 1.8.0_275)

[info] loading settings for project sbttest-build from plugin.sbt ...

[info] loading project definition from /home/ec2-user/sbtTest/project

[info] Updating

[info] Resolved  dependencies

[warn]

[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.

[warn]          com.typesafe.sbt:sbt-js-engine:1.2.3 (scalaVersion=2.12, sbtVersion=1.0)

[warn]          com.typesafe.sbt:sbt-native-packager:1.5.2 (scalaVersion=2.12, sbtVersion=1.0)

[warn]          com.lightbend.sbt:sbt-javaagent:0.1.5 (scalaVersion=2.12, sbtVersion=1.0)

[warn]          com.typesafe.sbt:sbt-twirl:1.5.1 (scalaVersion=2.12, sbtVersion=1.0)

[warn]          com.typesafe.sbt:sbt-web:1.4.4 (scalaVersion=2.12, sbtVersion=1.0)

[warn]

[warn]  Note: Unresolved dependencies path:

[error] sbt.librarymanagement.ResolveException: Error downloading com.typesafe.sbt:sbt-js-engine;sbtVersion=1.0;scalaVersion=2.12:1.2.3

[error]   Not found

[error]   Not found

[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-js-engine_2.12_1.0/1.2.3/sbt-js-engine-1.2.3.pom

[error]   not found: /home/ec2-user/.ivy2/localcom.typesafe.sbt/sbt-js-engine/scala_2.12/sbt_1.0/1.2.3/ivys/ivy.xml

[error]   download error: Caught javax.net.ssl.SSLException (Unsupported or unrecognized SSL message) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-js-engine/scala_2.12/sbt_1.0/1.2.3/ivys/ivy.xml

[error]   download error: Caught javax.net.ssl.SSLException (Unsupported or unrecognized SSL message) while downloading [https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-js-engine/scala_2.12/sbt_1.0/1.2.3/ivys/ivy.xml`](https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-js-engine/scala_2.12/sbt_1.0/1.2.3/ivys/ivy.xml%60)

**Comment by mkurz** [comment]
Please set Scala version to 2.13.10 in your `build.sbt` (but that should not be the problem).

Have you defined any resolvers in your `build.sbt` or `project/plugins.sbt`?

You can also try fresh by removing your `$HOME/.sbt/` folder and the `target` folder in project (also any `target` folder under `plugins`).

Maybe can you post your full `project/plugins.sbt` and `build.sbt`? Are there any other `.sbt` files in your projects root folder or the plugins folder?

**Comment by nileshrockfire** [comment]
@mkurz , thanks for the reply.

I tried your suggestions, but no luck.

 

1) Even though, I explicitly set the scalaVersion:="2.13.10" in my `build.sbt`, while running sbt, it is picking `2.12.16`. Check below initial logs :

 

```

downloading sbt launcher 1.8.0

[info] [launcher] getting org.scala-sbt sbt 1.7.1  (this may take some time)...

[info] [launcher] getting Scala 2.12.16 (for sbt)...

[info] welcome to sbt 1.7.1 (Red Hat, Inc. Java 1.8.0_282)

[info] loading settings for project sbtproj-build from plugins.sbt ...

[info] loading project definition from /home/ec2-user/sbtProj/project

[info] Updating

```

--------------------------

Below is my build.sbt content, I haven't added any resolver yet.

 

```

name := """product-code-api"""

organization := "com.wu"

version := "11.0.1"

scalaVersion := "2.13.10"

```

-----------------------------------------------------------------------

**Plugins.sbt :**

 

`addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.8.18")`

 

 

Please note that I have done fresh installation of SBT in my Amazon linux EC2.

**Comment by mkurz** [comment]
I tried locally with a clean `.sbt` and `.cache/coursier` folder, etc. and it worked with just the two configs you posted.

I am pretty sure this is not sbt nor Play's fault. You get a `javax.net.ssl.SSLException`
```
[error] download error: Caught javax.net.ssl.SSLException: Unsupported or unrecognized SSL message (Unsupported or unrecognized SSL message) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-js-engine/scala_2.12/sbt_1.0/1.2.3/ivys/ivy.xml
```
There is somethings going on on your EC2 instance that is causing problems. Maybe amazon is blocking requests, firewall, or maybe use another java version (e.g. java 11 or OpenJdk).
Currently you use Red Hat jdk:
```
[info] welcome to sbt 1.7.1 (Red Hat, Inc. Java 1.8.0_275)
```

**Comment by eed3si9n** [comment]
Maybe something to try is running curl inside the EC2 machine to see that the certificates are up to date?

```bash
curl --head -L https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-js-engine/scala_2.12/sbt_1.0/1.2.3/ivys/ivy.xml
```

This should return HTTP/1.1 200 OK.

**Comment by nileshrockfire** [comment]
Getting this error now :
```
curl --head -L https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-js-engine/scala_2.12/sbt_1.0/1.2.3/ivys/ivy.xml
HTTP/1.1 302 Moved Temporarily
Content-Length: 145
Content-Type: text/html
Date: Thu, 08 Dec 2022 18:30:16 GMT
Location: https://scala.jfrog.io/artifactory/sbt-plugin-releases/com.typesafe.sbt/sbt-js-engine/scala_2.12/sbt_1.0/1.2.3/ivys/ivy.xml
Server: nginx/1.19.6
Connection: keep-alive

curl: (35) SSL received a record that exceeded the maximum permissible length.
```

**Comment by eed3si9n** [comment]
Yea, so that's likely an issue with your environment. Unless Scala Center's Artifactory is blocked AWS-wide, I think it's outside of the scope of issue tracking. 

Feel free to continue the discussion on Discord etc though - https://www.scala-sbt.org/community.html
