### ISSUE TITLE
facing a compiler error (scalac: Error: xsbt.CompilerInterface)

### ISSUE THREAD

**Issue by kayllenng** [sbt/sbt#7089]
## problem
```
scalac: Error: xsbt.CompilerInterface
java.lang.ClassNotFoundException: xsbt.CompilerInterface
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at sbt.internal.inc.AnalyzingCompiler.getBridgeClass(AnalyzingCompiler.scala:372)
	at sbt.internal.inc.AnalyzingCompiler.bridgeInstance(AnalyzingCompiler.scala:321)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:95)
	at org.jetbrains.jps.incremental.scala.local.IdeaIncrementalCompiler.compile(IdeaIncrementalCompiler.scala:57)
	at org.jetbrains.jps.incremental.scala.local.LocalServer.doCompile(LocalServer.scala:52)
	at org.jetbrains.jps.incremental.scala.local.LocalServer.compile(LocalServer.scala:30)
	at org.jetbrains.jps.incremental.scala.remote.Main$.compileLogic(Main.scala:209)
	at org.jetbrains.jps.incremental.scala.remote.Main$.$anonfun$handleCommand$1(Main.scala:192)
	at org.jetbrains.jps.incremental.scala.remote.Main$.decorated$1(Main.scala:182)
	at org.jetbrains.jps.incremental.scala.remote.Main$.handleCommand(Main.scala:189)
	at org.jetbrains.jps.incremental.scala.remote.Main$.serverLogic(Main.scala:165)
	at org.jetbrains.jps.incremental.scala.remote.Main$.nailMain(Main.scala:105)
	at org.jetbrains.jps.incremental.scala.remote.Main.nailMain(Main.scala)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.facebook.nailgun.NGSession.runImpl(NGSession.java:312)
	at com.facebook.nailgun.NGSession.run(NGSession.java:198)
```

**Comment by adpi2** [comment]
@kayllenng In order to help you, we would need more information.

What sbt version do you have in your `./project/build.properties` file?

Can you share your `build.sbt` file as well? In particular what is your `scalaVersion`?

**Comment by SethTisue** [comment]
note the presence of `org.jetbrains.jps.incremental.scala.local.IdeaIncrementalCompiler` in the stack trace — perhaps this is actually an IntelliJ bug or a zinc bug and has nothing to do with sbt per se?

**Comment by eed3si9n** [comment]
There's a reason why we have steps, problem, and expectations. Without further information, I'd agree with Seth that this is not an sbt issue, so I'm closing this for now.
