### ISSUE TITLE
Running `sbtn` on aarch64 Linux fails

### ISSUE THREAD

**Issue by mkurz** [sbt/sbt#7095]
On my Apple M1 MacBook, running Asahi Linux, I created the sbtn binary via: `sbt clean nativeImage`
Running the binary I get following error, which seems similiar to what happend on M1 macOS (#6162):

```
# started server by running sbt

# Now try to connect with sbtn:
$ ../client/target/bin/sbtn 
[info] entering *experimental* thin client - BEEP WHIRR
java.lang.UnsatisfiedLinkError: Can't load library: /tmp/.sbt/ipcsocket/libsbtipcsocket15328888734327544076.so
        at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibrary(NativeLibrarySupport.java:105)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:228)
        at java.lang.Runtime.load0(Runtime.java:768)
        at java.lang.Runtime.load(Runtime.java:244)
        at java.lang.System.load(System.java:358)
        at org.scalasbt.ipcsocket.NativeLoader.load(NativeLoader.java:87)
        at org.scalasbt.ipcsocket.JNIUnixDomainSocketLibraryProvider.<clinit>(JNIUnixDomainSocketLibraryProvider.java:78)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:351)
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:271)
        at org.scalasbt.ipcsocket.UnixDomainSocketLibraryProvider.get(UnixDomainSocketLibraryProvider.java:26)
        at org.scalasbt.ipcsocket.UnixDomainSocket.<init>(UnixDomainSocket.java:50)
        at sbt.protocol.ClientSocket$.localSocket(ClientSocket.scala:46)
        at sbt.protocol.ClientSocket$.socket(ClientSocket.scala:38)
        at sbt.internal.client.NetworkClient.mkSocket(NetworkClient.scala:144)
        at sbt.internal.client.NetworkClient.connect$1(NetworkClient.scala:193)
        at sbt.internal.client.NetworkClient.connectOrStartServerAndConnect(NetworkClient.scala:213)
        at sbt.internal.client.NetworkClient.init(NetworkClient.scala:223)
        at sbt.internal.client.NetworkClient.connect(NetworkClient.scala:761)
        at sbt.internal.client.NetworkClient$.clientImpl(NetworkClient.scala:1187)
        at sbt.internal.client.NetworkClient$.client(NetworkClient.scala:1178)
        at sbt.internal.client.NetworkClient$.$anonfun$main$4(NetworkClient.scala:1242)
        at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withIn(Console.scala:230)
        at sbt.internal.util.Terminal$.withIn(Terminal.scala:578)
        at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:358)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withOut(Console.scala:167)
        at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:568)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withErr(Console.scala:196)
        at sbt.internal.util.Terminal$.withOut(Terminal.scala:568)
        at sbt.internal.util.Terminal$.withStreams(Terminal.scala:358)
        at sbt.internal.client.NetworkClient$.main(NetworkClient.scala:1240)
        at sbt.internal.client.NetworkClient.main(NetworkClient.scala)
        at sbt.client.Client.main(Client.java:19)
```

**Comment by mkurz** [comment]
So, I guess we have to first add support for aarch64 Linux in sbt/ipcsocket, like https://github.com/sbt/ipcsocket/pull/11 did?

(Also see https://github.com/sbt/sbt/issues/6906#issuecomment-1360587477 and https://github.com/sbt/sbt/issues/6162)

**Comment by eed3si9n** [comment]
Added Aarch64 binary in https://github.com/sbt/ipcsocket/releases/tag/v1.6.0 (currently Central sync is delayed but visible here - https://oss.sonatype.org/content/repositories/public/org/scala-sbt/ipcsocket/ipcsocket/1.6.0/).
