### ISSUE TITLE
Unable to load Iceberg in sbt test (but can in sbt test:console so I know it's on the classpath just something funky is happening with the loaders)?

### ISSUE THREAD

**Issue by holdenk** [sbt/sbt#7137]
## steps

Try and use sbt (w/ flat) to test iceberg

```
import Dependencies._

ThisBuild / scalaVersion     := "2.12.8"
ThisBuild / version          := "0.1.0-SNAPSHOT"
ThisBuild / organization     := "com.holdenkarau"
ThisBuild / organizationName := "holdenkarau"
ThisBuild / name := "Iceberg WAP plugin"

Test / classLoaderLayeringStrategy := ClassLoaderLayeringStrategy.Flat
Test / parallelExecution := false
Test / fork := false



lazy val root = (project in file("."))
  .settings(
    name := "Iceberg Spark Upgrade WAP Plugin",
    libraryDependencies += scalaTest % Test,
    libraryDependencies += icebergSparkRuntime % Test,
    libraryDependencies += sparkTestingBase % Test,
    libraryDependencies += iceberg % Provided,
    libraryDependencies += logback % Provided,
    libraryDependencies += scalaLogging,
  )

// See https://www.scala-sbt.org/1.x/docs/Using-Sonatype.html for instructions on how to publish to Sonatype.

```

## problem

I get the exception:

```

[info] - WAPIcebergSpec should be called on iceberg commit *** FAILED ***
[info]   org.apache.spark.SparkException: Cannot find catalog plugin class for catalog 'spark_catalog': org.apache.iceberg.spark.SparkSessionCatalog
[info]   at org.apache.spark.sql.errors.QueryExecutionErrors$.catalogPluginClassNotFoundForCatalogError(QueryExecutionErrors.scala:1455)
[info]   at org.apache.spark.sql.connector.catalog.Catalogs$.load(Catalogs.scala:65)
[info]   at org.apache.spark.sql.connector.catalog.CatalogManager.loadV2SessionCatalog(CatalogManager.scala:66)
[info]   at org.apache.spark.sql.connector.catalog.CatalogManager.$anonfun$v2SessionCatalog$2(CatalogManager.scala:85)
[info]   at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:86)
[info]   at org.apache.spark.sql.connector.catalog.CatalogManager.$anonfun$v2SessionCatalog$1(CatalogManager.scala:85)
[info]   at scala.Option.map(Option.scala:163)
[info]   at org.apache.spark.sql.connector.catalog.CatalogManager.v2SessionCatalog(CatalogManager.scala:84)
[info]   at org.apache.spark.sql.connector.catalog.CatalogManager.catalog(CatalogManager.scala:50)
[info]   at org.apache.spark.sql.connector.catalog.CatalogManager.currentCatalog(CatalogManager.scala:117)
[info]   ...
[info]   Cause: java.lang.ClassNotFoundException: org.apache.iceberg.spark.SparkSessionCatalog
[info]   at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
[info]   at sbt.internal.ManagedClassLoader.findClass(ManagedClassLoader.java:102)
[info]   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
[info]   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[info]   at org.apache.spark.sql.connector.catalog.Catalogs$.load(Catalogs.scala:55)
[info]   at org.apache.spark.sql.connector.catalog.CatalogManager.loadV2SessionCatalog(CatalogManager.scala:66)
[info]   at org.apache.spark.sql.connector.catalog.CatalogManager.$anonfun$v2SessionCatalog$2(CatalogManager.scala:85)
[info]   at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:86)
[info]   at org.apache.spark.sql.connector.catalog.CatalogManager.$anonfun$v2SessionCatalog$1(CatalogManager.scala:85)
[info]   at scala.Option.map(Option.scala:163)
[info]   ...

````

Note I can load the class in test:console:

```
scala> val cl = Thread.currentThread.getContextClassLoader
cl: ClassLoader = scala.tools.nsc.interpreter.IMain$TranslatingClassLoader@329c5cb3

scala> cl.loadClass("org.apache.iceberg.spark.SparkSessionCatalog")
res2: Class[_] = class org.apache.iceberg.spark.SparkSessionCatalog


```

Spark is using this logic to choose the class loader (see utils.scala)

```
  /**
   * Get the Context ClassLoader on this thread or, if not present, the ClassLoader that
   * loaded Spark.
   *
   * This should be used whenever passing a ClassLoader to Class.ForName or finding the currently
   * active loader when setting up ClassLoader delegation chains.
   */
  def getContextOrSparkClassLoader: ClassLoader =
    Option(Thread.currentThread().getContextClassLoader).getOrElse(getSparkClassLoader)


```
## expectation

Spark loads the iceberg class and then my test fails because.

## notes

There is a very long stream of me trying to figure out whats going on YouTube if you want https://www.youtube.com/watch?v=KonKR6qdrMc but hopefully this is a good enough summary.

**Comment by SethTisue** [comment]
Do you have reason to believe there is a bug in sbt here? If so, what is the bug?

**Comment by holdenk** [comment]
Well it only shows up when I invoke with SBT, otherwise I can load the class just fine. As far as I understand (from the error messages) sbt is doing some smart things with the class loaders which when coupled with a failure to load a class that only shows up in SBT makes me think it might be related to some of the smart things SBT is doing to make things go faster.

**Comment by SethTisue** [comment]
does it work with `Test / fork := true`?

**Comment by SethTisue** [comment]
If you want to try and figure out what's actually going on with classloaders in the non-forked case, this documentation might help: https://www.scala-sbt.org/1.x/docs/In-Process-Classloaders.html
