### ISSUE TITLE
Division by Zero error when backspacing in Eclipse ELT Terminal

### ISSUE THREAD

**Issue by pmeheut** [sbt/sbt#714]
Hi,
When backspacing in Eclipse Terminal ELT (https://code.google.com/p/elt/), I get a Division by Zero error each time and sbt usually ends up quitting. 
I'm using 0.12.2 and last returned:

java.lang.ArithmeticException: / by zero
        at jline.ConsoleReader.backspace(ConsoleReader.java:1414)
        at jline.ConsoleReader.backspace(ConsoleReader.java:1436)
        at jline.ConsoleReader.readLine(ConsoleReader.java:628)
        at jline.ConsoleReader.readLine(ConsoleReader.java:457)
        at sbt.JLine.sbt$JLine$$readLineDirectRaw(LineReader.scala:48)
        at sbt.JLine$$anonfun$readLineDirect$2.apply(LineReader.scala:41)
        at sbt.JLine$$anonfun$readLineDirect$2.apply(LineReader.scala:41)
        at sbt.Signals0.withHandler(Signal.scala:55)
        at sbt.Signals$.withHandler(Signal.scala:13)
        at sbt.JLine.readLineDirect(LineReader.scala:41)

This is obviously a jline bug and it seems to come from the ELT terminal having "columns" to 0 in the tty configuration. Maybe trying a more recent jline version would help (I'm not sure which one is used).

**Comment by harrah** [comment]
See #523.

**Comment by eamelink** [comment]
As a work-around for people finding this issue through Google:

With `stty -a` you can inspect whether it's actually the case that columns is set to 0, and to change it, use:

```
stty columns 80
```
