### ISSUE TITLE
when starting "sbt --sbt-create" met invalidPathException.

### ISSUE THREAD

**Issue by nwmoon** [sbt/sbt#7146]
## steps

after setting JAVA_OPTS of our proxy, tried to install sbt ---sbt-create

## problem

met invalidPathException

## expectation

sbt server running

## notes

```scala
[info] sbt server started at local:sbt-server-59a8c5f06e1b17d1bf5d
Exception in thread "sbt-socket-server" java.nio.file.InvalidPathException: Illegal char <"> at index 0: "C:\Users\nwmoon\AppData\Local\Microsoft\WindowsApps
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at sbt.internal.bsp.BuildServerConnection$.$anonfun$sbtScriptInPath$2(BuildServerConnection.scala:69)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
        at scala.collection.TraversableLike.map(TraversableLike.scala:286)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
        at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
        at sbt.internal.bsp.BuildServerConnection$.$anonfun$sbtScriptInPath$1(BuildServerConnection.scala:69)
        at scala.Option.map(Option.scala:230)
        at sbt.internal.bsp.BuildServerConnection$.sbtScriptInPath(BuildServerConnection.scala:69)
        at sbt.internal.bsp.BuildServerConnection$.$anonfun$writeConnectionFile$1(BuildServerConnection.scala:31)
        at scala.Option.orElse(Option.scala:447)
        at sbt.internal.bsp.BuildServerConnection$.writeConnectionFile(BuildServerConnection.scala:31)
        at sbt.internal.server.Server$$anon$1$$anon$2.run(Server.scala:105)
```

**Comment by eed3si9n** [comment]
@nwmoon Thanks for the report!

I feel like this "Illegal char" is a somewhat recurrent issue with Windows that we've seen elsewhere in sbt.

- https://github.com/sbt/sbt/issues/6720
- https://github.com/sbt/sbt/issues/5994
- https://github.com/sbt/sbt/issues/4690

Also the fact that double quote character is getting converted to a NIO Path itself seems to be a symptom of another logical problem.
