### ISSUE TITLE
Fetch artifact on Maven with credentials

### ISSUE THREAD

**Issue by max-empirys** [sbt/sbt#7181]
Hi,

## summary

We are not able to fetch artifacts from a Maven repository (hosted by Jetbrain Space) using credentials.

## steps

Sbt version `1.8.2` in a Playframework project.

build.sbt
````
lazy val root = (project in file(".")).enablePlugins(PlayJava)
scalaVersion := "2.13.10"
credentials += Credentials("space-maven", "https://maven.pkg.jetbrains.space/xxxx/p/main/space-maven", "user", "pass")
resolvers += "space-maven" at "https://maven.pkg.jetbrains.space/xxxx/p/main/space-maven"

libraryDependencies += "com.xxxx.hello" % "hello" % "1.0"
````

plugins.sbt
````
// The Play plugin
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.8.19")
libraryDependencySchemes += "org.scala-lang.modules" %% "scala-xml" % VersionScheme.Always
````

Run `sbt compile`

## problem

We get Unauthorized. It's like credentials are not used (got the same issues with sbt 1.7.2) :

````
[error] sbt.librarymanagement.ResolveException: Error downloading com.xxxx.hello:hello:1.0
[error]   Not found
[error]   Not found
[error]   not found: /Users/maxence/.ivy2/localcom.xxxx.hello/hello/1.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/xxxx/hello/hello/1.0/hello-1.0.pom
[error]   unauthorized: https://maven.pkg.jetbrains.space/xxxx/p/main/space-maven/com/xxxx/hello/hello/1.0/hello-1.0.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:344)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:313)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:313)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:59)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3687)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:833)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.xxxx.hello:hello:1.0
[error]   Not found
[error]   Not found
[error]   not found: /Users/maxence/.ivy2/localcom.xxxx.hello/hello/1.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/xxxx/peppol/hello/1.0/hello-1.0.pom
[error]   unauthorized: https://maven.pkg.jetbrains.space/xxxx/p/main/space-maven/com/xxxx.hello/hello/1.0/hello-1.0.pom
````

## expectation

Artifact should be fetched with the credentials.

## notes

- We are looking to use the credentials like this to make it easier to provide the login and pass via environment variables for our CI.
- The "password" is a token generated that looks like a JWT token and work with maven for publish and read artifacts
- We tested the credentials with a maven project and it works as expected (we can fetch the dependency).

I tried multiple things to debug but I can't figure out if it's a bug or not.

**Comment by SethTisue** [comment]
It would be useful to know if the problem is reproducible using Coursier alone, or whether there's truly an set-specific angle here.

**Comment by max-empirys** [comment]
Hi,

Thank you for the feedback.

It looks like it's not related to Coursier.

Here is a test without Coursier. I added `ThisBuild / useCoursier := false` in `build.sbt`. 

Here is the trace : 

````

[error] Unable to find credentials for [ @ maven.pkg.jetbrains.space].
[warn] 	module not found: com.xxxx.hello#hello;1.0
[warn] ==== local: tried
[warn]   /Users/maxence/.ivy2/local/com.xxxx.hello/hello/1.0/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/xxxx/hello/hello/1.0/hello-1.0.pom
[warn] ==== space-maven: tried
[warn]   https://maven.pkg.jetbrains.space/xxxx/p/main/space-maven/com/xxxx/hello/hello/1.0/hello-1.0.pom
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.xxxx.hello#hello;1.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::


....


[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.xxxx.hello:hello:1.0 (/Users/maxence/dev/workspace/myproject/back/build.sbt#L128-129)
[warn] 		  +- com.xxxx:myproject_2.13:1.0-SNAPSHOT
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.xxxx.hello#hello;1.0: not found
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:335)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:211)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:245)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:209)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:72)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$1.call(Ivy.scala:82)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:113)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannelRetries$1(Locks.scala:91)
[error] 	at xsbt.boot.Locks$GlobalLock.$anonfun$withFileLock$1(Locks.scala:119)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:12)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.withFileLock(Locks.scala:119)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:71)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:59)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:47)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:36)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:82)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:203)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:200)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:244)
[error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:196)
[error] 	at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:22)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:59)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3687)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:833)
[error] (update) sbt.librarymanagement.ResolveException: unresolved dependency: com.xxxx.hello#hello;1.0: not found
````

Seeing above logs I tried to change my credentials realm with `maven.pkg.jetbrains.space` because I saw `Unable to find credentials for [ @ maven.pkg.jetbrains.space]`.

Here is my new config for the maven part : 

````
credentials += Credentials("maven.pkg.jetbrains.space", "https://maven.pkg.jetbrains.space/xxxx/p/main/space-maven", "user", "pass")
resolvers += "maven.pkg.jetbrains.space" at "https://maven.pkg.jetbrains.space/xxxx/p/main/space-maven"
````

Unfortunatly I get the exact same error as above.

Note that I have the user and pass directly in my file for now to make sure I get them correct and they work 100% sure.

I guess something wrong with my config (or a bug?) when I see `[error] Unable to find credentials for [ @ maven.pkg.jetbrains.space].`

Feel free to ask any tests that could help.

**Comment by max-empirys** [comment]
Maybe something wrong because when i look on internet I see that the realm should be something like `[Realm Name @ my.host.com]`. In my case it's likes the Realm name is not specified.

**Comment by max-empirys** [comment]
# Full Resolvers

````
[IJ][myproject] $ show fullResolvers
[info] * Raw(ProjectResolver(inter-project, mapped: ))
[info] * FileRepository(local, Patterns(ivyPatterns=Vector(${ivy.home}/local/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)([branch]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), artifactPatterns=Vector(${ivy.home}/local/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)([branch]/)[revision]/[type]s/[artifact](-[classifier]).[ext]), isMavenCompatible=false, descriptorOptional=false, skipConsistencyCheck=false), FileConfiguration(true, None))
[info] * public: https://repo1.maven.org/maven2/
[info] * maven.pkg.jetbrains.space: https://maven.pkg.jetbrains.space/xxxx/p/main/space-maven
````

# Credentials
````
[IJ][myproject] $ show credentials
[info] * DirectCredentials("maven.pkg.jetbrains.space", "https://maven.pkg.jetbrains.space/xxxx/p/main/space-maven", "user", ****)
````

**Comment by max-empirys** [comment]
Yay, I found my issue looking at @mantovani comment here : https://github.com/sbt/sbt/issues/5492#issuecomment-614492826

My new **working** configuration is : 

````.sbt
credentials += Credentials(null, "maven.pkg.jetbrains.space", "user", "pass")
resolvers += "space-maven" at "https://maven.pkg.jetbrains.space/xxxx/p/main/space-maven"
````

The trick is to set the Realm to `null`.

It works without **and with** Coursier (eg. with or without this line `ThisBuild / useCoursier := false`).

For those looking for environement variables it also work like this : 

````.sbt
credentials += Credentials(null, "maven.pkg.jetbrains.space", sys.env.get("MY_MAVEN_USER").get, sys.env.get("MY_MAVEN_PASSWORD").get)
resolvers += "space-maven" at "https://maven.pkg.jetbrains.space/xxxx/p/main/space-maven"
`````

This works with the `sbt-dotenv` plugin too (for dev mode), that could looks like : 

.env
````.env
MY_MAVEN_USER=user
MY_MAVEN_PASSWORD=pass

````

We are using `sbt-dotenv` version `3.0.0` : 
```.sbt
addSbtPlugin("nl.gn0s1s" % "sbt-dotenv" % "3.0.0")
```


Hope this may help someone trying to use Jetbrains Space or any Maven repo with Credentials.
