### ISSUE TITLE
When I write "sbt update"

### ISSUE THREAD

**Issue by youssame** [sbt/sbt#7182]
When I write `sbt update` I have this error, I'm working on **Ubuntu On Windows** with sbt ` 1.3.12` and Intellij
```` java
[error] lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[error] https://splunk.jfrog.io/artifactory/ext-releases-local/com/splunk/splunk/1.6.5.0/splunk-1.6.5.0.jar: download error: Caught java.net.UnknownHostException: jfrog-prod-use1-shared-virginia-main.s3.amazonaws.com (jfrog-prod-use1-shared-virginia-main.s3.amazonaws.com) while downloading https://splunk.jfrog.io/artifactory/ext-releases-local/com/splunk/splunk/1.6.5.0/splunk-1.6.5.0.jar
[error]
[error]         at lmcoursier.internal.shaded.coursier.Artifacts$.$anonfun$fetchArtifacts$14(Artifacts.scala:302)
[error]         at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
[error]         at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
[error]         at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
[error]         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:829)
[error] Caused by: lmcoursier.internal.shaded.coursier.cache.ArtifactError$DownloadError: download error: Caught java.net.UnknownHostException: jfrog-prod-use1-shared-virginia-main.s3.amazonaws.com (jfrog-prod-use1-shared-virginia-main.s3.amazonaws.com) while downloading https://splunk.jfrog.io/artifactory/ext-releases-local/com/splunk/splunk/1.6.5.0/splunk-1.6.5.0.jar
[error]         at lmcoursier.internal.shaded.coursier.cache.FileCache$.helper$2(FileCache.scala:1018)
[error]         at lmcoursier.internal.shaded.coursier.cache.FileCache$.coursier$cache$FileCache$$downloading(FileCache.scala:1032)
[error]         at lmcoursier.internal.shaded.coursier.cache.FileCache.doDownload$1(FileCache.scala:320)
[error]         at lmcoursier.internal.shaded.coursier.cache.FileCache.$anonfun$download$54(FileCache.scala:507)
[error]         at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:59)
[error]         at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:84)
[error]         at lmcoursier.internal.shaded.coursier.cache.FileCache.$anonfun$download$32(FileCache.scala:508)
[error]         at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[error]         at scala.util.Success.$anonfun$map$1(Try.scala:255)
[error]         at scala.util.Success.map(Try.scala:213)
[error]         at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[error]         at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[error]         at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[error]         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:829)
[error] Caused by: java.net.UnknownHostException: jfrog-prod-use1-shared-virginia-main.s3.amazonaws.com
[error]         at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:229)
[error]         at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[error]         at java.base/java.net.Socket.connect(Socket.java:609)
[error]         at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:305)
[error]         at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
[error]         at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
[error]         at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:508)
[error]         at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
[error]         at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
[error]         at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:373)
[error]         at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:207)
[error]         at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
[error]         at java.base/sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1071)
[error]         at java.base/sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1069)
[error]         at java.base/java.security.AccessController.doPrivileged(Native Method)
[error]         at java.base/java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:795)
[error]         at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1068)
[error]         at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:193)
[error]         at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
[error]         at java.base/sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1512)
[error]         at java.base/sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1510)
[error]         at java.base/java.security.AccessController.doPrivileged(Native Method)
[error]         at java.base/java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:795)
[error]         at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
[error]         at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
[error]         at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
[error]         at lmcoursier.internal.shaded.coursier.cache.CacheUrl$.redirectTo(CacheUrl.scala:152)
[error]         at lmcoursier.internal.shaded.coursier.cache.CacheUrl$.redirect(CacheUrl.scala:162)
[error]         at lmcoursier.internal.shaded.coursier.cache.CacheUrl$.urlConnectionMaybePartial(CacheUrl.scala:304)
[error]         at lmcoursier.internal.shaded.coursier.cache.CacheUrl$.urlConnectionMaybePartial(CacheUrl.scala:277)
[error]         at lmcoursier.internal.shaded.coursier.cache.FileCache.$anonfun$download$33(FileCache.scala:349)
[error]         at lmcoursier.internal.shaded.coursier.cache.FileCache$.$anonfun$downloading$1(FileCache.scala:998)
[error]         at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.withUrlLock(CacheLocks.scala:102)
[error]         at lmcoursier.internal.shaded.coursier.cache.FileCache$.helper$2(FileCache.scala:998)
[error]         at lmcoursier.internal.shaded.coursier.cache.FileCache$.coursier$cache$FileCache$$downloading(FileCache.scala:1032)
[error]         at lmcoursier.internal.shaded.coursier.cache.FileCache.doDownload$1(FileCache.scala:320)
[error]         at lmcoursier.internal.shaded.coursier.cache.FileCache.$anonfun$download$54(FileCache.scala:507)
[error]         at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:59)
[error]         at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:84)
[error]         at lmcoursier.internal.shaded.coursier.cache.FileCache.$anonfun$download$32(FileCache.scala:508)
[error]         at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[error]         at scala.util.Success.$anonfun$map$1(Try.scala:255)
[error]         at scala.util.Success.map(Try.scala:213)
[error]         at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[error]         at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[error]         at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[error]         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:829)
[error] lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[error] https://splunk.jfrog.io/artifactory/ext-releases-local/com/splunk/splunk/1.6.5.0/splunk-1.6.5.0.jar: download error: Caught java.net.UnknownHostException: jfrog-prod-use1-shared-virginia-main.s3.amazonaws.com (jfrog-prod-use1-shared-virginia-main.s3.amazonaws.com) while downloading https://splunk.jfrog.io/artifactory/ext-releases-local/com/splunk/splunk/1.6.5.0/splunk-1.6.5.0.jar
[error]
[error]         at lmcoursier.internal.shaded.coursier.Artifacts$.$anonfun$fetchArtifacts$14(Artifacts.scala:302)
[error]         at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
[error]         at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
[error]         at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
[error]         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:829)
[error] Caused by: lmcoursier.internal.shaded.coursier.cache.ArtifactError$DownloadError: download error: Caught java.net.UnknownHostException: jfrog-prod-use1-shared-virginia-main.s3.amazonaws.com (jfrog-prod-use1-shared-virginia-main.s3.amazonaws.com) while downloading https://splunk.jfrog.io/artifactory/ext-releases-local/com/splunk/splunk/1.6.5.0/splunk-1.6.5.0.jar
[error]         at lmcoursier.internal.shaded.coursier.cache.FileCache$.helper$2(FileCache.scala:1018)
[error]         at lmcoursier.internal.shaded.coursier.cache.FileCache$.coursier$cache$FileCache$$downloading(FileCache.scala:1032)
[error]         at lmcoursier.internal.shaded.coursier.cache.FileCache.doDownload$1(FileCache.scala:320)
[error]         at lmcoursier.internal.shaded.coursier.cache.FileCache.$anonfun$download$54(FileCache.scala:507)
[error]         at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:59)
[error]         at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:84)
[error]         at lmcoursier.internal.shaded.coursier.cache.FileCache.$anonfun$download$32(FileCache.scala:508)
[error]         at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[error]         at scala.util.Success.$anonfun$map$1(Try.scala:255)
[error]         at scala.util.Success.map(Try.scala:213)
[error]         at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[error]         at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[error]         at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[error]         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:829)
[error] Caused by: java.net.UnknownHostException: jfrog-prod-use1-shared-virginia-main.s3.amazonaws.com
[error]         at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:229)
[error]         at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[error]         at java.base/java.net.Socket.connect(Socket.java:609)
[error]         at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:305)
[error]         at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
[error]         at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
[error]         at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:508)
[error]         at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
[error]         at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
[error]         at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:373)
[error]         at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:207)
[error]         at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
[error]         at java.base/sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1071)
[error]         at java.base/sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1069)
[error]         at java.base/java.security.AccessController.doPrivileged(Native Method)
[error]         at java.base/java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:795)
[error]         at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1068)
[error]         at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:193)
[error]         at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
[error]         at java.base/sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1512)
[error]         at java.base/sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1510)
[error]         at java.base/java.security.AccessController.doPrivileged(Native Method)
[error]         at java.base/java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:795)
[error]         at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
[error]         at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
[error]         at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
[error]         at lmcoursier.internal.shaded.coursier.cache.CacheUrl$.redirectTo(CacheUrl.scala:152)
[error]         at lmcoursier.internal.shaded.coursier.cache.CacheUrl$.redirect(CacheUrl.scala:162)
[error]         at lmcoursier.internal.shaded.coursier.cache.CacheUrl$.urlConnectionMaybePartial(CacheUrl.scala:304)
[error]         at lmcoursier.internal.shaded.coursier.cache.CacheUrl$.urlConnectionMaybePartial(CacheUrl.scala:277)
[error]         at lmcoursier.internal.shaded.coursier.cache.FileCache.$anonfun$download$33(FileCache.scala:349)
[error]         at lmcoursier.internal.shaded.coursier.cache.FileCache$.$anonfun$downloading$1(FileCache.scala:998)
[error]         at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.withUrlLock(CacheLocks.scala:102)
[error]         at lmcoursier.internal.shaded.coursier.cache.FileCache$.helper$2(FileCache.scala:998)
[error]         at lmcoursier.internal.shaded.coursier.cache.FileCache$.coursier$cache$FileCache$$downloading(FileCache.scala:1032)
[error]         at lmcoursier.internal.shaded.coursier.cache.FileCache.doDownload$1(FileCache.scala:320)
[error]         at lmcoursier.internal.shaded.coursier.cache.FileCache.$anonfun$download$54(FileCache.scala:507)
[error]         at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:59)
[error]         at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:84)
[error]         at lmcoursier.internal.shaded.coursier.cache.FileCache.$anonfun$download$32(FileCache.scala:508)
[error]         at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[error]         at scala.util.Success.$anonfun$map$1(Try.scala:255)
[error]         at scala.util.Success.map(Try.scala:213)
[error]         at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[error]         at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[error]         at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[error]         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:829)
[error] (adminstpback / update) lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[error] https://splunk.jfrog.io/artifactory/ext-releases-local/com/splunk/splunk/1.6.5.0/splunk-1.6.5.0.jar: download error: Caught java.net.UnknownHostException: jfrog-prod-use1-shared-virginia-main.s3.amazonaws.com (jfrog-prod-use1-shared-virginia-main.s3.amazonaws.com) while downloading https://splunk.jfrog.io/artifactory/ext-releases-local/com/splunk/splunk/1.6.5.0/splunk-1.6.5.0.jar
[error] (stats / update) lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[error] https://splunk.jfrog.io/artifactory/ext-releases-local/com/splunk/splunk/1.6.5.0/splunk-1.6.5.0.jar: download error: Caught java.net.UnknownHostException: jfrog-prod-use1-shared-virginia-main.s3.amazonaws.com (jfrog-prod-use1-shared-virginia-main.s3.amazonaws.com) while downloading https://splunk.jfrog.io/artifactory/ext-releases-local/com/splunk/splunk/1.6.5.0/splunk-1.6.5.0.jar
[error] Total time: 42 s, completed 21 mars 2023 à 18:21:26
````

**Comment by SethTisue** [comment]
It seems extremely doubtful here — unless further evidence is offered — that the root cause here would be a bug in sbt, so I'm changing it to a discussion in case anyone wants to offer troubleshooting assistance. (Our issue tracker is a bug tracker, not a support forum.)
