### ISSUE TITLE
Checksum error under QEMU on Arm64

### ISSUE THREAD

**Issue by keynmol** [sbt/sbt#7204]
## steps

On Linux, you need docker-multiplatform set up (https://docs.docker.com/build/building/multi-platform/)

On Mac, you can just run the reproduction without any extra steps

Take this Dockerfile:

```Dockerfile
FROM eclipse-temurin:17-focal
WORKDIR /sources
RUN apt update && apt install wget
RUN mkdir project && echo 'addSbtPlugin("com.dwijnand" % "sbt-dynver" % "4.1.1")' > project/plugins.sbt
RUN wget https://raw.githubusercontent.com/sbt/sbt/1.9.x/sbt && chmod +x sbt
RUN ./sbt update
```

Try to build it:

```
docker build --platform linux/arm64 . -t test-sbt-arm64
```

## problem

Build fails with

```
 RUN ./sbt update:
#8 0.306 downloading sbt launcher 1.8.0
#8 1.037 copying runtime jar...
#8 5.960 [info] [launcher] getting org.scala-sbt sbt 1.8.0  (this may take some time)...
#8 14.88 [info] [launcher] getting Scala 2.12.17 (for sbt)...
#8 15.69 [info] Updated file /sources/project/build.properties: set sbt.version to 1.8.0
#8 15.71 [info] welcome to sbt 1.8.0 (Eclipse Adoptium Java 17.0.6)
#8 17.32 [info] loading settings for project sources-build from plugins.sbt ...
#8 17.91 [info] loading project definition from /sources/project
#8 21.49 [warn]
#8 21.49 [warn]         Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
#8 21.50 [warn]                 com.dwijnand:sbt-dynver:4.1.1 (sbtVersion=1.0, scalaVersion=2.12)
#8 21.50 [warn]
#8 21.50 [warn]         Note: Unresolved dependencies path:
#8 21.53 [error] sbt.librarymanagement.ResolveException: Error downloading com.dwijnand:sbt-dynver;sbtVersion=1.0;scalaVersion=2.12:4.1.1
#8 21.53 [error]   Not found
#8 21.53 [error]   Not found
#8 21.53 [error]   not found: https://repo1.maven.org/maven2/com/dwijnand/sbt-dynver_2.12_1.0/4.1.1/sbt-dynver-4.1.1.pom
#8 21.53 [error]   not found: /root/.ivy2/localcom.dwijnand/sbt-dynver/scala_2.12/sbt_1.0/4.1.1/ivys/ivy.xml
#8 21.53 [error]   checksum format error: /root/.cache/coursier/v1/https/repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.dwijnand/sbt-dynver/scala_2.12/sbt_1.0/4.1.1/ivys/ivy.xml.sha1
#8 21.53 [error]   checksum format error: /root/.cache/coursier/v1/https/repo.typesafe.com/typesafe/ivy-releases/com.dwijnand/sbt-dynver/scala_2.12/sbt_1.0/4.1.1/ivys/ivy.xml.sha1
#8 21.53 [error]        at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:344)
#8 21.53 [error]        at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:313)
#8 21.53 [error]        at scala.util.Either$LeftProjection.map(Either.scala:573)
#8 21.53 [error]        at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:313)
#8 21.53 [error]        at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
#8 21.53 [error]        at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:59)
#8 21.53 [error]        at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
#8 21.53 [error]        at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
#8 21.53 [error]        at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
#8 21.53 [error]        at scala.util.control.Exception$Catch.apply(Exception.scala:228)
#8 21.53 [error]        at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
#8 21.53 [error]        at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
#8 21.53 [error]        at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
#8 21.53 [error]        at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
#8 21.53 [error]        at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3687)
#8 21.53 [error]        at scala.Function1.$anonfun$compose$1(Function1.scala:49)
#8 21.53 [error]        at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
#8 21.53 [error]        at sbt.std.Transform$$anon$4.work(Transform.scala:68)
#8 21.53 [error]        at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
#8 21.53 [error]        at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
#8 21.53 [error]        at sbt.Execute.work(Execute.scala:291)
#8 21.53 [error]        at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
#8 21.53 [error]        at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
#8 21.53 [error]        at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
#8 21.53 [error]        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
#8 21.53 [error]        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
#8 21.53 [error]        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
#8 21.53 [error]        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
#8 21.53 [error]        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
#8 21.53 [error]        at java.base/java.lang.Thread.run(Thread.java:833)
#8 21.54 [error] (update) sbt.librarymanagement.ResolveException: Error downloading com.dwijnand:sbt-dynver;sbtVersion=1.0;scalaVersion=2.12:4.1.1
#8 21.54 [error]   Not found
#8 21.54 [error]   Not found
#8 21.54 [error]   not found: https://repo1.maven.org/maven2/com/dwijnand/sbt-dynver_2.12_1.0/4.1.1/sbt-dynver-4.1.1.pom
#8 21.54 [error]   not found: /root/.ivy2/localcom.dwijnand/sbt-dynver/scala_2.12/sbt_1.0/4.1.1/ivys/ivy.xml
#8 21.54 [error]   checksum format error: /root/.cache/coursier/v1/https/repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.dwijnand/sbt-dynver/scala_2.12/sbt_1.0/4.1.1/ivys/ivy.xml.sha1
#8 21.54 [error]   checksum format error: /root/.cache/coursier/v1/https/repo.typesafe.com/typesafe/ivy-releases/com.dwijnand/sbt-dynver/scala_2.12/sbt_1.0/4.1.1/ivys/ivy.xml.sha1
#8 21.54 [warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
```

## expectation

Build suceeds

## notes

I have a ARM64 VM from Parallels - ~works without issue~ actually not true, I can reproduce it with _some_ plugins.

**Comment by armanbilge** [comment]
Symptom of https://github.com/sbt/sbt/issues/7202 maybe?

**Comment by keynmol** [comment]
Seems so - the checksum file is a HTML page which is consistent with sonatype having issues.
Will close until the sonatype outage is resolved

**Comment by SethTisue** [comment]
note that #7202 and the Sonatype outage are entirely separate things that just happen to be occurring at the same time
