### ISSUE TITLE
Error fetching org.scala-sbt:scripted-sbt_3:1.8.2

### ISSUE THREAD

**Issue by andrzejj0** [sbt/sbt#7208]
org.scala-sbt:scripted-sbt_3:1.8.2 is nowhere to be found

When trying to launch sbt:

```
[info] Reapplying settings...
...
[warn] sbt 0.13 shell syntax is deprecated; use slash syntax instead: Global / dumpStructure
[warn]
[warn] 	Note: Unresolved dependencies path:
[error] stack trace is suppressed; run 'last update' for the full output
[error] stack trace is suppressed; run 'last ssExtractDependencies' for the full output
[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.scala-sbt:scripted-sbt_3:1.8.2
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/org/scala-sbt/scripted-sbt_3/1.8.2/scripted-sbt_3-1.8.2.pom
[error]   not found: /Users/ajarmoniuk/.ivy2/local/org.scala-sbt/scripted-sbt_3/1.8.2/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-sbt/scripted-sbt_3/1.8.2/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/scripted-sbt_3/1.8.2/ivys/ivy.xml
[error] (ssExtractDependencies) sbt.librarymanagement.ResolveException: Error downloading org.scala-sbt:scripted-sbt_3:1.8.2
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/org/scala-sbt/scripted-sbt_3/1.8.2/scripted-sbt_3-1.8.2.pom
[error]   not found: /Users/ajarmoniuk/.ivy2/local/org.scala-sbt/scripted-sbt_3/1.8.2/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-sbt/scripted-sbt_3/1.8.2/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/scripted-sbt_3/1.8.2/ivys/ivy.xml
[error] Total time: 8 s, completed Apr 8, 2023, 9:22:14 AM
[info] shutting down sbt server
```

**Comment by andrzejj0** [comment]
Any workarounds? Some other version I could use?

```
$ sbt compile
...

[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading org.scala-sbt:scripted-sbt_3:1.8.2
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/org/scala-sbt/scripted-sbt_3/1.8.2/scripted-sbt_3-1.8.2.pom
[error]   not found: /Users/ajarmoniuk/.ivy2/local/org.scala-sbt/scripted-sbt_3/1.8.2/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-sbt/scripted-sbt_3/1.8.2/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/scripted-sbt_3/1.8.2/ivys/ivy.xml
[error]         at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:344)
[error]         at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:313)
[error]         at scala.util.Either$LeftProjection.map(Either.scala:573)
[error]         at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:313)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:59)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
[error]         at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
[error]         at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3687)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[error]         at java.base/java.lang.Thread.run(Thread.java:1589)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.scala-sbt:scripted-sbt_3:1.8.2
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/org/scala-sbt/scripted-sbt_3/1.8.2/scripted-sbt_3-1.8.2.pom
[error]   not found: /Users/ajarmoniuk/.ivy2/local/org.scala-sbt/scripted-sbt_3/1.8.2/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-sbt/scripted-sbt_3/1.8.2/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/scripted-sbt_3/1.8.2/ivys/ivy.xml
[error] Total time: 8 s, completed Apr 8, 2023, 9:31:19 AM
```

**Comment by andrzejj0** [comment]
Version 2.0.0-

**Comment by adpi2** [comment]
The `_3` in `scripted-sbt_3` looks quite suspicious. We started cross-building `scripted-sbt` with Scala 3 only very recently in some PR and released it only in alpha versions.

sbt should not need the Scala 3 version of `scripted-sbt` unless you ask it explicitly but then the version would be incorrect. Did you add this dependency to `scripted-sbt` explicitly in your build?

**Comment by adpi2** [comment]
> Version 2.0.0-

Oh, are you trying to use sbt 2.0.0-alpha version? If so, do you have any sbt plugin project in your build?

**Comment by ajarmoniuk** [comment]
```scala
ThisBuild / scalaVersion := "3.2.2"

// ...

val jettyVersion = "9.4.51.v20230217"
val mavenVersion = "3.3.9"

ThisBuild / crossPaths := false

//...

// dependencies
libraryDependencies ++= Seq(
  "org.apache.maven.plugin-tools" % "maven-plugin-annotations" % "3.8.1" % Provided,
  "org.apache.maven" % "maven-plugin-api" % "3.9.1" % Provided,
  "org.eclipse.jetty" % "jetty-client" % jettyVersion,
  "javax.inject" % "javax.inject" % "1" % Provided,

  "org.slf4j" % "slf4j-simple" % "2.0.7" % Test,
  "org.eclipse.jetty" % "jetty-server" % jettyVersion % Test,
  "org.eclipse.jetty" % "jetty-security" % jettyVersion % Test,
  "org.eclipse.jetty" % "jetty-proxy" % jettyVersion % Test,
  "org.eclipse.jetty" % "jetty-servlet" % jettyVersion % Test,
  "org.scalatest" %% "scalatest" % "3.2.15" % Test,
)
```

**Comment by ajarmoniuk** [comment]
But I think the real problem is this:

https://repo1.maven.org/maven2/org/scala-sbt/scripted-sbt_3/1.8.2/scripted-sbt_3-1.8.2.pom

returns 404

and if I remove _3:

https://repo1.maven.org/maven2/org/scala-sbt/scripted-sbt/1.8.2/

also returns 404

**Comment by andrzejj0** [comment]
Closing.
