### ISSUE TITLE
sbt sbt-version fails to create update.log due to restricted rights in windows 7

### ISSUE THREAD

**Issue by gtrsk** [sbt/sbt#722]
the exception:
java.io.FileNotFoundException: \ServerName\Home\User\MyUserName.sbt\boot\update.log (The system cannot find the path specified)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileWriter.<init>(Unknown Source)
        at xsbt.boot.Update.<init>(Checks.java:51)
        at xsbt.boot.Launch.update(Launch.scala:275)
        at xsbt.boot.Launch$$anonfun$jnaLoader$1.apply(Launch.scala:120)
        at scala.Option.getOrElse(Option.scala:108)
        at xsbt.boot.Launch.jnaLoader$2f324eef(Launch.scala:115)
        at xsbt.boot.Launch.<init>(Launch.scala:94)
        at xsbt.boot.Launcher$.apply(Launch.scala:290)
        at xsbt.boot.Launch$.apply(Launch.scala:16)
        at xsbt.boot.Boot$.runImpl(Boot.scala:31)
        at xsbt.boot.Boot$.main(Boot.scala:20)
        at xsbt.boot.Boot.main(Boot.scala)
Error during sbt execution: java.io.FileNotFoundException: \ServerName\Home\User\MyUserName.sbt\boot\update.log (The system cannot find the path specified)

I am on a LAN, where I have the rights to \MyUserName\DATA but not \MyUserName

Is there anyway I can set to boot somewhere else than \MyUsername ?

**Comment by jsuereth** [comment]
yes.  -Dsbt.boot.directory, although you may need to move the ivy cache too.

Also, sbt -Dsbt.dir=   may work as well.

**Comment by harrah** [comment]
@jsuereth is there a bug here?

**Comment by jsuereth** [comment]
Yeah, I think it's an issue with the .bat script, was missing a \ somewhere.   Probably should move this to sbt-launcher-package

**Comment by harrah** [comment]
Per @jsuereth, please open against https://github.com/sbt/sbt-launcher-package/issues.
