### ISSUE TITLE
Doc command fails with InvocationTargetException

### ISSUE THREAD

**Issue by mbovel** [sbt/sbt#7256]
## steps

I have the following directory structure:

```
├── build.sbt
├── docs
│   └── _docs
│       └── hello.md
├── project
│   └── build.properties
└── src
    └── main
        └── scala
            └── main.scala
```

with the following `build.sbt`:

```scala
name := "scaladoc-test"
scalaVersion := "3.3.1-RC1-bin-20230516-51d69e8-NIGHTLY" // same issue with "3.2.2"

Compile / doc / scalacOptions ++= Seq("-siteroot", "docs") // removing this line solves the problem
```

Project: [scaladoc-test.zip](https://github.com/sbt/sbt/files/11495536/scaladoc-test.zip).

I am on macOS 13.2.1 (22D68) with Eclipse Adoptium Java 17.

## problem

Fails with a `java.lang.reflect.InvocationTargetException` exception.

## expectation

Compiles the documentation successfully.

## logs

```
➜  ~/Desktop/scaladoc-test sbt
[info] welcome to sbt 1.8.2 (Eclipse Adoptium Java 17)
[info] loading project definition from /Users/mbovel/Desktop/scaladoc-test/project
[info] loading settings for project scaladoc-test from build.sbt ...
[info] set current project to scaladoc-test (in build file:/Users/mbovel/Desktop/scaladoc-test/)
[info] sbt server started at local:///Users/mbovel/.sbt/1.0/server/ab43f5bb402d0c1f45cf/sock
[info] started sbt server
sbt:scaladoc-test> doc
[info] compiling 1 Scala source to /Users/mbovel/Desktop/scaladoc-test/target/scala-3.3.1-RC1-bin-20230516-51d69e8-NIGHTLY/classes ...
[info] Main Scala API documentation to /Users/mbovel/Desktop/scaladoc-test/target/scala-3.3.1-RC1-bin-20230516-51d69e8-NIGHTLY/api...
[error] stack trace is suppressed; run last Compile / doc for the full output
[error] (Compile / doc) java.lang.reflect.InvocationTargetException
[error] Total time: 4 s, completed May 17, 2023, 9:53:48 AM
sbt:scaladoc-test> last Compile / doc
[info] Main Scala API documentation to /Users/mbovel/Desktop/scaladoc-test/target/scala-3.3.1-RC1-bin-20230516-51d69e8-NIGHTLY/api...
[debug] Returning already retrieved and compiled bridge: /Users/mbovel/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-sbt-bridge/3.3.1-RC1-bin-20230516-51d69e8-NIGHTLY/scala3-sbt-bridge-3.3.1-RC1-bin-20230516-51d69e8-NIGHTLY.jar.
[debug] Calling Dottydoc with arguments  (ScaladocInterface):
[debug] 	-d
[debug] 	/Users/mbovel/Desktop/scaladoc-test/target/scala-3.3.1-RC1-bin-20230516-51d69e8-NIGHTLY/api
[debug] 	-project
[debug] 	scaladoc-test
[debug] 	-siteroot
[debug] 	docs
[debug] 	-bootclasspath
[debug] 	/Users/mbovel/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.3.1-RC1-bin-20230516-51d69e8-NIGHTLY/scala3-library_3-3.3.1-RC1-bin-20230516-51d69e8-NIGHTLY.jar:/Users/mbovel/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.10/scala-library-2.13.10.jar
[debug] 	-classpath
[debug] 	dummy_f71b2d6d
[debug] 	/Users/mbovel/Desktop/scaladoc-test/target/scala-3.3.1-RC1-bin-20230516-51d69e8-NIGHTLY/classes/main$package.tasty
[debug] 	/Users/mbovel/Desktop/scaladoc-test/target/scala-3.3.1-RC1-bin-20230516-51d69e8-NIGHTLY/classes/main.tasty
[error] java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[error] 	at xsbt.DottydocRunner.run(DottydocRunner.java:65)
[error] 	at xsbt.ScaladocInterface.run(ScaladocInterface.java:11)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[error] 	at sbt.internal.inc.AnalyzingCompiler.invoke(AnalyzingCompiler.scala:329)
[error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:175)
[error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:133)
[error] 	at sbt.Doc$.$anonfun$scaladoc$1(Doc.scala:52)
[error] 	at sbt.Doc$.$anonfun$scaladoc$1$adapted(Doc.scala:40)
[error] 	at sbt.RawCompileLike$.$anonfun$prepare$1(RawCompileLike.scala:79)
[error] 	at sbt.RawCompileLike$.$anonfun$prepare$1$adapted(RawCompileLike.scala:72)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$4(RawCompileLike.scala:63)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$4$adapted(RawCompileLike.scala:61)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219
[error] 	at sbt.RawCompileLike$.$anonfun$cached$1(RawCompileLike.scala:68)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$1$adapted(RawCompileLike.scala:52)
[error] 	at sbt.Defaults$.$anonfun$docTaskSettings$4(Defaults.scala:2156
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:833)
[error] Caused by: java.lang.reflect.InvocationTargetException
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[error] 	at xsbt.DottydocRunner.run(DottydocRunner.java:61)
[error] 	at xsbt.ScaladocInterface.run(ScaladocInterface.java:11)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[error] 	at sbt.internal.inc.AnalyzingCompiler.invoke(AnalyzingCompiler.scala:329)
[error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:175)
[error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:133)
[error] 	at sbt.Doc$.$anonfun$scaladoc$1(Doc.scala:52)
[error] 	at sbt.Doc$.$anonfun$scaladoc$1$adapted(Doc.scala:40)
[error] 	at sbt.RawCompileLike$.$anonfun$prepare$1(RawCompileLike.scala:79)
[error] 	at sbt.RawCompileLike$.$anonfun$prepare$1$adapted(RawCompileLike.scala:72)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$4(RawCompileLike.scala:63)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$4$adapted(RawCompileLike.scala:61)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219
[error] 	at sbt.RawCompileLike$.$anonfun$cached$1(RawCompileLike.scala:68)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$1$adapted(RawCompileLike.scala:52)
[error] 	at sbt.Defaults$.$anonfun$docTaskSettings$4(Defaults.scala:2156
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:833)
[error] Caused by: java.util.NoSuchElementException: head of empty list
[error] 	at scala.collection.immutable.Nil$.head(List.scala:662)
[error] 	at scala.collection.immutable.Nil$.head(List.scala:661)
[error] 	at dotty.tools.scaladoc.site.common$package$.loadTemplateFile(common.scala:66)
[error] 	at dotty.tools.scaladoc.site.StaticSiteLoader.loadRecursively(StaticSiteLoader.scala:191)
[error] 	at dotty.tools.scaladoc.site.StaticSiteLoader.loadRecursively$$anonfun$1(StaticSiteLoader.scala:188)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:293)
[error] 	at dotty.tools.scaladoc.site.StaticSiteLoader.loadRecursively(StaticSiteLoader.scala:188)
[error] 	at dotty.tools.scaladoc.site.StaticSiteLoader.loadBasedOnFileSystem(StaticSiteLoader.scala:100)
[error] 	at dotty.tools.scaladoc.site.StaticSiteLoader.load$$anonfun$3(StaticSiteLoader.scala:22)
[error] 	at scala.Option.fold(Option.scala:263)
[error] 	at dotty.tools.scaladoc.site.StaticSiteLoader.load(StaticSiteLoader.scala:24)
[error] 	at dotty.tools.scaladoc.site.StaticSiteContext.staticSiteRoot$lzyINIT1(StaticSiteContext.scala:44)
[error] 	at dotty.tools.scaladoc.site.StaticSiteContext.staticSiteRoot(StaticSiteContext.scala:44)
[error] 	at dotty.tools.scaladoc.renderers.Renderer.<init>(Renderer.scala:36)
[error] 	at dotty.tools.scaladoc.renderers.HtmlRenderer.<init>(HtmlRenderer.scala:10)
[error] 	at dotty.tools.scaladoc.Scaladoc$.run(Scaladoc.scala:237)
[error] 	at dotty.tools.scaladoc.Scaladoc$.run$$anonfun$1(Scaladoc.scala:68)
[error] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15
[error] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10
[error] 	at scala.Option.map(Option.scala:242)
[error] 	at dotty.tools.scaladoc.Scaladoc$.run(Scaladoc.scala:72)
[error] 	at dotty.tools.dottydoc.Main$.process(Main.scala:25)
[error] 	at dotty.tools.dottydoc.Main.process(Main.scala)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[error] 	at xsbt.DottydocRunner.run(DottydocRunner.java:61)
[error] 	at xsbt.ScaladocInterface.run(ScaladocInterface.java:11)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[error] 	at sbt.internal.inc.AnalyzingCompiler.invoke(AnalyzingCompiler.scala:329)
[error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:175)
[error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:133)
[error] 	at sbt.Doc$.$anonfun$scaladoc$1(Doc.scala:52)
[error] 	at sbt.Doc$.$anonfun$scaladoc$1$adapted(Doc.scala:40)
[error] 	at sbt.RawCompileLike$.$anonfun$prepare$1(RawCompileLike.scala:79)
[error] 	at sbt.RawCompileLike$.$anonfun$prepare$1$adapted(RawCompileLike.scala:72)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$4(RawCompileLike.scala:63)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$4$adapted(RawCompileLike.scala:61)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219
[error] 	at sbt.RawCompileLike$.$anonfun$cached$1(RawCompileLike.scala:68)
[error] 	at sbt.RawCompileLike$.$anonfun$cached$1$adapted(RawCompileLike.scala:52)
[error] 	at sbt.Defaults$.$anonfun$docTaskSettings$4(Defaults.scala:2156
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by adpi2** [comment]
This exception is thrown by Dotty: https://github.com/lampepfl/dotty/blob/51d69e85e1f7c31459b57fe747a6d2ae7d1d3ab7/sbt-bridge/src/xsbt/DottydocRunner.java#L65

Would be good to know the target of the `InvocationTargetException`, is it coming from dotty or Zinc?

**Comment by mbovel** [comment]
I completed the logs in the issue's description with the whole trace. The root cause is actually:

```
[error] Caused by: java.util.NoSuchElementException: head of empty list
[error] 	at scala.collection.immutable.Nil$.head(List.scala:662)
[error] 	at scala.collection.immutable.Nil$.head(List.scala:661)
[error] 	at dotty.tools.scaladoc.site.common$package$.loadTemplateFile(common.scala:66)
[error] 	at dotty.tools.scaladoc.site.StaticSiteLoader.loadRecursively(StaticSiteLoader.scala:191)
[error] 	at dotty.tools.scaladoc.site.StaticSiteLoader.loadRecursively$$anonfun$1(StaticSiteLoader.scala:188)
```

**Comment by mbovel** [comment]
So this is not an SBT issue.

~Seems to be a problem when there is no YAML file to define items in the sidebar.~ I'll try to produce in Dotty directly.

**Comment by mbovel** [comment]
The problem was due to `hello.md` being empty.

Fixed by https://github.com/lampepfl/dotty/pull/17527.
