### ISSUE TITLE
scala-cli's repositories.default config interferes with sbt's repository configuration

### ISSUE THREAD

**Issue by dccorona** [sbt/sbt#7258]
I can't really figure out the root cause here so I don't know if it is more appropriate to flag this issue to scala-cli or sbt, so apologies if I got it wrong - but it seems like sbt should not allow another cli tool to interfere with its correctness, so I flagged the issue here.

## steps

I was trying to set up a sample project, and actually discovered that it even breaks the launcher, so no project is even needed to reproduce the issue. The example below reproduces using SBT 1.9.0-RC3 just because that contains the `init` command, but you can get the same issue with a released version, i.e. 1.8.0

First, install sbt and [scala-cli](https://scala-cli.virtuslab.org/install/)

```
> scala-cli --power config repositories.default http://not.a.repo.com
> sbt -Dsbt.version=1.9.0-RC3 init
[error] sbt.librarymanagement.ResolveException: Error downloading org.scala-sbt:sbt:1.9.0-RC3
[error]   checksum format error: /Users/USERNAME/Library/Caches/Coursier/v1/http/not.a.repo.com/org/scala-sbt/sbt/1.9.0-RC3/sbt-1.9.0-RC3.pom.sha1
[error] Error downloading org.scala-lang:scala-library:2.12.17
[error]   checksum format error: /Users/USERNAME/Library/Caches/Coursier/v1/http/not.a.repo.com/org/scala-lang/scala-library/2.12.17/scala-library-2.12.17.pom.sha1
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:344)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:313)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:313)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:59)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3800)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[error] 	at java.base/java.lang.Thread.run(Thread.java:1623)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.scala-sbt:sbt:1.9.0-RC3
[error]   checksum format error: /Users/USERNAME/Library/Caches/Coursier/v1/http/not.a.repo.com/org/scala-sbt/sbt/1.9.0-RC3/sbt-1.9.0-RC3.pom.sha1
[error] Error downloading org.scala-lang:scala-library:2.12.17
[error]   checksum format error: /Users/USERNAME/Library/Caches/Coursier/v1/http/not.a.repo.com/org/scala-lang/scala-library/2.12.17/scala-library-2.12.17.pom.sha1
```

You can "repair" your environment after running this test by running:

```
scala-cli --power config --unset repositories.default
```

## problem

When the `repositories.default` setting is set in scala-cli, SBT uses that repository instead of whatever is configured for the build (this overrides both the defaults, and settings passed through via mechanisms like sbt.boot.properties)

## expectation

scala-cli repository configuration should have no bearing on what repositories are used by sbt, because they are different tools

## notes

If it's relevant - I discovered the issue on a Mac (macOS 13.3.1 (a))

**Comment by booniepepper** [comment]
I experienced the same on Ubuntu 20.04

**Comment by bitcompass** [comment]
Hi, @eed3si9n 
As a new contributor, I want to work on this issue.
If this issue still available, could you assign this to me?

**Comment by eed3si9n** [comment]
@bitcompass I generally avoid assigning tasks to new contributors, since we get varying PRs from the miners. Do you have a general outline of how this issue should be tackled? As far as I can tell, this seems to be more to do with scala-cli and Coursier's problem.

Also please check out our [Contributor's Guildeline](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) and:
1. Make sure you can reproduce the problem and the fix manually (we regularly block folks who send speculative PRs)
2. Include tests for the change
3. Follow our AI assisted contributions guideline
4. Multiple contributors might work on this issue in parallel
5. Generally we recommend getting CI to pass on a forked repo before sending a pull request
6. Sign Scala CLA <https://contribute.akka.io/contribute/cla/scala>
