### ISSUE TITLE
SBT (1.3.13) Compilation Issue- java.lang.NoClassDefFoundError: xsbt/DelegatingReporter$PositionImpl$

### ISSUE THREAD

**Issue by Roohein** [sbt/sbt#7270]
Scala Version - 2.13.0
JAVA Version- Corretto-8.282.08.1

I am facing Issues While compiling SBT 
ERROR-

<details>

<summary>

```scala
[error] ## Exception when compiling 228 sources to /target/scala-2.13/classes
[error] java.lang.NoClassDefFoundError: xsbt/DelegatingReporter$PositionImpl$
[error] xsbt.DelegatingReporter$.convert(DelegatingReporter.scala:149)
```
</summary>

```scala
[error] ## Exception when compiling 228 sources to /target/scala-2.13/classes
[error] java.lang.NoClassDefFoundError: xsbt/DelegatingReporter$PositionImpl$
[error] xsbt.DelegatingReporter$.convert(DelegatingReporter.scala:149)
[error] xsbt.DelegatingReporter.info0(DelegatingReporter.scala:181)
[error] scala.reflect.internal.Reporter.error(Reporting.scala:92)
[error] scala.tools.nsc.backend.jvm.PostProcessorFrontendAccess$PostProcessorFrontendAccessImpl$directBackendReporting$.$anonfun$error$1(PostProcessorFrontendAccess.scala:244)
[error] scala.tools.nsc.backend.jvm.PostProcessorFrontendAccess$PostProcessorFrontendAccessImpl$directBackendReporting$.error(PostProcessorFrontendAccess.scala:32)
[error] scala.tools.nsc.backend.jvm.PostProcessorFrontendAccess$BufferingBackendReporting$ReportError.relay(PostProcessorFrontendAccess.scala:146)
[error] scala.tools.nsc.backend.jvm.PostProcessorFrontendAccess$BufferingBackendReporting.relayReports(PostProcessorFrontendAccess.scala:130)
[error] scala.tools.nsc.backend.jvm.GeneratedClassHandler$WritingClassHandler.$anonfun$complete$2(GeneratedClassHandler.scala:165)
[error] scala.tools.nsc.backend.jvm.GeneratedClassHandler$WritingClassHandler.complete(GeneratedClassHandler.scala:162)
[error] scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.$anonfun$run$1(GenBCode.scala:79)
[error] scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.run(GenBCode.scala:76)
[error] scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1510)
[error] scala.tools.nsc.Global$Run.compileUnits(Global.scala:1494)
[error] scala.tools.nsc.Global$Run.compileSources(Global.scala:1486)
[error] scala.tools.nsc.Global$Run.compile(Global.scala:1615)
[error] xsbt.CachedCompiler0.run(CompilerInterface.scala:153)
[error] xsbt.CachedCompiler0.run(CompilerInterface.scala:125)
[error] xsbt.CompilerInterface.run(CompilerInterface.scala:39)
[error] sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] java.lang.reflect.Method.invoke(Method.java:498)
[error] sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:122)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:95)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:91)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:186)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3$adapted(MixedAnalyzingCompiler.scala:77)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:215)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:77)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:146)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:343)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:343)
[error] sbt.internal.inc.Incremental$.doCompile(Incremental.scala:120)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:100)
[error] sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:180)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:98)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:102)
[error] sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:155)
[error] sbt.internal.inc.Incremental$.compile(Incremental.scala:92)
[error] sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:75)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:348)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:301)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:168)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:248)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:74)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1765)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1738)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] sbt.Execute.work(Execute.scala:290)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] java.lang.Thread.run(Thread.java:748)
[error]            
[error] java.lang.NoClassDefFoundError: xsbt/DelegatingReporter$PositionImpl$
[error]         at xsbt.DelegatingReporter$.convert(DelegatingReporter.scala:149)
[error]         at xsbt.DelegatingReporter.info0(DelegatingReporter.scala:181)
[error]         at scala.reflect.internal.Reporter.error(Reporting.scala:92)
[error]         at scala.tools.nsc.backend.jvm.PostProcessorFrontendAccess$PostProcessorFrontendAccessImpl$directBackendReporting$.$anonfun$error$1(PostProcessorFrontendAccess.scala:244)
[error]         at scala.tools.nsc.backend.jvm.PostProcessorFrontendAccess$PostProcessorFrontendAccessImpl$directBackendReporting$.error(PostProcessorFrontendAccess.scala:32)
[error]         at scala.tools.nsc.backend.jvm.PostProcessorFrontendAccess$BufferingBackendReporting$ReportError.relay(PostProcessorFrontendAccess.scala:146)
[error]         at scala.tools.nsc.backend.jvm.PostProcessorFrontendAccess$BufferingBackendReporting.relayReports(PostProcessorFrontendAccess.scala:130)
[error]         at scala.tools.nsc.backend.jvm.GeneratedClassHandler$WritingClassHandler.$anonfun$complete$2(GeneratedClassHandler.scala:165)
[error]         at scala.tools.nsc.backend.jvm.GeneratedClassHandler$WritingClassHandler.complete(GeneratedClassHandler.scala:162)
[error]         at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.$anonfun$run$1(GenBCode.scala:79)
[error]         at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.run(GenBCode.scala:76)
[error]         at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1510)
[error]         at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1494)
[error]         at scala.tools.nsc.Global$Run.compileSources(Global.scala:1486)
[error]         at scala.tools.nsc.Global$Run.compile(Global.scala:1615)
[error]         at xsbt.CachedCompiler0.run(CompilerInterface.scala:153)
[error]         at xsbt.CachedCompiler0.run(CompilerInterface.scala:125)
[error]         at xsbt.CompilerInterface.run(CompilerInterface.scala:39)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
[error]         at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:122)
[error]         at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:95)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:91)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:186)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3$adapted(MixedAnalyzingCompiler.scala:77)
[error]         at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:215)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:77)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:146)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:343)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:343)
[error]         at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:120)
[error]         at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:100)
[error]         at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:180)
[error]         at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:98)
[error]         at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:102)
[error]         at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:155)
[error]         at sbt.internal.inc.Incremental$.compile(Incremental.scala:92)
[error]         at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:75)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:348)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:301)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:168)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:248)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:74)
[error]         at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1765)
[error]         at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1738)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] Caused by: java.lang.ClassNotFoundException: xsbt.DelegatingReporter$PositionImpl$
[error]         at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[error]         at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[error]         at xsbt.DelegatingReporter$.convert(DelegatingReporter.scala:149)
[error]         at xsbt.DelegatingReporter.info0(DelegatingReporter.scala:181)
[error]         at scala.reflect.internal.Reporter.error(Reporting.scala:92)
[error]         at scala.tools.nsc.backend.jvm.PostProcessorFrontendAccess$PostProcessorFrontendAccessImpl$directBackendReporting$.$anonfun$error$1(PostProcessorFrontendAccess.scala:244)
[error]         at scala.tools.nsc.backend.jvm.PostProcessorFrontendAccess$PostProcessorFrontendAccessImpl$directBackendReporting$.error(PostProcessorFrontendAccess.scala:32)
[error]         at scala.tools.nsc.backend.jvm.PostProcessorFrontendAccess$BufferingBackendReporting$ReportError.relay(PostProcessorFrontendAccess.scala:146)
[error]         at scala.tools.nsc.backend.jvm.PostProcessorFrontendAccess$BufferingBackendReporting.relayReports(PostProcessorFrontendAccess.scala:130)
[error]         at scala.tools.nsc.backend.jvm.GeneratedClassHandler$WritingClassHandler.$anonfun$complete$2(GeneratedClassHandler.scala:165)
[error]         at scala.tools.nsc.backend.jvm.GeneratedClassHandler$WritingClassHandler.complete(GeneratedClassHandler.scala:162)
[error]         at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.$anonfun$run$1(GenBCode.scala:79)
[error]         at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.run(GenBCode.scala:76)
[error]         at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1510)
[error]         at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1494)
[error]         at scala.tools.nsc.Global$Run.compileSources(Global.scala:1486)
[error]         at scala.tools.nsc.Global$Run.compile(Global.scala:1615)
[error]         at xsbt.CachedCompiler0.run(CompilerInterface.scala:153)
[error]         at xsbt.CachedCompiler0.run(CompilerInterface.scala:125)
[error]         at xsbt.CompilerInterface.run(CompilerInterface.scala:39)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
[error]         at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:122)
[error]         at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:95)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:91)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:186)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3$adapted(MixedAnalyzingCompiler.scala:77)
[error]         at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:215)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:77)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:146)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:343)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:343)
[error]         at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:120)
[error]         at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:100)
[error]         at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:180)
[error]         at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:98)
[error]         at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:102)
[error]         at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:155)
[error]         at sbt.internal.inc.Incremental$.compile(Incremental.scala:92)
[error]         at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:75)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:348)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:301)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:168)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:248)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:74)
[error]         at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1765)
[error]         at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1738)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (Compile / compileIncremental) java.lang.NoClassDefFoundError: xsbt/DelegatingReporter$PositionImpl$
```

</details>

This issue initially occurred  after upgrading the SBT version of my project. In an attempt to resolve it, I undertook the following steps:

1. Deleted the target file and retried the operation.
2. Completely reinstalled SBT and Java, starting from a clean slate.
3. Other Solutions available  online.
However, none of these measures proved effective in resolving the issue.

SBT(1.3.13) Installed using .tgz file available on SBT Download page and the followed these commands
`tar -xvzf sbt-1.3.13.tgz`
`cd sbt-1.3.13/bin`
`./sbt`

**Comment by SethTisue** [comment]
2.13.0 and 1.3.13 are very old versions — is the problem reproducible using 2.13.10 and 1.8.3?

**Comment by Roohein** [comment]
I have updated Scala version -2.13.0 and SBT version to 1.8.3 Still facing same issues.
P.S I am using MAC M1

**Comment by mkurz** [comment]
Is that a Play Framework project?

**Comment by Roohein** [comment]
yes

**Comment by mkurz** [comment]
Which Play version are you using or were you using before / after the sbt upgrade?

**Comment by Roohein** [comment]
build.properties -> sbt.version=1.3.13
 plugins.sbt ->
 addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.8.8")
addSbtPlugin("org.scoverage" %% "sbt-scoverage" % "2.0.1")

play version ->2.8.8

**Comment by mkurz** [comment]
Try:
* sbt 1.8.2
* Play 2.8.19

Make sure you removed `target` folders.

**Comment by eed3si9n** [comment]
Could you provide reproduction steps so we can reproduce your problem on _our computers_? At this point, I'd assume that using the latest version of Scala version would fix this issue. Please see https://www.scala-sbt.org/community.html on where you can get help regarding sbt.
