### ISSUE TITLE
`sbtPluginPublishLegacyMavenStyle := false` and scripted test

### ISSUE THREAD

**Issue by adpi2** [sbt/sbt#7285]
### Discussed in https://github.com/sbt/sbt/discussions/7277

<div type='discussions-op-text'>

<sup>Originally posted by **xuwei-k** June  3, 2023</sup>
Could not resolve local sbt plugin if `sbtPluginPublishLegacyMavenStyle := false`.
Is there any solution with keep `sbtPluginPublishLegacyMavenStyle := false` ? Should we use local maven repo? 🤔 

- https://github.com/xuwei-k/sbtPluginPublishLegacyMavenStyle-false-scripted-test/actions/runs/5162314405/jobs/9299928807
- https://github.com/xuwei-k/sbtPluginPublishLegacyMavenStyle-false-scripted-test/commit/518f6e474b55980de488e16342e9b2690d9a9675

```
[info] 	delivering ivy file to /home/runner/work/sbtPluginPublishLegacyMavenStyle-false-scripted-test/sbtPluginPublishLegacyMavenStyle-false-scripted-test/target/scala-2.12/sbt-1.0/ivy-0.1.0-SNAPSHOT.xml
[info] 	published foo_2.12_1.0 to /home/runner/.ivy2/local/com.example/foo/scala_2.12/sbt_1.0/0.1.0-SNAPSHOT/jars/foo_2.12_1.0.jar
[info] 	published foo_2.12_1.0 to /home/runner/.ivy2/local/com.example/foo/scala_2.12/sbt_1.0/0.1.0-SNAPSHOT/srcs/foo_2.12_1.0-sources.jar
[info] 	published foo_2.12_1.0 to /home/runner/.ivy2/local/com.example/foo/scala_2.12/sbt_1.0/0.1.0-SNAPSHOT/docs/foo_2.12_1.0-javadoc.jar
[info] 	published foo_2.12_1.0 to /home/runner/.ivy2/local/com.example/foo/scala_2.12/sbt_1.0/0.1.0-SNAPSHOT/poms/foo_2.12_1.0.pom
[info] 	published ivy to /home/runner/.ivy2/local/com.example/foo/scala_2.12/sbt_1.0/0.1.0-SNAPSHOT/ivys/ivy.xml
```

```
[info] [error] lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[info] [error] file:///home/runner/.ivy2/local/com.example/foo/scala_2.12/sbt_1.0/0.1.0-SNAPSHOT/jars/foo.jar: not found: /home/runner/.ivy2/local/com.example/foo/scala_2.12/sbt_1.0/0.1.0-SNAPSHOT/jars/foo.jar
[info] [error] 
[info] [error] 	at lmcoursier.internal.shaded.coursier.Artifacts$.$anonfun$fetchArtifacts$9(Artifacts.scala:365)
[info] [error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
```
</div>

**Comment by adpi2** [comment]
Unfortunately this bug is not specific to `publishLocal`. The same can happen if I use `publish` to an Ivy repository with `publishMavenStyle := true` and `sbtPluginPublishLegacyMavenStyle := false`. While there is probably no good reason to do that, nothing prevents the user from doing it.

**Comment by adpi2** [comment]
Of actually it seems not possible to `publish` to an Ivy repository with `publishMavenStyle := true`. `publishLocal` is really a weird things that mixes Maven style and Ivy style. So we are good with #7286  to fix the issue.
