### ISSUE TITLE
dependencyUpdates on large sbt project fails wit out of memory

### ISSUE THREAD

**Issue by jmvandebron** [sbt/sbt#7321]
## steps

using sbt 1.8.2 (same result for 1.9.0), on an sbt project with about 180 sub projects, the `dependencyUpodates` command (from `addSbtPlugin("org.jmotor.sbt" % "sbt-dependency-updates" % "1.2.7")`) fails when run on the root project.
Our sbt process typically needs 6Gb heap to operate (compile, test, and other commands), but this command fails even when providing 8Gb.

Our monorepo consists of about 100 microservices/jobs/applications that use shared code from about 70 modules (sub projects) that have a lot of `dependsOn` relationships. All of them are Scala modules.
We have a steady growth of modules, adding one or a few each month.  (we are working on breaking that trend, and we will be splitting the codebase into more manageable parts in the near future, but at the moment we're stuck with this mega-monorepo setup).

## problem

We recently added a new resolver (S3 resolver, using `addSbtPlugin("com.frugalmechanic" % "fm-sbt-s3-resolver" % "0.21.0")`), which leads to extra calls being made for each dependency

I suspect there are too many threads being created for the (parallel) verification of dependency versions, and/or results from earlier queries are not reused but are being fetched again.

## expectation

`dependencyUpdates` on the root project should work and report on all 180+ sub projects

## notes

The (partial) error output for 1.8.2:
```
...
[info] ---------------------------------- Global Plugins ----------------------------------
[success   ] com.github.sbt:sbt-git:2.0.1 √
[info] ----------------------------------- Dependencies -----------------------------------
[expired   ] org.scala-lang:scala-library:2.12.17 ---> 2.13.11
[expired   ] io.kamon:kanela-agent:1.0.11 ---> 1.0.17
[79.085s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 2048k, guardsize: 4k, detached.
[79.085s][warning][os,thread] Failed to start the native thread for java.lang.Thread "OkHttp Dispatcher"
[79.085s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 2048k, guardsize: 4k, detached.
[79.085s][warning][os,thread] Failed to start the native thread for java.lang.Thread "OkHttp Dispatcher"
[79.085s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 2048k, guardsize: 4k, detached.
[79.085s][warning][os,thread] Failed to start the native thread for java.lang.Thread "OkHttp Dispatcher"
[79.085s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 2048k, guardsize: 4k, detached.
java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
[79.085s][warning][os,thread] Failed to start the native thread for java.lang.Thread "OkHttp Dispatcher"
	at java.base/java.lang.Thread.start0(Native Method)
	at java.base/java.lang.Thread.start(Thread.java:802)
	at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:945)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1364)
	at okhttp3.internal.connection.RealCall$AsyncCall.executeOn(RealCall.kt:514)
	at okhttp3.Dispatcher.promoteAndExecute(Dispatcher.kt:184)
	at okhttp3.Dispatcher.enqueue$okhttp(Dispatcher.kt:125)
	at okhttp3.internal.connection.RealCall.enqueue(RealCall.kt:168)
	at org.jmotor.tools.Conversions$OkHttpCallWrapper.toFuture(Conversions.scala:16)
	at org.jmotor.artifact.metadata.loader.MavenRepoMetadataLoader.getVersions(MavenRepoMetadataLoader.scala:38)
	at org.jmotor.sbt.metadata.MetadataLoaderGroup.$anonfun$getVersions$1(MetadataLoaderGroup.scala:28)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)

	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)

	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at org.jmotor.sbt.metadata.MetadataLoaderGroup.getVersions(MetadataLoaderGroup.scala:26)
	at org.jmotor.sbt.service.VersionServiceImpl.$anonfun$check$2(VersionServiceImpl.scala:54)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)[79.134s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 2048k, guardsize: 4k, detached.

[79.149s][warning][os,thread] Failed to start the native thread for java.lang.Thread "OkHttp TaskRunner"
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
	at java.base/java.lang.Thread.start0(Native Method)
	at java.base/java.lang.Thread.start(Thread.java:802)
	at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:945)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1364)
	at okhttp3.internal.connection.RealCall$AsyncCall.executeOn(RealCall.kt:514)
	at okhttp3.Dispatcher.promoteAndExecute(Dispatcher.kt:184)
	at okhttp3.Dispatcher.enqueue$okhttp(Dispatcher.kt:125)
	at okhttp3.internal.connection.RealCall.enqueue(RealCall.kt:168)
[79.149s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 2048k, guardsize: 4k, detached.
	at org.jmotor.tools.Conversions$OkHttpCallWrapper.toFuture(Conversions.scala:16)
	at org.jmotor.artifact.metadata.loader.MavenRepoMetadataLoader.getVersions(MavenRepoMetadataLoader.scala:38)
	at org.jmotor.sbt.metadata.MetadataLoaderGroup.$anonfun$getVersions$1(MetadataLoaderGroup.scala:28)
[79.149s][warning][os,thread] Failed to start the native thread for java.lang.Thread "OkHttp TaskRunner"
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
[79.149s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 2048k, guardsize: 4k, detached.
[79.149s][warning][os,thread] Failed to start the native thread for java.lang.Thread "OkHttp TaskRunner"
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at org.jmotor.sbt.metadata.MetadataLoaderGroup.getVersions(MetadataLoaderGroup.scala:26)
	at org.jmotor.sbt.service.VersionServiceImpl.$anonfun$check$2(VersionServiceImpl.scala:54)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
[79.150s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 2048k, guardsize: 4k, detached.
[79.150s][warning][os,thread] Failed to start the native thread for java.lang.Thread "OkHttp TaskRunner"
```

Output for 1.9.0:
```
...
                                             searchService
[info] ---------------------------------- Global Plugins ----------------------------------
[success   ] com.github.sbt:sbt-git:2.0.1 √
[info] ----------------------------------- Dependencies -----------------------------------
[expired   ] org.scala-lang:scala-library:2.12.17 ---> 2.13.11
[expired   ] io.kamon:kanela-agent:1.0.11 ---> 1.0.17
[expired   ] com.sksamuel.elastic4s:elastic4s-client-esjava:7.17.2 ---> 8.8.0
[expired   ] org.keycloak:keycloak-core:18.0.2 ---> 21.1.1
[expired   ] org.keycloak:keycloak-adapter-core:18.0.2 ---> 21.1.1
[expired   ] org.jboss.logging:jboss-logging:3.5.0.Final ---> 3.5.1.Final
[expired   ] org.apache.httpcomponents:httpclient:4.5.13 ---> 4.5.14
[124.146s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 2048k, guardsize: 4k, detached.
[124.146s][warning][os,thread] Failed to start the native thread for java.lang.Thread "OkHttp Dispatcher"
[124.146s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 2048k, guardsize: 4k, detached.
[124.146s][warning][os,thread] Failed to start the native thread for java.lang.Thread "OkHttp Dispatcher"
[124.146s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 2048k, guardsize: 4k, detached.
[124.146s][warning][os,thread] Failed to start the native thread for java.lang.Thread "OkHttp Dispatcher"
java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
	at java.base/java.lang.Thread.start0(Native Method)
	at java.base/java.lang.Thread.start(Thread.java:802)
	at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:945)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1364)
	at okhttp3.internal.connection.RealCall$AsyncCall.executeOn(RealCall.kt:514)
	at okhttp3.Dispatcher.promoteAndExecute(Dispatcher.kt:184)
	at okhttp3.Dispatcher.enqueue$okhttp(Dispatcher.kt:125)
	at okhttp3.internal.connection.RealCall.enqueue(RealCall.kt:168)
	at org.jmotor.tools.Conversions$OkHttpCallWrapper.toFuture(Conversions.scala:16)
	at org.jmotor.artifact.metadata.loader.MavenRepoMetadataLoader.getVersions(MavenRepoMetadataLoader.scala:38)
	at org.jmotor.sbt.metadata.MetadataLoaderGroup.$anonfun$getVersions$1(MetadataLoaderGroup.scala:28)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at org.jmotor.sbt.metadata.MetadataLoaderGroup.getVersions(MetadataLoaderGroup.scala:26)
	at org.jmotor.sbt.service.VersionServiceImpl.$anonfun$check$2(VersionServiceImpl.scala:54)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
...
```

**Comment by jmvandebron** [comment]
I now realise that this could be a problem that's confined to the `sbt-dependency-update` plugin, and I am investigating different scenario's. When I do a `clean` and then a `Test/compile` to force building the entire monorepo, there are sporadic bursts of messages about leaked connections (see below).

This might be related to the fact that we have a resolver for internally published artefacts (that has nothing except our internal libraries), and the default resolvers for everything else (that do not know about our internal libraries). Could this be causing a lot of 'not found' results when interacting with either resolver, and is there perhaps some missing `close`/cleanup of failed requests?

```
...
Jun 26, 2023 8:52:08 AM okhttp3.internal.platform.Platform log
WARNING: A connection to https://repo1.maven.org/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
Jun 26, 2023 8:52:08 AM okhttp3.internal.platform.Platform log
WARNING: A connection to https://repo1.maven.org/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
Jun 26, 2023 8:52:08 AM okhttp3.internal.platform.Platform log
WARNING: A connection to https://repo1.maven.org/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
Jun 26, 2023 8:52:08 AM okhttp3.internal.platform.Platform log
WARNING: A connection to https://repo1.maven.org/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
Jun 26, 2023 8:52:08 AM okhttp3.internal.platform.Platform log
WARNING: A connection to https://oss.sonatype.org/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
Jun 26, 2023 8:52:08 AM okhttp3.internal.platform.Platform log
WARNING: A connection to https://oss.sonatype.org/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
Jun 26, 2023 8:52:08 AM okhttp3.internal.platform.Platform log
WARNING: A connection to https://oss.sonatype.org/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
Jun 26, 2023 8:52:08 AM okhttp3.internal.platform.Platform log
WARNING: A connection to https://oss.sonatype.org/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
Jun 26, 2023 8:52:08 AM okhttp3.internal.platform.Platform log
WARNING: A connection to https://oss.sonatype.org/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
...
```

**Comment by jmvandebron** [comment]
Removing a snapshot resolver (which we only sporadically needed) seems to resolve - pun indented ;) -  the issue. We had a `lazy val globalResolvers = Resolver.sonatypeOssRepos("snapshots")`
and `ThisBuild / resolvers += globalResolvers` in our build.sbt.
Removing it gets rid of the OOM.

The underlying question remains open: why does having one or more resolvers that don't host many of the dependencies, lead to an OOM when performing an update and/or other commands that are related to dependencies.

**Comment by eed3si9n** [comment]
Could you please contact https://github.com/aiyanbo/sbt-dependency-updates first? From what I can tell it seems to be an issue created mostly via two plugins that you're using combined with a large-ish number of subprojects.

**Comment by jmvandebron** [comment]
I've created a ticket there (https://github.com/aiyanbo/sbt-dependency-updates/issues/24).
