### ISSUE TITLE
Stack traces missing in batch mode, only when using `stream.value.log`

### ISSUE THREAD

**Issue by dragos** [sbt/sbt#7322]
## steps

I have minimized the issue to this crashing task (note the commented line)

```
val hello = taskKey[Unit]("blah")

hello := {
    // val log = streams.value.log
    throw new RuntimeException("boom!")
}
```

When ran on the CLI, in batch mode, it correctly displays the stack trace

<details>

```
❯ sbt hello
[info] welcome to sbt 1.9.1 (BellSoft Java 17.0.4)
[info] loading global plugins from /Users/idragos/.sbt/1.0/plugins
...
[info] set current project to test-project (in build file:/Users/idragos/workspace/discoveries/sbt-task-progress/test-project/)
[error] java.lang.RuntimeException: boom!
[error] 	at $fc3ca1ba05bef2f053bb$.$anonfun$$sbtdef$1(/Users/idragos/workspace/discoveries/sbt-task-progress/test-project/build.sbt:51)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.Execute.work(Execute.scala:292)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:833)
[error] (hello) boom!
[error] Total time: 0 s, completed 27 Jun 2023, 14:19:56
```
</details>

## problem

When uncommenting the streams.value.log line, the stack trace is missing (only one [error] line is printed):

```
❯ sbt hello
[info] welcome to sbt 1.9.1 (BellSoft Java 17.0.4)
[info] loading global plugins from /Users/idragos/.sbt/1.0/plugins
...
[info] set current project to test-project (in build file:/Users/idragos/workspace/discoveries/sbt-task-progress/test-project/)
[error] Total time: 0 s, completed 27 Jun 2023, 14:20:06
```

This seems to be specific to `streams.value`, replacing that with another setting dependency such as `scalaVersion` doesn't change the behavior (stack trace still displayed).

## expectation

I'd expect the behavior to be consistent regardless of what task dependencies I have.

I think this must be related to `traceLevel` but I still think this is somewhat buggy, or I can't wrap my head around it. This fails a number of our tests and makes it quite fragile to maintain them.

The [default trace level](https://github.com/sbt/sbt/blob/634e8799e76395f7bb280ea7f5f910f9cce21838/main/src/main/scala/sbt/internal/LogManager.scala#L226-L227) is set to `Int.MaxValue` when not in `interactive` mode (which is the case here)...

**Comment by atoz96** [comment]
Hi, @eed3si9n
Can I contribute to this issue?

**Comment by Crystora** [comment]
@eed3si9n Can I work on this? I am ready to raise PR.
thank you

**Comment by eed3si9n** [comment]
Yes, this issue is open for contribution. Please check out our [Contributor's Guildeline](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) and:
1. Make sure you can reproduce the problem and the fix manually
2. Include tests for the change
3. Follow our AI assisted contributions guideline (please disclose AI usages in the PR description, if any)
4. Multiple contributors might work on this issue in parallel
5. Generally we recommend getting CI to pass on a forked repo before sending a pull request (pull requests that do not pass tests will be closed after a few days)

**Comment by Crystora** [comment]
@eed3si9n 

I tested this on the `develop` branch (sbt 2.0.0-RC9-bin-SNAPSHOT) and **the bug does not reproduce**. Both tasks show full stack traces in batch mode, whether or not `streams.value.log` is used.

Test case:

```scala
lazy val helloWithoutStreams = taskKey[Unit]("")
lazy val helloWithStreams = taskKey[Unit]("")

helloWithoutStreams := {
  throw new RuntimeException("boom without streams!")
}

helloWithStreams := {
  val log = streams.value.log
  throw new RuntimeException("boom with streams!")
}
```

Both produce identical stack trace output when run in batch mode. This was likely fixed as part of the 1.x → 2.x refactoring.

I've also added a scripted regression test at `sbt-app/src/sbt-test/actions/streams-trace-level/` to prevent this from regressing. Happy to open a PR if that would be useful.
Which option would you prefer: test PR or close this issue?

**Comment by eed3si9n** [comment]
Using the build you provided, I can reproduce the issue in both the tasks:

```bash
$ sbt helloWithoutStreams
[info] server was not detected. starting an instance
[info] welcome to sbt 2.0.0-RC9-bin-SNAPSHOT (Azul Systems, Inc. Java 17.0.12)
....
[info] sbt server started at local:///Users/xxx/dotfiles/sbt/2/server/4036f98ede645c010dd3/sock
[info] started sbt server
[error] stack trace is suppressed; run last helloWithoutStreams for the full output
[error] elapsed time: 0 s

$ sbt helloWithStreams
[error] stack trace is suppressed; run last helloWithStreams for the full output
[error] elapsed time: 0 s
```

**Comment by Crystora** [comment]
@eed3si9n 
I tested in true batch mode using `java -jar sbt-launch.jar <task>` (no server involved), and both tasks show full stack traces:

```
$ java -jar sbt-launch.jar helloWithoutStreams
[info] welcome to sbt 2.0.0-RC9-bin-SNAPSHOT (Ubuntu Java 21.0.10)
[info] loading project definition from /tmp/sbt-7322-test/project
[info] set current project to sbt-7322-test (in build file:/tmp/sbt-7322-test/)
[warn] scalaVersion for subproject sbt-7322-test fell back to a default value 3.8.2; declare it explicitly in build.sbt:
[warn]   scalaVersion := "3.8.2"
[error] java.lang.RuntimeException: boom without streams!
[error] 	at $Wrapaec9961342$.$sbtdef$$anonfun$1$$anonfun$1(build.sbt:5)
[error] 	at sbt.util.ActionCache$.organicTask$1(ActionCache.scala:77)
....

$ java -jar sbt-launch.jar helloWithStreams
[info] welcome to sbt 2.0.0-RC9-bin-SNAPSHOT (Ubuntu Java 21.0.10)
[info] loading project definition from /tmp/sbt-7322-test/project
[info] set current project to sbt-7322-test (in build file:/tmp/sbt-7322-test/)
[warn] scalaVersion for subproject sbt-7322-test fell back to a default value 3.8.2; declare it explicitly in build.sbt:
[warn]   scalaVersion := "3.8.2"
[error] java.lang.RuntimeException: boom with streams!
[error] 	at $Wrap9ba6fe6693$.$sbtdef$$anonfun$1$$anonfun$1(build.sbt:10)
[error] 	at sbt.util.ActionCache$.organicTask$1(ActionCache.scala:77)
....
```

So the original issue - where adding `streams.value.log` caused stack traces to disappear in batch mode - **does not reproduce in sbt 2.x**.

In your test, I noticed `server was not detected. starting an instance` in the output, which means `$ sbt` went through the thin client/server. The server runs in interactive mode where traces are suppressed by default for all tasks. That's why both tasks showed `stack trace is suppressed` - it's the expected interactive mode behavior, not this issue. 
Could you test again?

**Comment by eed3si9n** [comment]
Sure, `sbt --server helloWithStreams` works on sbt 2.x, but I'd argue that on sbt 2.x batch mode would be sbtn, not `sbt --server`.
