### ISSUE TITLE
java.lang.ClassNotFoundException: wvlet.log.AirframeLogManager when creating a new project on JDK 17

### ISSUE THREAD

**Issue by anatoliykmetyuk** [sbt/sbt#7338]
## steps

1. Install Java 17
2. Run `sbt new scala/scala3.g8` from an empty directory

## problem

I see an exception in the terminal. SBT doesn't crash though and continues to operate, so I am able to use it. But the exception is not a nice thing to see.

<details>
<summary>Exception</summary>

```
tsf-436-wpa-5-059:tmp kmetiuk$ sbt new scala/scala3.g8
[info] welcome to sbt 1.7.1 (Homebrew Java 17.0.8)
[info] loading settings for project global-plugins from publishing.sbt ...
[info] loading global plugins from /Users/kmetiuk/.sbt/1.0/plugins
Could not load Logmanager "wvlet.log.AirframeLogManager"
java.lang.ClassNotFoundException: wvlet.log.AirframeLogManager
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.logging/java.util.logging.LogManager$1.run(LogManager.java:239)
	at java.logging/java.util.logging.LogManager$1.run(LogManager.java:223)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.logging/java.util.logging.LogManager.<clinit>(LogManager.java:222)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.management/sun.management.ManagementFactoryHelper$LoggingMXBeanAccess.getMXBeanImplementation(ManagementFactoryHelper.java:243)
	at java.management/sun.management.ManagementFactoryHelper$LoggingMXBeanAccess.<init>(ManagementFactoryHelper.java:259)
	at java.management/sun.management.ManagementFactoryHelper$PlatformLoggingImpl.getInstance(ManagementFactoryHelper.java:339)
	at java.management/sun.management.ManagementFactoryHelper$PlatformLoggingImpl.<clinit>(ManagementFactoryHelper.java:342)
	at java.management/sun.management.ManagementFactoryHelper.getPlatformLoggingMXBean(ManagementFactoryHelper.java:160)
	at java.management/java.lang.management.DefaultPlatformMBeanProvider$9.nameToMBeanMap(DefaultPlatformMBeanProvider.java:378)
	at java.management/java.lang.management.ManagementFactory.lambda$getPlatformMBeanServer$0(ManagementFactory.java:488)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.management/java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:489)
	at wvlet.log.LogEnv$.registerJMX(LogEnv.scala:67)
	at wvlet.log.LogEnv$.<init>(LogEnv.scala:62)
	at wvlet.log.LogEnv$.<clinit>(LogEnv.scala)
	at wvlet.log.Logger$.rootLogger$lzycompute(Logger.scala:203)
	at wvlet.log.Logger$.rootLogger(Logger.scala:202)
	at wvlet.log.Logger$.clearAllHandlers(Logger.scala:268)
	at wvlet.log.Logger$.init(Logger.scala:272)
	at xerial.sbt.Sonatype$.<init>(Sonatype.scala:23)
	at xerial.sbt.Sonatype$.<clinit>(Sonatype.scala)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at sbt.internal.inc.ModuleUtilities$.getObject(ModuleUtilities.scala:24)
	at sbt.internal.inc.ModuleUtilities$.getCheckedObject(ModuleUtilities.scala:32)
	at sbt.internal.inc.ModuleUtilities$.$anonfun$getCheckedObjects$1(ModuleUtilities.scala:37)
	at scala.collection.immutable.Stream.$anonfun$map$1(Stream.scala:418)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1173)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1163)
	at scala.collection.generic.Growable.loop$1(Growable.scala:57)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:61)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:184)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:47)
	at scala.collection.TraversableLike.to(TraversableLike.scala:786)
	at scala.collection.TraversableLike.to$(TraversableLike.scala:783)
	at scala.collection.AbstractTraversable.to(Traversable.scala:108)
	at scala.collection.TraversableOnce.toList(TraversableOnce.scala:350)
	at scala.collection.TraversableOnce.toList$(TraversableOnce.scala:350)
	at scala.collection.AbstractTraversable.toList(Traversable.scala:108)
	at scala.collection.immutable.List.$plus$plus(List.scala:216)
	at sbt.internal.PluginDiscovery$.discoverAll(PluginDiscovery.scala:58)
	at sbt.internal.Load$.loadPlugins(Load.scala:1329)
	at sbt.internal.Load$.loadPluginDefinition(Load.scala:1274)
	at sbt.internal.Load$.noPlugins(Load.scala:1249)
	at sbt.internal.Load$.plugins(Load.scala:1234)
	at sbt.internal.Load$.$anonfun$loadUnit$2(Load.scala:700)
	at sbt.internal.Load$.timed(Load.scala:1406)
	at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:700)
	at sbt.internal.Load$.timed(Load.scala:1406)
	at sbt.internal.Load$.loadUnit(Load.scala:694)
	at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:492)
	at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:180)
	at sbt.internal.BuildLoader.apply(BuildLoader.scala:245)
	at sbt.internal.Load$.loadURI$1(Load.scala:554)
	at sbt.internal.Load$.loadAll(Load.scala:570)
	at sbt.internal.Load$.loadURI(Load.scala:500)
	at sbt.internal.Load$.load(Load.scala:479)
	at sbt.internal.Load$.$anonfun$apply$1(Load.scala:241)
	at sbt.internal.Load$.timed(Load.scala:1406)
	at sbt.internal.Load$.apply(Load.scala:241)
	at sbt.internal.Load$.defaultLoad(Load.scala:56)
	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:953)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:953)
	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:906)
	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:150)
	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:145)
	at sbt.Command$.process(Command.scala:189)
	at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:245)
	at scala.Option.getOrElse(Option.scala:189)
	at sbt.MainLoop$.process$1(MainLoop.scala:245)
	at sbt.MainLoop$.processCommand(MainLoop.scala:278)
	at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:163)
	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:289)
	at sbt.State$StateOpsImpl$.process$extension(State.scala:325)
	at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:163)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.MainLoop$.next(MainLoop.scala:163)
	at sbt.MainLoop$.run(MainLoop.scala:144)
	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:119)
	at sbt.io.Using.apply(Using.scala:27)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:112)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:66)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:51)
	at sbt.MainLoop$.runLogged(MainLoop.scala:42)
	at sbt.StandardMain$.runManaged(Main.scala:215)
	at sbt.xMain$.$anonfun$run$9(Main.scala:113)
	at sbt.io.IO$.withTemporaryDirectory(IO.scala:490)
	at sbt.io.IO$.withTemporaryDirectory(IO.scala:500)
	at sbt.xMain$.run(Main.scala:101)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:57)
	at sbt.xMain.run(Main.scala:46)
	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
	at xsbt.boot.Launch$.run(Launch.scala:149)
	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
	at xsbt.boot.Launch$.launch(Launch.scala:159)
	at xsbt.boot.Launch$.apply(Launch.scala:44)
	at xsbt.boot.Launch$.apply(Launch.scala:21)
	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
	at xsbt.boot.Boot$.run(Boot.scala:73)
	at xsbt.boot.Boot$.main(Boot.scala:21)
	at xsbt.boot.Boot.main(Boot.scala)
[info] set current project to new (in build file:/private/var/folders/vl/y4c295x15g5dngc86djvdhvc0053w1/T/sbt_42e65e97/new/)

A template to demonstrate a minimal Scala 3 application
```
</details>

## expectation

Should not throw that exception.

## notes

Versions of software:

```
tsf-436-wpa-5-059:tmp kmetiuk$ sbt --version
sbt version in this project: 1.7.1
sbt script version: 1.7.1
tsf-436-wpa-5-059:tmp kmetiuk$ java -version
openjdk version "17.0.8" 2023-07-18
OpenJDK Runtime Environment Homebrew (build 17.0.8+0)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.8+0, mixed mode, sharing)
tsf-436-wpa-5-059:tmp kmetiuk$ jenv
jenv 0.5.5
```

I am using `jenv` to manage Java. When I switch to Java 8 using `jenv local 1.8`, the problem disappears.

**Comment by eed3si9n** [comment]
```
java.lang.ClassNotFoundException: wvlet.log.AirframeLogManager
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	...
java.management/java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:489)
	at wvlet.log.LogEnv$.registerJMX(LogEnv.scala:67)
	at wvlet.log.LogEnv$.<init>(LogEnv.scala:62)
	at wvlet.log.LogEnv$.<clinit>(LogEnv.scala)
	at wvlet.log.Logger$.rootLogger$lzycompute(Logger.scala:203)
	at wvlet.log.Logger$.rootLogger(Logger.scala:202)
	at wvlet.log.Logger$.clearAllHandlers(Logger.scala:268)
	at wvlet.log.Logger$.init(Logger.scala:272)
	at xerial.sbt.Sonatype$.<init>(Sonatype.scala:23)
```

Looking at the stacktrace, it seems like an issue with sbt-sonatype. 

sbt runs scripted test on CI using JDK 17, so our normal operation _should_ work on JDK 17.

**Comment by SethTisue** [comment]
"welcome to sbt 1.7.1 ", it says? is the problem reproducible on 1.9.2? I couldn't reproduce it, just now.

does it depend on having certain plugins activated globally? these lines suggest it might:

```
[info] loading settings for project global-plugins from publishing.sbt ...
[info] loading global plugins from /Users/kmetiuk/.sbt/1.0/plugins
```

these lines in the stack trace make me suspect sbt-sonatype:

```
	at xerial.sbt.Sonatype$.<init>(Sonatype.scala:23)
	at xerial.sbt.Sonatype$.<clinit>(Sonatype.scala)
```

**Comment by SethTisue** [comment]
jinx

**Comment by anatoliykmetyuk** [comment]
Ok, it turned out to be the plugins. I had in `~/.sbt/1.0/plugins/publishing.sbt`:

```scala
addSbtPlugin("com.github.sbt" % "sbt-pgp" % "2.1.2")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "3.9.5")
```

I updated it to:

```scala
addSbtPlugin("com.github.sbt" % "sbt-pgp" % "2.2.1")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "3.9.21")
```

That solved the issue. Also I updated SBT to 1.9.3.
