### ISSUE TITLE
sbt produces Null Pointer Exception

### ISSUE THREAD

**Issue by samthebest** [sbt/sbt#7342]
## steps

```
git clone git@github.com:samthebest/reproducing-sbt-bug.git
cd reproducing-sbt-bug
time sbt -verbose "project halogenTelemetryWriter" assembly
```

(I was actually trying to reproduce this bug here: https://github.com/sbt/sbt/issues/7341, but got this NPE before even getting to that stage).

## problem

```
[error] java.lang.NullPointerException
[error] 	at sbt.librarymanagement.ModuleIDFormats$$anon$1.write(ModuleIDFormats.scala:35)
[error] 	at sbt.librarymanagement.ModuleIDFormats$$anon$1.write(ModuleIDFormats.scala:9)
[error] 	at sjsonnew.SupportConverter.toJsonUnsafe(SupportConverter.scala:23)
[error] 	at sjsonnew.SupportConverter.toJsonUnsafe$(SupportConverter.scala:20)
[error] 	at sjsonnew.support.scalajson.unsafe.Converter$.toJsonUnsafe(Converter.scala:7)
[error] 	at sbt.Classpaths$$anon$7.write(Defaults.scala:3675)
[error] 	at sbt.Classpaths$$anon$7.write(Defaults.scala:3670)
[error] 	at sjsonnew.CollectionFormats$$anon$1.$anonfun$write$1(CollectionFormats.scala:40)
[error] 	at sjsonnew.CollectionFormats$$anon$1.$anonfun$write$1$adapted(CollectionFormats.scala:38)
[error] 	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:400)
[error] 	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:728)
[error] 	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:728)
[error] 	at sjsonnew.CollectionFormats$$anon$1.write(CollectionFormats.scala:38)
[error] 	at sjsonnew.CollectionFormats$$anon$1.write(CollectionFormats.scala:32)
[error] 	at sjsonnew.SupportConverter.toJsonUnsafe(SupportConverter.scala:23)
[error] 	at sjsonnew.SupportConverter.toJsonUnsafe$(SupportConverter.scala:20)
[error] 	at sjsonnew.support.scalajson.unsafe.Converter$.toJsonUnsafe(Converter.scala:7)
[error] 	at sjsonnew.SupportConverter.$anonfun$toJson$1(SupportConverter.scala:14)
[error] 	at scala.util.Try$.apply(Try.scala:213)
[error] 	at sjsonnew.SupportConverter.toJson(SupportConverter.scala:14)
[error] 	at sjsonnew.SupportConverter.toJson$(SupportConverter.scala:13)
[error] 	at sjsonnew.support.scalajson.unsafe.Converter$.toJson(Converter.scala:7)
[error] 	at sbt.util.FileOutput.write(Output.scala:39)
[error] 	at sbt.util.FileBasedStore.write(CacheStore.scala:90)
[error] 	at sbt.internal.InMemoryCacheStore$CacheStoreImpl.write(InMemoryCacheStore.scala:76)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:75)
[error] 	at sbt.Classpaths$.$anonfun$dependencyPositionsTask$5(Defaults.scala:3863)
[error] 	at sbt.Classpaths$.$anonfun$dependencyPositionsTask$5$adapted(Defaults.scala:3829)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:220)
[error] 	at sbt.Classpaths$.$anonfun$dependencyPositionsTask$1(Defaults.scala:3865)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.Execute.work(Execute.scala:292)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:829)

... repeats ....

then finally

[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:829)
[error] (dependencyPositions) java.lang.NullPointerException
[error] (core / dependencyPositions) java.lang.NullPointerException
[error] (core / moduleSettings) java.lang.NullPointerException
[error] (core / csrFallbackDependencies) java.lang.NullPointerException
[error] (core / csrProject) java.lang.NullPointerException
[error] (dynamoUtil / csrFallbackDependencies) java.lang.NullPointerException
[error] (moduleSettings) java.lang.NullPointerException
[error] (csrFallbackDependencies) java.lang.NullPointerException
[error] (csrProject) java.lang.NullPointerException
[error] Total time: 6 s, completed 1 Aug 2023, 10:59:24

```

## expectation

Well I was expecting to reproduce a _different_ bug, but of course ideally I was hoping it would build a jar.

## Extra Info

```
[sbt_options] declare -a sbt_options='()'
[process_args] java_version = '11'
[copyRt] java9_rt = '/Users/sam/.sbt/1.0/java9-rt-ext-adoptopenjdk_11_0_11/rt.jar'
# Executing command line:
java
-Xmx16G
-Xss16M
-Xms4G
-Dsbt.script=/opt/homebrew/Cellar/sbt/1.9.0/libexec/bin/sbt
-Dscala.ext.dirs=/Users/sam/.sbt/1.0/java9-rt-ext-adoptopenjdk_11_0_11
-jar
/opt/homebrew/Cellar/sbt/1.9.0/libexec/bin/sbt-launch.jar
"project halogenTelemetryWriter"
assembly

```

**Comment by samthebest** [comment]
@eed3si9n if you checkout `experiments2` from `reproducing-sbt-bug`, then I've managed to isolate the NPE to a very small trivial change:

```
sam@sams-MacBook-Pro.local:/Users/sam/src/hypervolt-repos/reproducing-sbt-bug git diff 7336fa4f3aaf3d183509638bbf614bf84de99876
diff --git a/project/Dependencies.scala b/project/Dependencies.scala
index fac75b3..6e640a6 100644
--- a/project/Dependencies.scala
+++ b/project/Dependencies.scala
@@ -1,10 +1,10 @@
 import sbt._
 
 object Dependencies {
-  val scanamoVersion = "1.0.0-M15"
-
   object Misc {
+    val scanamoVersion = "1.0.0-M15"
     val scanamo = "org.scanamo" %% "scanamo" % scanamoVersion
+    
     val bigquery = "com.google.cloud" % "google-cloud-bigquery" % "2.16.1"
   }
```

**Comment by eed3si9n** [comment]
See also https://github.com/sbt/sbt/issues/7341#issuecomment-1661210892

I'd recommend keep adding more `lazy` or change them all to `def`.

**Comment by SethTisue** [comment]
I didn't dig into it, but certainly my first impression here was "that looks like a Scala issue around initialization order, not an sbt issue". If it's actually an sbt issue, that needs to be argued for and demonstrated — "I got an NPE" isn't a demonstration.

**Comment by eed3si9n** [comment]
As far as bug reporting goes, I am happy to see repro project. We (the maintainers) can decide on the details of if it's a Scala issue or an sbt issue, and in this case I think it's a Scala issue too esp because it also hanging.

**Comment by samthebest** [comment]
@eed3si9n @SethTisue if there is a bug in an underlying lib/lang being used, please could we at least catch the exception and handle it 🙏  - say, a message like "You are using a feature that isn't supported by Scala 2.12, please try ..., for more info see  https://github.com/sbt/sbt/issues/7342 and SI-XXXX".

**Comment by SethTisue** [comment]
That's a good thought in general, but I don't see how it's feasible in this case. There's a null pointer exception and at runtime I don't think sbt has enough information to figure out what the cause might be.

Perhaps I'm wrong, but I'd need it laid out for me how it could work.

**Comment by mzuehlke** [comment]
Maybe [JEP 358: Helpful NullPointerExceptions](https://openjdk.org/jeps/358) which is enabled from JDK 15 on would produce a better error message.
