### ISSUE TITLE
SBT overrides Test scope with Compile scope when debugging.

### ISSUE THREAD

**Issue by rochala** [sbt/sbt#7344]
## steps

`Sbt 1.9.3`

```sbt
name := "playground"
version := "0.1.0-SNAPSHOT"

lazy val root = (project in file(".")).
  enablePlugins(BuildInfoPlugin).
  settings(
    scalaVersion := "3.3.0",
    libraryDependencies += "junit" % "junit" % "4.13.2" % Test,
    libraryDependencies += "com.github.sbt" % "junit-interface" % "0.13.2" % Test,
    Compile / buildInfoPackage := "dotty.tools.pc.util",
    Compile / buildInfoKeys := Seq(scalaVersion),
    Test / buildInfoKeys := Seq(scalaVersion, scalaBinaryVersion),
    BuildInfoPlugin.buildInfoScopedSettings(Compile),
    BuildInfoPlugin.buildInfoScopedSettings(Test),
    BuildInfoPlugin.buildInfoDefaultSettings
  )
```
With example test `src/test/scala/MySuite.scala`
```scala
import org.junit.Test
import org.junit.Assert._
import dotty.tools.pc.util.BuildInfo

class TestMain:
  @Test
  def test1 =
    println(BuildInfo.scalaBinaryVersion)
    assertEquals(1, 1)
```

Will throw:

```
Test TestMain.test1 failed: java.lang.NoSuchMethodError: 'java.lang.String dotty.tools.pc.util.BuildInfo$.scalaBinaryVersion()', took 0.069 sec
    at TestMain.test1(MySuite.scala:9)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
NativeMethodAccessorImpl.java:36
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
NativeMethodAccessorImpl.java:77
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
DelegatingMethodAccessorImpl.java:43
    at java.lang.reflect.Method.invoke(Method.java:568)
Method.java:568
    ...
```

## problem

It seems that sbt passes Compile scope path of `BuildInfo` to debugging classpath instead of Test scope when it is run in debug mode.
We're using this configuration in the dotty compiler to include Scala library classpath for testing purposes, and we can't debug it due to this issue.

It will greatly improve quality of life of developers, as we will be able to easily start specific test debugging without manually setting the proper classpath.

## expectation

It should properly use Test scope.
## notes

I'm not sure if this is the correct repository to create issue in, but it seems that bloop correctly resolves the scope.

**Comment by rochala** [comment]
It should belong in scala-debug-adapter.
