### ISSUE TITLE
Facing error while migrating sbt based scala app from 1.3.13 to 1.9.0

### ISSUE THREAD

**Issue by anishb266** [sbt/sbt#7373]
I have an enterprise app created with Scala and Play. I'm using sbt **1.3.13** currently. Now, I want to migrate it to **1.9.0**.

When I'm compiling the project, I'm getting this error :

`java.net.URISyntaxException: Illegal character in path at index 100: https://example.com/repo/com/example/demo/1.2/${id}-1.2.jar`

**built.sbt.**
```

resolvers ++= Seq(
  "repo" at "https://example.com/repo",
   .........
)
```

I was not getting this error earlier on 1.3.13. What could be the issue? Is it something related to changes which happened for URL parsing which is causing this issue? 

**Note:** Tested with 1.8.3, it's working as expected.

**Comment by eed3si9n** [comment]
@anishb266 Thanks for the report. This might be related to https://github.com/sbt/io/pull/341, where we now use URI constructor as opposed to the deprecated URL constructor.  /cc @xuwei-k 

Could you tell use the actual illegal character, even if you can't share the actual URL? Was it the left curly brace `{`? If so you might need to encode it as `%7B`, and `}` with `%7D` (haven't confirmed).

**Comment by anishb266** [comment]
> @anishb266 Thanks for the report. This might be related to [sbt/io#341](https://github.com/sbt/io/pull/341), where we now use URI constructor as opposed to the deprecated URL constructor. /cc @xuwei-k
> 
> Could you tell use the actual illegal character, even if you can't share the actual URL? Was it the left curly brace `{`? If so you might need to encode it as `%7B`, and `}` with `%7D` (haven't confirmed).



Yes, the issue is `${id}` in the url. sbt is trying to pull the dependencies from the remote repo. Throwing me the error while it's encountering the `${id}` thing in the url.

**Comment by anishb266** [comment]
@eed3si9n But this url pattern with ${id} I didn't mentioned it in the **build.sbt**. It's pulled from remote repo. SBT is not able to resolve that dynamic parameter by replacing ${id} with the actual value. 

How to tell sbt to resolve this kind of url which contains dynamic parameters?

**Comment by eed3si9n** [comment]
Could you share a stacktrace please?

**Comment by anishb266** [comment]
@eed3si9n  Yes, sure:

```
[info] Executing in batch mode. For better performance use sbt's shell
[success] Total time: 1 s, completed 13 Sep, 2023 6:30:59 PM
[info] ExecutionContext implicit check took 13 ms
[info] Nullable implicit RequestContext check took 205 ms
[info] Fetching artifacts of
[info] Fetched artifacts of
[error] java.net.URISyntaxException: Illegal character in path at index 100: https://artifactory.in.here.com/artifactory/here-olp-sit/com/here/dp/event-management-client/1.7.7/${em.client.artifact.id}-1.7.7.jar
[error] 	at java.net.URI$Parser.fail(URI.java:2873)
[error] 	at java.net.URI$Parser.checkChars(URI.java:3046)
[error] 	at java.net.URI$Parser.parseHierarchical(URI.java:3130)
[error] 	at java.net.URI$Parser.parse(URI.java:3078)
[error] 	at java.net.URI.<init>(URI.java:588)
[error] 	at java.net.URL.toURI(URL.java:989)
[error] 	at sjsonnew.JavaExtraFormats.$anonfun$urlStringIso$1(JavaExtraFormats.scala:40)
[error] 	at sjsonnew.IsoString$$anon$1.to(IsoString.scala:26)
[error] 	at sjsonnew.IsoFormats$$anon$2.write(IsoFormats.scala:31)
[error] 	at sjsonnew.StandardFormats$OptionFormat.write(StandardFormats.scala:37)
[error] 	at sjsonnew.StandardFormats$OptionFormat.addField(StandardFormats.scala:44)
[error] 	at sjsonnew.StandardFormats$OptionFormat.addField(StandardFormats.scala:33)
[error] 	at sjsonnew.Builder.addField(Builder.scala:43)
[error] 	at sbt.librarymanagement.ArtifactFormats$$anon$1.write(ArtifactFormats.scala:36)
[error] 	at sbt.librarymanagement.ArtifactFormats$$anon$1.write(ArtifactFormats.scala:9)
[error] 	at sjsonnew.CollectionFormats$$anon$2.$anonfun$write$2(CollectionFormats.scala:85)
[error] 	at sjsonnew.CollectionFormats$$anon$2.$anonfun$write$2$adapted(CollectionFormats.scala:85)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at sjsonnew.CollectionFormats$$anon$2.write(CollectionFormats.scala:85)
[error] 	at sjsonnew.CollectionFormats$$anon$2.write(CollectionFormats.scala:80)
[error] 	at sjsonnew.JsonWriter.addField(JsonFormat.scala:40)
[error] 	at sjsonnew.JsonWriter.addField$(JsonFormat.scala:37)
[error] 	at sjsonnew.CollectionFormats$$anon$2.addField(CollectionFormats.scala:80)
[error] 	at sjsonnew.Builder.addField(Builder.scala:43)
[error] 	at sbt.librarymanagement.ModuleReportFormats$$anon$1.write(ModuleReportFormats.scala:42)
[error] 	at sbt.librarymanagement.ModuleReportFormats$$anon$1.write(ModuleReportFormats.scala:9)
[error] 	at sjsonnew.CollectionFormats$$anon$2.$anonfun$write$2(CollectionFormats.scala:85)
[error] 	at sjsonnew.CollectionFormats$$anon$2.$anonfun$write$2$adapted(CollectionFormats.scala:85)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at sjsonnew.CollectionFormats$$anon$2.write(CollectionFormats.scala:85)
[error] 	at sjsonnew.CollectionFormats$$anon$2.write(CollectionFormats.scala:80)
[error] 	at sjsonnew.JsonWriter.addField(JsonFormat.scala:40)
[error] 	at sjsonnew.JsonWriter.addField$(JsonFormat.scala:37)
[error] 	at sjsonnew.CollectionFormats$$anon$2.addField(CollectionFormats.scala:80)
[error] 	at sjsonnew.Builder.addField(Builder.scala:43)
[error] 	at sbt.librarymanagement.ConfigurationReportFormats$$anon$1.write(ConfigurationReportFormats.scala:26)
[error] 	at sbt.librarymanagement.ConfigurationReportFormats$$anon$1.write(ConfigurationReportFormats.scala:9)
[error] 	at sjsonnew.CollectionFormats$$anon$2.$anonfun$write$2(CollectionFormats.scala:85)
[error] 	at sjsonnew.CollectionFormats$$anon$2.$anonfun$write$2$adapted(CollectionFormats.scala:85)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at sjsonnew.CollectionFormats$$anon$2.write(CollectionFormats.scala:85)
[error] 	at sjsonnew.CollectionFormats$$anon$2.write(CollectionFormats.scala:80)
[error] 	at sjsonnew.JsonWriter.addField(JsonFormat.scala:40)
[error] 	at sjsonnew.JsonWriter.addField$(JsonFormat.scala:37)
[error] 	at sjsonnew.CollectionFormats$$anon$2.addField(CollectionFormats.scala:80)
[error] 	at sjsonnew.Builder.addField(Builder.scala:43)
[error] 	at sbt.librarymanagement.UpdateReportFormats$$anon$1.write(UpdateReportFormats.scala:27)
[error] 	at sbt.librarymanagement.UpdateReportFormats$$anon$1.write(UpdateReportFormats.scala:9)
[error] 	at sjsonnew.SupportConverter.toJsonUnsafe(SupportConverter.scala:23)
[error] 	at sjsonnew.SupportConverter.toJsonUnsafe$(SupportConverter.scala:20)
[error] 	at sjsonnew.support.scalajson.unsafe.Converter$.toJsonUnsafe(Converter.scala:7)
[error] 	at sjsonnew.SupportConverter.$anonfun$toJson$1(SupportConverter.scala:14)
[error] 	at scala.util.Try$.apply(Try.scala:213)
[error] 	at sjsonnew.SupportConverter.toJson(SupportConverter.scala:14)
[error] 	at sjsonnew.SupportConverter.toJson$(SupportConverter.scala:13)
[error] 	at sjsonnew.support.scalajson.unsafe.Converter$.toJson(Converter.scala:7)
[error] 	at sbt.util.FileOutput.write(Output.scala:38)
[error] 	at sbt.util.FileBasedStore.write(CacheStore.scala:89)
[error] 	at sbt.internal.InMemoryCacheStore$CacheStoreImpl.write(InMemoryCacheStore.scala:75)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:74)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3801)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:750)
[error] (update) java.net.URISyntaxException: Illegal character in path at index 100: https://artifactory.in.here.com/artifactory/here-olp-sit/com/here/dp/event-management-client/1.7.7/${em.client.artifact.id}-1.7.7.jar
[error] Total time: 4 s, completed 13 Sep, 2023 6:31:03 PM
```

**Comment by anishb266** [comment]
@eed3si9n Can you kindly reply on this? I need to understand where is the issue.

**Comment by eed3si9n** [comment]
O hi sorry, it became clear to me that the problem is at sjsonnew when I saw the stacktrace but forgot to reply here.

**Comment by anishb266** [comment]
@eed3si9n No problem. Can you tell me what I need to do to fix this?

**Comment by anishb266** [comment]
@eed3si9n Can we acknowledge this as a bug on the sbt version 1.9.x?

**Comment by eed3si9n** [comment]
I am not 100% sure. Technically speaking URI should not contain curly braces, so sjson-new complaining about it is correct.
When using sbt 1.3.x, does the artifact actually result to a successful download of JARs?

**Comment by anishb266** [comment]
@eed3si9n Yes! The artifacts are getting successfully downloaded. It's working with both 1.3.x and 1.8.x also. I don't know why 1.9.x is complaining. It should have worked the same way as other lower versions.

**Comment by anishb266** [comment]
@eed3si9n Can you please tell a workaround for this?

**Comment by SethTisue** [comment]
@anishb266 have you done any investigation or troubleshooting on your own?

**Comment by anishb266** [comment]
@SethTisue @eed3si9n  I haven't done that yet. But I can do the troubleshooting. That's not a big deal.

But before doing that I wanted to know the reason why this happened in 1.9.x version only. 

That's why I have raised the concern. I wanted to know a solution for now before jumping into my organization's code.

**My organization's project is using sbt from a very long time. Obviously, there was no issue with URI having curly braces.**

**This arises another question:**

How come URI containing curly braces was earlier working with sbt version up till `1.8.x` then and not in version > `1.8.x`?

Can you try to reproduce on your side? I'm not sure but I guess this merge request https://github.com/sbt/io/pull/341 has to do something with the current issue.

This has to be acknowledged as a bug on sbt.

**Comment by anishb266** [comment]
@SethTisue Currently, I have migrated the project with 1.8.3 version of sbt as it's completely working fine.

But I have to know the reason why it didn't work for 1.9.x. I wanted my code base to use latest version of sbt as much as possible.

**Comment by SethTisue** [comment]
> Can you try to reproduce on your side?

What steps would I follow to do that?

**Comment by eed3si9n** [comment]
> My organization's project is using sbt from a very long time. Obviously, there was no issue with URI having curly braces.

I don't think anything is really obvious here. POM files can contain [properties](https://maven.apache.org/pom.html#Properties) like

```xml
  <properties>
    <em.client.artifact.id>x</em.client.artifact.id>
  </properties>
```

and this can later appear in POM as `${em.client.artifact.id}`. However, by the time UpdateReport structure is created by the dependency resolution engine, the URL of the artifact is expected to be resolved to a concrete URL.

In addition, line 40 in question

https://github.com/eed3si9n/sjson-new/blame/66f05ac562a5c4ed544d24c41aacf3b69a9318f4/core/src/main/scala/sjsonnew/JavaExtraFormats.scala#L39-L40
```scala
implicit val urlStringIso: IsoString[URL] = IsoString.iso[URL](
    _.toURI.toASCIIString, (s: String) => (new URI(s)).toURL)
```

has not changed in 7 years, so at least the JSON decoding/encoding isn't really part of the problem.

It's still possible something somewhere changed in some way, but without publicly reproducible steps, I can't tell what could be causing this, or even if it's doing the right thing or wrong thing.
