### ISSUE TITLE
NumberFormatException: For input string: "1B

### ISSUE THREAD

**Issue by coffius** [sbt/sbt#7375]
## steps
**SBT version:** 1.9.4
**build.sbt:** can't provide it as it is a closed sourced project
**Description:**  
* Each time when I run `sbt clean test:compile` in the project I got the error.
* If I run `sbt clean` and then `sbt test:compile` separately one by one then the same error appears.
* But if I run `sbt test:compile` again then it passes ok,
```
sbt clean # Ok here
sbt test:compile # The error
sbt test:compile # Ok
```

## problem

```
[error] java.lang.NumberFormatException: For input string: "1B
error]  at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
[error]         at java.base/java.lang.Integer.parseInt(Integer.java:668)
[error]         at java.base/java.lang.Integer.<init>(Integer.java:1127)
[error]         at org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:120)
[error]         at java.base/java.io.FilterOutputStream.write(FilterOutputStream.java:137)
[error]         at java.base/java.io.PrintStream.write(PrintStream.java:568)
[error]         at sbt.internal.util.Terminal$proxyErrorOutputStream$.write(Terminal.scala:755)
[error]         at java.base/java.io.PrintStream.write(PrintStream.java:568)
[error]         at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)
[error]         at java.base/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:313)
[error]         at java.base/sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:318)
[error]         at java.base/sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:160)
[error]         at java.base/java.io.OutputStreamWriter.flush(OutputStreamWriter.java:248)
[error]         at lmcoursier.internal.shaded.coursier.cache.loggers.ProgressBarRefreshDisplay.stop(ProgressBarRefreshDisplay.scala:33)
[error]         at lmcoursier.internal.shaded.coursier.cache.loggers.RefreshLogger$UpdateDisplayRunnable.stop(RefreshLogger.scala:171)
[error]         at lmcoursier.internal.shaded.coursier.cache.loggers.RefreshLogger.stop(RefreshLogger.scala:289)
[error]         at lmcoursier.internal.shaded.coursier.cache.CacheLogger$Using.$anonfun$apply$4(CacheLogger.scala:63)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error]         at lmcoursier.internal.shaded.coursier.util.Task$.wrap(Task.scala:82)
[error]         at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$delay$2(Task.scala:47)
[error]         at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[error]         at scala.util.Success.$anonfun$map$1(Try.scala:255)
[error]         at scala.util.Success.map(Try.scala:213)
[error]         at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[error]         at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[error]         at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[error]         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error]         at java.base/java.lang.Thread.run(Thread.java:833)
[error] (update) java.lang.NumberFormatException: For input string: "1B

error] Total time: 56 s, completed Sep 12, 2023, 11:34:16 AM
```

## expectation
`sbt clean test:compile` should work without exceptions.

**Comment by SethTisue** [comment]
I understand that you can't share your closed-source build, but have you attempted to construct a standalone reproducer than you can share?

**Comment by eed3si9n** [comment]
Based on the stack trace it's either Coursier's progress logger, sbt's Terminal hijacking, or Jansi AnsiOutputStream causing this issue.

**Comment by mzuehlke** [comment]
Jansi `AnsiOutputStream` is not thread safe (on purpose !)
> This particular class is not synchronized for improved performances.

But it seems it is used from an async task.

Jline 3 made the `write` method synchronized to fix a very similar looking bug:
- https://github.com/jline/jline3/commit/4bda4a15ff9d9ea2ebc27795ea777016c6f1d44f
- https://github.com/jline/jline3/issues/116

**Comment by Friendseeker** [comment]
sbt is no longer using Jansi.

Feel free to reopen the issue if the issue somehow remains reproducible on sbt 1.10.4
