### ISSUE TITLE
sbt --client leads to java.nio.channels.ClosedChannelException exception in shutdown hook

### ISSUE THREAD

**Issue by anton-trunov** [sbt/sbt#7380]
## steps

Consider the following piece of code:

```
object Main {
  def main(args: Array[String]): Unit = {
    println("Hello world!")
    sys.exit(0)
  }
}
```

If I run it like so:

```shell
$ sbt --client run
```

I get the following output:
```
[info] entering *experimental* thin client - BEEP WHIRR
[info] server was not detected. starting an instance
[info] welcome to sbt 1.9.5 (Homebrew Java 20.0.2)
[info] loading project definition from /Users/anton_1/prj/my/scala/sbt-client-issue-repro/project
[info] loading settings for project root from build.sbt ...
[info] set current project to sbt-client-issue-repro (in build file:/Users/anton_1/prj/my/scala/sbt-client-issue-repro/)
[info] sbt server started at local:///Users/anton_1/.sbt/1.0/server/9f0b45b952173b1a6c65/sock
[info] started sbt server
[info] terminate the server with `shutdown`
> run
[info] compiling 1 Scala source to /Users/anton_1/prj/my/scala/sbt-client-issue-repro/target/scala-2.12/classes ...
[info] running Main
Hello world!
Caught exception running shutdown hook: java.nio.channels.ClosedChannelException
java.nio.channels.ClosedChannelException
	at sbt.internal.util.Terminal$TerminalImpl.throwIfClosed(Terminal.scala:968)
	at sbt.internal.util.Terminal$TerminalImpl$$anon$6.write(Terminal.scala:998)
	at sbt.internal.util.Terminal$proxyOutputStream$.write(Terminal.scala:742)
	at sbt.internal.util.Terminal$proxyOutputStream$.write(Terminal.scala:740)
	at sbt.internal.util.Terminal$LinePrintStream.$anonfun$println$1(Terminal.scala:507)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.internal.util.Terminal$.withWriteLock(Terminal.scala:228)
	at sbt.internal.util.Terminal$LinePrintStream.println(Terminal.scala:506)
	at sbt.internal.util.ConsoleOut$$anon$1.println(ConsoleOut.scala:71)
	at sbt.internal.util.ConsoleOut$$anon$1.println(ConsoleOut.scala:66)
	at sbt.internal.util.ConsoleOut$Proxy$.println(ConsoleOut.scala:42)
	at sbt.internal.util.Appender.write(ConsoleAppender.scala:515)
	at sbt.internal.util.Appender.$anonfun$appendLog$1(ConsoleAppender.scala:493)
	at sbt.internal.util.Appender.$anonfun$appendLog$1$adapted(ConsoleAppender.scala:479)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at sbt.internal.util.Appender.appendLog(ConsoleAppender.scala:479)
	at sbt.internal.util.Appender.appendLog(ConsoleAppender.scala:440)
	at sbt.internal.util.Appender.appendLog$(ConsoleAppender.scala:439)
	at sbt.internal.util.ConsoleAppender.appendLog(ConsoleAppender.scala:350)
	at sbt.util.LoggerContext$LoggerContextImpl$Log.$anonfun$log$2(LoggerContext.scala:125)
	at sbt.util.LoggerContext$LoggerContextImpl$Log.$anonfun$log$2$adapted(LoggerContext.scala:125)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at sbt.util.LoggerContext$LoggerContextImpl$Log.log(LoggerContext.scala:125)
	at sbt.internal.util.ManagedLogger.log(ManagedLogger.scala:42)
	at sbt.util.Logger.warn(Logger.scala:28)
	at sbt.EvaluateTask$runningEngine$1$.cancelAndShutdown(EvaluateTask.scala:523)
	at sbt.internal.server.NetworkChannel$.cancel(NetworkChannel.scala:950)
	at sbt.internal.CommandExchange.$anonfun$removeChannel$5(CommandExchange.scala:166)
	at sbt.internal.CommandExchange.$anonfun$removeChannel$5$adapted(CommandExchange.scala:165)
	at scala.Option$WithFilter.foreach(Option.scala:407)
	at sbt.internal.CommandExchange.removeChannel(CommandExchange.scala:165)
	at sbt.internal.server.NetworkChannel.shutdown(NetworkChannel.scala:570)
	at sbt.internal.server.NetworkChannel.shutdown(NetworkChannel.scala:554)
	at sbt.internal.CommandExchange.$anonfun$shutdown$1(CommandExchange.scala:290)
	at sbt.internal.CommandExchange.$anonfun$shutdown$1$adapted(CommandExchange.scala:290)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at sbt.internal.CommandExchange.shutdown(CommandExchange.scala:290)
	at sbt.StandardMain$.$anonfun$closeRunnable$1(Main.scala:217)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.internal.ShutdownHooks$.$anonfun$add$1(ShutdownHooks.scala:31)
	at sbt.internal.ShutdownHooks$.$anonfun$runAll$1(ShutdownHooks.scala:42)
	at java.base/java.util.concurrent.ConcurrentHashMap$ForEachValueTask.compute(ConcurrentHashMap.java:5030)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:667)
	at java.base/java.util.concurrent.ConcurrentHashMap.forEachValue(ConcurrentHashMap.java:4057)
	at sbt.internal.ShutdownHooks$.sbt$internal$ShutdownHooks$$runAll(ShutdownHooks.scala:42)
	at sbt.internal.ShutdownHooks$$anon$1.run(ShutdownHooks.scala:21)

sbt server connection closed.
```

SBT version:
```shell
$ sbt --version
sbt version in this project: 1.9.5
sbt script version: 1.9.4
```

My `build.sbt` (generated by Intellij IDEA):

```shell
$ cat build.sbt
ThisBuild / version := "0.1.0-SNAPSHOT"

ThisBuild / scalaVersion := "2.12.18"

lazy val root = (project in file("."))
  .settings(
    name := "sbt-client-issue-repro"
  )
```

## problem

The `sys.exit(0)` causes the issue.

## expectation

It should behave the same as plain non-client sbt:

```
$ sbt run
[info] welcome to sbt 1.9.5 (Homebrew Java 20.0.2)
[info] loading project definition from /Users/anton_1/prj/my/scala/sbt-client-issue-repro/project
[info] loading settings for project root from build.sbt ...
[info] set current project to sbt-client-issue-repro (in build file:/Users/anton_1/prj/my/scala/sbt-client-issue-repro/)
[info] running Main
Hello world!
```

## notes

No notes.

**Comment by fury0928** [comment]
### Approach for fix/7380-closed-channel-exception

**Root cause**: `TerminalImpl.throwIfClosed` throws `ClosedChannelException` when the terminal is already stopped. During JVM shutdown (triggered by `sys.exit(0)` in client mode), the shutdown hook chain calls `CommandExchange.shutdown` → `removeChannel` → `NetworkChannel.cancel` → `EvaluateTask.cancelAndShutdown`, which calls `log.warn("Canceling execution...")`. This logging goes through `ConsoleAppender` → `ConsoleOut.terminalOut` → `Terminal.get.printStream` → `TerminalImpl.outputStream.write` → `throwIfClosed` → throws.

Note: `proxyOutputStream` already catches `ClosedChannelException`, but the logger bypasses the proxy — it accesses the terminal's print stream directly via `Terminal.get.printStream`. The codebase also already has a `ConsoleOut.safeTerminalOut` wrapper that catches the exception, but it isn't used in the shutdown path.

**Proposed fix** (two parts):

1. **`Terminal.scala`** — Change `TerminalImpl.throwIfClosed` from throwing to silently discarding writes when the terminal is stopped. Writing to a closed terminal during shutdown is expected and harmless; a no-op is safer than an exception that leaks through shutdown hooks.

   ```scala
   // Before:
   def throwIfClosed[R](f: => R): R = if (isStopped.get) throw new ClosedChannelException else f

   // After:  
   def throwIfClosed(f: => Unit): Unit = if (!isStopped.get) f
   ```

   All callers of `throwIfClosed` are the `outputStream.write` methods (return `Unit`), so narrowing the type is safe.

2. **`Terminal.scala`** — Add `ClosedChannelException` handling to `proxyErrorOutputStream` for consistency with `proxyOutputStream` (currently unprotected).

This eliminates the exception at the source rather than catching it at every call site, which is more robust against future code paths that may also write to the terminal during shutdown.

@eed3si9n Does this approach look reasonable, or would you prefer a different strategy (e.g., catching at the call sites instead)?

**Comment by eed3si9n** [comment]
Now that sbt run pushes to client-side run, we should check if that issue is still relevant / reproducible.

**Comment by eed3si9n** [comment]
```bash
$ sbt --client run
[info] server was not detected. starting an instance
[info] welcome to sbt 2.0.0-RC9 (Azul Systems, Inc. Java 17.0.12)
....
[info] sbt server started at local:///Users/xxxx/.sbt/2/server/ccf999da34a624dc015f/sock
[info] running (fork) Main
Hello world!
[success] elapsed time: 2 s
```
