### ISSUE TITLE
Scala 3 sbt sandwich doesn't work

### ISSUE THREAD

**Issue by MateuszKubuszok** [sbt/sbt#7405]
I have a following repro:

```scala
// plugins.sbt
addSbtPlugin("com.eed3si9n" % "sbt-projectmatrix" % "0.9.0")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.11.0")
```

```scala
// build.sbt
val a = projectMatrix
  .in(file("a"))
  .customRow(
    scalaVersions = Seq("3.2.0"),
    axisValues = Seq(VirtualAxis.jvm),
    settings = Seq(
      //name := "a"
    )
  )
  .customRow(
    scalaVersions = Seq("3.2.0"),
    axisValues = Seq(VirtualAxis.js),
    settings = Seq(
      //name := "a"
    )
  )

val b = projectMatrix
  .in(file("b"))
  .customRow(
    scalaVersions = Seq("2.13.10"),
    axisValues = Seq(VirtualAxis.jvm),
    settings = Seq(
      //name := "b"
    )
  )
  .customRow(
    scalaVersions = Seq("2.13.10"),
    axisValues = Seq(VirtualAxis.js),
    settings = Seq(
      //name := "b"
    )
  )
  .dependsOn(a % Test)

val root = project.in(file("."))
  .aggregate(a.projectRefs ++ b.projectRefs: _*)
```

When I would run commands like `b/test` or `b/publishM2` I would expect the code to depend on `a` (with Scala 3) project when running test and not introduce any "phantom" dependencies to runtime scope. However, I get:

```
sbt:root> b/publishM2
[info] Wrote /Users/dev/Workspaces/GitHub/projectmatrix-repro/b/target/jvm-2.13/b_2.13-0.1.0-SNAPSHOT.pom
[info] Updating
https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.10/scala-library-2.13.10.pom
  100.0% [##########] 1.6 KiB (1.7 KiB / s)
[info] Resolved  dependencies
[info] Updating
[info] Resolved  dependencies
[warn]
[warn] 	Note: Unresolved dependencies path:
[error] stack trace is suppressed; run last b / update for the full output
[error] (b / update) sbt.librarymanagement.ResolveException: Error downloading a:a_2.13:0.1.0-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /Users/dev/.ivy2/local/a/a_2.13/0.1.0-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/a/a_2.13/0.1.0-SNAPSHOT/a_2.13-0.1.0-SNAPSHOT.pom
[error] Total time: 3 s, completed Oct 21, 2022, 4:23:31 PM
sbt:root> b/test
[info] Updating
[info] Resolved  dependencies
[warn]
[warn] 	Note: Unresolved dependencies path:
[error] stack trace is suppressed; run last b / update for the full output
[error] (b / update) sbt.librarymanagement.ResolveException: Error downloading a:a_2.13:0.1.0-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /Users/dev/.ivy2/local/a/a_2.13/0.1.0-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/a/a_2.13/0.1.0-SNAPSHOT/a_2.13-0.1.0-SNAPSHOT.pom
[error] Total time: 1 s, completed Oct 21, 2022, 4:26:40 PM
```

This issue can be worked around by putting Scala-version-specific test dependencies into a separate repository, publishing them and then using `testLibrary.cross(CrossVersion.for2_13Use3) % Test` but this worked in sbt-cross plugin so it should be possible to make it work in sbt-projectmatrix as well. Since sandwich scenario is shown as example this exceptional behavior caught me by surprise.

**Comment by MateuszKubuszok** [comment]
I decided to check again and this time use the setup provided in https://github.com/sbt/sbt-projectmatrix/tree/8d27205428e7da3000cca05a83572292459208f7/src/sbt-test/projectMatrix/jvm-sandwich-sbt-1.3 and modify it a bit (use only 1 version of Scala 3, update Scala 3 and 2.13, use fixed version of sbt-projectmatrix) and run it locally:

```scala
// build.sbt

lazy val check = taskKey[Unit]("")
lazy val scala3 = "3.3.1"
lazy val scala213 = "2.13.12"

lazy val fooApp = (projectMatrix in file("foo-app"))
  .dependsOn(fooCore)
  .settings(
    name := "foo app",
  )
  .jvmPlatform(scalaVersions = Seq(scala3))

lazy val fooApp3 = fooApp.jvm(scala3)
  .settings(
    test := { () },
  )

lazy val fooCore = (projectMatrix in file("foo-core"))
  .settings(
    name := "foo core",
  )
  .jvmPlatform(scalaVersions = Seq(scala213, "2.12.18"))

lazy val barApp = (projectMatrix in file("bar-app"))
  .dependsOn(barCore)
  .settings(
    name := "bar app",
  )
  .jvmPlatform(scalaVersions = Seq(scala213))

lazy val barCore = (projectMatrix in file("bar-core"))
  .settings(
    name := "bar core",
  )
  .jvmPlatform(scalaVersions = Seq(scala3))

// choose 2.13 when bazCore offers both 2.13 and Dotty
lazy val bazApp = (projectMatrix in file("baz-app"))
  .dependsOn(bazCore)
  .settings(
    name := "baz app",
    check := {
      val cp = (Compile / fullClasspath).value
        .map(_.data.getName)

      assert(cp.contains("baz-core_2.13-0.1.0-SNAPSHOT.jar"), s"$cp")
      assert(!cp.contains("baz-core_3.3.1-0.1.0-SNAPSHOT.jar"), s"$cp")
    },
  )
  .jvmPlatform(scalaVersions = Seq(scala213))

lazy val bazCore = (projectMatrix in file("baz-core"))
  .settings(
    name := "baz core",
    exportJars := true,
  )
  .jvmPlatform(scalaVersions = Seq(scala213, scala3))
```

```
project/plugins.sbt
addSbtPlugin("com.eed3si9n" % "sbt-projectmatrix" % "0.9.1")
```

```
sbt.version = 1.9.6
```

then I run `update` command which fails for me in my setups:

```
sbt update
[info] welcome to sbt 1.9.6 (Amazon.com Inc. Java 17.0.7)
[info] loading settings for project global-plugins from plugins.sbt,sonatype.sbt ...
[info] loading global plugins from /Users/dev/.sbt/1.0/plugins
[info] loading settings for project toscik-build from plugins.sbt ...
[info] loading project definition from /Users/dev/Workspaces/GitHub/toscik/project
[info] loading settings for project toscik from build.sbt ...
[info] set current project to toscik (in build file:/Users/dev/Workspaces/GitHub/toscik/)
[info] Updating
[info] Resolved  dependencies
[warn]
[warn] 	Note: Unresolved dependencies path:
[info] Updating
[info] Resolved  dependencies
[warn]
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading bar-core:bar-core_2.13:0.1.0-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /Users/dev/.ivy2/local/bar-core/bar-core_2.13/0.1.0-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/bar-core/bar-core_2.13/0.1.0-SNAPSHOT/bar-core_2.13-0.1.0-SNAPSHOT.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:344)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:313)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:313)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:60)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:134)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:74)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:147)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:147)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:128)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:220)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:161)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3801)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.Execute.work(Execute.scala:292)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:833)
[error] sbt.librarymanagement.ResolveException: Error downloading foo-core:foo-core_3:0.1.0-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /Users/dev/.ivy2/local/foo-core/foo-core_3/0.1.0-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/foo-core/foo-core_3/0.1.0-SNAPSHOT/foo-core_3-0.1.0-SNAPSHOT.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:344)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:313)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:313)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:60)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:134)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:74)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:147)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:147)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:128)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:220)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:161)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3801)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.Execute.work(Execute.scala:292)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:833)
[error] (barApp / update) sbt.librarymanagement.ResolveException: Error downloading bar-core:bar-core_2.13:0.1.0-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /Users/dev/.ivy2/local/bar-core/bar-core_2.13/0.1.0-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/bar-core/bar-core_2.13/0.1.0-SNAPSHOT/bar-core_2.13-0.1.0-SNAPSHOT.pom
[error] (fooApp3 / update) sbt.librarymanagement.ResolveException: Error downloading foo-core:foo-core_3:0.1.0-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: /Users/dev/.ivy2/local/foo-core/foo-core_3/0.1.0-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/foo-core/foo-core_3/0.1.0-SNAPSHOT/foo-core_3-0.1.0-SNAPSHOT.pom
[error] Total time: 4 s, completed Oct 18, 2023, 1:30:50 PM
```

This makes me think that sbt sandwich does not work at all. I suspect that it wasn't caught by tests because they only try to start sbt console without trying to run any command. That's why I am changing the title of the issue.

**Comment by eed3si9n** [comment]
ok, so this sounds like a bug in sbt itself.

**Comment by eed3si9n** [comment]
Here's a PR to repro this on CI - https://github.com/sbt/sbt-projectmatrix/pull/84

**Comment by eed3si9n** [comment]
I have a PR for this here - https://github.com/sbt/sbt/pull/7907. I can probably backport it to sbt 1.x

**Comment by MateuszKubuszok** [comment]
It would be great!

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt-projectmatrix/pull/97
