### ISSUE TITLE
Regression: sbt 1.9.4 or newer fails to download artifacts from custom maven repo

### ISSUE THREAD

**Issue by mims-github** [sbt/sbt#7407]
## steps

1. Run `sbt update` with the following `build.sbt` and sbt version 1.9.4 or latest 1.9.6.

```
ThisBuild / resolvers ++= List(
  "Atlassian Public" at "https://packages.atlassian.com/mvn/maven-external"
)

lazy val p = project.settings(
	libraryDependencies += "com.atlassian.sal"     % "sal-api"                       % "4.6.2"
)
```

## problem
`sbt update` fails with:
```
[info] welcome to sbt 1.9.4 (Eclipse Adoptium Java 17.0.8)
.....
[error] lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[error] https://packages.atlassian.com/mvn/maven-external/com/atlassian/sal/sal-api/4.6.2/sal-api-4.6.2.atlassian-plugin: not found: https://packages.atlassian.com/mvn/maven-external/com/atlassian/sal/sal-api/4.6.2/sal-api-4.6.2.atlassian-plugin
[error] 
[error] 	at lmcoursier.internal.shaded.coursier.Artifacts$.$anonfun$fetchArtifacts$9(Artifacts.scala:365)
[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.wrap(Task.scala:82)
[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
[error] 	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:833)
[error] Caused by: lmcoursier.internal.shaded.coursier.cache.ArtifactError$NotFound: not found: https://packages.atlassian.com/mvn/maven-external/com/atlassian/sal/sal-api/4.6.2/sal-api-4.6.2.atlassian-plugin
[error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader.checkErrFile$1(Downloader.scala:471)
[error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader.$anonfun$shouldDownload$16(Downloader.scala:518)
[error] 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[error] 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[error] 	at scala.util.Success.map(Try.scala:213)
[error] 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[error] 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:833)
[error] (p / update) lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[error] https://packages.atlassian.com/mvn/maven-external/com/atlassian/sal/sal-api/4.6.2/sal-api-4.6.2.atlassian-plugin: not found: https://packages.atlassian.com/mvn/maven-external/com/atlassian/sal/sal-api/4.6.2/sal-api-4.6.2.atlassian-plugin
```

## expectation

Works with sbt 1.9.3 or older.

## notes

Probably the [corresponding pom](https://packages.atlassian.com/content/groups/public/com/atlassian/sal/sal-api/4.6.2/sal-api-4.6.2.pom) with the tag `<package>atlassian-plugin</package>` confuses latest sbt/coursier version?

Seems that with 1.9.4 coursier got updated from 2.1.0 to 2.1.1 with these changes: https://github.com/coursier/coursier/compare/v2.1.0...v2.1.1

Thanks for having a look.
And let me know, if I help with anything else.

**Comment by eed3si9n** [comment]
@mims-github Thanks for the report. Apart of shading, we use Coursier code as-is, so could you also report this to coursier/coursier repo as well? In the meantime, could it be worked around using excludes?

**Comment by mims-github** [comment]
Thanks, will do.

I just tried with using excludes, but could not work around it. But probably because I could not figure out, how to specify an exclusion based on extension `atlassian-plugin`. How would that look like?

But I just found out, that adding `withSources()` or also `jar()` clause makes it work. :)
I guess sbt then is asking more precisely what artifacts it needs, and coursier does not need to parse and interpret the "broken"/nonconform pom from the repository?
