### ISSUE TITLE
`run` task does not fail if throw `LinkageError`

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt#7408]
### `Main.scala`

```scala
package example

object Main {
  def main(args: Array[String]): Unit = {
    throw new LinkageError
  }
}
```

### `project/build.properties`

```properties
sbt.version=1.9.6
```

`sbt run`

## problem

```
[info] running example.Main 
Exception in thread "sbt-bg-threads-6" java.lang.LinkageError
	at example.Main$.main(Main.scala:5)
	at example.Main.main(Main.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at sbt.Run.invokeMain(Run.scala:144)
	at sbt.Run.execute$1(Run.scala:94)
	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:121)
	at sbt.Run$.executeSuccess(Run.scala:187)
	at sbt.Run.runWithLoader(Run.scala:121)
	at sbt.Defaults$.$anonfun$bgRunTask$6(Defaults.scala:1988)
	at sbt.Defaults$.$anonfun$termWrapper$2(Defaults.scala:1927)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:367)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
[success] Total time: 0 s, completed Oct 21, 2023, 1:23:54 AM
```

## expectation

`run` task should fail

## notes

 workaround: set `run / fork := true`

**Comment by xuwei-k** [comment]
- https://github.com/sbt/sbt/issues/6852 same issue ? 🤔

**Comment by xuwei-k** [comment]
sbt 1.5.7

```
[error] (run-main-0) java.lang.LinkageError
[error] java.lang.LinkageError
[error] 	at example.Main$.main(Main.scala:5)
[error] 	at example.Main.main(Main.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] stack trace is suppressed; run last Compile / bgRun for the full output
[error] Nonzero exit code: 1
[error] (Compile / run) Nonzero exit code: 1
```

**Comment by mkdev5** [comment]
@eed3si9n can you close the issue?
