### ISSUE TITLE
[BUG] Updating SBT from 1.9.2 to 1.9.5 breaks the build

### ISSUE THREAD

**Issue by REASY** [sbt/sbt#7430]
## steps
1. Clone https://github.com/REASY/jai-core-breakage-during-sbt-update
2. Run `sbt ";clean;compile" and verify it succeeds
3. Modify project/build.properties and update SBT to 1.9.5
4. Run `sbt ";clean;compile" and see it fails with the error below
```
sbt ";clean;compile"
[info] [launcher] getting org.scala-sbt sbt 1.9.5  (this may take some time)...
[info] welcome to sbt 1.9.5 (Ubuntu Java 11.0.20.1)
[info] loading global plugins from /home/artavazd.balaian/.sbt/1.0/plugins
[info] loading settings for project scala-json-benchmark-build from plugins.sbt ...
[info] loading project definition from /home/artavazd.balaian/work/github/REASY/scala-json-benchmark/project
[info] loading settings for project scala-json-benchmark from build.sbt ...
[info] set current project to jai-core-breakage-during-sbt-update (in build file:/home/artavazd.balaian/work/github/REASY/scala-json-benchmark/)
[success] Total time: 0 s, completed Nov 10, 2023, 9:27:04 PM
[info] Updating
https://repo1.maven.org/maven2/org/scala-lang/scala2-sbt-bridge/2.13.12/scala2-sbt-bridge-2.13.12.pom
  100.0% [##########] 1.9 KiB (1.3 KiB / s)
[info] Resolved  dependencies
[info] Fetching artifacts of
[info] Fetched artifacts of
[error] lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[error] https://repo1.maven.org/maven2/javax/media/jai_core/1.1.3/jai_core-1.1.3.jar: not found: https://repo1.maven.org/maven2/javax/media/jai_core/1.1.3/jai_core-1.1.3.jar
[error]
[error]         at lmcoursier.internal.shaded.coursier.Artifacts$.$anonfun$fetchArtifacts$9(Artifacts.scala:365)
[error]         at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
[error]         at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
[error]         at lmcoursier.internal.shaded.coursier.util.Task$.wrap(Task.scala:82)
[error]         at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
[error]         at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
[error]         at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
[error]         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:829)
[error] Caused by: lmcoursier.internal.shaded.coursier.cache.ArtifactError$NotFound: not found: https://repo1.maven.org/maven2/javax/media/jai_core/1.1.3/jai_core-1.1.3.jar
[error]         at lmcoursier.internal.shaded.coursier.cache.internal.Downloader.checkErrFile$1(Downloader.scala:471)
[error]         at lmcoursier.internal.shaded.coursier.cache.internal.Downloader.$anonfun$shouldDownload$16(Downloader.scala:518)
[error]         at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[error]         at scala.util.Success.$anonfun$map$1(Try.scala:255)
[error]         at scala.util.Success.map(Try.scala:213)
[error]         at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[error]         at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[error]         at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[error]         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:829)
[error] (update) lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[error] https://repo1.maven.org/maven2/javax/media/jai_core/1.1.3/jai_core-1.1.3.jar: not found: https://repo1.maven.org/maven2/javax/media/jai_core/1.1.3/jai_core-1.1.3.jar
[error] Total time: 8 s, completed Nov 10, 2023, 9:27:12 PM

```
## problem

It is true that on that link, https://repo1.maven.org/maven2/javax/media/jai_core/1.1.3/jai_core-1.1.3.jar:,  there is no JAR file
```
 date && curl  https://repo1.maven.org/maven2/javax/media/jai_core/1.1.3/jai_core-1.1.3.jar
Fri Nov 10 09:34:48 PM +08 2023
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
```
But it is available at https://nexus.geomatys.com/repository/geotoolkit/javax/media/jai_core/1.1.3/jai_core-1.1.3.jar and https://nexus.geomatys.com/repository/geotoolkit was added as "Geomatys" resolver, https://github.com/REASY/jai-core-breakage-during-sbt-update/blob/main/build.sbt#L11
```
date && curl https://nexus.geomatys.com/repository/geotoolkit/javax/media/jai_core/1.1.3/jai_core-1.1.3.jar
Fri Nov 10 09:40:15 PM +08 2023
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
```

## expectation

I guess patch update in terms of SemVer shall not break build.

### sbt -v
```
sbt -v
[sbt_options] declare -a sbt_options=()
[process_args] java_version = '11'
[copyRt] java9_rt = '/home/artavazd.balaian/.sbt/1.0/java9-rt-ext-ubuntu_11_0_20_1/rt.jar'
# Executing command line:
java
-Dfile.encoding=UTF-8
-Xms1024m
-Xmx1024m
-Xss4M
-XX:ReservedCodeCacheSize=128m
-Dsbt.script=/home/artavazd.balaian/.cache/coursier/arc/https/github.com/sbt/sbt/releases/download/v1.8.3/sbt-1.8.3.zip/sbt/bin/sbt
-Dscala.ext.dirs=/home/artavazd.balaian/.sbt/1.0/java9-rt-ext-ubuntu_11_0_20_1
-jar
/home/artavazd.balaian/.cache/coursier/arc/https/github.com/sbt/sbt/releases/download/v1.8.3/sbt-1.8.3.zip/sbt/bin/sbt-launch.jar

[info] welcome to sbt 1.9.5 (Ubuntu Java 11.0.20.1)
```

### sbt -version
```
sbt -version
sbt version in this project: 1.9.5
sbt script version: 1.8.3
```

**Comment by SethTisue** [comment]
how about 1.9.7? 1.9.5 isn't the current version anymore.

do you believe there is a bug in sbt here? if so, what do you claim is the bug, exactly?

is the problem reproducible with just Coursier, or is sbt itself actually needed to demonstrate the problem? (sbt uses Coursier for artifact resolution.)

**Comment by eed3si9n** [comment]
See https://repo1.maven.org/maven2/javax/media/jai_core/1.1.3/.
The problem is that they've managed to publish the POM file, but not the JAR. You can argue your case with coursier/coursier, but I'd say the problem is with Maven Central (at least that slice of Maven Central), not us.

**Comment by REASY** [comment]
Thanks for the reply, @SethTisue @eed3si9n 

@SethTisue with SBT 1.9.7 it produces the same error:
```
sbt ";clean;compile"
[info] welcome to sbt 1.9.7 (Ubuntu Java 11.0.20.1)
[info] loading global plugins from /home/artavazd.balaian/.sbt/1.0/plugins
[info] loading settings for project scala-json-benchmark-build from plugins.sbt ...
[info] loading project definition from /home/artavazd.balaian/work/github/REASY/scala-json-benchmark/project
[info] loading settings for project scala-json-benchmark from build.sbt ...
[info] set current project to jai-core-breakage-during-sbt-update (in build file:/home/artavazd.balaian/work/github/REASY/scala-json-benchmark/)
[success] Total time: 0 s, completed Nov 11, 2023, 7:59:17 PM
[error] lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[error] https://repo1.maven.org/maven2/javax/media/jai_core/1.1.3/jai_core-1.1.3.jar: not found: https://repo1.maven.org/maven2/javax/media/jai_core/1.1.3/jai_core-1.1.3.jar
[error]
[error]         at lmcoursier.internal.shaded.coursier.Artifacts$.$anonfun$fetchArtifacts$9(Artifacts.scala:365)
[error]         at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
[error]         at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
[error]         at lmcoursier.internal.shaded.coursier.util.Task$.wrap(Task.scala:82)
[error]         at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
[error]         at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
[error]         at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
[error]         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:829)
[error] Caused by: lmcoursier.internal.shaded.coursier.cache.ArtifactError$NotFound: not found: https://repo1.maven.org/maven2/javax/media/jai_core/1.1.3/jai_core-1.1.3.jar
[error]         at lmcoursier.internal.shaded.coursier.cache.internal.Downloader.checkErrFile$1(Downloader.scala:471)
[error]         at lmcoursier.internal.shaded.coursier.cache.internal.Downloader.$anonfun$shouldDownload$16(Downloader.scala:518)
[error]         at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[error]         at scala.util.Success.$anonfun$map$1(Try.scala:255)
[error]         at scala.util.Success.map(Try.scala:213)
[error]         at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[error]         at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[error]         at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[error]         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:829)
[error] (update) lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[error] https://repo1.maven.org/maven2/javax/media/jai_core/1.1.3/jai_core-1.1.3.jar: not found: https://repo1.maven.org/maven2/javax/media/jai_core/1.1.3/jai_core-1.1.3.jar
[error] Total time: 0 s, completed Nov 11, 2023, 7:59:17 PM
````
Though it does work with SBT 1.9.2 and this is what confuses me. Probably some internal changes were in Coursier or elsewhere. From the perspective of a typical SBT user it a bit suprising.

Thanks.

**Comment by REASY** [comment]
I ended-up excluding javax.media:jai_core from GeoTools, it helped https://github.com/REASY/jai-core-breakage-during-sbt-update/commit/776e0ddc65d630be9fc31f90b32609fd881a468e

Thanks.

**Comment by SethTisue** [comment]
> Probably some internal changes were in Coursier or elsewhere

(exactly — Coursier is where I would suggest looking if you decide to try to uncover the root cause)

**Comment by danicheg** [comment]
@SethTisue as you may hold the context, was that issue investigated somewhere? It's still reproducing...

**UPD**. No need to answer, I found that it won't be fixed https://github.com/coursier/coursier/issues/2942#issuecomment-2145674637
