### ISSUE TITLE
Do not try to overwrite and fail if the same cached file is being produced

### ISSUE THREAD

**Issue by regiskuckaertz** [sbt/sbt#7439]
## steps

- setup an S3 bucket with object lock enabled
- setup a remote cache to use that bucket with [the fm-sbt-s3-resolver plugin](https://github.com/tpunder/fm-sbt-s3-resolver) 
- run `sbt pullRemoteCache compile pushRemoteCache` twice

## problem

even if the output content is the same, sbt will try to upload and overwrite the file, giving some hints as to what to do about it:

```
[error] java.io.IOException: PUT operation failed because the destination file exists and overwriting is disabled:
[error]     source     : /.../project/scalatest-kit/target/scala-2.13/scalatest-kit_2.13-local-cached-compile.jar
[error]     destination: s3://.../com/pirum/scalatest-kit_2.13/0.0.0-fcbd95e8a47846f5/scalatest-kit_2.13-0.0.0-fcbd95e8a47846f5-cached-compile.jar
[error] If you have a staging repository that has failed, drop it and start over.
[error] Otherwise fix the double publishing, or relax the setting as follows:
[error]     publishConfiguration := publishConfiguration.value.withOverwrite(true)
[error]     publishLocalConfiguration := publishLocalConfiguration.value.withOverwrite(true)
[error] 
[error] If you have a remote cache repository, you can enable overwriting as follows:
[error]     pushRemoteCacheConfiguration := pushRemoteCacheConfiguration.value.withOverwrite(true)
```

## expectation

I would argue that since the hash is the same and overwrite is `false`, then SBT should _not_ try to overwrite the file and just report it.

## notes

We have put an object lock upon request by our security team, so we cannot allow overwrite in our case.

**Comment by regiskuckaertz** [comment]
do you agree @eed3si9n ?

**Comment by eed3si9n** [comment]
Yea. Likely this is more of an sbt matter, so I suggest we move transfer this to sbt/sbt, but I agree with the expectation of the issue.

**Comment by regiskuckaertz** [comment]
That makes sense. Happy to contribute a PR (not before end of next week), I'll try to find my way around.

**Comment by regiskuckaertz** [comment]
@eed3si9n I had a look at the code and I can see this is an exception thrown [here](https://github.com/sbt/librarymanagement/blob/54011d5e74335bab229bc3f6532b6a1ca6d0d5cd/ivy/src/main/scala/sbt/internal/librarymanagement/ConvertResolver.scala#L437), so I guess the plan would be to catch that somewhere upstream, I'm just not sure where exactly. Would you be able to point me to it please?

**Comment by eed3si9n** [comment]
The push code is using Ivy publish - https://github.com/sbt/sbt/blob/cfe0fc8e2ee3c551389fc24d836b04764e9a2e2b/main/src/main/scala/sbt/internal/RemoteCache.scala#L204-L210, so I guess we can catch there?

**Comment by regiskuckaertz** [comment]
Yep, that seems like the best place. Thanks, I'll raise an MR for this change.

**Comment by minchowang** [comment]
@eed3si9n Hi, When we uset the sbt 1.6.2 and set 
```java
publishConfiguration := publishConfiguration.value.withOverwrite(true)
publishLocalConfiguration := publishLocalConfiguration.value.withOverwrite(true)
```

the issues exiting yet.
```java
[error] Caused by: java.io.IOException: destination file exists and overwrite == false
[error]         at sbt.internal.librarymanagement.ConvertResolver$LocalIfFileRepo.put(ConvertResolver.scala:373)
[error]         at org.apache.ivy.plugins.repository.AbstractRepository.put(AbstractRepository.java:130)
[error]         at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put(ConvertResolver.scala:118)
[error]         at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put$(ConvertResolver.scala:105)
[error]         at sbt.internal.librarymanagement.ConvertResolver$$anonfun$defaultConvert$lzycompute$1$PluginCapableResolver$1.put(ConvertResolver.scala:165)
[error]         at org.apache.ivy.plugins.resolver.RepositoryResolver.publish(RepositoryResolver.java:216)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5(IvyActions.scala:504)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error]         at scala.util.Try$.apply(Try.scala:213)
[error]         at sbt.internal.librarymanagement.IvyUtil$.retryWithBackoff(IvyUtil.scala:22)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$4(IvyActions.scala:503)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$4$adapted(IvyActions.scala:501)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:943)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error]         at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:501)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$3(IvyActions.scala:143)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error]         at sbt.internal.librarymanagement.IvyActions$.withChecksums(IvyActions.scala:157)
[error]         at sbt.internal.librarymanagement.IvyActions$.withChecksums(IvyActions.scala:150)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$1(IvyActions.scala:143)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$1$adapted(IvyActions.scala:133)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:251)
[error]         at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:215)
[error]         at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:77)
[error]         at sbt.internal.librarymanagement.IvySbt$$anon$1.call(Ivy.scala:87)
[error]         at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:113)
[error]         at xsbt.boot.Locks$GlobalLock.withChannelRetries$1(Locks.scala:91)
[error]         at xsbt.boot.Locks$GlobalLock.$anonfun$withFileLock$1(Locks.scala:119)
[error]         at xsbt.boot.Using$.withResource(Using.scala:12)
[error]         at xsbt.boot.Using$.apply(Using.scala:9)
[error]         at xsbt.boot.Locks$GlobalLock.withFileLock(Locks.scala:119)
[error]         at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:71)
[error]         at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:59)
[error]         at xsbt.boot.Locks$.apply0(Locks.scala:47)
[error]         at xsbt.boot.Locks$.apply(Locks.scala:36)
[error]         at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:87)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:209)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:206)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:250)
[error]         at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:133)
[error]         at sbt.Classpaths$.$anonfun$publishTask$4(Defaults.scala:3556)
[error]         at sbt.Classpaths$.$anonfun$publishTask$4$adapted(Defaults.scala:3549)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:829)
[error] (libShadedCommonDependencies / publishM2) java.io.IOException: PUT operation failed because the destination file exists and overwriting is disabled:
[error]     source     : /Users/xxxxxx.pom
[error]     destination: file:/Users/xxxxx.pom
[error] If you have a staging repository that has failed, drop it and start over.
[error] Otherwise fix the double publishing, or relax the setting as follows:
[error]     publishConfiguration := publishConfiguration.value.withOverwrite(true)
[error]     publishLocalConfiguration := publishLocalConfiguration.value.withOverwrite(true)
[error] 
[error] If you have a remote cache repository, you can enable overwriting as follows:
[error]     pushRemoteCacheConfiguration := pushRemoteCacheConfiguration.value.withOverwrite(true)
[error] Total time: 0 s, completed 2024年8月1日 下午2:19:57

```

**Comment by karlveezoo** [comment]
@regiskuckaertz Hi, did you get anywhere with this one? I also found it quite annoying to get these large stack traces if it cannot overwrite a cache that is identical
