### ISSUE TITLE
run/fork-loader seems unstable

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#7443]
## steps

See https://github.com/sbt/sbt/pull/7441, which updates Zinc.

```
scripted run/fork-loader 
```

## problem

```
[info] Running run/fork-loader
[info] [info] welcome to sbt 1.9.7-SNAPSHOT (Eclipse Adoptium Java 17.0.9)
[info] [info] loading settings for project global-plugins from metals.sbt ...
[info] [info] loading global plugins from /tmp/sbt_caa5a219/global/plugins
[info] [info] loading settings for project root from build.sbt ...
[info] [info] set current project to forked-test (in build file:/tmp/sbt_caa5a219/)
[info] [info] compiling 1 Scala source to /tmp/sbt_caa5a219/target/scala-2.12/classes ...
[info] [info] done compiling
[info] [info] running CheckLoader 
[info] [error] java.lang.AssertionError: assertion failed: Application classes not loaded in the system class loader
[info] [error] 	at scala.Predef$.assert(Predef.scala:223)
[info] [error] 	at CheckLoader$.apply(CheckLoader.scala:6)
[info] [error] 	at CheckLoader$.main(CheckLoader.scala:2)
[info] [error] 	at CheckLoader.main(CheckLoader.scala)
[info] [error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info] [error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[info] [error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info] [error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[info] [error] stack trace is suppressed; run last Compile / run for the full output
[info] [error] (Compile / run) java.lang.AssertionError: assertion failed: Application classes not loaded in the system class loader
[info] [error] Total time: 0 s, completed Nov 27, 2023, 7:17:49 PM
[info] [info] compiling 2 Scala sources to /tmp/sbt_caa5a219/target/scala-2.12/test-classes ...
[info] [info] done compiling
[info] [info] ! Forked loader.Loaded from application loader: Exception raised on property evaluation.
[info] [info] > Exception: java.lang.AssertionError: assertion failed: Application classes not loaded in the system class loader
[info] [info] Failed: Total 1, Failed 0, Errors 1, Passed 0
[info] [error] Error during tests:
[info] [error] 	TestForked
[info] [error] (Test / test) sbt.TestsFailedException: Tests unsuccessful
[info] [error] Total time: 0 s, completed Nov 27, 2023, 7:17:49 PM
[info] [info] shutting down sbt server
Error:  x run/fork-loader 
Error:   Cause of test exception: {line 4}  Command failed
```

## expectation

I am not sure if the test failure is catching underlying issue in our code or some other parameter.

**Comment by atoz96** [comment]
Hi, @eed3si9n 
Can I contribute to this issue?

**Comment by eed3si9n** [comment]
Unless you have a pretty solid reproduction, I'd advise against this issue for the first contribution.

**Comment by dev-miro26** [comment]
Okay, thank you for your advice.
Thanks again! 👍

**Comment by atoz96** [comment]
Hi @eed3si9n 
Thanks
