### ISSUE TITLE
NullPointerException when start sbt-launch.jar sbt 1.9.8

### ISSUE THREAD

**Issue by laglangyue** [sbt/sbt#7472]
## steps

found on `scalikejdbc`, sbt 1.9.7 is ok , but use sbt 1.9.8, it will cause a npe
(1) git clone https://github.com/scalikejdbc/scalikejdbc-sandbox.git
(2) open this repo in idea, and env : java8(java 11, java 17) , mint linux21. Jdk and sbt installed by sdkman

## problem

java.lang.NullPointerException
can't start sbt-launch.jar

## expectation

```shell
Picked up JAVA_TOOL_OPTIONS: -Duser.language=en
java.lang.NullPointerException
	at sun.net.util.URLUtil.urlNoFragString(URLUtil.java:50)
	at sun.misc.URLClassPath.getLoader(URLClassPath.java:523)
	at sun.misc.URLClassPath.getNextLoader(URLClassPath.java:495)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:249)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:405)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:405)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:405)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:405)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:53)
	at sbt.xMain.run(Main.scala:47)
	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
	at xsbt.boot.Launch$.run(Launch.scala:149)
	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
	at xsbt.boot.Launch$.launch(Launch.scala:159)
	at xsbt.boot.Launch$.apply(Launch.scala:44)
	at xsbt.boot.Launch$.apply(Launch.scala:21)
	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
	at xsbt.boot.Boot$.run(Boot.scala:73)
	at xsbt.boot.Boot$.main(Boot.scala:21)
	at xsbt.boot.Boot.main(Boot.scala)
[error] [launcher] error during sbt launcher: java.lang.NullPointerException

```

**Comment by eed3si9n** [comment]
https://github.com/scalikejdbc/scalikejdbc-cookbook.git doesn't look like a repo with any sbt build. Is there a repro step that doesn't involve IntelliJ?

**Comment by laglangyue** [comment]
> https://github.com/scalikejdbc/scalikejdbc-cookbook.git doesn't look like a repo with any sbt build. Is there a repro step that doesn't involve IntelliJ?

it's https://github.com/scalikejdbc/scalikejdbc-sandbox.git,my mistake. Indeed, any project will generate this error, is it because of the idea.

**Comment by laglangyue** [comment]
![image](https://github.com/sbt/sbt/assets/35491928/ad1aa87b-0a89-4b30-ba08-e7545ab0d5eb)

**Comment by eed3si9n** [comment]
It's hard to tell what's causing what problem, but I'd suggest updating Scala plugin to the latest and if the problem persists, filing an issue with them as well.

**Comment by laglangyue** [comment]
> It's hard to tell what's causing what problem, but I'd suggest updating Scala plugin to the latest and if the problem persists, filing an issue with them as well.

idea and idea-scala-plugin are all  latest.
thanks for your answer, hope to keep this issue some time , I will close it on this Sunday if there's no clue yet.
