### ISSUE TITLE
A question about the “sbt stage” command

### ISSUE THREAD

**Issue by 1201wen** [sbt/sbt#7483]
The following error is reported when using the “sbt stage” command. The sbt version used is 1.9.8 and the scala version is 2.13.12. It is the first time to use it. How to deal with the following situation?
```
[info] Resolved  dependencies
[warn] 
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.github.sbt:sbt-findbugs:2.0.0 (sbtVersion=1.0, scalaVersion=2.12)
[warn] 		com.dwijnand:sbt-dynver:4.1.1 (sbtVersion=1.0, scalaVersion=2.12)
[warn] 
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.github.sbt:sbt-findbugs;sbtVersion=1.0;scalaVersion=2.12:2.0.0
[error]   Not found
[error]   Not found
[error]   not found: /home/wen/.ivy2/localcom.github.sbt/sbt-findbugs/scala_2.12/sbt_1.0/2.0.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/github/sbt/sbt-findbugs_2.12_1.0/2.0.0/sbt-findbugs-2.0.0.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-releases/com/github/sbt/sbt-findbugs_2.12_1.0/2.0.0/sbt-findbugs-2.0.0.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/github/sbt/sbt-findbugs_2.12_1.0/2.0.0/sbt-findbugs-2.0.0.pom
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.github.sbt/sbt-findbugs/2.0.0/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.github.sbt/sbt-findbugs/2.0.0/ivys/ivy.xml
[error] Error downloading com.dwijnand:sbt-dynver;sbtVersion=1.0;scalaVersion=2.12:4.1.1
[error]   Not found
[error]   Not found
[error]   not found: /home/wen/.ivy2/localcom.dwijnand/sbt-dynver/scala_2.12/sbt_1.0/4.1.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/dwijnand/sbt-dynver_2.12_1.0/4.1.1/sbt-dynver-4.1.1.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-releases/com/dwijnand/sbt-dynver_2.12_1.0/4.1.1/sbt-dynver-4.1.1.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/dwijnand/sbt-dynver_2.12_1.0/4.1.1/sbt-dynver-4.1.1.pom
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.dwijnand/sbt-dynver/4.1.1/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.dwijnand/sbt-dynver/4.1.1/ivys/ivy.xml
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:344)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:313)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:313)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:59)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3801)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[error] 	at java.base/java.lang.Thread.run(Thread.java:1589)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.github.sbt:sbt-findbugs;sbtVersion=1.0;scalaVersion=2.12:2.0.0
[error]   Not found
[error]   Not found
[error]   not found: /home/wen/.ivy2/localcom.github.sbt/sbt-findbugs/scala_2.12/sbt_1.0/2.0.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/github/sbt/sbt-findbugs_2.12_1.0/2.0.0/sbt-findbugs-2.0.0.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-releases/com/github/sbt/sbt-findbugs_2.12_1.0/2.0.0/sbt-findbugs-2.0.0.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/github/sbt/sbt-findbugs_2.12_1.0/2.0.0/sbt-findbugs-2.0.0.pom
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.github.sbt/sbt-findbugs/2.0.0/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.github.sbt/sbt-findbugs/2.0.0/ivys/ivy.xml
[error] Error downloading com.dwijnand:sbt-dynver;sbtVersion=1.0;scalaVersion=2.12:4.1.1
[error]   Not found
[error]   Not found
[error]   not found: /home/wen/.ivy2/localcom.dwijnand/sbt-dynver/scala_2.12/sbt_1.0/4.1.1/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/dwijnand/sbt-dynver_2.12_1.0/4.1.1/sbt-dynver-4.1.1.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-releases/com/dwijnand/sbt-dynver_2.12_1.0/4.1.1/sbt-dynver-4.1.1.pom
[error]   not found: https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/dwijnand/sbt-dynver_2.12_1.0/4.1.1/sbt-dynver-4.1.1.pom
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.dwijnand/sbt-dynver/4.1.1/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.dwijnand/sbt-dynver/4.1.1/ivys/ivy.xml
```

**Comment by SethTisue** [comment]
https://www.scala-sbt.org/community suggests places to ask questions.

Open a bug if you become convinced a bug in sbt is the root cause of your issue, and if you can substantiate the claim.

**Comment by SethTisue** [comment]
`stage` isn't even part of sbt; it comes from a plugin. So if there were a bug, you'd need to report it against the plugin, not against sbt itself.
