### ISSUE TITLE
sbt doesn't seem to follow 307 redirects

### ISSUE THREAD

**Issue by nickorr-plusone** [sbt/sbt#7581]
## steps

using sbt 1.9.x / play framework 3.x / aws codeartifact / scala 2.13.x

credentials / resolvers are setup correctly for code artifact (I can see from the logs the request and I've confirmed with aws support)

library dependency in codeartifact

```scala
libraryDependencies ++= Seq(
  guice,
  javaJdbc,
  javaWs,
  "net.plusonesolutions" % "plusone-tazworks" % "1.1"
)
```

## problem

We have a private artifact repository (aws codeartifact) that we are unable to pull artifacts from because the response from the repository is a 307 redirect and sbt isn't following the redirect.

```
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading net.plusonesolutions:plusone-tazworks:1.1
[error]   forbidden: https://x.d.codeartifact.us-west-2.amazonaws.com/maven/redacted/plusone-tazworks/1.1/plusone-tazworks-1.1.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:344)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:313)
```

Using chrome I can see the request is being sent a 307 and I can download correctly
![image](https://github.com/sbt/sbt/assets/40372803/495cccef-3301-473c-8867-226dacafa0b3)

## expectation

sbt should follow redirects

**Comment by eed3si9n** [comment]
@nickorr-plusone Thanks for the report. sbt uses Coursier as the dependency resolver, and likely the downloading is their implementation detail. Could you report this to coursier/coursier as well, to get their attention please?

**Comment by eed3si9n** [comment]
Closing this as won't fix, at least from sbt/sbt side.
