### ISSUE TITLE
`publishLocal` on the zinc module outputs error

### ISSUE THREAD

**Issue by SlowBrainDude** [sbt/sbt#7608]
## steps

Run `publishLocal` on a fresh checkout of the zinc module on the default branch.

## problem

The build process outputs an error:

```
[error] stack trace is suppressed; run last compilerBridge2_10 / update for the full output
[error] (compilerBridge2_10 / update) sbt.librarymanagement.ResolveException: Error downloading org.scalameta:semanticdb-scalac_2.10.7:4.9.7
[error]   Not found
[error]   Not found
[error]   not found: /home/me/.ivy2/local/org.scalameta/semanticdb-scalac_2.10.7/4.9.7/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.10.7/4.9.7/semanticdb-scalac_2.10.7-4.9.7.pom
[error] Total time: 162 s (02:42), completed 20.07.2024, 04:10:25
sbt:zinc Root>
```
Running `last compilerBridge2_10 / update` gives:

```
sbt:zinc Root> last compilerBridge2_10 / update
[debug] not up to date. inChanged = true, force = false
[debug] Updating compilerBridge2_10...
[info] Updating compiler-bridge_2.10
[info] Resolved compiler-bridge_2.10 dependencies
[warn]
[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading org.scalameta:semanticdb-scalac_2.10.7:4.9.7
[error]   Not found
[error]   Not found
[error]   not found: /home/me/.ivy2/local/org.scalameta/semanticdb-scalac_2.10.7/4.9.7/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.10.7/4.9.7/semanticdb-scalac_2.10.7-4.9.7.pom
[error]         at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:346)
[error]         at lmcoursier.CoursierDependencyResolution.$anonfun$update$39(CoursierDependencyResolution.scala:315)
[error]         at scala.util.Either$LeftProjection.map(Either.scala:573)
[error]         at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:315)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:60)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:142)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:74)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:144)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:131)
[error]         at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:220)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:169)
[error]         at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3867)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error]         at sbt.Execute.work(Execute.scala:292)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error]         at java.base/java.lang.Thread.run(Thread.java:840)
[error] (compilerBridge2_10 / update) sbt.librarymanagement.ResolveException: Error downloading org.scalameta:semanticdb-scalac_2.10.7:4.9.7
[error]   Not found
[error]   Not found
[error]   not found: /home/me/.ivy2/local/org.scalameta/semanticdb-scalac_2.10.7/4.9.7/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.10.7/4.9.7/semanticdb-scalac_2.10.7-4.9.7.pom
sbt:zinc Root>
```

It seems nobody builds any SemanticDB against an outdated Scala version.

## notes

This error seems to not affect building a local SBT version for current Scala versions. That worked fine for me.

Bottom line: Scala 2.10 series is no longer actively maintained since many years. (Last release [7 years ago](https://github.com/scala/scala/releases/tag/v2.10.7), and it would likely not work anymore on current JDKs anyway).

I think SBT should just remove any references to Scala 2.10 at this point. It's dead upstream.

In case this is the right approach to solve this error here I could try to submit a PR. But maybe it has reasons that some 2.10 references are still kept in SBT?

**Comment by eed3si9n** [comment]
Well `semanticdbEnabled` is set to `false` for Zinc on my machine. Do you have Metals plugin that's changing the semantics of the build maybe? If so maybe BSP should be disabled for older compiler bridges?

**Comment by SlowBrainDude** [comment]
OK, it's indeed opening Metals that changes the build. Good catch! :+1: 

So it's not really a SBT bug.

Still not sure what to do with it. It doesn't affect me. But it's ugly.

I'm not sure it makes sense to make Metals, or Bloop, or whatever mechanism adds the build extensions to generate SemanticDB, smarter in a way to avoid to add such extensions to builds targeting Scala 2.10. Looks like quite some work to support an effectively dead Scala version. (It would be a fun plot twist if SBT generates this build addition itself when run as BSP. But I actually don't know who does it. But in that case changes to SBT would be needed… :smile:)

Why does SBT actually carry some Scala 2.10 parts?

**Comment by eed3si9n** [comment]
> Why does SBT actually carry some Scala 2.10 parts?

When sbt 1.x came out Scala 2.10 was still somewhat active, in part as the version that compiled sbt 0.13.
Effectively, Zinc's compile API is the cross-Scala compiler API in the Scala ecosystem, and the compiler bridge, as the name suggest provides the bridge implementation for each Scala version (modern compilers have now in-sourced this bridge to their own repo).

I'm guessing setting `bspEnabled` to false on the compiler bridges would fix this issue.

**Comment by SlowBrainDude** [comment]
> I'm guessing setting bspEnabled to false on the compiler bridges would fix this issue.

Yeah, sure. But that setting was made by the Metals import automatically. So one would need to teach the importer to not set it on 2.10 build targets to avoid any manual intervention.

I've got confused and opened this ticket. Because it looked like a bug to me. "Not touched" code outputs (actually irrelevant) errors. "Not touched" besides opening this folder in an IDE…

Also just disabling BSP would disable IDE features for that whole sub-project, right? A less invasive solution would try to not use SemanticDB on a 2.10 build target, but only there. But I don't even know how to configure that out of the top of my head. Never looked in detail what the "metals.sbt" does. I didn't know until this here that just opening a project in Metals could possibly affect a build at all. (I guess that's a little bit naive of me, as a .sbt file can do "anything" in the end, so there is always the possibility for inference with the rest of the build).

Regardless, I still don't understand why SBT needs to carry this code path with it. The Scala 2.10 compiler will never see any updates as it's unmaintained. So any old compiler bridge already published should suffice, wouldn't it?

Sorry if that questions may sound stupid to you, maybe I just don't understand all fine details of cross building the compiler bridge.

My point just being: Referencing old, not maintained code leads to bit-rot issues sooner or later. Bit rot-like here, where things try to load something that does not exist and confuse people. If there is no good reason to keep this Scala 2.10 support code it should be retired. Less code == less maintenance && less things that could go wrong (which leads to less people opening tickets in the bug-tracker :wink:).

Anyway, I think, as this isn't a SBT bug this ticket can be closed. But I'm not sure weather it would make sense to open a follow up ticket to further discuss removal of the v2.10 compiler bridge from the codebase, or maybe just a PR that explains in the DEV docs that this (meaningless) error may appear after opening the zinc sub-project once in an IDE.

What do you think?

I think "fixing it" by disabling BSP is a worse solution than just documenting the quirk, as the error doesn't affect anything at all, at least if you're not trying to necromance some Scala 2.10 things. Getting rid of a harmless error message for the price of loosing code intelligence in the IDE is not worth it, imho.

---

BTW, and sorry for the quick off-topic question: I've seen your conditional compilation thingy on Reddit. Looks neat! :heart: 

Could it help solve such kind of cross compile issues like the one with the `threadId` from yesterday?

**Comment by eed3si9n** [comment]
> Could it help solve such kind of cross compile issues like the one with the threadId from yesterday?

Not ifdef alone, no, because the problem is that the user on JDK 8 would blow up at runtime. For that, you need a multi-release JAR that can overlay different class files depending on the JDK.

**Comment by SlowBrainDude** [comment]
I don't even know how to construct "a multi-release JAR that can overlay different class files depending on the JDK". But couldn't `ifdef` do that for people like me?

I would imagine a good and easy to understand solution to problems like that one with `threadId` is to have just a "compile time if-else" that asks for compile target and switches two or more variants of the affected block. (Say one with `getId` and one with `threadId`). Under the hood it needs of course to do whatever it take to make this work when used. So most likely create that multi-release JAR in case of the JVM. I guess this would require some build time magic. But I've also heard someone with expert knowledge on builds is said to be here somewhere around... :grin: 

That's how it works for example in C/++, e.g. to switch OS dependent code, or work around different feature support in different compilers. Would be really cool to have that in Scala, too!

But back on topic: You didn't answer my actual question. I've asked for an opinion before I close this here. :slightly_smiling_face: 

Also I'm inclined a little bit to open a ticket about incremental build time of SBT. The iteration cycles are really long for me. It constantly compiles "the whole project" (maybe not the whole, but hundreds of source files). Even when I just change some string literal… This makes my computer fly and takes forever. Adding one line of logs is almost a 10 minute undertaking. Do I do something wrong? Or is there something I could do to speed up things? Or is this just normal in this project and I have to live with it?

**Comment by eed3si9n** [comment]
> Anyway, I think, as this isn't a SBT bug this ticket can be closed. But I'm not sure weather it would make sense to open a follow up ticket to further discuss removal of the v2.10 compiler bridge from the codebase, or maybe just a PR that explains in the DEV docs that this (meaningless) error may appear after opening the zinc sub-project once in an IDE.
>
> What do you think?

idk. I'd just disable bsp for parts of the code that doesn't work and call it a day.

**Comment by SlowBrainDude** [comment]
But "it works". The problem is the confusing error message.

In the end it doesn't affect anything because "nobody is using Scala 2.10 anyway". It just fails to compile the old compiler bridge for 2.10. One can ignore that, because what do you need this compiler bridge for when you built SBT from source today? Likely for nothing. Still it outputs an error after you opened the project once in an IDE. Which caused me to open a ticket…

I'll think I document that quirk. One can safely ignore that error message. It's for sure not a reason to disable BSP. IDE support works fine, it just output this error when running `publishLocal` from the console. But you get built artifacts for all still supported versions of Scala. It's confusing, but has no real consequences.

But instead of documenting quirks I would prefer to make quirks disappear when I'm anyway at it. But to decide whether to submit something else than a doc update I would need to understand why SBT targets still Scala 2.10 with parts of its code. I mean there are only two possibilities: The existence of that code has valid reasons I don't see (and I've asked now a few times for such reasons). Or it's just an old leftover that could be cleaned up.

So my question was more: Why would you prefer documenting quirks instead of cleaning this up? If the answer is "we don't touch anything here besides when it's absolutely unavoidable, because who knows" I can accept that, though. It's an old project and not much maintainers around to do firefighting in case something gets overlooked. So I fully understand a "better safe than sorry" attitude. I just try to avoid a situation where I need to submit a PR that removes that part of the code just to find out _why_ this will get a "NO". You could just tell me upfront if there is such reason. :slightly_smiling_face:

**Comment by eed3si9n** [comment]
For local testing using scripted publishLocal I don't think can error out. So the current status quo I'd say is suboptimal, at least with regards to Metals. otoh I don't see any problem turning off BSP for old compiler bridge.

**Comment by SlowBrainDude** [comment]
> I don't see any problem turning off BSP for old compiler bridge

OK.

How would I do that?

It ideally wouldn't disable BSP for the whole submodule, but just disable SemanticDB generation for that old 2.10 build target where it fails. (So IDE features wouldn't get crippled). Does this need to happen in the zinc build? Or is this something that can be only be controlled locally because `metals.sbt` would overwrite a setting in the zinc build? My knowledge about cross builds is quite limited, so sorry if this sounds like a stupid, obvious question. Any pointers to how such setup needs to look like would be helpful. Do some other project builds do something similar, so I could see how it's done? If it can happen in the zinc build I could try to submit a PR there.
