### ISSUE TITLE
Can't seem to fix runtime IllegalAccessError

### ISSUE THREAD

**Issue by lespea** [sbt/sbt#7620]
## steps

1. Clone my test repo: https://github.com/lespea/sbtAccessIssue
2. `sbt run`
3. Observe error

## problem

Loading this up in sbt and running it gives you the following error.  I've tried changing the classloader strategy to `ScalaInstance` and `Flat` and neither make a difference.  Changing the scala version to `3.3.3` doesn't seem to make a difference however reverting back to `2.13.14` allows the code to run as expected.

I'm not sure if there is some other option I need to set or this is a legitimate bug with sbt or scala.

#### Error message

```
Exception in thread "sbt-bg-threads-32" java.lang.IllegalAccessError: Error running public static void Run.main(java.lang.String[]).
java.lang.IllegalAccessError: failed to access class org.apache.commons.io.input.BoundedInputStream$AbstractBuilder from class Run$ (org.apache.commons.io.input.BoundedInputStream$AbstractBuilder and Run$ are in unnamed module of loader sbt.internal.LayeredClassLoader @248cdc34)
If using a layered classloader, this can occur if jvm package private classes are accessed across layers. This can be fixed by changing to the Flat or ScalaInstance class loader layering strategies.
	at sbt.Run.invokeMain(Run.scala:153)
	at sbt.Run.execute$1(Run.scala:94)
	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:121)
	at sbt.Run$.executeSuccess(Run.scala:187)
	at sbt.Run.runWithLoader(Run.scala:121)
	at sbt.Defaults$.$anonfun$bgRunTask$6(Defaults.scala:2038)
	at sbt.Defaults$.$anonfun$termWrapper$2(Defaults.scala:1977)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:367)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

## expectation

No runtime issues

## notes

`N/A`

**Comment by eed3si9n** [comment]
@lespea Thanks for the bug report with repro project! I think this is a bug in Scala 3 compiler. We can compare the bytecode produced by Scala 2.13.14 vs 3.4.2.

### Scala 2.13.14

For `.setMaxCount(12)` Scala 2.13.14 generates 
<details>

<summary>
<pre>
      33: invokevirtual #55                 // Method org/apache/commons/io/input/BoundedInputStream$Builder.setMaxCount:(J)Lorg/apache/commons/io/input/BoundedInputStream$AbstractBuilder;
</pre>
</summary>

```java
$ javap -classpath target/scala-2.13/classes -c 'Main$'
Compiled from "Main.scala"
public final class Main$ {
  public static final Main$ MODULE$;

  public static {};
    Code:
       0: new           #2                  // class Main$
       3: dup
       4: invokespecial #20                 // Method "<init>":()V
       7: putstatic     #22                 // Field MODULE$:LMain$;
      10: return

  public void main(java.lang.String[]);
    Code:
       0: new           #27                 // class java/io/ByteArrayInputStream
       3: dup
       4: ldc           #29                 // String this is a string
       6: invokevirtual #35                 // Method java/lang/String.getBytes:()[B
       9: invokespecial #38                 // Method java/io/ByteArrayInputStream."<init>":([B)V
      12: astore_2
      13: invokestatic  #42                 // Method org/apache/commons/io/input/BoundedInputStream.builder:()Lorg/apache/commons/io/input/BoundedInputStream$Builder;
      16: aload_2
      17: invokevirtual #46                 // Method org/apache/commons/io/input/BoundedInputStream$Builder.setInputStream:(Ljava/io/InputStream;)Lorg/apache/commons/io/build/AbstractOriginSupplier;
      20: checkcast     #12                 // class org/apache/commons/io/input/BoundedInputStream$Builder
      23: lconst_0
      24: invokevirtual #50                 // Method org/apache/commons/io/input/BoundedInputStream$Builder.setCount:(J)Lorg/apache/commons/io/input/BoundedInputStream$AbstractBuilder;
      27: checkcast     #12                 // class org/apache/commons/io/input/BoundedInputStream$Builder
      30: ldc2_w        #51                 // long 12l
      33: invokevirtual #55                 // Method org/apache/commons/io/input/BoundedInputStream$Builder.setMaxCount:(J)Lorg/apache/commons/io/input/BoundedInputStream$AbstractBuilder;
      36: checkcast     #12                 // class org/apache/commons/io/input/BoundedInputStream$Builder
      39: invokevirtual #59                 // Method org/apache/commons/io/input/BoundedInputStream$Builder.get:()Lorg/apache/commons/io/input/BoundedInputStream;
      42: astore_3
      43: getstatic     #64                 // Field scala/Predef$.MODULE$:Lscala/Predef$;
      46: new           #31                 // class java/lang/String
      49: dup
      50: aload_3
      51: invokevirtual #67                 // Method org/apache/commons/io/input/BoundedInputStream.readAllBytes:()[B
      54: invokespecial #68                 // Method java/lang/String."<init>":([B)V
      57: invokevirtual #72                 // Method scala/Predef$.println:(Ljava/lang/Object;)V
      60: return
}
```

</details>

### Scala 3.4.2

For `.setMaxCount(12)` Scala 3.4.2 generates 

<details>
<summary>
<pre>
      30: invokevirtual #66                 // Method org/apache/commons/io/input/BoundedInputStream$AbstractBuilder.setMaxCount:(J)Lorg/apache/commons/io/input/BoundedInputStream$AbstractBuilder;
</pre>
</summary>

```java
$ javap -classpath target/scala-3.4.2/classes -c 'Main$'
Compiled from "Main.scala"
public final class Main$ implements java.io.Serializable {
  public static final Main$ MODULE$;

  public static {};
    Code:
       0: new           #2                  // class Main$
       3: dup
       4: invokespecial #24                 // Method "<init>":()V
       7: putstatic     #26                 // Field MODULE$:LMain$;
      10: return

  public void main(java.lang.String[]);
    Code:
       0: new           #38                 // class java/io/ByteArrayInputStream
       3: dup
       4: ldc           #40                 // String this is a string
       6: invokevirtual #46                 // Method java/lang/String.getBytes:()[B
       9: invokespecial #49                 // Method java/io/ByteArrayInputStream."<init>":([B)V
      12: astore_2
      13: invokestatic  #53                 // Method org/apache/commons/io/input/BoundedInputStream.builder:()Lorg/apache/commons/io/input/BoundedInputStream$Builder;
      16: aload_2
      17: invokevirtual #57                 // Method org/apache/commons/io/input/BoundedInputStream$Builder.setInputStream:(Ljava/io/InputStream;)Lorg/apache/commons/io/build/AbstractOriginSupplier;
      20: checkcast     #14                 // class org/apache/commons/io/input/BoundedInputStream$Builder
      23: lconst_0
      24: invokevirtual #61                 // Method org/apache/commons/io/input/BoundedInputStream$Builder.setCount:(J)Lorg/apache/commons/io/input/BoundedInputStream$AbstractBuilder;
      27: ldc2_w        #62                 // long 12l
      30: invokevirtual #66                 // Method org/apache/commons/io/input/BoundedInputStream$AbstractBuilder.setMaxCount:(J)Lorg/apache/commons/io/input/BoundedInputStream$AbstractBuilder;
      33: checkcast     #14                 // class org/apache/commons/io/input/BoundedInputStream$Builder
      36: invokevirtual #70                 // Method org/apache/commons/io/input/BoundedInputStream$Builder.get:()Lorg/apache/commons/io/input/BoundedInputStream;
      39: astore_3
      40: getstatic     #75                 // Field scala/Predef$.MODULE$:Lscala/Predef$;
      43: new           #42                 // class java/lang/String
      46: dup
      47: aload_3
      48: invokevirtual #78                 // Method org/apache/commons/io/input/BoundedInputStream.readAllBytes:()[B
      51: invokespecial #79                 // Method java/lang/String."<init>":([B)V
      54: invokevirtual #83                 // Method scala/Predef$.println:(Ljava/lang/Object;)V
      57: return
}
```
</details>

### Dotty generates code that cause Exception in thread "main" java.lang.IllegalAccessError during runtime.

It turns out that there was a previous report on this issue https://github.com/scala/scala3/issues/13897.

```scala
package bugreport

import com.a.b.Baz

object Main {
  def main(args: Array[String]): Unit = {
    val b = new Baz.Builder()
    b.call() // works
    val x = b.call(); val y = x.call() // also works
    b.call().call() // works on 2.13, fails on Scala 3
  }
}
```

Following the above, I reassigned the `.setCount(0)` into a `val`, and that seems to have worked:

```scala
import org.apache.commons.io.input.BoundedInputStream

import java.io.ByteArrayInputStream

object Main {

  def main(args: Array[String]): Unit = {
    val in = new ByteArrayInputStream("this is a string".getBytes)

    val b = BoundedInputStream
      .builder()
      .setInputStream(in)
      .setCount(0)
    val is = b
      .setMaxCount(12)
      .get()

    println(new String(is.readAllBytes()))
  }

}
```

In any case, I don't think this is an sbt bug.

**Comment by lespea** [comment]
Interesting.  Sorry I filed it here I wasn't sure if it was sbt or scala but the classpath warnings/hints seemed to hint it was sbt so I went with it.  I tried finding similar bugs but obviously failed.  Appreciate the help showing how to get around the bug!

**Comment by eed3si9n** [comment]
No worries. Here's my PR on Scala 3 btw - https://github.com/scala/scala3/pull/21362
