### ISSUE TITLE
NoClassDefFoundError Win32NamedPipeServerSocket

### ISSUE THREAD

**Issue by LyndonArmitage** [sbt/sbt#7624]
## steps

- Install `sbt` on Mac using SDKMAN (seemingly works correctly), setting the version to a recent one `1.9.0`, `1.10.1` tested with.
- Attempt to run `sbt` either in a project or blank directory

## problem

`sbt` fails to work with the following exception:

```
java.lang.NoClassDefFoundError: org/scalasbt/ipcsocket/Win32NamedPipeServerSocket
        at sbt.xMain$.getSocketOrExit(Main.scala:151)
        at sbt.xMain$.bootServerSocket$lzycompute$1(Main.scala:77)
        at sbt.xMain$.bootServerSocket$1(Main.scala:77)
        at sbt.xMain$.withStreams$1(Main.scala:85)
        at sbt.xMain$.run(Main.scala:122)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:57)
        at sbt.xMain.run(Main.scala:46)
        at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
        at xsbt.boot.Launch$.run(Launch.scala:149)
        at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
        at xsbt.boot.Launch$.launch(Launch.scala:159)
        at xsbt.boot.Launch$.apply(Launch.scala:44)
        at xsbt.boot.Launch$.apply(Launch.scala:21)
        at xsbt.boot.Boot$.runImpl(Boot.scala:78)
        at xsbt.boot.Boot$.run(Boot.scala:73)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.ClassNotFoundException: org.scalasbt.ipcsocket.Win32NamedPipeServerSocket
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        ... 22 more
[error] [launcher] error during sbt launcher: java.lang.NoClassDefFoundError: org/scalasbt/ipcsocket/Win32NamedPipeServerSocket
````

## expectation

`sbt` runs successfully.

## notes

This is happening to a colleague on a fresh install on their Mac, so apologies that I cannot be more specific. I believe he has been able to run `sbt` on some of our older projects using versions like `1.5.7`

Previously I've seen problems on these Macs that involve our VPN/Endpoint protection software, ZScaler, interfering with HTTPS downloads when resolving dependencies (this is post successful installs though). I believe the software installs a root certificate, and essentially man-in-the-middles local HTTPS traffic, and if the Java Environment (also managed by SDKMAN) is missing this certificate it can cause failed downloads because every HTTPS connection is untrusted.

So my working theory is that something similar is happening when sbt first starts up and tries to download the correct JAR files. Does this seem like a sound theory? Are there other possible causes we should consider?

I am going to be debugging this in person with the colleague later today, including seeing if ZScalers root certificate is correctly inside the Java environment and using `keytool` to add it if not, but in the meantime I thought I'd document the issue in a bug report in case this has been seen by others and in case there is a desire for adding better error reporting around this issue.

**Comment by LyndonArmitage** [comment]
When looking at the contents of the `.sbt/` folder it seems only some of the downloaded sbt versions have an `ipcsocket` jar file. Which correspond to the `sbt` and Scala versions that seem to be working for him. Which is pointing towards some issue during installation.

**Comment by eed3si9n** [comment]
Could you try wiping out `$HOME/.sbt/boot/scala-2.12.19/org.scala-sbt/sbt/1.10.1` and see if that would help?

**Comment by LyndonArmitage** [comment]
> Could you try wiping out `$HOME/.sbt/boot/scala-2.12.19/org.scala-sbt/sbt/1.10.1` and see if that would help?

Thanks! It looks like blatting the whole directory (including that path) and getting it to re-download with proper certificates installed in the JVM worked.

I haven't had a proper look into the sbt shell script but I assume that's where the downloading of dependencies is taking place? Is there some way we could add a failsafe check within it so something like this could be caught earlier? I'm happy to contribute if that's a feasible idea. It'd probably be better to document it in another issue if we do go ahead.

**Comment by eed3si9n** [comment]
> I haven't had a proper look into the sbt shell script but I assume that's where the downloading of dependencies is taking place? Is there some way we could add a failsafe check within it so something like this could be caught earlier? I'm happy to contribute if that's a feasible idea. It'd probably be better to document it in another issue if we do go ahead.

The resolution and download of sbt artifacts are done by the sbt launcher - https://github.com/sbt/launcher, which is a program responsible for handling all modern versions of sbt. Internally it's using some version of Coursier. Feel free to open issues there and/or contribute. I'm going to close this ticket for now.
