### ISSUE TITLE
Getting Error in sbt shell  Caused by: java.lang.ClassNotFoundException: sbt.State$Next

### ISSUE THREAD

**Issue by ssonimgm** [sbt/sbt#7664]
sbt shell not runnig and when executed below error comes up, can you please help
java.lang.NoClassDefFoundError: sbt/State$Next
        at sbt.xMain.run(Main.scala:29)
        at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
        at xsbt.boot.Launch$.run(Launch.scala:149)
        at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
        at xsbt.boot.Launch$.launch(Launch.scala:159)
        at xsbt.boot.Launch$.apply(Launch.scala:44)
        at xsbt.boot.Launch$.apply(Launch.scala:21)
        at xsbt.boot.Boot$.runImpl(Boot.scala:78)
        at xsbt.boot.Boot$.run(Boot.scala:73)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.ClassNotFoundException: sbt.State$Next
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 12 more
[error] [launcher] error during sbt launcher: java.lang.NoClassDefFoundError: sbt/State$Next

**Comment by eed3si9n** [comment]
Thanks for the report. Could you provide reproduction steps so we can reproduce your problem on _our computers_ or on GitHub Actions?

**Comment by eed3si9n** [comment]
Closing this for now.
