### ISSUE TITLE
[2.x]  java.lang.ClassCastException: java.net.URL cannot be cast to java.net.URI

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#7720]
## steps

Bump to lm 2.0.0-M1, then run `dependency-management/artifact` scripted test

## problem

```scala
[info] [info] welcome to sbt 2.0.0-alpha12-SNAPSHOT (Azul Systems, Inc. Java 1.8.0_402)
[info] [info] loading project definition from /private/var/folders/hg/2602nfrs2958vnshglyl3srw0000gn/T/sbt_3624414e/project
[info] [error] java.lang.ClassCastException: java.net.URL cannot be cast to java.net.URI
[info] [error] 	at sjsonnew.IsoString$$anon$1.to(IsoString.scala:26)
[info] [error] 	at sjsonnew.IsoFormats$$anon$2.write(IsoFormats.scala:31)
[info] [error] 	at sjsonnew.StandardFormats$OptionFormat.write(StandardFormats.scala:37)
[info] [error] 	at sjsonnew.StandardFormats$OptionFormat.addField(StandardFormats.scala:44)
[info] [error] 	at sjsonnew.StandardFormats$OptionFormat.addField(StandardFormats.scala:40)
[info] [error] 	at sjsonnew.Builder.addField(Builder.scala:43)
[info] [error] 	at sbt.librarymanagement.ArtifactFormats$$anon$1.write(ArtifactFormats.scala:36)
[info] [error] 	at sbt.librarymanagement.ArtifactFormats$$anon$1.write(ArtifactFormats.scala:29)
[info] [error] 	at sjsonnew.TupleFormats$$anon$2.write(TupleFormats.scala:49)
[info] [error] 	at sjsonnew.TupleFormats$$anon$2.write(TupleFormats.scala:47)
[info] [error] 	at sjsonnew.CollectionFormats$$anon$2.write$$anonfun$2(CollectionFormats.scala:85)
[info] [error] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[info] [error] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[info] [error] 	at scala.collection.immutable.Vector.foreach(Vector.scala:2124)
[info] [error] 	at sjsonnew.CollectionFormats$$anon$2.write(CollectionFormats.scala:85)
[info] [error] 	at sjsonnew.CollectionFormats$$anon$2.write(CollectionFormats.scala:82)
[info] [error] 	at sjsonnew.JsonWriter.addField(JsonFormat.scala:40)
[info] [error] 	at sjsonnew.JsonWriter.addField$(JsonFormat.scala:35)
[info] [error] 	at sjsonnew.CollectionFormats$$anon$2.addField(CollectionFormats.scala:80)
[info] [error] 	at sjsonnew.Builder.addField(Builder.scala:43)
[info] [error] 	at sbt.librarymanagement.ModuleReportFormats$$anon$1.write(ModuleReportFormats.scala:41)
[info] [error] 	at sbt.librarymanagement.ModuleReportFormats$$anon$1.write(ModuleReportFormats.scala:38)
[info] [error] 	at sjsonnew.CollectionFormats$$anon$2.write$$anonfun$2(CollectionFormats.scala:85)
[info] [error] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[info] [error] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[info] [error] 	at scala.collection.immutable.Vector.foreach(Vector.scala:2124)
[info] [error] 	at sjsonnew.CollectionFormats$$anon$2.write(CollectionFormats.scala:85)
[info] [error] 	at sjsonnew.CollectionFormats$$anon$2.write(CollectionFormats.scala:82)
[info] [error] 	at sjsonnew.JsonWriter.addField(JsonFormat.scala:40)
[info] [error] 	at sjsonnew.JsonWriter.addField$(JsonFormat.scala:35)
[info] [error] 	at sjsonnew.CollectionFormats$$anon$2.addField(CollectionFormats.scala:80)
[info] [error] 	at sjsonnew.Builder.addField(Builder.scala:43)
[info] [error] 	at sbt.librarymanagement.ConfigurationReportFormats$$anon$1.write(ConfigurationReportFormats.scala:26)
[info] [error] 	at sbt.librarymanagement.ConfigurationReportFormats$$anon$1.write(ConfigurationReportFormats.scala:23)
[info] [error] 	at sjsonnew.CollectionFormats$$anon$2.write$$anonfun$2(CollectionFormats.scala:85)
[info] [error] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[info] [error] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[info] [error] 	at scala.collection.immutable.Vector.foreach(Vector.scala:2124)
[info] [error] 	at sjsonnew.CollectionFormats$$anon$2.write(CollectionFormats.scala:85)
[info] [error] 	at sjsonnew.CollectionFormats$$anon$2.write(CollectionFormats.scala:82)
[info] [error] 	at sjsonnew.JsonWriter.addField(JsonFormat.scala:40)
[info] [error] 	at sjsonnew.JsonWriter.addField$(JsonFormat.scala:35)
[info] [error] 	at sjsonnew.CollectionFormats$$anon$2.addField(CollectionFormats.scala:80)
[info] [error] 	at sjsonnew.Builder.addField(Builder.scala:43)
[info] [error] 	at sbt.librarymanagement.UpdateReportFormats$$anon$1.write(UpdateReportFormats.scala:27)
[info] [error] 	at sbt.librarymanagement.UpdateReportFormats$$anon$1.write(UpdateReportFormats.scala:24)
[info] [error] 	at sjsonnew.SupportConverter.toJsonUnsafe(SupportConverter.scala:23)
[info] [error] 	at sjsonnew.SupportConverter.toJsonUnsafe$(SupportConverter.scala:5)
[info] [error] 	at sjsonnew.support.scalajson.unsafe.Converter$.toJsonUnsafe(Converter.scala:7)
[info] [error] 	at sjsonnew.SupportConverter.toJson$$anonfun$1(SupportConverter.scala:14)
[info] [error] 	at scala.util.Try$.apply(Try.scala:210)
[info] [error] 	at sjsonnew.SupportConverter.toJson(SupportConverter.scala:14)
[info] [error] 	at sjsonnew.SupportConverter.toJson$(SupportConverter.scala:5)
[info] [error] 	at sjsonnew.support.scalajson.unsafe.Converter$.toJson(Converter.scala:7)
[info] [error] 	at sbt.util.FileOutput.write(Output.scala:39)
[info] [error] 	at sbt.util.FileBasedStore.write(CacheStore.scala:90)
[info] [error] 	at sbt.util.Tracked$.lastOutput$$anonfun$1(Tracked.scala:86)
[info] [error] 	at sbt.internal.LibraryManagement$.$anonfun$3(LibraryManagement.scala:149)
[info] [error] 	at sbt.internal.LibraryManagement$.$anonfun$adapted$1(LibraryManagement.scala:159)
[info] [error] 	at sbt.util.Tracked$.inputChangedW$$anonfun$1(Tracked.scala:233)
[info] [error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:173)
[info] [error] 	at sbt.Classpaths$.updateTask0$$anonfun$1(Defaults.scala:4189)
[info] [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:79)
[info] [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:79)
[info] [error] 	at sbt.std.Transform$$anon$5.work(Transform.scala:79)
[info] [error] 	at sbt.std.Transform$$anon$5.work(Transform.scala:79)
[info] [error] 	at sbt.Execute.submit$$anonfun$1$$anonfun$1(Execute.scala:284)
[info] [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[info] [error] 	at sbt.Execute.work(Execute.scala:295)
[info] [error] 	at sbt.Execute.submit$$anonfun$1(Execute.scala:284)
[info] [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$2(ConcurrentRestrictions.scala:277)
[info] [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:75)
[info] [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:73)
[info] [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info] [error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info] [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info] [error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info] [error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info] [error] 	at java.lang.Thread.run(Thread.java:750)
[info] [error] (update) java.lang.ClassCastException: java.net.URL cannot be cast to java.net.URI
[info] [warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
[error] x dependency-management/artifact
```

## expectation
It works

**Comment by jtjeferreira** [comment]
This is very weird, It looks like an `Artifact` is being created with an `Option[URL]` somewhere, but because the JVM erasure (url is a an Option[Any]) the only error happens when trying to write the Artifact to Json. I see you are reverting the change in https://github.com/sbt/librarymanagement/pull/447 (which is fine to unblock) but I will have a closer look at this

**Comment by jtjeferreira** [comment]
I think `librarymanagement-coursier_3-2.0.0-alpha8.jar` needs to be updated to use `lm 2.0.0-M1`, but I cant find the code... https://mvnrepository.com/artifact/org.scala-sbt/librarymanagement-coursier_3/2.0.0-alpha8 links to 
https://github.com/coursier/sbt-coursier, but there I dont see any 2.0.0-alpha8.jar release nor any cross compilation with scala3...

**Comment by jtjeferreira** [comment]
Ok, I think I found it https://github.com/adpi2/sbt-coursier/blob/wip/sbt-2.x/build.sbt ?

**Comment by jtjeferreira** [comment]
And I created a PR https://github.com/adpi2/sbt-coursier/pull/1

**Comment by eed3si9n** [comment]
@jtjeferreira Thanks for the detective work!

**Comment by jtjeferreira** [comment]
@adpi2 created a proper branch and did a [PR](https://github.com/coursier/sbt-coursier/pull/521)

@eed3si9n shall I revert the [revert](https://github.com/sbt/librarymanagement/pull/447)?

**Comment by eed3si9n** [comment]
Yes please.

**Comment by adpi2** [comment]
Fixed by https://github.com/sbt/sbt/pull/7739
