### ISSUE TITLE
[2.x] InvalidClassException: sbt.ForkMain$SubclassFingerscan; local class incompatible

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt#7724]
## steps

https://github.com/xuwei-k/sbt-2-InvalidClassException/commit/a4467091ae7418ff3dab6bc3806efd764455a4ad

`build.sbt`

```scala
scalaVersion := "3.3.4"

Test / fork := true

libraryDependencies += "org.scalatest" %% "scalatest-funsuite" % "3.2.19" % Test

enablePlugins(SbtPlugin)

pluginCrossBuild / sbtVersion := {
  scalaBinaryVersion.value match {
    case "2.12" => sbtVersion.value
    case _ => "2.0.0-M2"
  }
}
```

`project/build.properties`

```properties
sbt.version=1.10.2
```

`src/test/scala/ExampleTest.scala`

```scala
package example

class ExampleTest extends org.scalatest.funsuite.AnyFunSuite {
  test("test") {
    assert((1 to 10).sum == 55)
  }
}
```

```
sbt "++ 3.x" test
```

## problem

https://github.com/xuwei-k/sbt-2-InvalidClassException/actions/runs/11192392099/job/31116498060#step:4:37

```
[error] Uncaught exception when running tests: java.io.InvalidClassException: sbt.ForkMain$SubclassFingerscan; local class incompatible: stream classdesc serialVersionUID = -8806153822637628239, local class serialVersionUID = 4207735866278500086
[error] sbt.ForkMain$ForkError: java.io.InvalidClassException: sbt.ForkMain$SubclassFingerscan; local class incompatible: stream classdesc serialVersionUID = -8806153822637628239, local class serialVersionUID = 4207735866278500086
[error] 	at java.base/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:598)
[error] 	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2078)
[error] 	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1927)
[error] 	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2252)
[error] 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1762)
[error] 	at java.base/java.io.ObjectInputStream$FieldValues.<init>(ObjectInputStream.java:2618)
[error] 	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2469)
[error] 	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2284)
[error] 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1762)
[error] 	at java.base/java.io.ObjectInputStream.readArray(ObjectInputStream.java:2186)
[error] 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1750)
[error] 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:5[40](https://github.com/xuwei-k/sbt-2-InvalidClassException/actions/runs/11192392099/job/31116498060#step:4:41))
[error] 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:498)
[error] 	at sbt.ForkMain$Run.runTests(ForkMain.java:307)
[error] 	at sbt.ForkMain$Run.run(ForkMain.java:192)
[error] 	at sbt.ForkMain$Run.access$100(ForkMain.java:187)
[error] 	at sbt.ForkMain.main(ForkMain.java:178)
[error] 	at sbt.ForkMain.main(ForkMain.java:164)
```

**Comment by xuwei-k** [comment]
- maybe https://github.com/sbt/sbt/pull/6735 🤔

**Comment by xuwei-k** [comment]
https://github.com/xuwei-k/sbt-2-InvalidClassException/commit/f0c25dfc2058250a5ed3a2b1c9e63293ab8bf0d7

no error with sbt 2.0.0-RC2 🤔 🎉

**Comment by eed3si9n** [comment]
Ref https://github.com/sbt/sbt/pull/8170. This reimplements forked test communication to use JSON-RPC.
