### ISSUE TITLE
[2.x] ClassNotFoundException: dotty.tools.dottydoc.Main

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt#7725]
## steps

`A.scala`

```scala
package x

class A
```

`build.sbt`

```scala
scalaVersion := "3.3.3"
```

`project/build.properties`

```scala
sbt.version=2.0.0-M2
```

run `sbt doc`

## problem

```
[error] java.lang.RuntimeException: java.lang.ClassNotFoundException: dotty.tools.dottydoc.Main
[error] 	at xsbt.DottydocRunner.run(DottydocRunner.java:65)
[error] 	at xsbt.ScaladocInterface.run(ScaladocInterface.java:11)
[error] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[error] 	at sbt.internal.inc.AnalyzingCompiler.invoke(AnalyzingCompiler.scala:329)
[error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:175)
[error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:133)
[error] 	at sbt.Defaults$.docTaskSettings$$anonfun$4(Defaults.scala:2325)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:79)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:79)
[error] 	at sbt.std.Transform$$anon$5.work(Transform.scala:79)
[error] 	at sbt.std.Transform$$anon$5.work(Transform.scala:79)
[error] 	at sbt.Execute.submit$$anonfun$1$$anonfun$1(Execute.scala:284)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.Execute.work(Execute.scala:295)
[error] 	at sbt.Execute.submit$$anonfun$1(Execute.scala:284)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$2(ConcurrentRestrictions.scala:277)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:75)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:73)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[error] 	at java.base/java.lang.Thread.run(Thread.java:1583)
[error] Caused by: java.lang.ClassNotFoundException: dotty.tools.dottydoc.Main
[error] 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[error] 	at java.base/java.lang.Class.forName0(Native Method)
[error] 	at java.base/java.lang.Class.forName(Class.java:421)
[error] 	at java.base/java.lang.Class.forName(Class.java:412)
[error] 	at xsbt.DottydocRunner.run(DottydocRunner.java:59)
[error] 	at xsbt.ScaladocInterface.run(ScaladocInterface.java:11)
[error] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[error] 	at sbt.internal.inc.AnalyzingCompiler.invoke(AnalyzingCompiler.scala:329)
[error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:175)
[error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:133)
[error] 	at sbt.Defaults$.docTaskSettings$$anonfun$4(Defaults.scala:2325)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:79)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:79)
[error] 	at sbt.std.Transform$$anon$5.work(Transform.scala:79)
[error] 	at sbt.std.Transform$$anon$5.work(Transform.scala:79)
[error] 	at sbt.Execute.submit$$anonfun$1$$anonfun$1(Execute.scala:284)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.Execute.work(Execute.scala:295)
[error] 	at sbt.Execute.submit$$anonfun$1(Execute.scala:284)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$2(ConcurrentRestrictions.scala:277)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:75)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:73)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[error] 	at java.base/java.lang.Thread.run(Thread.java:1583)
[error] (Compile / doc) java.lang.ClassNotFoundException: dotty.tools.dottydoc.Main
```

## notes

success if change to another `scalaVersion`

**Comment by eed3si9n** [comment]
I'm running into this while trying to port sbt-native-packager since none of the scripted tests specify the `scalaVersion`.

There's an optimization where we try to avoid using the normal classloader for the Scala version if the metabuild already used it. I guess the problem is that there's something different about the way `doc` is created for Scala 3 I guess?

**Comment by adpi2** [comment]
> I guess the problem is that there's something different about the way doc is created for Scala 3 I guess?
 
I remember I created the `ScalaDocTools` configuration for Scala 3, and so scaladoc is probably not in the same classloader.

**Comment by jtjeferreira** [comment]
Shall this be closed since #7878 was merged? Or do you plan to revisit this?

**Comment by eed3si9n** [comment]
The merged fix is a workaround so we should keep it open if we can find a better fix.

**Comment by eed3si9n** [comment]
Maybe I should give up on this one, since I don't want scaladoc's JARs as sbt's dependency either.

**Comment by erikerlandson** [comment]
I hit this with latest scala steward PR:
https://github.com/erikerlandson/coulomb/pull/701

**Comment by mzuehlke** [comment]
This bug is about sbt 2.x
Your are still on 1.x

The last sbt release has some changes: https://github.com/sbt/sbt/releases/tag/v1.12.0  t
hat require sbt-unidoc https://github.com/sbt/sbt-unidoc/releases/tag/v0.6.1

You are getting that via sbt-typelevel. So You can try to bump that plugin in your app or wait for a sbt-typelevel update.
