### ISSUE TITLE
[2.x] `ProjectRef` does not work

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt#7738]
## steps

`a1/build.sbt`

```scala
val a1 = project.in(file("."))
```

`build.sbt`

```scala
val root = project
  .in(file("."))
  .dependsOn(ProjectRef(file("a1"), "a1"))
```

`project/build.properties`

```properties
sbt.version=2.0.0-M2
```

launch sbt

https://github.com/xuwei-k/sbt-2-ProjectRef/commit/d95024648a7b78b906e3444a616ccf19f0659cb3

## problem

```
[info] welcome to sbt 2.0.0-M2 (Eclipse Adoptium Java 21.0.4)
[info] loading project definition from /home/runner/work/sbt-2-ProjectRef/sbt-2-ProjectRef/project
java.lang.RuntimeException: Invalid build URI (no handler available): file:/home/runner/work/sbt-2-ProjectRef/sbt-2-ProjectRef/a1/a1/
	at scala.sys.package$.error(package.scala:[27](https://github.com/xuwei-k/sbt-2-ProjectRef/actions/runs/11235435655/job/31233373768#step:4:28))
	at sbt.internal.Load$.$anonfun$30(Load.scala:549)
	at sbt.internal.BuildLoader.$anonfun$1(BuildLoader.scala:245)
	at scala.Option.getOrElse(Option.scala:201)
	at sbt.internal.BuildLoader.apply(BuildLoader.scala:245)
	at sbt.internal.Load$.loadURI$1(Load.scala:619)
	at sbt.internal.Load$.loadAll(Load.scala:635)
	at sbt.internal.Load$.loadURI(Load.scala:565)
	at sbt.internal.Load$.load(Load.scala:538)
	at sbt.internal.Load$.$anonfun$10(Load.scala:263)
	at sbt.internal.Load$.timed(Load.scala:1570)
	at sbt.internal.Load$.apply(Load.scala:263)
	at sbt.internal.Load$.defaultLoad(Load.scala:57)
	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:963)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:970)
	at sbt.BuiltinCommands$.loadProjectImpl$$anonfun$2(Main.scala:917)
	at sbt.Command$.applyEffect$$anonfun$2$$anonfun$1(Command.scala:151)
	at sbt.Command$.applyEffect$$anonfun$1$$anonfun$1(Command.scala:146)
	at sbt.Command$.process(Command.scala:194)
	at sbt.MainLoop$.$anonfun$12(MainLoop.scala:266)
	at scala.Option.getOrElse(Option.scala:201)
	at sbt.MainLoop$.process$1(MainLoop.scala:266)
	at sbt.MainLoop$.processCommand(MainLoop.scala:315)
	at sbt.MainLoop$.next$$anonfun$1$$anonfun$1(MainLoop.scala:169)
	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:290)
	at sbt.State$StateOpsImpl$.process$extension(State.scala:326)
	at sbt.MainLoop$.next$$anonfun$1(MainLoop.scala:169)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
	at sbt.MainLoop$.next(MainLoop.scala:170)
	at sbt.MainLoop$.run(MainLoop.scala:150)
	at sbt.MainLoop$.runWithNewLog$$anonfun$1(MainLoop.scala:125)
	at sbt.io.Using.apply(Using.scala:[28](https://github.com/xuwei-k/sbt-2-ProjectRef/actions/runs/11235435655/job/31233373768#step:4:29))
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:128)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:72)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:57)
	at sbt.MainLoop$.runLogged(MainLoop.scala:48)
	at sbt.StandardMain$.runManaged(Main.scala:232)
	at sbt.xMain$.run$$anonfun$3(Main.scala:142)
	at sbt.internal.util.Terminal$.withStreams(Terminal.scala:442)
	at sbt.xMain$.withStreams$1(Main.scala:93)
	at sbt.xMain$.run(Main.scala:144)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:68)
	at sbt.xMain.run(Main.scala:50)
	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
	at xsbt.boot.Launch$.run(Launch.scala:149)
	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:[44](https://github.com/xuwei-k/sbt-2-ProjectRef/actions/runs/11235435655/job/31233373768#step:4:45))
	at xsbt.boot.Launch$.launch(Launch.scala:159)
	at xsbt.boot.Launch$.apply(Launch.scala:44)
	at xsbt.boot.Launch$.apply(Launch.scala:21)
	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
	at xsbt.boot.Boot$.run(Boot.scala:73)
	at xsbt.boot.Boot$.main(Boot.scala:21)
	at xsbt.boot.Boot.main(Boot.scala)
[error] Invalid build URI (no handler available): file:/home/runner/work/sbt-2-ProjectRef/sbt-2-ProjectRef/a1/a1/
[error] Use 'last' for the full log.
```

**Comment by eed3si9n** [comment]
@xuwei-k Thanks for the report!

**Comment by eed3si9n** [comment]
Here's a PR for this - https://github.com/sbt/sbt/pull/7925
