### ISSUE TITLE
scripted for cross building plugins

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#781]
### steps

Use sbt 0.12.4-RC2 to cross build 0.13.0-Beta2 plugin. build.properties:

``` scala
sbt.version=0.12.4-RC2
```

build.sbt:

``` scala
...

ScriptedPlugin.scriptedSettings

sbtVersion in Global := "0.13.0-Beta2" 

scalaVersion in Global := "2.10.2-RC2" 
```

Then run `scripted`.
### problem

```
java.lang.NoSuchMethodError: scala.Predef$.augmentString(Ljava/lang/String;)Lscala/collection/immutable/StringOps;
    at sbt.ConsoleLogger$.<init>(ConsoleLogger.scala:129)
    at sbt.ConsoleLogger$.<clinit>(ConsoleLogger.scala)
    at sbt.test.ScriptedTests$.run(ScriptedTests.scala:108)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at sbt.ScriptedPlugin$$anonfun$scriptedTask$2$$anonfun$apply$1.apply(ScriptedPlugin.scala:43)
    at sbt.ScriptedPlugin$$anonfun$scriptedTask$2$$anonfun$apply$1.apply(ScriptedPlugin.scala:42)
    at sbt.Scoped$$anonfun$hf10$1.apply(Structure.scala:586)
    at sbt.Scoped$$anonfun$hf10$1.apply(Structure.scala:586)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:49)
    at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
    at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:41)
    at sbt.std.Transform$$anon$5.work(System.scala:71)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.Execute.work(Execute.scala:238)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:680)
```
### expectation

It would be nice if scripted ran in the context of sbt 0.13.0-Beta2.
jrudolph/sbt-cross-building does it.

**Comment by harrah** [comment]
This was fixed by the above commits.  There will be an RC3 with this next week, but I don't think it will need to reset the two weeks until final as long as this feature works.

**Comment by harrah** [comment]
0.12.4-RC3 contains this fix.  Let me know if it works for you and then I can publish it as final.

**Comment by eed3si9n** [comment]
Using 0.12.4-RC3 I was able to run scripted tests for sbt-buildinfo successfully:

```
Running sbt-buildinfo / append
Running sbt-buildinfo / caching
Running sbt-buildinfo / multi
Running sbt-buildinfo / simple
[success] Total time: 337 s, completed Jun 21, 2013 12:50:15 PM
sbt-buildinfo> 
```

Here are the changes I made to the build: sbt/sbt-buildinfo@b792ed27bd203e68ff61362ac30f73f53303bb1a
It's mostly expected changes due to the difference in Scala version etc, but one thing I had to add was 

``` scala
scriptedLaunchOpts ++= Seq("-Xmx1024M", "-XX:MaxPermSize=256M")
```

Without it the scripted failed by running out of PermGen space.

**Comment by harrah** [comment]
Thanks @eed3si9n.  Not sure about the PermGen offhand.  Is that close to the lowest amount required?  That is, if you drop to 128M, I assume it doesn't finish or takes much longer?

**Comment by eed3si9n** [comment]
> Is that close to the lowest amount required?

No, I used it because that's the setting I use for sbt-assembly.
I was able to run scripted with 128M fine for sbt-buildinfo:

```
Running sbt-buildinfo / append
Running sbt-buildinfo / caching
Running sbt-buildinfo / multi
Running sbt-buildinfo / simple
[success] Total time: 249 s, completed Jun 22, 2013 2:00:43 PM
```

64M (default) fails as follows:

```
sbt-buildinfo> scripted
[info] :: delivering :: com.eed3si9n#sbt-buildinfo;0.2.5-SNAPSHOT :: 0.2.5-SNAPSHOT :: integration :: Sat Jun 22 14:01:50 EDT 2013
[info]  delivering ivy file to /Users/eed3si9n/work/sbt-buildinfo/target/scala-2.10/sbt-0.13.0-Beta2/ivy-0.2.5-SNAPSHOT.xml
[info] Packaging /Users/eed3si9n/work/sbt-buildinfo/target/scala-2.10/sbt-0.13.0-Beta2/sbt-buildinfo-0.2.5-SNAPSHOT.jar ...
[info] Done packaging.
[info]  published sbt-buildinfo to /Users/eed3si9n/.ivy2/local/com.eed3si9n/sbt-buildinfo/scala_2.10/sbt_0.13.0-Beta2/0.2.5-SNAPSHOT/srcs/sbt-buildinfo-sources.jar
[info]  published sbt-buildinfo to /Users/eed3si9n/.ivy2/local/com.eed3si9n/sbt-buildinfo/scala_2.10/sbt_0.13.0-Beta2/0.2.5-SNAPSHOT/jars/sbt-buildinfo.jar
[info]  published sbt-buildinfo to /Users/eed3si9n/.ivy2/local/com.eed3si9n/sbt-buildinfo/scala_2.10/sbt_0.13.0-Beta2/0.2.5-SNAPSHOT/docs/sbt-buildinfo-javadoc.jar
[info]  published sbt-buildinfo to /Users/eed3si9n/.ivy2/local/com.eed3si9n/sbt-buildinfo/scala_2.10/sbt_0.13.0-Beta2/0.2.5-SNAPSHOT/srcs/sbt-buildinfo-test-sources.jar
[info]  published sbt-buildinfo to /Users/eed3si9n/.ivy2/local/com.eed3si9n/sbt-buildinfo/scala_2.10/sbt_0.13.0-Beta2/0.2.5-SNAPSHOT/docs/sbt-buildinfo-test-javadoc.jar
[info]  published ivy to /Users/eed3si9n/.ivy2/local/com.eed3si9n/sbt-buildinfo/scala_2.10/sbt_0.13.0-Beta2/0.2.5-SNAPSHOT/ivys/ivy.xml
Running sbt-buildinfo / append
[info] Getting net.java.dev.jna jna 3.2.3 ...
....
[info] [info] Done updating.
[error] sbt appears to be exiting abnormally.
[error]   The log file for this session is at /var/folders/bc/mmccbbns3f37k9x499ydvlk40000gn/T/sbt1352439859787200311.log
[error] java.lang.OutOfMemoryError: PermGen space
[error]     at java.lang.ClassLoader.defineClass1(Native Method)
[error]     at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
[error]     at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
[error]     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
[error]     at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
[error]     at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
[error]     at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
[info] Error during sbt execution: java.lang.OutOfMemoryError: PermGen space
[error]     at java.security.AccessController.doPrivileged(Native Method)
[error]     at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
[error]     at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
[error]     at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
[error]     at java.lang.ClassLoader.defineClass1(Native Method)
[error]     at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
[error]     at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
[error]     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
[error]     at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
[error]     at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
[error]     at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
[error]     at java.security.AccessController.doPrivileged(Native Method)
[error]     at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
[error]     at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
[error]     at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
[error]     at scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator$ExtractorCall$.fromCaseClass(MatchTranslation.scala:411)
[error]     at scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator$class.translatePattern(MatchTranslation.scala:326)
[error]     at scala.tools.nsc.transform.patmat.PatternMatching$OptimizingMatchTranslator.translatePattern(PatternMatching.scala:87)
[error]     at scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator$class.translateCase(MatchTranslation.scala:231)
[error]     at scala.tools.nsc.transform.patmat.PatternMatching$OptimizingMatchTranslator.translateCase(PatternMatching.scala:87)
[error]     at scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator$$anonfun$4.apply(MatchTranslation.scala:153)
[error]     at scala.tools.nsc.transform.patmat.MatchTranslation$MatchTranslator$$anonfun$4.apply(MatchTranslation.scala:153)
[error]     at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[error]     at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[error]     at scala.collection.immutable.List.foreach(List.scala:318)
[error] x sbt-buildinfo / append
[trace] Stack trace suppressed: run last *:scripted for the full output.
[error] (*:scripted) Remote sbt initialization failed
[error] Total time: 55 s, completed Jun 22, 2013 2:02:44 PM
```

**Comment by harrah** [comment]
64MB is what is needed to run two Scala versions in the same JVM, so that is expected.
