### ISSUE TITLE
testing java ffi: combase.dll not found correctly on windows

### ISSUE THREAD

**Issue by soloturn** [sbt/sbt#7833]
## steps

with java-22 or java-23, on windows, check out dirs-dev repo, switch to branch for this pull request, 
https://github.com/dirs-dev/directories-jvm/pull/61
and do `sbt test`

## problem
combase.dll not found when using java ffi. the path displayed is in sbt temp directory.

## expectation

testing java ffi works, just like it does on linux.

**Comment by Friendseeker** [comment]
I do not have access to a windows machine for the next few days but is it possible to workaround the issue via using `System.load` and specify an absolute path instead of using `System.loadLibrary`?

---

I had tested that the following snippet workarounds around the issue and makes the CI test pass.

```java
if (Constants.operatingSystem == 'w') {
      String sysdir = System.getenv("WINDIR") + "\\system32";
      System.load(sysdir + "\\combase.dll");
      System.load(sysdir + "\\ole32.dll");
      System.load(sysdir + "\\shell32.dll");
}
```

**Comment by Friendseeker** [comment]
Btw this might be the referring to the same issue? The stackoverflow answer suggests the actual cause of the issue is trying to load a 32 bit DLL from `C:\Windows\System32`

> https://stackoverflow.com/a/9835908

Shall close this issue for now. Feel free to reopen it if new evidence emerges that suggest this is indeed caused by `sbt`.

**Comment by soloturn** [comment]
> I do not have access to a windows machine for the next few days but is it possible to workaround the issue via using `System.load` and specify an absolute path instead of using `System.loadLibrary`?
> 
> I had tested that the following snippet workarounds around the issue and makes the CI test pass.
> 
> ```java
> if (Constants.operatingSystem == 'w') {
>       String sysdir = System.getenv("WINDIR") + "\\system32";
>       System.load(sysdir + "\\combase.dll");
>       System.load(sysdir + "\\ole32.dll");
>       System.load(sysdir + "\\shell32.dll");
> }
> ```

@Friendseeker , what windows version was this on? for me, windows-11, this gives:
```
[error] Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Directory separator should not appear in library name: C:\WINDOWS\system32\combase.dll [in thread "pool-1-thread-1"]
```
btw, i have no right to reopen, but still am not sure if this is really an sbt thing.

**Comment by Friendseeker** [comment]
> what windows version was this on? for me, windows-11, this gives:

I ran https://github.com/Friendseeker/directories-jvm/actions/runs/11535962968/job/32111615159, which runs the same CI job as https://github.com/dirs-dev/directories-jvm/pull/61

**Comment by Friendseeker** [comment]
> what windows version was this on? for me, windows-11, this gives:

This error is very confusing... I currently don't have a windows machine with me so cannot perform live investigation. But I had checked JVM source code and `System.load` should not throw "Directory separator should not appear in library name" error. Rather this error message seems to be exclusive to `System.loadLibrary`.

```java
    @CallerSensitive
    @Restricted
    public void loadLibrary(String libname) {
        Class<?> caller = Reflection.getCallerClass();
        Reflection.ensureNativeAccess(caller, Runtime.class, "loadLibrary", false);
        loadLibrary0(caller, libname);
    }

    void loadLibrary0(Class<?> fromClass, String libname) {
        @SuppressWarnings("removal")
        SecurityManager security = System.getSecurityManager();
        if (security != null) {
            security.checkLink(libname);
        }
        if (libname.indexOf((int)File.separatorChar) != -1) {
            throw new UnsatisfiedLinkError(
                "Directory separator should not appear in library name: " + libname);
        }
        ClassLoader.loadLibrary(fromClass, libname);
    }
```

```java
    @CallerSensitive
    @Restricted
    public void load(String filename) {
        Class<?> caller = Reflection.getCallerClass();
        Reflection.ensureNativeAccess(caller, Runtime.class, "load", false);
        load0(caller, filename);
    }

    void load0(Class<?> fromClass, String filename) {
        @SuppressWarnings("removal")
        SecurityManager security = System.getSecurityManager();
        if (security != null) {
            security.checkLink(filename);
        }
        File file = new File(filename);
        if (!file.isAbsolute()) {
            throw new UnsatisfiedLinkError(
                "Expecting an absolute path of the library: " + filename);
        }
        ClassLoader.loadLibrary(fromClass, file);
    }
```

**Comment by soloturn** [comment]
oh, my bad, i overlooked that you changed from "loadLibary" to "load". i can reproduce now, thank you so much!

**Comment by Friendseeker** [comment]
I did some more digging and... it probably is an sbt issue.

I tried an Intellij Java project

```
public class Main {
    public static void main(String[] args) {
        System.loadLibrary("combase");
    }
}
```

A Scala Project with Intellij build system

```
@main
def main(): Unit = {
  System.loadLibrary("combase")
}

```

A sbt project (run via `sbt run Main`)

```
@main
def main(): Unit = {
  System.loadLibrary("combase")
}
```

Only the sbt project failed to load combase...

**Comment by Friendseeker** [comment]
Full Stacktrace for reference

```
Exception in thread "sbt-bg-threads-8" java.lang.UnsatisfiedLinkError: D:\Repos\untitled2\target\task-temp-directory\sbt_2b92f817\combase.dll: A dynamic link library (DLL) initialization routine failed
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2444)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:916)
        at java.base/java.lang.System.loadLibrary(System.java:2063)
        at main$package$.main(main.scala:5)
        at main.main(main.scala:2)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at sbt.Run.invokeMain(Run.scala:144)
        at sbt.Run.execute$1(Run.scala:94)
        at sbt.Run.$anonfun$runWithLoader$5(Run.scala:121)
        at sbt.Run$.executeSuccess(Run.scala:187)
        at sbt.Run.runWithLoader(Run.scala:121)
        at sbt.Defaults$.$anonfun$bgRunTask$6(Defaults.scala:2030)
        at sbt.Defaults$.$anonfun$termWrapper$2(Defaults.scala:1969)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.util.Try$.apply(Try.scala:213)
        at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:367)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)

```

**Comment by Friendseeker** [comment]
https://github.com/sbt/zinc/blob/0de8e03e57e48195d22aca7ff6f7bbb2a4020c88/internal/zinc-classpath/src/main/scala/sbt/internal/inc/classpath/ClassLoaders.scala#L166-L209

```java
/**
 * Loads native libraries from a temporary location in order to work around the jvm native library uniqueness restriction.
 * See [[NativeCopyConfig]] for configuration details.
 */
```

The issue probably stems around here.

**Comment by Friendseeker** [comment]
Cause: combase.dll cannot be moved. If we move it out of system32, it can no longer be loaded.

Try running the following java snippet

```
public class Main {
    public static void main(String[] args) {

        System.loadLibrary("karma"); // rename combase.dll as karma.dll and place it elsewhere in java.library.path
        // interestingly copy combase.dll as karma.dll and place it back in system32 is fine.
    }
}
```

Now we reproduce the exact same stacktrace.
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\ProgramData\chocolatey\bin\karma.dll: A dynamic link library (DLL) initialization routine failed
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:259)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:251)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2451)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:916)
	at java.base/java.lang.System.loadLibrary(System.java:2063)
	at Main.main(Main.java:4)
```

**Comment by Friendseeker** [comment]
The plot thickens...

When we run the tests when settings `Test / fork = true`, sbt does not do the same native lib classpath manipulation, and in fact, the `loadLibrary` all succeeded.

![image](https://github.com/user-attachments/assets/63c3c0d1-130c-4c68-a17c-4ef53d69205e)

![image](https://github.com/user-attachments/assets/645e900b-ef22-432a-a5cf-9753adc68d53)

In fact `testOnly *DirectoriesTest*` crashes right around here.
![image](https://github.com/user-attachments/assets/d49460aa-c5a8-4485-933c-8bdb594f4c65)

**Comment by eed3si9n** [comment]
> `Test / fork = true`

Yea, so if a test needs native library loading, probably it requires forked test.
