### ISSUE TITLE
[1.x] CI Job 1 has been failing since `634a584`

### ISSUE THREAD

**Issue by Friendseeker** [sbt/sbt#7851]
It shows up as successful, but actually the job failed...

https://github.com/sbt/sbt/actions/runs/11551736612/job/32149389986

```bash
[info] entering *experimental* thin client - BEEP WHIRR
[info] server was not detected. starting an instance
Error: Exception in thread "client-read-thread" java.lang.UnsatisfiedLinkError: Can't load library: /run/user/1001/.sbt1858715345/ipcsocket/libsbtipcsocket16431783303030607129.so
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibraries.loadLibraryAbsolute(NativeLibraries.java:105)
	at java.base@23.0.1/java.lang.ClassLoader.loadLibrary(ClassLoader.java:116)
	at java.base@23.0.1/java.lang.Runtime.load0(Runtime.java:852)
	at java.base@23.0.1/java.lang.System.load(System.java:2028)
	at org.scalasbt.ipcsocket.NativeLoader.load(NativeLoader.java:106)
```

@eed3si9n @adpi2

**Comment by tgodzik** [comment]
Och, looks like we have the same issue in our CI https://github.com/scalameta/metals/actions/runs/11612067598/job/32334742253?pr=6899

**Comment by eed3si9n** [comment]
So I guess this is relayed to musl static linking.

**Comment by Friendseeker** [comment]
> So I guess this is relayed to musl static linking.

Guess the issue is that ipcsocket is not linked against musl?

We need to improve our CI coverage around native build.

**Comment by Friendseeker** [comment]
I installed WSL2 Ubuntu 24 LTS for dogfooding and the stack trace here is more detailed.

The initial aim of static linking, as mentioned in https://github.com/sbt/sbt/issues/7785#issue-2599982717, is to make the build process more robust. But currently it looks like it actually make the build more fragile with problems here and there (unwanted interaction with JNI dependency & arm64 architecture).

While we can [fix the problems in the stacktrace](https://www.blog.akhil.cc/static-jni), I wonder if we should abandon our static linking effort as it seems that we are deviating away from our initial aim.

```
jerrytan@DESKTOP-6SUJJE2:~/sbt$ sbtn
Oct 31, 2024 1:16:05 PM org.jline.nativ.JLineNativeLoader log
WARNING: Failed to load native library:jlinenative-3.27.1-c3919511fa16b570-libjlinenative.so. osinfo: Linux/x86_64 (caused by: java.lang.UnsatisfiedLinkError: Can't load library: /tmp/jlinenative-3.27.1-c3919511fa16b570-libjlinenative.so, enable debug logging for stacktrace)
[info] entering *experimental* thin client - BEEP WHIRR
[info] server was not detected. starting an instance
Exception in thread "client-read-thread" java.lang.UnsatisfiedLinkError: Can't load library: /run/user/1000/.sbt1560092452/ipcsocket/libsbtipcsocket8480260381110590324.so
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibraries.loadLibraryAbsolute(NativeLibraries.java:105)
        at java.base@23.0.1/java.lang.ClassLoader.loadLibrary(ClassLoader.java:116)
        at java.base@23.0.1/java.lang.Runtime.load0(Runtime.java:852)
        at java.base@23.0.1/java.lang.System.load(System.java:2028)
        at org.scalasbt.ipcsocket.NativeLoader.load(NativeLoader.java:106)
        at org.scalasbt.ipcsocket.JNIUnixDomainSocketLibraryProvider.<clinit>(JNIUnixDomainSocketLibraryProvider.java:78)
        at org.scalasbt.ipcsocket.UnixDomainSocketLibraryProvider.get(UnixDomainSocketLibraryProvider.java:26)
        at org.scalasbt.ipcsocket.UnixDomainSocket.<init>(UnixDomainSocket.java:50)
        at sbt.protocol.ClientSocket$.localSocket(ClientSocket.scala:47)
        at sbt.internal.client.NetworkClient$$anon$3.$anonfun$run$1(NetworkClient.scala:405)
        at scala.util.Try$.apply(Try.scala:213)
        at sbt.internal.client.NetworkClient$$anon$3.run(NetworkClient.scala:405)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:832)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:808)
copying runtime jar...
...
[info] Welcome to the build for sbt.
[info] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[info]   Java version is 11. We recommend java 8.
[info] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
java.lang.NoClassDefFoundError: Could not initialize class org.scalasbt.ipcsocket.JNIUnixDomainSocketLibraryProvider
        at org.scalasbt.ipcsocket.UnixDomainSocketLibraryProvider.get(UnixDomainSocketLibraryProvider.java:26)
        at org.scalasbt.ipcsocket.UnixDomainSocket.<init>(UnixDomainSocket.java:50)
        at sbt.protocol.ClientSocket$.localSocket(ClientSocket.scala:47)
        at sbt.protocol.ClientSocket$.socket(ClientSocket.scala:39)
        at sbt.internal.client.NetworkClient.mkSocket(NetworkClient.scala:145)
        at sbt.internal.client.NetworkClient.connect$1(NetworkClient.scala:194)
        at sbt.internal.client.NetworkClient.connectOrStartServerAndConnect(NetworkClient.scala:214)
        at sbt.internal.client.NetworkClient.init(NetworkClient.scala:224)
        at sbt.internal.client.NetworkClient.connect(NetworkClient.scala:762)
        at sbt.internal.client.NetworkClient$.clientImpl(NetworkClient.scala:1188)
        at sbt.internal.client.NetworkClient$.client(NetworkClient.scala:1179)
        at sbt.internal.client.NetworkClient$.$anonfun$main$4(NetworkClient.scala:1242)
        at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withIn(Console.scala:230)
        at sbt.internal.util.Terminal$.withIn(Terminal.scala:610)
        at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:390)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withOut(Console.scala:167)
        at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:600)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withErr(Console.scala:196)
        at sbt.internal.util.Terminal$.withOut(Terminal.scala:600)
        at sbt.internal.util.Terminal$.withStreams(Terminal.scala:390)
        at sbt.internal.client.NetworkClient$.main(NetworkClient.scala:1240)
        at sbt.internal.client.NetworkClient.main(NetworkClient.scala)
        at sbt.client.Client.main(Client.java:20)
        at java.base@23.0.1/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
```

**Comment by eed3si9n** [comment]
> While we can [fix the problems in the stacktrace](https://www.blog.akhil.cc/static-jni), I wonder if we should abandon our static linking effort as it seems that we are deviating away from our initial aim.

Created an issue on this - https://github.com/sbt/sbt/issues/7856

**Comment by Friendseeker** [comment]
> > While we can [fix the problems in the stacktrace](https://www.blog.akhil.cc/static-jni), I wonder if we should abandon our static linking effort as it seems that we are deviating away from our initial aim.
> 
> 
> 
> Created an issue on this - https://github.com/sbt/sbt/issues/7856

Shall we close #7851 and continue the discussion in #7856?
