### ISSUE TITLE
[2.x] NoSuchFileException during syncBlobs

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#7857]
## steps

sbt-buildinfo/task scripted test for sbt-buildinfo.

## problem

https://github.com/sbt/sbt-buildinfo/actions/runs/11647889149/job/32433762172

```scala
[info] [error] java.nio.file.NoSuchFileException: /tmp/sbt_24e1ed74/target/out/jvm/scala-2.12.12/projoutoftaskgraph1/zinc/inc_compile_2.12.zip
[info] [error] 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
[info] [error] 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
[info] [error] 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
[info] [error] 	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
[info] [error] 	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
[info] [error] 	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
[info] [error] 	at java.nio.file.Files.readAttributes(Files.java:1737)
[info] [error] 	at java.nio.file.Files.size(Files.java:2332)
[info] [error] 	at sbt.internal.inc.MappedVirtualFile.sizeBytes(MappedVirtualFile.scala:25)
[info] [error] 	at sbt.util.Digest$package$Digest$.apply(Digest.scala:41)
[info] [error] 	at sbt.util.DiskActionCacheStore.syncBlobs$$anonfun$2(ActionCacheStore.scala:258)
[info] [error] 	at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:118)
[info] [error] 	at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:105)
[info] [error] 	at scala.collection.immutable.Vector.flatMap(Vector.scala:115)
[info] [error] 	at sbt.util.DiskActionCacheStore.syncBlobs(ActionCacheStore.scala:262)
[info] [error] 	at sbt.util.AggregateActionCacheStore.$anonfun$2(ActionCacheStore.scala:109)
[info] [error] 	at sbt.util.AggregateActionCacheStore.syncBlobs$$anonfun$1(ActionCacheStore.scala:85)
[info] [error] 	at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:183)
[info] [error] 	at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:179)
[info] [error] 	at scala.collection.immutable.List.foldLeft(List.scala:79)
[info] [error] 	at sbt.util.AggregateActionCacheStore.syncBlobs(ActionCacheStore.scala:85)
[info] [error] 	at sbt.util.ActionCache$.organicTask$1(ActionCache.scala:72)
[info] [error] 	at sbt.util.ActionCache$.cache(ActionCache.scala:78)
[info] [error] 	at sbt.Defaults$.$init$$$anonfun$1(Defaults.scala:2525)
[info] [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:79)
[info] [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:79)
[info] [error] 	at sbt.std.Transform$$anon$5.work(Transform.scala:79)
[info] [error] 	at sbt.std.Transform$$anon$5.work(Transform.scala:79)
[info] [error] 	at sbt.Execute.submit$$anonfun$1$$anonfun$1(Execute.scala:284)
[info] [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[info] [error] 	at sbt.Execute.work(Execute.scala:295)
[info] [error] 	at sbt.Execute.submit$$anonfun$1(Execute.scala:284)
[info] [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$2(ConcurrentRestrictions.scala:277)
[info] [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:75)
[info] [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:73)
[info] [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:[266](https://github.com/sbt/sbt-buildinfo/actions/runs/11647889149/job/32433762172#step:5:267))
[info] [error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info] [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info] [error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info] [error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info] [error] 	at java.lang.Thread.run(Thread.java:750)
[info] [error] (projOutOfTaskGraph1 / Compile / compileIncremental) java.nio.file.NoSuchFileException:
```

## expectation

https://github.com/sbt/sbt/blob/8c8cc430a8365ec0620ddad7fa64a008cf81f773/util-cache/src/main/scala/sbt/util/ActionCache.scala#L72

Looks like the file has disappeared while trying to cache? If the actual task was successful it's possible that we don't need to throw?

**Comment by mrdziuban** [comment]
I'm seeing a similar error during scripted tests on sbt 2.0.0-M4, no mention of `syncBlobs` though:

```scala
[info] [error] java.nio.file.NoSuchFileException: /tmp/sbt_e707c4e3/target/out/jvm/scala-3.7.1/root/root_3-0.1.0-SNAPSHOT-tests.jar
[info] [error] 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
[info] [error] 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
[info] [error] 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[info] [error] 	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
[info] [error] 	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
[info] [error] 	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
[info] [error] 	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
[info] [error] 	at java.base/java.nio.file.Files.size(Files.java:2468)
[info] [error] 	at sbt.internal.inc.MappedVirtualFile.sizeBytes(MappedVirtualFile.scala:25)
[info] [error] 	at sbt.internal.util.codec.HashedVirtualFileRefFormats.hashedVirtualFileRefToStr(HashedVirtualFileRefFormats.scala:15)
[info] [error] 	at sbt.internal.util.codec.HashedVirtualFileRefFormats.hashedVirtualFileRefToStr$(HashedVirtualFileRefFormats.scala:9)
[info] [error] 	at sbt.internal.util.codec.ActionResultCodec$.hashedVirtualFileRefToStr(ActionResultCodec.scala:11)
[info] [error] 	at sbt.internal.util.codec.HashedVirtualFileRefFormats.hashedVirtualFileRefIsoString$$anonfun$1(HashedVirtualFileRefFormats.scala:28)
[info] [error] 	at sjsonnew.IsoString$$anon$1.to(IsoString.scala:26)
[info] [error] 	at sjsonnew.IsoFormats$$anon$2.write(IsoFormats.scala:31)
[info] [error] 	at sjsonnew.CollectionFormats$$anon$2.write$$anonfun$2(CollectionFormats.scala:85)
[info] [error] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[info] [error] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[info] [error] 	at scala.collection.immutable.Vector.foreach(Vector.scala:2125)
[info] [error] 	at sjsonnew.CollectionFormats$$anon$2.write(CollectionFormats.scala:85)
[info] [error] 	at sjsonnew.CollectionFormats$$anon$2.write(CollectionFormats.scala:82)
[info] [error] 	at sjsonnew.JsonWriter.addField(JsonFormat.scala:40)
[info] [error] 	at sjsonnew.JsonWriter.addField$(JsonFormat.scala:35)
[info] [error] 	at sjsonnew.CollectionFormats$$anon$2.addField(CollectionFormats.scala:80)
[info] [error] 	at sjsonnew.Builder.addField(Builder.scala:43)
[info] [error] 	at sbt.internal.util.codec.ActionResultFormats$$anon$1.write(ActionResultFormats.scala:27)
[info] [error] 	at sbt.internal.util.codec.ActionResultFormats$$anon$1.write(ActionResultFormats.scala:25)
[info] [error] 	at sjsonnew.SupportConverter.toJsonUnsafe(SupportConverter.scala:23)
[info] [error] 	at sjsonnew.SupportConverter.toJsonUnsafe$(SupportConverter.scala:5)
[info] [error] 	at sjsonnew.support.scalajson.unsafe.Converter$.toJsonUnsafe(Converter.scala:7)
[info] [error] 	at sbt.util.DiskActionCacheStore.put(ActionCacheStore.scala:211)
[info] [error] 	at sbt.util.AggregateActionCacheStore.put$$anonfun$1(ActionCacheStore.scala:99)
[info] [error] 	at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:183)
[info] [error] 	at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:179)
[info] [error] 	at scala.collection.immutable.List.foldLeft(List.scala:79)
[info] [error] 	at sbt.util.AggregateActionCacheStore.put(ActionCacheStore.scala:97)
[info] [error] 	at sbt.util.ActionCache$.organicTask$1(ActionCache.scala:70)
[info] [error] 	at sbt.util.ActionCache$.cache(ActionCache.scala:78)
[info] [error] 	at sbt.Defaults$.packageTask$lzyINIT1$$anonfun$1(Defaults.scala:1802)
[info] [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:79)
[info] [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:79)
[info] [error] 	at sbt.std.Transform$$anon$3.work(Transform.scala:79)
[info] [error] 	at sbt.std.Transform$$anon$3.work(Transform.scala:79)
[info] [error] 	at sbt.Execute.submit$$anonfun$1$$anonfun$1(Execute.scala:284)
[info] [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[info] [error] 	at sbt.Execute.work(Execute.scala:295)
[info] [error] 	at sbt.Execute.submit$$anonfun$1(Execute.scala:284)
[info] [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$2(ConcurrentRestrictions.scala:275)
[info] [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:75)
[info] [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:73)
[info] [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[info] [error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[info] [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[info] [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[info] [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[info] [error] 	at java.base/java.lang.Thread.run(Thread.java:840)
[info] [error] (Test / packageBin) java.nio.file.NoSuchFileException: /tmp/sbt_e707c4e3/target/out/jvm/scala-3.7.1/root/root_3-0.1.0-SNAPSHOT-tests.jar
```
