### ISSUE TITLE
[2.x] ConcurrentModificationException in SbtParser

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt#7873]
## steps

sbt 2.0.0-M2

flaky some sbt plugin scripted test

## problem

https://github.com/wartremover/wartremover-contrib/actions/runs/11697441192/job/32576176336#step:5:812

```
Error:  Exception in thread "sbt-parser-init-thread" java.lang.ExceptionInInitializerError
Error:  	at sbt.internal.parser.SbtParserInit$$anon$1.run(SbtParser.scala:179)
Error:  Caused by: java.util.ConcurrentModificationException
Error:  	at java.util.Hashtable$Enumerator.next(Hashtable.java:1408)
Error:  	at scala.collection.convert.JavaCollectionWrappers$JPropertiesWrapper$$anon$6.next(JavaCollectionWrappers.scala:622)
Error:  	at scala.collection.convert.JavaCollectionWrappers$JPropertiesWrapper$$anon$6.next(JavaCollectionWrappers.scala:618)
Error:  	at scala.collection.IterableOnceOps.find(IterableOnce.scala:634)
Error:  	at scala.collection.IterableOnceOps.find$(IterableOnce.scala:631)
Error:  	at scala.collection.AbstractIterator.find(Iterator.scala:1300)
Error:  	at dotty.tools.dotc.config.PathResolver$Environment$.searchForBootClasspath(PathResolver.scala:40)
Error:  	at dotty.tools.dotc.config.PathResolver$Environment$.javaBootClassPath(PathResolver.scala:49)
Error:  	at dotty.tools.dotc.config.PathResolver$Defaults$.javaBootClassPath(PathResolver.scala:75)
Error:  	at dotty.tools.dotc.config.CommonScalaSettings.$init$(ScalaSettings.scala:97)
Error:  	at dotty.tools.dotc.config.ScalaSettings.<init>(ScalaSettings.scala:15)
Error:  	at dotty.tools.dotc.core.Contexts$ContextBase.<init>(Contexts.scala:857)
Error:  	at dotty.tools.dotc.Driver.initCtx(Driver.scala:61)
Error:  	at sbt.internal.parser.SbtParser$ParseDriver.<init>(SbtParser.scala:138)
Error:  	at sbt.internal.parser.SbtParser$.<clinit>(SbtParser.scala:135)
```

## notes

Maybe not thread safe 🤔 

https://github.com/sbt/sbt/blob/v2.0.0-M2/buildfile/src/main/scala/sbt/internal/parser/SbtParser.scala#L138

**Comment by jtjeferreira** [comment]
I also faced this issue, when working on https://github.com/sbt/sbt-native-packager/pull/1647 /  https://github.com/eed3si9n/sbt-native-packager/pull/1 . Rerunning the job "fixed" it.

I no longer can find the link to the github action log...

**Comment by eed3si9n** [comment]
Here's a PR for this - https://github.com/sbt/sbt/pull/7938

**Comment by adpi2** [comment]
Fixed by #7938

Also will be fixed upstream by https://github.com/scala/scala3/pull/22180

**Comment by xuwei-k** [comment]
😢 

https://github.com/dwijnand/sbt-project-graph/actions/runs/12402208148/job/34623254878?pr=155#step:7:170

https://github.com/dwijnand/sbt-project-graph/pull/155/commits/5003ae6f4d283dd0e9a723f707995ba8ae5a35e0

<img width="1057" alt="img" src="https://github.com/user-attachments/assets/c75a5f09-399c-4f39-845f-e6fca7ad5c6c" />

**Comment by jtjeferreira** [comment]
> Also will be fixed upstream by [scala/scala3#22180](https://github.com/scala/scala3/pull/22180)

There was no reply in that PR from the scala team. Can someone pull some strings?

**Comment by jtjeferreira** [comment]
We still need to upgrade scala to a version that includes the fix scala/scala3#22180, or properly implement the retry

**Comment by dwickern** [comment]
We see this frequently in sbt-native-packager CI. Here are a couple of failing jobs:
https://github.com/sbt/sbt-native-packager/actions/runs/12622476129/job/35170459950?pr=1662#step:5:2664
https://github.com/sbt/sbt-native-packager/actions/runs/12636292339/job/35208137960?pr=1665#step:5:2664

**Comment by jtjeferreira** [comment]
> We see this frequently in sbt-native-packager CI. Here are a couple of failing jobs: [sbt/sbt-native-packager/actions/runs/12622476129/job/35170459950?pr=1662#step:5:2664](https://github.com/sbt/sbt-native-packager/actions/runs/12622476129/job/35170459950?pr=1662#step:5:2664) [sbt/sbt-native-packager/actions/runs/12636292339/job/35208137960?pr=1665#step:5:2664](https://github.com/sbt/sbt-native-packager/actions/runs/12636292339/job/35208137960?pr=1665#step:5:2664)

Yes, we to wait for a new version of sbt 2.x that includes https://github.com/sbt/io/pull/397. I think the only worakaround is to retry the specific jobs that are failing in the github actions UI

**Comment by eed3si9n** [comment]
Maybe we should release 2.0.0-M4 soon for this.

**Comment by xuwei-k** [comment]
- https://github.com/sbt/sbt/pull/8011

**Comment by mrdziuban** [comment]
@eed3si9n any chance that sbt 2.0.0-M4 will come soon? This fix plus the addition of `Def.inputTaskDyn` in #8033 should help unblock a few migrations:

- https://github.com/eed3si9n/scalaxb/pull/676
- https://github.com/scalacenter/sbt-scalafix/pull/440
- https://github.com/scalacenter/sbt-dependency-submission/pull/246

**Comment by eed3si9n** [comment]
Yea once I can land client-side run on sbt 1.x / sbtn, I'm planning to ship M4.
