### ISSUE TITLE
CancellationException thrown on compile error with usePipelining

### ISSUE THREAD

**Issue by OlegYch** [sbt/sbt#7973]
## steps

set `ThisBuild / usePipelining := true`
compile some code with errors

## problem

```
[error] four errors found
java.util.concurrent.CancellationException
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:121)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at sbt.ConcurrentRestrictions$$anon$4.take(ConcurrentRestrictions.scala:311)
        at sbt.Execute.next$1(Execute.scala:118)
        at sbt.Execute.processAll(Execute.scala:128)
        at sbt.Execute.runKeep(Execute.scala:96)
        at sbt.EvaluateTask$.liftedTree1$1(EvaluateTask.scala:520)
        at sbt.EvaluateTask$.run$1(EvaluateTask.scala:519)
        at sbt.EvaluateTask$.runTask(EvaluateTask.scala:543)
        at sbt.internal.Aggregation$.$anonfun$timedRun$4(Aggregation.scala:105)
        at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:432)
        at sbt.internal.Aggregation$.timedRun(Aggregation.scala:103)
        at sbt.internal.Aggregation$.runTasks(Aggregation.scala:117)
        at sbt.internal.Aggregation$.$anonfun$applyTasks$1(Aggregation.scala:72)
        at sbt.Command$.$anonfun$applyEffect$2(Command.scala:146)
        at sbt.internal.Aggregation$.$anonfun$evaluatingParser$11(Aggregation.scala:219)
        at sbt.internal.Act$.$anonfun$actParser0$8(Act.scala:500)
        at sbt.Command$.process(Command.scala:194)
        at sbt.MainLoop$.$anonfun$processCommand$7(MainLoop.scala:267)
        at scala.Option.getOrElse(Option.scala:189)
        at sbt.MainLoop$.process$1(MainLoop.scala:267)
        at sbt.MainLoop$.processCommand(MainLoop.scala:312)
        at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:171)
        at sbt.State$StateOpsImpl$.runCmd$1(State.scala:290)
        at sbt.State$StateOpsImpl$.process$extension(State.scala:326)
        at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:171)
        at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
        at sbt.MainLoop$.next(MainLoop.scala:171)
        at sbt.MainLoop$.run(MainLoop.scala:152)
        at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:127)
        at sbt.io.Using.apply(Using.scala:41)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:120)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:74)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:59)
        at sbt.MainLoop$.runLogged(MainLoop.scala:50)
        at sbt.StandardMain$.runManaged(Main.scala:225)
        at sbt.xMain$.$anonfun$run$11(Main.scala:136)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withIn(Console.scala:230)
        at sbt.internal.util.Terminal$.withIn(Terminal.scala:620)
        at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:400)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withOut(Console.scala:167)
        at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:610)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withErr(Console.scala:196)
        at sbt.internal.util.Terminal$.withOut(Terminal.scala:610)
        at sbt.internal.util.Terminal$.withStreams(Terminal.scala:400)
        at sbt.xMain$.withStreams$1(Main.scala:89)
        at sbt.xMain$.run(Main.scala:124)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:59)
        at sbt.xMain.run(Main.scala:48)
        at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
        at xsbt.boot.Launch$.run(Launch.scala:149)
        at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
        at xsbt.boot.Launch$.launch(Launch.scala:159)
        at xsbt.boot.Launch$.apply(Launch.scala:44)
        at xsbt.boot.Launch$.apply(Launch.scala:21)
        at xsbt.boot.Boot$.runImpl(Boot.scala:78)
        at xsbt.boot.Boot$.run(Boot.scala:73)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)


[error] java.util.concurrent.CancellationException
[error] Use 'last' for the full log.
```

## expectation

no exception thrown (or at least no stacktrace)

## notes
sbt 1.10.6

**Comment by Friendseeker** [comment]
Reproduction: https://github.com/Friendseeker/sbt-7973

**Comment by Friendseeker** [comment]
Reproducible back in `1.10.0`

So not caused by https://github.com/sbt/sbt/pull/7830

**Comment by Friendseeker** [comment]
PR that may be of interest: https://github.com/sbt/sbt/pull/5847

**Comment by OlegYch** [comment]
still an issue on 1.10.11

**Comment by OlegYch** [comment]
a workaround
```scala
val _ = System.setErr(new PrintStream(System.err){
  override def println(x: Any) = {
    x match {
      case e: java.util.concurrent.CancellationException =>
        ()
        e.setStackTrace(Array())
      case _ =>
        super.println(x)
    }
  }
})

```

**Comment by evolvomind** [comment]
Hi @eed3si9n, @OlegYch ,
I am a new contributor to this repo.
Do you think this is good first issue as a fresher?

**Comment by eed3si9n** [comment]
@evolvomind There's a bug in sbt 2.x that doesn't reproduce the same way as described here, but I think fixing this against the **1.12.x branch** would be relatively straightforward. Given the top of the stack trace:

```scala
[error] four errors found
java.util.concurrent.CancellationException
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:121)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at sbt.ConcurrentRestrictions$$anon$4.take(ConcurrentRestrictions.scala:311)
```

you can wrap line 311 https://github.com/sbt/sbt/blob/08ab372fa6cdc05c986b9ca807802a65d2ae5941/tasks/src/main/scala/sbt/ConcurrentRestrictions.scala#L311

with try-catch, specifically catching CancellationException, and rethrow MessageOnlyException instead.

https://github.com/sbt/sbt/blob/08ab372fa6cdc05c986b9ca807802a65d2ae5941/internal/util-control/src/main/scala/sbt/internal/util/MessageOnlyException.scala#L11.

You can follow the instruction here (https://github.com/sbt/sbt/blob/develop/contributing-docs/06_manual_tests.md) to manually test your fix.

**Comment by evolvomind** [comment]
Thanks for your reply, @eed3si9n 

So I'd like to select the issue for the first time, and could you help me to select the good issues as a fresher if you don't mind?

**Comment by eed3si9n** [comment]
Not sure if I follow. I think this is a good first issue.

**Comment by evolvomind** [comment]
@eed3si9n 

Okay, got it.
I will work on this.
So should I reproduce this bug on 1.12.x or on 2.x?

**Comment by eed3si9n** [comment]
I suggest working with a branch off of 1.12.x branch, and sending a PR there first.

**Comment by evolvomind** [comment]
@eed3si9n , I tried to reproduce this bug, but can't.

Here is some error logs
```
[info] welcome to sbt 1.12.0 (Ubuntu Java 21.0.9)
[info] loading project definition from /work/82/projects/sbt-7973/project
[info] loading settings for project sbt-7973 from build.sbt...
[info] set current project to sbt-7973 (in build file:/work/82/projects/sbt-7973/)
[info] Executing in batch mode. For better performance use sbt's shell
[info] compiling 1 Scala source to /work/82/projects/sbt-7973/B/target/scala-3.3.4/classes ...
[warn] bad option '-Ypickle-java' was ignored
[warn] bad option '-Ypickle-write' was ignored
[error] -- [E007] Type Mismatch Error: /work/82/projects/sbt-7973/B/src/main/scala/main.scala:3:15 
[error] 3 |  val x: Int = "hello"   // keep this
[error]   |               ^^^^^^^
[error]   |               Found:    ("hello" : String)
[error]   |               Required: Int
[error]   |
[error]   | longer explanation available when compiling with `-explain`
[error] -- [E007] Type Mismatch Error: /work/82/projects/sbt-7973/B/src/main/scala/main.scala:4:18 
[error] 4 |  val y: String = 42     // add another type mismatch
[error]   |                  ^^
[error]   |                  Found:    (42 : Int)
[error]   |                  Required: String
[error]   |
[error]   | longer explanation available when compiling with `-explain`
[error] -- [E006] Not Found Error: /work/82/projects/sbt-7973/B/src/main/scala/main.scala:5:10 
[error] 5 |  val z = undeclared     // add not-found
[error]   |          ^^^^^^^^^^
[error]   |          Not found: undeclared
[error]   |
[error]   | longer explanation available when compiling with `-explain`
[warn] two warnings found
[error] three errors found
[error] (B / Compile / compileIncremental) Compilation failed
[error] Total time: 3 s, completed Jan 23, 2026, 9:54:40 AM
```

Couldn't find any log tip `CancellationException` in it.

As you suggested, I am working against `1.12.x` branch.

**Comment by eed3si9n** [comment]
@evolvomind Try breaking subproject A first, I think.

**Comment by evolvomind** [comment]
@eed3si9n , @Richman018

So this issue is solved?

**Comment by eed3si9n** [comment]
There's an open PR https://github.com/sbt/sbt/pull/8637, but it hasn't landed yet.

**Comment by it-education-md** [comment]
@eed3si9n can I take charge of this issue?

**Comment by eed3si9n** [comment]
@it-education-md Sure thing!

**Comment by Eruis2579** [comment]
Hi, @eed3si9n can I try this issue?

**Comment by eed3si9n** [comment]
Sure as per usual, contributions are welcome on accepted issues. Please check out our [Contributor's Guildeline](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) and:
1. Make sure you can reproduce the problem and the fix manually
2. Include tests for the change
3. Follow our AI assisted contributions guideline (disclose AI usages in the PR description, if any)
4. Multiple people may work on a PR in parallel, and maintainers may merge whichever one (we prefer concise impl)
