### ISSUE TITLE
[2.x] compile on AppVeyor causes java.io.FileNotFoundException: C:\temp\....\inc_compile_3.zip (Access is denied)

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#7976]
## steps

scripted test `windows/absolute-path-in-bat` for sbt-native-packager on AppVeyor.

## problem

https://ci.appveyor.com/project/muuki88/sbt-native-packager/builds/51230330

```scala
[info] [info] Wrote C:\temp\sbt_89e589ea\target\out\jvm\scala-3.6.2\absolute-path-in-bat\absolute-path-in-bat_3-0.1.0.pom
[info] [info] compiling 1 Scala source to C:\temp\sbt_89e589ea\target\out\jvm\scala-3.6.2\absolute-path-in-bat\backend ...
[info] [info] done compiling
[info] [error] java.io.FileNotFoundException: C:\temp\sbt_89e589ea\target\out\jvm\scala-3.6.2\absolute-path-in-bat\zinc\inc_compile_3.zip (Access is denied)
[info] [error] 	at java.io.FileOutputStream.open0(Native Method)
[info] [error] 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
[info] [error] 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[info] [error] 	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
[info] [error] 	at sbt.io.Using$.$init$$$anonfun$5(Using.scala:118)
[info] [error] 	at sbt.io.Using$$anon$3.openImpl(Using.scala:100)
[info] [error] 	at sbt.io.OpenFile.open(Using.scala:67)
[info] [error] 	at sbt.io.OpenFile.open$(Using.scala:59)
[info] [error] 	at sbt.io.Using$$anon$3.open(Using.scala:99)
[info] [error] 	at sbt.io.Using$$anon$3.open(Using.scala:99)
[info] [error] 	at sbt.io.Using.apply(Using.scala:39)
[info] [error] 	at sbt.io.IO$.copyFile$$anonfun$3(IO.scala:910)
[info] [error] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[info] [error] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[info] [error] 	at sbt.io.Using.apply(Using.scala:41)
[info] [error] 	at sbt.io.IO$.copyFile(IO.scala:909)
[info] [error] 	at sbt.io.IO$.move(IO.scala:1127)
[info] [error] 	at sbt.internal.inc.consistent.ConsistentFileAnalysisStore$AStore.set(ConsistentFileAnalysisStore.scala:97)
[info] [error] 	at xsbti.compile.AnalysisStore$CachedAnalysisStore.set(AnalysisStore.java:126)
[info] [error] 	at xsbti.compile.AnalysisStore$SyncedAnalysisStore.set(AnalysisStore.java:150)
[info] [error] 	at sbt.Defaults$.compileTask$$anonfun$1(Defaults.scala:2282)
[info] [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:79)
[info] [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:79)
[info] [error] 	at sbt.std.Transform$$anon$3.work(Transform.scala:79)
[info] [error] 	at sbt.std.Transform$$anon$3.work(Transform.scala:79)
[info] [error] 	at sbt.Execute.submit$$anonfun$1$$anonfun$1(Execute.scala:284)
[info] [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[info] [error] 	at sbt.Execute.work(Execute.scala:295)
[info] [error] 	at sbt.Execute.submit$$anonfun$1(Execute.scala:284)
[info] [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$2(ConcurrentRestrictions.scala:275)
[info] [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:75)
[info] [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:73)
[info] [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info] [error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info] [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info] [error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info] [error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info] [error] 	at java.lang.Thread.run(Thread.java:750)
[info] [error] (Compile / compile) java.io.FileNotFoundException: C:\temp\sbt_89e589ea\target\out\jvm\scala-3.6.2\absolute-path-in-bat\zinc\inc_compile_3.zip (Access is denied)
```

## expectation

compile works.

## note

https://github.com/sbt/zinc/blob/5b553288e611252808e808a305d01a8fbdb75f7a/internal/zinc-persist/src/main/scala/sbt/internal/inc/consistent/ConsistentFileAnalysisStore.scala#L97

**Comment by eed3si9n** [comment]
Related

```scala
[info] [info] welcome to sbt 2.0.0-M3 (Azul Systems, Inc. Java 11.0.25)
[error] java.nio.file.AccessDeniedException: C:\temp\sbt_b628e199\project\project\target\config-classes
[error] 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
[error] 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[error] 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[error] 	at java.base/sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:509)
[error] 	at java.base/java.nio.file.Files.createDirectory(Files.java:690)
[error] 	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:797)
[error] 	at java.base/java.nio.file.Files.createDirectories(Files.java:783)
[error] 	at sbt.internal.Eval.$init$$$anonfun$1(Eval.scala:38)
[error] 	at scala.Option.foreach(Option.scala:437)
[error] 	at sbt.internal.Eval.<init>(Eval.scala:37)
[error] 	at sbt.internal.Load$.mkEval(Load.scala:503)
[error] 	at sbt.internal.Load$.eval$lzyINIT2$1$$anonfun$1(Load.scala:798)
[error] 	at sbt.internal.Load$.timed(Load.scala:1585)
```

**Comment by Dairus01** [comment]
@eed3si9n Please, I would love to work on this issue can I go ahaed,

btw I noticed that the fix would be in https://github.com/sbt/zinc repository

**Comment by eed3si9n** [comment]
@Dairus01 Please go ahead.
