### ISSUE TITLE
updateSbtClassifiers fails in 0.13.0-Beta2 sbt.ResolveException: unresolved dependency: default#bla-build;0.1-SNAPSHOT: not found

### ISSUE THREAD

**Issue by OlegYch** [sbt/sbt#798]
With an empty project (only build.properties) and latest launcher i get this:

```
sbt.ResolveException: unresolved dependency: default#bla-build;0.1-SNAPSHOT: not found
        at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:213)
        at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:122)
        at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:121)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:116)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:116)
        at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:104)
        at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:51)
        at sbt.IvySbt$$anon$3.call(Ivy.scala:60)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:98)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:81)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:102)
        at xsbt.boot.Using$.withResource(Using.scala:11)
        at xsbt.boot.Using$.apply(Using.scala:10)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:62)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:52)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at sbt.IvySbt.withDefaultLogger(Ivy.scala:60)
        at sbt.IvySbt.withIvy(Ivy.scala:101)
        at sbt.IvySbt.withIvy(Ivy.scala:97)
        at sbt.IvySbt$Module.withModule(Ivy.scala:116)
        at sbt.IvyActions$.update(IvyActions.scala:121)
        at sbt.IvyActions$.transitiveScratch(IvyActions.scala:166)
        at sbt.Classpaths$$anonfun$sbtClassifiersTasks$5$$anonfun$apply$55.apply(Defaults.scala:1072)
        at sbt.Classpaths$$anonfun$sbtClassifiersTasks$5$$anonfun$apply$55.apply(Defaults.scala:1070)
        at sbt.Classpaths$$anon$2.call(Defaults.scala:1093)
        at sbt.Classpaths$$anon$2.call(Defaults.scala:1091)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:98)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:81)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:102)
        at xsbt.boot.Using$.withResource(Using.scala:11)
        at xsbt.boot.Using$.apply(Using.scala:10)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:62)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:52)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at sbt.Classpaths$.withExcludes(Defaults.scala:1091)
        at sbt.Classpaths$$anonfun$sbtClassifiersTasks$5.apply(Defaults.scala:1070)
        at sbt.Classpaths$$anonfun$sbtClassifiersTasks$5.apply(Defaults.scala:1068)
        at scala.Function6$$anonfun$tupled$1.apply(Function6.scala:35)
        at scala.Function6$$anonfun$tupled$1.apply(Function6.scala:34)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
        at sbt.std.Transform$$anon$4.work(System.scala:64)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
        at sbt.Execute.work(Execute.scala:234)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:166)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:166)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:722)
[error] (*:updateSbtClassifiers) sbt.ResolveException: unresolved dependency: default#bla-build;0.1-SNAPSHOT: not found
[error] Total time: 2 s, completed Jun 26, 2013 6:21:14 PM
```

full log at https://gist.github.com/OlegYch/5868439

**Comment by harrah** [comment]
Thanks for the test case, should be fixed now.

**Comment by OlegYch** [comment]
Thanks Mark.
