### ISSUE TITLE
1.8 support for sbt

### ISSUE THREAD

**Issue by wsargent** [sbt/sbt#842]
SBT does not currently support Java 1.8, as the bytecode format is different.  Currently with 0.13, if you use a 1.8 compiler and use lambdas, you'll run into unknown constants.

```
java.lang.RuntimeException: Unknown constant: 18
at scala.sys.package$.error(package.scala:27)
at sbt.classfile.Parser$.getConstant(Parser.scala:150)
at sbt.classfile.Parser$.parse$1(Parser.scala:127)
at sbt.classfile.Parser$.sbt$classfile$Parser$$parseConstantPool(Parser.scala:132)
at sbt.classfile.Parser$$anon$1.<init>(Parser.scala:32)
at sbt.classfile.Parser$.parseImpl(Parser.scala:24)
at sbt.classfile.Parser$.sbt$classfile$Parser$$parse(Parser.scala:20)
at sbt.classfile.Parser$$anonfun$apply$1.apply(Parser.scala:19)
at sbt.classfile.Parser$$anonfun$apply$1.apply(Parser.scala:19)
at sbt.Using.apply(Using.scala:25)
at sbt.classfile.Parser$.apply(Parser.scala:19)
at sbt.classfile.Analyze$$anonfun$apply$2.apply(Analyze.scala:32)
at sbt.classfile.Analyze$$anonfun$apply$2.apply(Analyze.scala:31)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
```

**Comment by harrah** [comment]
Problem of using newer jdk version with an older jdk running sbt (via forking) moved to #887.
