### ISSUE TITLE
NoSuchElementException with test option from non-loaded test framework 

### ISSUE THREAD

**Issue by retronym** [sbt/sbt#87]
I was picking up this from a standard build:

  `(testOptions in Test) += Tests.Argument(TestFrameworks.Specs2, "console", "junitxml")`

But my build uses Specs1. When trying to apply this option, the following exception is raised.

```
> last execute-tests
java.util.NoSuchElementException: key not found: sbt.TestFramework@12c0689
        at scala.collection.MapLike$class.default(MapLike.scala:223)
        at scala.collection.immutable.Map$Map3.default(Map.scala:132)
        at scala.collection.MapLike$class.apply(MapLike.scala:134)
        at scala.collection.immutable.Map$Map3.apply(Map.scala:132)
        at sbt.Tests$$anonfun$apply$2.apply(Tests.scala:72)
        at sbt.Tests$$anonfun$apply$2.apply(Tests.scala:54)
        at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.
scala:61)
        at scala.collection.immutable.List.foreach(List.scala:45)
        at sbt.Tests$.apply(Tests.scala:54)
        at sbt.Defaults$$anonfun$testTasks$4.apply(Defaults.scala:236)
        at sbt.Defaults$$anonfun$testTasks$4.apply(Defaults.scala:236)
        at sbt.Scoped$$anonfun$hf6$1.apply(Structure.scala:511)
        at sbt.Scoped$$anonfun$hf6$1.apply(Structure.scala:511)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:44)
        at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$9.apply(Structur
e.scala:305)
        at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$9.apply(Structur
e.scala:305)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:39)
        at sbt.std.Transform$$anon$5.work(System.scala:66)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:22
0)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:22
0)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:13)
        at sbt.Execute.work(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:220)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:220)
        at sbt.CompletionService$$anon$1$$anon$2.call(CompletionService.scala:26
)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
        at java.util.concurrent.FutureTask.run(FutureTask.java:138)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:44
1)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
        at java.util.concurrent.FutureTask.run(FutureTask.java:138)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExec
utor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:908)
        at java.lang.Thread.run(Thread.java:619)
[error]   {file:/E:/code/analytics/}analytics-utils/test:execute-tests: java.uti
l.NoSuchElementException: key not found: sbt.TestFramework@12c0689
```

**Comment by harrah** [comment]
Is the problem that there should be a simple error message or warning stating that you are trying to set arguments for non-existing framework instead of a not helpful stack trace?

**Comment by retronym** [comment]
Yes, it's a usability problem. A warning would suffice.
