### ISSUE TITLE
sbt 0.13.0 doesn't start, "Found class jline.Terminal, but interface was expected"

### ISSUE THREAD

**Issue by vn971** [sbt/sbt#968]
I had a project that worked pretty well with "sbt.version=0.12.4". I changed the version to "sbt.version=0.13.0". After downloading the SBT and ivy stuff, the sbt went dead, exited with an error.
Repeates restarts give the error almost instantly.

```
    [SUCCESSFUL ] org.scala-sbt#apply-macro;0.13.0!apply-macro.jar (1240ms)
:: retrieving :: org.scala-sbt#boot-app
    confs: [default]
    43 artifacts copied, 0 already retrieved (12440kB/212ms)
[ERROR] Terminal initialization failed; falling back to unsupported
java.lang.IncompatibleClassChangeError: Found class jline.Terminal, but interface was expected
    at jline.TerminalFactory.create(TerminalFactory.java:101)
    at jline.TerminalFactory.get(TerminalFactory.java:159)
    at sbt.ConsoleLogger$.ansiSupported(ConsoleLogger.scala:85)
    at sbt.ConsoleLogger$.<init>(ConsoleLogger.scala:79)
    at sbt.ConsoleLogger$.<clinit>(ConsoleLogger.scala)
    at sbt.GlobalLogging$.initial(GlobalLogging.scala:40)
    at sbt.StandardMain$.initialGlobalLogging(Main.scala:54)
    at sbt.StandardMain$.initialState(Main.scala:60)
    at sbt.xMain.run(Main.scala:26)
    at xsbt.boot.Launch$.run(Launch.scala:55)
    at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
    at xsbt.boot.Launch$.launch(Launch.scala:69)
    at xsbt.boot.Launch$.apply(Launch.scala:16)
    at xsbt.boot.Boot$.runImpl(Boot.scala:31)
    at xsbt.boot.Boot$.main(Boot.scala:20)
    at xsbt.boot.Boot.main(Boot.scala)

java.lang.IncompatibleClassChangeError: JLine incompatibility detected.  Check that the sbt launcher is version 0.13.x or later.
    at sbt.ConsoleLogger$.ansiSupported(ConsoleLogger.scala:96)
    at sbt.ConsoleLogger$.<init>(ConsoleLogger.scala:79)
    at sbt.ConsoleLogger$.<clinit>(ConsoleLogger.scala)
    at sbt.GlobalLogging$.initial(GlobalLogging.scala:40)
    at sbt.StandardMain$.initialGlobalLogging(Main.scala:54)
    at sbt.StandardMain$.initialState(Main.scala:60)
    at sbt.xMain.run(Main.scala:26)
    at xsbt.boot.Launch$.run(Launch.scala:55)
    at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
    at xsbt.boot.Launch$.launch(Launch.scala:69)
    at xsbt.boot.Launch$.apply(Launch.scala:16)
    at xsbt.boot.Boot$.runImpl(Boot.scala:31)
    at xsbt.boot.Boot$.main(Boot.scala:20)
    at xsbt.boot.Boot.main(Boot.scala)
Error during sbt execution: java.lang.IncompatibleClassChangeError: JLine incompatibility detected.  Check that the sbt launcher is version 0.13.x or later.
```

I launch SBT through `sbt`,
it's installed system-wide, the inner version is "sbt-launch-0.11.jar". But I explicetely stated that I want "0.13.0" in my project/build.properties. And the "0.13.0" version _was_ dowloaded.

**Comment by vn971** [comment]
Closed: seems like a well-known issue without fixes.

**Comment by dcsobral** [comment]
I wish you had not closed it without more information, for I have the same problem.

**Comment by harrah** [comment]
The error message indicates that a 0.13 launcher is required.  If you are using a 0.13 launcher and you are seeing the error, this is not a well-known problem.

**Comment by vn971** [comment]
@dcsobral in another words, you should upgrade the _launcher_ (executables+jar) to be able to use 0.13.0.

**Comment by jsuereth** [comment]
We haven't quite worked out a way to automatically upgrade the launcher.  It's possible the Activator team may figure out a mechanism, and pull requests are welcome in this area.  However, right now you should always be using the latest launcher with previous sbt.
